### ISSUE TITLE
automatic flag of the posts that receive X counts of downvotes

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10029]
To detect and act on all problems between users quickly (or improper posts in the forum), it would be great to get a flag notification as admins or modes if a post receives X counts of downvotes in a determined amount of time. I believe this would be useful for others as well. 

For example, it would be nice for us to immediately detect the posts that got more than 20 downvotes in the first 24 hours that it has been posted. Although people downvote inappropriate posts, they do not usually report or flag all these posts to us. I guess they assume that we will see them, but unfortunately, it takes time for us to see these posts. 

Thanks.

**Comment by julianlam** [comment]
Hmm.. but who would be the actual reporter of the flag? You'd have twenty different people downvoting a post, but nobody is stepping up to flag :smile:

**Comment by AliCihan** [comment]
Yes, we have other measures such as two-way block ( thanks to @oplik0 ) , so rather than dealing with trolls, people choose to ignore them. However, as moderators/admins, we would like to be aware of what is going on in the forum. And some days, we get thousands of posts, so it is becoming harder and harder to read all posts in the forum. 

However, what I have described would solve this problem, since we will be able to reach "problematic posts" immediately after we log in. 

So, it does not really matter to us who the reporter is. we want to be in a situation where the forum automatically flags these posts for us to review, rather than relying on other users to flag them first.

**Comment by julianlam** [comment]
Okay, I will think on it. Maybe a system user. 👍

Thank you for the suggestion

**Comment by AliCihan** [comment]
thanks a lot @gasoved 🙏
