### ISSUE TITLE
Paginator scroll events bubble up to window

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10032]
When scrolling in this widget, the window scrolls as well

![image](https://user-images.githubusercontent.com/923011/143304276-7f5f3ac6-0848-4ab5-8bcd-95f98a691923.png)

Needs [`overscroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior)

**Comment by barisusakli** [comment]
Actually that windows doesn't have any scroll events, scrolling just scrolls the window and this window updates as you go to new posts.
