### ISSUE TITLE
No response when navigating to admins-mods page

### ISSUE THREAD

**Issue by jaromanda** [NodeBB/NodeBB#10048]
When navigating to `/admin/manage/admins-mods`, there's no response for 5 minutes, then a generic "you have internet issues" page is shown - clearly I don't have internet issues as I can navigate the whole forum and admin in another tab/browser while waiting for this page to load

- **NodeBB version:** 1.18.6
- **NodeBB git hash:** 22e74dc0bb9cf296f548ad3b67ba1d297e4a7dc1
- **NodeJS version:** 16.13.0
- **Installed NodeBB Plugins:**         * nodebb-plugin-composer-default@7.0.14 (installed, enabled)
        * nodebb-plugin-custom-pages@1.3.1 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.0 (installed, enabled)
        * nodebb-plugin-emoji@3.5.4 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
        * nodebb-plugin-markdown@8.14.4 (installed, enabled)
        * nodebb-plugin-mentions@3.0.2 (installed, enabled)
        * nodebb-plugin-ns-embed@5.0.0 (installed, enabled)
        * nodebb-plugin-ns-spoiler@8.0.0 (installed, enabled)
        * nodebb-plugin-youtube-embed@0.6.9 (installed, enabled)
        * nodebb-rewards-essentials@0.2.0 (installed, enabled)
        * nodebb-theme-persona@11.2.21 (installed, enabled)
        * nodebb-widget-board-stats@1.2.3 (installed, enabled)
        * nodebb-widget-essentials@5.0.4 (installed, enabled)

Note: Even after disabling most of the above, same results

- **Database type:** mongo
- **Database version:** db version v4.2.17
- **Exact steps to cause this issue:**
	1. Go to Admin
	2. Select Manage
	3. Select Admins & Mods
- **What you expected:** Admins and Mods page
- **What happened instead:** Nothing, absolutely nothing - spinning blue wheel on right hand of page, in Browser Developer tools, the request is made to /api/admin/manage/admins-mods?_=1638363542654 - and it remains pending
Then after 5 minutes - `500.js` is loaded with a generic, uninteresting
```
Internal Error.
Oops! Looks like something went wrong!

There seems to be a problem with your internet connection
```

If, on the other hand, I navigate directly to that page by typing the URL in the address bar, the `get` remains in a pending state *forever* (well, 10 minutes so far)

Note: 
- I recently upgraded to this version of nodebb (from 1.18.5) - however, I did successfully navigate to that page shortly afterwards
```
[30/Nov/2021:05:17:40 +1100] "GET /api/admin/manage/admins-mods?_=1638209670040 HTTP/3" 200 1953
[30/Nov/2021:05:17:40 +1100] "GET /assets/templates/admin/manage/admins-mods.js?v=12v4ct4uikg HTTP/3" 200 2232
[30/Nov/2021:05:17:40 +1100] "GET /assets/language/en-GB/admin/manage/admins-mods.json?v=12v4ct4uikg HTTP/3" 200 312
[30/Nov/2021:05:17:40 +1100] "GET /assets/src/admin/manage/admins-mods.js?v=12v4ct4uikg HTTP/3" 200 1007
[30/Nov/2021:05:17:50 +1100] "GET /api/admin/manage/admins-mods?cid=6&_=1638209670041 HTTP/3" 200 2024
[30/Nov/2021:05:17:54 +1100] "GET /api/admin/manage/admins-mods?cid=9&_=1638209670042 HTTP/3" 200 1983
```
Then, today when I went to that page the first time
```
[01/Dec/2021:23:10:21 +1100] "GET /api/admin/manage/admins-mods?_=1638360344479 HTTP/3" 502 2197
[01/Dec/2021:23:10:21 +1100] "GET /api/admin/manage/admins-mods?_=1638360375746 HTTP/3" 502 2197
[01/Dec/2021:23:10:21 +1100] "GET /api/admin/manage/admins-mods?_=1638360375748 HTTP/3" 502 2197
[01/Dec/2021:23:10:21 +1100] "GET /api/admin/manage/admins-mods?_=1638360432308 HTTP/3" 502 2197
```
And since then
```
[02/Dec/2021:00:09:03 +1100] "GET /api/admin/manage/admins-mods?_=1638364037594 HTTP/3" 0 0
[02/Dec/2021:00:09:03 +1100] "GET /admin/manage/admins-mods HTTP/3" 0 0
```
You can see, the status is 0, the data sent is 0

- I've restarted `nodebb`
- I've run `nodebb build` trying to fix this
- I've restarted the server
- I've tried turning it off and on

Thanks

**Comment by barisusakli** [comment]
Can you add some console.logs to debug? One before this line https://github.com/NodeBB/NodeBB/blob/master/src/controllers/admin/admins-mods.js#L22 and one after. See if you see both console.logs.

There isn't much going on in that route so should be easy to find which call is causing the issue.

**Comment by jaromanda** [comment]
> Can you add some console.logs to debug? One before this line https://github.com/NodeBB/NodeBB/blob/master/src/controllers/admin/admins-mods.js#L22 and one after. See if you see both console.logs.

Nothing gets logged - do I have to "rebuild" or anything?

**Comment by barisusakli** [comment]
After you add console.logs you need to restart nodebb

**Comment by jaromanda** [comment]
Nope, adding console.log in there does nothing, nothing gets logged

**Comment by pitaj** [comment]
What did you say to be logged?

**Comment by barisusakli** [comment]
What about this line https://github.com/NodeBB/NodeBB/blob/master/src/controllers/admin/admins-mods.js#L18?
Check the values of `selectedCategory` and `cid`.

**Comment by jaromanda** [comment]
Ok, logging working now ... after doing some testing, the promise returned by

     groups.get('administrators', { uid: req.uid })

never resolves - the other 3 in that `Promise.all` do however.

**Comment by barisusakli** [comment]
Now you have to dig into that function to figure out which call is causing it 😆 https://github.com/NodeBB/NodeBB/blob/master/src/groups/index.js#L123-L147
It could be one of the calls or hooks in there.

**Comment by jaromanda** [comment]
changing

    String(groupData.description || '')

to

    String(groupData.description || ' ')

allowed me to edit the groups, so now everything works

Of course, there's still a bug if a Group is created with no description

**Comment by barisusakli** [comment]
This seems like a bug with the plugin using `filter:parse.raw` then. What version of plugin-markdown are you using? Check plugins that hook into filter:parse.raw at `/admin/advanced/hooks`

**Comment by jaromanda** [comment]
OK, my bad it was that damned `nodebb-plugin-sanitizehtml` which causes all sorts of other issues - I thought I had that removed!!! It didn't show up in that list of plugins either

Thanks for the help, sorry for the missing piece of the puzzle - as soon as I saw that was in the list of filter:parse.raw hooks, I knew it would be the culprit!!
