### ISSUE TITLE
NodeBB API documentation pages are not loading

### ISSUE THREAD

**Issue by sunilkolluru** [NodeBB/NodeBB#10058]
NodeBB API pages are not loading. 
https://docs.nodebb.org/api/read/ - read.yaml is throwing CORS error
https://docs.nodebb.org/api/write/ - write.yaml is throwing CORS error

New Post on https://community.nodebb.org is non functional and a blocker as always insists for Categroy but isn't fetching any categories in the drop down.

Thanks!

**Comment by a4anes** [comment]
Having the same issue.

**Comment by julianlam** [comment]
Thanks for reporting, we'll take a look. May be related to a recent server move.

**Comment by julianlam** [comment]
For the second, I am able to select a new category and post. Are you seeing this on desktop or mobile?

**Comment by barisusakli** [comment]
Getting two errors on desktop
![image](https://user-images.githubusercontent.com/2583394/144853874-029cbc88-8d6b-4919-aa76-fdff51dcbe37.png)

**Comment by sunilkolluru** [comment]
> For the second, I am able to select a new category and post. Are you seeing this on desktop or mobile?

I am seeing on desktop
![image](https://user-images.githubusercontent.com/75263980/144854935-a00220cb-fc4e-40f2-9661-b1b79ead9a55.png)

**Comment by julianlam** [comment]
@sunilkolluru Works fine here...

![image](https://user-images.githubusercontent.com/923011/144882767-88778925-8201-44c1-8256-249dda099490.png)

Can you open up dev tools and let me know what errors you see, if any?

**Comment by sunilkolluru** [comment]
> @sunilkolluru Works fine here...
> 
> ![image](https://user-images.githubusercontent.com/923011/144882767-88778925-8201-44c1-8256-249dda099490.png)
> 
> Can you open up dev tools and let me know what errors you see, if any?

I see the categories now. Any resolution on the api documentation pages issue? That was my primary issue. 

Thanks for looking into it.

**Comment by julianlam** [comment]
Not yet, but I will look into it :smile:

**Comment by julianlam** [comment]
@sunilkolluru I really do not know why this broke, the ACAO header was blank (but I think it was always blank).

Nevertheless, I've added `https://docs.nodebb.org` to the allow list now. Thank you for letting us know!

**Comment by sunilkolluru** [comment]
> @sunilkolluru I really do not know why this broke, the ACAO header was blank (but I think it was always blank).
> 
> Nevertheless, I've added `https://docs.nodebb.org` to the allow list now. Thank you for letting us know!
@julianlam Read APIs are loading but write APIs are still throwing the CORS error. 
Could you pls look into it?
Thanks

**Comment by julianlam** [comment]
The Write API loads for me, it might be a caching issue on your end.

**Comment by sunilkolluru** [comment]
> The Write API loads for me, it might be a caching issue on your end.
Yes, got it. Thanks for all the help.
