### ISSUE TITLE
Negative post count for users

### ISSUE THREAD

**Issue by MaxWaldorf** [NodeBB/NodeBB#10067]
- **NodeBB version:** v1.18.6
- **NodeBB git hash:** (official docker container)
- **NodeJS version:** (official docker container)

- **Installed NodeBB Plugins:** 
Active plugins:
        * nodebb-plugin-archiver@5.0.1 (installed, enabled)
        * nodebb-plugin-composer-default@7.0.14 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.0 (installed, enabled)
        * nodebb-plugin-desktop-notifications@0.3.3 (installed, enabled)
        * nodebb-plugin-emoji@3.5.3 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
        * nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
        * nodebb-plugin-feed@2.0.0 (installed, enabled)
        * nodebb-plugin-google-analytics@0.6.0 (installed, disabled)
        * nodebb-plugin-gravatar@2.3.0 (installed, enabled)
        * nodebb-plugin-hashtags@2.1.2 (installed, enabled)
        * nodebb-plugin-imgur@2.0.4 (installed, enabled)
        * nodebb-plugin-markdown@8.14.4 (installed, enabled)
        * nodebb-plugin-mentions@3.0.3 (installed, enabled)
        * nodebb-plugin-night-mode@1.0.7 (installed, enabled)
        * nodebb-plugin-openidconnect@0.0.2 (installed, enabled)
        * nodebb-plugin-poll@2.0.2 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.12.12 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.19 (installed, enabled)
        * nodebb-plugin-shortcuts@1.1.2+936 (installed, enabled)
        * nodebb-plugin-soundpack-default@2.0.0 (installed, enabled)
        * nodebb-plugin-spam-be-gone@0.7.11 (installed, enabled)
        * nodebb-plugin-youtube-embed@0.6.9 (installed, enabled)
        * nodebb-rewards-essentials@0.2.0 (installed, enabled)
        * nodebb-theme-lavender@5.3.1 (installed, disabled)
        * nodebb-theme-persona@11.2.22 (installed, enabled)
        * nodebb-theme-slick@1.4.16 (installed, disabled)
        * nodebb-theme-vanilla@12.1.10 (installed, disabled)
        * nodebb-widget-essentials@5.0.4 (installed, enabled)
- **Database type:** mongo
- **Database version:** 
v5.0.4
- **Exact steps to cause this issue:**

Deleting posts from users seems to put some of them in a negative count...

![image](https://user-images.githubusercontent.com/15877853/145092095-7535fbdb-ac07-4eed-bbbd-17849482f815.png)

- **What you expected:**
Post count should be 0 minimum
- **What happened instead:**
Negative post count on admin
0 post count on user profile...

**Comment by barisusakli** [comment]
Can you post the below info for the user with -6 posts.

```
db.objects.findOne({_key: "user:<replace_with_uid>"});
db.objects.findOne({_key: "users:postcount", value: "<replace_with_uid>"});
db.objects.count({_key: "uid:<replace_with_uid>:posts"});
```

**Comment by MaxWaldorf** [comment]
here is the info for the 3 queries:

`{
        "_id" : ObjectId("61608700cff079450bbe558d"),
        "_key" : "user:7253",
        "acceptTos" : 0,
        "banned" : 0,
        "birthday" : "redacted",
        "email" : "redacted",
        "gdpr_consent" : 0,
        "joindate" : 1477899596000,
        "lastonline" : 1477899596000,
        "lastposttime" : 1477955803000,
        "picture" : "redacted",
        "postcount" : -6,
        "reputation" : 10,
        "status" : "offline",
        "topiccount" : -1,
        "uid" : 7253,
        "uploadedpicture" : "redacted",
        "username" : "redacted",
        "userslug" : "redacted",
        "passwordExpiry" : 0,
        "password" : "redacted",
        "email:confirmed" : 1,
        "showemail" : 0,
        "showfullname" : 0,
        "profileviews" : 1
}`

`{
        "_id" : ObjectId("61608700cff079450bbe5599"),
        "_key" : "users:postcount",
        "value" : "7253",
        "score" : -6
}`

`0`

**Comment by barisusakli** [comment]
@MaxWaldorf you can run these to fix the negative counts.

```
// set all negative postcounts to 0 in user hashes
db.objects.update({
    _key: /^user:\d+$/, postcount: { $lt: 0 }
}, {
    $set: { postcount: 0 }
});

// set all negative scores in users:postcount zset to 0
db.objects.update({
    _key: "users:postcount", score: { $lt: 0 }
}, {
    $set: { score: 0 }
});
```

**Comment by MaxWaldorf** [comment]
Bith give the following result:

`WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })`

**Comment by barisusakli** [comment]
What do these give?
```
db.objects.count({
    _key: /^user:\d+$/, postcount: { $lt: 0 }
});
db.objects.count({
    _key: "users:postcount", score: { $lt: 0 }
});
```

**Comment by MaxWaldorf** [comment]
```
> db.objects.count({
...     _key: /^user:\d+$/, postcount: { $lt: 0 }
... });
294
> db.objects.count({
...     _key: "users:postcount", score: { $lt: 0 }
... });
290
```

**Comment by barisusakli** [comment]
Maybe try the original updates with `db.objects.updateMany` instead of `db.objects.update`

**Comment by MaxWaldorf** [comment]
Works!

Thanks
