### ISSUE TITLE
Pinned sort order doesnt set position correctly

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10068]
Should this just be ui.item.index()?

If I moved a topic from 4th place (data-index = 3) to the top of the pinned list (ui.item.index() = 0) the the current logic would be

3 + 0 - 1 = 2

So even though Ive moved it to the top on refresh the topic is now third in the list.

https://github.com/NodeBB/NodeBB/blob/45d8157feee5ba8b20f5525393eb2307fb6e5de4/public/src/client/category/tools.js#L294

**Comment by barisusakli** [comment]
@uplift thanks for reporting

**Comment by uplift** [comment]
@barisusakli Just testing the latest change. It works better than previous but if you move a lower pin to the top then start moving other pins, the order number goes wrong. Ill try to explain

With 4 pins, if you move the 4th pin (data-index = 3) to the top. (This works correctly)
If you then move the new 4th pin to the 3rd place then the new logic is 

3 (index from new first pin) + 2 (ui.item.index()) = 5 (bigger than the total amount of pins, which on refresh puts it as the last pin)

**Comment by barisusakli** [comment]
@uplift this is happening by doing the ordering multiple times without reloading the page right? I guess the data-index values are wrong after drag drop which causes this.
I will take a look.

**Comment by uplift** [comment]
Yeah no refresh between multiple reorders.

Maybe on init the baseIndex should be calculated for all future reorders (I'm assuming the baseIndex is used for when you have multiple pages of pins?)

**Comment by barisusakli** [comment]
Exactly baseIndex is used for multiple pages of pinneds and for infinitescroll, as in you scroll down and load more topics and the first pages of topics disappear so it needs to be calculated again. If you have lots of pinned topics.

If you are on page 2 baseIndex is 20 if topicsPerPage is 20.

**Comment by barisusakli** [comment]
I think fixing the `data-index` values of the pinned topic elements would fix this.

**Comment by barisusakli** [comment]
@uplift let me know, seems to work with multiple reorders now

**Comment by uplift** [comment]
Forgot to reply to this. That change seemed to have worked in my testing. Cheers for the fix
