### ISSUE TITLE
SEO cannibalism because of post_index

### ISSUE THREAD

**Issue by shayanYousefi** [NodeBB/NodeBB#10075]
- **NodeBB version**:*1.18.6* 
- **NodeBB git hash**:*16398dd92fb8092fe26603b72220044337aee51a* 

It seems that for navigating to a specific post of a topic, NodeBB is creating a unique link in the URL like this:

Without post_index: `https://my.forum.com/topic/:topic_id/topic-slug`
With post_index: `https://my.forum.com/topic/:topic_id/topic-slug/:post_index`

But routing in this way hurts the SEO ranking of forum because of cannibalism ([reference](https://yoast.com/keyword-cannibalization/)).

Instead what would be a better solution is to use query strings for post_index instead of putting it in URL path like this:
`https://my.forum.com/topic/:topic_id/topic-slug/?post_index=10`

This way when bots are crawling the site they know both URLs are referencing the same topic and rank the topic higher.

**Comment by julianlam** [comment]
Hello @shayanYousefi, we do not suffer from keyword or link cannibalism as each topic supplies a `rel="canonical"` tag referencing back to the main topic url (without the post index).

Are you seeing duplicate search results in a search query?If so, please link the search url for us to take a look.

**Comment by julianlam** [comment]
* https://yoast.com/rel-canonical/
* https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls
