### ISSUE TITLE
[suggestion] Add the invitation button under user avatar dropdown list

### ISSUE THREAD

**Issue by lslzl3000** [NodeBB/NodeBB#10072]
- **NodeBB version:**  v1.18.x

~~There is a panel in admin to send invitations, but can't find a button for normal users.~~
~~There are several options for invitation under user settings, but no native panel to use for normal users?~~

**Comment by lslzl3000** [comment]
Sorry, I have found the entry for native invitation under `/users`. It is hard to find~ And I don't want to add the users button in the navi bar.

Can we also just add a simpler button under user avatar dropdown list?

**Comment by barisusakli** [comment]
Custom JS to create invite button in user profile dropdown.

```
$('<li><a component="user/invite" href="#"><i class="fa fa-fw fa-users"></i> <span>Invite</span></a></li>').insertAfter(
    $('[component="header/profilelink/settings"]').parent()    
);
require(['accounts/invite'], function (accountsInvite) {
    accountsInvite.handle();
});
```

Or if you want to place it anywhere you want with an html widget place the below in an html widget

```
<button class="btn btn-default" component="user/invite">Invite Users</button>
<script>
document.addEventListener('DOMContentLoaded', function () {
  require(['accounts/invite'], function (accountsInvite) {
    accountsInvite.handle();
  });
});
</script>
```

![image](https://user-images.githubusercontent.com/2583394/151443668-86e5309a-01c5-4229-a068-8610a03bac69.png)
