### ISSUE TITLE
Increase the usage of compound assignment operators

### ISSUE THREAD

**Issue by elfring** [NodeBB/NodeBB#10073]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of compound operators](https://262.ecma-international.org/12.0/#sec-assignment-operators "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-/%^]|\*\*?|&&?|\|\|?|\?\?|<<|>>>?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/NodeBB/lokal -name '*.js')
```

**Comment by elfring** [comment]
💭 I would appreciate another constructive response for this issue.

**Comment by julianlam** [comment]
Hi @elfring — was there a specific reason we'd want to increase the usage of compound operators? We currently enforce style via eslint, and so while we're open to pull requests, it would have to pass that linter before being merged.

I believe we already use compound assignment operators when present (eslint would flag it for fixing), but if there are other opportunities, I suppose we would be open to it.

**Comment by elfring** [comment]
>was there a specific reason we'd want to increase the usage of compound operators?

💭 I imagine that software run time characteristics can be influenced another bit into desirable directions.


>…, but if there are other opportunities, I suppose we would be open to it.

:thinking: Would you dare to try a variant of the shown Perl command example out on another test repository?
