### ISSUE TITLE
Need details regarding ResetPassword API

### ISSUE THREAD

**Issue by sunilkolluru** [NodeBB/NodeBB#10076]
Hi,

There is an API for update password which takes in the current password and new password and updates it. Looking for reset password API. Any help is appreciated.

Thanks!

**Comment by julianlam** [comment]
Hi @sunilkolluru -- currently there is no API for user resets. It is still using the old websocket implementation (which works fine at present, which is why there is no immediate need to change it.)

Will keep this issue open as a reminder to port it over in time.

**Comment by sunilkolluru** [comment]
Thanks @julianlam for prompt response. Will check with my dev and follow-up if any further queries.

Appreciate all the help.
