### ISSUE TITLE
Problem displaying new internal link content

### ISSUE THREAD

**Issue by shlomo-shlomo** [NodeBB/NodeBB#10096]
In version NODEBB 18.6 (latest) a feature has been added that hovers over an internal link within the forum
A panel with the contents of the post is displayed
The problem is that if you put a link to another NODEBB site, it looks for the post number in the current forum, and displays incorrect content.
example (Place the link on the NODEBB website and hover over it to see):
https://try.nodebb.org/topic/2/creating-tables-in-nodebb/1
Hovering over the link, he tries to display:
https://community.nodebb.org/topic/2/test
<img width="884" alt="image" src="https://user-images.githubusercontent.com/78599753/147118495-c95e15b4-ee6e-4d67-858f-7d837cd4b153.png">

---
In addition, many times the view remains even after the mouse is removed from the link, and the page needs to be refreshed to get rid of it.

**Comment by barisusakli** [comment]
The issue with renaming preview should be fixed in https://github.com/NodeBB/NodeBB/commit/a9f81215cfe41aa8da12d05e16171cc7a2858d30

**Comment by shlomo-shlomo** [comment]
@barisusakli I did not understand, why did the problem close?
Has it been resolved yet?

**Comment by julianlam** [comment]
Yes, he fixed it in the above-mentioned commit.
