### ISSUE TITLE
GET request responses result in JSON SyntaxError

### ISSUE THREAD

**Issue by NazimHAli** [NodeBB/NodeBB#10105]
Hello,

I'm running into this JSON parsing bug with multiple endpoints. Here's a reproducible example using `community.nodebb.org ` following the GET example in https://docs.nodebb.org/api/#tag/topics/paths/~1api~1popular/get:

```js
fetch("https://community.nodebb.org/api/popular", {mode: "no-cors"})
        .then((response) => response.json())
        .then((data) => data);
```
```js
Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

Random public endpoints I tested that had the same error:
- https://community.nodebb.org/api/categories
- https://community.nodebb.org/api/recent/posts

When I inspect the network tab in the console, I see that data is returned. Would someone else test this and confirm if this is a bug?

![image](https://user-images.githubusercontent.com/26750288/147304125-156ce19e-5969-42c3-b422-c6942daa4fad.png)

**Comment by barisusakli** [comment]
Works fine for me 

![image](https://user-images.githubusercontent.com/2583394/147306640-404aee35-c8d9-4505-a93f-0705cd15e3ce.png)

**Comment by NazimHAli** [comment]
Wow, that's crazy, going to test it again. I tested that snippet with several endpoints and all of them returned a syntax error.

**Comment by NazimHAli** [comment]
Just tested it again, I think it only results in a syntax error if the request originates from a different subdomain. If you run that same snippet in:
- https://community.nodebb.org/ - works
- https://www.nodebb.org/ - errors out

Can you test this? The network tab shows the response returned, but not sure why it errors out.

**Comment by pitaj** [comment]
That's expected with `no-cors`. You can't read the response body if the request is made to a different domain.

https://evertpot.com/no-cors/

**Comment by NazimHAli** [comment]
> That's expected with `no-cors`. You can't read the response body if the request is made to a different domain.
> 
> https://evertpot.com/no-cors/

Ah I see, thanks for the info. I will close this since it's not a bug. The solution I used was to re-configure `nginx` so that only specific `origin` values were allowed. The response will not even be returned, by default all origins are blocked, here's sample code to allow specific origins in case anyone needs it:

```nginx
        if ($http_origin ~* "(https://nodebb.org|https://community.nodebb.org)") {
            add_header                  "Access-Control-Allow-Origin" "*";
        }
```

**Comment by pitaj** [comment]
You should be able to just put those origins in the ACAO header.

**Comment by NazimHAli** [comment]
@pitaj that's the first way I configured it, but received errors that the origin wasn't in the ACAO list. I expected it to work, but kept getting errors. Tried with local env and deployed test site.
