### ISSUE TITLE
Scaling docs make no mention of "isPrimary" or "jobsDisabled"

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10103]
Despite these two terms sounding like opposites of each other (which would mean one's superfluous), they actually mean something different and both need to be used in a scaled setup.

For the life of me I cannot remember what the difference is, [but the docs also make no mention of these configuration properties](https://docs.nodebb.org/configuring/scaling/).

Suggest adding them in.

**Comment by julianlam** [comment]
Looking at the code it seems like `isPrimary` is actually automatically set by `loader.js`, so it might not be necessary to explicitly define in `config.json`, but `jobsDisabled` does need to be set to prevent things like duplicate digests, etc.

**Comment by barisusakli** [comment]
`jobsDisabled` is mentioned here https://docs.nodebb.org/configuring/config/ might make sense to add a blurp on scaling page because that's where it is required.

**Comment by julianlam** [comment]
:+1: Perfect, will copy it over.

**Comment by barisusakli** [comment]
```
isCluster Set this to true if you have multiple machines each running a single NodeBB process. This setting is not required if you have multiple NodeBB processes running either on a single or multiple machines.
```
this can be copied to scaling as well. It needs to be used when you have multiple machines all using a single nodebb process.

**Comment by julianlam** [comment]
ah `isCluster`... :shipit: totally forgot about this one

**Comment by julianlam** [comment]
Updated.
