### ISSUE TITLE
ACP Rewards "Remove from Group" no dropdown

### ISSUE THREAD

**Issue by Jey-Cee** [NodeBB/NodeBB#10116]
- **NodeBB version:** 1.18.6 
- **NodeBB git hash:** b46dcd9243cafc2b087023345c0ceec51bb9d2ae 
- **NodeJS version:** 1.18.6
- **Installed NodeBB Plugins:** 
        * nodebb-plugin-composer-default@7.0.14 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.0 (installed, disabled)
        * nodebb-plugin-emoji@3.5.4 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
        * nodebb-plugin-markdown@8.14.4 (installed, enabled)
        * nodebb-plugin-mentions@3.0.3 (installed, enabled)
        * nodebb-plugin-spam-be-gone@0.7.11 (installed, disabled)
        * nodebb-rewards-essentials@0.2.0 (installed, enabled)
        * nodebb-theme-lavender@5.3.1 (installed, disabled)
        * nodebb-theme-persona@11.2.21 (installed, enabled)
        * nodebb-theme-slick@1.4.16 (installed, disabled)
        * nodebb-theme-vanilla@12.1.9 (installed, disabled)
        * nodebb-widget-essentials@5.0.4 (installed, enabled)
- **Database type:** mongo
- **Database version:** v4.0.27

- **Exact steps to cause this issue:**
    1. Go to ACP ->  Extend -> Rewards
    2. Add new reward with + button on the right bottom
    3. Choose "Remove from Group" in the then box
    
- **What you expected:**
   After step three there should apear a dropdown to choose the group, as it is when "Add to Group" is choosen.

- **What happened instead:**
   There is no dropdown to choose a group. See screenshot. 
   Also recognized after saving that the site did not load fully and the spinner is running always.
   
Log from browser console:
`Uncaught (in promise) TypeError: t.values.forEach is not a function
    at rewards.js:99
    at Array.forEach (<anonymous>)
    at c (rewards.js:94)
    at i (rewards.js:60)
    at HTMLSelectElement.<anonymous> (rewards.js:20)
    at Function.each (jquery.js:385)
    at C.fn.init.each (jquery.js:207)
    at Object.t.init (rewards.js:19)
    at ajaxify.js:357`

![image](https://user-images.githubusercontent.com/16007760/147859076-22243736-8c99-449e-ab43-5aab1cf20bde.png)

**Comment by barisusakli** [comment]
@Jey-Cee thanks for reporting.
