### ISSUE TITLE
"@" mention autocompletion not work on chat/global chat and PM after upgrade (1.18.6) 

### ISSUE THREAD

**Issue by DroidBV8** [NodeBB/NodeBB#10115]
- **NodeBB version:** 1.18.6
- **NodeBB git hash:** b46dcd9243cafc2b087023345c0ceec51bb9d2ae
- **NodeJS version:** v14.18.2

- **Installed NodeBB Plugins:** 
 * nodebb-plugin-beep@0.4.6 (installed, enabled)
        * nodebb-plugin-btn-spoilers (not installed, enabled)
        * nodebb-plugin-composer-default@7.0.14 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.0 (installed, enabled)
        * nodebb-plugin-email-blacklist (not installed, enabled)
        * nodebb-plugin-embed@3.0.19 (installed, enabled)
        * nodebb-plugin-emoji@3.5.4 (installed, enabled)
        * nodebb-plugin-emoji-apple@2.0.5 (installed, enabled)
        * nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
        * nodebb-plugin-global-chat@2.0.0 (installed, enabled)
        * nodebb-plugin-imgur@2.0.4 (installed, enabled)
        * nodebb-plugin-lightgallery@1.0.18 (installed, enabled)
        * nodebb-plugin-makesmart-gallery (not installed, enabled)
        * nodebb-plugin-markdown@8.14.4 (installed, enabled)
        * nodebb-plugin-mentions@3.0.3 (installed, enabled)
        * nodebb-plugin-night-mode@1.0.7 (installed, enabled)
        * nodebb-plugin-poll@2.0.2 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.12.10 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.19 (installed, enabled)
        * nodebb-plugin-shoutbox-neho (not installed, enabled)
        * nodebb-plugin-soundpack-default@2.0.0 (installed, enabled)
        * nodebb-plugin-spam-be-gone@0.7.11 (installed, enabled)
        * nodebb-plugin-view-votes@1.0.0 (installed, enabled)
        * nodebb-plugin-youtube-embed@0.6.9 (installed, enabled)
        * nodebb-rewards-essentials@0.2.0 (installed, enabled)
        * nodebb-theme-lavender@5.3.1 (installed, disabled)
        * nodebb-theme-persona@11.2.21 (installed, enabled)
        * nodebb-theme-slick@1.4.16 (installed, disabled)
        * nodebb-theme-vanilla@12.1.9 (installed, disabled)
        * nodebb-widget-essentials@5.0.4 (installed, enabled)
        * nodebb-widget-html-extended (not installed, enabled)

- **Database type:** mongo
- **Database version:**  v4.4.6
- **Exact steps to cause this issue:**
After upgrade to 1.18.6, I have a bug to mention and find users with autocompletion in chat, global chat and PM with the @
It doesn't work on chat, global chat and all PM.

- **What you expected:** That AUTOCMPLETION WITH @ works

- **What happened instead:**
That Not Works

**Comment by barisusakli** [comment]
Regression from https://github.com/NodeBB/NodeBB/pull/9679/files
`chat:autocomplete:init` was triggered via window now it switched to hooks and the hooks module doesnt support `chat:autocomplete:init`
