### ISSUE TITLE
Unable to resolve dependency tree when installing

### ISSUE THREAD

**Issue by trancephorm** [NodeBB/NodeBB#10133]
- NodeBB version: 1.18.6
- NodeBB git hash: 023e4cfcee208a0bae121a6e343a8c53009fd090
- NodeJS version: 16.13.1
- Installed NodeBB Plugins: no installed pluging, installation of NodeBB is itself broken 
- Database type: mongo (installation broke before option to choose DB, so I guess it's irrelevant)
- Database version: 5.0.5
- Exact steps to cause this issue:
1. Issuing ./nodebb setup I get this:

```pyc@ttdev:~/ttforum$ ./nodebb setup
package.json not found.
Populating package.json...
OK
Dependencies outdated or not yet installed.
Installing them now...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nodebb@1.16.2
npm ERR! Found: nodebb-plugin-emoji@3.5.4
npm ERR! node_modules/nodebb-plugin-emoji
npm ERR!   nodebb-plugin-emoji@"^3.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer nodebb-plugin-emoji@"^2.0.0" from nodebb-plugin-emoji-android@2.0.0
npm ERR! node_modules/nodebb-plugin-emoji-android
npm ERR!   nodebb-plugin-emoji-android@"2.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/pyc/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pyc/.npm/_logs/2022-01-09T12_49_15_236Z-debug.log
Error installing dependencies!
message: Command failed: npm install --production
stdout: null
stderr: null
/home/pyc/ttforum/src/cli/package-install.js:81
                throw e;
                ^

Error: Command failed: npm install --production
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.installAll (/home/pyc/ttforum/src/cli/package-install.js:72:9)
    at Object.<anonymous> (/home/pyc/ttforum/src/cli/index.js:62:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 248893,
  stdout: null,
  stderr: null
}```

- What you expected: I expected setup to continue
- What happened instead: Setup broke & I'm going to fire up my lappy if we don't get it fixed soon ;)

**Comment by trancephorm** [comment]
So I executed npm install --legacy-peer-deps
and it goes through with lot of audit fixes that need to be done:
18 vulnerabilities (1 low, 15 moderate, 2 high)

afterwards, executing ./nodebb setup

I get some almost trash on the screen along with endless
```t̑͊e̐̆ś̽t̒̾iͩ̓ ̖̖n̽̓ǧ̊ ͐͌t̆̔ ̰̮e͂ͫṡ̚ ̵͡t̅̎ ̥͚i̊̓n͒ͨ ̤́ǵͪ ̌ͭtͨ̋eͨ̋s̋̋t̀ͮi̒͒ň͛gͦ͋ ͂̅t̎̔e͗̂ ̴̺s͗̏ť͑i͐̓nͬͪğͤ ͦ͂tͧ͑e͑̄ŝͣt̿̾i̋ͩnͥͥg̔͌ ̅̄t̐͒eͦͩs͊̓tͩ̇ ͇͉i̓ͬ ͡͝nͦ̂ ͟͡g̔̈ ͬ̿ ̺̯t͒ͩȅ͂ṡ̌ ͕͈t̔̒ĭ̍nͭ̓g͗̍
t͊͆ ̛͘è͐s̅͊ ̸̧t̀ͨi̎ͬň̓ġ̈ ̋ͥt̃ͤe̅́sͥ͒t̓͊iͦ̀ ͕̪n̈͋g̀̉ ͭ̓t̆ͩeͮ͒s̾̉t̓̐ỉ̐n̈ͯgͬ̌ ̽ͬt̄̌e̅͂s̉͛t̓̓ ͚̫i̅͌n̎͗g̽͌ ͊̎t̿ͨē͑s̈ͦt̾̊i̓ͩn͊ͨg͒̄ ̆ͧt͗ͯ ͢͡ē͂sͥ̿tͪ̋i̓̉ ͙̬n̎ͣ ̛͘gͬ̿ ̇̌tͯ͌e̓̔s͆̒t̽ͮi̎ͬn̑ͮgͧ͆
tͨ̒ë͌ŝͧ ̪͞t̾ͩiͭ̓ ̸̧n̿̓ǵ̌ ͮͬt̎̌ ̸͘e̅͑s̄͋t́̓iͩ̾n̎̅ġ̒ ̄͆t̽̑eͥ̈sͪ̈tͫͨí͌nͬ̈g̾̆ ̐ͩt́̂eͧͤś́tͯ̈i͌̑ ̨̣n͊̋ ̛͖gͨ͐ ͨ́t̅̚e͒̑ ̛͝sͩ̒t̋̿iͦͮn̂ͣgͪ͗ ̥̘ ̀ͯt͌́eͨ̐s̊̔tͭ̍i͗̆ń͂g͆ͥ ̍͒t͒ͦ ̵̢eͭ̚ ̢͜s͆ͨtͨ͒i̋ͪn͐̈ğ͊
t̔́e̍ͫs̈̚t̊ͤiͥ̇n̽̒g̓ͧ ́ͧt͐̐eͤ̚sͭͦt̑̾i̅̚n̆ͯ ̵͝gͥ͐ ͥͯt̂͌e̾̌sͯ̌t͐ͥi̓̍n̓̂ġͧ ͛̓t̍ͪe̾͌s͋̂t͒̔i͆ͧnͯ͂g̃̐ ͋̚ṫ͑e̎̓s͆͌ ̴͠t̉ͥi̋ͦn̆͑ġ̃ ͨͥ ͈͉t͐ͬeͯ̏s̔̇tͦͯī̚ńͪg͋͛ ̓̔t̊ͪe͊ͨs͗ͦ ̺͡t̐ͨĩͩ ̟͘nͣ̉gͭ͆
tͬ̄e̽̚sͭ̈ ̶͇ẗ̒i̍̚nͮͧ ̢͜g̉̓ ͧͣ ̡͙t͂̂ ̕͝e̾̏s̈ͭt̓̓iͮͯnͫ̆g̍̂ ̉̚tͭͮ ̢͡eͣ̚sͮ̐t̒̌iͩ̄n̉̈gͦͭ ͒̒t͆̄e̅ͥ ̧͓s̊ͤt͑ͨȉͭn͛̍g͐͐ ͋ͬt̑͗ ̛͡eͬ͛s͑ͮtͪͤi͗̐nͫͤg̽ͫ ͣ̋t̍͗e̊̂s͌ͥt́̎ ̶̵i̾ͫn̓ͧg͂ͨ ͂́t̄ͦe͂ͨs̓̔tͨ͂i͂̆n͂͛g̈̌
t̍ͩe͊̇ ̵͎s͐͑t̊͊ĭ̍ ̛͞n̍ͧg̃ͬ ͨ̚tͨ̃ê̏sͥ͛tͦ̔ ̴́iͬ̐n͐̈ ̨̳g̃̓ ͮ̍t̽ͬȇ̒s͑̆t͛̅ ̺́ĩ̒n̅̈g̿̇ ̌́t͑ͦè̏s̐ͥt́ͭi͐͊n̂ͮg͊ͨ ͒̑t͛̈ ͜͠e͗̔ś̉t̿ͣi̇͊n͌̆ġͫ ̔̏ṫ̀ē̔ṡ̔tͬ̒i̓̓n̽ͧḡ́ ̂̉tͥͩẻ̾ ̨̕sͭ̈tͬ̏i̓̚n̔ͣg͆̒
ẗ̈e̔ͯs̈͊t͗̇i̓ͧn͂̈ ̴̲g̈͑ ͯͦtͪͣeͪ̓s̅̀t̓͑i͐̏  ̤̺n͂͒ğ̉ ̯̺ ͭ̋t̐̏e̓̇s͂̂tͯͤi̾̈ ̣̳nͩ̚gͫ̍ ͒̋t̍͒eͦ͗s̅ͧt̒͊iͮͧň͑ ̷͟gͪͤ ̰̞ ̎̉ ̲̯t̓́e͗ͦs̃̔tͭ̽i͋̐nͮͯg̃͐ ̴̮ ̽̒tͭ͑eͨ̉ ͙͜s̾ͧt́̾i͌̏ ̴͎n̐ͪg̉͒  ̨̛ ̀̓t̀ͫĕ͒s̓̐t̀͒i̓ͮnͨ̓g̏ͨ
t̑ͬe͋͛ŝ͆tͮ͛i̔ͭnͨͧĝ̾ ̇̓tͯ͑e̋ͩs͑͂t̐ͤï̌n͑̑g̋̔ ͖͠ ͆͐t͐ͭēͬsͣ̌tͧ͋iͤ̔n̓̀ḡ̐ ̵̣ ̾̅t͗̅e͋̓s̈̾ẗ̊ ̕͘ï̿n͒̀gͫ͒ ̈̈tͮ͐e͒ͥs̔ͣt́̎iͦͤ ̢̲n͒̇g͌͐ ̂̏t̎̉ ̢̡e̎͋s̏̑t̑̌ ̬̦iͦ̃n̈ͮg͆ͮ ̔͗t͆̆ë̾sͮ̿t̊ͤ ̧̭iͭͣńͮgͭ̍
```

Is this problem a subtle message that I should buy a licence for hosted NodeBB?
Setup is completely broken.

**Comment by pitaj** [comment]
Why are you installing NodeBB 1.16.2? The latest version is 1.18.x

**Comment by trancephorm** [comment]
Didn't pay attention to git clone line, I should've changed version. Thanks for helping me out. Anyways, that could be fixed in https://docs.nodebb.org/installing/os/ubuntu/, or make it always up-to-date somehow.

Also there is another error in [Inst](https://docs.nodebb.org/installing/os/ubuntu/).
mongo -u admin -p your_password --authenticationDatabase=admin   user should be nodebb instead of admin

**Comment by oplik0** [comment]
This step is for verifying you have administrative access after enabling authorization in mongodb.
A separate step to check if nodebb user is working correctly could be added, but admin access is also good to have here, because otherwise you'll need to disable authorization and restart MongoDB to change anything outside of the nodebb database.

And I just remembered that I made a PR to update versions in docs some time ago :) https://github.com/NodeBB/docs/pull/56
I'll add some minor bumps there though, since I think when I made it 1.18.0 was the latest version.

**Comment by trancephorm** [comment]
Ain't there a way to git clone always the last version?

**Comment by oplik0** [comment]
You can use the `master` branch to always get the latest code, but there isn't any "always latest release" branch AFAIK.
I assume the reason is that there can be breaking changes between new release branches (for example you can see breaking changes that will happen in 1.19 [here](https://community.nodebb.org/topic/15981/1-19-0-breaking-changes)), so changing the branch is additional friction to prevent the user from accidently updating to a new version and breaking some plugin/theme.
