### ISSUE TITLE
Multilanguage support of content

### ISSUE THREAD

**Issue by loid345** [NodeBB/NodeBB#10130]
In the era of the global internet, many platforms have long had multilingual support of content. I think it is high time nodebb as a mature platform have multilingual support of content. To begin with, at a minimal level, at least translation of categories and descriptions of categories, and then translation of tags, static pages, widgets, etc. How do you think?

**Comment by julianlam** [comment]
How do you mean? NodeBB is already internationalized into 40 plus languages.

We cannot control the localization of user generated content, of course

**Comment by loid345** [comment]
> How do you mean? NodeBB is already internationalized into 40 plus languages.
> 
> We cannot control the localization of user generated content, of course

I mean, the forum is conducted in the same language anyway. Right now we can't add multiple category names and descriptions of a certain category, tag, etc. in different languages. The only thing we can do is create a new forum for each language. This limits the owners of the forum in its use for multilingual communities.

**Comment by pitaj** [comment]
List out exactly what you'd like to be able to translate. So far we have:

- category names
- category descriptions
- tags
- widgets

I think this probably won't be too difficult to support with nodebb-plugin-customize. All we need to do is add creation of new translation tokens. Just need to make sure translations aren't escaped in those places (at least on the admin side).

**Comment by loid345** [comment]
> Перечислите, что именно вы хотели бы уметь переводить. На данный момент у нас есть:
> 
> * названия категорий
> * описания категорий
> * теги
> * виджеты
> 
> Я думаю, что это, вероятно, не будет слишком сложно поддерживать с помощью nodebb-plugin-customize. Все, что нам нужно сделать, это добавить создание новых токенов перевода. Просто нужно убедиться, что переводы не экранированы в этих местах (по крайней мере, на стороне администратора).

To begin with, at least bring the names and descriptions of categories. I am creating a community in Russian and English. In order not to duplicate categories for each language, it is necessary to specify the names and descriptions of categories in both languages. It would be great to translate the tags as well.

**Comment by barisusakli** [comment]
Category names and descriptions are already translated, if you put in translation key in name/description they will be translated.

**Comment by loid345** [comment]
> Category names and descriptions are already translated, if you put in translation key in name/description they will be translated.

Thanks for the answer. But where can I get this translation key for my content? For example, for the English version, I enter the text in the title/description of the category "Nodebb platform/Nodebb platform is the best platform for creating communities in the world", and for the Russian version, I need to add the translation "Платформа Nodebb/Платформа Nodebb лучшая платформа в мире для создания сообществ".

**Comment by barisusakli** [comment]
You add them in translation files in your theme/plugin. Like this https://github.com/NodeBB/nodebb-theme-persona/blob/master/languages/en-GB/persona.json.

And in the ACP you put translation keys in the name/description like `[[mytheme:category1-name]]` / `[[mytheme:category1-description]]`. Translations are loaded from json files.

**Comment by loid345** [comment]
> And in the ACP you put translation keys in the name/description like `[[mytheme:category1-name]]` / `[[mytheme:category1-description]]`.

Tell me, where is put translation keys in the admin panel?

**Comment by barisusakli** [comment]
You put them in the category edit page.

![image](https://user-images.githubusercontent.com/2583394/148710974-54778539-ebdc-40ee-9e7d-74dc719776ad.png)

And then provide the translation json files in your theme/plugin.

**Comment by loid345** [comment]
> Вы помещаете их на страницу редактирования категории.
> 
> ![изображение](https://user-images.githubusercontent.com/2583394/148710974-54778539-ebdc-40ee-9e7d-74dc719776ad.png)
> 
> А затем предоставьте JSON-файлы перевода в вашей теме/плагине.

**Comment by loid345** [comment]
> > Вы помещаете их на страницу редактирования категории.
> > ![изображение](https://user-images.githubusercontent.com/2583394/148710974-54778539-ebdc-40ee-9e7d-74dc719776ad.png)
> > А затем предоставьте JSON-файлы перевода в вашей теме/плагине.

Thank you very much! Yes, everything works) I added the translation to the persona theme for testing, but it's probably worth creating a separate plugin for translation, because when updating, custom translations will be deleted. What else can be translated this way? Tags, widgets?

**Comment by barisusakli** [comment]
Tags won't work right now because you can't use `:` in tag names. Also users likely won't be entering translation keys in the composer. When you use html/text widgets if you use translation keys in the content those will be translated.

**Comment by loid345** [comment]
> Теги не будут работать прямо сейчас, потому что вы не можете использовать их `:`в именах тегов. Также пользователи, скорее всего, не будут вводить ключи перевода в файл composer. Когда вы используете html/текстовые виджеты, если вы используете ключи перевода в контенте, они будут переведены.



> Tags won't work right now because you can't use `:` in tag names. Also users likely won't be entering translation keys in the composer. When you use html/text widgets if you use translation keys in the content those will be translated.
You can modify the platform so that tags tags are compatible with `:`?

**Comment by barisusakli** [comment]
We might allow `:` in tags as part of https://github.com/NodeBB/NodeBB/issues/10135, but it doesn't solve the issue of translating tags, one user can enter `bug` as tag another user can enter `ошибка` these would be treated as 2 different tags by the system.

**Comment by loid345** [comment]
> We might allow `:` in tags as part of #10135, but it doesn't solve the issue of translating tags, one user can enter `bug` as tag another user can enter `ошибка` these would be treated as 2 different tags by the system.

I agree. It is necessary to establish a uniform standard in the creation of tags. Or prevent users from creating new tags. Then there probably won't be duplicates

**Comment by barisusakli** [comment]
Hmm I think so, they should be translated if you use a translation key. I'm not sure if we display description anywhere. Should only be in the meta tags.

**Comment by loid345** [comment]
> Hmm I think so, they should be translated if you use a translation key. I'm not sure if we display description anywhere. Should only be in the meta tags.

Thanks, I'll try. This is necessary for SEO, and meta tags are displayed at the top in the browser. One more question, it's off topic. Can I move the user menu block with search and notification from the desktop menu to the mobile menu instead of the message block? To make the mobile menu more convenient, as in the best solutions? The mobile menu needs improvement, it is not usability

**Comment by loid345** [comment]
It will be the best gift in 2022 for users to make a cool mobile menu. And an even better gift if this menu can be moved up or down the mobile view

**Comment by barisusakli** [comment]
For that kind of modification you need to fork persona and modify the templates.

**Comment by loid345** [comment]
> For that kind of modification you need to fork persona and modify the templates.

Does it prevent you from doing it now and competing with discourse and hundreds of other solutions? Is it very inconvenient right now, or am I wrong?

**Comment by loid345** [comment]
The devil is in the little things. And this is not a trifle

**Comment by julianlam** [comment]
@loid345 Persona has the mobile menus implemented in that way as a design decision. NodeBB does not hamstring you to a specific design, that's part of what makes NodeBB great (its flexibility for theming).

**Comment by loid345** [comment]
> @loid345 Persona has the mobile menus implemented in that way as a design decision. NodeBB does not hamstring you to a specific design, that's part of what makes NodeBB great (its flexibility for theming).

I'm not talking about the persona, I'm talking about the mobile menu. Can't you see for yourself that it's uncomfortable on the right? There is only a messenger, and there should be a block of search, notifications, messenger and user. Like in the desktop menu, like everyone else. It's very convenient, it's right, and now it's a modern usability standard.

**Comment by loid345** [comment]
How many examples can you find? I can find at least 20

**Comment by loid345** [comment]
This is the standard.

**Comment by loid345** [comment]
Show me an example of where the search is hidden. The search icon is always visible on the mobile menu, this is critical for the community. Search is 20% of the actions of community users, it should be visible

**Comment by loid345** [comment]
The most important function on the forum is search. It is impossible to find anything without searching on the forum. Where is the search in all forums? In the header of the mobile menu

**Comment by julianlam** [comment]
This issue is not the appropriate forum to discuss design of the theme. Please take this to the community forum, if you'd like to continue discussion. Thanks!

**Comment by loid345** [comment]
> I can see that this issue is very important to you. However, this issue is not the appropriate forum to discuss design of the theme. Please take this to the community forum, if you'd like to continue discussion. Thanks!

Thanks a lot for your answer. Yes, this question is very important, but not only for me, but for all communities. This will be of great benefit to nodebb, this is a critical point. Let's keep in touch with the community. Thanks again)
