### ISSUE TITLE
Top liked posts of the forum

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10165]
This is an enhancement request similar to the most popular topics... 

Currently, when we click "popular" icon on the top, the popular page lists the topics with the most replies with these parameters: day / week / month / all time 

We can have several options on the top of the popular page (TOPICS / POSTS) ... And "posts" button lists the most liked posts of the forum by keeping the same parameters (day / week / month / all time)... 

The main objective is that the most liked posts are usually the one that is most useful or more likely to be useful, but there is no easy way to reach these posts in a regular forum setting. This will likely increase the overall interaction in the forum and especially in the topics that have these "liked/popular" posts...

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-best-posts
