### ISSUE TITLE
topic link is broken after merging the topic 

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10170]
after merging the topic, the topic URL has an addition of `/topic/` before the "subfolder" addition, which breaks the link...  You can see the link on the below picture at the bottom left corner... 

<img width="940" alt="Screen Shot 2022-01-15 at 5 08 47 PM" src="https://user-images.githubusercontent.com/52054408/149639278-0879e6a8-b313-4607-aff4-91d66e8db68c.png">

**Comment by barisusakli** [comment]
Bug is in the turkish translation file https://github.com/NodeBB/NodeBB/blob/master/public/language/tr/topic.json#L58 compare the merged message with english it has an extra topic in it.

**Comment by barisusakli** [comment]
Needs to be fixed on transifex turkish file.

**Comment by AliCihan** [comment]
I deleted the "topic" in the html code, can you please check? 

https://www.transifex.com/nodebb/nodebb/translate/#tr/topic/135342705

**Comment by barisusakli** [comment]
It should be `"merged_message": "Bu başlık <a href=\"%1\">%2</a> ile birleştirildi",` in the turkish topic.json file

**Comment by barisusakli** [comment]
Looks good I think.
