### ISSUE TITLE
[Feature request] Read API: Allow getting of all posts in topic

### ISSUE THREAD

**Issue by matsjs** [NodeBB/NodeBB#10176]
Hi,

I would like to get all posts in a topic without pagination. One way to do this could be setting `stop` to `-1`  in [src/controllers/topics.js](https://github.com/NodeBB/NodeBB/blob/14e211fb68534ec88e1035bd65eecf13087a8c5e/src/controllers/topics.js) `calculateStartStop` if `!settings.usePagination`. Another option could be to read a query parameter setting pagination to false.

If this feature would be welcome I'll make a pull request.

**Comment by matsjs** [comment]
Thank you for your response Pitaj.
Cannot disagree with that. However, I doubt that the post count per topic in my use case ever will be large enough to be problematic. In any case I'd switch to paginated calls before that would be a problem.

My use case is simply displaying forum posts from a NodeBB instance in another front-end service.

**Comment by pitaj** [comment]
Would you be satisfied with an option to load a number of posts of your choosing at a time? Like pass in a count parameter and you get that many posts returned? We'd probably cap it around 100 or something.

**Comment by matsjs** [comment]
No - it's fine. I'll just add pagination to my frontend. Thank you!
