### ISSUE TITLE
Hooks for Lake or Dislike

### ISSUE THREAD

**Issue by shlomo-shlomo** [NodeBB/NodeBB#10179]
Hello, I'm looking for action hockey (Customer side) that occurs when:
1. Add a Like to the post.
2. Add a dislike (vote below) to the post.
I found [here](https://github.com/NodeBB/NodeBB/blob/b06c6329e4dab9e4408d7a02f5f649a86f2f8575/src/posts/votes.js#L212) the "action: post.upvote" and "action: post.downvote", but it does not work
 Is there anything that works?
 @barisusakli I saw you changed something in this area of the code, maybe you can help
...

**Comment by shlomo-shlomo** [comment]
Note: I know there is this: "action: post.toggleVote", but I'm looking for a separate hook to vote down and a separate hook to vote down.

**Comment by barisusakli** [comment]
You can use `action:post.toggleVote` it is passed a delta value and unvote flag, from those you can determine if its an upvote or downvote.
```
$(window).on('action:post.toggleVote', (ev, hookData) {
    const isUpvote = hookData.delta === 1 && !hookData.unvote;
    const isDownvote = hookData.delta === -1 && !hookData.unvote;
    console.log(isUpvote, isDownvote);
});
```

**Comment by shlomo-shlomo** [comment]
@barisusakli Thank you, it's great. (By the way, you forgot to add "=>" in the arrow function setting ;-))
How can I get information about Like / Dislike already given?

**Comment by barisusakli** [comment]
To cancel a upvote you make an `delete` request to the same endpoint
