### ISSUE TITLE
Cannot disable email confirmation

### ISSUE THREAD

**Issue by SenkJu** [NodeBB/NodeBB#10180]
- **NodeBB version:** 1.19.0
- **NodeBB git hash:** aa77758afd7f97a762a7b53a910a72260153cfbe
- **NodeJS version:** v14.18.3

- **Installed NodeBB Plugins:**
- nodebb-plugin-composer-default
- nodebb-plugin-dbsearch
- nodebb-plugin-emailer-mailgun
- nodebb-plugin-emoji
- nodebb-plugin-emoji-android
- nodebb-plugin-github-embed
- nodebb-plugin-markdown
- nodebb-plugin-mentions
- nodebb-plugin-ns-login-reloaded
- nodebb-plugin-poll
- nodebb-plugin-question-and-answer
- nodebb-plugin-recent-cards
- nodebb-plugin-spam-be-gone
- nodebb-plugin-sso-google
- nodebb-plugin-youtube-embed
- nodebb-rewards-essentials
- nodebb-theme-persona
- nodebb-widget-essentials

- **Database type:** mongo
- **Database version:** db version v4.4.11

- **Exact steps to cause this issue:**
I'm not sure if I'm just blind, but I cannot for the life of me find the setting which enables email confirmation on the latest version. I'm almost certain that it used to reside under `Settings->Users->User Registration` and the search bar, in fact, still finds the setting I'm looking for, but when I click it, I can't see it. Has it been moved to a different location or is this a bug?

The setting I'm searching for:
![01-19-22_M0sMd2Oy_msedge](https://user-images.githubusercontent.com/18741573/150034956-c017f08b-a55c-44d2-b42a-f812d9260b02.png)

What I see when I click the search result:
![01-19-22_rgbdGYDP_msedge](https://user-images.githubusercontent.com/18741573/150035076-0ddb8abd-ce43-45a2-99cc-79d796e52167.png)

**Comment by barisusakli** [comment]
A verified-users group was added and the requireEmailConfirmation config was removed, https://github.com/NodeBB/NodeBB/commit/69c96dd23c5c6101100402eee4ca45c410665867

You can prevent users with unconfirmed emails from posting by using the privilege system.

There is a setting https://community.nodebb.org/admin/settings/user#user-registration to require an email address during registration.

**Comment by barisusakli** [comment]
I removed the unused language key so it doesnt show up in ACP search.

**Comment by FartCheese** [comment]
POV: CCBlueX Forum
