### ISSUE TITLE
External assets fail to load to "service-worker.js"

### ISSUE THREAD

**Issue by MaxWaldorf** [NodeBB/NodeBB#10193]
- **NodeBB version:**
1.19.1

- **NodeBB git hash:**
Official Docker Image 1.19.1

- **NodeJS version:**
Official NodeBB docker image

- **Installed NodeBB Plugins:** 
        * nodebb-plugin-2factor@3.0.4 (installed, disabled)
        * nodebb-plugin-archiver@5.0.1 (installed, enabled)
        * nodebb-plugin-composer-default@7.0.18 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.1 (installed, enabled)
        * nodebb-plugin-desktop-notifications@0.3.3 (installed, enabled)
        * nodebb-plugin-emoji@3.5.4 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
        * nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
        * nodebb-plugin-feed@2.0.0 (installed, enabled)
        * nodebb-plugin-google-analytics@0.6.1 (installed, enabled)
        * nodebb-plugin-gravatar@2.3.0 (installed, enabled)
        * nodebb-plugin-hashtags@2.1.3 (installed, enabled)
        * nodebb-plugin-imgur@2.0.4 (installed, enabled)
        * nodebb-plugin-markdown@8.14.6 (installed, enabled)
        * nodebb-plugin-mentions@3.0.4 (installed, enabled)
        * nodebb-plugin-night-mode@1.0.7 (installed, enabled)
        * nodebb-plugin-openidconnect@0.0.2 (installed, enabled)
        * nodebb-plugin-poll@2.0.2 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.12.20 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.19 (installed, enabled)
        * nodebb-plugin-shortcuts@1.1.2+936 (installed, enabled)
        * nodebb-plugin-soundpack-default@2.0.0 (installed, enabled)
        * nodebb-plugin-spam-be-gone@0.7.12 (installed, enabled)
        * nodebb-plugin-youtube-embed@0.6.9 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@5.3.2 (installed, disabled)
        * nodebb-theme-persona@11.3.18 (installed, enabled)
        * nodebb-theme-slick@1.4.23 (installed, disabled)
        * nodebb-theme-vanilla@12.1.16 (installed, disabled)
        * nodebb-widget-essentials@5.0.4 (installed, enabled)

- **Database type:** mongo 

- **Database version:** 
5.0.5

- **Exact steps to cause this issue:**
Using Brave Browser V1.34.81 , I get an issue on first load after upgrading to 1.19.1
Local assets are being fetched correctly but remote assets are failing to display...

Here is an example of feedback from browser console:
```
The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
service-worker.js:14          Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:14:11
www.googletagmanager.com/gtag/js?id=REDACTED:1 Failed to load resource: net::ERR_FAILED
service-worker.js:14          Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:14:11
service-worker.js:14          Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:14:11
service-worker.js:14          Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:14:11
service-worker.js:14          Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:14:11
413f56c6afdb710583f065d241143758:1 Failed to load resource: net::ERR_FAILED
ad4cc06e3b5f05d765c56da799a3011f:1 Failed to load resource: net::ERR_FAILED
api.js:1 Failed to load resource: net::ERR_FAILED
www.clarity.ms/tag/REDACTED:1 Failed to load resource: net::ERR_FAILED
service-worker.js:14          Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:14:11
app.js:364 ServiceWorker registration succeeded.
www.googletagmanager.com/gtag/js?id=REDACTED:1 Failed to load resource: net::ERR_FAILED
DevTools failed to load source map: Could not load content for https://REDACTED/assets/src/modules/pulling-drawer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

- **What you expected:**
Normal and direct load of the page without errors

- **What happened instead:**

In order To solve this, I have to force reload the page...

Cheers

**Comment by barisusakli** [comment]
Can you post your commit hash?

**Comment by barisusakli** [comment]
Can you check admin/settings/advanced for these settings 

![image](https://user-images.githubusercontent.com/2583394/150987869-6ff98a39-b4e2-48a6-b286-6d96a4c144c7.png)

**Comment by MaxWaldorf** [comment]
Disabled

I think it really was a browser issue in the end...
