### ISSUE TITLE
internal error in ACP (Manage>Uploads>Files)

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10208]
In ACP > Manage > Uploads > Files ...

You can browse the files when the page number can be seen in the pagination box, however, when you type the page number in the pagination box it gives an internal error... 

Here is the screenshot:
<img width="1205" alt="Screen Shot 2022-01-29 at 9 47 18 PM" src="https://user-images.githubusercontent.com/52054408/151684765-467ede31-5340-4229-aadc-4020d5452542.png">

Here is the log: 
<img width="882" alt="IMG_2212" src="https://user-images.githubusercontent.com/52054408/151684768-cb70db7a-e626-424e-b6c7-1e6f4fa73487.png">

**Comment by barisusakli** [comment]
Seems like something is wrong with the path being used.
`/forum/api/admin/manage/uploads?dir=%252Ffiles` Seems the dir query param is url encoded twice.
