### ISSUE TITLE
`./nodebb upgrade -m` clobbers custom values if they differ from install/package.json

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10229]
There is custom logic to handle the `dependencies` property:

https://github.com/NodeBB/NodeBB/blob/8ba9e67cbd5044ffa02ae042baa9609fc706c108/src/cli/package-install.js#L33-L38

However, anything outside of that is overwritten if the value is present in `install/package.json`:

https://github.com/NodeBB/NodeBB/blob/8ba9e67cbd5044ffa02ae042baa9609fc706c108/src/cli/package-install.js#L43

Specifically, if the local project has custom `devDependencies`, or some added `scripts`, the values will be lost every time the package.json files are merged.

**Comment by pitaj** [comment]
devDeps will be hard to handle because it'll be hard to know which old ones were from an older version of NodeBB or customized.
