### ISSUE TITLE
users' posts with negative votes

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10233]
users' posts with negative votes (worst posts) should be available on the profile options for admins... 

https://community.nodebb.org/topic/16279/a-user-s-posts-with-negative-votes

**Comment by julianlam** [comment]
Shall we call it "Controversial", like Reddit does :stuck_out_tongue:

**Comment by AliCihan** [comment]
> Shall we call it "Controversial", like Reddit does 😛

I guess "controversial posts" sounds better than the "worst posts" lol
