### ISSUE TITLE
Write API v3 `/users/:uid/emails/:email/confirm` not working

### ISSUE THREAD

**Issue by psloh** [NodeBB/NodeBB#10236]
I'm running NodeBB v1.19.1 on NodeJS v16.13.2 using Mongo, and have thoroughly enjoyed watching this platform grow over the past 8 years.

I have our account creation on a separate platform, which calls the NodeBB Write API to create users by supplying an email, username, and password. The Write API (v3) creates the accounts, but marks the email addresses as unconfirmed. Many versions ago, it was possible for people to log in using that email address and password. I then upgraded many versions, up to v1.18.x and now v1.19.x. Now, I'm facing a problem where users are not able to log in using their email addresses. I have noticed that if I manually go into the Admin Control Page and mark their email address as confirmed, then they can log in using their email address.

So, I tried calling the `/users/:uid/emails/:email/confirm` API route, using a Write API (v3) master bearer token with `_uid` equal to 1 (admin). It gave me the error:

```
{"status":{"code":"not-found","message":"Invalid API call"},"response":{}}
```

I was using the command line:

```
curl -H "Authorization: Bearer [bearer token from Settings > API Access] " -X POST https://forum.poshenloh.com/api/v3/users/8815/emails/fakepoemail6@po.com/confirm -H "Content-type: application/json" --data '{"_uid": 1}'
```

(I had created a user with `uid` `8815` and email address `fakepoemail6@po.com`.)

Also, when I tested another endpoint of the Write API (v3), I got the strange output:

```
curl -H "Authorization: Bearer [token]" -X GET https://forum.poshenloh.com/api/v3/users/8815/emails?_uid=1
```

gave

```
{"status":{"code":"ok","message":"OK"},"response":{"emails":[]}}
```

Is this expected behavior? If so, what is the right way to invoke the Write API (v3) to confirm an email address? Thank you!

**Comment by julianlam** [comment]
Hi @psloh! Long time no see.

The email validation API route is fairly new (as of a couple weeks ago, even), so it may have a bug. I will take a closer look.

**Comment by julianlam** [comment]
Confirmed bug, the logic for email confirmation relies on the email being present in `email:uid`, as it does a check to verify that the email is set... but on user creation, the email is not added to `email:uid`, so it's a bit of a :chicken: :egg: problem.

**Comment by psloh** [comment]
Wow! You are so fast! It's so nice to hear from you too. I've been banging away on some other projects in the meantime (www.novid.org and live.poshenloh.com). But whenever we want to spin up a forum, you guys are the way to go.

Separately, was it intentional that when a user account is created with email + username + password via Write API (v3), the user is unable to log in using that email address? The easiest solution for us would be to allow unconfirmed email addresses to log in, or to make it so that the user account creation could have a "email:confirmed: true" option, to save the follow-up API call to confirm the email address.

I look forward to upgrading to 1.19.2 :)

**Comment by psloh** [comment]
You are awesome.

**Comment by pitaj** [comment]
@julianlam wanted to point this out

> Separately, was it intentional that when a user account is created with email + username + password via Write API (v3), the user is unable to log in using that email address? The easiest solution for us would be to allow unconfirmed email addresses to log in

**Comment by julianlam** [comment]
Thanks, a decision was made to restrict this behaviour because it meant that users could create an account with whatever email they wanted, even if it was out of their control.

I didn't want NodeBB to be part of that kind of mail spam, so we don't (be default) send emails to unconfirmed emails, and we don't associate emails with users unless they've been explicitly confirmed via code or by an admin.

**Comment by julianlam** [comment]
Passing in email in user creation is supported only for backwards compatibility (and probably won't be removed), but the ideal flow would be to pass in username and password, and when the user logs in for the first time, they'll be asked to add an email address.
