### ISSUE TITLE
Should purging topic purge topic thumbs?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10257]
Not sure if I've missed it in the code (v1.19.1) but should purging a topic also purge topic:${tid}:thumbs?

https://github.com/NodeBB/NodeBB/blob/0823992d63891699b9b44d9803b11d02711c1bb0/src/topics/delete.js#L66-L101

**Comment by julianlam** [comment]
* [ ] Refactor `thumbs.delete` to take an array in `relativePath`
* [ ] New method `thumbs.deleteAll` to remove all thumbs for a given tid
* [ ] Call `thumbs.deleteAll` on topic delete

**Comment by julianlam** [comment]
Unfortunately, I couldn't write an upgrade script to clean up the leftover orphaned files and database entries, as I don't have a record of which topics were purged :stuck_out_tongue_closed_eyes:

**Comment by julianlam** [comment]
Mm, actually, `db.scan` could work, trying that now.

**Comment by barisusakli** [comment]
You can start from 1 and go to global.nextTid and check if tid is in `topics:tid` if it's not topic is purged.

**Comment by julianlam** [comment]
Better. I'd rather not invoke db.scan :smile:
