### ISSUE TITLE
question about manifest.webmanifest?loggedin

### ISSUE THREAD

**Issue by joyhope** [NodeBB/NodeBB#10258]
I am using nodebb 1.19.1 , and https://github.com/LM1LC3N7/nodebb-plugin-private-forum.

after success login, the  URL is  https://xxxx/manifest.webmanifest?loggedin,  the is a JSON based page displayed. 

{"name":"xxx ","short_name":"xxx","start_url":"https://xxxx","display":"standalone","orientation":"portrait","theme_color":"#ffffff","background_color":"#ffffff","icons":[]}

It seems the plugin is correct, but nodebb manifest.webmanifest handle has a problem, it does not jump to the correct main page. 

I am using nginx as proxy for Nodebb.   

Is there any suggestion to solve my redir problem.?

**Comment by julianlam** [comment]
The manifest file is supposed to return JSON. It looks like the issue is with the plugin redirecting you to that page instead of to the homepage.
