### ISSUE TITLE
Post uploads deleted from disk are still associated with the user

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10272]
#10271 allows for automatic deletion of uploaded assets when a post is purged. However, we also track uploads by uid, and save it to `uid:<uid>:uploads` zset.

Unfortunately we do not have a zset tracking the reverse, so I cannot clean up the since-removed upload from the `uid:` zset.

* [x] Refactor post upload to hash files using the `/files/` prefix (+ upload script)
* [x] Upload script to fix uid upload zset members, and to add uid to the hash
* [x] On user upload association, save uid to uploads: hash (thanks @barisusakli)
* [x] Add new method to `src/user/uploads.js` for explicitly associating an upload with a user (instead of it being a one-off line in `src/controller/uploads.js`)
* [x] Fix `deleteUploads` in `src/user/delete.js` to call `User.deleteUpload` instead of doing it itself (:shipit:!)
* [x] On post upload dissociation, call `user.deleteUpload`
* [x] On user upload deletion, call `posts.uploads.dissociate` and delete upload object from db
* Tests
  * [x] on user upload association or deletion, the file path should be validated (exists and is in uploads dir)

**Comment by barisusakli** [comment]
`Store a reverse zset, upload:${md5(path)}:uids`

Does this make sense? An upload can't belong to more than one user so the zset would always have one uid. In that case might make more sense to have a `upload:${md5(path)}` hash with a uid field.

Also it seems all of our post uploads code only works with local uploads. So if someone is using a plugin like s3 to store uploads elsewhere `uid:<uid>:uploads` and `post:<pid>:uploads` will always be empty.

**Comment by julianlam** [comment]
Thanks for the feedback! 

In regards to the latter, we actually only store this information for GDPR purposes, and that includes the ability to delete the files (GDPR's right to be forgotten), so it is perfectly ok that these zsets only contain entries for locally uploaded files.

As for the former... You're right, while an upload can be associated with multiple pids, an upload is only ever associated with one user. I'll add it to the hash instead, thanks! That's a good catch.
