### ISSUE TITLE
"Changing" theme moves all widgets to global / draft zone

### ISSUE THREAD

**Issue by sadaszewski** [NodeBB/NodeBB#10276]
- **NodeBB version:** 1.19.1
- **NodeBB git hash:** 
- **NodeJS version:** 14

- **Installed NodeBB Plugins:** 

- **Database type:**  postgres
- **Database version:** 

- **Exact steps to cause this issue:**
I have set up nodebb-custom-pages with a /home and /partners routes which I have customized using Extend > Widgets. Then I activated the Persona theme (I was already using Persona at the time, I was just wondering if there are more settings if one clicks the "Current Theme" link). This caused all my widgets to move to the global / draft zone, a very unpleasant surprise.

- **What you expected:**

I thought nothing would happen to the widgets.
- **What happened instead:**

This caused all my widgets to move to the global / draft zone, a very unpleasant surprise. I had to manually redistribute them to the correct pages / zones.

**Comment by julianlam** [comment]
Yes, this is the expected behavior. Different themes have different support for widget areas, and not all themes have widget areas.

For compatibility across themes, we reset widgets when themes are changed.

That said, if you change a theme to the same theme, widgets shouldn't reset.

**Comment by julianlam** [comment]
To give additional contacts, if you have a widget setup in a specific widget area, change the scene, and that theme doesn't have that same widget area, the widget will disappear.

**Comment by sadaszewski** [comment]
I can only confirm that I was changing from the default theme to the Persona theme. The Persona theme was marked as "Current Theme". I clicked the "Current Theme" button/link and my widgets ended up in global / draft zone. I believe it would be better if that did not happen or at least if there was a warning / confirmation dialog. The widgets were on custom pages. I can't confirm at the moment but perhaps that played a role?

**Comment by julianlam** [comment]
Right, sounds like there are some bugs on this page. I can likely assume that widget reset would move every single widget to drafts, even those that weren't in the original theme. It may take a bit of work to update this to only move affected widgets out.

You are correct, widgets added to areas defined by custom pages should not be touched at all

**Comment by julianlam** [comment]
* [ ] "Current theme" button should have `.btn-disabled` class and client side event handler should not react to it
* [ ] On theme change, only widgets whose areas are not in the new theme should be moved to the draft zone
* [ ] widgets in areas added by the custom pages plugin should remain untouched
