### ISSUE TITLE
User.delete code duplication

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10277]
When calling User.delete it calls removeFromSortedSets then calls User.deleteAccount. 
Inside deleteAccount it then calls removeFromSortedSets again. 

Is the use on L25 needed?

https://github.com/NodeBB/NodeBB/blob/b8362c49cdaa571fad89652412be737d58d9f518/src/user/delete.js#L25-L26

https://github.com/NodeBB/NodeBB/blob/b8362c49cdaa571fad89652412be737d58d9f518/src/user/delete.js#L94-L100

**Comment by julianlam** [comment]
Hey, can we hire you to review our codebase more thoroughly? :laughing:

**Comment by uplift** [comment]
Trust me, you don't want that. My colleagues hate me 😄
