### ISSUE TITLE
Failed to load emoji metadata since v1.19.2

### ISSUE THREAD

**Issue by olivierlambert** [NodeBB/NodeBB#10278]
- **NodeBB version:** v1.19.2
- **NodeBB git hash:** ded19254ace8515a7a9bc02d06f326f86b2ed6ee
- **NodeJS version:** v16.13.0
- **Installed NodeBB Plugins:** 
	* nodebb-plugin-2factor@3.0.4 (installed, disabled)
	* nodebb-plugin-composer-default@7.0.20 (installed, enabled)
	* nodebb-plugin-custom-pages@1.3.1 (installed, disabled)
	* nodebb-plugin-dbsearch@5.1.1 (installed, enabled)
	* nodebb-plugin-emoji@3.5.9 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
	* nodebb-plugin-github-embed@0.7.8 (installed, enabled)
	* nodebb-plugin-markdown@9.0.5 (installed, enabled)
	* nodebb-plugin-mentions@3.0.4 (installed, enabled)
	* nodebb-plugin-ns-awards (not installed, enabled)
	* nodebb-plugin-poll@2.0.2 (installed, enabled)
	* nodebb-plugin-prometheus@0.4.0 (installed, enabled)
	* nodebb-plugin-question-and-answer@0.12.20 (installed, enabled)
	* nodebb-plugin-shortcuts@1.1.2 (installed, enabled)
	* nodebb-plugin-soundpack-default@2.0.1 (installed, enabled)
	* nodebb-plugin-spam-be-gone@0.7.12 (installed, enabled)
	* nodebb-plugin-sso-facebook@3.6.3 (installed, disabled)
	* nodebb-plugin-sso-github@2.3.1 (installed, enabled)
	* nodebb-plugin-sso-twitter@2.5.12 (installed, enabled)
	* nodebb-plugin-sso-wordpress@2.2.0 (installed, disabled)
	* nodebb-plugin-tenor-gif@1.2.8 (installed, enabled)
	* nodebb-rewards-essentials@0.2.1 (installed, enabled)
	* nodebb-theme-lavender@5.3.2 (installed, disabled)
	* nodebb-theme-persona@11.3.38 (installed, enabled)
	* nodebb-theme-slick@1.4.23 (installed, disabled)
	* nodebb-theme-vanilla@12.1.17 (installed, disabled)
	* nodebb-widget-essentials@5.0.7 (installed, enabled)
- **Database type:** redis
- **Database version:** Redis server v=3.2.12
- **Exact steps to cause this issue:**
	1. Updated from v1.19.1 to v1.19.2
	2. Any new answer in a thread (or new thread) will be an error toaster with "Failed to load emoji metadata". Emoji preview is broken, as completion for nicknames when typing in the answer text field.
- **What you expected:** same working behavior than the previous version
- **What happened instead:** error message and losing emojis preview

**Comment by pitaj** [comment]
Please try rebuilding emoji assets in the ACP plugin page, then rebuilding and restarting NodeBB.

**Comment by olivierlambert** [comment]
@pitaj that did the trick. Thank you!
