### ISSUE TITLE
Too much empty space in notifications in 1.19.2

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10284]
The new version has an unnecessary gain on each alert (previously it was not):
![image](https://user-images.githubusercontent.com/78599753/153725614-99703d8e-6e87-41a1-9c24-32fb390b3e15.png)

**Comment by julianlam** [comment]
Hi, what's a "gain"?

**Comment by ShlomoCode** [comment]
@julianlam 🤔?

**Comment by julianlam** [comment]
Haven't had a chance to address, but look to be an issue, yes.

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/155783883-61e30f99-ea66-412f-bdb3-5a62ea05a501.png)
