### ISSUE TITLE
Inscription links in Hebrew went completely wrong

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10283]
Since the last update (19.2) any link whose text is displayed in Hebrew, has become completely distorted!
It also includes the "User said in" and the subject title:
![image](https://user-images.githubusercontent.com/78599753/153725495-165fe06e-b4b6-418f-bc4d-9fcea1a23c26.png)
And also any link with display text in Hebrew:
![image](https://user-images.githubusercontent.com/78599753/153725521-25428de0-0528-4714-a116-57bb57205033.png)
Changing the interface language to English did not help.
This is really a bug!
I searched here in issues and did not find that they have written about it already.

**Comment by julianlam** [comment]
Fixed already in markdown plugin.

**Comment by ShlomoCode** [comment]
> Try with markdown 9.0.6

Why does it not offer me in the plugins #upgrade to upgrade?
I also see in the plugin details (in ACP) it appears that 9.0.5 is the latest version!
![image](https://user-images.githubusercontent.com/78599753/153725941-7f965404-cfaf-423a-8319-8561b0471547.png)

**Comment by ShlomoCode** [comment]
@julianlam What's the command if I now have 9.0.5 and I want to get the revised version?

**Comment by barisusakli** [comment]
`npm i nodebb-plugin-markdown@9.0.6`
