### ISSUE TITLE
package-install requires lodash, preventing fresh installs

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#10289]
https://community.nodebb.org/topic/16362/1-19-2-github-won-t-install-or-update/5

https://github.com/NodeBB/NodeBB/blob/a1593e35c0274a41a60a9760f8640279d910790e/src/cli/package-install.js#L6

External dependencies can't be used here. Use Object.assign or something instead, or move the require of lodash into the updatePackageFile function.

Need to eventually change tests to use our recommended fresh install steps so that this kind of thing gets caught.

**Comment by barisusakli** [comment]
😬

**Comment by julianlam** [comment]
Hmm, right.
