### ISSUE TITLE
Legacy Ban Data Sets Removal?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10290]
Nodebb 1.19.1
Redis Database

I've been doing some investigation into our data integrity and size of our Redis database.

In an upgrade script in 1.10.2 the ban data was upgraded to hashes but the existing sets were left. Can these sets be safely removed? I cant see any reference to them in the code but wanted to check I hadn't missed anything

The legacy sets are

uid:${uid}:bans
banned:${uid}:reasons

**Comment by barisusakli** [comment]
Yeah those are safe to remove, upgrade scripts leave them behind just in case we need to run the upgrade script again.
