### ISSUE TITLE
Deleting User leaves some User Data

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10292]
Nodebb 1.19.1

When deleting a user account the below keys seem to remain behind as far as I can tell. Should they be deleted also?

uid:${uid}:tids_read
uid:${uid}:tids_unread
uid:${uid}:blocked_uids
uid:${uid}:moderation:notes
uid:${uid}:moderation:note:*

In my db I also have the below. Any idea what it is or came from? I cant find it in the code anymore.

uid:${uid}:posts:votes (not to be confused with tid:${tid}:posts:votes)

**Comment by barisusakli** [comment]
I left moderation notes in case someone to review them for deleted users.

You can safely delete `uid:${uid}:posts:votes` they are not used anymore. We store them by category in these sets `cid:${cid}:uid:${uid}:pids:votes`

**Comment by uplift** [comment]
Leaving the moderation notes helps me with another issue but does that mean ban history should be left for the same reason? Actually I'll raise another issue and explain myself more 😄
