### ISSUE TITLE
Deleted Posts don't delete Post Diffs

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10291]
Nodebb 1.19.1

While investigating our database size I've noticed that between the post:${uid}:diffs and diff:${uid}.${timestamp} (most likely this key) keys it takes up about 40% of our total database size.

For a long running forum I assume diffs would take a fair chunk of memory but investigating further I cant see any code that would delete the diffs when the actual post is purged. Is it safe to delete diffs if a post has been purged? What would be the best way to do this for already purged posts?

**Comment by barisusakli** [comment]
They are safe to delete if the post is deleted, you could do this with a custom script.
