### ISSUE TITLE
When selecting a text for quoting, it is not the selected text that is copied, but the entire text

### ISSUE THREAD

**Issue by loid345** [NodeBB/NodeBB#10316]
nodebb: all versions.
Quick quoting is very convenient for answering a certain phrase. But the whole text is copied, not the selected phrase. When selecting a text for quoting, it is not the selected text that is copied, but the entire text. 
For an example of how it works correctly (discourse script)
![error](https://user-images.githubusercontent.com/20200970/154552218-fd30bcb1-fa47-48ca-9551-34e372c6c699.png)

**Comment by pitaj** [comment]
There's a little quote button that pops up when you select text. This quotes only that text.

**Comment by pitaj** [comment]
I'm pretty sure the quote feature used to work as you describe in general though.

**Comment by loid345** [comment]
> Я почти уверен, что функция цитаты работала так, как вы описываете в целом.

Yes, that's how it should be. But it doesn't work

**Comment by julianlam** [comment]
@loid345 Yeah this looks like a regression... if text is highlighted and you press "reply" from within the post, it should pre-populate the composer with the highlighted text.
