### ISSUE TITLE
Use a thread pool for password hashing

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#10326]
More efficient than using processes.

**Comment by julianlam** [comment]
Is that new? Could be we weren't ready for await before, but this is exciting :+1:

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/154728578-ed435325-a94e-404f-b1d9-1601df7e29d3.png)

**Comment by pitaj** [comment]
https://www.npmjs.com/package/bcrypt

> The async version uses a thread pool which does not block the main event loop.

**Comment by barisusakli** [comment]
Arent we using bcryptjs the js implementation of this 🤔 https://github.com/dcodeIO/bcrypt.js/
