### ISSUE TITLE
/users should show "Recently online" users

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10324]
Here's a bad UI mockup:

![image](https://user-images.githubusercontent.com/923011/154714214-739f1d81-810a-4928-ad5f-5d9b9252156e.png)

Perhaps showing users online within last 24 hours (ACP configurable?), in addition to users who are currently online.

**Comment by barisusakli** [comment]
Makes more sense to display a single list of past 24 hours, users who are currently online will be at the front of the list anyways.

**Comment by AliCihan** [comment]
Hi @barisusakli , I do not see this change in the prod NodeBB yet? Will "24 hours" be ACP configurable? 

and will there be two separate pages? 
* users?section=online
* users?section=recent

**Comment by barisusakli** [comment]
It's the same route users?section=online, 24 hours is not configurable right now.

**Comment by AliCihan** [comment]
I see how it works now on the forum. A little bit different than what I was thinking, will this change affect the online users widget? That was useful while PM'ing online users. If, that widget also will show the users in the last 24 hours, can I request two separate widgets?

**Comment by barisusakli** [comment]
This only effects the /users page, the online users widget didn't change.

**Comment by AliCihan** [comment]
that is great then... Thanks a lot. The current online users widget is cool enough 😎
