### ISSUE TITLE
Upload button for chat on a mobile device

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10320]
In version 19.2 they added an important thing - uploading photos and files directly to the chat, by dragging and dropping. But on a mobile device, even a tablet, it is impossible to drag ... Is it possible to add a button on the mobile to upload photos, as there is in the composer of the posts? Thanks!

**Comment by ShlomoCode** [comment]
@julianlam @barisusakli  Will it be done?

**Comment by ShlomoCode** [comment]
Why doesn't it appear in which commit it was completed? 🤔

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/79731735c0b2998b0165ae4d036b5bb4bb3d2591

**Comment by ShlomoCode** [comment]
Thank you
