### ISSUE TITLE
 Quote part of the post  didn't work 

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#10340]
- **NodeBB version:** v1.19.3

 Quote part of the post  didn't work Properly, it quote all of the post

![image](https://user-images.githubusercontent.com/37838903/155401510-0f079b53-dce7-4103-8a3f-ed29effdd310.png)

or 

![image](https://user-images.githubusercontent.com/37838903/155403381-ac6a7cea-8675-471f-97ce-16ac79e07669.png)

![image](https://user-images.githubusercontent.com/37838903/155403741-47ae0e5a-d89e-4fc8-9cee-3cbe641be834.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/10316
