### ISSUE TITLE
remove request and use fetch

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#10341]
since fetch will be part of nodejs. wait until we are node 18+ minimum

**Comment by barisusakli** [comment]
now that node 16 is EoL, we can start replacing request/request-promise-native with fetch 🤔

**Comment by GitHubCloud** [comment]
Hi @barisusakli, any updates?
i've also created a issue for the webhook plugin: https://github.com/NodeBB/nodebb-plugin-webhooks/issues/15

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/12236
