### ISSUE TITLE
og:image:url bad link for topics with thumbnail

### ISSUE THREAD

**Issue by phit** [NodeBB/NodeBB#10366]
- **NodeBB version:** 1.19.3
- **NodeBB git hash:**  673fcfb052d7c76ccc506fd640d3a7030caafdc4 
- **NodeJS version:** v16.14.0

- **Installed NodeBB Plugins:** 

- **Database type:** mongo, redis, or postgres
- **Database version:** 

- **Exact steps to cause this issue:**
Create a topic and upload a thumbnail for it

- **What you expected:**

working og:image:url tags

- **What happened instead:**

the thumbnail url is there twice, but the very top one has a bad url with /files/files/ in it

i removed the extra files/ here and that seems to have solved the bad url at least, but the thumbnail can still be found twice in the meta tags

https://github.com/NodeBB/NodeBB/blob/46789910a81de8d5ecb6ca3fec6cc9f1444808e3/src/controllers/topics.js#L272

you can actually even see this issue on the community page https://community.nodebb.org/topic/15182/topic-thumbnail-testing

![image](https://user-images.githubusercontent.com/2097483/156650373-84f4a133-7b50-4333-8938-c6898646c12b.png)

note: this was fine on 1.16.x which i upgraded from

**Comment by julianlam** [comment]
Thanks, this looks to be a recent regression

**Comment by phit** [comment]
thanks!
