### ISSUE TITLE
Notifications will not be sent to some groups

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#10365]
- **NodeBB version:** v1.19.3

- **Database type:** mongo, redis, 

Groups with more than 1000 member users.
When these groups are mentioned in the post, No notifications will be sent to group members
This is not the case for groups with fewer members

**Comment by barisusakli** [comment]
We recently added this limitation https://github.com/julianlam/nodebb-plugin-mentions/blob/master/library.js#L164,
Had some issues with big groups being mentioned (200k members).
