### ISSUE TITLE
additional event logs and filters for ACP>Advanced>Events

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10405]
To keep a record of all moderations in the forum, can you please add events for these types of actions:

* topic move
* topic merge
* post move
* post accept/reject
* post edit (for content)
* post edit (for version in the history) 

if you think post edits will flood the logs, maybe only admin/moderator edits in someone else's posts can be included? 

additionally, is it possible to add "event filter" by a specific user and groups (such as global moderators)? 

<img width="302" alt="Screen Shot 2022-03-16 at 12 57 54 PM" src="https://user-images.githubusercontent.com/52054408/158645596-f0d70b1e-9a19-49ff-9f0f-929c4bddfc6b.png">

**Comment by AliCihan** [comment]
hi @barisusakli , thanks again for the new mute function, I am looking forward to muting the folks in our forum 🤣 
I guess "user mute" will also be included in the events, right? 

https://github.com/NodeBB/NodeBB/issues/8426

**Comment by barisusakli** [comment]
User mute is already logged as an event https://github.com/NodeBB/NodeBB/blob/master/src/api/users.js#L239-L245
