### ISSUE TITLE
/admin/extend/plugins#download gives blank page

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10415]
no plugin can be searched or downloaded in NodeBB 1.19.5 

https://community.nodebb.org/topic/16415/plugins-not-listed-in-1-19-5

**Comment by julianlam** [comment]
I've triggered a rebuild of the compatibility tables for nbbpm.

A couple of odd version tags got pushed up, and were causing nbbpm to crash because they were not valid semver tags.
