### ISSUE TITLE
EXIF image orientation is not respected

### ISSUE THREAD

**Issue by sadaszewski** [NodeBB/NodeBB#10417]
I have a related issue (#7095) where any image with EXIF orientation info uploaded into a post is displayed in the default landscape orientation anyway. Within the post/topic view, the CSS attribute *image-orientation* could do the trick. Then upon clicking the image, NodeBB currently just links to raw image file and Firefox by default ignores EXIF data. Images upon clicking should probably be displayed still wrapped in a web page, not directly.

**Comment by julianlam** [comment]
Sorry, what is the bug here, that the orientation is incorrect when uploaded into a post? If so, please paste a link to the troublesome image here.

I don't see an issue with opening the image in full when clicked. It's the easiest way to show the user exactly what they want -- the image.

In my opinion, third party plugins can override that behaviour if desired.

**Comment by sadaszewski** [comment]
Actually, it is perhaps easier than that. The image is displayed correctly before uploading to NodeBB. Then the EXIF data seems to actually be stripped. Downloading the image again contains the same image in wrong orientation. Currently I have only a private image I do not really wish to share but I can prepare an example later. I think that indeed I enabled EXIF info stripping but clearly the intended behavior here would be to not strip the orientation attribute, just all the others.

**Comment by sadaszewski** [comment]
I confirm that EXIF data stripping is enabled on my forum so that's it. It's a feature request then I guess to enable EXIF data stripping without the orientation attribute, so either bake in the orientation when stripping EXIF data or leave EXIF data with just the orientation attribute.

**Comment by julianlam** [comment]
A sample image would be helpful... my understanding was that we take in the orientation, orient it correctly, and then strip everything out for privacy (so the orientation data is superfluous).

**Comment by sadaszewski** [comment]
I can see in the code that indeed it is as your describe. I also could not reproduce this effect on community.nodebb.org. Guess it must be my version of sharp. I will take a closer look on my end.

**Comment by sadaszewski** [comment]
I can also confirm that disabling EXIF data stripping does not demonstrate the same effect, presumably because the image is just kept verbatim. This would confirm that the problem is in the execution path we have discussed, i.e. in stripEXIF.

**Comment by sadaszewski** [comment]
OK it's on my end. libexif was missing while building libvips from source.
