### ISSUE TITLE
Question: Should global counts match set lengths?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10422]
In the global object should the following values match the length of their corresponding sets? If they are different has something broken at some point in time and should I write a script to make them match again?

global:postCount === 'posts:pid'
global:topicCount === 'topics:tid'
global:userCount === 'users:uid'

**Comment by uplift** [comment]
It might be a script Ive written thats trying to clear purged data by for example looping to nextPid and if no longer exists calls Posts.purge but that would decrease counters when they could have already been decreased when it was actually purged but has left random bits of data that Im trying to clear up now. Ill revert and see what the state was before I ran the script. Thanls for feedback

**Comment by barisusakli** [comment]
You can also fix it with a db call like this.
```
await db.setObject('global', {
  postCount: await db.sortedSetCard('posts:pid'),
  topicCount: await db.sortedSetCard('topics:tid'),
  userCount: await db.sortedSetCard('users:joindate'), 
});
```
