### ISSUE TITLE
adding delay to the 'post queue' rejections

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10427]
It is possible to mistakenly press the "reject" button on mobile while browsing the post queue. This happened to one of our moderators, and unfortunately, the pending post vanished with no trace. 

Do you think it is possible to either create a warning with a delay just like the one in topic-move so that the action is reversed and the mistakenly rejected post is put back? (only for rejections though, since approved ones can still be deleted later if mistakenly accepted)

Or maybe a temporary rejected-post-list just like spam mailboxes where all spams are deleted automatically in 30 days (or rejected posts will be deleted from the database after 24 hours)? In 24 hours, there is still a chance to bring it back?

**Comment by barisusakli** [comment]
A bootbox.confirm might work better for this.

**Comment by ShlomoCode** [comment]
Hello, I discovered this when I upgraded my forum, and I think it's really not good - it should have been done only in a mobile view or as a configurable feature
Explanation: I allow anonymous comments, but in a queue of posts. And so there are sometimes a lot of junk comments, so I just reject everything. Now you have to click OK every time... also on the computer. It's really annoying!
There is also no other button that allows you to postpone quantitatively...
@barisusakli

**Comment by barisusakli** [comment]
Maybe we should add bulk accept reject, please open a seperate issue

**Comment by ShlomoCode** [comment]
@barisusakli OK, I [opened](https://github.com/NodeBB/NodeBB/issues/10520). But why a feature that is consumed only on a mobile phone, added to a computer as well, and without the possibility of disabling it?
