### ISSUE TITLE
Investigate why route helpers `setupPageRoute` and `setupAdminPageRoute` require `middleware` as an argument

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10509]
These two methods in `src/routes/helpers.js` require that `middleware` be passed in as the third argument. However, it seems that in all cases, this argument is supposed to be passed the module exported in `src/middleware/index.js`.

It seems redundant to do this because `src/routes/helpers.js` already requires the middleware library, so there is no need for it to be passed in.

**Comment by barisusakli** [comment]
Long time ago, the middleware lib wasn't requireable from anywhere. So it was being passed around. I think this is a left over from that era. https://github.com/NodeBB/NodeBB/commit/8f408faf4649ff87a4e6491e2473fbfa5f2efe16

**Comment by julianlam** [comment]
Hm... in that case makes sense to make that helper simpler, although removing that argument that would be a breaking change. :grimacing:

**Comment by barisusakli** [comment]
Would have to write it so it supports 4 and 5 arguments so it doesn't break existing plugins 👼🏼

**Comment by julianlam** [comment]
```
helpers.setupPageRoute = function (...args) {
  let router;
  let name;
  let middlewares;
  let controller;

  if (args.length === 4) {
    ([router, name, middlewares, controller] = args);
  else if (args.length === 5) {
    ([router, name,, middlewares, controller] = args);
  }

  // ...
```

:trollface:

**Comment by barisusakli** [comment]
need args.length === 3 as well, middlewares is optional too 😆 https://github.com/NodeBB/NodeBB/commit/4b5450853d16fe2168e6272f050628479a44d51c

**Comment by julianlam** [comment]
Well while we're at it why don't we just make controllers optional too. After all, middlewares and controllers are the same thing except controllers usually call `res.render` at the end.

Unless a middleware calls res.render :laughing:
