### ISSUE TITLE
Support Redis Sentinels for Automatic DB Failover

### ISSUE THREAD

**Issue by caiman-09** [NodeBB/NodeBB#10512]
Hi there. First of all thank you for an amazing product.

I can see that NodeBB supports Redis Clustering, as outlined [here](https://redis.io/docs/manual/scaling/) and [here](https://github.com/NodeBB/NodeBB/issues/9508)

However, for HA applications, does NodeBB support capturing the relevant sentinel information within the config file to obtain the new Redis Master DB and failover automatically?

Apologies if this is a stupid question as I'm far from an expert, but I know ioredis supports this but wasn't sure if anything extra is needed to make this work with the NodeBB config file.

**Comment by barisusakli** [comment]
It should work transparently https://github.com/luin/ioredis#sentinel.

I made some changes so it works similar to our cluster config. It should look like this 

"redis": {
   "options": {
        // options for sentinel from https://github.com/luin/ioredis#sentinel
   },
   "sentinels": [
       {"host": "", "port": ""}, 
       {"host": "", "port": ""}
    ]
]

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/82389469f602837d3376486f3cf5b05297d784c4
