### ISSUE TITLE
Configure configuration using environment variables

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10529]
Nodebb's config is saved in the config.json file.
Is there a way for the forum to take the configuration (login details of the Mongo db database for example) from an environment variable?
Thanks.

**Comment by julianlam** [comment]
Yes, [via envvar or json](https://github.com/NodeBB/NodeBB/blob/master/src/install.js#L53-L64)

**Comment by ShlomoCode** [comment]
@julianlam Is your intention to determine the values in the environment and then automatically it is inserted into Config.json? Because I couldn't have been acting according to the variable only

**Comment by julianlam** [comment]
It is used when you call `./nodebb setup`

I believe for any value in the config, you can pass in a corresponding environment variable as well.

e.g. `url=https://localhost/forum ./nodebb start`

**Comment by ShlomoCode** [comment]
@julianlam The question is is it possible to run the forum using environment variables **only**?
For example in heroku, upload the app to their git. So the changes in config.json should be included in the git history ... which also means that the repo should be kept very secure, and of course it can not be published as a public repo.
If the forum could only be run by environment variables only (https://devcenter.heroku.com/articles/config-vars), that would be great!

**Comment by julianlam** [comment]
My thinking is that it _should_ be able to. The way NodeBB works with `config.json` and envvars is... it is all consumed at the start by nconf, and so it doesn't matter _how_ it is passed in.

There _may_ be a check to make sure `config.json` actually exists... but maybe you can just save that file with contents `{}` and maybe it will work ok.

**Comment by ShlomoCode** [comment]
> There _may_ be a check to make sure `config.json` actually exists... but maybe you can just save that file with contents `{}` and maybe it will work ok.

@julianlam  I tried now, well ... the forum did not turn on (but there was no error. Just closed right back, and when I tried to run nodebb stop he wrote that the forum has already stopped)
