### ISSUE TITLE
error configuring mongodb after installing mongo on Ubuntu 20.04 

### ISSUE THREAD

**Issue by okaeiz** [NodeBB/NodeBB#10535]
I'm trying to install NodeBB on ubuntu 20.04 using its official documentation.

I have installed Node:
>>> node --version
>> v16.14.2

I have also installed MongoDB:
>>> mongo --version | head -n 1 && mongod --version | head -n 1
>> MongoDB shell version v5.0.7
>> db version v5.0.7

But when I try to configure MongoDB and set it up, I get the following error:
>>> mongo
>> MongoDB shell version v5.0.7
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1_

**Comment by julianlam** [comment]
Most likely MongoDB is not started up.

`systemctl enable mongodb` to have it start on boot
`systemctl start mongodb` to start it up.
