### ISSUE TITLE
occasional broken page (post in the left edge)

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10557]
from time to time, when I open a topic in a wide full screen, I see something like this:

<img width="1424" alt="Screen Shot 2022-04-22 at 3 22 37 PM" src="https://user-images.githubusercontent.com/52054408/166120046-3acb7369-b7b2-43e4-9bb7-a9e7eb8439dc.png">

The first post on the top of the page can be seen doubled and one of them is squeezed into the left edge of the page. How can I find the reason for this break, and how can I fix this when this happens again?

It only occasionally happens (once a week or so); and usually, when I refresh the page, it goes back to normal. But this break is reported by other members of our forum as well.

**Comment by barisusakli** [comment]
I think this is the post preview when you hover over a link. You can try disabling post previews and see if it happens again.

It might be that the post preview is being added after page navigation.

**Comment by barisusakli** [comment]
@AliCihan what version are you running?

**Comment by AliCihan** [comment]
1.19.5 
I think we can close this issue. I have to test it by disabling post previews. You might be right because we were not having this problem in the past.
