### ISSUE TITLE
a bug in the "post queue" ?

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10555]
hi @barisusakli, 

I think there is a small inconvenience (maybe a bug?) on the post queue page. When there is a new post, I see it as a notification but the notification only shows one post when I click it... (e.g. /post-queue/reply-1651336395505)

when I approve the new post, rather than showing me other posts in the queue it tells me "there are no posts in the post queue"... but this is not correct and there are other posts... I can only reach these other posts in the queue when I re-click the "post queue" from "moderator tools". But I believe this page (/post-queue) should be reachable from the page I am approving posts. 

<img width="1077" alt="Screen Shot 2022-04-30 at 1 58 01 PM" src="https://user-images.githubusercontent.com/52054408/166117100-08cb3847-5372-4825-b76f-8583aff78af0.png">

In the picture above, you can see that after approval "post queue" page is not clickable in the purple box. 

The black box claims "there are no posts in the post queue", which is wrong. When I click "/post-queue/" link, I can see all the posts waiting to be approved. 

And when I click the link in the orange box, it takes me to the settings rather than the "post queue" page... Since this is the only link on the page, involuntarily I keep clicking this link after approving the post.

**Comment by AliCihan** [comment]
I think I forgot to write above, the biggest problem is here that after approving one post from notification, it gives the impression that there are no more posts to approve. 

I have realized this after getting complaints from users that why I am not approving their posts on time :D 

Currently, I am checking /post-queue page several times to make sure :D but it should be easier 👍

**Comment by barisusakli** [comment]
Yeah, after approving/rejectinh from the link of the notification it should go to /post-queue so you see the whole list. I'll fix this.

**Comment by AliCihan** [comment]
Many thanks. 🙏
