### ISSUE TITLE
Copy only certain permissions to the offspring or all categories

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10558]
Peace.
I run a forum with categories, where the structure is that each domain has a main category, and under it sub-categories - of help, tutorials, questions, and the like.
I define the permissions, then copy them to the descendants.
But if so I see for example, that I accidentally allowed everyone to see the edit history. So I need to either fix each category individually, or copy all the settings, and then change all the exceptions again, for example the setting in the tutorials category the response is forbidden.
Is it possible to copy only one column of descendants / all categories?
For example I will only copy the definition of who will be able to view the category, for all the descendants, without copying all the permissions.

It would be nice if it would also be possible to select categories to copy ... meaning that there will be check boxes with the names of the existing categories, and I will mark where I want to copy.
Thanks!

**Comment by ShlomoCode** [comment]
Again and again I come across the critical need for such a thing. Is it in the program?

**Comment by julianlam** [comment]
I think that would unnecessarily complicate the category cloning UX.

If your categories are different enough that you are looking to customize which items/privileges to clone, then it is probably best for you to _not_ use the cloning helper buttons, and create the category yourself from scratch.

Sorry about that.

**Comment by ShlomoCode** [comment]
@julianlam And what if I want to change some permission for all categories. For example, I want to do that only registered users can watch all categories - and I have dozens of categories? Today there is no way but to pass a category and change ....
