### ISSUE TITLE
Code display goes wrong as soon as there is a change on the page

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10556]
Long code block, displayed correctly with line drop:
![image](https://user-images.githubusercontent.com/78599753/166119275-592f5ea7-2ac8-4a48-afd8-76b7691f7f3e.png)
As soon as something changes on the page - for example, a new post is sent on the current topic, or an existing (other) post is edited, the line drop goes wrong and the code is displayed as one line:
![image](https://user-images.githubusercontent.com/78599753/166119287-7ad7db5c-889b-494f-824f-1fb87b90613e.png)

And only after this refresh is it displayed back properly.
Versions where the glitch appeared:
1.19.6, 1.19.5 and more
Forum language: Hebrew

**Comment by ShlomoCode** [comment]
@barisusakli @julianlam Is not this a bug? 🤔 Maybe need more information? I will happily deliver

**Comment by barisusakli** [comment]
I couldn't reproduce this, does this happen on community.nodebb.org as well?

**Comment by ShlomoCode** [comment]
@barisusakli No... but I've already encountered this in some NodeBB forums
what could it be?

**Comment by barisusakli** [comment]
Not sure, could be a plugin, do you have a link to a forum that has this issue?

**Comment by ShlomoCode** [comment]
@barisusakli I found - the error only occurs when configured like this in a markdown in ACP (`/admin/plugins/markdown`):
![image](https://user-images.githubusercontent.com/78599753/167013833-4b04f9a9-8cab-4b24-a5cd-c0a557ee293a.png)

(markdown is a plugin that comes by default...)

**Comment by julianlam** [comment]
> Forum language: Hebrew

Does this only occur with Hebrew language enabled?

**Comment by barisusakli** [comment]
Was able to reproduce this on english
