### ISSUE TITLE
share post options for mobile version

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10566]
Currently, we can share posts on Facebook and on Twitter by default. However, since most of the users are using mobile devices to read forums (that is the case for us, and I believe it is the same for the majority), I believe adding 

* Share on Telegram
* Share on Whatsapp

options would facilitate users' work. Of course, this addition could be added to the mobile version only (or both since both Telegram and Whatsapp have official desktop apps). 

ps. I know there were plugins for this but unfortunately, they are not working properly for us.

**Comment by AliCihan** [comment]
additionally, on mobile, there is no easy way to get a link for a specific post. Several users told me they first click "share on twitter" option and get the link of the post from there and then share the link in other apps (especially Telegram). 

So, in addition to the two options above, I believe the "copy post link" option can be added to the post options?

**Comment by julianlam** [comment]
For that last part -- it's a bit of a hidden feature, I suppose, but the post timestamp itself is the permalink to the post.

Long-pressing on it on mobile should allow you to copy the direct link to the post.

**Comment by AliCihan** [comment]
hi @julianlam , unfortunately, this long-pressing trick does not work on ios safari pwa apps. 

That is how I get the post link on the desktop, from timestamp :) but I use the forum added to the Home Screen as Safari PWA (I guess this is the correct terminology). And long pressing does not show any options, unfortunately. 

However, I can confirm this works if I use a regular Safari browser. 

I just saved nodebb community forum as an app shortcut to the home screen, and it does not work there either. So, I can tell it is not related to our own forum.

**Comment by julianlam** [comment]
Ah, I suppose that is a feature:tm: of PWAs, isn't it... that might be the same on Android as well.

Adding in a link to copy the permalink to clipboard is a good idea nevertheless.

**Comment by AliCihan** [comment]
thanks 👍 I too think it would be a nice addition.

**Comment by julianlam** [comment]
@AliCihan Thanks for the reminder
