### ISSUE TITLE
NodeBB 2.0.0: WebInstaller does not exit process after installation

### ISSUE THREAD

**Issue by nilsramsperger** [NodeBB/NodeBB#10586]
# Situation
I start the application via `node app.js`. On first run, the WebInstaller is started.
After completing the installation the process was exited on old versions (1.19.x). Now it stays alive.
Clicking the "Launch NodeBB" Button after installation has no effect.

# Expected behaviour
The NodeBB process terminates after installation

# Observed behaviour
The  NodeBB process stays alive after installation

# Consequences
This behaviour mitigates the automatic relaunch of my containerized installation, thus requiring a manual restart.
Even on a bare metal installation, I need to kill the process and start it again.

Greets
Nils

**Comment by barisusakli** [comment]
That's weird does it hit this line https://github.com/NodeBB/NodeBB/blob/master/install/web.js#L219?

**Comment by nilsramsperger** [comment]
As far as I understand the sources, the process will exit on issuing a POST on /launch.
The network tab in my browser-tools tell me, that this request is **not** send clicking the button.

**Comment by barisusakli** [comment]
Yeah it should exit after the POST. I will take alook.

**Comment by nilsramsperger** [comment]
Now the installer works as expected. Even the work-in-progress-indicators and the DB properties Inputs are back.
Well done.
