### ISSUE TITLE
Add mute user action to flag details user actions 

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10585]
Noticed recently you've added Mute functionality which allows a user to be logged in but removes there posting privileges'. Is there any documentation about this that answer the below questions or code I've missed? (Great feature to add by the way 👍)

- How does a user know they've been muted? Is there a notification sent on mute with details?
- Should this functionality be in the User Actions on Flag Detail page (permissions allowing)

**Comment by barisusakli** [comment]
Open a new issue for that
