### ISSUE TITLE
nodebb setup fail:Dependencies outdated or not yet installed.

### ISSUE THREAD

**Issue by Jaccckx** [NodeBB/NodeBB#10587]
- **NodeJS version:v16.15.0

	i was following the  tutorial to install Nodebb.
        Link：https://docs.nodebb.org/installing/os/ubuntu/
        but  something is  wrong with the step "sudo apt-get install -y git"  at first
        And something is wrong with the step: './nodebb setup'" secondly

 git-daemon-run : Conflicts: git-daemon-sysvinit but 1:2.25.1-1ubuntu3.4 is to be installed
 git-daemon-sysvinit : Conflicts: git-daemon-run but 1:2.25.1-1ubuntu3.4 is to be installed
 golang-github-dnephin-cobra-dev : Conflicts: golang-github-spf13-cobra-dev
E: Unable to correct problems, you have held broken packages.

- **What you expected:**

1. > sudo apt-get install -y git
The following packages have unmet dependencies:
 git-daemon-run : Conflicts: git-daemon-sysvinit but 1:2.25.1-1ubuntu3.4 is to be installed
 git-daemon-sysvinit : Conflicts: git-daemon-run but 1:2.25.1-1ubuntu3.4 is to be installed
 golang-github-dnephin-cobra-dev : Conflicts: golang-github-spf13-cobra-dev
E: Unable to correct problems, you have held broken packages.
2. > ./nodebb setup
lighthouse@VM-4-6-ubuntu:~$ cd nodebb/.
lighthouse@VM-4-6-ubuntu:~/nodebb$ ./nodebb setup
Dependencies outdated or not yet installed.
Installing them now...

npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code 1
npm ERR! path /home/lighthouse/nodebb/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-linux-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: socket hang up

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lighthouse/.npm/_logs/2022-05-06T18_17_56_310Z-debug-0.log
Error installing dependencies!
message: Command failed: npm install --production
stdout: null
stderr: null
/home/lighthouse/nodebb/src/cli/package-install.js:82
                throw e;
                ^

Error: Command failed: npm install --production
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at Object.installAll (/home/lighthouse/nodebb/src/cli/package-install.js:73:9)
    at Object.<anonymous> (/home/lighthouse/nodebb/src/cli/index.js:62:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 26975,
  stdout: null,
  stderr: null
}

**Comment by julianlam** [comment]
That's an odd set of errors... looks like you'll want to resolve the `git` installation issue first, which is outside the scope of NodeBB.

It looks like the installation of the `sharp` dependency failed. What happens if you try to run `npm i --production` again?

**Comment by Jaccckx** [comment]
thank u very much.after i fixed the problem with git.i exec the 'npm i --production'.everything is good

**Comment by Jaccckx** [comment]
> That's an odd set of errors... looks like you'll want to resolve the `git` installation issue first, which is outside the scope of NodeBB.
> 
> It looks like the installation of the `sharp` dependency failed. What happens if you try to run `npm i --production` again?

thank u very much.after i fixed the problem with git.i exec the 'npm i --production'.everything is good
