### ISSUE TITLE
cannot uninstall scoped packages from the ACP

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#10582]
makes a request to `Cannot GET /api/v1/plugins/@nodebb/nodebb-plugin-reactions`

https://github.com/NodeBB-Community/nodebb-plugin-reactions/issues/8

**Comment by barisusakli** [comment]
@julianlam seems to be caused by this https://github.com/NodeBB/NodeBB/commit/5ddf70221c8a0a9a510b70eb49b55ee245106de5

**Comment by julianlam** [comment]
oooh, that's a funny one... express router doesn't catch it because of the slash. Let me try escaping it :thinking:

**Comment by barisusakli** [comment]
`isValidPackage = /^nodebb-(plugin|theme|widget|rewards)/,` this check in package-manager needs to be updated to handle scoped packages as well

**Comment by julianlam** [comment]
Installation is fine though?

**Comment by barisusakli** [comment]
Should fail if installed from acp I think since it uses the same code.
