### ISSUE TITLE
user.deleteAccount doesn't work

### ISSUE THREAD

**Issue by sy-data** [NodeBB/NodeBB#10583]
- **NodeBB version:**
- 1.19.x  
- **NodeJS version:**
- 14

- **Installed NodeBB Plugins:**
- nothing 
- persona theme

- **Database type:** 
- mongo
- **Database version:**
-  MongoDB 5.0.6 Community 

- **Exact steps to cause this issue:**
1. http://localhost:4567/user/:user/edit
2. $('#deleteAccountBtn').click()
3. malfunction

- **What you expected:**
1. Nodebb>src>socket.io>user.js 
2. no function there

- **What happened instead:**

**Comment by sy-data** [comment]
relevant:
Nodebb/public/src/client/account/edit.js
line 61 
function handleAccountDelete()

Nodebb/src/socket.io/user.js
**there is no function** 
SocketUser.deleteAccount = async function( ) 

Nodebb/src/user/delete.js
line 86
User.deleteAccount = async function (uid) {

**Comment by sy-data** [comment]
@barisusakli please, i need hot fix. or Function arguments and return values  for SocketUser.deleteAccount = async function( ) that you will update later

**Comment by barisusakli** [comment]
@sy-data see the changeset https://github.com/NodeBB/NodeBB/commit/5e82cf23c66d99cc844e01e0a51619e90ffd0fc7. Updating the socket.emit with the api.del method will fix this issue.
