### ISSUE TITLE
 build error NodeBB 2.0 warn: [meta/templates] Partial not loaded: partials/topic/browsing-users.tpl

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#10590]
NodeBB version 2.0
NodeJS version 18.1

I get the following error when running `./nodebb build`:
 ```warn: [meta/templates] Partial not loaded: partials/topic/browsing-users.tpl```

**Comment by uplift** [comment]
I'm also getting this error on 1.19.7

**Comment by julianlam** [comment]
Added an empty partial so NodeBB won't complain. The partial gets overwritten by the browsing-users plugin.
