### ISSUE TITLE
Reverse Select button in Categories/Recent

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10602]
I find it quite useful to have an option on the page of the Recent/Unread topics, and in the category pages, an option to make the choice - meaning I can select a few topics, say 3, and make the choice - then all the rest except those 3, lock, or move, or Delete, etc.
Thanks!
By the way: this option exists for example in Windows Explorer, and also in gmail there is a button Select all, then you uncheck for some :)

**Comment by ShlomoCode** [comment]
It will also be useful for marking topics read - for example not everything interests me, except for a few individuals in random categories. So I make a reversal of choice, and make everything else "read"...

**Comment by julianlam** [comment]
I think it may be difficult to come up with a UX for this that works well... we don't have a header on our topic lists, so there is no convenient place to put a "select all"-type checkbox.

However, you can select the first topic, and then shift-click the last topic. Every topic in between will be selected. Perhaps that will be an acceptable workaround?

**Comment by ShlomoCode** [comment]
@julianlam It's really nice the trick with shift! I didn't know
Maybe do it with ctrl + a, like in Google Drive?
