### ISSUE TITLE
window.open doesn't work properly in nodebb

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#10609]
below code works fine on other sites, but on nodebb it prints true on the first tick of the interval
```
const newWindow = window.open('https://google.com', '_blank', 'width=200,height=200,scrollbars=no,status=no');
console.log('window.closed 1', newWindow.closed); // prints false as expected
if (newWindow) {
    const timer = setInterval(function () {
        console.log('window.closed 2', newWindow.closed); // prints true
        if (newWindow.closed) {
            clearInterval(timer);
            console.log('window.closed 3', newWindow.closed); // prints true
        }
    }, 1000);
}
```
It should keep printing `false` until the window is closed

**Comment by pitaj** [comment]
Sounds like a CORS sorta thing. Where else did you try it?

**Comment by barisusakli** [comment]
works fine on
github.com
google.com
stackoverflow.com
nodebb.org (the main site) https://nodebb.org/

it's weird cuz it even fails on the /debug/test route which doesn't load anything

**Comment by hello-smile6** [comment]
Stepping through it with `debugger`, it looks like the browser initializes it with `closed` as `false`. Is it redefined as `true` later?

**Comment by hello-smile6** [comment]
It may be caused by NodeBB, `nodebb.min.js` is running when it is set to `true`.

**Comment by barisusakli** [comment]
Yeah when it is first created it is false, which is correct. But it is set to false by something before the timer ticks. It should only be set to true when the window is actually closed by the user.  I couldn't find what sets it to true.

**Comment by hello-smile6** [comment]
> Yeah when it is first created it is false, which is correct. But it is set to false by something before the timer ticks. It should only be set to true when the window is actually closed by the user. I couldn't find what sets it to true.

It seems to be the browser, because an `about:blank` window is `closed: false`, but a cross-origin window is `closed: true`.

**Comment by julianlam** [comment]
Yeah I'll echo that it's probably a CORS issue. Popups loading cross-origin sites have `window.opener` as `null`. Likewise, the parent cannot interact with the child.

**Comment by hello-smile6** [comment]
> For what it's worth, for me it prints `true` on the first tick on Github.com. Haven't tried other sites.

It could be CSP.
