### ISSUE TITLE
postIndex will never be 'unread' in topics controller

### ISSUE THREAD

**Issue by cortona-mwersig** [NodeBB/NodeBB#10607]
In [controllers/topics.j](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/topics.js)s the postIndex variable will never be 'unread'

postIndex is set in [line 32](https://github.com/NodeBB/NodeBB/blob/70ad4a5222c3c99077e08e6bda73c672ebfa2193/src/controllers/topics.js#L32):
```js
let postIndex = parseInt(req.params.post_index, 10) || 1;
```
in[ line 65](https://github.com/NodeBB/NodeBB/blob/70ad4a5222c3c99077e08e6bda73c672ebfa2193/src/controllers/topics.js#L65) it will be checked for 'unread':
```js
if (postIndex === 'unread') {
	postIndex = await topics.getUserBookmark(tid, req.uid);
}
```

**Comment by barisusakli** [comment]
@cortona-mwersig thanks for reporting
