### ISSUE TITLE
Posts.getPostsFields does not return cid

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10608]
Hello, I'm trying to use a plugin for nodebb in the following code or so to get details for a post - who created it and in which category:
```
Topics = require.main.require('./src/topics');
Posts.getPostsFields([25], ['cid', 'uid', 'pid'])
```
But the output is:
`[{ cid: null, uid: 1, pid: 25 }]`
That is, no cid is returned.
Is this correct? Is not this the method I should use to get the important details of a particular posts?
Would appreciate help. Thanks

**Comment by barisusakli** [comment]
Post objects don't store the category id, it is part of the topic object. You need to make an extra call to load it or use `posts.getCidByPid`.
```
const topics = require.main.require('./src/topics');
const posts =  require.main.require('./src/posts');
const postData = await Posts.getPostFields(25, ['tid', 'uid', 'pid']);
const cid = topics.getTopicField(postData.tid, 'cid');
```

or
```
const cid = await posts.getCidByPid(25);
```
