### ISSUE TITLE
v2.0.0 Build error after upgrading from 1.8

### ISSUE THREAD

**Issue by mahmudz** [NodeBB/NodeBB#10612]
- **NodeBB version:** 2.0
- **NodeBB git hash:** 6e011b8ff5f23bd62c69fc916d486b983f07499c
- **NodeJS version:** 14.19
- **Installed NodeBB Plugins:** 
  - nodebb-plugin-2factor@4.0.0 (installed, disabled)
  - nodebb-plugin-composer-default@8.0.0 (installed, disabled)
  - nodebb-plugin-composer-quill@2.3.1 (installed, enabled)
  - nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
  - nodebb-plugin-emoji@4.0.2 (installed, enabled)
  - nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
  - nodebb-plugin-markdown@10.0.0 (installed, disabled)
  - nodebb-plugin-mentions@3.0.10 (installed, enabled)
  - nodebb-plugin-question-and-answer@0.12.23 (installed, enabled)
  - nodebb-plugin-s3-uploads-etr@0.6.1 (installed, enabled)
  - nodebb-plugin-session-sharing@5.1.6 (installed, enabled)
  - nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
  - nodebb-rewards-essentials@0.2.1 (installed, enabled)
  - nodebb-theme-lavender@6.0.0 (installed, disabled)
  - nodebb-theme-persona@12.0.1 (installed, enabled)
  - nodebb-theme-slick@2.0.0 (installed, disabled)
  - nodebb-theme-vanilla@12.1.17 (installed, disabled)
  - nodebb-widget-essentials@6.0.0 (installed, enabled)
- **Database type:** mongo
- **Database version:** v4.4.13

- **Exact steps to cause this issue:**
    - Installed v1.18 a few days ago
    - Checked out to v2.0.0 branch
    - Ran ./nodebb upgrade
    - Site ran successfully & with issues, see attached video

#### Build Logs

```
ERROR in ./build/public/scripts-client.js 2672:2-2692:4
Module not found: Error: Can't resolve 'composer' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/autocomplete' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/categoryList' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/drafts' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/formatting' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/preview' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/resize' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/scheduler' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/tags' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/scripts-client.js
Module not found: Error: Can't resolve 'composer/uploads' in '/home/ubuntu/apps/nodebb/build/public'

ERROR in ./build/public/src/client/chats.js
Module not found: Error: Can't resolve 'composer/autocomplete' in '/home/ubuntu/apps/nodebb/build/public/src/client'

ERROR in ./build/public/src/modules/emoji-dialog.js
Module not found: Error: Can't resolve 'composer/controls' in '/home/ubuntu/apps/nodebb/build/public/src/modules'

ERROR in ./build/public/src/modules/emoji.js 34:57-110
Module not found: Error: Can't resolve 'composer/formatting' in '/home/ubuntu/apps/nodebb/build/public/src/modules'

ERROR in ./build/public/src/modules/persona/quickreply.js
Module not found: Error: Can't resolve 'composer/autocomplete' in '/home/ubuntu/apps/nodebb/build/public/src/modules/persona'

ERROR in ./build/public/src/modules/topicThumbs.js 65:10-68:12
Module not found: Error: Can't resolve 'composer' in '/home/ubuntu/apps/nodebb/build/public/src/modules'

webpack 5.72.0 compiled with 15 errors in 58758 ms
2022-05-14T13:19:07.353Z [4567/139753] - info: [build] Asset compilation successful. Completed in 69.107sec.
```

**Comment by barisusakli** [comment]
I think quill composer needs updating to 2.0.0, can you try disabling quill and enabling composer-default? See it builds after that.

**Comment by mahmudz** [comment]
@barisusakli If i disable quill & re-enable composer-default. It builds fine.
