### ISSUE TITLE
Unable to create/list API tokens

### ISSUE THREAD

**Issue by bugsounet** [NodeBB/NodeBB#10611]
Hi, I'm not able to create / list any tokens for using NodeBB API

using: NodeBB v2.0.0

I have this error on console:

![image](https://user-images.githubusercontent.com/30669209/168423337-140aab42-0a7f-4d60-a8e7-d12ab5193339.png)

Note: I think, it's related to an deleted user, but 100% not deleted from database and on final, Nodebb don't find token of the deleted user

any suggestion  ?

Thanks
@bugsounet

**Comment by barisusakli** [comment]
@bugsounet thanks for reporting

**Comment by bugsounet** [comment]
Hi, I don't know why it's not patched again in v1.19.7/v1.19.8?
The problem is actually the same

**Comment by barisusakli** [comment]
I cherrypicked this commit to 1.19.x branch https://github.com/NodeBB/NodeBB/commit/37c1fa17a9679309b3438956073c16cadbb68af9
