### ISSUE TITLE
Expanding Admins & Mods panel...

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10610]
Hello, 

In ACP > Manage > Admins & Mods... 

Some time ago, we were able to see all moderators as one page; however, for some time we have to pick an individual category to manage. We have ~95 categories, sub-categories, and sub-sub-categories... the more people we are assigning as moderators, the more time it takes to manage this section. Currently, it is taking more than 5 minutes to check categories one by one :D 

<img width="845" alt="Screen Shot 2022-05-13 at 4 23 18 PM" src="https://user-images.githubusercontent.com/52054408/168384304-53ef66c4-3859-4a57-a4b5-377e75f417ac.png">

I do not know if this change was for a technical reason, but I would like to ask for a better panel... If it is not possible to bring back the old one, can we at least have it category by category? so, when I pick one major category, all sub and sub-sub categories can appear at once... or maybe the old version where we can see everything, but it does not come automatically... It only shows up if we have to click a button?

**Comment by barisusakli** [comment]
Changed it so it looks like this 
![image](https://user-images.githubusercontent.com/2583394/168402552-7ff6e7da-ea90-4c9a-91c8-6839ffdc0611.png)

Clicking subcategories will display the subcategories of that category.

![image](https://user-images.githubusercontent.com/2583394/168402564-5917336d-bd84-4d42-a782-52286949403c.png)

We don't display the entire category tree as it becomes really slow when you have a lot of categories.

**Comment by AliCihan** [comment]
@barisusakli thanks a lot. Yeap, I assumed there was a technical reason for the change since the new version was not very practical... but this change you made will definitely make it better than the current version, it was taking a lot of time to make any change, and be sure of it :) Thanks.
