### ISSUE TITLE
Creating a user in Mongo 

### ISSUE THREAD

**Issue by okaeiz** [NodeBB/NodeBB#10629]
I'm following the official documentation for installing NodeBB on Ubuntu Server 20.04
When I try to create a user in Mongo, it outputs the following error:

What I write: > ```
db.createUser( { user: "admin", pwd: "<Enter a secure password>", roles: [ { role: "root", db: "admin" } ] } )
And I change the pwd value.
```

What I get: ```
uncaught exception: Error: couldn't add user: command createUser requires authentication :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
```

**Comment by pitaj** [comment]
This isn't the place for tech support, please take all further questions to the community forum: https://community. nodebb.org

That said, I think this will help you:
https://www.mongodb.com/community/forums/t/cant-add-user-after-creating-admin-user-createuser-requires-authentication/5896
