### ISSUE TITLE
Rebuild & Restart buttons are not working

### ISSUE THREAD

**Issue by mahmudz** [NodeBB/NodeBB#10620]
- When Clicked Rebuild Button
![When Clicked Rebuild Button](https://user-images.githubusercontent.com/22455598/168441916-08afb11c-cff8-426f-8c27-cb05661a8f8e.png)

- When Clicked Restart Button
![When Clicked Restart Button](https://user-images.githubusercontent.com/22455598/168441945-233b63d0-11ed-49c6-ab5d-4a6447251e04.png)

**Comment by barisusakli** [comment]
@mahmudz thanks for reporting
