### ISSUE TITLE
move Post reply does not update its association with the post

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10622]
When I comment on a particular post, using the "Comment" button below each post:
![image](https://user-images.githubusercontent.com/78599753/168448966-351e2156-9e49-4a0f-b4ba-f73a8c151ebb.png)
And then moves the post I created to another topic, the topic itself is moved, but below the post I commented on - there is such a mark:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/78599753/168448976-da382ee8-b8e2-4226-adfe-976d2c649389.png">
That when I expand it - the post is displayed:
![image](https://user-images.githubusercontent.com/78599753/168448991-1ccd5edf-2ab1-471b-910d-88814d7326db.png)
This is even though he is no longer on this topic...
Nodebb version: 1.18.6
Database: MongoDB

**Comment by ShlomoCode** [comment]
Now I think this may be a desirable behavior? I can understand that the target post shows that it is in response to a certain post, but I think that if you move a post to another topic, it should not be displayed in the original topic in any way...

**Comment by barisusakli** [comment]
Yeah this was intended, if you don't want this behavior you can clear the association when the post is moved in `action:post.move`

```
myPlugin.actionPostMove = async (hookData) => {
  const { pid } = hookData.post;
  const toPid = await posts.getPostField(pid, 'toPid');
  if (parseInt(toPid, 10)) {
    await db.deleteObjectField(`post:${pid}`, 'toPid');
    await db.sortedSetRemove(`pid:${toPid}:replies`, pid);
    const replyCount = await db.sortedSetCard(`pid:${toPid}:replies`);
    await posts.setPostField(toPid, 'replies', replyCount);
  }
}
```
