### ISSUE TITLE
NodeBB Admin Timeout

### ISSUE THREAD

**Issue by AkanshDivker** [NodeBB/NodeBB#10632]
Hi,

We're currently trying to upgrade our forum from vBulletin 4 to NodeBB. We're trying to make use of this migration plugin (https://github.com/akhoury/nodebb-plugin-import) which requires an initial version of NodeBB v1.12.1. The plugin works as intended, but our forum has over 100GB of data that needs to be migrated. As you can imagine, this process will take quite a while to finish. The issue we're encountering is with the admin timeout on NodeBB, which causes the plugin to stop working when it occurs. 

We have tried disabling the timeout to the best of our knowledge in the NodeBB code, but it had no effect. We also tried staying active on the page or refreshing the page periodically, but the timeout was still occuring. We're out of ideas on how to get around the timeout issue which forces the admin logout, which in turn stops the plugin from completing the migration.

Would appreciate a solution that details on how to actually disable the timeout, if possible. Again, the issue we are facing is not with the plugin as it works as intended. The NodeBB timeout causing the logout is just interrupting it.

Thanks!

- **NodeBB version:** 1.12.1
- **NodeJS version:** 16.15.0
- **Database type:** mongo
- **Plugin**: https://github.com/akhoury/nodebb-plugin-import

**Comment by julianlam** [comment]
Which part of the code did you attempt to comment out?

**Comment by AkanshDivker** [comment]
I guess I should have been a bit more clear, I apologize for that. We already tried changing the setting in ACP but we had no success with that. Restarted and rebuilt NodeBB, as well as logged out and logged in again. It was still timing out. Another correction, seems like we didn't try to comment out any code in NodeBB as of yet.

Is there any other way to get around this or something we might be missing? Changing the settings in ACP seem to have no effect.
