### ISSUE TITLE
Infinite startup loop after upgrade to 2.0.0

### ISSUE THREAD

**Issue by klauso** [NodeBB/NodeBB#10634]
- **NodeBB version:** 2.0.0
- **NodeJS version:** 16.14.2
- **Installed NodeBB Plugins:** 
        * nodebb-plugin-2factor@4.0.0 (installed, disabled)
        * nodebb-plugin-composer-default@8.0.0 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
        * nodebb-plugin-embed@3.0.19 (installed, enabled)
        * nodebb-plugin-emoji@4.0.2 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-emoji-apple@2.0.5 (installed, enabled)
        * nodebb-plugin-markdown@10.0.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.10 (installed, enabled)
        * nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-persona@12.0.1 (installed, enabled)
        * nodebb-theme-slick@2.0.0 (installed, disabled)
        * nodebb-theme-vanilla@12.1.17 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)
- **Database type:** mongo
- **Database version:** 4.4.10

- **Exact steps to cause this issue:**

1. I upgraded to NodeBB 2.0.0
2. After the update, the forum didn't start up anymore; it was stuck in an infinite loop.

The relevant excerpt of the log is this:
```
May 20 15:39:20 G[2/5] Resolving packages...
May 20 15:39:22 GGGGGGGGGGGGGGGGGGGGGKGerror Could not write file "/app/code/yarn-error.log": "EROFS: read-only file system, open '/app/code/yarn-error.log'"
May 20 15:39:22 Gerror An unexpected error occurred: "https://registry.yarnpkg.com/nodebb-plugin-twitter-klaus: Not found".
May 20 15:39:22 Ginfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
``` 

3. The bug was triggered by a Twitter plugin I was using, which is a tiny modification of the [Community Twitter plugin](https://github.com/NodeBB-Community/nodebb-plugin-twitter).
4. I had to completely remove and reinstall everything afterwards; even a downgrade from a backup to an older version did not get rid of the loop.

**Comment by julianlam** [comment]
Can you share the entire startup log, including one invocation of the loop? It sounds like a call to yarn is being made, and exiting with an error because of your plugin.

It looks like `nodebb-plugin-twitter-klaus` is not published on npm. You can either do that, or use `npm link` to install it onto your NodeBB.

**Comment by klauso** [comment]
Yes, `nodebb-plugin-twitter-klaus` is not published. 

I'm not sure whether it makes a difference, but I'm using NodeBB via Cloudron 7.2.0.

Unfortunately I can't provide a full log at the moment. I should have saved it. But now I have reinstalled the forum and I'd rather not destroy it again. I was hoping that the information above would be sufficient to find the cause of the problem. It looks like some kind of file permission issue to me. A plugin that isn't registered surely shouldn't lead to a startup loop.

**Comment by julianlam** [comment]
I think the fix here is that `twitter-klaus` should not be in your `package.json`. Yarn is trying to install it, but cannot find it, so it aborts the install.
