### ISSUE TITLE
Menus don't function on firefox mobile / small window on firefox desktop

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#10642]
- **NodeBB version:**  v2.0.0
- **NodeBB git hash:** 6e011b8ff5f23bd62c69fc916d486b983f07499c
- **NodeJS version:** v16.15.0
- **Installed NodeBB Plugins:** 
 	* nodebb-plugin-2factor@4.0.0 (installed, disabled)
	* nodebb-plugin-category-notifications@3.1.1 (installed, enabled)
	* nodebb-plugin-composer-default@8.0.0 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
	* nodebb-plugin-email-blacklist@1.1.1 (installed, enabled)
	* nodebb-plugin-embed@3.0.19 (installed, enabled)
	* nodebb-plugin-emoji@4.0.2 (installed, disabled)
	* nodebb-plugin-emoji-android@3.0.0 (installed, disabled)
	* nodebb-plugin-gdpr@1.1.1 (installed, enabled)
	* nodebb-plugin-github-embed@0.7.9 (installed, enabled)
	* nodebb-plugin-google-analytics@0.6.2 (installed, enabled)
	* nodebb-plugin-gravatar@2.3.0 (installed, enabled)
	* nodebb-plugin-markdown@10.0.0 (installed, enabled)
	* nodebb-plugin-mentions@3.0.10 (installed, enabled)
	* nodebb-plugin-night-mode@1.0.7 (installed, enabled)
	* nodebb-plugin-recent-cards@2.0.22 (installed, enabled)
	* nodebb-plugin-soundpack-default@2.0.1 (installed, disabled)
	* nodebb-plugin-spam-be-gone@1.0.0 (installed, enabled)
	* nodebb-rewards-essentials@0.2.1 (installed, disabled)
	* nodebb-theme-lavender@6.0.0 (installed, disabled)
	* nodebb-theme-persona@12.0.1 (installed, enabled)
	* nodebb-theme-slick@2.0.0 (installed, disabled)
	* nodebb-theme-vanilla@12.1.17 (installed, disabled)
	* nodebb-widget-essentials@6.0.0 (installed, enabled)
- **Database type:** mongo
- **Database version:** v4.2.20
- **Exact steps to cause this issue:**
Load Firefox (v100 on desktop or mobile (tested Firefox v100 on Ubuntu 22.04 and Android 10) 
Log in to https://retropie.org.uk/forum
On desktop resize to mobile size so there is a top left and top right menu.
Click either menu
- **What you expected:**
The menus with Unread / recent posts and user profile to appear.
- **What happened instead:**
Nothing - the buttons "press" and no menus appear.

Screenshot from Firefox on Ubuntu 22.04 after pressing the top left menu icon.

![nodebb](https://user-images.githubusercontent.com/5365574/170168581-6a308db2-9a62-48a1-9f2f-ce5c72feb4dd.png)

**Comment by sweetppro** [comment]
I have this issue as well, everything works well on Chrome based browsers...
but on Firefox and Safari the mobile menu does not work after a page reload.

If I empty the cache, the menus work until the page is refreshed manually,
then they don't work until I empty the cache and reload.

NodeBB v2.0.1
Persona theme v12.0.4
Paper Skin

**Comment by barisusakli** [comment]
Can you guys try something, put a console.log on this line https://github.com/NodeBB/nodebb-theme-persona/blob/master/public/persona.js#L15 and see if it gets triggered when the mobile menu doesn't work.

**Comment by barisusakli** [comment]
Seems like on firefox `action:app.load` if fired before persona theme adds the hook listener.
