### ISSUE TITLE
format of the link that is added to the posts? 

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10640]
I am not sure if this is intended or a bug? 

when the link does not start with HTTPS, the forum turns the link as an extension to the forum link... however if it starts with HTTPS, then it is taking you to the correct site...  

you can see the problem here in the first post:
https://community.nodebb.org/topic/16499/enter-the-nodebb-meatgistics-giveaway

Facebook link works fine but the Instagram link takes you to here: https://community.nodebb.org/topic/16499/instagram.com/p/CdoNVHhO56U/?igshid=YmMyMTA2M2Y=

**Comment by barisusakli** [comment]
Not sure if it is intended, if you don't put the protocol it treats as local link. I fixed the link on the post you linked.

**Comment by AliCihan** [comment]
> Not sure if it is intended, if you don't put the protocol it treats as local link. I fixed the link on the post you linked.

what is the use case of this local link? can you give an example, please? because link is added to the end of the topic link... 

you can close the issue if there is no problem. I was not sure if this is intended or a bug...

**Comment by julianlam** [comment]
It's not an explicit thing we do, it is matching the behaviour of the browser.

If you craft an anchor thusly: `<a href="instagram.com/whatever">test</a>`, the link will be `https://yourcurrentpage.com/instagram.com/whatever`

The default assumption is that in the absence of a protocol, that it be treated as a relative path.
