### ISSUE TITLE
Orphaned files when cancel post

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#10659]
NodeBB 2.0.1 (may be this is the same behaviour as previous releases)

When I click **Reply** o create a **New Thread**, in the composer window I added a file, whatever file type (image, pdf, etc). But then I cancel the post or reply. The file still in `public/uploads/files`.

This file should be delete if I cancel the reply or post. Another idea (better) can be something like a cron job that explore for orphaned files and then delete, or marked for a manual delete in ACP.

Regards!

EDIT: The problem with cron job is if it running at the same time I writing a post with a file, but no posted yet, the job will delete the file. A workaround for this may be check the timestamp of the file, and evaluate is it is older than ex. 24hs, and it is orphaned, then delete.

**Comment by julianlam** [comment]
Ah yes, this brings to mind a concern I had when I built out the post association logic...

While everything in `uploads/files` _should_ be an upload in a post, that is not always strictly the case. So I put in an "orphaned" tag if I don't have a post association, but that doesn't necessarily mean that it is not used elsewhere.

Take—for example—our own community site. We have this file: https://community.nodebb.org/assets/uploads/files/porpoise.jpg

I have no idea why it's there, or why it was uploaded to this folder, but maybe it is linked to from outside NodeBB...

**The point is**, I can't just unilaterally make a decision to add a cronjob to empty files in this folder that are orphans, because that may have unintended consequences.

**Comment by julianlam** [comment]
However, this does get me thinking that a daily job to clear old uploads could still be added, but enabled only on new installs.

Old installs can enable it, but would need to make that determination for themselves based on their specific context.

**Comment by NormandoHall** [comment]
@julianlam agree with you. There is another side issue with this: the resized images leaves the original ones orphaned, at least as I know.

Thank for the great work!

**Comment by ShlomoCode** [comment]
@julianlam @NormandoHall What about files / pictures that are uploaded to chat? I'll send someone a screenshot, and he will not have time to see it and it will be deleted... :|

**Comment by NormandoHall** [comment]
@ShlomoCode @julianlam I think the files should be uploaded with a default prefix on the filename, indicating that it is not committed yet (for example when the chat message has not been sent yet, or the post has not been published yet) and take that file as a preview only (eg `preview-image.jpg`). When that chat message is sent or the post is published, the file is renamed to `image.jpg` by removing the prefix `preview-`.

I think it's a way to keep the orphaned file folder clean. In my case, I have over 200,000 files, and I'm pretty sure half of them aren't linked to anything within the forum. Also orphaned images `image.jpg` from reduced `image-resize.jpg`. Both one still exists in the folder.

**Comment by ShlomoCode** [comment]
It seems to me that at the moment what is sent in the chat, is considered "orphan". First of all it needs to change... :)

**Comment by julianlam** [comment]
Hmm... That's a point I hadn't considered, perhaps chat images should be saved elsewhere.

Nevertheless at least for now the default is 0, or disabled.

**Comment by julianlam** [comment]
@NormandoHall as for resized images, they should both be associated with the post. I'll see if I can account for that.

When you click on the resized photo, it should load the full resolution photo.

**Comment by julianlam** [comment]
> There is another side issue with this: the resized images leaves the original ones orphaned, at least as I know.

@NormandoHall Is this still an issue? The logic seems to account for resized uploads already:

![image](https://user-images.githubusercontent.com/923011/174363789-2bcda683-cadc-47e6-a627-3df0fc44615d.png)

**Comment by NormandoHall** [comment]
Yes @julianlam you are right. It is ok about original and resized images. Thanks
