### ISSUE TITLE
Images broken in notification emails

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#10660]
NodeBB fresh installed 2.0.1

Sending emails, banned, digest, etc. the site logo image is broken (and probably others)

This is the source I get in emails of the logo image:

```
<img src=3D"https://xxxxxxxx/assets/uploads/system/sit=
e-logo-x50.png" height=3D"50" width=3D"50" alt=3D"Profesionales ERF" =
border=3D"0" style=3D"height: 50px; width: 50px; background: #f6f6f6; =
font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,=
sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol; font-size: =
15px; line-height: 20px; color: #333333;">
```

And this is the email template:

```
<!-- IF logo.src -->
<img src="{logo.src}" height="{logo.height}" width="{logo.width}" alt="{site_title}" border="0" style="height: {logo.height}px; width: {logo.width}px; background: #f6f6f6; font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol; font-size: 15px; line-height: 20px; color: #333333;">
<!-- ELSE -->
```

**Comment by julianlam** [comment]
@NormandoHall Can you share how you set the site logo?

I am testing this right now, and the logo shows up (albeit I am using [email-helper](https://github.com/julianlam/nodebb-plugin-email-helper), which is _close_ to a real digest, but not the real thing).

What happens if you go to https://xxxxxxxx/assets/uploads/system/site-logo.png ? The full-size site logo should load.

**Comment by NormandoHall** [comment]
Hi @julianlam 

> What happens if you go to https://xxxxxxxx/assets/uploads/system/site-logo.png ? The full-size site logo should load.

Yes, it shows the logo image

> Can you share how you set the site logo?

Under general setting in ACP:

![image](https://user-images.githubusercontent.com/2943127/172679523-e8521423-4a7e-470d-912a-830da360521c.png)


And also the avatar images from profile not shows in emails:

Test email:

![image](https://user-images.githubusercontent.com/2943127/172679772-85ecfa17-f556-4f50-beee-609ed615440f.png)

Digest emails with avatar images broken:

![image](https://user-images.githubusercontent.com/2943127/172679933-d39064a1-fd21-40b8-a0a4-9228474b4cad.png)

NodeBB: 2.1.0

**Comment by NormandoHall** [comment]
Also note these strange added characters like **3D** or **x50**

img src=**3D**"https://xxxxxxxx/assets/uploads/system/sit=
e-logo-**x50**.png" height=**3D**"50"...

in:
```
<img src=3D"https://xxxxxxxx/assets/uploads/system/sit=
e-logo-x50.png" height=3D"50" width=3D"50" alt=3D"Profesionales ERF" =
border=3D"0" style=3D"height: 50px; width: 50px; background: #f6f6f6; =
font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,=
sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol; font-size: =
15px; line-height: 20px; color: #333333;">
```

**Comment by julianlam** [comment]
Regarding the odd characters, how are you seeing them, by viewing the email in plaintext? Those characters are normal, I think, they're handled properly by the email client.

If you're viewing the email in an email client, just right click the image and let me know where the image links to...

**Comment by NormandoHall** [comment]
Well... seems a Thunderbird issue @julianlam 

This is in Gmail webmail:

![image](https://user-images.githubusercontent.com/2943127/172692351-f6d401aa-dc25-4db2-8eb0-79b47fc98119.png)

Thanks you so much and sorry for disturb with this
