### ISSUE TITLE
Require.js dependency removed

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10673]
Hi,
I have several scripts for NodeBB (some of them are here: https://github.com/yossizahn/nodebb-scripts) that require modules, for example clipboard, using `require`. I saw that in version 2.0 require was canceled, what replaced it?
app.require does not do the job (I did `const require = app.require`)
The scripts work fine in older nudibi, but in 2.0 do not work.
Please help...
Thanks!

**Comment by ShlomoCode** [comment]
@pitaj I have some scripts that use require; I'm looking for a general solution.
Here's a sample script - this script adds a button to the comprse toolbar, which adds code characters:
<img width="49" alt="image" src="https://user-images.githubusercontent.com/78599753/171425853-0016b548-74c7-47d8-a5ca-489618c82214.png">
Although there is a built-in button, the built-in it is intended for large snippets of code, and it adds 3 `s and not just 1 '.
```js
(function () {
  "use strict";
  /* globals require, $ */
  require(["composer/formatting"], function (formatting) {
    require(["composer/controls"], function (controls) {
      formatting.addButton(
        "fa fa-terminal",
        function (textarea, selectionStart, selectionEnd) {
          if (selectionStart === selectionEnd) {
            var block = controls.getBlockData(textarea, "`", selectionStart);
            if (block.in && block.atEnd) {
              controls.updateTextareaSelection(
                textarea,
                selectionStart + 1,
                selectionStart + 1
              );
            } else {
              controls.insertIntoTextarea(textarea, `\`code\``);
              controls.updateTextareaSelection(
                textarea,
                selectionStart + 1,
                selectionStart + "code".length + 1
              );
            }
          } else {
            var wrapDelta = controls.wrapSelectionInTextareaWith(textarea, "`");
            controls.updateTextareaSelection(
              textarea,
              selectionStart + 1 + wrapDelta[0],
              selectionEnd + 1 - wrapDelta[1]
            );
          }
        },
        "code"
      );
    });
  });
})();
```
With NodeBB 1.19.x), it works. With NodeBB 2.0 No:
![image](https://user-images.githubusercontent.com/78599753/171426562-b761c5d9-f2bd-4769-9a25-32926e3552a1.png)
I tried to add at the beginning of the function:
```js
const require = app.require;
```
And the error has disappeared, but the code still does not work..

**Comment by barisusakli** [comment]
Yeah there is no global require function anymore, that was provided by require.js.

You should be able to do the below in custom scripts.

```
const [formatting, controls] = await app.require(['composer/formatting', 'composer/controls']);
```

**Comment by ShlomoCode** [comment]
@barisusakli Thanks!
Why can I not import the 'clipboard' module this way?
![image](https://user-images.githubusercontent.com/78599753/171435035-46189b6d-2e8c-4db8-b57b-ad9f80c757bd.png)

**Comment by ShlomoCode** [comment]
in requirejs it work:
https://github.com/yossizahn/nodebb-scripts/blob/33cd18d76f6f039ada9957b5b04d339ab0dd1233/copy-code-area.js#L4
