### ISSUE TITLE
Unable to reply after update to 2.1.1

### ISSUE THREAD

**Issue by nono-lqdn** [NodeBB/NodeBB#10688]
- **NodeBB version:** 2.1.1
- **NodeBB git hash:** d2e3c913b6701c18cd7db3f2bd184ba7be1cacef
- **NodeJS version:** Welcome to Node.js v14.19.3.

- **Installed NodeBB Plugins:** 
- Active plugins:
        * nodebb-plugin-2factor@5.0.0 (installed, disabled)
        * nodebb-plugin-composer-default@8.0.0 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
        * nodebb-plugin-desktop-notifications@0.3.3 (installed, enabled)
        * nodebb-plugin-emailer-smtp@1.0.2 (installed, enabled)
        * nodebb-plugin-embed@3.0.19 (installed, disabled)
        * nodebb-plugin-emoji@4.0.4 (installed, disabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, disabled)
        * nodebb-plugin-emoji-apple@2.0.5 (installed, disabled)
        * nodebb-plugin-emoji-one@2.0.5 (installed, disabled)
        * nodebb-plugin-emoji-static@1.0.4 (installed, disabled)
        * nodebb-plugin-local-image-upload@0.0.3 (installed, disabled)
        * nodebb-plugin-markdown@10.0.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.11 (installed, enabled)
        * nodebb-plugin-ns-likes@3.0.0 (installed, enabled)
        * nodebb-plugin-poll@2.0.2 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.12.20 (installed, enabled)
        * nodebb-plugin-reactions@0.0.4 (installed, disabled)
        * nodebb-plugin-soundpack-default@2.0.0 (installed, disabled)
        * nodebb-plugin-spam-be-gone@1.0.0 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-persona@12.0.9 (installed, enabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.17 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)

- **Database type:** mongo
- **Database version:** 
```
mongod --version                                                                  │
db version v4.2.20                                                                                        │
git version: 15c0712952c356cb711c13a42cb3bca8617d4ebc                                                     │
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022                                                              │
allocator: tcmalloc                                                                                       │
modules: none                                                                                             │
build environment:                                                                                        │
    distmod: debian10                                                                                     │
    distarch: x86_64                                                                                      │
    target_arch: x86_64     
```
- **Exact steps to cause this issue:**

	1. Update to NodeBB 2.1.1
	2. Then, I clicked on "Reply"
	3. Reply does not appear, nothing happens.

- **What you expected:**
Reply box to appear, be able to submit a reply.
- **What happened instead:**
Nothing

Javascript logs : 

```
Uncaught TypeError: window.Poll is undefined
    60175 https://forum.fr/assets/nodebb.min.js?v=niqgvlpfmjk:2
    60175 https://forum.fr/assets/nodebb.min.js?v=niqgvlpfmjk:2
    o https://forum.fr/assets/nodebb.min.js?v=niqgvlpfmjk:2
    <anonymous> https://forum.fr/assets/nodebb.min.js?v=niqgvlpfmjk:2
    <anonymous> https://forum.fr/assets/nodebb.min.js?v=niqgvlpfmjk:2
    <anonymous> https://forum.fr/assets/nodebb.min.js?v=niqgvlpfmjk:2
nodebb.min.js:2:66320
```

**Comment by barisusakli** [comment]
Update poll plugin to latest

**Comment by nono-lqdn** [comment]
It's at version 2.0.3, the latest being 2.0.3. :(

**Comment by pitaj** [comment]
Latest is 2.0.6, you may need to install it via cli.

**Comment by nono-lqdn** [comment]
How can I do that ? :)

**Comment by nono-lqdn** [comment]
I just removed the extension and regenerated the forum, but it doesn't change anything.

**Comment by nono-lqdn** [comment]
I removed the extension and rebuilt the JS with `./nodebb rebuild`, it fixed the issue.

**Comment by barisusakli** [comment]
You can run `npm i nodebb-plugin-poll@2.0.6` to install that version
