### ISSUE TITLE
.fab is conflicting with floating action button from somewhere

### ISSUE THREAD

**Issue by oplik0** [NodeBB/NodeBB#10698]
- **NodeBB version:** 1.18.0-2.1.1 (current master)
- **NodeJS version:** all supported

This is something of an issue I have caused myself; while I have tested all previous icons it seems I missed the new ones that require `.fab` class. They still work with less aliases and directly setting font, but when trying to use just classes, due to a conflict with some other style (bootstrap? Somewhere where `.fab` means floating action button anyway) you'll get the icon in a circle of the same color, making it invisible.

There are a few options for resolving it that I see:
1. add alternative class - for example `.fa-brands`
2. replace the `.fab` class with an alternative as above
3. upgrade to FontAwesome 6, which uses `.fa-brands` as the prefix already

I'd say 3 is preferable, but it's a slightly bigger effor. I'll try to do it in the next few days. Thankfully it seems it's basically fully backwards-compatible with FA5 by default (including old prefixes) and there are still shims for FA4, so it should be easier than the migration to v5.

The licensing shouldn't be an issue either, as it appears to be the same situation as in FA5 for the free version: https://fontawesome.com/license/free (fonts are under SIL OFL 1.1, icons CC BY 4.0 and code MIT)

**Comment by julianlam** [comment]
This is just for the ACP, yes?

It's likely https://getmdl.io/ or whatever we use on the ACP side...

**Comment by julianlam** [comment]
In that case, that's something we can also fix... whatever stylesheet that is, it shouldn't need to be on the client-side. I'll open a companion issue.
