### ISSUE TITLE
Forum Traffic Screen 

### ISSUE THREAD

**Issue by cgtyysr** [NodeBB/NodeBB#10694]
Hi,
After updated 2.1.1 version, the traffic screen of nodebb not working.

![image](https://user-images.githubusercontent.com/106465804/173288736-e44ab080-cfa2-4acb-aa49-73646a0ef4e2.png)

**Comment by cgtyysr** [comment]
![image](https://user-images.githubusercontent.com/106465804/173510729-db66e6d7-55e6-41bf-8cd0-3100d5fa43af.png)

@nodebb/nodebb-plugin-user-level
nodebb-plugin-browsing-users
nodebb-plugin-cards
nodebb-plugin-composer-default
nodebb-plugin-custom-pages
nodebb-plugin-customize
nodebb-plugin-dbsearch
nodebb-plugin-desktop-notifications
nodebb-plugin-embed
nodebb-plugin-emoji
nodebb-plugin-emoji-android
nodebb-plugin-featured-topics-extended
nodebb-plugin-google-analytics
nodebb-plugin-hashtags
nodebb-plugin-iframely
nodebb-plugin-markdown
nodebb-plugin-mentions
nodebb-plugin-night-mode
nodebb-plugin-question-and-answer
nodebb-plugin-recent-cards
nodebb-plugin-soundpack-default
nodebb-plugin-twitter
nodebb-rewards-essentials

thank you.

**Comment by julianlam** [comment]
Likely it is a plugin that is incompatible with NodeBB v2. Can you please run `./nodebb reset -p` and then re-activate them one by one (rebuilding NodeBB as necessary in between) in order to figure out which one?

**Comment by cgtyysr** [comment]
yes of course.

**Comment by barisusakli** [comment]
Update nodebb-plugin-customize to 2.0.5 see this thread https://community.nodebb.org/topic/16517/console-error-after-upgrade-to-2-1-0
