### ISSUE TITLE
Ability to disable welcome email

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10691]
From https://community.nodebb.org/post/88366

**Comment by barisusakli** [comment]
Looks like this was added but it disables both the welcome email and the emails sent if you add change email later on.
https://github.com/NodeBB/NodeBB/commit/09e0c6d503e4267087f3695755e20fd94df312a9

**Comment by julianlam** [comment]
Thanks @baris :+1:

**Comment by julianlam** [comment]
The welcome mail is just a differently worded verification email now, so it would be difficult to disable just the one. Will reply with a workaround, in that topic linked above.
