### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by Justman10000** [NodeBB/NodeBB#10700]
I was about to install NodeBB, but all I get is this:

> Error [ERR_REQUIRE_ESM]: require() of ES Module /home/NodeBB/node_modules/chalk/source/index.js from /home/NodeBB/src/prestart.js not supported.
Instead change the require of index.js in /home/NodeBB/src/prestart.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/NodeBB/src/prestart.js:7:15)
    at require.main.require (/home/NodeBB/require-main.js:8:10)
    at Object.<anonymous> (/home/NodeBB/app.js:43:18) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by julianlam** [comment]
Related:
* https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
* https://github.com/chalk/chalk/issues/549

**Comment by Justman10000** [comment]
> Related:
> 
>     * https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
> 
>     * [something error please help  chalk/chalk#549](https://github.com/chalk/chalk/issues/549)

```bash
node app.js
```

> TypeError: Cannot read properties of undefined (reading 'node')

**Comment by Justman10000** [comment]
```bash
node app.js
```

> TypeError: Cannot read properties of undefined (reading 'node')

**Comment by Justman10000** [comment]
@julianlam

**Comment by julianlam** [comment]
How are you installing NodeBB? You should probably follow the steps here: https://docs.nodebb.org/installing/os/ubuntu/

I'm not even sure what you're running to get that particular error.

**Comment by Justman10000** [comment]
> How are you installing NodeBB? You should probably follow the steps here: https://docs.nodebb.org/installing/os/ubuntu/
> 
> I'm not even sure what you're running to get that particular error.

I pulled NodeBB over Source... Node as archive and unpacked...
