### ISSUE TITLE
tabs at the bottom of notification and chat panels

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10706]
When the translation is long, it overlaps with the other tab... What do you think would be best? 
Should I re-translate for Turkish to make it shorter? Or will you change the height of the tab? 

**For Chat Panel:**

This is how it looks in English:

![Screen Shot 2022-06-16 at 7 15 40 PM](https://user-images.githubusercontent.com/52054408/174193707-f694d928-21a1-4509-8174-99ab18a06539.png)

This is how it looks in Turkish:

![Screen Shot 2022-06-16 at 7 14 22 PM](https://user-images.githubusercontent.com/52054408/174193768-82771bf9-b658-48a5-ae59-35be885cd235.png)

**For Notification Panel:**

This is how it looks in English:

![Screen Shot 2022-06-16 at 7 15 30 PM](https://user-images.githubusercontent.com/52054408/174193834-28245827-f477-472f-bc00-6a80ddd414fa.png)

This is how it looks in Turkish:

![Screen Shot 2022-06-16 at 7 12 26 PM](https://user-images.githubusercontent.com/52054408/174193882-93c10909-1487-42fc-861e-36d8cd97fdc1.png)

**Comment by julianlam** [comment]
😒 lovely.

**Comment by barisusakli** [comment]
Turkish 💪🏼 😆

**Comment by AliCihan** [comment]
and this is how it looks in Bulgarian... 

<img width="500" alt="Screen Shot 2022-06-16 at 8 12 24 PM" src="https://user-images.githubusercontent.com/52054408/174198009-dfcfc599-921e-4f92-a9b9-e4cc329f2ae9.png">
