### ISSUE TITLE
Switch from Transifex to Weblate/Crowdin

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10712]
> Well, we have 3 options:
> 
> - We'll stay with Transifex
> - We're moving to Weblate
> 
> or
> 
> - We're moving to Crowdin...
> 
> 
> Here is a overview:
> 
> -  Crowdin has a clear advantage over Weblate and Transifex... _The tree structure_! For example, if you have the _test_ directory in your GitHub repository, all files in Crowdin will also be nested under the _test_ directory...
> 
> - Unlike Transifex, Weblate and Crowdin can use nested JSON strings...
> 
> - Unlike Crowdin and Transifex, Weblate can be self-hosted and is opensource, you don't need a cloud version so you have no restrictions!

_Originally posted by @Justman10000 in https://github.com/NodeBB/NodeBB/issues/10697#issuecomment-1157343524_

**Comment by julianlam** [comment]
For what it's worth, Transifex looks like it oes support nested keys now](https://docs.transifex.com/formats/json), so a switch may not be necessary.

**Comment by julianlam** [comment]
The free/libre aspect of weblate appeals to me, but the network effect of larger services cannot be ignored. The community contribution to the localisations are what make the entire system work.

I don't know where most of our translators come from. Are they NodeBB users, or are they using Transifex purely because Transifex has gamified their interface and incentivised localisations for projects that they do not even use?

The last thing I want to do is switch over to a different system and lose our entire contributor base, just because it looks nicer or has a couple features Tx does not have.

**Comment by Justman10000** [comment]
> The free/libre aspect of weblate appeals to me, but the network effect of larger services cannot be ignored. The community contribution to the localisations are what make the entire system work.
> 
> I don't know where most of our translators come from. Are they NodeBB users, or are they using Transifex purely because Transifex has gamified their interface and incentivised localisations for projects that they do not even use?
> 
> The last thing I want to do is switch over to a different system and lose our entire contributor base, just because it looks nicer or has a couple features Tx does not have.

Especially since we would need a VPS to host ourselves... Which would be pretty cheap, since Weblate doesn't eat up much performance...

**Comment by AliCihan** [comment]
if there is not any clear and obvious advantage for switching, then it might be better to stay on Transifex. 

In any case, I would be OK with moving to a new platform if it is necessary; but I do not know about others.

**Comment by julianlam** [comment]
I think if we were to seriously consider it, I'd want a commitment from at least one translator in at least 50% of our supported languages
```
$ ls -1 | wc -l
47
```

46 languages :grimacing: (the readme is the remaining file)

**Comment by Justman10000** [comment]
> That said, I am leaning towards keeping Transifex, currently.

Yes, Weblate doesn't support nested components (tree view)! However, it is already in the works! You would have to ask Crowdin for an Enterprise Edition...

**Comment by Justman10000** [comment]
> That said, I am leaning towards keeping Transifex, currently.

Yes, Weblate doesn't support nested components (tree view)! However, it is already in the works! We would have to ask Crowdin for an Enterprise Edition...

**Comment by oplik0** [comment]
I personally prefer the Crowdin UI (no experience with Weblate), but it's a slight preference, not something big enough to change platforms. Unless there are some other benefits I too don't think there is a point in switching platforms, but I'd also be okay with it.

**Comment by andrii-bodnar** [comment]
Hi @julianlam @julianlam @oplik0 @AliCihan!

it's Andrii from Crowdin. Crowdin is free for open source, I can do a pull request with the integration setup. 

I would only need a green light from you and the minimal setup of this repo (create a Crowdin project and add some Actions secrets).

The integration can be completely automatic and can be done via [Crowdin GH Action](https://github.com/crowdin/github-action).

Crowdin has great support for the JSON files, so it should be easy to set up the integration.

**Comment by Justman10000** [comment]
@julianlam

If we accept his offer, I would like to have the ownership rights, I know it's asking a lot and also misses the point of owning NodeBB, but I've already worked with Chatwoot's enterprise and also a little with the private version Crowdins... Especially since I would love to learn how to set this up and would also have the benefit of being able to manage everything... In the Crowdin Enterprise (I don't know if this also exists in the private edition) there is an admin rank, which is directly below the owner! If trusting me with the ownership rights is too much for you, I might as well become an admin...

**Comment by andrii-bodnar** [comment]
@Justman10000 

> You are a Crowdin employee?

Yes. 

I can prepare a PR including configured GitHub workflow (will use the Crowdin GitHub Action) and a demo project.

Then, you can create a [Crowdin](https://accounts.crowdin.com/register) or [Crowdin enterprise](https://accounts.crowdin.com/workspace/create) account, make some Repo configuration and merge my PR.

**Comment by Justman10000** [comment]
@andrii-bodnar

As if a Crowdin employee would personally answer... Anyway, got submitted
![grafik](https://user-images.githubusercontent.com/49990629/174893237-15a542a8-2c3a-43e9-93dc-7345c4c8269a.png)

You can see 2 notes there, don't be surprised if it arrives twice, simply delete one of the two applications... Whether I should get the property rights or then cede them can still be discussed afterwards... As already mentioned above...

**Comment by oplik0** [comment]
> As if a Crowdin employee would personally answer...

I mean, it takes just a moment to look at their activity in @crowdin org to verify that, even if you thought they for some reason lied about being an employee. For example see https://github.com/crowdin/zapier-integration where they're the sole contributor.

**Comment by andrii-bodnar** [comment]
Hey everyone,

Just created the PR - #10721. In this PR you will find the configuration and the demo Crowdin project.

**Comment by Justman10000** [comment]
> Hey everyone,
> 
> Just created the PR - #10721. In this PR you will find the configuration and the demo Crowdin project.

Hmm, the project doesn't exist yet! I still don't have a confirmation email!

**Comment by Justman10000** [comment]
@andrii-bodnar @julianlam 

I have already created the Enterprise project:

https://nodebb.crowdin.com

Couldn't wait any longer 🤣...

@andrii-bodnar

I don't know but it's certainly possible, could you set this so that I don't have to pay for https://nodebb.crowdin.com after 30 days?

**Comment by Justman10000** [comment]
@andrii-bodnar @DimaYashchyshyn

So, I don't see the message with the test phase anymore... Does this mean that we can now use this without restrictions?

**Comment by andrii-bodnar** [comment]
> So, I don't see the message with the test phase anymore... Does this mean that we can now use this without restrictions?

Yes, you can now use this without restrictions

**Comment by Justman10000** [comment]
> > So, I don't see the message with the test phase anymore... Does this mean that we can now use this without restrictions?
> 
> Yes, you can now use this without restrictions

Great, then only the employees of NodeBB and its community are missing...

**Comment by Andrulko** [comment]
> > > So, I don't see the message with the test phase anymore... Does this mean that we can now use this without restrictions?
> > 
> > 
> > Yes, you can now use this without restrictions
> 
> I don't know if it's asking too much, but could we have business as a plan?

I guess the reason is [SAML SSO](https://support.crowdin.com/enterprise/saml/)? It's available for your organization already 👍

**Comment by Justman10000** [comment]
> Just from a contributor: is there any need for this? From my understanding the main difference relevant here is permission granularity, and I'm not sure if it'll be necessary here.
> 
> At the very least I'd wait until the move from Transifex to Crowdin is finished to see if it's really needed.

I also spoke about the other strings and manager slots

**Comment by Justman10000** [comment]
@akhoury @barisusakli @julianlam

I'm still waiting 😅

**Comment by julianlam** [comment]
We have not decided to switch from Transifex to Crowdin yet. Please do not jump the gun on our behalf @Justman10000 ...?

@andrii-bodnar can you please email me julian@nodebb.org

**Comment by julianlam** [comment]
@Justman10000 can you also email me? I'd like to speak to you both separately.

**Comment by Justman10000** [comment]
> We have not decided to switch from Transifex to Crowdin yet. Please do not jump the gun on our behalf @Justman10000 ...?
> 
> @andrii-bodnar can you please email me [julian@nodebb.org](mailto:julian@nodebb.org)

I explained it above...

**Comment by Justman10000** [comment]
> @Justman10000 can you also email me? I'd like to speak to you both separately.

I have

**Comment by Justman10000** [comment]
@julianlam

And? Did you guys clear it up?

**Comment by julianlam** [comment]
We decided to remain with Transifex for the time being. The existing localisation community is best left undisturbed. We can look into tree-style JSON files.

**Comment by Justman10000** [comment]
> We decided to remain with Transifex for the time being. The existing localisation community is best left undisturbed. We can look into tree-style JSON files.

The Crowdin instance is already approved!

**Comment by julianlam** [comment]
I fail to see what bearing that has on whether we uproot our entire localisation community for Crowdin.

I applaud your enthusiasm, but at this time we will continue with hosting our localisation on Transifex unless some other factor forces our hand. You have the attitude of "get s*** done", which is definitely advantageous in many respects. There was a time when we would've made decisions like this, without considering the consequences, but we're at a point now when we need to consider how one change affects the workflow of others, and of the quality of the project as a whole.

**Comment by Justman10000** [comment]
> I fail to see what bearing that has on whether we uproot our entire localisation community for Crowdin.
> 
> I applaud your enthusiasm, but at this time we will continue with hosting our localisation on Transifex unless some other factor forces our hand. You have the attitude of "get s*** done", which is definitely advantageous in many respects. There was a time when we would've made decisions like this, without considering the consequences, but we're at a point now when we need to consider how one change affects the workflow of others, and of the quality of the project as a whole.

I'm not quite getting it... I certainly didn't bother to create the Enterprise instance and even applied for a license for our instance, which was granted... Just so you can stay with Transifexs? It would certainly be a bit of work at first, but once this was behind us...

**Comment by Justman10000** [comment]
@julianlam

But, if it stays that way, I would like to be a proofreader for German

**Comment by Justman10000** [comment]
> @Justman10000 — you are now a reviewer for the German language on our Transifex org.

Thanks
<br>
> As for this:
> 
> > I certainly didn't bother to create the Enterprise instance and even applied for a license for our instance, which was granted... Just so you can stay with Transifexs?
> 
> I again appreciate your initiative, but you're not seriously going to lay blame on me after you singlehandedly and proactively decided to spend the time to do this, _without asking for our go-ahead_?

Well... Probably true again... only... What do we do with the instance now? Keep until you should switch?

**Comment by Justman10000** [comment]
@julianlam

Could I be admin of the trasnifex instance? Or Team-Manager of german?
