### ISSUE TITLE
Header bar not working on iOS & Android 

### ISSUE THREAD

**Issue by cgtyysr** [NodeBB/NodeBB#10713]
We have determined that the website does not work when we click on the areas shown in the picture. There is no problem in other areas, such as entering a topic, but only in these two places.
![image0](https://user-images.githubusercontent.com/106465804/174426031-98e001aa-9787-44d7-8870-eb7c19f1b2b3.jpeg)

**Comment by pitaj** [comment]
What version of NodeBB? What theme? What version of iOS? Have you tried disabling all plugins, followed by a rebuild and restart?

**Comment by cgtyysr** [comment]
We have seen and tested that it does not work on Android also. I get the same error when I disable the plugins. I'm already continuing with the minimum level of plugins. 

Nodebb version: 2.2.0
IOS: last version 15.
Theme standart of Nodebb.

**Comment by cgtyysr** [comment]
Active plugins:
        * nodebb-plugin-browsing-users@2.0.4 (installed, enabled)
        * nodebb-plugin-composer-default@8.0.0 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
        * nodebb-plugin-emoji@4.0.4 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-google-analytics@0.6.2 (installed, enabled)
        * nodebb-plugin-iframely@0.7.16 (installed, enabled)
        * nodebb-plugin-markdown@10.0.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.11 (installed, enabled)
        * nodebb-plugin-poll@2.0.6 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.12.24 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.22 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-persona@12.0.11 (installed, disabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.18 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)

**Comment by AliCihan** [comment]
according to this list: https://community.nodebb.org/post/88408

only poll plugin is extra in your forum... disable that plugin and reboot... if problem continues, you can paste the log here...

**Comment by cgtyysr** [comment]
problem fixed.

restarted server
deactiveted theme
reactiveted theme
and problem is fixed.

ps some plugins deleted because of new version of Nodebb.

current active plugins;

Active plugins:
        * nodebb-plugin-browsing-users@2.0.4 (installed, enabled)
        * nodebb-plugin-composer-default@8.0.0 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
        * nodebb-plugin-emoji@4.0.4 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-google-analytics@0.6.2 (installed, enabled)
        * nodebb-plugin-iframely@0.7.16 (installed, enabled)
        * nodebb-plugin-markdown@10.0.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.11 (installed, enabled)
        * nodebb-plugin-poll@2.0.6 (installed, disabled)
        * nodebb-plugin-question-and-answer@0.12.24 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.22 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-persona@12.0.11 (installed, enabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.18 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)
