### ISSUE TITLE
Service Worker causes Android based browsers (except Firefox) to freeze then crash

### ISSUE THREAD

**Issue by phenomlab** [NodeBB/NodeBB#10715]
- **NodeBB version: 2.1.0 
- **NodeBB git hash: a3114d3359f5d38aeb525082be1e0d54cc9cbabe
- **NodeJS version: 18.x
- **Installed NodeBB Plugins:** 
        * @nodebb/nodebb-plugin-user-level@1.0.0 (installed, enabled)
        * nodebb-plugin-2factor@5.0.0 (installed, enabled)
        * nodebb-plugin-blog-comments@0.8.6 (installed, enabled)
        * nodebb-plugin-browsing-users@2.0.4 (installed, enabled)
        * nodebb-plugin-cards@0.3.1 (installed, enabled)
        * nodebb-plugin-category-notifications@3.1.1 (installed, enabled)
        * nodebb-plugin-composer-default@8.0.0 (installed, enabled)
        * nodebb-plugin-custom-pages@1.3.3 (installed, enabled)
        * nodebb-plugin-customize@2.0.5 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
        * nodebb-plugin-desktop-notifications@0.3.3 (installed, enabled)
        * nodebb-plugin-embed@3.0.19 (installed, enabled)
        * nodebb-plugin-emoji@4.0.4 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-emoji-apple@3.0.0 (installed, disabled)
        * nodebb-plugin-featured-topics-extended@0.10.1 (installed, enabled)
        * nodebb-plugin-gdpr@1.1.1 (installed, enabled)
        * nodebb-plugin-glossary@0.0.22 (installed, enabled)
        * nodebb-plugin-gravatar@2.3.0 (installed, enabled)
        * nodebb-plugin-iframely@0.7.16 (installed, enabled)
        * nodebb-plugin-insult-filter@1.0.2 (installed, enabled)
        * nodebb-plugin-markdown@10.0.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.11 (installed, enabled)
        * nodebb-plugin-poll@2.0.6 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.12.24 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.22 (installed, enabled)
        * nodebb-plugin-registration-notification@2.0.2 (installed, enabled)
        * nodebb-plugin-reputation-rules@1.2.3 (installed, enabled)
        * nodebb-plugin-soundpack-default@2.0.2 (installed, enabled)
        * nodebb-plugin-spam-be-gone@1.0.0 (installed, enabled)
        * nodebb-plugin-sso-discord-with-logo@1.0.2 (installed, enabled)
        * nodebb-plugin-sso-google@2.5.7 (installed, enabled)
        * nodebb-plugin-sso-twitter@2.5.13 (installed, enabled)
        * nodebb-plugin-twitter-netdata@1.0.0 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-material@2.13.1 (installed, disabled)
        * nodebb-theme-persona@12.0.8 (installed, enabled)
        * nodebb-theme-slick@2.0.1 (installed, disabled)
        * nodebb-theme-vanilla@12.1.17 (installed, disabled)
        * nodebb-widget-board-stats@1.2.3 (installed, enabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)
- **Database type: mongo
- **Database version: 4.0.28
- **Exact steps to cause this issue:**

- **What you expected:**
I expected to be able to use the app without issues
- **What happened instead:**
Browser froze for a couple of seconds, then crashed completely. This appears to be the result of the service worker related to PWA - see https://community.nodebb.org/topic/16537/nodebb-freezing-on-android-devices/3 according to @pitaj

**Comment by julianlam** [comment]
Our existing service worker configuration only exists so that you can install the app onto your home screen.

It doesn't actually do anything, but we also don't have much expertise in the implementation. If it is indeed causing issues on android, we may need to remove it completely.

**Comment by phenomlab** [comment]
Hey Julian,

It is causing issues for Android, but not when using Firefox.  @pitaj has been able to confirm my findings.

**Comment by julianlam** [comment]
> Is there a way to disable it from the ACP ? I couldn't see anything obvious.

No, unfortunately not. Right now the service worker is just loaded via the meta tag along with the manifest file. It's the bare minimum (as implemented by @psychobunny) to allow for NodeBB to be installed as an "app" on your home screen.

I can look into putting it behind a feature flag.

**Comment by julianlam** [comment]
Correction, `registerServiceWorker` is called in `app.js` on load. Should be trivial to put this behind a feature flag.

**Comment by julianlam** [comment]
As an aside, the reason why the page works fine on Safari is because `registerServiceWorker` checks for iOS devices and does nothing... so it seems.

**Comment by phenomlab** [comment]
> As an aside, the reason why the page works fine on Safari is because `registerServiceWorker` checks for iOS devices and does nothing... so it seems.

Ok, but what about Firefox on Android which seems to be unaffected ? The bug is clearly evident with Edge, Chrome, Brave etc (anything Webkit based essentially)

**Comment by julianlam** [comment]
I hate to be a "blame the bigger org", but the situation as I understand it seems to be;

* The service worker implementation was working fine for all browsers up until now
* It only stopped working on webkit-based browsers
* The service worker code has not changed in many years

Therefore, it seems straightforward that either the Chrome team introduced a breaking change (or a deprecation window has run out causing compatibility to no longer be assured), or it's a bug that will eventually be fixed.

Firefox uses their own rendering engine, so seems as yet unaffected. However their commitment to PWA is not encouraging, and so I am not certain whether we ought to continue supporting it at all.

**Comment by phenomlab** [comment]
> Firefox uses their own rendering engine, so seems as yet unaffected. However their commitment to PWA is not encouraging, and so I am not certain whether we ought to continue supporting it at all.

I'm of the same opinion. Personally, I'd expect it to be a matter of time before Firefox is impacted by an outlier in the sense that this could easily be in the form of a vendor patch for that application, and not Firefox themselves. Something Samsung to very often.

**Comment by julianlam** [comment]
I imagine this was a transient issue and is no longer happening?
