### ISSUE TITLE
1.19.9 shows wrong version number

### ISSUE THREAD

**Issue by nilsramsperger** [NodeBB/NodeBB#10711]
Hi there.

The package.json of tag 1.19.9 contains 1.19.7 as version number.

Greets
Nils

**Comment by julianlam** [comment]
Thanks @nilsramsperger -- as per pre-v2 release policy, I will be re-tagging the version to fix the version number.

**Comment by julianlam** [comment]
[fdf8cf5](https://github.com/NodeBB/NodeBB/commit/fdf8cf5842f17d4ad2d3141199bdf3ac964b6689)

**Comment by nilsramsperger** [comment]
The checkin you mention fixes tag v1.19.8 showing 1.19.9.
Tag v1.19.9 is still showing 1.19.7.

**Comment by julianlam** [comment]
Hmm unless I'm mistaken we don't have a 1.19.9 tag... At least we don't have a release under that version. Perhaps it was tagged by mistake? 

@barisusakli ? 🤔

**Comment by oplik0** [comment]
There is a tag but no version: https://github.com/NodeBB/NodeBB/releases/tag/v1.19.9

**Comment by barisusakli** [comment]
Yeah I tagged it for a client, but there is no release 🤔
