### ISSUE TITLE
Disconnect the forum

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#10722]
- **NodeBB version:**  v2.1.0
- **NodeBB git hash:** 

- **Installed NodeBB Plugins:** 

- **Database type:** mongo, redis, 
- **Database version:** MongoDB Version 4.2.17 , Redis Version 7.0.0
- 

The forum is disconnected many times each day with  502error and reconnected.
And users get a lot of errors
We have about 6,000 users every month

**Comment by julianlam** [comment]
You will need to provide server logs in order for us to debug.

**Comment by AliCihan** [comment]
have you tried to adjust "ACP > Settings > Advanced > Traffic Management" values? 

if I remember correctly we previously solved a similar problem by adjusting these values.

**Comment by julianlam** [comment]
@AliCihan that'd be a 504 error. A 502 suggests a server crash...

**Comment by roghaye-m** [comment]
> You will need to provide server logs in order for us to debug.


Do you mean this error?

![error](https://community.nodebb.org/assets/uploads/files/1656056402216-error.png)

If not, where can I get it?

**Comment by julianlam** [comment]
That specific error suggests more than one NodeBB is running at the same time.

`pkill -9 node` and then start NodeBB again.

Keep in mind that the above command will kill off every single nodejs process running
