### ISSUE TITLE
client-cide hook for delete post

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#10734]
### Description

Hi,
I researched a lot and it seems that there is no client side hook called in **deleting a post** - and with it I will also be able to delete proactively with `$(window).gtigger()`...

---
I checked `action:post.delete`
And I listened to all the hooks with the help of the function brought [here](https://stackoverflow.com/a/41388827/17059718);
For editing an example post called a hook, for deleting no.
Could that be added?
Thenks!

----
>I saw that when deleting, an `HTTP DELETE` request is sent to `https://forum.com/api/v3/posts/{postId}/state`
But when I sent such a request through the console I encountered an error 403...

**Comment by oplik0** [comment]
It should be `static:post.delete`.
See https://github.com/NodeBB/NodeBB/blob/f38b2a737a6fc8a501f86893c42fd3e800264cc1/public/src/client/topic/postTools.js#L415-L419

And the way it's triggered here: https://github.com/NodeBB/NodeBB/blob/f38b2a737a6fc8a501f86893c42fd3e800264cc1/public/src/client/topic/postTools.js#L403-L409

**Comment by ShlomoCode** [comment]
Uh-huh... It's Wu Sesti, you can't test it with wind `$(window).on`, need to use require (or app.require for version 2 and above)
👍
By the way, why didn't the API request work? After all, it was sent from the same site and if so the cookies were also sent...

**Comment by ShlomoCode** [comment]
@oplik0 
```
require(['hooks'], (hooks) => {
    hooks.fire('static:post.delete', {
        action: 'delete',
        pid: '146318',
    });
});
```
![image](https://user-images.githubusercontent.com/78599753/176572897-18e0a80f-bec1-4633-8615-e0a16842511d.png)
Why doesn't it do anything on the forum? 🤔

**Comment by pitaj** [comment]
You probably need to use `const hooks = await app.require('hooks')`

**Comment by ShlomoCode** [comment]
@pitaj This is a forum in version `1.9.x`.
In any case, it does not work either...
![image](https://user-images.githubusercontent.com/78599753/176580235-39127699-c87a-4ee5-afd4-6105cffc37a0.png)
```js
const hooks = await app.require('hooks')
await hooks.fire('static:post.delete', {
     action: 'delete',
     pid: '146318',
});
```
It seems so, but in practice nothing happens - no delete confirmation window opens, nor is the post deleted,
of course
Maybe you can check it out in your forum?

**Comment by pitaj** [comment]
Oh, if you're trying to delete the post, firing the hook probably won't do that. Hooks exist for adding actions to existing functionality, not for triggering that functionality.

**Comment by ShlomoCode** [comment]
In action Hooks Activating a hook with the correct information object triggers the action... 🙄
For example: editing a post, a new topic, commenting on a topic...
I thought this was the right way if I want to for example add a button in a different location than the built-in, or add a keyboard shortcut to the action...

**Comment by pitaj** [comment]
Did you read that somewhere? Sorry if you were misled.

**Comment by ShlomoCode** [comment]
@pitaj OK...
So actually how can I get a client-side to delete a post?

**Comment by oplik0** [comment]
You can use the `api` module (https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/api.js)

```js
const api = app.require("api");
await api.del(`/api/v3/posts/${postId}/state`);
```

**Comment by ShlomoCode** [comment]
@oplik0 Wow, it's just amazing!
thanks 👏👏

**Comment by ShlomoCode** [comment]
@oplik0 I just wanted you to see how much good you did - check out what I did with your knowledge 🙃
![delete-btn](https://user-images.githubusercontent.com/78599753/176792604-fea11fd1-2de2-4bfe-b5be-22449834eea3.gif)
And of course everything with full localization for any language that NodeBB supports - with a "translation" model of NodeBB 😁
