### ISSUE TITLE
Is socket.io-adapter-cluster used?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10741]
### NodeBB version

v2.2.3

### NodeJS version

v16.15.1

### Database type

Redis

### Anything else?

Is socket.io-adapter-cluster package used in the codebase? We are having a legal review of packages used in our setup and this was raised to review but I cant identify where this is used in the codebase. It doesn't seem to be required anywhere unless I've missed it. Can you confirm where its used or can it be removed?

**Comment by oplik0** [comment]
It shouldn't be used anywhere AFAIK - NodeBB hasn't even been using the `cluster` module for quite some time.
