### ISSUE TITLE
Missing Muted Loc Text

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10757]
Nodebb v2.2.3

Not sure how your loc pipeline works with your Transifex project but some of the muted text in error.json text is not loc'ed in the following locs that we use

es, ja, ko, pl, pt-br, ru, th, zh-tw

with the following keys

cant-mute-other-admins
user-muted-for-hours
user-muted-for-minutes

**Comment by julianlam** [comment]
Hi @uplift — do you mean that those particular keys are not properly localized in that they just display english?

That may be intended, if the translators have not gotten to those keys yet. In that case, the localization will just fall back to the default `en-GB` source string (english).

**Comment by julianlam** [comment]
Happy to re-open if that's not what you're referring to

**Comment by uplift** [comment]
Yeah the keys in those files are in English instead of the relevant loc. 
Do you know if there is a timeframe for getting to them? I can update a bug on our forum with the information so my test team will know when to look out for new loc.

**Comment by julianlam** [comment]
Unfortunately not, since our l10n efforts are entirely community driven. The project itself is hosted on https://www.transifex.com/nodebb/nodebb/, but we don't have a localization team ourselves to translate those keys.
