### ISSUE TITLE
Allow defining active plugins outside of the database

### ISSUE THREAD

**Issue by oplik0** [NodeBB/NodeBB#10766]
### Description

A generalization of the feature that #10036 was trying to add.

Having to define plugin state in the database causes some issues for example if one wants to create a reproducible configuration. Additionally, it means that instances sharing a database have to share all enabled plugins as well.

As such, I'm proposing (and will try implementing :) to allow plugin state to be defined via nconf as well - which would let them be defined in `config.json`, environmental variables and command line flags, covering probably all use cases without creating additional files NodeBB might rely on.

My current idea would be that **if** such configuration is detected it is used **instead** of the database. This would ensure the configuration always results in the expected behavior (no random plugin enabled because it was in database), and since it's opt-in anyway, it wouldn't break any current workflow. 

One thing I'm uncertain of:
Should the implementation write state changes in ACP to `config.json`, or should one assume the passed configuration is how it should be and basically disable this functionality of ACP?

**Comment by julianlam** [comment]
Keep the behaviours predictable. If defining plugins via configuration, then there is no need to sync `plugins.active`

**Comment by julianlam** [comment]
In fact, I'd disable the ACP outright
