### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by mway-niels** [NodeBB/NodeBB#10779]
I tried setting up NodeBB and am presented with the following error message:
```
2022-07-20T12:18:30.591Z [4567/75] - error: GET /
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.helpers.buildBodyClass (/usr/src/app/src/middleware/helpers.js:60:46)
    at defaultHandler (/usr/src/app/src/controllers/errors.js:77:33)
    at handleErrors (/usr/src/app/src/controllers/errors.js:91:10)
```

Looking at the code (https://github.com/NodeBB/NodeBB/blob/master/src/middleware/helpers.js) it seems like this line is causing issues:
```
parts.push(`theme-${meta.config['theme:id'].split('-')[2]}`);
```

Is this a required property? Where do I set it and which values are allowed?

**Comment by mway-niels** [comment]
No, I'm running on Kubernetes and therefore have no option to manually run commands. Can I set this in the `config.json` instead?

**Comment by julianlam** [comment]
You can set [the following values in `config.json`](https://docs.nodebb.org/configuring/config/). If your config.json has appropriate database connection values, then NodeBB will automatically connect to it and run the initial setup (and populate the database, etc.)

You can also specify admin username and password here, I think, but I may be wrong. `admin:username` and `admin:password`
