### ISSUE TITLE
How exactly are the bots identified? The analytics look suspicious.

### ISSUE THREAD

**Issue by sadaszewski** [NodeBB/NodeBB#10780]
### What you expected

Having my website online for 6+ months I have observed linear increase in bot views while the guest page views remained at the same, close to zero level. At the same time the unique visitors increased linearly to the level of about 1200 / day. I have hard time believing that this small website is visited 1200 / day by bots, besides I know by personal account dozens of users who visit it. Could there be a bug? I wanted to ask how are the bots exactly identified by NodeBB or if you could point me to the relevant portion of the code? Thank you in advance.

**Comment by julianlam** [comment]
We use a dependent package called [spider-detector](https://www.npmjs.com/package/spider-detector?activeTab=readme), though it (and by extension, we) make no guarantees that the slotting of users is accurate. There may be false positive, there may be false negatives, and given the state of the SEO industry, it is no surprise that the numbers are not accurate.

You could install _X_ analytics trackers on any given website, and receive no two identical result sets :smile:

**Comment by julianlam** [comment]
For what it's worth, you can selectively filter out specific group sets in the admin homepage analytics chart. Just click on the label at the top to toggle it on/off.

A site with lots of bots will essentially drop the other lines to near-zero.

**Comment by sadaszewski** [comment]
Many thanks!
