### ISSUE TITLE
Group cover photos should not be saved in /public/uploads/files

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#10783]
### NodeBB version

v2.2.5

### NodeJS version

v16.15.0

### Database type

MongoDB

### Exact steps to cause this issue

After upgrading to 2.2.3 (I can't remember very well, because now I stay in 2.2.5) now I realize that group images covers are gone. 

![image](https://user-images.githubusercontent.com/2943127/180379940-416321e0-e33f-421e-9693-bf129c611c08.png)

And also in a lot of posts (not all), the resized file are deleted from filesystem, but still there the original ones. The problem is that posts shows `-resized` images and they are broken, but clicking on the link goes to the original one that shows correctly.

The upload settings are as follow:

![image](https://user-images.githubusercontent.com/2943127/180380417-3620dd1b-3804-475b-9c94-cc78bff9ae4b.png)

![image](https://user-images.githubusercontent.com/2943127/180380477-1b22c63b-d6c5-42b7-9c9c-78b712d76406.png)

![image](https://user-images.githubusercontent.com/2943127/180380529-2e62c816-816d-46b5-9082-0efe18f06c4b.png)

**Comment by julianlam** [comment]
Ah, that's annoying, group covers are saved to `public/uploads/files` too. I'll move them out, sorry for the inconvenience!

This was due to the newly added feature to delete orphaned images. (#10659)

**Comment by julianlam** [comment]
As mentioned before by @ShlomoCode, the logic to purge orphaned files will incorrectly purge chat uploads too, since we don't track them. This will eventually be handled in #10705.

**Comment by julianlam** [comment]
:point_up: This commit will at least stop the group covers from being purged. The actual relocation of the group covers would actually fall under #10705, so I will expand that issue to include it.

**Comment by NormandoHall** [comment]
Thanks @julianlam !
