### ISSUE TITLE
Imgur images not showing in v2.3.0

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#10798]
### NodeBB version

v2.3.0

### NodeJS version

v18.6.0

### Installed NodeBB plugins

Active plugins:
	* nodebb-plugin-2factor@5.0.1 (installed, enabled)
	* nodebb-plugin-composer-default@8.0.0 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
	* nodebb-plugin-emoji@4.0.4 (installed, enabled)
	* nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
	* nodebb-plugin-imgur@2.0.5 (installed, enabled)
	* nodebb-plugin-markdown@10.0.0 (installed, enabled)
	* nodebb-plugin-mentions@3.0.11 (installed, enabled)
	* nodebb-plugin-soundpack-default@2.0.1 (installed, disabled)
	* nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
	* nodebb-rewards-essentials@0.2.1 (installed, disabled)
	* nodebb-theme-lavender@6.0.0 (installed, disabled)
	* nodebb-theme-persona@12.0.12 (installed, disabled)
	* nodebb-theme-slick@2.0.2 (installed, disabled)
	* nodebb-theme-sweetp@1.0.0 (installed, enabled)
	* nodebb-theme-vanilla@12.1.18 (installed, disabled)
	* nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

PostgreSQL

### Database version

14.4 (Ubuntu 14.4-1.pgdg20.04+1)

### Exact steps to cause this issue

Upgraded from v2.2.0 to v2.3.0

### What you expected

Group images and uploaded images would remain visible

### What happened instead

all Imgur images are not visible on my forum

### Anything else?

here's a link to my forum:
https://support.sweetpproductions.com

**Comment by julianlam** [comment]
Looks related to [Cross-Origin-Resource-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)), thanks for reporting.

**Comment by julianlam** [comment]
v.2.3.1 incoming...

**Comment by sweetppro** [comment]
Got it, and working great.
Thx for the quick fix
