### ISSUE TITLE
Gmail no longer providing option of "less secure apps"

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#10808]
### NodeBB version

current master

### NodeBB git hash

cba9047f67ead034ca412c36985194e27589d013

### NodeJS version

N/A

### Installed NodeBB plugins

N/A

### Database version

N/A

### Exact steps to cause this issue

Just noticed the "gmail warnings" in the email settings page: https://github.com/NodeBB/NodeBB/blob/d4e5259fcffeaba1dfffd43f559df7d195c8e7a7/src/views/admin/settings/email.tpl#L129-L134

When you click on the link about how to enable "less secure apps" it tells you that this feature is no longer available, Gmail only accepts oauth2 for third party applications if I understand this correctly. So the warning is misleading since June 1st. What worked for me is that I used the "App specific passwords" feature that can be used if 2FA is enabled on the account which basically gives you a password you can use for a specific device/application. This is also mentioned in the nodemailer docs that are referenced in the warning/info text: https://nodemailer.com/usage/using-gmail/

**Comment by julianlam** [comment]
Thanks @RoiEXLab ! That's a little disappointing but was nevertheless inevitable. I'll update the verbiage to talk about app specific passwords.

**Comment by julianlam** [comment]
App specific password works like a charm :+1:

**Comment by RoiEXLab** [comment]
@julianlam Thanks for the quick fix 👍
