### ISSUE TITLE
Prints internal error when posting a topic without a body

### ISSUE THREAD

**Issue by ravinhwg** [NodeBB/NodeBB#10831]
### NodeBB version

v2.4.0

### NodeBB git hash

55254422794f9d221a996d306c5ab44c33989057

### NodeJS version

v16.16.0

### Installed NodeBB plugins

	* nodebb-plugin-2factor@5.0.2 (installed, disabled)
	* nodebb-plugin-composer-default@8.0.0 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
	* nodebb-plugin-emoji@4.0.4 (installed, enabled)
	* nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
	* nodebb-plugin-google-analytics@0.6.3 (installed, enabled)
	* nodebb-plugin-imgur@2.0.5 (installed, enabled)
	* nodebb-plugin-markdown@10.1.0 (installed, enabled)
	* nodebb-plugin-mentions@3.0.11 (installed, enabled)
	* nodebb-plugin-ns-embed@6.0.0 (installed, enabled)
	* nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
	* nodebb-plugin-tenor-gif@2.2.0 (installed, enabled)
	* nodebb-plugin-twitter@0.1.0 (installed, disabled)
	* nodebb-rewards-essentials@0.2.1 (installed, enabled)
	* nodebb-theme-lavender@6.0.0 (installed, disabled)
	* nodebb-theme-persona@12.1.0 (installed, enabled)
	* nodebb-theme-slick@2.0.2 (installed, disabled)
	* nodebb-theme-vanilla@12.1.18 (installed, disabled)
	* nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

MongoDB

### Database version

 v5.0.10

### Exact steps to cause this issue

1. Enable new topics without a post on ACP. (Setting minimum post length to 0)
2. Start a new topic without a post.
3. Shows error saying that "sizeCalculation return invalid (expect positive integer)" and does not get navigated out of the composer window.  
4. However the new topic gets posted 
5. Upon navigation to the new topic that got posted without a post it throws an error saying "sizeCalculation return invalid (expect positive integer)"

### What you expected

The topic to successfully get posted without throwing error messages in the composer window and the topic to get properly displayed 

### What happened instead

1. Shows an error message saying "sizeCalculation return invalid (expect positive integer)" in the composer but looks like the topic got posted in the background.
2. Shows the same error upon navigation to the topic. 

### Anything else?

New topics with an intial post does not show cause any errors.

Logger output:
2022-08-13T04:17:34.938Z [4567/182203] - [31merror[39m: GET /api/topic/23/today-is-the-international-left-handers-day/1?_=1660364189026
TypeError: sizeCalculation return invalid (expect positive integer)
    at LRUCache.requireSize (/home/forumadmin/nodebb/node_modules/lru-cache/index.js:379:19)
    at LRUCache.set (/home/forumadmin/nodebb/node_modules/lru-cache/index.js:575:17)
    at Object.cache.set (/home/forumadmin/nodebb/src/cache/lru.js:65:12)
    at Posts.parsePost (/home/forumadmin/nodebb/src/posts/parse.js:66:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Posts.getPostsByPids (/home/forumadmin/nodebb/src/posts/index.js:48:10)
    at async Topics.getTopicPosts (/home/forumadmin/nodebb/src/topics/posts.js:47:18)
    at async Promise.all (index 0)

When upgrading from the pervious version of nodebb this dep caused issues. Resolved the issue by following issue #10817

**Comment by ravinhwg** [comment]
@oplik0 is there anything we can do to fix the issue in our instance?

**Comment by oplik0** [comment]
Right now? You can manually add this change - either by cherry-picking it with git, or (since it's a very simple change) just using some text editor to change `src/posts/cache.js`.

If you want to go with the cherry-pick route, you'll need to first fetch the branch from my fork:
```bash
git fetch https://github.com/oplik0/NodeBB.git fix-cache-size-calculation
git cherry-pick 83e0413187c4d1ddef96c8fc8711d229569f2d5c
```

For the second route just look at the 4 character change in https://github.com/oplik0/NodeBB/commit/83e0413187c4d1ddef96c8fc8711d229569f2d5c and apply it manually to `src/posts/cache.js`.
