### ISSUE TITLE
Add a way to export user content via the REST API

### ISSUE THREAD

**Issue by oplik0** [NodeBB/NodeBB#10834]
### Description

The read API contains three export endpoints (`/api/user/{userslug}/export/posts`, `/api/user/{userslug}/export/uploads` and `/api/user/{userslug}/export/profile`) that for anyone actually wanting to get these files programatically will appear not to work.
The reason is that they don't actually try exporting anything, instead only letting one download a pre-existing export, which is done via users rights and consent page, or socket.io (there doesn't appear to be anything in write API related to this functionality).

So it'd be good to either have these endpoints try generating the export if it doesn't exist yet, or have new endpoint(s) for that purpose.

EDIT: this actually worked in the past. It's a regression back from v1.14, caused by this commit https://github.com/NodeBB/NodeBB/commit/8383992dccf4c84fcc4fbb5cdb2b99d7f8637b6f

### Community forum reference

https://community.nodebb.org/topic/16615/export-user-s-posts-in-csv

**Comment by julianlam** [comment]
Yeah makes sense. A new set of API routes would be handy.

* [ ] `POST` routes to generate a new export
* [ ] Restrict generations to one a day unless admin
* [ ] `HEAD` to return `Last-Modified` or `HTTP 204` if no export generated
* [ ] `GET` sends the file, or `HTTP 204` if no export generated

Likely will follow the existing schema: `/api/v3/users/{uid}/export/posts`, and so on...
