### ISSUE TITLE
Delete Account isSelf failing

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#10849]
The below line seems to be comparing an int to a string (at least in my envs). The caller.uid looks like it needs a parseInt round it.

https://github.com/NodeBB/NodeBB/blob/77e492b8d728912321db7cc2e99277587c61446d/src/api/users.js#L308

**Comment by barisusakli** [comment]
Are you using delete account from the user profile page?

**Comment by barisusakli** [comment]
caller.uid comes from either `socket.uid` or `req.uid` both are numbers, I added a parseInt just in case it is being called from somewhere else with a string

**Comment by uplift** [comment]
> Are you using delete account from the user profile page?

Its through the API
