### ISSUE TITLE
[bug] req.logout is not a function - v2.4.3

### ISSUE THREAD

**Issue by lslzl3000** [NodeBB/NodeBB#10847]
### NodeBB version

v2.4.3

### NodeBB git hash

9c647c6ce22a0e589fc64c4c5abc0d1906287566

### NodeJS version

v14.19.0

### Installed NodeBB plugins

Active plugins:
	* nodebb-plugin-2factor@5.0.2 (installed, disabled)
	* nodebb-plugin-alioss-new@1.0.2 (installed, enabled)
	* nodebb-plugin-composer-default@8.0.0 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
	* nodebb-plugin-emailer-aliyun-dm@1.0.0 (installed, enabled)
	* nodebb-plugin-emoji@4.0.4 (installed, enabled)
	* nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
	* nodebb-plugin-google-analytics@0.6.3 (installed, enabled)
	* nodebb-plugin-markdown@10.1.0 (installed, enabled)
	* nodebb-plugin-mentions@3.0.11 (installed, enabled)
	* nodebb-plugin-night-mode@1.0.7 (installed, disabled)
	* nodebb-plugin-ns-embed@6.0.0 (installed, enabled)
	* nodebb-plugin-spam-be-gone@1.0.0 (installed, enabled)
	* nodebb-plugin-sso-github@2.3.2 (installed, enabled)
	* nodebb-rewards-essentials@0.2.1 (installed, enabled)
	* nodebb-theme-lavender@6.0.0 (installed, disabled)
	* nodebb-theme-persona@12.1.0 (installed, enabled)
	* nodebb-theme-slick@2.0.2 (installed, disabled)
	* nodebb-theme-vanilla@12.1.18 (installed, disabled)
	* nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

MongoDB

### Database version

v5.0.3

### Exact steps to cause this issue

1. login first
2. try `logout` button in user menu

### What you expected

logout successfully

### What happened instead

1. nothing happened for the web
2. server log error

![Screen Shot 2022-08-18 at 15 36 45](https://user-images.githubusercontent.com/3398981/185337397-d1c65d06-3488-425d-a39d-320b8617561d.png)

**Comment by barisusakli** [comment]
@lslzl3000 thanks for reporting, fixed in 2.4.4
