### ISSUE TITLE
Uploading a file with a disallowed extension shows error message in resulting markdown

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10846]
![image](https://user-images.githubusercontent.com/923011/185271407-7f25ba7f-09a1-4ad4-88d2-208c0aedcb39.png)

Not certain if this was done on purpose, but the error should be in a toast.

**Comment by barisusakli** [comment]
I actually did this on purpose, https://github.com/NodeBB/nodebb-plugin-composer-default/commit/b1a9dba20fa144bea1bdaeabad0544b94da4b5ac

The error should be displayed in an alert.error() as well https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer/uploads.js#L256

Before this change when the upload failed the composer text would stay as `[derp.html](Uploading 100%)` and you would only get an alert.

**Comment by julianlam** [comment]
Thanks for the context! That's exactly what I was looking for.

I didn't actually see the toast, so that might need to be looked into. I'm assuming it wasn't possible to just remove the markdown code completely?
