### ISSUE TITLE
Cannot change email

### ISSUE THREAD

**Issue by quarhodron** [NodeBB/NodeBB#10841]
### NodeBB version

2.4.0

### NodeBB git hash

4834cde335aa500eb3a4cad903345ebb36c4a499

### NodeJS version

16.16.0

### Installed NodeBB plugins

the default ones. Any other was removed or added.

### Database type

MongoDB

### Database version

5.0.10

### Exact steps to cause this issue

1. Go to my profile
2. Click change email
3. Change email to something else
4. Click submit

### What you expected

I expected a popup that says I need to verify my new email.

### What happened instead

The email screen hasn't changed and at the top of the page is a warning in a yellow box that says:
Please review the entered information
Błędne hasło (that means wrong password in polish) 

### Anything else?

Language version: polish, admin panel in english if that matters

**Comment by julianlam** [comment]
Hi @quarhodron thanks for reporting. When you attempt to change your email, do you see a password field in the email change screen? It should challenge you to enter your password as a security measure.

Alternatively, do you not have a password set on your account?

**Comment by quarhodron** [comment]
A password is set on an account. It's the same as was given during registration.

There is no password field in the email change screen. But there isn't such a field on https://community.nodebb.org/register/complete.

**Comment by julianlam** [comment]
Thanks for reporting!
