### ISSUE TITLE
viewcount ignored when creating topic via API

### ISSUE THREAD

**Issue by PatrickLaferl** [NodeBB/NodeBB#10850]
### NodeBB version

2.4.4

### NodeBB git hash

d5525c873b8c0f15c9a65cebd7a65e17f65b43da

### NodeJS version

v16.14.2

### Installed NodeBB plugins

        * nodebb-plugin-2factor@5.0.2 (installed, disabled)
        * nodebb-plugin-composer-default@8.0.0 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
        * nodebb-plugin-emoji@4.0.4 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-markdown@10.1.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.11 (installed, enabled)
        * nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-persona@12.1.0 (installed, enabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.18 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)
        * nodebb-widget-search-bar@1.1.2 (installed, disabled)

### Database type

MongoDB

### Database version

v5.0.10

### Exact steps to cause this issue

POST a new topic via the API, setting the `viewcount` field to a non-zero positive number.

### What you expected

The provided number should be reflected in the displayed view count of the topic.

### What happened instead

The topic has a view count of zero.

### Anything else?

I am migrating from a different forum and need to preserve all data.
Setting the `timestamp` field on a topic works, but the `viewcount` does not.

**Comment by barisusakli** [comment]
How are you calling the topic create function? Might be better to set viewcount after topic is created. If we add code to allow setting viewcount via the api route then people can make calls to from the clientside to create topics with arbitrary viewcounts.

**Comment by PatrickLaferl** [comment]
Calling like this:
`POST /api/v3/topics/`
Headers:
```
	Authorization: Bearer <my-token>
	Content-Type: application/json
```
Body:
```
	title: ...
	content: ...
	timestamp: ...
	viewcount: ...
	...
```

**Comment by julianlam** [comment]
Using the v3 API in this manner is definitely a possibility, but as Baris mentioned, it comes with safeguards to prevent users from doing unexpected things.

It's too late now, but for others, the best way to migrate data into NodeBB would be to use something like [nodebb-plugin-import](https://github.com/akhoury/nodebb-plugin-import) which uses internal API methods to bypass sanity checks like this.
