### ISSUE TITLE
How can I find who visit the topic?

### ISSUE THREAD

**Issue by tanxi** [NodeBB/NodeBB#10866]
### Description

I am a new user for NodeBB, I use NodeBB for an internal community, and I config Google SSO for user login.
Now I want to know who has visited the topics, so I can know who don't visit the topic, I need to ask people who don't visit the topic to visit it.

Now I can use the admin Dashboard, but it just can see how many people had visited the topic, but don't know who visited it.

**Comment by pitaj** [comment]
You can have them upvote the topic when they visit, and check the upvotes.

**Comment by barisusakli** [comment]
`const uids = await db.getSortedSetRange(`tid:${tid}:bookmarks`, 0, -1);`  This will give you the uids of the users who have read a topic. It is only updated for topics that have more than `meta.config.bookmarkThreshold` posts, you can modify that value in the ACP (Minimum posts in topic before tracking last read), the default is 5.
