### ISSUE TITLE
npm test giving error for the first time setup

### ISSUE THREAD

**Issue by kreloaded** [NodeBB/NodeBB#10860]
### NodeBB version

2.4.5

### NodeBB git hash

b424ba46379b1f0ee62dfed613aa32fa6ee5ef38

### NodeJS version

v16.15.1

### Installed NodeBB plugins

* nodebb-plugin-2factor@5.0.2 (installed, disabled)
	* nodebb-plugin-composer-default@8.0.0 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.5 (installed, disabled)
	* nodebb-plugin-emoji@4.0.4 (installed, enabled)
	* nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
	* nodebb-plugin-markdown@10.1.0 (installed, enabled)
	* nodebb-plugin-mentions@3.0.11 (installed, enabled)
	* nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
	* nodebb-rewards-essentials@0.2.1 (installed, enabled)
	* nodebb-theme-lavender@6.0.0 (installed, disabled)
	* nodebb-theme-persona@12.1.0 (installed, enabled)
	* nodebb-theme-slick@2.0.2 (installed, disabled)
	* nodebb-theme-vanilla@12.1.18 (installed, disabled)
	* nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

Redis

### Database version

v7.0.0

### Exact steps to cause this issue

1. I started performing steps from this [doc](https://docs.nodebb.org/installing/os/osx-mavericks/). 
2. The `./nodebb setup` step worked fine. Chose required redis db configurations.
3. Executed `./nodebb start` and confirmed whether nodebb is working fine or not. It is working!
4. Tried to run test cases using: `npm test`
5. Received a following error:
<img width="577" alt="Screenshot 2022-08-23 at 11 46 19 AM" src="https://user-images.githubusercontent.com/26052182/186084382-9ff5c3f1-69b0-463d-9745-fed9bdfbf760.png">

### Anything else?

The issue got resolved after installing npm packages exclusively using `npm install`. But, I consider the `npm install` should be there in the **setup** stage only!

**Comment by julianlam** [comment]
nyc is used during development mode, so NodeBB setup doesn't install it.
