### ISSUE TITLE
All screens are empty - Eg: Categories, Unread, Tags

### ISSUE THREAD

**Issue by hari-iouring** [NodeBB/NodeBB#10869]
### NodeBB version

v2.5.0

### NodeJS version

v16.17.0

### Installed NodeBB plugins

Active plugins:
        * nodebb-plugin-2factor@5.0.2 (installed, disabled)
        * nodebb-plugin-composer-default@8.0.0 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, disabled)
        * nodebb-plugin-emoji@4.0.4 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-markdown@10.1.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.11 (installed, enabled)
        * nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-persona@12.1.0 (installed, enabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.18 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

MongoDB

### Database version

bionic

### Exact steps to cause this issue

1. Checked out the master branch v2.5.0 and setup NodeBB with MongoDB as database and Nginx as the reverse proxy.
2. Installation was done with Docker Compose. Installation was successful. Admin user is created from Web.
3. After installation feature sections - Categories, Register, Login , etc all the contents while clicking from links are getting blank.  When refreshing the screen ( ctrl + r ), the page is appearing.  Tested with Chrome, Mobile browser, Firefox etc all are showing same error.

From chrome console, one error is keep emitting attached the screenshots.

Verified the network ( https, websocket, Nginx logs), data transfer looks fine not seeing any failures. 

Chrome version: 104.0.5112.82

### What you expected

All screens should be displaying properly

### What happened instead

![image](https://user-images.githubusercontent.com/102995221/187143281-ffc53d1d-3f0d-490c-a481-fac3c3ad9f62.png)

**Comment by pitaj** [comment]
Is there a reason you're installing the master branch? We recommend installing based on the version branches instead.

**Comment by hari-iouring** [comment]
@pitaj - I tried the following release branch also and facing the same issue

  https://github.com/NodeBB/NodeBB/tree/v2.x

**Comment by barisusakli** [comment]
An empty page usually means you are connected to a an empty/wrong database. Check your config.json and make sure the database connected is correct and has the data from `./nodebb setup`
