### ISSUE TITLE
Problem in validating users

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#10878]
### NodeBB version

v2.2.5

### Database type

MongoDB, Redis

### Database version

mongodb Version 4.2.20 ,  Redis Version 7.0.0

### Exact steps to cause this issue

We used to set the Registration Type to Admin Invite Only and use nodebb-plugin-sso-google plugin
 for registration, and the privileges were active for all registered-users.

But after we changed the Registration Type to normal mode
And we activated privileges only for verified-users
Some of our previous verified users are not identified
Even though their email address is shown as verified in the ACP, therefore, these users cannot do any activity, can't post
can't create topic ,...

**Comment by julianlam** [comment]
Are the users not in the `validated-users` group? Does it affect all user who registered using sso-google?

**Comment by roghaye-m** [comment]
> Does it affect all user who registered using sso-google?

Where can I access the members of this group? This group is not displayed in the list of groups

**Comment by barisusakli** [comment]
Is autoconfirm turned on in google sso plugin page? 
![image](https://user-images.githubusercontent.com/2583394/201370057-0986b297-2ffb-45bd-9ce1-52b5a16a63ee.png)

Without that turned on users will need to click the confirm link in the email sent. Also the acp uses `email:confirmed` field in the user object to display the value but if for whatever reason the user wasn't added to the `verified-users` group they won't get the permissions.

You can confirm by checking the account of a user that has this problem. 

First check if the value of `email:confirmed` in the user object by `db.objects.findOne({_key: "user:<uid>"});`

Then check if they are in the `verified-users` group with `db.objects.find({_key: "group:verified-users:members", "value: "<uid_of_user>"});`
