### ISSUE TITLE
$.timeago is undefined

### ISSUE THREAD

**Issue by nebulade** [NodeBB/NodeBB#10877]
### NodeBB version

v2.5.2

### NodeJS version

v16.13.1

### Installed NodeBB plugins

no plugins

### Database type

MongoDB

### Database version

v5

### Exact steps to cause this issue

Loading the main page works fine, but shows the error pasted below about `$.timeago` being undefined already in the console. The admin app entry point mostly works as well, but some pages won't work like the email settings, where it seems that exception makes the code stop at more crucial points.

For the trace I added `console.logs()` to the timeago module.

### What you expected

On loading the page, the two console logs from the timeago module are shown and it attaches fine to jquery. Later during the page load, the timeago jquery plugin is gone. I wasn't able to find where and how this could have been removed or maybe `$` got replaced mid-way? Not sure if this may be related to the `ServiceWorker` getting registered?

### What happened instead

webinspector console logs:

```
== registering timeago to $ [nodebb.min.js:2:372487](https://domain.com/assets/nodebb.min.js?v=94bakrlc426)
timeago on $: 
function timeago(t)
[nodebb.min.js:2:372693](https://domain.com/assets/nodebb.min.js?v=94bakrlc426)
ServiceWorker registration succeeded. [nodebb.min.js:2:51753](https://forum.nebulon.space/assets/nodebb.min.js?v=94bakrlc426)
Uncaught (in promise) TypeError: $.timeago is undefined
```

### Anything else?

This happens during the app packaging for the Cloudron package. NodeBB v2.4 works as expected, the issue started from 2.5 on.

**Comment by nebulade** [comment]
Possibly related https://github.com/rmm5t/jquery-timeago/issues/350

**Comment by nebulade** [comment]
Further a stacktrace without minification if that helps:
```
Uncaught (in promise) TypeError: $.timeago.settings is undefined
    overrideTimeagoCutoff webpack://nodebb/./build/public/src/overrides.js?:116
    overrideTimeago webpack://nodebb/./build/public/src/overrides.js?:125
    load webpack://nodebb/./build/public/src/app.js?:117
    load webpack://nodebb/./build/public/src/app.js?:121
    promise callback*app.load webpack://nodebb/./build/public/src/app.js?:103
    onDomReady webpack://nodebb/./build/public/src/app.js?:34
    jQuery 12
        mightThrow
        process
        setTimeout handler*resolve/<
        fire
        fireWith
        fire
        fire
        fireWith
        ready
        setTimeout handler*
        <anonymous>
        <anonymous>
    js https://forum.nebulon.space/assets/nodebb.min.js?v=kuobf20daeo:399
    __webpack_require__ https://forum.nebulon.space/assets/nodebb.min.js?v=kuobf20daeo:772
    <anonymous> webpack://nodebb/./build/public/src/app.js?:3
    js https://forum.nebulon.space/assets/nodebb.min.js?v=kuobf20daeo:50
    __webpack_require__ https://forum.nebulon.space/assets/nodebb.min.js?v=kuobf20daeo:772
    <anonymous> webpack://nodebb/./build/public/src/client.js?:3
    js https://forum.nebulon.space/assets/nodebb.min.js?v=kuobf20daeo:61
    __webpack_require__ https://forum.nebulon.space/assets/nodebb.min.js?v=kuobf20daeo:772
    <anonymous> https://forum.nebulon.space/assets/nodebb.min.js?v=kuobf20daeo:1051
    <anonymous> https://forum.nebulon.space/assets/nodebb.min.js?v=kuobf20daeo:1053
```

I tried to debug this, but my app init flow knowledge is still a bit too limited wrt nodebb :/

**Comment by julianlam** [comment]
Good lord.

I spent literally **hours** of my life trying to figure this one out. HOURS 😠 

The workaround is to delete node_modules and use npm to install the dependencies.

**Comment by nebulade** [comment]
oh great! Thanks for letting us know and in fact the Cloudron package uses `yarn` due to symlinking issues with `npm`...I guess I still have to get down to the root cause with `yarn` then unless we figure out how to rework the packaging.

I will post any further findings here for reference then.

**Comment by nebulade** [comment]
I compared what `npm` vs `yarn` would install in `node_modules` and it looks like `npm` flattens it much better according to semver, which means for `timeago`, yarn installs `jquery@3.6.1` while `npm` is fine for that module with `jquery@3.6.0` which is going to be installed as toplevel.

This in turn seems to make webpack produce code resulting in two jquery objects and `timeago` will be attached to the `$` of the one which is not going to be attached to `window.$` later.

I am no `yarn` expert either, but have to see why the behaviour is so different, which might result in much more unknown side-effects.

**Comment by pitaj** [comment]
Might need to add a resolutions field for yarn: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by nebulade** [comment]
This was a great hint and in fact adding the following to the `package.json` will prevent `yarn` from installing a separate `jquery` version, which in turn fixes the loading of two distinct `jquery` modules via `webpack` and the issue is then resolved.
```
  "resolutions": {
    "timeago/jquery": "3.6.0"
  },
```
Now of course this does make me wonder what else might be affected and with other node_modules in a similar way but so far got undetected. 

Not sure if it makes sense to have that `resolutions` addition in the upstream `package.json` to support `yarn`, otherwise I guess we can close this issue?

**Comment by pitaj** [comment]
I'd guess this is because we pin the jQuery version. It may also be possible to tell webpack to always use our version of jQuery, or at least warm when multiple versions of a package are included.

**Comment by pitaj** [comment]
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle

**Comment by nebulade** [comment]
To update this here, it looks like currently at least those modules will be affected if `yarn` installs different jquery versions: `timeago`, `jquery-form`, `jquery-deserialize` and `jquery-ui` as far as I can tell. I guess the main question then is, if there is any will in the project to even support a yarn installation in the first place, if so, using the suggested `resolutions` object in the `package.json` for yarn does solve the issue. Although once jquery version changes, this has to be revisited.

**Comment by julianlam** [comment]
Whether or not we will support yarn is a good question actually. I happen to be the only maintainer using it.

This issue, combined with the fact that yarn no longer installs peer dependencies, could potentially introduce complications

**Comment by pitaj** [comment]
It may be possible to set resolutions to a wildcard so as to not worry about keeping the versions in check.

**Comment by nebulade** [comment]
Actually using the following resolution for yarn, does indeed work as expected:
```
  "resolutions": {
    "*/jquery": "3.6.0"
  }
```
I guess this can be closed then, an `yarn` support at least be partially solved. It is still not clear to me how many 3rdparty plugins might face similar issues with packages other than `jquery`

**Comment by pitaj** [comment]
I meant put the wildcard on the right hand side, like so:
```
  "resolutions": {
    "*/jquery": "3.*"
  }
```

**Comment by nebulade** [comment]
Seems like adding the wildcard on the jquery version side, `yarn` will again install different `jquery` versions like `3.6.0` and `3.6.1` leading to the same `webpack` bundling issue as initially.

**Comment by Justman10000** [comment]
> Seems like adding the wildcard on the jquery version side, `yarn` will again install different `jquery` versions like `3.6.0` and `3.6.1` leading to the same `webpack` bundling issue as initially.

Why should yarn do this but not NMP? Where's the logic?

**Comment by Justman10000** [comment]
Surely the yarn developers should know that this causes errors?

**Comment by julianlam** [comment]
@pitaj is this worth adding `resolutions` to `install/package.json`? We'll just have to take care to keep it up to date with the installed jQuery version.

**Comment by pitaj** [comment]
I certainly think it's worth it, yeah

**Comment by julianlam** [comment]
@nebulade Sorry for the delay in getting this fixed. Since this only bit yarn installs, let me know if you need me to publish a new patch version on the v2.x branch.

Thank you to both you and @pitaj for doing the legwork on this. I can say confidently that I would never have found this solution, even if simple :smile:
