### ISSUE TITLE
[[error:invalid-files]] when uploading images via API

### ISSUE THREAD

**Issue by hnipps** [NodeBB/NodeBB#10899]
### NodeBB version

v2.3.1

### NodeBB git hash

Not sure, moved into my own monorepo and removed `.git/`

### NodeJS version

v16.13.2

### Installed NodeBB plugins

Active plugins:
        * nodebb-plugin-2factor@5.0.1 (installed, disabled)
        * nodebb-plugin-composer-default@8.0.0 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, disabled)
        * nodebb-plugin-emoji@4.0.4 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-markdown@10.0.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.11 (installed, enabled)
        * nodebb-plugin-session-sharing@5.1.9 (installed, disabled)
        * nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
        * nodebb-plugin-sso-lit-protocol@1.3.0-alpha-1 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-persona@12.0.14 (installed, enabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.18 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

PostgreSQL

### Database version

v14 (latest docker image)

### Exact steps to cause this issue

Attempting to upload profile image via API like so:
```ts
  const formData = new FormData();

  formData.append("file", file); // file is a jpeg image File

  return fetch(`/api/user/${uid}/uploadpicture`, {
    method: "POST",
    body: formData,
    headers: {
      "x-csrf-token": config.csrf_token,
    },
  });
```

### What you expected

Image is uploaded and associated with user's profile.

### What happened instead

I get a 500 error and the NodeBB logs show:
```
2022-09-16T19:56:23.829Z [4567/12458] - error: POST /api/user/1/uploadpicture
Error: [[error:invalid-files]]
    at validateFiles (/Users/<USER>/repos/member-directory/api/src/middleware/index.js:113:15)
    at Layer.handle [as handle_request] (/Users/<USER>/repos/member-directory/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/<USER>/repos/member-directory/api/node_modules/express/lib/router/route.js:144:13)
    at Form.<anonymous> (/Users/<USER>/repos/member-directory/api/node_modules/connect-multiparty/index.js:114:7)
    at Form.emit (events.js:412:35)
    at /Users/<USER>/repos/member-directory/api/node_modules/multiparty/index.js:612:12
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by barisusakli** [comment]
Have you tried putting the file in `formData.files = [jpegFiles];` Take a look at our test that uploads images. https://github.com/NodeBB/NodeBB/blob/master/test/helpers/index.js#L121-L136

Server side expects a `req.files.files` array https://github.com/NodeBB/NodeBB/blob/master/src/middleware/index.js#L105

Maybe try

```
  const formData = new FormData();

  formData.append("files[]", file); // file is a jpeg image File

  return fetch(`/api/user/${uid}/uploadpicture`, {
    method: "POST",
    body: formData,
    headers: {
      "x-csrf-token": config.csrf_token,
    },
  });
```

**Comment by hnipps** [comment]
Thank you @barisusakli !

This worked after switching `uid` for `userslug`:
```
  const formData = new FormData();

  formData.append("files[]", file); // file is a jpeg image File

  return fetch(`/api/user/${userslug}/uploadpicture`, {
    method: "POST",
    body: formData,
    headers: {
      "x-csrf-token": config.csrf_token,
    },
  });
```
