### ISSUE TITLE
The image of a category does not display in the bubble of the taskbar when creating a new topic

### ISSUE THREAD

**Issue by DroidBV8** [NodeBB/NodeBB#10896]
### NodeBB version

2.5.2

### NodeBB git hash

babcd17e6c091156eee429a936fba9aa5df9bc13

### NodeJS version

v16.17.0

### Installed NodeBB plugins

* @nodebb/nodebb-plugin-reactions@1.0.2 (installed, disabled)
 * @nodebb/nodebb-plugin-user-level@1.0.4 (installed, disabled)
 * nodebb-plugin-2factor@5.0.2 (installed, disabled)
 * nodebb-plugin-browsing-users@2.0.4 (installed, disabled)
* nodebb-plugin-cards@0.3.1 (installed, disabled)

        * nodebb-plugin-composer-default@9.1.0 (installed, enabled)
        
* nodebb-plugin-dbsearch@5.1.5 (installed, disabled)
* nodebb-plugin-emoji@4.0.4 (installed, disabled)
* nodebb-plugin-emoji-android@3.0.0 (installed, disabled)
* nodebb-plugin-extended-markdown@1.6.0 (installed, disabled)
* nodebb-plugin-global-chat@2.0.0 (installed, disabled)
* nodebb-plugin-iframely@0.7.16 (installed, disabled)
* nodebb-plugin-markdown@10.1.0 (installed, disabled)
* nodebb-plugin-mentions@3.0.11 (installed, disabled)
* nodebb-plugin-ns-embed@6.0.0 (installed, disabled)
* nodebb-plugin-osm-map@1.0.1 (installed, disabled)
* nodebb-plugin-poll@2.0.6 (installed, disabled)
* nodebb-plugin-question-and-answer@0.12.25 (installed, disabled)
* nodebb-plugin-recent-cards@2.0.22 (installed, disabled)
* nodebb-plugin-soundpack-default@2.0.2 (installed, disabled)
* nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
* nodebb-plugin-tenor-gif@2.2.0 (installed, disabled)
* nodebb-plugin-twitter@0.1.0 (installed, disabled)
* nodebb-plugin-view-votes@1.0.0 (installed, disabled)
 * nodebb-plugin-ws-dice@2.5.0 (installed, disabled)
* nodebb-plugin-youtube-embed@0.6.9 (installed, disabled)
* nodebb-rewards-essentials@0.2.1 (installed, disabled)
* nodebb-theme-lavender@6.0.0 (installed, disabled)

        * nodebb-theme-persona@12.1.1 (installed, enabled)
        
* nodebb-theme-slick@2.0.2 (installed, disabled)
* nodebb-theme-vanilla@12.1.18 (installed, disabled)
* nodebb-widget-essentials@6.0.0 (installed, disabled)

### Database type

MongoDB

### Database version

v5.0.12

### Exact steps to cause this issue

gif N°1:

1. On ACP/management/category, I add an image on a category, I select no icon and I save.
2.  On this modified category, i open a new topic
3. The image category doesn't appeear, just the color background.

-- When I open a new topic, the image category on the bottom bubble taskbar does not appear 

-- On dev console browsers, I see the url of file image is not encode properly, if I change it manually, the image appears on the bubble (gif N°2)

Here is the gif N°1 & N°2 for see the problem:

![new topic](https://user-images.githubusercontent.com/71468154/190502611-2e37562d-aca7-4486-b8a6-5e07d22b9e85.gif)
![new topic 2](https://user-images.githubusercontent.com/71468154/190503019-2d74cb8e-771f-40aa-a96f-b74104349af1.gif)

### What you expected

That the image configured in the category is displayed correctly in the bubble of the taskbar when creating a new subject in this category or another for that matter

### What happened instead

The image does not appear in the bubble when creating a new topic

### Anything else?

I have tested external url and internal url for the image = same
I have disable all custom CSS, custom JS, custom header, custom widgets and all the plugins on ACP = same

**Comment by barisusakli** [comment]
regression from https://github.com/NodeBB/NodeBB/commit/67cb70352f994d8fab3477f0d753e0dd588bab70
