### ISSUE TITLE
Data export in Your Rights & Consent not working

### ISSUE THREAD

**Issue by sqlik** [NodeBB/NodeBB#10906]
### NodeBB version

2.5.2

### Database type

MongoDB, Redis

### Exact steps to cause this issue

When the user tries to download his data, an error is shown
/user/{user}/consent

[screenshot-1](https://p212.p2.n0.cdn.getcloudapp.com/items/eDu7PDn4/e59c179e-ce1c-4f70-ab28-bc2a3eef2100.png?v=64d5ddf74001153751046c2f69e9d7a7)

It is also not possible to download from the administrator account.
[screenshot-2](https://p212.p2.n0.cdn.getcloudapp.com/items/P8u7yq2A/bdc9347a-6806-4865-9acc-91628037d09e.png?v=39e4f7da4e1cfa6ba448132d00d70acd)

### What you expected

User can download his data .json, .csv and .zip

**Comment by barisusakli** [comment]
Regression from https://github.com/NodeBB/NodeBB/commit/d05705183f3eb0cde6c3bce3a814a6a5c31117ed

**Comment by julianlam** [comment]
The ur provided in the notification was not properly updated.

**Comment by julianlam** [comment]
Ah, no, the old route still exists, but is just deprecated.
