### ISSUE TITLE
Email domain limitation (whitelist/blacklist)

### ISSUE THREAD

**Issue by floufille** [NodeBB/NodeBB#10919]
### Description

NodeBB version: 2.5.2

Since one month, i've faced to some bot that are trying to register to the forum, and try to post spam (in profile description).

spams are blocked, because user registration has failed, but i need to delete manually severals bot users per days.

I saw a plugin was developped, some times ago, and julianlam contributes to it https://github.com/NodeBB-Community/nodebb-plugin-email-blacklist , from a fork of: https://community.nodebb.org/topic/10434/registration-email-domain-blacklisting .

I would like to know if it is possible to update the plugin, or to integrate this feature directly in NodeBB.

If it is not possible, i'd like to know what i have to change in the source code to block a domain in the registration process. I think there is something to change in the _registration.js_ file, but i'm not totally sure if it is the good place.

NB: In this case, the bots are always using the same registration domain. nginx rules are not sufficient to block them (ip are changing every days, user agent is up to date).

**Comment by AliCihan** [comment]
I think since providing an email address is optional now, the plugin will not work... 

https://community.nodebb.org/post/87536

But, I do support your idea. At least, for those forums (like us) that will always require email confirmation, it would be great if this plugin is updated so at least we can clear the forum from "obvious" spam addresses...

**Comment by julianlam** [comment]
No, those plugins will not work anymore. However, they can be updated to add additional validation, so that the existing email interstitial will not succeed.

At least, that is the idea

**Comment by julianlam** [comment]
The email-blacklist plugin was just updated for v2 support.

https://github.com/NodeBB-Community/nodebb-plugin-email-blacklist/
