### ISSUE TITLE
bottom sheet height incorrect 

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#10935]
some elements hidden
![image](https://user-images.githubusercontent.com/2583394/193651980-7be5bc71-8d98-4047-b3e7-7671bb3914e8.png)

**Comment by julianlam** [comment]
Can't seem to reproduce this one actually

**Comment by barisusakli** [comment]
Seems like only repros if the site title is long enough to push the profile image out of viewport, try it with a long site title

**Comment by barisusakli** [comment]
fixed in https://github.com/NodeBB/nodebb-theme-persona/commit/4906bfdc182ceada74a910f3de18b00b90ad61bf
https://css-tricks.com/flexbox-truncated-text/
