### ISSUE TITLE
TypeError: $.timeago is undefined

### ISSUE THREAD

**Issue by Justman10000** [NodeBB/NodeBB#10946]
### NodeBB version

2.5.3

### NodeJS version

Runned with _v16.17.1_ and _v18.10.0_

### Installed NodeBB plugins

* nodebb-plugin-2factor@5.0.2 (installed, enabled)
* nodebb-plugin-composer-default@9.1.1 (installed, enabled)
* nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
* nodebb-plugin-emoji@4.0.4 (installed, enabled)
* nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
* nodebb-plugin-markdown@10.1.0 (installed, enabled)
* nodebb-plugin-mentions@3.0.11 (installed, enabled)
* nodebb-plugin-spam-be-gone@1.0.0 (installed, enabled)
* nodebb-rewards-essentials@0.2.1 (installed, enabled)
* nodebb-theme-lavender@6.0.0 (installed, disabled)
* nodebb-theme-persona@12.1.1 (installed, enabled)
* nodebb-theme-slick@2.0.2 (installed, disabled)
* nodebb-theme-vanilla@12.1.18 (installed, disabled)
* nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

PostgreSQL

### Database version

15beta4

### Exact steps to cause this issue

1. Visit your NodeBB instance
2. Click on any tab (e.g Groups)

### What you expected

The tab loaded

### What happened instead

White screen in the tab, instead of loading!

![grafik](https://user-images.githubusercontent.com/49990629/194708268-33a9e8d9-c481-45cb-b88d-e4a8eb387267.png)

### Anything else?

Full error:

![grafik](https://user-images.githubusercontent.com/49990629/194708297-9edc0888-223f-421b-b9c1-6653fe0328de.png)

<br>
According to VS Code, $.timeago is used in quite a few files, but it's really not declared anywhere!

**Comment by julianlam** [comment]
#10877.

Use npm for now.
