### ISSUE TITLE
v3.0.0-alpha.1 admin menus not working

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#10942]
### NodeBB version

v3.0.0-alpha.1

### NodeJS version

v18.10.0

### Database type

PostgreSQL

### Exact steps to cause this issue

Clean install
logged in to admin panel
no menus are showing on clicking
urls do resolve if manually entered though

**Comment by julianlam** [comment]
They work on our dev environments (believe me when I say that we'd notice if they didn't work 😝)

Please let me know if there are client side errors.

**Comment by sweetppro** [comment]
The menus work on mobile, but not on desktop - the drop down menus just don't show.
**macOS 12.6
Safari 16.0
FireFox 105.0.2**

Here's some errors on the **Logs** tab:
```
[Error] Failed to load resource: the server responded with a status of 404 () (advanced-logs.da26440c43fd6771ffb7.min.js, line 0)
[Error] Refused to execute https://test.nodebb3.com/assets/admin/advanced-logs.da26440c43fd6771ffb7.min.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
```

The **Themes** tab never loads and has the following errors:
```
[Error] Failed to load resource: the server responded with a status of 404 () (appearance-themes.e29aa577d05b1a7eeda6.min.js, line 0)
[Error] Refused to execute https://test.nodebb3.com/assets/admin/appearance-themes.e29aa577d05b1a7eeda6.min.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
```

**Comment by julianlam** [comment]
Hmm... unfortunately I can't reproduce this, the admin menus work just fine on my local build of v3.0.0-alpha.1

Did `./nodebb upgrade` complete with no errors? Perhaps run it again and let us take a look at the log.

**Comment by sweetppro** [comment]
that didn't help.... no errors, and the same behaviour

I tried the following commands:
```
./nodebb reset -p
./nodebb build
```

and got these build errors:
```
ERROR in ./build/public/src/client/chats.js
Module not found: Error: Can't resolve 'composer/autocomplete' in '/var/www/vhosts/sweetpproductions.com/test.sweetpproductions.com/NodeBB/build/public/src/client'

ERROR in ./build/public/src/modules/topicThumbs.js 65:10-68:12
Module not found: Error: Can't resolve 'composer' in '/var/www/vhosts/sweetpproductions.com/test.sweetpproductions.com/NodeBB/build/public/src/modules'

webpack 5.74.0 compiled with 2 errors in 24895 ms
```

**Comment by sweetppro** [comment]
@pitaj yup, that did it!
thanks
👍
