### ISSUE TITLE
V3 custom child theme and overrides.scss 

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#10951]
### NodeBB version

V3.0.0-alpha

### NodeJS version

V18.10

### Database type

PostgreSQL

### Exact steps to cause this issue

Install custom child theme (persona)

### What you expected

A clean build

### What happened instead

Crashing when building styles
Nodebb can’t find scss/overrides.scss

### Anything else?

I got it building by copying scss/overrides.css to my theme

**Comment by sweetppro** [comment]
Here is my working (but unfinished) v3 child theme: https://github.com/sweetppro/nodebb-theme-sweetp/tree/nodebb-v3

**Comment by barisusakli** [comment]
Nice we shouldnadd this to breaking changes blog post. overrides.scss is required if you are building anew theme in v3

**Comment by julianlam** [comment]
I can add, but why is it erroring out?

I see the file in `public/scss/overrides.scss`, so the (empty) file should be found and included in the build, no?

**Comment by julianlam** [comment]
Added to migration guide.
