### ISSUE TITLE
QOL updates to email confirmation

### ISSUE THREAD

**Issue by ayyilmaz** [NodeBB/NodeBB#10954]
### NodeBB version

2.5

### NodeJS version

16.x

### Database type

MongoDB, Redis

### Exact steps to cause this issue

1. Go to https://community.nodebb.org/
2. Click Register button and select one of the alternative regsiters (githup, google, facebook, twitter)
3. Register via accept conditions at opened modal or page.
4. Yes we have registered but nodebb also send us an confirmation email.
5. Click to confirmation link at the email
6. Link redirect us to forum and give error this link is not work etc.

### What you expected

We should not get any confirmation if we register 3rd party systems which are presented forum.

### What happened instead

system send us confirmation email although we register with trusted social media or 3rd party services and confirmation link is missed, does not work.

**Comment by julianlam** [comment]
We can't blindly trust that emails set back by SSO providers can be trusted, so we usually request confirmation anyway.

If the link doesn't work that's likely a bug. What was the link presented to you?

**Comment by oplik0** [comment]
Note that plugins can bypass this - for example [nodebb-plugin-sso-google](https://github.com/julianlam/nodebb-plugin-sso-google) has a toggle in ACP for skipping email verification when users register via Google.

So if you need this feature from a specific plugin you might want to open an issue there or add it there yourself.

One possible issue is that I think NodeBB will still send the email when creating the user - perhaps there could be a flag added to `user.create` to skip sending the validation email (either auto validate it or just skip and let the caller handle that instead)

**Comment by ayyilmaz** [comment]
> We can't blindly trust that emails set back by SSO providers can be trusted, so we usually request confirmation anyway.
> 
> If the link doesn't work that's likely a bug. What was the link presented to you?

I clicked to verify button at email and this directed me to the link and I get error:

https://community.nodebb.org/confirm/b9460037-1118-4689-ad5f-8ea98d8fbf1e

**Comment by julianlam** [comment]
Hi @ayyilmaz — it is likely that the confirmation key has expired and will not function anymore.

I am seeing if is still a way to re-send that validation email, or whether it was accidentally removed.

**Comment by AliCihan** [comment]
@julianlam I see this being a problem for us... 10 minutes is very short :D 

Do you think that we will encounter any problem if we change that to "1 week"? I mean security-wise etc.

**Comment by julianlam** [comment]
I have identified the following items that need attention:

Resending an email confirmation is only applicable to users who have an email explicitly set in their user hash, which really only happens with old accounts w/ unconfirmed emails, or SSO users. It is in our best interest to redirect users to the email change flow.

* [ ] `emailConfirmInterval` should be deprecated
* [ ] The existing prompt to resend validation email should send users to `/me/edit/email` (the form will be pre-filled since the email is already set in their user hash)
* [ ] `user.emailConfirm` can probably be removed?

The existing `emailConfirmInterval` is quite short

* [ ] Introduce a new ACP setting for expiration of the confirmation link, with a sensible default (e.g. 24 hours)

**Comment by julianlam** [comment]
@AliCihan You can change the existing value to something higher, yes. It is only used in two places:

* As a delay between re-sending email confirmations
* To instruct the database to expire the confirmation link (which I think was an unintentional use of that ACP setting)

**Comment by AliCihan** [comment]
@julianlam thanks for the update...

**Comment by julianlam** [comment]
Fixed in #10987
