### ISSUE TITLE
NodeBB v3.0-alpha Mobile Hamburger(navigation) menu becomes stuck when directly clicking on the User menu

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#10966]
### NodeBB version

v3.0-alpha

### NodeJS version

v18.10

### Database type

PostgreSQL

### Exact steps to cause this issue

While on a mobile device:
* click on the User menu to open the user side panel
* click on the Hamburger menu to show the forum navigation side panel
* click outside the navigation menu

### What you expected

the navigation panel should slide out

### What happened instead

the navigation panel stays on screen and cannot be dismissed

**Comment by julianlam** [comment]
@pitaj do you mind taking a look at this?

**Comment by pitaj** [comment]
I can't seem to reproduce this. What mobile device and browser are you using?

**Comment by sweetppro** [comment]
@pitaj im using:
macOS 12.6
Safari 16.0 (responsive design mode)
Flatly skin
Persona (Child theme)

**Comment by sweetppro** [comment]
hmm,
it seems to be something with my child theme...
running the default Persona theme works as expected.
I guess Im not importing something I should be

**Comment by barisusakli** [comment]
I noticed another issue with the mobile user menu, clicking the different tabs scrolls the menu down to the pane so that will need to be fixed.

**Comment by sweetppro** [comment]
Is there a definitive list of what I need to import in my plugin.json file?

**Comment by julianlam** [comment]
Does the persona theme work fine with the flatly skin?

Paste your child theme's plugin.json I guess?

**Comment by sweetppro** [comment]
Yeah it does that’s the strange thing. I don’t add any custom JavaScript…

i have an idea I’ll try later today. I guess my custom css may be altering the dom enough to mess with the default js.

**Comment by sweetppro** [comment]
just for completion. if anyone else runs int0 a similar issue, I fixed it with the following child theme script:
```
'use strict';

document.addEventListener('DOMContentLoaded', function() {
    //fix mobile menu behavior
    const toggleElems = document.querySelectorAll('.navbar-toggler');
    toggleElems.forEach(function(elem) {

        elem.addEventListener('click', function(e) {
            e.preventDefault();
            e.stopPropagation();

            toggleElems.forEach(function(subelem) {
                subelem.style.pointerEvents = togglePointerEvent();
            });
        })
    });
});

function togglePointerEvent() {
  return "none" ? "all" : "all";
}
```
