### ISSUE TITLE
limiting chat function for unverified users

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#10962]
### Description

Forum allows chats for new users who have not confirmed their email addresses. We want them to be able to chat with moderators/admins so they can resolve membership-related problems without sending direct emails, but we do not want them to be able to chat with other regular users before verification.

We had cases where spam users logged in, did not confirm their email addresses, and sent spam messages to users...

### Community forum reference

https://community.nodebb.org/topic/16732/limiting-chat-function-for-unverified-users

**Comment by julianlam** [comment]
Sounds like more fine-grained chat privileges would be a good addition here.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/12092
