### ISSUE TITLE
Googlebot picking up `?lang=en-GB` from somewhere

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#10993]
I am not certain whether this is a bug, but it is causing noisy entries in webmaster tools.

We've received two separate reports (one privately, one [here](https://community.nodebb.org/topic/16747/google-constantly-complains-about-nodebb-forums)) that the query string `?lang=en-GB` is added to URLs reported in the webmaster tools. They also show up in some search results, so it seems Google considers the query string part of the URL.

It may or may not be indexed differently if the system language is set to something other than the default (`en-GB`)

Two things stick out:

1. `lang` is not a documented feature in NodeBB (although it does work to display alternative localised UI based on the passed-in value)
2. `en-GB` is a peculiar choice for Google because if it were added independently, they would've picked `en-US`.

Both things suggest that **we're** the ones adding this query string in.

**Comment by pitaj** [comment]
Could it be added to the canonical URL somewhere?

**Comment by julianlam** [comment]
Possibly, but I haven't been able to reproduce in any way whatsoever

**Comment by julianlam** [comment]
I was actually hoping @barisusakli might have some insights but if not we might have to just close 🤷

**Comment by barisusakli** [comment]
Seems like it is coming from the autoLocale middleware https://github.com/NodeBB/NodeBB/blob/master/src/middleware/headers.js#L89-L97.

If the request comes from a spider (`uid=-1`) and `autoDetectLang` is turned on. Then that code will apply to guests and spiders and add the lang into `req.query.lang`.  After that if you try to access a topic at an index that doesn't exist like /topic/slug/1000  or if you access a topic wihout a slug like `topic/123` this code(https://github.com/NodeBB/NodeBB/blob/master/src/controllers/topics.js#L65-L71) redirects you and the url has the lang in it.
