### ISSUE TITLE
success alert covers save button in navigation acp

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11000]

**Comment by julianlam** [comment]
Technically this applies to all routes with a save button at the bottom right 😬

**Comment by barisusakli** [comment]
Might be better to get rid of success alert and change the save button to success icon for a 1-2 seconds
![image](https://user-images.githubusercontent.com/2583394/197210944-41803aaa-db48-43a3-8abb-f8cf6577247f.png)
