### ISSUE TITLE
Change user email and username with API

### ISSUE THREAD

**Issue by nesro** [NodeBB/NodeBB#11009]
### Description

Hi NodeBB team,

currently, you can change change user basic information and password with API:
- https://docs.nodebb.org/api/write/#tag/users/paths/~1users~1%7Buid%7D/put
- https://docs.nodebb.org/api/write/#tag/users/paths/~1users~1%7Buid%7D~1password/put

I would like to be able to change user username and email too.

Is there any limitation, why it cannot be done? We're managing users in another site, so any conflicts are handled there.

As a workaround, can I safely just edit manually in the database records with _id 'email:uid' and `user:${userId}`?

Thanks,
Tomas

**Comment by barisusakli** [comment]
Hmm, I think the first endpoint also allows changing username but there are some restrictions there https://github.com/NodeBB/NodeBB/blob/master/src/api/users.js#L47-L50.
If you are changing your own username you also need to send the current password. If the calling user is an administrator then current password is not checked. 

As for email it gets a bit tricky, when that end point is called the code doesn't actually update the `email` field in the user field. It sends out an email to the address provided and when the user clicks the confirmation link in the email the value is saved into their profile. So it seems there is no way to change users email manually with the write api @julianlam

**Comment by julianlam** [comment]
@barisusakli is correct. Due to the nature of the logic (specifically, the API calls `user.updateProfile()`, which is the same code path that updating via the front-end uses), the password confirmation is bypassed, but a validation email is sent.

A new endpoint can be added to `/api/v3/users`, although it would have to be locked down to admins, if we were to allow it to bypass the email confirmation step.

**Comment by nesro** [comment]
Hi @julianlam adn @barisusakli.

The api v3 route added for changing email looks good, thank you!

It is possible to add a similar route for changing username?

**Comment by julianlam** [comment]
You should be able to use [PUT /users/:uid](https://docs.nodebb.org/api/write/#tag/users/paths/~1users~1%7Buid%7D/put) to change username.

**Comment by nesro** [comment]
@julianlam thanks! It seems to be working well.
