### ISSUE TITLE
Visiting certain URLs in the admin dashboard receive no response

### ISSUE THREAD

**Issue by Teresa-Hale-DHQ** [NodeBB/NodeBB#11012]
### NodeBB version

2.5.7

### NodeBB git hash

5836bf4a05651d8043c974c628f67170380eec36

### NodeJS version

18.6.0

### Installed NodeBB plugins
```
        * nodebb-plugin-2factor@5.0.2 (installed, disabled)
        * nodebb-plugin-align-center@0.1.3 (installed, enabled)
        * nodebb-plugin-composer-default@9.1.1 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
        * nodebb-plugin-embed@3.0.19 (installed, enabled)
        * nodebb-plugin-emoji@4.0.6 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, disabled)
        * nodebb-plugin-imgur@2.0.5 (installed, enabled)
        * nodebb-plugin-import@0.4.10 (installed, disabled)
        * nodebb-plugin-markdown@10.1.0 (installed, enabled)
        * nodebb-plugin-markdown-yourself@1.0.0 (installed, disabled)
        * nodebb-plugin-mentions@3.0.12 (installed, enabled)
        * nodebb-plugin-night-mode@1.0.7 (installed, enabled)
        * nodebb-plugin-sanitizehtml@1.0.0 (installed, enabled)
        * nodebb-plugin-session-sharing@7.0.0 (installed, enabled)
        * nodebb-plugin-soundpack-default@2.0.1 (installed, enabled)
        * nodebb-plugin-spam-be-gone@1.0.2 (installed, enabled)
        * nodebb-plugin-veegie-extended-markdown@1.0.0 (installed, enabled)
        * nodebb-plugin-write-api@5.8.11 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-persona@12.1.1 (installed, disabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.18 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)
```
### Database type

MongoDB

### Database version

5.0.13

### Exact steps to cause this issue

1. Visit/click on any of the following URLS
  - `/forum/admin/manage/admins-mods`
  - `/forum/admin/manage/groups/administrators`
  - `/forum/admin/manage/groups/<any-group-slug>`
2. Wait indefinitely 

### What you expected

I expect to the pages to load

### What happened instead

The page either doesn't load at all (if navigated to by clicking a link) OR I receive a 504 gateway timeout (if copy-pasted directly into the address bar)

### Anything else?

- There's nothing helpful in the logs. When I make a request to any of the aforementioned URLs, the log simply prints something like this with no stacktrace:
```
x.x.x.x - - [04/Nov/2022:03:25:02 +0000] "GET /forum/ admin/manage/groups/postrank-1 HTTP/1.1" - - "-" "<user-agent>"
```
- I'm using a reverse proxy (NGINX) with the following configuration
```
server {
	listen localhost:4000 ssl;
	server_name localhost;
	ssl_certificate /etc/nginx/ssl/localhost.crt;
        ssl_certificate_key /etc/nginx/ssl/localhost.key;
     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    ssl_ciphers 'AES128+EECDH:AES128+EDH';

    ssl_prefer_server_ciphers on;

    location /forum {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
	client_max_body_size 100M;
        proxy_pass http://127.0.0.1:4567; 
        proxy_redirect off;
        proxy_intercept_errors on;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by barisusakli** [comment]
Can you share a link to your forum if it's public, I think your issue is related to some kind of loop in categories where a child has its parent as a child which causes an infinite loop when trying to load those pages.

**Comment by Teresa-Hale-DHQ** [comment]
@barisusakli 
[Forum Link](https://www.rockfic.com/forum)

**Comment by barisusakli** [comment]
Are you able to modify this function https://github.com/NodeBB/NodeBB/blob/master/src/controllers/admin/groups.js#L35 and restart nodebb?

If you add some console.log statements in there we can figure out why it is not loading the `/forum/admin/manage/groups/administrators` page.

**Comment by Teresa-Hale-DHQ** [comment]
> Are you able to modify this function https://github.com/NodeBB/NodeBB/blob/master/src/controllers/admin/groups.js#L35 and restart nodebb?
> 
> If you add some console.log statements in there we can figure out why it is not loading the `/forum/admin/manage/groups/administrators` page.

I added a console.log statement inside `groupController.get` like so:
```diff
--- a/src/controllers/admin/groups.js
+++ b/src/controllers/admin/groups.js
@@ -2,6 +2,7 @@

 const nconf = require('nconf');
 const validator = require('validator');
+const winston = require("winston");

 const db = require('../../database');
 const user = require('../../user');
@@ -38,7 +39,7 @@ groupsController.get = async function (req, res, next) {
                getGroupNames(),
                groups.get(groupName, { uid: req.uid, truncateUserList: true, userListCount: 20 }),
        ]);
-
+       winston.info("gggggg", group);
```
Nothing gets logged though 😕

**Comment by barisusakli** [comment]
What if you put it at the top of the function like this.
```
groupsController.get = async function (req, res, next) {
	console.log('1')
```

Does that get logged?

**Comment by Teresa-Hale-DHQ** [comment]
> What if you put it at the top of the function like this.
> 
> ```
> groupsController.get = async function (req, res, next) {
> 	console.log('1')
> ```
> 
> Does that get logged?

Strangely enough, yes.

**Comment by barisusakli** [comment]
Ok that means it gets stuck in one of the function calls here 

```
const slug = slugify(req.params.name);
const groupName = await groups.getGroupNameByGroupSlug(slug);
const [groupNames, group] = await Promise.all([
	getGroupNames(),
	groups.get(groupName, { uid: req.uid, truncateUserList: true, userListCount: 20 }),
]);
```

I am guessing its `groups.get` but  you can rule it out by calling them one after the other like so.
```
const slug = slugify(req.params.name);
const groupName = await groups.getGroupNameByGroupSlug(slug);
const groupNames = await getGroupNames();
console.log('2');
const group = await groups.get(groupName, { uid: req.uid, truncateUserList: true, userListCount: 20 });
console.log('3');
```

And see which logs get written

**Comment by Teresa-Hale-DHQ** [comment]
I see `1` and `2`, but not `3`.

**Comment by barisusakli** [comment]
Now you can dog into groups.get to see where its hanging.

**Comment by barisusakli** [comment]
Not 🐶 I meant dig 😆

**Comment by Teresa-Hale-DHQ** [comment]
It hangs at `const results = await plugins.hooks.fire('filter:group-get', {group: groupData})`. Does this mean it's a plugin causing it?

**Comment by barisusakli** [comment]
Yes you can check out the /admin/advanced/hooks page to see which plugins are using that hook

**Comment by Teresa-Hale-DHQ** [comment]
Huh.... the relevant hook (`filter:group.get`) doesn't exist in the list!

**Comment by Teresa-Hale-DHQ** [comment]
![screenshot of hook](https://user-images.githubusercontent.com/71732052/200054363-3cc49137-1176-4b03-96cb-e598539abbac.png)

**Comment by barisusakli** [comment]
What happens if you comment out the fire hook function? Like this

```
groupData.isOwner = isOwner;
// const results = await plugins.hooks.fire('filter:group.get', { group: groupData });
return groupData;
```

Does the page load then?

**Comment by Teresa-Hale-DHQ** [comment]
Nope.

However, after disabling `nodebb-plugin-sanitizehtml` the groups load, signalling that it's a plugin issue. I'll close this off for now and open an issue in the relevant repository. Thanks for your time and help!! I appreciate it 😄

**Comment by barisusakli** [comment]
That plugin doesn't seem to use the `filter:group.get` hook, let us know what you find.
