### ISSUE TITLE
Existing Categories not shown on Home Page after upgrade/migration from nodebb 0.7.2 to 2.5.7

### ISSUE THREAD

**Issue by afh** [NodeBB/NodeBB#11015]
### NodeBB version

2.5.7

### NodeBB git hash

5836bf4a05651d8043c974c628f67170380eec36

### NodeJS version

v18.12.0

### Installed NodeBB plugins

* nodebb-plugin-2factor@5.0.2 (installed, disabled)
* nodebb-plugin-code-button@0.0.7 (installed, enabled)
* nodebb-plugin-composer-default@9.1.1 (installed, enabled)
* nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
* nodebb-plugin-emailer-mailgun@1.1.2 (installed, enabled)
* nodebb-plugin-emoji@4.0.6 (installed, disabled)
* nodebb-plugin-emoji-android@3.0.0 (installed, disabled)
* nodebb-plugin-markdown@10.1.0 (installed, enabled)
* nodebb-plugin-mentions@3.0.12 (installed, enabled)
* nodebb-plugin-recent-cards@3.1.3 (installed, enabled)
* nodebb-plugin-spam-be-gone@1.0.2 (installed, enabled)
* nodebb-plugin-sso-twitter@2.5.14 (installed, enabled)
* nodebb-rewards-essentials@0.2.1 (installed, enabled)
* nodebb-theme-lavender@6.0.0 (installed, disabled)
* nodebb-theme-persona@12.1.1 (installed, enabled)
* nodebb-theme-slick@2.0.2 (installed, disabled)
* nodebb-theme-vanilla@12.1.18 (installed, disabled)
* nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

Redis

### Database version

6.0.16

### Exact steps to cause this issue

* Dump redis database server on production server `redis-cli -rdb dump.rdb` (NOTA BENE: the production server runs nodebb 0.7.2)
* Copy redis database dump from production server to testing server: `scp dump.rdb forum-new:`
* Install latest version (2.5.7) of nodebb on testing server (running Ubuntue 22.04.1 LTS) according to [_Installation on Ubuntu_](https://docs.nodebb.org/installing/os/ubuntu/)
* Integrate nodebb into systemd according to [_Running NodeBB - systemd_](https://docs.nodebb.org/configuring/running/#systemd)
* Wipe redis data on testing server:
```
% redis-cli
127.0.0.1:6379> select 0
OK
127.0.0.1:6379> flushdb
(3.21s)
127.0.0.1:6379> exit
```
* Stop redis server: `# systemctl stop redis`
* Copy dump.rdb to redis import location: `# cp dump.rdb /var/lib/redis/dump.rdb`
* Start redis server: `# systemctl start redis`
* Configure nodebb on testing server as it is configured on production server
```
% cat <<EOF >config.json
{
    "url": "https://testing.example.com",
    "secret": "REDACTED",
    "database": "redis",
    "bind_address": "127.0.0.1",
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "password": "",
        "database": "0"
    }
}
EOF
```
* Migrate old nodebb data: `% ./nodebb upgrade`
* Copy uploads from production server to testing server: `% rsync -avz nodebb/public/uploads/ forum-new:nodebb/public/uploads/`
* Restart nodebb (for good measure): `# systemctl restart nodebb`
* Ensure that `Persona` is set as the current theme ✅

### What you expected

When viewing the nodebb Home Page on the testing server as a guest or logged-in user I expect to see a list of nodebb categories when the **Home Page Route** is set to **Categories** in **nodebb admin » Settings » Home Page** and the Categories Viewing Privileges allow for it:

![](https://user-images.githubusercontent.com/16507/200137321-a6860ae9-0230-438a-bd70-f26517f5c337.png)

### What happened instead

A blank homepage with only the customized header and footer from the global widget as configured in the admin page is shown along the `categories` headline.

### Anything else?

This issue is a follow-up from #11013.

Please find below the response from the local `/api/categories` endpoint:
<details><summary><code>% curl -H "Authorization: Bearer ${token}" 127.0.0.1:4567/api/categories?_uid=1'</code></summary>

```
{
  "title": "[[pages:categories]]",
  "selectCategoryLabel": "[[pages:categories]]",
  "categories": [],
  "pagination": {
    "prev": {
      "page": 1,
      "active": false
    },
    "next": {
      "page": 1,
      "active": false
    },
    "first": {
      "page": 1,
      "active": true
    },
    "last": {
      "page": 1,
      "active": true
    },
    "rel": [],
    "pages": [],
    "currentPage": 1,
    "pageCount": 1
  },
  "breadcrumbs": [
    {
      "text": "[[global:home]]",
      "url": "/"
    },
    {
      "text": "[[pages:categories]]"
    }
  ],
  "loggedIn": true,
  "relative_path": "",
  "template": {
    "name": "categories",
    "categories": true
  },
  "url": "/categories",
  "bodyClass": "page-categories page-status-200 theme-persona user-loggedin",
  "_header": {
    "tags": {
      "meta": [
        {
          "name": "viewport",
          "content": "width&#x3D;device-width, initial-scale&#x3D;1.0"
        },
        {
          "name": "content-type",
          "content": "text/html; charset=UTF-8",
          "noEscape": true
        },
        {
          "name": "apple-mobile-web-app-capable",
          "content": "yes"
        },
        {
          "name": "mobile-web-app-capable",
          "content": "yes"
        },
        {
          "property": "og:site_name",
          "content": "testing"
        },
        {
          "name": "msapplication-badge",
          "content": "frequency=30; polling-uri=https://testing.example.com/sitemap.xml",
          "noEscape": true
        },
        {
          "name": "theme-color",
          "content": "#ffffff"
        },
        {
          "name": "keywords",
          "content": "pythonista, editorial, ios"
        },
        {
          "name": "title",
          "content": "testing"
        },
        {
          "property": "og:type",
          "content": "website"
        },
        {
          "property": "og:title",
          "content": "[[pages:categories]]"
        },
        {
          "property": "og:image",
          "content": "https://testing.example.com/assets/images/logo@3x.png",
          "noEscape": true
        },
        {
          "property": "og:image:url",
          "content": "https://testing.example.com/assets/images/logo@3x.png",
          "noEscape": true
        },
        {
          "property": "og:image:width",
          "content": "963"
        },
        {
          "property": "og:image:height",
          "content": "225"
        },
        {
          "content": "https://testing.example.com/api/categories?_uid&#x3D;1",
          "property": "og:url"
        },
        {
          "content": "Community forum for Example",
          "name": "description"
        },
        {
          "content": "Community forum for Example",
          "property": "og:description"
        }
      ],
      "link": [
        {
          "rel": "icon",
          "type": "image/x-icon",
          "href": "/assets/uploads/system/favicon.ico?v&#x3D;662e747p7ih"
        },
        {
          "rel": "manifest",
          "href": "/manifest.webmanifest",
          "crossorigin": "use-credentials"
        },
        {
          "rel": "search",
          "type": "application/opensearchdescription+xml",
          "title": "testing",
          "href": "/osd.xml"
        },
        {
          "rel": "apple-touch-icon",
          "href": "/assets/images/touch/512.png"
        },
        {
          "rel": "icon",
          "sizes": "36x36",
          "href": "/assets/images/touch/36.png"
        },
        {
          "rel": "icon",
          "sizes": "48x48",
          "href": "/assets/images/touch/48.png"
        },
        {
          "rel": "icon",
          "sizes": "72x72",
          "href": "/assets/images/touch/72.png"
        },
        {
          "rel": "icon",
          "sizes": "96x96",
          "href": "/assets/images/touch/96.png"
        },
        {
          "rel": "icon",
          "sizes": "144x144",
          "href": "/assets/images/touch/144.png"
        },
        {
          "rel": "icon",
          "sizes": "192x192",
          "href": "/assets/images/touch/192.png"
        },
        {
          "rel": "icon",
          "sizes": "512x512",
          "href": "/assets/images/touch/512.png"
        },
        {
          "rel": "prefetch",
          "href": "/assets/src/modules/composer.js?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/src/modules/composer/uploads.js?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/src/modules/composer/drafts.js?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/src/modules/composer/tags.js?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/src/modules/composer/categoryList.js?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/src/modules/composer/resize.js?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/src/modules/composer/autocomplete.js?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/templates/composer.tpl?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/language/en-US/topic.json?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/language/en-US/modules.json?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch",
          "href": "/assets/language/en-US/tags.json?v&#x3D;662e747p7ih"
        },
        {
          "rel": "prefetch stylesheet",
          "type": "",
          "href": "/assets/plugins/nodebb-plugin-markdown/styles/default.css"
        },
        {
          "rel": "prefetch",
          "href": "/assets/language/en-US/markdown.json?v&#x3D;662e747p7ih"
        }
      ]
    }
  },
  "widgets": {
    "header": [],
    "footer": [
      {
        "html": "<footer id=\"footer\" class=\"container footer\">\r\n\t<div class=\"copyright\">\r\n\t\tPowered by <a target=\"_blank\" href=\"https://nodebb.org\">NodeBB Forums</a> | <a target=\"_blank\" href=\"//github.com/NodeBB/NodeBB/graphs/contributors\">Contributors</a>\r\n\t</div>\r\n</footer>"
      }
    ]
  }
}
```

</details>

**Comment by afh** [comment]
Poking around a bit in the API the followoing struck me as notable:

```
% curl -sH "Authorization: Bearer $(secenv NODEBB_TOKEN)" 127.0.0.1:4567/api\?_uid=1 | jaq
{
  "path": "&#x2F;api&#x2F;categories",
  "error": "req.query.hasOwnProperty is not a function",
  "bodyClass": "page-categories page-status-500 theme-persona user-guest"
}
```

NOTE: `secenv` is a small custom wrapper around [sorah/envchain](https://github.com/sorah/envchain) to inject secrets and token stored securely in envchain into commands.

Apologies if the mentioned api request does not make sense at all and the error is legitimate; I'm slowly getting acquainted with nodebb and have much to learn and discover :)

**Comment by pitaj** [comment]
I also mentioned this in the PR you opened.

I think the issue is trying to upgrade straight to 2.x from a version prior to 1.0, which isn't supported. This should be documented but doesn't appear to be because it's so rare.

You will probably need to follow the procedure here: https://community.nodebb.org/post/83303

**Comment by afh** [comment]
Thanks for chiming in here to, @pitaj.
I went ahead:
* uninstalled Ubuntu's node
* installed node 4 (via nvm)
* installed dependencies needed by gyp like make, g++, python2
* checked out nodebb `v0.7.x`
* cleaned the nodebb installation `git clean -dfx`
* and ran `npm i`

Unfortunately that fails with a lot of compile errors (see [v0.7.x-upgrade.log](https://github.com/NodeBB/NodeBB/files/9946331/v0.7.x-upgrade.log); view with `less -R`).
I might be missing something, yet it seems trying to fix the data from an 0.7.2 to 2.5.7 upgrade seems easier than trying to address all those compile errors (see v0.7.x-upgrade.log above); especially as I'd expect more of those errors with every major and minor version upgrade as described in [the aforementioned procedure](https://community.nodebb.org/topic/15667/upgrade-from-v0-6-1-to-v1-17-0-latest-need-recommendation/6).

**Comment by barisusakli** [comment]
Can you check the output of these.

`zrange categories:cid 0 -1`
`zrange cid:0:children 0 -1`

These should return category ids. Then check if the data exists with

```
hgetall category:<cid>
```

Replace `<cid>` with the ids from above query.

If these return the correct data check https://github.com/NodeBB/NodeBB/blob/master/src/controllers/categories.js#L24 with some console logs

**Comment by barisusakli** [comment]
Also do you see them in the categories page in the admin page?

**Comment by afh** [comment]
Thank you for chiming in, @barisusakli.

As requested please find below the output of the redis commands.
```
127.0.0.1:6379> zrange categories:cid 0 -1
1) "5"
2) "6"
3) "2"
4) "1"
5) "4"
127.0.0.1:6379> zrange cid:0:children 0 -1
(empty array)
```

<details><summary><code>127.0.0.1:6379> hgetall category:1</code></summary>

```
 1) "cid"
 2) "1"
 3) "name"
 4) "Announcements"
 5) "description"
 6) "Announcements regarding our community"
 7) "icon"
 8) "fa-bullhorn"
 9) "bgColor"
10) "#fda34b"
11) "color"
12) "#ffffff"
13) "slug"
14) "1/announcements"
15) "parentCid"
16) "0"
17) "topic_count"
18) "1"
19) "post_count"
20) "24"
21) "disabled"
22) "0"
23) "order"
24) "4"
25) "link"
26) ""
27) "numRecentReplies"
28) "1"
29) "class"
30) "col-md-3 col-xs-6"
31) "imageClass"
32) "auto"
33) "undefined"
34) "on"
35) "subCategoriesPerPage"
36) "10"
```

</details>

<details><summary><code>127.0.0.1:6379> hgetall category:2</code></summary>

```
 1) "cid"
 2) "2"
 3) "name"
 4) "General Discussion"
 5) "description"
 6) "A place to talk about whatever you want"
 7) "icon"
 8) "fa-comments-o"
 9) "bgColor"
10) "#9366b2"
11) "color"
12) "#ffffff"
13) "slug"
14) "2/general-discussion"
15) "parentCid"
16) "0"
17) "topic_count"
18) "404"
19) "post_count"
20) "1441"
21) "disabled"
22) "1"
23) "order"
24) "3"
25) "link"
26) ""
27) "numRecentReplies"
28) "1"
29) "class"
30) "col-md-3 col-xs-6"
31) "imageClass"
32) "auto"
33) "subCategoriesPerPage"
34) "10"
```

</details>

<details><summary><code>127.0.0.1:6379> hgetall category:4</code></summary>

```
 1) "cid"
 2) "4"
 3) "name"
 4) "Comments & Feedback"
 5) "description"
 6) "Got a question? Ask away!"
 7) "icon"
 8) "fa-question"
 9) "bgColor"
10) "#e95c5a"
11) "color"
12) "#ffffff"
13) "slug"
14) "4/comments-feedback"
15) "parentCid"
16) "0"
17) "topic_count"
18) "0"
19) "post_count"
20) "0"
21) "disabled"
22) "1"
23) "order"
24) "5"
25) "link"
26) ""
27) "numRecentReplies"
28) "1"
29) "class"
30) "col-md-3 col-xs-6"
31) "imageClass"
32) "auto"
33) "subCategoriesPerPage"
34) "10"
```

</details>

<details><summary><code>127.0.0.1:6379> hgetall category:5</code></summary>

```
 1) "cid"
 2) "5"
 3) "name"
 4) "Python"
 5) "description"
 6) "Share scripts and get help with your programming questions"
 7) "icon"
 8) "fa-comments"
 9) "bgColor"
10) "#0485a6"
11) "color"
12) "#ffffff"
13) "slug"
14) "5/python"
15) "parentCid"
16) "0"
17) "topic_count"
18) "6056"
19) "post_count"
20) "43564"
21) "disabled"
22) "0"
23) "order"
24) "1"
25) "link"
26) ""
27) "numRecentReplies"
28) "1"
29) "class"
30) "col-md-3 col-xs-6"
31) "imageClass"
32) "auto"
33) "subCategoriesPerPage"
34) "10"
```

</details>

<details><summary><code>127.0.0.1:6379> hgetall category:6</code></summary>

```
 1) "topic_count"
 2) "911"
 3) "description"
 4) "Discuss plain text productivity and workflow automation"
 5) "slug"
 6) "6/editor"
 7) "disabled"
 8) "0"
 9) "color"
10) "#ffffff"
11) "parentCid"
12) "0"
13) "link"
14) ""
15) "imageClass"
16) "auto"
17) "cid"
18) "6"
19) "post_count"
20) "3313"
21) "icon"
22) "fa-comments"
23) "numRecentReplies"
24) "1"
25) "bgColor"
26) "#495c74"
27) "order"
28) "2"
29) "name"
30) "Editor"
31) "class"
32) "col-md-3 col-xs-6"
33) "subCategoriesPerPage"
34) "10"
```

</details>

And yes, the categories all appear in the categories page in the admin page:


<img width="1178" alt="image" src="https://user-images.githubusercontent.com/16507/200189200-a98a36d2-9af9-434c-9f74-61bc7c2e47ed.png">

Can you provide more detailed and specific steps on how to _"check https://github.com/NodeBB/NodeBB/blob/master/src/controllers/categories.js#L24 with some console logs_", please?
I'm uncertain whether I need to visit a specific nodebb URL in the browser and inspect the browser's console or I'd need to check the nodebb logs on the server.

**Comment by barisusakli** [comment]
I think I see what the problem is, you can run the below query in redis to add the categories to `cid:0:children` then they should show up on /categories.

```
zadd cid:0:children 1 5 2 6 3 2 4 1 5 4 
```

Let me know if they show up after running that. Alternatively you can fix this in the ACP by creating a new category and moving  all the categories to be a child of that one. And then moving them back to the root. This should fix the `cid:0:children` sorted set. 

I am not sure why cid:0:children is empty in your case, but like @pitaj said 0.7.2 is a really old version possibly cid:0:children didn't exist back then.

**Comment by afh** [comment]
Great, that seems to have fixed it! Thanks so much for your excellent and quick help on this, especially as this is a rather esoteric issue given the fact it happens when upgrading from what can be considered an ancient version of nodebb.

I'll run through the whole upgrade process once again tomorrow and will close this issue in case everything works out well.

**Comment by pitaj** [comment]
The npm install errors you're seeing may or may not prevent the upgrade scripts from working. I'd recommend trying moving forward to `./nodebb upgrade` and see if that works. That is, if you continue to run into similar problems.

**Comment by afh** [comment]
The results from the upgrade process I followed including the manual `zadd cid:0:children 1 5 2 6 3 2 4 1 5 4` are satisfactory.

Hence I'm closing this issue and thank you @barisusakli and @pitaj for the outstanding help! ⭐⭐⭐⭐⭐
