### ISSUE TITLE
Most of the Skins are not useable with Persona Theme

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#11035]
### NodeBB version

latest

### NodeBB git hash

445f09f0dc9d3b5c2e7d6758beec134d05612acb

### NodeJS version

16

### Database type

MongoDB

### Database version

6.0.2

### Exact steps to cause this issue

1. use Persona Theme
2. use Skin for example Slate
3. have a look at the Tags in a List of topics
4. select a topic and look at the title with the tags

### What you expected

readable Tags

### What happened instead

Text color and Background are the same?

### Anything else?

I use the dark mode of the operating system and browser

**Comment by julianlam** [comment]
@awunnenb if the tags page has elements that are unreadable, that means the entire skin itself is **unusable**?

Oh dear.

**Comment by barisusakli** [comment]
This is already fixed in 3.x applied the same fix to 2.x persona as well. Let us know if you notice other contrast issues. 
https://community.nodebb.org/ is running 3.x so you can test the skins there.
