### ISSUE TITLE
missing await on db.sortedSetsCard()

### ISSUE THREAD

**Issue by cisnerosebastian** [NodeBB/NodeBB#11052]
https://github.com/NodeBB/NodeBB/blob/a87f64b4bb9246f5548abf4c11afdb595baa6f3e/src/posts/delete.js#L206

using `count` variable before waiting the promise to resolve

**Comment by cisnerosebastian** [comment]
I've found several topics in my database without the `replies` property, and causing error on posting new comments.

![image](https://user-images.githubusercontent.com/938368/203132152-58d5026d-1c68-4a94-b078-1972a702d209.png)

this is ahppening because after purging a post, some times the promise is not resolved before using its value, then setting up the `replies` property to undefined

**Comment by barisusakli** [comment]
@cisnerosebastian thanks for reporting, how many of these null values do you have in your db? Maybe you can run the below and check.

```
db.objects.count({_key: /^post:\d+/, replies: null});
```

**Comment by cisnerosebastian** [comment]
![image](https://user-images.githubusercontent.com/938368/203135436-52cfff36-bb00-461d-8e96-204ec5cc95e3.png)

I think that query is getting more results that what I expected

![image](https://user-images.githubusercontent.com/938368/203136139-2b79a55a-ef4e-4d25-9d3f-0b511be971bb.png)

**Comment by barisusakli** [comment]
Ah in that case you can try `db.objects.count({_key: /^post:\d+$/, replies: {$type: 10 }});`

**Comment by cisnerosebastian** [comment]
9

![image](https://user-images.githubusercontent.com/938368/203136860-f11b9543-9078-4db4-a318-a6a82353bc43.png)

that sounds more accurate. Thanks.

**Comment by barisusakli** [comment]
It doesn't seem a lot so I would fix them by hand. To get the correct number you can run the below queries.
```
db.objects.find({_key: /^post:\d+$/, replies: {$type: 10 }}).pretty();
```

Once you have the post ids(pids) you can get the correct replies count with
```
db.objects.count({_key: "pid:<pid>:replies"}); // replace <pid> with the post id from the above query.
```

Once you have the correct number set it to the object with
```
db.objects.update({_key: "post:<pid>", { $set: { replies: <replace_with_count> } } });
```
Do this for the 9 posts that have null in their replies field.
