### ISSUE TITLE
I can no longer backup a nodebb forum with mongodump

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#11051]
### NodeBB version

2.5.8

### NodeBB git hash

a87f64b4bb9246f5548abf4c11afdb595baa6f3e

### NodeJS version

v16.18.1

### Database type

MongoDB

### Database version

v6.0.3

### Exact steps to cause this issue

mongodump -d nodebb --username xxxx --password yyy --authenticationDatabase=admin

### What you expected

2022-11-19T13:00:28.464+0100	done dumping ...

### What happened instead

2022-11-19T12:56:16.833+0100	writing nodebb.searchpost to dump/nodebb/searchpost.bson
2022-11-19T12:56:16.833+0100	writing nodebb.socket.io to dump/nodebb/socket.io.bson
2022-11-19T12:56:16.833+0100	writing nodebb.sessions to dump/nodebb/sessions.bson
2022-11-19T12:56:16.845+0100	writing nodebb.objects to dump/nodebb/objects.bson
2022-11-19T12:56:16.964+0100	done dumping nodebb.sessions (6444 documents)
2022-11-19T12:56:16.968+0100	writing nodebb.searchtopic to dump/nodebb/searchtopic.bson
2022-11-19T12:56:16.975+0100	done dumping nodebb.searchtopic (425 documents)
2022-11-19T12:56:17.036+0100	done dumping nodebb.socket.io (11709 documents)
2022-11-19T12:56:19.801+0100	[........................]  nodebb.searchpost    101/25541  (0.4%)
2022-11-19T12:56:19.802+0100	[........................]     nodebb.objects  101/1080360  (0.0%)
2022-11-19T12:56:19.802+0100
2022-11-19T12:56:22.801+0100	[........................]  nodebb.searchpost    101/25541  (0.4%)
2022-11-19T12:56:22.801+0100	[........................]     nodebb.objects  101/1080360  (0.0%)
2022-11-19T12:56:22.801+0100    endless...

the problem in all databases is nodebb.objects

### Anything else?

I can no longer backup a nodebb forum with mongodump. I'm not sure if it's because of nodebb but the error only occurs in connection with nodebb. With all other mongodb databases it works fine. I also can't restore old backups although I can restore them on other servers or my Mac without problems. I have already completely uninstalled and reinstalled mongodb.

mongodump version: 100.6.1 and same problem with mongodump version: 100.6.0

all servers are running with Debian 11

**Comment by pitaj** [comment]
Are you sure NodeBB is stopped? Check and see if any node processes are running.

**Comment by awunnenb** [comment]
yes
Status: Active: inactive (dead)

**Comment by awunnenb** [comment]
there are no errors when i call db.objects.validate(). There are no known errors in the operation of the forum. Only the dumps are not working.

**Comment by julianlam** [comment]
What about db.showOps()?

**Comment by awunnenb** [comment]
db.showOps();
TypeError: db.showOps is not a function

**Comment by julianlam** [comment]
My bad, db.currentOp():

**Comment by awunnenb** [comment]
which role do I need for the command

**Comment by pitaj** [comment]
Did you check and see if any node processes are running?

**Comment by awunnenb** [comment]
all node processes for nodebb are stopped. This is controlled in the backup script and I have checked it. nodebb is stopped.

**Comment by awunnenb** [comment]
Based on the tests on the database, I also believe that it is not due to nodebb. I suspect the error in the operating system or firewall. I am just surprised that it happens exclusively with nodebb databases. It always happens when objects are accessed. But you should not invest too much time in this problem. I have another question if there are solutions for the critical vulnerabilities in nodebb audit.

**Comment by barisusakli** [comment]
I would also check if the system has enough ram/hdd space available when doing the mongodump.

**Comment by awunnenb** [comment]
The dump for nodebb.objects is definitely prevented by the firewall. mongodump runs over 127.0.0.1 so why? The problem occurs since 11/16/2022 without changing anything on the system. Is it possible that someone has inserted malware in a forum post that wants to get out when accessed by mongodump. I don't think so but why does the firewall block a dump or export of nodebb.objects?

**Comment by julianlam** [comment]
I think that is highly highly improbable... Using NodeBB as a vector to attack a MongoDB instance. It sounds like perhaps you should try the mongo support (IRC?)

**Comment by pitaj** [comment]
Have you tried rebooting your server?

**Comment by awunnenb** [comment]
Is there a solution for 
"7 high severity vulnerabilities" that are not fixed with npm audit fix

**Comment by barisusakli** [comment]
@awunnenb please open a separate issue for that
