### ISSUE TITLE
Topic events are broken

### ISSUE THREAD

**Issue by oplik0** [NodeBB/NodeBB#11053]
### NodeBB version

v2.5.8

### NodeBB git hash

ever since 55a197a7d79037a08cec9c71bb6b9e66f09f94f8

### NodeJS version

v16.18.1

### Installed NodeBB plugins

* nodebb-plugin-2factor@5.0.2 (installed, disabled)
* nodebb-plugin-composer-default@9.1.1 (installed, enabled)
* nodebb-plugin-dbsearch@5.1.5 (installed, disabled)
* nodebb-plugin-emoji@4.0.6 (installed, enabled)
* nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
* nodebb-plugin-markdown@10.1.0 (installed, enabled)
* nodebb-plugin-mentions@3.0.12 (installed, enabled)
* nodebb-plugin-spam-be-gone@1.0.2 (installed, disabled)
* nodebb-plugin-ws-dice@2.5.0 (installed, enabled)
* nodebb-rewards-essentials@0.2.1 (installed, enabled)
* nodebb-theme-lavender@6.0.0 (installed, disabled)
* nodebb-theme-persona@12.1.10 (installed, enabled)
* nodebb-theme-slick@2.0.2 (installed, disabled)
* nodebb-theme-vanilla@12.1.19 (installed, disabled)
* nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

MongoDB

### Database version

v6.03

### Exact steps to cause this issue

1. do anything that should cause a topic event to appear (eg. lock, unlock, pin, attempt to use nodebb-plugin-ws-dice)
2. see it shows up
3. refresh tab
4. topic event is gone

### What you expected

Topic events should be shown to users

### What happened instead

Topic events only appear when adding them and disappear once you reload the topic

### Anything else?

This started in 55a197a7d79037a08cec9c71bb6b9e66f09f94f8 - probably due to the Persona update. I suspect https://github.com/NodeBB/nodebb-theme-persona/commit/c9604f216a87ae867a7c31e10abbb43f30e2f19a might be to blame, but I only bisected NodeBB itself and don't have time to work through Persona commits for the next few days.

I noticed this issue while researching https://github.com/Wieloswiat/nodebb-plugin-ws-dice/issues/93

**Comment by barisusakli** [comment]
Weird, it works on community.nodebb.org which has everything from master and persona AFAIK. Is the topic sorted by most votes by any chance?

**Comment by barisusakli** [comment]
I can definitely reproduce on master with nodebb-theme-persona@12.1.10 so I will take look.

**Comment by oplik0** [comment]
> Weird, it works on community.nodebb.org which has everything from master and persona AFAIK. Is the topic sorted by most votes by any chance?

Wasn't Community on v3 alpha? This seems to affect v2 only, so perhaps it's some issue in implementing something that changed in v3?

**Comment by oplik0** [comment]
It's probably this: https://github.com/NodeBB/NodeBB/commit/093093420027999df3c67bf0ea6024f6dbf81d2d

The partial needs topic event data in topicData, but v2 isn't adding it there.

**Comment by barisusakli** [comment]
Yeah I think persona theme has that change you posted https://github.com/NodeBB/nodebb-theme-persona/commit/c9604f216a87ae867a7c31e10abbb43f30e2f19a the code to make that work is only in bootstrap5(v3) branch thats why it's not working with v2. So will have to revert that back in persona 12.x

**Comment by barisusakli** [comment]
Try with persona 12.1.12

**Comment by oplik0** [comment]
Yup, seems to be working fine now

**Comment by barisusakli** [comment]
We will make a release for 2.x this wednesday 👍🏼
