### ISSUE TITLE
Plugin installation via cli

### ISSUE THREAD

**Issue by nebulade** [NodeBB/NodeBB#11060]
### Description

If this was asked for in the past and I just didn't find it, sorry upfront.

Is there any reason why the cli tool does not have a way to install plugins, but it lists plugins and can activate them?

I am aware that one can just use `npm install <plugin>` to perform the installation, however this has the issue that the nodebb specific compatibility field in the `package.json` is not taken into account. I guess this is also why https://docs.nodebb.org/configuring/plugins/#installing-plugins has the disclaimer.

I am no nodebb expert, but if this is just because it was not yet implemented, I could try to add this to the cli, if there is a possibility that this gets merged.

From very far, it looks like we can follow similar code paths from https://github.com/NodeBB/NodeBB/blob/bb82eb71e23533678af92e014962f273c85db2f4/src/cli/manage.js to https://github.com/NodeBB/NodeBB/blob/a6f7fff0ad376369d84c178f72f8e35877a45bcf/src/plugins/install.js 

To give some background, why this came up: In the Cloudron installation package, we have to install plugins fresh after app updates, due to the fact that on Cloudron the filesystem is mostly read-only.

**Comment by barisusakli** [comment]
`./nodebb install <pluginname>`
That calls plugin install code would make sense i yhink

**Comment by nebulade** [comment]
Oh awesome, thanks!

**Comment by nebulade** [comment]
Would be great if this could be cherry-picked into the next patch release for v2 so we can incorporate this into our packaging. As far as I can tell it didn't make into v2.6.1

**Comment by barisusakli** [comment]
Looks like I forgot to add this to master, done now should be available in 2.6.2

**Comment by nebulade** [comment]
I was trying to integrate this into our app package, however our tests then found that, this will only allow installation of plugins which have a suggested upstream version for the version of nodebb. Unfortunately many plugins don't seem to provide up-to-date compatibility info and thus the cli will refuse to install that. Not sure what is a good approach to still allow them to get installed with a warning, similar to the admin UI. 

Maybe some cli flag to allow to override this?
