### ISSUE TITLE
Add Custom Flag States when Moderating

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#11065]
### Description

Would it be possible to add a hook to be able to add custom Flags Moderated States. Currently they are hardcoded to 4 states but our mods would like to add another option to the list.

https://github.com/NodeBB/NodeBB/blob/8a15e58dff72481f83a0c020459505b6638775f1/src/flags.js#L23-L31

Could the data be added to 'filter:flags.getFilters' if not a separate hook?

https://github.com/NodeBB/NodeBB/blob/8a15e58dff72481f83a0c020459505b6638775f1/src/flags.js#L86-L93

**Comment by julianlam** [comment]
Yes I think that can be done 🙂 thanks for suggesting

**Comment by julianlam** [comment]
This is still on my radar, just otherwise engaged with Harmony.

**Comment by julianlam** [comment]
Ah, of course... the states are currently hardcoded in the template too :face_exhaling:

**Comment by julianlam** [comment]
When v2.8.0 is released, you will be able to hook into `filter:flags.init` and update the `states` property with additional states. A [Map object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) is passed in.
