### ISSUE TITLE
Something wrong with sharp package

### ISSUE THREAD

**Issue by bhavya3024** [NodeBB/NodeBB#11076]
### NodeJS version

12.22.1

### Database type

MongoDB

### Exact steps to cause this issue

npm i is failing with this error as shown in this issue: 

https://github.com/lovell/sharp/issues/3478

### What you expected

install sharp package successfully

### What happened instead

errors,

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.31.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.31.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bhavya.dhiman/.npm/_logs/2022-12-04T08_52_47_876Z-debug.log
```

**Comment by pitaj** [comment]
It looks like they helped you there

**Comment by barisusakli** [comment]
We will up our minimum node version to 14.x Seems like package.json is still 12
