### ISSUE TITLE
email verify

### ISSUE THREAD

**Issue by Amonologue-z** [NodeBB/NodeBB#11106]
Please forgive me for my poor English. I'm not a native speaker of English  :)

When I use a new account to register an account, the beginning of the verified link in the email is localhost:4567/confirm/xxxxxxx
(So my user cannot verify the mail)

I haven't changed the mail template
Please tell me how to solve this problem as soon as possible. This problem is very important to me

**Comment by oplik0** [comment]
In `config.json` in the folder NodeBB is installed in there should be a `url` value - is it set to your forum URL or `http://localhost:4567` (default if you just clicked enter during the setup)? If it's the latter, change it to your forum URL instead (eg. `https://forum.example.com`)

**Comment by julianlam** [comment]
☝️
