### ISSUE TITLE
validation emails still sent even if auto confirm is turned on in sso plugin

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11148]
This is an issue with most of the sso plugins that have auto-confirm I think.
https://github.com/julianlam/nodebb-plugin-sso-facebook/blob/master/library.js#L251-L280

If auto confirm is turned on, the plugin automatically confirms the email but `user.create` that is called by the plugin will still send a validation email. Need to add a option into user.create to prevent sending validation emails.

**Comment by barisusakli** [comment]
yeah so sso plugins need to be updated to not send `email` in `user.create` if autoConfirm is on

**Comment by julianlam** [comment]
* [ ] Facebook
* [ ] Google
* [ ] Twitter

**Comment by julianlam** [comment]
Twitter has `autoConfirm` option, but it doesn't have access to email via twitter :thinking: so that's kind of pointless.

**Comment by julianlam** [comment]
https://github.com/julianlam/nodebb-plugin-sso-twitter/commit/e239b00f70f0aa792bd1de3d65539105787d33c5
