### ISSUE TITLE
Different pages for different languages.

### ISSUE THREAD

**Issue by Michaelwucoc** [NodeBB/NodeBB#11147]
### Description

I am wondering that whether your team can add a settings which can enables different pages for different languages.

Also I want to know how I can customize the translations in the admin panel

**Comment by julianlam** [comment]
You'll have to clarify what you mean for the 1st.

For the 2nd, look to nodebb-plugin-customize

**Comment by Michaelwucoc** [comment]
Thank you for offering a solution to the second question I posed!

To the first suggestion, I mean:

When the user switches languages, display the page appropriate to his language.
For example, when I switch to Chinese, the page link is
nodebb.web/Zh-Cn
When I switch to English, the page link is
nodebb.web/EN

I don't know if this makes sense to you, thanks.



Best regards,

Michael Wu

**Comment by shuzhouliu** [comment]
> You'll have to clarify what you mean for the 1st.
> 
> For the 2nd, look to nodebb-plugin-customize

probably he means i18n

**Comment by Michaelwucoc** [comment]
Actually,I have wrote in https://github.com/NodeBB/NodeBB/issues/11147#issuecomment-1383421068

**Comment by Michaelwucoc** [comment]
Yes:/

**Comment by julianlam** [comment]
We don't support that out of the box, you'd have to create a plugin to do that, sorry.

**Comment by barisusakli** [comment]
nodebb translates the page using a query string so instead of `nodebb.com/<lang>` its `nodebb.com?lang=<lang>`.
