### ISSUE TITLE
Qna topic evet shows wrong text

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11159]
[[[object Object]-ago, System, ]] probably need to update plugin on community 

https://community.nodebb.org/topic/16909/theme

**Comment by Michaelwucoc** [comment]
This is my topic and  I met a bug :(
When I click the Topic Tool Button, it has no response….

**Comment by barisusakli** [comment]
Please open a new issue with a screenshot of the issue, thanks.

**Comment by Michaelwucoc** [comment]
> Please open a new issue with a screenshot of the issue, thanks.

It is normal now, thanks
