### ISSUE TITLE
v3.0.0 beta.1 issues

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#11157]
### NodeBB version

v3.0.0 beta.1

### Exact steps to cause this issue

Admin panel still shows `Running NodeBB v3.0.0-alpha.3`

I also get the following build warning running a custom Persona child theme:
```
2023-01-17T10:16:14.975Z [4568/729464] - warn: [meta/templates] Partial not loaded: partials/chats-menu.tpl
2023-01-17T10:16:14.975Z [4568/729464] - warn: [meta/templates] Partial not loaded: partials/menu.tpl
```

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/cbb875c7320b58a7a1caf33c96e97aa8a330f587

Version tag was updated that day, you probably have to run `./nodebb upgrade -m`

Child theme issues can be discussed on the forum, as it doesn't seem to be a core issue if only exhibited by a child theme.
