### ISSUE TITLE
Text Bug

### ISSUE THREAD

**Issue by Michaelwucoc** [NodeBB/NodeBB#11161]
![IMG_3991](https://user-images.githubusercontent.com/110759450/212933360-6b18051c-c433-4332-855b-6181f1a956e8.png)

**Comment by barisusakli** [comment]
Seems like the browser doesnt support line-clamp maybe. Is it mobile safari? 

This is what it looks like on chrome

![image](https://user-images.githubusercontent.com/2583394/212934482-32c6c128-9089-408f-8b38-fcce6d5dec88.png)

**Comment by Michaelwucoc** [comment]
Yes, maybe it is a bug on mobile…

**Comment by julianlam** [comment]
Seems on iOS it's just `line-clamp`

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/7571139ee2dbec4af7719fa27386761862765172
