### ISSUE TITLE
draft save icon not aligned with rest of controls

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11164]
![image](https://user-images.githubusercontent.com/2583394/212967874-9e65d206-2c49-47e4-bd73-344b7da2b788.png)

**Comment by julianlam** [comment]
Are you using the right composer version? This is what it looks like for me:

![image](https://user-images.githubusercontent.com/923011/213227285-a6af0800-0c90-4144-b7db-0084f7a157e9.png)


That said, even here the draft indicator is not centred, but the submit buttons look different.
