### ISSUE TITLE
no caret in composer dropdown color doesnt match

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11165]
![image](https://user-images.githubusercontent.com/2583394/212968221-65810398-f203-4557-87d5-acc270e8fd21.png)

**Comment by julianlam** [comment]
@barisusakli `E_NOREPRO`

![image](https://user-images.githubusercontent.com/923011/213227495-9cc63938-056e-4b96-8c90-36a799547e24.png)

**Comment by barisusakli** [comment]
latest composer + question and answer plugin
![image](https://user-images.githubusercontent.com/2583394/213249661-69e93e4d-d066-4d23-9f40-39a2e4abb174.png)
