### ISSUE TITLE
Navigator: text overlaps when close to the end of topic

### ISSUE THREAD

**Issue by vladstudio** [NodeBB/NodeBB#11183]
When I'm approaching the end of the topic, 2 block of text (current post info, # unread) overlap.

<img width="183" alt="image" src="https://user-images.githubusercontent.com/914320/213701531-87eb7c68-1147-4355-ae68-7f6fcdd36cf1.png">

Possible solution: hide "# unread" after the navigator knob is down, say, > 60%.

**Comment by julianlam** [comment]
At-a-glance navigator removed and original nav restored :smile:
