### ISSUE TITLE
due to opacity post tools goes behind quick reply

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11180]
![image](https://user-images.githubusercontent.com/2583394/213358178-d4da04b5-c6e4-4173-ae15-0ead01a5a4d4.png)

**Comment by julianlam** [comment]
Under what condition is the entire topic faded? :thinking:

**Comment by barisusakli** [comment]
Entire topic isn't faded the last above in the above screenshot is deleted so it has opacity, opening its dropdown goes under quickreply
