### ISSUE TITLE
topic filters are asking text input on mobile

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#11191]
### NodeBB version

3

### Anything else?

each time topic filters are pressed, it behaves as text box on mobile, and the keyboard automatically appears and occupies more than half of the screen. 

https://community.nodebb.org/post/90839

**Comment by aryatalathi** [comment]
Can I work on this issue?

**Comment by julianlam** [comment]
@AliCihan That's intentional insofar as it focuses the cursor into a textbox so you can filter the categories.

This was added by @barisusakli so that you wouldn't have to scroll endlessly if you have many many categories in your forum.

**Comment by AliCihan** [comment]
> @AliCihan That's intentional insofar as it focuses the cursor into a textbox so you can filter the categories.
> 
> This was added by @barisusakli so that you wouldn't have to scroll endlessly if you have many many categories in your forum.

@julianlam @barisusakli 
this is creating a bad experience on mobile since it limits the screen size that is available and makes the search without text very unpractical. Can it be optional in ACP? 
So, if a forum has many categories, they can choose to use this. But otherwise, they disable it and rely on the dropdown menu?

**Comment by julianlam** [comment]
It is already fixed 😄

**Comment by AliCihan** [comment]
> It is already fixed 😄

lol sorry, I was not aware. I have just checked and it is definitely better, thanks. 
you have to click twice if you want to get text input; and just once if you want to pick from the list. 👍
