### ISSUE TITLE
Unable to leave chat room

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#11239]
The below caller.uid needs a parseInt wrapped around it for the equality check to be true otherwise it falls into the else and errors if you arent the owner of the chat room

https://github.com/NodeBB/NodeBB/blob/24e58c289587c52aaf02417a276ac120dfac7606/src/api/chats.js#L112-L116

**Comment by barisusakli** [comment]
What version of nodebb? And how do you reproduce? I tried to leave a room that I am not the owner of and it worked fine. caller.uid is either `req.uid` or ` socket.uid` both are numbers. 🤔

**Comment by uplift** [comment]
v2.8.1

I forgot to add this is through the API. 

The caller.uid is definitely a string if I typeof the value.

Also using Session Sharing plugin if that impacts it

**Comment by barisusakli** [comment]
Can you share how you are calling the api? I want to find out how req.uid is becoming a string. Maybe add a console.log(new Error('a').stack) right before the if check

**Comment by uplift** [comment]
The api url is 

```
setupApiRoute(router, 'delete', '/:roomId/users/:uid', [...middlewares, middleware.assert.room, middleware.assert.user], controllers.write.chats.kickUser);
```

Stack trace:-

Chats.kickUser (\src\controllers\write\chats.js:83:16)
at async \src\routes\helpers.js:73:5

**Comment by barisusakli** [comment]
I meant how are you making the request to the API? via curl or something else etc?

**Comment by barisusakli** [comment]
👍🏼 I will take a look, we will probably parseInt the _uid when we get it on our side so we don't have to parseInt all the `caller.uid` variables everywhere.

**Comment by barisusakli** [comment]
Can you test the above change?
