### ISSUE TITLE
Missing Loc keys in Error.json

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#11241]
These keys seem to be missing from en-gb language error.json file.

https://github.com/NodeBB/NodeBB/blob/0713482bd414219ee4b51804102c7751ff2a4c3f/src/messaging/rooms.js#L15

https://github.com/NodeBB/NodeBB/blob/0713482bd414219ee4b51804102c7751ff2a4c3f/src/messaging/rooms.js#L92

https://github.com/NodeBB/NodeBB/blob/0713482bd414219ee4b51804102c7751ff2a4c3f/src/messaging/rooms.js#L110

https://github.com/NodeBB/NodeBB/blob/0713482bd414219ee4b51804102c7751ff2a4c3f/src/messaging/rooms.js#L195

**Comment by julianlam** [comment]
Is this v3 or v2.x?

**Comment by barisusakli** [comment]
Seems like 2.x

**Comment by uplift** [comment]
Sorry yeah should have put that in main post. Its v2.8.1 but seems to be case for latest Main/Master branch too
