### ISSUE TITLE
IP Ban not accepting CIDR range format

### ISSUE THREAD

**Issue by GeorgeSpelvin** [NodeBB/NodeBB#11267]
### NodeBB version

2.5.8

### Exact steps to cause this issue

I'm a moderator, not the site owner and help almost exclusively with deleting spam accounts.  I'll review all the new accounts each morning and delete the ones created just for SEO/spam purposes.  It's not uncommon for there to be 20 new accounts and 10 of them from spammers.

Decided to start trying out the IP Blacklist and, no surprise, some of the spammers are using the same IP range.  

### What you expected

Entered a few of the new individual IP address without problem but, when I tried to use the CIDR format for adding a range, I get an error every time.

Entered it as:
X.Y.49.0/255
X.Y.50.0/255

I also tried X.Y.0/255.0/255 but was less surprised when it wouldn't accept a broader range like that.

### What happened instead

The following 2 rules are invalid:

X.Y.49.0/255
X.Y.50.0/255

**Comment by julianlam** [comment]
Thanks @GeorgeSpelvin — this might be a silly question, but when you say `X.Y.`, you are actually putting a real range, right? Not literally?

**Comment by GeorgeSpelvin** [comment]
Absolutely.  So (using made up numbers)  142.128.23.0/255 .  The NodeBB instructions say that should work but fail to pass validation.

**Comment by julianlam** [comment]
I am trying with some CIDR examples and they are all being parsed correctly. Keep in mind that unless I am mistaken (which does happen often), `/255` is not a valid CIDR suffix. The highest is `/32`

**Comment by GeorgeSpelvin** [comment]
First off, btw, thanks for the help.


Huh.  The instructions are:
**Define a single IP addresses per line. You can add IP blocks as long as they follow the CIDR format (e.g. 192.168.100.0/22).**

But doesn't specify limitations.  I changed one line to 103.171.100.0/32 and that was accepted but then I tried 33/64 and that was rejected.  How the heck do you specify higher ranges higher than 32?  What if multiple spammers were from, say, 103.171.100.194-211?

**Comment by julianlam** [comment]
@GeorgeSpelvin You'll have to excuse my inexperience, as my A+ cert (not that it does a damn thing) was granted many many years ago.

If you want to match more IP addresses, you need to specify a **lower** CIDR suffix bit range.

**Comment by GeorgeSpelvin** [comment]
Wikipedia to the rescue, correcting my misunderstanding of CIDR:

"the IPv4 block 198.51.100.0/22 represents the 1024 IPv4 addresses from 198.51.100.0 to 198.51.103.255."  Not quite clear how 22 points represent 1024 addresses but okay.

So, to block out a X.Y.Z.0-255 range, X.Y.Z.0/24 ... with credit to https://www.ipaddressguide.com/cidr for the calculations.

**Comment by julianlam** [comment]
👍

**Comment by julianlam** [comment]
/22 is 2¹⁰, counting back from 32. 2¹⁰ is 1024.
