### ISSUE TITLE
Chats dropdown has invalid HTML

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#11264]
This one's just a bugbear for me.

* The chats dropdown has a `<ul>` with a `<a>` descendant.
* The `<a>` has a `<li>` descendant.
* [ ] The list item should be directly underneath the unordered list element
* [ ] Anchors cannot contain block level elements (renders fine however)

**Comment by julianlam** [comment]
Also this is the perfect use case of `.stretched-link`, which I've been trying to find a use for since we switched to bootstrap 5 lol

**Comment by barisusakli** [comment]
>Anchors cannot contain block level elements

I don't think this matters anymore, as long as you don't have other anchors inside or buttons etc.

**Comment by julianlam** [comment]
Yeah, it doesn't actually matter in practice... call me old-fashioned, still bothers me :laughing:
