### ISSUE TITLE
Refactor out empty chats page

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#11308]
When you go to `/me/chats`, the recent chats are loaded and the main messages area just contains a messaging saying that there is no active chat.

... which is kind of superfluous, we should just load the most recent chat.

**Comment by barisusakli** [comment]
Careful not to break mobile, on mobile the chat list is displayed on /me/chats and when a chat is clicked it displays the messages.

So gotto keep the current behaviour at least on mobile.

**Comment by julianlam** [comment]
Re: mobile, I can use `req.useragent` to determine if it is mobile or not, but I am not sure if I trust it :smile: 

I'll leave it as is :laughing:
