### ISSUE TITLE
"SMTP Transport" client-side helper invoking incorrectly

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#11312]
Language key: `smtp-transport.auto-enable-toast`

This toast (and the associated logic) get executed on page load because it listens to `change` on the form element. Settings v1 changes the form elements on load, but this logic should only get executed on user action.

**Comment by barisusakli** [comment]
I think this fixes that, maybe cherry-pick to dev?
https://github.com/NodeBB/NodeBB/commit/1f62593a21418db4e3c5e86d85de2c4347d14642

**Comment by julianlam** [comment]
Ah 👍

**Comment by julianlam** [comment]
Cherry-picked 8cf4a6f62eab74961f351f0cbf83e53722378e04 into master, thanks!
