### ISSUE TITLE
Let admins change root

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#1133]
http://community.nodebb.org/topic/931/change-default-root-path#6667

**Comment by linonetwo** [comment]
@psychobunny Your plugin is for define the layout of the homepage. Can it change default / to show what is in /recent?

I want to make /recent show in the /, so it shows a stream of posts, instead of showing some categories.

**Comment by barisusakli** [comment]
@linonetwo you don't need a plugin for this, you can change which page is usd for `/` in the ACP at /admin/settings/general#home-page

![image](https://github.com/NodeBB/NodeBB/assets/2583394/8f89add5-2b96-411c-9725-c0a88e6d68e5)

**Comment by linonetwo** [comment]
Thank you! I can't google about this, and chatgpt even tell me to use "custom route plugin" that don't even exist... You are the only one helpful man!

**Comment by julianlam** [comment]
@linonetwo :smile: I guess ChatGPT doesn't know everything after all.
