### ISSUE TITLE
Locked Out

### ISSUE THREAD

**Issue by BubblyStarss** [NodeBB/NodeBB#11358]
### Description

hey its bubbleburddd how long do i have because it says 
i am locked out.
and i am confused what i did can you tell me how much longer i have then...?
![Screenshot 2023-03-14 11 29 43 AM](https://user-images.githubusercontent.com/127879646/225076509-90751e10-9928-4e7f-90c1-56d95605eb6e.png)

**Comment by julianlam** [comment]
One hour

**Comment by BubblyStarss** [comment]
Do you know why i was locked out by chance?

**Comment by BubblyStarss** [comment]
well maybe its because i was using a school computer maybe?
    On Tuesday, March 14, 2023 at 11:50:39 AM CDT, Julian Lam ***@***.***> wrote:  
 
 

Due to too many login attempts.

This is a tracker for bugs for NodeBB, not for regaining account access for forums running NodeBB, thank you.
