### ISSUE TITLE
Minor button alignment issues in chats modal

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#11350]
![image](https://user-images.githubusercontent.com/923011/224456938-dfde87b4-5540-48af-ae75-cc4df840b102.png)

**Comment by julianlam** [comment]
Also the text boxes focuses in on Firefox :x: but works fine in Chrome.

**Comment by DevSources** [comment]
I can't scroll a text in input window (chat). Browser Chrome, PC.
