### ISSUE TITLE
Dependency issue on installation

### ISSUE THREAD

**Issue by danraymond** [NodeBB/NodeBB#11379]
### NodeBB version

2.8.9

### NodeBB git hash

57f14e419f58d62f431e061e05ce7ac757ebb4e9

### NodeJS version

16.0.0

### Database type

MongoDB

### Database version

6.0.5

### Exact steps to cause this issue

Running ./nodebb setup, I get:

Dependencies outdated or not yet installed.                                           
Installing them now...                                                                
                                                                                      
npm ERR! code ERESOLVE                                                                
npm ERR! ERESOLVE unable to resolve dependency tree                                   
npm ERR!                                                                              
npm ERR! While resolving: nodebb@2.8.9                                                
npm ERR! Found: textcomplete@0.18.2                                                   
npm ERR! node_modules/textcomplete                                                    
npm ERR!   textcomplete@"0.18.2" from the root project                                
npm ERR!                                                                              
npm ERR! Could not resolve dependency:                                                
npm ERR! peer textcomplete@"^0.14.2" from textcomplete.contenteditable@0.1.1          
npm ERR! node_modules/textcomplete.contenteditable                                    
npm ERR!   textcomplete.contenteditable@"0.1.1" from the root project                 
npm ERR!                                                                              
npm ERR! Fix the upstream dependency conflict, or retry                               
npm ERR! this command with --force, or --legacy-peer-deps                             
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.       
npm ERR!                                                                              
npm ERR! See /root/.npm/eresolve-report.txt for a full report.                        
                                                                                      
npm ERR! A complete log of this run can be found in:                                  
npm ERR!     /root/.npm/_logs/2023-03-20T01_03_34_278Z-debug.log                      
Error installing dependencies!                                                        
message: Command failed: npm install --omit=dev                                       

### What you expected

install

### What happened instead

error on version of textcomplete version installed 0.18.2 version expected 0.14.2

**Comment by julianlam** [comment]
Have you tried again? I am not seeing an issue running `./nodebb setup` on the master branch (which would be v2.8.9 as well)

**Comment by danraymond** [comment]
HI Yes seems to be an issue my end will keep trying.
