### ISSUE TITLE
children categories on same line as description

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11421]
![image](https://user-images.githubusercontent.com/2583394/228987539-f5c9c3e1-2bdf-4d88-83c2-d13a7bec5cfb.png)
![image](https://user-images.githubusercontent.com/2583394/228987570-0e7acd7d-c2e8-46cc-ba2b-5cb18e71486a.png)

**Comment by vladstudio** [comment]
Fixed in latest commit: https://github.com/NodeBB/nodebb-theme-harmony/commit/eb3e4f498f9e75893b1d12bc89e1403f818bd563
