### ISSUE TITLE
More post queue improvements

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#11431]
* Show link to account info in Actions dropdown
* Add "permaban" button to Actions dropdown
* ~"Warning signs"; show badge in section if any of the following apply~ Suspicion score via weights, all posts are checked and given a score
    * _the score delta that each metric contributes should be configurable_
    * Account is new (reputation `<` `newbiePostDelayThreshold` — poorly named config option, should be renamed)
    * The reply would necro a topic (days since last reply `>` `necroThreshold`)
    * Has zero posts
    * uid in `unverified-users` group
    * Contains an external link
    * Hooks so plugins can define their own (e.g. spam-be-gone could add a badge if the queued post IP or user email is spammy)

**Comment by julianlam** [comment]
@pitaj I wanted to make sure I didn't forget what you told me earlier.

**Comment by julianlam** [comment]
Might be these "warning signs" could have admin-configured "weights", which culminate in a suspicion score (not to make it overly technical or anything...)

e.g. new user is an automatic 5 points, unverified email is another point... caps out at 10 points, and we can colour the badge based on the score... 0 is green, 10 is red...

Which technically then would suggest we should refactor the whole post queue system so that posts are added to the queue based on the score (instead of the rather simple, heavy-handed metrics we use now, which is purely based on reputation threshold)

**Comment by pitaj** [comment]
Instead of badges, I'd rather just see the numbers directly:

- reputation
- # of posts
- age of account
- time since previous reply in topic (good idea there)

Often they might have posted once before, to accrue reputation or make themselves look less suspicious.

And just wanted to clarify that the permaban action should ban for spam and deny the post. Ideally I'd have a way to purge all of their posts when banning, in case they've made previous ones.

**Comment by julianlam** [comment]
Yeah now that I've written it out it makes more sense to refactor the queue system to take additional data into account.

When reviewing the post, the admin should then be able to expand a panel to see all the relevant metrics.

**Comment by barisusakli** [comment]
Showing their post count might be moot because posts don't go into the queue if they already have more than 0 posts. Exception to that rule is if they have been downvoted below the `postQueueReputationThreshold` reputation threshold. Then all their posts go into the queue.

**Comment by julianlam** [comment]
Right, that's a good point.

I think if we go the refactor route, then whether a post ends up in the queue would be more complicated than looking at `postCount < 0 || rep < threshold`... I was thinking we would take all these weights into consideration and queue if it passes a configurable threshold (e.g. 5/10)

**Comment by pitaj** [comment]
One reason to keep around permabanned accounts is to have the emails and usernames on hand for future filtering efforts.

I don't really care too much though, I'd be fine with a "Purge spammer" button instead.

@barisusakli are you sure it's zero posts? I've seen multiple cases where post queue has still caught them.

**Comment by julianlam** [comment]
The specific logic is to queue if the user has less than 0 posts:

https://github.com/NodeBB/NodeBB/blob/c33730530e4f3a5474447b975cba4e6b7c7660c0/src/posts/queue.js#L90

I... don't know when that'd ever happen though.

**Comment by barisusakli** [comment]
Yup if they have been downvoted below the threshold they will go into post queue even if they have 100s of posts.

**Comment by pitaj** [comment]
Just to be clear, what rep does a user start with, what's the default threshold, and what is the threshold on community?

**Comment by barisusakli** [comment]
A user starts with 0 reputation. The default value of `postQueueReputationThreshold` is 0 on new installs, on community it is set to  -2.
