### ISSUE TITLE
Chat message notification time out should be restricted to emails only

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#11445]
When a chat message is sent, NodeBB waits for about a minute to collect additional messages, before issuing a notification to the recipient user.

This is to reduce notification / email spam if multiple chat messages are sent at once.

Given that notifications themselves are merged, this really only applies to emails. Therefore the timeout should only apply when the user elects to be notified via email. Otherwise an instant notification would be preferable.

**Comment by julianlam** [comment]
The chat system has bespoke logic to delay sending of notifications until a timeout is reached. During that timeout, additional message text is concatenated to the notification-to-be.

The logic was also introduced prior to support for notification merge ids.

The logic will need to be unwound and re-implemented using merge ids and handled from within notifications themselves.

**Comment by Nanak360** [comment]
Hey I can take up this issue. Seems straightforward to me.
Still will definitely dig deeper into it and some more clarification might be necessary.

**Comment by julianlam** [comment]
@barisusakli changed the `notificationSendDelay` value to `5` on our community forum which is a more sensible default. That should be changed in addition to this refactor.
