### ISSUE TITLE
MIssing docker image on Github

### ISSUE THREAD

**Issue by MaxWaldorf** [NodeBB/NodeBB#11462]
### NodeBB version

v2.8.11

### Exact steps to cause this issue

Hello,

It seems you changed your pipelines to push new images on github but I can't see anything on the packages distribution on this repository.

Did the pipeline succeed properly?

Cheers

**Comment by julianlam** [comment]
Thanks! Resolved via repo settings 😄 our guidance on this subject will go live on Wednesday
