### ISSUE TITLE
upgrading from 2.x to 3.x fails if forum bootswatch skin is not available

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11511]
from https://community.nodebb.org/topic/17099/2-x-to-3-x-upgrade-error

some skins got removed or renamed, need upgrade script to set it to default if it doesn't exist

**Comment by ShlomoCode** [comment]
@barisusakli this fix handles the default Skin setting for the forum,
But if the option to choose a personal skin in the user settings was enabled, and someone had previously chosen the "Readable" skin after the upgrade of the forum, the display went wrong...
This should also reset the user's skin setting, if their skin is no longer supported

**Comment by barisusakli** [comment]
I will have to write a new upgrade script in 3.1 for that.

**Comment by barisusakli** [comment]
You can run this query to fix it for 'readable'.

```
db.objects.update({
  _key: /^user:\d+:settings$/, 
  "bootswatchSkin": "readable" 
}, {
  $set: { "bootswatchSkin": "" } 
});
```
