### ISSUE TITLE
Deleting a tag in the admin background will remove all the tags of the related posts

### ISSUE THREAD

**Issue by Veronikya** [NodeBB/NodeBB#11515]
### NodeBB version

v3.0.0-rc.2

### Exact steps to cause this issue

In 3.0.0rc I just delete a tag associated with the topic of the tags are deleted, but can be indexed to

**Comment by barisusakli** [comment]
So if a topic has 3 different tags and you delete one of them in the ACP it removes all 3 tags from the topic?

**Comment by Veronikya** [comment]
Yes, all tags of other topics will be removed as long as the tag being removed is related to it.

Hooks return data without attribute tags

**Comment by barisusakli** [comment]
Thanks for reporting, i will fix it
