### ISSUE TITLE
Backtick + brackets + colons is shown as a sad smiley

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11540]
### NodeBB version

v3.0.0 (https://community.nodebb.org)

### Exact steps to cause this issue
text (`Formatted text by Backtick`):

I created a live demo here: https://community.nodebb.org/post/92818

### What you expected

Text will be displayed, closing brackets, and then colons (just like here in Github):
text (`Formatted text by Backtick`):

### What happened instead

It was taken like this:
text (`Formatted text by Backtick` 🙁

**Comment by ShlomoCode** [comment]
https://user-images.githubusercontent.com/78599753/235573721-f09b2489-aca1-4d5f-a046-f129891a2c81.mp4

**Comment by julianlam** [comment]
Hey @pitaj, so I asked ChatGPT how to modify your regular expression to account for this particular edge case, and this was its response :laughing: 

----

> To avoid matching `):` and `(:)` when there is another pair of parentheses in the same line, you can modify the regular expression to use a negative lookahead assertion to check for the presence of another pair of parentheses in the same line. Here's one way to do it:
>
> ```
> new RegExp(`(^|\\s|\\n)(?<!:)(?:(?!.*[()]{1,2}.*[()]{1,2})(?:${asciiPattern}))(?!:)(?=\\n|\\s|$)`, 'g')
> ```
> Here's what's changed:
>
>1.     `(?<!:)` is a negative lookbehind assertion that checks that the previous character is not a colon `:`.
>1.    `(?:(?!.*[()]{1,2}.*[()]{1,2})(?:${asciiPattern}))` is the new capture group. It consists of two negative lookahead assertions and the original capture group containing `asciiPattern`.
>        *    The first negative lookahead assertion `(?!.*[()]{1,2}.*[()]{1,2})` checks that there are no two pairs of parentheses in the same line.
>        *    The second negative lookahead assertion `(?:${asciiPattern})` is the original capture group containing `asciiPattern`.
> 1. `(?!:)` is a negative lookahead assertion that checks that the next character is not a colon `:`.
>
>The first negative lookahead assertion ensures that there are no two pairs of parentheses in the same line. The quantifier `{1,2}` matches one or two of the preceding character, so `[()]{1,2}` matches one or two parentheses. The dot `.` matches any character except line breaks, so `.*` matches any number of characters. Therefore, `.*[()]{1,2}.*[()]{1,2}` matches any line that contains two pairs of parentheses.
>
>With this modification, the regular expression should match `:)` and `:(` only when there is no other pair of parentheses in the same line.

You are welcome... :no_mouth:

**Comment by julianlam** [comment]
It is very likely that this is potentially overkill @ShlomoCode ... you might just have to... not put colons after closing parentheses :smile:

**Comment by julianlam** [comment]
When challenged to check if it works with _other_ parentheses on the same line, ChatGPT updated the expression:

```
new RegExp(`(^|\\s|\\n)(?<!:)(?:(?!.*\\([^()]*${asciiPattern}[^()]*\\)).*${asciiPattern})(?!:)(?=\\n|\\s|$)`, 'g')
```

**Comment by julianlam** [comment]
Not necessarily, it's mostly just a lot of work to fix what is an edge case.

To do it without all the crazy regex, @pitaj would need to excise parts of the code that do not apply to emoji rendering (e.g. backticked text, stuff in code fences, etc.)... but an even simpler solution might even be to not consider ): to be a valid smiley to parse.

If you don't care for smilies to be converted to emoji, you can probably just disable that option in the Emoji plugin :smile:
