### ISSUE TITLE
Inverted tooltips in rtl view

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11559]
### NodeBB version

v3.0.0 (https://community.nodebb.org)

### Exact steps to cause this issue

Enter the user settings and select RTL language, for example Hebrew (he) or Arabic (ar) and save changes

### What you expected

The arrow of the tooltips will point towards the button

### What happened instead

He turns in the opposite direction

### Anything else?

![CleanShot 2023-05-03 at 18 18 47](https://user-images.githubusercontent.com/78599753/235961487-69a88b4d-0479-4d86-bded-3dbf1fbc6d59.gif)

**Comment by barisusakli** [comment]
This is a weird one, it happens on community.nodebb.org  but doesn't happen on local 🤔 
![tooltip](https://user-images.githubusercontent.com/2583394/235977312-8cd9e840-2927-48db-b18e-4c331fcd4fd1.gif)

**Comment by ShlomoCode** [comment]
@barisusakli It is strange! I have no explanation
In my local it appears...
And on community.nodebb.org and on another forum in Hebrew (https://tchumim.com) it appears

**Comment by barisusakli** [comment]
It happens when the css is minified comment out these 3 lines and it should work https://github.com/NodeBB/NodeBB/blob/master/src/meta/minifier.js#L171-L173. Not sure which module has the issue 🤷🏼

**Comment by ShlomoCode** [comment]
@barisusakli So what is actually the way to force a rebuild of the minified CSS, if nodebb build doesn't do it?

**Comment by ShlomoCode** [comment]
@barisusakli I didn't understand...

**Comment by barisusakli** [comment]
running `./nodebb build` minifies it and that process seems to break the direction of the tooltip arrows. If you disable css minification by commenting out those 3 lines then the arrows work, personally I would just hide the arrows and leave the minification in place.

**Comment by ShlomoCode** [comment]
I understood... so there is no solution without canceling the reduction :(
Too bad
But for a forum whose majority of users are in Hebrew, it will be possible to insert the CSS you wrote in ACP Custom CSS :)

**Comment by barisusakli** [comment]
Try with above changes, I think it should be fixed now.

**Comment by barisusakli** [comment]
Should also seems to fix the arrows on sub categories
![image](https://user-images.githubusercontent.com/2583394/235995084-b0d68537-f13c-4b73-8f04-17d6ce5f07c2.png)

**Comment by ShlomoCode** [comment]
> Try with above changes, I think it should be fixed now.

OK, problem solved with that!
It was fast 💪
Thanks!
