### ISSUE TITLE
Composer buttons are hidden in the RTL view

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11558]
### NodeBB version

v3.0.0 - https://community.nodebb.org

### Exact steps to cause this issue

1. Enter the user settings and select RTL language, for example Hebrew (he) or Arabic (ar) and save changes
2. Shrink the size of the browser window a little, something like 80% of the 14" screen
3. Try creating a new topic or replying to an existing topic

### What happened instead

The send/discard post buttons are not visible and cannot be clicked.
The topic can only be sent using the keyboard (ctrl + enter)...
Screenshot attached:
![CleanShot 2023-05-03 at 18 16 09@2x](https://user-images.githubusercontent.com/78599753/235960514-0ab792ab-bb23-480e-be1b-3e8ff8693852.png)

**Comment by ShlomoCode** [comment]
Actually the expected behavior is that the writing box will be on the right side of the screen, and not on the left side. Then the button problem will also be solved.
But if I fix it alone with CSS for the right part of the screen, there is another problem - that part of the width of the category selection box is hidden:

**Comment by ShlomoCode** [comment]
@barisusakli Thanks, but some buttons are still hidden (I ran `npm i nodebb-theme-harmony@1.0.13`):
<img width="1512" alt="CleanShot 2023-05-03 at 18 51 06@2x" src="https://user-images.githubusercontent.com/78599753/235970089-02869366-8dfe-4c17-b4a8-5f5a36dd70e3.png">

---

Additionally, the issue also exists in the Persona theme

**Comment by barisusakli** [comment]
Works fine for me on harmony 1.0.14
![image](https://user-images.githubusercontent.com/2583394/236004705-141e3dae-16b2-4e79-80f1-dd0ceff438f9.png)

**Comment by ShlomoCode** [comment]
@barisusakli Maybe it has to do with screen size?
Mine 14.2" (MacBook Pro)

**Comment by ShlomoCode** [comment]
> Additionally, the issue also exists in the Persona theme
<img width="1502" alt="CleanShot 2023-05-04 at 03 40 58@2x" src="https://user-images.githubusercontent.com/78599753/236080373-51e73cb8-1c59-4228-bb21-c08bd9d7f5f8.png">

**Comment by ShlomoCode** [comment]
Why is this issue closed? 🤔

**Comment by barisusakli** [comment]
Works fine on persona@13.0.62 as well.

![image](https://user-images.githubusercontent.com/2583394/236350555-2c72d468-0dc5-49db-a839-5322a2f66fa1.png)

**Comment by ShlomoCode** [comment]
@barisusakli You're right, I had a plugin that messed up the page display 😧
I apologize for bothering you :(
indeed it works properly in both persona and harmony!
One small problem still exists in harmony@1.0.18 that when the side menu is expanded, part of the category selection drop-down menu is hidden by the side bar:

https://user-images.githubusercontent.com/78599753/236352235-ac3e2301-9147-427e-94a0-755df4d1556c.mp4

**Comment by barisusakli** [comment]
@ShlomoCode fixed in linked issue
