### ISSUE TITLE
"Expand" icon inverted in RTL view

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11560]
### NodeBB version

v3.0.0 - https://community.nodebb.org

### Exact steps to cause this issue

Enter the user settings and select RTL language, for example Hebrew (he) or Arabic (ar) and save changes

### What you expected

When the sidebar is collapsed, the arrow will point to the left (towards the content itself), and when expanded it will be to the right, towards the edge of the screen

### What happened instead

The behavior is the opposite. 
Note that this behavior is normal for LTR display, but not for RTL display

### Anything else?

![CleanShot 2023-05-03 at 18 22 32](https://user-images.githubusercontent.com/78599753/235962396-a0096102-14d9-47ac-9f09-5c74411338fd.gif)

**Comment by ShlomoCode** [comment]
@barisusakli This is weird... I upgraded to nodebb-theme-harmony@1.0.14:
![CleanShot 2023-05-03 at 19 45 36@2x](https://user-images.githubusercontent.com/78599753/235984283-c8c40528-090b-4653-9532-4531826ef260.png)
But the correction is not noticeable! I also did a build...
<img width="312" alt="CleanShot 2023-05-03 at 19 47 09@2x" src="https://user-images.githubusercontent.com/78599753/235984398-a9803dba-f1ad-45de-8ef5-7d77d564b45f.png">
But when I insert the CSS you wrote in the DevTools, it does correct..
Does it work for you?

**Comment by barisusakli** [comment]
Yes it works for me.

![toggle](https://user-images.githubusercontent.com/2583394/236079021-0bd2f7be-d71f-4a5f-8042-7427fa298f53.gif)

**Comment by ShlomoCode** [comment]
@barisusakli Yes, now I tried to reinstall and build and it works! Looks like there was some cache issue or something similar
apologetic
