### ISSUE TITLE
Downvote, upvote, follow,unfollow,bookmark,unbookmark apis  not working....

### ISSUE THREAD

**Issue by virtuoustechlogic3** [NodeBB/NodeBB#11582]
https://community.nodebb.org/api/v3/topics/{tid}/follow
https://community.nodebb.org/api/v3/posts/{pid}/vote
https://community.nodebb.org/api/v3/posts/{pid}/bookmark

i want to use this apis to integrate in flutterproject but its not working
![post](https://user-images.githubusercontent.com/123167713/236993616-cff1279c-4fd3-4e42-9afa-eea82a865a01.png)

I am working on forum based project where I used nodebb apis for fetching topics and I want to downvote, upvote,and flow topic 

Thanks in Advance...

**Comment by julianlam** [comment]
https://community.nodebb.org/topic/17184/getting-below-response-while-integrating-vote-put-delete-bookmark-put-delete-follow-put-delete
