### ISSUE TITLE
error on upgrade from 3.0.1 to 3.10

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#11588]
### NodeBB version

v3.1.0

### NodeJS version

v20.1.0

### Database type

PostgreSQL

### Database version

15.2

### Exact steps to cause this issue

Upgrade to v3.1.0
```
git fetch
git stash
git checkout v3.x
git merge origin/v3.x
./nodebb upgrade
```

### What you expected

a clean build

### What happened instead

`error: uncaughtException: ENOENT: no such file or directory, scandir '.../NodeBB/node_modules/nodebb-theme-harmony/languages'`

the issue is easy to fix.
Once I manually created the languages folder, it builds cleanly

**Comment by barisusakli** [comment]
That's weird the languages folder is removed in the latest harmony, what version of harmony is installed in your build? It should be  "nodebb-theme-harmony": "1.0.24",

**Comment by barisusakli** [comment]
What do you have in your package.json/plugin.json in the child theme?

**Comment by sweetppro** [comment]
**package.json**

`{
  "name": "nodebb-theme-harmony-sweetp",
  "version": "1.0.0",
  "author": {
    "name": "SweetP Productions, Inc",
    "url": "https://sweetpproductions.com"
  },
  "description": "SweetP Productions NobeBB support forums custom harmony theme",
  "repository": {
    "type": "git",
    "url": "https://github.com/sweetppro/nodebb-theme-sweetp"
  },
  "keywords": [
    "nodebb",
    "theme",
    "forum",
    "responsive",
    "sweetp"
  ],
  "nbbpm": {
    "compatibility": "^3.0.0"
  },
  "main": "lib/theme.js",
  "license": "MIT"
} `

**plugin.json**

`{
    "id": "nodebb-theme-harmony-sweetp",
    "url": "https://github.com/sweetppro/nodebb-theme-sweetp",
    "hooks": [
        { "hook": "static:app.load", "method": "init" },
        { "hook": "filter:admin.header.build", "method": "addAdminNavigation" },
        { "hook": "filter:config.get", "method": "getThemeConfig" },
        { "hook": "filter:settings.get", "method": "getAdminSettings" },
        { "hook": "filter:user.saveSettings", "method": "saveUserSettings" },
        { "hook": "filter:user.profileMenu", "method": "addProfileItem" },
        { "hook": "filter:middleware.render", "method": "removeFinalBreadcrumb" }
    ],
    "scripts": [
        "../nodebb-theme-harmony/public/harmony.js",
        "scripts/sweetp.js"
    ],
    "modules":
    {
        "../admin/plugins/harmony.js": "../nodebb-theme-harmony/public/admin.js",
        "../client/account/theme.js": "../nodebb-theme-harmony/public/settings.js",
        "sweetp/customHelpers.js": "public/modules/customHelpers.js",
        "sweetp/customHelpers-common.js": "public/modules/customHelpers-common.js"
    },
    "templates": "templates",
    "languages": "../nodebb-theme-harmony/languages"
} `



https://github.com/sweetppro/nodebb-theme-sweetp/blob/master

**Comment by barisusakli** [comment]
remove this line ` "languages": "../nodebb-theme-harmony/languages"`

**Comment by barisusakli** [comment]
We moved the language files to core so you don't need that line anymore

**Comment by sweetppro** [comment]
@barisusakli so obvious. Thanks
