### ISSUE TITLE
Some translations were not updated from transifex in version 3.1.0

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11586]
### NodeBB version

v3.1.0

### What you expected

The translations I made in transifex between the release of version 3.0.1 and the release of 3.1.0 will be included in 3.1.0

### What happened instead

Some of them have not been updated. For example all the strings on the search page, even though I translated them in transifex a few days ago

### Anything else?

I don't know if it's like that in every language, but I translated in Hebrew and it didn't go in.

**Comment by julianlam** [comment]
Thanks for the report, it looks like @nodebb-misty stopped updating translations. It looks like the underlying `tx` client got updated :thinking:

**Comment by julianlam** [comment]
`--parallel` is no longer a valid argument. Interesting.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/77212c4219391f4813c473bf6772333b1245f5d9

**Comment by julianlam** [comment]
Thanks for bringing this to our attention @ShlomoCode, we will release a patch version with the latest translations today.
