### ISSUE TITLE
[2.8.13] req.csrfToken is not a function error

### ISSUE THREAD

**Issue by MaxWaldorf** [NodeBB/NodeBB#11617]
### NodeBB version

v2.8.13

### NodeBB git hash

Official v2.8.13 container

### NodeJS version

Using container version

### Exact steps to cause this issue

With DB Search plugin and imgur plugins, I am getting the following error when navigating throught the admin plugin interface:

`Error: req.csrfToken is not a function`

It is a regression as it crashes NodeBB instantly...

**Comment by barisusakli** [comment]
Released 2.8.14 with the fix
https://github.com/NodeBB/NodeBB/releases/tag/v2.8.14
