### ISSUE TITLE
"Moved from" label looks like a link

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#11634]
![image](https://github.com/NodeBB/NodeBB/assets/923011/983deb07-18b3-4d16-9735-b61e1f75f8e0)

:point_up: 

The badge should either be muted (`text-secondary` etc.), or the badge should link to the old cid.

Maybe both.

**Comment by barisusakli** [comment]
Those labels all have the same style, pinned/locked/scheduled etc so just made it a link to the old category

![image](https://github.com/NodeBB/NodeBB/assets/2583394/6dc08380-3006-4509-8a18-3ede7eae492c)
