### ISSUE TITLE
Long text comes out of the post in RTL view

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11643]
### NodeBB version

v3.1.4 (https://community.nodebb.org)

### Exact steps to cause this issue

1. Change your language settings (here https://community.nodebb.org/me/settings) to RTL language, like Hebrew/Arabic
2. Go to this example post: https://community.nodebb.org/topic/17228/long-text-test

### What you expected

The text will not go outside the width of the post, even if it is long

### What happened instead

If the text is long, it just slides out (screenshot attached)

### Anything else?

![CleanShot 2023-05-29 at 01 45 47@2x](https://github.com/NodeBB/NodeBB/assets/78599753/4ba8e258-1924-48fe-b6f6-cb7cfedac0b9)

**Comment by barisusakli** [comment]
https://getbootstrap.com/docs/5.2/utilities/text/#word-break, seems like bootstrap removes text-break from their rtl css due to arabic.

Maybe you can add it back in your custom css with the below.

```
html[data-dir="rtl"] {
    .text-break {
        word-wrap: break-word!important;
        word-break: break-word!important;
    }
}
```

**Comment by ShlomoCode** [comment]
@barisusakli Yes it solves... but there is no general solution?
Maybe check the language and according to that apply a break? If I understand correctly the problem exists only in Arabic and not in other RTL languages
Another point is that it is very possible that it is better to break the word in Arabic as well and disrupt the word in case it is a very, very long sentence, than it will just continue and float out of the post in an ugly way in fact
Maybe in other elements the bootstrap approach is correct, but in the post box it seems wrong to me

**Comment by barisusakli** [comment]
Not sure if we should add this into core or not but you can also check the language in the css.

```
html[lang="he"] {
    .text-break {
        word-wrap: break-word!important;
        word-break: break-word!important;
    }
}
```

And it will only apply to hebrew.

**Comment by ShlomoCode** [comment]
I think it's better to cut a word than this thing...
![CleanShot 2023-05-30 at 04 58 19](https://github.com/NodeBB/NodeBB/assets/78599753/2e1ea288-2704-4505-94b8-aeb3870d40cd)
 @julianlam What do you think?
