### ISSUE TITLE
code blocks is right-aligned in RTL view

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11655]
### NodeBB version

v3.1.4 (https://community.nodebb.org)

### Exact steps to cause this issue

1. Change your language settings (here https://community.nodebb.org/me/settings) to RTL language, like Hebrew/Arabic
2. Go to this example post: https://community.nodebb.org/post/93580

### What you expected

The code block will be aligned to the left, since there is no programming language that is in the RTL language, the programming language will always be in English - LTR

### What happened instead

The code block is aligned to the right (screenshot attached)

### Anything else?

<img width="981" alt="CleanShot 2023-05-31 at 02 44 48@2x" src="https://github.com/NodeBB/NodeBB/assets/78599753/9fc21da6-5f72-4760-923f-3355be911256">

**Comment by barisusakli** [comment]
There is a fix for this on the forum https://community.nodebb.org/post/92172.

I added it into core so it will be available in 3.2.0
