### ISSUE TITLE
Topic searching does not work when "Enable In-Topic Searching" is enabled in ACP

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11673]
### NodeBB version

v3.1.4

### NodeBB git hash

9f3bdf75d00e2978fb60410d05a5c1debb3e12cf

### NodeJS version

v20.1.0

### Database type

MongoDB

### Exact steps to cause this issue

1. Activate the setting "Enable In-Topic Searching" in ACP (`/admin/settings/user#user-search`)
2. Build and restart
3. Go to topic page
4. Press F5 on your keyboard to search

### What you expected

In the past (nodebb v2) it would open a quick search of the forum within the topic, and pressing F5 again would open the browser's built-in search window

### What happened instead

Nothing happens even when you press F5 several times

**Comment by ShlomoCode** [comment]
@barisusakli Not fixed for me... :(
Updated devlop branch (git hash: 9522951fbde4f600c4ed2b940efeb11b9761f1dd)

**Comment by barisusakli** [comment]
Works for me, did you enable it in user settings? The user setting overrides the acp setting. 

![image](https://github.com/NodeBB/NodeBB/assets/2583394/072bc416-6816-421a-b46c-3150bcd868d1)

After hitting ctrl+f I get this. 
![image](https://github.com/NodeBB/NodeBB/assets/2583394/b5294608-c9b4-47fb-9a04-29ce6a987b64)
 and the results are from that topic

**Comment by ShlomoCode** [comment]
@barisusakli This setting does not appear at all in the user settings, even when it is marked Boy in the default settings in ACP (http://localhost:4567/admin/settings/user#default-user-settings) and when it is not
<img width="540" alt="CleanShot 2023-06-12 at 01 34 29@2x" src="https://github.com/NodeBB/NodeBB/assets/78599753/fafb4e06-a723-41a0-a885-1c799d703834">

**Comment by barisusakli** [comment]
That means the search plugin you are using doesn't implement in topic searching, try with nodebb-plugin-dbsearch

**Comment by ShlomoCode** [comment]
@barisusakli Yes you are right! working. Thank you
