### ISSUE TITLE
No indication of invalid image type when uploading favicon (ASC)

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11706]
### NodeBB version

v3.1.4

### Exact steps to cause this issue

When uploading a favicon (/admin/settings/general), when I choose a png image type it seems to upload properly, while there is an error and the file is not saved

### What you expected

An error message will appear

### What happened instead

Nothing appears, and only in DevTools can you see the error

### Anything else?

<img width="1181" alt="CleanShot 2023-06-13 at 16 38 00@2x" src="https://github.com/NodeBB/NodeBB/assets/78599753/0a5db200-e11e-4c23-8018-e327a218ffb2">

**Comment by barisusakli** [comment]
Seems like there is an error but API is returning 200, will take a look

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/11707
