### ISSUE TITLE
Login Forbidden Error

### ISSUE THREAD

**Issue by Michaelwucoc** [NodeBB/NodeBB#11710]
### NodeBB version

v3.1.4

### Database type

MongoDB

### Database version

v5.0.9

### Exact steps to cause this issue

When I log into the admin panel, I met a forbidden error.
![Screenshot_20230612_231628_com huawei browser](https://github.com/NodeBB/NodeBB/assets/110759450/d6abe157-cc77-4dfb-907a-77c5fa40c218)
I need to logout and login again to solve it

**Comment by Michaelwucoc** [comment]
Yes,it also happens on my computers.
It only happens when I try to log in to the admin panel again

**Comment by zach28attack** [comment]
Hi I would like to work on this if possible.

**Comment by julianlam** [comment]
@Michaelwucoc are you still seeing this issue, and if you clear your cookies, does it resolve the issue?

**Comment by Michaelwucoc** [comment]
> @Michaelwucoc are you still seeing this issue, and if you clear your cookies, does it resolve the issue?

I tried to open the site in Incognito mode, but it still doesn't work....

**Comment by Michaelwucoc** [comment]
I seemed to be a csef error or sth.? I dont know what is that kind of thing..

**Comment by barisusakli** [comment]
How is ssl handled? Do  you have https or http in your config.json? This sounds similar to https://github.com/NodeBB/NodeBB/issues/11011

**Comment by bukaixyz** [comment]
> Does this happen when you do not use the Huawei browser?
> 
> Does this only happen when you are away from the admin panel for an hour or so, and then try to access the admin panel again?

Huawei is garbage🌝

**Comment by Michaelwucoc** [comment]
Yeah! I solved by #11011 !
I add an SSL To my website and it wont happen again!
tysm!
