### ISSUE TITLE
Topic Paging postIndex always set to 1

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#11731]
When using the api to do paging on a topic eg ?page=2 etc, the postIndex always returns the value of 1 even though that index isnt on that page. Should it return the top index (depending on user sort setting) for that page?

https://github.com/NodeBB/NodeBB/blob/090a792168d798f78cf711599edd101f34cc3d67/src/controllers/topics.js#L31

**Comment by barisusakli** [comment]
postIndex is mainly used for infinite scroll mode in client side, when it is > 1 then client side will scroll to that post https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic.js#L151-L154. 

So it would require changing those places to add a `!config.usePagination` check as well.

**Comment by uplift** [comment]
I think we use the topic navigator different to the default themes (its been a while since I've used them) in that we have the topic navigator using the postIndex but it only navigates the existing page like a quick scroller. Then we have paging instead of infinite scroll so when you change pages it still has bottom of the last page set as postIndex until page is scrolled. Its not a big issue but I guess its using API data different to how it was originally intended.

**Comment by barisusakli** [comment]
@uplift is your forum public somewhere?

**Comment by barisusakli** [comment]
postIndex will be set in nbb 3.2.0 when you have ?page=2 in the url.
