### ISSUE TITLE
Can Voting privilege be returned in Topic data

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#11732]
### Description

This is using API but I think the same is with Persona theme.

Upvote button is shown in the UI but if the user doesn't have privileges to vote on a topic when clicking the upvote button they get an error. It would be good to either hide or disable the button based on their privilege. Is it possible for this data to be in the api request response?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/11734
