### ISSUE TITLE
feature to create a home page that connect to the forum and SAAS plugin

### ISSUE THREAD

**Issue by AlstonDar** [NodeBB/NodeBB#11752]
### Description

As the direct connection of the forum page may look weird sometimes so it is better if the user is able to create a home page and a option to route his forum to a domin using saas plugin. thank for your time and the forum that u have created has help me a lot as i don't know much about coding.

**Comment by ShlomoCode** [comment]
@AlstonDar Creating a custom HTML page: https://github.com/NodeBB-Community/nodebb-plugin-custom-pages#readme
You can set all users as the "home page" the custom page you will create in ACP: `https://your-forum.com/admin/settings/general#home-page`
