### ISSUE TITLE
admins can't upvote if they have 0 rep

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11766]
Should probably let them upvote.
From https://community.nodebb.org/topic/17366/definition-that-restrictions-cannot-on-managers

**Comment by Mordechay0000** [comment]
it is necessary to disable all restrictions (including file restrictions, etc.). Perhaps in the administration settings, there can be an option to allow administrators to bypass the restrictions. It would be great if administrators can choose which specific restrictions they can bypass. Additionally, it would be helpful to display a warning before bypassing any restriction.

**Comment by Mordechay0000** [comment]
The post/header length restrictions as well as the file size limit for uploading still remain

**Comment by barisusakli** [comment]
Open separate issues for those
