### ISSUE TITLE
a widget hidden from the "spiders" group is displayed for Google Bot

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11765]
### NodeBB version

v3.1.4

### Database type

MongoDB

### Exact steps to cause this issue

Create a widget and set it as hidden to the "spiders" group
![CleanShot 2023-06-29 at 01 39 51@2x](https://github.com/NodeBB/NodeBB/assets/78599753/3eed8679-6f76-448f-9664-fb7f591557ea)

### What you expected

The widget will not load for bots, including the Google search bot

### What happened instead

The widget still appears in the search results and also in Google's page test:
![CleanShot 2023-06-29 at 01 37 09@2x](https://github.com/NodeBB/NodeBB/assets/78599753/a89b0cdb-fb9e-4ac6-8762-4918e5232bc4)

**Comment by ShlomoCode** [comment]
Even when changing User Agent to Google (from https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers#common-crawlers) using this official Google extension [User-Agent Switcher for Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg) the widget is not hidden.

**Comment by barisusakli** [comment]
@Schamper thanks for reporting
https://github.com/NodeBB/NodeBB/commit/7d5fe20b105e45c765f6d5e4d70de5a55982cfeb

**Comment by ShlomoCode** [comment]
@barisusakli The widget still appears in the active URL check in Google Search Console, even after upgrading to the last commit in the master

**Comment by barisusakli** [comment]
Can you add a console.log at this line https://github.com/NodeBB/NodeBB/blob/master/src/widgets/index.js#L104 and let me know the result when you access it via google console?

`console.log(uid, isHidden, data.groupsHideFrom)`. 

When accessing as a spider uid should be -1.

**Comment by ShlomoCode** [comment]
@barisusakli I'm having a hard time isolating the Google bot request from people's normal browsing to the site, this is what I managed (i inspect the url `https://madrichim.ovh/`):
https://gist.github.com/ShlomoCode/dfddf6d96334402e85068b50f428a4cb

**Comment by barisusakli** [comment]
```
-1 true [ 'spiders' ]
-1 true [ 'spiders' ]
```

This looks correct to me 🤔 not sure why it shows up on google chrome console though.

**Comment by ShlomoCode** [comment]
@barisusakli It's not Google Chrome Console, it's Google **Search** Console - https://search.google.com/search-console
In any case, I sent a page from the website to be re-scanned by Google, after which I will check if the text in the widget stopped appearing in the summary of the result in Google.

**Comment by barisusakli** [comment]
Yeah sorry I meant google search console, I tested there too and I see the widget in the screenshot that is supposed to be hidden.

**Comment by ShlomoCode** [comment]
@barisusakli You are right... the UA is `Mozilla/5.0 (compatible; Google-InspectionTool/1.0;)` or `Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Google-InspectionTool/1.0;)` which is not included in the directory you linked...

**Comment by barisusakli** [comment]
You can send a PR to that repo to add Google-InspectionTool, they added  /Google-Structured-Data-Testing-Tool/i, some time ago

**Comment by ShlomoCode** [comment]
After a (normal) Google rescan of the page, the widget no longer appears in the indexed HTML displayed in Google Search Console
When I google the address the widget text still appears, but it will probably be updated over time.
Thank you @barisusakli!

**Comment by ShlomoCode** [comment]
After upgrading to `spider-detector@2.0.1`, the widget is properly hidden in live page inspection
<img width="378" alt="CleanShot 2023-06-30 at 03 21 05@2x" src="https://github.com/NodeBB/NodeBB/assets/78599753/2a9fec20-1e6c-4a01-bcfd-04d33dc74f90">

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/97d8f85816d8281a067c71bb36da6437926103c2
