### ISSUE TITLE
nodebb failed to load RTL version of skins css

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11775]
### NodeBB version

v3.2.0

### Installed NodeBB plugins

Active plugins:
	* nodebb-plugin-2factor@7.1.3 (installed, disabled)
	* nodebb-plugin-browsing-users@3.1.0 (installed, enabled)
	* nodebb-plugin-cloudstorage@1.0.24 (installed, disabled)
	* nodebb-plugin-composer-default@10.2.3 (installed, enabled)
	* nodebb-plugin-contact-page@1.3.0 (installed, enabled)
	* nodebb-plugin-custom-pages@2.0.3 (installed, enabled)
	* nodebb-plugin-customize@4.0.0 (installed, enabled)
	* nodebb-plugin-dbsearch@6.1.0 (installed, enabled)
	* nodebb-plugin-emoji@5.1.2 (installed, enabled)
	* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
	* nodebb-plugin-emoji-apple@4.0.0 (installed, enabled)
	* nodebb-plugin-extended-markdown@2.0.1 (installed, enabled)
	* nodebb-plugin-markdown@12.1.4 (installed, enabled)
	* nodebb-plugin-mentions@4.2.0 (installed, enabled)
	* nodebb-plugin-ns-embed@6.0.0 (installed, enabled)
	* nodebb-plugin-ntfy@1.0.15 (installed, disabled)
	* nodebb-plugin-question-and-answer@1.1.0 (installed, enabled)
	* nodebb-plugin-recent-cards-free@0.1.1 (installed, enabled)
	* nodebb-plugin-spam-be-gone@2.1.0 (installed, disabled)
	* nodebb-plugin-sso-github@3.1.0 (installed, enabled)
	* nodebb-plugin-sso-google@3.1.0 (installed, enabled)
	* nodebb-rewards-essentials@0.2.3 (installed, enabled)
	* nodebb-theme-harmony@1.0.64 (installed, enabled)
	* nodebb-theme-lavender@7.1.1 (installed, disabled)
	* nodebb-theme-peace@2.0.32 (installed, disabled)
	* nodebb-theme-persona@13.1.6 (installed, disabled)
	* nodebb-widget-essentials@7.0.13 (installed, enabled)

### Database type

MongoDB

### Exact steps to cause this issue

1. Go to user settings, set the language to RTL language - for example Hebrew
2. Change the skin to any skin, for example lumen
3. Save and refresh the page

### What you expected

The forum tries to load an RTL version of the design, for example `/assets/client-lumen-rtl.css`, but a 404 error page is received
When loading `/assets/client-lumen.css` there is no error and the theme is loaded
**The strange thing about https://community.nodebb.org is that it works properly**, but both on me and on another forum of a friend in the same version, it doesn't work, as described

### Anything else?

The problem is both in persona and Harmony

**Comment by barisusakli** [comment]
@ShlomoCode thanks for reporting will be fixed in 3.2.1

**Comment by ShlomoCode** [comment]
@barisusakli Thank you, I'm just curious how the address did work in the community forum? (for example https://community.nodebb.org/assets/client-sandstone-rtl.css)

**Comment by barisusakli** [comment]
Probably files cached by nginx, I was able to reproduce the issue on my local
