### ISSUE TITLE
dropdown of tpl is partially hidden in RTL

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11804]
### NodeBB version

v3.2.2 (from master)

### NodeBB git hash

`562e4d6e439547167677cb6bce4743a2d1d7d77f`

### Exact steps to cause this issue

1.Change the management language to the RTL language, for example Hebrew
2. Go to /admin/extend/widgets
3. Click on the TPL selection dropdown (where the widget will appear, for example global/posts)

### Anything else?

<img width="224" alt="CleanShot 2023-07-15 at 23 24 10@2x" src="https://github.com/NodeBB/NodeBB/assets/78599753/73bfa42f-d609-4ce6-9411-e89cb0aaac73">

**Comment by barisusakli** [comment]
@ShlomoCode thanks for reporting, let me know if you notice any other odd dropdowns like that.

![image](https://github.com/NodeBB/NodeBB/assets/2583394/44e89756-5dad-4e24-89dd-c6374ced613c)

**Comment by ShlomoCode** [comment]
@barisusakli I don't see anything like that, but when I searched I saw 2 other small bugs:

in `/admin/advanced/logs` - the content is wider than the screen size:
<img width="1512" alt="CleanShot 2023-07-16 at 02 20 45@2x" src="https://github.com/NodeBB/NodeBB/assets/78599753/1d498e5f-a8da-4883-ac59-7da2ae271b8c">

in `/admin/manage/uploads` - a link to the current page appears:

![CleanShot 2023-07-16 at 02 21 05@2x](https://github.com/NodeBB/NodeBB/assets/78599753/e8058675-d9fc-4168-b3a0-d7fad394215b)

**Comment by barisusakli** [comment]
@ShlomoCode https://github.com/NodeBB/NodeBB/commit/2a3d6d5cfb002e05c384deaf2571c04444f3a109
