### ISSUE TITLE
The admin toc list javascript error when language is non english

### ISSUE THREAD

**Issue by astontek** [NodeBB/NodeBB#11802]
### Database type

MongoDB

### Exact steps to cause this issue

The admin toc list throws javascript error when language is non english. The reason is the code is using section text as element id, it is ok for english, but caused error when language is unicode since jquery does not allow unicode for query.

Fix: just simply use section for element id.
https://github.com/NodeBB/NodeBB/blame/master/public/src/admin/settings.js
headers.each(function (i) {
	const header = $(this).text();
	const anchor = `section${i}`;

**Comment by barisusakli** [comment]
@astontek thanks for reporting, we still want `/admin/settings/general#home-page` to take you to the correct place, so we will have to use non translated names for the anchors. If we use `section${index}` url would look like `/admin/settings/general#section3`

**Comment by astontek** [comment]
@barisusakli thanks for your quick reply. It works perfectly for users that use locale like en-US etc, but it will throw errors if you switch your locale to others, try zh-CN, you will see the errors.

**Comment by barisusakli** [comment]
Yeah I know, I will update the anchor ids so they don't use translated text.

**Comment by astontek** [comment]
Thank you. That is perfect, just need more work.
