### ISSUE TITLE
Code display in RTL

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#11806]
### NodeBB version

v3.2.2 (https://community.nodebb.org)

### Exact steps to cause this issue

change user lang to hebrew

go to https://community.nodebb.org/post/94651

### Anything else?

<img width="1069" alt="CleanShot 2023-07-16 at 03 03 48@2x" src="https://github.com/NodeBB/NodeBB/assets/78599753/3c28dd2c-8f1c-400f-a488-5a979dff256d">

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-markdown/commit/1e347bdf24faae1909c983be4fd59b7dec521c20

**Comment by barisusakli** [comment]
@ShlomoCode I updated https://community.nodebb.org/ with the fixes, thanks for reporting

**Comment by ShlomoCode** [comment]
@barisusakli It still looks better on the LRT 😀
![CleanShot 2023-07-16 at 04 25 41@2x](https://github.com/NodeBB/NodeBB/assets/78599753/463a4a35-cd69-487a-b46c-6536b5cf72ec)

![CleanShot 2023-07-16 at 04 25 57@2x](https://github.com/NodeBB/NodeBB/assets/78599753/718f6087-4190-4077-a055-1162a840ac9a)

**Comment by barisusakli** [comment]
@ShlomoCode https://github.com/NodeBB/nodebb-plugin-markdown/commit/16bcf020607da19ff30645de423425ba56d498dd this fixes the rest of those issues.

![image](https://github.com/NodeBB/NodeBB/assets/2583394/61cf5b66-12e1-43e7-b150-03cb84d08686)
