### ISSUE TITLE
Registration interstitial allows email to be changed to one that's already in use

### ISSUE THREAD

**Issue by 3ldor** [NodeBB/NodeBB#11836]
### NodeBB version

v3.2.3

### NodeBB git hash

b06d3e63cbdd0f00aed73dd8550221e5ee48ba2f

### NodeJS version

v18.16.0

### Installed NodeBB plugins

* nodebb-plugin-2factor@7.1.3 (installed, enabled)
* nodebb-plugin-composer-default@10.2.4 (installed, enabled)
* nodebb-plugin-dbsearch@6.1.0 (installed, enabled)
* nodebb-plugin-emoji@5.1.3 (installed, enabled)
* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
* nodebb-plugin-markdown@12.1.4 (installed, enabled)
* nodebb-plugin-mentions@4.2.0 (installed, enabled)
* nodebb-plugin-ntfy@1.0.15 (installed, disabled)
* nodebb-plugin-quickstart@0.3.1 (installed, disabled)
* nodebb-plugin-spam-be-gone@2.1.1 (installed, disabled)
* nodebb-rewards-essentials@0.2.3 (installed, enabled)
* nodebb-theme-harmony@1.0.65 (installed, enabled)
* nodebb-theme-lavender@7.1.1 (installed, disabled)
* nodebb-theme-peace@2.0.32 (installed, disabled)
* nodebb-theme-persona@13.1.8 (installed, disabled)
* nodebb-widget-essentials@7.0.13 (installed, enabled)

### Database type

MongoDB

### Database version

v6.0.4

### Exact steps to cause this issue

1. Create account `test` with email `test@domain.tld`
2. Verify email `test@domain.tld`
3. Create account `test2` with email `test2@domain.tld` (trying to use `test@domain.tld` throws "Email taken")
4. During the "We'd like some additional information in order to update your account..." step, set email to `test@domain.tld`
5. Verify email `test@domain.tld`

### What you expected

An error like "Email taken" to be thrown during step 4.

### What happened instead

The first account `test` got its email moved to `test2`, rendering `test` without one even though the "Require new users to specify an email address" setting is set.

**Comment by julianlam** [comment]
"email taken" allows for enumeration, which is not very good.

Email is not set, only when confirmed. So this is still secure.

**Comment by julianlam** [comment]
`test` will need to enter an email when they log in again.
