### ISSUE TITLE
ip blacklist only applies to a few routes

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11868]
From https://community.nodebb.org/post/95133

Only checked on 
```
/login
/register
/register/complete
/register/abort
```

So it doesn't have any effect until user logs out. 

Could be added to setupPageRoute so it applies to all routes?

**Comment by AliCihan** [comment]
yes, it would be better if it applies to all routes...

> So it doesn't have any effect until user logs out.

currently, when we have an attack, besides blacklisting IP address, we have to "revoke the login session" for the user.

**Comment by julianlam** [comment]
+1

I'm fine to have it added to `setupPageRoute`. We've been instructing plugin devs to use those helper methods for awhile now so not doing so is sort of "YMMV" territory.

**Comment by ShlomoCode** [comment]
> "YMMV" territory

What? 🤔

**Comment by julianlam** [comment]
Your mileage may vary. It's probably a North American term 😁

Just means you're on your own

**Comment by barisusakli** [comment]
What about admins? Should they be exempt? What if someone puts their own IP in 😆

**Comment by ShlomoCode** [comment]
> What if someone puts their own IP in 😆

As of today, once he logs out of the account, he will not be able to log in again

**Comment by barisusakli** [comment]
I think try to save the IP blacklist should warn the user if they entered their own IP
