### ISSUE TITLE
Bug in right-to-left

### ISSUE THREAD

**Issue by Mordechay0000** [NodeBB/NodeBB#11874]
### Description

Bug in right-to-left language support
written like this:
<img width="552" alt="image" src="https://github.com/NodeBB/NodeBB/assets/116315289/51d90b36-81f7-40b4-b6f3-fee14ac0a690">

It seems so:
<img width="692" alt="image" src="https://github.com/NodeBB/NodeBB/assets/116315289/beadbc7b-e836-4789-ab4f-6be0f955b611">

**Comment by barisusakli** [comment]
@Mordechay0000 is this happening in the composer preview area? Is the preview not rtl?

**Comment by barisusakli** [comment]
Not sure if there is a fix for this, but it happens due to mixing LTR/RTL on the same line, see below screenshot and some discussion here https://github.com/commonmark/commonmark-spec/issues/722

![image](https://github.com/NodeBB/NodeBB/assets/2583394/d0cdca45-4678-43b0-97dc-11237151da0a)

If your forum is never gonna mix RTL/LTR in post content then you can probably do 

```
.preview p { direction: rtl; }
```

**Comment by Mordechay0000** [comment]
My forum is mixed with English and Hebrew but it would be good for me if it always starts from right to left

**Comment by Mordechay0000** [comment]
I don't really understand web design, I tried to add to custom css what you sent and it doesn't help, I tried to change p dir to rtl and it fixed the problem, the question is how do you change it, what is custom css

**Comment by barisusakli** [comment]
In your nodebb's admin page there is a custom css tab at `/admin/appearance/customise` you can paste css there and save.

**Comment by Mordechay0000** [comment]
I did it, not working.

**Comment by barisusakli** [comment]
Did you enable it as well like below screenshot?

![image](https://github.com/NodeBB/NodeBB/assets/2583394/6afcbe81-de4c-4826-b57f-9071de098549)

**Comment by Mordechay0000** [comment]
I'm not that far... Of course I turned it on, it doesn't help.
<img width="1312" alt="image" src="https://github.com/NodeBB/NodeBB/assets/116315289/b4db0b81-2a3f-43fa-ad70-078033204187">
<img width="158" alt="image" src="https://github.com/NodeBB/NodeBB/assets/116315289/8001d69d-0f3d-4c05-b02c-f73661c1b394">

**Comment by barisusakli** [comment]
Seems to work for me, maybe check it in your browser's developer tools to see if the custom css is applied.

![image](https://github.com/NodeBB/NodeBB/assets/2583394/7541eb85-d3b9-4d9a-b7df-3a5061d198d5)

**Comment by Mordechay0000** [comment]
True, I didn't see it, but the post itself is not displayed from its date to the left
<img width="1245" alt="image" src="https://github.com/NodeBB/NodeBB/assets/116315289/b7e5ef04-f018-42d9-80f2-3bf4cfbe3970">
<img width="1243" alt="image" src="https://github.com/NodeBB/NodeBB/assets/116315289/f73e1ccf-2952-40c9-93cf-8028ad178f8b">

**Comment by barisusakli** [comment]
You probably need another css rule for the post content.
```
.preview p { direction: rtl; }
[component="post/content"] p { direction: rtl; }
```

**Comment by Mordechay0000** [comment]
Thank you!!! It works for me
