### ISSUE TITLE
Users created via API will not get email adresses

### ISSUE THREAD

**Issue by SebastianSander** [NodeBB/NodeBB#11872]
### NodeBB version

latest

### Exact steps to cause this issue

When creating Users via the API, they will not be assigned their email addresses. I fixed this by deleting the check on IsFirstUser in your User.create function line 106
```
if (data.email /*&& isFirstUser*/) {
	await User.setUserField(uid, 'email', data.email);
	await User.email.confirmByUid(userData.uid);
}
```
correct me if i'm wrong but i do not understand the necessity of only adding an email address to the first user which this line seems to be doing..

**Comment by julianlam** [comment]
Read this please https://community.nodebb.org/topic/16962/all-about-emails-and-how-they-re-used-in-nodebb

Emails are not saved until confirmed.
