### ISSUE TITLE
harmony: unable to reply to posts

### ISSUE THREAD

**Issue by diamante0018** [NodeBB/NodeBB#11885]
### NodeBB version

v3.2.3

### NodeBB git hash

b06d3e63cbdd0f00aed73dd8550221e5ee48ba2f

### NodeJS version

v18.16.0

### Installed NodeBB plugins

nodebb-plugin-2factor@7.1.3 (installed, enabled)
nodebb-plugin-composer-default@10.2.4 (installed, enabled)
nodebb-plugin-dbsearch@6.1.0 (installed, enabled)
nodebb-plugin-emoji@5.1.3 (installed, enabled)
nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
nodebb-plugin-markdown@12.1.4 (installed, enabled)
nodebb-plugin-mentions@4.2.0 (installed, enabled)
nodebb-plugin-ntfy@1.0.15 (installed, disabled)
nodebb-plugin-quickstart@0.3.1 (installed, disabled)
nodebb-plugin-spam-be-gone@2.1.1 (installed, disabled)
nodebb-rewards-essentials@0.2.3 (installed, enabled)
nodebb-theme-harmony@1.0.65 (installed, enabled)
nodebb-theme-lavender@7.1.1 (installed, disabled)
nodebb-theme-peace@2.0.32 (installed, disabled)
nodebb-theme-persona@13.1.8 (installed, disabled)
nodebb-widget-essentials@7.0.13 (installed, enabled)

### Database type

MongoDB

### Database version

v6.0.4

### Exact steps to cause this issue

- Open a post from mobile using the chrome browser (latest version, stable)
- Unable to click the quick reply button because it's hidden or completely covered by other elements 

### What you expected

I expect the quick reply button to be the element that is always readily accessible 

### What happened instead

The button cannot be interacted with.
When switching to desktop view from mobile chromium clicking the button causes a generic error.
Not only is the quick reply button hidden, but when someone manages to click it forcefully it appears completely unusable.

### Anything else?

![Screenshot_20230808_112533_Chrome](https://github.com/NodeBB/NodeBB/assets/37080671/a3295334-4f2f-4afd-b943-4c791919ac74)
This screenshot shows the quick reply button hidden by another element on the foreground
It cannot be tapped at all, unusable.

![Screenshot_20230808_113948_Chrome](https://github.com/NodeBB/NodeBB/assets/37080671/cd26d0f8-60ab-4d3e-afaa-558406897b03)
This screenshot shows the button is unusable when switching to desktop view even though the elements that cover it are finally gone.

**Comment by barisusakli** [comment]
@diamante0018 I can't reproduce the "Error error" clicking quick reply when the text area is empty results in an error message.

![image](https://github.com/NodeBB/NodeBB/assets/2583394/6952a3c6-094c-42a2-b607-6233dab3254e)

Can you reproduce at https://community.nodebb.org/?

**Comment by diamante0018** [comment]
Unable to reproduce on your main website. 
I can confirm my main complaint was fixed.
Thanks y'all.
