### ISSUE TITLE
Potential SSO information leakage in API

### ISSUE THREAD

**Issue by 3ldor** [NodeBB/NodeBB#11906]
### NodeBB version

v3.2.3

### NodeBB git hash

b06d3e63cbdd0f00aed73dd8550221e5ee48ba2f

### NodeJS version

v18.16.0

### Installed NodeBB plugins

* nodebb-plugin-2factor@7.1.3 (installed, enabled)
* nodebb-plugin-composer-default@10.2.4 (installed, enabled)
* nodebb-plugin-dbsearch@6.1.0 (installed, enabled)
* nodebb-plugin-emoji@5.1.3 (installed, enabled)
* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
* nodebb-plugin-markdown@12.1.4 (installed, enabled)
* nodebb-plugin-mentions@4.2.0 (installed, enabled)
* nodebb-plugin-ntfy@1.0.15 (installed, disabled)
* nodebb-plugin-quickstart@0.3.1 (installed, disabled)
* nodebb-plugin-spam-be-gone@2.1.1 (installed, disabled)
* nodebb-rewards-essentials@0.2.3 (installed, enabled)
* nodebb-theme-harmony@1.0.65 (installed, enabled)
* nodebb-theme-lavender@7.1.1 (installed, disabled)
* nodebb-theme-peace@2.0.32 (installed, disabled)
* nodebb-theme-persona@13.1.8 (installed, disabled)
* nodebb-widget-essentials@7.0.13 (installed, enabled)

### Database type

MongoDB

### Database version

v6.0.4

### Exact steps to cause this issue

1. Use plugin that adds information via the `filter:auth.list` hook (eg. `nodebb-plugin-sso-facebook` or `nodebb-plugin-sso-google`)
2. Fetch `/api/user/<user with linked sso>`

### What you expected

The `sso` field not to be present for unauthorized users, and certainly not unauthenticated users!

### What happened instead

The full data populated from the hook is shown, including the `url` which contains the linked user id.

### Anything else?

It'd probably be beneficial for administrators (and anyone else who can access "Edit Profile" for another user) to still be able to get the information.

**Comment by julianlam** [comment]
Thanks! It should be ok to leak the remote id (although not intentionally) so there's no vulnerability here I can see for now. 

Will get this patched up.

**Comment by julianlam** [comment]
After reviewing the implementation and several examples of listeners for said hook, I have come to the conclusion that showing the sso data is expected.

We use this data only in the `/me/edit` page, to show the existing services available, and to present the user with association/deauth links if available.

Other themes may want to use this data to show what social media services users have associated with.

The remote ID is not considered a sensitive piece of PII, much like a uid in NodeBB. While I cannot say this for all SSO providers, **this is a common practice**, and does require that the SSO plugin itself explicitly send this data back through the hook.

There is one bug, however, in that serving the `deauthUrl` when associated and `url` when not associated makes no sense unless the caller uid is the target uid. I'll get that fixed.

**Comment by julianlam** [comment]
* nodebb/nodebb-theme-persona@8d21fe83
* nodebb/nodebb-theme-persona@76cf30c4
* nodebb/nodebb-theme-harmony@93dcd55

**Comment by 3ldor** [comment]
A use-case that this commit https://github.com/NodeBB/NodeBB/commit/19e047e2d3929ba41e854d2f775493f59c4cbceb fails to take into account now, is privileged users dissociating other users, which was possible previously with crafted deauth urls.

**Comment by julianlam** [comment]
> Even though the id itself may not contain PII, such data could likely be extracted using it. 

Sorry, if a site let you extract sensitive user data using nothing but an id then there are more serious security implications already present. 

Re: deauth, I may be mistaken but using the deauth URL only deauthorizes your own account, not somebody else's

**Comment by julianlam** [comment]
Different sites may want to hide SSO connections, I get that.

I'll add a toggle

**Comment by 3ldor** [comment]
> Re: deauth, I may be mistaken but using the deauth URL only deauthorizes your own account, not somebody else's

This depends on the implementation. In plugins I wrote I made it possible for administrators to deauth other users by passing the id in the deauth url. I think this is useful to retain.

**Comment by GravzyIT** [comment]
Agreed - I have my own plugin to allow admins to deauth other users as it's useful for user support, would be great if the functionality could be kept.

**Comment by julianlam** [comment]
After your replies, I went back and looked again, and what I originally dismissed as sloppy was actually intentional. I had used verbiage that explicitly implied that the SSO block was meant to be viewed by the calling user only, and only for their account.

Considering the above and that the only place it is used is in the edit page, I have updated both master and develop so that the SSO block is only shown on the calling user's `/edit` page, or to admins.

Let me know if that works for you.

**Comment by julianlam** [comment]
Nope, fix was no good, stand by...

**Comment by julianlam** [comment]
df65c60081e515f23c5e8e470559b3e2d6198b57

**Comment by 3ldor** [comment]
Yep, this works. Thanks!
