### ISSUE TITLE
I hava a suggestion that make `loggedInUser` return null when the `loggedIn` is false in read api(get recent topics)

### ISSUE THREAD

**Issue by allinprogram** [NodeBB/NodeBB#11901]
### Description

I hava a suggestion that make `loggedInUser` return null when the `loggedIn` is false in read api(get recent topics).

It is hard to serialize the `loggedInUser` Object in some scense.

**Comment by barisusakli** [comment]
We use the loggedInUser object to display the avatar on quick reply box if guests are allowed to post so we need it to contain the guest info as well. Name is a bit confusing maybe it should have been called `currentUser` but it would be breaking change to rename that.

**Comment by allinprogram** [comment]
Yes, I have done a lot of tests on the api and saw the scenario you mentioned. Making changes will be a destructive behavior, making it impractical for a short time, so I will take the initiative to close this Issue.

I put forward this issue because I am considering using the null-safe architecture and api for development. For the current API design, many models will be nullable.

It makes it difficult to adhere to the principle of null-safe, and when serializing objects, the model structure depends on other fields of the same response.

Thank you for your reply.
