### ISSUE TITLE
Post moderation menu opens outside the visible area.

### ISSUE THREAD

**Issue by Jane-N** [NodeBB/NodeBB#11937]
### NodeBB version

v3.2.3

### Exact steps to cause this issue

1. Open a topic with multiple posts.
2. Click on the ⋮ menu on a post in the thread that's near the bottom of the screen.

### What you expected

The menu is fully visible on the screen.

### What happened instead

First, the menu opens half outside the visible area. You need to either scroll the page a bit or close the menu and reopen it, for the menu to appear correctly.

**Comment by julianlam** [comment]
If the handler works on second invocation, then that suggests that the `dropup` class got added too late :thinking:
