### ISSUE TITLE
Skins tab never finishes loading in nodeBB v3.3.0+

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#11945]
### NodeBB version

v3.3.6

### NodeBB git hash

7fb387926e5e7ef8e001fcdae19a6e2c7d2f953e

### NodeJS version

v20.5.1

### Installed NodeBB plugins

Active plugins:
	* nodebb-plugin-2factor@7.2.1 (installed, disabled)
	* nodebb-plugin-composer-default@10.2.13 (installed, enabled)
	* nodebb-plugin-dbsearch@6.2.0 (installed, enabled)
	* nodebb-plugin-emoji@5.1.5 (installed, enabled)
	* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
	* nodebb-plugin-imgur@4.1.0 (installed, enabled)
	* nodebb-plugin-markdown@12.1.7 (installed, enabled)
	* nodebb-plugin-mentions@4.3.4 (installed, enabled)
	* nodebb-plugin-ntfy@1.4.0 (installed, disabled)
	* nodebb-plugin-soundpack-default@2.0.1 (installed, disabled)
	* nodebb-plugin-spam-be-gone@2.1.1 (installed, disabled)
	* nodebb-rewards-essentials@0.2.3 (installed, enabled)
	* nodebb-theme-harmony@1.1.41 (installed, disabled)
	* nodebb-theme-harmony-sweetp@1.0.0 (installed, enabled)
	* nodebb-theme-lavender@7.1.3 (installed, disabled)
	* nodebb-theme-peace@2.1.12 (installed, disabled)
	* nodebb-theme-persona@13.2.19 (installed, disabled)
	* nodebb-theme-slick@2.0.2 (installed, disabled)
	* nodebb-theme-vanilla@12.1.19 (installed, disabled)
	* nodebb-widget-essentials@7.0.13 (installed, enabled)

### Database type

PostgreSQL

### Database version

v15.4

### Exact steps to cause this issue

open admin
open Appearance > Skins

### What you expected

Skins tab should load

### What happened instead

Loading Skins... and the loading animation never end

### Anything else?

this began happening after the update to NodeBB v3.3.0

**Comment by barisusakli** [comment]
@sweetppro you can create a custom skin in the custom skins tab then the skins should load, will release 3.3.7 tomorrow
