### ISSUE TITLE
Login sessions list broken for users with 2FA

### ISSUE THREAD

**Issue by 3ldor** [NodeBB/NodeBB#11946]
### NodeBB version

v3.3.6

### NodeBB git hash

7fb387926e5e7ef8e001fcdae19a6e2c7d2f953e

### NodeJS version

v18.16.0

### Installed NodeBB plugins

* nodebb-plugin-2factor@7.2.1 (installed, enabled)
* nodebb-plugin-composer-default@10.2.13 (installed, enabled)
* nodebb-plugin-dbsearch@6.2.0 (installed, enabled)
* nodebb-plugin-emoji@5.1.5 (installed, enabled)
* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
* nodebb-plugin-markdown@12.1.7 (installed, enabled)
* nodebb-plugin-mentions@4.3.4 (installed, enabled)
* nodebb-plugin-ntfy@1.4.0 (installed, disabled)
* nodebb-plugin-quickstart@0.3.1 (installed, disabled)
* nodebb-plugin-spam-be-gone@2.1.1 (installed, disabled)
* nodebb-rewards-essentials@0.2.3 (installed, enabled)
* nodebb-theme-harmony@1.1.41 (installed, enabled)
* nodebb-theme-lavender@7.1.3 (installed, disabled)
* nodebb-theme-peace@2.1.12 (installed, disabled)
* nodebb-theme-persona@13.2.19 (installed, disabled)
* nodebb-widget-essentials@7.0.13 (installed, enabled)

### Database type

MongoDB

### Database version

v6.0.4

### Exact steps to cause this issue

1. Have account with 2FA enabled.
2. Login like normal, wait at 2FA prompt and check "Account Info" with admin account (session is listed).
3. Finish 2FA prompt.

### What you expected

I expected the session to remain visible once fully logged in.

### What happened instead

The session isn't shown anywhere (not even for user in "Login Sessions").

### Anything else?

Unsure if this is a bug with NodeBB itself or the 2factor plugin.

**Comment by julianlam** [comment]
> 2. Login like normal, wait at 2FA prompt and check "Account Info" with admin account (session is listed).
> 3. Finish 2FA prompt.

Admin needs to check login sessions before 2FA is complete?

**Comment by 3ldor** [comment]
> > 2. Login like normal, wait at 2FA prompt and check "Account Info" with admin account (session is listed).
> > 3. Finish 2FA prompt.
> 
> Admin needs to check login sessions before 2FA is complete?

The issue appears _after_ 2FA is complete, it only "works" during the challenge, which is what I was trying to describe to potentially make debugging easier.

**Comment by julianlam** [comment]
Hah, that's wild. Just repro'd. It also answers the question of why exactly I have 0 sessions listed on community.nodebb.org :thinking:

**Comment by julianlam** [comment]
This looks to be related to TOTP logins only. Using backup code and Authn strategies do not exhibit this issue.

This points to session-rolling logic added by default in newer versions of PassportJS.

**Comment by julianlam** [comment]
Blocked by #11996

**Comment by julianlam** [comment]
6bc2b6c5ae1249309abbe52acffcee83e9380f5e
