### ISSUE TITLE
Uncaught (in promise) SyntaxError: JSON.parse during the user register

### ISSUE THREAD

**Issue by LingkongSky** [NodeBB/NodeBB#11960]
### NodeBB version

v3.3.9

### NodeBB git hash

f455c959b2d4cac4046b4945bfed335ee3d97300

### NodeJS version

v20.5.1

### Installed NodeBB plugins

     * @nodebb/nodebb-plugin-reactions@2.1.9 (installed, disabled)
        * @nodebb/nodebb-plugin-registration-question@1.1.0 (installed, disabled)
        * @nodebb/nodebb-plugin-reputation-rules@2.0.0 (installed, disabled)
        * @nodebb/nodebb-plugin-user-level@2.1.1 (installed, disabled)
        * nodebb-plugin-beep@0.4.8 (installed, disabled)
        * nodebb-plugin-composer-default@10.2.13 (installed, enabled)
        * nodebb-plugin-dbsearch-rsjieba@0.2.0 (installed, disabled)
        * nodebb-plugin-emoji@5.1.5 (installed, disabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, disabled)
        * nodebb-plugin-emoji-apple@4.0.0 (installed, disabled)
        * nodebb-plugin-extended-markdown@2.0.1 (installed, disabled)
        * nodebb-plugin-feed@3.0.7 (installed, disabled)
        * nodebb-plugin-markdown@12.1.7 (installed, disabled)
        * nodebb-plugin-mentions@4.3.5 (installed, disabled)
        * nodebb-plugin-ntfy@1.4.0 (installed, disabled)
        * nodebb-plugin-question-and-answer@1.1.0 (installed, disabled)
        * nodebb-plugin-spam-be-gone@2.1.1 (installed, disabled)
        * nodebb-plugin-two-way-block@1.5.2 (installed, disabled)
        * nodebb-rewards-essentials@0.2.3 (installed, disabled)
        * nodebb-theme-aurinkomaa@1.1.7 (installed, disabled)
        * nodebb-theme-harmony@1.1.41 (installed, disabled)
        * nodebb-theme-lavender@7.1.3 (installed, disabled)
        * nodebb-theme-persona@13.2.19 (installed, disabled)
        * nodebb-theme-vanilla@12.1.19 (installed, disabled)
        * nodebb-theme-vtubeando@2.0.2 (installed, enabled)
        * nodebb-widget-essentials@7.0.13 (installed, disabled)

### Database type

MongoDB, Redis

### Database version

5.0.19

### Exact steps to cause this issue

For unknown reason,when I try to register a new user to test,the error was happend.

When I try to take the focus away from the username or hit the register button,the console echo "Uncaught (in promise) SyntaxError: JSON.parse

And after that,I locate the problem code is form /public/src/modules/api.js
The value of isJSON is the problem,and when i change its value to False,then i can register success.
![LNJL`I(2}@P7AUCX7M }B{X](https://github.com/NodeBB/NodeBB/assets/61834524/dccc991e-6fc9-4f2d-9ee4-b576cc5b1094)

### What you expected

register successful

### What happened instead

Uncaught (in promise) SyntaxError: JSON.parse

**Comment by barisusakli** [comment]
Can you post the details of xhr request that happens when you take away the focus from the username input. THere should be two requests that check if the username is already taken.

They look like 
```
http://127.0.0.1:4567/api/v3/users/bySlug/<value_entered>
http://127.0.0.1:4567/api/v3/groups/<value_entered>
```

Check the value of `Content-Type` in response headers for these two requests.

**Comment by LingkongSky** [comment]
![屏幕截图 2023-08-29 090611](https://github.com/NodeBB/NodeBB/assets/61834524/51631746-7fc6-48b0-9a88-3874c36b90bd)
![图片](https://github.com/NodeBB/NodeBB/assets/61834524/54c2527a-770b-441e-9b6f-1ededccb30f8)

**Comment by barisusakli** [comment]
Yeah seems like an issue with `content-type` when I try it on https://community.nodebb.org I get text/plain

![image](https://github.com/NodeBB/NodeBB/assets/2583394/7aabadc6-dbad-48b0-b6b5-3f25da01f5e0)

**Comment by barisusakli** [comment]
@LingkongSky let me know if the above commit fixes your issue

**Comment by LingkongSky** [comment]
The error has been fixed,Thanks.
