### ISSUE TITLE
admin changing another users email uses same template as new user signup

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11971]
If admin is changing someone elses email it should not use the same template and it shouldn't force every page to redirect to register/complete.

Might make sense to completely remove edit email(for admins) from front end and only do it in the ACP side with a simple modal/input

![image](https://github.com/NodeBB/NodeBB/assets/2583394/da175e73-192e-4371-b0e1-90d3cd22a4c5)

from https://community.nodebb.org/topic/17521/unable-to-change-another-user-s-email-via-acp

**Comment by julianlam** [comment]
I'm ok with this, it would simplify the interstitial logic as well.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/11973
