### ISSUE TITLE
 The format of the interface(`/api/notifications`) return field `tid` is uncertain.

### ISSUE THREAD

**Issue by allinprogram** [NodeBB/NodeBB#12007]
### NodeBB version

v3.4.2

### NodeJS version

v20

### Database type

MongoDB

### Database version

v7.0.1

### Exact steps to cause this issue

1. Log in to an ordinary account and call the interface. The tid format is a `string`;
2. Log in to the administrator account and call the interface. The tid format is `int`.

### What you expected

All the tid format is `int`, just like read api doc described.

**Comment by barisusakli** [comment]
@allinprogram can you share the type/nid fields of the notification that has a string tid?

**Comment by allinprogram** [comment]
admin user get api return:
![image](https://github.com/NodeBB/NodeBB/assets/29867703/3e4e6dff-6577-477c-97d0-eeb76079f88a)

ordinary user get api return:
![image](https://github.com/NodeBB/NodeBB/assets/29867703/cf788a95-54c9-4ddb-bdcb-d53a1ffa80c8)

**Comment by Jaya-sys** [comment]
would like to work on this issue?

**Comment by julianlam** [comment]
@Jaya-sys don't ask, just open a PR to fix

**Comment by allinprogram** [comment]
Sorry, thank you for your contribution, and I also hope to contribute my own strength, but my js ability is very weak, and I need to work more than 14 hours a day.

If there are projects such as rust, java, dart or C, I am very willing to contribute.
