### ISSUE TITLE
Heder title touching the upside

### ISSUE THREAD

**Issue by chaursiyasanjeet** [NodeBB/NodeBB#12061]
Hey I want to enhance the header title css so it not touch upside of the browser.
<img width="958" alt="image" src="https://github.com/NodeBB/NodeBB/assets/111435565/54e80451-a078-492b-97d2-cd56059e2c88">

please assign this issue

**Comment by julianlam** [comment]
This is not the correct repo for that site.

**Comment by oplik0** [comment]
Tbf there just isn't a correct (public) repo for that site :)
(as far as I'm aware at least)
