### ISSUE TITLE
Translation not working for dont-have-account in Harmony theme

### ISSUE THREAD

**Issue by saikarthikp9** [NodeBB/NodeBB#12095]
### NodeBB version

v3.4.3

### NodeJS version

18.18.0

### Installed NodeBB plugins

        * @nodebb/nodebb-plugin-registration-question@1.1.0 (installed, enabled)
        * nodebb-plugin-2factor@7.3.0 (installed, disabled)
        * nodebb-plugin-composer-default@10.2.20 (installed, enabled)
        * nodebb-plugin-dbsearch@6.2.2 (installed, enabled)
        * nodebb-plugin-emoji@5.1.5 (installed, enabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
        * nodebb-plugin-markdown@12.2.3 (installed, enabled)
        * nodebb-plugin-mentions@4.3.5 (installed, enabled)
        * nodebb-plugin-ntfy@1.6.1 (installed, disabled)
        * nodebb-plugin-question-and-answer@1.2.4 (installed, enabled)
        * nodebb-plugin-spam-be-gone@2.1.1 (installed, disabled)
        * nodebb-rewards-essentials@0.2.3 (installed, enabled)
        * nodebb-theme-harmony@1.1.85 (installed, disabled)
        * nodebb-theme-harmony-test@1.1.88 (installed, enabled)
        * nodebb-theme-lavender@7.1.3 (installed, disabled)
        * nodebb-theme-peace@2.1.18 (installed, disabled)
        * nodebb-theme-persona@13.2.29 (installed, disabled)
        * nodebb-widget-essentials@7.0.13 (installed, enabled)

### Database type

MongoDB

### What you expected

dont-have-account should be translated. The translation exists.

I am using the harmony theme.

### What happened instead

dont-have-account did not get translated.

<img width="195" alt="Screenshot 2023-10-17 at 9 06 58 PM" src="https://github.com/NodeBB/NodeBB/assets/69390532/64da5cd0-8087-456a-b4f1-97162cc2f149">

**Comment by barisusakli** [comment]
What language are you using?

**Comment by saikarthikp9** [comment]
en-GB

**Comment by barisusakli** [comment]
If you are on nodebb 3.4.3 you should be using harmony  "nodebb-theme-harmony": "1.1.60",
1.1.85 is for the upcoming nodebb 3.5.0
