### ISSUE TITLE
pinned until timestamp doesnt need the hh:mm:ss

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#12123]
Pinning a topic lets you select a expiry date, the expiry doesn't let you select hour/minutes but the label shows hh:mm:ss

Either should let selecting hh:mm or remove the hh:mm:ss

![image](https://github.com/NodeBB/NodeBB/assets/2583394/3b78aa0d-31ef-43dd-850d-7c6132896a4e)

**Comment by julianlam** [comment]
ToLocaleDateString should work?
