### ISSUE TITLE
Public chat mention notifications not showing correctly

### ISSUE THREAD

**Issue by david-1904** [NodeBB/NodeBB#12124]
### NodeBB version

v3.5.0

### Database type

MongoDB

### Exact steps to cause this issue

I felt bad that @barisusakli always created issues for my reports so here is my first own issue. :D

It seems that on NodeBB v3.5.0 notfication messages for mentions in public chat rooms are not displayed correctly.

![2023-10-25 20_51_46-3 5 0 Upgrade Support _ NodeBB Community – Mozilla Firefox](https://github.com/NodeBB/NodeBB/assets/121203536/c90a2a7d-1018-47d7-9f62-f9d83c43d85d)

**Comment by david-1904** [comment]
issue in wrong repo and already fixed

**Comment by barisusakli** [comment]
👍🏼
