### ISSUE TITLE
Topic timestamp should go to latest post

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12146]
![image](https://github.com/NodeBB/NodeBB/assets/923011/381d0d25-8b7a-4332-a69f-30cb87434dc7)

**Comment by julianlam** [comment]
Seems this is wrong on desktop too

**Comment by barisusakli** [comment]
Actually on desktop it shows the topic creation timestamp so should go to first post on desktop at least.

**Comment by julianlam** [comment]
Ah good catch

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-harmony/commit/04930d09c2f44bd0dfe5f7a546569124c7ec5d63 👍🏼
