### ISSUE TITLE
Adding a new group to privilege table does not render checkboxes

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12156]
When a group is added via the "Add Group" modal, the row is added, but the generated row is missing the cells with checkboxes.

Related topic: https://community.nodebb.org/topic/17648/new-install-can-t-assign-group-privileges

**Comment by julianlam** [comment]
Thanks @barisusakli :smile:

**Comment by yasz** [comment]
see it again when i upgrade 3.8 to 4.4.6

<img width="1361" height="646" alt="Image" src="https://github.com/user-attachments/assets/973855b8-f0b3-43c5-948a-516afd23c29c" />

**Comment by barisusakli** [comment]
Doesn't happen for me on 4.4.6, make sure you run `./nodebb build` and clear browser cache.
