### ISSUE TITLE
Add Exception Group List to New User Restrictions

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#12154]
### Description

Would it be possible to add a group list to the New User Restrictions section so selected groups don't have the restrictions applied to them?

We have a group that aren't mods or admins but do post topics related to our product (lets call them editors) that need to be able to post and edit without restrictions which is not the case when a new editor joins the team. We don't really want to lower the forum wide thresholds for a select few users if possible.

**Comment by barisusakli** [comment]
Makes sense, we have a setting for the post queue so we can add the same for new user restrictions.

![image](https://github.com/NodeBB/NodeBB/assets/2583394/0aedd8b2-fde5-40ed-936b-9822697a6d5d)
