### ISSUE TITLE
S3 Upload plugin bypass extensions restriction policy (allowedMimeTypes)

### ISSUE THREAD

**Issue by tchesley85** [NodeBB/NodeBB#12179]
### NodeBB version

v3.5.0

### NodeBB git hash

b17ee0f09e8e0e4ccd7bb3bd7c25c64df64af702

### NodeJS version

v20.9.0

### Installed NodeBB plugins

* @nodebb/nodebb-plugin-s3-uploads@3.0.2 (installed, enabled)
* nodebb-plugin-2factor@7.4.0 (installed, disabled)
* nodebb-plugin-composer-default@10.2.24 (installed, enabled)
* nodebb-plugin-dbsearch@6.2.2 (installed, enabled)
* nodebb-plugin-emoji@5.1.13 (installed, enabled)
* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
* nodebb-plugin-markdown@12.2.5 (installed, enabled)
* nodebb-plugin-mentions@4.3.6 (installed, enabled)
* nodebb-plugin-ntfy@1.7.3 (installed, disabled)
* nodebb-plugin-spam-be-gone@2.2.0 (installed, disabled)
* nodebb-plugin-sso-oauth2-multiple@1.3.9 (installed, enabled)
* nodebb-rewards-essentials@1.0.0 (installed, enabled)
* nodebb-theme-harmony@1.1.90 (installed, enabled)
* nodebb-theme-lavender@7.1.5 (installed, disabled)
* nodebb-theme-peace@2.1.23 (installed, disabled)
* nodebb-theme-persona@13.2.42 (installed, disabled)
* nodebb-widget-essentials@7.0.14 (installed, enabled)

### Database type

PostgreSQL

### Database version

13.13

### Exact steps to cause this issue

I'm working to run NodeBB in an EKS Environment and use S3 as the main storage for all uploaded data.
1 . Firstly I did install the @nodebb/nodebb-plugin-s3-uploads@3.0.2
2 . The plugin side was properly configured using environment variables
3 . I was able to upload/store all my uploaded content to the S3 Bucket
4 . But for some reason the restriction by extensions under Settings > Uploads > Allowed File Extensions is not being applied.

To reproduce the issue I disabled the S3 Upload plugin and tried to upload an empty Yaml file using the default Allowed extension types, see the image below: 

<img width="777" alt="image" src="https://github.com/NodeBB/NodeBB/assets/87079806/108a055b-07e2-434a-9d08-f7feb0271ccc">

Now I have re-activated the plugin and performed the Rebuild and Restart to apply my settings and no Error is presented as per the image below:

<img width="1634" alt="image" src="https://github.com/NodeBB/NodeBB/assets/87079806/cd280f45-1d58-4433-ba8c-dcf1fedcd5b7">

### What you expected

I expected to get the same Error below when uploading files using S3 plugin:

<img width="777" alt="image" src="https://github.com/NodeBB/NodeBB/assets/87079806/108a055b-07e2-434a-9d08-f7feb0271ccc">

### What happened instead

Instead, not allowed file extensions are being uploaded to the S3 bucket:

**Comment by barisusakli** [comment]
Give @nodebb/nodebb-plugin-s3-uploads@3.0.3 a try, looks like mime types were hardcoded into the s3 plugin, I switched it to use the setting from ACP.

**Comment by tchesley85** [comment]
> Give @nodebb/nodebb-plugin-s3-uploads@3.0.3 a try, looks like mime types were hardcoded into the s3 plugin, I switched it to use the setting from ACP.

Hi @barisusakli, I did the update and the rebuild/restart but it is still presenting the issue. Just double-checked inside the server to ensure that I'm using the version  @nodebb/nodebb-plugin-s3-uploads@3.0.3 as you can see here: 

<img width="956" alt="image" src="https://github.com/NodeBB/NodeBB/assets/87079806/cafbf95f-a538-4b56-b3e8-3ced3f58e900">

Any thoughts?

**Comment by barisusakli** [comment]
Can you debug with a console.log before this line https://github.com/NodeBB-Community/nodebb-plugin-s3-uploads/blob/master/index.js#L240 and see what the values of `allowed` and `image.path` are?

**Comment by tchesley85** [comment]
> Can you debug with a console.log before this line https://github.com/NodeBB-Community/nodebb-plugin-s3-uploads/blob/master/index.js#L240 and see what the values of `allowed` and `image.path` are?

@barisusakli, I did the tests here, but I'm not getting when the Allowed Extensions is being checked, look: 

``` 2023-11-22T14:19:30.268Z [4567/15290] - verbose: [plugins/fireHook] filter:uploadFile
Start UploadFile
{
  fieldName: 'files[]',
  originalFilename: 'test.yaml.zip',
  path: '/var/folders/4f/pq1vhxwd43v1s0yw0bz62q3r0000gn/T/sF55L_t4rNK_o73QSzeR172h.zip',
  headers: {
    'content-disposition': 'form-data; name="files[]"; filename="test.yaml.zip"',
    'content-type': 'application/zip'
  },
  size: 191,
  name: 'test.yaml.zip',
  type: 'application/zip'
}
checking file vs. settings
begin of readFile
/var/folders/4f/pq1vhxwd43v1s0yw0bz62q3r0000gn/T/sF55L_t4rNK_o73QSzeR172h.zip
End of plugin UploadFile
Start UploadToS3
putObject
putObject before callback
application/zip
```

The function recognizes the extension as expected but there are no restrictions. In another hand, when I get to the UploadImage function I get the following output: 

```
Starting plugin UploadImage
{
  fieldName: 'files[]',
  originalFilename: 'ja9.jpg',
  path: '/var/folders/4f/pq1vhxwd43v1s0yw0bz62q3r0000gn/T/mph7X9JbxI_YyDv5gSz3w9sU.jpg',
  headers: {
    'content-disposition': 'form-data; name="files[]"; filename="ja9.jpg"',
    'content-type': 'image/jpeg'
  },
  size: 217261,
  name: 'ja9.jpg',
  type: 'image/jpeg'
}
TESTS
file
IF type === file
{
  saveFileToLocal: [AsyncFunction: wrapperCallback],
  base64ToLocal: [AsyncFunction: wrapperCallback],
  appendToFileName: [Function (anonymous)],
  allowedExtensions: [Function (anonymous)],
  exists: [AsyncFunction: wrapperCallback],
  existsSync: [Function (anonymous)],
  delete: [AsyncFunction: wrapperCallback],
  link: [AsyncFunction: wrapperCallback],
  linkDirs: [AsyncFunction: wrapperCallback],
  typeToExtension: [Function (anonymous)],
  walk: [AsyncFunction: wrapperCallback]
}

[ '.png', '.jpg', '.bmp', '.txt', '.jpeg' ]

[ '.png', '.jpg', '.bmp', '.txt', '.jpeg' ]
End of plugin UploadImage
Start UploadToS3
putObject
putObject before callback
image/jpeg
```
I now wondering if should we have the same validation [here](https://github.com/NodeBB-Community/nodebb-plugin-s3-uploads/blob/498228ced87fb24a4e1abc7db435402d62e1fade/index.js#L294) as we have in this [line](https://github.com/NodeBB-Community/nodebb-plugin-s3-uploads/blob/master/index.js#L233), or even a new one to check the Files Uploaded before calling the putObject function.

Thanks is advance by your time and patience.

**Comment by barisusakli** [comment]
@tchesley85 I added the same type check into uploadFile() please try with 3.0.4.  https://github.com/NodeBB-Community/nodebb-plugin-s3-uploads/commit/10da950e2eb2714760f8e77c532ec2102c78000c

**Comment by tchesley85** [comment]
Worked like a charm! Thank you 🙏 
<img width="1396" alt="image" src="https://github.com/NodeBB/NodeBB/assets/87079806/06de7878-ddb4-4220-8bd1-e3e96d7f85b7">
