### ISSUE TITLE
NodeBB configured subfolder in URL is not used for all assets

### ISSUE THREAD

**Issue by arkabase** [NodeBB/NodeBB#12184]
### NodeBB version

v3.5.1

### NodeBB git hash

4c543488719cbe6d8716a7dff5af9100945deb6c

### NodeJS version

v20.9.0

### Installed NodeBB plugins

        * nodebb-plugin-2factor@7.4.0 (installed, disabled)
        * nodebb-plugin-composer-default@10.2.24 (installed, enabled)
        * nodebb-plugin-dbsearch@6.2.2 (installed, disabled)
        * nodebb-plugin-emoji@5.1.13 (installed, enabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
        * nodebb-plugin-markdown@12.2.5 (installed, enabled)
        * nodebb-plugin-mentions@4.3.7 (installed, enabled)
        * nodebb-plugin-ntfy@1.7.3 (installed, disabled)
        * nodebb-plugin-spam-be-gone@2.2.0 (installed, disabled)
        * nodebb-rewards-essentials@1.0.0 (installed, enabled)
        * nodebb-theme-harmony@1.1.91 (installed, enabled)
        * nodebb-theme-lavender@7.1.5 (installed, disabled)
        * nodebb-theme-peace@2.1.23 (installed, disabled)
        * nodebb-theme-persona@13.2.42 (installed, disabled)
        * nodebb-widget-essentials@7.0.14 (installed, enabled)

### Database type

MongoDB

### Database version

v7.0.3

### Exact steps to cause this issue

1. Install NodeBB as in the documentation
2. Change url in config.json to https://domain.tld/forum
3. Create a systemd service to start NodeBB on reboot
4. Start NodeBB service

### What you expected

All the queries  to NodeBB pages and assets use the configured URL with the subfolder

### What happened instead

The main page, the websocket and most assets are well served under the subfolder, but some assets are queried without the subfolder and return 502 errors from the NginX proxy : 

https://domain.tld/assets/49375.298045c2ed6dfe315442.min.js
https://domain.tld/assets/modules/navigator.10fbc30a1a73c5cdb4c0.min.js
https://domain.tld/assets/modules/composer-drafts.f38a37326391a2a7d23d.min.js
https://domain.tld/assets/timeago/jquery-timeago-fr.8d4de2b6a98ffb1240fe.min.js
... (+ other built js files)

**Comment by barisusakli** [comment]
After changing the url in config.json did you rebuild the assets with `./nodebb build`? The webpack config looks at the relative path from config.json  https://github.com/NodeBB/NodeBB/blob/master/webpack.common.js#L29

**Comment by arkabase** [comment]
> After changing the url in config.json did you rebuild the assets with `./nodebb build`? The webpack config looks at the relative path from config.json https://github.com/NodeBB/NodeBB/blob/master/webpack.common.js#L29

Okay, I missed this one. Is it in the documentation ?
Worked like a charm, thank you so much !

**Comment by barisusakli** [comment]
@arkabase added some info into docs https://github.com/NodeBB/docs/commit/4cfc767fd9e7bcb4863292f6cee803d370018387
