### ISSUE TITLE
invalid csrf token

### ISSUE THREAD

**Issue by bukaixyz** [NodeBB/NodeBB#12205]
### NodeBB version

v3.5.2

### NodeBB git hash

17c19c701d8a4959c02091dc50d445bf1982418

### NodeJS version

v20.9.0

### Installed NodeBB plugins

Active plugins:
* nodebb-plugin-2factor@7.4.0 (installed, disabled)
* nodebb-plugin-composer-default@10.2.27 (installed, enabled)
* nodebb-plugin-dbsearch06.2.2 (installed, disabled)
* nodebb-plugin-emoji@5.1.13 (installed, enabled)
* nodebb-plugin-emoji-android 4.0.0 (installed, enabled) nodebb-plugin-markdown@12.2.5 (installed, enabled)
* nodebb-plugin-mentions@4.3.7 (installed, enabled)
* nodebb-plugin-ntfy@1.7.3 (installed, disabled)
* nodebb-plugin-spam-be-gone@2.2.0 (installed, disabled)
* nodebb-rewards-essentials@1.0.0 (installed, enabled)
*
nodebb-theme-harmony@1.1.91 (installed, enabled)
* nodebb-theme-lavender@7.1.5 (installed, disabled)
* nodebb-theme-peace@2.1.23 (installed, disabled)
* nodebb-theme-persona@13.2.42 (installed, disabled) nodebb-widget-essentials@7.0.14 (installed, 

### Database type

MongoDB

### Database version

7.0.4

### Exact steps to cause this issue

Can not login 🌝

### What you expected

login

### What happened instead

Can not login 🌝
![IMG_0877](https://github.com/NodeBB/NodeBB/assets/85857425/e446c7c2-6cd0-488f-9892-4ef4ea34ca8d)

**Comment by julianlam** [comment]
Check config.json matches the URL you are using to access the site.
