### ISSUE TITLE
Chatroom is not responsive on all devices 

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#12211]
### NodeBB version

3.5.2

### Exact steps to cause this issue

See the picture attached. The message input box is hiding and cutting and unusable.
![Screenshot_2023-12-03-20-45-22-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NodeBB/NodeBB/assets/9073066/59a56b84-7773-4703-b44f-d0c440f26f0d)

**Comment by julianlam** [comment]
Hi @FaizanZahid I need more info here re: browser version, OS, etc. and whether you've tried on other browsers.

I'll be completely honest here, we cannot fix it because it often only happens on very specific hardware that we do not have access to.

Currently when I access chats, the chat box is not cut off/impeded.

**Comment by barisusakli** [comment]
This was only happening on persona due to some 🐟 css + navbar

**Comment by FaizanZahid** [comment]
Thanks Baris, can you confirm if you have fixed this issue on all default themes including persona and harmony>?

Is nodeBB default theme now harmony instead of persona?

**Comment by barisusakli** [comment]
New default theme is harmony, in the next minor release 3.7.0 persona will use the same layout for chat as harmony. https://github.com/NodeBB/nodebb-theme-persona/commit/689ba45853ba654ef16c3f0b9cdcb376936e3c06

**Comment by FaizanZahid** [comment]
Ok, at the moment I have updated my forum to 3.6.2 and I m still facing the chat box input cutting on all mobile devices. You can see the problem attached in screenshot.
![Screenshot_2024-01-11-23-06-20-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NodeBB/NodeBB/assets/9073066/61147029-e77a-4055-b856-7163f590950a)

Yes that might solve this problem if you update the chat to use the harmony UI.
