### ISSUE TITLE
ability to override service-worker.js from plugin

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#12235]
from https://community.nodebb.org/topic/17720/plugin-development-modify-service-worker-js

**Comment by k1r0s** [comment]
related https://github.com/NodeBB/nodebb-plugin-quickstart/issues/264

**Comment by k1r0s** [comment]
so, service-worker might have unused features. I would rather do a PR to issue these changes.

And maybe in the future `/service-worker.js` path for static request should be dynamic and served by express.js so the content of the service-worker would be dynamic and plugin dependent

**Comment by barisusakli** [comment]
It is being served by express right now https://github.com/NodeBB/NodeBB/blob/master/src/routes/meta.js#L15-L17 unless you setup nginx etc to serve it directly.

What we need is a hook in that function or serve it from build/public/src so plugins can override it with a entry in plugin.json.

**Comment by k1r0s** [comment]
these are the changes that the service worker might include without being a breaking change:
```diff
diff --git a/public/src/service-worker.js b/public/src/service-worker.js
index babbf24f19..d9739825da 100644
--- a/public/src/service-worker.js
+++ b/public/src/service-worker.js
@@ -17,3 +17,14 @@ self.addEventListener('fetch', function (event) {
                return response;
        }));
 });
+
+self.addEventListener("push", event => {
+  event.waitUntil(self.clients.matchAll().then(clients => {
+    const data = event.data.json();
+    const title = data.title;
+
+    return Promise.all(clients.map(client => client.postMessage(data))).then(() => {
+      if(title) return self.registration.showNotification(title, data);
+    });
+  }));
+});

```
will come back here with feedback

**Comment by barisusakli** [comment]
@k1r0s seems like this is already possible from a plugin. Add your own `my-service-worker.js` in the public folder of your plugin.

Then add a new route in your plugin init function and serve the new service-worker. See below for a sample.

```
// goes in library.js of your plugin inside init function
library.init = async function (params) {
	const { router, middleware } = params;

	router.get('/service-worker.js', (req, res) => {
		console.log('overrides core route s owe serve our own file')
		const path = require('path');
		res.status(200)
			.type('application/javascript')
			.set('Service-Worker-Allowed', `${nconf.get('relative_path')}/`)
			.sendFile(path.join(__dirname, 'public/my-service-worker.js'));
	});
};
```

![image](https://github.com/NodeBB/NodeBB/assets/2583394/9aa5c93e-6236-4d94-aa19-20fe97738ebe)

**Comment by k1r0s** [comment]
yes, is indeed possible to override the default service-worker. however it might raise incompatibilities between other plugins ... :\

**Comment by k1r0s** [comment]
thx a lot!
