### ISSUE TITLE
Build Failed On NodeBB Setup

### ISSUE THREAD

**Issue by davesargrad** [NodeBB/NodeBB#12239]
### NodeBB version

I cloned the latest nodebb as follows:

`git clone -b v3.x https://github.com/NodeBB/NodeBB nodebb`

### Database type

I am using the basic installation procedures with mongo as my database.

### Exact steps to cause this issue

I ran the ./nodebb setup command. 
Everything seemed ok except for one error.

![image](https://github.com/NodeBB/NodeBB/assets/48793689/170e63f1-d533-4226-b8bf-eb167d7d5b80)

It wasnt clear if this was a fatal error.

I can run nodebb, and even login. However when I try to compose a message, and click "Submit" nothing happens. I do see the following in the console.

![image](https://github.com/NodeBB/NodeBB/assets/48793689/1616275e-c3b8-417e-bbb1-e5e7eb2a3002)

![image](https://github.com/NodeBB/NodeBB/assets/48793689/8f8bac01-5e24-4710-8792-f24b50278c2d)

**Comment by barisusakli** [comment]
For reference there seems to be ~4k fs.readFile calls made in parallel during language build so maybe we should put a limit on that 🤔

**Comment by davesargrad** [comment]
Thanks for your fast feedback guys. I think my issue was that I cloned an older version of nodebb.. I just recloned 3.5.3. Things seem to be up and running smoothly now.

**Comment by davesargrad** [comment]
I'll close this for now. I do think that the documentation for centos, perhaps needs to somehow reflect the right version to clone. The documentation actually references 2.x.

**Comment by barisusakli** [comment]
@davesargrad 👍🏼 ours docs are here https://github.com/NodeBB/docs/blob/master/src/docs/installing/os/centos.md, feel free to send a pull request to update them for centos

**Comment by davesargrad** [comment]
@barisusakli Awesome responsiveness!
