### ISSUE TITLE
CORS Failure

### ISSUE THREAD

**Issue by davesargrad** [NodeBB/NodeBB#12242]
### What happened instead

Hi. I am trying to exercise the API. I can use curl to access endpoints such as "/api/categories". However in my web app I see the following failure in response to an axios call. 
![image](https://github.com/NodeBB/NodeBB/assets/48793689/0b48f5a3-ff2c-45ba-b783-338626fb421b)

I've searched online and have found several nodebb CORS posts, but I havent really found a clean description of what I need to do. 

https://github.com/NodeBB/NodeBB/pull/3899

I also looked at the documentation on config.json (to see if there was a CORS configuration that I could set in the nodebb server).. but did not find this.

https://docs.nodebb.org/configuring/config/

My web app is running in firefox.

Thx in advance for any guidance.

**Comment by julianlam** [comment]
You can set CORS allowed origins in the ACP. 

Also can you move follow-up inquiries to the community forum? Thanks! 😁

https://community.nodebb.org
