### ISSUE TITLE
theme error shows 500 but returns 200

### ISSUE THREAD

**Issue by braco** [NodeBB/NodeBB#12255]
### NodeBB version

3.6.1

### NodeJS version

v18.19.0

### Database type

PostgreSQL

### Exact steps to cause this issue

I'm working on a child theme based on https://github.com/nodebb/nodebb-theme-quickstart, which is throwing a 500 error.

I don't see any logs relating to the 500 so I'm not sure what's causing the error, which is surprising because it should be in dev mode. Where are these errors logged?

The bug-worthy issue here is that although the page is throwing a 500, the status code from the server is 200.

### What you expected

status code 500

### What happened instead

status code 200

### Anything else?

For 200, see network log on last line here:

<img width="608" alt="Screenshot 2024-01-01 at 10 40 38 AM" src="https://github.com/NodeBB/NodeBB/assets/2449172/206323fd-4dc9-4ab2-b789-1943f63e6df8">

**Comment by julianlam** [comment]
Please let us know what the server stack trace says. Likely that will point out the culprit.

**Comment by braco** [comment]
Thanks @julianlam, where would that be? It's not in the stdout from `./nodebb dev` and logs/output.log is empty.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-quickstart/issues/11
