### ISSUE TITLE
failed to parse platform

### ISSUE THREAD

**Issue by rafalohaki** [NodeBB/NodeBB#12256]
### NodeBB version

v3.6.1

```
root@minifast:~/docker/NodeBB-3.6.1# docker-compose --profile redis up
Building nodebb
Sending build context to Docker daemon  17.68MB
Step 1/25 : FROM --platform=$BUILDPLATFORM node:lts as npm
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
ERROR: Service 'nodebb' failed to build : Build failed
root@minifast:~/docker/NodeBB-3.6.1#
```

### Anything else?

Tried to use nodebb via docker from:
https://docs.nodebb.org/installing/cloud/docker/

**Comment by oplik0** [comment]
What version of Docker are you running? (just use `docker --version`)
If you're running a version <23.0 can you try running `docker buildx install` and then running `docker-compose --profile redis up`?
If you're running a version >23.0, can you try `docker compose` instead of `docker-compose`?

**Comment by rafalohaki** [comment]
> What version of Docker are you running? (just use `docker --version`) If you're running a version <23.0 can you try running `docker buildx install` and then running `docker-compose --profile redis up`? If you're running a version >23.0, can you try `docker compose` instead of `docker-compose`?

root@minifast:~/docker/NodeBB-3.6.1# docker --version
Docker version 20.10.24+dfsg1, build 297e128
