### ISSUE TITLE
accepted types in the upload image button

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#12267]
### Description

The upload button is for uploading an image:
![CleanShot 2024-01-07 at 03 30 36@2x](https://github.com/NodeBB/NodeBB/assets/78599753/e49c1296-b4cc-4f6b-8b93-bd923dd4b963)
but `accept="image/*"` (maybe `image/*,video/*`) is not set.
You should add it. This causes the inappropriate files to be hidden in a computer selector making selection easier, and on mobile displays an alternative selector for media-only files instead of a cumbersome file explorer.

**Comment by barisusakli** [comment]
Can't use both image/*, video/*
