### ISSUE TITLE
Use older node (v16) for compatibility with older Linux machines

### ISSUE THREAD

**Issue by Michaelwucoc** [NodeBB/NodeBB#12260]
### Description

I am using CentOS 7 to install NodeBB. When I updated, the node.js warns me that I need to install v.18 of node. But Centos 7 is incompatible with node v18. It may affect some features, wish can use older node to take care of old node users! plz

**Comment by julianlam** [comment]
I think in this case the newer node.js version a result of a requirement from an underlying dependency. If you need to maintain NodeBB on a centos machine, you may just need to use 3.5.x, we can backport security fixes as necessary

**Comment by Michaelwucoc** [comment]
Okay, but what I'm asking is will future versions of NodeBB still be compatible with Node 16? Or is it permanently developed on v18+?

**Comment by Michaelwucoc** [comment]
Cause, we old node users want to experience new features too! =w=)

**Comment by oplik0** [comment]
The issue with maintaining compatibility is that the entire Node ecosystem is moving along to Node 18 - a lot of NodeBB's dependencies already require v18.

The big update for NodeBB is stabilization of the `fetch` API - which NodeBB is moving to from an older, officially deprecated, `request` library.

Incompatibility with CentOS 7 is unfortunate, but continuing to support Node 16 would require:
- rewriting `fetch` calls to another Node HTTP library that supports older versions of Node, or creating an IMO fairly hacky polyfill using something like `node-fetch` package
- forking and maintaining dependencies that moved required Node version up
- avoiding using any new ECMAScript features that aren't yet present in Node 16, e.g. streams, blobs, broadcastchannels, or even some new array methods added in newer v8 versions
- maintaining another CI target

All of this essentially just to support a 9.5-year old target that will officially reach EoL in 6 months.

(Note that I'm not part of NodeBB team so this isn't a decision, just some background and opinion on why NodeBB dropped support for Node 16)

**Comment by Michaelwucoc** [comment]
I think this is a great change from v16 ==> v18. Yeah. But, every time I see I need to update I will be sad..

**Comment by Michaelwucoc** [comment]
I agree that v18 has more function, and I can use v16 version still. (Cause we have use NodeBB build our community for 2 years and I don't want easily erase it)
