### ISSUE TITLE
Routing homepage for logged and non logged users with custom page

### ISSUE THREAD

**Issue by smontiu** [NodeBB/NodeBB#12271]
### Description

Hi!

I use a custom page plugin to have a landing page for my forum, but the configuration only allows to have one custom page for all kinds of users. I will like to have the option to set a different custom page for logged users, and no logged users. Root them to "categories" instead of the custom page (landing page).

I am pretty sure that more users would like to do the same thing.

**Comment by barisusakli** [comment]
You should be able to do this using the hook `action:homepage.get:<pathname>` https://github.com/NodeBB/NodeBB/blob/master/src/controllers/home.js#L55

Assuming your page is called `custom` the name of the hook that would fire would be `action:homepage.get:custom`. You add a entry in your plugin.json hooks array like so:

```
{ "hook": "action:homepage.get:custom", "method": "actionHomePageGetCustom" }
```

And implement it in your plugin library.js file like below.

```
library.actionHomePageGetCustom = async ({ req, res, next }) => {
	// redirect non-logged in users to categories
	if (req.uid <= 0) {
		const controllersHelpers = require.main.require('./src/controllers/helpers');
		controllersHelpers.redirect(res, '/categories');
		return;
	}
	// default action, redirect to custom page
	const pathname = res.locals.homePageRoute;
	req.url = req.path + (!req.path.endsWith('/') ? '/' : '') + pathname;
	next();
};
```

This would cause logged in users to see the custom page and everyone else would get redirected to `/categories/

Let me know if that helps.
