### ISSUE TITLE
[feat req] Add option to disable "flag profile" button or "flag post" for users that abuse it

### ISSUE THREAD

**Issue by diamante0018** [NodeBB/NodeBB#12274]
### Description

Hello, I have a somewhat weird case where a user doesn't do anything that would be considered "ban-worthy". However, I find an high amount of "spam" by them when they report a lot of posts using one of the buttons found in the screenshots below.

I may be mistaken as I have permission to "ban" users but I am not the actual sys admin of the forum I'm part of so I am not 100% sure this feature is missing. 

Anyhow, If possible I would like to know if such a feature could be considered and implemented.

My goal would be to either:

- Quitely block them. So if the user spams reports they do nothing and I as a mod don't see them in the notifications tab.
- Displays an error message to the user saying the flag feature is disabled (for them specifically).

Thanks a lot.

![image](https://github.com/NodeBB/NodeBB/assets/37080671/a0f9215a-dcb6-4a9b-9765-b7a3dce19e2e)
![image](https://github.com/NodeBB/NodeBB/assets/37080671/e88c860c-225a-4d94-b218-ebde25a97eb2)

**Comment by barisusakli** [comment]
Some kind of rate limiting on flag profile/flag post would be nice.

**Comment by diamante0018** [comment]
Sounds good to me
