### ISSUE TITLE
Google Search Console - '"Comment" object must be nested inside a "CreativeWork" object'

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#12308]
### NodeBB version

v3.6.4

### NodeJS version

v20.11.0

### Installed NodeBB plugins

* nodebb-plugin-2factor@7.4.0 (installed, disabled)
* nodebb-plugin-composer-default@10.2.31 (installed, enabled)
* nodebb-plugin-dbsearch@6.2.3 (installed, enabled)
* nodebb-plugin-emoji@5.1.13 (installed, enabled)
* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
* nodebb-plugin-imgur@4.1.0 (installed, enabled)
* nodebb-plugin-markdown@12.2.5 (installed, enabled)
* nodebb-plugin-mentions@4.3.7 (installed, enabled)
* nodebb-plugin-ntfy@1.7.3 (installed, disabled)
* nodebb-plugin-soundpack-default@3.0.0 (installed, disabled)
* nodebb-plugin-spam-be-gone@2.2.0 (installed, disabled)
* nodebb-rewards-essentials@1.0.0 (installed, disabled)
* nodebb-theme-harmony@1.1.108 (installed, disabled)
* nodebb-theme-harmony-sweetp@1.0.0 (installed, enabled)
* nodebb-theme-lavender@7.1.7 (installed, disabled)
* nodebb-theme-peace@2.1.26 (installed, disabled)
* nodebb-theme-persona@13.2.50 (installed, disabled)
* nodebb-theme-slick@2.0.2 (installed, disabled)
* nodebb-theme-vanilla@12.1.19 (installed, disabled)
* nodebb-widget-essentials@7.0.14 (installed, enabled)

### Database type

PostgreSQL

### Database version

v16.1 (Ubuntu 16.1-1.pgdg22.04+1)

### Exact steps to cause this issue

Ive finally gotten around to submitting my forum to Google Search Console, and received the error:

```
Discussion forum structured data issues detected in <mynodeBBinstance>
Search Console has identified that your site is affected by 1 Discussion forum structured data issue(s).
The following issues were found on your site.

Top non-critical issues‡

"Comment" object must be nested inside a "CreativeWork" object
```

### What you expected

No errors

**Comment by barisusakli** [comment]
This should have fixed that issue  https://github.com/NodeBB/NodeBB/commit/4427ca4cab0b38aa7b53119093e70b4a9119f481

Our forum is running 3.6.4 and comments are nested under DiscussionForumPosting which are CreativeWorks https://schema.org/DiscussionForumPosting

Make sure your posts have the `itemprop="comment"` property on them.


![image](https://github.com/NodeBB/NodeBB/assets/2583394/d0aa89c0-38a6-49e6-953b-f624793c885d)
