### ISSUE TITLE
Nothing indicates new posts in categories page

### ISSUE THREAD

**Issue by waazdakka** [NodeBB/NodeBB#12312]
### Description

I just installed the very good theme on my brand new Nodebb.

Everything works very well for the moment, I created some content to test but one functionality is sorely missing: in the categories page, there is nothing to indicate when a new message has been posted in a sub-category. And when you enter a category and go back, the blue highlighting of the text disappear even if you didn't read the post.

It is very difficult for users to manage the "new messages posted" system, so I'm not sure I could keep this template :(

I think the title of categories with new messages should stay in bold as long as messages are not read

But maybe I'm missing something...

Thanks!

**Comment by waazdakka** [comment]
I can see that and this behaviour is really not the one the users could handle... Is this a behaviour of this particular template or of all NodeBB templates?

**Comment by barisusakli** [comment]
Yes it effects all templates right now.

**Comment by waazdakka** [comment]
Thanks for your fast answer!

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/12317
