### ISSUE TITLE
html tags in email subject for new topic notification

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#12331]
### NodeBB version

v3.6.5

### NodeJS version

v20.11.0

### Installed NodeBB plugins

* nodebb-plugin-2factor@7.4.0 (installed, disabled)
* nodebb-plugin-composer-default@10.2.31 (installed, enabled)
* nodebb-plugin-dbsearch@6.2.3 (installed, enabled)
* nodebb-plugin-emoji@5.1.13 (installed, enabled)
* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
* nodebb-plugin-imgur@4.1.0 (installed, enabled)
* nodebb-plugin-markdown@12.2.5 (installed, enabled)
* nodebb-plugin-mentions@4.3.7 (installed, enabled)
* nodebb-plugin-ntfy@1.7.3 (installed, disabled)
* nodebb-plugin-soundpack-default@3.0.0 (installed, disabled)
* nodebb-plugin-spam-be-gone@2.2.0 (installed, disabled)
* nodebb-rewards-essentials@1.0.0 (installed, disabled)
* nodebb-theme-harmony@1.1.108 (installed, disabled)
* nodebb-theme-harmony-sweetp@1.0.0 (installed, enabled)
* nodebb-theme-lavender@7.1.7 (installed, disabled)
* nodebb-theme-peace@2.1.26 (installed, disabled)
* nodebb-theme-persona@13.2.50 (installed, disabled)
* nodebb-theme-slick@2.0.2 (installed, disabled)
* nodebb-theme-vanilla@12.1.19 (installed, disabled)
* nodebb-widget-essentials@7.0.14 (installed, enabled)

### Database type

PostgreSQL

### Database version

16.1 (Ubuntu 16.1-1.pgdg22.04+1)

### Exact steps to cause this issue

a new topic is created

### What you expected

a new topic email notification is sent with a sanitised subject

### What happened instead

My new topic email subject notifications look like so:
```[MyNodeBB Forum] <strong>Roger888</strong> has posted a new topic in <strong>New Stuff</strong>```

### Anything else?

my custom theme is a minimal sub theme for Harmony, so I can't imagine it is causing the issue:
https://github.com/sweetppro/nodebb-theme-sweetp

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/e01bceff97d48de2d475194ea0372605ffbb82c3
