### ISSUE TITLE
theme-harmony: Buttons are not showing in the right theme

### ISSUE THREAD

**Issue by itzdrli** [NodeBB/NodeBB#12336]
### NodeBB version

3.6.5

### NodeBB git hash

f7736155aed6f668fadeef15521923a829469e73

### NodeJS version

20.11.0

### Installed NodeBB plugins

        * @nodebb/nodebb-plugin-reactions@2.2.1 (installed, enabled)
        * @nodebb/nodebb-plugin-s3-uploads@3.0.4 (installed, disabled)
        * nodebb-plugin-2factor@7.4.0 (installed, enabled)
        * nodebb-plugin-composer-default@10.2.31 (installed, enabled)
        * nodebb-plugin-dbsearch@6.2.3 (installed, enabled)
        * nodebb-plugin-emoji@5.1.13 (installed, enabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
        * nodebb-plugin-gdpr@2.0.0 (installed, enabled)
        * nodebb-plugin-markdown@12.2.5 (installed, enabled)
        * nodebb-plugin-mentions@4.3.7 (installed, enabled)
        * nodebb-plugin-ntfy@1.7.3 (installed, enabled)
        * nodebb-plugin-spam-be-gone@2.2.0 (installed, enabled)
        * nodebb-plugin-sso-github@3.1.0 (installed, enabled)
        * nodebb-plugin-sso-qq-fix@2.2.2 (installed, disabled)
        * nodebb-plugin-sso-steam-2@1.0.2 (installed, enabled)
        * nodebb-plugin-uploads-s3-update@1.0.4 (installed, disabled)
        * nodebb-rewards-essentials@1.0.0 (installed, enabled)
        * nodebb-theme-harmony@1.2.23 (installed, enabled)
        * nodebb-theme-harmony-dna@1.0.21 (installed, disabled)
        * nodebb-theme-peace@2.1.26 (installed, disabled)
        * nodebb-theme-persona@13.3.5 (installed, disabled)
        * nodebb-theme-slick@2.0.5 (installed, disabled)
        * nodebb-theme-vanilla@12.1.19 (installed, disabled)
        * nodebb-widget-essentials@7.0.14 (installed, enabled)

### Database type

MongoDB

### Database version

7.0.5

### Exact steps to cause this issue

1. Install nodebb-theme-harmony@1.2.23
2. Enable it and then build & restart

### What you expected

the buttons should be looked like this:
![image](https://github.com/NodeBB/NodeBB/assets/52338732/debf93b7-0dc7-4bae-a68a-2ecb506c656f)

### What happened instead

The buttons looked like this:
![image](https://github.com/NodeBB/NodeBB/assets/52338732/f9590422-c5bb-406c-91cb-d0c587d9198f)
using skin: superhero/cyborg/flatly
and also the images are looking strange too:
![image](https://github.com/NodeBB/NodeBB/assets/52338732/2a212ee9-692e-4928-89f3-590c8e83f42f)

### Anything else?

Not sure if this is the right place to post this issue, if not, sorry about that.

**Comment by barisusakli** [comment]
If you are using nodebb 3.6.5 you should be using "nodebb-theme-harmony": "1.1.108",

https://github.com/NodeBB/NodeBB/blob/v3.6.5/install/package.json#L106

1.2.23 is for the upcoming 3.7.0 release.

**Comment by itzdrli** [comment]
> If you are using nodebb 3.6.5 you should be using "nodebb-theme-harmony": "1.1.108",
> 
> https://github.com/NodeBB/NodeBB/blob/v3.6.5/install/package.json#L106
> 
> 1.2.23 is for the upcoming 3.7.0 release.

thanks, working now
