### ISSUE TITLE
Cannot find module './settings/advanced' 

### ISSUE THREAD

**Issue by arkabase** [NodeBB/NodeBB#12413]
### NodeBB version

v3.7.1

### NodeBB git hash

712365a592e3d1bc1a95464f45e97d1bac6f3ac3

### NodeJS version

v20.9.0

### Installed NodeBB plugins

        * @nodebb/nodebb-plugin-reactions@2.2.1 (installed, enabled)
        * nodebb-plugin-2factor@7.4.0 (installed, disabled)
        * nodebb-plugin-audio-embed@2.0.1 (installed, enabled)
        * nodebb-plugin-composer-default@10.2.33 (installed, enabled)
        * nodebb-plugin-dbsearch@6.2.3 (installed, enabled)
        * nodebb-plugin-emoji@5.1.13 (installed, enabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
        * nodebb-plugin-gravatar@4.0.0 (installed, enabled)
        * nodebb-plugin-knowledge-base@2.0.1 (installed, enabled)
        * nodebb-plugin-markdown@12.2.6 (installed, enabled)
        * nodebb-plugin-mentions@4.4.0 (installed, enabled)
        * nodebb-plugin-ntfy@1.7.3 (installed, disabled)
        * nodebb-plugin-osm-map@2.2.0 (installed, enabled)
        * nodebb-plugin-poll@3.1.2 (installed, enabled)
        * nodebb-plugin-question-and-answer@1.2.7 (installed, enabled)
        * nodebb-plugin-session-sharing@7.1.2 (installed, disabled)
        * nodebb-plugin-spam-be-gone@2.2.1 (installed, disabled)
        * nodebb-rewards-essentials@1.0.0 (installed, enabled)
        * nodebb-theme-harmony@1.2.40 (installed, enabled)
        * nodebb-theme-lavender@7.1.7 (installed, disabled)
        * nodebb-theme-peace@2.2.4 (installed, disabled)
        * nodebb-theme-persona@13.3.11 (installed, disabled)
        * nodebb-widget-essentials@7.0.15 (installed, enabled)

### Database type

MongoDB

### Database version

v7.0.6

### Exact steps to cause this issue

- Login as administrator
- Go to admin menu
- Click on Settings > Advanced

### What you expected

Open advanced settings page without error

### What happened instead

Advanced settings page opens but throws following error in the browser console :
```
error loading admin/settings/advanced
Error: Cannot find module './settings/advanced'
    at https://<nodebb-path>/assets/admin.min.js?v=b6tnrivm6a8:1:21166
    at async T (https://<nodebb-path>/assets/admin.min.js?v=b6tnrivm6a8:1:34265)
    at async Promise.all (index 0)
    at async app.require (https://<nodebb-path>/assets/admin.min.js?v=b6tnrivm6a8:2:54)
    at async https://<nodebb-path>/assets/admin.min.js?v=b6tnrivm6a8:1:27943
```

### Anything else?

Advanced settings page seems to work fine, so I don't know why this error is thrown, unless there is something that don't work and I'm not aware of...

**Comment by barisusakli** [comment]
This is fine, some pages don't have a client side js module

**Comment by arkabase** [comment]
Maybe this should be addressed by the app to avoid throwing an error for nothing
