### ISSUE TITLE
Add filter hook to update file

### ISSUE THREAD

**Issue by JhnW** [NodeBB/NodeBB#12416]
### Description

Hi.
I am currently writing a view in which for some topics some users should have different avatars uploaded. On the front side, everything is OK, the modules used in the profile to create a dialog box and crop the image are written in a very universal way, allowing you to customize them with parameters. Unfortunately, I encountered a problem when integrating with the backend.
_pictureCropper.show takes_ a structure with a field as its first argument _socketMethod_. 
Unfortunately, you can't use your own method because the backend has the following filter:
```
uploads.upload = async function (socket, data) {
	const methodToFunc = {
		'user.uploadCroppedPicture': socketUser.uploadCroppedPicture,
		'user.updateCover': socketUser.updateCover,
		'groups.cover.update': socketGroup.cover.update,
	};
	if (!socket.uid || !data || !data.chunk ||
		!data.params || !data.params.method || !methodToFunc.hasOwnProperty(data.params.method)) {
		throw new Error('[[error:invalid-data]]');
	}
```
from _/src/socket.io/uploads.js_

I don't know to what extent the use of this filter makes sense in itself, but adding a filter hook for allowed methods would be very good (it would require a slight change in the maxSize count to deliver imageData/size to the new socket in order to independently handle the size).

**Comment by barisusakli** [comment]
@JhnW you can use `filter:uploads.upload` to add your own socket method this is on the develop branch now.

https://github.com/NodeBB/NodeBB/blob/develop/src/socket.io/uploads.js#L21-L29

```
myPlugin.filterUploadsUpload = async (hookData) => {
   hookData.methods['user.someCustomName'] = myCustomUploadFunction;
   hookData.maxSize = customUploadMaxSize;
   return hookData;
};

async function myCuystomUploadFunction(socket, params) {
   // handle upload
}
```
