### ISSUE TITLE
Menu/nav bar at top always requires double tapping in iOS

### ISSUE THREAD

**Issue by sorvani** [NodeBB/NodeBB#1241]
in order to use the new posts or see my alerts, I have to tap once to select the object and then again to display whatever it is supposed to display. I think for a mobile centric BB application, that it should understand that I am using a touch device and the single tap should show the content.

**Comment by martyalicante** [comment]
not solved, please reopen

**Comment by barisusakli** [comment]
https://github.com/twbs/bootstrap/issues/6232

**Comment by barisusakli** [comment]
ipad is not identified as xs or sm so tooltips are created and because of the above bug it blocks click events on first tap.
