### ISSUE TITLE
API for upvoting a post is not working

### ISSUE THREAD

**Issue by nesro** [NodeBB/NodeBB#12422]
### NodeBB version

v3.7.1

### NodeJS version

v20

### Database type

MongoDB

### Exact steps to cause this issue

Call the API to upvote a post https://docs.nodebb.org/api/write/#tag/posts/paths/~1posts~1%7Bpid%7D~1vote/put

### What you expected

It should upvote a post

### What happened instead

I'm not seeing the post upvoted

### Anything else?

If I manually add the user to the members array in `{_key: 'pid:{pid}:upvote'}` and then calls the API, it works and the post is upvoted. This is a hotfix that is currently working for us, but the API should work on it's own.

**Comment by barisusakli** [comment]
What are you seeing in your network tab when you upvote a post? Are you using the UI or are you making an api call only?

**Comment by nesro** [comment]
When I call the API from a Node backend or from the command line via curl - I get a normal status 200 response.

But there is no effect and the post is not upvoted. Only when I edit the members list in Mongo and then call the API, the post is upvoted.

**Comment by barisusakli** [comment]
This seems to work for me on 3.x 
```
curl -X PUT http://127.0.0.1:4567/api/v3/posts/32312/vote?_uid=1 --data "delta=1" -H "Authorization: Bearer xxxxx"
```

**Comment by nesro** [comment]
Hi Baris, it's possible that it wasn't working for me because of other things. I will retest it and let you know. Thanks for the info that it's working for you.

**Comment by nesro** [comment]
I made a mistake by using userToken instead of a masterToken when trying to upvote a post on behalf of a user. Sorry for the false bug report. I'm closing this issue.
