### ISSUE TITLE
Error While Creating User using nodebb api

### ISSUE THREAD

**Issue by shefali-jain21** [NodeBB/NodeBB#12421]
### NodeBB version

3.7.0

### NodeJS version

v20.11.1

### Database type

MongoDB

### Database version

v4.0.11

### What you expected

const myHeaders = new Headers();
myHeaders.append("Content-Type", "application/json");
myHeaders.append("Authorization", "Bearer db96a903-bce1-4e96-9ced-ef2c9b664bdb");
myHeaders.append("Cookie", "express.sid=s%3AEmar91r32ehIF51BqPv9QO90WMVsKZmu.r4%2FV834Ydv6wIwMauDaXJRFF1nCGIDraGaB0MGtDl5w");

const raw = JSON.stringify({
  "username": "jitendra",
  "email": "jitendra.tailor@habilelabs.io",
  "password": "morwalexamsbook",
  "_uid": 0
});

const requestOptions = {
  method: "POST",
  headers: myHeaders,
  body: raw,
  redirect: "follow"
};

fetch("http://localhost:4567/api/v3/users", requestOptions)
  .then((response) => response.text())
  .then((result) => console.log(result))
  .catch((error) => console.error(error));

### What happened instead

{
    "status": {
        "code": "internal-server-error",
        "message": "Failed to serialize user into session"
    },
    "response": {}
}

**Comment by julianlam** [comment]
Likely this: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
