### ISSUE TITLE
Utilize taskbar at the bottom for chats

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#1242]
If the chat can be in the task bar instead of a popup modal. The reason being is that it would save some space. To give an example, Facebook utilizes this quite well as an unobtrusive integrated application within the site. What do you guys think of this idea/enhancement?

**Comment by cnvo** [comment]
No more drawing on paper, I have Sketch now. :+1:

**Comment by psychobunny** [comment]
I'm closing this as its actually a theme issue not core. That said, it is on my todo list for persona; I really want to get shot of that chat modal we have as default

@cnvo I really liked that FB style chat popup you made a while ago, not sure for which version of Majestic it was. Would totally love to get that in as default ;)
