### ISSUE TITLE
Post visibility

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12448]
A concept mutually exclusive from category privileges, a post should be able to specify its own recipients.

While there is limited use-case for it in NodeBB itself, ActivityPub specifies that individual Notes may be addressed to the public pseudo-address, follower collections, or **specific users**.

In order to support this, NodeBB would need to have the concept of post visibility.

**Comment by julianlam** [comment]
Topic visibility can be governed by OP post visibility. I am not certain what kind of restrictions we will add at this time.

**Comment by AliCihan** [comment]
> Topic visibility can be governed by OP post visibility. I am not certain what kind of restrictions we will add at this time.

nice 👍 Will admins be able to change this visibility later if the topic needs to be hidden from public?

**Comment by julianlam** [comment]
@AliCihan I think so, if you have moderation privileges, you should be able to adjust visibility settings as well.

**Comment by julianlam** [comment]
Seems the following sorted sets are also appended to, and require test cases:

* `cid:${c}:uid:${userData.uid}:pids`
* `cid:${c}:uid:${userData.uid}:pids:votes`
* `cid:${c}:uid:${userData.uid}:tids`
* `uid:${userData.uid}:followed_tids`
* `uid:${userData.uid}:ignored_tids`

**Comment by julianlam** [comment]
Putting a pause on this one as the implementation seems to be a lot more difficult and fragile than I expected.
