### ISSUE TITLE
Deleting user images is very slow

### ISSUE THREAD

**Issue by nesro** [NodeBB/NodeBB#12449]
### NodeBB version

v3.7.1

### NodeJS version

v20

### Database type

MongoDB

### Exact steps to cause this issue

Delete a user - with API or from web.

### What you expected

User images are deleted quickly.

### What happened instead

The glob that is looking for pictures and covers to delete from the `/assets/uploads/profile` directory takes too long ( https://github.com/NodeBB/NodeBB/blob/master/src/user/delete.js#L231 ). This is causing troubles and in our case healtcheck timeouts and the instance is restarted.

### Anything else?

A quick fix would be to delete only user's `cover:url` (if it's a file not url) and `uploadedpicture` from the directory (direct file access is fast). But it won't work in general.  For cases when the `keepAllUserImages` setting is true, the best fix would be to store all paths to user covers and pictures and then delete them all without needing to use glob.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/12450
