### ISSUE TITLE
ability to edit moderation notes

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#12477]

**Comment by AliCihan** [comment]
additionally, can we have active links on the notes? right now, links are turned into simple texts...

**Comment by AliCihan** [comment]
hi @barisusakli , are we able to upload an image to these notes just like posts? thanks.

**Comment by barisusakli** [comment]
@AliCihan nope, although you can upload somewhere else and put a link to it using markdown and it will show the image.
