### ISSUE TITLE
Send a unique `id` for all ActivityPub server-to-server events

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12483]
e.g. `Create(Note)` contains two ids, one for the `Create`, and another for the `Note`. This issue pertains to the former.

Apparently activity IDs could be used as part of an `Undo` call _shrug_

Further research needed.

**Comment by oplik0** [comment]
Status update: now Create(Note), Update(Note), Follow and Undo(Follow) have ids.

**Comment by julianlam** [comment]
silverpill notified me that our `Like` activities are also missing an `id`, which is necessary as some implementations use the id to handle undos.
