### ISSUE TITLE
Unable to follow remote accounts on Mitra/Akkoma

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12488]
Follow problems with Akkoma and Mitra accounts might be related; same follow id or accept id issue?

**Comment by oplik0** [comment]
There were two issues here:
1. we didn't send an ID along with the `Follow` activity (see #12483)
2. we fully rejected activities with objects when their id didn't match the activity's origin

The latter was done for security reason, but meant that a lot of activities either couldn't work or would break with compliant implementations. Now instead such mismatched objects are stripped down to just their ids and then retrieved from origin (once [FEP-8b32](https://codeberg.org/fediverse/fep/src/branch/main/fep/8b32/fep-8b32.md) is finalized and implemented it should allow to skip this additional download for signed objects)
