### ISSUE TITLE
World (Curated) & World (All) menu items for Guests

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#12506]
### Exact steps to cause this issue

Tested on https://community.nodebb.org/

Registered/logged-in users:
![g1](https://github.com/NodeBB/NodeBB/assets/11160550/db490891-d286-4b08-8392-5e7c098d42e8)

Guests:
![g2](https://github.com/NodeBB/NodeBB/assets/11160550/20b48314-d780-43ae-848a-27e9bea009a8)

### What you expected

Same text to be rendered no matter who visits NodeBB app.

### What happened instead

Different menu for guests and logged-in users.

### Anything else?

Both English and non-English web browser shows it wrongly.

**Comment by wakest** [comment]
happy to see you reported this @nhlpl I was just filing this issue myself and see you beat me to it!

**Comment by julianlam** [comment]
Translation strings are sent out for localisation once the branch lands in `develop`, so there will be none for now.
