### ISSUE TITLE
remote ActivityPub representation of Category "avatars"

### ISSUE THREAD

**Issue by wakest** [NodeBB/NodeBB#12507]
### Exact steps to cause this issue

I searched for https://community.nodebb.org/category/30/activitypub in Mastodon and followed the Category from there which shows up as a "Group" on Mastodon and looks like this:
<img width="615" alt="image" src="https://github.com/NodeBB/NodeBB/assets/7890201/01fd3623-da50-484e-8730-631339270ab3">

### What you expected

the Category I was searching for has an icon set so I would have assumed that should be displayed back on Mastodon
<img width="472" alt="image" src="https://github.com/NodeBB/NodeBB/assets/7890201/ccc35775-ddf9-402f-8563-0ff70689a9ca">

### What happened instead

Mastodon is somehow getting a copy of the header for the NodeBB instance and cropping the middle for the avatar representation

**Comment by julianlam** [comment]
Unfortunately that icon is a text icon and not an image 😞

**Comment by wakest** [comment]
the way that writefreely does it is take the first letter and rendering it into an image which seems like that could totally be done with a webfont
<img width="349" alt="image" src="https://github.com/NodeBB/NodeBB/assets/7890201/35107928-b083-4c4a-adc4-0086b314192f">

**Comment by julianlam** [comment]
Problem here is not that it is impossible, but that it is rather resource intensive to do so... though one can make the argument that it is only once in awhile that this is done.

We could actually send out an SVG... that can be programmatically generated, I think.

**Comment by julianlam** [comment]
I attempted to send in a data-uri for an SVG, but ran into escaping issues, so I think allowing data-uris to be accepted would be a bit difficult to do.

For now, the icon is the forum brand icon, and the category image (if uploaded), will be sent as `image`, which is typically used in Mastodon as a cover photo of sorts.

**Comment by julianlam** [comment]
Potentially we could use a method similar to vercel/og

* [Satori](https://github.com/vercel/satori) followed by [resvg-js](https://www.npmjs.com/package/@resvg/resvg-js)
