### ISSUE TITLE
Skip value must be non-negative, but received: -1

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#12502]
### Exact steps to cause this issue

https://community.nodebb.org/post/99165
Returns an error:
`Skip value must be non-negative, but received: -1`

### What you expected

Posts to be displayed instead of an error page.

### What happened instead

Internal error page.

**Comment by julianlam** [comment]
Seems ActivityPub related. Oddly, only occurs when the post index is `3`. :thinking:
