### ISSUE TITLE
Webfinger queries require %-encoded parameters

### ISSUE THREAD

**Issue by jernst** [NodeBB/NodeBB#12531]
### Anything else?

This comes from a review of https://github.com/NodeBB/NodeBB/blob/activitypub/test/activitypub.js.

The Webfinger queries performed all do not percent-encode the URL parameters, e.g. `.../webfinger?resource=acct:foobar@${host}` vs `.../webfinger?resource=acct%3afoobar%40${host}`, which RFC7033 specifically requires. See https://datatracker.ietf.org/doc/html/rfc7033#section-4.1

I did not review the actual code that this tests, which presumably also might need adjusting.

**Comment by oplik0** [comment]
Done, we were accepting such requests just fine (so the tests should work fine either way :), but it seems that fetch isn't doing this kind of encoding of query params by default. In the end I just used `URLSearchParams` to achieve this instead, since it percent-encodes everything correctly.
