### ISSUE TITLE
ability to chat with a specific group in the forum

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#12570]
### Description

thanks to your efforts, we can now restrict new users to chat with all users and prevent spams... 

![Screenshot 2024-05-12 at 20 38 02](https://github.com/NodeBB/NodeBB/assets/52054408/2c42bec2-42a4-47a5-b953-b65a818c8345)

I wonder if we can have another layer of chat option to able/disable with specific group of users... currently, we have option for privileged users only (both admins and global moderators, right?) 

especially we have two groups of people that we want to allow for new users to chat besides admins... the first group is "category moderators" which are not global moderators (are they considered privileged?), and the second group is professionals in the forum (they are not necessarily moderators but users may want to reach them directly for their private issues)...

**Comment by barisusakli** [comment]
Moderators are considered privileged users so you should be able to achieve this by creating a private category for the "professionals" group and making them moderators of that category, then regular users will be able to send chat messages to professionals group.
