### ISSUE TITLE
visibility of votes: new feature to make votes visible to logged in users only

### ISSUE THREAD

**Issue by khassel** [NodeBB/NodeBB#12597]
### Description

Release v3.7.4 fixed

* if votes are not public, dont show upvoter names in tooltip (https://github.com/NodeBB/NodeBB/commit/5af69dbcef43d7fa499741fa405203f1a1975c6c)

AFAIS: All users were able to use this tooltip before the fix. After the fix, the tooltip (and popup) will only be visible to admins and mods.

We want tooltips and popups to be visible to all logged in users, but not to guests.

At the moment we only have the choice between
- all users (including guests)
- admin and mods only

Users get the error messages on the newer forum versions and ask why they are no longer allowed to see votes...

Maybe I'm missing something and this is already possible?

**Comment by barisusakli** [comment]
![image](https://github.com/NodeBB/NodeBB/assets/2583394/b1e552e1-757b-49d9-ba0e-ef3426be292f)

**Comment by khassel** [comment]
that was quick, thanks!
