### ISSUE TITLE
`@context` in actor objects is missing `https://w3id.org/security/v1`

### ISSUE THREAD

**Issue by grishka** [NodeBB/NodeBB#12604]
### NodeBB version

v3.8.2

### Exact steps to cause this issue

Fetch a NodeBB actor, e.g. `curl "https://community.nodebb.org/user/julian" -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"'`

### What you expected

The `@context` should contain `https://w3id.org/security/v1`

### What happened instead

It does not, thus Smithereen doesn't see the public key because I somehow made the only server on the entire fediverse that actually does JSON-LD processing I guess

**Comment by julianlam** [comment]
Thanks, I initially had it, but omitted it because I didn't have time to actually look into what `https://w3id.org/security/v1` meant, and I didn't want to claim support for something that I don't even know the details about.

**Comment by grishka** [comment]
Context URLs aren't about claiming support for something. They specify aliases and namespaces you can reference in your object, as well as object types (e.g. that some field is an `@id`, so a URL that references something, rather than a plain string). Those parts of the context that you don't reference are inert.

**Comment by julianlam** [comment]
Pardon my ignorance; which properties in the user actor are defined under the W3ID Security Vocabulary? I see `publicKey`, `owner`, `publicKeyPem`?

Ironically it says here `owner` is deprecated... 🤔

**Comment by grishka** [comment]
>  I see publicKey, owner, publicKeyPem?

Yes, `publicKey` itself and everything under it.

> Ironically it says here owner is deprecated... 🤔

You mean there's some documentation for it somewhere? You can just open the URL itself, https://w3id.org/security/v1, to see everything that gets added to your context. I had no idea these things can get deprecated (and come with docs that say so), but it's set in stone now either way.

**Comment by julianlam** [comment]
Thanks @grishka, sorry for the delay, I've added it to both user and category actors now :)
