### ISSUE TITLE
For all users to use SSO accounts

### ISSUE THREAD

**Issue by daoauth** [NodeBB/NodeBB#12622]
### Description

I’m planning to set up a forum using NodeBB. I want all users to use SSO accounts.
1.	Is it possible to use only alternative registration?
2.	Can the admin user also be set to use SSO during the initial setup?

**Comment by julianlam** [comment]
Yes, you can disable local registration.

Local account is required for initial setup if only because you probably won't be able to set up the SSO plugin without that local account first.

Once you have an SSO account promoted to admin, you could always delete that first local user.
