### ISSUE TITLE
updating user profile sends update note to 16k+ users

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#12674]
https://github.com/NodeBB/NodeBB/blob/activitypub/src/api/activitypub.js#L174-L187

**Comment by julianlam** [comment]
Yes, not ideal, but intentional.

The total number of calls is actually fewer because most implementers use shared inboxes, so all accounts on a single domain are ideally done with one call.

But we could just update followers, that's fine too.
