### ISSUE TITLE
[ActivityPub] Emoji support

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12683]
(@pitaj) The following changes to nodebb-plugin-emoji would be helpful to allow NodeBB to federate out emoji properly:

1. On `filter:parse.post`, check the `type` parameter now passed-in in NodeBB v4. If type is `activitypub.note`:
    * ~~Send the unicode equivalent of the emoji instead of the image html (e.g. 🙈 instead of `<img src="..." class="emoji"...>`)~~
    * ~~If a custom emoji is used, it has no unicode character, so~~ transparently pass through the colon-shorthand (i.e. `:smile:`)
1. Add a listener to `filter:activitypub.mocks.note`
    * `({ object, post })` is passed in. `object` is the mocked ActivityPub object, `post` is the result of `getPostSummaryByPids`
    * Add the following to `object.@context`: `{ "Emoji": "http://joinmastodon.org/ns#Emoji" }`
    * For each emoji detected (raw markdown found in `object.source.content`), append an object `{ id, type, name, icon }` to the `object.tag` array, where:
        * `id` is a unique identifier for the emoji (if you use a URL, I don't think it needs to resolve)
        * `type` is `Emoji`
        * `name` is the colon-shorthand, i.e. `:smile:`
        * `icon` is an object containing `type`, `mediaType`, and `url`, where
            * `type` is `Image`
            * `mediaType` is the emoji MIME type
            * `url` is a absolute URL to the emoji

----

(@julian) When content is received, replace the incoming shortcode with an image tag of the linked resource with the `emoji` class.

----

Acceptance tests:

* @pitaj 
    * [x] Mocked note with emoji returns `content` without parsed emoji (`:smile:` shortcode only, no `<img...>`)
    * [x] Mocked note contains `tag` element with emoji used in post with acceptable values
    * [x] Federated note to Mastodon (via activitypub.academy) correctly displays the emoji
* @julianlam 
    * [x] Federated NodeBB-to-NodeBB note with emoji correctly parsed and displayed.

**Comment by julianlam** [comment]
The current state is that `img` tags for each individual emoji are added to the parsed post content because NodeBB uses emoji packs and each install potentially uses different emoji (though most installs just use the default Android "blob" emoji).

When federated out via ActivityPub, recipient implementors could choose how to handle those img tags. Broadly, they fall into two categories:

1. The tags are stripped out (Mastodon and forks) and content sentiment provided by emoji is lost (if any)
2. The emoji are sent through with potentially incorrect sizing because the `emoji` class has no meaning outside of NodeBB.

The first change above would allow emoji to be sent out even if images are stripped and serves as a good fallback. The second change would allow NodeBB to send the proper image along as metadata for supporting implementations to optionally utilise.

**Comment by umarasf** [comment]
use remini apk for emojies editing. [https://reminigeek.com/](https://reminigeek.com/)

**Comment by julianlam** [comment]
@pitaj successfully implemented the above requirements under the `activitypub` branch of `nodebb-plugin-emoji`, thank you!

----

The following issues remain:

* [ ] [Open PR re: `@context` property update](https://github.com/NodeBB/nodebb-plugin-emoji/pull/67), needs review and merging
* [ ] `import('mime');` issue in compiled js (typescript config needs adjustment)
* [ ] `buildEmoji()` in `parse.js` exported and called in `nodebb-plugin-reactions`, which is not passing in required parameters post-refactor

**Comment by pitaj** [comment]
published `nodebb-plugin-emoji@6.0.0`

**Comment by julianlam** [comment]
```
TypeError: Cannot read private member from an object whose class did not declare it
    at __classPrivateFieldGet (file:///path/to/nodebb/node_modules/nodebb-plugin-emoji/node_modules/mime/dist/src/Mime.js:3:94)
    at getType (file:///path/to/nodebb/node_modules/nodebb-plugin-emoji/node_modules/mime/dist/src/Mime.js:53:16)
    at /path/to/nodebb/node_modules/nodebb-plugin-emoji/build/lib/parse.js:255:28                                                     
    at buildEmoji (/path/to/nodebb/node_modules/nodebb-plugin-emoji/build/lib/parse.js:78:5)
```

FYI

**Comment by pitaj** [comment]
`nodebb-plugin-emoji@6.0.1`

**Comment by almasdafer** [comment]
Hay varias aplicaciones que ofrecen servicios de chat y mensajería. [WhatsApp](https://www.whatsapp.com/) es la app más popular en todo el mundo y ofrece servicios ilimitados de chat, audio y videollamadas. Hay más de 4.000 millones de usuarios de WhatsApp en todo el mundo. WhatsApp ofrece muchas funciones, pero algunas de ellas son todavía limitadas. Por lo tanto, para evitar la dificultad de otras características premium, nuestro equipo ofrece una versión modificada de WhatsApp, a saber, WhatsApp Plus.
[https://whtspplus.com/](url)
