### ISSUE TITLE
Topic Synchronization via resolvable `context`

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12695]
Despite topic backfill being more performant and reliable compared to `inReplyTo` traversal, backfill can be relatively more resource intensive as a resolvable context needs to be repeatedly queried (page-by-page) in order to gather all objects or ids, and each object then needs to be de-referenced via a remote call to the object's origin server.

Topic synchronization could be a useful extension of #12647, so that once a context is backfilled, future context retrievals could skip backfill if there is nothing new.

Some technical aspects of this are lifted from [FEP-8fcf: Followers collection synchronization across servers](https://codeberg.org/fediverse/fep/src/branch/main/fep/8fcf/fep-8fcf.md).

### Caveat

**Context synchronization works only with publicly-available content**

Unlike FEP-8fcf, this proposal is much simpler. There is a single header (`ETag`) whose contents are only the calculated digest. There are no new endpoints with their associated logic. This is done on purpose because context synchronization intentionally deals with **publicly-available** content only, meaning the returned set of objects do not change depending on who the requester is.

### The Digest

A given context's collection of objects can be distilled into a digest for comparison purposes.

This digest is created by XORing together the individual SHA256 digests of each **publicly-available** context object id.

`contextDigest = SHA256(object1) XOR SHA256(object2) XOR ... XOR SHA256(objectN)`

*N.B. The use of exclusive-or allows for the order of objects to no longer be significant*

### The Response Header

When a context is queried, an `ETag` header is sent back alongside the response payload. That header's value will be the digest as outlined above.

The requester of a given context collection MAY elect to compare this value with their own independently calculated digest, and proceed with context backfill at their discretion.

[More information on `ETag`s](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)

### The Request Header

When responding to a request for a context collection (either the context itself or a page therein), the ActivityPub server may elect to check the `If-None-Match` header and compare that to the requested context's digest. If the values match, then a `304 Not Modified` status code can be sent.

Implementers sending this additional header can use the 304 response as a signal to skip context resolution as nothing has changed.

**Comment by aicuaboom** [comment]
auto touch click sharening wep all file all
