### ISSUE TITLE
Separate visibility setting for upvotes and downvotes

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/NodeBB#12698]
### Description

Currently we can only:
- Completely disable downvotes
- Completely hide the information about who voted, and hovering over the number of votes it says only "votes"

However, we want more flexibility, to separate the settings, so that it would be like this:
- [] Hide downvotes (But users can still vote down! But regular users will not be able to see *who* voted down)
- [] Upvotes are visible

Then we can set the downvotes to be hidden, but the upvotes to be fully visible (and other communities may want to set the opposite).

This is a forum with 24k users, so it is not a niche request. Previously this was possible with nodebb.

**Comment by barisusakli** [comment]
Right now we have the below setting which controls both upvotes and downvotes, I think splitting that into 2 makes sense.
![image](https://github.com/user-attachments/assets/d8eb1095-71ef-4be0-ab8e-256017eb492a)
