### ISSUE TITLE
Chat: Receiving user of a new room chat message doesnt show up in chat room list

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#12713]
### NodeBB version

v3.8.3

### Exact steps to cause this issue

1. Login in with two accounts in different browsers
2. Have one account send chat message in a new room to the other account (both sat on chat page/template)

### What you expected

New room should be added to room list (left of page)

### What happened instead

No room added

### Anything else?

I'm in middle of upgrading from v2 to v3 and noticed this. Not sure if this is an intended change as part of the chat improvement done in v3 or a regression issue.

**Comment by julianlam** [comment]
Was it working fine in v2?

I noticed something similar, in that the chat teaser doesn't update. Could be a related issue.

**Comment by uplift** [comment]
> Was it working fine in v2?
> 
> I noticed something similar, in that the chat teaser doesn't update. Could be a related issue.

Not at my machine with my setup but I think it was this block of code in v2.8.17. Not got to testing teaser but Ill have a check tomorrow and Ill take a look at @barisusakli changes.

https://github.com/NodeBB/NodeBB/blob/dc14d6a8d17e6b15dd8b8958b7bd4d967cf4c8da/public/src/client/chats.js#L476-L487

**Comment by uplift** [comment]
@barisusakli @julianlam 

So for my own understanding what is the difference between event:chats.receive and event:new_notification (with type new-chat). Is the chats.receive only for use when you have a chat active/open?

If the chat room/user has 'no notifications' set then as far as I can see the recent chats/teasers arent updated using event:new_notification. Should I raise this as a separate bug?

**Comment by barisusakli** [comment]
`event:chats.receive` is only send to users that have the chat open already. So the only other way to know about a new chat message if you are don't have the chat open is `event:new_notification`. 

If you disable chat notifications then you won't know about new chat messages.

**Comment by uplift** [comment]
Thanks for clarifying. 

So I guess the question is should the recent chat update even with 'no notifications' set as the user wont know messages exist till a page refresh/navigation? From a user POV seems that 'no notifications' means don't show in notification bar/popup toasts rather than not show chat at all.

**Comment by barisusakli** [comment]
@uplift see  above commit, I changed the event used from `event:new_notification` to `event:unread.updateChatCount`, which is always sent to mark the chat unread on the chats page, it also sends the teaser of the message now so it can be updated on the client side.

**Comment by uplift** [comment]
@barisusakli Apologies for slow response, I've been away. Your latest changes now update the teaser which is great but only for chat rooms that already exist in the recent rooms list. Should it add a new room to the recent list like in v2?

**Comment by barisusakli** [comment]
It should already add a new room to the list when the other side sends a message. That's when `event:unread.updateChatCount` is sent.

**Comment by barisusakli** [comment]
@uplift no worries 👍🏼
