### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by emzi** [NodeBB/NodeBB#1278]
0.
http://localhost:4567/admin => Is there any program to translate the dashboard?
# Screenshots:

1.
![notifications_tr](https://cloud.githubusercontent.com/assets/1899175/2534211/74a71748-b576-11e3-804d-99853aaf5a82.png)

2.
![InvalidPassword_tr](https://cloud.githubusercontent.com/assets/1899175/2534279/23fdadfa-b578-11e3-8274-aa485997715b.png)

3.
![CurrentPassword_tr](https://cloud.githubusercontent.com/assets/1899175/2534244/3764db4e-b577-11e3-96dc-3078acf8fca6.png)

4.
Repeated phrase on Transifex trunk?!
![Duplicated-Phrases](https://cloud.githubusercontent.com/assets/1899175/2534549/10772040-b57d-11e3-9906-bdcbc7c4293e.png)

**Comment by MohammadZokaie** [comment]
`Groups` is not translated while [it's on Transifex](https://www.transifex.com/projects/p/nodebb/translate/#fa_IR/$?q=Groups)!

![transifex2015](https://cloud.githubusercontent.com/assets/1899175/7630845/fc3541de-fa4f-11e4-864b-7f56c2a5c662.png)
