### ISSUE TITLE
Empty menu when editing message

### ISSUE THREAD

**Issue by aworobel** [NodeBB/NodeBB#12785]
### NodeBB version

3.8.4

### NodeJS version

v20.16.0

### Installed NodeBB plugins

        * nodebb-plugin-adsense@4.0.1 (installed, enabled)
        * nodebb-plugin-composer-default@10.2.36 (installed, enabled)
        * nodebb-plugin-custom-pages@2.1.0 (installed, enabled)
        * nodebb-plugin-dbsearch@6.2.5 (installed, enabled)
        * nodebb-plugin-emoji@5.1.15 (installed, enabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
        * nodebb-plugin-google-analytics@1.1.0 (installed, enabled)
        * nodebb-plugin-gravatar@4.0.0 (installed, enabled)
        * nodebb-plugin-imgur@4.1.0 (installed, enabled)
        * nodebb-plugin-markdown@12.2.6 (installed, enabled)
        * nodebb-plugin-mentions@4.4.3 (installed, enabled)
        * nodebb-plugin-newsletter@0.11.1 (installed, enabled)
        * nodebb-plugin-ntfy@1.7.4 (installed, enabled)
        * nodebb-plugin-poll@3.2.3 (installed, enabled)
        * nodebb-plugin-question-and-answer@1.2.7 (installed, enabled)
        * nodebb-plugin-soundpack-default@3.0.1 (installed, enabled)
        * nodebb-plugin-spam-be-gone@2.2.2 (installed, enabled)
        * nodebb-rewards-essentials@1.0.0 (installed, enabled)
        * nodebb-theme-harmony@1.2.63 (installed, enabled)
        * nodebb-theme-lavender@7.1.8 (installed, disabled)
        * nodebb-theme-peace@2.2.6 (installed, disabled)
        * nodebb-theme-persona@13.3.25 (installed, disabled)
        * nodebb-widget-essentials@7.0.18 (installed, enabled)

### Database type

MongoDB, Redis

### Database version

mongo : v7.0.5, redis : v7.4.0

### Exact steps to cause this issue

Hello,

When i try to edit a message, there is a little bubble without any links inside.
Don't know when it appears.
Nothing in the logs server (nginx, nodebb), nothing in the web console browser, so very difficult for me to debug.

### What you expected

Need to get the orignal menu when you click on the "..." close to the message

![debug](https://github.com/user-attachments/assets/d28187c1-e261-4d1e-bbe3-bcbe22a96ae7)

### What happened instead

The menu is empty, tried various browser mobile or desktop has the same problem.

### Anything else?

Thanks :)

**Comment by julianlam** [comment]
Can you let us know if you see any errors in the browser dev console?

**Comment by aworobel** [comment]
Hello,

No error neither in web console browser (it was the first place i checked
because i though it was a JavaScript error) neither in th nginx logs or
nodebb logs :/


Arnaud.

Le mar. 10 sept. 2024, 22:33, Julian Lam ***@***.***> a
écrit :

**Comment by barisusakli** [comment]
Take a look at the websocket messages in your browser console, when you click the three dots it should load some data to display that dropdown. Do you see the data returned?

![image](https://github.com/user-attachments/assets/019c4f8a-abc3-4799-9b21-736a931a5f47)

**Comment by aworobel** [comment]
Hello @barisusakli,

Thanks for your answer, but i found nothing in message , the socket.io message is only on page load, nothing more when i click on the dot :/
![image](https://github.com/user-attachments/assets/9cd404dc-72e8-42ee-b589-b932fdb5e16f)

**Comment by barisusakli** [comment]
When I load your forum I can see bunch of errors on the browser console one of them is the socket.io connection.

![image](https://github.com/user-attachments/assets/b10d30ff-1a22-4562-8551-d61028957984)


Without that working you won't see the post tools menu.

**Comment by aworobel** [comment]
Hello,

I didn't find anything interesting and can't reproduce the websocket error you get @barisusakli 
I have this one too that blocks the loading of the plugin list. i don't know if it has a link with the initial problem.

`2024-09-12T09:53:33.858Z [4501/461] - error: Error loading https://packages.nodebb.org/api/v1/plugins [[error:unable-to-load-plugins-from-nbbpm]] {"stack":"Error: [[error:unable-to-load-plugins-from-nbbpm]]\n    at Plugins.list (/usr/src/app/src/plugins/index.js:174:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getPlugins (/usr/src/app/src/controllers/admin/plugins.js:63:23)\n    at async getAllPlugins (/usr/src/app/src/controllers/admin/plugins.js:58:9)\n    at async Promise.all (index 1)"`

**Comment by aworobel** [comment]
Hello,

Finally got it !
I don't know why it worked before :
So here is the problem 

In my docker compose i had a volume mounted like this :
     - static:/usr/src/app/public
 i changed to : 
     - static:/usr/src/app/public/uploads

It was an otpimization with shared module to provide the static contect with nginx. 
As it does not work i need to delete this optimization in my nginx docker compose : 

        **- nodebb-static:/usr/share/nginx/html/nodebb_static/public** <--- deleted
        - nodebb-build:/usr/share/nginx/html/nodebb_static/build
        - /etc/localtime:/etc/localtime:ro
        - ./logs:/var/log/nginx
        environment:
            - NGINX_PORT=80
        networks:
           - web

networks:
   web:
      name: web
      external: true

volumes:
   conf:
   logs:
   html:
   nodebb-static:
      external: true
      name: nodebb_static
   nodebb-build:
      external: true
      name: nodebb_build
