### ISSUE TITLE
Locking all users views by funny characters in user profile

### ISSUE THREAD

**Issue by paboum** [NodeBB/NodeBB#12786]
### NodeBB version

v3.8.4

### NodeBB git hash

4833f9a63e661cc88006f110c2b3df063d59f500

### NodeJS version

v22.7.0

### Installed NodeBB plugins

```
	* @nodebb/nodebb-plugin-topic-ratings@1.0.5 (installed, enabled)
	* @nodebb/nodebb-plugin-user-level@2.1.2 (installed, disabled)
	* nodebb-plugin-2factor@7.5.3 (installed, enabled)
	* nodebb-plugin-browsing-users@4.0.1 (installed, enabled)
	* nodebb-plugin-composer-default@10.2.36 (installed, enabled)
	* nodebb-plugin-dbsearch@6.2.5 (installed, disabled)
	* nodebb-plugin-emoji@5.1.15 (installed, enabled)
	* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
	* nodebb-plugin-glossary@1.1.0 (installed, enabled)
	* nodebb-plugin-markdown@12.2.6 (installed, enabled)
	* nodebb-plugin-mentions@4.4.3 (installed, enabled)
	* nodebb-plugin-ntfy@1.7.4 (installed, disabled)
	* nodebb-plugin-poll@3.2.3 (installed, enabled)
	* nodebb-plugin-question-and-answer@1.2.7 (installed, enabled)
	* nodebb-plugin-spam-be-gone@2.2.2 (installed, enabled)
	* nodebb-rewards-essentials@1.0.0 (installed, enabled)
	* nodebb-theme-harmony@1.2.63 (installed, enabled)
	* nodebb-theme-lavender@7.1.8 (installed, disabled)
	* nodebb-theme-peace@2.2.6 (installed, disabled)
	* nodebb-theme-persona@13.3.25 (installed, disabled)
	* nodebb-widget-essentials@7.0.18 (installed, enabled)
```

### Database type

MongoDB

### Database version

v7.0.14

### Exact steps to cause this issue

Not really sure what I did, but:
1. Created a new user account, random password generated by browser `}Z5SViuSs^k78dc` (might be important due to heading `}`)
2. Logged in, got to profile editing
3. Filled out name, some non-URL string (letters only) in webpage, some city, some birthday, some regular text in "about me"
4. Inserted a complicated signature with chars like `:`, `|`, `@`
5. Tried to save changes but got error `Invalid UTF-8 string in BSON document`
6. Did try to save a few more times, omitting some fields and replacing `|`s with `#`s

### What you expected

Board to operate normally.

### What happened instead

From this account's session all I got from now on, were internal server errors, 500 or 503, don't remember.
From admin account's session started getting internal errors everywhere where culprit account would be listed: `users`, `admin/dashboard/users`, `admin/manage/users`, no way to delete that account, `Invalid UTF-8 string in BSON document` everywhere.
Tried restarting nodebb, no luck.
Had to enter mongo shell, find the culprit's ID:
`db.objects.find({_key:"username:sorted", value: {$regex: /{{culprit}}/}});`
And then remove all related stuff:
`db.objects.remove({value: "{{ID}}"});`
In fact, I first removed some objects by known keys (like `username:sorted`) which led to the state in which everything worked fine except `admin/manage/registration`. I turned switched Registration Approval Type back from `Admin Approval for IPs` to `Normal` as this may be causing the whole thing.

### Anything else?

Tried reproducing the same on https://try.nodebb.org/ but with no luck, possibly it's missing the key plugin or setting?
Didn't try nor want to reproduce it on my instance.

All fields and characters I described should be sanitized. This is too important of an issue to simply ignore it due to lack of my full test logs or even exact reproduction steps. You need to find this and fix this, as someone could just break random boards with this.

Edit: Oh, and my locale is pl

**Comment by paboum** [comment]
In fact, instead of sanitizing user input prior to saving in db, it could also just help to ignore incorrect entries in db while listing them, instead of crashing the whole app. So this bug report is actually helping you fix two faulty parts of code at the price of one.

**Comment by barisusakli** [comment]
I couldn't reproduce with your steps, do you have the string you used to cause the initial utf error? You can send it to baris@nodebb.org if you don't want to post here.

**Comment by julianlam** [comment]
Added the needs more info tag. If you cannot provide a working string this issue will close in 14 days, otherwise the issue is far too vague.

**Comment by paboum** [comment]
Of course you can reproduce half of the issue by manually updating test database with incorrect UTF-8 characters in any user profile field and observing why it causes 503 errors while admin tries to delete that account fron his panel.

The other half will be discovered by hackers just via analysing your code for vulnerabilities like JSON injection, you will learn the exact string from the media.

**Comment by paboum** [comment]
Apparently this may be an internal MongoDB issue:
https://www.mongodb.com/community/forums/t/error-invalid-utf-8-string-in-bson-document-after-rebuild-on-windows/293410

After you confirm this, the only question is if NodeBB can mitigate this - if db returns errors instead of some entries, shouldn't the whole admin panel simply ignore these errors instead of crashing.
