### ISSUE TITLE
RTLing

### ISSUE THREAD

**Issue by emzi** [NodeBB/NodeBB#1279]
# Screenshots

![0](https://cloud.githubusercontent.com/assets/1899175/2534352/c7dd74c2-b579-11e3-915f-0d001b2de9e9.png)

![1](https://cloud.githubusercontent.com/assets/1899175/2534353/ccec7260-b579-11e3-9a1b-c37a841776a8.png)

![2](https://cloud.githubusercontent.com/assets/1899175/2534354/d2a8e24c-b579-11e3-8319-be8c64ffb0cb.png)

![3](https://cloud.githubusercontent.com/assets/1899175/2534401/b27c67fe-b57a-11e3-8cc0-81115f433881.png)

![5](https://cloud.githubusercontent.com/assets/1899175/2534380/5ef5b7e8-b57a-11e3-9db8-fb86672c679b.png)

@akhoury

**Comment by MohammadZokaie** [comment]
Here are some more:
![2015-05-14--1431599844_1893x306_scrot](https://cloud.githubusercontent.com/assets/1899175/7630677/b9834acc-fa4d-11e4-9dfe-d8bdcaf4be88.png)
