### ISSUE TITLE
Unable to start nodebb Server

### ISSUE THREAD

**Issue by Chouhan171** [NodeBB/NodeBB#12793]
### Exact steps to cause this issue

Clone the repo master verison , it will get you following error 
![image](https://github.com/user-attachments/assets/4cc7ef74-6d31-444f-80e3-164590cc941e)

### What you expected

Should start the nodebb server , Even tried with installing the compose plugin as well . b

**Comment by barisusakli** [comment]
Make sure you have nodebb-plugin-composer-default active and try rebuilding.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/20fd75bf76b2d31b75fabd8e15de093b08a1c37f
