### ISSUE TITLE
NodeBB start to crash with 30k topics

### ISSUE THREAD

**Issue by duyanhstar** [NodeBB/NodeBB#12833]
### NodeBB version

v3.10.0

### NodeBB git hash

b60a9b4e6f38bc04afa4e16a9e2cb2c26ab773bf

### NodeJS version

v20.15.1

### Installed NodeBB plugins

Active plugins:
        * nodebb-plugin-2factor@7.5.5 (installed, disabled)
        * nodebb-plugin-composer-default@10.2.39 (installed, enabled)
        * nodebb-plugin-config-home-page@1.0.0 (installed, disabled)
        * nodebb-plugin-dbsearch@6.2.5 (installed, disabled)
        * nodebb-plugin-emoji@5.1.15 (installed, enabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
        * nodebb-plugin-import-json@1.0.0 (installed, enabled)
        * nodebb-plugin-iocodes-iframe@1.0.0 (installed, enabled)
        * nodebb-plugin-iocodes-mn-streamurl-player@1.0.0 (installed, enabled)
        * nodebb-plugin-markdown@12.2.8 (installed, enabled)
        * nodebb-plugin-mentions@4.4.3 (installed, enabled)
        * nodebb-plugin-ntfy@1.7.7 (installed, disabled)
        * nodebb-plugin-spam-be-gone@2.2.2 (installed, disabled)
        * nodebb-plugin-torrent-topic@1.0.0 (installed, enabled)
        * nodebb-plugin-type-category@1.0.0 (installed, enabled)
        * nodebb-rewards-essentials@1.0.0 (installed, enabled)
        * nodebb-theme-harmony@1.2.71 (installed, enabled)
        * nodebb-theme-lavender@7.1.8 (installed, disabled)
        * nodebb-theme-peace@2.2.7 (installed, disabled)
        * nodebb-theme-persona@13.3.37 (installed, disabled)
        * nodebb-widget-essentials@7.0.29 (installed, enabled)

### Database type

MongoDB

### Database version

6.0.18

### Exact steps to cause this issue

1. I use my plugin for converting WP to NodeBB.
2. Everything are fine when i just convert 30k topics ( POST from WP)
3. Starting problem when i get over 32k or 36k topics, site load very slow and get 503 error.
4. I test in my dedicate server with 48C/96T - 128GB RAM and Only me visit website ( NO have traffic)

### What you expected

i hope you have solution for solving this case, becuz i love NodeBB, i want to replace WP by NodeBB

### NodeBB have a big problem when access to https://*.nodebb.org/api/v1/plugins 
This service is not stable: https://*.nodebb.org/api/v1/plugins

```
024-10-04T10:39:02.444Z [4567/57590] - error: Error loading https://packages.nodebb.org/api/v1/plugins?version=3.10.0 [[error:unable-to-load-plugins-from-nbbpm]] {"stack":"Error: [[error:unable-to-load-plugins-from-nbbpm]]\n    at Plugins.list (/home/nodebb/src/plugins/index.js:176:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getPlugins (/home/nodebb/src/controllers/admin/plugins.js:63:23)\n    at async getCompatiblePlugins (/home/nodebb/src/controllers/admin/plugins.js:54:9)\n    at async Promise.all (index 0)\n    at async pluginsController.get (/home/nodebb/src/controllers/admin/plugins.js:11:38)\n    at async /home/nodebb/src/routes/helpers.js:80:5"}
{
  ok: false,
  status: 526,
  statusCode: 526,
  statusText: '',
  headers: {
    'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
    'cf-ray': '8cd48c6d6a4adca0-FRA',
    connection: 'keep-alive',
    'content-length': '7111',
    'content-type': 'text/html; charset=UTF-8',
    date: 'Fri, 04 Oct 2024 10:39:31 GMT',
    expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    'referrer-policy': 'same-origin',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=XJrfmRv2fG1aJKwHwAYglZXw%2F0J6w3ZJolXHQWvaBfD1%2B8vsrdVLGMnNu%2BziH4BnXHdSTSkTVv8NH3DUwyRkvrqcADSxyRDEDnNdFKKR%2B42rUbHkyLvhibqjUkJaxmOA9GylLn%2FN"}],"group":"cf-nel","max_age":604800}',
    server: 'cloudflare',
    'x-frame-options': 'SAMEORIGIN'
  }
}
```

**Comment by barisusakli** [comment]
What is the output of `db.objects.stats()` in your mongodb database?

**Comment by duyanhstar** [comment]
I don’t see any log on ./nodebb log

So hard when i try to find the problem

*Duy Anh Le (Mr.)*
*Product Development and Optimization*
*iOCodes.com - Solutions for online product to wonderful*
*What's app/M/Telegram:* (+84) 909 023 668  *Skype: *duyanh_star007
*Website*: www.iocodes.com <https://iocodes.com/>


Vào Th 6, 4 thg 10, 2024 lúc 20:05 Barış Soner Uşaklı <
***@***.***> đã viết:

**Comment by duyanhstar** [comment]
> What is the output of `db.objects.stats()` in your mongodb database?

This is information:
`
{
    "ns" : "nodebb.objects",
    "size" : 137902338,
    "count" : 1310823,
    "avgObjSize" : 105,
    "numOrphanDocs" : 0,
    "storageSize" : 76955648,
    "freeStorageSize" : 18837504,
    "capped" : false,
    "wiredTiger" : {
        "metadata" : {
            "formatVersion" : 1
        },
        "creationString" : "access_pattern_hint=none,allocation_size=4KB,app_metadata=(formatVersion=1),assert=(commit_timestamp=none,durable_timestamp=none,read_timestamp=none,write_timestamp=on),block_allocation=best,block_compressor=snappy,cache_resident=false,checksum=on,colgroups=,collator=,columns=,dictionary=0,encryption=(keyid=,name=),exclusive=false,extractor=,format=btree,huffman_key=,huffman_value=,ignore_in_memory_cache_size=false,immutable=false,import=(compare_timestamp=oldest_timestamp,enabled=false,file_metadata=,metadata_file=,repair=false),internal_item_max=0,internal_key_max=0,internal_key_truncate=true,internal_page_max=4KB,key_format=q,key_gap=10,leaf_item_max=0,leaf_key_max=0,leaf_page_max=32KB,leaf_value_max=64MB,log=(enabled=true),lsm=(auto_throttle=true,bloom=true,bloom_bit_count=16,bloom_config=,bloom_hash_count=8,bloom_oldest=false,chunk_count_limit=0,chunk_max=5GB,chunk_size=10MB,merge_custom=(prefix=,start_generation=0,suffix=),merge_max=15,merge_min=0),memory_page_image_max=0,memory_page_max=10m,os_cache_dirty_max=0,os_cache_max=0,prefix_compression=false,prefix_compression_min=4,source=,split_deepen_min_child=0,split_deepen_per_child=0,split_pct=90,tiered_storage=(auth_token=,bucket=,bucket_prefix=,cache_directory=,local_retention=300,name=,object_target_size=0),type=file,value_format=u,verbose=[write_timestamp],write_timestamp_usage=none",
        "type" : "file",
        "uri" : "statistics:table:collection-0--8766218406389098767",
        "LSM" : {
            "bloom filter false positives" : 0,
            "bloom filter hits" : 0,
            "bloom filter misses" : 0,
            "bloom filter pages evicted from cache" : 0,
            "bloom filter pages read into cache" : 0,
            "bloom filters in the LSM tree" : 0,
            "chunks in the LSM tree" : 0,
            "highest merge generation in the LSM tree" : 0,
            "queries that could have benefited from a Bloom filter that did not exist" : 0,
            "sleep for LSM checkpoint throttle" : 0,
            "sleep for LSM merge throttle" : 0,
            "total size of bloom filters" : 0
        },
        "autocommit" : {
            "retries for readonly operations" : 0,
            "retries for update operations" : 0
        },
        "block-manager" : {
            "allocations requiring file extension" : 7292,
            "blocks allocated" : 304179,
            "blocks freed" : 298017,
            "checkpoint size" : 58101760,
            "file allocation unit size" : 4096,
            "file bytes available for reuse" : 18837504,
            "file magic number" : 120897,
            "file major version number" : 1,
            "file size in bytes" : 76955648,
            "minor version number" : 0
        },
        "btree" : {
            "btree checkpoint generation" : 1407,
            "btree clean tree checkpoint expiration time" : 0,
            "btree compact pages reviewed" : 0,
            "btree compact pages rewritten" : 0,
            "btree compact pages skipped" : 0,
            "btree skipped by compaction as process would not reduce size" : 0,
            "column-store fixed-size leaf pages" : 0,
            "column-store fixed-size time windows" : 0,
            "column-store internal pages" : 0,
            "column-store variable-size RLE encoded values" : 0,
            "column-store variable-size deleted values" : 0,
            "column-store variable-size leaf pages" : 0,
            "fixed-record size" : 0,
            "maximum internal page size" : 4096,
            "maximum leaf page key size" : 2867,
            "maximum leaf page size" : 32768,
            "maximum leaf page value size" : 67108864,
            "maximum tree depth" : 4,
            "number of key/value pairs" : 0,

`

I have attack full information
[data.json](https://github.com/user-attachments/files/17265148/data.json)

**Comment by barisusakli** [comment]
What is the output you get when you stop nodebb and start it with `node app.js` ? Any errors?

**Comment by duyanhstar** [comment]
> What is the output you get when you stop nodebb and start it with `node app.js` ? Any errors?

i think problem from session when i login.
My test case:
1. Don't login: site load fast.
2. Login with admin user: loading a long time. I can't load anything>
3. Delete session in MongoDB, site load fast.

**Comment by barisusakli** [comment]
You should post any errors from your nodebb logs when you login with an admin user. Does it happen with regular users or just a single admin user?

**Comment by barisusakli** [comment]
You should also disable your custom plugins and see if they are causing the issue.

The below plugins are not bundled with nodebb.

```

* nodebb-plugin-config-home-page@1.0.0 (installed, disabled)
* nodebb-plugin-import-json@1.0.0 (installed, enabled)
* nodebb-plugin-iocodes-iframe@1.0.0 (installed, enabled)
* nodebb-plugin-iocodes-mn-streamurl-player@1.0.0 (installed, enabled)
* nodebb-plugin-torrent-topic@1.0.0 (installed, enabled)
* nodebb-plugin-type-category@1.0.0 (installed, enabled)
```

**Comment by duyanhstar** [comment]
> You should post any errors from your nodebb logs when you login with an admin user. Does it happen with regular users or just a single admin user?

The important, i sent all logs. Nothing more.



> You should also disable your custom plugins and see if they are causing the issue.
> 
> The below plugins are not bundled with nodebb.

Yes, i did! and get same problem. I run with: node app.js

MongoDB version: 8.0.1

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/f53f1394bd9bce44149674049fcf66a30376aeee
