### ISSUE TITLE
[AP][Federation] Posts with an existing `context` but no `inReplyTo` end up forking the thread, not attached to existing one

### ISSUE THREAD

**Issue by trwnh** [NodeBB/NodeBB#12835]
### NodeBB version

Whatever's running on community.nodebb.org

### Exact steps to cause this issue

1. Deliver an activity where the object has a `context` but no `inReplyTo`:

https://browser.pub/https://mastodon.social/@erincandescent@erincandescent.net/113250700052546021

### What you expected

The post should be attached to the thread represented by the existing `context`

### What happened instead

The post is attached to a new thread which doesn't match the existing `context`

**Comment by julianlam** [comment]
Agreed, this is a bug in the context resolution handler. Given a resolvable context it should've added the conversation to the existing topic.

Will have to retrace and see what happened. It feels like the context didn't resolve and when it encountered no inReplyTo, it created a new topic.

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/d451adafc4edf832216fb2df2d6a99982b5bb501

**Comment by julianlam** [comment]
Was just a straight up bug that caused context resolution to always return empty.
