### ISSUE TITLE
Unable to finish installing NodeBB

### ISSUE THREAD

**Issue by lorimode** [NodeBB/NodeBB#12845]
### NodeBB version

v3.9.0

### NodeBB git hash

b60a9b4e6f38bc04afa4e16a9e2cb2c26ab773bf

### NodeJS version

v18.20.4

### Installed NodeBB plugins

/

### Database type

MongoDB

### Database version

v5.0.26

### Exact steps to cause this issue

1 ) git clone -b v3.x https://github.com/NodeBB/NodeBB.git nodebb
cd nodebb
2 ) ./nodebb setup
3 ) fill in database information, create config.json
4 ) the rest bug and error `Error: write EPIPE
    at target._send (node:internal/child_process:872:20)
    at target.send (node:internal/child_process:745:19)
    at process.<anonymous> (/usr/home/****/*/domains/**************/nodebb/src/meta/minifier.js:118:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on process instance at:
    at node:internal/child_process:876:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}`
Arrived...

### What you expected

Let the installation finish

### What happened instead

`Error: write EPIPE
    at target._send (node:internal/child_process:872:20)
    at target.send (node:internal/child_process:745:19)
    at process.<anonymous> (/usr/home/****/*/domains/**************/nodebb/src/meta/minifier.js:118:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on process instance at:
    at node:internal/child_process:876:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}`

**Comment by lorimode** [comment]
Hello
Any opinions on this problem?

**Comment by barisusakli** [comment]
Couple things to check.
1. Make sure you are using a non privileged user and that user has write permissions to the nodebb folder
2. Make sure there is enough disk space
3. Make sure there is enough ram

**Comment by lorimode** [comment]
> Couple things to check.
>     2. Make sure there is enough disk space

Because how much storage space is needed (normally, I have enough) ?

**Comment by barisusakli** [comment]
Make sure you have at least 1gb and setup some swap for spikes

**Comment by lorimode** [comment]
Hello again
This is not due to resources, several tests have been done, even with 128GB of RAM, still the same problem...

Could you see how to resolve this ?

**Comment by lorimode** [comment]
Good morning
Did you receive my message? As it is no longer in the open topic, I wonder if it reached you...

**Comment by barisusakli** [comment]
Did you check if you are using a nonprivileged user to  run the commands and that user owns the nodebb directory? Otherwise try on a clean ubuntu install and see if it works.

**Comment by lorimode** [comment]
Small clarification: It's on FreeBSD that I have the error...

**Comment by lorimode** [comment]
J'ai suivi c'est instructions : [https://docs.nodebb.org/installing/os/freebsd/](https://docs.nodebb.org/installing/os/freebsd/ )...
