### ISSUE TITLE
Error: Cannot find module 'wrap-ansi' after upgrade

### ISSUE THREAD

**Issue by arkabase** [NodeBB/NodeBB#12885]
### NodeBB version

v3.10.3

### NodeBB git hash

025ffe03297aea1660178960fe79ce3c1a38cb86

### NodeJS version

v20.9.0

### Installed NodeBB plugins

can't retrieve plugin list because ./nodebb crashes with the reported error

### Database type

MongoDB

### Database version

v7.0.15

### Exact steps to cause this issue

```
./nodebb stop
git fetch
git reset --hard v3.10.3
./nodebb upgrade
```

### What you expected

upgrade completes with success

### What happened instead

```
Error: Cannot find module 'wrap-ansi'
Require stack:
- /.../nodebb/node_modules/cliui/build/index.cjs
- /.../nodebb/node_modules/yargs/build/index.cjs
- /.../nodebb/node_modules/yargs/index.cjs
- /.../nodebb/src/cli/index.js
- /.../nodebb/nodebb
```

### Anything else?

Is there a simple way to downgrade to last working version ?

**Comment by barisusakli** [comment]
Before downgrading try running `npm install` in the nodebb directory and see if it works.
