### ISSUE TITLE
context collection is incorrectly represented as OrderedCollectionPage

### ISSUE THREAD

**Issue by trwnh** [NodeBB/NodeBB#12893]
### Exact steps to cause this issue

https://browser.pub/https%3A%2F%2Fcommunity.nodebb.org%2Ftopic%2F18364

### What you expected

The type should be OrderedCollection

### What happened instead

The type is instead OrderedCollectionPage

**Comment by julianlam** [comment]
.. and here I thought I'd fly under the radar until I eventually got around to fixing this... :smile:
