### ISSUE TITLE
A requirement for webhooks

### ISSUE THREAD

**Issue by wzyxdwll** [NodeBB/NodeBB#12903]
### Description

Currently, nodeBB doesn't seem to have an official webhook capability. For example, when I @ someone on a post, I need to notify that person on my IM. The plugins I found are relatively old and may not support the latest version. Is it currently only possible to solve this need through plugins? Is it possible to consider officially launching a webhook plugin or capability in the future?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-webhooks is the official plugin, let us know if you run into any issues using it.

**Comment by wzyxdwll** [comment]
Thank you very much
