### ISSUE TITLE
Notification dropdown tap target too small

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12927]
![image](https://github.com/user-attachments/assets/b7bd3af7-653b-40af-8784-7893dd65637f)

Especially on mobile it is easy to "miss" the button and toggle the scroll bar instead, causing the notification to scroll out of view.

**Recommended remediation**

1. Move "mark (un)read" indicator/button further out from right edge, or
2. Move indicator/button to left side of notification

**Comment by barisusakli** [comment]
err no repro 
![image](https://github.com/user-attachments/assets/7daa6e60-be94-4138-8c02-a813a32f6117)
