### ISSUE TITLE
Remove file-upload from chat if maximum file size is 0

### ISSUE THREAD

**Issue by gunnarvelle** [NodeBB/NodeBB#12926]
### Description

If you set maximum file size to be 0 in settings, the possibillity to upload files in posts disappear. But the possibility remains in chat, making it seem you can upoad files but then get an error message when you click sumbit.

The best solution here would be to hide the file-upload from chat if file size is set to 0.

**Comment by barisusakli** [comment]
When I set file size to 0 the composer still shows the upload buttons and you get an error when you try to upload. So it seems both chat and topics have the same issue.

![image](https://github.com/user-attachments/assets/430b61e1-15e6-45db-80f3-7e00398a1133)
