### ISSUE TITLE
Emoji plugin does not properly handle emoji in private messages

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12947]
This is likely a result of me also firing `filter:activitypub.mocks.note` (of which plugin-emoji has a listener for) for private notes, but passing the `messageObj` into `post` instead of... you know.. a post object.

**Comment by pibilo** [comment]
Find premium call girls in Manali on Pibilo. Find call girls and top escort services for adult entertainment.

[Manali Call Girls](https://in.pibilo.com/escorts/manali)
[Mapusa Call Girls](https://in.pibilo.com/escorts/mapusa)
[Mehsana Call Girls](https://in.pibilo.com/escorts/mehsana)
[Morbi Call Girls](https://in.pibilo.com/escorts/morbi)
[Murshidabad Call Girls](https://in.pibilo.com/escorts/murshidabad)

**Comment by julianlam** [comment]
It actually does handle it properly. Mastodon (which I was testing against) doesn't handle emoji, of course.
