### ISSUE TITLE
More consistent usage of full name if enabled in settings.

### ISSUE THREAD

**Issue by gunnarvelle** [NodeBB/NodeBB#12945]
### Description

If enabled in the settings, nodebb should use full name instead of username where possible.

* In email digests, both the name of the receiver and in the links to the posts.
* In chats, both in the chat-list, the userlist per chat and the chat header.
* It should also be used in links to user when replying to posts.

**Comment by barisusakli** [comment]
@gunnarvelle can you provide a screenshot for `It should also be used in links to user when replying to posts.` 

Mentions plugin has a setting for fullname so it displays  the fullname in the dropdown, but the post will still have `@username` AFAIK.

![image](https://github.com/user-attachments/assets/7e5760fa-ec91-409e-aad9-8b03a96685c7)

![image](https://github.com/user-attachments/assets/c78bef18-6870-48bc-8133-e8a2addc8213)
