### ISSUE TITLE
add some missing canonical tags

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#12961]
from https://community.nodebb.org/topic/18467/user-group-tag-and-more-pages-do-not-have-canonical-url

**Comment by reederz** [comment]
@barisusakli thanks for helping with this. Just one comment: I noticed that you used `req.url` to construct canonical URLs in some places. Won't `req.url` return URL that includes query string? It's important that canonical URLs don't contain query strings.

In fact, I noticed that og:url meta also has a problem with query string being included.
