### ISSUE TITLE
BridgyFed integration

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#12972]
Received reports that actor assertion or activities from bridgyfed accounts were not working

**Comment by julianlam** [comment]
Seems to be working, awaiting confirmation of successful message receipt from @wakest

**Comment by julianlam** [comment]
Confirmed working. BridgyFed will capture responses to and from BlueSky but bsky won't continue a conversation chain unless it already knows about it.

**Comment by wakest** [comment]
Wooohhh! glad to see this marked off as working now!
