### ISSUE TITLE
How to show image thumbnails in the list page of topics 

### ISSUE THREAD

**Issue by Vander-Bilt** [NodeBB/NodeBB#12978]
### NodeBB version

V3.11

### NodeJS version

V20

### Exact steps to cause this issue

For example, I write a post, upload 3 images. What I expected is their thumbnails are automatically shown up on the list page of topics.
Please take a look below diagram.

I made some tries modifying the template file topics_list.tpl, as result only that "123" text shown up.  No any post content like image shown up.

```
<div class="content text-break" component="post/content" itemprop="text">
   {posts.content} 123
</div>
```

### What you expected

![image](https://github.com/user-attachments/assets/020fa3cd-fccb-4ce3-8e38-949544e1a4ca)

**Comment by julianlam** [comment]
Right now only topic thumbnails show up, but any uploaded image assets are not. It would be a good idea to automatically include those uploaded assets in the topic thumbnail listing as well, so they show up in the topic list.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/cc65214de93294e596689a5a07c98f0e6186dd15
