### ISSUE TITLE
The iframly plugin no longer works for me

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#12985]
### NodeBB version

v3.12.0

### NodeBB git hash

b4ec3a6a40

### NodeJS version

v20.18.1

### Installed NodeBB plugins

iframly

### Database type

MongoDB

### Exact steps to cause this issue

The iframly plugin no longer works for me after updating to version 3.12. I'm not sure since which version it no longer provides a preview. Only the link in the message is displayed. I think that some time ago there was also a Settings button for the plugin, but now you can only activate/deactivate it. How can I determine if the problem is with nodebb or iframly itself. iframly runs as a service on its default port and does not give an error in the journal.

**Comment by barisusakli** [comment]
@awunnenb are you able to load the plugin page in the ACP? I justed tested the latest version of the plugin on my local and seems to work so, I am using it with an api key though, try it like that see if it makes a difference.

**Comment by awunnenb** [comment]
I think there is no plugin config page for iframely. It is not listed on the main page of the ACP under Plugins. If I go to the “Advanced” page, it is listed there but only with the option activate / deactivate.

**Comment by barisusakli** [comment]
iframely definitely has a plugin page, see below

![image](https://github.com/user-attachments/assets/40f02a32-0529-4bba-ab37-eb0084c20f9e)

**Comment by awunnenb** [comment]
For me, it is not listed directly under Plugins. Only under Advanced/Plugins. There it says that it is installed.

**Comment by awunnenb** [comment]
![image](https://github.com/user-attachments/assets/302348eb-c3aa-46a5-8211-ef8c4c930a91)

**Comment by awunnenb** [comment]
![image](https://github.com/user-attachments/assets/0276a371-6638-4dab-b161-89515e5b24d5)

**Comment by barisusakli** [comment]
Put a console.log [here](https://github.com/NodeBB-Community/nodebb-plugin-iframely/blob/master/library.js#L71) see if it is triggered, maybe you have some errors during startup that's preventing the admin link from showiug up. Do you get a 404 when you load `/admin/plugins/iframely`?

**Comment by barisusakli** [comment]
That means the plugin isn't loaded properly during startup, you will have to check your nodebb logs for any error messages.

**Comment by awunnenb** [comment]
the last errors in the log are from January 2023 and there was a missing file for the custom pages plugin but I added the missing file and since January no more errors in the log

**Comment by awunnenb** [comment]
How can I make the plugin page visible again and get the plugin running again? Would an npm install help or does nodebb not like that?

**Comment by barisusakli** [comment]
You can stop nodebb and start with `node app.js` and check the output.

**Comment by awunnenb** [comment]
good idea:
`
024-12-20T19:18:07.003Z [60001/13606] - error: Error: Cannot find module 'request'
Require stack:
- /opt/nodebb/require-main.js
- /opt/nodebb/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at require.main.require (/opt/nodebb/require-main.js:8:10)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-iframely/library.js:4:28)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
`

**Comment by barisusakli** [comment]
@awunnenb I will publish a new version with a fix.

**Comment by barisusakli** [comment]
@awunnenb try with nodebb-plugin-iframely@1.2.0

**Comment by awunnenb** [comment]
It works again. You have been providing great support for years. Thank you very much for that and happy holidays.

**Comment by barisusakli** [comment]
No worries, happy holidays 🎄
