### ISSUE TITLE
Allow mentions of groups

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#1331]
As an update to mentions, be able to tag groups:

* [x] **Core** `Groups.search()`, similar to `User.search()`
* [x] **Mentions** Search for both users and groups in autocomplete
* [ ] **Core** ~~Admin created groups should have a "slug" set, defaulted to a slugified version of the group name~~
* [x] **Core** `Notifications.pushToGroup()` which would push a `nid` to that group's users
* [ ] **Mentions** Notify users in group

---

Re: #1326 -- would be useful to tag mobile compatibility team in a single message.

This also goes halfway towards exposing the groups system to the front-end, so users can be added to special groupings and be shown on the board as a type of flair, e.g. "Translators", "Mobile Compatibility Team"

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-mentions/pull/42
