### ISSUE TITLE
How delete posts?

### ISSUE THREAD

**Issue by Vadorequest** [NodeBB/NodeBB#1394]
I'm wondering about how delete definitively a post/topic?

Basically a user created a bullshit message and I can't delete it, when I do, it's still visible, I don't want that.

How can I do?
Thanks.

**Comment by starhawkhkk** [comment]
The post is gone but the count on the category still takes into account the deleted posts.

Also non-admin user can still see (but can't access) the deleted posts if they choose to follow a category.
