### ISSUE TITLE
Multiple ownership for posts/topics

### ISSUE THREAD

**Issue by damianb** [NodeBB/NodeBB#148]
This is a much more theoretical thing, but it's worth thinking about.

Gist of it is that instead of a single "author", you have multiple for a given post or topic so that multiple users can edit the post/topic; by this, you can allow trusted users to manage information in a given topic for providing updates, corrections, etc. This would be different from moderation however, as it'd be on a per-topic/post basis for instances where a topic represents a given project, narration, or work of a group of people.

This'd allow much more flexibility than other systems, and allow this project to fill a niche similar to that of stackoverflow, as well.

**Comment by psychobunny** [comment]
Closing due to lack of interest. Not to say this is a bad idea, but we're cleaning up our issue tracker for bugs and features we would implement sooner than later. Good plugin idea though :)

**Comment by damianb** [comment]
Is there something set up for a general "idea" tracker at all, like a trello board?  Something that plugin authors could use for their own inspiration.

**Comment by julianlam** [comment]
Hey @damianb -- not really, we've kept most of the discussion to the forum, and we don't really maintain a Trello board as we don't have the time to do so.

We could always start one up (or have someone from the community do so) and pin it to the plugins category I suppose...

**Comment by damianb** [comment]
Noted. Shame time is such a sparse thing all around!
