### ISSUE TITLE
[RFC] Moving current default routes into plugins

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#1480]
/unread
/recent
/popular
/outgoing
/search -- this isn't even accessible without a search plugin!
/notifications ?
chat?

-- the list goes on - do we really, really, need user/name/followers and user/name/following routes in core? This is normally a plugin in most other forum software.

Things like `/popular` might be a plugin instead. I envy Ghost for their simplicity (grand total of four templates). Without any real scientific data to back this claim up I would wager that the amount of themes released is indirectly proportional to the amount of templates one requires to theme. Makes sense in my head. Proof here: http://themeforest.net/category/blogging/ghost-themes

Anyway - I feel like the less default templates in a stock vanilla NodeBB the better. Would be less overwhelming for a would-be designer. Also coming from a phpBB background I know how much of a hassle it is to theme 35+ views. That is definitely no easy task.

Would it make more sense to have /popular et al. released as bundled plugins in NodeBB? At the very, very least, the /search template for example should be bundled with the appropriate search plugin.

This task should be broken up into multiple issues after RFC is complete.

**Comment by pitaj** [comment]
:+1:
