### ISSUE TITLE
[RFC] menu.tpl needs a re-consideration

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#1481]
Our default menu is based on the default bootstrap menu. I feel like we're crippling ourselves by shoehorning the menu system into the bootstrap feel.

I think at the very least, all menu items should be served from the API and not hardcoded into the templates. So we can end up doing something like:

    
      <div class="whaaaatever you want!"> {menu.name}</div>
    

Right now, we're essentially hardcording all of the routes and then we add the custom menu items from plugins. But what if you wanted something totally different? You're out of luck. We should look into this before we go too far with the current idea.

**Comment by pitaj** [comment]
To implement this idea, a few things would have to be done:

 * Each item in the menu has a unique identifier (could be a hash, or an id provided by the plugin, or whatever)
 * Add an ACP configuration page (could look like the one from [my plugin](http://github.com/pitaj/nodebb-plugin-header-extend))
 * Maybe allow for custom html
 * Possibly add dropdown submenus as an option
 * Allow for icons that aren't Font Awesome characters
 * Save the information (order, routes, icons, ids, names, etc) to the database in this form: 
```json
[
  {
    "id": "recent",
    "title": "Recent",
    "route": "/recent",
    "text": "<i class='fa fa-clock-o fa-fw'><span class='visible-xs'>Recent</span>",
    "class": "whatever-recent"
  },
  ...
]
```
 * Use the database information in the template like it is now

**Comment by pichalite** [comment]
@psychobunny Disable and Delete don't work. I was looking to disable or delete /search route as it is already available on the right side of the navbar. I like the search option on the right as I can type the search term by clicking the icon.

**Comment by pichalite** [comment]
@psychobunny not able to delete menu items from active navigation.

**Comment by psychobunny** [comment]
Did you click save?

(I realize that some ACP has save on delete, others require you to delete then save, another issue for another day)

**Comment by pichalite** [comment]
When I click "Delete", the complete page refreshes and the browser address bar changes to this address

`http://localhost:4567/admin/general/navigation?id=&route=%2Fforum&title=Blog&text=Blog&iconClass=fa-group&textClass=visible-xs-inline&enabled=`

I can still see the menu item under active navigation. Clicking save doesn't do anything for delete.

Disabling the menu item works. Clicking on the "Disable" button changes the button to "Enable" and clicking the save button removes the item from the menu in the header of NodeBB.
