### ISSUE TITLE
Post edit history / diffs

### ISSUE THREAD

**Issue by damianb** [NodeBB/NodeBB#149]
As on tin - providing edit history for posts (or just storing diffs - whichever ends up being smaller perhaps?) would be a useful moderation tool.

If implemented, packaging it with the ability to revert a change (or multiple) somehow would be beneficial, as well.

**Comment by ApfelUser** [comment]
After nearly 1 year, I second @a5mith :smile:

**Comment by robotanarchy** [comment]
me too, I'd also like to see this feature :+1:

**Comment by pauljherring** [comment]
Me too!!!eleventy-one.  ! 

Got a bit too used to it in Discourse, which we'll be moving away from.

**Comment by freewind** [comment]
👍

**Comment by BenLubar** [comment]
Well, four years later...

https://github.com/BenLubar/nodebb-plugin-post-revisions

**Comment by julianlam** [comment]
This is fantastic! Good work @benlubar

**Comment by julianlam** [comment]
Done in core in `develop` (hopefully won't interfere with your plugin @BenLubar !)

**Comment by julianlam** [comment]
Testing on community.nodebb.org

![image](https://user-images.githubusercontent.com/923011/36343981-9f22d80e-13e1-11e8-9b47-0e3e9fc64f9a.png)

![selection_288](https://user-images.githubusercontent.com/923011/36343987-afb1f6d2-13e1-11e8-9d0e-871609c1b4d6.png)
