### ISSUE TITLE
[Settings] default values not being set for regular input types

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#1528]
So, here's the first time we're using the new settings framework in core. I realize that if a default value is set by `data-new` or `data-empty` (not sure which is the preferred one to use) the value is `[object Object]` even though I'm sending through a string.

Everything else seems to work, and after first time save, works fine.

To repro, update to latest, relevant commit is here: [core](https://github.com/designcreateplay/NodeBB/commit/a5a2e6f04e55ce123c59f2987528632dc2a6b25c), [template](https://github.com/designcreateplay/nodebb-theme-vanilla/commit/493858eec5b0e427197d7f15d5e8716c755134d3)

**Comment by pitaj** [comment]
Is this still a thing?

**Comment by julianlam** [comment]
@frissdiegurke @yariplus Is this issue still present?
