### ISSUE TITLE
[Settings] Make getting settings less complicated

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#1529]
So I finally got a chance to play with the new settings framework @frissdiegurke, here are my thoughts:

See https://github.com/designcreateplay/NodeBB/blob/master/src/meta.js#L391-L394

I think would be great if we can convert the syntax to something like:

```
var settings = require('./settings');
settings.get('branding', function(err, branding) {
    branding; // this is branding.cfg._ in the current code
});
```

So in other words, 

1. make `version` and `default config` optional parameters
2. callback should be `function(err, object, otherConfigurations)`
3. don't use `new` syntax, we try to avoid that in NodeBB in general so this would kind of break style (sort of an unwritten rule)

If that's too overwhelming for you @frissdiegurke I can take a crack at it, but would need to familiarize myself with the more complex settings plugins first.

**Comment by pitaj** [comment]
Is this still a thing?

**Comment by julianlam** [comment]
I think @psychobunny has given up on settingsv3, so we'll leave it as-is :smile:
