### ISSUE TITLE
<code> blocks need better CSS

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#153]
This is potentially a candidate for upstream bugfixing via twitter bootstrap (v2.0 branch).

Currently, it looks like this:

![](http://i.imgur.com/dFJgUqf.png)

Instead of one continuous block of code

**Comment by sambomartin** [comment]
For a code fenced block, i.e.
```javascript
var x=1;
var y=x;
```

is outputting:
<code>javascript
var x=1;
var y=x;</code>

which is being rendered inline.

Should it not be <pre><code>...</code></pre>

If not, how do i make it a block?

Thanks
Sam

**Comment by julianlam** [comment]
Do you have the markdown plugin activated, with code block formatting enabled?
