### ISSUE TITLE
Editable language strings

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#1643]
This is something we always wanted to do in phpBB but never happened afaik.

The ability to fork and modify a language for your own forum in the ACP itself, so you could turn "Reply" to "Respond" for example. Got a Q&A site? The button should be "Answer" then!

With widgets it could be very powerful, really letting you customize your forum to the max :)

Post 0.5x.

**Comment by julianlam** [comment]
While not exactly the feature as written out here, as of v1.1.0, plugins can override core language strings :smile:
