### ISSUE TITLE
Revamp "Upload Picture" Button in composer

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#1659]
Right now there are multiple buttons for uploading or attaching pictures in a post, and UX-wise, it could use an improvement.

I very much like this look that GitHub uses:

![selection_004](https://cloud.githubusercontent.com/assets/923011/3218523/82cb8dd6-efeb-11e3-9296-13c52eab7752.jpg)

How about something similar, that comes up when the "Picture" button is clicked via composer?

![selection_006](https://cloud.githubusercontent.com/assets/923011/3218531/a65cccc4-efeb-11e3-98dc-93cbf0fd7b8c.jpg)

* The first would open the file upload box, similar to how it is now.
* The second would open another bootbox modal.
    * Alternatively, it could just close the modal and add `![alt text](image url)` to the composer body with `image url` highlighted.
* The third would open up another bootbox modal to take a picture using the camera API (would be cool, but this is really just a gimmick).

In all three cases, the first modal would close.

**Comment by psychobunny** [comment]
@julianlam closable with new WYSIWYG composer?

**Comment by julianlam** [comment]
.. we have this now :stuck_out_tongue: 

![selection_078](https://cloud.githubusercontent.com/assets/923011/17678575/ad0f0804-6305-11e6-8228-ff8a2afc69c3.png)

**Comment by psychobunny** [comment]
Haha. +1 for the original proposed styling though

**Comment by julianlam** [comment]
:+1: me too, though now it's a theme issue :trolleybus:

**Comment by pichalite** [comment]
should have atleast fixed the button text visibility before uploading the screen shot :troll:

**Comment by pichalite** [comment]
merge the PR for that.
