### ISSUE TITLE
Duplicate content and PageRank loss

### ISSUE THREAD

**Issue by nodecode** [NodeBB/NodeBB#1668]
It is not good for search engines to use when scrolling URLs like https://community.nodebb.org/topic/72/we-need-your-help/18. As soon as a user this URL copied, and they linked from a website, Google finds duplicate content. In addition, the PageRank goes to different URLs, and not to one single.
See also: https://support.google.com/webmasters/answer/66359?hl=en

There are two ways to resolve this problem:
- The easiest and in my opinion better solution would be to use URLs like https://community.nodebb.org/topic/72/we-need-your-help#18.
- The second solution would be to use <code>rel="canonical"</code>. (https://support.google.com/webmasters/answer/139066?hl=en)

**Comment by svishi** [comment]
@psychobunny somehow this still keeps happening. The latest source code doesn't have the `rel=canonical` tag on topics. Can this be fixed by adding another JSON block in `src\controllers\topics.js` at line 290 `res.locals.linkTags` like so:

```
	res.locals.linkTags = [
		{
			rel: 'alternate',
			type: 'application/rss+xml',
			href: topicData.rssFeedUrl,
		},
		{
			rel: 'canonical',
			href: nconf.get('url') + '/topic/' + topicData.slug,
		},
	];
```

**Comment by psychobunny** [comment]
reopened, RFC

**Comment by julianlam** [comment]
If we don't already have the link to the canonical topic URL, then we should definitely add one

**Comment by svishi** [comment]
It's not there. Could we add it in the next release?

**Comment by BenLubar** [comment]
@barisusakli what about multi-page topics?

**Comment by barisusakli** [comment]
I think [this](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/topics.js#L158-L161) code was added to handle that.

**Comment by BenLubar** [comment]
I'm pretty sure Google honors `rel="canonical"` on pages even if they're linked to from a `<link>` tag. I would suggest setting the canonical URL to the current post rounded down to a multiple of the page size. That's why I currently have WTDWTF set to use pagination for logged-out users.

**Comment by barisusakli** [comment]
So canonical url should be as follows when posts per page is 20?
```
http://forum.com/topic/1/title on page1
http://forum.com/topic/2/title/20 on page2
http://forum.com/topic/2/title/40 on page3 
...
```

**Comment by BenLubar** [comment]
Yeah, that would work, assuming the page ending in /20 includes posts 20-39 on load (without any scrolling to load content required)
