### ISSUE TITLE
Refactor chat system layer

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#1798]
Writing this down before I forget...

@barisusakli, it seems the current chat backend works like so, please correct me if I am wrong:

* When a chat message is sent, a new `message` object, identified by an `mid` is created, and the `mid` itself is appended to the list: `messages:{fromUid}:{toUid}`
* If the user on the receiving end is offline (no socket session ids are present in the user's room), a notification is sent
* ... and a socket message is emitted saying a chat message was received

It *seems* as though it would be easier if you were to use the rooms abstraction throughout, to manage the chats:

* `julian` (uid `382`) chats with `baris` (uid `859`), they enter (or re-enter) room `chat_382_859`, room id is constructed by ordering the uids in numerical order, and then separating them with underscores (see methods introduced in 7b31592)
* On new message, check socket ids present in room, and if any recipients are offline, send them a notification as normal (7b31592 again)
* **Send chat message event to the room instead of the sockets**
* **Extend this further**, three person chat? `chat_382_859_1044`
    * No need to do `server.getUserSockets(someUid)` to determine receipient sockets to send chat notifications, just send the notification object to the room, because socket.io can do that

Worth it?

**Comment by psychobunny** [comment]
imo time to rename this issue to "GROUP CHAT" :P 

We've already closed a few as dupes because this one isn't as searchable :P

**Comment by pitaj** [comment]
I say copy how Google Hangouts does it.

**Comment by leader21** [comment]
sorry to bother, but any news on this guys?

**Comment by lnxseed** [comment]
yes, group chat room will be great! any plan for the feature?

**Comment by deltaflux** [comment]
Is anyone actively working on this? I'm currently evaluating NodeBB and the forums/groups look like exactly what I need but I also need private group chat as well as large chat rooms (IRC style) for with support for large user numbers (100+ per room) and I'm trying to get a gauge on how much NodeBB could cover.

**Comment by mamuesp** [comment]
Nearly same question here ... I planned to write a (small) node.js based forum software by myself, as I found discourse and nodeBB (BTW I earn my money as software developer ...). My "brain concept" had a similar stucture in mind I found in nodeBB - that's great! But some functions are really missing - ok, private messaging is covered by User2User-Chat, that's fine, but group chat is a feature really needed. Why is it not possible to have chat between two groups, handled by the messenger.js, and a layer on top which handles the single users? Just a thought ...

**Comment by julianlam** [comment]
@mamuesp No reason, really. The system was envisioned to be user-to-user, and only after release did we learn that many users wanted group chats :)

We could always tear the existing code down and re-write, but there is lots of code (incl. third-party contributor) code that we'd love to re-use, so it's more a matter of finding a sufficiently large block of time to dedicate to this.

**Comment by mamuesp** [comment]
THX for the information. It's your project, so the user-to-user aspect has to be respected. As I'm courious, I'll analyze the "group chat" point a little more - perhaps we may discuss somethng later on.

**Comment by henrywright** [comment]
Thinking about how this (seemingly huge) task could be simplified. Perhaps re-use much of the code that already exists in NodeBB. Could group chats just be "private" categories, formatted to feel "chat-like" at the front-end?

**Comment by pitaj** [comment]
![Noooooooooooo](http://media.giphy.com/media/12XMGIWtrHBl5e/200w.gif)

**Comment by henrywright** [comment]
@pitaj lol

**Comment by erayaydin** [comment]
@henrywright ![oh hell no](http://media.giphy.com/media/jfM7rT6YOxpx6/giphy.gif)

**Comment by julianlam** [comment]
Hahah... 

>  Could group chats just be "private" categories, formatted to feel "chat-like" at the front-end?

I'm going to admit that while it seems like a novel idea, in practice, it is likely end up closer to a square-peg-round-hole implementation.

**Comment by henrywright** [comment]
Haha, sorry for the bad idea :)

**Comment by pitaj** [comment]
Any update on this? It's still by far the largest missing feature IMO

**Comment by akhoury** [comment]
+1 for group messages
