### ISSUE TITLE
"Test Email" functionality

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#1837]
A button in core to send a test email
- [x] Send email button in ACP settings
- [x] Language strings
- [x] Proper handling if there are no `email.send` listeners

**Comment by kdrdgn** [comment]
Send Test Email functionality doesnt working with Mailgun plugin

**Comment by julianlam** [comment]
Please start a new topic in our community forum if you're having issues with emailers. Likely you're on master, and you should install the emailer via npm.
