### ISSUE TITLE
App Crash after latest push

### ISSUE THREAD

**Issue by src1988** [NodeBB/NodeBB#1841]
Not sure what this error is relating to, any help?

Jul 16 22:52:42 fateoftime heroku/web.1:  State changed from starting to crashed 
Jul 16 22:52:43 fateoftime heroku/web.1:  Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch 
Jul 16 22:52:43 fateoftime heroku/web.1:  Stopping process with SIGKILL 
Jul 16 22:52:43 fateoftime heroku/web.1:  Process exited with status 137 
Jul 16 22:52:43 fateoftime heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=fateoftime.com request_id=fe1e6917-c8bb-449b-aa6e-ea68a5398115 fwd="24.147.197.146" dyno= connect= service= status=503 bytes= 
Jul 16 22:52:45 fateoftime heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=fateoftime.herokuapp.com request_id=32b28c1e-6874-465f-a787-237752285554 fwd="54.205.75.195" dyno= connect= service= status=503 bytes= 
Jul 16 22:52:46 fateoftime heroku/router:  at=error code=H10 desc="App crashed" method=GET path="/" host=fateoftime.herokuapp.com request_id=3c6207ed-2077-45df-a63a-f1b56318164d fwd="24.147.197.146" dyno= connect= service= status=503 bytes=

**Comment by jay941** [comment]
at=error code=H10 desc="App crashed" method=POST path="/setData" host=bridge941.herokuapp.com request_id=6744ec8b-1d67-4f14-9f06-340dd807bd9e fwd="1.186.60.140" dyno= connect= service= status=503 bytes=
 i am getting this error help me

**Comment by julianlam** [comment]
Please direct configuration issues to our support forum. https://community.nodebb.org
