### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by frenchja** [NodeBB/NodeBB#1907]
Is it possible to include a Redis to MongoDB migration option in a future release?

**Comment by KanwalSingh** [comment]
@julianlam I am worried about using redis in production due to persistence problems. 
Can you also include Aerospike db connectors 

and +1 for the migration between databases.

**Comment by julianlam** [comment]
@frenchja @KanwalSingh  We've implemented a Redis-to-Mongo converter. Please contact us if you're interested in having your database converted :smile:

**Comment by KanwalPrakashSingh** [comment]
@julianlam I hope it works the other way round as well (i.e. mongo to redis )

**Comment by julianlam** [comment]
No, we didn't build the converter to go the other way around, as there was not much interest in doing so. Not that Mongo is _superior_ than Redis, they both have their uses.

**Comment by hallard** [comment]
@julianlam 
I'm interested by this converter, I experienced a redis strange thing, database for nodebb was almost empty and I lost 2 months of community (everybody has a weekly backup yuhh ?). Setup was done using flush every 10 changes and every hours, nothing in redis log, very strange.
So I would like to move to another database soit is possible to get this converter ?
thanks for your help

**Comment by julianlam** [comment]
@hallard Please reach out to us at sales@nodebb.org for info about the converter :smile:
