### ISSUE TITLE
Allow admins to change the web socket address to a different domain

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#1916]
An advanced option, for users who want to route websocket connections (and _only_ websocket connections) to a separate non-CloudFlare-accelerated subdomain, while maintaining accelerated assets for the rest of the site.

**Comment by lots0logs** [comment]
@julianlam @barisusakli @psychobunny Where has this option gone? Is it still available? It would be a huge time saver to have websockets on a sub domain so we can let cloudflare block the spam bots!

**Comment by barisusakli** [comment]
It's defined in config.json now https://docs.nodebb.org/en/latest/configuring/config.html

**Comment by lots0logs** [comment]
Thanks!!
