### ISSUE TITLE
translator needs to have an option to escape % and , in variables

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#1951]

**Comment by pitaj** [comment]
☝️ even more postponing. It is absolutely possible to escape `%` from arguments but it isn't possible to escape `,` unless we do so explicitly. Something like `\,` could be used to denote that an actual comma should come out after translation is complete. Another option is using grouping characters like quotes or backticks.

Keep in mind that all of these options would only work for one pass, so nested translations would have to have sufficient escapes for every level:

    [[abc:jkl, [[just:text, all at once\\, this should go]]]]

**Comment by pitaj** [comment]
Also, just realized we now have two forms of helpers: custom translator modules and t.js helpers

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/5248
