### ISSUE TITLE
Admin lockout timer.

### ISSUE THREAD

**Issue by a5mith** [NodeBB/NodeBB#1972]
I know this can be changed globally from 14 days. However I think admins should have to verify their login more regularly, Most forum software will make you reverify your password when trying to access the ACP for the first time in over an hour or so. Would be an additional layer of security for admins who log in somewhere and don't have the chance/forget to logout. Perhaps the ability to close sessions from your user settings may also be nice.

**Comment by julianlam** [comment]
Unfortunately I'm going to have to re-open this issue as admins who control their forums via SSO login only are locked out of their ACPs as of ced7fb5.

**Comment by lots0logs** [comment]
@julianlam @barisusakli I've been hit with this issue after upgrading today. I tried upgrading to the latest master and still can't access the ACP. I'm using SSO only (local is disabled completely). Is there something I need to implement in my SSO plugin to make this work? Please let me know. Thanks.

**Comment by barisusakli** [comment]
Does your user account also have a local password?

**Comment by lots0logs** [comment]
@barisusakli Sorry I missed your reply. Hmm..Yes I believe it does. We imported about 3000 users when we first started with nodebb and we didn't setup SSO until quite some time later.

**Comment by lots0logs** [comment]
@barisusakli @julianlam

**Comment by julianlam** [comment]
Yes, sorry. Your SSO plugin will need to call onSuccessfulLogin when authentication completes.
