### ISSUE TITLE
Ability to change "home"

### ISSUE THREAD

**Issue by a5mith** [NodeBB/NodeBB#2002]
I recall @psychobunny mentioning this a while back, so thought I'd make an issue out of it. 

Being able to change what page is displayed as "home", so, for example, the homepage could be changed to Recent, or Popular etc. 

Might be worth a "Request for Comments", see what others think?

**Comment by barisusakli** [comment]
- [ ] rename home.tpl to categories.tpl in vanilla & lavender
- [ ] rename home.js to categories.js in core
- [ ] rename categories.tpl to categories-widget.tpl in widget-essentials
- [ ] home.tpl has a global class called `home` it should really be `categories` fix the css after that change in lavender & vanilla

**Comment by psychobunny** [comment]
@barisusakli need to update https://github.com/NodeBB/NodeBB/blob/master/package.json too imo otherwise

![](http://images.huffingtonpost.com/2014-10-29-CHALLENGEREXPLOSION.jpg)
