### ISSUE TITLE
Socket.io unrecognized message

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2127]
If client sends unrecognized message, server should tell client that it's out of date - please reload

**Comment by julianlam** [comment]
@psychobunny I like how we talked about this, agreed on a solution, and then promptly forgot to implement it.

> Ajaxify still works without an active socket connection. Completely forgot about that

As of two days ago, ajaxify no longer works without an active socket connection (as intended), so this solution is out...

Unless the existing "a new version is available" message is broken, then this is no longer an issue. Re-open if I'm mistaken.
