### ISSUE TITLE
Ability to set a Group as a Category moderator + Global moderator

### ISSUE THREAD

**Issue by Ribesg** [NodeBB/NodeBB#2144]
I really don't see the point in being able to set specific users as moderators of a category, but that's implemented. On the other hand, setting a "moderator" group as a Category moderator isn't possible, which is weird.

It would also be nice to be able to set a group as global moderator.

**Comment by barisusakli** [comment]
![image](https://cloud.githubusercontent.com/assets/2583394/9341038/6b3cfac4-45c1-11e5-990d-766a8ebb8860.png)
