### ISSUE TITLE
[RFC] UCP needs love, big time

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2167]
(User Control Panel, aka `/user/:user/settings` route)

This is kind of like the "ACP needs love" issue I made over 6 months ago, and only recently has the ACP been getting the treatment it deserves (and it has a long way to go)

I wanted to just open this up for a bit so we can get some comments on what we need to be having. As a forum user, please leave your suggestions. UCP's for traditional forum software has a shit ton of features, right now we have literally only a dozen settings which is the bare minimal. Let's figure this out :+1: 

I doubt we will tackle the brunt of this till post 0.6x tbh, but we just need to get a heads up sooner than later on what is in demand.

**Comment by pitaj** [comment]
Also, allowing plugins to add settings to the user settings page (under a plugins section or something) would be awesome. Then Pushbullet wouldn't have to add an entry to the dropdown.

Also, a link to the settings page should be under the same menu as the link to your profile and the selection of your online status.

**Comment by psychobunny** [comment]
UCP has come a long way since 12 months ago, time to close
