### ISSUE TITLE
SSO auth redirect to localhost

### ISSUE THREAD

**Issue by aortmannm** [NodeBB/NodeBB#2168]
Hi,

I created a new forum with nodebb on my server. It works well and I can use it via my subdomain e.g. forum.domain.de . Now I want to activate the login via facebook twitter etc...

I click on the twitter button in the login and I get a redirect to: 

http://localhost:9000/auth/twitter/callback?oauth_token...

How can I change this that it will be my subdomain and not the localhost

**Comment by machado2** [comment]
This also happens with me.

**Comment by julianlam** [comment]
You'll want to specify the proper url in `config.json`
