### ISSUE TITLE
customisable email templates

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2183]
@a5mith

**Comment by julianlam** [comment]
A plugin can define templates to override email templates now, so this issue is defunct (unless you meant to edit email templates in ACP, which is a completely different idea altogether...)

**Comment by psychobunny** [comment]
Even 12 months ago it was possible to do that. Yeah I meant edit in ACP

**Comment by julianlam** [comment]
:clap: @a5mith see, we get to all issues eventually
