### ISSUE TITLE
Log rotation 

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2185]
Log rotation was a hack job that doesn't work well. Better to use something that is well tested: https://www.npmjs.org/package/logrotate-stream

**Comment by arbisofttaha** [comment]
@julianlam Can we update this logrotate limit from 1MB to some other value?

**Comment by barisusakli** [comment]
@arbisofttaha you can modify the value on [this](https://github.com/NodeBB/NodeBB/blob/master/loader.js#L30) line until we make it configurable.

**Comment by arbisofttaha** [comment]
Thanks @barisusakli
