### ISSUE TITLE
plugin page not loaded

### ISSUE THREAD

**Issue by rawbean** [NodeBB/NodeBB#2193]
Plugin page can not be loaded in a new installation of version 0.5.1 , error log found:

{"level":"error","message":"Error parsing plugins : Unexpected token u","timestamp":"2014-10-01T11:12:56.796Z"}

**Comment by mikwys** [comment]
I have simmilar problem in 0.6.1-dev. I can't load plugins page. I got error in log
Error parsing plugins : Unexpected end of input
and also in console Error code: ERR_EMPTY_RESPONSE

**Comment by orangeclk** [comment]
I cannot load plugins page either while I am using v0.6.0, which is the release version. I also get the error code *ERR_EMPTY_RESPONSE*.

**Comment by mikwys** [comment]
It looks like problem with router / local network. It works ok when I connected through wifi created on my mobile phone..
