### ISSUE TITLE
Ability to show/hide "Full Name" in user profile

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2195]
As requested by a user of NodeBB:

> **Show/hide name in profile option**
> Is it possible hide full name in every profile by default and show it only when checked in settings (basically same as email).

**Comment by magillo** [comment]
I thought the same, until reading a post on an external site (www.airpair.com) that required being logged in github to view code snippets.
Anyway any external sites (like this one) that rely on OAuth or similar for authenticating users, often require a github profile with full name provided.
So, leaving full name empty is not a good option.
That is not a problem, I'm ok to share my name or email address vs a site I trust, but an option to hide full name to public, leaving access to OAuth providers, would be nice. 
Nothing against that site in particular, just as example.

**Comment by nitrocode** [comment]
Ran into this recently where for auditing reasons we needed the full name to be available to org owners but did not want to show the full name on our profiles. The workaround is to create a brand new github account which separates one account from another but still shows publicly your full name.
