### ISSUE TITLE
ACP - Option to prevent editing of a post after a certain time limit

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2247]
As mentioned here, https://github.com/NodeBB/NodeBB/issues/2237

Low priority until somebody requests this feature, not something we personally need but is definitely a feature on other forum software.

**Comment by pitaj** [comment]
The execution of this should probably be done in the following way:

1. Implement a post locking system
A moderator would click a button on a post to prevent it from being edited (and hiding the edit button)
2. Create a filled in the ACP to automatically lock a post after a certain amount of time
