### ISSUE TITLE
infinite scroll breaks if new post comes in

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2271]
repro

1. load a topic that has lots of posts. ie 40+
2. start scrolling down until infinite loader kicks in and loads posts 10-20.
3. on another tab make a new post in the same topic.
4. the new post appears at the bottom on the other tab.
5. if you try to scroll down in the original tab infinite scroll wont load posts 20-30 since the last post is now the latest in the topic.

Part of the problem https://github.com/NodeBB/NodeBB/blob/master/public/src/client/infinitescroll.js#L64 uses .last() to get the index.

**Comment by pitaj** [comment]
Is this closed or what?

**Comment by pitaj** [comment]
Seems like it's related to #2269
