### ISSUE TITLE
Buttons not working on mobile

### ISSUE THREAD

**Issue by gishmel** [NodeBB/NodeBB#2324]
Does anybody else see this problem? I am using the Lavender Theme for NodeBB and have updated but still have a lack of working buttons? Anybody have any suggestions or comments on the subject?

**Comment by efkay1** [comment]
these problems reappear in the new persona theme

**Comment by psychobunny** [comment]
Hi, this is very likely unrelated (code wise) so can you make an issue in the persona tracker with detail please, easier to track for us. Thanks!
