### ISSUE TITLE
Permission to purge your posts should be separate from edit permission.

### ISSUE THREAD

**Issue by dwendt** [NodeBB/NodeBB#2330]
I believe the code in question is here: https://github.com/NodeBB/NodeBB/blob/a65d61290742fef5ed76834a73e069336ebe5b6b/src/postTools.js#L181

Allowing users to perma-delete their own posts is super abusable. It should be its own permission, off by default for registered users imo. You could say that they could just edit the content of their post out -- but at least I could have a plugin keep track of every post edit and give me a history to restore that post back to.

Doesn't seem like there are group-level permissions yet, so it'd need to be a checkbox under users I guess.

**Comment by Korrosivo** [comment]
@barisusakli Sorry for the duplicate issue.
That is a "must" to use NodeBB in some countries. Hope to see it in the near future.

Thanks!

**Comment by limitmaker** [comment]
What about allowing users to disable their user account and have their information hidden, instead of doing a purge?  A soft delete.

**Comment by MegaGM** [comment]
https://github.com/NodeBB/NodeBB/issues/3255
Please, add the option ![](http://smayly.ru/gallery/anime/RedFox/15.gif)
