### ISSUE TITLE
nodebb sso plugins cause server crash

### ISSUE THREAD

**Issue by rahilwazir** [NodeBB/NodeBB#2405]
When activating any `nodebb-plugin-soo-*` plugin cause server to crash.

Here's the log (It keep spamming this):

> 2014-11-13T16:45:09.137Z - error: TypeError: Cannot read property 'admin' of undefined
>     at Object.Twitter.init (/home/llamamall/llamamall2/forum/node_modules/nodebb-plugin-sso-twitter/library.js:29:64)
>     at /home/llamamall/llamamall2/forum/src/plugins.js:489:23
>     at /home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:125:13
>     at Array.forEach (native)
>     at _each (/home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:46:24)
>     at Object.async.each (/home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:124:9)
>     at Object.Plugins.fireHook (/home/llamamall/llamamall2/forum/src/plugins.js:487:12)
>     at Plugins.reloadRoutes (/home/llamamall/llamamall2/forum/src/plugins.js:135:11)
>     at /home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:656:23
>     at fn (/home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:641:34)
> TypeError: Cannot read property 'admin' of undefined
>     at Object.Twitter.init (/home/llamamall/llamamall2/forum/node_modules/nodebb-plugin-sso-twitter/library.js:29:64)
>     at /home/llamamall/llamamall2/forum/src/plugins.js:489:23
>     at /home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:125:13
>     at Array.forEach (native)
>     at _each (/home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:46:24)
>     at Object.async.each (/home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:124:9)
>     at Object.Plugins.fireHook (/home/llamamall/llamamall2/forum/src/plugins.js:487:12)
>     at Plugins.reloadRoutes (/home/llamamall/llamamall2/forum/src/plugins.js:135:11)
>     at /home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:656:23
>     at fn (/home/llamamall/llamamall2/forum/node_modules/async/lib/async.js:641:34)
> 2014-11-13T16:45:09.141Z - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
> 2014-11-13T16:45:09.141Z - info: [app] Database connection closed.
> 2014-11-13T16:45:09.142Z - info: [app] Web server closed to connections.
> 2014-11-13T16:45:09.142Z - info: [app] Shutdown complete.
> 2014-11-13T16:45:09.911Z - info: Enabling 'trust proxy'
> 
> 2014-11-13T16:45:10.049Z - warn: [plugins/nodebb-plugin-markdown] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
> 2014-11-13T16:45:10.049Z - warn: [plugins/nodebb-plugin-markdown] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset plugin="nodebb-plugin-markdown".
> 
> 2014-11-13T16:45:10.051Z - warn: [plugins/nodebb-plugin-mentions] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
> 2014-11-13T16:45:10.051Z - warn: [plugins/nodebb-plugin-mentions] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset plugin="nodebb-plugin-mentions".
> 
> 2014-11-13T16:45:10.052Z - warn: [plugins/nodebb-widget-essentials] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
> 2014-11-13T16:45:10.053Z - warn: [plugins/nodebb-widget-essentials] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset plugin="nodebb-widget-essentials".

**Comment by zaasmi** [comment]
nternal Error.
Oops! Looks like something went wrong!
/admin/plugins/sso-facebook
Failed to lookup view "admin/plugins/sso-facebook" in views directory "/var/www/cyberian.pk/nodebb/build/public/templates"

**Comment by julianlam** [comment]
Run `./nodebb build`

**Comment by zaasmi** [comment]
> Run `./nodebb build`

thanks working

**Comment by zaasmi** [comment]
Internal Error.
Oops! Looks like something went wrong!
/auth/facebook/callback
This IP can't make requests for that application.

> Run `./nodebb build`

Internal Error.
Oops! Looks like something went wrong!
/auth/facebook/callback
This IP can't make requests for that application.

**Comment by zaasmi** [comment]
> Internal Error.
> Oops! Looks like something went wrong!
> /auth/facebook/callback
> This IP can't make requests for that application.
> 
> > Run `./nodebb build`
> 
> Internal Error.
> Oops! Looks like something went wrong!
> /auth/facebook/callback
> This IP can't make requests for that application.

sorry ip was not listed working
