### ISSUE TITLE
Renamed topic urls are not redirected automatically

### ISSUE THREAD

**Issue by bendem** [NodeBB/NodeBB#2437]
After renaming a topic, `/topic/3/` will redirect to the correct url (`/topic/3/what-about-subcats-on-main-page`) but `/topic/3/what-abou-subcats-on-main-page` (using the previous url) won't.

**Comment by pitaj** [comment]
Just check the mind type of the URL

**Comment by Ribesg** [comment]
@barisusakli does the closing means this is fixed in 0.7.0?

**Comment by barisusakli** [comment]
Yes @julianlam fixed this a while back.
