### ISSUE TITLE
Move Email digests from core to a plugin

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2455]
This should be done because of [this](https://community.nodebb.org/topic/3339/is-it-possible-to-configure-daily-email-to-send-only-if-there-is-at-least-one-event) and [this](https://community.nodebb.org/topic/3269/100-no-js-clients-compatibility/8).

It would allow administrators to customize their own daily digests (the format, etc). 

This functionality just belongs to plugin-sphere. It would enable plugin creators to add functionality without duplicating the core functionality or modifying the core.

EDIT: 
also, [this](https://community.nodebb.org/topic/2336/reply-by-email/)
and, [this](https://community.nodebb.org/topic/2383/email-integration-confusion/)

**Comment by psychobunny** [comment]
I recently added the ability to customise the digest template in ACP. Not saying that this is what you were looking for, but I think digests are here to stay in core. If you like, open new issues for specific feature requests 

I'm cleaning up our issues, trying to find things that are probably unclosable unless they were broken up etc

**Comment by jraichur-group1200** [comment]
It would be great if we could change the digest time in ACP.
