### ISSUE TITLE
plugin.json hook for translator.addTranslation

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2461]
Right now plugins need to call `translator.addTranslation` directly, *for each* language. Perhaps best to define an i8n directory in `plugin.json` which will set it all up for you.

Not high up on the priority list, so plugin devs +1 this issue if you want us to move it to the top of the queue if you are planning on supporting i8n soon.

**Comment by pitaj** [comment]
Didn't you do this already?

**Comment by psychobunny** [comment]
I don't think so, unless I was sleepwalking recently :p

**Comment by pitaj** [comment]
In my calendar plugin I have a languages hash in plugin.json that takes a finger of translations in json format. So I think it does work.

**Comment by psychobunny** [comment]
I can't find your languages hash in your plugin:
https://github.com/pitaj/nodebb-plugin-calendar/blob/master/plugin.json

**Comment by pitaj** [comment]
It's in the 0.2.x branch

https://github.com/pitaj/nodebb-plugin-calendar/blob/0.2.x/plugin.json#L28

**Comment by pitaj** [comment]
@psychobunny I'm pretty sure someone has implemented this. 

It's working in my plugin.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/blob/master/src/plugins/load.js#L161-L200

https://github.com/NodeBB/NodeBB/blob/master/src/plugins.js#L335-L349

**Comment by barisusakli** [comment]
>I don't think so, unless I was sleepwalking recently :p

https://github.com/NodeBB/NodeBB/commit/b5d3186120dade8f0ae01f59470088024f9c265f

:laughing:
