### ISSUE TITLE
General Permissions Changes

### ISSUE THREAD

**Issue by Ktar5** [NodeBB/NodeBB#2462]
As I said in an earlier issue #2460 , I'm going to make an index of suggestions for permissions, so let us start out with basic changes to the permission handling system (well.. basic in idea, not in execution, sorry devs).

### General Suggested Changes
- Ability to add per-group permissions for whole forum rather than only per-category
- Inheritance
  - Group A has the permission to move topics in all forums, but maybe we don't want our Group A's to be all touchy-feely with our News category. To fix this, in the categories, we should can disable that permission node for that group within the specified category.
- New interface for permission changing
  - The current one (listing all permissions in a drop down menu), although simple and unobtrusive, seems counter-intuitive to me based upon the friendliness of all NodeBB's other UX features.
    - Possibly a new page dedicated to permissions?

With that being said, I believe that is the end to my rant of general changes, the next topic to tackle will be moderator permissions, but I'll post that later on within the next day or so. Feel free to comment suggestions/changes. Toodle Oo for now.

**Comment by niklas-heer** [comment]
+1

**Comment by julia-enko** [comment]
+1

**Comment by barisusakli** [comment]
>New interface for permission changing
The current one (listing all permissions in a drop down menu), although simple and unobtrusive, seems counter-intuitive to me based upon the friendliness of all NodeBB's other UX features.
Possibly a new page dedicated to permissions?

This is already done AFAIK.

**Comment by thesbros** [comment]
Why was this closed? Most of this stuff hasn't happened.
