### ISSUE TITLE
Categories feel hard to manage

### ISSUE THREAD

**Issue by Ktar5** [NodeBB/NodeBB#2463]
In the current system for categories, we are shown a list of all our categories with all their private options exposed to our eyes. This makes the feel of the category menu, for me at least, feel cluttered. When someone like me has many categories, and subcategories, we have a large, scary page in front of us.

Solution?
I propose that categories should hide their options until we call for them. A great example of category management is in VanillaForums: Create a category, drag and drop it slightly to the right of another category to mark it as a subcategory, with a pretty little edit button on the side to allow us to change those more sensitive settings: such as permissions, icon, title, etc.

Here is a visual of VanillaForums category system, and yes, I own a Minecraft server, don't hate.
![](http://i.imgur.com/GPpcjYm.png)

**Comment by Ktar5** [comment]
Woot! Things happening

**Comment by julianlam** [comment]
:shipit: Long way to go...

**Comment by pichalite** [comment]
:+1: awesome
