### ISSUE TITLE
"Click to verify" Error

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2465]
Alert shows up when a user tries to post but their account is not verified

* [ ] If not verified, posting a new topic should throw an alert
* [ ] If not verified, posting a reply should throw an alert
* [ ] If not verified, sending a chat message should throw an alert
* [ ] Ensure that all three cases utilise the same code
* [ ] After clicking on the alert, a modal should appear with confirmation that a verification email was sent (is it an alert now? Perhaps bootbox is better suited)

**Comment by pitaj** [comment]
Also, provide the option to send another email.
