### ISSUE TITLE
template.match Javascript TypeError

### ISSUE THREAD

**Issue by rahilwazir** [NodeBB/NodeBB#2466]
I'm getting error in console

> template.match is not a function

```
function checkConditional(template, key, value) {
    var matches = template.match(makeConditionalRegex(key));
```

Problem persist on both Lavendar and Vanilla theme. Already update with recent commits of `v0.6.0-dev`.

**Comment by FishbaitHarry** [comment]
FYI I had the same error and I managed to find that it was just a widget problem - I had some widgets added to the homepage, but the plugins that provided these widgets were disabled. I removed all widgets and it started working.
