### ISSUE TITLE
Notification count 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2467]
So I had 18 notifs, and I clicked on the icon, and clicked on a link that took me to a certain topic.

Now the 18 disappeared... Intended? Shouldn't this be 17 now until I clear all of my notifs? (I think this is how Facebook operates... but I'm not sure if this makes sense, hence the `question` label on this issue)

**Comment by justinlosh** [comment]
I agree, if you can make it so when you click one notification, it marks that one read. Add the option to clear all notifications.
