### ISSUE TITLE
Allow binding to unix domain socket

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2497]
Currently NodeBB binds to port numbers (e.g. `4567`), but it would be beneficial, especially on servers with high load, if binding via a unix domain socket was possible.

I'd just override `port`, since it behaves similarly...

**Comment by VincentTide** [comment]
@julianlam Hi Julian, I would like to bind nodebb to a unix socket as well for performance reasons. Can you share how you did this?

Thanks.

**Comment by psychobunny** [comment]
Hey @VincentTide please post on our community at https://community.nodebb.org :)

**Comment by VincentTide** [comment]
@psychobunny My apologies, I will submit a post there instead. :)

**Comment by psychobunny** [comment]
Nah, no need to apologize. Questions like these are best posted on our community because it makes it easier for others to find in future :)
