### ISSUE TITLE
Package Manager - For version 0.7

### ISSUE THREAD

**Issue by sinofanger** [NodeBB/NodeBB#2499]
https://packages.nodebb.org/
@julianlam  I recently remembered your idea where you were thinking of a packages website so that users can review and vote on plugins.

Here are some suggestions to your original plan. These suggestions might seem farfetched for a young project. But in the long run it will be helpful. Once NBB starts getting more plugins and themes, the current way of organization will be very confusing for normal users (non power users) who just want to run a community based on NBB.

1) The website, packages.nodebb.com, should host all the plugins for NBB instead of pulling them from github or NPM. There should be proper categories like productivity, social media etc for the plugins.

2) The registered members should be allowed to upload plugins to the site.Any registered member should be able to  upload a plugin in zip format, after filling out a form providing details like description, screenshots, faq, about their plugin or theme. Once the editors approve it, it can be published.  At the end of every week, one of the nodebb team members can go through the submitted plugins and approve or decline it. 

3) In the ACP of NBB, the plugins and themes list should be generated based on the database of packages.nodebb.org instead of pulling from Github or NPM. This will give give the main community more flexibility in removing obsolete plugins or labeling these plugins as outdated. So users can avoid installing plugins which has the label "outdated" 

4) Rather than providing voting options in the website (which WordPress tried and failed), the voting ability should be provided inside the ACP, where each plugin or theme has two options to vote "works" or "breaks", after selecting the version of NBB. This will encourage every admin who uses NBB to vote right from their ACP. 
![screenshot_2](https://cloud.githubusercontent.com/assets/9476430/5326570/94986826-7d45-11e4-9894-1cb92a148900.png)

5) For each registered member of packages.nodebb.org website, their profile can show details like their most downloaded plugin, most rated plugin etc. More like this leaderboard feature in the original plan. Also an option for them to re-upload any updated versions of their plugin.
![screenshot_3](https://cloud.githubusercontent.com/assets/9476430/5326595/3da2ee54-7d47-11e4-8ddb-5a5faf8cf3d6.png)

6)The website should have a "sign in with nodebb" option along with github so that users of community.nodebb can login with their credentials.

Hope you guys try to go through these suggestions and give it a thought. This is a lot of work, but try to implement this or a version of this "packages.nodebb.org" idea before releasing 0.7.

**Comment by pitaj** [comment]
Also, any bugs should be automatically posted to the plugin's issues page on Github if possible.
