### ISSUE TITLE
User Profile Fields - version 0.7

### ISSUE THREAD

**Issue by sinofanger** [NodeBB/NodeBB#2500]
The user profile could use some polish. As of now profile fields are very limited. A forum/community/message board user profile should have fields and sections. 
Try taking these ideas for example:
-- "About Me" section - a small bio of the user with mardown or wysiwyg editor enabled.
-- Ability to add a cover pic. The cover pic can be displayed behind the profile pic with a slight blur effect. 
-- Most upvoted posts made by the user
-- Social Network links for the user. 
-- Push down the "Recent Posts" section of the user to the bottom most part. When we visit a user's profile in a big community. It is to know more about him or her. So the data like bio, social network links, age, country and all should occupy the upper part of a profile instead of "recent posts"
![screenshot_4](https://cloud.githubusercontent.com/assets/9476430/5326629/fa147480-7d48-11e4-88ed-70b190391c01.png)

These are some basic necessities which should be inbuilt rather than outsourced from plugins. Plugin authors can make more extensions like more social network inclusions, social network cross posting, blog functionality etc. But the above mentioned options are some which should come pre-built in a next generation app like NBB.

**Comment by pitaj** [comment]
Just have a Markdown description and a cover photo. The use can include whatever links, etc they want that way.

**Comment by barisusakli** [comment]
Yeah thinking about adding a "about me" section that is parsed as MD that is only visible on the users profile.
