### ISSUE TITLE
A

### ISSUE THREAD

**Issue by Miaourt** [NodeBB/NodeBB#2508]
a

**Comment by Master-Antonio** [comment]
I didn't find the discussion on the forum.
Im really interested to use this mechanism.

**Comment by julianlam** [comment]
Use the config as per OP.

**Comment by Master-Antonio** [comment]
A ok, work all perfectly?
Nodebb do all automatically?

**Comment by akhoury** [comment]
OP has 
```
    "database": "redis",  //<-- shouldn't that be mongo ?
```
