### ISSUE TITLE
Posts from child categories are not shown on the home page.

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#2549]
This becomes an issue when the parent category does not contain any posts directly, but has several child categories. Is there a way to adjust this behavior? If anyone could point me in the right direction it would be much appreciated! :smile:

**Comment by barisusakli** [comment]
See answer here https://community.nodebb.org/topic/3603/is-it-possible-to-display-previews-from-child-categories-when-the-parent-has-no-posts

**Comment by lots0logs** [comment]
I posted a reply explaining why this issue is still not resolved. I do appreciate the response though!

**Comment by pitaj** [comment]
It would be possible to create a plugin that, on category change, would cache a multidimensional array and then that array could be inserted into the template.

This would require a hook for category modifications.
