### ISSUE TITLE
Email confirmation issue when registering though twitter sso

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2560]
When I register using twitter, email address is getting populated with "undefined".

![screen shot 2014-12-28 at 11 39 32 pm](https://cloud.githubusercontent.com/assets/10014774/5566393/e99c9aec-8eeb-11e4-8e55-fe9fbff07001.png)

When I click on this notification on nodebb, I get the success notification message that the email is sent.

If I go to the user profile page, click "Edit", I can see the "Confirm Email" button and when I click on it, the success notification message is displayed.

nodebb v0.6.0
NodeBB Twitter SSO v0.5.1

**Comment by pichalite** [comment]
@barisusakli I am seeing this message in ACP. I already have an email address for the user I am logged in as.

![screen shot 2015-02-23 at 10 57 20 am](https://cloud.githubusercontent.com/assets/10014774/6334654/f9f35aee-bb4a-11e4-965d-ea58ae7742c5.png)

**Comment by barisusakli** [comment]
Thanks fixing.

**Comment by barisusakli** [comment]
Can you give it another shot.

**Comment by pichalite** [comment]
:+1: fixed
