### ISSUE TITLE
Passive tracking of topic views (sessionStorage) for anons

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2563]
Ironically, this is quite simple to do, but isn't really a *big* problem:

### Expected

1. While browsing anonymously, observe that topics 1 and 2 are marked unread (either due to "blue bar" shown to left of topic [on lavender], or in unread list).
1. Read topics 1 and 2
1. Log into NodeBB
1. Topics 1 and 2 are no longer marked unread, as their activity during the anonymous session has been saved post-login to their account

### Actually

* Topics read as anon are still unread after logging in

### Notes

* sessionStorage > localStorage as this is just incidental data that isn't all that important (plus makes it easier to handle cases where multiple accounts are used on one machine)

**Comment by psychobunny** [comment]
@julianlam, 9 months later what is your opinion of this issue? Not sure if there's interest so I thought I'd ping you (just cleaning up issues)

**Comment by barisusakli** [comment]
Imo it shouldn't be marked read lets say person A opened the forum as anon on my computer and read topic x,y,z then I login and those topics are magically read.

**Comment by psychobunny** [comment]
If you inplement this, you can't take into account somebody using a diff browser as anon and then switching to another browser and its unread

Probably more trouble than its worth

**Comment by julianlam** [comment]
Adds complexity for relatively little gain.
