### ISSUE TITLE
Global footer code disappears after upgrade / clean install

### ISSUE THREAD

**Issue by baerrus** [NodeBB/NodeBB#2570]
Steps to repro:

1. Start with a running instance of nodebb which has some global widget code. For example, it has a global footer code customized.

2. Stop the running instance

3. Create a new workplace and install and configure by executing  './nodebb setup' another instance of nodebb. Point the new instance to use the same database. Launch it.

Result: The new instance picks up everything like content, view statistics, except that all custom widgets are wiped out. So the new instance renders a default global footer.

Expected: All custom widget code must be preserved. This is causing a problem in upgrades!

**Comment by julianlam** [comment]
@psychobunny Does a NodeBB setup rewrite widgets? It shouldn't afaik...

**Comment by psychobunny** [comment]
It doesn't, so there's something else going wrong here. 

Same version of the widgets plugin + themes installed, right?

**Comment by baerrus** [comment]
@psychobunny I assume so. I noticed this problem first when upgrading from v0.5.0 to v0.5.3. Then it bit me again when upgrading from v0.5.3 to v0.5.7. The last time it was switching from 0.5.7 to another instance of 0.5.7. So that should have the same set of themes and widget plugin. Note, I never tested this issue on master branch.

**Comment by baerrus** [comment]
Let me know if you have trouble reproducing

**Comment by psychobunny** [comment]
I haven't had the chance to try repro'ing yet but just wanted to throw this out there that most of our hosted NodeBB instances do have custom global footer widgets, and we haven't encountered this problem while doing our routine upgrades

**Comment by baerrus** [comment]
I never do upgrades by pulling latest from github. The way I do upgrades is different from what nodebb docs recommend. I always setup a brand new workspace, install everything there. Copy over config.json, then execute nodebb setup, which adds a few more plugins (wish those were part of regular dependency install). That way I am safe and can always fallback to a working instance, should upgrade encounter problems. Can that workflow hitting some path that is unexpected?

**Comment by julianlam** [comment]
This happens because ./nodebb setup calls `setCopyrightWidget` which replaces the global footer.

https://github.com/NodeBB/NodeBB/blob/master/src/install.js#L419-L427

**Comment by baerrus** [comment]
Great, I can fix that unless you have already.
