### ISSUE TITLE
jquery and require not defined after upgrade to 0.6.0

### ISSUE THREAD

**Issue by Arany** [NodeBB/NodeBB#2572]
Heyo,

I just upgraded from 0.5.7 to 0.6.0 and now the adminpanel is not working at all, I get those errors in the JS console:

    admin:30 Uncaught ReferenceError: require is not defined
    colorpicker.js?v=v0.6.0:9 Uncaught ReferenceError: jQuery is not defined
    admin.js?v=v0.6.0:5 Uncaught ReferenceError: $ is not defined
    nanoscroller.min.js?v=v0.6.0:3 Uncaught ReferenceError: jQuery is not defined
    jquery.event.drag.js?v=v0.6.0:402 Uncaught ReferenceError: jQuery is not defined
    jquery.event.drop.js?v=v0.6.0:302 Uncaught ReferenceError: jQuery is not defined
    jquery.ba-serializeobject.min.js?v=v0.6.0:9 Uncaught ReferenceError: jQuery is not defined
    jquery.deserialize.min.js?v=v0.6.0:8 Uncaught ReferenceError: jQuery is not defined

on the index page itself, require is not defined and I do not see my sidebar any more (dont know if more is missing):

    (index)/:39 Uncaught ReferenceError: require is not defined
    (index)/:688 Uncaught ReferenceError: require is not defined

**Comment by julianlam** [comment]
Sounds like the admin stylesheets have not been loaded (assuming NodeBB itself works outside of the ACP?)

Check vanilla and lavender versions?

**Comment by Arany** [comment]
I am using the vanilla theme, but I cannot change anything in the admin panel, as I clicking on anything doesn't work.

**Comment by julianlam** [comment]
Can you execute "npm ls nodebb-theme-vanilla"?

**Comment by Arany** [comment]
```npm ls nodebb-theme-vanilla
npm WARN unmet dependency /home/valyra/nodejs/nodebb/node_modules/nodebb-plugin-imgur requires winston@'~0.7.2' but will load
npm WARN unmet dependency /home/valyra/nodejs/nodebb/node_modules/winston,
npm WARN unmet dependency which is version 0.8.3
npm WARN unmet dependency /home/valyra/nodejs/nodebb/node_modules/levelup requires semver@'~2.2.1' but will load
npm WARN unmet dependency /home/valyra/nodejs/nodebb/node_modules/semver,
npm WARN unmet dependency which is version 4.2.0
nodebb@0.6.0 /home/valyra/nodejs/nodebb
└── nodebb-theme-vanilla@0.2.8```

I did npm install & npm update already twice, also ./nodebb upgrade

**Comment by barisusakli** [comment]
Disable all custom js and plugins and see if it still happens.

**Comment by kacemlight** [comment]
@Arany , Please can you tell me how you solved your problem ? I have the same now and no one can help me.
