### ISSUE TITLE
Don't send chat notification if the sanitised string is an empty string

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2574]
In @a5mith's case, he sent me the :stuck_out_tongue_winking_eye: emoji

**Comment by a5mith** [comment]
:stuck_out_tongue_winking_eye:

**Comment by barisusakli** [comment]
How do you determine if its empty?

:stuck_out_tongue_winking_eye:  is `:stuck_out_tongue_winking_eye:` after all :laughing:

**Comment by psychobunny** [comment]
Is this a bug? If I send just ":p" via SMS you'll get a notif yeah

**Comment by barisusakli** [comment]
Well I think Julian doesn't want notifications from chat messages that are just emojis.

Maybe notifications are showing up empty if the only content is an emoji?

**Comment by psychobunny** [comment]
then the real bug is: chat notifications should show the unparsed version of the message?

`:p`

**Comment by barisusakli** [comment]
Well I just checked and the chat notifications don't display the chat message anyways.

![image](https://cloud.githubusercontent.com/assets/2583394/6642485/4f5f68cc-c97b-11e4-87c9-451646a50650.png)

**Comment by julianlam** [comment]
The mechanism is... the chat message is parsed as a post, and then the HTML
is stripped out because Pushbullet doesn't do html.

So the image is just completely removed and an empty push is sent haha

**Comment by psychobunny** [comment]
I think you should handle that on pushbullet's end then. UX wise I'd want to receive a ":P" notification, this indicates the person has read and acknowledged my previous message

**Comment by julianlam** [comment]
Ok, will do :y:
