### ISSUE TITLE
Remove duplicate fields from plugin.json

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2578]
package.json field | plugin.json field
---------|-----------
`name` | `id`
`description` | `description`
`homepage` | `url`
`main` | `library`

I propose removing at least the `description` and `url` fields from the `plugin.json` spec. 

Duplication is annoying, confusing, and causes problems. For instance, if I change the description in `package.json` but not in `plugin.json` and publish.

**Comment by julianlam** [comment]
:+1:

**Comment by pitaj** [comment]
Awesome!

**Comment by MegaGM** [comment]
https://docs.nodebb.org/en/latest/plugins/create.html#configuration
Since in the docs nothing was changed, please, give a brief overview somewhere, preferably on the forum, what exactly has been changed?
