### ISSUE TITLE
Cannot install plugins on v0.6.1-dev

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2590]
I get this error when I try to install plugins on v0.6.1-dev
[56135] - error: Error: Attempt to unlock /path_to_nodebb/node_modules/nodebb-plugin-amazons3, which hasn't been locked

**Comment by julianlam** [comment]
Unfortunately unrelated to NodeBB. Give this a shot:

```
$ cd /path_to_nodebb
$ sudo chown -R `whoami` ./node_modules
```

**Comment by pichalite** [comment]
That didn't work. Actually when I was setting up NodeBB, running ./nodebb setup threw an EACCESS error on /Users/xxxxxxx/.npm/_locks/redis-6386c16e1da3fa4d.lock. 

If I use sudo ./nodebb setup, the setup works but I get the errors while installing plugins.

This time I changed the permissions for /Users/xxxxxxx/.npm, then ran ./nodebb setup and everything works fine now.

**Comment by julianlam** [comment]
:+1: Good to know
