### ISSUE TITLE
Cannot flag or delete posts

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2591]
NodeBB v0.6.0 & v0.6.1-dev

![screen shot 2015-01-09 at 11 25 40 am](https://cloud.githubusercontent.com/assets/10014774/5685751/532a63b8-97f2-11e4-8216-a45509087d6e.png)
![screen shot 2015-01-09 at 11 25 56 am](https://cloud.githubusercontent.com/assets/10014774/5685750/53271550-97f2-11e4-9b27-170b9c1393a1.png)

**Comment by julianlam** [comment]
Please update your vanilla/lavender files, let us know if the issue persists.

**Comment by pichalite** [comment]
How do I do that? I just cloned the master and setup a new installation. Am I missing something here?

**Comment by julianlam** [comment]
Hm, you're right, looks like bootstrap needs to be updated. Weird how it broke.
