### ISSUE TITLE
Allow the path in the CSS/LESS array in plugin.json to be a directory 

### ISSUE THREAD

**Issue by Schamper** [NodeBB/NodeBB#2593]
Related to #1729. If you're doing it to one, why not all?

![](http://i.imgur.com/c7NJRa2.gif)

Currently gives:
`error: [meta/css] Could not minify LESS/CSS: EISDIR, read`

**Comment by pitaj** [comment]
+1 :+1:

**Comment by MegaGM** [comment]
+1 for CSS only, but not for LESS.
For LESS, I believe, we should use ``` @import ./blablah ```

**Comment by julianlam** [comment]
Best practices aside (whether we should force devs to use `@import` or not), I see no impediments to this.
