### ISSUE TITLE
Expose api data on normal routes

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2598]
For instance, lets say I have the routes `/calendar` and `/api/calendar` for my Calendar plugin. 

As it stands right now, in order to access the api data, I either have to use the templates.js way and pull the data in inside my template file, or I have to run an ajax request to the api route and grab the data from there. 

I propose adding an `api` field to the global `app` variable. This would allow plugins to simply access `app.api.whatever` to get to their data.

**Comment by barisusakli** [comment]
related https://github.com/NodeBB/NodeBB/issues/1999

**Comment by barisusakli** [comment]
>I propose adding an api field to the global app variable. This would allow plugins to simply access app.api.whatever to get to their data.

I did this yesterday and didn't really like that solution. We end up with a giant json blob in the header. And most of it is unused. Not sure what a better alternative is at the moment.

**Comment by pitaj** [comment]
Try this then:

The data that is passed to `render` has a certain key called `client` or
something, and that object is stored in the app.api object on the client
side.

**Comment by julianlam** [comment]
That would be what we'd like, but that data is not set on cold load. To
have it present there, we'd also need some code to call the /api route, but
that would cause a double-hit to NodeBB.

**Comment by barisusakli** [comment]
#1999
