### ISSUE TITLE
Use jQuery UI Touch Punch for greater mobile support

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2600]
http://touchpunch.furf.com/

It's really cool!

I guess that, for now, I'll have to include it separately :cry:

**Comment by julianlam** [comment]
Which parts of jQuery UI does this supplement? I don't believe we're using too many parts of it in NodeBB... maybe just ACP?

**Comment by psychobunny** [comment]
Well, 8 months later we have touch-to-slide open menus and stuff. I don't know if this is relevant anymore so I'm going to close. Feature request on persona if you want tho :)
