### ISSUE TITLE
[UX] clicking on reply/new topic as a guest 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2601]
Redirects you to the login screen with no messaging at all. 

Either app.alert with instructions or tell the user that she needs to log in or register with a link to go back to browse as guest. (First option preferred and IMO easier)

**Comment by psychobunny** [comment]
Ah I like this one better actually (up for debate):

Rename the button if guest to "Log in to post"

?

**Comment by pichalite** [comment]
:+1:  Rename the button if guest to "Log in to post"

**Comment by barisusakli** [comment]
The only problem with this fix is if guests are allowed to post they will still get a `login to post` text on the button.

**Comment by julianlam** [comment]
They shouldn't, afaik... the logic dictates that if they can post, they see post, and if not, *then* they see "Log in to post"

**Comment by julianlam** [comment]
The edge case is if nobody is allowed to post, then guest will still see "Log in to post", and upon login, *then* the button disappears... but that's ok to me.

**Comment by barisusakli** [comment]
Ahh right if they are a guest and have permission to post then `privileges.topics:create` is true I guess so should be good.

**Comment by dipeshkc** [comment]
hello
