### ISSUE TITLE
plugin.json.scripts is getting overwritten by package.json.scripts

### ISSUE THREAD

**Issue by akhoury** [NodeBB/NodeBB#2604]
Here: 
https://github.com/NodeBB/NodeBB/blob/master/src/plugins/load.js#L212

That breaks backward compatibility, for example, [spam-be-done](https://github.com/akhoury/nodebb-plugin-spam-be-gone) had some default `script` value in `package.json` which is overwriting the [plugin.json](https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/master/plugin.json#L8) `script` value. 

I can easily fix this in the spam-be-gone plugin, but I am a little worried about other plugins.

One potential fix is to let the plugin.json data ovewrite the package.json data when merging, so flip the order, at the file/line mentioned above. That, to me makes more sense as there might be collisions, but the plugin data should take precedence. 

```javascript
var obj = utils.merge(packageData, pluginData);
```

**Comment by akhoury** [comment]
I don't know the implications of switching the merge order, so I'll let you decide wether it's a good idea or not

**Comment by akhoury** [comment]
this is a live issue if you open https://community.nodebb.org/register in incognito mode, the captcha doesn't show, because the `plugin.json.scripts` array is never picked up

**Comment by barisusakli** [comment]
My bad, I don't think we need to merge the entire package.json and plugin.json, let me know if that commit fixes your issue.

**Comment by barisusakli** [comment]
The captcha should show up now as well.
