### ISSUE TITLE
Don't pass deleted posts if you're not admin/mod

### ISSUE THREAD

**Issue by Korrosivo** [NodeBB/NodeBB#2607]
Hi,

In some cases, users must not know that there are a deleted post, even if the message is not shown. NodeBB should only pass posts with { "deleted": true } if you're logged in as admin/mod.

If not logged in or logged in as user, you'll not see the post, if you're logged in as admin/mod, you can show the deleted post with a low opacity through the template, as always.

Thanks guys!

**Comment by pitaj** [comment]
This should be made a group permission aka `Can see deleted posts` and `Can see deleted post content`

**Comment by barisusakli** [comment]
The reason we pass the deleted posts is to make sure pagination doesn't have empty pages, if you want posts gone purge them.
