### ISSUE TITLE
Styling bugs on widget page in ACP

### ISSUE THREAD

**Issue by Schamper** [NodeBB/NodeBB#2610]
@psychobunny 
![](http://i.imgur.com/3ZPSUGh.png)

**Comment by julianlam** [comment]
08e883de44f1523c51dfa5e77fdd23e102534d5e was my attempt at fixing this -- as you can see it fixed the widgets themselves, but not the draft zone or the pills, so possible may want to remove the `col-xs-12` I added and fix it properly.
