### ISSUE TITLE
[UX] User mentions in new topic or reply

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2613]
Cannot click on username to pick user.

![screen shot 2015-01-14 at 3 47 47 pm](https://cloud.githubusercontent.com/assets/10014774/5750454/34c6ee84-9c0a-11e4-9525-16f266f9264a.png)

**Comment by julianlam** [comment]
This seems to be an issue better handled upstream..

**Comment by cnvo** [comment]
The dropdown should turn unto a dropup in this case, depending on the
window height.

**Comment by cnvo** [comment]
A higher z-index as well.

**Comment by pitaj** [comment]
Why was this reopened? Was it fixed or not?

**Comment by julianlam** [comment]
It didn't seem fixed :)

**Comment by barisusakli** [comment]
Fixed zindex in https://github.com/julianlam/nodebb-plugin-mentions/commit/2e7785a24cc50bc21abfdbc10c0ba0590b11584c

dropup doesnt seem to work with textcomplete. Apparently its bugged https://github.com/yuku-t/jquery-textcomplete/pull/129
