### ISSUE TITLE
Width can not be changed (button disappeared)

### ISSUE THREAD

**Issue by Morphy2k** [NodeBB/NodeBB#2617]
Exampel (http://178.62.242.232)

![home - cyonic industries board](https://cloud.githubusercontent.com/assets/4280578/5770067/44f1db72-9d25-11e4-8976-4da0a8572d30.png)

Exists since the changes from 01.14.
I use the master branch.

**Comment by barisusakli** [comment]
There is a javascript error on your home page. Are you on latest from master if so did you update your lavender and vanilla themes as well?

**Comment by Morphy2k** [comment]
Yep, I use the latest version.

Lavender 0.2.10
Vanilla 0.2.15

**Comment by julianlam** [comment]
Try disabling your plugins one by one until you find the plugin that is at fault. It is causing your client-side js to crash...

**Comment by Morphy2k** [comment]
I just pulled the latest commits, now the problem is solved.
Thanks! :)
