### ISSUE TITLE
Can not disable login via username (minor security issue)

### ISSUE THREAD

**Issue by iquidus** [NodeBB/NodeBB#2618]
Currently users can log in with either a username or email, there should be an option to make this email only as usernames are visible to other users and guests, giving attackers a starting point to breach accounts. 

Logging in with email is more secure as a users email can be hidden from other users/guests.

**Comment by dwendt** [comment]
Having this go the other way and disabling login via e-mail would be ideal as well. This way an attacker can't take a list of compromised email+password combos and try them against the site.
