### ISSUE TITLE
Trying to chat with same user as logged in user doesn't display error message

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2619]
Navigating to https://community.nodebb.org/chats/logged-in-username doesn't display any error. Clicking Send after typing a message doesn't do anything.

May be this error message from error.json should be displayed.	"cant-chat-with-yourself": "You can't chat with yourself!"

**Comment by limitmaker** [comment]
I think you should be able to chat with yourself :D.  Facebook does it ;)
