### ISSUE TITLE
no hooks available to filter favourite commands

### ISSUE THREAD

**Issue by TheBronx** [NodeBB/NodeBB#2620]
### The problem I'm facing
I'm developing a reputation rules plugin. Basically what it does is control when a user can upvote/downvote a post. For example, if you have less than 50 messages, you can't downvote. Or if you have voted a user in the last 7 days, you can't upvote him again. 
### How I'm doing it now
I'm using `action.post.upvote/downvote/unvote` hooks (the unvote hook exists, but it's not included in the docu). This hooks are fired AFTER the action has been taken. So, if the vote was not allowed I have to **undo** the vote.  
An example: a post that was upvoted now changes to a downvote. But the downvote is not allowed, so in my plugin I have to **remove** the downvote and **restore** the upvote. This means changes to a few `_key`'s, with functions that are not public. If I try to use the Favourites module then new hooks will be fired (if I try to unvote for example, the unvote hook will be triggered and that would be a mess).
### Easier solution
Fire a hook before the action takes place. Plugins can intercept the action, modify it or cancel it before it is too late. That is, a filter. 
See the pull request.

Let me know if there is something wrong with this. Thank you!

**Comment by barisusakli** [comment]
Closed in pr https://github.com/NodeBB/NodeBB/pull/2621
