### ISSUE TITLE
Can't access admin page on 0.6.0 (local)

### ISSUE THREAD

**Issue by esiao** [NodeBB/NodeBB#2622]
Hello, finally got the time to upgrade my NodeBB and my Plugins but I wan't to check if they're working properly before releasing the updated versions.
And I'm stuck because I can't access the admin panel. The page doesn't resolve and there's no error in the console.

![](http://i.imgur.com/DWhLHJB.png)
![](http://i.imgur.com/p1Oh9jG.png)

Any idea on what it could be ?

**Comment by barisusakli** [comment]
Try resetting themes and updating vanilla, is if it works then.

**Comment by esiao** [comment]
Updated both Vanilla and Lavender and still can't acces to ACP.

**Comment by barisusakli** [comment]
Try resetting all plugins as well.

**Comment by esiao** [comment]
It was linked to a plugin. I'm reactivating them one by one to find the culprit.

**Comment by barisusakli** [comment]
Let us know the plugin if you found it or report it on its repo. Thanks.

**Comment by esiao** [comment]
Didin't find it, I've reactivated all of them and it's working like before the update.
