### ISSUE TITLE
Group chat messages

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2627]
Group chat messages are a necessary feature for NodeBB. 

Essentially just copy what Hangouts does as far as adding people to the chat goes

**Comment by psychobunny** [comment]
https://github.com/NodeBB/NodeBB/issues/1798 please put any comments here for when the system gets refactored :)

**Comment by pitaj** [comment]
@psychobunny Sorry, didn't see that one. Oops
