### ISSUE TITLE
[UX] issue marking topics as read in Unread page

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2633]
If the user has lot of unread topics (I don't know what's the magic number to trigger this issue but lets say 40+), selecting all in the mark as read dropdown displays the message "There are no unread topics." but reloading the page or clicking on "Unread" in the header displays more unread topics.

![screen shot 2015-01-19 at 1 35 17 pm](https://cloud.githubusercontent.com/assets/10014774/5808312/e2f7bfb8-9fe0-11e4-9616-9902e5260bc7.png)

**Comment by barisusakli** [comment]
Right now this is by design although I don't really like it.

Clicking `mark as read>all` only marks the topic that are visible read not everything. So if you were to scroll down and let infinite scroll load more unread topics and then  clicked mark as read > all it would mark everything read.
