### ISSUE TITLE
Infinite scroll stops working

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2637]
I am not able to find the exact steps to reproduce so not sure what's happening.

I have a test setup where I have multiple categories and the nodebb-plugin-rss has feeds that post to these categories. The plugin posts duplicates and topics without any posts. I go through each category and delete and purge these duplicates and empty topics. After I go through 3 or 4 categories suddenly the infinite scroll stops working. I have to refresh the page to get it working.

NodeBB v.0.6.0

**Comment by MegaGM** [comment]
https://community.nodebb.org/topic/3654/posts-getupvoters-socket-io-flood-user-emit-banned

**Comment by julianlam** [comment]
Is this still an issue @pichalite ?

**Comment by pichalite** [comment]
Since the RSS plugin has been fixed I didn't have to delete duplicate topics. Let me check and see if this is still an issue.

**Comment by pichalite** [comment]
@julianlam this issue seems to be related to "Mark as read" in the unread page. I logged in to my test site using a username that hasn't logged in for a while. Navigated to unread page and selected Mark as Read -> All. I see the notification that all topics are marked as read and the unread count is gone. When I go to any category, infinite scroll doesn't work anymore unless I reload the browser window and a lot of topics are still displayed as unread when I go to any category.

**Comment by MegaGM** [comment]
@pichalite I guess symptoms of "socket.io flood - user emit banned" there is in this issue (that link I've mentioned above)
Do you get this message? https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/index.js#L138

**Comment by pichalite** [comment]
@MegaGM I know what you are talking about but I didn't see any messages or errors in the log file.

**Comment by pichalite** [comment]
Issue seems to be resolved. cannot reproduce anymore.
