### ISSUE TITLE
Admin approval re: Registration

### ISSUE THREAD

**Issue by tgezginis** [NodeBB/NodeBB#2638]
Hi everyone,

Nodebb is amazing project and I want to use it. But I didn't find admin approval. I need this feature for new users. I don't want to write up to admins confirm user.

My another request is bulk add users to group. It'll be good feature.

What can i do for it?

Thanks.

**Comment by barisusakli** [comment]
https://github.com/pichalite/nodebb-plugin-newuser-approval

Not sure if we should roll that into core. 
https://community.nodebb.org/topic/3735/nodebb-plugin-newuser-approval-plugin-for-admins-to-approve-new-users/2

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/57c2418157110bd7a0ac4f0f2b460b5baf7834e3
