### ISSUE TITLE
Visual Character Limits on Tags

### ISSUE THREAD

**Issue by justinlosh** [NodeBB/NodeBB#2639]
Hello,
I've noticed that as of late when users enter tags on our forum, they seem to be getting cut off. I think it would be a good idea to set a visual charater limit on each tag.

**Comment by barisusakli** [comment]
You can set the minimum and maximum tag length from the ACP is that what you need?
![image](https://cloud.githubusercontent.com/assets/2583394/5849429/a7db6a18-a1b3-11e4-9e5e-16994c2736a6.png)

**Comment by justinlosh** [comment]
Sort of... So in the picture, you have the maximum tag length set at 24. I was hoping for something that shows 5/24 Characters remaining if you say used 19 characters. Hopefully that makes more sense. This might just be a nice feature in my opinion, but you might want to request for comment if it is something you consider it.
