### ISSUE TITLE
Privileges Error on Group Delete

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#2644]
I'm aware groups are in refactor but I just had this error when I try to delete groups in ACP (as admin obviously).

It tells me I have not the right privileges to do so.

(last update 70f6c396fcb53137d78db0f77122d7b9f0dfb302)

**Comment by julianlam** [comment]
:sunrise: Morning :sleeping:

**Comment by tedr56** [comment]
No problem, not urgent.

Take your coffee first. :smile:

**Comment by tedr56** [comment]
Well done, as usual. Thanks
