### ISSUE TITLE
npm dispute resolution

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2647]
`alebcay <calebcenter@live.com>` is the owner of the package `nodebb` on npm.

[How to file a dispute:](https://www.npmjs.com/policies/disputes)

> Get the author email with `npm owner ls <pkgname>`
> Email the author, CC support@npmjs.com
> Mention in the email that he can run `npm owner add dev_name nodebb` to add `dev_name` as an owner of the `nodebb` package.
> After a few weeks, if there's no resolution, email npm once more, and npm will sort it out

Do the above. Get that package under control!

It would be great to one day be able to do `npm install nodebb` to install and `npm install nodebb@0.6.1` to update!

**Comment by cnvo** [comment]
So, correct me if I'm wrong, but it looks like this person is name squatting packages?

**Comment by julianlam** [comment]
Name squatting? How awful. May as well send him an email.

**Comment by pitaj** [comment]
@julianlam if he doesn't respond or won't cooperate the npm guys will probably give you ownership anyways (since you have ever reason to own it). You just have to try first.

**Comment by julianlam** [comment]
The current owner has kindly added us to the repository as maintainers, and has published the latest development version :smile: 

We'll probably maintain this (though after this, we'll publish only the **stable** versions to npm).
