### ISSUE TITLE
Problem uploading images in latest chrome

### ISSUE THREAD

**Issue by lekoder** [NodeBB/NodeBB#2649]
When trying to upload image in google chrome `40.0.2214.91 m` there is error on js console:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```
Image is not uploaded.

**Comment by barisusakli** [comment]
Just tested uplading in 40.0.2214.91 m worked for me. Was using imgur plugin and uploading to a post. Win8.1.

Any other repro steps?

**Comment by lekoder** [comment]
Updated all plugins to latest versions and problem went away. Considering issue closed - already solved.
