### ISSUE TITLE
Authentication problem - v0.6.x on ARM

### ISSUE THREAD

**Issue by Couby** [NodeBB/NodeBB#2650]
Coming back recently on my forum, after several weeks away from it, I had the surprise not being able to connect it.
I had some issues migrating to v0.6.0 but it was working when I left it.

I copied the dump.rdb and reinstalled NodeBB.
But no change, I'm still unable to connect again my forum :-/

I feel a bit trapped and don't see what to do more...

Any idea ?

**Comment by Couby** [comment]
Would it work/is there a way : reinstall from scratch again and import users and content from the dump.rdb ?

**Comment by pitaj** [comment]
Have you tried starting it in Dev mode? What errors are there?

**Comment by Couby** [comment]
Just made a try with NODE_ENV=development but I don't see errors in logs.
Here's the forum : http://forums.fabriques-alternatives.org .
Registration doesn't work also.
I'm missing something...

**Comment by psychobunny** [comment]
I think he means he's unable to log in? Is that the case?

**Comment by barisusakli** [comment]
There is a js error on your register page
`Uncaught TypeError: Cannot read property 'match' of undefined`

**Comment by Couby** [comment]
@psychobunny yes that's it.

**Comment by Couby** [comment]
Could there be something related to the secret setup settings ? As I'm replacing dump.rdb by my backup but not the new secret due to reinstall ?

**Comment by psychobunny** [comment]
There's definitely something wrong with your forum, when registering I received this error

`Erreur d'enregistrement

<html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html> `

It successfully created my user though, and when I tried to log in I received a similar error:

`Echèc d'authentification, veuillez réessayer.

<html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html> `

Can you reproduce this, and when you do can you please paste the server logs as well?

**Comment by Couby** [comment]
Hi @psychobunny ,
Yes I encountered this also.
I'll take a look tonight and will report what I have in server logs.

**Comment by Couby** [comment]
@psychobunny around the time of your message, here is what I have in the logs : 
> 2015/01/27 10:32:21 [error] 4998#0: *86944 upstream prematurely closed connection while reading response header from upstream, client: 173.206.74.28, server: forums.fabriques-alternatives.org, request: "POST /register HTTP/1.1", upstream: "http://127.0.0.1:4367/register", host: "forums.fabriques-alternatives.org", referrer: "http://forums.fabriques-alternatives.org/register"

> 2015/01/27 10:32:58 [error] 4998#0: *86944 upstream prematurely closed connection while reading response header from upstream, client: 173.206.74.28, server: forums.fabriques-alternatives.org, request: "POST /login HTTP/1.1", upstream: "http://127.0.0.1:4367/login", host: "forums.fabriques-alternatives.org", referrer: "http://forums.fabriques-alternatives.org/login"

In the former days many errors are more like this one : 

> 2015/01/24 20:13:45 [error] 4998#0: *81592 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.64, server: forums.fabriques-alternatives.org, request: "GET /socket.io/?EIO=3&transport=polling&t=1422130425894-172 HTTP/1.1", upstream: "http://127.0.0.1:4367/socket.io/?EIO=3&transport=polling&t=1422130425894-172", host: "forums.fabriques-alternatives.org", referrer: "http://forums.fabriques-alternatives.org/"

So maybe more on Nginx side ? ...
Making some search on this 111 error.

**Comment by Couby** [comment]
Still stuck in the mud :-/
I made a try using varnish as I read someone solving such similar problem with that : 
http://ashtonandgray.com/topic/183/nginx-errors-connection-timed-out-while-reading-response-header-from-upstream
http://forum.linuxbsdos.com/topic/184/how-to-configure-varnish-for-websocket-traffic

But nope, no change.

Something I notice is that after some of you made tries and registered the forum, the number of users jumped from 6 to 11.
I made a reboot and I see back 6 users registered.

Could it be more something related to Redis ?

**Comment by Couby** [comment]
A new report about my morning search.

I removed the Nginx layer, accessing directly the forum via ip:port.
Error is **Failed login attempt, please try again.** a litlle bit different of 502 report when trying to log from url.

I reinstalled Redis from scratch with recompilation.

I installed a fresh new NodeBB **v0.6** (no replacement of dump.rdb). 
And I still have the same error **Failed login attempt, please try again.**.
No way to connect this fresh new forum.

Strange.

I decided then to make install a fresh new NodeBB **v0.5.x** : **this one works fine**, I can connect the forum !

There is something specific with v0.6 and my system, but what ?
Could it be related to the arm architecture as this is an Olinuxino A20 ? ...

**Comment by Couby** [comment]
Just made a try with a fresh NBB stable (v0.6.1-dev) also. Same. No way to login with administrator account.

I tried v0.6 on my computer and its working fine.

This problem is clearly related to the system or hardware (Olinuxino A20).
My forum is back in v0.5.7 for the moment on this dev board.
Could be the moment for me to migrate it from the dev board to a VPS. 

Are there any people who could test on such or similar board (Rpi) ?

**Comment by barisusakli** [comment]
Hmm try swapping out brcyptjs to bcrypt see if that helps. https://github.com/NodeBB/NodeBB/blob/master/bcrypt.js#L4

**Comment by Couby** [comment]
Yeeah, that works ! :-)

Thank you @barisusakli .

Don't know if something can be done so that ARM users (if that's effectively the origin of the problem) don't have to fix this manually each update... :-/

At least this fix exists :-).

Do you think we should close this issue or keep it open ?

**Comment by julianlam** [comment]
It's been an issue with ARM devices in the past (RPi is the only one I have, actually), where the bcrypt library we use, bcryptjs, isn't quite as performant as the native version (bcrypt).

I don't quite know why it was ok in v0.5.x but not v0.6.x, but it could be any multitude of reasons! :smile: 

Glad you got it working though.
