### ISSUE TITLE
Client side hook for when all core Javascript finishes

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2651]
This would be a good feature, so plugin developers don't have to use timeouts to execute their code after core.

**Comment by psychobunny** [comment]
This would be `action:ajaxify.end` :)

**Comment by pitaj** [comment]
A description in the docs would be grrrrreat

**Comment by psychobunny** [comment]
![](http://i.imgur.com/jz8mjhw.png)

**Comment by psychobunny** [comment]
Made an issue, I'll make sure to write something up on this when I get hte chance
