### ISSUE TITLE
Reply by email functionality

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2652]
Just something I've been working on recently... :smile: 

This functionality would enable you to respond to a topic simply by replying to the email notification for it. It does require some admin configuration, which is why it's been a bit of a sticky subject to implement.

Latest commits in NodeBB's master branch add the ability to receive an email notification every time somebody responds to a topic you are subscribed to.

These emails have a `Reply-To` header containing `reply-{pid}@{receive_domain}`, and a corresponding emailer plugin handles emails coming *back to that address*.

As of today, the Mandrill plugin has a beta version of this reply-handling code, **it has not been pushed to npm**.

To give it a try:
```
$ cd /path/to/nodebb/node_modules
$ rm -rf nodebb-plugin-emailer-mandrill
$ git clone git@github.com:julianlam/nodebb-plugin-emailer-mandrill.git -b incoming && npm install
```

... and then configure the plugin in the ACP.

### To Do

* [x] If the reply pid does not exist, NodeBB shouldn't crash
* [ ] If the reply pid does not exist, NodeBB should notify the original sender
* [x] ~~If the uid doesn't exist, NodeBB shouldn't crash~~
* [x] If the uid doesn't exist, NodeBB should post it as a guest if guests can post to that category
* [x] Figure out bouncing. If the route isn't configured properly, does Mandrill send a bounce back to the user?
* [x] Handle quoted material... should the emailer parse posts so that quoted text at the bottom of a reply is minimised?

**Comment by justinlosh** [comment]
If a uid doesn't exist, maybe the option to delete the email and do nothing (or reply with error).

**Comment by pitaj** [comment]
Make everything a configurable option of you are trying to figure it out.

**Comment by julianlam** [comment]
Effort :rage2:

**Comment by pitaj** [comment]
Oh, and move it to a plugin :P

**Comment by julianlam** [comment]
Yeah, every part of it should be already, NodeBB just handles the plugin hooks to send emails.

**Comment by julianlam** [comment]
Done, pending merge into Mandrill plugin by @akhoury : https://github.com/akhoury/nodebb-plugin-emailer-mandrill/pull/9

**Comment by akhoury** [comment]
nodebb-plugin-emailer-mandrill@0.2.3 is published
