### ISSUE TITLE
Upgrade script doesn't generate group slugs properly

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2655]
https://github.com/NodeBB/NodeBB/blob/master/src/upgrade.js#L691

Seems `Groups.list` doesn't actually pick up the proper groups, so no slugs get generated except for the administrators group.

**Comment by julianlam** [comment]
Also, after upgrade, the "Latest Posts" block isn't populated, odd...

https://community.nodebb.org/groups/3rd-party-developers

**Comment by julianlam** [comment]
Hahaha Baris... :goberserk: -- latest code calling Groups.list thinks it's a zset, hence returns `[]`, even though the upgrade script for it is afterwards.

**Comment by barisusakli** [comment]
Hmm upgrade scripts shouldn't use the wrappers and use the db.XX methods directly?

**Comment by julianlam** [comment]
yeah agreed. I just slacked off on that one.
