### ISSUE TITLE
Unread count not updated correctly

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#2664]
I have this strange behaviour with the Unread Post count.

The Unread Count is sometimes not updated at all. With new & existing topics.
But unread posts are showing up in /unread and notifications are corrects too.
It seems to happen randomly. I can't figure the behaviour behind this.
Maybe it's linked with the fact my NodeBB tab is constantly open.

It's happenning for a while now. I would say since 0.6.0.

And it's happenning to other users too.

I know it's pretty vague but if you have an idea...

**Comment by barisusakli** [comment]
This was by design, if you were not active in the past 5 minutes the system didn't send new posts to the client. I have added some code that will push the unread code when you  ajaxify so the count should update as soon as the user navigates for the first time.
