### ISSUE TITLE
Latest v0.6.x doesn't deliver content when certain text occurs in post content

### ISSUE THREAD

**Issue by sweetpi** [NodeBB/NodeBB#2666]
NodeBB times out when the following text is posted:

```
if [[ -z $challenge ]]; then
```

All pages where this post content should be rendered are not working anymore. 
Steps to reproduce:

1. Clone the v0.6.0 branch
2. Run Setup
3. Login and post the text above.

Is this a known bug? It seems to be fixed in the master branch, but I don't want to update to the dev version. **Don't try this with your production forum**, you have to remove the post from the database manual, because the post can't be accessed with NodeBB anymore.

**Comment by barisusakli** [comment]
Yes this is fixed on latest we should backport to 0.6.x

https://github.com/NodeBB/NodeBB/blob/master/public/src/translator.js#L163-L165

**Comment by sweetpi** [comment]
Thanks for the fast reply. I've submitted a pull request.

**Comment by psychobunny** [comment]
Thanks :) I still remember Baris and I trying to fix this at like 3am or something

**Comment by sweetpi** [comment]
> Thanks :) I still remember Baris and I trying to fix this at like 3am or something

I tried to find it by debugging me with console.logs through the code to find the missing callback call, but couldn't find it. So I'm very happy about your quick reply. Very nice forum, keep up the good work!
