### ISSUE TITLE
Editing / Deleting Chats

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2668]
1. Clickable settings icon with edit / delete on each message
2. Pressing "up" on keyboard should automatically allow editing

**Comment by julianlam** [comment]
I think @Schamper has some experience with editing and deleting things like chat messages :smile: 

#autoassigned

**Comment by Schamper** [comment]
Hehe.. I'll see if I get around to it ;)

**Comment by julianlam** [comment]
@pichalite Please note the theme changes for new components, etc, as listed above.
