### ISSUE TITLE
Restrict plugins from creating topics without any posts

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2669]
Topics without any posts don't show up in /unread and cannot be marked as read from this page (nodebb-plugin-rss sometimes creates topics without any post). May be we should have the same restriction for plugins as we have in the UI that you cannot create a topic without a post.

**Comment by julianlam** [comment]
This seems to be an issue with the RSS plugin calling Topics.create instead
of the proper Topics.post, perhaps Baris can confirm?

**Comment by barisusakli** [comment]
It does use topics.post() https://github.com/barisusakli/nodebb-plugin-rss/blob/master/index.js#L205

The plugin was just trying to post 4 times because of cluster. Should be fixed on latest rss plugin.
