### ISSUE TITLE
There is no way to unfollow a topic

### ISSUE THREAD

**Issue by xusoo** [NodeBB/NodeBB#2674]
With the latest changes, the `follow` function in `src/socket.io/topics.js` has changed from:

```javascript
SocketTopics.follow = function(socket, tid, callback) {
    if(!socket.uid) {
        return callback(new Error('[[error:not-logged-in]]'));
    }
    threadTools.toggleFollow(tid, socket.uid, callback);
};
```
to:

```javascript
SocketTopics.follow = function(socket, tid, callback) {
	if(!socket.uid) {
		return callback(new Error('[[error:not-logged-in]]'));
	}

	topics.follow(tid, socket.uid, callback);
};
```

but the follow button's click event still calls 'follow' regardless of the following state:

```javascript
$('.posts').on('click', '.follow', function() {
	socket.emit('topics.follow', tid, function(err, state) {
		...
	});

	return false;
});
```

so now, there is no way to unfollow a following topic :(

I guess the solution is just change `socket.emit('topics.follow')` for `socket.emit('topics.toggleFollow')`, isn't it?

**Comment by barisusakli** [comment]
Yeah already fixed on 0.7.0 branch looks like we forgot to add to master.

**Comment by xusoo** [comment]
Ah, didn't notice, sorry. Also, now that I'm trying it, it would be nice to change text from "Follow" to "Unfollow" (and viceversa) when user clicks.

**Comment by barisusakli** [comment]
That should already be the case, it changes between watch unwatch when I click it on lavender theme. Is it not working for you?

**Comment by psychobunny** [comment]
Actually that's not the case, I had to add some magic in some other theme to change the text:

```
$(window).on('action:ajaxify.end', function(ev, data) {
		$('.favourite').on('click', function() {
			var $this = $(this),
				fav = $this.attr('data-favourited');

			$this.html(fav === 'false' ? 'Unfollow' : 'Follow');
		});
});
```

So, that kind of sucks. See here https://github.com/psychobunny/templates.js/issues/6 for some idea on what we're trying to do to avoid this problem in future

**Comment by barisusakli** [comment]
Thats favourite, this is for follow. But yeah it depends on certain DOM elements so :-1: 
https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic/threadTools.js#L150-L165

**Comment by xusoo** [comment]
Oops, my fault. There was a bug in the topic.tpl of my theme. Now is working, thank you both :+1:
