### ISSUE TITLE
Don't minify js if in dev mode

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2678]
This would be pretty helpful for debugging what is going on.

**Comment by julianlam** [comment]
Development mode js is concatenated, and not minified, as far as I know... it's still one file, but that makes it easier for NodeBB to not have multiple behaviour paths for dev vs. prod.

**Comment by pitaj** [comment]
Okay. How do I run in Dev mode on windows BTW?

**Comment by julianlam** [comment]
Not sure -- when I use windows, I just use `git bash` and run `./nodebb dev` like always.

**Comment by MegaGM** [comment]
> Okay. How do I run in Dev mode on windows BTW?

AFAIK you can set ``` NODE_ENV='development' ``` in your environment, then run ``` node app.js ``` as usual, it should work.

> to revamp the entire system to use grunt or gulp

gulp please! ![](http://smayly.ru/gallery/anime/RedFox/22.gif) it's really handy-dandy thing. It's next generation tool relative to grunt and so on.
