### ISSUE TITLE
Groups - Modifying the group name revokes privileges

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#2679]
Created a ``group`` -> Changed the ``group title`` (and saved) -> Changed the ``group title`` (again, and saved) -> Changed the ``group tag title`` -> Refreshed the page, and this would be the result;

![screen shot 2015-02-01 at 8 36 02 am](https://cloud.githubusercontent.com/assets/113159/5992220/d3c7b266-a9ed-11e4-9b2f-34e7aab5985c.png)

Not once did I actually leave the group.

**Comment by julianlam** [comment]
Is this on our forum? I believe the latest code might have resolved this
already

**Comment by cnvo** [comment]
Yeah, this is on the community forum.

**Comment by barisusakli** [comment]
@julianlam sounds like privilege groups are never renamed?

**Comment by barisusakli** [comment]
Nvm https://github.com/NodeBB/NodeBB/blob/master/src/groups.js#L541-L547 seems to rename all group members including privilege groups.

**Comment by julianlam** [comment]
yeah community just needs to be updated.
