### ISSUE TITLE
incorrect link to uploaded avatars is email digests

### ISSUE THREAD

**Issue by arasbm** [NodeBB/NodeBB#2681]
I [reported this bug on the forum](https://community.nodebb.org/topic/3752/uploaded-avatars-do-not-show-up-in-email-digest).

For example, an avatar in email digest seems to be pointing to this location:

`https://ci5.googleusercontent.com/proxy/SwWh9ksJkkmyRq6cRBz7HQVkhBAclT3OV_IBabx3kUeX6cPO3dLrhwusl3izP0DcxTRnvjZaJgR7OML2wm7F=s0-d-e1-ft#http:///uploads/profile/24-profileimg.jpg`

where in fact it is located here:
`http://community.kamloopsmakerspace.com/uploads/profile/24-profileimg.jpg`

![selection_066](https://cloud.githubusercontent.com/assets/193687/5994658/321b3a3e-aa31-11e4-9317-60bebaa28da4.png)

**Comment by julianlam** [comment]
When we uploaded images locally, NodeBB would save the relative path into the database. If imgur, it saves a link. This is why some images work and some don't.

**Comment by julianlam** [comment]
... but then if the site's URL changes, all the images lose their mapping... let me investigate other fixes...

**Comment by surajdalvi** [comment]
I got the  same issue in **NodeBB 7.0**  but instead of avatars it show me username. but I want to show user avatars in digest. How I fix this help me?
