### ISSUE TITLE
maximum post length setting in acp

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2685]
What is a good default? 5000 chars? :rage1:

**Comment by MegaGM** [comment]
32767? Just because

**Comment by barisusakli** [comment]
Ahhh signed short int

**Comment by kevinfmoody** [comment]
Just ran into a bug with the following line:

    config.minimumPostLength = meta.config.maximumPostLength;

should be

    config.maximumPostLength = meta.config.maximumPostLength;

in /src/controllers/api.js.

**Comment by barisusakli** [comment]
@kevinfmoody thanks for pointing it out.
