### ISSUE TITLE
Use JSDoc for automated documentation

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2688]
http://usejsdoc.org/

It works a lot like JavaDoc or PHPDoc:

```javascript
/**
 * Represents a book.
 * @param {string} title - The title of the book.
 * @param {string} author - The author of the book.
 */
function Book(title, author) {
}
```

**Comment by psychobunny** [comment]
We're going to do this for plugin hooks, but I think it would be too cumbersome to do it for every single method in NodeBB and keep it updated.

I think for  your average plugin developer ideally this should be enough

(See: https://github.com/NodeBB/NodeBB/issues/2729)
