### ISSUE TITLE
emoji-extended and imgbed do not show up in the plugin list

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2689]
@bdharrington7 @frissdiegurke 

Kind of weird, most likely a bug with nbbpm. Just tracking it here.

Version suggestion seems to work fine, though:
* https://packages.nodebb.org/api/v1/suggest?package=nodebb-plugin-emoji-extended&version=0.6.0
* https://packages.nodebb.org/api/v1/suggest?package=nodebb-plugin-imgbed&version=0.6.0

**Comment by pichalite** [comment]
I can't find nodebb-plugin-sso-facebook in the plugin list anymore.

**Comment by julianlam** [comment]
@pichalite then I suppose it's a good thing I'm fixing this isn't it ;) 

I'm in the process of refactoring the whole syncing system. 

Go go gadget reinvent wheel!

**Comment by julianlam** [comment]
Closed by above commit
