### ISSUE TITLE
guests can join groups and show up in user list

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2690]
https://community.nodebb.org/groups/russians

**Comment by julianlam** [comment]
hm, I actually tried to reproduce this the other day to no avail.

Does this happen on latest code?

**Comment by barisusakli** [comment]
Was only reproducable with socket.emit() there was no server side check.
https://github.com/NodeBB/NodeBB/commit/311fd00ecdd45a4a2037e62250784ae0637b6d76

**Comment by MegaGM** [comment]
It was me. I've planned to make an issue, but you faster.

**Comment by MegaGM** [comment]
I did it again, sorry ![](http://smayly.ru/gallery/anime/RedFox/30.gif) https://community.nodebb.org/groups/gnu-linux-user

**Comment by MegaGM** [comment]
related https://github.com/NodeBB/NodeBB/pull/2693

**Comment by barisusakli** [comment]
@MegaGM just to make sure, did you do a socket.emit()? try isn't updated yet to latest code.

**Comment by MegaGM** [comment]
Yup, ``` socket.emit( join ); ``` works yet for guests. Nothing else, but ` join ` only. I'll try to boogie-woogie with groups, when code will be updated.

**Comment by MegaGM** [comment]
Oh, sorry,  ``` socket.emit( leave ); ``` works as well.

**Comment by barisusakli** [comment]
Updated our forum as well.
