### ISSUE TITLE
[acp] Make the right sidebar fixed

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2696]
I dislike the requirement to scroll all the way up to the top of page to do things.

**Comment by julianlam** [comment]
Right sidebar inside of individual plugin pages? That's on a per-plugin level, actually, so that's a bit harder to do...

**Comment by pitaj** [comment]
I only meant for core pages like groups, categories, etc...

**Comment by julianlam** [comment]
http://getbootstrap.com/javascript/#affix

Send PR please :smile: 

I believe I tried this awhile back, but I don't *quite* remember why it didn't work...

**Comment by pitaj** [comment]
Alright, will do.

**Comment by psychobunny** [comment]
+1 good idea
