### ISSUE TITLE
[acp] Google Docs style user presence

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2699]
Would be nice to add profile image on the header to see if another admin is in that "room". Clicking on the avatar should open up a chat

**Comment by julianlam** [comment]
Superceding the list in topics? I love that idea :+1: 

Bonus points for reading user-agents to have special icons for bots :smile:

**Comment by psychobunny** [comment]
ACP sorry if that wasn't clear. So I don't overwrite something someone else is working on

**Comment by MegaGM** [comment]
It will become NodeBB's killer feature!

**Comment by psychobunny** [comment]
Since the browsing users functionality was removed out of core I think this idea is probably overkill (whereas originally, might have just been able to reuse the same code)
