### ISSUE TITLE
Publically created groups

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2701]
Admin controls (ex. delete group) needs to be visible on group page - I shouldn't have to join the group in order to moderate it, as an administrator

**Comment by julianlam** [comment]
Code is structured in such a way that the only check made is to determine whether the calling user is an owner prior to deleting/editing. Adding checks for admin would increase complexity (for both backend and UI), which would normally not be an issue, *except* groups can be deleted with impunity from the ACP.

Let me know if you still want this

**Comment by MegaGM** [comment]
I guess, if you an admin, it should be ok for you, to be going in ACP for such things like groups deleting etc.

**Comment by pitaj** [comment]
I agree with @MegaGM and @Julian - I don't think it's worth the effort.

**Comment by psychobunny** [comment]
Hmm

```
<!-- IF isAdmin -->
Add button to go to ACP directly
<!-- ENDIF isAdmin -->
```

?

**Comment by psychobunny** [comment]
I might have changed my mind about the above: 

Yeah it's extra work, but we should keep in mind the trend we have set of being able to moderate things within the forum itself (ex. we put a lot of effort for admins to be able to delete posts or topics within the forum itself)

Also, keep in mind if you have 1000's of groups, will be an extra X amount of steps to locate the group in the ACP and then delete.

**Comment by MegaGM** [comment]
> the above solution I proposed can bring you straight to the group in the ACP
Looking forward to it too :crying_cat_face: (separate page for managing groups in ACP)
