### ISSUE TITLE
filter:widget.render returns string

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2702]
https://github.com/NodeBB/NodeBB/blob/master/src/widgets.js#L38-L42

If there are no hooks it returns the passed in object, if there is a hook it returns a string.

Was causing crashes if widget-essentials was disabled.

Temp fix https://github.com/NodeBB/NodeBB/commit/d3aa353d73d474ca26d5592e0451107f4360fc7f

Filters should return the same object that is passed in and add stuff into that object or modify properties of that object

**Comment by julianlam** [comment]
Agreed, as widget plugins expect the argument to be an object, if there are two widgets that listen to the same hook, the first will get the object, and the second will get the string.

Looks like @psychobunny will need to refactor widget essentials for this.
