### ISSUE TITLE
Problem with groups and Access control in 0.6.1

### ISSUE THREAD

**Issue by shady2k** [NodeBB/NodeBB#2707]
After fresh install 0.6.1 Acess Control for any category does not show groups.
![image](https://cloud.githubusercontent.com/assets/3366415/6097008/379a85a0-afbd-11e4-8fde-53f5ee83b2e9.png)

**Comment by julianlam** [comment]
Once fixed, should be backported to `v0.6.x` branch

**Comment by albig** [comment]
I've seen this too. After fixing websockets, I get the list of available groups.

**Comment by shady2k** [comment]
Why doesn't work via ajax?

**Comment by shady2k** [comment]
Check now, yes, with socket available it works. But I want ajax...

**Comment by julianlam** [comment]
With no websocket, it should drop down to ajax. We use socket.io to power all server/client communication :smile:

**Comment by shady2k** [comment]
Should, but don't. Problem does not solved.

**Comment by albig** [comment]
@shady2k is right. In this case the fallback to ajax doesn't work. I don't know the code and the reason. Just wondered about it during installation. It's my first try with nodebb. Maybe @julianlam can have deeper look on it.

**Comment by shady2k** [comment]
Request URL:
http://xxxxxxx/socket.io/?EIO=3&transport=polling&t=2423603256397-13&sid=5CFybja0JvS5Vcs1AAEl
EIO:3
transport:polling
t:2423603256397-13
sid:5CFybja0JvS5Vcs1AAEl

Request Payload
48:426["admin.categories.getPrivilegeSettings","4"]

Response:
ok

Is it correct response?

**Comment by sub-lunar** [comment]
Same thing here. I have two productive nodebbs running, both without websockets. The first one I installed as version 5.x and upgraded to 6.0; the second one was installed as 6.1 and doesn’t show the dropdown -- the first one (v6.0) still does.
(I really first noticed this when I logged out and realized that some categories were publicly visible, and then tried to change it. This (not being able to establish privacy on new categories) is also the reason why I didn’t upgrade the other one to 6.1 yet.)

**Comment by EvSpirit** [comment]
Same problem here. I see no server-side error, but I got a client-side one:

```
TypeError: null is not an object (evaluating 'privilegeList.length') categories.js:377
```

**Comment by EvSpirit** [comment]
I've just noticed, that some categories became invisible for all users, I think the problem is related to the discussed one.

**Comment by EvSpirit** [comment]
I debugged that a bit and found out, that the issue is related to #2477 (partially). It seems that NodeBB doesn't create permissions keys if no permissions is specified for some category. #2477 commit changed categories.js (lines 69+):

```javascript
		groups.get('cid:' + cid + ':privileges:' + privilege, { expand: true }, function(err, groupObj) {
			if (err || !groupObj) {
				return next(err, members);
			}

			members = members.concat(groupObj.members);

			next(null, members);
		});
```

So if no key is found, that code will fail with an error and that error won't be handled at client-side js. 

It seems we should wait for a fix, but if you need a hotfix urgently, you can temporary revert that changes.

**Comment by EvSpirit** [comment]
It seems it should be closed now as it was fixed at daaf61bc68348bd0f027ef4d6b1e679fef318244 commit.

**Comment by julianlam** [comment]
Can someone running xhr-polling only confirm this fix?

**Comment by EvSpirit** [comment]
@julianlam , yes, I confirm that everything works fine using xhr-polling.

**Comment by julianlam** [comment]
:clap: Thanks @EvSpirit !

**Comment by niklas-heer** [comment]
This bug also occurs if I enable cloudflare for my nodebb domain.

**Comment by julianlam** [comment]
CloudFlare settings should be "grey clouds", not orange.

**Comment by niklas-heer** [comment]
@julianlam in general for nodebb or for this specific bug?
Because I did change them to "grey clouds" because of this specific bug.

**Comment by julianlam** [comment]
In general. NodeBB falls back to xhr polling without websockets, but it's definitely a second-class experience.
