### ISSUE TITLE
Reopen #2707 (problem with groups and Access Control in 0.6.1 with polling transport)

### ISSUE THREAD

**Issue by shady2k** [NodeBB/NodeBB#2710]
Reopen the issue #2707, please. Problem does not solved.

**Comment by psychobunny** [comment]
Are you having this problem only in the groups ACP? ie. does everything else work on long polling in ACP and NodeBB itself?

**Comment by shady2k** [comment]
Yes, problem only in ACP with group Access list. Everything else works fine.
