### ISSUE TITLE
Ajaxify prevent default change breaks Admin link in navbar

### ISSUE THREAD

**Issue by joe1chen** [NodeBB/NodeBB#2711]
The change to add ```return e.preventDefault();``` in ajaxify.js (57d45518bdc71e50654802116e189680ac478d16) seems to break the Admin link in the navbar.

**Comment by julianlam** [comment]
Confirmed, will need to split that conditional in two, one just to handle `href="#"` and `data-ajaxify="false"`, and another to handle the other two
