### ISSUE TITLE
clearRequireCache breaks some plugins

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2714]
ie rss feed plugin.

each call to reload causes the plugin code to be executed again and start extra cronjobs.

**Comment by julianlam** [comment]
Hm... clearRequireCache removes the lib itself from the cache, but all the cronjobs should be added when `.init()` is called, no?

It [should not be floating free in the plugin library code itself](https://github.com/barisusakli/nodebb-plugin-rss/blob/master/index.js#L24-L27)...

**Comment by barisusakli** [comment]
init() is called on reload as well. So there is no way to stop the cronjobs that were started before even if they are inside init()

**Comment by barisusakli** [comment]
I think there needs to be some kind of hook that fires before the require cache is cleared so plugins can cleanup.

**Comment by julianlam** [comment]
Yes, I've come to the same conclsion as well...
