### ISSUE TITLE
Widgets on the "Global Sidebar" display at bottom on all links from the navbar

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2717]
Widgets on the "Global Sidebar" display at bottom on all links from the navbar (unread, recent, popular...)

NodeBB v0.6.x and v0.7.0-dev

![screen shot 2015-02-11 at 5 32 37 pm](https://cloud.githubusercontent.com/assets/10014774/6160176/05979652-b214-11e4-93bf-df93948624f9.png)

**Comment by barisusakli** [comment]
Looks like its caused by this change https://github.com/NodeBB/NodeBB/pull/2547/files

**Comment by pichalite** [comment]
@barisusakli related question, the breadcrumb on all pages is displayed only up to the side bar if there are widgets except for the category page. Shouldn't this be uniform across all pages?

**Comment by barisusakli** [comment]
Yeah it's fixed in lavender and vanilla.

**Comment by pichalite** [comment]
:+1:
