### ISSUE TITLE
Domain name for my nodeBB with Digitalocean

### ISSUE THREAD

**Issue by kacemlight** [NodeBB/NodeBB#2718]
Hello,

 I just got NodeBB working on my Digital Ocean server. And I also transferred domain names to the server. However, the regular domain name don't work www.nodejslearning.com but www.nodejslearning.com:4567 works.. What should I do to make my domain work ??

Thanks,

**Comment by ApfelUser** [comment]
Which web server are you using? NGINX or Apache2?

**Comment by kacemlight** [comment]
Apache I think.

**Comment by ApfelUser** [comment]
Then you need to follow this:

https://docs.nodebb.org/en/latest/configuring/proxies/apache.html

**Comment by kacemlight** [comment]
Thank youuu :+1:

**Comment by ApfelUser** [comment]
You're welcome. You can close this if it works now.

**Comment by kacemlight** [comment]
I cannot test now.. I will close it after testing tonight..

**Comment by julianlam** [comment]
If you run into further issues, please post a new topic in our Community Forum :)
