### ISSUE TITLE
Error installing any plugin on v0.7.0-dev

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2719]
When I try to install any plugin, I see an error notification and the plugins page stays at "Installing". I don't see any errors in the log file and the plugin gets installed.

`
Error
The package nodebb-theme-vanilla does not satisfy its siblings' peerDependencies requirements!
`

**Comment by barisusakli** [comment]
:rage3:

**Comment by pichalite** [comment]
I think I figured out the case when this error is happening. 

Your setup has any plugins that were installed when you were on v0.6.x master and have a dependency on vanilla's previous version.
You pull in the latest code from master, this starts happening when installing any plugin (doesn't matter if this plugin has dependency on vanilla or not).

**Comment by julianlam** [comment]
Latest code should resolve this, I believe. If not, recommended advice is to uninstall all affected plugins (that npm complains about), and re-install them.
