### ISSUE TITLE
Post Edit not working

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#2722]
I noticed I updated to version 0.7.0-dev and I have strange error.

In fact, I can't edit post any more.

Maybe it's related to https://github.com/Schamper/nodebb-plugin-poll
I noticed this using this and not working. I have disable it.

Or maybe it's related to 0.7.0
Im on 1029b6c2f327db2c48e5f5353bc93598fa1e2c34

There is no error in server or in JS.
Except this :/
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create nodebb.min.js:13
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. nodebb.min.js:2```

**Comment by tedr56** [comment]
I noticed issues about edit/delete permisssions refactoring.
Maybe it's related.

It can wait if it's like planned. :)

**Comment by barisusakli** [comment]
Thanks for reporting should be fixed on master.

**Comment by tedr56** [comment]
You're welcome.
Thanks to you @barisusakli
