### ISSUE TITLE
When navigating backwards via ajaxify, vertical scroll position should be remembered 

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2724]
If I scroll down a bit and then go to another page, if I press back, I expect the vertical scroll position to be restored to what it was before I left. 

This commonly happens in the recent / unread pages, where I'd want to go back to the same spot in a list I was just at after reading a topic

**Comment by psychobunny** [comment]
This mechanism doesn't translate very well with inifinite scroll though

**Comment by julianlam** [comment]
For topics? Yeah, that is a concern, although could be mitigated if:

`if (savedScrollPos > pageHeight) goToBookmark();`

We also use infinite scroll in the user list, though I'm not sure what to do about that...

**Comment by julianlam** [comment]
Also, disney branch makes this a non-issue :laughing:

**Comment by MegaGM** [comment]
` if (savedScrollPos > pageHeight) goToBookmark(); `
Yup! And of course store ` savedScrollPos ` in LocalStorage for each topic, next to bookmarks :)
btw that table ![](http://i.imgur.com/qv9M02X.png) so damn annoying >.< personally I even hate it
I saw somewhere on the forum (or mb here on Github?) a suggestion to make different behavior of those links
![](http://i.imgur.com/MiitME3.jpg)
1 - start of topic
2 - goToBookmark (without annoying alerts =^,^= just go!)

**Comment by barisusakli** [comment]
Then how do you go to the main post :older_man:

**Comment by MegaGM** [comment]
by clicking on that handy-dandy button ![](http://i.imgur.com/lBwzQE3.png)
or by clicking on 1 or 2 if there all posts are unread (if there is no bookmark yet)

**Comment by julianlam** [comment]
There has to be a way to get to the main post from the topic listing, otherwise it's a usability issue and people will complain (I *assume* this is the case, that is...)

**Comment by barisusakli** [comment]
Yeah that's my worry, if topic title doesn't take you to main post then you need 2 clicks to get to main post from topic listing.

**Comment by MegaGM** [comment]
But NodeBB is
> The next generation forum software that's free and easy to use.

If we have now 1 and 2 ways to open topic, maybe it's not a bad idea to add 3?
1 - start of topic
2 - go to first unread message
3? - goToBookmark (without annoying alerts =^,^= just go!)

![](http://smayly.ru/gallery/anime/DaiDai/45.gif)

**Comment by MegaGM** [comment]
I like that button ![](http://i.imgur.com/hOzfK1v.jpg)
Discourse is used there on screenshot.

Maybe we can create a totally new way for opening topics, that even better than all existed?
"INTELLECTUAL OPENING" ![](http://smayly.ru/gallery/anime/RedFox/35.gif)
or right next to just "OPEN TOPIC" place a new button "NANO_OPEN" ![](http://smayly.ru/gallery/anime/RedFox/39.gif)
or just add small badge right next to topic title "GOTO BOOKMARK or GOTO LAST SEEN POST"
it's kinda kidding but I'm serious :3
