### ISSUE TITLE
How to install google Re-Captcha ?

### ISSUE THREAD

**Issue by kacemlight** [NodeBB/NodeBB#2725]
I got my Public and private API Key, but I don't know how to make reCAPTCHA widget to appear, and this step : 
Step 2: Server side integration
When your users submit the form where you integrated reCAPTCHA, you'll get as part of the payload a string with the name "g-recaptcha-response". In order to check whether Google has verified that user, send a GET request with these parameters:
URL: https://www.google.com/recaptcha/api/siteverify

I don't know what command to use with my terminal to do this stuff ??

**Comment by akhoury** [comment]
just use this plugin https://www.npmjs.com/package/nodebb-plugin-spam-be-gone

**Comment by kacemlight** [comment]
How to use it ? Or how to install it ?

**Comment by akhoury** [comment]
from the 
NodeBB Admin Panel > Extend > Plugins

Search for "Spam Be Gone", install it (activate it if it's already installed), then wait for the server to reload, refresh the page. then under "Installed Plugins" the menu should have an entry for "Spam be Gone"

then, just like the screenshot, enable Re-Captcha, enter the public and private keys, You might have to restart the server again, i do not remember.

![Spam Be Gone Screenshot](http://i.imgur.com/GRkH2c9.png)

**Comment by kacemlight** [comment]
Yes I do this but now the captcha doesn't display
![capture d ecran 2015-02-14 a 01 05 22](https://cloud.githubusercontent.com/assets/10455208/6197083/425c94b6-b3e0-11e4-92fa-1c885e7b1aa3.png)

**Comment by akhoury** [comment]
which NodeBB version are you using?

**Comment by kacemlight** [comment]
I don't know :s .. how to check ?

**Comment by kacemlight** [comment]
ok I find it :  NodeBB v0.6.1.

**Comment by kacemlight** [comment]
I solve the problem.. Thank you !

**Comment by akhoury** [comment]
what was it?

**Comment by julianlam** [comment]
@kacemlite, in the future, please create new topics in the community forum,
not on this issue tracker.
