### ISSUE TITLE
Documentation: Plugin Hookss (style issue)

### ISSUE THREAD

**Issue by MegaGM** [NodeBB/NodeBB#2729]
I guess you all know, we need to restyle the entire page https://github.com/NodeBB/NodeBB/wiki/Plugin-Hooks
Personally, I have no style preferences, except one thing: all should be in similar style. I guess it would be nice if core team members tell us, which style should we all use.

p.s. Probably it will be right to ask RFC for this issue. Maybe somebody can advice a good style for the hooks.

**Comment by psychobunny** [comment]
I'm up for any style as long as it's easy to maintain really. Also, half of that doc is just a list of hooks :P

**Comment by barisusakli** [comment]
Imo we should build/find a tool to search for plugins.fireHook() in the source code and auto generate the hook list. 0 maintenance :laughing:

**Comment by psychobunny** [comment]
I agree so much with this, if it can auto update and link to the correct line in core then it would be immediately obvious to plugin devs what is coming in and going out. Right now, there are no guarantees that the hook you're looking at even exists let alone has the same parameters.

**Comment by psychobunny** [comment]
Here's what I've come up with so far, any suggestions?

https://github.com/NodeBB/docgen/blob/master/output/hooks.md

Next steps are running this as a service that listens to commits and auto updates the wiki page.

**Comment by psychobunny** [comment]
Okay that's done. Any commit against the NodeBB repo will trigger an update for the docs, located here https://github.com/NodeBB/NodeBB/wiki/Hooks

**Comment by barisusakli** [comment]
:+1:

**Comment by barisusakli** [comment]
Should we delete the old hooks page ?

**Comment by psychobunny** [comment]
Yup, in a bit. Gonna take some of the header content from there and stick it into the docgen

**Comment by pichalite** [comment]
:+1:
