### ISSUE TITLE
nodebb notification URL 

### ISSUE THREAD

**Issue by sourav82** [NodeBB/NodeBB#2730]
I'm to write a .Net application to connect with the nodebb socket for various notification like update a post, like etc.

I would like to know where can I get the URL for the socket to listen to from my C# application? My nodebb is accessible in below URL - http://10.242.138.102:4567/threadbasedforum/login. Also, to connect to socket do I need to pass username/password to get the notifications?

Thanks & Regards,
Sourav

**Comment by julianlam** [comment]
Please ask questions regarding implementation and configuration of NodeBB in our [community forum](https://community.nodebb.org). 

Thanks.
