### ISSUE TITLE
Password Reset is broken in 0.6.x

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#2731]
Users can request to reset their password. A reset code is generated, saved to the database correctly, and e-mailed to the user. However, when the user clicks the link in the e-mail the "Incorrect Reset Code" error message is shown. 

`./nodebb dev` does not show any output that coincides with this issue. It doesn't even give any indication that the reset link was used or anything. The same goes for `./nodebb log`.

I have tried switching the theme to lavender to rule out the issue being caused by my custom theme and the issue was the same. 

I've gone through the code trying to find the problem but so far I dont see anything that would be causing this. I just migrated from phpBB a few days ago and have 2k users who cannot access their account because they can't reset the password. :worried:

**Comment by julianlam** [comment]
Hello there, can you please provide the git hash you are on? `git rev-parse HEAD`

**Comment by julianlam** [comment]
Password resets seem to be working fine in latest code (v0.7.0-dev), can you give that a try?

**Comment by lots0logs** [comment]
`cb32d68e3acfd0c3aa7ef7bc84b58f6adaea2b2d`

I'll give it a try and let you know the result. Thanks!

**Comment by lots0logs** [comment]
Okay, so the problem does not occur with v0.7.0-dev! :relieved:

**Comment by julianlam** [comment]
Thanks for the update! :smile:

**Comment by Radiergummi** [comment]
Sorry to open this up again, but I am experiencing this on 0.6.1 :smile: 
When a user clicks on reset password, nothing happens visually and the log shows the following entry:  

```
Missing error handler on `socket`.
ReferenceError: db is not defined
    at SocketUser.reset.commit (/var/www/node/nodebb/src/socket.io/user.js:95:20)
    at callMethod (/var/www/node/nodebb/src/socket.io/index.js:223:2)
    at onMessage (/var/www/node/nodebb/src/socket.io/index.js:160:3)
    at Socket.<anonymous> (/var/www/node/nodebb/src/socket.io/index.js:60:3)
    at Socket.emit (events.js:107:17)
    at Socket.onevent (/var/www/node/nodebb/node_modules/socketio-wildcard/index.js:17:17)
    at Socket.onpacket (/var/www/node/nodebb/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/var/www/node/nodebb/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/var/www/node/nodebb/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/var/www/node/nodebb/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
```

I tried incorporating the changes in the respective file at `public/src/client/reset_code.js` from master, but that had no effect. I'd rather not upgrade to a dev branch yet... Any solution? Thanks!

**Comment by Radiergummi** [comment]
@julianlam , could you kindly give me some advice here?

**Comment by julianlam** [comment]
Do the latest commits in v0.6.x branch resolve this?

**Comment by Radiergummi** [comment]
Just pulled the whole thing again. Now the reset seems to work, nevertheless NodeBB logs an error and restarts. Emailer is installed and working flawlessly...
```
19/3 21:01 [12818] - info: [emailer.smtp] Sent `reset` email to uid 545
19/3 21:01 [12818] - error: ReferenceError: emailer is not defined
    at /var/www/node/nodebb/src/socket.io/user.js:108:4
    at /var/www/node/nodebb/src/user.js:33:4
    at /var/www/node/nodebb/src/user.js:39:4
    at Object.Plugins.fireHook (/var/www/node/nodebb/src/plugins/hooks.js:60:11)
    at modifyUserData (/var/www/node/nodebb/src/user.js:133:11)
    at /var/www/node/nodebb/src/user.js:75:4
    at /var/www/node/nodebb/src/database/redis/hash.js:66:4
    at /var/www/node/nodebb/node_modules/redis/index.js:1170:13
    at try_callback (/var/www/node/nodebb/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/var/www/node/nodebb/node_modules/redis/index.js:685:13)
ReferenceError: emailer is not defined
    at /var/www/node/nodebb/src/socket.io/user.js:108:4
    at /var/www/node/nodebb/src/user.js:33:4
    at /var/www/node/nodebb/src/user.js:39:4
    at Object.Plugins.fireHook (/var/www/node/nodebb/src/plugins/hooks.js:60:11)
    at modifyUserData (/var/www/node/nodebb/src/user.js:133:11)
    at /var/www/node/nodebb/src/user.js:75:4
    at /var/www/node/nodebb/src/database/redis/hash.js:66:4
    at /var/www/node/nodebb/node_modules/redis/index.js:1170:13
    at try_callback (/var/www/node/nodebb/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/var/www/node/nodebb/node_modules/redis/index.js:685:13)
19/3 21:01 [12818] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
19/3 21:01 [12818] - info: [app] Database connection closed.
19/3 21:01 [12818] - info: [app] Web server closed to connections.
19/3 21:01 [12818] - info: [app] Shutdown complete.
[cluster] Child Process (12818) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
19/3 21:01 [12830] - info: Time: Thu Mar 19 2015 21:01:19 GMT+0100 (CET)
19/3 21:01 [12830] - info: Initializing NodeBB v0.6.1
19/3 21:01 [12830] - info: Enabling 'trust proxy'
```

**Comment by barisusakli** [comment]
Pull again added the missing require

**Comment by Radiergummi** [comment]
Yes it did, but I don't think NodeBB crashing is supposed to happen :smile:

**Comment by julianlam** [comment]
NodeBB's still crashing? Let us know what commit you're on

**Comment by Radiergummi** [comment]
That would be 37fe854f46c9db8e9dfd98614cd7633bb9b1c296

**Comment by barisusakli** [comment]
You should be on https://github.com/NodeBB/NodeBB/commit/fe1c38605aff45448c6a33f1a02e4d6f70c6a696 thats the latest on 0.6.x branch

**Comment by Radiergummi** [comment]
Okay, I force-reset and pulled again, am on fe1c38605aff45448c6a33f1a02e4d6f70c6a696 now and password reset works, though I seem to be missing the template file for emails/reset_notify. I'll just create it myself though. Thanks!
