### ISSUE TITLE
Crashing on every http request after failed group creation attempt

### ISSUE THREAD

**Issue by sub-lunar** [NodeBB/NodeBB#2732]
Just after commenting on the issue about the dropdown menu not showing up on the category permissions dialog (https://github.com/NodeBB/NodeBB/issues/2707) I was wondering what would happen if I added a group manually. So I went to *Manage* → *Groups*. The list had one item, the administrators group created by the system. Then I clicked the *New Group* button, named the new group – probably problematically – "Guests", gave it no description and hit *Create*. The request never really completed and ever since, my nodebb crashes on every single http request.

Here’s the log:
```
@4000000054e2988925b8e604 17/2 02:25 [14227] - info: NodeBB v0.6.1 Copyright (C) 2013-2014 NodeBB Inc.
@4000000054e2988925cc2f84 17/2 02:25 [14227] - info: This program comes with ABSOLUTELY NO WARRANTY.
@4000000054e2988925cf4c64 17/2 02:25 [14227] - info: This is free software, and you are welcome to redistribute it under certain conditions.
@4000000054e2988925d19654 17/2 02:25 [14227] - info: 
@4000000054e2988926632fc4 17/2 02:25 [14227] - info: Time: Tue Feb 17 2015 02:25:19 GMT+0100 (CET)
@4000000054e29889266673b4 17/2 02:25 [14227] - info: Initializing NodeBB v0.6.1
@4000000054e2988b0b47524c 17/2 02:25 [14227] - info: Enabling 'trust proxy'
@4000000054e2988e18c47e04 17/2 02:25 [14227] - info: NodeBB is now listening on: 0.0.0.0:61616
@4000000054e29891099d5f54 17/2 02:25 [14227] - info: NodeBB Ready
@4000000054e298951db1c8a4 17/2 02:25 [14227] - error: TypeError: undefined is not a function
@4000000054e298951db1d45c     at /home/edelextr/nodebb/src/groups.js:204:12
@4000000054e298951db1d45c     at /home/edelextr/nodebb/node_modules/async/lib/async.js:592:17
@4000000054e298951db1d844     at done (/home/edelextr/nodebb/node_modules/async/lib/async.js:135:19)
@4000000054e298951db1dc2c     at /home/edelextr/nodebb/node_modules/async/lib/async.js:32:16
@4000000054e298951db1dc2c     at /home/edelextr/nodebb/node_modules/async/lib/async.js:589:21
@4000000054e298951db260fc     at /home/edelextr/nodebb/src/groups.js:158:7
@4000000054e298951db264e4     at try_callback (/home/edelextr/nodebb/node_modules/redis/index.js:573:9)
@4000000054e298951db264e4     at RedisClient.return_reply (/home/edelextr/nodebb/node_modules/redis/index.js:661:13)
@4000000054e298951db268cc     at ReplyParser.<anonymous> (/home/edelextr/nodebb/node_modules/redis/index.js:309:14)
@4000000054e298951db26cb4     at ReplyParser.emit (events.js:95:17)
```
Nodebb comes up without problems every time and stays up as long as I do nothing; but as soon as my browser sends a request, it crashes. I somehow managed to logout, though, so maybe _something_ is still done between request and crash.

I also found this in the appendonly-file of my redis db.
```
...
$9
PEXPIREAT
$37
sess:T3kCSnLOyn14OTCh7CcX3Bs06_NLpuQB
$13
1425344387721
*1
$5
MULTI
*1
$4
EXEC
*4
$4
zadd
$17
groups:createtime
$13
1424134789247
$6
Guests
*22
$5
hmset
$12
group:Guests
$4
name
$6
Guests
$4
slug
$6
guests
$10
createtime
$13
1424134789247
$9
userTitle
$6
Guests
$11
description
$0

$11
memberCount
$1
0
$7
deleted
$1
0
$6
hidden
$1
0
$6
system
$1
0
$7
private
$1
1
*3
$4
sadd
$19
group:Guests:owners
$1
1
*4
$4
zadd
$20
group:Guests:members
$13
1424134789247
$1
1
*4
$4
hset
$19
groupslug:groupname
$6
guests
$6
Guests
*1
$5
MULTI
*1
$4
EXEC
*1
$5
MULTI
*1
$4
...
```
Maybe I could just cut out the malicious group creation attempt? But from where to where would I have to cut?

**EDIT**: After some trial & error, I got my nodebb up and running again by:
*   stopping redis
*   cutting off everything from the appendonly file beginning from
```
*4
$4
zadd
$17
groups:createtime
$13
1424134789247
$6
Guests
...
```
   to the end
*   running `redis-check-aof --fix appendonly.aof` on the file
*   starting redis again
*   starting up nodebb

Looks like everything is there, but strangely, it switched to the nodebb vanilla theme and I can’t activate lavender again. The theme is my smallest problem though :)

**EDIT 2**: The theme problem seems to have gone away by itself, or maybe because I checked some files in public/templates (logs said that header.tpl could not be opened).

So I got everything working again and as far as I can tell no content was lost; but I still think it’s an issue!

**Comment by julianlam** [comment]
Yes, this does sound a bit concerning, as:

1. You shouldn't be able to create a group called "Guest"
1. NodeBB shouldn't crash when you create said group :smile:
