### ISSUE TITLE
alert.tpl error lavender theme on reload

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2734]
I am seeing this error in log after "Reload". NodeBB v0.7.0-dev. I am on latest version of master and all themes are latest.

`
 error: /templates/alert.tpl
 Error: ENOENT, open '/path-to-nodebb/public/templates/header.tpl'
`

**Comment by julianlam** [comment]
We'll need more info -- where are you seeing this error? How can it be triggered after hitting reload in ACP dash?

**Comment by pichalite** [comment]
It's triggered after hitting reload in ACP. On the client side I don't get the "forum updated.. reload" notification and I see the tpl error in the browser console.

**Comment by pichalite** [comment]
I don't see this issue anymore. Probably happened because of a plugin.

**Comment by julianlam** [comment]
Thanks for following up :smile:
