### ISSUE TITLE
I cannot use Google API authentification

### ISSUE THREAD

**Issue by kacemlight** [NodeBB/NodeBB#2735]
I add google api authentification with the required api code client and all setings, but everytime I try to login with google I got This :
 400. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://128.199.126.245/auth/google/callback

Learn more

Request Details
scope=https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
response_type=code
redirect_uri=http://128.199.126.245/auth/google/callback
client_id=311352084105-74ij1ndpha44909piv7ubrq849fjkums.apps.googleusercontent.com
That’s all we know.

Please can someone help me !?

**Comment by julianlam** [comment]
Hello @kacemlight -- this is a problem with your configuration. Google does not allow an IP address, as specified by their error message:

> Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://128.199.126.245/auth/google/callback

Please set up your NodeBB with a domain name via reverse proxy (see documentation for details on how to achieve this).

**Comment by julianlam** [comment]
https://docs.nodebb.org/en/latest/configuring/proxies/nginx.html

**Comment by kacemlight** [comment]
No SSO login plugin works.. This is my configuration : 

server {
        listen 80;

        server_name nodejsworld.com;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://127.0.0.1:4567/;
                proxy_redirect off;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                }
}

server {
    listen   80;
    listen   [::]:80;
    server_name www.nodejsworld.com;
    return 301 http://nodejsworld.com$request_uri;
}
server {
    listen   80;
    listen   [::]:80;
    server_name www.nodecommunity.com;
    return 301 http://nodejsworld.com$request_uri;
}
server {   listen   80;
    listen   [::]:80;
    server_name nodecommunity.com;
    listen   [::]:80;
    server_name nodecommunity.com;
    return 301 http://nodejsworld.com$request_uri;
}
server {
    listen   80;
    listen   [::]:80;
    server_name www.nodejslearning.com;
    return 301 http://nodejsworld.com$request_uri;
}
server {
    listen   80;
    listen   [::]:80;
    server_name nodejslearning.com;
    return 301 http://nodejsworld.com$request_uri;
}
server {
    listen   80;
    listen   [::]:80;
    server_name www.nodejsword.com;
    return 301 http://nodejsworld.com$request_uri;
}



I'm using 3 domain names.. Please what should I change in my config ?

**Comment by julianlam** [comment]
`config.json` `url` should read `http://nodejsworld.com`

**Comment by kacemlight** [comment]
I don't understand what I have to change :(

**Comment by julianlam** [comment]
In the NodeBB root folder, there exists a file called `config.json`. You'll want to edit it and change the `url` property

**Comment by kacemlight** [comment]
I do the change but I hace always the same error : 
400. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://128.199.126.245/auth/google/callback

Learn more
Request Details

    scope=https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    response_type=code
    redirect_uri=http://128.199.126.245/auth/google/callback
    client_id=311352084105-74ij1ndpha44909piv7ubrq849fjkums.apps.googleusercontent.com



This is my config.json : 


{
    "url": "http://nodejsworld.com",
    "secret": "3dcc5e2e-0574-46fd-88a9-9f9649a16ef7",
    "database": "redis",
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "password": "",
        "database": "0"
    }
}

**Comment by kacemlight** [comment]
Please change the status of this issue to open !

**Comment by julianlam** [comment]
This is not a bug with NodeBB, so you are advised to seek integration help on our [community support forum](https://community.nodebb.org)

In your case, your NodeBB is still reporting the raw IP address. You need to restart your NodeBB before it will identify as the domain name.

**Comment by kacemlight** [comment]
Ok I restart my server and now it works.. Thank you very much !
