### ISSUE TITLE
Urgent !!!! Help Please !

### ISSUE THREAD

**Issue by kacemlight** [NodeBB/NodeBB#2742]
I installed Amazon S3 plugin, I configured it and after this I tried to upload a file and it crashed, after this I cannot access to my website anymore I get 502 Bad Gateway nginx/1.6.2. 
nodejsworld.com

I need your help because I already have some users :(

**Comment by kacemlight** [comment]
How a plugin can crashed my website like this ?

**Comment by julianlam** [comment]
Hello @kacemlight -- please limit issues on this issue tracker for bugs in NodeBB itself. Plugin errors are not part of NodeBB, so please create a new topic **[in our community forum](community.nodebb.org)**. Thanks!

**Comment by julianlam** [comment]
Alternatively, report the issue to the upstream developer's git repository.

**Comment by kacemlight** [comment]
Ok sir, I'm sorry I was used to post issues here .. I well delete this :)
