### ISSUE TITLE
Composer formatting options should no longer be hardcoded in core

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2743]
We hard-code bold, italic, etc in core, but the real awkward part is that the parser is a plugin, meaning if you swapped out Markdown for something else (like BBCode), you would still get the old formatting options inputting *markdown* into the composer instead of `[b]`, etc.

Oops.

Additionally, several other plugins attempt to modify the toolbar, but because of this hardcoding, plugins are resorting to tactics like appending to the end, which is good, but *not powerful enough*.

* [ ] Add a filter for plugins to add their own formatting options
* [x] Update Markdown plugin to utilise this method
* [ ] Remove hardcoded formatting options from core

**Comment by MegaGM** [comment]
I guess that discussion is related https://github.com/NodeBB/NodeBB/pull/2654

**Comment by julianlam** [comment]
Yep, sure is. I incorporated most of the changes outlined in that issue, so we can build off of the changes introduced here.

**Comment by julianlam** [comment]
@psychobunny @TedRinehart @a5mith I believe you all append buttons to the toolbar in some way?

### [You can see how Markdown does it here](https://github.com/julianlam/nodebb-plugin-markdown/commit/10b25c699e6ac2639cceb40b466f513af1ceeabb)

**Comment by MegaGM** [comment]
Thank you! These changes were necessary, definitely.
Next step will be using composer in plugins :3 I've planned it for nodebb-plugin-mega-chatbox

**Comment by julianlam** [comment]
Please let us know if you run into any awkward issues with the composer when integrating with another plugin.

For example, the composer itself *should* be a distinct entity from other parts of NodeBB, so if you catch it doing weird things like posting new topics, etc, let us know.

**Comment by MegaGM** [comment]
> so if you catch it doing weird things like posting new topics, etc, let us know.

@julianlam Of course :+1:
