### ISSUE TITLE
ACP navbar search issue

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2746]
"Search the forum" option should not be displayed if no search plugin is activated. Displays a not found error if no search plugin is activated.

"Search the forum" option should open in a new tab, not in the ACP. Right now it opens in the ACP with breadcrumb, copyright and vanilla theme applied to the page. Clicking on "Home" in the breadcrumb, opens the forum homepage in the ACP (with vanilla theme applied and some weird formatting) and the browser address bar points to homepage instead of ACP.

**Comment by yariplus** [comment]
I got this working, but I didn't see any way for ajaxify.go to open in a new tab, so I used a javascript click event to open the new tab (When no admin results are found). It works great, but is there something bad about not using ajaxify.go?

**Comment by julianlam** [comment]
@yariplus `ajaxify.go` is only used for going between pages, but going from ACP to front-end would need a new page load anyways, so opening a new tab via js is sufficient.
