### ISSUE TITLE
Allow ordering of plugins in ACP

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2749]
Currently, there is no way of determining plugin execution order. As active plugins are saved to a set in the data store, and the set order is determined by how the set is returned by redis/mongo (which I believe is alphanumerically?). We've simply never run into problems with this because of pure luck.

It may be advantageous for some admins to manually configure the sort order. For example, ensuring that markdown is always run first, and then the other *-embed plugins are run after it, so their HTML doesn't get accidentally clobbered when markdown sanitizes it.

So, the `plugins:active` set needs to be upgraded to a zset.

**Comment by barisusakli** [comment]
:rage3:
