### ISSUE TITLE
Categories empty and crash after upgrade from 0.5.7 to 0.6.1

### ISSUE THREAD

**Issue by reddcoin** [NodeBB/NodeBB#2750]
Hi

We are having problems upgrading from 0.5.7 to 0.6.1. After the upgrade is done, all categories are empty and when you visit one of them, the forum crash and restart with this error. You can see the test server upgraded to 0.6.1 here http://test.reddcointalk.org/. When you visit "General discussions", it crash with the error. All other categories are empty.

We try deleting all plugin but no change. Thanks for the help.

19/2 10:27 [16886] - info: NodeBB Ready
19/2 10:27 [16886] - info: NodeBB is now listening on: 0.0.0.0:4567
19/2 10:27 [16886] - verbose: [cluster] Client-side javascript and mapping propagated to worker 16886
19/2 10:27 [16886] - verbose: [cluster] Stylesheets propagated to worker 16886
19/2 10:28 [16886] - error: TypeError: Cannot read property 'tid' of null
    at /home/reddcoin/reddcointalk.org/src/topics/teaser.js:58:25
    at Array.map (native)
    at /home/reddcoin/reddcointalk.org/src/topics/teaser.js:57:26
    at Object.User.getMultipleUserFields (/home/reddcoin/reddcointalk.org/src/user.js:53:11)
    at /home/reddcoin/reddcointalk.org/src/topics/teaser.js:41:9
    at Object.Posts.getPostsFields (/home/reddcoin/reddcointalk.org/src/posts.js:142:11)
    at Object.Topics.getTeasers (/home/reddcoin/reddcointalk.org/src/topics/teaser.js:30:9)
    at Object.async.parallel.teasers (/home/reddcoin/reddcointalk.org/src/topics.js:162:13)
    at /home/reddcoin/reddcointalk.org/node_modules/async/lib/async.js:583:25
    at /home/reddcoin/reddcointalk.org/node_modules/async/lib/async.js:125:13
[cluster] Child Process (16886) has exited (code: 1, signal: null)
[cluster] Spinning up another process...

**Comment by julianlam** [comment]
Any chance you could provide us with a copy of your database for testing purposes?

**Comment by reddcoin** [comment]
Yes, can you give me your email address?

**Comment by reddcoin** [comment]
I can send the dump to your email, it's under 5mb. Ok?

**Comment by julianlam** [comment]
Sure, no problem.

**Comment by julianlam** [comment]
Long story short -- It seems as though one of the upgrade scripts failed to run. Re-running it fixes the issue.

1. Download [this diff](https://gist.github.com/julianlam/8590652772bb3ae66ed9)
1. Apply it: `cd /path/to/nodebb && patch -p1 /path/to/downloaded/gistfile1.diff`
1. In redis, run this to tell NodeBB it's out-of-date: `set schemaDate 1415318399999`
1. Upgrade NodeBB: `node app --upgrade`
1. Reverse the patch: `path -Rp1 /path/to/downloaded/gistfile1.diff`
1. Profit

**Comment by reddcoin** [comment]
Thanks a lot for your help.
