### ISSUE TITLE
Rewards API

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2751]
# Rewards API

## A simple logic engine in the ACP to allow you to do actions based on events.

This was originally part of the badge system plugin but I decided to remove this and make it core, and have other plugins be able to build on top of it (badges plugin, achievements plugin, etc)

![](http://i.imgur.com/gYbKM3h.png)

This is just a basic iteration and I'm sure there's a ton more we can do to make this cooler in future.

* [x] Basic Rewards ACP interface
* [x] Allow plugins to [define conditions](https://github.com/NodeBB/nodebb-rewards-essentials/blob/master/library.js#L15-L38) (ex. "If user's reputation is over X")
* [x] Allow plugins to [define conditionals](https://github.com/NodeBB/nodebb-rewards-essentials/blob/master/lib/conditionals.js#L33-L51) (ex. "greater than", "smaller than")
* [x] Allow plugins to define [rewards/actions](https://github.com/NodeBB/nodebb-rewards-essentials/blob/master/lib/rewards.js#L44-L52) (ex. "Add user to group", "Send alert to user")
* [x] Plugins can define custom parameters in the Rewards ACP (ex. the Message / Title field for the alert reward)
* [x] Rewards Essentials plugin with samples on how to do all of the above
* [x] Allow to define a reward as claimable only once or multiple / infinite times

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-rewards-essentials

**Comment by MegaGM** [comment]
Thank you!

**Comment by pichalite** [comment]
@psychobunny Should I be able to create some basic rewards with this or do I need to wait for plugins to be implemented? Right now nothing happens when I click "New Reward".

**Comment by psychobunny** [comment]
`./nodebb upgrade`

should have installed the plugin, if not then `npm install /nodebb-rewards-essentials`

**Comment by pichalite** [comment]
nodebb-rewards-essentials plugin is already installed and activated.

**Comment by psychobunny** [comment]
Just double checking, you did restart forum after activating etc right?

Do you get any error messages in the console when clicking on "New Reward"?

**Comment by pichalite** [comment]
Yes, I did restart. I just restarted it again.

I don't see any error messages in the console when I click "New Reward". It just doesn't do anything.

After I come to the "Rewards" page, every link I click in the ACP throws this error in the console.

`Uncaught SyntaxError: Unexpected token u`

**Comment by psychobunny** [comment]
I committed a fix for that second error, but I can't reproduce the first one. Tried it on an older db that I had upgraded to latest. Going to try on a fresh install now

**Comment by psychobunny** [comment]
Got it to work on a completely fresh install as well. Try and see if the fix I posted above for the other error somehow resolves the first issue?

**Comment by pichalite** [comment]
pulled the latest code and the "New Reward" button works now.

The default "Then:" is set to "Add to Group" but it doesn't display the "Group Name:" select list unless I pick "Send alert message" and then change it to "Add to Group".

In the "Group Name:" select list, in addition to groups, all the categories are listed with privileges. Is that how it's going to be?

![screen shot 2015-02-23 at 12 30 06 pm](https://cloud.githubusercontent.com/assets/10014774/6336479/c0196fd6-bb57-11e4-9f1b-78664f33b222.png)

**Comment by psychobunny** [comment]
The first one is a minor bug (although I thought I fixed that), will look into it shortly

The second is intended, permissions are actually "groups". So a use case could be, if you gained enough reputation, you'd be able to allow a user to post in Category X

It needs better UX / design though, which is something I'll focus on as we go along

**Comment by psychobunny** [comment]
> The first one is a minor bug (although I thought I fixed that), will look into it shortly

Was working on FF but broken on chrome - fixed
