### ISSUE TITLE
Maintain a back/forward cache during navigation 

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2753]
Just a thought that's been bouncing around the back of my head for the last couple of weeks...

When I browse NodeBB on my phone, the flow is *typically* `Unread -> Topic -> (Back to) Unread -> Topic`. The way NodeBB is currently set up, clicking back fires off a brand new ajaxify event, to load a page that usually hasn't changed in the 30 seconds I've been away.\*

The additional XHR (and thus, the additional time it takes to receive the data and parse the template) is nearly imperceptible on a desktop, but on a phone, there is a noticible delay between page transitions due to the combined time it takes to:

1. Request and receive the api data
1. Parse the template (and download the template if it is not a template downloaded prior)

Knowing this, what if every time an internal link in NodeBB was clicked, we saved the content of the previous page, and if the user clicked `Back`, we just swapped pages\*\*? No extra xhr, instantaneous page transition.

Possible downsides:

1. The transition *feels* broken. Regular page changes feature a fade out/in and a loading bar, but this has neither, so the site feels like it has broken.
  * I added a 100ms delay, which seems to address this partially.
  * ... but now I've removed it again, because introducing a 100ms delay seems hacky at best
1. Because we're only swapping the DOM, the content doesn't update with new content, if there was any. In the above example, the unread topics would stay unread when returning to the page, whereas a proper navigation would load the new data without the since-read topic.
  * Resolved via bdab98d38fba789ce2eb37c84ca8998bdb8a9c7c, clicking a topic/teaser timestamp now marks the topic as read and removes it from the DOM)
  * Is there an expectation that clicking "Back" gets the latest info? I don't believe so. On a regular page load, clicking back causes the browser to simply load the cached version of the page, so I actually think this is a non-issue.

Given the possible downsides, I was wondering what thoughts others had on the issue.

Want to try it out? Nice. It's currently living on the `ajaxify-cache` branch:

``` bash
$ cd /path/to/nodebb
$ git fetch
$ git checkout ajaxify-cache

# And to go back...
$ git checkout master
```

----

#### Notes

\* Actually, for `/unread`, it *does* change, because the topic I went into is now marked read, but I digress

\*\* "Swap" pages, because then the user can click `Forward` again

**Comment by julianlam** [comment]
If merged, I'd *probably* introduce a userland option to **disable** the ajaxify cache, but only to appease @psychobunny :smile:

**Comment by psychobunny** [comment]
If the change is completely transparent UX wise then there's no reason to add that option in UCP (plus it would be a confusing option for the end user anyways)

**Comment by julianlam** [comment]
I'm leaning towards merging it in at the moment... see what early adopters think.

**Comment by julianlam** [comment]
e6701c5a1f5a87a526c860f8e25e68ca1a65492d

**Comment by psychobunny** [comment]
Amazingly that fix works for unread too, unread posts are removed when pressing back. Mind blown
