### ISSUE TITLE
Modifying home page route in ACP

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2755]
If I change the "Home Page Route" in ACP to either Recent or Popular, I don't see a way in NodeBB to get to Categories other than directly going to example.com/categories.

I think "Categories" should take the place of Recent or Popular in the navbar when they are set as home page route.

**Comment by barisusakli** [comment]
Yeah this is going to be available when we make menu.tpl completely configurable so you can display whatever you want in the header. The route is already there going to forum.com/categories will display the category list.

**Comment by pichalite** [comment]
:+1:
