### ISSUE TITLE
When accessed with no search term, `/search` should automatically expand the search form

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2757]
e.g. on Mobile, `/search` is accessed directly.

**Comment by lots0logs** [comment]
@julianlam This issue is still present. When you access `/search` you are presenting with the search box closed/minimized and an error message:
```
No matches found
```

**Comment by lots0logs** [comment]
Wow, you guys are fast. Thanks for creating and maintaining such a great platform!!!

**Comment by barisusakli** [comment]
:dash: 
This fix requires the theme to be updated as well, I have republished vanilla and persona.
