### ISSUE TITLE
Expose "hidden" group property to owners

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2758]
Was only used internally, but should be extended to group owners as well.

https://community.nodebb.org/topic/3389/ability-to-hide-groups-from-groups/

**Comment by julianlam** [comment]
@TedRinehart

**Comment by julianlam** [comment]
* [x] Add descriptive badge (hidden) to group details box
* [x] Expose option to change hidden state of group
* [ ] If a group is hidden, they should not be able to be accessed via url

**Comment by julianlam** [comment]
:rage2: More work

* User invitation mechanic
  * [ ] `group:{slug}:invited` zset
  * [ ] Interface in group details page
  * [ ] Socket calls and library methods

**Comment by julianlam** [comment]
:rage3: Even more work

* [ ] Build generic modal for user searching

**Comment by DaveArthur** [comment]
Just a query, could group owners create their own private categories? (with any limit set in ACP) 
So those categories would only be viewable to group members.
Also detag option not everyone wants or needs to have a label

**Comment by julianlam** [comment]
>  could group owners create their own private categories

Not in core, but would be a neat addition via plugin.

> Also detag option not everyone wants or needs to have a label

Yes, this would be nice to add too.

**Comment by psychobunny** [comment]
> Also detag option not everyone wants or needs to have a label

This option would probably live in the UCP, just like in other forums, will make new issue for that

**Comment by julianlam** [comment]
Thanks @psychobunny :smile:

**Comment by DaveArthur** [comment]
k, thanks both, I better start reading up on these plugins!
