### ISSUE TITLE
Title selector in UCP

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2759]
Ability to pick and choose what title to display (conferred by your group memberships)

Also RFC: I think we should limit the amount of titles shown to just 1, and then the rest of your titles on 
your user page. Feels a bit cluttered when you have 3+ group memberships and you have all sorts of title badges in the post area

**Comment by pichalite** [comment]
:+1:

**Comment by MegaGM** [comment]
:+1::+1::+1:
