### ISSUE TITLE
Misleading UX for badge preview

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2766]
![](http://i.imgur.com/l7upbeI.png)

If `Badge Text` is empty, you won't display a badge in /topics - yet the badge preview will still show an icon. Ideally there should be a checkbox to allow badge or not, alternatively, the preview should become empty if badge text is also empty (less ideal, unless messaged to user)

**Comment by psychobunny** [comment]
Regardless of which method is chosen, the `Badge Text` textbox should be moved above the preview.

**Comment by pichalite** [comment]
@julianlam 

Create a new group -> go to group details page -> badge preview is not visible.

Uncheck "Show Badge" -> Save -> check "Show Badge" -> Save, badge preview is visible all the time after that.
