### ISSUE TITLE
Don't lock accounts for incorrect password attempts unless a mailer plugin is active and installed

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2767]
Include messaging to admin in the ACP, for ex.:

> "Warning: Brute-force login security is disabled until you install and activate an emailer plugin"

**Comment by psychobunny** [comment]
Nvm, apparently I misinterpreted how this system works, @barisusakli suggested `./nodebb resetPassword=abcdef` instead

**Comment by julianlam** [comment]
Before we hard-code in a shortcut to reset the **admin password**, I'd like someone with a security background to weigh in.

On the one hand, yeah, if you have shell access, you're compromised *anyway*, but on the other hand, there's a reason why WP/Drupal/phpBB/[insert web app name] doesn't have a short-circuit like this.

**Comment by MegaGM** [comment]
> but on the other hand, there's a reason why

I guess [web apps names] don't have that feature cuz those web apps don't have that feature.
It's the only reason. ![](http://smayly.ru/gallery/ava/Kanade/56.jpg)
What about WP/Drupal/phpBB, it's all are PHP apps. They all have no feature to run them like "./phpbb start" at all.
Many of others applications have this feature. And this way to reset pass even useful sometimes. I guess it's quite normal to have the feature in NodeBB too. But it's also quite normal not to have it :D

**Comment by psychobunny** [comment]
Tbh if someone is able to run an executable on your server you're in trouble already. `npm install nodebb-plugin-sinister-behaviour`

Not to mention the fact that they can read your config.json

I don't think there is a problem here
