### ISSUE TITLE
[docs] Add instructions on installing plugins that provide default/expected forum behaviors

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2768]
* [ ] Emailer
* [ ] Search

**Comment by julianlam** [comment]
Anybody in the @NodeBB/documentation-translation-team can definitely contribute to this one :smile: 

Just link back to this issue in the appropriate commit in nodebb/nodebb-english

**Comment by psychobunny** [comment]
Moved to docs tracker
