### ISSUE TITLE
[ACP] Better messaging to admin about missing plugins for expected behaviors

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2769]
(https://github.com/NodeBB/NodeBB/issues/2768 related)

![](http://i.imgur.com/XNOcmBZ.png)

There is no instruction on how to go about resolving this problem (imagine an everyday admin with non-dev background encountering this message)

RFC for best practices - imo maybe just `<small>Please click **here** to visit the plugins page </small>`

**Comment by julianlam** [comment]
Was thinking maybe an [info-circle](http://fortawesome.github.io/Font-Awesome/icon/info-circle/) icon with `.text-info` beside the message, with a bootbox alert to explain what to do about it
