### ISSUE TITLE
Horizontal scrolling on chat modal

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2770]
Add `word-wrap: break-word;` to the `ul` element for the themes.

**Comment by julianlam** [comment]
Can you provide a screenshot of how it is not rendering properly right now?

**Comment by pitaj** [comment]
No, but if there is a really long link, it won't break properly, and there
will be a horizontal scroll bar.

**Comment by pitaj** [comment]
Here's a picture:

![picture of overflow](http://i.imgur.com/mlQjuko.png)
