### ISSUE TITLE
Unexpected UX due to priority sorting of unread notifs

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2772]
(Original issue was here: https://github.com/NodeBB/NodeBB/issues/2764 - if you can imagine, if I'm confused by this UX then imagine an ordinary user?)

Notifs should be sorted in chronological order regardless of read/unread status. Right now, a 1 week old notif will be pushed to the top of the list - this is the current UX flow:

1 - user clicks on any notif, gets sent to the right page
2 - if user opens notif dropdown again, will expect to see the "read" notif in the same place.

vs. 

1 - user clicks on 1 week old unread notif (sorted to the top because it's unread)
2 - on subsequent opening of notif dropdown, this notif has "disappeared" because it's pushed down by more recent notifications

This issue probably relies on https://github.com/NodeBB/NodeBB/issues/2771 being addressed first.

**Comment by psychobunny** [comment]
ex. of "disappearing" notifs

Before:
![](https://camo.githubusercontent.com/052924f0f52736d19a01682a7c90ac5edbd02900/687474703a2f2f692e696d6775722e636f6d2f4d367534455a412e706e67)

After:
![](http://i.imgur.com/MeIcyZ3.png)

**Comment by julianlam** [comment]
> This issue probably relies on #2771 being addressed first.

:trollface:
