### ISSUE TITLE
"Mark as Unread" is confusing

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2773]
If I am a newly registered user, all topics in every category look like they are unread. When I go to the "Unread" page, the page only displays topics posted in the last 7 hours (at least that's what it looks like and the infinite scroll stops there, I have rss plugin creating topics every hour).

When I pick Mark as Unread -> All, topics posted in the last day are marked as read (not just what's displayed in the Unread page or every topic in the forum), but all the older topics still look like unread in the categories. 

![screen shot 2015-02-24 at 10 22 45 pm](https://cloud.githubusercontent.com/assets/10014774/6365970/b825ba06-bc73-11e4-9255-6da7c597a433.png)

**Comment by barisusakli** [comment]
This happens because /unread only displays topics from the past 24 hours. Maybe everything beyond that should be considered read so it is consistent.
