### ISSUE TITLE
Chatbox not rendered properly

### ISSUE THREAD

**Issue by theinvinciblesun** [NodeBB/NodeBB#2775]
On my HTC One M7 gpe using chrome browser the chatbox where text is entered is hidden behind the keyboard during text entry.
One can keep typing but cannot see what is being typed unless the keyboard is minimized.

![screenshot_2015-02-25-13-32-18](https://cloud.githubusercontent.com/assets/9161199/6367010/7f8bcad4-bcf3-11e4-90ba-9d3c3f6a7a2e.png)
![screenshot_2015-02-25-13-32-05](https://cloud.githubusercontent.com/assets/9161199/6367014/8a1231fa-bcf3-11e4-99ca-aefcd583f730.png)

**Comment by theinvinciblesun** [comment]
Also there is a lot of wasted space as seen in the 2nd screenshot although that might be intentional

**Comment by julianlam** [comment]
@theinvinciblesun Let me know if this fixes it for you :smile:
