### ISSUE TITLE
Add a link sign below posts

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2776]
Next to the flag button, there should be a small link button that, when pressed, brings up a modal which shows for the copying of the link directly to that post. This allows people to more easily reference individual posts.

**Comment by julianlam** [comment]
This is a theme-specific issue -- for Lavender, the link is found under the heart:

![selection_023](https://cloud.githubusercontent.com/assets/923011/6371743/85e7c04e-bccc-11e4-8190-a704170c6b8e.png)
