### ISSUE TITLE
Unread topics and disabled category

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2777]
NodeBB shows a number of unread topics in a hidden categories.

Steps to reproduce:
1. Create New Category
2. Start a New Topic in newly created Category
3. Mark New Topic as Unread
4. Disable New Category
5. Click on Unread icon

"There are no unread topics." will be shown and "1" notification on top of "Unread" icon.

**Comment by barisusakli** [comment]
Does it still show 1 unread after you reload the page?

**Comment by nhlpl** [comment]
Yes, it does. It's quite important for those who import data from other forum software.
