### ISSUE TITLE
Option to clone a category in ACP

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2779]
It would be nice to have an option to clone a category with all settings and access control from existing category applied to the new category.

**Comment by pichalite** [comment]
@psychobunny Duplicating the category is not copying the settings. Default settings are getting applied. Disabling the category created with duplicating is not working and the duplicated category is always going to the top of the list in ACP and in the forum.

**Comment by psychobunny** [comment]
Yeah, I'd imagine the permissions wouldn't have been copied over from what I wrote. The last issue seems acceptable though
