### ISSUE TITLE
[ACP] FontAwesome Icon Picker

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2780]
http://mjolnic.com/fontawesome-iconpicker/

Yes.

**Comment by julianlam** [comment]
:+1:

**Comment by psychobunny** [comment]
It's pretty cool, but only catch is that he doesn't seem to be updating it often - last update is 8 months ago. We can probably drop it in core and modify it so that it points to our version of font awesome though.

**Comment by psychobunny** [comment]
I tried this, it just doesn't work. I get an infinite loop when I attempt to include it so, oh well.
