### ISSUE TITLE
Can't see administrators group anymore in ACP

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2781]
Can't see administrators group anymore in ACP under Manage -> Groups.

NodeBB v0.7.0-dev

**Comment by MegaGM** [comment]
I'm too.

**Comment by julianlam** [comment]
Making users admins is done in "Manage -> Users", and the administrators group shouldn't normally be edited. What did you need this for?

**Comment by pichalite** [comment]
Changing Badge text, icon and color...
