### ISSUE TITLE
Applying a container to widgets doesn't work on master

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2782]
Applying a container to widgets doesn't work on master. It's not adding the container to the widget no matter which one I pick.

NodeBB v0.7.0-dev

**Comment by pichalite** [comment]
Widgets that were already existing before git pull work fine.

**Comment by barisusakli** [comment]
Looks like templates.js regression :rage2:

**Comment by psychobunny** [comment]
yup, thanks

**Comment by pichalite** [comment]
@psychobunny still not working for me. I don't see the container applied to the widget on the forum pages.

**Comment by psychobunny** [comment]
Just to confirm, you have to add a new container, if you added the container while this bug existed

**Comment by psychobunny** [comment]
Shoot looks like I didn't commit the server component. Will do when I reach home

**Comment by julianlam** [comment]
Do it now :rage2: (just kidding)

**Comment by pichalite** [comment]
@psychobunny works mostly, minor issue. When I drag the Panel with header and body, the panel body has "\" in it which makes the container to not work.

```<div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">{title}</h3></div><div class="panel-body">\{body\}</div></div>```

**Comment by julianlam** [comment]
awesome, thanks :)
