### ISSUE TITLE
Ajaxify Cache: Going back to unread does not load latest unread posts

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2785]

**Comment by julianlam** [comment]
I'd argue that there is less of an expectation that going "back" to a page would load new unread posts. 

All over the web, if you hit back, the browser cached page loads, outdated content and all. 

For the sake of progress, if we *could* have the latest posts loaded, that would be best, but then at that point you may as well just disable the ajaxify cache on /unread :stuck_out_tongue:

**Comment by psychobunny** [comment]
My argument is you are only caching one history. Cache it all or don't cache at all imo

**Comment by psychobunny** [comment]
> All over the web, if you hit back, the browser cached page loads, outdated content and all.

1. Open Gmail, enter a thread
2. Email yourself from another app/email
3. Press back

Same behavior across anything you would classify as a modern app

**Comment by julianlam** [comment]
That's slightly different, as Gmail maintains a list of emails and updates that list irrespective of what page you're on. 

Note, if you lose connection and navigate, you can still enter topics you've been in, but half the time I use Gmail, it stops updating the unread cache until I hit refresh anyway. 

I can do that too with /unread, if you like :stuck_out_tongue:

**Comment by psychobunny** [comment]
What about plugin routes that expect fresh data?
