### ISSUE TITLE
[UX] Category View -> Topic View -> back does not mark topic as unread

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2790]
For ex. in Lavender, topic is still bolded and has a left border to indicate it is unread

**Comment by psychobunny** [comment]
Same issue on /recent

**Comment by julianlam** [comment]
@barisusakli can confirm, but I remember that a topic is not considered "read" unless you have scrolled to the bottom... not exactly sure if this is actually the case, however.

**Comment by julianlam** [comment]
Also, can't repro.

**Comment by psychobunny** [comment]
This was with the ajaxify cache, forgot to include that on the title
