### ISSUE TITLE
unread icon off

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2795]
not sure if its because of the menu.tpl changes @psychobunny 
![image](https://cloud.githubusercontent.com/assets/2583394/6387070/9b3eefd6-bd52-11e4-9f7e-5026a0af108a.png)

**Comment by psychobunny** [comment]
I noticed that too earlier today, but thought it was something you guys did

I'll fix

**Comment by psychobunny** [comment]
Actually I remember removing some margin-left -11px hax in vanilla today,
might have effected this too
