### ISSUE TITLE
Clicking on image selection icon on "New Topic" creation doesn't work

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2796]
Here's a screenshot from the community site. I clicked on the icon, nothing happens

![screen shot 2015-02-25 at 10 09 14 pm](https://cloud.githubusercontent.com/assets/10014774/6387177/67137a68-bd3b-11e4-9da9-158815d2a6c8.png)

**Comment by MegaGM** [comment]
++ If I don't mistake, it's since https://github.com/NodeBB/NodeBB/commit/ceb18fe73da77f5ba91bfa4e7af9e4fad7b05610
