### ISSUE TITLE
[UI] Plugin "Install" button text wraps when clicked to install the plugin

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2797]
![screen shot 2015-02-25 at 11 01 48 pm](https://cloud.githubusercontent.com/assets/10014774/6387590/582b81d8-bd42-11e4-8567-72fea98f9b83.png)

**Comment by julianlam** [comment]
@pichalite I can't reproduce this -- the button isn't constrained by width, so it expands to fit the enlarged text.

**Comment by julianlam** [comment]
Let me know if this is still an issue for you.

**Comment by pichalite** [comment]
I don't see this after updating to latest. closing issue.
