### ISSUE TITLE
Marking notifications as read/unread does not work

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2799]
Marking notifications as read/unread does not work. If I click the circle next to notifications, the UI changes to indicate that the notification is marked as read/unread but returns to it's original state if the notifications dropdown is opened again.

The unread notification count is incremented/decremented right after the topics are marked as unread/read but refreshing the page changes the count to the original number displayed before marking the notifications as read/unread.

**Comment by pichalite** [comment]
"Mark all notification read" doesn't work either.

**Comment by pichalite** [comment]
:+1:

**Comment by julianlam** [comment]
Marking all notifs read broken still. Plus no way to do so in mobile.

**Comment by barisusakli** [comment]
Weird it works on https://community.nodebb.org/ broken on latest?

**Comment by julianlam** [comment]
I ran into it a couple days back, will try again when I get home... hm

**Comment by barisusakli** [comment]
Can confirm mark all is broken on try as well, but marking read from the circle works.

**Comment by julianlam** [comment]
Thanks, yes, this is what I see as well.
