### ISSUE TITLE
connection has been lost error when registering an account

### ISSUE THREAD

**Issue by arasbm** [NodeBB/NodeBB#2805]
I received this report from one of the potential users of [our forum](http://community.kamloopsmakerspace.com
) who tried to register but could not. Here is all the information I have received so far from him:

> I've tried to register on you site. The registration does not complete and it says "Connection to Kamloops Makerspace has been lost, attempting to reconnect...."

> It's a win 8.1 laptop using Firefox. I have cable internet with a wireless router. No other connection problems. I have tried over two days to make the connection.

> I did the reboot. Cannot connect using Firefox, Chrome, or IE. I'm in Kitimat right now. Had my wife in Kamloops try to sign up with her computer. It worked fine for her.  I'll attach the traceroute from my location.

The user is pretty tech savvy and I can ask him to run command line tests if there is anything he can do to provide debugging information. 

The site is community.kamloopsmakerspace.com
Let me know if I can provide any more info to help debug this issue.

**Comment by tinfoilknight** [comment]
I'm the user in question. I've subscribed to this conversation to stay updated.

**Comment by julianlam** [comment]
@tinfoilknight Can you please give this a try: http://websocketstest.com/

**Comment by tinfoilknight** [comment]
It had three failures.


   - *WebSockets (Port 80)*ConnectedNo✘ Disconnected at 17:31:48
   - *WebSockets (Port 443)*ConnectedNo✘ Disconnected at 17:31:49
   - *WebSockets (Port 8080)*ConnectedNo✘ Disconnected at 17:31:49

I tried disabling the AV and turned off windows firewall. Still get those
ports blocked. There is nothing configured in the router for blocking ports.

**Comment by julianlam** [comment]
OS and browser please :)

**Comment by tinfoilknight** [comment]
Windows 8.1 64 bit, with Firefox. Tried again in chrome and IE and got the
same result.

**Comment by julianlam** [comment]
Unfortunately it may just be that your ISP is blocking websockets :frowning:

**Comment by tinfoilknight** [comment]
I will take it up with my ISP. On Sunday evening I will be able to try
again with a different ISP.

**Comment by pitaj** [comment]
You should still be able to use the site without web sockets IMO. That's one of the main reasons to use socket.io

**Comment by tinfoilknight** [comment]
Problem is with my computer, not the ISP.  Verified problem still happens
with different ISP and got the following reply from my ISP:

"We do not block any services, especially port 80, 443, which is used for
SSL transactions on the web and port 8080

is used for many other web services.



If we did that it would pretty much kill internet for everyone.


There might a firewall or some other device that you will have to open
those ports to allow access."

**Comment by julianlam** [comment]
Some anti-virus softwares *do* interfere with websockets, which is a bit of a problem. Even if it's "disabled", who knows...

Do other computers on the same network work?

**Comment by tinfoilknight** [comment]
Uninstalling adaware antivirus allowed the websockets to work. Shopping for
a replacement now

**Comment by julianlam** [comment]
Thanks for the update! :smile:

**Comment by Yatko** [comment]
Same issue here [community.h7.org](http://community.h7.org) (new install) registration/login won't work, tried with different ISPs and devises.

**Comment by Yatko** [comment]
./nodebb dev output, NodeBB address in use error: 

```sh
7/10 01:54:30 [19404] - info: Enabling 'trust proxy'
7/10 01:54:30 [19404] - error:  Error: listen EADDRINUSE 0.0.0.0:4567
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
7/10 01:54:30 [19404] - error: NodeBB address in use, exiting...
3 restarts in 10 seconds, most likely an error on startup. Halting.
```

**Comment by pitaj** [comment]
Open a topic on community.nodebb.org please

**Comment by Yatko** [comment]
Thanks @pitaj [here is the topic](https://community.nodebb.org/topic/11339/error-registering-new-account-connection-has-been-lost).
