### ISSUE TITLE
[UX] Route '/admin/anonexistentroute' should redirect to '/admin'

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#2807]
Would eliminate a click, if say, a plugin is removed and the plugin's settings page is reloaded.

Probably only useful to plugin devs, but it sure would make me happy. :grin:

**Comment by pitaj** [comment]
I disagree. Right now it shows a helpful error message. I don't think things that that should fail silently.

**Comment by yariplus** [comment]
Yeah, you're right, the error message is important. My issue is that it pops out of the admin panel, even if you were logged in and on the admin panel previously. Maybe I'll take a look at it and see if I can get it to nicely wrap the error in the admin panel if you're logged into it.
