### ISSUE TITLE
suggestion: grab vendor components from bower

### ISSUE THREAD

**Issue by vincentbriglia** [NodeBB/NodeBB#281]
instead of manually updating jquery, bootstrap one could use bower.

to fit the scheme for NodeBB; create a root level .bowerrc file with the following json:

``` JSON
{
    "directory": "public/vendor"
}
```

`npm install bower --save-dev`

`bower install bootbox --save`
`bower install bootstrap --save`
`bower install font-awesome --save`
`bower install jquery --save`
`bower install requirejs --save`

again, just a suggestion

**Comment by julianlam** [comment]
Started doing this (1.5 years later!), but am still unfamiliar with bower. How do I save the installed components in an easily referenceable file without running `bower init`? That command seems to be geared towards prepping a node package for inclusion *into* the bower index...

**Comment by julianlam** [comment]
As a reference to myself, this is what I have so far...

`bower install jquery jquery.ui bootbox fontawesome jquery-timeago jquery-form jquery-textcomplete visibilityjs bootstrap bootstrap-tagsinput tommoor/tinycon buzz ccampbell/mousetrap`

**Comment by vincentbriglia** [comment]
you can have a bower.json file in your repository without having to worry opening it up for the public. Just like a package.json, it's really just all about package management. 

after what you have above, if you do 'bower install' (just like npm install) and if you added an optional .bowerrc file, you will either see a 'bower_components' folder in the top-level folder where your bower.json file is or in the public/vendor folder.

you might have to change some paths around, as each vendor has different directory structures inside. 

I would suggest pinning your versions inside bower.json just like you pin your version numbers in the package.json file (i prefer the following notation over the ~ and/or ^ notation)

```json
  "dependencies": {
    "jquery": "2.1.x",
    "bootstrap": "3.3.x"
  }
```

part of your 'npm install' you could then have a script entry that says:
```json
    "postinstall": "node node_modules/bower/bin/bower install"
```
or if you have bower installed globally
```json
    "postinstall": "bower install"
```

**Comment by julianlam** [comment]
Mm, that's handy. If locally installed bower has a binary executable, that would be better than requiring our users install yet-another-system-dependency.
