### ISSUE TITLE
[question] [Redis] Export DB x / import DB y ... for NBB use ...

### ISSUE THREAD

**Issue by Couby** [NodeBB/NodeBB#2810]
Hope this is not a problem asking a more related Redis question, yet I don't find answer in Redis google group or stackoverflow...

I run multiple NodeBB instances on multiple servers. Having issues on the one with ARM architecture I'd like to move a forum on this server to another server.

So I'm looking for a way to export Redis DB x and import it as Redis DB y.

Any help from people mastering Redis welcome.

**Comment by Fusselwurm** [comment]
I think that's as easy as copying `/var/lib/redis/dump.rdb` & restarting redis

**Comment by Couby** [comment]
@Fusselwurm not really.
Doing that way I would overwrite other Redis DBs on the other server...

**Comment by Fusselwurm** [comment]
Okay, so I'm aware that this is not exactly what you're looking for here  ... but how about you run several redis instances on one host?

**Comment by julianlam** [comment]
@Couby we used to do this as well, although multiple database on one instance are discouraged in favour of multiple instances

**Comment by Couby** [comment]
@pitaj : hi, I can't assign labels as I'm not a contributor. Yet I put [question] [Redis] in the title as a way to propose some labels anyway :-).

@Fusselwurm & @julianlam : ok I didn't thought about that. That's all the more a good way to solve that "problem" as it is more recommended.
Will go that direction. Thanks a lot friends :-).

**Comment by MegaGM** [comment]
@Couby Does it not enough? http://redis.io/commands/MIGRATE

**Comment by Couby** [comment]
@MegaGM I'll take a look, sounds as a way to do what I was looking for to do, even if recommended practise is to use another Redis instance. Thanks :-).
