### ISSUE TITLE
Cleaning up your issues

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2812]
Okay, so I was going through your issues last night while trying to go to sleep (cuz, why the hell not), and I came across a few issues that I think are either fixed or don't have labels or whatever, so here it goes:

Issues related to how chats work (should probably merge them all into one)

 - #2211 - textarea hidden, pretty sure this is fixed (I haven't had any problems lately)
 - #1798 - Backend refactor
 - #2475 - Inbox limit
 - #2668 - Editing / Deleting chats
 - #1242 - Utilize taskbar for chats
 - #2158 - Remember scroll position
 - #2427 - Minor chat UX tweaks
 - #2574 - Don't send notification in not an empty string  
IMO, there shouldn't be any notifications sent at all for chats, as they should be a separate system altogether

Issues related to the ACP

 - #2808 - No reload notice for plugin update
 - #2869 - Better messaging for missing plugins
 - #2780 - Fontawesome icon picker
 - #2754 - Multiple modals messing with things
 - #2746 - ACP navbar search shows when no search plugin installed
 - #2699 - Google Docs style user presence
 - #2463 - Category management is complicated
 - #2268 - Undo events from ACP
 - #2165 - Upload new sounds and select "none" for sounds
 - #1966 - ACP config for IP blocks
 - #1643 - Customize language strings
 - #1509 - Asset manager
 - #2779 - Cloning category should clone permissions
 - #1972 - Admin lockout timer

Issues related to posts/topics

- #2773 - Mark as read is confusing
- #2637 - Infinite scroll stops working
- #2607 - Don't pass deleted posts if not mod
- #2515 - Special topic permissions for OP
- #2437 - Renamed topic urls don't redirect
- #2330 - Permission to purge should be separate from permission to edit
- #2309 - Post topic as locked / pinned
- #2269 - Scrolling to bottom of topic doesn't disable infinite scrolling
- #2069 - Confusing UX with thread restoration
- #1919 - Save as draft, and discard like Gmail
- #148 - Multiple ownership / editorship for posts / topics

Issues related to emails

- #2398 - Allow opt-in by default
- #2455 - Move digests from core to a plugin
- #2183 - Customizable email templates

Issues without labels

 - #2810 
 - #2773 
 - #2702 
 - #2637 
 - #2642 
 - #2613 
 - #2607 
 - #2502 
 - #2500 
 - #2465 
 - #2462 
 - #2319 
 - #2304 
 - #2302 
 - #2299 
 - #2268 
 - #2252 
 - #2183 
 - #2166 
 - #2144 
 - #2105 
 - #2060 
 - #1642 
 - #1637
 - #1529
 - #1528 
 - #1509 

Will continue later

**Comment by psychobunny** [comment]
Aw, "cleaning up your issues" - thought you meant you were going to start fixing all of them  :D

**Comment by damianb** [comment]
I know a secret to making *all* these issues disappear, @psychobunny. Just move all the files into `/dev/null` and nobody will be the wiser. :)

**Comment by julianlam** [comment]
Thanks @pitaj -- this will come in handy the next time we set out to cull the issue list :smile:

**Comment by drewdotpro** [comment]
Maybe cull before a new version release? If other developers are anything like me you hit a GitHub project, look at the stars, look at the last time someone worked on master, look at the number of issues and decide from those 3 pieces of info whether to even bother looking at the project. You're killing it for stars and commits, so you'd be a triple threat.

**Comment by benjaminabel** [comment]
tweeter recently released a tool for that purpose for the bootstrap package, it's called [NO CARRIER](https://github.com/twbs/no-carrier) it's a java program that closes automatically issues whith a specific label after a selected number of days.

**Comment by psychobunny** [comment]
I'm in the process of closing a bunch of random issues that isn't actually a NodeBB issue. This o guess is one of them. :p :wave:
