### ISSUE TITLE
Socket.io admin namespace for plugins

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2814]
Expanding on this: https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/plugins.js

Adding middleware to `plugins.admin.*` so plugin authors don't have to worry about having to write the user.isAdministrator check.

Not a big deal but one day somebody might write an admin call and forget to do that check

**Comment by MegaGM** [comment]
To make my plugins interacting with backend from client-side, I use something like this
```
var SocketModules = require.main.require('./src/socket.io/modules');
      SocketModules.myMethod = function () {};
```

Could somebody please tell me whether is there a better way? Which approach is the right now?

**Comment by psychobunny** [comment]
As per: https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/plugins.js

```
var SocketPlugins = module.parent.require('./socket.io/plugins');
SocketPlugins.myPlugin = {};
SocketPlugins.myPlugin.myMethod = function() { ... };
```

So that you don't clobber some module in core by accident

**Comment by MegaGM** [comment]
@psychobunny Thank you!

**Comment by barisusakli** [comment]
This is already done just add your methods to the `admin.plugins` object.

ie `socket.emit('admin.plugins.myPlugin.foo');` will check if the calling user is an administrator.
