### ISSUE TITLE
Incorrect behaviour when creating/replaying topic on mobile interface.

### ISSUE THREAD

**Issue by jarey** [NodeBB/NodeBB#2817]
When composing a new post (creating a new topic, or replaying) the buttons on the toolbar doesn't respond (only the last two icons of the bar are active, the question mark and the poll).

Furthermore the tag icon is shown instead the smiley icon that is shown on PC layout.

Here's an screenshot (Reproduced on Firefox and Chrome using Android):

![Image of Bug](https://i.imgur.com/hFs8fDp.png)

**Comment by julianlam** [comment]
Thanks @jarey, I think I know why this is happening.

**Comment by julianlam** [comment]
https://github.com/NodeBB/nodebb-theme-vanilla/commit/90f3aae10cfbc29aef56a8328e37db2c106ceeba
