### ISSUE TITLE
Users Navigation - route not accessible

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#2818]
I just noticed the "new"? navigation tab in acp because my users icon was gone.

After some tweaking, it appears that ```/users``` route seems not accessible.
But when I change it to ```/users/online``` , the icon is back again.

I can tell it's here from at least c40258a

**Comment by psychobunny** [comment]
How does your nav acp look like for users? Also there's another setting for private user info in Settings -> Users that if you check will override and hide the user icon as well

**Comment by tedr56** [comment]
My panel is the default. I even deleted it to add a default new one.

![screenshot from 2015-03-03 20 13 11](https://cloud.githubusercontent.com/assets/186070/6470176/06b17480-c1e2-11e4-99f4-fb91cacb703b.png)

My users info are indeed in private mode.
This leads to a strange behaviour since /users/online is still accesible.

**Comment by psychobunny** [comment]
> My users info are indeed in private mode.

Then in that case its fair to say this is working as intended? I'll fix the nav to hide any /users/? route

**Comment by psychobunny** [comment]
Also it seems like this icon should show up if you're an admin (which is why you noticed it "disappeared"). Will fix this as well
