### ISSUE TITLE
The sidebar slide down on topic page

### ISSUE THREAD

**Issue by blindson76** [NodeBB/NodeBB#2821]
The sidebar and widgets in it are sliding down on topic pages.
![indir](https://cloud.githubusercontent.com/assets/8769145/6510218/5887225a-c36d-11e4-883a-42566f7c73d1.png)

**Comment by julianlam** [comment]
This issue is incomplete, please provide NodeBB core version and theme versions [as outlined in CONTRIBUTING.md](https://github.com/NodeBB/NodeBB/blob/master/CONTRIBUTING.md).

**Comment by blindson76** [comment]
nodebb@0.6.1
├── nodebb-theme-lavender@0.2.13
└── nodebb-theme-vanilla@0.2.35

**Comment by psychobunny** [comment]
This is probably fixed by now, but if not, please repost on the actual Lavender theme thread as it is not a core issue. Thanks!
