### ISSUE TITLE
Guests can't access pictures 

### ISSUE THREAD

**Issue by niklas-heer** [NodeBB/NodeBB#2826]
Hi first of all great work you doing here!

__Now my problem:__
If a guests visits the site, he gets a **403 Error** every time something from `public/uploads/files` should be rendered.

_My setup:_
**CentOS 6** with **nginx/1.6.2** and the latest **nodebb** release **0.6.1**. We are also using clustering with 3 processes, but it was the same when we had it on our apache server with only one process.

Am I missing something here?
I also searched the forums but nothing helped.

If it helps here is the sites url:
http://linux-statt-windows.org/

![screenshot](http://screens.niklas-heer.de/ru7Sr3.jpg)

**Comment by barisusakli** [comment]
Hi can you take a look at your ACP setting for private uploads?

![image](https://cloud.githubusercontent.com/assets/2583394/6529041/1555ef02-c3f4-11e4-8559-18aa28b18f58.png)

If it is ticked, untick and save.

**Comment by niklas-heer** [comment]
Hehe shame on me! Thanks for the quick reply! It works now! :) Thank you <3

**Comment by psychobunny** [comment]
Shouldn't the site logo be something that's accessible despite this setting?

**Comment by psychobunny** [comment]
Shouldn't the site logo be something that's accessible despite this setting?

**Comment by MegaGM** [comment]
> Shouldn't the site logo be something that's accessible despite this setting?

Without doubts!
