### ISSUE TITLE
nbbpm not documented

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2828]
https://docs.nodebb.org/en/latest/plugins/create.html

```
nbbpm :{
compatibility: "x.y.z"
}
```
should be documented in the docs

**Comment by psychobunny** [comment]
:+1: 
man I built this originally now even I don't know how this works, wtb documentation

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-english/commit/dd3126766d85cc96c7f932ea04ea9af04d31afd4
