### ISSUE TITLE
nbbpm.compatibility not read by core

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2829]
its looking at compatibility

https://github.com/NodeBB/NodeBB/blob/master/src/plugins/load.js#L25

instead of 

https://github.com/NodeBB/NodeBB/blob/master/src/plugins/load.js#L216

**Comment by julianlam** [comment]
Nice! `nbbpm.compatibility` is used by the package manager, but good to know that check is done in NodeBB now too
