### ISSUE TITLE
Proposal: Keep posts and topics after user deletion

### ISSUE THREAD

**Issue by niklas-heer** [NodeBB/NodeBB#2832]
Hi,

I would like to propose the following:
1. The posts and topics  of an deleted/inactive user should not be deleted as well, because some conversations don't make sense that way.
2. It should be highlighted in some sort of way, that this user is not an "active" user anymore. (Maybe like the deleted posts for admins.)
3. There should be an option to keep the users account "inactive" for `x` amount of days, so that the account could be reactivated by the user in the set time frame, else it should be deleted and only proposal 1 and 2 should apply from that point in time.

I hope I could explain my ideas. I also hope that I didn't miss a similar proposal.

**Comment by pitaj** [comment]
Wait, are they deleted? I was under the understanding that they weren't deleted. Let me check...

Okay, you're right. I agree that this behavior is weird. Maybe making this an option in the ACP, like `[checkbox] Purge user topics and posts on user delete`, would be good. 

The posts would still display the username, but the rest of the user info would be removed, and the name wouldn't be clickable.

**Comment by niklas-heer** [comment]
@pitaj that would be great for the start, but I would like a more visual representation of posts from deleted users. (as described in proposal 2)
Also proposal (3) would be really nice, since the posts will be kept anyways.

**Comment by martyalicante** [comment]
i´m up with this proposal 
removing post from a user removes all his post and topics and of course post from others users that posted on his topics
not the way to go

**Comment by joolswills** [comment]
Is there an option to remove posts still along with a user also? - there is a use case for this and I use it all the time - when we have spammers join up (We have anti spam measures in place, but it's hard to stop human spammers). It's nice to be able just to remove the account completely, to clear up their posts. I agree it is useful to keep posts, but it would be good to have it optional.

**Comment by joolswills** [comment]
Apologies - I just read the diff in more detail and see it is optional - perfect. There is often little detail put in git changes here - just "closed XXX" - would be good to have a commit summary.
