### ISSUE TITLE
RSS feed items are missing a proper description 

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#2835]
The RSS feed items include only a link to the post as the description. The feed isn't very useful without at least an excerpt of the post content included in the description. 
```
<description>
<![CDATA[
<p><a href="http://antergos.com/blog/antergos-minimal-iso-for-those-who-dont-need-a-full-live-environment-and-want-a-faster-download/">http://antergos.com/blog/antergos-minimal-iso-for-those-who-dont-need-a-full-live-environment-and-want-a-faster-download/</a></p>
]]>
</description>
```

**Comment by barisusakli** [comment]
Which feed is this?

**Comment by lots0logs** [comment]
all of them.. though it was on `recent.rss` and `popular.rss` that I first noticed the issue.
