### ISSUE TITLE
Category ACL Dialog: Missing groups / privileges

### ISSUE THREAD

**Issue by MacounDe** [NodeBB/NodeBB#2836]
When clicking on "Options" and "Access Control" i'll get an "Category Permissions"-Dialog **without** groups or privileges settings. Just an "User Search" field. 

![screen 2015-03-09](https://cloud.githubusercontent.com/assets/1102043/6553624/e449fbea-c652-11e4-918b-3d23d581b1b7.png)

nodeBB Version: v0.7.0-dev
Database Version: redis 2.6.10

P.S.: To exclude unregistered users it should be like in this post: 
https://community.nodebb.org/topic/2371/faq-how-to-make-your-forum-private

**Comment by julianlam** [comment]
@MacounDe -- try with the latest version of NodeBB please (if not already latest commits).

Also, use websockets... xhr polling is shifty at best.

**Comment by MacounDe** [comment]
@julianlam I tried it and it didn't fix it.
* I also tried `reset all`. Problem still exists.
* I flushed the DB. Also din't help.

At last i completely wiped the nodebb dir and reinstalled from the scratch. Now it works. What's interesting: I've had exactly the same problem on two different machines. :confused:

**Comment by MacounDe** [comment]
Can't reproduce it anymore. So i close it
