### ISSUE TITLE
[scroll] Start loading before bottom of page is reached

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2841]
This would lead to a smoother experience, especially on mobile

**Comment by julianlam** [comment]
It is, actually :sobbing:

**Comment by pitaj** [comment]
Really? Huh. Maybe increase the buffer?

**Comment by julianlam** [comment]
Actually, I was just getting in, so now I can properly troll this issue :trollface: 

----

Luckily for you, this is already implemented, so I am closing it.

Unluckily for you, it is implemented in the `disney` branch, so bug @psychobunny about it :trollface:

**Comment by psychobunny** [comment]
Yeah, I have been working on a secret branch. Please re troll our infinite scroll after I eventually merge. Thanks ;)

**Comment by barisusakli** [comment]
Loading starts happening when you reach 85% of the page check here

https://github.com/NodeBB/NodeBB/blob/master/public/src/client/infinitescroll.js#L21-L22
