### ISSUE TITLE
Disabling local login in ACP

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2842]
This feature hasn't been thought out very well. The primary admin is always registered locally!

**Comment by julianlam** [comment]
Typically used if sites want SSO-only, which does happen.

Possibly show throw bootbox confirmation when checkbox clicked, and introduce `./nodebb reset settings` that reverts this?

**Comment by psychobunny** [comment]
Doesn't bode very well for hosted customers

**Comment by psychobunny** [comment]
Random thought, going to /admin should always get you a /login prompt, regardless of what is enabled or not?

**Comment by julianlam** [comment]
Yeah, that might work.. if you're an admin, then local login block in `login.tpl` doesn't hide?

**Comment by psychobunny** [comment]
If you are redirected from `/admin`

**Comment by barisusakli** [comment]
>Yeah, that might work.. if you're an admin, then local login block in login.tpl doesn't hide?

Can't tell if the user is admin if they are not logged in :laughing: 

Also just showing the login form isn't enough, right now this setting sends all posts requests to /login to 404.

https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L138-L141
