### ISSUE TITLE
SEO and friendly urls

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#2846]
Hello!!!

I would like to be removed from the url 'category', 'cid', 'pid', 'topic'. I think to make it through the plug-in, as not all need it, not to touch the source code.

To change this: `http://myforum.com/category/22/categoryname`
To: `http://myforum.com/categoryname`

And, to change this: `http://myforum.com/category/23/subcategoryname`
To: `http://myforum.com/categoryname/subcategoryname`

Same with topics.

Could you suggest something? What hooks require and in general it is possible to do it by means of plug-in? I on the right path?

**Comment by julianlam** [comment]
I'm sorry, this cannot happen, as the parameters are required for proper functioning of NodeBB. 

If we removed the cid or tid, we would no longer he able to make a topic with the same normalised slug as another topic. 

If you removed "topic" or "category", then you compound the problem further.

**Comment by atomoc** [comment]
So without changing the kernel will not work to solve this problem? 
Can then still change the kernel to create this plugin?

**Comment by atomoc** [comment]
A lot of work, but it's really need.

**Comment by julianlam** [comment]
It is possible to overwrite the routes to achieve what you desire (that is,
navigating by slug alone), but it would not scale well as every access
would require a search across the entire topic and category indices in
order to find the tid or cid you wish to access.

To *not* do this is a decision we've made long ago, but while it will not
be in core, it is completely possible via plugin.

I would recommend you start a discussion on the community forum.

**Comment by atomoc** [comment]
I find it difficult to translate what you write to me. In particular it is not clear:
> To **not** do this is a decision we've made long ago, but while it will not
be in core, it is completely possible via plugin.

**Comment by pitaj** [comment]
They decided to not do this a long time ago. 

It can be done with a plugin.

**Comment by atomoc** [comment]
Thanks!

**Comment by pitaj** [comment]
If you need any help, feel free to contact me with the chat feature on the forums.

**Comment by jraichur-group1200** [comment]
Did you make a plugin for it yet? I'm interested in doing this too.
