### ISSUE TITLE
SSO links on the login page don't work without refreshing the page.

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#2847]
When you click one of the providers to login with SSO, you are shown this message:
```
/api/auth/twitter Not Found
not-found
```

Upon refreshing the page it works as it should. 

I verifed this issue is also present on http://communiy.nodebb.org

**Comment by barisusakli** [comment]
Fixed on our forum as well. Thanks for reporting.

**Comment by lots0logs** [comment]
Thanks for the prompt response :+1:
