### ISSUE TITLE
peerDependencies is being deprecated

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#2848]
So, how should NodeBB handle themes which build upon other themes, like all of them. 

https://github.com/npm/npm/issues/6565

**Comment by jhnns** [comment]
`peerDependencies` *won't* be deprecated https://github.com/npm/npm/issues/6565#issuecomment-74971689

They will just not be installed auto-magically.

**Comment by julianlam** [comment]
Thanks @jhnns. We'd prefer the dependent package were installed automatically (as they're supposed to be *dependencies* after all, but then we're just arguing semantics.

**However**, `peerDependencies` have been more trouble than they're worth, so I'd advocate removing them from our plugins altogether.

@akhoury uses them in one package afaik, that's about it.

**Comment by julianlam** [comment]
> The problem of keeping plugins versioned consistently with the thing to which they plug in is still a big one for many projects. The problem is that peerDependency handling often causes more problems than it solves, and has a bad habit of putting developers right back into the dependency hell that npm tries to help you escape.

Oh this is good, at least it won't error out anymore, so there's no compelling reason to *remove* them from plugins' `package.json` altogether.
