### ISSUE TITLE
Template variable error when cold loading directly from /category route

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#2856]
When cold loaded in any category, which is the error:

![screen shot 2015-03-12 at 7 51 49 pm](https://cloud.githubusercontent.com/assets/113159/6630639/a19fe326-c8f1-11e4-9af7-d1952711163f.png)

When browsing from then back to (ajaxified) that category, it works:

![screen shot 2015-03-12 at 7 52 56 pm](https://cloud.githubusercontent.com/assets/113159/6630645/a91da016-c8f1-11e4-8291-35ec6c40e0f1.png)

The variable would be: ``{name}`` in the ``category.tpl`` template.

**Comment by cnvo** [comment]
Actually here:

```
<input type="hidden" template-variable="category_id" value="{cid}" />
<input type="hidden" template-variable="category_name" value="{name}" />
<input type="hidden" template-variable="category_slug" value="{slug}" />
<input type="hidden" template-variable="topic_count" value="{topic_count}" />
<input type="hidden" template-variable="currentPage" value="{currentPage}" />
<input type="hidden" template-variable="pageCount" value="{pageCount}" />
```

**Comment by barisusakli** [comment]
Same bug as https://github.com/psychobunny/templates.js/issues/29 I believe?
