### ISSUE TITLE
Moving or deleting posts in preexisting topic causes NodeBB to crash

### ISSUE THREAD

**Issue by Korynkai** [NodeBB/NodeBB#2858]
Seems when attempting to move or delete a post from one preexisting topic to another, my Apache server returns a 503: Service Unavailable with NodeBB's dev log showing the error message posted here: https://gist.github.com/Korynkai/86cc33f6711031abb3a4 or https://gist.github.com/Korynkai/b4f7b48f136f42739a2d depending on which was called ... Any known workaround for this? Specifically, shouldn't `postData.pid` on that line be simply `pid`? Not quite sure about that object call though without looking at the code in more detail...

**Comment by barisusakli** [comment]
Hey what git revision is this happening on?

**Comment by Korynkai** [comment]
This is occurring at f7f048f06a6b3056c255c88b996ddaf6bbfdf8e4.

**Comment by barisusakli** [comment]
Both moving and deleting should be fixed thanks for reporting.
