### ISSUE TITLE
Fix broken links on readme 

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2859]
![](http://i.imgur.com/9fIyIol.jpeg)

**Comment by cnvo** [comment]
http://convoe.com -> https://bvse.co

**Comment by julianlam** [comment]
@cnvo That link doesn't work for me either :frowning:

**Comment by cnvo** [comment]
For some reason it automatically 404's on maintenance mode. Could be an nginx configuration issue. :-1:
