### ISSUE TITLE
Admin widget areas not showing all areas.

### ISSUE THREAD

**Issue by xbenjii** [NodeBB/NodeBB#2868]
Basic install on fd5f00459b0ec28e6bb3e81661ad90b30515fb4f

Shouldn't the header/footer be here too?

![](https://xbenjii.co.uk/i/RupIX)

**Comment by julianlam** [comment]
Nothing in the "global" section?

**Comment by xbenjii** [comment]
The global section is fine, but I don't want it on every page.

![](https://xbenjii.co.uk/i/4ewN2)

**Comment by xbenjii** [comment]
Just to add,
```
hgetall widgets:categories.tpl
```
returns
```
1) "sidebar"
2) "[]"
3) "header"
4) "[]"
```

**Comment by psychobunny** [comment]
Closed due to lack of activity, that said, if it's still a problem after you upgrade to latest NodeBB I'm more than happy to debug :)
