### ISSUE TITLE
RSS feed entries always use the topic's information, even for posts. 

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#2872]
Currently, the RSS feeds generated by the NodeBB use the topic information for each feed item. This means that new posts will produce a new feed item as expected, but the information that is included for the feed item/entry (description, author, date, etc) is taken from the topic instead of the post. I am not sure if it's the intended behavior or if its a bug. IMO, it's a bug because the resulting RSS feed shows what appears to be duplicated feed items.

**Comment by barisusakli** [comment]
Are you still having this problem? If so which feeds is it /topic/id.rss or /recent.rss etc.

**Comment by lots0logs** [comment]
Yes. The feeds I see the issue with are `recent.rss` and `popular.rss` I have not checked other feeds, though I dont think it would affect `topic/id.rss` (for obvious reasons)

**Comment by lots0logs** [comment]
I'll port your change tonight and let you know the result!

**Comment by lots0logs** [comment]
The behavior has not changed. It still displays each feed item using the title, author, and description of the topic instead of the post that triggered the feed item in the first place. The post author and description should be used (IMO).

**Comment by barisusakli** [comment]
Yeah I see what you mean, /recent is a list of topics but the order of that list is updated by the last post. But the description of the feed item is always the content of the main post intead of that last reply. Same for author its always the OP. Not sure if we should update those to be the last post in the topic. @julianlam ?

**Comment by julianlam** [comment]
I tend to agree. Even our api doesn't show the original post content, just the last post teaser, so the same should be done with the RSS feed.

**Comment by lots0logs** [comment]
I finally had time to pull the latest from master and see the results of your changes. It's not quite resolved yet :grimacing: Now the feed only displays one entry for each topic (the last post to that topic). So basically if a topic had multiple post in a 24 hour period, only the last post shows in the feed which isn't particularly useful since you could be missing any number of posts prior to the last post to the topic (in the last 24 hours). Does that makes sense? Also, I'm using 24 hours as an example, I'm not sure what time frame you guys are using for recent posts so if its wrong then just forget I said 24 hours :sweat_smile:

**Comment by barisusakli** [comment]
Hmm that was the case before my changes as well, /recent.rss displays a list of topics it doesn't/shouldn't display duplicate topics with the current code.

It grabs the latest 20 topcis that received a reply and populates the list.

**Comment by lots0logs** [comment]
I see. Is there any chance of making a recent posts endpoint available? In its current form the recent rss feed is not very useful (to me anyway, others may disagree)
