### ISSUE TITLE
Text in curly brackets in topic or post not shown

### ISSUE THREAD

**Issue by tekojo** [NodeBB/NodeBB#2874]
Any text inside curly brackets is hidden in topics or posts.

For example the text "layout{this};"  would be rendered as in the post "layout;"

See:
https://community.nodebb.org/topic/4010/testing-code-and-curly-brackets

**Comment by julianlam** [comment]
Thanks @tekojo, we are aware of this bug and @psychobunny is working on a solution :smile:

**Comment by tekojo** [comment]
:) excellent

**Comment by julianlam** [comment]
@psychobunny Relevant downstream community awaiting updates: http://forum.qt.io/topic/52320/this-forum-swallows-braces-if-no-whitespace-between-and-with-layout-this/12

**Comment by psychobunny** [comment]
duplicate: #2830
