### ISSUE TITLE
Separate out require.js configuration into a partial, so new paths can be added without blowing everything up

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2875]
Last two times I added something to the require.js config, we had to deal with 2 months' worth of bug reports because people were using outdated theme versions.

By moving this out of the themes and into a partial hosted in core itself (thanks for `/src/views`, @psychobunny, really), I'll hopefully be able to eliminate this as a problem.

**Comment by psychobunny** [comment]
nice. maybe this should be a core partial as well:

```
	<script>
		var RELATIVE_PATH = "{relative_path}";
		var config = JSON.parse('{configJSON}');
		var app = {
			template: "{template.name}"
		};
		app.user = JSON.parse('{userJSON}');
	</script>
```

**Comment by julianlam** [comment]
Yeah, looks good to me.
