### ISSUE TITLE
Template engine closing tags for no reason

### ISSUE THREAD

**Issue by Ribesg** [NodeBB/NodeBB#2882]
https://community.nodebb.org/topic/4022/nodebb-template-results-in-something-completely-wrong

I tried to look at the code of templates.js but didn't *understand* anything there.

**Comment by Ribesg** [comment]
Ok, I found one of the cause of the problem. This post contained a link.
Writting it as plain text or using markdown gives the same result shown in the post above.
**Removing it fixes everything**

So yeah! I'll just have to ban using link in posts! ...

Yeah no, something's wrong and it's linked to the content of the post. It shouldn't.

**Comment by Ribesg** [comment]
I ended up adding ``a`` to ``stripTags`` [here](https://github.com/NodeBB/NodeBB/blob/v0.6.x/public/src/utils.js#L207). It's a workaround but it obviously disables links completely, preventing them from appearing on the front page.

**Comment by psychobunny** [comment]
tj.s version?

Post a link to your full tpl file and api return if possible

**Comment by Ribesg** [comment]
I tested it on version 15 and 30, as well as some others in between those (27 I think, maybe 29). No change.

[API return for / and home.tpl](https://gist.github.com/Ribesg/af788d079c24b88cdc44)

**Comment by julianlam** [comment]
Hi @Ribesg, let me know if this issue still persists, and we'll reopen.

**Comment by Ribesg** [comment]
What is supposed to having fixed it?
