### ISSUE TITLE
Include subcategories recent topics in getRecentTopicReplies()

### ISSUE THREAD

**Issue by EvSpirit** [NodeBB/NodeBB#2886]
When you have some subcategories in a category, it's recent topics listing won't include subcategories topics. I thinks it would be great to include such topics in a result set.

**Comment by EvSpirit** [comment]
Solution is quite simple, but I'm not good at JS dev, so sorry for missed Pull Request :)

recentreplies.js

Look at assignPostsToCategory:
````
...
return post.category && parseInt(post.category.cid, 10) === parseInt(category.cid, 10);
...
````

we should make it like this:
````
			return !!(post.category && (parseInt(post.category.cid, 10) === parseInt(category.cid, 10)
			) || (parseInt(post.category.parentCid, 10) === parseInt(category.cid, 10)));
````

The only problem is that **parentCid** is missed cause posts are fetched without that param. My solution is a bit straightforward - we can pick it up at getRecentTopicReplies() cause there are all categories with parentCid defined.

````
				posts.forEach(function(post) {
					for(var i=0; i<categoryData.length; i++) {
						if(categoryData[i] && parseInt(categoryData[i].cid, 10) === parseInt(post.category.cid, 10)) {
							post.category.parentCid = categoryData[i].parentCid;
							break;
						}
					}
				});
```` 

I do sure that you'll find a much better solution, but I hope that would save a bit time :)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/2890
