### ISSUE TITLE
Issue installing NodeBB with Mongo

### ISSUE THREAD

**Issue by dsharer** [NodeBB/NodeBB#2888]
If I setup NodeBB with MongoDB, I get warn: NodeBB Setup Aborted. [[error:no-category]].

**Comment by barisusakli** [comment]
See my answer on the forums. https://community.nodebb.org/topic/4059/cannot-get-through-setup-with-mongo

Try with the mongodb3.0 branch.

**Comment by barisusakli** [comment]
The branch is on master now, let me know if you run into any issues.

**Comment by dsharer** [comment]
@barisusakli With the latest on master, I got it to install again using mongo.. Thanks!

**Comment by pykiss** [comment]
Same error, with docker

    nodebb/docker        centos              f6fededf225b
    nodebb/docker        ubuntu              d6efb9254666
    mongo                latest              5c87d8a0a8da
