### ISSUE TITLE
what's the use of cid:<cid>:read_by_uid?

### ISSUE THREAD

**Issue by cismous** [NodeBB/NodeBB#2892]
I have search it on the source code, but down't know what is it useful?

**Comment by julianlam** [comment]
Keep track of whether categories are unread, as far as I know. @barisusakli can confirm, then close.

**Comment by cismous** [comment]
@julianlam  Yes, so you can know whether categories are unread, but what's it can used to do something?

**Comment by barisusakli** [comment]
You can use it on the categories listing to show an icon next to unread categories. Keep in mind a category is marked read when a topic inside is read. We don't keep track of all unread topics in categories.
