### ISSUE TITLE
Debugging environment problem

### ISSUE THREAD

**Issue by EvSpirit** [NodeBB/NodeBB#2893]
Hi there!

I've noticed one strange thing - when you start project in InteliijIDEA (or similar) with debugger it cannot load minified JS. I checked local path ./public/nodebb.min.js and it's there, everything is fine, but at the same time it cannot be loaded via web. (http://localhost:4567/nodebb.min.js returns nothing). 

The thing is that IDE starts up project with --debug-brk=NNNNN option (where NNNNN is a random port number). It also adds --nolazy option, but it seems it changes nothing about JS loading. 

The solution is to launch the project manually with just --debug=NNNNN option (not a --debug-brk) and then connect with debugger separately. 

I suppose the problem is in --debug-brk option. Does anyone meet the same difficulties?

Thanks in advance!

**Comment by julianlam** [comment]
@EvSpirit When you use `debug-brk`, does NodeBB not load at all, or just the minified file?

Possibly the process is not forking properly (in order to minify or recapture the minified js), so it is blank. The file as written to disk is there purely for services like nginx to serve as static assets.

**Comment by EvSpirit** [comment]
@julianlam , everything works except JS. admin.css and stylesheet.css are in place, pictures are accessible too. The only problem is JS. More than that - I copy-pasted nodebb.min.js content to test.min.js - and it can be accessed via web too. 

**update:** I debugged all the stuff a bit and that's what I've found:

meta.js
Minified JS is handled here:
````
function sendMinifiedJS(req, res, next) {
	res.type('text/javascript').send(meta.js.cache);
}
````

````
module.exports = function(app, middleware, controllers) {
	app.get('/stylesheet.css', middleware.addExpiresHeaders, sendStylesheet);
	app.get('/admin.css', middleware.addExpiresHeaders, sendACPStylesheet);
	app.get('/nodebb.min.js', middleware.addExpiresHeaders, sendMinifiedJS);
	app.get('/sitemap.xml', controllers.sitemap);
	app.get('/robots.txt', controllers.robots);
	app.get('/css/previews/:theme', controllers.admin.themes.get);
};
````

The problem is that minified JS cache is empty (checked via debugger).

After that I checked minifier:
````
var minifier = Meta.js.minifierProc = fork('minifier.js')
....
....
			minifier.on('message', function(message) {
				switch(message.type) {
				case 'end':
					Meta.js.cache = message.minified;
					onComplete();
					break;
````

I putted a breakpoint here and checked forked process with ps -ef : 
````
/usr/local/bin/node --debug-brk=58094 --nolazy minifier.js
````

So it's forked with --debug-brk param.

**Comment by EvSpirit** [comment]
I've just created a PR with a solution of the problem. Actually, it's quite simple:

````
			var forkProcessParams = {};
			if(global.v8debug) {
				forkProcessParams = {execArgv: ['--debug-brk=' + (global.process.debugPort + 1)]};
			}

			var minifier = Meta.js.minifierProc = fork('minifier.js', [], forkProcessParams),
````

@ js.js 

Please, review it, but it seems to be correct. I checked that locally - everything is fine, JS loaded correctly.

**Comment by barisusakli** [comment]
Follow up in PR
