### ISSUE TITLE
Categories visibility problem after 0.6.x --> 0.7.0-dev migration

### ISSUE THREAD

**Issue by EvSpirit** [NodeBB/NodeBB#2896]
Hi there!

It seems there is a problem with categories filtration after migration. Right after running upgrade script the main page became empty. I haven't looked into code yet, but I suppose the problem is in parentCid param. I played around a bit with categories and found out, that newly created category is visible @ main page. At the same time, old categories are accessible via direct link too. It can be "hotfixed" with the following hack:
* create new category
* add an old category to the new one as a child cat 
* check if it's visible as a subcategory
* move subcategory pack

I'll try to check it on my own a bit later ;)

**Comment by EvSpirit** [comment]
Yeap, I confirm that there is no parentCid after migration and that's the reason of the problem (checked via redis keys)

**Comment by barisusakli** [comment]
Hmm are you sure this is caused by parentCid? I have some categories with no parentCid field but they are still visible on the home page.

Check the privileges for the category as well to make sure registered-users have find read access.

**Comment by EvSpirit** [comment]
Hmm, strange enough. I think all the values should be compared. Unfortunately, I've not debbuged that yet. May be some other values are missed, but moving some old category to subcategory and back again fix the problem for sure.
