### ISSUE TITLE
Search doesn't work if key words are in cyrillic

### ISSUE THREAD

**Issue by EvSpirit** [NodeBB/NodeBB#2897]
I've noticed that if dbsearch plugin is installed, it doesn't work for russian letters. At the same time, it works perfectly with en-requests.

**Comment by julianlam** [comment]
This is likely a limitation of the reds search engine. I'd advise you use Solr instead.

**Comment by EvSpirit** [comment]
Yeap, that's what I'm working on. Thanks for your advice, @julianlam !
