### ISSUE TITLE
Registration error on latest master

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2898]
Updated to latest master and getting error on user registration.

![screen shot 2015-03-25 at 7 06 45 pm](https://cloud.githubusercontent.com/assets/10014774/6839198/1fda6894-d322-11e4-8c00-1e80e400db26.png)

**Comment by julianlam** [comment]
Still an issue?

**Comment by pichalite** [comment]
That was on a test installation. Started getting the error after I pulled in the latest code for v0.7.0-dev. Dropped the database and setup NodeBB again and didn't see the error.

Tried the same thing on another test instance. Getting the same error.

**Comment by Jenkler** [comment]
I can can confirm this issue, user get null as id

**Comment by psychobunny** [comment]
Anybody still running into this? It's been a few months and the issue hasn't come up again

**Comment by barisusakli** [comment]
On the instance that is not working check the mongodb dependency version. It should be 2.0.0+ if you are using nodebb 0.7.0.
