### ISSUE TITLE
Themes should be looked up via config and not in the database

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#2899]
So I hit a roadblock here somewhat when doing some theme development. I was trying to use the same database for another instance of NodeBB on the same server;

``nodebb`` and ``staging.nodebb``

The problem here is, I wanted to use different themes for both of them, but I cannot using the same database because that just isn't possible. I was thinking, one instance's theme shouldn't effect another instance's theme.

My solution would be to take theme lookups out of the database in favor of putting it in the configuration or somewhere else static. I hope you guys understand how much of a pain this is when doing themes, updating them, and etc.

**Comment by pitaj** [comment]
No, they should definetly be sued in the database. Only information that absolutely must be stored in the config should be there. 

It would be better to just create a link between databases or a canned database.
