### ISSUE TITLE
warn: [meta/templates] Partial not loaded: admin/partials/fontawesome.tpl

### ISSUE THREAD

**Issue by cismous** [NodeBB/NodeBB#2901]
'/NodeBB/src/views/admin/manage/category.tpl' need 'admin/partials/fontawesome.tpl'

I can't find out it

`<div id="icons" style="display:none;">
	<div class="icon-container">
		<div class="row fa-icons">
			<i class="fa fa-doesnt-exist"></i>
			
		</div>
	</div>
</div>`
This code should be deleted?

**Comment by julianlam** [comment]
Possibly there is a file I did not commit.

**Comment by cismous** [comment]
Mabye, but i think it not used to do somthing.

**Comment by julianlam** [comment]
Sorry, check again.

Fixed via d4e28c4 and 0d044c3
