### ISSUE TITLE
Need to press back twice after composing on mobile to go back

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2903]
My temporary work around for the sidebar bug has been to hit back after composing a post. However, this is just causing the topic go ajaxify to itself, possibly because it is going from `#composer` back to the topic. 

So I need to click back twice.

**Comment by psychobunny** [comment]
> My temporary work around for the sidebar bug 

What's the commit for that?

**Comment by julianlam** [comment]
Hm? There's no commit, I just mean I press back twice when I've finished posting.

**Comment by psychobunny** [comment]
Oh. Misinterpreted:

> My temporary work around for the sidebar bug
