### ISSUE TITLE
Deprecate reputation thresholds

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#2904]
Back when we built NodeBB I had the awesome idea that we should build in trust levels that grant you access to moderator-like features once you reached a certain reputation threshold. (Actually, after being pointed out otherwise by @psychobunny, I was inspired by stackoverflow originally)

In hindsight, I don't think anybody uses it, and at worse, it's surprising when somebody discovers that this is by default active. *Surprise!* It's a neat mechanic when you're building a novel application, but not so much when you're attempting to improve upon decades of solidified forum-style behaviour.

It also adds a little bit of overhead to the entire privilege checking mechanic, in addition to the regular `isModerator`/`isAdministrator`/`hasPrivilege` checks...

So in the interest of simplicity, we're cutting this out for 0.7.0. The *proper* way to do this is to build a plugin that listens for the `filter:user.isModerator` hook, and updates the Boolean values as necessary.

**Comment by pichalite** [comment]
:+1:
