### ISSUE TITLE
topic/browsing/list component element is changed to block positioning by nodebb client-side script

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#2912]
Not sure when exactly this started happening though I think around the same time I ported the new template "components" code from Lavendar.

Screenshot:
![2015-03-28_06-49-23-pm](https://cloud.githubusercontent.com/assets/4675662/6883447/32f5406a-d57b-11e4-9706-fa638de14ce3.png)

Here is the HTML from the client:
```html
<div component="topic/browsing/list" class="thread_active_users active-users inline-block" style="display: block;">
    <div class="inline-block">
        <a data-uid="678" data-count="1" href="/user/lots-0-logs">
            <img title="" src="/uploads/profile/678-profileimg.png" data-original-title="lots.0.logs">
        </a>
    </div>
</div>
```

**Comment by barisusakli** [comment]
Can't reproduce this on lavender 1.0.26 vanilla 1.0.80 and latest core.

What are your theme versions and core revision?

**Comment by lots0logs** [comment]
Lavender: 1.0.26
Vanilla: 1.0.80
Core: 8026b3c7d832a52a4163102849f211ecc0198089

I'll try to pull in the latest from master and see if the issue is resolved ASAP. Thanks.
