### ISSUE TITLE
Install NodeBB via one single command or via package

### ISSUE THREAD

**Issue by unixfox** [NodeBB/NodeBB#2913]
Ability to install NodeBB via a shell script or via package (example : .deb / .rpm / repo).

I can do it when I have free time.

**Comment by unixfox** [comment]
Can you create a new repo Github to host the shell script or I have to put in the current repo NodeBB ?

**Comment by julianlam** [comment]
You're free to handle the packaging on your own, and possibly submit it as a PPA? That would be nice :)

This is beyond the scope of our work, so we wouldn't be able to maintain it, however.

**Comment by psychobunny** [comment]
> I can do it when I have free time.

I think he might have been asking us to create a repo like NodeBB/xxx and he would maintain it?

**Comment by unixfox** [comment]
@psychobunny Yes but I can create the repo on my github. I asked you that to have more visibility if the deposit was in the group NodeBB.

**Comment by psychobunny** [comment]
That makes sense. Once you get it up and running you can transfer over the repo (if you wish) and we can make a group for linux package maintainers and make you a member :)

**Comment by unixfox** [comment]
@psychobunny Thank you ! I will work on [this](https://github.com/unixfox/NodeBB-AutoInstall) tonight.
