### ISSUE TITLE
[0.7.x] Cannot select icon for the category

### ISSUE THREAD

**Issue by aixnr** [NodeBB/NodeBB#2915]
![screen shot 2015-03-29 at 12 02 27 pm](https://cloud.githubusercontent.com/assets/1288147/6886419/9a4390d8-d60b-11e4-8701-66bac9944c75.png)

I tried clicking on the icon, but nothing happened.

**Comment by julianlam** [comment]
Report commit hash please

**Comment by aixnr** [comment]
Most recent commit, `8026b3c`.

**Comment by psychobunny** [comment]
I ran into this same problem when updating the community this morning. Turns out that I was ahead on core but behind on nodebb-theme-vanilla, specifically [this commit](https://github.com/NodeBB/nodebb-theme-vanilla/commit/03a4bfda36ce950e7d3b7e395a8c19839513bab3)
