### ISSUE TITLE
Don't update pagination # when scrolling, update position when stopped

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#2923]
Its still an issue with Chromium when scrolling up or down on a topic or in the category theres some lag/delay. This has been an issue for a long time now that I brought up before. 

The best way to fix this I've noticed is to not update the pagination # on a scrolling event like it is now, but instead updating the pagination # when the user has stopped scrolling to that certain position.

Example:
//example.tld/topic/#/topic.name/ ``##``

The last numbers is what I am referring to.

**Comment by MegaGM** [comment]
It would be awesome!!

**Comment by barisusakli** [comment]
We don't update the url on every scroll, we update it when the url actually has to change, ie you go from one post to another.

https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic.js#L235
