### ISSUE TITLE
NodeBB crash when logging in with wrong password

### ISSUE THREAD

**Issue by lullerhaus** [NodeBB/NodeBB#2934]
There seems to be issue with latest NodeBB v0.7.0-dev that crashes NodeBB when attempting to log in with invalid password.

Here's link to crash log.
[https://paste.kde.org/poj5gsqms/z4ewcx](https://paste.kde.org/poj5gsqms/z4ewcx)

i'm on latest _master_ branch with commit
>commit 3efb1345e008410d392e37f0f1e67269cf4ecf93
>Author: barisusakli
>Date:   Thu Apr 2 17:33:28 2015 -0400

**Comment by julianlam** [comment]
Thanks @lullerhaus!
