### ISSUE TITLE
Notifications page shouldn't truncate with ellipsis

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2935]
Otherwise you can't click on the actual notification link on mobile

**Comment by barisusakli** [comment]
works for me the entire text links to the post.

![image](https://cloud.githubusercontent.com/assets/2583394/7034145/7ffab582-dd4d-11e4-8e82-2f087f59cf26.png)

**Comment by psychobunny** [comment]
derp, guess you're right
