### ISSUE TITLE
some groups cover images dont show up on mobile

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2937]
https://community.nodebb.org/groups/anime-lovers is not visible if browsers width < 500px

**Comment by julianlam** [comment]
:rage2: `background-type: cover;` means the actual dimensions of the image change relative to the CSS. TIL.

Should switch to %age...

**Comment by julianlam** [comment]
Reported upstream: kentor/jquery-draggable-background#16

**Comment by julianlam** [comment]
Looking at how this is handled on Facebook: The profile page has a fixed width, so this issue is sidestepped altogether.

I'd still personally prefer if the plugin above supported percentages, however.

**Comment by julianlam** [comment]
Fixed via e147328
