### ISSUE TITLE
When i click '.navbar-toggle' to open other page, the '.navbar-collapse' didn't hide, is a bug?

### ISSUE THREAD

**Issue by cismous** [NodeBB/NodeBB#2938]
![selection_009](https://cloud.githubusercontent.com/assets/3208016/6992226/53526b52-daf4-11e4-94ba-ee9e77115df4.png)

**Comment by cismous** [comment]
ajaxify.end = function(url, tpl_url) {
	if(($('.navbar-collapse').attr('aria-expanded'))==='true') {
		$('.navbar-toggle').trigger('click');
	}
};

i use this to fix it for the time being

**Comment by barisusakli** [comment]
Update to latest lavender this should be fixed there.
https://github.com/NodeBB/nodebb-theme-lavender/commit/b0cde07ba7bb3ff10e28b19b49d261b9542d092c
