### ISSUE TITLE
# of category posts incorrect after upgrade to 0.7.0 from 0.6.x

### ISSUE THREAD

**Issue by frenchja** [NodeBB/NodeBB#2939]
CentOS 2.6.32
Redis 2.8.9
Node v0.10.31

I copied all the keys in Redis DB 0 to 1, and ran `./nodebb upgrade` from the fresh git clone on the copied DB.

![screen shot 2015-04-05 at 8 07 52 am](https://cloud.githubusercontent.com/assets/720035/6996936/a80e5d6e-db6b-11e4-80a8-0000915ffba7.png)
![screen shot 2015-04-05 at 8 08 04 am](https://cloud.githubusercontent.com/assets/720035/6996938/acd5e90c-db6b-11e4-8d4f-1f22cbc36d1e.png)

**Comment by barisusakli** [comment]
You can fix this through redis-cli. 

Find the category id of the category `Interociter` then run the following commands.

```
redis-cli
zcard cid:<category_id>:pids #this gets the number of posts in that category
hset category:<category_id> post_count <value from above command> #set the value into category hash
```
