### ISSUE TITLE
Option to grant permissions recursively to all a parent category's children

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#2941]
The new categories interface is a huge improvement over the previous one ( thanks @julianlam ). That being said, configuring permissions is still a very tedious process when you have many categories/child categories. It would be great if there was an option to apply a permission change recursively to all children of a parent category. Is that something you guys could implement without much effort and if so would you consider it?

**Comment by MegaGM** [comment]
you meant literally smth like additional button "copy permissions of current category for every children categories"? if yes - it's sounds great, but mb will be better not to be able to copy from current category to all their childrends, but to be able for each category to "copy permissions from <a dropdown> category"? it seems even more flexible

**Comment by NukeRusich** [comment]
+1
