### ISSUE TITLE
Security: Logout not clearing the session immediately

### ISSUE THREAD

**Issue by kumarbalap** [NodeBB/NodeBB#2942]
I have opened 2 tabs in a browser.

1 window, I have opened the new Topic button, and composing.
Another window, I just clicked the logout button.

I came back to the first window, and added some more content and I'm able to post the data.

We should have middle ware to handle all the requests for authentication.

Thanks,
Bala

**Comment by pitaj** [comment]
This is how pet much everything online works. Google services work this way. The session is only maintained for that browser tab. It isn't maintained in the computer.
