### ISSUE TITLE
Long loading categories in the admin page

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#2943]
If count categories > 1000 their loading is very very long in admin panel, more than half a minute, at a sufficiently good server.

Can do pagination with sorting and searching? :)

Continuing [the post](https://community.nodebb.org/topic/4160/long-loading-categories-in-the-admin-page).

**Comment by barisusakli** [comment]
Let us know how much the above commit helps.

**Comment by atomoc** [comment]
It did not help.

**Comment by barisusakli** [comment]
Does it still take 30+ seconds? Also post the network call so we can get a better info about timing and data size.

**Comment by atomoc** [comment]
I do not quite understand what you mean. Can i give you access?

**Comment by atomoc** [comment]
Yes, 30+ seconds.

**Comment by atomoc** [comment]
Thanks! Very cool and beautiful!

**Comment by atomoc** [comment]
7 seconds on the very powerful server, normal!
