### ISSUE TITLE
Deploying to Heroku results in an error and app crash due to Error R10 boot timeout

### ISSUE THREAD

**Issue by AXtime** [NodeBB/NodeBB#2945]
v0.6.1 - I followed the manual for Heroku, but after pushing the build would always get;

Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

I was able to get things working by adding Heroku's PORT environment variable to the getPorts() function in loader.js

I changed line 185 from 

`var port = nconf.get('port') || nconf.get('PORT') || urlObject.port || 4567;`

to

`var port = process.env.PORT || nconf.get('port') || nconf.get('PORT') || urlObject.port || 4567;`

**Comment by julianlam** [comment]
thanks. I wonder why this happened -- `nconf.get('PORT');` should've read the environment variable. Perhaps this changed recently with grunt integration, @psychobunny ?

**Comment by nhlpl** [comment]
Have you tried to add "bind_address": "0.0.0.0", to config.json?
https://github.com/NodeBB/NodeBB/issues/1841#issuecomment-49385222

On OpenShift cloud it can be done using this.
https://github.com/NodeBB/NodeBB/pull/2778

**Comment by AXtime** [comment]
@nhlpl, yes I did try the bind_address in config.json.  Same result.

It looks like loader.js line 233 (v0.6.1) doesn't call the .env() in the chain which I believe is needed to enable environment variables (not familiar with nconf).

`nconf.argv().file({`

should probably be

`nconf.argv().env().file({`

?

**Comment by AXtime** [comment]
I made the change (adding .env() to the nconf chain while also removing my other mod to getPorts().  The change fixed the original error, so this looks like the confirmed fixed.

**Comment by julianlam** [comment]
Thanks @AXtime -- normally our Heroku users run directly on `app.js`, since `loader.js` didn't work for whatever reason.

Does it work on `loader.js` now? If so, the documentation should be amended.

**Comment by AXtime** [comment]
No problem @julianlam.  Thanks for all your great work on this project!

Yes, I am running off of `loader.js` with the `.env()` applied to the `nconf.` chain.
