### ISSUE TITLE
Login page error display

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2947]
If I enter an invalid username/password combo or click "Login" without entering them, an error message is displayed as expected.

If I dismiss the error message by clicking on "x" and try the login again with an invalid username/password combo or empty fields the error message is not displayed again.

**Comment by julianlam** [comment]
Thanks. The client side code for this should match how we handle errors in all other parts of NodeBB. 

Namely, it shouldn't use an alert div, but rather a toaster pop-up or modal.
