### ISSUE TITLE
Recently Logged In IPs & 127.0.0.1

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2950]
Steps to reproduce:

1. Register at http://wikievolved.org/
v0.7.0-dev
2. Go to your profile and check Recently Logged In IPs
3. NodeBB shows only one IP - 127.0.0.1

Alternatively you can install NodeBB v0.7.0-dev or v0.6.x on OpenShift cloud to end up with the same issue.

**Comment by julianlam** [comment]
This is a configuration issue with nginx not passing the original IP through.
