### ISSUE TITLE
Users search

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2951]
Steps to reproduce:

1. Open https://community.nodebb.org/users/search
2. Type "!" to get https://community.nodebb.org/user/shubs1
3. Type "%" to get https://community.nodebb.org/user/-
4. Type "&" to get https://community.nodebb.org/user/nodecode

```
Signature
http://nodecode.de (previous username: nonenomail) <script>alert("okay");</script>
```

**Comment by julianlam** [comment]
The `%` search seemed okay (although technically, a user can no longer register with that username, we fixed that a couple years ago)

**Comment by julianlam** [comment]
Assigned @barisusakli

**Comment by barisusakli** [comment]
This happens because these users have those characters in their `fullname` field and the /users/search page does a search on username and fullname.
