### ISSUE TITLE
Composer & disabled Replying to

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2953]
Steps to reproduce:

1. Open Composer as Reply window
2. Move mouse cursor over topic title inside Composer "Replying to "Introducing the NodeBB 0.7.0 Persona preview"
3. For some reason it's disabled and placeholder says Enter your topic title here...

```
<input class="title form-control" type="text" tabindex="1" placeholder="Enter your topic title here..." disabled="">
```

**Comment by julianlam** [comment]
It's disabled as it is a reply, not a new topic.

**Comment by nhlpl** [comment]
So "Enter your topic title here..." is in wrong place.

**Comment by nhlpl** [comment]
Okay, I believe it's working as it should. But I'm more interested in mouse cursor changes from normal state into crossed circle.

**Comment by barisusakli** [comment]
Ideally instead of using a disabled input on a regular reply, it should just be a regular span with the 'replying to "{topic.title}" ' text so the cursor doesn't change.
