### ISSUE TITLE
Pagination, sort by and last read

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2954]
Steps to reproduce:

1. Make sure to enable pagination
2. Open a topic with last read information
https://community.nodebb.org/topic/4054/introducing-the-nodebb-0-7-0-persona-preview
3. Change Sort by settings
4. Use a link "Click here to return to your last position or close to discard"
5. NodeBB will freeze forever.

![sortfreeze](https://cloud.githubusercontent.com/assets/11160550/7033066/bcfec80e-dd77-11e4-8da6-c7d2c37cdd5f.jpg)

**Comment by julianlam** [comment]
This seems to have been resolved.
