### ISSUE TITLE
Default language didn't save [0.7.0 dev]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#2957]
When changing the default language (ACP > General > Language) and save the settings, it always reset to the first entry of the language choosing popup (ar) when returning to that ACP-Language-Page.

![bildschirmfoto 2015-04-08 um 11 13 33](https://cloud.githubusercontent.com/assets/11850083/7042189/53550ca6-dde0-11e4-97cb-3bba481b7441.png)

**Comment by julianlam** [comment]
``` html
<script type="text/javascript">
$('#language').val(translator.getLanguage());
</script>
```

:rage2: Logic mixed with views
