### ISSUE TITLE
Default setting for external links [0.7.0 dev]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#2958]
A default setting in the admin panel for "open external links in new tabs" is missing. This default setting is open in the same tab and it is just available for the user.

**Comment by frissdiegurke** [comment]
If sth. like this gets considered please do it within admin-feature to modify default user-settings.
Don't handle this single option at its own.

**Comment by nhlpl** [comment]
What we want here is enabling/disabling in Admin:
Profile > Settings > Browsing Settings > Open outgoing links in new tab?

Admin should be also able do decide about "Enable In-Topic Searching" (very important on big boards) , "Only allow chat messages from users I follow" (in real world spammers will kill your community) and maybe "Follow topics you create." (I have tested it on daily basis and it's not so bad as it sounds).
