### ISSUE TITLE
Editing post not possible

### ISSUE THREAD

**Issue by Armadill0** [NodeBB/NodeBB#2961]
When I try to edit this post: https://community.nodebb.org/topic/4128/does-nodebb-plugin-import-phpbb-work-with-3-1-x-phpbb/15

I get the following error: "Please enter a longer title. Titles should contain at least 3 characters."

This is reproducable with any other post I did on community.nodebb.org.

**Comment by nhlpl** [comment]
Confirmed here.
https://community.nodebb.org/topic/4203/default-setting-for-external-links-0-7-0-dev/8

**Comment by julianlam** [comment]
Hey guys -- confirmed latest code editing is okay, so this is most likely fixed since 0d515803e448ce097d574cd1112ffd4a00496603
