### ISSUE TITLE
Filesystem convention for plugins

### ISSUE THREAD

**Issue by ahwayakchih** [NodeBB/NodeBB#2962]
Hi,

I'm trying to make NodeBB work on OpenShift as good as locally and currently i'm trying to workout the best way for storing files.

OpenShift has special "data" directory, that is kept intact between updates to the application repository. Other files may be erased every time someone pushes changes to the repository.

So far, i made symlinks for "data/public-uploads" and "data/logs" directories. As long as files are uploaded and/or created in "public/uploads" or "logs" directories, they will be safe.
Now i'm wondering about plugins. Is there any convention that plugins should follow to create their own files on server? I mean, files that do not belong to the "public/uploads" directory (for whatever reason).

I'm sorry if it's already explained somewhere and i just did not look hard enough to find it.

**Comment by julianlam** [comment]
Hi @ahwayakchih -- thanks for your inquiry. There is no convention for plugins to save files to a specific place. However, it would be advisable to save them in `public/uploads` (possibly something like `public/uploads/plugins/[pluginname]`, but this is not something we'd enforce.

If plugins use the file upload module we ship in the core code, then those files will be saved in `public/uploads` as well.

**Comment by ahwayakchih** [comment]
Thanks!
