### ISSUE TITLE
Installing on Heroku guide could be helpful to include mention of plugins

### ISSUE THREAD

**Issue by AXtime** [NodeBB/NodeBB#2964]
On the guide of how to install on Heroku, it would be helpful to include something about plugins.  To my knowledge you must update the package.json and push.   You can't use the Admin panel UI to add them.    I'm assuming this is due to the fact that Heroku dynos don't have persistent storage, so a restart clears any plugin you may add.

If this is indeed the case, it would be worth mentioning this on the Heroku install guide.

**Comment by psychobunny** [comment]
Moved this to the documentation issue tracker https://github.com/NodeBB/nodebb-english/issues/44
