### ISSUE TITLE
Users page & Delete Account

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2967]
Steps to reproduce:

1. https://community.nodebb.org/users
2. Watch a user who will delete his/her account
3. Deleted and no longer exist
4. Online/Offline Indicator shows he/she is still online
5. Hit F5 and it will be OK

**Comment by psychobunny** [comment]
Hey @nhlpl, stuff like this is really low priority for the platform. The actual number of times someone will run into this on a live environment is very low and probably not inconvenient for them, meanwhile adding socket listeners will add unnecessary bloat in code and potentially scaling wise

Thanks for reporting though, you're on a roll :P

**Comment by psychobunny** [comment]
nvm, you know what, I think I can do this without any additional overhead, one sec.
