### ISSUE TITLE
Change password and alert-success

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2973]
Steps to reproduce:

1. Profile > Edit
2. Type wrong phrase in "Current Password"
3. Type new phrase in "Password" & "Confirm Password"
4. Hit "Change Password"

Please remove alert-success from "Password" & "Confirm Password" before next try.

**Comment by psychobunny** [comment]
This is actually more serious.

Type wrong password in "current password"
Type mismatch passwords in "password" and "confirm password"

Password gets updated anyways.
