### ISSUE TITLE
Pagination, allowed values

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2975]
Steps to reproduce:

1. Profile > Settings > Pagination
2. Topics per Page can be a number from 1 to 20
3. Posts per Page can be a number from 1 to 20
4. Admin > Posts per Page = 60 & Topics per Page = 60
5. Profile > Settings > Pagination  
Posts per Page max = 20 & Topics per Page max = 20

Changes in Admin should impact allowed user choice in profile.

**Comment by psychobunny** [comment]
IMO I don't think user should even be allowed to modify pagination settings, not sure if there really is a use case there. Most definitely should not be allowed to exceed the admin setting

**Comment by nhlpl** [comment]
I have checked settings for our forums.

Number of topics per forum page = 30
Number of posts per topic page = 20

Okay, so let's use a global limits of 30 and 20 in NodeBB. I imagine it should allow a user to use a range of 1-30 and 1-20 and not 1-20 and 1-20 as it is right now.
