### ISSUE TITLE
Q&A plugin breaks replying

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2976]
[Solved] Cannot create new topic
https://community.nodebb.org/topic/4212/cannot-create-new-topic

Hit Reply or Quote
Replying to "

Please fix this as I want to add my 2 cents. Thanks!

**Comment by psychobunny** [comment]
I managed to reply (now deleted). Although that `Replying to ''` is a bug. Regardless, it's unrelated to the Q&A plugin (afaik) because it doesn't actually have anything to do with the composer

**Comment by nhlpl** [comment]
You deleted reply can be seen on forum index "testing a reply".

**Comment by psychobunny** [comment]
That's because we added you to the moderator group :) Just tested on a regular user, works as expected

**Comment by psychobunny** [comment]
> Regardless, it's unrelated to the Q&A plugin (afaik) because it doesn't actually have anything to do with the composer

Turns out you're right, will look into it :+1:

**Comment by nhlpl** [comment]
A picture is worth a thousand words.

![qaspan](https://cloud.githubusercontent.com/assets/11160550/7084830/6b328afa-df71-11e4-9ee4-f64ede0927e5.jpg)

**Comment by nhlpl** [comment]
Replying now works but something wrong here.

![spanclass](https://cloud.githubusercontent.com/assets/11160550/7118889/59c6c360-e202-11e4-8b7c-287e8d5db476.jpg)

**Comment by psychobunny** [comment]
Turns out I fixed the bug but never updated the plugin on our community. Replying should work here now: https://community.nodebb.org/topic/4212/cannot-create-new-topic
