### ISSUE TITLE
Need dedicated link to advanced search page

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#2978]
Possibly something like the ACP dropdown?

**Comment by julianlam** [comment]
Hey, I thought we had this settable in the "Navigation" part of the ACP already :smile: 

![selection_043](https://cloud.githubusercontent.com/assets/923011/7077635/6f56a3b4-dee0-11e4-83d1-992b9c0093c5.png)

:trollface:

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/80
