### ISSUE TITLE
Minimize reply window and whitespace

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2981]
I have been testing your community forums against this bug.
https://github.com/NodeBB/NodeBB/issues/2976

and found one more

Steps to reproduce:
1. https://community.nodebb.org/category/4/testing-ground
2. Reply to a random topic and minimize composer
3. Go to forum index and scroll down to the bottom of the page  
A LOT of whitespace

![qatest](https://cloud.githubusercontent.com/assets/11160550/7084516/4df5f826-df6e-11e4-9a68-60a17dbdf6f8.jpg)

**Comment by julianlam** [comment]
Might be advantageous to remove the whitespace hack altogether, as the
composer can be resized...
