### ISSUE TITLE
After editing the topic

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#2982]
After editing the topic indicated slug wrong if the title was changed. If update the page will be an error due to a non-existent page.

**Comment by julianlam** [comment]
This is intentional, for reasons we have explained in the past. (on phone now, cannot comment at length)

**Comment by atomoc** [comment]
It will not work correct?

**Comment by julianlam** [comment]
The slug will change. Safest way is to refer to the topic without the slug, and it will be auto-added.

**Comment by barisusakli** [comment]
We could fix this by redirecting to the correct slug if the user edits the title. I will take a look.

**Comment by atomoc** [comment]
Thanks!
