### ISSUE TITLE
Chats alert bar stops responding

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2983]
Steps to reproduce:

1. Start new topics and minimize them (composer)
2. Start replying in many places and minimize (composer)
3. Start some chats and minimize their windows

![spambar](https://cloud.githubusercontent.com/assets/11160550/7085071/344db904-df73-11e4-84c0-75c45fef4abf.jpg)

An alert bar will stop responding.

**Comment by julianlam** [comment]
This issue requires a stricter set of reproduction steps:

* Please expand on "stop responding", does it no longer respond to clicks? Do new chats no longer cause the button to pulse?
* Is it a specific action that causes the alert bar to stop responding?
* If it is related to the number of chats/composers open, then what is the number?
* Can you reproduce it effectively 100% of the time, and can you please reduce the reproduction steps to a few as possible? (e.g. can you reproduce it with just "New Topic" composers? just chats?)
