### ISSUE TITLE
Not purge multiple category

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#2985]
In admin page.

**Comment by julianlam** [comment]
?

**Comment by atomoc** [comment]
Only one by one.

**Comment by atomoc** [comment]
In principle, it is not particularly important, I just wanted to emphasize this point.

**Comment by julianlam** [comment]
It seeems very dangerous to be able to purge multiple categories at once, even if you have the best intentions.

**Comment by nhlpl** [comment]
It can be useful on big boards. I prefer to have "select all" and "with selected... do sth" over sorting using drag-n-drop and similar modern web ideas.

**Comment by julianlam** [comment]
Haven't really seen much interest for this feature, so it'll be benched for now.
