### ISSUE TITLE
Hook: message saved action

### ISSUE THREAD

**Issue by lnxseed** [NodeBB/NodeBB#2988]
I think "action:messaging.save" will be useful!
thanks

**Comment by psychobunny** [comment]
This already exists as `filter:messaging.save`  - https://github.com/NodeBB/NodeBB/wiki/Hooks#messaging

Let me know if this wasn't what your plugin requires

**Comment by lnxseed** [comment]
yes, but filter may be used to obtain content before message saved, and after saved , a action will be usedful
