### ISSUE TITLE
Register and form validation

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2989]
Issues on Register form:

1. alert-success needs a refresh (see #2973)
2. a@@mail.com, b@mail..com, c@ are recognized as valid
3. alreadyused+phrase@mail.com should be refused as +phrase is used to stop spam only and is not really a new mail account

and

Profile > Edit > Email > Save Changes
gano+g1@@@@@@@landmail.....co

**Comment by julianlam** [comment]
Re: #2, this will not change. The only check we do here is ensuring that the email contains @. If you put in an invalid email, then it is your own fault when you cannot receive password reset requests, etc.

**Comment by nhlpl** [comment]
I don't know how it works on Mandrill but on local server it will be a problem for sysadmin. A bunch of errors on daily basis. And it will end up with a need of replacing wrong email address for a user.

**Comment by dwendt** [comment]
3 is incorrect, + is a valid character in e-mails. How gmail handles it is unrelated to nodebb.

**Comment by julianlam** [comment]
Agreed. I use + in my registrations all the time and there are no problems. If an emailer errors out due to that address, it's a problem with the emailer!

**Comment by nhlpl** [comment]
A)
We're not talking here about random new email address but comparing it to the one already registered in the datastore/database.

alreadyused@mail.com
Error: Email taken

alreadyused+nospam@mail.com
You can be our new forum user

B)
I have commented (2) on the list and not (3).

The email address "c@" is not recognized. Please fix it and try again.
The email address "b@mail..com" is not recognized. Please fix it and try again.
The address "a@@mail.com" in the "To" field was not recognized. Please make sure that all addresses are properly formed.

**Comment by dwendt** [comment]
Even in the context of checking for existing emails within the system that's incorrect.

email@provider.com
email+@provider.com
email++@provider.com
email+++@provider.com

These are different emails and shouldn't be considered the same.
