### ISSUE TITLE
Mention a username with spaces

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2992]
https://community.nodebb.org/topic/4227/mention-a-username-with-spaces

https://community.nodebb.org/register

Big Joe Junior
Others can mention you with @Big Joe Junior.

Big.Joe.Junior
Others can mention you with @Big.Joe.Junior.

Please change it to:
Others can mention you with @Big-Joe-Junior.

**Comment by julianlam** [comment]
Hehe, this was fun. I wrote the client-side event for this page before user slugs were even a part of NodeBB. Back then you could name yourself anything :rage2:
