### ISSUE TITLE
Two browser tabs and Unread (1)

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2993]
Steps to reproduce:

1. Leave first tab opened. In my case it was:
https://community.nodebb.org/user/trevor/posts
2. In second tab browse NodeBB as usual
3. I don't remember which tab to close but both them have had Unread (1)
4. Closed one of them and in second one clicked on Unread (1)
5. Unread page was blank as you can see on a screenshot
6. Hitting F5 removed Unread (1) and changed it to Unread (0) so it works fine after a refresh.

![unreadblank](https://cloud.githubusercontent.com/assets/11160550/7102924/4414365e-e092-11e4-9ee5-b95fd0bdfcbd.jpg)

**Comment by julianlam** [comment]
This seems to have been resolved.
