### ISSUE TITLE
[Composer] Reply and special characters

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2994]
When replying here:
https://community.nodebb.org/topic/4228/3-2-1-engage

Replying to "3

![321reply](https://cloud.githubusercontent.com/assets/11160550/7102990/b8a41d7a-e094-11e4-8883-e6b2db7466c6.jpg)

**Comment by barisusakli** [comment]
Happens because of https://github.com/NodeBB/NodeBB/issues/1951

The template has this when title is `3,2,1 ...`

`<span class="title form-control">[[topic:composer.replying_to, "3,2,1 ..."]]</span>`

**Comment by psychobunny** [comment]
Kind of the same issue but not really. Translator should take quoted variables as one argument

**Comment by psychobunny** [comment]
I'll try and get those both fixed before 0.7
