### ISSUE TITLE
[Composer] Resize by only using New topic and Discard

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2997]
1. I'm pretty sure it works for my main account and not so sure for new accounts
2. Composer visible on 3rd screenie can be resized to such position by only browsing categories, clicking new topic/discard and on b/w arrow to move composer window to the top
3. Not a browser issue as I thought about it earlier

![compwin1](https://cloud.githubusercontent.com/assets/11160550/7104823/60859874-e0fa-11e4-8a46-a44b091b64c3.jpg)
![compwin2](https://cloud.githubusercontent.com/assets/11160550/7104824/608f3a96-e0fa-11e4-9fcb-6cf890002f0f.jpg)
![compwin3](https://cloud.githubusercontent.com/assets/11160550/7104825/6093e942-e0fa-11e4-96b8-f568b87672e0.jpg)

**Comment by barisusakli** [comment]
Not sure what the issue here is. Can you clarify the problem?

**Comment by nhlpl** [comment]
Okay, will test it again. On all of my fullscreen screenshots Composer windows was on the wrong place. On the top near to URL browser bar without an option to minimize. Minimize arrow did nothing.

Only re-login and clear cache helped.

**Comment by psychobunny** [comment]
Just to help you out in repro - re-logging in shouldn't make a diff, but clearing cache potentially is, because we save some of the composer state in localStorage

**Comment by nhlpl** [comment]
Chrome 41.0.2272.118 m
New user

Bug still exists

![stillhere](https://cloud.githubusercontent.com/assets/11160550/7124482/798a19dc-e229-11e4-86f2-5eb6e3fd75eb.jpg)

**Comment by nhlpl** [comment]
Confirmed here: https://community.nodebb.org/topic/4252/bootswatch-skins

**Comment by nhlpl** [comment]
Fedora 21, Firefox 37.0.1
external LCD, 1920x1080px

```
 class="row write-preview-container" style="height: 328.692px;"
```
```
<div class="row write-preview-container" style="height: 339px;"
```
```
<div class="row write-preview-container" style="height: 350px;"
```
