### ISSUE TITLE
Chats vs Private Messages

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#2998]
I know you're working hard to bring your Chat to the next level and it was already discussed here on GitHub. 

Issues:

1)
Please add a feature to bump a user with a notification or sound. For example I helped a new user to install NodeBB and he simply closed chat window without a notice. And I really don't know if he read all the text or not. I have sent him a hint to remove a Redis secret from a post and it was ignored.

So he should see a warning. Do you really want to close ongoing chat session? Yes/No. If yes I should receive a message similar to "user1 is typing something" that chat session was closed.

2)
Add search to your Chats similar to in:topic. We have more than 100.000 private messages and you don't want to talk to angry users who can't find important data.

3)
Add an option to use multiline Composer vs one line as it is right now.

You'll not believe but people who professionally work with text (books, translations) in many cases do not use SMS (Short Message Service) or Instant Messaging. As a moderator such person will send you 300 lines of text and not just 3 messages in real-time.

Sorry to say but it's like forcing real-time strategy lovers to love turn-based games and vice versa.

4)
Please bring an option to choose a classic sorting of archived messages in place of Recent, 7 Days, 30 Days, 3 Months. You really don't want people who write a lot to use search every single time.

Maybe an option to filter what you sent and what you received?

5)
Report abuse in Chat.

**Comment by nhlpl** [comment]
I have something to add.

Spirit (Python) uses Private Topics. The only difference between topic and private topic is who can see them. So two users can post earch other in their private topics. Those private topics can be accessed from profile dropdown menu.

vBulletin has a feature to create a category where topics can only be seen by topic starter and moderators. Forum owner can use it for newbie support, abuse reporting and similar stuff.

**Comment by julianlam** [comment]
> vBulletin has a feature to create a category where topics can only be seen by topic starter and moderators. Forum owner can use it for newbie support, abuse reporting and similar stuff.

FYI, done via `support-forum` plugin: https://github.com/julianlam/nodebb-plugin-support-forum

**Comment by julianlam** [comment]
> Private Topics

May work for private messaging, although adding this logic would complicate the permission system considerably, and also keep in mind we don't have "per-topic" privileges, so that would be a whole tonne of extra work just for refactoring the chat subsystem :smile:

**Comment by nhlpl** [comment]
Less groundbreaking ideas:

a)
Please add an option for Chats to hide "Contacts" and "Recent Chats". Similar to "Hide Preview" in Composer.

b)
Add Composer to Chats page. As I already said many users will prefer to use full editor instead of 1-line real-time input. They may want to find and replace typos in long texts.

c)
Add custom labels or tags for archived chat sessions.

User1: Pre-Sales, Feedback, Support
User2: Work, Home
User3: Starred, Important
User4: Code samples, Useful URLs, Tips/Hints
User5: Gaming, Hardware, Off-topic
User6: 2015-04, 2015-03, 2015-02, 2015-01

**Comment by psychobunny** [comment]
Can we please repost this idea (if you're still interested) on the community? These are all valid points but the visibility over here is mostly towards core devs. Best to have the community have it's say then we post some concrete doable issues on this tracker. Thanks!
