### ISSUE TITLE
Chat and text after expanding

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3000]
Steps to reproduce:

1. Start a chat in a pop-up
2. Some text [Shift+Enter] More text [Shift+Enter] Even more text [Shift+Enter]
3. I feel a need of more space so hitting Expand/Maximize icon
4. Text field will be empty in full screen mode (refresh in the middle)

**Comment by julianlam** [comment]
Hm, a warning during expanding may be a good idea, as the modal and chat page are two separate pages...
