### ISSUE TITLE
Minor issues for validating user

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3001]
1)
Non-confirmed user can follow other users

2)
Non-confirmed user can join public group

3)
Non-confirmed user can use search

4)
Confirmed user can send chat message to non-confirmed user

5)
Non-confirmed user can't reply to chat message but can click on send many times

main account
testuser is typing ..

testuser account
Error
You have sent too many messages, please wait awhile.

**Comment by barisusakli** [comment]
#1 can fix the issue in #3010

**Comment by nhlpl** [comment]
No longer an issue so closing it. Thanks you for your time and advices..
