### ISSUE TITLE
Search & Advanced Search

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3004]
It took me a minute to realize that I have to remove nginx from simple search to use advanced search. I looked for a seach button below advanced search.

Unintuitive and can be improved.

![doublesearch](https://cloud.githubusercontent.com/assets/11160550/7106762/638b0bbe-e14d-11e4-9002-1dc7da09edd4.jpg)

**Comment by barisusakli** [comment]
The By field in the advanced search is to specify the user, you don't have to empty the search field.

search = "nginx", by = "nodebb" will search for `nginx` in content that were made by user `nodebb`

We can change the labels to better message that, Search -> Search term, By - > By User

**Comment by nhlpl** [comment]
Thanks for your explanation.

Would be much better to replace it with "By User". I've checked our own forums and we have "Filter by Member Name (optional)" and it was always easy to understand.
