### ISSUE TITLE
Picture From URL and large files

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3005]
Please add restrictions or image optimization to:
Profile > Edit > Change Picture > Upload New Picture From URL

A user can upload image of any size and dimensions. Nothing wrong about that. The bad thing here is such big file will be used as an avatar.

Tested with 1280x960px and 650 KB.

**Comment by psychobunny** [comment]
This setting doesn't work?

![](http://i.imgur.com/qnrtFum.png)

Admin -> Settings -> User

**Comment by psychobunny** [comment]
Oh, from URL. Gotcha
