### ISSUE TITLE
Watch/Ignore & i18n

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3009]
Profile > Settings > Language > PL, DE, FR > Save Changes
Category view > Watch/Ignore

![plignore](https://cloud.githubusercontent.com/assets/11160550/7112598/81a0b8d2-e1cb-11e4-8126-589889605ce2.jpg)
![plignore2](https://cloud.githubusercontent.com/assets/11160550/7112599/81c70820-e1cb-11e4-91b8-7ba330bd7383.jpg)
![plignore3](https://cloud.githubusercontent.com/assets/11160550/7112600/81da9e1c-e1cb-11e4-8a06-31ce80ecf619.jpg)

**Comment by jarey** [comment]
This is caused because there isn't a translation available in that languages. A translation need to be made in Transifex, and then updated in the json files in order to show the messages properly. Community work needed.

**Comment by nhlpl** [comment]
NodeBB should show a message in English or in any other choosen language. Users in PL in most cases will understand default messages.

**Comment by julianlam** [comment]
The fallback is English, in this case, possibly the translation strings haven't been pushed to transifex yet, so there is no fallback.

**Comment by nhlpl** [comment]
Not a bug anymore I think.
https://github.com/NodeBB/NodeBB/commit/5db4714ba850bfc829034123cccac8253002684b

**Comment by psychobunny** [comment]
The template and core changes were made at the same commit btw. But yeah, hasn't been pushed to transifex yet = no fallback
