### ISSUE TITLE
Notifications and deleted users

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3010]
https://community.nodebb.org/notifications

![followjoe1](https://cloud.githubusercontent.com/assets/11160550/7112771/61fc3400-e1cd-11e4-9a75-e84bb3d4eafb.jpg)

Can be used to spam your forums.

**Comment by barisusakli** [comment]
Each follow notification uses the same unique id so you only get 1 notification from the same user following you, even if they follow/unfollow you multiple times.

**Comment by psychobunny** [comment]
yeah I just tested this out with @barisusakli , followed and unfollowed him about a bazillion times, only ended up with one notif on his notif page

**Comment by nhlpl** [comment]
But it will be still there after account being deleted. For example shop.com in username who followed all your forum members. We have had such spammers.

**Comment by barisusakli** [comment]
It might be better to prevent users from following others before they are verified and/or have certain rep then.

**Comment by nhlpl** [comment]
Okay, no problem. Will do.
