### ISSUE TITLE
XSS executed on composer

### ISSUE THREAD

**Issue by FezVrasta** [NodeBB/NodeBB#3011]
https://community.nodebb.org/topic/4243/script-alert-injected-script

**Comment by julianlam** [comment]
Please follow proper guidelines for reporting security issues in the future.

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/blob/master/CONTRIBUTING.md

**Comment by FezVrasta** [comment]
Ah ops! Sorry

**Comment by psychobunny** [comment]
Thanks for reporting. This vulnerability was only present for 6 days on the master branch and we do instruct end-users to use only the latest stable branch for production, so nothing to worry.

https://github.com/NodeBB/nodebb-theme-vanilla/commit/9b565749d535de3053ce9cd6efd75df2941f83ed
