### ISSUE TITLE
Localisation incomplete - user settings [0.7.0 dev]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#3014]
profile > settings > groups
A popup is not localized

![bildschirmfoto 2015-04-13 um 17 04 59](https://cloud.githubusercontent.com/assets/11850083/7118844/0708f756-e202-11e4-8c27-6be8d27c0f66.png)

**Comment by psychobunny** [comment]
Thanks for reporting. Same issue as https://github.com/NodeBB/NodeBB/issues/3009

Will be resolved when we push the latest strings to transifex, soon

**Comment by NoodleBB** [comment]
Great. :)
