### ISSUE TITLE
Edit menu behind following post [0.7.0 dev]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#3015]
The edit menu of an deleted post is unreachable, because it appears behind the following items.

![bildschirmfoto 2015-04-13 um 18 22 13](https://cloud.githubusercontent.com/assets/11850083/7120091/d5b49f44-e20a-11e4-92b9-2a088d89698b.png)

![bildschirmfoto 2015-04-13 um 18 28 44](https://cloud.githubusercontent.com/assets/11850083/7120109/f795656c-e20a-11e4-8372-68435f8376eb.png)

**Comment by psychobunny** [comment]
In future please report theme (styling) specific issues to the repo of the actual theme affected. That said, thank you for reporting :)
