### ISSUE TITLE
Change of Site Title in Settings General changes site title of all NodeBB installations on server

### ISSUE THREAD

**Issue by FoundationAwesome** [NodeBB/NodeBB#3018]
I have got 3 NodeBB installation on my server. Up to now everything worked properly. But just some minutes ago I changed the 'Site Title" in Settings General to a new title and it effected all installations. And again and again the same problem no matter which I changed.

Here are two sites: community.coinawesome.com
and tips.coinawesome.com

NodeBB v0.6.1/0

All config.json have a different DB setting (redis number).

I wanted to launch the third site today... so it's pretty urgent.

Please help.

**Comment by FoundationAwesome** [comment]
It does this even when I am logged out of one of them.
And inside /admin/settings/general the correct settings are kept, but in the header of the forum at / it gets changed everywhere.

Any idea how to fix or workarround this?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/1cc80cbc842a2f6bf48fc987c27ad121136bcdd5
