### ISSUE TITLE
Menu on mobile devices do not work

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3019]
Apparently this is due to not fully downloadable content.
![screenshot_2015-04-14-09-44-39](https://cloud.githubusercontent.com/assets/465108/7131804/f349e3e4-e28b-11e4-9666-7f07e455203d.png)
Loading never stops.

**Comment by julianlam** [comment]
Hm. Is this on every page load? Does it work better on other pages (topic page, etc)?

**Comment by atomoc** [comment]
I checked on android 4.0 and this loading was on all pages. In android 4.4 in the chrome is no problem. In iphone 4 and 5 resources fully loaded, but the menu does not appear. Displayed only indication clicking on icon, it becomes gray.

**Comment by psychobunny** [comment]
This is actually a known issue with socket.io and older Android browsers, see: https://github.com/NodeBB/NodeBB/issues/1323

Seems like it got reverted a long time later. Any reason not to re-add that line back @barisusakli? 

Right now if you wait about 20 seconds or so (until it drops to xhr-polling) then menu, ajaxify, etc will start working again

**Comment by barisusakli** [comment]
We already use

`config.socketioTransports = nconf.get('socket.io:transports') || ['polling', 'websocket'];`

So it starts with polling then tries to update to websocket on socket.io1.0

**Comment by psychobunny** [comment]
Oh that's cool. Well then, time to find my old android phone and figure out what's breaking on 4.0 stock -_-

**Comment by atomoc** [comment]
> Well then, time to find my old android phone and figure out what's breaking on 4.0 stock -_-

:)  I think it would be important to do for iphone.

**Comment by deltreey** [comment]
I can confirm this is the case.  You don't even need a mobile device, just shrink the window down to where the navbar compacts and it will stop working.  Example: http://forums.adventureatyourowrnisk.com

**Comment by psychobunny** [comment]
Lots of work on persona since then (I've rewritten the entire menu system since this issue was created), please report on the persona repo if you are still running into any issues:)
