### ISSUE TITLE
Spam protection needs improvement

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3020]
4 bots in short time created 4 topics with similar content.

![autospam1](https://cloud.githubusercontent.com/assets/11160550/7132747/789ac982-e28c-11e4-9e5d-19c761df52a1.jpg)
![autospam2](https://cloud.githubusercontent.com/assets/11160550/7132749/7a1cf4ba-e28c-11e4-8a67-bd4706fc4820.jpg)

**Comment by julianlam** [comment]
We use third-party spam tools for this, so there's nothing we can do directly, and occasionally, *some spam does get through*. We'll keep an eye on it.
