### ISSUE TITLE
Advanced Search found 426 results and shows 0

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3022]
https://community.nodebb.org/search/nodebb?in=posts&categories[]=3&searchChildren=true&replies=100&repliesFilter=atleast&sortBy=timestamp&sortDirection=desc&showAs=topics

returns

![426a](https://cloud.githubusercontent.com/assets/11160550/7134814/db4596c0-e2a0-11e4-92ff-6e0c38c5a04d.jpg)
![426b](https://cloud.githubusercontent.com/assets/11160550/7134815/db4672ca-e2a0-11e4-9d71-571a5d977dbe.jpg)

**Comment by barisusakli** [comment]
@julianlam I tracked this down to a topic in category `NodeBB Blog` that is deleted but has 500 posts.

solr seems to be returning those pids even those the topic is deleted. Tried restoring then deleting the topic again but didn't change anything.

**Comment by julianlam** [comment]
Thanks, will take a look. Does flushing and reindexing make them go away?

**Comment by barisusakli** [comment]
Hmm didn't try that on try since It would take a while.

**Comment by julianlam** [comment]
v2.0.2 of Solr contains fixes for this. Thanks @nhlpl!
