### ISSUE TITLE
Page footer and nodebb.com

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3023]
Please change link in "Copyright © 2015 NodeBB | Contributors".

https://nodebb.org/
https://www.nodebb.com/

![footercom](https://cloud.githubusercontent.com/assets/11160550/7135113/d8ddcc60-e2a3-11e4-9195-4d57b74b7730.jpg)

**Comment by julianlam** [comment]
Not really a bug, but fixed on our production instance.
