### ISSUE TITLE
Search and special characters

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3024]
https://community.nodebb.org/search/**?options=on

!!!
@@@
###
$$$
%%%
^^^
&&&
***
(((
)))

returns
500 result(s) matching "**", (0.09 seconds)

![doublestar](https://cloud.githubusercontent.com/assets/11160550/7135305/9d724424-e2a5-11e4-8739-06a552806131.jpg)

**Comment by nhlpl** [comment]
https://community.nodebb.org/search/www.apple.com?in=posts&sortBy=timestamp&sortDirection=desc&showAs=posts

www.apple.com
works fine

no results when special characters used
www.apple.com/
http://www.apple.com

**Comment by barisusakli** [comment]
Seems to work now
