### ISSUE TITLE
Search +/- phrase

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3025]
Try to search it one by one for many times.
https://community.nodebb.org/search/toronto%20expensive?in=titlesposts

toronto expensive
3 result(s) matching "toronto expensive", (0.01 seconds)

toronto +expensive
28 result(s) matching "toronto +expensive", (0.02 seconds)

toronto -expensive
13 result(s) matching "toronto -expensive", (0.02 seconds)

**Comment by julianlam** [comment]
This would be better filed against Solr and/or dbsearch. Thanks!
