### ISSUE TITLE
Pagination and jump to page

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3027]
1) 
Double-arrow up/down and box with "123" can be used to jump to another page. Go to next post single arrow takes you only to the end of the current page.

Those who read topics from end to start (from right to left) are forced to scroll down to change page number.

2)
Please add an option to jump to page number on the bottom of Topic View. I mean when a topic is long (500 pages) you may want to select 345.

![pagnext](https://cloud.githubusercontent.com/assets/11160550/7145575/9b80a7da-e2ed-11e4-95a2-4690f7b8ccae.jpg)

**Comment by barisusakli** [comment]
![image](https://cloud.githubusercontent.com/assets/2583394/7278041/33eeff64-e8e1-11e4-9f8c-d21d78346d12.png)
