### ISSUE TITLE
Fresh install, forbidden login

### ISSUE THREAD

**Issue by thebotanyofsouls** [NodeBB/NodeBB#3029]
After freezing my previous new install at http://192.241.210.65:4567 I deleted, and reinstalled nodebb several times - the final time deleting and reinstalling redis as well.

When I do the final node app --setup command, it does NOT prompt me to make a new user and uses the database I attempted to delete - the posts I made before the site went kaput are still there, and when I attempt to login (as admin) I get a "forbidden" error. Help?

**Comment by thebotanyofsouls** [comment]
Oh - I can create a new user and login, I just can't login to my administrator user (the account is now locked after the last attempt to login), if that helps at all.

**Comment by julianlam** [comment]
Hi @thebotanyofsouls -- when you deleted Redis, it doesn't take the database file with it, so when you re-installed Redis, it just re-used the old Redis database file :smile: 

To clear the database, log into the command-line interface (`redis-cli`), and run the `flushdb` command.

**Comment by thebotanyofsouls** [comment]
Did not resolve the forbidden error upon login. Fresh install, flushed redis, this is the error the console spits out when I attempt to login using the admin user (never logged in before)
14/4 21:03 [9201] - error: TypeError: undefined is not a function
    at /home/thebotanyofsouls/mynodebb/src/database/redis/main.js:121:4
    at try_callback (/home/thebotanyofsouls/mynodebb/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/home/thebotanyofsouls/mynodebb/node_modules/redis/index.js:661:13)
    at ReplyParser.<anonymous> (/home/thebotanyofsouls/mynodebb/node_modules/redis/index.js:309:14)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_reply (/home/thebotanyofsouls/mynodebb/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/home/thebotanyofsouls/mynodebb/node_modules/redis/lib/parser/javascript.js:189:22)
    at RedisClient.on_data (/home/thebotanyofsouls/mynodebb/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/home/thebotanyofsouls/mynodebb/node_modules/redis/index.js:91:14)
    at Socket.emit (events.js:107:17)

**Comment by julianlam** [comment]
Ah, in *that* case, you'll want to install a newer version of Redis (>= v2.4)

**Comment by thebotanyofsouls** [comment]
Wow, I feel kinda dumb as I type this. An outdated database would do that ;-p How do I install the latest version of redis? I downloaded version 3.0, but I'm not sure how to push the tar.gz file to the server (using digitalocean as the host for the application, if that helps)

**Comment by julianlam** [comment]
That depends on what OS you've installed on your digitalocean box.

**Comment by julianlam** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-redis

This may help for Ubuntu, but since Redis on Ubuntu is already > 2.4, I doubt this is the OS you've got...

**Comment by thebotanyofsouls** [comment]
Updated redis, still forbidden from logging in.

**Comment by thebotanyofsouls** [comment]
And yes, I'm using ubuntu 14.04 x64 as the distro. The guide here
http://burnaftercompiling.com/nodebb/setting-up-a-nodebb-forum-for-dummies/
suggests a 32bit server, but I wanted it scaleable in case I wanted to upgrade the amount of CPU I was using at a later date. Sorry about the slow reply.

**Comment by julianlam** [comment]
Are you sure you've updated Redis? (May seem a silly question, but sometimes you never know...) Let me know the output of `redis-cli -v`

**Comment by julianlam** [comment]
Hm, with 14.04, you can use apt. `sudo apt-get install redis-server` should install a new enough version.

**Comment by thebotanyofsouls** [comment]
Output says the version is 2.8.9. 

Before the last post I flushed the database after I updated redis, and ran node app --setup again to make sure that the user was created with the proper credentials, and still I get the forbidden error (just typing that makes me giggle in spite of all my frustration).

**Comment by thebotanyofsouls** [comment]
Oh, and new user registration is also forbidden if that helps at all.

**Comment by julianlam** [comment]
Can you paste the entire stack trace, and also `npm ls nodebb-theme-vanilla nodebb-theme-lavender`?

**Comment by thebotanyofsouls** [comment]
The terminal running nodebb
14/4 21:51 [16630] - error: /login
 invalid csrf token
14/4 21:52 [16630] - error: /login
 invalid csrf token
14/4 22:08 [16630] - error: /login
 invalid csrf token
14/4 22:08 [16630] - error: /register
 invalid csrf token

For the themes
├── nodebb-theme-lavender@1.0.36 
└── nodebb-theme-vanilla@1.0.107

**Comment by julianlam** [comment]
v0.6.x of NodeBB?

**Comment by thebotanyofsouls** [comment]
version 0.7.0-dev is what the git command pulled for me. I've tried installing the 0.6.x version, and it had errors during the install.

**Comment by Revii** [comment]
I think, that "bug" was fixed in #3033.

**Comment by barisusakli** [comment]
Yes, let us know if its not.
