### ISSUE TITLE
Post duplicated over 8,000 times

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#3031]
I'm not sure what caused this to happen. A couple hours ago, a post was duplicated over 8,000 times. The duplicated posts were assigned their own unique PID. I deleted the posts form the database. Though by the time I noticed it was too late to stop e-mail notifications from being sent out to all subscribers of the topic for each one of the duplicated posts. I am hoping that Mailgun won't hold us to paying the bill because our project can't afford it :worried:  Anyway, that's not why I'm posting. I want to provide any information that could be helpful for you to identify the issue. Also I hope you will put some safe guards in place to prevent this type of thing from occurring (especially the e-mail notifications)

Advanced>>Logs: http://paste.ee/p/c7Ylq

Let me know if there's anything else I can provide that would be useful. Thanks.

Edit: BTW, I pulled the latest from master about an hour before the issue occurred.

**Comment by jarey** [comment]
You should not work with master for production usage. Be aware that it is in active development/testing and unwanted results may occur.

I think nodebb developers would be thankfull if you provide the commit hash you were on when the issue occurred.

**Comment by lots0logs** [comment]
Yes, I'm aware of that. Like I said in my message, the purpose of my post is to help prevent this kind of thing from happening to others. I'm not upset or blaming anyone for the issue. The commit hash is the HEAD of master at present (27049a218082a169755f37cb32674aadb4f25ebd)

**Comment by nhlpl** [comment]
Does it happen on http://forum.antergos.com?

**Comment by barisusakli** [comment]
The crash in your logs is fixed on master now.

I remember this happening in the past to a few people @cnvo being one. Here is my educated guess on why this happened. 

Making a post was causing a crash due to the above bug. The crash causes socket.io to disconnect, when the forum restarts itself socket.io tries to send the same message again, in this case `topics.reply` which causes it to crash again. The crash was happenign after the reply was done so you get X replies until the browser is tab is closed.

If this was a regular user they should have been caught by the 10 second post delay, although if they are an admin they can just post indefinitely. Let me know if the above commit fixes the issue.

**Comment by lots0logs** [comment]
Okay, thanks for the quick response! I have to work today so I can't test it now. I will do it ASAP. One thing I do want to mention is that after the first occurrence of the issue I raised the 10 second post delay to 30 seconds. Though it did not prevent the two occurrences that followed. From your description of the issue, it doesn't seem like the post delay would/should be effective. If we a restarting from a crash, doesn't that result in the post delay being reset? Also, assuming this does indeed fix this issue, is there anything you guys can do to prevent thousands of posts by one user (just in case a new bug was to show up causing a similar result in the future)

**Comment by barisusakli** [comment]
When the user posts we save the timestamp to the db so we can check if they can post again in X seconds so it shouldn't be affected by the forum restart. Although admins don't go through that check. Was this a regular user?

I agree we shouldn't let this happen even on server crashes. Need to figure out the real cause first though I am not 100% sure if its socket.io replaying all the same emits after reconnect.

**Comment by lots0logs** [comment]
The first time it happened it was an admin. The other two occurrences were from regular users. I'll let you know how it goes once I pull your changes. If there's anything else you need from me, let me know :smile:
