### ISSUE TITLE
Minor text after ordered list styling

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3032]
Please add more whitespace between ordered list and text at the bottom.

![bulletlist](https://cloud.githubusercontent.com/assets/11160550/7155977/54d8deda-e363-11e4-9fc2-32df8aded96c.jpg)

**Comment by barisusakli** [comment]
Where is this?

**Comment by julianlam** [comment]
I believe this is *any* list inside of post content.

Because posts *themselves* are an unordered list, any list inside the rendered post is actually a "sublist", and the default browser stylesheet **does not apply a top or bottom margin** like it does for root-level lists.

**Comment by julianlam** [comment]
![selection_055](https://cloud.githubusercontent.com/assets/923011/7163982/2ae14588-e36b-11e4-8a22-b54673a0bd20.png)

![selection_056](https://cloud.githubusercontent.com/assets/923011/7163983/2d9f1c50-e36b-11e4-945b-d0a7c4ff1052.png)

Vanilla and Lavender looked ok. Fixed in Persona.
