### ISSUE TITLE
Minor links with no http(s)

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3034]
New post or edit post > Add links without http(s)

nodebb.org
http://nodebb.org/ in Composer preview
```
<a href="http://nodebb.org">nodebb.org</a>
```
Works fine.

community.nodebb.org
http://community.nodebb.org/ in Composer preview
```
<a href="http://community.nodebb.org">community.nodebb.org</a>
```

https://community.nodebb.org/http://community.nodebb.org
/api/http://community.nodebb.org Not Found
not-found

**Comment by barisusakli** [comment]
https://community.nodebb.org/topic/4274/testing-3034
