### ISSUE TITLE
Not search category

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3037]
In my case categories are quite independent resources, search in their fields would be useful.

**Comment by julianlam** [comment]
I do not understand what you are requesting. Are you looking for a way to filter the list of categories by name? 

If so, this would be better accomplished as a plugin, as it's use would be limited in core.

**Comment by atomoc** [comment]
No. I need search Category both are now searching for Posts. In [Search page](https://community.nodebb.org/search).

**Comment by pitaj** [comment]
I think he's requesting a way to search within a category

**Comment by julianlam** [comment]
![selection_045](https://cloud.githubusercontent.com/assets/923011/7754358/04e7470e-ffba-11e4-9e4a-0b7546e75354.png)

:point_up: The advanced search page can do this, so let me know if I am mistaken again :smile:

**Comment by julianlam** [comment]
If you're looking to have the search page search for categories *themselves*, that's not something we'll do in core, so yes, this would be plugin territory.

**Comment by barisusakli** [comment]
Yeah pretty sure he means searching category names since he has like 1500 categories.

**Comment by atomoc** [comment]
> Yeah pretty sure he means searching category names since he has like 1500 categories.

Yes. Thanks Baris!
