### ISSUE TITLE
In-Topic Searching stops responding

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3040]
Steps to reproduce:

1. Profile > Settings > Browsing Settings > Enable In-Topic Searching
2. Profile > Settings > Pagination > Paginate topics and posts instead of using infinite scroll
2. Open https://community.nodebb.org/topic/4274/testing-3034
3. Click on Search icon and use in:topic-4232 windows
4. In-Topic Searching buttons can be seen for a moment in old topic and will disappear in new topic
5. Click on Search icon and hit Enter to use In-Topic nav buttons
6. Go to 8/9 and watch what will happen after jump to page (2)
7. Click on Search icon and hit Enter to use In-Topic nav buttons
8. Use In-Topic UP nav arrow to go to the (1) page (previous)
9. On page (2) it was 1/9 and after a jump to page (1) it is 9/9 (In-Topic results for windows)
10. Use In-Topic UP nav arrow and see how it stops responding

**Comment by julianlam** [comment]
Thanks @nhlpl -- seems as though in-topic search should never disabled if ajaxifying as a result of an action from the search interface.

**Comment by nhlpl** [comment]
In real world usage it's easier to tell someone to put something in search window and jump between pages using intopic search arrows. I think it can be improved from current state. More newbie friendly.

Thanks for taking it under consideration.

**Comment by julianlam** [comment]
@nhlpl As you can imagine, the in-topic searching wasn't designed with pagination in mind, only infinite scrolling :smile: 

Expected behaviour would be hitting "previous" or "next", and having the window stay open while pages change.
