### ISSUE TITLE
Minor dots in Profile Settings

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3041]
Profile > Settings

Dot at the end of the line
*If enabled, in-topic searching will override the browser's default page search behaviour and allow you to search through the entire topic, instead of what is only shown on screen.*

No dot at the end of the line
*Subscribe to email updates for this forum (new notifications and topics) according to a set schedule*

Lack of dot at the end of the line
*Send an email if a new chat message arrives and I am not online*
*Send an email when replies are made to topics I am subscribed to*

Dot at the end of the line
*Follow topics you create.*
*Follow topics that you reply to.*

...and so on.

**Comment by psychobunny** [comment]
Sounds like you're running out of bugs to report :D

**Comment by nhlpl** [comment]
Yeah, no more bugs on the frontend. How about Admin? Will test it after v0.7.0 release.
