### ISSUE TITLE
Minor website field encoding

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3043]
https://community.nodebb.org/user/baris
Website
```
http:&#x2F;&#x2F;nodebb.org
```
https://community.nodebb.org/user/psychobunny
Website
```
http:&#x2F;&#x2F;nodebb.org
```
https://community.nodebb.org/user/nhl-pl
Website
```
http:&#x2F;&#x2F;www.nhl.pl
```

**Comment by barisusakli** [comment]
This is actually fixed on master, but previously we were storing escaped data into db instead of escaping on the way out. Resaving the profile fixes it.

**Comment by julianlam** [comment]
I'm not sure if I should take a look at it anyway. I was thinking we could validate the urls parsed in using url module in node, so we can add protocol if it is missing etc.
