### ISSUE TITLE
Reset Password & Flood control

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3044]
https://community.nodebb.org/reset
You can send as many emails as you want. Please add restrictions.

Related: https://github.com/NodeBB/NodeBB/issues/2971

**Comment by nhlpl** [comment]
"Password successfully changed" action do not block links from other emails. Please prune away Update Password / Reset Password tokens after using one of them.

**Comment by julianlam** [comment]
The tokens expire after two hours. The ability to issue multiple reset tokens is not really a bug, and invalidating any prior tokens is difficult to do because we don't store a uid->tokens mapping, just the other way around.

Let me know if you'd like us to reconsider.
