### ISSUE TITLE
Search matches 30 results and shows 28

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3046]
Steps to reproduce:

1. Search for truly
2. 30 result(s) matching "truly", (0.02 seconds)
3. Check number of results on each page
4. 1st page = 10, 2nd page = 8, 3rd page = 10

**Comment by psychobunny** [comment]
Wonder if its indexing deleted matches?

**Comment by julianlam** [comment]
Yeah that might be fixed now -- need to update Solr on the community forum and re-index.
