### ISSUE TITLE
Restart- & Reload-Buttons in Plugin section [Feature request] [v.0.7.0] 

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#3049]
I would be great, if the Restart- & Reload buttons would also appear in the plugins section. Because there is the place, where they are needed most of the time.

**Comment by psychobunny** [comment]
Sounds like it would be best moved to the header, under a settings dropdown perhaps

**Comment by julianlam** [comment]
:+1:

**Comment by NoodleBB** [comment]
:+1:

**Comment by NoodleBB** [comment]
I assumue psychobunny has implemented this?

I can't find the buttons. Were they are?

**Comment by NoodleBB** [comment]
It's in the profile popup. yariplus told me. And there is more.
