### ISSUE TITLE
Change button text for category icon select

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3050]
Clicking "Save" on the icon select dialog does not save the icon to the category. You have to click save on the edit category page to have the icon applied. It's probably better to change button text to "Select" or something on the dialog.

![screen shot 2015-04-17 at 12 44 12 pm](https://cloud.githubusercontent.com/assets/10014774/7209680/cd7e4bf2-e4ff-11e4-9f3c-27adb63e96e8.png)

**Comment by julianlam** [comment]
:+1:
