### ISSUE TITLE
Edit post and topic name

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3053]
I have seen this in real-time - new topic/post and "This post is deleted!" then typing icon.
https://community.nodebb.org/topic/4296/leaving-subdomain-alert-when-connecting-to-a-rootdomain-link

The second post did not show in real-time.

efkay comment:
"I couldn't edit my first post since the board forces me to give a topic name but there already is one so I deleted my first post and reply a 2nd edited one"

Edit:
Cannot reproduce on main and new accounts in Testing Ground

**Comment by barisusakli** [comment]
`"leaving-subdomain" alert when connecting to a rootdomain link`

Quotes seem to break title input
