### ISSUE TITLE
ACP: Home button is missing [dev v.0.7.0]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#3055]
Since last pull the homepage button is missing in the ACP.

Before:
![bildschirmfoto 2015-04-19 um 11 23 17](https://cloud.githubusercontent.com/assets/11850083/7218911/bd911106-e686-11e4-9fb3-c57f65a43b81.png)

Now:
![bildschirmfoto 2015-04-19 um 11 23 25](https://cloud.githubusercontent.com/assets/11850083/7218912/c31ea44e-e686-11e4-8c08-7aa7d95385e0.png)

**Comment by julianlam** [comment]
In dropdown now

![](http://puu.sh/hjfZZ.png)

**Comment by NoodleBB** [comment]
It's a kind of unclear, to have it inside this popup.

**Comment by julianlam** [comment]
Will let @psychobunny decide :smile:

**Comment by psychobunny** [comment]
I never saw the home button as something super vital to have direct access (in fact at some point I had removed it altogether, but someone complained that they actually used it)

I think behind a dropdown is good enough really for me. If enough people are bothered by it I might reconsider
