### ISSUE TITLE
Unread vs Recent and new topics

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3058]
https://community.nodebb.org/recent
shows a message in real-time
"There is a new post. Click here to reload."

https://community.nodebb.org/unread
only updates Unread (1) icon and clicking on it or hitting F5 is needed
"There are no unread topics."

Similar situation with deleting and purging a topic.

**Comment by barisusakli** [comment]
This seems to work for me, although we stop sending realtime updates if the user is not active after 5 minutes. That could be why you didn't see it updated in realtime.

**Comment by nhlpl** [comment]
Okay, I can confirm lack of updates after long time of inactivity. Thank you for your respond.
