### ISSUE TITLE
Password reset via plugin emailer-local doesn't work [v.0.7.0]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#3061]
When sending a request for password reset. The users don't get such an email.

The "emailer-local"-plugin seems to work correct.
The test emails from within the ACP works correct. 
The email subscription works also correct.

Only the mails from the request for password reset doesn't work.

**Comment by nhlpl** [comment]
It was discussed here:
https://community.nodebb.org/topic/4303/password-reset-doesn-t-work-v-0-7-0

NoodleBB has done tests on a fresh install and using a new user accounts.

**Comment by barisusakli** [comment]
I tested this on our community forum and I received the email although it took a while. We use mandrill plugin.

**Comment by NoodleBB** [comment]
For the records: 
Tested from the scratch with a new installation, and the Mandril-service and -plugin. 
* The test emails from within the ACP works correct. 
* The request for password reset mails does not work.

**Comment by ahwayakchih** [comment]
I have https://github.com/erlgo/nodebb-plugin-emailer-ssl-smtp installed and it worked. Here's what i tried:

1. I registered new account as guest.
2. I clicked on the link in activation e-mail.
3. I logged out.
4. I used "Reset Password" page to enter e-mail.

I got e-mail, clicked on the link it contained and got page where i could enter new password.

After i changed password (ok, i actually entered the same password, but that probably does nto change a thing), i got e-mail notification.

**Comment by NoodleBB** [comment]
I did exactly the same. But there never came an email with an reset-passord-link.

**Comment by ahwayakchih** [comment]
Did you check the logs? Is there an information about mail being sent, or not sent?

**Comment by NoodleBB** [comment]
Yes, I've checked the logs, but they didn't give a hint what went wrong.

```
17/4 18:33 [20235] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 7!!
17/4 18:34 [20235] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 7!!
...
19/4 14:25 [20235] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
19/4 14:25 [20235] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
19/4 14:26 [20235] - [33mwarn[39m: [emailer.smtp] Sent `welcome` email to uid 34
19/4 14:35 [8934] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
19/4 14:36 [8934] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
19/4 14:36 [8934] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
19/4 14:37 [8934] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
19/4 14:37 [8934] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
...
19/4 14:48 [8934] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 34!!
19/4 14:49 [8934] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 34!!
19/4 14:49 [8934] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 34!!
19/4 14:50 [8934] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 34!!
19/4 14:51 [8934] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
...
19/4 14:59 [8934] - [32minfo[39m: [emailer.smtp] Sent `notif_chat` email to uid 3
19/4 15:07 [8934] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 34!!
19/4 15:14 [8934] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 34!!
...
19/4 15:26 [8934] - [33mwarn[39m: [emailer.smtp] Unable to send `reset` email to uid 34!!
19/4 15:41 [8934] - [32minfo[39m: [emailer.smtp] Sent `test` email to uid 2
...
19/4 21:05 [8934] - [32minfo[39m: [emailer.smtp] Sent `notif_chat` email to uid 2
19/4 21:07 [8934] - [32minfo[39m: [emailer.smtp] Sent `notif_chat` email to uid 14
...
20/4 17:00 [8934] - [32minfo[39m: [user/jobs] Digest (day) scheduling completed.
```

**Comment by ahwayakchih** [comment]
If you would like to get a better error report from the plugin, you can try to modify line 48 of nodebb-plugin-emailer-ssl-smtp/index.js file, to look like this:

```js
winston.warn('[emailer.smtp] Unable to send `' + data.template + '` email to uid ' + data.uid + '!!', err);
```

That should output full error data from node.js to your logs/console, which should help to find out why the plugin could not send e-mail.

**Comment by NoodleBB** [comment]
The output is the same:
```
21/4 13:55 [24720] - warn: [emailer.smtp] Unable to send `test` email to uid 1!!
```

**Comment by ahwayakchih** [comment]
Strange. Try to add a line after the edited one:

```js
winston.log(err);
```

**Comment by NoodleBB** [comment]
In line 50 it makes more sense. :relaxed: 

```
21/4 16:56 [24720] - warn: [emailer.smtp] Unable to send `test` email to uid 1!! Error: 140005216278304:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:

    at SlabBuffer.use (tls.js:235:18)
    at CleartextStream.read [as _read] (tls.js:455:29)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)

```

**Comment by julianlam** [comment]
> You will get such error message when you request HTTPS resource via wrong port, such as 80. So please make sure you specified right port, 443, in the Request options.

http://stackoverflow.com/a/18142862

**Comment by ahwayakchih** [comment]
> In line 50 it makes more sense.

Sorry, i may have mixed up something with line number.

Now you know what is wrong (more or less :). Here are some answers from stackoverflow:
http://stackoverflow.com/questions/15421050/node-request-getting-error-ssl23-get-server-hellounknown-protocol

It's strange that test mail was OK, but password reset did not work. If it was a wrong port number or secureProtocol, then it should not work at all.

I don't know the internals of NodeBB, but i assume that it tries to send e-mails the same way, so both test and reset should use the same config. I guess that it would return different error, if it was the SMTP server which was rejecting message because of some spam protection or whatever.

Can you make sure that both test and reset emails are for the same user ID? Maybe it somehow depends on target e-mail address?

**Comment by nhlpl** [comment]
nodebb-plugin-emailer-ssl-smtp depends on nodemailer-smtp-transport
https://github.com/andris9/nodemailer-smtp-transport

**Comment by ahwayakchih** [comment]
@NoodleBB, @nhlpl just pointed out for me, that last log you wrote is about test mail not reset mail. So it looks like both cannot be sent. Are you testing everything in the same environment, or are you changing stuff between different tests?

**Comment by NoodleBB** [comment]
@julianlam The port is correct: 587 (RFC 6409, RFC3207, RFC 2476)

@ahwayakchih For peeking around in the code i've setup a second machine for testing purposes. So the second log came from this testing host.

**Comment by NoodleBB** [comment]
@julianlam The port is correct: 587 (RFC 6409, RFC3207, RFC 2476)

**Comment by NoodleBB** [comment]
I think i've watched a strange thing here.
When i do the setup with the patched "nodebb-plugin-emailer-ssl-smtp"-plugin it doesn't work. Bad
When i do the setup with "snodebb-plugin-emailer-local"-plugin it also doesn't work at all. Also bad.

But:
When i do the setup **only** with the **patched "nodebb-plugin-emailer-ssl-smtp"**-plugin. Disable this plugin and activate the "snodebb-plugin-emailer-local"-plugin. Then it seems to work!?!?

I'll try that again, with another fresh installation.

**Comment by NoodleBB** [comment]
This is crazy. 

Setting up the emailer with the patched "nodebb-plugin-emailer-ssl-smtp", but finally using the "snodebb-plugin-emailer-local"-plugin. It seems, both plugins use the same settings-data. It could be a temp workaround. 

```
22/4 13:08 [10871] - info: NodeBB Ready
22/4 13:09 [10871] - info: [emailer.smtp] Sent `test` email to uid 1
22/4 13:09 [10871] - info: [emailer.smtp] Sent `test` email to uid 1
22/4 13:09 [10871] - info: [emailer.smtp] Sent `test` email to uid 1
22/4 13:13 [10871] - info: [emailer.smtp] Sent `reset` email to uid 2
22/4 13:17 [10871] - info: [emailer.smtp] Sent `reset` email to uid 2
22/4 13:17 [10871] - info: [emailer.smtp] Sent `reset` email to uid 2
22/4 13:18 [10871] - info: [emailer.smtp] Sent `reset` email to uid 2
22/4 13:21 [10871] - info: [emailer.smtp] Sent `notif_chat` email to uid 2
22/4 13:23 [10871] - info: [emailer.smtp] Sent `notif_post` email to uid 2
22/4 13:23 [10871] - info: [emailer.smtp] Sent `notif_post` email to uid 2
```

**Comment by NoodleBB** [comment]
I've wrote a temp workaround-receipt for that. 
https://community.nodebb.org/topic/4323/emailer-via-local-smtp-an-ssl-tls

So users can use SMTP with TLS until that issue is finally fixed.

**Comment by ahwayakchih** [comment]
:)

**Comment by julianlam** [comment]
Seems this is a bug for the emailer-local plugin, so I'll close this for now. Please let me know if I am mistaken.

**Comment by NoodleBB** [comment]
Yes, you're right. This is bug of the emailer-local plugin.
