### ISSUE TITLE
The context menu disappears

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3066]
![2015-04-20 10 35 21](https://cloud.githubusercontent.com/assets/465108/7225712/1a07da32-e74a-11e4-884e-33f6800afc3c.png)

**Comment by atomoc** [comment]
![2015-04-20 10 47 52](https://cloud.githubusercontent.com/assets/465108/7225844/63b3e24c-e74b-11e4-8ed1-73d5145682a0.png)

**Comment by barisusakli** [comment]
I think this is fixed on the latest version of nodebb-theme-persona. @psychobunny ?

**Comment by atomoc** [comment]
Sorry, every time I forget that they are in different repositories. Later, I be sure to check out.

**Comment by atomoc** [comment]
:)

**Comment by atomoc** [comment]
>I think this is fixed on the latest version of nodebb-theme-persona. @psychobunny ?

Good! Thanks!!!
