### ISSUE TITLE
Refresh on every page

### ISSUE THREAD

**Issue by Revii** [NodeBB/NodeBB#3072]
Just updated my forum to the latest v0.7.0 build, and then realize that entire page refresh after go to any link.

**Comment by julianlam** [comment]
You've got a plugin crashing your client side. Check the web console :smile:

**Comment by Revii** [comment]
Weard, after in "dev mode" everything locks good. I hurried with issue. Thank you anyway.

**Comment by Revii** [comment]
OK, hurried one more time. :/
[image](https://cloud.githubusercontent.com/assets/1218869/7239687/10294dae-e7ac-11e4-8c2d-e721ff32a380.png)

Began to appear after: 37a7ac5

**Comment by julianlam** [comment]
Update to new core code please. Resolved in https://github.com/NodeBB/NodeBB/commit/e309a188c317dc8ef2566f3286f419c39c873fdf
