### ISSUE TITLE
Invalid data when no read permissions for guests

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#3075]
https://community.nodebb.org/topic/4311/invalid-data/6

Internal error.
Oops! Looks like something went wrong!

This error normally shows when you disconnect internet connection and click on a tab with opened NodeBB. It also shows when no read permissions were given for guests to see categories.

/
Invalid data

**Comment by barisusakli** [comment]
Tried on latest, if there are no read permissions for any categories for guests I get an empty home page but no invalid data error.

Anyone else can repro?

**Comment by nhlpl** [comment]
Confirmed for Apache and Windows?
https://community.nodebb.org/topic/4311/invalid-data/7

**Comment by barisusakli** [comment]
Sounds like a config/password issue.
