### ISSUE TITLE
Use RSCSS to make CSS more reusable and modular

### ISSUE THREAD

**Issue by FezVrasta** [NodeBB/NodeBB#3080]
You may consider to adopt [RSCSS](https://github.com/rstacruz/rscss).

It helps a lot making the CSS cleaner and it would make the NodeBB components better scoped.

**Comment by julianlam** [comment]
We don't use CSS, we use LESS :)

**Comment by FezVrasta** [comment]
It's not related to preprocessors, it can be applied to all

**Comment by julianlam** [comment]
Ah, in that case -- this is how we intend on structing our CSS going forward. Certain parts of NodeBB are still styled on a page-by-page basis, although we'd ideally like to remove it over time :smile:
