### ISSUE TITLE
Infinite scroll / Pagination block issue

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3081]
![screen shot 2015-04-22 at 2 57 30 pm](https://cloud.githubusercontent.com/assets/10014774/7286316/eface0cc-e8ff-11e4-9303-f846d991d9fa.png)

Not sure why those two are out of sync. If I refresh the browser window now, posts 88, 89, 90 are not displayed at all and page doesn't scroll down.

Change the topic index in the browser url and click enter or click on the pagination block and enter an index, the page goes to the post with the index. Infinite scroll doesn't kick in if I try to scroll down. I have to scroll up atleast a little bit and then scroll down for infinite scroll to work and load posts after that index.

**Comment by barisusakli** [comment]
See here for why it happens https://github.com/NodeBB/NodeBB/issues/2878

The number in the url uses the index of the post from the top, the navigator uses the index from the bottom.

**Comment by pichalite** [comment]
Got it, thanks. Is there a way to change/fix the scroll issue?

**Comment by barisusakli** [comment]
I think inf scroll doesn't kick in because the page doesn't have any margin at the bottom so scroll event doesn't trigger.
