### ISSUE TITLE
Web Installer for NodeBB

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3082]
1. git clone
2. npm install
3. node app (in future npm start imo)

Launches step by step web interface for you to create admin account and enter database information

**Comment by akhoury** [comment]
+1
dont take away terminal access please :) `node app --setup={}`

**Comment by psychobunny** [comment]
haha yeah, that'll still be in there.

**Comment by psychobunny** [comment]
![](http://i.imgur.com/ORVpTUR.png)

https://www.youtube.com/watch?v=f2QjVWELIow

recorded with some potato software

**Comment by julianlam** [comment]
@akhoury Terminal access is still there, but we're preferring environment variables over serialised JSON string passed into `--setup`: https://community.nodebb.org/topic/4325/set-up-nodebb-via-environment-variables
