### ISSUE TITLE
Database type not set

### ISSUE THREAD

**Issue by FormalHellhound** [NodeBB/NodeBB#3085]
I'm getting the error Database type not set immediately when I try to run the setup.

**Comment by barisusakli** [comment]
What git revision is this happening on?

**Comment by FormalHellhound** [comment]
Most recent. I updated to the latest commit. Should I be using the web installer instead of ./nodebb setup?

**Comment by barisusakli** [comment]
No ./nodebb setup should work, looks like it broke on latest commits though.

**Comment by barisusakli** [comment]
Should be good on master now
