### ISSUE TITLE
Category lose name on reload

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3086]
Steps for the bug: 
Go to https://community.nodebb.org
Enter General Discussion
Reload page by pressing f5 or reload button from your browser
"General Discussion" text at the bottom of new topic button will change to Category.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/60

**Comment by julianlam** [comment]
Kind of an important bug to resolve before launch I think? :/

**Comment by psychobunny** [comment]
You've closed this in the referenced theme as well, so make up your mind and let me know.

**Comment by julianlam** [comment]
https://github.com/psychobunny/templates.js/issues/29
