### ISSUE TITLE
Composer broken on iOS

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3090]
is near impossible to write a post on iphone or ipad. 
When you select write area and press first letter the page will move up or composer will dissapear and you wont see what you are actually writing
Even trying to go down again sometimes will end with  composer going mad mode :p
Is more noticeable on ipad with full composer
Tested on last 0.7 dev

**Comment by psychobunny** [comment]
Sorry it took so long to get progress on this, I just got an iphone for testing a few days ago and I'm looking into it now

**Comment by martyalicante** [comment]
Nice. Safari is annoying some times :)
Notice menu dropdown doesnt open also on persona

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/a862051a35101e3151c9b847f1d482d4c55a845a
and
https://github.com/NodeBB/nodebb-theme-vanilla/commit/18279b67e515f81533dd4228a2a26513a49f682d

as well. It's not perfect, but it's definitely usable now

**Comment by psychobunny** [comment]
I found additional bugs so this isn't ready to go just yet
