### ISSUE TITLE
No input for post title neither in create nor in edit mode

### ISSUE THREAD

**Issue by Chart3JS** [NodeBB/NodeBB#3092]
My nodebb on kstars-production.com is of the last version. Title input stopped to appear when I want edit the existing post or to create a new one.
Thanks in advance

**Comment by psychobunny** [comment]
Are you on latest vanilla and persona as well?

**Comment by Chart3JS** [comment]
Latest vanilla + levander. I've tried to switch to persona and other themes- it does not solve the problem.

**Comment by barisusakli** [comment]
Can you post the git hash you are on and the version of the themes.

**Comment by Chart3JS** [comment]
f928b87997f2d7f9fa405482506f9dcede0f0b77

version: 1.0.117

**Comment by barisusakli** [comment]
Your vanilla version is latest but core is 1 month old, you should update to latest.
