### ISSUE TITLE
Clustering doesn't work on master

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3098]
Only starts one process on ./nodebb start. Throws an error on restart. I'm on latest master.

![screen shot 2015-04-27 at 2 37 57 pm](https://cloud.githubusercontent.com/assets/10014774/7358587/411ec3dc-eceb-11e4-9e8b-6ae5e1c1d77f.png)

![screen shot 2015-04-27 at 2 38 57 pm](https://cloud.githubusercontent.com/assets/10014774/7358593/451ed59e-eceb-11e4-8713-5b560596a639.png)

**Comment by pichalite** [comment]
Nodebb v0.7.0-dev

GIT Hash: 51212c2bfac6e5569cc35cc7cf25d1ac1d96be7c

**Comment by barisusakli** [comment]
What does your config.json look like?

**Comment by pichalite** [comment]
Same as what I had before... nothing changed recently.

```
{
    "url": "http://pichalite.com",
    "secret": "somesecret",
    "database": "mongo",
    "mongo": {
        "host": "127.0.0.1",
        "port": "mongo-port",
        "username": "mongo-username",
        "password": "",
        "database": "mongo-db"
    },
    "redis": {
        "host": "127.0.0.1",
        "port": "redis-port",
        "password": "redis-password",
        "database": "0"
    },
    "port": ["4567", "4568", "4569"]
}
```

**Comment by barisusakli** [comment]
Broken in this commit https://github.com/NodeBB/NodeBB/commit/2fbe7a81904731a2e44bd327a84207626d6c8335
@psychobunny 
Gonna take a look

**Comment by barisusakli** [comment]
Let me know if you run into any issues.

**Comment by psychobunny** [comment]
Thanks @barisusakli
