### ISSUE TITLE
Proposal: Add the option to disable Gravatar

### ISSUE THREAD

**Issue by niklas-heer** [NodeBB/NodeBB#3103]
Sorry if I am bordering you guys, but I have a forum with really privacy-focused people so I researched a lot of stuff lately.

The problem with Gravatar is that according to [this discussion](http://meta.stackexchange.com/questions/44717/is-gravatar-a-privacy-risk) the Gravatar service was only created to collect data and monetize it. Therefor I would like to have an option to disable Gravatar in the ACP, as discussed a while ago [here](https://community.nodebb.org/topic/2157/disable-gravatar).

**Comment by julianlam** [comment]
> was only created to collect data and monetize it

I wouldn't go so far as to assume that was the **only** reason for Gravatar's inception. You'll have to admit that it does come in handy for quick avatar creation/reference.

That said, I do eventually want to strip out Gravatar into a plugin, so we'll use this as the issue to track that eventual change.

**Comment by niklas-heer** [comment]
> I wouldn't go so far as to assume that was the only reason for Gravatar's inception. You'll have to admit that it does come in handy for quick avatar creation/reference.

Sure it is really handy, but it also comes with hidden costs and these costs imoh are not worth the thing you're getting.
So I'm very glad to hear these news, thanks! :)

**Comment by phoenixlzx** [comment]
+1 on this, and in some area gravatar may stuck on loading.

**Comment by NijiharaTsubasa** [comment]
Please, we need a way to disable gravatar.
We are hosting a forum with nodebb in China. China GFWed(blocked) gravatar.
And as a result it stuck on loadinguntil connection timeout, even not displaying the default one set in admin panel.

**Comment by Watomsk** [comment]
I concur with Phoenixlzx. Gravatar sometimes gets stuck on loading in my forums. I really wish we could disable it.

**Comment by robotanarchy** [comment]
I'd also like to have an option for disabling gravatar.

**Comment by julianlam** [comment]
We have a working solution although it is currently not compatible with all
browsers.

Still investigating alternatives....

**Comment by robotanarchy** [comment]
@julianlam: I don't quite understand what you need to investigate or check against browsers there.

When Gravatar is disabled, I'd expect a default picture, something like that *(random google images search...)*: http://www.keralabjp.org/images/No_Image.jpg 

Uploading custom user pictures already works anyway.

If you want to make it extra nice, give the admin the ability to upload a default picture.

So what exactly is the problem?

**Comment by julianlam** [comment]
The alternative was to use a letter with random background, constructed via
css.

Works great on Chrome, doesn't work at all. on Firefox.

Version 1 of this worked quite well across browsers, but was quite a bit of
work to convert for existing themes, hence the search for a better
solution.

**Comment by robotanarchy** [comment]
How about generating these images on the server side (maybe with a cache?) or at least implementing the simple solution I've described until the better version is ready?

**Comment by julianlam** [comment]
They're not images.

**Comment by robotanarchy** [comment]
What I ment is: generate it on the server side, then cache it as image (the [identicon](https://www.npmjs.com/package/identicon) nodejs library can do that).

However, if you want to do it client-side only, what about [Jdenticon](http://jdenticon.com/#browser-support) for example? It works on the following browsers:

> Internet Explorer 9 and later
> Chrome 7 and later
> Firefox 4 and later
> Opera 11 and later
> Safari 5 and later

**Comment by julianlam** [comment]
User Icons merged into master now :smile:
