### ISSUE TITLE
Merging Topics

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3106]
There´s an option to divide topics , why not one for merge similar ones?
Should be a good enhancement

**Comment by pitaj** [comment]
How could this be done? How would the merge occur? During a topic is simple, you just make a new topic referencing the old one. 

But merging two would be more difficult. You'd have to figure out a system to bring the posts from the other topic into the original. Would you just append them? That wouldn't make much sense. Would you insert them by time? That could interrupt the original flow.

**Comment by julianlam** [comment]
I would imagine that the ideal use case for topic merging would be for
topics with one or two replies, where merging wouldn't interrupt any flow,
if at all. Would be useful for two topics posted around the same time that
ask the same question.

Implementation wise, it's up to the forum admin to decide when and when not
to merge, I'd think.

**Comment by martyalicante** [comment]
I woudnt mind to follow the vbulletin method

When you merge a thread, the posts of one thread are added into the other thread. As they are displayed by date, posts can be mixed throughout the thread. Whichever thread was started first has the first post.
You can choose to keep the other thread as a redirect or to delete it completely.

**Comment by julianlam** [comment]
Best to keep this functionality to a plugin, if desired.
