### ISSUE TITLE
Messages on flags

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3107]
I would like to see on the future the option to include a message when you submit a flag form a post so the moderator can see the problem easy

**Comment by pitaj** [comment]
Good idea

:+1:

**Comment by psychobunny** [comment]
If we're doing this, it would be good to have some default options as well ex

* post is spam
* post is offensive 
* post is (textarea)

And then more feature creep: a hook to add more options.

This would be a great PR - I don't think we will plan to build this ourselves till post 1.x

**Comment by martyalicante** [comment]
Agree @psychibunny. 
Thank for reply
