### ISSUE TITLE
Unable to change user picture

### ISSUE THREAD

**Issue by robzhu** [NodeBB/NodeBB#3108]
Latest version of NodeBB using redis appears to have an issue where Profile -> Edit -> Change Picture lists Gravatar as the only option. 

http://i.imgur.com/44LaMRJ.png

**Comment by barisusakli** [comment]
Can you check the setting in ACP?

admin>settings>user

![image](https://cloud.githubusercontent.com/assets/2583394/7448363/c87ffe64-f1e5-11e4-912f-cdc33ebdc532.png)

**Comment by robzhu** [comment]
Wow, I feel incredibly dumb. Sorry about that, closing the issue.
