### ISSUE TITLE
Feature reqest: Pass path to filter:scripts.get hook

### ISSUE THREAD

**Issue by kurt-stolle** [NodeBB/NodeBB#3111]
I want to serve different scripts depending on the URL the user is visiting. 

For example, if the URI is `/plugins/myplugin/foo` I want to serve `/plugins/myplugin/src/foo.js`, but if the URI is `/plugins/myplugin/bar` I want to serve `/plugins/myplugin/src/bar.js`.

The hook to add scripts appears to be `filter:scripts.get`, but from this hook it is not possible to check the path of the request. 

# Request
Add a path/URI data element to the hook call `filter:scripts.get`.
https://github.com/NodeBB/NodeBB/blob/master/src/meta/js.js#L243

**Comment by julianlam** [comment]
Hi @kurt-stolle, the `filter:scripts.get` hook is fired once on startup, and not on a page-by-page basis, so this wouldn't quite work as you'd want it to.

Have you started a topic on the community forum? You may be able to get alternate options there :smile:
