### ISSUE TITLE
Logging in on mobile (android)

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3117]
If an input box is focused, it requires two clicks to hit the submit button. We probably have this same issue elsewhere as well.

**Comment by julianlam** [comment]
On my phone, I can't reproduce this. Focusing on either username or password input box, I can click "Login" without having to "click out" of the focused input.

**Comment by psychobunny** [comment]
Weird, we have the same phone and I'm still reproducing it. Have to click twice, once to unfocus and hide the keyboard, and again to submit

**Comment by julianlam** [comment]
Chrome 42.0.2311.111? (That's the one on my device)

**Comment by psychobunny** [comment]
oh wow, my chrome's out of date, ver 40. After updating, this works as expected :+1:
