### ISSUE TITLE
Show the first group badge if none has been selected yet

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3118]
Right now requires you to go to your user settings to select the badge you wish to display. If you have no selected badge and you own at least one, it should by default display your first available group badge

**Comment by lots0logs** [comment]
:+1:

**Comment by pichalite** [comment]
I am not sure if this has to be a separate issue but, if I am an admin and I belong to the system group "administrators" I do not have an option to display the groups badge that I am an admin.

**Comment by zetas** [comment]
Thanks for opening this @psychobunny it's been bothering me for awhile. Is there a way to force it to assign to a user in the meantime?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/2816 :trollface:

**Comment by zetas** [comment]
haha... that's hilarious. @psychobunny is on drugs!

**Comment by lots0logs** [comment]
:laughing: keep taking whatever led you to create THIS issue @psychobunny, forget the other one (oh wait, you already did that hehe) :wink:

**Comment by psychobunny** [comment]
What's sad is I don't do drugs :( .. I imagine if I did!

There was a good and unrelated reason for #2816 but for the sake of comic relief I'll just leave this as is :D
