### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3120]
Topics page, posts page in user profile displays 1 more topic/post than the setting

![screen shot 2015-05-07 at 11 23 40 am](https://cloud.githubusercontent.com/assets/10014774/7522917/29d442e6-f4ad-11e4-89f9-1eb196c06ba6.png)
![screen shot 2015-05-07 at 11 24 24 am](https://cloud.githubusercontent.com/assets/10014774/7522926/31c5e1a8-f4ad-11e4-8ebb-ad24a882a79f.png)

In the category page, some pages show less topics than the setting. This may be because of deleted topics but this will be confusing to the user. There should atleast be a topic deleted message.

![screen shot 2015-05-07 at 11 27 31 am](https://cloud.githubusercontent.com/assets/10014774/7522949/5911f30a-f4ad-11e4-835c-572fb9810b1a.png)
![screen shot 2015-05-07 at 11 27 56 am](https://cloud.githubusercontent.com/assets/10014774/7522953/5cae16b0-f4ad-11e4-9490-6daf2ce7514d.png)
![screen shot 2015-05-07 at 11 28 32 am](https://cloud.githubusercontent.com/assets/10014774/7522959/6002e1f6-f4ad-11e4-9956-5fccc960c8f9.png)

**Comment by barisusakli** [comment]
Yeah missing topics are deleted ones. Maybe it should display [topic-deleted] like we do for posts.

**Comment by pichalite** [comment]
:+1:
