### ISSUE TITLE
email address validations stop working

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3123]
Email address validations stop working. Now I can use an email address from an already existing user and register with a different username.

**Comment by barisusakli** [comment]
The url in config.json doesn't have anything to do with the  checks we do for email availability this is probably an unrelated bug.

Are you on latest and did you run the latest upgrade script from yesterday?

**Comment by barisusakli** [comment]
Are you on redis? If so please run the following and check the output

```
redis-cli
zscore email:uid "already_taken@gmail.com"
```

Use an email adress that is already taken.

**Comment by pichalite** [comment]
mongo is my primary db. I use redis for clustering

**Comment by barisusakli** [comment]
in that case run

```
mongo
db.objects.find({_key: "email:uid", "value": "already_taken@gmail.com"});
```

**Comment by pichalite** [comment]
doesn't return anything

**Comment by barisusakli** [comment]
What about  `db.objects.find({_key:"email:uid"})` ?

**Comment by pichalite** [comment]
sorry it does return the object. forgot to run ```use dbname```

{ "_id" : ObjectId("554d0e961bb52375a532bb7d"), "_key" : "email:uid", "value" : "pichalite.com@gmail.com", "score" : 13 }

only returns one. I have two users with same email address.

**Comment by barisusakli** [comment]
Ok reproduced. Thanks.

**Comment by pichalite** [comment]
I was setting up an sso plugin and had to change the url to use https and got this issue after that. I thought the url shouldn't be the issue but for some reason logged this ticket with that. I should probably change the title.

**Comment by barisusakli** [comment]
Yeah its not related to the url in config, its an issue with the emails being stored with \uff0e in mongo.

**Comment by pichalite** [comment]
The fix will probably solve this issue as well but just so you know...
Searching for user in ACP using email address with a "." doesn't display users that were created before the upgrade.

**Comment by barisusakli** [comment]
Yeah It will.

**Comment by barisusakli** [comment]
Update to latest and run the upgrade script, it will fix the wrong emails. Then try the register bit again

**Comment by pichalite** [comment]
:+1: looks good

**Comment by pichalite** [comment]
@barisusakli is this related?
user settings page does not load settings

**Comment by barisusakli** [comment]
Just published vanilla&persona to npm update those and it should work again.
