### ISSUE TITLE
Feature: Allow users to unfollow certain categories

### ISSUE THREAD

**Issue by Radiergummi** [NodeBB/NodeBB#3124]
We have a RPG category. Some users don't participate though, so they find it pretty annoying to have multiple topics listed under *unread*. I don't know how this is implemented, but would it be possible to prevent certain categories from showing up here?

**Comment by julianlam** [comment]
You can already do this :) visibility settings for each category are along the top of the category template

**Comment by Radiergummi** [comment]
I'm sorry, I just discovered the ignore-button :D
