### ISSUE TITLE
Curly braces in templates are being escaped, preventing scripts from working

### ISSUE THREAD

**Issue by Radiergummi** [NodeBB/NodeBB#3125]
I just noticed that curly braces in my templates are being escaped to `&#123;` and `&#125;`, which prevents custom scripts or plugins such as [polls](https://github.com/schamper/nodebb-plugin-polls) from working (which uses `<script>Poll.load({ pollid: {pollid} })</script>` to show a poll).  
I have a feeling this is due to the recent template.js change which requires two curly braces in some places, but I don't really know.  
My site is on `9ca7243124` currently.

**Comment by julianlam** [comment]
@psychobunny can elaborate if needed, but I believe the solution here is to have @schamper update his use of `{poll}` to use double curly braces: `{{poll}}`

**Comment by julianlam** [comment]
pollid*

**Comment by lots0logs** [comment]
I think I am seeing the same problem. Every page that loads has this error in the console:
```
Uncaught SyntaxError: Unexpected token &
```
Then if I click on it to view the source it shows this:
```
$(window).on('action:ajaxify.start', function(ev) &#123;
	socket.removeListener('event:new_topic', addActiveUser);
&#125;);

function addActiveUser(topic) &#123;
	var activeUser = $('.active-users').find('a[data-uid="' + topic.uid + '"]');

	if(!activeUser.length) {
		ajaxify.loadTemplate('activeusers', function(template) {

			var newUser = templates.parse(templates.getBlock(template, 'active_users'), {
				active_users: [{
					uid: topic.uid,
					username: topic.user.username,
					userslug: topic.user.userslug,
					picture: topic.user.picture
				&#125;]
			});
			$(newUser).prependTo($('.active-users'));
		});
	} else &#123;
		activeUser.prependTo($('.active-users'));
	&#125;
}

socket.on('event:new_topic', addActiveUser);
```

**Comment by julianlam** [comment]
@lots0logs Please update to latest core code, and then go to the widgets page in ACP. For all of your active widgets, drag a new container to replace the existing one.

@psychobunny will probably write an upgrade script this coming week.

**Comment by lots0logs** [comment]
@julianlam That didn't help. Actually made it worse, see http://forum.antergos.com/

**Comment by julianlam** [comment]
Hm... what version of t.js are you running? Should be v0.2.x

**Comment by lots0logs** [comment]
yeah its 0.2.0. Everything is updated to the current master. I also merged lavender changes to my theme so I dont think that's the problem :confused:

**Comment by julianlam** [comment]
Can you paste the contents of the container html?

**Comment by lots0logs** [comment]
```
<div id="welcome" class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">{\{title}\}</h3></div><div class="panel-body">{\{body}\}</div></div>
```

**Comment by julianlam** [comment]
I see, thanks. Please change that to `{{title}}` and `{{body}}`, with no interstitial slashes.

@psychobunny :trollface: time to fix again.

**Comment by Radiergummi** [comment]
@lots0logs yeay, my favorite distro uses NodeBB :smile:  

@julianlam I tried changing to double curly braces, but that just escaped the inner braces... No luck yet. Any advice?

**Comment by lots0logs** [comment]
@julianlam Your suggestion has resolved the issue for me. Thanks!

**Comment by psychobunny** [comment]
> @psychobunny will probably write an upgrade script this coming week.

done, won't clobber anything if you had already made this change manually.
