### ISSUE TITLE
Unread section

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#3128]
Possible enhance
The unread section lose its function on big forums
let me explain, when you follow a main category on a big forum you end up with a permanent 20+ notification of unreads on your navigation bar
then you go try clear by reading it but every post on the category will give you another unread so you just get mad and stop using it.
maybe a good solution should be an option to let users decide if they want all topics os just the ones they following

**Comment by pitaj** [comment]
I feel like you should be able to toggle between topics and posts on the unread page. That would be a nice feature IMO.

**Comment by julianlam** [comment]
@martyalicante Traditional advice re: this is to "ignore" categories that you are not interested in receiving updates for.

That said, we are aware that for busy forums, the unread page is basically the same as `/recent`, so some adaptation would be nice.

You could also remove the unread page entirely from the navigation bar, but that is less ideal if you like what it does :smile:

**Comment by martyalicante** [comment]
@julian on bigs forums it doesnt mather if you only follow 1-2 category. Unread page will fill up very quick. 
Maybe the option to see and switch unreads of x category could be nice to be integrated inside unread page

**Comment by lots0logs** [comment]
How about making the unread post list filterable by category. The filterable functionality would work in a similar way as shown here (ignore the irrelevant content/layout): http://www.elegantthemes.com/preview/Divi/filterable-portfolio-1-column/

**Comment by martyalicante** [comment]
Yeah Thats nice idea @lost0logs

**Comment by julianlam** [comment]
@lots0logs This is already the case, as far as I know. In v0.7.0, you can "ignore" categories, and they do not show up in your unread list.

**Comment by aggied** [comment]
piggybacking of my post [here](https://community.nodebb.org/topic/6063/why-would-i-follow-another-user), I I would like to see a view where the user can get a custom feed of all the things relevant to them -- meaning a compiled feed of all the topics and users they follow (maybe categories as well if they desire). Right now the user following is a bit weak, and a combined feed of all the users a user follows would be very helpful. Seems we could just include a users followed users' posts in the unread section?

**Comment by henrywright** [comment]
+1 to @aggied's suggestion. I like the idea of having a page of topics created by users I'm following. 

The unread page shows me too much stuff I'm not interested in so I don't use it.

**Comment by henrywright** [comment]
Thinking about this issue some more, I think the unread feature fails because it is __opt-out__ rather than __opt-in__. For example, currently I have to click _Ignore_ on a particular category to remove those topics from my unread page. This means I start with an unread topics page that takes all categories into account, and I get a lot of unread topics show up. I'd rather start with a blank unread page, and then _Watch_ the categories that I'm interested in.

**Comment by boomzillawtf** [comment]
I've been working on this and have an implementation. We've been discussing here:
https://what.thedailywtf.com/topic/19702/ignoring-a-topic

I also just opened this for discussion:
https://community.nodebb.org/topic/8527/ignoring-individual-threads
