### ISSUE TITLE
Use SpeakingURL for slugs

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#3129]
http://pid.github.io/speakingurl/

This module is really nice and could easily replace your society function for the better.

**Comment by julianlam** [comment]
Hm... our slugify method is highly optimised, plus it is only one method, any particular reason to switch and incur possible overhead (although it would probably be quite minimal) besides transliteration support?

**Comment by pitaj** [comment]
In my opinion, if someone else is willing to maintain code for you and
possibly improve upon it, you should always use that to your advantage.

**Comment by julianlam** [comment]
@pitaj I want to do this right, and so I have to push this to v1.0.0

For that version we're planning to swap out require.js for browserify and rewrite our modules in CommonJS format (the exact details have not been clearly defined at this point), so at that point we'd want to use the npm package for speakingurl and require it on the client-side as necessary.

**Comment by julianlam** [comment]
speakingurl works in very narrow situations... namely topic and category slugs. I can't see it working well as a replacement for `utils.slugify()`, since usernames don't really slugify well, nor am I sure if they _should_, since then it would be difficult to know how to mention somebody (do you type in the speakingurl letters, or the proper character?)

So it looks like I might just use this module separately on the server-side for those two use cases...

**Comment by nhlpl** [comment]
`transliteration` module is able to convert Chinese, Japanese and Korean.

**Comment by julianlam** [comment]
Closing this as:

1. speakingurl does not handle asian characters (returns `''`)
1. limax, the other alternative, requires compiled dependencies
1. There is no pure js solution

Until the third is resolved, we'll stick with our own implementation for now :smile:

**Comment by ahwayakchih** [comment]
@julianlam https://github.com/andyhu/node-transliteration mentioned by @nhlpl seems to handle asian characters pretty well and is pure JS. Maybe NodeBB could simply allow plugins to override built-in transliteration? That way, NodeBB could keep its highly optimised method, but those who need more advanced one, could install a plugin for that.
