### ISSUE TITLE
Chinese translation issue

### ISSUE THREAD

**Issue by poppinlp** [NodeBB/NodeBB#3132]
watch 和 unwatch 的中文翻译是 “监视” 和 “取消监视”。
这翻译感觉怪怪的，换成 “关注” 会不会好点？

**Comment by julianlam** [comment]
Sounds good, you can contribute to the translation effort here :smile: : 

https://transifex.com/projects/p/nodebb/

**Comment by poppinlp** [comment]
@julianlam 
THX.
Add suggestion for 'watch' 'unwatch' and 'stop watching this topic' already.
