### ISSUE TITLE
acp.min.js

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3134]
Right now, ACP just requires all files separately and unminified. Additionally it includes the entire nodebb.min.js file despite the fact that it only requires `app`, `ajaxify`, `translator`, and `templates.js`

Also, allow plugins to define `acpScripts`

**Comment by NicolasSiver** [comment]
It's good news, that this update will be included in `0.7.1` ;)
Also would be great if you will use some sort of dedupe for minification process of admin scripts.

**Comment by NicolasSiver** [comment]
With latest update to ACP. I have found interesting thing. If you just include `.js` in ACP template, it will work OK now, so you don't need concatenate with all js scripts.
