### ISSUE TITLE
Mark unread for all doesn't work

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3138]
Tested on mobile on a topic with just one post. Maybe infinite load triggers and marks it read? 

I do get the success alert.

**Comment by julianlam** [comment]
@psychobunny Can you try clearing phone cache? When I implemented it, I tested on chrome mobile view, and it worked.

Didn't work on my phone (a week ago), but when I tried it again yesterday, it worked.

**Comment by psychobunny** [comment]
Yeah, works now
