### ISSUE TITLE
Long loading pages categories

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3139]
I've written before about long loading in the administrative panel of categories, but it is important this issue!

If more than 1500 categories, the loading becomes unbearably long, especially on slower servers, more than 10 seconds! On a very good server, it is more than 3 seconds.

Please, deal with it as soon as possible! I do not want to change NodeBB ipboard, phpbb or something.

Please tell me when it will be decided?

**Comment by Fusselwurm** [comment]
I haven't ever seen a board with nearly as much as a thousand categories. Just out of curiosity, what kind of board are you hosting?

**Comment by atomoc** [comment]
On my work computer, icore 5 4000, 8gb.

**Comment by atomoc** [comment]
> I haven't ever seen a board with nearly as much as a thousand categories.

I understand it.

**Comment by pitaj** [comment]
It could be sped up, maybe, with some infinite scroll stuff. But loading 1500 categories unto the page in the first page creates such a huge DOM structure that your computer should be dead.

**Comment by atomoc** [comment]
By the way, the home page is loaded longest, but it has only 10 categories.

**Comment by pitaj** [comment]
Is that on a cold load? Because that would make sense, since all of the scripts have to loaded in at once in that case.

**Comment by atomoc** [comment]
> Is that on a cold load?

Exactly.

**Comment by psychobunny** [comment]
I think the best way for us to look into it is if you can provide a dump (hopefully nothing sensitive) then we can test against it. Right now 1500 categories seems like a really odd use case, but it is still worth looking into

Can you triage for us exactly which pages load slowly? (Both front end and admin)


> Also, are you sure you're not using categories where you should use tags?

This BTW. Any chance of you reconsidering how you organize your structure?

**Comment by atomoc** [comment]
> I think the best way for us to look into it is if you can provide a dump (hopefully nothing sensitive) then we can test against it.

If I understand correctly, I could give you any data authentication: ssh, ftp, NodeBB. Server running on the netbook, this is the easiest way to check NodeBB.

> This BTW. Any chance of you reconsidering how you organize your structure?

Look it up yourself.

**Comment by atomoc** [comment]
> I do not want to change NodeBB ipboard, phpbb or something.

Understand, for me, all this is very important. You should understand the horror I feel at the mere mention of their names forums engines.

**Comment by atomoc** [comment]
> Server running on the netbook

NodeBB run on three servers. Just my computer is the most powerful of them. Netbook is open 24 hours a day, and he is very weak, we can see how everything is bad.

**Comment by atomoc** [comment]
The third server does not pull NodeBB, because on it a problem because of the memory, but there it is 2000mb. Perhaps this is due to the inability to establish `vm.overcommit_memory=1`?

**Comment by atomoc** [comment]
NodeBB run very rarely on the third server.

**Comment by atomoc** [comment]
[Link](http://eyrini.ru/forum) to netbook server.

**Comment by atomoc** [comment]
Close Why? The problem is not solutions

**Comment by atomoc** [comment]
More 503 error displays after the last update!
