### ISSUE TITLE
Please consider my PullRequest

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3140]
https://github.com/NodeBB/NodeBB/pull/3101/files

In the community NodeBB psychobunny [gave me the opportunity to participate in developing and now I'm waiting](https://community.nodebb.org/topic/4328/add-two-fields-in-nodebb/5). I want to know how much I have to wait? Describe, please, why do not you take it?

**Comment by julianlam** [comment]
Hi @atomoc, please realise that we have many other obligations and cannot respond to all requests quickly. I've replied to your pull request now.
