### ISSUE TITLE
OP should be able to fork a topic

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3142]
Hmm, I think this used to work at some point. Currently only mods can do this

**Comment by julianlam** [comment]
I think only moderators and admins are allowed to do this. I personally don't think OP should be given this power, but that is just my opinion of course.

Theoretically, OP could fork out replies that do not agree with his statement :wink:

**Comment by Ekunia** [comment]
Allow admins to disable it.

**Comment by julianlam** [comment]
I personally still feel this could be abused by having an overzelous OP fork out dissenting opinions to his post...

Besides, after a certain number of posts, wouldn't the post be less about OP than ever?

**Comment by aggied** [comment]
Still learning the ways of NodeBB here, but for my thoughts on the matter please see this post. I hope it will be worth the 30 seconds of reading. 

https://community.nodebb.org/topic/4487/concept-subtopics/14
