### ISSUE TITLE
How to use /api/login

### ISSUE THREAD

**Issue by blackbox063** [NodeBB/NodeBB#3144]
Hi everyone! I trying to login to NodeBB using /api/login with POST method and username, password parameters but it return 404. How to use this api?
![screen shot 2015-05-16 at 17 25 17](https://cloud.githubusercontent.com/assets/2224866/7665754/dd2d63fa-fbf0-11e4-89f3-ae4de92caeed.png)

**Comment by barisusakli** [comment]
There is no /api/login route, the login route is called /login. You also need to send a csrf_token with the username/password
