### ISSUE TITLE
Widget Areas missing

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#3145]
Is my setup messed up or Categories and Topic Areas are no longer in ACP>Extend>Widgets ?
I only have "global" and "groups/details.tpl" left.

**Comment by julianlam** [comment]
Hey there,

That is correct, the Persona theme does not have widget areas defined for
now, in anticipation of a widgets refactor by @psychobunny.

There is, however, nothing stopping you from adding widget areas of your
own... :)

**Comment by tedr56** [comment]
Thanks. I understand.
However, I have no idea how to do this.
I actually don't need them. I wanted to share, just in case.

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/69
