### ISSUE TITLE
Remove unused containers

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#3146]
After update, I think the shoutbox plugin was making trouble.
So, I have disabled it from console.
In ACP, the Soutbox Widget is no longer in my Global/Sidebar and available widget list, but an empty container was still visible in the forum.

I had to go back in ACP and click "Save" to resolve it.

**Comment by tedr56** [comment]
Any insight on this?

**Comment by pitaj** [comment]
Yeah, It's because the widget is technically still there, but it doesn't exist anymore. Maybe on every restart, NodeBB should check widgets.
