### ISSUE TITLE
External links bug in 0.7-dev?

### ISSUE THREAD

**Issue by capr** [NodeBB/NodeBB#3148]
My forum is at https://luapower.com/forum (config.json:url set accordingly). Clicking on a link pointing to https://luapower.com/foo for instance is redirected at runtime (the href looks fine) to https://luapower.com/forum/foo (a nonexistent url) and the page says:

/forum/api/foo Not Found
This only happened after the upgrade from 0.6 which is why I thought it may be a bug.

Note1: I deactivted all the plugins for this test except the markdown plugin.
Note2: Issue seems to only happen if the URL starts with https://luapower.com

Thanks!
Cosmin.

**Comment by capr** [comment]
Note that the described behavior is __not present__ on the website currently because I inserted the following workaround:

<script>
$(function() {
    $('a').each(function() {
        var href = $(this).attr('href')
        if (!href) return
        if ((href.indexOf('https://') == 0 || href.indexOf('/') == 0) && href.indexOf('/forum') != 0)
            $(this).click(function(e) {
                e.stopPropagation()
            })
    })
})
</script>

**Comment by barisusakli** [comment]
Yeah sounds like a bug. If you forum is at `https://luapower.com/forum` then `https://luapower.com/foo` shouldn't use ajaxify.

**Comment by julianlam** [comment]
Sorry about that @capr :smile: We updated how we handle detection for external URLs, but we forgot to fix that up for subfolder installations.

**Comment by capr** [comment]
> Sorry about that @capr We updated how we handle detection for external URLs, but we forgot to fix that up for subfolder installations.

Thank you!
