### ISSUE TITLE
Use JSON-LD as microdata format

### ISSUE THREAD

**Issue by Radiergummi** [NodeBB/NodeBB#3149]
Google recommends using JSON-LD as the microdata format (start reading [here](https://developers.google.com/structured-data/)) for websites. It would be pretty neat to have JSON-LD generated by NodeBB, as it also enables knowledge graph boxes and so on.

**Comment by julianlam** [comment]
We already have schema.org microdata embedded in the site, although I suppose it wouldn't hurt to look into this as well. Is one better than the other?
