### ISSUE TITLE
no categories.tpl in widgets page on admin control panel

### ISSUE THREAD

**Issue by Firelad97** [NodeBB/NodeBB#3151]
It was there - until I installed and enabled Custom Homepage plugin and then disable it. It works before Persona (or v0.7.0-dev) was released. I don't know how this plugin caused this... well, can it be fixed?

**Comment by pichalite** [comment]
Persona theme is not setup for widgets. You will have to use a different theme (lavender or vanilla) for using widgets.

**Comment by Firelad97** [comment]
Lol I'm sure I had tested with Lavender and Vanilla themes and home.tpl still isn't showing up on widgets page. Proebaby I'm wrong, I will check again later today (Monday).

**Comment by Firelad97** [comment]
Ok I'm pretty sure it's categories.ptl now, because I just checked today. Changed to Lavender and Vanilla themes to see if it shows up on widgets page now. Yes, they do but not on Persona. Maybe should I had posted an issue in Persona instead of here?

**Comment by pichalite** [comment]
As I said, persona is not setup for widgets. There is an issue already under persona, you don't have to create a new one. I think you can close this one.

https://github.com/NodeBB/nodebb-theme-persona/issues/69

**Comment by Firelad97** [comment]
Haha thanks for letting me know. I didn't notice that issue.
