### ISSUE TITLE
0.7.0-Dev (Commit #: 48b5d90a9e135e91eca27a550c7815ad410a8403) Signatures not showing in forums even when enabled.

### ISSUE THREAD

**Issue by mastacontrola** [NodeBB/NodeBB#3152]
Signatures are not displaying on any post even with signatures enabled.

**Comment by julianlam** [comment]
Persona theme elects not to display signatures, I think...

**Comment by mastacontrola** [comment]
I switched out with lavender and the vanilla themes.  I did not see the signature in either of the themes provided.

**Comment by psychobunny** [comment]
I tested against that commit on the latest vanilla (1.0.127) and it works perfectly for me. Did you perhaps disable signatures in the ACP?

**Comment by mastacontrola** [comment]
Apparently we did disable signatures, and I thought wrong.  I've put a request to get signatures back in on the persona theme though as we much prefer it's layout, but also like the signatures.  Just an enhancement request. I'll close this issue then.

Thanks for the assist and sorry about posting as an issue on all of NodeBB.
