### ISSUE TITLE
can we bring tags (or releases) back? or what's the alternative?

### ISSUE THREAD

**Issue by akhoury** [NodeBB/NodeBB#3154]
I know there was a discussion about this somewhere, I kind of missed out on it. 
What happened to tagging and shipping?
I liked the idea of code-frozen tags or releases, i..e 0.7.0, to develop plugins against. 
It's really not-as-cool to keep track of stable code via git hashes.

**Comment by julianlam** [comment]
Hey Aziz -- definitely more fun to have releases :smile: 

The only blockers we have left are listed here: https://github.com/NodeBB/NodeBB/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.7.0

Mostly iOS compatibility with Persona theme, then we're set to launch.

**Comment by akhoury** [comment]
ah, my bad, i thought there was a release but wasn't tagged in here.
