### ISSUE TITLE
Can't open menu on iPhone

### ISSUE THREAD

**Issue by jbredice** [NodeBB/NodeBB#3158]
Selecting the menu icon on the top right doesn't open the menu on iPhone 6.  Button highlights but nothing happens.  Worked in 0.6 but not 0.7.  Verified on community.nodebb.org

**Comment by pichalite** [comment]
This issue was fixed on persona theme yesterday. The theme is probably not upgraded on community.nodebb.org

https://github.com/NodeBB/nodebb-theme-persona/issues/46

**Comment by psychobunny** [comment]
I've just updated the community, @jbredice can you give it another shot? I've been testing on a 4s and would like to confirm it working on other versions :)

Also... does the menu have an animation when it opens?

**Comment by jbredice** [comment]
Works!

**Comment by jbredice** [comment]
Menu pops open and closed.  No discernible animation.

**Comment by psychobunny** [comment]
Thanks. I guess that's better than not working at all haha.

I'll try to figure it out
