### ISSUE TITLE
Error in chats on master

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3168]
![screen shot 2015-05-22 at 8 20 40 am](https://cloud.githubusercontent.com/assets/10014774/7773804/8e7a33a4-005b-11e5-8b49-95464bacef59.png)

**Comment by julianlam** [comment]
Can you report your git hash? This sounds like a bug Baris fixed in latest

**Comment by pichalite** [comment]
Never mind, forgot to pull latest commit from @baris that fixed this.
