### ISSUE TITLE
Urgent issue

### ISSUE THREAD

**Issue by kacemlight** [NodeBB/NodeBB#3171]
Hello,

This morning I got a real problem with my nodebb website : www.nodejsworld.com .
First it was down, and when I restart it, my web site have a lot of bugs : 
Admin control panel don't work 
No footer
Cannot logout or login
And the website not displayed properly.

You can visit the website and see some javascript problems in the console.

Please I don't know how to solve this problem. Please help!

Regards,
Thanks

**Comment by kacemlight** [comment]
When i see in console of my browser, I think the problem is related to the jquery library. But I don't know how to solve it. Help please!

**Comment by julianlam** [comment]
Try starting NodeBB in dev mode (`./nodebb dev`), and let us know what errors you see when you start NodeBB.

Also, what error do you see on the client side?

**Comment by kacemlight** [comment]
Hi,

When I rstart my nodebb site in dev mode I got this : 

kacemlight@nodebb:~/nodebb$ ./nodebb dev
Launching NodeBB in "development" mode.
To run the production build of NodeBB, please use "forever".
More Information: https://docs.nodebb.org/en/latest/running/index.html

NodeBB v0.6.1 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

24/5 15:11 [31272] - info: Time: Sun May 24 2015 15:11:03 GMT-0400 (EDT)
24/5 15:11 [31272] - info: Initializing NodeBB v0.6.1
24/5 15:11 [31272] - verbose: * using configuration stored in: /home/kacemlight/nodebb/config.json
24/5 15:11 [31272] - verbose: * using redis store at 127.0.0.1:6379
24/5 15:11 [31272] - verbose: * using themes stored in: /home/kacemlight/nodebb/node_modules
24/5 15:11 [31272] - verbose: [plugins] Initializing plugins system
24/5 15:11 [31272] - info: Enabling 'trust proxy'
24/5 15:11 [31272] - verbose: [notifications.init] Registering jobs.
24/5 15:11 [31272] - info: [themes] Using theme nodebb-theme-lavender
24/5 15:11 [31272] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-youtube
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-youtube
24/5 15:11 [31272] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-google-analytics
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-google-analytics
24/5 15:11 [31272] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-codebender
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-codebender
24/5 15:11 [31272] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-spam-be-gone
24/5 15:11 [31272] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-spam-be-gone
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-spam-be-gone
24/5 15:11 [31272] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-github-embed
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-github-embed
24/5 15:11 [31272] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-widget-essentials
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
24/5 15:11 [31272] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-chat-emote
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-chat-emote
24/5 15:11 [31272] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-custom-mentions
24/5 15:11 [31272] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-custom-mentions
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-custom-mentions
24/5 15:11 [31272] - verbose: [plugins] Found 2 css file(s) for plugin nodebb-plugin-carousel
24/5 15:11 [31272] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-carousel
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-carousel
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-outside
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-secure-images
24/5 15:11 [31272] - warn: [plugins.reload] Library not found for plugin: nodebb-plugin-code-button
24/5 15:11 [31272] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-code-button
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-code-button
24/5 15:11 [31272] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-desktop-notifications
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-desktop-notifications
24/5 15:11 [31272] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-video
24/5 15:11 [31272] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-mentions
24/5 15:11 [31272] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-mentions
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-google
24/5 15:11 [31272] - warn: [plugins.reload] Library not found for plugin: nodebb-plugin-vibration-notifications
24/5 15:11 [31272] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-vibration-notifications
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-vibration-notifications
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-facebook
24/5 15:11 [31272] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-emoji-extended
24/5 15:11 [31272] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-emoji-extended
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-github
24/5 15:11 [31272] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-markdown
24/5 15:11 [31272] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-markdown
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-emailer-mailgun
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-rss
24/5 15:11 [31272] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-buzzer
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-buzzer
24/5 15:11 [31272] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-coub
24/5 15:11 [31272] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-coub
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-twitter
24/5 15:11 [31272] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-google-adsense
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-google-adsense
24/5 15:11 [31272] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-imgshow
24/5 15:11 [31272] - verbose: [plugins] Found 3 js file(s) for plugin nodebb-theme-lavender
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-location-to-map
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-codepen
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-imgur
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-google-spreadsheet
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-dbsearch
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-dailymotion
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-video
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-jsfiddle
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-extended
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-coub
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-plugin-imgshow
24/5 15:11 [31272] - verbose: [plugins] Loaded plugin: nodebb-theme-lavender
24/5 15:11 [31272] - info: [plugins/spam-be-gone] Settings loaded
24/5 15:11 [31272] - verbose: [hotswap] Router with id `plugins` replaced successfully
24/5 15:11 [31272] - verbose: [plugins] All plugins reloaded and rerouted
24/5 15:11 [31272] - info: [plugins] Plugins OK
24/5 15:11 [31272] - verbose: [meta/css] Minifying LESS/CSS
24/5 15:11 [31272] - warn: [meta/css] File not found! nodebb-plugin-chat-emote/style.css
24/5 15:11 [31272] - warn: [meta/css] File not found! nodebb-plugin-buzzer/css/style.css
24/5 15:11 [31272] - verbose: [hotswap] Router with id `auth` replaced successfully
24/5 15:11 [31272] - verbose: [sounds] Sounds OK
24/5 15:11 [31272] - verbose: [meta/css] admin.css committed to disk.
24/5 15:11 [31272] - verbose: [meta/css] stylesheet.css committed to disk.
24/5 15:11 [31272] - verbose: [meta/templates] Compiling templates
24/5 15:11 [31272] - verbose: [meta/templates] Successfully compiled templates.
24/5 15:11 [31272] - error: Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at module.exports.listen (/home/kacemlight/nodebb/src/webserver.js:139:18)
    at /home/kacemlight/nodebb/node_modules/async/lib/async.js:656:23
    at fn (/home/kacemlight/nodebb/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/home/kacemlight/nodebb/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at module.exports.listen (/home/kacemlight/nodebb/src/webserver.js:139:18)
    at /home/kacemlight/nodebb/node_modules/async/lib/async.js:656:23
    at fn (/home/kacemlight/nodebb/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/home/kacemlight/nodebb/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
24/5 15:11 [31272] - error: NodeBB address in use, exiting...
[cluster] Child Process (31272) has exited (code: 0, signal: null)

**Comment by kacemlight** [comment]
The error i get on the client side : 
Uncaught ReferenceError: require is not defined(anonymous function) @ (index):36
The function : 
<script>
		require.config({
			baseUrl: "/src/modules",
			waitSeconds: 3,
			urlArgs: "v0.6.1",
			paths: {
				'forum': '../forum',


And on the admin panel nothing work : 

![image](https://cloud.githubusercontent.com/assets/10455208/7789239/0914ebf4-025a-11e5-81f7-092a7e4eb926.png)

**Comment by kacemlight** [comment]
And on the admin panel nothing work : 

![image](https://cloud.githubusercontent.com/assets/10455208/7789239/0914ebf4-025a-11e5-81f7-092a7e4eb926.png)

**Comment by kacemlight** [comment]
Please how can I fix this problem.. You can see how the situation is very critical by visiting my site : nodejsworld.com

**Comment by julianlam** [comment]
EADDRINUSE means that you already have NodeBB running. Use `ps` utility to find and kill it.

**Comment by kacemlight** [comment]
Please how to kill it .. And I don't know or understand how to do it ?

**Comment by kacemlight** [comment]
this is what i get with ps 
kacemlight@nodebb:~/nodebb$ ps
  PID TTY          TIME CMD
31159 pts/0    00:00:00 bash
32410 pts/0    00:00:00 ps

**Comment by Radiergummi** [comment]
`ps aux|grep nodebb`, then note the process Id and use `kill -9 <said id>`

kacemlight <notifications@github.com> schrieb am So., 24. Mai 2015 um 22:42:

**Comment by kacemlight** [comment]
Doesn't work ?

kacemlight@nodebb:~/nodebb$ ps aux|grep nodebb
1000      1464  0.0  0.1   4388   820 pts/0    S+   17:45   0:00 grep --color=auto nodebb
kacemlight@nodebb:~/nodebb$ kill -9 1000
-bash: kill: (1000) - No such process
kacemlight@nodebb:~/nodebb$ kill -9 4388
-bash: kill: (4388) - No such process
kacemlight@nodebb:~/nodebb$ kill -9 1464
-bash: kill: (1464) - No such process
kacemlight@nodebb:~/nodebb$ kill -9 820
-bash: kill: (820) - No such process
kacemlight@nodebb:~/nodebb$ kill 1000
-bash: kill: (1000) - No such process


Or I did it wrong ?

**Comment by kacemlight** [comment]
I found this https://github.com/NodeBB/NodeBB/issues/2572

It's the same problem that showed on the client side. But no one gave the solution.

**Comment by kacemlight** [comment]
I solve the EADDRINUSE problem but my site don't work properly, because I always have the js Jquery problem like it 's described in this issue https://github.com/NodeBB/NodeBB/issues/2572 : .

Please can someone tell me how can we resolve this problem ?!!

 I restar on dev mode : 

kacemlight@nodebb:~/nodebb$ ./nodebb dev
Launching NodeBB in "development" mode.
To run the production build of NodeBB, please use "forever".
More Information: https://docs.nodebb.org/en/latest/running/index.html

NodeBB v0.6.1 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

24/5 18:50 [3631] - info: Time: Sun May 24 2015 18:50:09 GMT-0400 (EDT)
24/5 18:50 [3631] - info: Initializing NodeBB v0.6.1
24/5 18:50 [3631] - verbose: * using configuration stored in: /home/kacemlight/nodebb/config.json
24/5 18:50 [3631] - verbose: * using redis store at 127.0.0.1:6379
24/5 18:50 [3631] - verbose: * using themes stored in: /home/kacemlight/nodebb/node_modules
24/5 18:50 [3631] - verbose: [plugins] Initializing plugins system
24/5 18:50 [3631] - info: Enabling 'trust proxy'
24/5 18:50 [3631] - verbose: [notifications.init] Registering jobs.
24/5 18:50 [3631] - info: [themes] Using theme nodebb-theme-lavender
24/5 18:50 [3631] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-youtube
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-youtube
24/5 18:50 [3631] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-google-analytics
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-google-analytics
24/5 18:50 [3631] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-codebender
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-codebender
24/5 18:50 [3631] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-spam-be-gone
24/5 18:50 [3631] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-spam-be-gone
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-spam-be-gone
24/5 18:50 [3631] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-github-embed
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-github-embed
24/5 18:50 [3631] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-widget-essentials
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
24/5 18:50 [3631] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-chat-emote
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-chat-emote
24/5 18:50 [3631] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-custom-mentions
24/5 18:50 [3631] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-custom-mentions
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-custom-mentions
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-outside
24/5 18:50 [3631] - verbose: [plugins] Found 2 css file(s) for plugin nodebb-plugin-carousel
24/5 18:50 [3631] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-carousel
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-carousel
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-secure-images
24/5 18:50 [3631] - warn: [plugins.reload] Library not found for plugin: nodebb-plugin-code-button
24/5 18:50 [3631] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-code-button
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-code-button
24/5 18:50 [3631] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-desktop-notifications
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-desktop-notifications
24/5 18:50 [3631] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-video
24/5 18:50 [3631] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-mentions
24/5 18:50 [3631] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-mentions
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-google
24/5 18:50 [3631] - warn: [plugins.reload] Library not found for plugin: nodebb-plugin-vibration-notifications
24/5 18:50 [3631] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-vibration-notifications
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-vibration-notifications
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-facebook
24/5 18:50 [3631] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-emoji-extended
24/5 18:50 [3631] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-emoji-extended
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-github
24/5 18:50 [3631] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-markdown
24/5 18:50 [3631] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-markdown
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-emailer-mailgun
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-rss
24/5 18:50 [3631] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-buzzer
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-buzzer
24/5 18:50 [3631] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-coub
24/5 18:50 [3631] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-coub
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-sso-twitter
24/5 18:50 [3631] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-google-adsense
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-google-adsense
24/5 18:50 [3631] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-imgshow
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-location-to-map
24/5 18:50 [3631] - verbose: [plugins] Found 3 js file(s) for plugin nodebb-theme-lavender
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-codepen
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-imgur
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-google-spreadsheet
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-dbsearch
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-dailymotion
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-video
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-jsfiddle
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-extended
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-coub
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-plugin-imgshow
24/5 18:50 [3631] - verbose: [plugins] Loaded plugin: nodebb-theme-lavender
24/5 18:50 [3631] - info: [plugins/spam-be-gone] Settings loaded
24/5 18:50 [3631] - verbose: [hotswap] Router with id `plugins` replaced successfully
24/5 18:50 [3631] - verbose: [plugins] All plugins reloaded and rerouted
24/5 18:50 [3631] - info: [plugins] Plugins OK
24/5 18:50 [3631] - verbose: [meta/css] Minifying LESS/CSS
24/5 18:50 [3631] - warn: [meta/css] File not found! nodebb-plugin-chat-emote/style.css
24/5 18:50 [3631] - warn: [meta/css] File not found! nodebb-plugin-buzzer/css/style.css
24/5 18:50 [3631] - verbose: [hotswap] Router with id `auth` replaced successfully
24/5 18:50 [3631] - verbose: [sounds] Sounds OK
24/5 18:50 [3631] - verbose: [meta/css] admin.css committed to disk.
24/5 18:50 [3631] - verbose: [meta/css] stylesheet.css committed to disk.
24/5 18:50 [3631] - verbose: [meta/templates] Compiling templates
24/5 18:50 [3631] - verbose: [meta/templates] Successfully compiled templates.
24/5 18:50 [3631] - info: NodeBB is now listening on: 0.0.0.0:4567
24/5 18:50 [3631] - verbose: [cluster] Stylesheets propagated to worker 3631

**Comment by julianlam** [comment]
This log looks fine.

As this is not a bug with NodeBB, please take this discussion to our community forum. Furthermore, as you are having trouble getting your instance set up and maintained properly, I would suggest using a hosted provider of NodeBB, so these aspects are handled by somebose else more familiar with the OS/software.

**Comment by kacemlight** [comment]
No I don't think it's related to the hosted provider. Please see this issue https://github.com/NodeBB/NodeBB/issues/2572  . It's the same problem and case.

**Comment by julianlam** [comment]
I suggested to USE a hosted provider for NodeBB.

**Comment by kacemlight** [comment]
I use DigitalOcean and it worked perfectly for a few months. I already have many of data on my web site that I don't wanna lose. I create post my problem on nodebb forum : https://community.nodebb.org/topic/4578/jquery-and-require-not-defined

**Comment by kacemlight** [comment]
This is the response of digitalocean my hosted provider about this issue : 

Hi there,

Sorry to hear you're having this problem. From my own testing, http://nodejsworld.com/ does seem to load and display properly[1], though I do see two "Uncaught ReferenceError: require is not defined" errors for lines 36 and 866 in your index file. The specifics might vary based on which libraries you're using, but one should provide the require function to resolve those error.

Since this is a code debugging issue, it might not be something that we can troubleshoot.
