### ISSUE TITLE
Site Theme Bug

### ISSUE THREAD

**Issue by abhiklodh** [NodeBB/NodeBB#3172]
I am using the persona theme on  NodeBB v0.7.0-dev  nd when i click on the site's Name (Logo or default NodeBB) 
![image](https://cloud.githubusercontent.com/assets/8018018/7784204/b32cf5e0-017a-11e5-8763-5cddd5c1e846.png)
 or AmpCruncherz here
It redirects to the same page(base url) with different theme
like this:
![image](https://cloud.githubusercontent.com/assets/8018018/7784224/93e301ce-017b-11e5-814f-5c445d9c5b9e.png)

Thnx ahead

**Comment by julianlam** [comment]
Have you restarted NodeBB completely (not just a reload) after changing the theme?

**Comment by abhiklodh** [comment]
I have restarted .... BTW this happens only on Google chrome 
Guess this is a caching issue
Running locally is okay

**Comment by julianlam** [comment]
Please let us know if the issue persists. Thanks!
