### ISSUE TITLE
Language ru error

### ISSUE THREAD

**Issue by codesoon** [NodeBB/NodeBB#3173]
file /public/language/ru/reset_password.json
5 str error: href=\"/login\\\"
fix: href=\"/login\"

**Comment by julianlam** [comment]
Hi there @codesoon, please fix this on the Transifex project for NodeBB :)

**Comment by codesoon** [comment]
@julianlam ok

**Comment by codesoon** [comment]
@julianlam in Transifex translate ok.

There: https://github.com/NodeBB/NodeBB/blob/master/public/language/ru/reset_password.json
This is not ok)

**Comment by codesoon** [comment]
@julianlam again: https://github.com/NodeBB/NodeBB/blob/master/public/language/ru/reset_password.json
