### ISSUE TITLE
Can't add users to group

### ISSUE THREAD

**Issue by Firelad97** [NodeBB/NodeBB#3175]
I already had posted here https://community.nodebb.org/topic/4554/unable-to-add-people-to-groups.

@barisusakli said he just fixed it and I just pulled and still not working. See screenshot in my post. (upper caps or lower caps does not matter)

**Comment by unek** [comment]
was just going to report this bug: upper case letters can't be used for some reason it the search, it will always say "No Users Found". Lower case letters work.

**Comment by Firelad97** [comment]
@unek Try pulling the latest commit. @barisusakli already fixed that.

**Comment by unek** [comment]
@Firelad97 I am on the latest commit, still not working for me.

**Comment by unek** [comment]
took a hard refresh to make it work.

**Comment by Firelad97** [comment]
Hey, reopen this please. I'm still having issue with it on newest branch, v0.7.0.

![image 1](http://i.imgur.com/YTFPHS5.png)
![image 2](http://i.imgur.com/jBQEUDT.png)

**Comment by NoodleBB** [comment]
It isn't fixed. The bug still exist. And the group-management is currently absolute *broken* because of that bug.

So, reopen that bug.

**Comment by Welcius** [comment]
I just did a fresh install of this release and the bug still exists

**Comment by barisusakli** [comment]
@Firelad97 does it work if you search for Magistar? What commit hash are you on?

**Comment by Firelad97** [comment]
Sorry I have no members anymore, but I can create new user and test this.

**Comment by agarcia17** [comment]
I'm having the same problem, whether i search for the exact username (case-sensitive) or not. this is with a fresh install from the master and 0.7 release.

**Comment by barisusakli** [comment]
@agarcia17 are you using redis? If so can you post the output of the following command.

```
redis-cli
zrange username:sorted 0 -1
```

**Comment by agarcia17** [comment]
@barisusakli sorry for the late reply but I actually installed a fresh copy of NodeBB today (0.7.x) and everything is working correctly now :)

**Comment by julianlam** [comment]
@Welcius @NoodleBB I've created a new install and tested, and user searching in the group mgmt modal is working fine here...

**Comment by Welcius** [comment]
@julianlam Installed v0.7.x again and works fine now!
