### ISSUE TITLE
Schema out up date, upgrading from v0.6.x to v0.7.x

### ISSUE THREAD

**Issue by sadtaco** [NodeBB/NodeBB#3177]
I just installed the latest nodebb 3 days ago and saw the 0.7 update.

I tried 
    git checkout v0.6.x
    node app --upgrade
    git checkout master
    ./nodebb upgrade

But I still get
    23/5 23:20 [16769] - error: [upgrade] NodeBB upgrade could not complete, as your database schema is too far out of date.
    23/5 23:20 [16769] - error: [upgrade]   Please ensure that you did not skip any minor version upgrades.
    23/5 23:20 [16769] - error: [upgrade]   (e.g. v0.1.x directly to v0.3.x)

**Comment by julianlam** [comment]
@sadtaco Hm. Are you using mongo or redis?

**Comment by julianlam** [comment]
Nevermind, we fixed it. Can you please pull the latest commit from `v0.7.x` again?

**Comment by sadtaco** [comment]
I was using redis.

And yes either you fixed it, or me using "./nodebb upgrade" after "git checkout v0.6.x" instead of just "node app --upgrade" fixed it. Works now!

**Comment by julianlam** [comment]
Great, thanks for the update :smile:
