### ISSUE TITLE
Transition to the web installer

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3178]
Now that v0.7.0 is out, we're doubling down on the web installer. :smile: 

Currently there are multiple ways to set up NodeBB:
1. Interactive installer (e.g. `./nodebb setup`)
2. Environment variables (e.g. `database=mongo url=mysite.com mongo__database=mysite node app --setup`)
3. Web installer

The third is new, and I'd like to simultaneously have #3 be the official method, while deprecating #1, the interactive installer. (#3 uses #2 behind the scenes)

So the following needs to be done:
* [x] Documentation needs to be updated so `npm start` is called instead of `./nodebb setup`
    * [ ] @NodeBB/documentation-translation-team needs to update their respective documentation translations as well, once this is complete
* [x] Possibly add a screenshot of the web installer to the readme
* [ ] ~~Update behaviour of `./nodebb setup` so that if it does not have enough info to configure NodeBB, it launches the web installer instead of the interactive installer~~
* [ ] ~~Remove deprecated interactive installer code~~

**Comment by Firelad97** [comment]
Web installer does not work with Openshift, so I will have to write new config.json so I can start setup.

**Comment by julianlam** [comment]
The web installer actually writes the `config.json` file for you, and starts (and binds to port 4567) if the config file isn't found, so hopefully you'll be able to have OpenShift work with the web installer :smile: 

Just call `node loader.js` or `npm start`. Depending on whether a `config.json` exists, either NodeBB will start, or the web installer will.

**Comment by Firelad97** [comment]
Nope, web installer does not start when I executed `npm start`. I got errors, and my port is different, so that's why. Also when I wrote the new config.json, and executed `npm start`, I got errors too. Don't know why.

Is it possible to still use interactive installer?

**Comment by psychobunny** [comment]
This is probably an issue for itself, but add it to the list - i8n for web installer

**Comment by Firelad97** [comment]
I don't understand what you mean. So far I know is that web installer does not work with Openshift. Interactive installer is needed very much for Openshift.

**Comment by psychobunny** [comment]
Sorry! I was speaking to @julianlam in that reply

I think you can have the web installer listen to a custom port via something like

`npm start -- --port=xyz`

Not sure if that would help your scenario

**Comment by Firelad97** [comment]
@psychobunny That does not work...

**Comment by MegaGM** [comment]
Don't kill Interactive installer please! Keep it. ![](http://smayly.ru/gallery/anime/RedFox/5.gif)

**Comment by MegaGM** [comment]
Don't kill Interactive installer, please! Keep it. ![](http://smayly.ru/gallery/anime/RedFox/5.gif)

**Comment by Firelad97** [comment]
I second this! :sob:

**Comment by julianlam** [comment]
Wow, you guys really like the interactive installer huh?

**Comment by MegaGM** [comment]
@julianlam Definitely. I even think it's much more handy than web installer.

**Comment by unixfox** [comment]
@julianlam I prefer the interactive installer.

**Comment by julianlam** [comment]
It seems the public has spoken, the interactive installer shall stay :smile:

**Comment by Firelad97** [comment]
Yay!
