### ISSUE TITLE
Strange Startup

### ISSUE THREAD

**Issue by Firelad97** [NodeBB/NodeBB#3180]
When v0.7.0 is out, and @psychobunny say I should try `npm start -- --port=xyz`... Well, it does not work. So instead I've tried `-- --port:xyz`, `-- port:xyz`, and `-- port=xyz`. Neither works.

However `-- --port:xyz` does work - but all I got was a strange line: `24/5 02:48 [409906] - info: NodeBB is now listening on: [object Object]`

It's supposed to be listening on `[http://www.mysite.com/]` or something, not `[object Object]`.

This never happens before v0.7.0 (excluding v0.7.0-dev).

EDIT: I mean this only occurs when doing a clean new install.

**Comment by julianlam** [comment]
What are you trying to do?

**Comment by Firelad97** [comment]
I was trying to do a clean and new install.

**Comment by Firelad97** [comment]
I possibly found a workaround for this. Closing, if that's alright.
