### ISSUE TITLE
style error in v0.7.x

### ISSUE THREAD

**Issue by nemoxiaolan** [NodeBB/NodeBB#3181]
I'm using nodebb 0.7.x, and when I enter a post, I got the page style like:
![image](https://cloud.githubusercontent.com/assets/4438542/7787697/531d1810-024c-11e5-8afe-076ba5d44c0e.png)

when I refresh the page, everything be ok. what's wrong? 

webserver: nginx 1.6.0
database: mongodb 2.6.0
webbrower: chrome 43.0.xxxx

**Comment by psychobunny** [comment]
Are both Lavender and Vanilla themes up to date? 

If they are, can you try switching your theme to vanilla, restart, and then switch back to lavender and restart?

**Comment by julianlam** [comment]
This seems to be a caching problem. Let us know if it persists and we'll re-open.
