### ISSUE TITLE
Can't stop dragging widget

### ISSUE THREAD

**Issue by Firelad97** [NodeBB/NodeBB#3183]
Without development mode, I can drag and drop widgets, but when in development mode, I can't stop dragging. It is stuck on mouse.

EDIT: Just turned off development mode and still can't stop dragging widget.

**Comment by psychobunny** [comment]
Is there any errors in the console when you start dragging?

**Comment by Firelad97** [comment]
Sorry, it was an issue with Openshift. Might because of outdated NodeJS and database. I'm upgrading both and sees what will happen.

**Comment by psychobunny** [comment]
Cool, let me know if it still persists. I couldn't reproduce - closing for now
