### ISSUE TITLE
collapse characters for mention autocomplete

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#3185]
I don't know how feasible this is, but just putting this here to bring attention to it, and for better i18n support...

I noticed that when I tried to @mention a user with an 'é' character by typing a normal 'e', it doesn't show up:
![image](https://cloud.githubusercontent.com/assets/4553795/7806028/a8036192-0330-11e5-9eba-3286f88d9e93.png)

But, if I can type the accented character (a la holding down the 'e' key on OSX):
![image](https://cloud.githubusercontent.com/assets/4553795/7806036/bb8abf08-0330-11e5-9afe-c8a0226719e9.png)

**Comment by julianlam** [comment]
Hm, this may be tricky to do well, as we'd have to bundle in a module that converted accented characters to their non-accented equivalents for searching purposes.

Then you go outside of the realm of latin-root languages, and we will need to consider whether we need to handle romanised version of Chinese/Japanese/Korean/etc as well...! :laughing:

**Comment by bdharrington7** [comment]
Yeah I know it can be tricky, but it's analogous to how search analysis works, maybe this would be useful? http://stackoverflow.com/a/23688057/1827734

Since NodeBB supports usernames with non-ascii characters, there needs to be some sort of baseline where we can match a name, no?

just off the top of my head, if you decide to implement something like this, it would have to be processed, and then stored, but then also process whatever the user is typing too, so that has to be taken into consideration

**Comment by bdharrington7** [comment]
Oh maybe this is supposed to go in nodebb-plugin-mentions, forgot that was a plugin

**Comment by bdharrington7** [comment]
Moved to https://github.com/julianlam/nodebb-plugin-mentions/issues/66
