### ISSUE TITLE
Groups page doesn't display groups when sort order is changed

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3186]
Groups page doesn't display groups when sort order is changed

**Comment by pichalite** [comment]
![screen shot 2015-05-26 at 3 35 04 pm](https://cloud.githubusercontent.com/assets/10014774/7810087/d6c1d7f2-03bc-11e5-8de2-b4061aa35f2c.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/4420e7a9fcf4518e1d7d0357126ec67c46e462a9
