### ISSUE TITLE
public/less/admin/manage/groups.less doesn't exist anymore

### ISSUE THREAD

**Issue by Alpacatty** [NodeBB/NodeBB#3188]
yet https://github.com/NodeBB/NodeBB/blob/master/public/less/admin/admin.less still imports it.

**Comment by julianlam** [comment]
Didn't we fix this...

**Comment by Alpacatty** [comment]
@julianlam it looks like due to some git weirdness the only change actually pulled in with 03bc31706578fa2534bdf98e5f9609b62806b4e0 was the deletion of groups.less, not all of the other stuff that is there when looking through the recent commit history, such as the deletion of references to said groups.less :persevere:

**Comment by julianlam** [comment]
Yeah, "git weirdness" is right. There was a merge conflict between @barisusakli and myself, and GitHub for Windows decided to force push my changeset to `/dev/null`. Still scratching my head on that one.
