### ISSUE TITLE
Searching breaks links in result

### ISSUE THREAD

**Issue by henrikekblad** [NodeBB/NodeBB#3194]
If a search is performed which hits an url. The link (or image) will be corrupted when <bold> </bold> tags is inserted.

Example: Search for "amazon" on NodeBB forum and look at the fourth result.

**Comment by barisusakli** [comment]
I think @psychobunny fixed this for images in https://github.com/NodeBB/NodeBB/commit/b96018b0f555b98dd519382419ccf781a3b89778 links are probably still broken.

**Comment by henrikekblad** [comment]
Still breaks image-urls inserted by plugin in normal priority.

**Comment by henrikekblad** [comment]
I can confirm that it works now. Thanks!
