### ISSUE TITLE
Rendering templates via /api/widgets/render

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3196]
Seems, does not work with [template.js helpers](https://github.com/psychobunny/templates.js#helpers).

**Comment by psychobunny** [comment]
Missed this, what's the issue exactly, can you give me an example of what you're trying to do?

**Comment by NicolasSiver** [comment]
As I remember:

- I have declared helper, and it works ok if you refresh page
- but when you navigate ACP, helpers aren't invoked.

**Comment by psychobunny** [comment]
Hey, made a few changes in both acp and tjs since then, sorry for the late follow up. Are you still having this problem? If you are can you post the code

**Comment by NicolasSiver** [comment]
Consider closed ;)
I will reopen, if will find the same problem again.
