### ISSUE TITLE
Heroku Hosting Issue

### ISSUE THREAD

**Issue by abhiklodh** [NodeBB/NodeBB#3197]
I tried 2 host nodebb on heroku after following the docs but failed badly.
entering all information corectly (yup, i double checked it) after running node app --setup came up with this message (a life threatning error)

pls help me get this thing right :)

```
30/5 12:36 [2633] - info: NodeBB v0.7.1-dev Copyright (C) 2013-2014 NodeBB Inc.
30/5 12:36 [2633] - info: This program comes with ABSOLUTELY NO WARRANTY.
30/5 12:36 [2633] - info: This is free software, and you are welcome to redistribute it under certain conditions.
30/5 12:36 [2633] - info: 
30/5 12:36 [2633] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://ampcruncherz.herokuapp.com) 
Please enter a NodeBB secret (xyz) 30/5 12:36 [2633] - warn: Couldn't find convert. Did you install imagemagick?

Which database to use (redis) 

30/5 12:36 [2633] - info: Now configuring redis database:
Host IP or address of your Redis instance (127.0.0.1) redis://redistogo:thepassword@hammerjaw.redistogo.com:10458/
Host port of your Redis instance (6379) 10458
Password of your Redis database *its magic*
Which database to use (0..n) (0) 
Configuration Saved OK

npm WARN package.json nodebb@0.7.1-dev No README data
npm WARN package.json nodebb@0.7.1-dev license should be a valid SPDX license expression


redis@0.10.3 node_modules/redis

connect-redis@2.0.0 node_modules/connect-redis
└── debug@2.2.0 (ms@0.7.1)
Populating database with default configs, if not already set...
30/5 12:36 [2633] - warn: NodeBB Setup Aborted.
 undefined
```

**Comment by psychobunny** [comment]
> Please enter a NodeBB secret (xyz) 30/5 12:36 [2633] - warn: Couldn't find convert. Did you install imagemagick?

This sounds ominous. Wonder why that warning appeared in the middle of setup...

**Comment by xke** [comment]
Just as another data point: I was able to complete the instructions in the thorough documentation (yay!). However, when I went to the URL of the deployed Heroku app, the application crashed on me. :(

**Comment by abhiklodh** [comment]
The problem is with the last line i guess which says the setup is aborted ......undefined .
I can't see the issue as the repo can be hosted on c9 and also locally.

**Comment by julianlam** [comment]
Let us know if this is still an issue for you guys :smile:

**Comment by abhiklodh** [comment]
Just to inform u awesome guys out there! ...it's still not working yet
I can host it on amazon but don't wanna spend money as my first year has finished I kinda liked heroku.
Hope we get a solution.

**Comment by Jdesk** [comment]
i'm curious what the outcome was - i'm attempting to install within a docker container - same issue.
