### ISSUE TITLE
User search broken [0.7.0]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#3201]
When using a User search field you, don't get a search result, but an error box with the message:
``ERR unknown command 'zrangebylex'``

I appears in the forum search and in the admin page. Group handling is currently impossible because of that problem.

![](https://i.imgur.com/vsUAZ5Z.png)
![](https://i.imgur.com/Kylmsrk.png)

https://community.nodebb.org/topic/4632/user-search-broken-0-7-0

This is a follow up of the bug: https://community.nodebb.org/topic/4554/unable-to-add-people-to-groups

**Comment by julianlam** [comment]
Please upgrade redis to > 2.8

**Comment by NoodleBB** [comment]
Can't update to redis

**Comment by NoodleBB** [comment]
Those guys have the same problem: 
https://community.nodebb.org/topic/4554/unable-to-add-people-to-groups
