### ISSUE TITLE
HTML support for the description of Category

### ISSUE THREAD

**Issue by haoweilee** [NodeBB/NodeBB#3209]
When I use HTML code in the category description, it seems very nice in ACP, but it displayed all HTML code on the index page of the community.  Am I wrong?

**Comment by julianlam** [comment]
Hm, category description is parsed as post, right? So it should not allow html unless markdown plugin allows it

**Comment by pitaj** [comment]
It is showing the HTML code because it automatically escapes all `<` and `>` characters as their HTML equivalents. This is to prevent XSS. I do think this brings up a good point though. Maybe a preview should be available for the ACP category description thing.
