### ISSUE TITLE
[Help] API Endpoint to create a new user

### ISSUE THREAD

**Issue by trigun0x2** [NodeBB/NodeBB#3211]
Hi, I searched through the issues and Wiki but couldn't quite find an answer.

I'd like to create a new user in NodeBB as a callback from another application. I'm just wondering if I can do this right now or if I'd have to create a plugin of sorts.

Thanks!

**Comment by julianlam** [comment]
Please investigate using the write api for this :smile:

https://github.com/NodeBB/nodebb-plugin-write-api
