### ISSUE TITLE
Templating Engine

### ISSUE THREAD

**Issue by manolino** [NodeBB/NodeBB#3214]
As in Template basics (https://docs.nodebb.org/en/latest/themes/templates.html) all data returned by the API call can be used as template variable:

```html
<h3>User ID: {uid}</h3>

<p>{posts.contents}</p>
```
But what if you need to access an array element? For example to show, in `topic.tpl`, the name of a group the user is part of, but outside `<!-- BEGIN groups -->....<!-- END groups -->` tags, using: 
```html
<h4>Member of posts.user.groups[0].name</h4>
```
I created a custom post field tha contains an array. No errors from templating engine but templating can't resolve my custom field:
```html
<b>Temperature:{posts.mycustomfield[0]}</b>
```

**Comment by psychobunny** [comment]
There are a few ways of doing it, simplest way in your case is using `@first` or `@last`.

Example:

Data:

```
{
  posts: [
    {
      name: "test"
    }
  ]
}
```

(ie. `posts[0].name === 'test'`)

Template:

```
<!-- BEGIN posts -->
<!-- IF @first -->Name: {name}<!-- ENDIF @first -->
<!-- END posts -->
```

More complicated ways include using helpers, but in that case maybe it might just be better to refactor the data you pass in.

If you have any further questions please post on the template [repo instead](https://github.com/psychobunny/templates.js/issues/) :)
```
