### ISSUE TITLE
parse.post vs parse.raw

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#3215]
You use parse.post [here](https://github.com/NodeBB/NodeBB/blob/e75ec97049755d0f41e3657b2ec1735334a0abf7/src/posts/parse.js#L23)

And use parse.raw [here](https://github.com/NodeBB/NodeBB/blob/0e9a096c259b2190481dbe86dc231fac70825db9/src/socket.io/modules.js#L84)

Should I hook into both when I set up post parsing so the preview works right, or just one. Shouldn't the preview use `parse.post` to be accurate?

**Comment by julianlam** [comment]
@barisusakli would have a better idea, although I agree that the post preview should be parsed the same way...

**Comment by barisusakli** [comment]
Yeah agreed I think the only reason its not is because we only have content at that point and no real post data to pass to the hook. Although I don't think parse.post hook uses anything other than postData.content

**Comment by julianlam** [comment]
Hm, if `parse.post` sends more than just the content in, then it's probably a good idea to leave it as is, otherwise we'd run into issues where some plugins *expect* `uid` and the other arguments, whereas others just work on `content`...

RFC?

**Comment by pitaj** [comment]
How about this: `parse.raw` is used on the post content before `parse.post`
Something like this:
```
plugins.fireHook('filter:parse.raw', postData.content, function(err, parsedContent) {
  if (err) {
    return callback(err);
  }
  postData.content = parsedContent;
  plugins.fireHook('filter:parse.post', {postData: postData}, function(err, data) {
    if (err) {
      return callback(err);
    }
    cache.set(data.postData.pid, data.postData.content);

    callback(null, data.postData);
  });
});
```

**Comment by barisusakli** [comment]
To answer the original question.

>Should I hook into both when I set up post parsing so the preview works right, or just one. Shouldn't the preview use parse.post to be accurate?

Yes the preview uses parse.raw. And only has access to the content that the user has typed in.

So right now you need to hook in to both.
