### ISSUE TITLE
"Log in to post" button does not follow the correct URL

### ISSUE THREAD

**Issue by VincentTide** [NodeBB/NodeBB#3216]
During initial forum setup for version 0.7.0, I have the access url pointing to a subfolder like `http://example.com/forum`
Most links correctly append the /forum/ to the URL such as `example.com/forum/recent`

This does not work for the "Log in to post" button, it is using the URL `http://example.com/login?next=category/2/general-discussion` 

The expected URL should be `http://example.com/forum/login?next=category/2/general-discussion`

The "Log in to post" button needs to append the correct subfolder `/forum/` to the URL.

**Comment by julianlam** [comment]
A couple of issues here.

1. [ ] The `next` query string doesn't seem to be supported, so that needs to be removed
1. [ ] The buttons themselves don't point to the correct page in a subfolder install

**Comment by julianlam** [comment]
Seems clicking user avatars in chat didn't work either, so that's fixed up :+1:, thanks for reporting!

**Comment by VincentTide** [comment]
Hey Julian,

I upgraded nodebb-theme-persona to 0.1.61, which should be the bugfixed version, however this error is still there. 

Should upgrading to persona 0.1.61 fix this or do I have to wait for nodebb 0.7.1?

**Comment by VincentTide** [comment]
Ok so it is working now. I had restarted my server and node multiple times but the old bugged URL was still showing up. Apparently, it needed a browser cache refresh to get the correct URL to show.

**Comment by julianlam** [comment]
> Apparently, it needed a browser cache refresh to get the correct URL to show.

:+1: Good to know, thanks for the confirmation @VincentTide :smile:
