### ISSUE TITLE
Group label for pre-upgrade users

### ISSUE THREAD

**Issue by dstate** [NodeBB/NodeBB#3221]
Hello,
Apparently, after the upgrade to 0.7.0 with the new persona theme, the group labels are not showing for the members having joined the groups before the upgrade, but they are showing for the ones that are actually joining after this upgrade.

**Comment by Fusselwurm** [comment]
which group label is being shown is actually now part of the user's preferences (!).
it's not set during the upgrade.

**Comment by julianlam** [comment]
Yes, @Fusselwurm is correct. We were not setting the value prior to v0.7.x, but we are now, so this is a user-centric setting, that they can choose in their profile :smile:
