### ISSUE TITLE
Single quote in User Name issue

### ISSUE THREAD

**Issue by skoma** [NodeBB/NodeBB#3224]
If you create a user with a single quote in his name (User With'Quote)
the layout will not load fully and the user is not able to post nor to replay.

[edit]
nodebb version: v0.7.0

I'm also not sure anymore about the quotes, might also be a problem with the minifier.
Firefox works, but chrome now says:

Uncaught SyntaxError: Unexpected token <                    nodebb.min.js?0e948bbe:13

Renaming the user helps temporary. After next Login the issue returns.

**Comment by julianlam** [comment]
Hi there, this should be fixed on the latest commits to master. What hash are you on?

**Comment by skoma** [comment]
Hi julianlam,
thank you for the quick reply.
I'm on the v0.7.0 tag right now. Tomorrow I will try again on master.

**Comment by julianlam** [comment]
@skoma We could backport that change to v0.7.x I think...

**Comment by skoma** [comment]
Hi Julian,

I manged to upgrade nodebb to master (29c9b2e) but I get still SyntaxError in chrome:

Uncaught SyntaxError: Unexpected token <
define	@	nodebb.min.js?9e14d97d:8
(anonymous function)	@	nodebb.min.js?9e14d97d:9
(anonymous function)	@	nodebb.min.js?9e14d97d:9
nodebb.min.js?9e14d97d:8

Uncaught SyntaxError: Unexpected token ILLEGAL
k.execCb	@	nodebb.min.js?9e14d97d:8
x.check	@	nodebb.min.js?9e14d97d:8
x.enable	@	nodebb.min.js?9e14d97d:8
k.enable	@	nodebb.min.js?9e14d97d:8
(anonymous function)	@	nodebb.min.js?9e14d97d:8
e	@	nodebb.min.js?9e14d97d:8
z	@	nodebb.min.js?9e14d97d:8
x.enable	@	nodebb.min.js?9e14d97d:8
x.init	@	nodebb.min.js?9e14d97d:8
g	@	nodebb.min.js?9e14d97d:8
k.completeLoad	@	nodebb.min.js?9e14d97d:8
k.onScriptLoad	@	nodebb.min.js?9e14d97d:8

**Comment by skoma** [comment]
duplication of #3200
