### ISSUE TITLE
Not new posts

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3227]
If post created in the category above 3 level in all parents category not can get him, why?

**Comment by atomoc** [comment]
Or it refers to theme persona?

**Comment by atomoc** [comment]
I updated all to last versions: no results.

**Comment by atomoc** [comment]
**No problem:**
Category - sergej 5 days ago
No posts in this category
-- Subcategory - sergej 5 days ago
No posts in this category
---- Subdirectory - sergej 5 days ago
Post created by sergej 5 days ago

**Problem:**
Category - **No new posts**!! (why?)
No posts in this category
-- Subcategory - **No new posts**!! (why?)
No posts in this category
---- Subdirectory - sergej 5 days ago
No posts in this category
------ Subdirectory
Post created by sergej 5 days ago

Do you understand everything?

**Comment by psychobunny** [comment]
Do you have a demo up online so we can look / screenshots? I'm not 100% following what you mean

**Comment by atomoc** [comment]
**Problem:**
1. Home page:
![2015-06-17 11 12 43](https://cloud.githubusercontent.com/assets/465108/8202650/9ef4e90c-14e4-11e5-9fc5-8d9760224b3b.png)
2. Category:
![2015-06-17 11 12 56](https://cloud.githubusercontent.com/assets/465108/8202654/a41ef080-14e4-11e5-916c-f8a2bf674aae.png)
3. Subcategory:
![2015-06-17 11 13 09](https://cloud.githubusercontent.com/assets/465108/8202656/a9459b04-14e4-11e5-9ed0-c3a0784d9de7.png)
4. Category subcategory:
![2015-06-17 11 13 31](https://cloud.githubusercontent.com/assets/465108/8202658/ae9140fe-14e4-11e5-838b-1310006744b4.png)

**Comment by Fusselwurm** [comment]
The "new posts" preview (teaser) does not include new posts from subcategories.

**Comment by atomoc** [comment]
Please do not say what you do not know. That true for subcategory deeper than the third level.

**Comment by Fusselwurm** [comment]
@atomoc I was merely trying to re-state the problem you found as I understood it and as I have found it in my own nodebb instance.

**Comment by atomoc** [comment]
Thanks

**Comment by Fusselwurm** [comment]
I do have a similar problem, and I'm not having 3 levels of subcategories, but only 2 ... will need to investigate a bit.

**Comment by atomoc** [comment]
Strangely, I have checked several times. I am now even make a screencast of this test.

**Comment by atomoc** [comment]
**2 level not problems:**
1. Home page:
![2015-06-17 12 27 16](https://cloud.githubusercontent.com/assets/465108/8203777/ec72dc40-14ec-11e5-9dfb-d69f3beddeb3.png)
2. Category:
![2015-06-17 12 27 41](https://cloud.githubusercontent.com/assets/465108/8203782/f497cb24-14ec-11e5-948e-ff0d12a2f60e.png)
3. Subcategory:
![2015-06-17 12 28 11](https://cloud.githubusercontent.com/assets/465108/8203788/fbcf8116-14ec-11e5-8f27-b3dfeaf98148.png)

**Comment by XenTerSeO** [comment]
@barisusakli I think it still has problems.

![10](https://cloud.githubusercontent.com/assets/10964696/9380387/8dab5bd2-4738-11e5-854a-095a76a88832.png)

![11](https://cloud.githubusercontent.com/assets/10964696/9380406/a03e6abe-4738-11e5-8325-c25bf21ff0dd.png)


![12](https://cloud.githubusercontent.com/assets/10964696/9380391/9378d77e-4738-11e5-9def-b24aa7f82ca0.png)

**Comment by XenTerSeO** [comment]
@barisusakli Hey, man! It is still not working.

**Comment by psychobunny** [comment]
Did you upgrade templates.js?

**Comment by XenTerSeO** [comment]
@psychobunny Yes. Templates.js: 0.2.10
