### ISSUE TITLE
Long loading compose page

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3229]
On mobile when creating posts a delay response page at the same time to see what is written there is no possibility. At the time of loading in the console displays an error:
```
WebSocket connection to 'ws://mysite.com/forum/socket.io/?EIO=3&transport=websocket&sid=0wAK0fs4fsdf36i6AAAL' failed: Error during WebSocket handshake: 'Connection' header value must contain 'Upgrade'
```
Then page hangs, as previously mentioned.

Maybe the problem is the existence of a significant number of categories?

**Comment by atomoc** [comment]
I removed everything that is connected with categoryList in composer.js, I do not need it. Thanks!

**Comment by psychobunny** [comment]
see #3237
