### ISSUE TITLE
Safer Upgrades

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3236]
I propose the following changes:

* When upgrading a NodeBB, all active plugins and themes should have their compatibility value checked, and disabled if incompatible
    * Upside: Fewer broken upgrades
    * Downside: More installs would boot up again running vanilla/persona, with many plugins disabled
* Toggling active state of a plugin should do a compatibility check just like the install step

**Comment by psychobunny** [comment]
How do we deal with people on bleeding edge builds? If you remember the weeks leading up to the 0.7 release, pretty much every plugin was throwing a warning on startup about incompatibility

**Comment by Alpacatty** [comment]
@psychobunny maybe a small interactive menu reading something like "Several installed plugins are incompatble. Start NodeBB anyway? yes/no/manual" (with ofc. command-line flags to bypass that, i.e. `-y` `-n` to force-yes or force-no)
(manual allowing you to disable plugins on a plugin-by-plugin basis)

**Comment by julianlam** [comment]
We took a step towards this by doing a version check for any plugins listed in `package.json`. So at the very least a bundled plugin that is out of date would cause NodeBB to not start.
