### ISSUE TITLE
Category selector for composer

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3237]
https://github.com/NodeBB/NodeBB/issues/3229

Perhaps this could be changed to some sort of infinite scrolling dropdown. AFAIK there is no open source library for this so we'd have to write it from scratch unless somebody has a better idea

p.s - I don't think a standalone autocomplete would work very well in this scenario, although it could work in combination. Again, has to be written from scratch.

**Comment by pitaj** [comment]
I think something like a typeahead would work better, maybe with a dropdown that shows the most used groups

**Comment by psychobunny** [comment]
I think this is okay for 99% of use cases, the user that had a billion categories was a one off (and he fixed his issue by removing the drop down altogether). Pls comment if anyone disagrees, will reopen.

**Comment by pitaj** [comment]
@psychobunny on the closing shift, I see

**Comment by psychobunny** [comment]
Haha wow. I've been doing this for over an hour apparently lol
