### ISSUE TITLE
Custom avatar does not work

### ISSUE THREAD

**Issue by Tjatse** [NodeBB/NodeBB#3241]
For example, I am serving nginx with custom domain:
- ip  `192.168.100.130`
- port `8001`
- domain `example.com`

I uploaded a  custom avatar, the url is totally wrong:
```
http://i1.wp.com/192.168.100.130/uploads/system/gravatar-default.png`
```
It should be:
````
http://example.com/uploads/system/gravatar-default.png
```
or
````
http://192.168.100.130:8001/uploads/system/gravatar-default.png
```

**Comment by pitaj** [comment]
Do you have the correct url and everything set up in the `config.json`?

**Comment by Tjatse** [comment]
@pitaj After updated the `url` from `http://192.168.100.130:8001` to `http://example.com` manually,  It works like a charm. thanks a lot, dude.
