### ISSUE TITLE
Digest urls issues

### ISSUE THREAD

**Issue by slvlirnoff** [NodeBB/NodeBB#3257]
Hi there, 

After more testing with digests I've found the following issues:
settings link not working (non slug version of user name)
Notification link not working (relative path duplicated,  e.g. /forums/forums/topic...)

**Comment by slvlirnoff** [comment]
Oops submitted too quickly (mobile)

New/Recent topics link are fine but topic pictures are not (missing host name from url, e.g. http:///forums/Img...) probably only affect author with uploaded profile picture. 

Best,
Cyprien

**Comment by slvlirnoff** [comment]
Previous issue #3220

**Comment by barisusakli** [comment]
Seems like this is already fixed on master but not backported to 0.7.0

**Comment by barisusakli** [comment]
Let us know if you still get this on 0.7.1
