### ISSUE TITLE
Nodebb actions log

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3259]
The admin zone should have logs for important actions like..
- X user has been banned [ by username ]
- X thread has been deleted [ by username ]
- thread title has been changed to [new name] [ by username ]
etc

What do you think?

Thank you

**Comment by psychobunny** [comment]
We kind of have this already, in ACP -> Advanced -> Logs

Granted, it could look better / have more features but I think it has all the things you mentioned above

**Comment by psychobunny** [comment]
*ACP -> Advanced -> Events
