### ISSUE TITLE
Give a clear error when users are not allowed to post - and why

### ISSUE THREAD

**Issue by GitMensch** [NodeBB/NodeBB#3266]
I've registered at nodeBB community to start a question.
Clicking "New Topic" showed the according function. I've filled all fields and clicked on "Submit" - nothing happened.
Shortly before dropping nodeBB at all I've seen a registration email, clicked "activate" and was able to Submit.

In my opinion this is a *bug*: give the user the possibility to do something but simply not the possibility to do the last step *without any recognizable warning*. Possible solutions:

* prompt the user with an error message when clicking "New Topic"
* prompt the user with an error message when clicking "Submit"/"Ask as Question" (this is missing) - while preserving the content of the message (as it is now)

**Comment by barisusakli** [comment]
Hmm sounds like a bug, there should be an alert pop up when you try to post and dont have permissions/or not validated.

**Comment by barisusakli** [comment]
Also it might already be fixed yesterday but not pushed to our community.
