### ISSUE TITLE
Multiquote toogle suggestion

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3270]
I´m not a big fan of chained quoting but actually if you do a quote of several quotes....people wont see the text you quoting , only if you open toogle 

i will post 2 pictures to show an example of actual situation 

**first load ( i don't see the "2" and i´m actually replying that text )** 
![captura de pantalla 2015-06-26 a las 19 47 11](https://cloud.githubusercontent.com/assets/10746278/8383821/fb7a66fc-1c3c-11e5-8841-1c4296268bb1.png)

**toogle on will show the "2" of course**

![captura de pantalla 2015-06-26 a las 19 47 20](https://cloud.githubusercontent.com/assets/10746278/8384007/1e8ff3b8-1c3e-11e5-824e-f168977bd1ea.png)

so you will miss the conversation easy
maybe the approach should be the opposite way
now 2 pictures of suggested logic

**first load will show last quote**

![captura de pantalla 2015-06-26 a las 19 52 41](https://cloud.githubusercontent.com/assets/10746278/8383928/9639fcc0-1c3d-11e5-872b-79185325eaec.png)

**toogle on will open inside conversation** 

![captura de pantalla 2015-06-26 a las 19 51 29](https://cloud.githubusercontent.com/assets/10746278/8383946/af188f54-1c3d-11e5-8432-77bb69e5a3f3.png)

what do you think? just a suggestion
thank your for your time

**Comment by julianlam** [comment]
Seems to me that the "expander" should be present on all levels of quoting...

**Comment by martyalicante** [comment]
Maybe @julianlam. Anyways last quote should be visible by default without the need of pressing any toogle
