### ISSUE TITLE
Use Autoprefixer

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3273]
Could you use Autoprefixer in your merge process for less?
[Example how to use it with Grunt](https://github.com/postcss/autoprefixer#grunt).

If you don't want to use Autoprefixer, please add _css:[]_ block to plugin.json ;)

**Comment by NicolasSiver** [comment]
Oh, it seems there is css: [] for plugins already?

https://github.com/NodeBB/NodeBB/blob/c5b9c9254a4d40f792177259d313ffebb808b173/src/plugins/load.js#L33

**Comment by psychobunny** [comment]
That's right, check this out for an example:

https://github.com/psychobunny/nodebb-plugin-cash/blob/master/plugin.json#L25-L27

**Comment by NicolasSiver** [comment]
Would be great, if you update this document - https://docs.nodebb.org/et/latest/plugins/create.html 

@psychobunny also, give a try for the [Autoprefixer](https://github.com/postcss/autoprefixer), it's 2 lines of code in build process, but so much improvement for the end result ;)
