### ISSUE TITLE
Widget Render is triggered in ACP

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3274]
Guys, is it by design, that render method `filter:widget.render:` for the widget is triggered in ACP?

	area:
	   { template: 'admin/general/dashboard.tpl',
	     url: 'admin/general/dashboard',
	     locations: [ 'sidebar', 'footer', 'header' ] }

I have added widget to the global header.

![screen shot 2015-06-29 at 7 22 20 pm](https://cloud.githubusercontent.com/assets/135263/8412701/360dff5a-1e94-11e5-9162-acd1c47d353b.png)

**Comment by barisusakli** [comment]
Because of this https://github.com/NodeBB/NodeBB/blob/master/public/src/ajaxify.js#L158 a call goes out to render widgets everytime you ajaxify to a different page. Although I don't think it makes sense for it to happen on the ACP page. @psychobunny
