### ISSUE TITLE
Crash on editing profile with NodeBB 0.7.x

### ISSUE THREAD

**Issue by martin-mh** [NodeBB/NodeBB#3275]
Hello :-)

On editing my profile NodeBB totally crash. Here the logs :

    forum-0 30/6 11:32 [23110] - error: TypeError: undefined
    at Object.urlFormat [as format] (url.js:357:11)
    at updateField (/home/nodebb/src/user/profile.js:148:24)
    at /home/nodebb/node_modules/async/lib/async.js:122:13
    at _each (/home/nodebb/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/nodebb/node_modules/async/lib/async.js:121:9)
    at /home/nodebb/src/user/profile.js:108:11
    at /home/nodebb/node_modules/async/lib/async.js:251:17
    at /home/nodebb/node_modules/async/lib/async.js:154:25
    at /home/nodebb/node_modules/async/lib/async.js:248:21
    at /home/nodebb/node_modules/async/lib/async.js:612:34
    forum-0 TypeError: undefined
    at Object.urlFormat [as format] (url.js:357:11)
    at updateField (/home/nodebb/src/user/profile.js:148:24)
    at /home/nodebb/node_modules/async/lib/async.js:122:13
    at _each (/home/nodebb/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/nodebb/node_modules/async/lib/async.js:121:9)
    at /home/nodebb/src/user/profile.js:108:11
    at /home/nodebb/node_modules/async/lib/async.js:251:17
    at /home/nodebb/node_modules/async/lib/async.js:154:25
    at /home/nodebb/node_modules/async/lib/async.js:248:21
    at /home/nodebb/node_modules/async/lib/async.js:612:34
    30/6 11:32 [23110] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
    forum-0 30/6 11:32 [23110] - info: [app] Database connection closed.
    forum-0 30/6 11:32 [23110] - info: [app] Web server closed to connections.
    forum-0 30/6 11:32 [23110] - info: [app] Shutdown complete.

I don't installed specific plugins that may do that i think.
Do you have any idea to fix that :) ?

**Comment by barisusakli** [comment]
Let me know if above commits fixes the issue.

**Comment by martin-mh** [comment]
Yes it fix the issue at my home :-D !!
thanks !
