### ISSUE TITLE
Captcha login

### ISSUE THREAD

**Issue by julian9444** [NodeBB/NodeBB#3276]
Hello , it is possible to put a captcha ( recaptcha ) for the login ? , In order to avoid bruteforce.

**Comment by julianlam** [comment]
Yes, please activate the spam-be-gone plugin. :smile:

**Comment by julian9444** [comment]
spam-be-gone plugin that protects the registration page , not the login page :smile:

**Comment by psychobunny** [comment]
> In order to avoid bruteforce.

If you get the wrong password too many times your account gets locked, this is maybe good enough?

**Comment by julian9444** [comment]
I probably misspoke , I 'll rephrase :smile:.

Is it be possible to have a captcha (Google Recaptcha ) on the **login** page ?.

To answer your question, psychobunny :smile:, this protection is not really a protection, it affects more the user than the victim, in case of bruteforce attack than attacker ultimately gets what he wants, affect the stability of the forum.)

You're gonna tell me that there's the possibility of using the email address as a login, but just leaked to jeopardize the Forum's Board (in the case that that a y'ait one administrator ), the administrator account would be left off.

**Comment by julianlam** [comment]
Right, let's see if @akhoury has any thoughts about this.

**Comment by akhoury** [comment]
doable, track changes here
https://github.com/akhoury/nodebb-plugin-spam-be-gone/issues/32

if someone wants to have at it, be my guest, I'm booked for few weeks now.
