### ISSUE TITLE
Private route 

### ISSUE THREAD

**Issue by julian9444** [NodeBB/NodeBB#3277]
Hello , would it be possible to make a "route " Private ? Let me explain , I want to make sure that both :  registered and not, could not see content like https://domainname.tld/users (for exemple).

An indication that the /users is only accessible to administrators do not work (it works, the icon disappears , but /users remains available to users).

![cheese](https://cloud.githubusercontent.com/assets/13120452/8434130/e81bbc2c-1f49-11e5-8bf6-13a927c9994c.jpg)

Edit : I edited my post in a better english, sorry, I'm just a french guy :smile:

**Comment by psychobunny** [comment]
Is /users the only thing you need to make private?

Go to Admin -> Settings ->User
And select "Make user info private"

This will prevent anybody except admins from going to the /users or /user/name pages.

**Comment by julian9444** [comment]
the problem is, the icon disappears, but /users remains available to registered users, so the box Make private user information is checked, but I do not talk about that, but to this page : 
![cheese1](https://cloud.githubusercontent.com/assets/13120452/8442712/e5453712-1f80-11e5-96ae-c12e03379d4b.jpg)

**Comment by barisusakli** [comment]
`Make user info private` just makes it private for guests. If you want to completely hide /users change this piece of code https://github.com/NodeBB/NodeBB/blob/master/src/middleware/middleware.js#L109
to `if (!!parseInt(meta.config.privateUserInfo, 10)) {` The no one will be able to access /users

**Comment by julian9444** [comment]
It works , But It 's completely blocks the access to the home page /users.
