### ISSUE TITLE
Unload plugin

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3278]
Hello guys,

You have cool feature in the NodeBB: reloading of plugins, by activating/deactivating plugin, you perform reload of the modules in the background. 

What hook/event can I use to listen for these reloads? Because It creates memory-leaks in my plugin, I would like to dispose it properly on every reload.

**Comment by barisusakli** [comment]
`action:plugin.activate' and `action:plugin.deactivate` They hook is passed the id of the plugin that is activated/deactivated.

See here https://github.com/NodeBB/NodeBB/blob/master/src/plugins/install.js#L53

**Comment by NicolasSiver** [comment]
@barisusakli These hooks will be triggered just before reload?
Do you propose to listen for both hooks, and dispose plugin on every activate/deactivate call?

I don't think It's helpful, you can activate several plugins in a row, and only after it, perform reload.

**Comment by NicolasSiver** [comment]
What about this filter? - https://github.com/NodeBB/NodeBB/blob/master/src/plugins.js#L322

**Comment by julianlam** [comment]
The "require cache" is cleared (and thus the hook is fired) every time NodeBB is reloaded. For your purposes, you can either use baris' hook suggestions, or listen for the `clearRequireCache` hook, or just keep it simple and do what I do:

Store references to instantiated objects in the plugin's `module.exports` (or wherever is convenient for you), and clear them if necessary every time your init script (the method called that listens to `static:app.load`) is called.
