### ISSUE TITLE
getting some errors whenever I load the admin page

### ISSUE THREAD

**Issue by thelinuxlich** [NodeBB/NodeBB#3285]
nodebb.min.js?v=v0.7.0-1-g3e386e7:13 Uncaught SyntaxError: Unexpected token function
admin.js?v=v0.7.0-1-g3e386e7:28 Uncaught TypeError: Cannot read property 'emit' of undefined
admin.js?v=v0.7.0-1-g3e386e7:146 Uncaught ReferenceError: utils is not defined

**Comment by thelinuxlich** [comment]
This is random, sometimes it loads correctly, sometimes it doesn't

**Comment by barisusakli** [comment]
possibly same issue https://github.com/NodeBB/NodeBB/issues/3200

**Comment by thelinuxlich** [comment]
oh yeah. same errors

**Comment by julianlam** [comment]
Closed as duplicate.
