### ISSUE TITLE
Pagination Max pages

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#3286]
Maybe should set a max length for pagination so this won´t happen on slow resolutions and mobile
showing 5 pages at time should be enough

![captura de pantalla 2015-07-03 a las 3 04 27](https://cloud.githubusercontent.com/assets/10746278/8490889/cfb5f876-2130-11e5-9ba0-e1b5e9b2aa39.png)

**Comment by julianlam** [comment]
I was initially going to suggest that smaller resolutions should have smaller boxes, so they don't wrap, but UX-wise that's really the **opposite** of what we should be doing :smile: 

Perhaps on mobile resolutions, we can hide the majority and leave `<`. `>`, and the current page?

**Comment by martyalicante** [comment]
I have smaller boxes and still wont fit when you reach 3digit pages. 
5 pages max and some ellipsis should fit any mobile

**Comment by psychobunny** [comment]
How about on mobile, dump the `...` and have a horizontal swipe to scroll so you can visit any page?

**Comment by julianlam** [comment]
Oh, I like that idea :+1:

**Comment by martyalicante** [comment]
Sounds cools as long you keep first and last page links. I mean dont want to enter a thread and lose a lot time swipping till i reach last page.
In our forum we have threads with 100+ pages, usually an user will read first page then go to last page to see whats going on

**Comment by martyalicante** [comment]
just before i update my vanilla bases theme... 
will this be taken in consideration for future releases?

**Comment by barisusakli** [comment]
So all pages except the current one are hidden now on mobile?

**Comment by julianlam** [comment]
Yep, only previous, next, the current page, and the button to allow you to type the page number.

The other numbers are hidden.
