### ISSUE TITLE
when i submit a new topic ,the error occur

### ISSUE THREAD

**Issue by zhaovbo** [NodeBB/NodeBB#3290]
{ [MongoError: E11000 duplicate key error index: ptfeng.objects.$_key_1_value_-1 dup key: { : "user:2023", : null }]
  name: 'MongoError',
  message: 'E11000 duplicate key error index: ptfeng.objects.$_key_1_value_-1 dup key: { : "user:2023", : null }',
  index: 0,
  code: 11000,
  errmsg: 'E11000 duplicate key error index: ptfeng.objects.$_key_1_value_-1 dup key: { : "user:2023", : null }' }
{ [MongoError: E11000 duplicate key error index: ptfeng.objects.$_key_1_value_-1 dup key: { : "user:2885", : null }]
  name: 'MongoError',
  message: 'E11000 duplicate key error index: ptfeng.objects.$_key_1_value_-1 dup key: { : "user:2885", : null }

**Comment by barisusakli** [comment]
Can you post the output of the following.

```
db.objects.find({value: null});
```

**Comment by zhaovbo** [comment]
i  am sorry!
I do it ,but find nothing!
