### ISSUE TITLE
NodeBB Upgrade with latest master

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3291]
After `master` update, can't launch NodeBB.

Result of `./nodebb upgrade`

![screen shot 2015-07-04 at 10 35 22 am](https://cloud.githubusercontent.com/assets/135263/8506985/897c7a48-2238-11e5-9f7d-d3fa34965e83.png)

**Comment by julianlam** [comment]
Can you try `npm unl nodebb-theme-lavender`?

**Comment by NicolasSiver** [comment]
Thanks, it was helpful ;)

![screen shot 2015-07-04 at 4 37 36 pm](https://cloud.githubusercontent.com/assets/135263/8508094/08a86e4e-226b-11e5-83f5-92e666e147a5.png)
