### ISSUE TITLE
Post URLs break when "Pagination -> Posts per page" < 10

### ISSUE THREAD

**Issue by rbeer** [NodeBB/NodeBB#3292]
/topic/t#/slug/p# links end in never answered requests if infinite scroll is in use and user sets "Posts per page" to a value < 10.

~~Also, the permalinks in theme-persona are set to /topic/p# when loaded through scrolling (everything included in action:posts.loaded). Adresses of "first-load" posts (action:topic.loaded) are fine as links, but don't resolve either. The "< 10" does **not** apply here. It also happens on the standard setting of 20.~~

![issue-maxposts-url-broken](https://cloud.githubusercontent.com/assets/3411649/8507618/5fa7e410-224b-11e5-8806-fd635febb70f.png)

**Comment by julianlam** [comment]
Looks like #3289

**Comment by rbeer** [comment]
indeed; I noticed both abnormalities at the same time and mistakingly accounted both to changing the "Posts per page" option, while only the first (+ picture) can be.

I'd say this issue should only concern the first paragraph of my initial text, then.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/52f7e13a5c2bfb66c93afef9b989636a63cc5079
https://github.com/NodeBB/NodeBB/commit/1d4efaee68e75dce75e2d207a27474a86f206ac4

**Comment by rbeer** [comment]
@barisusakli 
LGTM, thanks! :+1:
