### ISSUE TITLE
Category Editing lost when selecting a parent category

### ISSUE THREAD

**Issue by drewdotpro** [NodeBB/NodeBB#3296]
Steps to recreate:
Create a category and set some icons, colour or other options.
Set the parent category.

Result:
Initial settings are reset.

**Comment by julianlam** [comment]
Hi @drewdotpro -- this is semi-intentional. Changing a category's parent immediately commits that change, although other changes (name, description, etc) are not saved immediately, but only when you hit _Save_.

Not quite the ideal behaviour, though, so this would be a nice thing to fix.

**Comment by drewdotpro** [comment]
Yay!
