### ISSUE TITLE
Upgrade the theme then cannot push anythiny

### ISSUE THREAD

**Issue by Xuchenhao** [NodeBB/NodeBB#3300]
a tpl file is lost. and nodebb.min.js need it
Could anyone help me?
Https://bbs.andy1999.com

**Comment by julianlam** [comment]
Are you on master?

**Comment by Xuchenhao** [comment]
I use nodebb dev -0.7.1 and the theme is nodebb-theme-persona.
Now I use the old one that have a file called compose.tpl . now it's ok.
The lasted didn't have that file so I cannot push anything

**Comment by julianlam** [comment]
You probably don't have the composer-default plugin. You must follow proper
upgrade procedure, especially on dev builds.

**Comment by Xuchenhao** [comment]
Thank you for your reply, I will try it.
