### ISSUE TITLE
Registration form error handling tweaks

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3305]
On lower-resolution mobile devices, the in-line error messages in the registration form may overlap the text area so much so that you cannot type in the box.

Ideally, the error should be changed to an "x" (rivalling the success checkmark), with an on-hover description of the error.

![selection_051](https://cloud.githubusercontent.com/assets/923011/8554157/1277226a-24b6-11e5-957c-1133e805dbd4.png)

**Comment by pichalite** [comment]
@julianlam on-hover on mobile?

**Comment by julianlam** [comment]
@pichalite :trollface: Not the most ideal solution, no. Open to suggestions on that one as well.

**Comment by psychobunny** [comment]
eh, I think the whole thing looks ugly anyways even on desktop, time for a redesign

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/242
