### ISSUE TITLE
register page timeout

### ISSUE THREAD

**Issue by chrismccoy** [NodeBB/NodeBB#3309]
when clicking the register link from the menubar, it keeps giving the ajax loading, but when visiting the url in the browser manually it works fine.

this is on 0.7.x

**Comment by julianlam** [comment]
Hi @chrismccoy is this still an issue? We cannot reproduce this one.

**Comment by chrismccoy** [comment]
no i fixed it by reinstalling, no idea what was causing the issue

**Comment by julianlam** [comment]
Okay, thanks Chris!
