### ISSUE TITLE
No fallback for missing languages in plugins.

### ISSUE THREAD

**Issue by rbeer** [NodeBB/NodeBB#3314]
Maybe I'm missing something; but as I'm adding language support to expiring-uploads, I noticed, that the "language engine" keels over, when the user chose a not specified (by the plugin) language.
As far as I can tell, this problem can be tackled by
  - letting plugin authors know, that they have to implement every language supported by the core. *Seriously not a good idea, though.*
or
  - Having the core fall back to one of the given languages. *Oh yes, please!*

I'm obviously a fan of the second solution, already. The question would still be though how to detect that fallback. Making a plugin.json field like "stdlang" or so mandatory, as soon as "languages" is given would be viable, I think.
![plugins-missing-languages](https://cloud.githubusercontent.com/assets/3411649/8636120/c46a59ea-2850-11e5-805c-fe3c5cec7269.png)

P.S.
I just tested this with my version of the [topic events plugin](https://github.com/rbeer/nodebb-plugin-topic-events). There it leads to the partials not being shown, at all. #very-nasty

**Comment by julianlam** [comment]
You know what @rbeer, kudos to you for trying to implement a thoroughly *untested* **and** *undocumented* feature :smile:

**Comment by julianlam** [comment]
We'd follow the same setting name we use in core: `defaultLang`...

**Comment by rbeer** [comment]
Well, I blame @psychobunny for that :stuck_out_tongue_closed_eyes:. I merely copied the principle from his mentioned topic events plugin.
The error message originates in translator.js@loadServer(), but as of now, mainly due to major caffeine headaches, I fail to see how to distinct whether a plugin is asking for the .json.
Then again, this seems to be the perfect time to set up a proper IDE and let go of that console.log debugging. :smile:

**Comment by julianlam** [comment]
@rbeer I'm trying this out, and in both server and client invocation, and in template inclusion, the translations work without crashing. If there is no language file present, then node complains, but still outputs the raw string (e.g. `[[markdown:bold]]` is translated to `bolded text` in english, but without a translation in, say, German, will simply be "translated" to `bold` in German language forums).

**Comment by julianlam** [comment]
Okay, tried it in a partial as well, and there's no crash.

Though yes, it would be nice to have a `defaultLang` parameter for plugins read... not sure how to integrate that yet though.

**Comment by julianlam** [comment]
@rbeer I made some changes :smile: 

You'll still define additional languages by pointing out the language folder to NodeBB via the `languages` property in `plugin.json`.

Now, however, if you also have `defaultLang` defined, then for any language file found when loading your plugin, NodeBB will use the defined default as a fallback language.

For example, if your plugin registers `de/topic-events.json`, and `defaultLang` is set to `de`, and someone loads your plugin with their language set to `en_GB`:

* During startup, NodeBB will preload `de/topic-events.json` (at least on the server-side)
* It will register a new route for other languages' `topic-events.json`, and return the contents of `de/topic-events.json`.

Client-side and server-side usage do not change:

``` js
require(['translator'], function(translator) {
  translator.translate('[[topic-events:rbeer-is-pain-in-the-butt]]', function(translated) {
    console.log(translated);
  });
});
```

**Comment by julianlam** [comment]
Documentation! https://docs.nodebb.org/en/latest/plugins/i18n.html

**Comment by rbeer** [comment]
I don't know...
Maybe it's just a uncommon usecase to have entire pages rendered from the backend. But I just can't shake the feeling, that having plugins do the translations explicitly is unnecessary.
Given that the translation is found, a simple [res.render(tpl, {tplVar: 'value'})](https://github.com/rbeer/nodebb-plugin-expiring-uploads/blob/master/expups_be.js#L268-L274) works just fine. I am trying to get the fallback in there.
But don't bother. I don't mean to be a `[[topic-events:rbeer-is-pain-in-the-butt]]` :kissing_heart:
I'll get my head around it sooner or later and let you know.
