### ISSUE TITLE
action:page.load hook?

### ISSUE THREAD

**Issue by RobertHerhold** [NodeBB/NodeBB#3317]
[On the old documentation describing all available hooks](https://docs.nodebb.org/nb_NO/latest/plugins/hooks.html#action-page-load), there exists a `action:page.load` hook that I would like to use. However, on the [updated GitHub docs page](https://github.com/NodeBB/NodeBB/wiki/Hooks), no such hook exists. What was the rationale behind removing this hook?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/1579

Maybe try `action:ajaxify.end`

**Comment by RobertHerhold** [comment]
Thanks!
