### ISSUE TITLE
Timeago - override .timeago() to change title to human readable format

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3322]
![](http://i.imgur.com/BtZ1Jhd.png)

After invoking `$('.timeago').timeago();` in `public/src/app.js` we should also take the `title` and change it to a human readable format (ex. 12 November 1987 00:27 :+1:)

**Comment by Fusselwurm** [comment]
Could you take care to make this customizable (or user agent dependent), or make sure the friendly format includes the time zone? 

(I'm afraid of information loss when things are dumbed down)

**Comment by pitaj** [comment]
A simple `(new Date(title)).toString()` should work.

Would output something like this: `Fri Jul 24 2015 18:57:38 GMT-0600 (Mountain Daylight Time)`
