### ISSUE TITLE
SocketIO address not working

### ISSUE THREAD

**Issue by ApfelUser** [NodeBB/NodeBB#3326]
My config:

```json
"socketio": {
      "address": "ws.domain.tld",
      "transports": ["websocket", "polling"]
}
```

Console log:

![](https://puu.sh/j1tq1/7a6423d364.png)

Other versions I have tried are:

  * `"address": "http://ws.domain.tld"`
  * `"address": "https://ws.domain.tld"`
  * `"address": "http://ws.domain.tld:8000"`
  * `"address": "https://ws.domain.tld:8000"`

They **all** don't work. NodeBB is always trying the normal domain `community.minora.io`. I am using a fresh `git pull` from `master`.

I also have restarted NodeBB after each configuration change.

Does anyone have an idea what could be causing this?

Cheers,

ApfelUser

**Comment by barisusakli** [comment]
Can you try 

```
"socket.io": {
      "address": "ws.domain.tld",
      "transports": ["websocket", "polling"]
}
```

**Comment by ApfelUser** [comment]
Same error again.

[Domain](https://community.minora.io/)

**Comment by barisusakli** [comment]
In your browser console what do you get when you type `config.websocketAddress` ?

**Comment by ApfelUser** [comment]
@barisusakli This:

![](https://puu.sh/j1zXq/07f31262a0.png)

**Comment by barisusakli** [comment]
Did you restart nodebb after you made the config change? That should show the string you put in the address section of the `socket.io` object.

**Comment by ApfelUser** [comment]
@barisusakli Oh. I am sorry. I missed your change with the `.` - It works now. The [Docs](https://docs.nodebb.org/en/latest/configuring/config.html) are showing **"socketio"**, but it seems corrected when I look at the [repository](https://github.com/NodeBB/nodebb-english). Did you miss to deploy it? Or is it some kind of cache?

Nevermind, just saw that you fixed the docs. Thanks a lot! Closing.

**Comment by barisusakli** [comment]
Yeah I fixed it in the docs as well, thanks for reporting.
