### ISSUE TITLE
View Count Behaviour

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3328]
Haven't heard a complaint about this for almost a year, but it bears discussion:

> If you refresh a topic, should the view count go up?

Arguments:
* Technically, you're _still_ viewing the topic, so the count shouldn't go up
* People can (and will) abuse this just for fun
* View counts are maintained on the server-side and we don't really track who views what

One possible implementation:
* ~~Every time a topic is loaded, the `tid` is saved into `req.session`, so if they re-visit the topic, the view count does not increment~~ (Nevermind, see below)
    * But what if they view the topic 6 hours later, should it count again? Should there be a timeout for the value saved into `req.session`?
    * What if you viewed a topic, and someone replied a minute later, and you viewed the new reply? One could argue that the topic ought to record a second view from you

RFC :smile:

**Comment by julianlam** [comment]
Ah, technically, we could also check the `uid:UID:tids_read` set, and increment if the tid is not present.

That's actually a neater solution than the one I suggested above.

**Comment by mrgame64** [comment]
We could also have a variable in `req.session` like `last_viewed_topic`, and every time the user visits a topic, we can do this check:
```javascript
if(req.session.last_viewed_topic != visiting_topic.id)
    visiting_topic.views++;
```

**Comment by julianlam** [comment]
Actually, we ended up benching discussion on this as it adds complexity (both in terms of code and perceived UX) to a system that is working fine as is, so this could be something a plugin could manage if so desired.
