### ISSUE TITLE
HTTP2 + WebSockets

### ISSUE THREAD

**Issue by ApfelUser** [NodeBB/NodeBB#3330]
Hello,

I am trying to use a HTTP2 web server for proxying NodeBB. Right now there is no implementation of the WebSocket standard in HTTP2. Would it be possible to make socket.io somehow only do HTTP/1 or HTTP/1.1 requests to the WebServer? Theoretically it should work then.

The issue on the web server project's bug tracker is https://github.com/mholt/caddy/issues/189

Cheers,

ApfelUser

**Comment by julianlam** [comment]
Hey there @ApfelUser, you may want to consider playing around with the [`socket.io` hash](https://docs.nodebb.org/en/latest/configuring/config.html?highlight=socket) in `config.json`.

**Comment by ApfelUser** [comment]
I don't understand how you could make NodeBB use < HTTP/1.1 for WebSockets using the config.json? Is there something I am maybe misunderstanding?

**Comment by julianlam** [comment]
Ah, I misread. You'll need to use a regular HTTP/1.1 server (nginx?) to proxy websocket requests to NodeBB... I do not have much experience with this, so I'm afraid I cannot help much.

**Comment by ApfelUser** [comment]
Well. What I am trying to do is actually using HTTP/2. So that is not an option :smile: I want to get HTTP/2 and WebSockets working. So thats why I was asking if you know of an option to force a HTTP version in socket.io or actually general javascript. I searched on Google and Stackoverflow etc. - it seems like there is no real option to force a HTTP version in javascript. Maybe there is one, but in that case it is not very well documented. I'll probably open another issue on socket.io but I guess they can't answer it either.
