### ISSUE TITLE
Special characters in names cause javascript errors

### ISSUE THREAD

**Issue by aorielly** [NodeBB/NodeBB#3332]
A fatal JS error occurs when there is an apostrophe in the name.  My last name is O'Rielly and i pasted below the JS errors i was getting in safari when trying to use the forums.

SyntaxError: Unexpected identifier 'Rielly'. Expected ')' to end a argument list.
nodebb.min.js:14:21065ReferenceError: Can't find variable: config
nodebb.min.js:14:47311ReferenceError: Can't find variable: config
announcements:35SyntaxError: Unexpected identifier 'Rielly'. Expected ')' to end a argument list.
nodebb.min.js:14:21065ReferenceError: Can't find variable: config
nodebb.min.js:14:47311ReferenceError: Can't find variable: config

**Comment by julianlam** [comment]
Hello there -- are you testing this on latest master? It is probably fixed.

**Comment by aorielly** [comment]
I believe we are using the latest release tagged at 0.7.0 so i have not done any testing on master.

**Comment by julianlam** [comment]
Thanks, we'll be launching v0.7.1 shortly (aiming for today), so when that is done, upgrading should take care of this issue.

**Comment by julianlam** [comment]
v0.7.1 launched now.
