### ISSUE TITLE
Feature: Hook: Adding sections in ACP

### ISSUE THREAD

**Issue by Xstasy** [NodeBB/NodeBB#3333]
Would you please consider adding a hook for making sections in ACP?

Hackish solution: https://community.nodebb.org/topic/6057/how-can-i-add-a-section-in-the-admin-menu

**Comment by julianlam** [comment]
This is a tricky issue, since on the one hand, we want to push for customisability in all aspects of NodeBB, while on the other hand, we don't want plugins to be adding menu items willy-nilly.

Any particular reason you want to maintain your own separate menu in the ACP instead of filing it under the "Installed Plugins" section?

**Comment by Xstasy** [comment]
Well, the plugin I'm currently writing has many parts and multiple menu items. While I could make tabs within my single plugin page I find it tedious to go into Installed Plugins -> Plugin -> Tab.

I understand why you don't want too many plugins doing this, but in the end the people who create plugins should be able to make them and extend any part of the menu. The plugin users can simply choose to not install them if they're cluttering.

**Comment by yariplus** [comment]
Hmm, but a plugin can already __[delete your entire forum](https://github.com/NodeBB/NodeBB/blob/master/src/database/redis/main.js#L30)__ willy-nilly if it wanted to, I'm okay with letting it change the ACP menu.

:+1:

**Comment by julianlam** [comment]
@yariplus double edged sword :smile:

**Comment by psychobunny** [comment]
We'd probably accept a PR for this if it came our way :+1:

**Comment by psychobunny** [comment]
For the ACP sections of course, not nodebb-plugin-flushdb :D

**Comment by psychobunny** [comment]
As said earlier, happy to accept a PR. I don't think many plugins require this usecase, but if yours does, feel free to submit a PR and we'll merge it :)
