### ISSUE TITLE
Mentions notification should follow categories permissions logic

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3335]
Possible bug. You should only get mentions notification from categories you can acess-read. 
At the moment if you mention someone on a category he will get the notfication and be able to read topic title even if he cant read the thread

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-mentions/commit/e9b6a265f69903cf34a3e76b4a755148b0861848
