### ISSUE TITLE
Decide on line endings in source

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#3343]
I hate to be pedantic, but there's a reason why so many SO questions reference this [article](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/) and [confusion has been had](https://www.google.com/search?q=crlf+will+be+replaced+by+lf) on dealing with line endings in source code in cross-platform projects. 

Right now as of commit 0bc4799c3c0de4c49837cda149eebac959c4909a there are these files that have CRLF line endings in their files, using the command `find . -not -type d -exec file "{}" ";" | grep CRLF`:

./app.js: ASCII c program text, with CRLF line terminators
./install/data/categories.json: ASCII text, with CRLF line terminators
./public/src/ajaxify.js: ASCII C++ program text, with CRLF line terminators
./public/src/app.js: ASCII C++ program text, with CRLF line terminators
./public/vendor/fontawesome/.gitignore: ASCII text, with CRLF, LF line terminators
./public/vendor/jquery/timeago/locales/jquery.timeago.fa.js: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./public/vendor/jquery/timeago/locales/jquery.timeago.uz.js: ASCII text, with CRLF line terminators
./README.md: ASCII English text, with very long lines, with CRLF line terminators
./src/routes/admin.js: ASCII text, with CRLF line terminators
./src/routes/authentication.js: ASCII text, with CRLF line terminators
./src/topics.js: ASCII text, with CRLF line terminators
./src/webserver.js: ASCII C++ program text, with CRLF line terminators

GitHub has written a nice article on it: https://help.github.com/articles/dealing-with-line-endings/

Inconsistencies like this make it more difficult for open source project contributors because of the availability of the source to many different developers' OS's. 

I guess what I'm really asking is, what would work with your guys' workflow? I see in the .editorconfig file that @akhoury added the line to have editors change eol to LF, but that's only if the dev has an editor that respects that setting. Would you be open to having a git-enforced policy?

This SO post illustrates it nicely as well: http://stackoverflow.com/a/20653073/1827734

**Comment by julianlam** [comment]
I'd be open to it. I've added a `.gitattributes` file and picked LF, because I happen to use Linux, and NodeBB is deployed most often to Linux boxes.

Now when I rebase or push, I get this warning :smile: 

```
warning: CRLF will be replaced by LF in src/routes/authentication.js.
The file will have its original line endings in your working directory.
```

So I suppose it's working.

**Comment by bdharrington7** [comment]
Awesome! You're awesome! Thanks!
