### ISSUE TITLE
Hidden Groups dont show Badges

### ISSUE THREAD

**Issue by TomasSchmidt** [NodeBB/NodeBB#3344]
If you set a group to be hidden, the members of that group aren't able to select the grouptitle/badge in their profile settings.

Might be useful for people who dont want to expose the groups but still showing the membership.

**Comment by julianlam** [comment]
Hi @TomasSchmidt -- this is intentional, as we wanted to keep groups logic simple. Badge visibility is tied to group visibility, and while I understand the proposed use case, I still believe it is easier to maintain it the way it is now...

So we'll leave it up for discussion in the meantime :smile:

**Comment by nbuckley** [comment]
I think this is a useful feature. A simple checkbox to allow use of the title anyways is all that is needed.

**Comment by s-blu** [comment]
I would prefer a checkbox to choose if a title is useable or not, too. I want to be able to activate the "Admin" Label, but I still want to manually add people to this group. If the group is visible users can request membership and that is not intended.

Maybe a possibility to show a group but close it for requests would be even better?

**Comment by lots0logs** [comment]
> would prefer a checkbox to choose if a title is useable or not, too. I want to be able to activate the "Admin" Label, but I still want to manually add people to this group. If the group is visible users can request membership and that is not intended.

+1 :+1:

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/4012

**Comment by lots0logs** [comment]
@barisusakli THANKS! :beers:

**Comment by s-blu** [comment]
@barisusakli Yay, thats great to hear! Thank you! :)
