### ISSUE TITLE
getting this error when run nodebb - when using mongodb+redis advance setup

### ISSUE THREAD

**Issue by frndxyz** [NodeBB/NodeBB#3345]
![nodebb mong_redis](https://cloud.githubusercontent.com/assets/6427428/8799137/7c8a6b98-2fc5-11e5-8da9-0ab7ed3ba2cf.png)

**Comment by frndxyz** [comment]
when using any single database, then there is no any error..

**Comment by julianlam** [comment]
Hi @frndxyz -- what's the specific use case for the advanced setup? We find that a common use case is offloading session support to Redis, and that doesn't require the advanced db setup.

**Comment by frndxyz** [comment]
i want to store all non-memory data to  mongoDB

**Comment by barisusakli** [comment]
Just setup mongo block in your config json like so. You can add a redis block as well and it will used as the session store. Here is a sample config.json

```
{
    "url": "http://yourforum.com:4568",
    "secret": "xxx",
    "database": "mongo",
    "mongo": {
       "host": "127.0.0.1",
       "port": "27017",
       "username": "",
       "password":"",
       "database":"0"
    },
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "password": "",
        "database": "1"
    }
}
```
