### ISSUE TITLE
Odd back behaviors.

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#3348]
Odd back behaviors.

**Process:**
at 93007bc34f73c35d71033d0c0954fe3736496b57
Browse to Categories
Click a Category
Click a Topic
Click Last Post Alert

**Chrome:**
Everything works as expected.
First Back: Returns to Category
Second Back: Returns to Categories

**Firefox:**
First Back: Scrolls to beginning of Topic
Second Back: Returns to Category
Third Back: Stays on Category, but changes url bar to "/categories#"
Fourth Back: Returns to Categories

**IE:**
First Back: Returns to Category, but url bar is "/category##"
Second Back: Stays on Category
Third Back: Returns to Categories, but url bar is "/categories#"
Fourth Back: Stays to Categories

**Comment by lnxseed** [comment]
yes, firefox twice.

**Comment by PierPP** [comment]
Probably same as #3424

**Comment by barisusakli** [comment]
Can you guys give this a shot on latest?

**Comment by yariplus** [comment]
Yep, worked a treat. Behavior is the same on all three browsers.
