### ISSUE TITLE
can't go to groups/administrators

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3349]
Upgraded from v0.7.0 to v0.7.1. When I go to /groups page, I can see the administrators group but when I click on the group, I get redirected back to /groups page. Same thing happens if I type the url directly.

**Comment by barisusakli** [comment]
Can you go the ACP and set the administrators group to not hidden?

**Comment by pichalite** [comment]
It is already set to not hidden in ACP as I can see the group in the /groups page.

**Comment by barisusakli** [comment]
Err sorry, try hidden>save>not hidden>save. Let me know if that fixes it :laughing:

**Comment by pichalite** [comment]
no change.

also the check boxes in the ACP groups edit page do not use the font awesome icons as the other ACP pages.

<img width="696" alt="screen shot 2015-07-22 at 12 38 25 pm" src="https://cloud.githubusercontent.com/assets/10014774/8835319/98eef66a-306e-11e5-9d73-2dd904f3b266.png">

**Comment by barisusakli** [comment]
Can you post the data of the admin group?
The key is `group:administrators`

**Comment by pichalite** [comment]
```
db.objects.find({_key: "group:administrators"});
{ "_id" : ObjectId("556b08af1bb52375a53370a0"), "_key" : "group:administrators", "name" : "administrators", "slug" : "administrators", "createtime" : 1433077935238, "userTitle" : "administrator", "description" : "", "memberCount" : 1, "deleted" : "0", "hidden" : "0", "system" : "1", "private" : "1", "icon" : "", "labelColor" : "#000000" }
```

**Comment by barisusakli** [comment]
Put a console log before [this](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/groups.js#L48) line. `console.log(exists, res.locals.groupName)`

Put a console log before [this](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/groups.js#L56) line `console.log(hidden, res.locals.groupName);`

Let me know the output.

**Comment by pichalite** [comment]
false null

null null

**Comment by barisusakli** [comment]
What is the output of `db.objects.find({_key:"groupslug:groupname"});`

**Comment by pichalite** [comment]
`
{ "_id" : ObjectId("556b1baf1bb52375a53370e9"), "_key" : "groupslug:groupname", "mlb" : "MLB", "test" : "test", "cid-6-privileges-groups-read" : "cid:6:privileges:groups:read", "cid-6-privileges-groups-topics-create" : "cid:6:privileges:groups:topics:create", "cid-6-privileges-groups-topics-reply" : "cid:6:privileges:groups:topics:reply", "cid-6-privileges-groups-find" : "cid:6:privileges:groups:find", "cid-7-privileges-groups-read" : "cid:7:privileges:groups:read", "cid-7-privileges-groups-topics-create" : "cid:7:privileges:groups:topics:create", "cid-7-privileges-groups-topics-reply" : "cid:7:privileges:groups:topics:reply", "cid-7-privileges-groups-find" : "cid:7:privileges:groups:find", "cid-8-privileges-groups-read" : "cid:8:privileges:groups:read", "cid-8-privileges-groups-topics-create" : "cid:8:privileges:groups:topics:create", "cid-8-privileges-groups-topics-reply" : "cid:8:privileges:groups:topics:reply", "cid-8-privileges-groups-find" : "cid:8:privileges:groups:find", "cid-9-privileges-groups-read" : "cid:9:privileges:groups:read", "cid-9-privileges-groups-topics-create" : "cid:9:privileges:groups:topics:create", "cid-9-privileges-groups-topics-reply" : "cid:9:privileges:groups:topics:reply", "cid-9-privileges-groups-find" : "cid:9:privileges:groups:find" }
`

**Comment by barisusakli** [comment]
Not sure why administrators is not in there. Run this in mongo

```
db.objects.update({_key: "groupslug:groupname"}, {$set: {"administrators": "administrators}});
```
Then try accessing /groups/administrators again

**Comment by pichalite** [comment]
that fixed it. I have a backup of db before I upgraded to v0.7.1. I will try to restore that in a separate mongo database and see if it was missing before the upgrade or after.

**Comment by pichalite** [comment]
restored the backup to a new db. ran the command.
`
db.objects.find({_key:"groupslug:groupname"});
`

the administrators group is missing before the upgrade

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/718f61e3bd5f3eb544284441411eb33e825d329a#diff-6368dbfcec6d363cbc2ce5a48b6781ad

Could be because at some point hidden groups were not added to `groupslug:groupname` So if you installed the forum during  that time administrators wont be in that hash. Which would cause the group/administrators page to redirect to groups if you are not an admin.
