### ISSUE TITLE
ACP plugins page issue

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3350]
After installing a plugin, an alert is displayed to activate the plugin. Instead of displaying the newly installed plugin under "Installed Plugins" at this point, the first plugin from the list of installed plugins is displayed.

**Comment by julianlam** [comment]
Hey @pichalite, I can't reproduce this issue. If I try to install a plugin, it disappears, and then the page scrolls up.

I mean, there's a bug in that the plugin doesn't load properly, but I may as well just refresh the page to simplify it...

**Comment by pichalite** [comment]
@julianlam If I remember it correctly, after you install a plugin it used to scroll up and just display the plugin that was installed under "Installed Plugins" so it can be activated. That's not happening now.

**Comment by julianlam** [comment]
Okay, thanks, will take a look.
