### ISSUE TITLE
Multi-tab chat UX Improvements

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3359]
Some annoyances that I want to address now:

* In scenarios where NodeBB is open in 1 or more tabs...
    * [x] When a new message arrives, it should appear on all taskbars (done already)
    * [x] If a chat modal is opened in one tab, in addition to marking that tab as no longer "new", it should also do the same to all other tabs
    * [x] If a chat modal is closed in one tab, it should close in all other tabs
    * [x] If you refresh the page, it should sync any open chat modals, and all tabs should have the same chats open

**Comment by pichalite** [comment]
@julianlam when I have multiple tabs open and a new message arrives, I get multiple notifications in the taskbar on all tabs (one for each tab).

Here's what I get when I have 4 tabs open and I get a chat message.

<img width="426" alt="screen shot 2015-07-24 at 3 05 56 pm" src="https://cloud.githubusercontent.com/assets/10014774/8885579/e1a6ff58-3215-11e5-8684-31d5c980fe45.png">

**Comment by julianlam** [comment]
... oh dear :laughing:

**Comment by pitaj** [comment]
lol :laughing:
