### ISSUE TITLE
Cannot find module 'npm' after upgrading.

### ISSUE THREAD

**Issue by Juxtapo** [NodeBB/NodeBB#3361]
Feel free to close this issue

**Comment by Icehunter** [comment]
On 0.7.x branch it's still an issue. Along with some other missing/miss-installed modules that were there before I upgraded.

I had to:

```
npm i nodebb-theme-persona nodebb-theme-vanilla npm uglify
```

**Comment by barisusakli** [comment]
@Juxtapo if you post the steps you took the resolve the issue it might help others.

**Comment by Juxtapo** [comment]
I ended up giving up and starting a new instance of NodeBB as there were also other issues on my server that I couldn't figure out.

**Comment by julianlam** [comment]
Issue resolved properly in v0.7.x as of c45e182bab87b1e45b31ce58f9e667337f01a4f3
