### ISSUE TITLE
Javascript code inside <script></script> in templates are not correctly parsed 

### ISSUE THREAD

**Issue by manolino** [NodeBB/NodeBB#3363]
Look at *populartopics.tpl* template (nodebb-widget-essensials).

Curly brackets in javascript code are parsed as `&#123;` and `&#125;` below.
```javascript
'use strict';
/* globals app*/

$(document).ready(function() &#123;
	app.createUserTooltips();
	$('.popular_topics').find('span.timeago').timeago();
&#125;);
```

**Comment by julianlam** [comment]
Please paste the contents of the widget's container.

**Comment by manolino** [comment]
I'm having problems with the default route ```/categories```.

Same problem in ```<head></head>``` section of some default routes (```&#x2F;``` instead of ```/``` ).
```javascript
<meta name="content-type" content="text&#x2F;html; charset=UTF-8" />
```
And in posts containing a poll.
```javascript
<script>Poll.load(&#123; pollid: 7 &#125;)</script></div>
```
In both themes Lavender and Persona. 

PS. I'm working on ```v0.7.1``` branch.

**Comment by julianlam** [comment]
Sorry for the delay. In a nutshell, the templating engine we use sanitises the data before it is output, although you can bypass the sanitiser by using `{{}}` instead of `{}`. Perhaps this is the reason?

If it is the poll plugin, try disabling it and seeing if the issue is resolved.

**Comment by manolino** [comment]
Disabled Poll plugin, But problem persists.

Check ```nodebb-widget-essentials/public/templates/suggestedtopics.tpl``` file for example.
The sanitized template code is:

```javascript
'use strict';
/* globals app*/

$(document).ready(function() &#123;
	app.createUserTooltips();
	$('.popular_topics').find('span.timeago').timeago();
&#125;);
```
If I change {} with {{}} as function code delimiters the sanitized code is:
  
```javascript
'use strict';
/* globals app*/

$(document).ready(function() &#123;{
	app.createUserTooltips();
	$('.popular_topics').find('span.timeago').timeago();
&#125;});
```
Reulting in a client side javascript error ```Uncaught SyntaxError: Unexpected token &```.

**Comment by psychobunny** [comment]
Sorry for the late reply here, @julianlam was referring to the widget container itself:

![](http://i.imgur.com/DUWIT4C.png)

If you use double curly braces as opposed to single it should prevent the escaping of JS
