### ISSUE TITLE
APC bug after plugin installed

### ISSUE THREAD

**Issue by mani95lisa** [NodeBB/NodeBB#3364]
always show `composer-default` plugin as installed plugin.

![qq20150727-1 2x](https://cloud.githubusercontent.com/assets/1968989/8903261/3fa308ac-3489-11e5-947d-e6b8558d24fa.jpg)

**Comment by julianlam** [comment]
> after plugin installed

Which plugin did you install? Is the ACP/Plugins page fixed after you `./nodebb reset -p {that plugin}`?

**Comment by pichalite** [comment]
@julianlam already filed this bug #3350.

**Comment by julianlam** [comment]
Ok thanks @pichalite
