### ISSUE TITLE
admin page logout doesnt work

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [NodeBB/NodeBB#3367]
While on admin , logout button doesnt work, the user is logged in on the main site as well,
NodeBB v0.7.1.
database mongo

**Comment by barisusakli** [comment]
Works for me are there any errors in the logs?

**Comment by KanwalPrakashSingh** [comment]
Now I dont see the issue occurring 

But what about this "Failed to load resource: the server responded with a status of 502 (Bad Gateway)" , i see this in console sometimes and some depricated warnings http://<domain>/socket.io/?EIO=3&transport=polling&t=1438195349313-12

**Comment by barisusakli** [comment]
The socket.io errors means there was a problem during the socket connection, could be beacuse of a proxy issue or something wrong with your connection.

You can ignore the deprecation warning if they are like these 
```
[deprecated] variables.set is deprecated, please use ajaxify.data, key=category_id
nodebb.min.js?19af63ec:10 [deprecated] variables.set is deprecated, please use ajaxify.data, key=category_name
nodebb.min.js?19af63ec:10 [deprecated] variables.set is deprecated, please use ajaxify.data, key=category_slug
nodebb.min.js?19af63ec:10 [deprecated] variables.set is deprecated, please use ajaxify.data, key=topic_count
nodebb.min.js?19af63ec:10 [deprecated] variables.set is deprecated, please use ajaxify.data, key=currentPage
nodebb.min.js?19af63ec:10 [deprecated] variables.set is deprecated, please use ajaxify.data, key=pageCount
```

**Comment by KanwalPrakashSingh** [comment]
alright then I should close this
