### ISSUE TITLE
Didn't work postcount for sub category & didn't work preview

### ISSUE THREAD

**Issue by pilyukhin** [NodeBB/NodeBB#3368]
Good day,
In v.0.7.1 & v.0.7.2 correctly count posts in old structure of sub category.
But if create new category & create post in sub category - counter didn't "see" posts in subcategory & didn't preview posts in main page.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/5b87af4389b8c3dc0495cc51f86edc176b086c75
