### ISSUE TITLE
Title edit options

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3373]
Enhancement. Admin option to let users edit topic title,... 
Some options could be. Users can edit topic title. Always, during X hours/days , disabled , avaliable to X group,etc

**Comment by julianlam** [comment]
Hm... to be honest, this seems more like a job for a plugin rather than in core. It seems to be a very niche case to restrict topic title editing from OP.

**Comment by julianlam** [comment]
Closing for now, but let me know if you (and others) disagree.

**Comment by martyalicante** [comment]
I guess doing a plugin for this should need  a hook to check when a title been changed?

**Comment by julianlam** [comment]
You'll want to subscribe to `filter:topic.edit`, and just remove the `title` and `slug` values. Then they won't be in the to-be-saved payload, and the title will not be changed.

**Comment by julianlam** [comment]
.. don't forget to allow admins to edit titles at all times :smile:
