### ISSUE TITLE
Unable to upgrade plugins/themes

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/NodeBB#3374]
Upon pressing the "Upgrade" button nothing visible happens on the ACP, but the terminal displays an error:
<img width="1438" alt="screen shot 2015-08-01 at 15 12 37" src="https://cloud.githubusercontent.com/assets/5879873/9021958/ebe52472-385f-11e5-9096-2f3920edebd1.png">

**Comment by julian9444** [comment]
I have exactly the same problem with nodebb 0.7.2, I could work around the problem with an npm upgrade :).

Just a question, you have access to the tab : Custom HTML & CSS ?, you're not a blank page ?.

**Comment by mrgame64** [comment]
Yeah, Custom CSS/HTML works like usual. It seems they are two distinct issues.

**Comment by mrgame64** [comment]
Cannot reproduce anymore, the plugin upgrading works just fine.
If it's the same for @julian9444, the issue can be closed
