### ISSUE TITLE
Images in signatures not working

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/NodeBB#3377]
As soon as an HTML img tag is added to the signature, it disappears upon saving the changes, no matter if the "Disable images in signatures" in ACP/Settings/Post is disabled or not.

Using the NodeBB 0.7.2 release

**Comment by barisusakli** [comment]
HTML is stripped from signatures try using `![](urlToImage)`

**Comment by mrgame64** [comment]
Using Markdown works indeed, thank you
