### ISSUE TITLE
"New Topic" and "Edit Post" issue after upgrading to 0.7.2

### ISSUE THREAD

**Issue by milipili** [NodeBB/NodeBB#3378]
Notepad++ now uses NodeBB, and we like it :)
However after upgrading from 0.7.0 to 0.7.2, it is no longer possible to create a new topic or to edit a post.

```
ReferenceError: module is not defined
 ->  nodebb.min.js:12:16739
```
![nodebb-new-topic-issue](https://cloud.githubusercontent.com/assets/5516919/9027117/7887f72c-3948-11e5-930b-d25f88d4e44d.png)
https://notepad-plus-plus.org/community/category/2/general-discussion

**Comment by mrgame64** [comment]
Have you updated your theme as well? It's possible it still uses the old API

**Comment by barisusakli** [comment]
Also make sure you have `nodebb-plugin-composer-default` installed and activated.

**Comment by milipili** [comment]
All plugins have been updated and `nodebb-plugin-composer-default` is activated.

**Comment by milipili** [comment]
Theme: `personna`

**Comment by barisusakli** [comment]
Seems like there is a js error that happens on page load, can you start the forum in dev mode with `./nodebb dev` and then check where the error is happening in your browsers dev console.

**Comment by milipili** [comment]
It seems that the parameter `module` is not defined
`21:01:21.232 ReferenceError: module is not defined1 nodebb.min.js:23617:0
`

Extract:
```js
  };

  module.exports.deflate = deflate;

}(module));   // <--

```

**Comment by milipili** [comment]
The nodeBB is currently in dev mode. You should be able to reproduce the issue too.

**Comment by milipili** [comment]
Here is the list of installed plugins :
 * `nodebb-plugin-archiver`
 * `nodebb-plugin-composer-default`
 * `nodebb-plugin-dbsearch`
 * `nodebb-plugin-emailer-local-0.7`
 * `nodebb-plugin-emoji-extended` (disabled)
 * `nodebb-plugin-github-embed`
 * `nodebb-plugin-markdown`
 * `nodebb-plugin-mentions`
 * `nodebb-plugin-plantuml`
 * `nodebb-plugin-soundpack-default`
 * `nodebb-plugin-spam-be-gone` (disabled)
 * `nodebb-plugin-sso-facebook-confirmed`
 * `nodebb-plugin-sso-github`
 * `nodebb-plugin-sso-google-confirmed`
 * `nodebb-plugin-sso-twitter`
 * `nodebb-rewards-essentials`
 * `nodebb-theme-lavender`
 * `nodebb-theme-persona`
 * `nodebb-theme-vanilla`
 * `nodebb-widget-essentials`

**Comment by barisusakli** [comment]
Try disabling this one `https://github.com/connorhillen/nodebb-plugin-plantuml` and the try again.

**Comment by barisusakli** [comment]
https://github.com/connorhillen/nodebb-plugin-plantuml/issues/1

**Comment by milipili** [comment]
Yeah \o/ It was the culprit indeed !
