### ISSUE TITLE
NodeBB v0.7.2 Release -> Custom HTML & CSS blank page (nodebb-theme-persona Latest 1.0.26)

### ISSUE THREAD

**Issue by julian9444** [NodeBB/NodeBB#3379]
![hello](https://cloud.githubusercontent.com/assets/13120452/9028468/1fb4f91a-397a-11e5-9342-de1e7def7786.jpg)

Uncaught TypeError: $(...).nanoScroller is not a function
nodebb.min.js?v=v0.5.0-2-3660-g2b93c01:5 WebSocket connection to 'wss://forum.xxxx.xx/socket.io/?EIO=3&transport=websocket&sid=LmlOTMvqv81scUIzAAAH' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by julianlam** [comment]
Cannot reproduce on latest core and theme. Please disable all non-essential plugins and see if the issue is resolved.

**Comment by julian9444** [comment]
The problem is solved, I'm behind Cloudflare, the problem came from Rocket Loader.
