### ISSUE TITLE
NodeBB v0.7.2 Release (Pannel Administration, Not Research)

### ISSUE THREAD

**Issue by julian9444** [NodeBB/NodeBB#3380]
![hello1](https://cloud.githubusercontent.com/assets/13120452/9031713/fe73109c-39b6-11e5-817a-4398d10bcd14.jpg)

**Comment by julianlam** [comment]
Hi there. What's the problem here?

**Comment by julian9444** [comment]
The problem is solved, I'm behind Cloudflare, the problem came from Rocket Loader.
