### ISSUE TITLE
Category Image Upload not working  & category description not appearing on refresh

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [NodeBB/NodeBB#3382]
After uploading imaging , it shows in preview but cannot be seen while visiting the category on forum.

version 0.7.1

No error in log / console

**Comment by pichalite** [comment]
@KanwalPrakashSingh which theme are you using?

**Comment by KanwalPrakashSingh** [comment]
persona

**Comment by pichalite** [comment]
Just checking, did you click "Save" in the ACP after uploading the image?

**Comment by KanwalPrakashSingh** [comment]
yup , 
I found the issue , image class  auto shows no image, but blank white screen. 
all the other image classes work

**Comment by KanwalPrakashSingh** [comment]
ah, i see, the image is shown but when auto is selected it takes one of the corners i guess .

There is another issue , for the categories some description is written. That description doesnt load when i refresh the page, but when i traverse the page again by pressing back button, i can see the description. 
<img width="899" alt="screen shot 2015-08-03 at 9 19 50 pm" src="https://cloud.githubusercontent.com/assets/1528747/9041399/6f1d0f5a-3a25-11e5-8a17-0b95356eef9b.png">
<img width="895" alt="screen shot 2015-08-03 at 9 19 36 pm" src="https://cloud.githubusercontent.com/assets/1528747/9041398/6f1a57e2-3a25-11e5-9b4f-bf497a9b859f.png">

**Comment by pichalite** [comment]
@KanwalPrakashSingh this is an issue with the theme not related to core so this should be created on the theme's github page.

**Comment by KanwalPrakashSingh** [comment]
@pichalite will open it there
