### ISSUE TITLE
Where find nodebb forum code?

### ISSUE THREAD

**Issue by ghost25s** [NodeBB/NodeBB#3386]
Xenforo e.g [size],[s] etc...

Nodebb forum has only this button. Bold,URL,Indent

**Comment by psychobunny** [comment]
http://daringfireball.net/projects/markdown/syntax

Depending on what plugins for composer you have you could also use bbcode or WYSIWYG instead.

**Comment by psychobunny** [comment]
Also, have a look at this plugin: https://community.nodebb.org/topic/2298/nodebb-plugin-buttons-galore-nodebb-buttons-galore

**Comment by ghost25s** [comment]
Default version not available. I am only user from forum. The use this nodebb.

But I can not use the bb-code. And now?

**Comment by ghost25s** [comment]
Help me?
