### ISSUE TITLE
After ajaxifying on FF, you require to press back twice to return

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3424]
Seems OK on chrome (desktop/mobile), recent regression on FF

**Comment by yariplus** [comment]
As I reported above, similar experience for me on IE, the first back works, but after that, all are doubled.

The fun has not been doubled. :banana:

**Comment by julianlam** [comment]
... and I thought I was done with `ajaxify.js`

**Comment by brownsmart** [comment]
I thought this was just how it was, clicking back twice... oh well...

**Comment by barisusakli** [comment]
TIL `window.location.hash = '';` causes a `popstate` event in firefox.

This line https://github.com/NodeBB/NodeBB/blob/master/public/src/ajaxify.js#L285 causes this bug removing it fixes it on firefox, although not sure why that line is there @julianlam ?
