### ISSUE TITLE
Redirect or confirmation message after user deletion

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3428]
If I go to a user's profile page whilst logged-in as an admin and then delete that user, nothing seems to happen. If I refresh the page manually, I can see that the deletion has worked, the user is gone. It would be great if some kind of message was displayed to say the deletion was successful or unsuccessful.

**Comment by barisusakli** [comment]
Which version are you on? We already do a history.back when you delete a user.

https://github.com/NodeBB/NodeBB/blob/master/public/src/client/account/profile.js#L157

**Comment by henrywright** [comment]
When I run `git pull` I get "Already-up-to-date" which I assume means I'm on the latest version?

**Comment by barisusakli** [comment]
Run `git rev-parse HEAD` in your nodebb folder. That should give you the nodebb commit hash you are on.

**Comment by henrywright** [comment]
OK, the hash I'm on is `4bcf7792f826a42e21df08847926feb75da1f2c5`

**Comment by barisusakli** [comment]
Looks like you do have that change, after deleting a user history.back() is called. Which browser are you on?

**Comment by henrywright** [comment]
Great, at least I'm up-to-date. I'm using Chromium 43.0.2357.130 and Ubuntu 14.04

**Comment by barisusakli** [comment]
This works for me on chrome with latest, any one else can reproduce?
