### ISSUE TITLE
[ie9] post tool buttons don't work, again

### ISSUE THREAD

**Issue by PierPP** [NodeBB/NodeBB#3430]
New Ajaxify and [ie9] post tool buttons don't work #2393

Post, Reply Quote buttons aren't working anymore on old browsers. Ajaxify.js problem I think

**Comment by barisusakli** [comment]
Does this happen on latest master, can you post the specific hash you are on?

**Comment by PierPP** [comment]
Tried on 0.7.2 (latest commit).
4bcf7792f826a42e21df08847926feb75da1f2c5

**Comment by barisusakli** [comment]
![image](https://cloud.githubusercontent.com/assets/2583394/9280470/7ddc6a80-428c-11e5-98fe-734769bab661.png)

is what I get in ie 9 emulation mode so cleary somethings wrong

**Comment by PierPP** [comment]
Ok, tried on latest commit on master branch: still the same behavior
8333a5dcd998a769d01c69ef8511221086eba924

**Comment by barisusakli** [comment]
@PierPP can you update to latest and give it another shot, don't forget to clear browser cache.

**Comment by PierPP** [comment]
Oh! it seems to work! I'm going to upgrade my production server and check again :)
