### ISSUE TITLE
Editor is way too complicated 

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [NodeBB/NodeBB#3432]
Hey Guys 

The editor seems to complicate for normal users, this I found out by surveying users. 
All but one said that they didnt understand what the editor icons meant, the one who didnt say it was a software developer who had markdown / html knowledge 

There should be tooltip on hover for the icons telling the user what the icons mean. 
Secondly the editor I find most useful and easy to understand is quora editor. 
After pasting the link it automatically scrapes the description. 

Hope you guys agree with the same

**Comment by julianlam** [comment]
The composer is not meant to be WYSIWYG, please use redactor composer if you're looking for that functionality
