### ISSUE TITLE
Wrong topics and posts counting

### ISSUE THREAD

**Issue by leksar** [NodeBB/NodeBB#3433]
I have a category "Hafen" on my forum mtgm.ru and the counter says it's only 3 topics in there, but i also have a category histories which is subcategory of subcategory of hafen. And looks like nodebb doesn't see the connection between those two. The "last comment" section doesn't work with this subcategory too.

**Comment by leksar** [comment]
that's what baris said:
Yeah the calculation doesn't work for subcategories, one reason is we don't have a recursive function to get all children and calculate the counts also we don't have a list of children category ids per category so without adding that this is difficult to achieve.

**Comment by leksar** [comment]
So I ask you to make the appropriate changes

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/3447
