### ISSUE TITLE
feature: Users: more filters to list users

### ISSUE THREAD

**Issue by milipili** [NodeBB/NodeBB#3436]
In `Manage`/`Users`, it would be nice to have more standard filters:

 - `Not validated`: all users who don't have validated their email
 - `Inactive`: all offline users for more than X months, sorted by date, to remove then (valid login account, but mostly used for spam actually)

**Comment by MegaGM** [comment]
:+1:

**Comment by wellenreiter01** [comment]
Another filter, which would be nice:
* users with no posts after X days/month from registration date

**Comment by milipili** [comment]
nice :)

**Comment by donho** [comment]
:+1:
