### ISSUE TITLE
spam-must-be-gone: auto ban users

### ISSUE THREAD

**Issue by milipili** [NodeBB/NodeBB#3437]
The plugin `spam-must-be-gone` is doing a wonderful work. Akimet prevent against spamming from valid account, Honeypot also helps a lot sometimes.
However, it would be nice to automatically ban the user after X spams messages in less than Y hours/days.

**Comment by milipili** [comment]
Actually, it would be nice to automatically send to Akismet all messages from a banned user, probably with another action `Report as spam`. On Notepad++ Community, we have a loooooot of spams...

**Comment by milipili** [comment]
And it would be nice to directly report from a category.

**Comment by julianlam** [comment]
@milipili  I noticed you had some spam last night :(

I'd recommend turning on the registration queue in the meantime, as a stopgap measure

**Comment by milipili** [comment]
it won't stop like that (already tested ^^) and it is really annoying for our users. But the services like Akismet are really efficient, even if not always working. However `spam-be-gone` lacks some bulk actions and automatic counter-measures.

**Comment by julianlam** [comment]
Yeah, as I mentioned in my last comment, it is very much a stopgap measure, and isn't really a solution. 

With the registration queue enabled, however, I just blindly reject any IP starting with `211.`...

**Comment by milipili** [comment]
We may have a proposal : #3552

**Comment by psychobunny** [comment]
Moving this to the plugin repo:
https://github.com/akhoury/nodebb-plugin-spam-be-gone/issues/47
