### ISSUE TITLE
Duplicate pages

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3438]
This isn't really a bug; instead, it's more of an observation that doesn't look quite right.

If I set the home page route to Categories under General > Home Page, I can access that particular page by going to both example.com and example.com/categories.

Setting the home page route to Recent, I can access that page via example.com and example.com/recent.

The same goes for Popular: example.com and example.com/popular.

The duplicate page feels odd. I'm not sure if it's needed?

**Comment by julianlam** [comment]
Yes, it is intentional :smile:

The idea is you'd customise the actual top navbar via the Navigation page in ACP, hiding the duplicate page as necessary

**Comment by henrywright** [comment]
That's kind of what I meant. I'm customising the nav menu so that the duplicate page doesn't appear, but it's still lurking there in the background if you know the URL.

**Comment by julianlam** [comment]
Trust me, your users won't go to that route directly via url :wink:

**Comment by henrywright** [comment]
OK I trust you haha
