### ISSUE TITLE
Topic tools broken

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3439]
I'm not sure if this is a theme issue (I'm using Persona) but if you navigate to a category page such as [this](https://community.nodebb.org/category/1/announcements) as an administrator, you will see a Topic Tools option list. The options aren't relevant on this page (in fact they don't work) because they all refer to a single topic (example: Delete Topic, Move Topic etc).

**Comment by julianlam** [comment]
Hey there!

Actually, the topic tools are supposed to be there :smile: -- if you click on the image next to a topic, it turns into a checkbox, so you can select multiple topics and delete/lock/pin them at the same time.

Of course, the dropdown does nothing if no topics are selected, so perhaps the dropdown should be hidden or greyed out if no topics are selected.

What do you think @psychobunny ?

**Comment by henrywright** [comment]
Hey @julianlam! After your explanation it all makes sense. I had no idea I had to click on an topic's image in order to use the topic tools.

**Comment by psychobunny** [comment]
The idea was stolen from gmail, which only makes sense on mobile. There should probably be a better interface for desktop. I'll post an issue on persona to remind myself to look into it
