### ISSUE TITLE
Plugin "Uninstall" button stuck on "Uninstalling"

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3440]
When I click Uninstall, the button seems to get stuck on "Uninstalling". See the screenshot below. Please note that the uninstall does work. For example, if I navigate away from the page and then back again I can see that the plugin has been uninstalled. 

![uninstall](https://cloud.githubusercontent.com/assets/1963288/9283278/74f4521e-42ca-11e5-993a-246a2d95e618.png)

I'm running NodeBB 0.7.2 on Nginx, Redis database, Ubuntu 14.04 VPS, Viewing the admin area with the Chromium browser.

**Comment by psychobunny** [comment]
Works for me :tm: on latest

**Comment by APXEOLOG** [comment]
I got this times to times. It works ok on "fresh" run, but if you install 5-6 plugins, activate some of them, reload (not restart), then deactivate, reload and uninstall, you can get this with high chance.

**Comment by barisusakli** [comment]
Is this happening when you run nodebb with `nodebb start`?

**Comment by henrywright** [comment]
Yes. I didn't know `dev` or `grunt` were available back then so would have used `./nodebb start`

**Comment by barisusakli** [comment]
Please report back if you encounter it again on 1.0.0+ and have repro steps.

**Comment by henrywright** [comment]
@barisusakli will do :)
