### ISSUE TITLE
Link to minified versions of JavaScript files

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3446]
[es5-shim.min.js](cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js) and [respond.js](cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js) are used in the project but there are minified versions of these available:

html5shiv.min.js
respond.min.js

Can the minified versions be used instead? We might gain a few millionths of a millisecond :)

**Comment by julianlam** [comment]
They are minified when nodebb.min.js is compiled.

**Comment by henrywright** [comment]
If the browser is crappy, I think the CDN versions are used? Taken from my HTML source:
