### ISSUE TITLE
Banning users should follow permission logic

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3453]
Actually to ban some user you must be admin
On a daily situation a mod should be able to ban a disturbing user and maybe not elegible to be admin.
maybe admin could give an user the ability to ban like you give the ability to moderate and then he could be able to ban from new buttons on user profiles.
I think is a reasonable enhancement.

**Comment by psychobunny** [comment]
https://www.npmjs.com/package/nodebb-plugin-superusers

I think this is close to what you're looking for. Its an officially supported plugin so feel free to leave enhancement requests there :)

**Comment by martyalicante** [comment]
That official plugin is not working and not updated for 6 months :(
