### ISSUE TITLE
category view showing both the last post and no new posts

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3454]
https://community.nodebb.org/topic/6302/looks-like-a-bug-on-topic-titles

Also inside a category, subcategory that is a link is still showing topic post count and teaser

https://community.nodebb.org/category/3/nodebb-development `nodebb localization` is a link it shouldn't have topic post counts and teaser.

**Comment by mrgame64** [comment]
I'm having the same problem, NodeBB v.0.7.3, Persona theme

**Comment by barisusakli** [comment]
https://github.com/psychobunny/templates.js/commit/3b5177b5d7f3f998ef673a107327aa482624e70d
