### ISSUE TITLE
can admin create a category and assign it to someone else later ?

### ISSUE THREAD

**Issue by frndxyz** [NodeBB/NodeBB#3455]

**Comment by julianlam** [comment]
What did you mean by "assign it to someone else"?

**Comment by frndxyz** [comment]
suppose i am admin, and create topic by getting information from web, later i assign to someone who can handle reply and question related to topic.

**Comment by barisusakli** [comment]
Categories don't have owners, do you mean a topic? Right now there is no way to change the owner of a topic.

**Comment by frndxyz** [comment]
yes ,i mean topic ,can this feature available later? 


     On Friday, 21 August 2015 1:06 AM, Barış Soner Uşaklı <notifications@github.com> wrote:
   

 Categories don't have owners, do you mean a topic? Right now there is no way to change the owner of a topic.—

**Comment by psychobunny** [comment]
Can you repost this on our community forum instead please? I'm trying to clean up our issue tracker from questions vs. feature requests / bugs. Thanks!
