### ISSUE TITLE
Need Translation Strings for "Cancel" and "OK" for Kinyarwanda (rw) Language

### ISSUE THREAD

**Issue by Abroum** [NodeBB/NodeBB#3457]
"Cancel" and "OK" (as seen on the warning dialog window screenshot below) aren't available for translation on Transifex.

![image](https://cloud.githubusercontent.com/assets/13814405/9395861/002891ae-475f-11e5-9cd5-f207c31a5d0c.png)

**Comment by barisusakli** [comment]
I think that modal is a bootbox modal, does it even support i18n? @julianlam

**Comment by psychobunny** [comment]
yeah it does, I see this in the source

```
...
es:{OK:"OK",CANCEL:"Cancelar",CONFIRM:"Aceptar"},fi:{OK:"OK",CANCEL:"Peruuta",CONFIRM:"OK"},fr:{OK:"OK",CANCEL:"Annuler",CONFIRM:"D'accord"},it:{OK:"OK",CANCEL:"Annulla",CONFIRM:"Conferma"}
...
```

**Comment by psychobunny** [comment]
That said, I think we should override it with our own language strings for maximum compatibility, shouldn't be too hard to mess about with the source

**Comment by Abroum** [comment]
Hi, guys! I didn't understand what the conclusion came out to be. Are those going to be possible to be translated for Kinyarwanda (rw) language?

**Comment by julianlam** [comment]
Should be implemented now.

**Comment by psychobunny** [comment]
Yup. The strings will be available in modules:bootbox

Hasn't been pushed to transifex yet, @julianlam when he's free will do so

**Comment by psychobunny** [comment]
inb4'd, mobile commenting ftw

**Comment by Abroum** [comment]
Okay. Cool. It makes sense now. 

Also, I forgot one thing: I forgot to mention that "said" needs to be translated as well. Should I start a new issue or you got it? The "said" string is the one that you see when you quote someone. Thanks.

**Comment by psychobunny** [comment]
Definitely new issue, although that might belong in composer repo: @julianlam?

**Comment by Abroum** [comment]
@psychobunny : cool bro
