### ISSUE TITLE
error when upload image or avatar

### ISSUE THREAD

**Issue by frndxyz** [NodeBB/NodeBB#3460]
getting error while uploading avatar or image at localhost server : "invalid-refresh-token"

**Comment by barisusakli** [comment]
Did you upgrade nodebb-plugin-imgur to 1.0+ if so please follow the instructions [here](https://github.com/barisusakli/nodebb-plugin-imgur#setup)

**Comment by frndxyz** [comment]
yes,plugin is latest version 1.0.4

**Comment by frndxyz** [comment]
same error occoured when upload avatar.

**Comment by frndxyz** [comment]
issue resolved...
