### ISSUE TITLE
Feature proposal: automatic language choice

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/NodeBB#3462]
I'm currently working on an international, multi-language forum powered by NodeBB, and I've run into a problem; all the new users will see the forum in the language I set as the default in the ACP, and can change it to their own only _manually_.

Would it be possible to add a functionality that automatically chooses the viewing language, basing on the user browser's default language? (if not overridden by the user's manual language setting)

**EDIT:** I think that such an option would be easily viable if we were to use the _Accept-Language_ HTTP header

**Comment by julianlam** [comment]
Possibly, though we do support `?lang=` querystring on all routes. Perhaps your site could show a modal to guests to select a language?

It seems automatic detection is not reliable as of yet...

**Comment by kerberjg** [comment]
@julianlam Is that really so? I've had the occasion to test a few Node.js i18n modules, and they seem quite reliable when it comes to locale recognition (from user agent, at least in the latest browsers)

**Comment by julianlam** [comment]
@kerberjg if you could suggest one I'll look into it :smile:

**Comment by kerberjg** [comment]
Sorry for the hiatus, I kind of forgot about this issue!

@julianlam So module I'd recommend is [locale](https://github.com/jed/locale), it's quite straightforward and I never had a reason to complain about it :)

**Comment by digitalLumberjack** [comment]
That would be awesome :)

**Comment by digitalLumberjack** [comment]
No need for automatic detection but we can rely on the browser language. It's standard and can be changed by user if needed.
The https://www.npmjs.com/package/accept-language plugin seems to works well :)

**Comment by digitalLumberjack** [comment]
@julianlam any news about this feature ? I put online the nodebb for https://forums.recalbox.com and it works great (thnak to the nodebb team btw) :) but the language selection from http header is really missing :)
