### ISSUE TITLE
Need Translation Strings for "said" When in the Composer

### ISSUE THREAD

**Issue by Abroum** [NodeBB/NodeBB#3467]
When quoting, there is no translation for "said" for Kinyarwanda (rw) language.

**Comment by julianlam** [comment]
There should be... it is in `modules.json`. `user_said_in` and `user_said`

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/blob/master/public/language/rw/modules.json#L21-L22

**Comment by Abroum** [comment]
@barisusakli & @julianlam : Those seem not to have the one I was pointing out. Let me attach the screenshot and show you which one I am taking about: 

![image](https://cloud.githubusercontent.com/assets/13814405/9453431/617a63b6-4a88-11e5-9903-73936d17f894.png)

If you are in Kinyarwanda,for example, it still shows "said" although you have switched languages. 

Since once you post it, it become static text, I think we need to do something about it. We can replace "said" with a symbol. In that way, it will be one symbol of communication for all languages. Let me know if you need further explanation.

**Comment by barisusakli** [comment]
Well if you are on latest and the users language is `rw` then they should see

```
@Kar yavuze:
> This is another
```

In the composer, maybe you are not on latest?

**Comment by Abroum** [comment]
I am on the latest update.

In fact, the same issue is reproduced on NodeBB community website. 

Check out this example: 

![image](https://cloud.githubusercontent.com/assets/13814405/9453698/183cd4e8-4a8a-11e5-8dcc-9bed7d2edaf6.png)

**Comment by barisusakli** [comment]
Oh now I see the problem, the translation for that word uses the config.defaultLang value which is the language set by the forum admin. If we translate that by each users language then each post will  have a different version of it.

**Comment by Abroum** [comment]
@barisusakli : Thanks. Now I get it. I think I will find a way to get around with it. Thanks. The issue is solved now.
