### ISSUE TITLE
Admin is unable to become Group owner of (System) Admin group.

### ISSUE THREAD

**Issue by Kowlin** [NodeBB/NodeBB#3469]
As the title suggests, there is no way for a system admin to become group owner of the system admin group. So it is impossible to carry out tasks like changing the background of the group.

**Comment by henrywright** [comment]
Perhaps there could also be an header image upload button at `example.comadmin/manage/groups/group-name`?

**Comment by julianlam** [comment]
Haha I noticed this earlier when I was trying to set a group image for the admin group in our community forum. I ended up db diving to make myself an admin, but yes,.. a bit of an oversight.

When a user joins a group and creates it, they should automatically become an owner...

**Comment by barisusakli** [comment]
@Kowlin if you want to fix this on an existing install, just make another admin user then toggle the admin status on the original user, making them an admin again will grant ownership of the group.
