### ISSUE TITLE
Bootstrap markup on a user's posts page wrong

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3476]
The width of each post on the following page is slightly too wide: https://community.nodebb.org/user/henrywright/posts

This is because some Bootstrap markup is missing. Currently the markup is:
```
<div class="row">
    <!-- Stuff -->
</div>
```

It needs to be something like:
```
<div class="row">
    <div class="col-xs-12">
        <!-- Stuff -->
    </div>
</div>
```

**Comment by julianlam** [comment]
Sharp eye :stuck_out_tongue:
