### ISSUE TITLE
Favourites page Bootstrap markup wrong

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3479]
The width of each favourited post on the following page is slightly too wide: https://community.nodebb.org/user/henrywright/favourites

This is because some Bootstrap markup is missing. Currently the markup is:
```
<div class="row">
    <!-- Stuff -->
</div>
```

It needs to be something like:
```
<div class="row">
    <div class="col-xs-12">
        <!-- Stuff -->
    </div>
</div>
```

This is almost a complete replica of issue [3476](https://github.com/NodeBB/NodeBB/issues/3476) which was recently fixed.

**Comment by julianlam** [comment]
Both were fixed in the commit for 3476.
