### ISSUE TITLE
Introduce a new tab in ACP/Plugins to list plugins that aren't specifically marked as compatible

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3480]
Due to demand by @psychobunny and possibly some others :smile: 

If I could make one request, it would be to place a fairly conspicuous warning on this tab.

**Comment by julianlam** [comment]
a27c8f0321340d1ddb35139b29b90b91367d448c and onwards contains the plugins in the "incompatible" template array.

**Comment by barisusakli** [comment]
"If you want to blow up your forum visit this tab" ? :laughing:

**Comment by psychobunny** [comment]
![](http://i.telegraph.co.uk/multimedia/archive/01941/shuttle-challenger_1941643c.jpg)
