### ISSUE TITLE
Gravatar logo used as guest avatar even when default is set to mystery-man

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3483]
If you set Default Gravatar Image (Settings > User > Avatars) to mystery-man, I'd expect the mystery-man to be used as the guest avatar on user pages such as example.com/users/online.

But, it's actually the Gravatar logo that is used:

![avatar](https://cloud.githubusercontent.com/assets/1963288/9450558/42b53e10-4aa1-11e5-83d0-eb59c9564319.png)

**Comment by psychobunny** [comment]
Coincidentally enough, my sister pointed that out to me yesterday. Are you my sister in disguise :rage:  :P

**Comment by henrywright** [comment]
@psychobunny haha. Your sister has a great eye for detail! :+1:
