### ISSUE TITLE
Back button navigation from /category to homepage is broken.

### ISSUE THREAD

**Issue by bwang29** [NodeBB/NodeBB#3486]
The homepage looks like this 

![image](https://cloud.githubusercontent.com/assets/806199/9458591/d9b0fad6-4aa4-11e5-84b3-4cc906cd0a4e.png)

After going into a category, and hit the back button on Google Chrome, it became

![image](https://cloud.githubusercontent.com/assets/806199/9458598/edccca5e-4aa4-11e5-99a3-5322e90d9a64.png)

**Comment by psychobunny** [comment]
Weird. Can you report your theme version and core hash? If the site is live please post a link so we can check it out

**Comment by bwang29** [comment]
Alright, just did some more test. This is only happening when log in as admin.

**Comment by psychobunny** [comment]
Ah, I didn't realize you're on our hosting plan. I notice your instance isn't running into this issue anymore, let me know if you do.

As I said in another issue, the best place to contact us is via the support ticket system in the back end, this way we can prioritize support for you. Thanks :)

**Comment by julianlam** [comment]
Hello @bwang29, are you still having issues with your NodeBB?

**Comment by psychobunny** [comment]
It seems like it works, if not feel free to send us an email :)
