### ISSUE TITLE
User can not create a new post. 

### ISSUE THREAD

**Issue by bwang29** [NodeBB/NodeBB#3487]
To try:

Go to http://polarr.nodebb.com
Create a new user
Go to any category
Click on 
![image](https://cloud.githubusercontent.com/assets/806199/9458691/481d2aca-4aa6-11e5-9eb4-a67550fbc013.png)

Nothing happens..no console logs, no error or warnings.

Note this is also happening to admin.  The site is just freshly setup with a $100 plan.

Tested with the latest Chrome and Firefox, non private browsing - cookie and everything enabled.

**Comment by barisusakli** [comment]
Thanks for reporting we are looking into it.

**Comment by barisusakli** [comment]
Should be resolved now thanks for reporting again.

**Comment by psychobunny** [comment]
Sorry about that! We also do have an internal support ticket system on the control panel, that's probably your best bet for getting our attention ASAP.

**Comment by barisusakli** [comment]
@bwang29 did you by any chance disable the composer-default plugin from the ACP?

**Comment by bwang29** [comment]
This is resolved! Thank you.

**Comment by julianlam** [comment]
Excellent, thanks @bwang29 !
