### ISSUE TITLE
The category settings do not have a image background field although it allows to adjust background-size attribute for the image. 

### ISSUE THREAD

**Issue by bwang29** [NodeBB/NodeBB#3492]
![image](https://cloud.githubusercontent.com/assets/806199/9481325/127fd0d2-4b3e-11e5-8514-20762f58d779.png)

**Comment by barisusakli** [comment]
Is there no upload button on the right side ?

![image](https://cloud.githubusercontent.com/assets/2583394/9484705/b31364f2-4b7d-11e5-982f-579a31dd6b5d.png)

**Comment by bwang29** [comment]
Thanks @barisusakli I thought the upload is for the icon.

**Comment by psychobunny** [comment]
Thanks for pointing that out though. We'll change that to "Upload Image" instead so its more obvious :)

**Comment by barisusakli** [comment]
Yeah I updated the text to Upload Image, you can change the icon by clicking it.
