### ISSUE TITLE
meta.depencies.check problem

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3493]
Once you install nodebb you will have a specific version for a plugin in package.json, for example  2.0.23 then if you upgrade the plugin to 2.0.24 through the ACP and try to reload/restart the dependency check fails(since in package.json its still 2.0.23) and nodebb doesn't start anymore.

**Comment by julianlam** [comment]
Already resolved via edba11f3885acd1cc70c2a6bd4552ae06491c3bb
