### ISSUE TITLE
Lang attribute value should use a hyphen instead of an underscore

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3499]
`<html lang="en_GB">`

Should really be:

`<html lang="en-GB">`

Ref: https://tools.ietf.org/html/rfc5646#section-2.1

**Comment by julianlam** [comment]
We follow the locales as specified by Transifex.

**Comment by henrywright** [comment]
The locales are OK I think. It's just the syntax that needs changing in the HTML (underscore to hyphen).

**Comment by psychobunny** [comment]
Is that the only change, for all languages?

**Comment by henrywright** [comment]
Yes, I used `en_GB` as an example but the same will apply to `en_US` etc.
