### ISSUE TITLE
Problems on upgrade plugin via admin panel

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [NodeBB/NodeBB#3500]
I have ubuntu server , running nodebb 0.7.1

Via the admin panel Whenever i upgrade the plugins , it shows it as updated (hides the upgrade icons below the plugin)

I did nodebb upgrade here is what i get

26/8 17:45 [4049] - info: [database] Checking database indices.
26/8 17:45 [4049] - info: Beginning database schema update
26/8 17:45 [4049] - info: [2015/02/08] Clearing reset tokens skipped
26/8 17:45 [4049] - info: [2015/02/17] renaming home.tpl to categories.tpl skipped
26/8 17:45 [4049] - info: [2015/2/23] Activating NodeBB Essential Rewards - skipped
26/8 17:45 [4049] - info: [2015/02/24] Upgrading plugins:active to sorted set skipped
26/8 17:45 [4049] - info: [2015/02/24] Upgrading privilege groups to system groups skipped
26/8 17:45 [4049] - info: [2015/02/25] Upgrading menu items to dynamic navigation system skipped
26/8 17:45 [4049] - info: [2015/05/07] Upgrading uid mappings to sorted set skipped
26/8 17:45 [4049] - info: [2015/05/08] Fixing emails skipped
26/8 17:45 [4049] - info: [2015/05/11] Updating widgets to tjs 0.2x skipped
26/8 17:45 [4049] - info: [2015/05/20] Adding username:sorted and email:sorted skipped
26/8 17:45 [4049] - info: [2015/06/02] Creating group sorted sets skipped
26/8 17:45 [4049] - info: [2015/07/03] Enabling default composer plugin skipped
26/8 17:45 [4049] - info: [upgrade] Schema already up to date!

After this when I refresh the plugins page , I see that no plugins have been upgraded, why is this happening ?

**Comment by julianlam** [comment]
It is not a problem. It is intentional, as you should not upgrade plugins past their recommended versions. 

This has been resolved for 0.7.4
