### ISSUE TITLE
Form action attribute must have a non-empty value

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3501]
According to the [HTML 5 spec](http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-fs-action), the form `action` attribute must have a non-empty value.

The templates affected are:

 - src/views/admin/footer.tpl

**Comment by barisusakli** [comment]
We cant really set an action there because it is set in javascript when the upload modal is opened.

Maybe the modal can be an partial that we load when the modal needs to open.

**Comment by henrywright** [comment]
Does HTML 5 permit us to remove the action attribute altogether? It might do, I'm not sure

**Comment by barisusakli** [comment]
>The action and formaction content attributes, if specified, must have a value that is a valid non-empty URL potentially surrounded by spaces.

I think we are good, we don't specify it in the html, but we set it before we submit the form.
