### ISSUE TITLE
Random notification translate bug

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3503]
I´m getting some bug on notifications on last 0.7.3
sometimes getting something like this
[[notifications:user_posted_topic, instead of the translated text
cleared all cache but still in trouble
tried all themes

![captura de pantalla 2015-08-27 a las 4 02 06](https://cloud.githubusercontent.com/assets/10746278/9510845/976c7236-4c70-11e5-9501-b9f4f69d262f.png)

**Comment by julianlam** [comment]
Hopefully resolved already by @psychobunny :smile: Can you please try running latest master? 

Alternatively, we'll launch 0.7.4 tomorrow (or maybe it will be 0.8...)

**Comment by martyalicante** [comment]
i try to stick with stable version right now but i can try tomorrow
 if is 0.8 please commit the fix on 0.7.x too :)

**Comment by julianlam** [comment]
Duplicate #3490, although the fix has been pushed to `v0.7.x`
