### ISSUE TITLE
Updating the nodebb-plugin-composer-default crashes NodeBB v0.7.3

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/NodeBB#3506]
Upon upgrading the over mentioned plugin and restarting NodeBB, I'm getting the following log output:
```
[outdated] nodebb-plugin-composer-default v1.0.12, requires 1.0.9
27/8 15:12 [14356] - warn: One or more of NodeBB's dependent packages are out-of-date. Please run the following command to update them:
27/8 15:12 [14356] - warn:     ./nodebb upgrade
[cluster] Child Process (14356) has exited (code: 0, signal: null)
```
and as a result the NodeBB doesn't launch. The only workaround seems to run `./nodebb upgrade` and never upgrade `nodebb-plugin-composer-default` again.

**Comment by julianlam** [comment]
Don't upgrade it. There's a reason the version is set. :smile:

This is resolved in latest core.

**Comment by mrgame64** [comment]
I guess I'll wait for 0.7.4, then...

**Comment by julianlam** [comment]
Yes, please do! We don't recommend upgrading plugins past their recommended versions, and in the case of the ACP, it would often recommend versions newer than that specified in package.json.

At least for bundled packages, the version should stay static as upgrading past may cause compatibility issues.
