### ISSUE TITLE
Filter in ACP/Users to show unvalidated users

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3507]
So they can all be deleted at once

Re: https://community.nodebb.org/topic/950/auto-delete-unverified-accounts

**Comment by henrywright** [comment]
Or perhaps bulk emailed with a reminder?

**Comment by patricksebastien** [comment]
would it be possible to have the redis-cli command to run to manually clean those accounts?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/3436
