### ISSUE TITLE
NavPagination Count not correct on category

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3511]
i have 8606 topics on general category (checked it with paginated mode) but navigation bar is showing 14 more, this makes scrolling not workingl on last page
any way to sort this?
![captura de pantalla 2015-08-28 a las 4 58 29](https://cloud.githubusercontent.com/assets/10746278/9538155/94b774ec-4d41-11e5-80ad-9b10ccdc59c0.png)

**Comment by julianlam** [comment]
Are some topics deleted?

**Comment by martyalicante** [comment]
Sure deleted and or purged

**Comment by barisusakli** [comment]
Redis or mongo?

**Comment by martyalicante** [comment]
mongo

**Comment by barisusakli** [comment]
Can you use the category id and run the following in mongo shell

```
db.objects.count({_key:"cid:<insert_category_id_here>:tids"});
```

**Comment by martyalicante** [comment]
>  db.objects.count({_key:"cid:3:tids"});
8620

**Comment by barisusakli** [comment]
What does this return

```
db.objects.find({_key:"category:3"}).pretty();
```

**Comment by martyalicante** [comment]
> db.objects.find({_key:"category:3"}).pretty();
{
	"_id" : ObjectId("553e2b000dd0f0bdcc9aa375"),
	"_key" : "category:3",
	"cid" : 3,
	"name" : "General",
	"description" : "Un poco de todo.",
	"icon" : "fa-comments-o",
	"bgColor" : "#fda34b",
	"color" : "#fff",
	"slug" : "3/general",
	"parentCid" : 0,
	"topic_count" : 8657,
	"post_count" : 286788,
	"disabled" : 0,
	"order" : 1,
	"link" : "",
	"numRecentReplies" : 1,
	"class" : "col-lg-12 col-md-12 col-sm-6 col-xs-6",
	"imageClass" : "cover",
	"_imported_cid" : 2,
	"_imported_path" : "",
	"_imported_name" : "General",
	"_imported_slug" : "",
	"_imported_parentCid" : "",
	"_imported_disabled" : 0,
	"_imported_description" : "Un poco de todo.",
	"image" : "https://i.imgur.com/oNwI7mu.jpg"
}

**Comment by barisusakli** [comment]
Ok please run

```
db.objects.update({_key: "category:3"}, {"$set": {topic_count: 8620}});
```

**Comment by martyalicante** [comment]
did it
now it show 8620/8620 but the issue didnt dissapeared

after that i did again object count and got different result

> db.objects.count({_key:"cid:3:tids"});
8644

now some examples

paginated mode, 20 per page, 431x20 = 8620
last one seems to be the tomatoe one.
![captura de pantalla 2015-08-30 a las 20 06 39](https://cloud.githubusercontent.com/assets/10746278/9568751/c8b5f19c-4f53-11e5-9a70-82a2b00ad1fa.png)

but this is not oldest post, theres 24 more.
paginated mode, 22 per page. 392x22 = 8624
Now 4 more topics appears after tomatoe.
![captura de pantalla 2015-08-30 a las 20 10 48](https://cloud.githubusercontent.com/assets/10746278/9568758/08842456-4f54-11e5-96cb-0c860eb83965.png)

infinite mode, 20 per page. can find 24 more topics after tomatoe and thats the end
![captura de pantalla 2015-08-30 a las 20 08 21](https://cloud.githubusercontent.com/assets/10746278/9568761/414bd0a4-4f54-11e5-92d4-b8a8e2965be0.png)


should i do another update with 8644?

thank you

**Comment by barisusakli** [comment]
You should stop your forum and get the latest value with

```
db.objects.count({_key:"cid:3:tids"});
```

Then use it to update with

```
db.objects.update({_key: "category:3"}, {"$set": {topic_count: <value_here>}});
```

**Comment by martyalicante** [comment]
solved, thank you very much

**Comment by martyalicante** [comment]
just a question
just moved out some deleted topics from that category to another and i saw the two numbers are different another time.

> db.objects.find({_key:"category:3"}).pretty();
{
	"_id" : ObjectId("553e2b000dd0f0bdcc9aa375"),
	"_key" : "category:3",
	"cid" : 3,
	"name" : "General",
	"description" : "Un poco de todo.",
	"icon" : "fa-comments-o",
	"bgColor" : "#fda34b",
	"color" : "#fff",
	"slug" : "3/general",
	"parentCid" : 0,
	"topic_count" : 8645,
	"post_count" : 286751,
	"disabled" : 0,
	"order" : 1,
	"link" : "",
	"numRecentReplies" : 1,
	"class" : "col-lg-12 col-md-12 col-sm-6 col-xs-6",
	"imageClass" : "cover",
	"_imported_cid" : 2,
	"_imported_path" : "",
	"_imported_name" : "General",
	"_imported_slug" : "",
	"_imported_parentCid" : "",
	"_imported_disabled" : 0,
	"_imported_description" : "Un poco de todo.",
	"image" : "https://i.imgur.com/oNwI7mu.jpg"
}
> db.objects.count({_key:"cid:3:tids"});
8643

should be that way?

**Comment by barisusakli** [comment]
Looks like a bug, I'm looking into it.

**Comment by barisusakli** [comment]
Should be fixed in https://github.com/NodeBB/NodeBB/commit/d23d814154f0a466b18686f694713da44d98af92

You might need to redo the above fix on both categories to fix the topic counts.

**Comment by martyalicante** [comment]
thank you :+1:

**Comment by martyalicante** [comment]
thank you will test it when it goes to stable version :+1:
