### ISSUE TITLE
Infinite mode scroll to post

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3512]
Paginated mode send you to your post after you submit
infinite mode should do similar? is it possible?

thank you

**Comment by julianlam** [comment]
This should already happen. I believe this is a regression.

**Comment by martyalicante** [comment]
what about other themes?

**Comment by psychobunny** [comment]
This only broke on persona. Unless this doesn't work on vanilla, in which case its actually unrelated to the other issue we had with infinite scrolling this past week

**Comment by martyalicante** [comment]
dont think so
just tried latest master with persona and vanilla and no one scroll to post after submit it
