### ISSUE TITLE
How to change CDN server

### ISSUE THREAD

**Issue by Xuchenhao** [NodeBB/NodeBB#3514]
In China , The cdn server is blocked by GFW.
Like https://storage.googleapis.com/code.getmdl.io/1.0.3/material.min.js this url.
So I want to put it to local.
But i changed it in /home/nodebb/public/templates/admin/header.tpl . When I restart NodeBB. It will be restored 
So. How to deal with?
Thank you!

**Comment by julianlam** [comment]
Hello @Xuchenhao -- which theme are you using?

**Comment by Xuchenhao** [comment]
Hello, I am using persona this theme.
And should I need to change it in node_modules/nodebb-theme-persona ?
But I also need to change Admin control panel.
Thank you!

**Comment by julianlam** [comment]
Oh, my apologies, I misread. If you want to change it in the ACP, look at the header file in `src/views/admin`
