### ISSUE TITLE
ACP themes

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#3527]
I was thinking about how Acp skin has changed along the NodeBB path.
A new feature could be to be able to choose in these different released themes.
And to go further. It could be possible to make Acp-only themes.

What do think about this?

**Comment by psychobunny** [comment]
Right now its already possible for people to modify the ACP's theme from a regular theme. But I'm assuming you want the ability to choose a forum theme and a separate ACP theme?

I'll revisit this only if somebody does make an ACP theme, then it would be worthwhile spending the time to build the feature :)
