### ISSUE TITLE
img-responsive within chat

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#3530]
Within the chat
https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/chat.js#L474
as well as the default composer preview
https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer/preview.js#L25
and maybe some other positions you just add `img-responsive` class to all `img` tags (within some container).

Now the problem is that emoji get added this too while they're supposed to be inline.

Since adding `img-responsive` to all images does seem a bit dirty to me I didn't want to just patch some styles to prevent its effect on emoji.
Maybe we should define a class like `not-responsive` and you add a `:not(.not-responsive)` to your selectors instead.

Open for discussion I think.

**Comment by barisusakli** [comment]
yeah that makes sense, I think emoji pliugin should add a not-responsive to its img tags and then we can make the change to the core so it doesnt add img-responsive class.

**Comment by julianlam** [comment]
Didn't @psychobunny do something about this recently? I recall him telling me to add a class to my images served by one of my plugins, and if it had a class, then core wouldn't add img-responsive to it, or something..... 

ring any bells @barisusakli?
