### ISSUE TITLE
Hook request filter:email.send

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#3531]
As discussed some time ago here: https://community.nodebb.org/topic/6248/email-modification-hook

A `filter:email.send` would be great to have.

**Comment by psychobunny** [comment]
If you submit a PR for this hook, we'll more than likely accept it, don't take it the wrong way that I'm closing this! :)

**Comment by frissdiegurke** [comment]
For completeness I link https://github.com/NodeBB/NodeBB/commit/45c446dac0a14ab64714312a544e8387ecfb4af7 here which adds this filter ;)
Thanks @barisusakli
