### ISSUE TITLE
ACP: Delete site logo 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3540]
After uploading one, you cannot remove it.

**Comment by psychobunny** [comment]
Or edit. See OP: https://community.nodebb.org/topic/6423/is-there-a-way-to-remove-the-site-logo-from-the-acp/2

**Comment by julianlam** [comment]
My commit doesn't actually remove the file from disk. Just sets `brand:logo` to "".

**Comment by Ribesg** [comment]
This still doesn't work. I'm on a fresh `0.8.x` install, applied a `0.6.x` `dump.rdb`, used `./nodebb upgrade` and copy-pasted the `uploads` folder. I tried replacing the logo by something else first then remove this one, it still doesn't work.
