### ISSUE TITLE
Dependencies within the source tree

### ISSUE THREAD

**Issue by num-lock** [NodeBB/NodeBB#3544]
Is there a reason for client-side third party things like `jquery`, `chartjs`, `fontawesome` etc. being within the code base (`/public/vendor`), while other things like `socket.io-client` are not, instead of getting everything just via `npm` or even `bower` and add the deployment into the gruntfile?

**Comment by psychobunny** [comment]
It's just how we started things two years ago and sadly just never had the time to refactor it. Don't worry though, we'll be doing this sooner than later. Related:

https://github.com/NodeBB/NodeBB/issues/3543
