### ISSUE TITLE
SSO not work

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3545]
![2015-09-02 23 52 01](https://cloud.githubusercontent.com/assets/465108/9644047/d462db1e-51cd-11e5-9cd3-dd53ba3c9c2a.png)
![2015-09-02 23 51 52](https://cloud.githubusercontent.com/assets/465108/9644049/d759eb28-51cd-11e5-989f-460757b47c5d.png)
![2015-09-02 23 51 37](https://cloud.githubusercontent.com/assets/465108/9644053/d9f9b7d2-51cd-11e5-971e-7813ed0db2dc.png)

Everything worked to upgrade plug-ins.

**Comment by julianlam** [comment]
Upgrade all of the SSO plugins.

**Comment by atomoc** [comment]
NodeBB 0.8.1
![2015-09-03 00 01 01](https://cloud.githubusercontent.com/assets/465108/9644530/40d19514-51cf-11e5-8172-7dc462b6c698.png)
And new problem:
![2015-09-03 00 03 19](https://cloud.githubusercontent.com/assets/465108/9644534/454d50ce-51cf-11e5-8453-a5f9c73db7bc.png)

**Comment by atomoc** [comment]
```
npm install nodebb-plugin-sso-google
npm install nodebb-plugin-sso-twitter
npm install nodebb-plugin-sso-facebook
```
not work

**Comment by julianlam** [comment]
Disable all plugins and enable one by one until you find the broken one.

**Comment by atomoc** [comment]
Broken not found, but all worked! Thanks!
I disable all plugins and enable one by one.
