### ISSUE TITLE
Feature request: moderator approval for the first posts of a new user

### ISSUE THREAD

**Issue by milipili** [NodeBB/NodeBB#3552]
it is easy for a spammer (not a bot, a real person paid to make your life a nightmare) to register and even to validate its email. Whatever your registration type (local, sso-github, sso-facebook...), distinguish a real user from a spammer is often impossible (its login ? its email ?).

Thus we have (at notepad++) a feature request to propose you : instead of requiring approval for new users, it would be best to require approval for the first messages of this user. New users may register at will and may create topics/posts at will. However, for being visible, a moderator should review those messages before moving this user to a white list.

For backward compatibility, this moderation can be ignored for users with enough reputation (2 or 3 would be quite enough from our point of view).

Obviously, this solution may probably not suit to all forums, but in most cases, it is easier to allow new messages (even if they are delayed a bit) rather than removing each spam one-by-one two or three hours later (one-by-one because you have to report akismet)

**Comment by milipili** [comment]
I was thinking to create a plugin for this feature, but I don't know how to hide topics/posts

**Comment by julianlam** [comment]
@milipili If I were to do it, I would just delete the post (not purge!), and add the pid to a moderation queue list. No need to overcomplicate :)

**Comment by julianlam** [comment]
... and I am in favour of this being a plugin, even if it ends up being bundled in the end.

**Comment by milipili** [comment]
Indeed a plugin would be quite far better. I wanted to make a distinction between deleted posts and posts waiting for moderation but if you like this way...

**Comment by julianlam** [comment]
Stylistically it is still possible to distinguish between them. A moderated post would simply be intercepted and have a marker of some sort added to the template data. A client side script could then read this if present, and apply a class accordingly. 

The sky's the limit! :smile:

**Comment by milipili** [comment]
lol oki I will try to create a plugin for that

**Comment by pichalite** [comment]
@milipili try this plugin if you haven't built one already

https://community.nodebb.org/topic/7810/nodebb-plugin-newuser-approval-plugin-for-admins-to-approve-new-users

**Comment by milipili** [comment]
oh that's sounds very nice , thanks :) unfortunately i had to do some work on other projects but this plugin seems definitely to do the job. nice one. it seems it is time to upgrade nodebb :)
