### ISSUE TITLE
Letting advanced search link on seach form

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3553]
let me explain, I wanted to have advanced search button inside search form like this

![captura de pantalla 2015-09-03 a las 20 13 56](https://cloud.githubusercontent.com/assets/10746278/9666786/80d70348-5278-11e5-814a-1c545aec1770.png)

that way i dont need another link jsut for advanced search

right now handleSeach function doesnt allow to do this because of the search input blur will close input box if you click the link

on my install i added 2 lines to manage this on public/src/app.js
#search-advanced is just the button and it doesnt hurts if not present on theme

```
app.handleSearch = function () {
		var searchButton = $("#search-button"), searchFields = $("#search-fields"), searchInput = $('#search-fields input');
		**$('#search-advanced').on('mousedown', function(){
			window.location = "/search";
		});**
		$('#search-form').on('submit', dismissSearch);
		searchInput.on('blur', dismissSearch);
		function dismissSearch(){
			searchFields.hide();
			searchButton.show(); 
};
```
i know this reload page , any idea to make it without reload or include this on the core?

you can test it on exo.do
thank you

**Comment by barisusakli** [comment]
We will probably include this in core @psychobunny

**Comment by barisusakli** [comment]
@martyalicante 
To make it go to search without reload you can do `ajaxify.go('/search');`

**Comment by martyalicante** [comment]
Thank you :)
