### ISSUE TITLE
Organization Features

### ISSUE THREAD

**Issue by wayneworkman** [NodeBB/NodeBB#3556]
Is there any way to request some sort of organization feature for the forums?

Hello - I'm a user of NodeBB over at https://forums.fogproject.org/

My problem is - I’m trying to follow & help with many threads - but I'll click on an unread post and then there’s no way for me to come back to that thread besides to “favorite” it (don’t wanna do that) or bookmark it, or just remember it’s name…

Why can't I have an area like “Actively participating in” or something similar?

Basically - I'm having issues with organizing and coming back to all the threads I'm involved in. When I’m busy at work; things I look at ONCE and reply ONCE to today might be buried in “recent” tomorrow - especially if I click to read an unread post in this thread and then don't reply immediately…

It’s sort of like - once I click on an unread post - I've committed to making a post right then - simply because I don't have an easy way to come back to that thread.

If the developers kindly would, please think of ways for users to organize threads. For instance, in Gmail I can create a label or a folder and then move threads into those - perhaps something similar can be done here? Or perhaps a way to list threads I've been active in AND have had a new post made in them since the last time I've responded - even though I may or may not have read that post.... Just throwing ideas around.

I'm basically asking for organizational features.

**Comment by wayneworkman** [comment]
How about a "Mark for later review" feature? But I'd like for any threads in such a list to automatically be removed from my "Review later" list when I post to them - regardless of posts from others.

Obviously I'd also want to be able to easily see the list of threads that I've marked for later review.

I think this is what I was trying to ask for - but I just didn't know exactly what I was needing. Sorry about that. :-\

**Comment by psychobunny** [comment]
"Mark as unread" is something I really want in. https://github.com/NodeBB/NodeBB/issues/2659

I get what you mean though, sometimes I'm on the train and I read an issue on our forum which I can't solve right away, so I always think I'll be able to address it later on - then I forget. If I could mark as unread at least later in the day when I visit the unread page I know to respond.

This is why I switched away from Google Inbox and back to regular gmail, because they didn't think of implementing that feature either.

**Comment by psychobunny** [comment]
I'm going to close this in favour of #2659, if you think we need a better solution feel free to comment and I'll reopen :)
