### ISSUE TITLE
Links in chat

### ISSUE THREAD

**Issue by jbob182** [NodeBB/NodeBB#3559]
Adding a link in chat will send it to the beginning of the message

E.G. typing "Hey, check out https://forums.fogproject.org/unread" will result in:

"https://forums.fogproject.org/unread Hey, check out"

**Comment by barisusakli** [comment]
.chat-modal .chat-content li.chat-message a {
    display: block;
    float: left;
}

**Comment by psychobunny** [comment]
Didn't realize there was an issue already. Track #3566 instead. Baris is that a fix?

**Comment by psychobunny** [comment]
Nvm track here instead ;)
