### ISSUE TITLE
Chat HTML stripping

### ISSUE THREAD

**Issue by jbob182** [NodeBB/NodeBB#3560]
Chats will automatically strip out tags. 

E.G. "Try using \<b>Test\</b> instead" will result in:
"Try using Test".

In certain cases I would actually want to send the user text contain a tag (not formatted, just the plain text with the tag included).

**Comment by julianlam** [comment]
You'll want to use back ticks to denote content to be unescaped

**Comment by julianlam** [comment]
e.g. `test <b>`

**Comment by jbob182** [comment]
Back ticks do not work in chat, nor do standard markdown escapes.

**Comment by mastacontrola** [comment]
This does not work.
Back ticks with `<test>` or `<b>` do not work.  It leaves only the back ticks.

**Comment by barisusakli** [comment]
Happens here https://github.com/NodeBB/NodeBB/blob/master/public/src/client/chats.js#L187

**Comment by julianlam** [comment]
What, seriously? Was this in place before we started parsing chat messages as posts?

This _explains so much of why formatting goes wonky in chat **sometimes**_...

I feel we should remove this line (assuming it doesn't expose us to any XSS vulnerabilities...)

**Comment by mastacontrola** [comment]
I think XSS should be safe, if you can reparse the tags as htmlentities and let the browser handle the coding of it.  Then again, I'm not too familiar with node.js coding yet.

**Comment by julianlam** [comment]
Should be safe as parsing as post should escape them (well, the plugins do
anyway).
