### ISSUE TITLE
Angular not loaded with nodebb plugin

### ISSUE THREAD

**Issue by ricoud** [NodeBB/NodeBB#3567]
Angularjs doesn't load when included in a plugin since 0.7.0. Everything was fine with 0.6.1
Here is a basic plugin example [nodebb-plugin-angtest](https://github.com/ricoud/nodebb-plugin-angtest) that shows the problem.
When you click the navbar icon (added through ACP general navigation) angular plugin page is loaded but angular is not active (not loaded?). If you refresh the page F5 or reload it everything works.
I tried to use filter:scripts.get hook and also to include angular.js inside the scripts object of the js.js file find in src/meta directory but the behaviour is the same.

**Comment by barisusakli** [comment]
Is your app.js getting loaded at all?

**Comment by barisusakli** [comment]
I don't think you need [this](https://github.com/ricoud/nodebb-plugin-angtest/blob/master/library.js#L16) if you have template file in the plugin it will get rendered

**Comment by ricoud** [comment]
Looks you're right app.js is also not loaded. Do not understand why? It was working nicely with 0.6.1. Removing the line you propose didn't change the behaviour. Any idea why my client scripts are not loaded when clicking on the navbar icon. Thanks in advance.

**Comment by barisusakli** [comment]
Ok so you need to defined a requirejs module in app.js with the same name as the as your template in this case `angular-test`. Then it should be loaded when you ajaxify from page to page.

**Comment by ricoud** [comment]
Not fully sure to understand what I should do. Can you please show me an example.

**Comment by barisusakli** [comment]
I placed an `alert('hello')` in your app.js and I got the alert so its clearly loading. Did you activate the plugin from the acp?

Also maybe wrapping everything in app.js in a `$(document).ready()` might fix your problem.

```
'use strict';
$(document).ready(function() {
    alert('loading angular');
    var myApp = angular.module('myApp',[]);

    myApp.controller('myCtrl', ['$scope',function($scope) {
         $scope.firstName= "John";
         $scope.lastName= "Doe";
    }]);
});
```

**Comment by barisusakli** [comment]
Also here is a sample app.js for use with requirejs and the ajaxify system in nodebb

```
'use strict';
define('angular-test', function() {
	var myModule = {};

	// called by nodebb ajaxify.js whenever you go from page to page
	myModule.init = function() {
		
		// init angular? not sure if you want to do this everytime user goes from page to page
		// if not move it out of myModule.init
		var myApp = angular.module('myApp',[]);

		myApp.controller('myCtrl', ['$scope',function($scope) {
			$scope.firstName= "John";
			$scope.lastName= "Doe";
		}]);
	};

	return myModule;
});
```

**Comment by ricoud** [comment]
I place a ```console.log('hello');``` in my app.js. When I call the page by entering the page address in the browser everything works. But when I include a link in Nodebb navbar through ACP/General/Navigation and then call the page through this link: it doesn't work.

Then I tried the two solutions you proposed but in both cases I have an angular error 
```Error: [$injector:modulerr] Failed to instantiate module myApp due to:
    [$injector:nomod] Module 'myApp' is not available! ```
even when I type directly the address in the browser.

It seems to me that the problem is related through the way a page is called when you click on the nodebb navbar.

Thanks for your help.

**Comment by barisusakli** [comment]
Yeah not sure why your angular module doesn't load. If you move the `angular.module` call it will load but then when you ajaxify from page to page it won't reinitialize the angular modules from what I can see. Not sure if there is a way to reinit angular after the content has been removed.

You can give it a shot with the following app.js

```
'use strict';
var myApp = angular.module('myApp',[]);
myApp.controller('myCtrl', ['$scope',function($scope) {
    $scope.firstName= "John";
    $scope.lastName= "Doe";
}]);

define('angular', function() {

    var module = {} ;

    module.init = function() {
        console.log('ajaxifying to page angular')
    };

    return module;
})
```

**Comment by ricoud** [comment]
Thanks for your help, but unfortunately this doesn't work. With this script there is no error but the behaviour it still same, need to reload the page to have it working.
Just to remind you that the script works perfectly with nodebb v0.6.1. The problem comes with v0.7.0 and the new way to include route in the navbar.

**Comment by barisusakli** [comment]
Adding routes to the navbar doesn't change the way nodebb loads pages when you navigate around.

You can just put a link into a post like `[angular](http://myforum.com/angular)` and it is identical to a link in the navbar. Not sure why it works in 0.6.1 do you have a forum on 0.6.1 with the plugin installed that works? Maybe post a link to it.

**Comment by ricoud** [comment]
Same behaviour with a link in a post. Unfortunately I do have forum installed. I currently working on a forum which works with a site. My wish is to include the site as a nodebb angular plugin that will call node webservices.
