### ISSUE TITLE
Technical text in code pages

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3569]
"Internal error.Oops! Looks like something went wrong!Upload pictureUpload a pictureYou may only upload PNG, JPG, or GIF files () SuccessCloseUpload picture"

You can remove the text from the code?

**Comment by atomoc** [comment]
It would be really great! :)

**Comment by psychobunny** [comment]
Sorry, not sure what you mean here. Can you re-explain please? :)

**Comment by atomoc** [comment]
[Tadam!](https://www.google.ru/search?newwindow=1&safe=active&client=ubuntu&espv=2&biw=1280&bih=937&q=site%3Acommunity.nodebb.org+Internal+error.Oops%21&oq=site%3Acommunity.nodebb.org+Internal+error.Oops%21&gs_l=serp.12...16532.16532.0.17163.1.1.0.0.0.0.37.37.1.1.0....0...1c.1.64.serp..1.0.0.M3Az3yZVQko) :)
