### ISSUE TITLE
Integrate cla-assistant 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3570]
As pointed out by @ApfelUser

> Since you're not using CLAHub anymore. (I suspect due to the errors and downtimes) I wanted to inform you that there is a new app from SAP called cla-assistant which you can even self-host if you don't trust them. It even integrates like Travis CI with GitHub as status check. Pretty neat in my opinion, you might want to try that out.

Looks pretty good to me!

**Comment by ApfelUser** [comment]
+1
