### ISSUE TITLE
Can not do npm i with vs2014 because mmmagic -> libmagic has issues

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [NodeBB/NodeBB#3571]
I have already posted the issue over at mmmagic but I supposed you might want to be aware of it as well. With vs2014 (2015 version) there seems to have come some new function which causes compile errors if not handled. This SO answer seems to make sense: http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti

In any case, when doing a clean npm i after git clone of NodeBB I get errors and can not finish with the npm i.

![](http://i.imgur.com/VVTrv34.png)

I'm not sure how to fix this...
Here is my mmmagic issue report:
https://github.com/mscdex/mmmagic/issues/57

**Comment by DominikDitoIvosevic** [comment]
You should target the newer 0.4.0 mmmagic version if possible because it is supporting vs2015

**Comment by julianlam** [comment]
Thanks @DominikDitoIvosevic
