### ISSUE TITLE
After upgrading to 0.8.1 categories page is empty

### ISSUE THREAD

**Issue by HorusGoul** [NodeBB/NodeBB#3572]
Hi, after upgrading my forum I can't see any category neither in /categories section nor in the index but in administration are displayed.

![](https://cloud.githubusercontent.com/assets/6759612/9719106/d27cdf90-5581-11e5-96a0-9553eaa252b3.png)
![](https://cloud.githubusercontent.com/assets/6759612/9719107/d292017c-5581-11e5-88ff-3358bd51d82f.png)
![](https://cloud.githubusercontent.com/assets/6759612/9719108/d296faba-5581-11e5-9d4f-9e972687ef14.png)

**Comment by barisusakli** [comment]
Do they have the find/read permissions setup properly?

**Comment by HorusGoul** [comment]
@barisusakli Yep, all categories have permissions.

**Comment by julianlam** [comment]
Do they fix themselves if you edit the category and select a parent category (or select no parent category)?

**Comment by HorusGoul** [comment]
@julianlam Thank you so much, all seems to work! :clap:
