### ISSUE TITLE
Update cache buster when switching themes

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3573]
Right now cache buster is based on git hash, which works fine when upgrading. Not as good when switching themes or installing plugins. I suggest modifying cache buster algo to just generate a new one every time forum restarts or reloads

**Comment by julianlam** [comment]
Cache buster is generated by looking at the core commit hash.

Best to just randomly generate one (generateUUID?) instead.

**Comment by julianlam** [comment]
* [x] Update to use cache buster instead of css and script busters
* [x] Update to re-generate buster on app start
* [ ] Ensure that on dev mode, files are generated with immediate expiry
* [ ] Ensure that on production, files are generated with a proper expiry
