### ISSUE TITLE
"Participated" indicator

### ISSUE THREAD

**Issue by wayneworkman** [NodeBB/NodeBB#3577]
Right now, going through the "recent" list and looking at all of the "Unsolved" titles, it'd also be incredibly helpful if there was some sort of indicator that I have participated in that thread... or any thread for that matter.

This comes back to the "organization features" I requested the other day. I'm looking for some method to come back to a thread that I've visited before (and have participated in) but perhaps haven't recently reply to.

Also, what if the "mark as unread" feature is implemented as aforementioned, what if I forget to mark a thread as unread? Just simply knowing if I've participated or not would be incredibly helpful.

It doesn't need to be anything fancy... a star, a certain coloring, maybe stick my avatar on it beside the author's avatar... anything.

Thanks for you consideration and thank you for creating a great platform for so many communities to help users through!

**Comment by julianlam** [comment]
We already track view state for the topic, although it is not shown in Persona (afaik, maybe I'm wrong @psychobunny ?)

**Comment by martyalicante** [comment]
i have it on my forum, but it requires, a plugin and a modification on template..

**Comment by martyalicante** [comment]
i have it on my forum
something like this
pencil button indicate you replied on that thread and fire means that thread is popular, more than X posts

![captura de pantalla 2015-09-15 a las 23 40 22](https://cloud.githubusercontent.com/assets/10746278/9890973/696d4a2a-5c03-11e5-889f-93e7121602a1.png)

problem
it requieres plugin and modifications on template, should be nice on core tho

**Comment by julianlam** [comment]
I think this is implemented already (blue stripe to the left of a topic when unread)

**Comment by martyalicante** [comment]
What you mean @julianlam
