### ISSUE TITLE
SSOs UI cosmetics

### ISSUE THREAD

**Issue by Fastidious** [NodeBB/NodeBB#3579]
See:

![screen shot 2015-09-09 at 11 28 02 am](https://cloud.githubusercontent.com/assets/8352292/9766351/63fda502-56e6-11e5-934f-d88127b7c9ee.png)

![screen shot 2015-09-09 at 11 28 15 am](https://cloud.githubusercontent.com/assets/8352292/9766352/67b9ddfa-56e6-11e5-8ea8-584d3ceffd65.png)

![screen shot 2015-09-09 at 11 28 26 am](https://cloud.githubusercontent.com/assets/8352292/9766354/6a77c098-56e6-11e5-8d75-4eda876d4f1b.png)

**Comment by julianlam** [comment]
julianlam/nodebb-plugin-sso-github@ea738a5148dfbfd42caf5b29371d7489d486b723
