### ISSUE TITLE
zoom issue with composer on ipad (safari)

### ISSUE THREAD

**Issue by EvaLok** [NodeBB/NodeBB#3580]
a user is reporting unexpected behaviour on ipad (safari) when trying to post/reply. any idea what might cause this? it appears to be some sort of zoom issue. got the user to restart device, log out / log in, and try two different skins.. no luck.

screenshots:
(on click of post or reply - typing produces no visible effect, just see white..)
![image1](https://cloud.githubusercontent.com/assets/12283250/9768565/b32fa1ca-56e1-11e5-93fc-8c4a4c499a26.png)

(after zooming out..)
![image3](https://cloud.githubusercontent.com/assets/12283250/9768577/c7042360-56e1-11e5-8546-91bfcbe79c44.png)

**Comment by EvaLok** [comment]
user reported resolved.. i guess some sort of browser setting or something that would be very tough to troubleshoot.. closing..

**Comment by psychobunny** [comment]
Actually, any chance you can ask the user about those settings? Another person has reported this as well: https://github.com/NodeBB/NodeBB/issues/3521

**Comment by EvaLok** [comment]
@psychobunny unfortunately the user just responded that sometimes safari acts a bit strangely on some sites. and couldn't be more specific than that. however, that would point to the issue being with safari as opposed to the composer, if that's any help to know for you..
