### ISSUE TITLE
Missing breadcrumbs

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3590]
The breadcrumb trail #3475 has just been introduced to pages that didn't have it :+1:  

I noticed these pages are lacking a third-level. For example: Home > Popular > __Monthly__

 - https://community.nodebb.org/popular/daily
 - https://community.nodebb.org/popular/weekly
 - https://community.nodebb.org/popular/monthly
 - https://community.nodebb.org/popular/alltime

These pages seem to be lacking a second-level. For example: Home > __Users__ > Online

 - https://community.nodebb.org/users/online
 - https://community.nodebb.org/users/latest
 - https://community.nodebb.org/users/sort-posts
 - https://community.nodebb.org/users/sort-reputation
 - https://community.nodebb.org/users/map
 - https://community.nodebb.org/users/search

**Comment by barisusakli** [comment]
I did this on purpose because there is no /users page it redirects to /users/online same with /popular it defaults to /popular/daily. Open to suggestions

**Comment by henrywright** [comment]
/popular could display "alltime" and you could completely remove /popular/all-time

/users could display "all users" sorted by latest and you could completely remove /users/latest

That could work? Just a suggestion.
