### ISSUE TITLE
Few bugs in the ACP

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/NodeBB#3591]
1) This:
<img width="158" alt="screen shot 2015-09-12 at 15 19 46" src="https://cloud.githubusercontent.com/assets/5879873/9831715/ddc34766-5961-11e5-89f8-0794525ad8fe.png">
appears after pressing the "Install" button twice, and the installation doesn't seem to ever finish until the page is refreshed.

2) The Dashboard page sometimes displays "You are up-to-date" under the NodeBB version more than once, I was unable to reproduce it more than once.

3) The Dashboard page says "Emailer Installed", even though it's not! It was until the update to v0.8.1 (from v0.7.4), but after the upgrade the emailer plugin was removed, as it wasn't marked as compatible in the plugin's .json file.

**Comment by barisusakli** [comment]
#3 is related to emoji see https://github.com/frissdiegurke/nodebb-plugin-emoji-extended/issues/28

Not sure about #2

**Comment by psychobunny** [comment]
I couldn't reproduce the second either. Perhaps open a new issue if you can get it to break again?

**Comment by mrgame64** [comment]
@psychobunny Will do
