### ISSUE TITLE
daily cron backup -- what all to backup?

### ISSUE THREAD

**Issue by koolnez** [NodeBB/NodeBB#3596]
Hi

I'm relatively new to administering servers, would appreciate some help.

I have NodeBB running on Openshift and would like to take daily backups to Amazon S3. I'm using the Nodejs and Redis cartridges.

Where is all the data stored? What is stored in Redis? What files should I backup using the cron service available on Openshift?

Are there any examples / documentation?

Thanks in advance.

**Comment by barisusakli** [comment]
https://community.nodebb.org/topic/6502/daily-cron-backup-what-all-to-backup
