### ISSUE TITLE
scrolltoPost on new posts

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3597]
is really disturbing that while you reading a post if someone reply in that thread, the page will scroll till new post
in big forums is a big headache, you have to go back to where you were reading everytime
i´m talking about this line of code
https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic/posts.js#L41

what do you think?

**Comment by MegaGM** [comment]
Maybe just try something classical like  `if [ scrollTop -gt something ]; then doScrollMagic`? And if not, then not :yum:

**Comment by martyalicante** [comment]
what is -gt?

**Comment by MegaGM** [comment]
@martyalicante It's just a common comparison operator in some languages: "greater than"
http://www.tldp.org/LDP/abs/html/comparison-ops.html

**Comment by barisusakli** [comment]
Should only scroll if you are the one posting

**Comment by martyalicante** [comment]
yeah @barisusakli that was solved in this line and working good https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic/posts.js#L35
