### ISSUE TITLE
filter:user.settings and filter:user.getSettings are duplicates

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3606]
.... sort of.

`.settings` is fired only in the `/user/settings` controller, while `.getSettings` is fired whenever user settings are called site-wide.

However, both hooks alter user settings, and `.settings` additionally adds a new property called `customSettings`.

Seems as though `.settings` is better off deprecated/removed as the same can be accomplished by `.getSettings`.

**Comment by barisusakli** [comment]
`filter:user.settings` should be renamed to `filter:user.customSettings` it is used to add html etc into the `/user/settings` page
