### ISSUE TITLE
New posts mark as read but doesn't appear

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#3613]
I noticed this a long time ago but wasn't sure.
I'm now pretty confident.

When a new post arrive in a topic you are already in, it's marked as viewed.
This can be normal behaviour, except the post doesn't show up.

In a previous issue, I was told that some websockets are closed after 5 minutes or so if you let the page open.
I suspect it's related with this.

This leads to a post marked as viewed, even if you didn't see it.

**Comment by julianlam** [comment]
This writeup makes sense to me (in that I believe your analysis is correct). 

Whether or not the topic is marked read is governed by some logic on the server side, and it may be possible that an inactive session may still be a member of a socket.io room...

**Comment by barisusakli** [comment]
>When a new post arrive in a topic you are already in, it's marked as viewed.
I don't think this is the case anymore, it is marked as read when you scroll down if you are using infinite scroll, it is not marked as read if you are in pagination mode.
