### ISSUE TITLE
[Enhancement] Let user select homepage

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3616]
Same as admin but on user profiles
![captura de pantalla 2015-09-15 a las 23 44 05](https://cloud.githubusercontent.com/assets/10746278/9891049/dc707c0e-5c03-11e5-87e2-ff7ef2e1f4b8.png)

**Comment by HorusGoul** [comment]
So good :+1:

**Comment by yariplus** [comment]
I can do.

**Comment by julianlam** [comment]
Done and merged, thanks @yariplus !
