### ISSUE TITLE
chat modals dont have timestamps

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3617]
works in the chat page at `/chats/<username>`

![image](https://cloud.githubusercontent.com/assets/2583394/9891838/745cac4a-5bd7-11e5-8727-95b851949c4e.png)

**Comment by psychobunny** [comment]
> this is a test message. does it work? yes so what? 

Stop talking to yourself :p

**Comment by barisusakli** [comment]
I'm lonely :frowning:
