### ISSUE TITLE
Skin pick reset

### ISSUE THREAD

**Issue by Fastidious** [NodeBB/NodeBB#3622]
As an administrator, while logged on the Dashboard, once a skin is set, there isn't a way currently (correct me if wrong) to reset it, that is, to pick *none*. The only way to "get rid" of a skin is to change themes back and forth.

There should be a setting under "Skins" to choose "None," to stay with what comes with the theme alone.

**Comment by psychobunny** [comment]
![](http://i.imgur.com/UeyNfGA.png)

^ That's a revert button :P

**Comment by barisusakli** [comment]
wurst UX :+1:

**Comment by Unknwon** [comment]
Click on this button does exactly nothing.

**Comment by Unknwon** [comment]
How can I reset by changing database?

**Comment by psychobunny** [comment]
Did you restart after clicking that button? Please open a new issue, thanks
