### ISSUE TITLE
jquery.timeago.it-short.js missing for jquery timeago plugin

### ISSUE THREAD

**Issue by jenkin** [NodeBB/NodeBB#3624]
Hi, in version 0.8.2 (fresh installation) the file *jquery.timeago.it-short.j* in vendor directory *public/vendor/jquery/timeago/locales/* is missing, but it seems to be requested by nodebb.min.js (with response 404 not found).

**Comment by julianlam** [comment]
This is normal (if a little weird). We request the load of this file, if it exists, and if not, we fall back to using English. 

You can see [here] (https://github.com/rmm5t/jquery-timeago/tree/master/locales) that there is no file for Italian short strings. 

Feel free to make a pull request to add it in their repository though! :smile:

**Comment by jenkin** [comment]
Ah, ok, sure, I can do that... :) Thanks!

**Comment by jenkin** [comment]
Et voilà! https://github.com/rmm5t/jquery-timeago/pull/237#event-412153409 :)
