### ISSUE TITLE
Performance issues with f.lux

### ISSUE THREAD

**Issue by amatmv** [NodeBB/NodeBB#3628]
As you know, in f.lux,  every so often the warmth decreases 1k of the unity. When this happens make the OS X mouse shutter a bit, like doing jumps, and it's kinda annoying. 
You should fix the performance problem around f.lux, otherwise it can be tiring.

**Comment by psychobunny** [comment]
This only happens when nodebb is running?

**Comment by amatmv** [comment]
What is nodebb?

**Comment by julianlam** [comment]
You don't know what NodeBB is?

**Comment by amatmv** [comment]
What is the relation with f.lux?

**Comment by julianlam** [comment]
There isn't one, so I'm thinking you may have reported a bug with the wrong project :smile:
