### ISSUE TITLE
Dangling category child links cause crash

### ISSUE THREAD

**Issue by Tim-Tom** [NodeBB/NodeBB#3633]
I'm not sure of the exact steps that led to this state, but somehow during category deletion, the parent categories link to the child were not removed (cid:{parent}:children). When the children are then fetched by the application, this results in a null category and a crash in getChildrenRecursive.

It was found on a6c8cd50e97c5761fd07b19980ec46339840004a but confirmed to exist at the current head of master (da9a6ba3993459b95f3e21e84e5cddbc09efa50e).

The simplest fix should be to add a guard before recursing into getChildrenRecursive to only call it if child is not null.

**Comment by barisusakli** [comment]
Can you add the full crash log.

Also do you have repro steps on master?

AFAIK on category deletion we remove the category from its parents children set and set all the children back to 0.

**Comment by Tim-Tom** [comment]
Here's the reported error and stack trace (from a6c8cd50e97c5761fd07b19980ec46339840004a). I could easily reproduce in in the database by putting an incorrect record like {"cid:1:children": 100000}, but I don't know how the users caused the original child category deletion to not proceed properly.

    17/9 22:23 [64504] - error: TypeError: Cannot read property 'cid' of null
      at async.waterfall.category.children (/var/www/nodebb/src/categories.js:330:43)
      at fn (/var/www/nodebb/node_modules/async/lib/async.js:717:34)
      at /var/www/nodebb/node_modules/async/lib/async.js:1170:16
      at /var/www/nodebb/node_modules/async/lib/async.js:172:37
      at /var/www/nodebb/node_modules/async/lib/async.js:677:43
      at /var/www/nodebb/node_modules/async/lib/async.js:173:37
      at Object.async.waterfall (/var/www/nodebb/node_modules/async/lib/async.js:681:44)
      at getChildrenRecursive (/var/www/nodebb/src/categories.js:328:9)
      at /var/www/nodebb/src/categories.js:345:6
      at /var/www/nodebb/node_modules/async/lib/async.js:187:20
    TypeError: Cannot read property 'cid' of null
      at async.waterfall.category.children (/var/www/nodebb/src/categories.js:330:43)
      at fn (/var/www/nodebb/node_modules/async/lib/async.js:717:34)
      at /var/www/nodebb/node_modules/async/lib/async.js:1170:16
      at /var/www/nodebb/node_modules/async/lib/async.js:172:37
      at /var/www/nodebb/node_modules/async/lib/async.js:677:43
      at /var/www/nodebb/node_modules/async/lib/async.js:173:37
      at Object.async.waterfall (/var/www/nodebb/node_modules/async/lib/async.js:681:44)
      at getChildrenRecursive (/var/www/nodebb/src/categories.js:328:9)
      at /var/www/nodebb/src/categories.js:345:6
      at /var/www/nodebb/node_modules/async/lib/async.js:187:20
    17/9 22:23 [64504] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/32041d50f727b76de87f83da6a05c4b0807ad76e should fix the crash. Let me know if you have repro steps tru the ACP on master.

**Comment by Tim-Tom** [comment]
Patch looks good.
