### ISSUE TITLE
categories acp has extra border

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3637]
github embed adding these?

![image](https://cloud.githubusercontent.com/assets/2583394/9977679/d2ed2bfa-5edd-11e5-9f78-e66c1ded4589.png)

**Comment by julianlam** [comment]
:suspect: ok

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-github-embed/commit/43461e29f5d782f25849629b425e19db568883e5
