### ISSUE TITLE
make imagemagick an optional dependency

### ISSUE THREAD

**Issue by robotanarchy** [NodeBB/NodeBB#3639]
Hello,

I'm running NodeBB and have not installed imagemagick on my system, and I don't really want to add this dependency, because it pulls a huge number of image libraries.

NodeBB always prints a warning, that it can't find the `convert` binary (from imagemagick).

Uploading PNG profile pictures works perfectly, they even get resized!

I've uploaded a GIF and the server crashes though, regardless whether the "convert images to PNG" option is enabled.

So my feature request is:
* when imagemagick is not installed, only allow PNG uploads
* make the installation without imagemagick officially supported

Thanks!

**Comment by julianlam** [comment]
Oh, actually, that warning should be moved out to the ImageMagick plugin. We've transitioned to using the lwip library, although personally a native js lib would be my preference...

**Comment by julianlam** [comment]
The other big deal is lwip **takes freaking forever** to compile. 

May look into [jimp](https://www.npmjs.com/package/jimp) today...  :smile:

**Comment by robotanarchy** [comment]
yep, I'd also have to compile it from source ;)
thanks for the quick answer!

**Comment by robotanarchy** [comment]
+1 for the native JS lib

**Comment by julianlam** [comment]
bac04d7ee6dfc0fb17df6bcea22718dc4a108a54

**Comment by julianlam** [comment]
@Alpacatty If you're interestd in continuing to use lwip, you can create your own fancy plugin for it :smile:

**Comment by Alpacatty** [comment]
@julianlam Eh, only wanted to use lwip to avoid having to install ImageMagick. Compile times didn't use to be so long, for me at least, and native Node modules can break way more frequently anyway so no objection to using Jimp from me.

Did you look at how fast it is, though? I recall you having me write benchmarks before lwip was merged :stuck_out_tongue:
