### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by mastacontrola** [NodeBB/NodeBB#3642]
I don't know if this is fixed in the master branch.

On our forums we are seeing an excessive number of threads being generated per user. Our Apache config worked perfectly for 0.8.1, but since upgrading 0.8.2 we keep losing connection because the maximum number of threads has been reached.

Our error logs are being spammed with:

```
[Mon Sep 21 06:58:06.635678 2015] [proxy:error] [pid 1779:tid 140585929238272] [client 161.51.11.2:24337] AH00898: Error reading from remote server returned by /socket.io/, referer: https://forums.fogproject.org/topic/991/operating-system-not-found-after-imaging-computers
[Mon Sep 21 06:58:06.707677 2015] [mpm_worker:error] [pid 351:tid 140587205535808] AH00288: scoreboard is full, not at MaxRequestWorkers
```

I've already tried adjusting the things it is requesting and as suggested by multiple sites and troubleshooting things, however the only thing that seems to have changed is the version of NodeBB we are running.

Any help in troubleshooting and narrowing down what exactly is causing the problem would be appreciated.

Of course I can provide any other information you may require.

**Comment by julianlam** [comment]
Can you confirm that switching back to the previous version of NodeBB fixes this issue? It seems like your WebSockets are not connected and are dropping back to Ajax polling.

**Comment by mastacontrola** [comment]
We have reverted to 0.8.1 and we are not seeing the same issues any more.

**Comment by mastacontrola** [comment]
That said, we are receiving errors saying Error reading from remote server returned by /socket.io/, but we are not receiving the MaxRequestWorkers error.  I believe this is because the way it looks like sockets are connected is not through a /socket.io/ but rather a query string of transport=socket.io.

My Code that doesn't throw the funny socket.io errors is:

```
        RewriteEngine On
        RewriteCond %{REQUEST_URI} ^/socket.io [NC]
        RewriteCond %{QUERY_STRING} transport=websocket [NC]
        RewriteRule /(.*) ws://127.0.0.1:4567/$1 [P,L]
        ProxyPassReverse /socket.io ws://127.0.0.1:4567/socket.io
        RewriteCond %{REQUEST_URI} ^/ [NC]
        RewriteRule ^/(.*)$ http://127.0.0.1:4567/$1 [P,L]
        ProxyPassReverse / http://127.0.0.1:4567/
```
The Code that does throw these errors is (as per NodeBB's documentation):
```
        ProxyRequests off
        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>
    ProxyPass /socket.io/1/websocket ws://127.0.0.1:4567/socket.io/1/websocket
    ProxyPassReverse /socket.io/1/websocket ws://127.0.0.1:4567/socket.io/1/websocket
    ProxyPass /socket.io/ http://127.0.0.1:4567/socket.io/
    ProxyPassReverse /socket.io/ http://127.0.0.1:4567/socket.io/
```

**Comment by mastacontrola** [comment]
Alright iether config presents the successive /socket.io/ transport issues, That being said, it is still true the 0.8.1 is not causing our server to puke all over itself for connections.

**Comment by julianlam** [comment]
It looks like the `socket.io` dependency [hasn't changed since late 2014](https://github.com/NodeBB/NodeBB/commit/7cbaa90d36e249bc6b2406e37a045c24881eed9b), so even the socket.io version is the same. Are you handy with git? Perhaps you can [use `git bisect` to determine which commit caused this to happen](http://git-scm.com/docs/git-bisect)...

**Comment by barisusakli** [comment]
Upgrading would still upgrade socket.io to 1.3.7 which was released yesterday no?

**Comment by jbob182** [comment]
@julianlam https://github.com/NodeBB/NodeBB/blob/master/package.json#L65 While the dependency hasn't changed you a using "^", so we would be pulling the latest release of it. 

With that said, our v0.8.1 and v0.8.2 installations of Nodebb both use socket.io@1.3.6

**Comment by barisusakli** [comment]
@jbob182 let us know your findings
