### ISSUE TITLE
Shareable Plugin

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3643]
Feature request: would be nice to have some core plugins or library plugins to reuse work across plugins. 

Main idea, it should be convenient for users. 

Use case: several plugins use some unique tech-stack, as a developer, you would like to move this stack to shareable source. Imagine list of activated plugins (order matters):

- nodebb-plugin-ns-core
- nodebb-plugin-ns-awards
- nodebb-plugin-ns-points

etc.

**Comment by julianlam** [comment]
Hi @NicolasSiver I don't understand what you are asking for here...? All of our bundled plugins are open source and you can `require` their libs if the method is exported internally :smile:

**Comment by NicolasSiver** [comment]
It's all about frontend and libraries that are used. 
When you have N plugins, you will find yourself, that they share something. 
Example: by using `async` in your ACP, you should include it with every plugin. Problem is redundancy. 

P.S.
Redundancy on NPM side will be resolved by NPM

**Comment by barisusakli** [comment]
Well if you have 3 plugins that needs to share some code, make an npm module with  that code and put it as a dependency in your 3 plugins. Isn't that solving this problem?

**Comment by NicolasSiver** [comment]
It should be some plugin that will inject frontend library.

Example: all yours plugins use Angular, you would like to create plugin dependency, that will be handled by NodeBB. Main requirement for such plugin: It should be included before dependent plugins and It should be activated if dependent plugins are activated. So you don't need bundle Angular with every your plugin.

**Comment by julianlam** [comment]
Hopefully, this can be handled _better_ if and when we overhaul Require.js, but in the meantime you will have to include the same front-end lib in all of your plugins, much like how both emoji-extended and mentions include the textcomplete lib

**Comment by mralexgray** [comment]
I wish this was possible, as well!
