### ISSUE TITLE
Notifications: HTML

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3647]
Problem with HTML tags in Notifications.
By sending basic html via `bodyShort` as a result you will get markup as text.

Example:

```
notificationObj.bodyShort = 'Some message <strong>important</strong>';
```

Html tags will be printed with text

**Comment by barisusakli** [comment]
Ran into this https://github.com/jprichardson/string.js/issues/76 when trying to fix this. I was going to allow some tags in bodyShort but trying to strip `<script>` also strips `<strong>` so waiting for a fix on string.js.

**Comment by julianlam** [comment]
For best compatibility with other services listening to notifications, like pushbullet etc, I'd suggest sticking with plaintext in notifications.

**Comment by barisusakli** [comment]
I sent a PR to string.js https://github.com/jprichardson/string.js/pull/181

Although it won't fixed this issue since, translator now escapes all html so html won't work in bodyShort anymore.

**Comment by NicolasSiver** [comment]
So, there is no way to provide rich notifications?

How do you produce notifications like this?

<img width="290" alt="screen shot 2016-03-03 at 9 02 50 am" src="https://cloud.githubusercontent.com/assets/135263/13496545/cfe766a0-e11e-11e5-9a93-a3d7a6899c5e.png">

**Comment by barisusakli** [comment]
Sorry shoud have been clearer. The translator escapes html on variables it is fine if its in the string itself like https://github.com/NodeBB/NodeBB/blob/master/public/language/en_GB/notifications.json
