### ISSUE TITLE
when I do a search for a word Create I get the following error.

### ISSUE THREAD

**Issue by ogerly** [NodeBB/NodeBB#3651]
when I do a search for a word Create I get the following error.

     22/9 16:28 [18998] - error: [plugins] filter:search.query,  Unable to execute query: error processing      query: ns=0.searchpost limit=20 skip=0
      Tree: TEXT : query=welt, language=, tag=NULL
      Sort: {}
      Proj: {}
        planner returned error: need exactly one text index for $text query
       22/9 16:28 [18998] - error: /api/search/welt
        MongoError: Unable to execute query: error processing query: ns=0.searchpost      limit=20 skip=0
       Tree: TEXT : query=welt, language=, tag=NULL
       Sort: {}
       Proj: {}
        planner returned error: need exactly one text index for $text query
      at Function.MongoError.create       (/var/www/clients/16/28/web/nodebb/node_modules/mongodb/node_modules/mongodb-      core/lib/error.js:31:11)
      at queryCallback       (/var/www/clients/16/28/web/nodebb/node_modules/mongodb/node_modules/mongodb-      core/lib/cursor.js:267:34)
      at Callbacks.emit       (/var/www/clients/16/28/web/nodebb/node_modules/mongodb/node_modules/mongodb-      core/lib/topologies/server.js:95:3)
      at null.messageHandler       (/var/www/clients/16/28/web/nodebb/node_modules/mongodb/node_modules/mongodb-      core/lib/topologies/server.js:243:23)
      at Socket.<anonymous>       (/var/www/clients/16/28/web/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:748:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:410:10)
      at emitReadable (_stream_readable.js:406:5)
       22/9 16:28 [18998] - error: [plugins] filter:search.query,  Unable to execute query: error processing       query: ns=0.searchtopic limit=20 skip=0
       Tree: TEXT : query=welt, language=, tag=NULL
       Sort: {}
       Proj: {}
        planner returned error: need exactly one text index for $text query

Title and posts Search does not work

People search works ok.

NodeBB 0.8.2

**Comment by barisusakli** [comment]
What is your mongodb version, check the mongo indexes as well.

```
mongo
use <your_database_name>
db.objects.getIndexes();
```

**Comment by ogerly** [comment]
![bildschirmfoto vom 2015-09-28 16 29 54](https://cloud.githubusercontent.com/assets/1324583/10138315/33274876-65fe-11e5-959f-5f914c1c6b7a.png)

**Comment by barisusakli** [comment]
Sorry wrong collection try 

```
db.searchtopic.getIndexes();
db.searchpost.getIndexes();
```

**Comment by ogerly** [comment]
At first glance, they are the same

![bildschirmfoto vom 2015-09-30 11 55 45](https://cloud.githubusercontent.com/assets/1324583/10190042/3db7c5be-676a-11e5-9f8d-7ae5b7615fcf.png)

![bildschirmfoto vom 2015-09-30 11 57 15](https://cloud.githubusercontent.com/assets/1324583/10190072/6cee53e8-676a-11e5-8e4c-e45f1ae2f52e.png)

**Comment by barisusakli** [comment]
What happens when you run 

`db.searchpost.find({$text: {$search: "welt"}});`

**Comment by ogerly** [comment]
### Local
locally I get the results. and it is also seeking the normal
![bildschirmfoto vom 2015-09-30 21 58 47](https://cloud.githubusercontent.com/assets/1324583/10204894/97a48d10-67be-11e5-9e68-c0fef735b156.png)

### Online 

online he probably a problem with the MongoDB. at the beginning when I start mongo come already warnings.


hfp
at HFP there is no total crash of NodeBB ..
![bildschirmfoto vom 2015-09-30 21 59 20](https://cloud.githubusercontent.com/assets/1324583/10204903/a79b73d2-67be-11e5-80a6-c1ac14d33992.png)


sender.fm
at sender.fm there is a total crash of NodeBB
![bildschirmfoto vom 2015-09-30 22 34 48](https://cloud.githubusercontent.com/assets/1324583/10205798/a1378b3e-67c3-11e5-91ab-f159dc73450b.png)

**Comment by barisusakli** [comment]
You can try dropping the db.searchpost and db.searchtopic collections and restarting nodebb and then reindexing from the plugin page. Looks like its a configuration issue.
