### ISSUE TITLE
Add possibility to specify image over a link for a category

### ISSUE THREAD

**Issue by lenovouser** [NodeBB/NodeBB#3652]
In e.g.

https://community.nodebb.org/admin/manage/categories/1

**Comment by ApfelUser** [comment]
Any updates?

**Comment by julianlam** [comment]
Wasn't aware this was not possible :smile:... a category image works if it is a link, no?

**Comment by lenovouser** [comment]
I don't know about now, but back then it was just possible to upload an image. Will check if it changed on the latest master tomorrow. Happy new year by the way! :fireworks: :tada: :confetti_ball: ( At least in Europe :smile: - if not - ahead a happy new year! )

**Comment by psychobunny** [comment]
This works, at least on latest master + persona

**Comment by barisusakli** [comment]
Where do you put the link to the image?

![image](https://cloud.githubusercontent.com/assets/2583394/13279617/d365ad3e-dae1-11e5-933b-523e54c2c60a.png)

**Comment by lenovouser** [comment]
Ohh. I think I was too stupid to explain, but @barisusakli still got it. I meant that you specify a image URL, like `https://i.imgur.com/xxxxxxx.jpg` instead of uploading. You probably understood that I meant to specify a link which is clickable by the user.
