### ISSUE TITLE
Add option to only allow specific languages

### ISSUE THREAD

**Issue by ApfelUser** [NodeBB/NodeBB#3653]
^

**Comment by barisusakli** [comment]
What is the use case for this?

**Comment by ApfelUser** [comment]
I don't want people to be able to select languages on my forum when I don't also have them on my website. For consistency. Also so that the Google Index doesn't display my forum in a language which isn't available on my website.

**Comment by psychobunny** [comment]
> Also so that the Google Index doesn't display my forum in a language which isn't available on my website.

This is impossible because anonymous (including bots) will always see your forum in the default language

**Comment by psychobunny** [comment]
> I don't want people to be able to select languages on my forum when I don't also have them on my website

I don't get why this is a problem. Ex. I went to google.com and they had language X & Y, but then I go to gmail.com and they had language X, Y, & Z. 

So I go to google.com and I have to deal with English but then I go to gmail.com and I get Malaysian, which makes me feel like I'm at home (good UX). It doesn't affect anybody else but me?

**Comment by ApfelUser** [comment]
Hm. I don't like the fact that there are different languages available. I want consistency, but that's just my opinion. I guess we'll put it in our plugin then.
