### ISSUE TITLE
Hardcoded header size in scrollToPost

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3655]
If a theme has a bigger header (or sub header, etc) then scrolling to post will be off by a bit 

Trying to think of the best way for the theme to let core know that value...

**Comment by barisusakli** [comment]
`$('#header').height()`  :trollface:

**Comment by julianlam** [comment]
Hm, isn't this why we have components? :smile:

**Comment by psychobunny** [comment]
This doesn't take into account subheaders and stuff which are independent of the header component

**Comment by psychobunny** [comment]
Basically any theme could declare a position: fixed element independent of header, which will cause this wonkiness

Theme needs to send in a padding height in lieu of `$('#header').height()`

**Comment by barisusakli** [comment]
Can probably get rid of the header height and use .offset() on the post container

https://api.jquery.com/offset/
