### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/NodeBB#3659]
Tooltip for "Tags" is not translated.

![bildschirmfoto 2015-09-23 um 09 22 08](https://cloud.githubusercontent.com/assets/11850083/10040478/5e3275f2-61dc-11e5-8a0f-7d380fdb1076.png)

**Comment by barisusakli** [comment]
Seems like already translated on transifex just needs to be pulled?, @julianlam
