### ISSUE TITLE
new posts can be parsed before they are indexed by search plugins

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3664]
Search plugins use `action:post.save` which is passed the `postData` object. When this hook is fired `postData.content` is not parsed. However this hook doesn't have a callback so execution continues and before the search plugin can index the content `postData.content` gets parsed at https://github.com/NodeBB/NodeBB/blob/master/src/topics/create.js#L287.

If the parsing happens before the search plugin indexing then search results will be wrong.

Gotto make sure other hooks don't suffer from this ie `post.restore` `post.edit`

**Comment by julianlam** [comment]
Heh, this can be worked around (I think) by reordering the search plugin before all plugins... but a better solution would be to update solr so that it uses only tid, not the post content.

**Comment by julianlam** [comment]
Oh, or just pass in a clone of the postData object, not the reference :stuck_out_tongue:
