### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3665]
<img width="428" alt="screen shot 2015-09-23 at 9 36 50 pm" src="https://cloud.githubusercontent.com/assets/135263/10063437/af7cbf4e-623b-11e5-8b06-db9666f3c5a3.png">

**Comment by julianlam** [comment]
Looks like you forgot to run `./nodebb upgrade` :smile:

**Comment by NicolasSiver** [comment]
I just installed them via Admin Panel, by clicking on Upgrade buttons

**Comment by julianlam** [comment]
Well that's not right. Admin panel shouldn't suggest that version for you to upgrade to. 

What version of NodeBB are you on?

**Comment by NicolasSiver** [comment]
I was on 0.8.2.

**Comment by psychobunny** [comment]
Reopening to make sure if this is an issue in ACP upgrading we should look into it
