### ISSUE TITLE
./nodebb upgrade slowness

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3666]
Takes about 2 minutes to run. Repro'd on two Ubuntu boxes and my local Windows. I noticed this issue after this commit https://github.com/NodeBB/NodeBB/commit/bac04d7ee6dfc0fb17df6bcea22718dc4a108a54

@julianlam 

Even running `./nodebb upgrade` a second time, it still takes that long, even though deps are already installed

**Comment by psychobunny** [comment]
Make that three Ubuntu boxes, I just updated our community and it took 2 minutes as well. I'm not sure why this happens TBH

**Comment by barisusakli** [comment]
Maybe post the output of ./nodebb upgrade?

**Comment by psychobunny** [comment]
It gets stuck on 

> 1. Bringing base dependencies up to date...

**Comment by psychobunny** [comment]
With jimp:

![](https://slack-imgs.com/?url=http%3A%2F%2Fi.imgur.com%2FDksBKqT.png&width=1319&height=515)

npm i lwip and removed jimp:

![](https://slack-imgs.com/?url=http%3A%2F%2Fi.imgur.com%2FDksBKqT.png&width=1319&height=515)

Both timings are the same regardless of if the modules were already installed or not, which is the more frustrating part.

**Comment by julianlam** [comment]
Unsure of why npm decided to always recompile lwip, but as we don't use lwip anymore, the upgrades are fine if it is unlinked.

For those coming in with this issue: `npm unl lwip && ./nodebb upgrade`.
