### ISSUE TITLE
Nodebb Fails to connect to Mongo after the master fails over.

### ISSUE THREAD

**Issue by apriendeau** [NodeBB/NodeBB#3670]
Currently, we have to reboot nodebb every time something happens to the node cluster when the master fails over, it would be nice if nodebb could just reconnect to mongo when this happens.

@tyauvil @joshughes

**Comment by Lesterpig** [comment]
According to this [this page](http://mongodb.github.io/node-mongodb-native/2.0/reference/connecting/connection-settings/), the mongodb driver tries 5 reconnection with some delay (5s) between them.

So, NodeBB will lose **silently** the DB connection after ~25 seconds of master outage.

**Comment by joshughes** [comment]
We see nodebb lose connection immediately when a master election takes place. Even when we have configured it for all 3 nodes in our mongodb cluster. Other applications that use the cluster fail over without any service disruption.

**Comment by julianlam** [comment]
Hi there, yes, this is a problem. We've never extensively tested Mongo fail over code, so I believe when the db disconnects, then one of our dependencies throws an error, which isn't caught, which brings down the server. 

Will need to test this and build in code for reconnection and fail over.

**Comment by barisusakli** [comment]
So the 2.2 driver tries 30 times with an internval of 1 second and then gives up, is this time not enough to connect to the new server in the replica set?

autoReconnect also defaults to true so not sure if we should just increase the `reconnectTries` and `reconnectInterval` connection settings

**Comment by Lesterpig** [comment]
`reconnectTries : 3600` seems to be a good choice for me: it's pretty good when an election occurs *and* when the whole cluster is down for maintenance.

Thanks!
