### ISSUE TITLE
categories [bgColor] problem after upgrade

### ISSUE THREAD

**Issue by ogerly** [NodeBB/NodeBB#3681]
I made an upgrade from 0.7.3 to 0.8.2.
that was all ok.

the new start of NodeBB everything was ok.

but when I saw the website aufrufte came a 503 error.

and press F5 when re .. following error occurs in the console.

a categorie has no color.

but I have all entries in the database does not check categorie found where the bgColor missing.

https://i.imgur.com/ARKBReQ.png

I have in the helpers.js the function which the categorie.bgColor is commented out. thus the page is running again.

but it lacks all categorie bgColor.

## public/src/modules/helpers.js : ( at line 77)
             if (category.bgColor) {
			style.push('background-color: ' + category.bgColor);
		}

**Comment by barisusakli** [comment]
Can you post a link to your forum?

**Comment by ogerly** [comment]
http://sender.fm

**Comment by barisusakli** [comment]
Looks like your site is in maintenance mode, can you also post which database you are using.

**Comment by ogerly** [comment]
now

**Comment by barisusakli** [comment]
Yeah I can see it now, there is an `null` category at the end of `/api/categories`

Please post the out of the following from your mongo shell.

```
mongo
use <your_database_name>
db.objects.find({_key: "categories:cid"});
```

**Comment by ogerly** [comment]
![bildschirmfoto vom 2015-09-27 23 53 40](https://cloud.githubusercontent.com/assets/1324583/10125410/08a3653e-6573-11e5-969c-1ba4d7333f6a.png)

**Comment by barisusakli** [comment]
Please run this as well by filling out the categories ids

```
db.objects.find({_key : {$in: ["category:44", "category:43", "category:36", .... so on]}}).pretty();
```

**Comment by ogerly** [comment]
![bildschirmfoto vom 2015-09-28 11 01 00](https://cloud.githubusercontent.com/assets/1324583/10131393/4e1bece6-65d0-11e5-85fe-a741984eaf24.png)
![bildschirmfoto vom 2015-09-28 11 01 20](https://cloud.githubusercontent.com/assets/1324583/10131399/56f2efc2-65d0-11e5-9ed0-54af0aa96fb5.png)
bgColor is everywhere.

**Comment by barisusakli** [comment]
Really hard to find anything in those pics, can you put the output to a text file. Also I don't see category:2 in there.
