### ISSUE TITLE
RFC: Necro-prevention

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3693]
I just got an upvote for a post I made 11 months ago :laughing: 

Which got me thinking -- should we have a customisable set of rules built into core that limit topic/post interaction after a set timeout? We have (had?) a plugin that auto-locked topics after a given date, so that could be incorporated into core.

In addition, limiting upvotes seems to be a good thing to add...

**Comment by jacobbridges** [comment]
Well, I understand that having an old thread pop back into the "recent" inbox because of an upvote can be annoying, but is that a reason to lock the thread?

Also, could you explain why you want to place a limit on upvotes? I think they are a very useful feature, especially in the Q/A topic threads.

**Comment by julianlam** [comment]
I envision it to be an opt-in feature in any case. I have no problem with old topics coming back up, although I think some communities have (unwritten) rules against it.

In any case, one example for the voting-locking I can think of is Reddit, where once in awhile, old posts are dredged up and showcased (think /r/bestof), but they don't want redditors to swarm the old topics with new comments and such, as that might defeat the purpose of the showcase. (e.g. "This guy predicted two years ago the Blue Jays would win the World Series! Got downvoted into oblivion but look at the jays now!", where the post linked to would have a ton of downvotes, but if not locked, new redditors would upvote the heck out of it)

**Comment by jacobbridges** [comment]
Ah that makes sense...I hadn't considered that scenario.

SMF (Simple Machines Forum) software handles a similar issue with a warning. So if a user attempts to post in a topic that has been inactive (no posts) for 60 days, it displays a warning when you click "reply" that says that the post is old and recommends starting a new thread.

Just an alternate idea. :) This is a good topic though--it would be nice if topics were auto-archived after a time and became read-only unless an admin un-archived it. Or something like that...

**Comment by julianlam** [comment]
https://github.com/julianlam/nodebb-plugin-archiver

:point_up: This is the plugin I was talking about in the top post. Just auto-locks topics x days after last activity or from creation.

**Comment by yariplus** [comment]
I like the idea of adding a confirmation warning before posting on an old thread. Always liked sites that do that.

Just a thought: It would be nice if the warning also gave a fork-like option to create a new thread and place a link to it on the old one. If the old topic was very popular, search engines are *incredibly bad* at finding the new one.

**Comment by lots0logs** [comment]
> I like the idea of adding a confirmation warning before posting on an old thread. Always liked sites that do that.
> 
> Just a thought: It would be nice if the warning also gave a fork-like option to create a new thread and place a link to it on the old one. If the old topic was very popular, search engines are incredibly bad at finding the new one.

+1 +1 +1 :+1:

**Comment by julianlam** [comment]
At present, right now a new admin option is introduced, allowing you to specify the # of days until a topic is considered stale. When stale, new replies or quotes will throw a modal asking if they'd want to create a new topic instead.

For now, the new topic text contains no link back.

**Comment by lots0logs** [comment]
@julianlam, Thanks for this!! :beers:

**Comment by jacobbridges** [comment]
:+1: Love it!

**Comment by julianlam** [comment]
Hitting cancel in the modal should still open the composer.
