### ISSUE TITLE
Possible infinite loop while starting nodebb

### ISSUE THREAD

**Issue by pedropapa** [NodeBB/NodeBB#3696]
For some reason my nodebb just doesn't work anymore, it just hang up while starting up with no error message even in dev mode and it seems to enter in a infinite loop as the nodejs proccess just consumes almost 100% CPU.

./nodebb dev output:
![](https://www.dropbox.com/s/rld7vmkb58pxge6/Screenshot%202015-10-01%2023.39.30.png?dl=1)

High CPU usage:
![](https://www.dropbox.com/s/f0biwf8cmeromu6/Screenshot%202015-10-01%2023.40.50.png?dl=1)

it always freezes at "[notifications.init] Registering jobs.".

I already ran ./nodebb reset -p to disable all plugins.

Note: The same problem occours in 0.7.x version of nodebb.

**Comment by psychobunny** [comment]
Is this a new forum or did you recently upgrade? If both are false then can you think of anything you've done recently that may have caused this?

**Comment by pedropapa** [comment]
Both false, it was running just fine from several days with no changes, one of the ways I tried to fix this problem was to upgrade to 0.8.x, but I had no luck. I think it is a problem with the redis database, but I just can't reset it because it is a production install.

**Comment by pedropapa** [comment]
While debbuging the code I found that notifications.init put Notifications.prune callback as a cron job, and it loads data from database:

```
Notifications.init = function() {
		winston.verbose('[notifications.init] Registering jobs.');
		new cron('*/30 * * * *', Notifications.prune, null, true);
	};
```

```
Notifications.prune = function() {
		var	week = 604800000,
			numPruned = 0;

		var	cutoffTime = Date.now() - week;

		db.getSortedSetRangeByScore('notifications', 0, 500, 0, cutoffTime, function(err, nids) {
			if (err) {
				return winston.error(err.message);
			}

			if (!Array.isArray(nids) || !nids.length) {
				return;
			}

			var	keys = nids.map(function(nid) {
				return 'notifications:' + nid;
			});

			numPruned = nids.length;

			async.parallel([
				function(next) {
					db.sortedSetRemove('notifications', nids, next);
				},
				function(next) {
					db.deleteAll(keys, next);
				}
			], function(err) {
				if (err) {
					return winston.error('Encountered error pruning notifications: ' + err.message);
				}
			});
		});
	};
```

**Comment by pedropapa** [comment]
Same problem even running ./nodebb reset -a   o__o

![](https://www.dropbox.com/s/8l6mmog5ljulr26/Screenshot%202015-10-02%2000.14.10.png?dl=1)

**Comment by barisusakli** [comment]
I can't repro, it is possibly hanging at the next step, you can put a few console.logs in webserver.js listen method and figure out whats wrong.

**Comment by pedropapa** [comment]
Hello,
I did what you ask and I think I found the problem:

my debug messages:
![](https://www.dropbox.com/s/76z4f1xwhttha12/Screenshot%202015-10-03%2021.53.41.png?dl=1)

My code:
![](https://www.dropbox.com/s/b2af67kjcnpnona/Screenshot%202015-10-03%2021.54.45.png?dl=1)

seems like this cron right there is hanging up the process, I just comented it and the forum is now working again.

can you please investigate this more deeply? do you need more information?

I just reset my redis database and the problem still occours, so there is no data in redis causing this problem.

**Comment by barisusakli** [comment]
Weird that only one of the cronjobs is hanging can you change its pattern to one of the others and see if it works?

**Comment by pedropapa** [comment]
Yeah.. changing the pattern from ```0 0 17 1 * *``` to ```0 0 17 * * 0``` (equals "week" cron) the problem seems to be solved.

My cron module version: ^1.0.5

**Comment by barisusakli** [comment]
Does `0 0 17 1 * *` work with 1.0.9 looks like thats the latest version of node-cron. If not maybe report it on their repo https://github.com/ncb000gt/node-cron/issues

**Comment by pedropapa** [comment]
Not, upgrading node-cron to 1.0.9 version doesn't solved the problem.

I'll create the issue on node-cron project, thank you.
