### ISSUE TITLE
Modifying plugin settings seems to cause site title, favicon, and other image uploads to disappear.

### ISSUE THREAD

**Issue by sejr** [NodeBB/NodeBB#3698]
NodeBB v0.8.2, for what it's worth.

**Comment by barisusakli** [comment]
Site logo image or the site title text in the acp?

**Comment by sejr** [comment]
The site logo image, sorry. I also have a custom image for the favicon, as well as for one of my forum categories. Those disappear as well.

**Comment by barisusakli** [comment]
Is this only happening with local uploads? Does it happen when you use nodebb-plugin-imgur? Also what OS/platform.

**Comment by sejr** [comment]
It also just happened with all user uploads as well. About 20-30 people just lost their avatars? I haven't used the imgur plugin. It's deployed on Heroku.

**Comment by barisusakli** [comment]
Could be related to herokus file system.
Read more here https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem
