### ISSUE TITLE
E-mails are not being sent with 0.8.x and master

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#3699]
About a week ago we started getting complaints that registration e-mails were not being received. I've finally had time to look into it and I confirmed that the messages are not being sent. There is no output to the logs indicating that any attempt was made to send them. When launched in `dev` mode and manually sending a validation email there is absolutely NO output related to the action (though on-screen it shows a notification that the email was sent). I confirmed that no attempt was made by checking the logs of my mailgun account. The last time the api was used by the forum was **9/26**. Please let me know if there is anything I can provide that will help resolve this issue. Thanks.

**Comment by barisusakli** [comment]
If you are on master you need the mailgun plugin version 1.0.0 with this change
https://github.com/julianlam/nodebb-plugin-emailer-mailgun/commit/45406e3986b614a35848b15aabfa023f14021f63

There are some breaking changes to emailer plugins on master.

**Comment by lots0logs** [comment]
I have the latest version of the plugin. I initially was not on `master` but I moved to master hoping it was fixed but its still broken with `master` and `v1.0` of the plugin.

**Comment by lots0logs** [comment]
Whoops, nevermind. I think when I ran `/nodebb upgrade` on `master` it downgraded the plugin back to the previous version. Its working now that I manually updated the plugin with `npm`. Sorry for the noise. Cheers!

**Comment by barisusakli** [comment]
:+1:
