### ISSUE TITLE
Default Composer: tags layout

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3703]
If you enter more than 2 tags, line will be moved to bottom:

<img width="501" alt="screen shot 2015-10-03 at 9 25 28 am" src="https://cloud.githubusercontent.com/assets/135263/10263160/e091a55a-69b0-11e5-839a-e1639382e354.png">

**Comment by julianlam** [comment]
Yes, I believe this is because the input itself has a set width, and we cannot minimise this size as different languages have different widths...

**Comment by barisusakli** [comment]
Another bug which started recently

![image](https://cloud.githubusercontent.com/assets/2583394/13610597/253c7b12-e567-11e5-914e-26988eb13f41.png)


It goes back to normal if you focus the tag input and remove focus.
