### ISSUE TITLE
SSO auth redirect to localhost (tested with Google)

### ISSUE THREAD

**Issue by machado2** [NodeBB/NodeBB#3706]
I tried installing google SSO, and I'm behind and nginx proxy. The error message from google is:

The redirect URI in the request: http://localhost:4531/auth/google/callback did not match a registered redirect URI.

I'm not acessing trough localhost, that is an internal URL. This is how my nginx config looks like:

    server {
        listen 80;
    
        server_name www.noiapapps.com;
    
        location / {
            rewrite /t/.*/8257 /topic/10/ last;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
    
            proxy_pass http://127.0.0.1:4531/;
            proxy_redirect off;
    
            # Socket.IO Support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

**Comment by julianlam** [comment]
Specify the proper url in your `config.json`
