### ISSUE TITLE
Visitor count in dashboard not working with Nginx Proxy

### ISSUE THREAD

**Issue by machado2** [NodeBB/NodeBB#3707]
I think it is related to the Nginx proxy forwarded-ip not being counted. My visitor count never get past 3, both analytics and logs show much more (even accounting for bots). This is my nginx config:

    server {
        listen 80;
    
        server_name www.noiapapps.com;
    
        location / {
            rewrite /t/.*/8257 /topic/10/ last;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
    
            proxy_pass http://127.0.0.1:4531/;
            proxy_redirect off;
    
            # Socket.IO Support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

**Comment by barisusakli** [comment]
This is a configuration issue, not related to nodebb core.

If nginx is behind something like cloudflare you will have to add other directives like http://nginx.org/en/docs/http/ngx_http_realip_module.html
