### ISSUE TITLE
deprecation notice

### ISSUE THREAD

**Issue by robjens** [NodeBB/NodeBB#3708]
I presume I am not alone when I state that, although a deprecation warning _can_ be useful, it would be even more useful to mentioned *what* alternative to use.

> Hook `filter:user.delete` is deprecated, please use an alternative

Take it there actually is none, this is even more frustrating because one goes to look and finds, nothing but the mention it is deprecated. But without any replacement, we're stuck...

Any thoughts? Is it a smart thing to deprecate and not offer a solution? What if there is none, should it still be used and if so, should it be noted that there is unlikely to _be_ an alternative when this piece of information is missing?

This message alone is about as useful as having software 'just break' one day as it does nothing but warn you of impeding danger. Like a pilot of a commercial jet: "Ladies and gentleman, we are sorry to disturb you but we are going to crash, I won't be able to make it with this speed and angle, please abandon all hope... you ARE going to die. Oops"

**Comment by barisusakli** [comment]
I guess this wasn't clear enough https://github.com/NodeBB/NodeBB/commit/a1d51327774c5750f6deb7a1729be8e466b2b7f8 :)

@julianlam

**Comment by robjens** [comment]
`static:user.delete` aha. Much thanks :)
