### ISSUE TITLE
[question] Why NodeBB for MongoDB uses system user collections not custom user collection?

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB/NodeBB#3710]
We are discussing why NodeBB for MongoDB uses system user collections not custom user collection, It will be a little difficult for my colleague to migrate database or backup it. I need to know the key point of using system user collections.

**Comment by jiangcaiyang** [comment]
I performed a database migration, not a problem, sorry for interrupting...

**Comment by psychobunny** [comment]
:+1:
