### ISSUE TITLE
Group banner: drag-drop non-functional on Windows / Unices

### ISSUE THREAD

**Issue by robjens** [NodeBB/NodeBB#3711]
Currently the group banner knows only the drag-drop option while editing the 'hero' part of a (self made) group. I think this should be a regular (perhaps in the group edit panel) **upload** button which pops open the traditional file selection dialog.

Reason is drag-drop under Linux never ever works and this way it is impossible to change group banner without switching operating system. Minor one but still...

**Comment by robjens** [comment]
Ok I just checked on windows, after having noticed the widgets (admin) do not drag drop either, and also windows is non-operational in my case. I presume anyone should be able to validate and reproduce this.

**Comment by julianlam** [comment]
Hey there @robjens -- can confirm the drag/drop works on unix at least, because that's what I use, and I wrote the darn thing :laughing: 

That said, @psychobunny has been bugging me to add an upload button for this, so this is a legitimate concern, esp. for browsers that do not support drag/drop image uploading.

**Comment by robjens** [comment]
Hmm thanks for that. After I fixed my redis unix sockets + websocket ws + nginx issues, I'll give it another try. Also going to try using a separate mouse since I've been having issues with this Windows 10 (host) and my synaptics touchpad device. Normally, I just run Xfce4 under ArchLinux on a virtualbox guest but I've always had problems with this kind of drag-drop operations (from tab to another tab, or from window to another tab) on nix. But since native host (Windows 10 though) also doesn't work... puzzled.

Anyway, you verified it works on your end so it definitely must be me, which makes it all the more mysterious. But good to hear a fallback option/button is going to be added at some point.

**Comment by robjens** [comment]
Found it. It's definitely *Chrome* browser causing my issues. Stuff just works using MS Edge or Firefox.
