### ISSUE TITLE
Group feed is displaying incorrect (all) history

### ISSUE THREAD

**Issue by robjens** [NodeBB/NodeBB#3712]
It is great that users (preferably certain designated groups or individual users, but this is a different topic for some other time) can create their own groups.

I noticed however something strange when I created a new group and this is the so-called feed being displayed. It seems to just show everything.

Now what we have here, in my view, is somewhat the result of the abstractions used but it can be tweaked to provided more sane results perhaps.

Since groups do not have their own designated category, but we can assign groups to categories. So it would make more sense to lookup this current group and see what categories it is assigned to. Those should probably be the feed that the group receives. But only those of course which have 'read' access to those categories, it wouldn't make much sense to display information people aren't supposed to read I guess. I wonder if this is already the case and what the current feed is pulling its information from.

**Comment by barisusakli** [comment]
The feed is displaying the latest X posts from members of the group. The posts are filtered if you don't have read access to the category it was posted in.

**Comment by julianlam** [comment]
How difficult would it be to add a filtering dropdown to this list?

**Comment by robjens** [comment]
@barisusakli: Ok thanks for the answer. I see that at least, it is not possible for non-group members to view messages placed in private groups or categories to which one is not a member. This is the least I would want indeed.

I am not sure if this is in all cases relevant though, I mean... even if I'm a member of the group that has access to category A, and also a member of B who has a member named Xm do I really care about X posting in A, while I'm in B?

Even 'worse', like Google promoting my own Google+ posts to the search results, you guys think I'm that forgetful or vain, that I need to see all my own posts I made in other categories, while viewing a completely different one?

**Comment by robjens** [comment]
Oh, I tend to mix up a few things though, making this a tad harder: a group can be member of multiple categories. Is it only those category posts shown? Or just all posts by a member who happens to be in that group?
