### ISSUE TITLE
Error: version not found: nodebb-plugin-emoji-extended@0.4.14

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB/NodeBB#3716]
I cloned NodeBB code from this repository, and cd && npm install, unfortunately, it caused this error:
npm ERR! Error: version not found: nodebb-plugin-emoji-extended@0.4.14
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/jiangcaiyang/WebProject/NodeBB
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jiangcaiyang/WebProject/NodeBB/npm-debug.log
npm ERR! not ok code 0

How could I resolve this problem?

**Comment by julianlam** [comment]
Hm, npm does say the package version is available...

https://skimdb.npmjs.com/registry/nodebb-plugin-emoji-extended

**Comment by jiangcaiyang** [comment]
It's strange that taobao has its latest dependency, version 0.1.15.
Could you please write dependence just a commit ahead?
http://npm.taobao.org/package/nodebb-plugin-emoji-extended

**Comment by jiangcaiyang** [comment]
OKay, I synchronized http://npm.taobao.org, and got this plugin back, now being able to get from this npm repository. Please close this bug.

**Comment by julianlam** [comment]
Thanks for the update :smile:
