### ISSUE TITLE
"modal-backdrop  in" does not disappear after upload custom images

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB/NodeBB#3718]
Here is my test website:
http://qtdream.com:1111
I've allowed user upload their favourite image.
When user wants to upload image, the div named "modal-backdrop  in" appears, but after successfully uploaded image, this div does not disappear. How could I resolve this problem?

**Comment by barisusakli** [comment]
Make sure you do these changes https://github.com/NodeBB/nodebb-theme-persona/commit/1fc6d56800435119f8e8122dbecddd92781a4fdf and are on latest master.

**Comment by jiangcaiyang** [comment]
Thank you, after installed NodeBB/nodebb-theme-persona, it come out without bugs.

**Comment by jiangcaiyang** [comment]
Please close it, thank you.
