### ISSUE TITLE
Use Autoprefixer as part of build process for themes

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3719]
Would be great, if Autoprefixer will be used as part of build process for themes at least.

FYI:

- https://css-tricks.com/autoprefixer/
- https://github.com/postcss/autoprefixer

**Comment by pitaj** [comment]
:+1:

Honestly, autoprefixer should be part of the CSS compilation right after the LESS step. You should not be prefixing yourself, as it makes your code bigger, uglier, and harder to maintain.

**Comment by luofan189** [comment]
+1, we use autoprefixer in our project, and it is a great lib. Would love to see this in nodebb.

**Comment by julianlam** [comment]
44.1kb to 43.8kb :laughing:

**Comment by NicolasSiver** [comment]
@julianlam don't forget to use Autoprefixer rules, to use all power of it.

> browsers=last 2 version

**Comment by pichalite** [comment]
:+1:

**Comment by pitaj** [comment]
Great, now you just need to remove all of the prefixes from the existing less!

**Comment by LordZardeck** [comment]
@julianlam Any idea when this will get into the v0.9.x branch?

**Comment by julianlam** [comment]
@LordZardeck As this is a new feature, we'll probably keep it out of v0.9.x as the next version is v1.0.0.

**Comment by LordZardeck** [comment]
@julianlam Any plans on when v1.0.0 will be released?
