### ISSUE TITLE
Categorie's Privileges isn't accounted

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3724]
If you remove all privileges, you still can see them around, here is an example of `Mark as read`:

<img width="306" alt="screen shot 2015-10-08 at 11 58 10 am" src="https://cloud.githubusercontent.com/assets/135263/10371982/e14ec282-6db3-11e5-9660-540c0d73ccc0.png">

Most of them:

- have disabled parent category
- don't have any privileges at all

<img width="1163" alt="screen shot 2015-10-08 at 11 59 18 am" src="https://cloud.githubusercontent.com/assets/135263/10372021/0a94805a-6db4-11e5-8bbc-d5633a43fb9b.png">

**Comment by barisusakli** [comment]
What happens when you add the `registered-users` group from the add group button? Does it have any privileges?

**Comment by NicolasSiver** [comment]
If you just add group `registered-users`, it will look like this:

<img width="1150" alt="screen shot 2015-10-08 at 3 24 26 pm" src="https://cloud.githubusercontent.com/assets/135263/10377355/d33fcff2-6dd0-11e5-9987-482a8cfc80eb.png">

**Comment by barisusakli** [comment]
Ok so if you remove the find/access read from registered-users. Do you still see the categories in the dropdown?

**Comment by barisusakli** [comment]
Not to mention if you are an admin you will see them so test with a regular user.

**Comment by NicolasSiver** [comment]
Even if an admin, what is the point to work/see Categories that are _disabled_?
Or to really disable you should go and disable every category?

**Comment by NicolasSiver** [comment]
@barisusakli  Maybe, `admin-users` privilege user group should be introduced?

**Comment by julianlam** [comment]
Admins will always be able to see all all categories. It would be counter intuitive to restrict a category from an admin....

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/0ce1e666e755ff60b6e6a81189408b882c5967e5

will disable children if you disable a parent so they won't be visible in that dropdown.

**Comment by NicolasSiver** [comment]
@julianlam it's counter intuitive now. Introduce privilege mask also for admins. Admins are also users, not gods.
If you need super user, introduce an idea of root admin.
Than it will look like something _intuitive_.
