### ISSUE TITLE
Searching several words logic

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3725]
Searching for "house of cards" should search for three words together. Actually you will get result for house, results for of , results for cards and results for 3 words.  and usually you wont find what you looking for. Imagine how many "of" resuls you will get. 
Also maybe search only titles should be default option. Searching on title and posts usually getting bad results, maybe because of the isolate searchs

**Comment by pitaj** [comment]
What search plugin are you using? The default one?

**Comment by martyalicante** [comment]
Yes

**Comment by pitaj** [comment]
You might try using other search plugins like elasticsearch

**Comment by martyalicante** [comment]
@pitaj elasticsearch plugin is broken for me, it restarts nodebb while building index
anyways you can test on nodebb community wich is using solr that it works the same way :(

**Comment by julianlam** [comment]
What happens if you search with quotes?

**Comment by martyalicante** [comment]
@julianlam with quotes "" seems to work well but i guess is not easy to discover for people

**Comment by martyalicante** [comment]
I tried before on community with qoutes but now trying with dbsearch default and it mess all results so i guess that quote system only works with solr

**Comment by barisusakli** [comment]
Are you on redis? The redis search right now only does an OR search of the keywords. I'm going to update it so it does an AND if the search is using quotes

**Comment by martyalicante** [comment]
I'm on mongo
Actually it should use AND by default if using several words in my opinion or put that results before the OR ones

**Comment by martyalicante** [comment]
Tested solr and working well without quotes etc. Guess you can you close it unless want to change on dbsearch
Thank you
