### ISSUE TITLE
NodeBB on OpenBSD

### ISSUE THREAD

**Issue by h4waii** [NodeBB/NodeBB#3727]
I've noticed quite often some issues with the current release on OpenBSD. All the modules seem to install correctly, however...if you interrupt or get thrown an error during setup, there are issues with locating the redis module. See below.

# ./nodebb start  

Starting NodeBB
  "./nodebb stop" to stop the NodeBB server
  "./nodebb log" to view server output
  "./nodebb restart" to restart NodeBB

8/10 16:12 [26395] - info: Launching web installer on port 4567
8/10 16:12 [26395] - info: Web installer listening on http://0.0.0.0:4567
8/10 16:12 [18494] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).

8/10 16:12 [18494] - info: Now configuring redis database:
Configuration Saved OK
redis@0.10.3 node_modules/redis

connect-redis@2.0.0 node_modules/connect-redis
└── debug@2.2.0 (ms@0.7.1)
Populating database with default configs, if not already set...
Enabling default theme: nodebb-theme-persona
No categories found, populating instance with default categories
8/10 16:12 [18494] - warn: No administrators have been detected, running initial user setup

8/10 16:12 [18494] - warn: NodeBB Setup Aborted.
 Error: [[user:change_password_error_length]]
    at Object.User.isPasswordValid (/root/NodeBB/src/user/create.js:188:20)
    at async.parallel.passwordValid (/root/NodeBB/src/user/create.js:160:11)
    at /root/NodeBB/node_modules/async/lib/async.js:689:13
    at /root/NodeBB/node_modules/async/lib/async.js:239:13
    at /root/NodeBB/node_modules/async/lib/async.js:119:13
    at _arrayEach (/root/NodeBB/node_modules/async/lib/async.js:91:13)
    at _forEachOf (/root/NodeBB/node_modules/async/lib/async.js:118:9)
    at _each (/root/NodeBB/node_modules/async/lib/async.js:83:13)
    at async.forEachOf.async.eachOf (/root/NodeBB/node_modules/async/lib/async.js:238:9)
    at _parallel (/root/NodeBB/node_modules/async/lib/async.js:688:9)

Starting NodeBB
    "./nodebb stop" to stop the NodeBB server
    "./nodebb log" to view server output
    "./nodebb restart" to restart NodeBB
# ./nodebb log   

# ./nodebb log 

Type Ctrl-C to exit

net.js:1237
    throw new Error('Not running');
          ^
Error: Not running
    at Server.close (net.js:1237:11)
    at shutdown (/root/NodeBB/app.js:294:36)
    at process.<anonymous> (/root/NodeBB/app.js:174:3)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:295:26)
3 restarts in 10 seconds, most likely an error on startup. Halting.

I understand OpenBSD might not be officially supported, but it doesn't appear to be an underlying cause of this issue...

**Comment by pitaj** [comment]
Try running `./nodebb setup` instead of the web installer. Make absolutely sure all of the database information is set up correctly.

**Comment by barisusakli** [comment]
>if you interrupt or get thrown an error during setup, there are issues with locating the redis module

this is expected, the redis module gets installed during `./nodebb setup`if you interrupt it or get an error during setup the module might not be installed.
