### ISSUE TITLE
Logs filled with User.getMultipleUserFields deprecation warning.

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#3728]
@barisusakli  It seems like the message is output 5-10 times for each request whether its a cold load or ajaxified:
```
warn: [deprecated] User.getMultipleUserFields is deprecated please use User.getUsers
```
I checked my fork of lavender and couldnt find anywhere that the deprecated function was used. How can I track down which plugin is causing all the log output?  (I mean is there a quicker way to do it then disabling them one-by-one?)

**Comment by barisusakli** [comment]
Go into your nodebb folder and run

`grep -r "User.getMultipleUserFields" node_modules`
