### ISSUE TITLE
Moving topic with a single category activated

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3731]
When I try to move a topic (my site has a single category activated), I get a modal appear which shows an infinite loading indicator:

![move](https://cloud.githubusercontent.com/assets/1963288/10392663/07625614-6e81-11e5-8304-186bbba55b41.png)

Testing done using the current master branch.

**Comment by henrywright** [comment]
After updating Persona, this is no longer a problem.

Just thinking though, is it worth removing the ability to _fork_ and _move_ a topic if a single category is activated?

**Comment by barisusakli** [comment]
You might still want to fork the topic in the same category, but you can't move it if there is only 1 category in the forum.

**Comment by henrywright** [comment]
> You might still want to fork the topic in the same category

Good point!

> but you can't move it if there is only 1 category in the forum.

You _may_ want to move it to a disabled category?
