### ISSUE TITLE
Duplicate post bar

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3732]
On single topic pages the post bar which contains stuff like the view count, reply button and the sort by option list appears twice on the page. This is great for topics that have lots of posts but not so great for topics that have one or two posts (see screenshot below).

Users who aren't familiar with NodeBB might wonder why they're seeing duplicate buttons. 

![topic](https://cloud.githubusercontent.com/assets/1963288/10392882/0ac86e4a-6e83-11e5-814c-c40641c3e482.png)

**Comment by NicolasSiver** [comment]
Also, if you delete that second post you will get both button sets in the same time ;)
Also, I don't think that button organization is smart, going to update layout in my theme.

**Comment by barisusakli** [comment]
I fixed the double post bar after you deleted the first reply.

**Comment by NicolasSiver** [comment]
@barisusakli :+1: 
When to wait for `0.9` release? ;)
I have to update several plugins to `0.8.2` still

**Comment by barisusakli** [comment]
We are aiming for end of this month for 0.9.0

For 0.9.0 breaking changes see https://community.nodebb.org/topic/6583/0-9-0-breaking-changes
