### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by alex9307** [NodeBB/NodeBB#3733]
After I run 'npm install' I get the following errors:

4136 error Windows_NT 6.1.7601
4137 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
4138 error node v4.1.2
4139 error npm  v2.14.4
4140 error code ELIFECYCLE
4141 error lwip@0.0.7 install: `node-gyp rebuild`
4141 error Exit status 1
4142 error Failed at the lwip@0.0.7 install script 'node-gyp rebuild'.
4142 error This is most likely a problem with the lwip package,
4142 error not with npm itself.

I tried this on:
- Windows 7 64bit;
- Node v4.1.2;
- Python v2.7.3 64bit;
- mv c++ 2013 64bit;
- windows sdk.

Any idea why? Thanks.

**Comment by dontpanic92** [comment]
I tried to install NodeBB 0.8.x on my Debian server and got the same error. My node version is 4.1.1.
It seems like something wrong with lwip. I have tried to change 0.0.7 to the latest 0.0.8 but it didn't work neither.

**Comment by psychobunny** [comment]
Not sure about Debian, but on Windows try installing Visual Studio 13, that worked for me

**Comment by pitaj** [comment]
Thank god the `lwip` dependency is being removed. It's the reason I now do all my development in an Ubuntu VM
