### ISSUE TITLE
Can't remove forum logo in 0.8.2

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3734]
Going to Settings > General > Site Logo and then clicking on the remove button, I see a message appear on screen "Logo removed". But when I visit my site I still see the logo appear in my site's header.

Tested using NodeBB 0.8.2 and Persona.

**Comment by barisusakli** [comment]
Seems like fixed on master? @julianlam

**Comment by henrywright** [comment]
This doesn't happen for me when using master.

**Comment by psychobunny** [comment]
Yeah I fixed this on master, I'll find the commit and backport to 0.8.2
when I get home

**Comment by psychobunny** [comment]
28a4703a4bf3d0ec81d14bf20724c707ec6a4eef
