### ISSUE TITLE
Support for Sass

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3737]
It would be great if NodeBB started to support Sass. [Bootstrap 4](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/) will be moving from Less to Sass so themes that use Bootstrap 4 as a framework might need this.

**Comment by ApfelUser** [comment]
:+1:

**Comment by pitaj** [comment]
Honestly, couldn't care less.

**Comment by henrywright** [comment]
@pitaj lol

**Comment by ApfelUser** [comment]
That pun :+1:

**Comment by pitaj** [comment]
:smiley:

**Comment by luofan189** [comment]
+1

**Comment by colin-marshall** [comment]
Sass support would be awesome!

**Comment by julianlam** [comment]
Going to close this for now, but we will likely try an experimental port to SASS when Bootstrap 4 hits beta... though it will be hard to justify putting it in place in production environments until BS4 hits RC...
