### ISSUE TITLE
Suggestion: Make user search easier to find

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3738]
The current user search is located at Home > Users > Search:

https://community.nodebb.org/users/search

I takes a few clicks to get to that page and for that reason people might not use the user search very much. I think the user search is a great feature which should be brought to the fore. May I suggest displaying it at the top of the main users page:

https://community.nodebb.org/users

The dedicated user search page could then be removed:

https://community.nodebb.org/users/search

**Comment by pitaj** [comment]
:+1:

**Comment by pichalite** [comment]
@barisusakli just want to give my 2 cents on the UX for the user search. When you type something in the "User search" box, searching all users makes sense on the /Users route but on the online, top posters and most reputation routes searching with in the list would probably make a better UX.

Thoughts @julianlam @psychobunny @henrywright ?

**Comment by henrywright** [comment]
@pichalite That seems logical to me and I would imagine that's what forum users would expect to happen.
