### ISSUE TITLE
Creating widget area work for ACP but not present in forum html

### ISSUE THREAD

**Issue by panpansh** [NodeBB/NodeBB#3743]
I have defined a widget area footer fixed like that :

Added to /nodebb-theme-material/lib/theme.js

    theme.defineWidgetAreas = function(areas, callback) {
		areas = areas.concat([
			{
				'name': 'Footer fixed',
				'template': 'footer-fixed.tpl',
				'location': 'bottom'
			}
		]);

		callback(null, areas);
	};

Added to /nodebb-theme-material/plugin.json

    {
			"hook": "filter:widgets.getAreas", "method": "defineWidgetAreas", "callbacked": true
    }

created /nodebb-theme-material/templates/footer-fixed.tpl

    <div widget-area="bottom"></div>

I can see a new widget area and I can put widgets on it.
But when the page is loaded and check for widget html code by the chrome devlopper tool, I can see nothing :/

Any help is welcome :)

**Comment by pitaj** [comment]
You need something like the following I think:

```html
<div widget-area="bottom">
	<!-- BEGIN widgets -->
	{widgets.html}
	<!-- END widgets -->
</div>
```

Look [here](https://github.com/psychobunny/nodebb-plugin-custom-pages/blob/master/templates/custom-page.tpl) for more examples

**Comment by panpansh** [comment]
content of /nodebb-theme-material/templates/footer-fixed.tpl
replaced by : 
    <div widget-area="bottom">
        
        {widgets.html}
        
    </div>
And I have the same issue

**Comment by julianlam** [comment]
Please ask in the community forum :smile: 

https://community.nodebb.org
