### ISSUE TITLE
IE9: compose window messed up

### ISSUE THREAD

**Issue by PierPP** [NodeBB/NodeBB#3744]
Tested on commit d0150d0be23a9376d149ede8170a0334f00d8770

![schermata 2015-10-11 alle 09 24 58](https://cloud.githubusercontent.com/assets/1764464/10415534/2c50b306-6ffa-11e5-86c5-846ba90bf0d0.jpg)

**Comment by barisusakli** [comment]
Any errors in the browser console?

**Comment by PierPP** [comment]
SCRIPT1002: Syntax error 

![schermata 2015-10-11 alle 20 43 34](https://cloud.githubusercontent.com/assets/1764464/10418371/ccf74758-7058-11e5-87f9-aff96444e9bf.jpg)

**Comment by barisusakli** [comment]
What is the nodebb commit hash? Is it happening on latest as well?

**Comment by PierPP** [comment]
![schermata 2015-10-16 alle 19 30 58](https://cloud.githubusercontent.com/assets/1764464/10548670/a9f4fb32-743c-11e5-81fc-867e566991e9.jpg)

this is from commit #e60c1d87369525a39906794cd14f6f6a01710774

**Comment by barisusakli** [comment]
Let us know if this is still happening on https://community.nodebb.org/
