### ISSUE TITLE
Compose Window gets blocked by "+"-icon and chat-icons (on small resolutions?)

### ISSUE THREAD

**Issue by robotanarchy** [NodeBB/NodeBB#3746]
Hello NodeBB devs,

when composing a new message in Firefox (41.0.1) and Chromium (45.0.2454.101), it is not possible to click the very bottom area (width: 100%, height: ~ icon size) of the textareas.

Even worse, in Chromium the very bottom of the textarea seems to be missing completely.

When clicking the 'up'-arrow-icon, to make the textareas cover most of the screen, they work. But we usually need to have another post open while creating a new one.

Desktop resolution:
1366x768

May you fix this please?
Thanks for making nodebb :+1:

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/issues/6
