### ISSUE TITLE
Attemping to access the user edit page causes an undefined error and forum shutdown

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3747]
Visiting the user/henrywright/edit page using NodeBB master and master Persona, I get a rather uninformative error show up in my logs and my forum shuts down:

> error: undefined undefined

Note, I'm not seeing this when I switch to the `v0.8.x` branch.

**Comment by barisusakli** [comment]
Sounds like https://github.com/NodeBB/NodeBB/issues/3694

what version of t.js + persona?

**Comment by henrywright** [comment]
@barisusakli I'm using the master branch of Persona and NodeBB master (commit [d0150d0](https://github.com/NodeBB/NodeBB/commit/d0150d0be23a9376d149ede8170a0334f00d8770))

**Comment by barisusakli** [comment]
What does `npm ls templates.js` say? Works fine for me on master btw with persona master and templates.js 0.2.16

**Comment by henrywright** [comment]
templates.js is 0.2.10

**Comment by barisusakli** [comment]
If you are on master running npm i should update it to 0.2.16

**Comment by henrywright** [comment]
Sorry, on master branch templates.js is actually already 0.2.16.

**Comment by henrywright** [comment]
I noticed the commit I was on wasn't latest so pulled and no longer get this error.
