### ISSUE TITLE
Unable to disable username changing

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3748]
I noticed there's a setting on the user/henrywright/edit/username page which allows users to change their username. I'd like to disable this ability if possible because it kind of ruins any existing @-mentions. I'm happy for my users to be stuck with the username they chose on sign up.

**Comment by barisusakli** [comment]
ACP setting doesn't work?
![image](https://cloud.githubusercontent.com/assets/2583394/10418210/b94c966c-7022-11e5-92a4-c14ed3d5c2c5.png)

**Comment by henrywright** [comment]
Ah great, this must be new?

I noticed changing usernames was possible when I logged into the NodeBB community forum earlier today, but on my live install (v0.8.2) I didn't see the admin option. I usually test using master branch on localhost but that's currently inaccessible due to #3747

**Comment by barisusakli** [comment]
Yeah it was added recently

**Comment by henrywright** [comment]
Nice one @barisusakli, thanks.
