### ISSUE TITLE
Safari 9: selected topic bug

### ISSUE THREAD

**Issue by PierPP** [NodeBB/NodeBB#3749]
![schermata 2015-10-11 alle 20 51 41](https://cloud.githubusercontent.com/assets/1764464/10418401/050fd8a2-705a-11e5-8f2b-c44754d4ce45.jpg)

Also, if I try to click the topic title on the first 4/5 chars it doesn't open the topic but selects it.

only error I see is: 
/vendor/jquery/timeago/locales/jquery.timeago.it-short.js Not found

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/c4b80db72f045c0d05db1f393dcbd6bd5ee1e278
