### ISSUE TITLE
[question]Could anyone tell me how could I get current user data while hooking "static:app.load"

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB/NodeBB#3751]
I need to set user name and its avatar on rendering sepcific web page, I do some routing on hooking "static:app.load", but I am confused at how to get current user data.

A second question, is it possible to make a native mobile application to do some signin/signout?

**Comment by jiangcaiyang** [comment]
Forget to say, I am developing a nodebb plugin.

**Comment by jacobbridges** [comment]
Hi @jiangcaiyang! You can get the current user from `app.user`.

By the way, for general questions like this it is better to post them in [NodeBB's community forum](https://community.nodebb.org/category/7/nodebb-plugins). The response time is much faster. :)

**Comment by jiangcaiyang** [comment]
Thank you, it's something urgent that I could only turn it for help. I found "req.user" is also possible, I've managed finding user name by requiring parent module "./user".

**Comment by jacobbridges** [comment]
Nice! I forgot about `req.user`. 

And as for your second question, are you talking about having a mobile app sign in/out of a NodeBB forum? Because I think it's possible though the particular forum might have to install a plugin for easy integration.

**Comment by psychobunny** [comment]
> By the way, for general questions like this it is better to post them in NodeBB's community forum. 

Indeed :)

**Comment by jiangcaiyang** [comment]
@jacobbridges 
I've tried log in by posting username/email and password through my mobile app ( which uses QML ), but to my astonishment, the forum return it with 403, i.e. I have no permission in posting data using my own way, is there any tricks that I couldn't find so far?

**Comment by navixco** [comment]
> Thank you, it's something urgent that I could only turn it for help. I found "req.user" is also possible, I've managed finding user name by requiring parent module "./user".
--
Hello @jiangcaiyang and @jacobbridges,
I'm try to setup nodebb for my forum. I use plugin ns-embed to show video:
https://github.com/NicolasSiver/nodebb-plugin-ns-embed 
I want to check current user logged in or not and his/her uid in this plugin for tracking purpose. Im newbie in nodejs so although search and try many ways with community search results but unfortunately still not successfully.
I want to ask you a help how I can : check current user logged in or not and his/her uid in this plugin, in particular, I need add check in this file:
https://github.com/NicolasSiver/nodebb-plugin-ns-embed/blob/master/plugin/rules.js
Insert check code before line 28:
 Current:
` for (i = 0; i < len; ++i) {
                rule = rules[i];
                try {`

Check will be:
` for (i = 0; i < len; ++i) {
                rule = rules[i];
               //
              //get current user uid
              //
              if (<current user uid>){
                 //do something here
             }

                try {`


Thanks so much for any advice from you.
Navix
