### ISSUE TITLE
Add salt to password 

### ISSUE THREAD

**Issue by Hawkings** [NodeBB/NodeBB#3753]
After inspecting the code I have discovered that a salt is not added to the password before the hashing. For improved security in case of a compromised server database, the passwords should be salted.

**Comment by NicolasSiver** [comment]
:+1:

**Comment by Hawkings** [comment]
I suggest a default salt length of 128 bits

**Comment by julianlam** [comment]
I believe the bcrypt module automatically adds salts to the passwords
before saving... but of course I could be wrong.

**Comment by Hawkings** [comment]
Salts have to be stored in the database (because they have to be retrieved to check if a password is correct). If I'm not wrong, bcrypt does not communicate with the database so it's impossible for it to use a salt.

**Comment by barisusakli** [comment]
http://stackoverflow.com/questions/6832445/how-can-bcrypt-have-built-in-salts

part of the stored hash is the salt
