### ISSUE TITLE
Markdown code blocks at the beginning of a posting are filtered

### ISSUE THREAD

**Issue by escitalopram** [NodeBB/NodeBB#3754]
Steps to reproduce:
* Write a posting starting with a markdown code block: [4 spaces][some text]
* Submit it

Expected result: First line is Markdown code block formatted
Actual result: Not code block formatted

This problem also occurs when editing a posting. The preview works normally.

**Comment by barisusakli** [comment]
Happens because we do `content.trim()` before we save the post. Could be changed to `rtrim`
