### ISSUE TITLE
pages beyond first one are not indexed

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3758]

**Comment by julianlam** [comment]
I thought this was handled through meta `next` and `prev` tags?

**Comment by julianlam** [comment]
The links *do* work, so they'll likely be followed by Google and indexed...

**Comment by barisusakli** [comment]
Yeah the prev and next links are present in <head> but the pages don't seem to be indexed. For example

https://community.nodebb.org/topic/104/hmmm-testing/72 has content `ornitorenk`

But no results in [google](https://www.google.ca/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site%3Acommunity.nodebb.org%20ornitorenk)

Same with other topics. I also submitted the page from google webmaster tools a week ago.

**Comment by julianlam** [comment]
Fixed via 68c3f9d849b266a66a607984d89003310335f5a6

![selection_012](https://cloud.githubusercontent.com/assets/923011/10831671/4c8a2d7a-7e5d-11e5-9609-068f34a1e1aa.png)

... after 3-4 days. :+1:

**Comment by julianlam** [comment]
Re-opening for now until verified fixed.

**Comment by julianlam** [comment]
https://www.google.ca/search?q=site%3Acommunity.nodebb.org+ornitorenk&oq=site%3Acommunity.no&aqs=chrome.3.69i57j69i59l3.3049j0j9&sourceid=chrome&es_sm=93&ie=UTF-8

Fixed @barisusakli :dog:
