### ISSUE TITLE
Bookmark isn't presented when post count <= 10

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#3759]
Small bug in the public/src/client/topic.js file, in the handleBookmark function:

this line:  `else if (bookmark && (!config.usePagination || (config.usePagination && pagination.currentPage === 1)) && ajaxify.data.postcount > 10)`

causes the bookmark not to be shown even if pagination isn't enabled.

It should be:
`else if (bookmark && (!config.usePagination || (config.usePagination && pagination.currentPage === 1 && ajaxify.data.postcount > 10)))`

**Comment by barisusakli** [comment]
Actually this was intentional, maybe it should be a lower number though, you don't really need the bookmark alert if the topic has only a  few posts.

**Comment by bdharrington7** [comment]
Oh, interesting. Was it for space savings? 10 might be a little high. Maybe
configurable?

**Comment by barisusakli** [comment]
I didn't think about that, that's a nice idea. I adjusted it down to 5 posts and bookmark wont be saved if there are less than 5 posts.
