### ISSUE TITLE
lwip@0.0.7 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by voidstarfire** [NodeBB/NodeBB#3760]
Following a very standard install from a fresh Ubuntu server here:
https://docs.nodebb.org/en/latest/installing/os/ubuntu.html

Running
- Ubuntu 14.04.3 LTS  
- Node v4.2.1
- NPM 3.3.6

I run sudo npm install --production

```
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
make: Leaving directory `/var/www/thewebsite.com/forum/nodebb/node_modules/lwip/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/thewebsite.com/forum/nodebb/node_modules/lwip
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm verb lifecycle lwip@0.0.7~install: unsafe-perm in lifecycle false
npm verb lifecycle lwip@0.0.7~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/www/thewebsite.com/forum/nodebb/node_modules/lwip/node_modules/.bin:/var/www/thewebsite.com/forum/nodebb/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle lwip@0.0.7~install: CWD: /var/www/thewebsite.com/forum/nodebb/node_modules/lwip
npm info lifecycle lwip@0.0.7~install: Failed to exec install script
npm verb unlock done using /home/oduser/.npm/_locks/staging-cd06958503b4c164.lock for /var/www/thewebsite.com/forum/nodebb/node_modules/.staging
npm verb stack Error: lwip@0.0.7 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid lwip@0.0.7
npm verb cwd /var/www/thewebsite.com/forum/nodebb
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/thewebsite.com/forum/nodebb/npm-debug.log
```

**Comment by barisusakli** [comment]
Can you https://github.com/NodeBB/NodeBB/blob/v0.8.x/package.json#L36 to 0.0.8 and see if it works?

**Comment by voidstarfire** [comment]
Massive error:

```
make: Leaving directory `/var/www/universepandemic.com/forum/nodebb/node_modules/lwip/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/universepandemic.com/forum/nodebb/node_modules/lwip
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
nodebb@0.8.2 /var/www/universepandemic.com/forum/nodebb
```

And more after a ton of packages

```
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/universepandemic.com/forum/nodebb/npm-debug.log
```

**Comment by barisusakli** [comment]
Maybe ask here https://community.nodebb.org/topic/6478/nodejs-4-0-released/13 someone managed to get lwip 0.0.8 working.

We removed the dependency on lwip on master so this won't be an issue once we launch 0.9.0

**Comment by voidstarfire** [comment]
Any idea when that will be? I can't run this until then :-/

**Comment by barisusakli** [comment]
Aiming for end of month for 0.9.0.

The log you posted still seems to be installing 0.0.7. Maybe try to clean your node_modules folder and retry npm install

**Comment by voidstarfire** [comment]
I had to do sudo npm install -g lwip and it works. Shame it doesn't run. Really looking forwards for the new version, really great work.

**Comment by Radiergummi** [comment]
I just managed to install `0.0.8` by modifying the dependency in NodeBB's `package.json` and installing with `npm install lwip`

**Comment by barisusakli** [comment]
@voidstarfire are you saying installing lwip 0.0.8 works but nodebb doesn't run?

**Comment by prestodigital** [comment]
I too am having (what looks to be) the same issue on Mac OSX 10.9.5 with Node v0.4.11

Bruce-iMac:nodeBB bwmadmin$ sudo npm install
-
> heapdump@0.3.7 install /Users/bwmadmin/NodeBB/node_modules/heapdump
> node-gyp rebuild


node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.inherits (util.js:425:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:63:6)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/readable.js:1:90)
    at Module._compile (module.js:402:26)
 
> mmmagic@0.4.0 install /Users/bwmadmin/NodeBB/node_modules/mmmagic
> node-gyp rebuild

-
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.inherits (util.js:425:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:63:6)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/readable.js:1:90)
    at Module._compile (module.js:402:26)
|
> lwip@0.0.7 install /Users/bwmadmin/NodeBB/node_modules/lwip
> node-gyp rebuild


node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.inherits (util.js:425:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:63:6)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/readable.js:1:90)
    at Module._compile (module.js:402:26)
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bwmadmin/NodeBB/npm-debug.log
Bruce-iMac:nodeBB bwmadmin$

**Comment by voidstarfire** [comment]
Yes it builds be it fails on the setup admin page. I can't get the error log right now but it's easy to replicate.

**Comment by ace-leandev** [comment]
So we cant use Nodejs 4?
I got many errors too.
Should i use 0.8?

**Comment by voidstarfire** [comment]
The problem that I face is that I can't downgrade node :-/. So basically most users can't use NodeBB as it stands.

**Comment by ace-leandev** [comment]
I've replaced my node.exe (v4) with node.exe (0.12) in Program Files. 
The setup ran but leveldb is not available.


This looks like a new installation, so you'll have to answer a few questions abo
ut your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://localhost:4567)
Please enter a NodeBB secret (a626b6c3-c15c-440c-b223-0a02d11b7774)
Which database to use (redis) level

17/10 03:24 [10052] - info: Now configuring level database:
17/10 03:24 [10052] - warn: NodeBB Setup Aborted.
 Error: unknown database : level
    at success (c:\Users\Ace\nodejs\NodeBB\install\databases.js:67:19)
    at c:\Users\Ace\nodejs\NodeBB\install\databases.js:93:4
    at fn (c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:717:34)
    at c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:1170:16
    at c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:172:37
    at c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:677:43
    at c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:173:37
    at Object.async.waterfall (c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib
\async.js:681:44)
    at module.exports (c:\Users\Ace\nodejs\NodeBB\install\databases.js:89:8)
    at c:\Users\Ace\nodejs\NodeBB\src\install.js:160:5

Ace@ACER ~/nodejs/NodeBB (v0.8.x)

**Comment by barisusakli** [comment]
leveldb is no longer supported use redis or mongo

**Comment by voidstarfire** [comment]
As a side note, do we have any way of installing on Node 4? (Maybe some alternative route for the time being? Like node N?)

**Comment by julianlam** [comment]
@voidstarfire Have you considered using `master`? We no longer require `lwip` as a dependency.

**Comment by voidstarfire** [comment]
Installation is different though, know where I can find instructions for Ubuntu?

**Comment by julianlam** [comment]
For `master` branch? They're the same, just `git clone` instead of `git clone -b v0.8.x`

**Comment by julianlam** [comment]
... or if you're already set up, `git checkout master && rm -rf node_modules && npm i`

**Comment by voidstarfire** [comment]
```git clone -b master https://github.com/NodeBB/NodeBB.git nodebb```

I get a load of problems though.
Firstly I couldn't connect to reddit because ```redisearch``` was failing.

Fixed that with:
```sudo npm i redisearch@0.0.5```
before ```sudo npm install```

Now the whole setup process runs but now I get 

```ERR_CONNECTION_REFUSED```

```sudo ./nodebb log``` shows that the service is running.

**Comment by voidstarfire** [comment]
I get the following now:

```25/10 08:58 [30118] - error: Your Redis version is not new enough to support NodeBB, please upgrade Redis to v2.8.9 or higher.```

But I have the latest Ubuntu version.. :-/

**Comment by julianlam** [comment]
Latest Ubuntu version is old, use the PPA :)

https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server

sudo add-apt-repository ppa:chris-lea/redis-server
sudo apt-get update
sudo apt-get upgrade

**Comment by voidstarfire** [comment]
Thanks already on the case, forum is now working at 
http://forum.universepandemic.com/

Hope this helps everyone else :-)

**Comment by voidstarfire** [comment]
My other main issue now is that I cannot get any email packages working.

**Comment by edasque** [comment]
I have a similar problem where I install an email plugin (mandrill), configure it, reload, etc. yet it still says I don't have an email provider.

**Comment by cnvo** [comment]
I can confirm the same issue @edasque and @voidstarfire is having.
![screen shot 2015-10-27 at 6 44 45 pm](https://cloud.githubusercontent.com/assets/113159/10774914/dbe0fdde-7cda-11e5-89ab-966b9f799c7b.png)

Installed the Mandrill email plugin.

**Comment by edasque** [comment]
It's because master now uses filter- for the email hook and check for this to see if email is enabled. The version of the mandrill plugin isn't the latest and doesn't include this change. The latest one does. I am not sure how a given version of nodebb decides what plugin versions to pull.
