### ISSUE TITLE
leveldb issue

### ISSUE THREAD

**Issue by ace-leandev** [NodeBB/NodeBB#3761]
Because nodejs  v4 wont start the App, I've replaced my node.exe (v4) with node.exe (0.12) in Program Files. 
The setup ran but leveldb is not available. I've already installed levelup , leveldown.

This looks like a new installation, so you'll have to answer a few questions abo
ut your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://localhost:4567)
Please enter a NodeBB secret (a626b6c3-c15c-440c-b223-0a02d11b7774)
Which database to use (redis) level

17/10 03:24 [10052] - info: Now configuring level database:
17/10 03:24 [10052] - warn: NodeBB Setup Aborted.
Error: unknown database : level
at success (c:\Users\Ace\nodejs\NodeBB\install\databases.js:67:19)
at c:\Users\Ace\nodejs\NodeBB\install\databases.js:93:4
at fn (c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:717:34)
at c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:1170:16
at c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:172:37
at c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:677:43
at c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib\async.js:173:37
at Object.async.waterfall (c:\Users\Ace\nodejs\NodeBB\node_modules\async\lib
\async.js:681:44)
at module.exports (c:\Users\Ace\nodejs\NodeBB\install\databases.js:89:8)
at c:\Users\Ace\nodejs\NodeBB\src\install.js:160:5

Ace@ACER ~/nodejs/NodeBB (v0.8.x)

**Comment by barisusakli** [comment]
leveldb is no longer supported, use redis or mongodb
