### ISSUE TITLE
Sort by tag, filter by tag

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#3762]
There should be a way to sort posts in the category view by tag or to filter them by tag.

**Comment by luofan189** [comment]
+1 for this, I like this feature!

**Comment by agarcia17** [comment]
+1 :)

**Comment by martyalicante** [comment]
+100

**Comment by renato** [comment]
@barisusakli I'm really sorry for necrobumping this issue, but is this possible (show the intersection between a category and a tag)?

**Comment by barisusakli** [comment]
Yes, use query params https://community.nodebb.org/category/3/nodebb-development?tag=nodebb

**Comment by exomarty** [comment]
Lol was this even used on a plugin or layout?

**Comment by barisusakli** [comment]
Some themes use it.

**Comment by exomarty** [comment]
Do you have any example?

**Comment by priyanka-bizstack** [comment]
After i create a topic by passing tag in the request body, topic gets created. But when trying to get recent with tags filter http://0.0.0.0:4567/api/recent?cid=31&_uid=3&tag=advice, this returns empty, any other settings to do?

**Comment by priyanka-bizstack** [comment]
Can we filter by tags for top topics?
