### ISSUE TITLE
ACP: Check for updates

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#3763]
~~On the ACP dashboard, tell the admin if the site is up to date with the latest patch version, minor version, and major version.~~ Send notifications to admins of updates when they arrive (by polling GitHub or something), and give a link to the updating docs.

The second part could be done in a plugin, but it would be good if it were in core IMO.

**Comment by psychobunny** [comment]
Don't we do this already? (The first part)

Its on the main dashboard screen in ACP

**Comment by pitaj** [comment]
Yes, I guess it does. Still think the second part would be good.
