### ISSUE TITLE
Bug display categories

### ISSUE THREAD

**Issue by XenTerSeO** [NodeBB/NodeBB#3766]
1 - We have categories:

![bug_notif](https://cloud.githubusercontent.com/assets/14257845/10576355/59ae53fe-766b-11e5-9fa6-f23f4e636f92.png)

2 - Put the paren:

![bug_notif](https://cloud.githubusercontent.com/assets/14257845/10576360/628c9058-766b-11e5-91eb-01b947ea4e44.png)

3 - Remove parent:

![bug_notif](https://cloud.githubusercontent.com/assets/14257845/10576364/67924ef8-766b-11e5-88a7-7d4a410cbe35.png)

---

As can be seen, the second category is displayed in the list of categories.
...but in fact it is the last:

![bug_notif](https://cloud.githubusercontent.com/assets/14257845/10576366/6b27838a-766b-11e5-8825-3a83f8624d6e.png)

**Comment by barisusakli** [comment]
This seems to be fixed in https://github.com/NodeBB/NodeBB/issues/3686
