### ISSUE TITLE
Bug with the number of threads/topics

### ISSUE THREAD

**Issue by vctfernandes** [NodeBB/NodeBB#3767]
Hey guys,

I've noticed a bug that can be reproduced by:
1) Go to https://community.nodebb.org/category/1/announcements (or any other category of a NodeBB installation of your own)
2) Open a thread by clicking on its name (make sure you're on the top of the page)
3) Once the page fully loads, hit the back button on the browser
4) On the upper left, you'll see: "NaN out of 41", where NaN should be a number
5) It goes away if you scroll the page.

I don't seem to have the skills to fix this by myself :grin:

**Comment by joshterrell805** [comment]
This is still a problem on the latest 0.9.x (just installed last night), but it looks like there was a commit to fix it 23 days ago. I looked through the changes of 6b1834d and made sure they are all still in 0.9.x's HEAD. Thoughts?

**Comment by vctfernandes** [comment]
Besides the NaN issue, now when you do the procedure I described, the first thread will vanish, only reappearing after a refresh/scrolling.
