### ISSUE TITLE
[Bug] Can not upload multiple images on mobile, but could on desktop

### ISSUE THREAD

**Issue by luofan189** [NodeBB/NodeBB#3772]
Can not upload multiple images on mobile, but could on desktop. On mobile, when I upload multiple images, they all point to the same URL. I have my site connected with imgur. This issue does NOT happen on desktop browser. This might be a bug of imgur plugin, if yes, I could move it over there.

Btw, great software!

**Comment by barisusakli** [comment]
might be fixed here https://github.com/NodeBB/nodebb-plugin-composer-default/issues/4

**Comment by luofan189** [comment]
That is exact the issue. Cool! Thanks! I will close this issue.
