### ISSUE TITLE
The disappearance first topic by clicking on the 'back'

### ISSUE THREAD

**Issue by XenTerSeO** [NodeBB/NodeBB#3774]
![1](https://cloud.githubusercontent.com/assets/14257845/10651383/dda96520-7857-11e5-9a5b-8bc507b2b494.png)
![2](https://cloud.githubusercontent.com/assets/14257845/10651386/e15e91cc-7857-11e5-9e74-8d1117532c2e.png)
![3](https://cloud.githubusercontent.com/assets/14257845/10651388/e2fe8b86-7857-11e5-9173-fb62fa85fdaf.png)

**Comment by julianlam** [comment]
Looks to be related to infinite scrolling, as scrolling down a tick and back up restores the missing topic...

**Comment by XenTerSeO** [comment]
@julianlam I'm sure you're right.
