### ISSUE TITLE
FontAwesome

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3775]
Update to latest in next release.
Thanks ;)

**Comment by barisusakli** [comment]
Isn't latest 4.4.0? https://github.com/NodeBB/NodeBB/commit/bc9e96f2104ba2ac73d9fc74c807bade4f33a915

**Comment by NicolasSiver** [comment]
Nice, It's already in master.
Thanks.

**Comment by julianlam** [comment]
Yeah, included an icon search in the selector too
