### ISSUE TITLE
Let's extend themes with widgets

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3777]
I have started to check if it good approach at all - https://community.nodebb.org/topic/6771/posts-with-widgets/2

My main point, for users, if you give them ability to add something via plugins, they should not edit directly templates. I think better approach is to have widgets and hooks. And popular plugins motivate theme developers to add necessary widget zones ;)

- Posts should support widgets (classic paging or infinite scroll)
- User profile should support widgets

Hooks ideas: 

#### User Profile

Would be great to have filter for user's metrics: posts, reputation, views, etc. (https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/account/profile.tpl#L51-L69) . `filter:user.metrics`?

**Comment by yariplus** [comment]
Sounds like a great idea if it can work!

The User Profile hook isn't really related to widgets. But it should be it's own issue. I can think of at least 5 different hooks that should be there, but aren't yet.

**Comment by julianlam** [comment]
Sorry for the delay -- widget areas ought to be added back to Persona if we can't get a new system in place by v1.0.0, @psychobunny ?

**Comment by NicolasSiver** [comment]
@julianlam could you share info about new widget system?
My main concern, do I need rewrite widget for the new system?

**Comment by julianlam** [comment]
I have no involvement with the planned update to the widget system :frowning: It's all @psychobunny's brainchild :smile:

**Comment by psychobunny** [comment]
Can we break this down into several smaller feature requests? I committed a hook for something related to this earlier today for profile edit page, which was mentioned in OP: https://github.com/NodeBB/NodeBB/issues/3837

Best if we can get smaller tackle-able issues rather than a big meta issue, thanks!
