### ISSUE TITLE
Empty sitemap

### ISSUE THREAD

**Issue by ps1dr3x** [NodeBB/NodeBB#3781]
I have a problem with the sitemap. 

![temp](https://cloud.githubusercontent.com/assets/10249616/10710918/b58e0094-7a6b-11e5-8f30-dcb0b5fe45a2.png)

I think that it's not my fault, i didn't find anything about it.

Anyway thanks for the help and for this nice software ;)

**Comment by julianlam** [comment]
Could not reproduce, unfortunately, please provide git hash so we can debug. Thanks!

**Comment by kdrdgn** [comment]
Setings  > Web Crawler - [View Sitemap] button opens an empty xml.

**Comment by ps1dr3x** [comment]
I just tried to clone the latest git and run the forum with my db, same problem.. Sorry but i don't know how to provide git hash because i have not cloned the repository the first time so i don't have the .git dir in the actual installation :-/

**Comment by julianlam** [comment]
What OS are you using?

**Comment by ps1dr3x** [comment]
Debian jessie

**Comment by ApfelUser** [comment]
Same here

**Comment by XenTerSeO** [comment]
+ same here.
