### ISSUE TITLE
If a message contains a picture, after the upgrade editing the, they can not be opened

### ISSUE THREAD

**Issue by XenTerSeO** [NodeBB/NodeBB#3784]
To solve necessary to refresh the page.

Example: https://community.nodebb.org/topic/6802/testingerring

**Comment by pitaj** [comment]
I can access the picture just fine. It's showing up, the link to imgur is correct. Are you talking about directly after editing the post?

**Comment by XenTerSeO** [comment]
@pitaj yes, after editing the post.
