### ISSUE TITLE
Chat with non-confirmed email user causes internal error

### ISSUE THREAD

**Issue by cubehouse** [NodeBB/NodeBB#3788]
If you chat with a user who hasn't yet confirmed their email address, the non-confirmed user can attempt to reply to the chat. If they click the "fullscreen" icon to expand the chat window, the URL will try to load /chat/[username], the user will get the message: "Internal error. Oops! Looks like something went wrong!"

Expected result: Either don't allow non-confirmed users to receive chat or fail gracefully when loading the chat "fullscreen" page.

Git hash: 28a4703a4bf3d0ec81d14bf20724c707ec6a4eef
NodeBB version: 0.8.2

I've pasted the log from the server below:

nodebb-1 | 2015-10-25T11:59:14.504672505Z 25/10 11:59 [57] - error: /api/chats/[username]
nodebb-1 | 2015-10-25T11:59:14.504704209Z  Error: [[error:email-not-confirmed-chat]]
nodebb-1 | 2015-10-25T11:59:14.504710079Z     at /opt/nodebb/src/messaging.js:379:23
nodebb-1 | 2015-10-25T11:59:14.504713589Z     at /opt/nodebb/src/user.js:45:4
nodebb-1 | 2015-10-25T11:59:14.504717846Z     at fireFilterHook (/opt/nodebb/src/plugins/hooks.js:86:11)
nodebb-1 | 2015-10-25T11:59:14.504721883Z     at Object.Plugins.fireHook (/opt/nodebb/src/plugins/hooks.js:70:5)
nodebb-1 | 2015-10-25T11:59:14.504726205Z     at modifyUserData (/opt/nodebb/src/user.js:141:11)
nodebb-1 | 2015-10-25T11:59:14.504729904Z     at /opt/nodebb/src/user.js:81:4
nodebb-1 | 2015-10-25T11:59:14.504735127Z     at /opt/nodebb/src/database/mongo/hash.js:139:4
nodebb-1 | 2015-10-25T11:59:14.504739044Z     at handleCallback (/opt/nodebb/node_modules/mongodb/lib/utils.js:96:12)
nodebb-1 | 2015-10-25T11:59:14.504743078Z     at /opt/nodebb/node_modules/mongodb/lib/cursor.js:842:16
nodebb-1 | 2015-10-25T11:59:14.504747601Z     at handleCallback (/opt/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:249:5)

**Comment by barisusakli** [comment]
Looks like a bug in the error middleware, it doesn't seem to handle any errors.
