### ISSUE TITLE
image uploads

### ISSUE THREAD

**Issue by Jdesk** [NodeBB/NodeBB#3791]
i'm really trying to make this software work out - i like it alot - we got 100k pageviews in less than 24 hours, image upload functionality is gone..  I implemented the imagur plugin and subsequently removed it - as well as twitter sso - it's not working on your site either (last time I checked) - but no image uploads - error 500.  Also 0.0.7 of one of the packages (it's late so I can't think off the top of my head) when updated to 0.0.8 manually is fine.  (there is only one dependency in package.json with that version so hopefully you already know).

**Comment by julianlam** [comment]
For implementation issues, please create a new topic on our community forum. 

Thanks!

**Comment by Jdesk** [comment]
My apologies - went there then saw a message asking for issues to be submitted here - found that odd as well.  anyhow I corrected all of the above - but twitter sso no go.  I will play with it in the morning.  I can write a new one and then will post in here for everyone - but I don't want to step on your toes :-)

**Comment by julianlam** [comment]
oof, well that's embarrassing :laughing:

There didn't seem to be any direct issues in your original submission, so that is best handled in the forum.

**Comment by Jdesk** [comment]
I totally understand man my bad - perhaps you can bring me on board here - i have a few helpful things and I want to contribute to something I actually believe in that's not all "mainstream like wordpress" - eg. this and ghost are my two top priorities personally right now.  I see a bright future for this.  In particular the dockerized version which is where I'm putting my energies atm.  Lmk.

**Comment by Jdesk** [comment]
i'm building an automated install of the whole thing with nginx configured.

**Comment by Jdesk** [comment]
with a few extra performance boosts on the nginx side.

**Comment by Jdesk** [comment]
if you guys are anything like me - it's impossible to do a million things at once.. extra hands won't ever hurt.   forget my projects - I want to be a part of this and help wherever I can.

**Comment by pitaj** [comment]
@Jdesk Cool
