### ISSUE TITLE
(very scary bug) Not change address if you leave the topic while scrolling

### ISSUE THREAD

**Issue by XenTerSeO** [NodeBB/NodeBB#3794]
![1443885765164-1](https://cloud.githubusercontent.com/assets/14257845/10776817/122a2398-7d26-11e5-9c12-ea5bbb6281b1.png)

**Comment by XenTerSeO** [comment]
This is because the address on message formed with a delay. If you leave the topic while the link is not formed - a bug.

**Comment by julianlam** [comment]
Legitimate bug, but I really want to know how this is "scary" to you :laughing:

**Comment by XenTerSeO** [comment]
The fact that a long time I could not understand the reason for this error.
I thought that it occurs randomly.
