### ISSUE TITLE
Markdown table support

### ISSUE THREAD

**Issue by ApfelUser** [NodeBB/NodeBB#3796]
Hey.

```
| Tables   |      Are       |  Cool   |
|----------|:--------------:|--------:|
| col 1 is |       x1       | $1600   |
| col 2 is |       x2       |   $12   |
| col 3 is |       x3       |    $1   |
```

should look like:

| Tables   |      Are       |  Cool   |
|----------|:--------------:|--------:|
| col 1 is |       x1       | $1600   |
| col 2 is |       x2       |   $12   |
| col 3 is |       x3       |    $1   |

in my opinion? Any plans to implement this?

**Comment by lots0logs** [comment]
+1 :+1:

**Comment by barisusakli** [comment]
Feel free to send a PR to persona/vanilla, this is just styling in the theme no?

**Comment by lots0logs** [comment]
@barisusakli I think it has to be implemented in the markdown plugin so that it gets converted to HTML. If I have some time this weekend I will try to look into it :smile:

**Comment by barisusakli** [comment]
It is already converted to an html table try posting the above on our forum, it will be an html table in the post body. It just needs styling.

**Comment by lots0logs** [comment]
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/10833844/f7876fd0-7e62-11e5-9531-dcfeae790a8a.gif)
