### ISSUE TITLE
Getting unread notifications but no unread topics

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3798]
This seems to happen quite a lot. I notice in the navbar I have an unread notification but when I visit the page at `/unread` I see "There are no unread topics.". Here's a screenshot:

![screenshot 2015-10-29 at 16 21 15](https://cloud.githubusercontent.com/assets/1963288/10824693/4ffc6954-7e59-11e5-82eb-d20fba41ccc6.png)

**Comment by NicolasSiver** [comment]
Confirming, there is such issue ;)

**Comment by barisusakli** [comment]
Is it going away when you do a hard reload? This would happen if someone posts a topic and then deletes it before you can go in a mark it read.

**Comment by henrywright** [comment]
No. Hard reload doesn't solve it. Also, the problem is getting more and more frequent, I doubt someone is posting and deleting that often

**Comment by NicolasSiver** [comment]
@barisusakli  Can issue transit from `needs confirmation` to `bug`?

**Comment by barisusakli** [comment]
Not until we know how to reproduce.

**Comment by henrywright** [comment]
@barisusakli If you could get a list of everything I'm _watching_ and then set up a dummy user who is watching those exact same things you may be able to reproduce the problem? You may have to leave the dummy user logged in to community.nodebb.org for ~15 minutes to see it happen.

**Comment by nhlpl** [comment]
Testing Ground issue and related to Mark as Read button as it shows TG in a drop down menu when some other topics starts to come in realtime (new posts from some other categories).

I have reported it here https://github.com/NodeBB/NodeBB/issues/4272
