### ISSUE TITLE
Reputation settings

### ISSUE THREAD

**Issue by PacketDev** [NodeBB/NodeBB#3801]
It'd be a nice addition if we could add a rating threshold that a user would need to pass to rate positive OR negative (currently only negative is supported).

https://i.gyazo.com/3750cbc92d30738b641012405eb9a3c6.png

Just copying the first option as 'Minimum reputation to upvote posts' would be very fancy :)

**Comment by Kowlin** [comment]
Out of curiosity, how will a user gain reputation if nobody can give reputation?

**Comment by PacketDev** [comment]
I would assume an administrator could bypass the limit.
