### ISSUE TITLE
Migration script to remove users with gravatar

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3803]
Since gravatar is no longer core

**Comment by psychobunny** [comment]
Perhaps move this into a `plugin:gravatar` hash that the future gravatar plugin can utilize

**Comment by NicolasSiver** [comment]
Did you guys develop scheme how plugins can work with avatars? Or you just chopped Gravatar from the core without thoughts how it will be used via plugins in future? ;)

For example, if you designed good API for this (several filters, actions and widget zone), I see possibility for such avatar-plugins like:

- Show Baldur's Gate portrait from username hash, etc.
- Crazy borders for the avatar, etc.

**Comment by julianlam** [comment]
We chopped it first.

Before v0.9.0 launch, I'll probably want to add in hooks so we can *build* a Gravatar plugin... if not building the plugin itself.

Then, yes, you'll be able to create your own plugins to let users use avatars from different sources :smile:
