### ISSUE TITLE
Users unable to change/remove profile avatars

### ISSUE THREAD

**Issue by Marc-Boisvert-Dupras** [NodeBB/NodeBB#3804]
Alright so basically, everything was working fine until we pulled the git repo from master on Monday (Oct. 26th) (perhaps we shouldn't have?). I do not have access to the server console so I cannot tell you precisely which git hash we're on.

Since then, users on our forums cannot change their account pictures. This pops up in the NodeBB log everytime a user tries to change their picture:
29/10 14:06 [15435] - error: unable to delete picture /tmp/ZBXRoFYlE-3oKz3fQst8hjbH.jpg

Could it be a permission issue? Or is it an issue with NodeBB itself?

Let me know if you need more details.

**Comment by barisusakli** [comment]
Please pull latest and run npm i and try again. This is probably resolved on latest.
