### ISSUE TITLE
Empty logs with 0.8.2 and theme lavender

### ISSUE THREAD

**Issue by luofan189** [NodeBB/NodeBB#3813]
For some reason, after I switched to them lavender, I can not see any logs output any more. The logs were there when I use persona. I use forever and crontab to auto-start my nodebb.

**Comment by luofan189** [comment]
I think I figured, I should just use nodebb start, it has the proper logs populated. Could somebody confirm with me that nodebb start will auto-restart if app crashes, right?

**Comment by psychobunny** [comment]
Yes it will :)

**Comment by luofan189** [comment]
Thanks!
