### ISSUE TITLE
Ability to change the position of the avatar

### ISSUE THREAD

**Issue by XenTerSeO** [NodeBB/NodeBB#3819]
Now you can upload cover in the profile.
You can change its position.

Perhaps it would be great to do a function for avatars?

**Comment by julianlam** [comment]
Perhaps :smile: Different ball game, though. Cover photo is a background in a container, whereas an avatar is... an image.

We don't have any client-side image editing tools at the moment :frowning:

**Comment by pichalite** [comment]
This can be closed. With the ability to crop avatar when uploading available in core you can pick the position and crop it before uploading.
