### ISSUE TITLE
Topic/reply editor 'Compose' help link.

### ISSUE THREAD

**Issue by tekojo** [NodeBB/NodeBB#3829]
When editing a topic/reply, there is a small help link titled 'Compose ?' at the top right corner of the editor window. The link provides a pop-up with a link to http://daringfireball.net/projects/markdown/syntax
While daringfireball is a good page about markdown, a cheat sheet like:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
is more helpful to users.

Also would it be possible to open the link in a new tab/window? Now it throws you off to another site right in the middle of editing.

**Comment by barisusakli** [comment]
The help text is in this plugin and not editable right now https://github.com/julianlam/nodebb-plugin-markdown/blob/master/index.js#L120

**Comment by julianlam** [comment]
Sure, sounds good to me.
