### ISSUE TITLE
User Settings: hook?

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3837]
I saw you did changes to user's settings page?
Did you add some hook so additional buttons/actions can be added?

<img width="218" alt="screen shot 2015-11-05 at 8 06 09 pm" src="https://cloud.githubusercontent.com/assets/135263/10986553/08dd4f70-83f9-11e5-8457-ee19bea5b52f.png">

Is it a good idea to have hook for such button?

Real Example: `Edit Custom Fields`, and by clicking it, user will visit dedicated page.

**Comment by NicolasSiver** [comment]
Related to #3777

**Comment by psychobunny** [comment]
> Real Example: Edit Custom Fields, and by clicking it, user will visit dedicated page.

Would it be better to add a section on the top right menu in profile? There's a hook for that already, used by push bullet, two factor auth, and some others, for their own profile page

Also, the edit section hasn't been revamped yet, will look into redesigning that soon

**Comment by NicolasSiver** [comment]
@psychobunny I'm not sure that It's more natural way to face custom fields editing. Where you have to find url in the end of the list, not as part of `edit`

<img width="246" alt="screen shot 2015-11-05 at 8 23 24 pm" src="https://cloud.githubusercontent.com/assets/135263/10986796/2da7254a-83fb-11e5-8ca9-e0f12cede4c3.png">

Anyway I didn't know about such hook. 
Maybe It's just a question of habit... Does hook support priorities, so link can be placed near something, for example: 

- Edit
- Edit Custom Fields

;)

**Comment by psychobunny** [comment]
Okay I agree. I also don't want to end up with 10  buttons on the left for editing things either, so I'll need to think of a better UX first, will definitely keep your hook suggestion in mind. :)

**Comment by psychobunny** [comment]
`filter:user.account.edit`

```
Plugin.editAccount = function(data, callback) {
	data.editButtons.push({
		link: "/my-plugin",
		text: "Edit My Plugin"
	});

	callback(null, data);
};
```

**Comment by NicolasSiver** [comment]
When use of relative path, like `./custom-fields`, should it be resolved from `/edit`?
Now it resolves from `/user`, but we are adding buttons to _edit_ list, aren't we?

i.e. `./edit/my-plugin` should be provide now, to have same pattern as edit for password, username, etc.
