### ISSUE TITLE
User Profile: metrics filter

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3838]
Would be great to have filter for user's metrics, so plugins can alter this collection of metrics, for example remove metrics about followers, but inject amount of points, etc.

<img width="584" alt="screen shot 2015-11-05 at 8 13 22 pm" src="https://cloud.githubusercontent.com/assets/135263/10986641/e3aafd32-83f9-11e5-9572-39b891582f18.png">

Also, add widget zone, somewhere on such page, so widgets with: awards, custom fields, etc. can be injected without need for template editing.

Thanks.

**Comment by NicolasSiver** [comment]
Related to #3777

**Comment by manV** [comment]
This will be awesome if implemented!

**Comment by julianlam** [comment]
Hm, should it be plugin editable (via hook), or plugin **populatable**, and then ordered/included/excluded via user profile setting?

Perhaps I don't want people to see how many profile views I have :smile:

**Comment by NicolasSiver** [comment]
@julianlam - technically both options is Ok.
If it will be array, to _populate_, some tricky plugins can still edit such array. I assume It will be a filter hook.

```
[{type:'views', value: 12390}, {type:'reputation', value: 18}, {type:'plugin:reactions', value: 2931}, ...]
```

Maybe someone will create plugin, `nodebb-plugin-metrics`, so administrator/user can check what metrics to show/use ;)

**Comment by manV** [comment]
@NicolasSiver Can this approach, in some way, also work when we have value other than numbers, like custom markup?

**Comment by julianlam** [comment]
@NicolasSiver Yes, it'd be a filter, no question about that :smile: Having a plugin specify what to show/hide could work, but may be better in core.

The main question is theme compatibility, which ties in to @manV's query -- the moment you add in custom html, things get dicey (security-wise), so would prefer it to stay as #s.

**Comment by NicolasSiver** [comment]
@julianlam if you would like to go with user's settings, please add also admin settings. So Admin can decide if user has such option or not, to mangle with metrics on his/her page ;)

Same applies to https://github.com/NodeBB/NodeBB/issues/3841

**Comment by julianlam** [comment]
Would like @psychobunny's thoughts on this, as it's his design :smile:

**Comment by pichalite** [comment]
It will probably be a nightmare to make it all look good on the theme if you don't know how many of theme items will be.

**Comment by psychobunny** [comment]
Closing this as it's a bit old and no demand for this recently, that said, am happy to accept a PR if anybody has an idea for implementation here.
