### ISSUE TITLE
ACP: ability to disable infinite scroll on the forum

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3841]
As an administrator I would like to control infinite scroll feature by enabling or disabling it.

**Comment by yariplus** [comment]
:+1:

**Comment by NicolasSiver** [comment]
@julianlam @psychobunny @barisusakli you are OK, if I will create Pull Request, where will add a new setting `disableUserScrollSetting`.

If activated by Administrator - scrolling will be used that is selected in ACP, and user can't mess with it in User Settings (hidden). If not activated - behavior is the same as now.

So I don't waste yours and mine time...

**Comment by NicolasSiver** [comment]
yes/no ?

**Comment by barisusakli** [comment]
I don't know how I feel about this, I feel like you can just remove the infinite scroll settings from the account/settings.tpl tpl in your custom theme and put it in a plugin using the hook `filter:config.get` and set `usePagination` to true.

**Comment by NicolasSiver** [comment]
Ok, It's much-much easier for me, but I will not ask users to do the same ;)
