### ISSUE TITLE
Windows guide - update plz

### ISSUE THREAD

**Issue by bz123** [NodeBB/NodeBB#3845]
Hey,

plz update the windows guide : http://nodebb-francais.readthedocs.org/projects/nodebb/en/latest/installing/os/windows8.html

It literally took me a few hours fiddling around and installing all kind of C++ etc cause I was getting nodebb 0.8.x which is decapitated version I asume. 
Also let people know that they need to use node 0.12 or something like that and not 4. not 0.8 or whatever.

I was hitting a build error with lwip... which doesn't even exist in any version. As soon as I figured out that oh that command am C/P from that guide actually gets me an old version, I was able to run it on windows in 2 mins.

I don't make this to whine about anything, I have some ---fun--- in the learning process and I understand that you are too busy, but this will prolly save a lot of time to a lot of people like me. 

Thanks for the amazing forum.

**Comment by barisusakli** [comment]
You can send a PR to the docs?

**Comment by psychobunny** [comment]
Yeah, there's an edit button on the top right which easily allows you to update it. This is an open source and free software so we rely on people like you to help out :)

I'm glad you figured it out though. If you have time please feel free to help :)
