### ISSUE TITLE
filter:user.ban hook

### ISSUE THREAD

**Issue by yulianovdey** [NodeBB/NodeBB#3846]
I came across #1812 but didn't find any other relevant discussion. Is `filter:user.delete` going away completely or being replaced with a `static:user.delete`? If it's not going away, is it possible to add a `user.ban` filter to the roadmap as well?

Thank you.

**Comment by barisusakli** [comment]
`filter:user.delete` will be removed use `static:user.delete` if you want to do something before a user is deleted.

**Comment by yariplus** [comment]
Seems to me like it should be static:user.ban since there's nothing to filter.
