### ISSUE TITLE
MongoDB Lib Undefined Errors in 0.9.0 Upgrade Script

### ISSUE THREAD

**Issue by scottalanmiller** [NodeBB/NodeBB#3847]
Doing a 0.8.2 upgrade to 0.9.0.  This is the error that I receive.

6/11 23:27 [6455] - info: [2015/09/30] Converting default Gravatar image to defa                                            ult User Avatar
6/11 23:27 [6455] - info: [2015/09/30] Converting default Gravatar image to defa                                            ult User Avatar skipped
6/11 23:27 [6455] - info: [2015/11/06] Removing gravatar

/opt/gamrhaus-9.0/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: Callback was already called.
    at /opt/gamrhaus-9.0/node_modules/async/lib/async.js:43:36
    at /opt/gamrhaus-9.0/node_modules/async/lib/async.js:694:17
    at /opt/gamrhaus-9.0/node_modules/async/lib/async.js:173:37
    at /opt/gamrhaus-9.0/src/database/mongo/hash.js:15:4
    at handleCallback (/opt/gamrhaus-9.0/node_modules/mongodb/lib/utils.js:95:12                                            )
    at /opt/gamrhaus-9.0/node_modules/mongodb/lib/collection.js:840:5
    at /opt/gamrhaus-9.0/node_modules/mongodb/node_modules/mongodb-core/lib/topo                                            logies/server.js:756:13
    at Callbacks.emit (/opt/gamrhaus-9.0/node_modules/mongodb/node_modules/mongo                                            db-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/opt/gamrhaus-9.0/node_modules/mongodb/node_modules/                                            mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/opt/gamrhaus-9.0/node_modules/mongodb/node_modules/m                                            ongodb-core/lib/connection/connection.js:262:22)

Error: undefined

**Comment by barisusakli** [comment]
What's the output of `npm ls mongodb` `npm ls async`?

**Comment by scottalanmiller** [comment]
root@iad-lnx-mangodb:/opt/gamrhaus-8.2# npm ls async
nodebb@0.8.2 /opt/gamrhaus-8.2
├── async@1.4.2
├─┬ grunt@0.4.5
│ └── async@0.1.22
├─┬ grunt-contrib-watch@0.6.1
│ └── async@0.2.10
├─┬ lwip@0.0.7
│ └── async@0.9.2
├─┬ nconf@0.7.2
│ └── async@0.9.2
├─┬ nodebb-plugin-dbsearch@0.2.16
│ └── async@0.2.10
├─┬ npm@2.14.3
│ └─┬ request@2.61.0
│   └─┬ form-data@1.0.0-rc3
│     └── async@1.4.2
├─┬ prompt@0.2.14
│ ├─┬ utile@0.2.1
│ │ └── async@0.2.10
│ └─┬ winston@0.8.3
│   └── async@0.2.10
├─┬ redisearch@0.0.4
│ └── async@0.9.2
├─┬ uglify-js@2.4.24
│ └── async@0.2.10
└─┬ winston@1.0.1
  └── async@0.9.2

root@iad-lnx-mangodb:/opt/gamrhaus-8.2# npm ls mongodb
nodebb@0.8.2 /opt/gamrhaus-8.2
└── mongodb@2.0.42  extraneous

npm ERR! extraneous: mongodb@2.0.42 /opt/gamrhaus-8.2/node_modules/mongodb
npm ERR! not ok code 0

**Comment by barisusakli** [comment]
@julianlam not sure if the above change fixes it since I wasn't getting this error.

I remember running into a limit with async when there are too many items in the asyc.series. Maybe that's related. If that's the case gotto trim the upgrade script.

**Comment by julianlam** [comment]
I'll look into this today.

**Comment by scottalanmiller** [comment]
Looks like that did it.  A fresh fetch, pull and upgrade and it worked fine.

**Comment by julianlam** [comment]
Glad to hear it.
