### ISSUE TITLE
0.9 language issue

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3849]
Setting 0.9 to spanish not working correctly
showing variables names

![captura de pantalla 2015-11-07 a las 14 01 39](https://cloud.githubusercontent.com/assets/10746278/11015271/789b7174-8558-11e5-8c2e-c7046de3a2d3.png)

**Comment by martyalicante** [comment]
7/11 14:10 [6202] - warn: [translator] Language 'es_ES' not found. Defaulting to 'en_GB'

**Comment by julianlam** [comment]
Hm, that's weird. Please go into Transifex and update the language code to read `es`

**Comment by martyalicante** [comment]
Not sure what you mean. Spanish been always es_ES

**Comment by julianlam** [comment]
Some helpful person changed it to `es_ES`, when it should just be `es`. That is the language code NodeBB expects :smile:
