### ISSUE TITLE
Profile image upload always disabled

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#3851]
I am able to upload avatars but not profile images, tried to restart etc, not sure if there is extra config for that

![captura de pantalla 2015-11-07 a las 15 38 01](https://cloud.githubusercontent.com/assets/10746278/11015632/a8c341c6-8565-11e5-925d-80092392f1f3.png)

**Comment by barisusakli** [comment]
git hash?

**Comment by martyalicante** [comment]
Happens on first commit of 0.9.0 unless you solve it today

**Comment by barisusakli** [comment]
You can fix it temporarily by enabling `Allow users to upload regular files` under `ACP>Settings>Post` or by installing `nodebb-plugin-imgur`
