### ISSUE TITLE
user icon is not displayed properly in lavender theme 0.9.0

### ISSUE THREAD

**Issue by luofan189** [NodeBB/NodeBB#3855]
In 0.9.0, we have the user icon feature. It shows properly on user profile page, but not right in other places, such as the header bar and topic thumbnail etc

user profile page:
<img width="124" alt="screen shot 2015-11-08 at 1 42 24 pm" src="https://cloud.githubusercontent.com/assets/1351099/11021625/9d43d004-861e-11e5-9a34-2c6482acc5d5.png">

topic list
<img width="463" alt="screen shot 2015-11-08 at 1 42 35 pm" src="https://cloud.githubusercontent.com/assets/1351099/11021627/a8463eb0-861e-11e5-8a8b-762618e6ca46.png">

Env:
nodebb 0.9.0
composer-redactor
lavendar - 2.0.13

Any configuration I missed to do to fix , maybe? Or this is a bug?

**Comment by julianlam** [comment]
Should be resolved with Lavender v3.0.0
