### ISSUE TITLE
Shadow "Guest" within group

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#3858]
I just encountered this entry within the "GNU/Linux User" group on community.nodebb.org
It links to `/user/` without suffix, so "Not Found".

![2015-11-09-024633_2560x1440_scrot](https://cloud.githubusercontent.com/assets/1626775/11024311/cf505d60-868c-11e5-8b45-460b1e398415.png)

I didn't try to kick so you can inspect it on your own.

```
<tr data-uid="0">
  <td>
    <a href="/user/">
      <div class="user-icon" style="background-color: #1b5e20;">[</div>
    </a>
  </td>
  <td class="member-name">
    <a href="/user/">Guest</a> <i title="Group Owner" class="fa fa-star text-warning invisible"></i>
  </td>
```

**Comment by julianlam** [comment]
Hah, why did a guest try to join... or *did* join... odd.

**Comment by julianlam** [comment]
That guest account doesn't seem to be there any more... :frowning:

**Comment by barisusakli** [comment]
It's still there if you scroll down in the member list.

**Comment by frissdiegurke** [comment]
Now he occurred with a post: https://community.nodebb.org/topic/6978/sfsdfdsfds
Same problem there: User-Link buggy, user-icon `[`

**Comment by barisusakli** [comment]
It's fixed in https://github.com/NodeBB/NodeBB/commit/277a3ba2af85f20d0cb6ade13e98513abf7e3e4a not pushed yet.
