### ISSUE TITLE
Registred User can join private groups

### ISSUE THREAD

**Issue by AsBilou** [NodeBB/NodeBB#3861]
Hi there!

I've got an embarrassing problem, i created some private groups for administration like moderator and community management, but all registred users can join this groups despite the fact that this groups are privates.
The only solution to stop people joining is to hide the groups.

I'm on debian and nodebb 0.9.

Is there a fixe published ?

Thx, Bilou.

**Comment by Kowlin** [comment]
Can confirm. This bug is on 0.9.0 as well as on Master. 
http://i.imgur.com/ij7XMnC.gifv

**Comment by barisusakli** [comment]
Weird, I can't repro on latest clicking join just puts me on the queue

**Comment by barisusakli** [comment]
Can you check the setting in ACP>settings>Groups

![image](https://cloud.githubusercontent.com/assets/2583394/11080251/33384014-87e0-11e5-92e9-3f8e25e3da76.png)

**Comment by AsBilou** [comment]
Yes, this options is enabled

**Comment by AsBilou** [comment]
Ok find the bug, the option appears enabled but it's not, i uncheck and check and now everything works

**Comment by julianlam** [comment]
Is this actually fixed @barisusakli? It seems the default behaviour is off even though the ACP default is on

**Comment by MegaGM** [comment]
@barisusakli @julianlam There is a bug somewhere, definitely, but I can't even imagine where :(
At one moment in the past I've encountered the same problem: all registered users were able to join private groups without approval. I was in panic ![](http://smayly.ru/gallery/ava/Kanade/47.jpg)
To solve the issue I had to uncheck/check this checkbox (under "/admin/manage/groups/group_name" route) for all groups.
![](http://i.imgur.com/97xqlLB.png)

It was happened on 0.8.2

**Comment by barisusakli** [comment]
@julianlam yeah default was off but the ACP was hardcoded to checked.
