### ISSUE TITLE
Performance Issue with embeds

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3862]
This issue is related to #3793 

Related, that presence of the embeds/iframes on page, creates huge CPU consumption.

Embeds from:

- Vimeo
- Coub
- Vine

Creates 100% CPU load. I have checked and deleted JS from the page, all that I can find in the header.
After deletion, there is no problem with CPU load. FYI that there are no problems with embeds from these resources.

CPU Profile, maybe it will give you some insights on problem. I very hope this problem will be resolved soon, so I can go further with another plugins ideas. Thanks.

<img width="1218" alt="screen shot 2015-11-09 at 6 46 37 pm" src="https://cloud.githubusercontent.com/assets/135263/11050491/7962fe34-8714-11e5-8d28-8f0ccf529740.png">

Environment:

- NodeBB, `0.8.x` branch
- Command Paging used (no infinite scroll)

**Comment by barisusakli** [comment]
If you run in dev mode you might get better traces in the profile tab.

**Comment by NicolasSiver** [comment]
@barisusakli when I have checked code line - It's templates library.

Also, by dev mode, do you mean this?

<img width="755" alt="screen shot 2015-11-11 at 11 29 49 am" src="https://cloud.githubusercontent.com/assets/135263/11096362/a52ebb94-8867-11e5-840e-54146663bad8.png">

**Comment by barisusakli** [comment]
I mean running nodebb in dev mode so the javascript file isn't uglified.

**Comment by NicolasSiver** [comment]
I'm running NodeBB in dev mode always. `./nodebb dev`
If you start `0.8.2` on your local machine, it will show you correct code line. - `nodebb.min.js 17941`
I thought such profile info will be enough for troubleshooting ;)

**Comment by NicolasSiver** [comment]
@barisusakli 

<img width="970" alt="screen shot 2015-11-11 at 5 59 47 pm" src="https://cloud.githubusercontent.com/assets/135263/11105622/1ce62f4c-889e-11e5-8761-11e965d6b79c.png">

**Comment by barisusakli** [comment]
Hmm probably safe to remove that block @psychobunny ?

It is for using webworkers in templates.js here https://github.com/psychobunny/templates.js/blob/master/lib/templates.js#L33-L42

**Comment by psychobunny** [comment]
It's disabled in NodeBB right now, but its possible other JS code (especially an embed, not surprised) might mess about with it

I'm fine removing that for now

**Comment by NicolasSiver** [comment]
What block of code should I remove to check if it helps?

**Comment by barisusakli** [comment]
Remove all parts that I link 

https://github.com/psychobunny/templates.js/blob/master/lib/templates.js#L33-L42
https://github.com/psychobunny/templates.js/blob/master/lib/templates.js#L48-L80

Let us know if you see any improvement.

**Comment by NicolasSiver** [comment]
@barisusakli @psychobunny yes. Removing these code blocks solves problem with performance. There is no load on CPU. Everything works fine.

Could you provide patch update `0.8.3` that will reference latest template.js with removed code blocks?

**Comment by NicolasSiver** [comment]
https://github.com/psychobunny/templates.js/pull/51 web workers removed

**Comment by NicolasSiver** [comment]
Forgot, this change also needed - https://github.com/NodeBB/NodeBB/issues/3841

**Comment by barisusakli** [comment]
I made a change in t.js let me know if its resolved with t.js 0.3.1

**Comment by NicolasSiver** [comment]
yes, `0.3.1` - `npm install templates.js@0.3.1` doesn't produce performance problems.

**Comment by NicolasSiver** [comment]
By using `0.3.1` templates.js with `0.8.x` produces glitches in topic view.
Every post tend to be smaller then previous one.
