### ISSUE TITLE
Update compat strings for core plugins 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3864]

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/ccdca39ad8eb9fcff7ad9c793fde85becc941c68 done already?

**Comment by psychobunny** [comment]
Oh? Okay. I only posted this because of 
https://community.nodebb.org/topic/6960/nodebb-0-90-what-exactly-is-compatible

Not backported I guess?

**Comment by julianlam** [comment]
Fix with 0.9.1 in a couple days time. No need to backport
