### ISSUE TITLE
categories purge broken on 0.8.2

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#3866]
Ran into some issues with the importer as it wouldn't delete all of my categories. Tracked it down to some (unfinished?) code in the Categories.purge() function of src/categories/delete.js. A call to `threadTools.purge(tid, 0, next);` will fail because uid `0` is not an admin. 

    tid: 185 uid: 0 isAdminOrMod: false purge: false owner false
    tid: 197 uid: 0 isAdminOrMod: false purge: false owner false
    tid: 202 uid: 0 isAdminOrMod: false purge: false owner false

I change it to `threadTools.purge(tid, 1, next);` and it seems to hang, but not getting the `no-privilege` error. I can reproduce by creating a category, adding a thread and a post, and trying to purge it. 

NBB hash: 6bf9e47c0e439115b71743e2ae18408abdb693a2
tag: 0.8.2

**Comment by barisusakli** [comment]
This was fixed here https://github.com/NodeBB/NodeBB/issues/3626 wasn't backported though.

**Comment by julianlam** [comment]
Backported to v0.8.x branch now.
