### ISSUE TITLE
Web installer: Email field.

### ISSUE THREAD

**Issue by Kowlin** [NodeBB/NodeBB#3869]
A minor bug for the email field on the web installer. The email field contains `<!-- IF admin:email -->{admin:email}<!-- ENDIF admin:email -->`
![](http://i.imgur.com/fIuekFO.png)

**Comment by julianlam** [comment]
Could not reproduce. Ensure you're on latest templates.js version :smile:

**Comment by Kowlin** [comment]
I'm 98% sure I'm running on the latest templates.js. slince I pulled from master into a entirely new folder.

**Comment by julianlam** [comment]
Still have this issue?

**Comment by Kowlin** [comment]
Nah, this is basicly fixed after tinkering with my dedicated server, still thanks ;)
