### ISSUE TITLE
Gif are not loaded

### ISSUE THREAD

**Issue by XenTerSeO** [NodeBB/NodeBB#3871]
Gif files are not uploaded to the server, and there is no possibility to install them on the avatars.

Error uploading:

 error: /api/user/xenterseo/uploadpicture
 Error: Unsupported MIME type: image/gif
    at Jimp.throwError (/var/www/node_modules/jimp/index.js:50:43)
    at Jimp.parseBitmap (/var/www/node_modules/jimp/index.js:237:31)
    at /var/www/node_modules/jimp/index.js:148:29
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by julianlam** [comment]
Yes, this is correct, since we removed imagemagick, we haven't supported gifs... it shouldn't error out though.

**Comment by julianlam** [comment]
oliver-moran/jimp#20

**Comment by XenTerSeO** [comment]
@julianlam, why did you decide to remove support for gif?

**Comment by julianlam** [comment]
The Jimp library does not have support for gifs.

**Comment by iDevPro** [comment]
and ?
That is really reason remove gif ?

**Comment by julianlam** [comment]
Yes.
