### ISSUE TITLE
update redis database package

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3873]
https://github.com/NodeBB/NodeBB/blob/master/src/install.js#L13

The version nodebb installs is 0.10.3 from on 22 May 2014 latest is 2.3.0

**Comment by barisusakli** [comment]
It might be better to move these to package.json so they are tracked at https://david-dm.org/nodebb/nodebb requires changes to install script though.

**Comment by barisusakli** [comment]
Blocked until socket.io-redis gets a new release 0.1.4 doesn't work with latest node_redis

**Comment by julianlam** [comment]
Automattic/socket.io-redis@1cf6ce846a88568af4c307efb6104f1de7495439

Released 6 days ago :smile:

**Comment by julianlam** [comment]
By the way, I am all for moving the access libs into `package.json` so david-dm can track it.
