### ISSUE TITLE
cluster config is not working and nodebb 0.9.0 wont start

### ISSUE THREAD

**Issue by luofan189** [NodeBB/NodeBB#3874]
steps to reproduce:

1. clone nodebb 0.9.0
2. update config.json to have 3 ports
3. run ```nodebb dev```

nodebb won't start, see infinite starting log over and over again. It was fine with 0.8.2, seems broken in 0.9.0

**Comment by barisusakli** [comment]
Post your config.json and log

**Comment by luofan189** [comment]
Just tried again, it worked. I think I was doing something wrong. Will close this issue.
