### ISSUE TITLE
ACP: Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3875]
There is a warning in ACP:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

When you are on plugins' page, if you refresh page via F5, everything is fine, but when you navigate from on option to another, you can experience problem with scripts, especially if you use `script` tag in template.

P.S.
<img width="519" alt="screen shot 2015-11-12 at 8 14 40 pm" src="https://cloud.githubusercontent.com/assets/135263/11136158/11f8e19c-897a-11e5-96fc-328eabf09a9a.png">

**Comment by NicolasSiver** [comment]
How do you recommend to use scripts in plugin section, which have requirement to be loaded via CDN link?

**Comment by julianlam** [comment]
@NicolasSiver Do you mean a script loaded in an ACP's plugin page?

**Comment by NicolasSiver** [comment]
Yes.
Somewhat It's related to https://github.com/NodeBB/NodeBB/issues/3134

Because now, for example, I include all plugin ACP scripts via `<script>` also

**Comment by julianlam** [comment]
Can you use `<script async src"...` instead?

**Comment by NicolasSiver** [comment]
I have tried it before, didn't help.

@julianlam It will be a very good, if you escalate `acp.min.js` feature and provide ability to specify CDN links in plugin.json:

```
"scripts": [
    "public/js/fields-edit.js",
    {"src":"plugin/acp/admin.js", "scope":"acp"},
    {"src":"//cdn.com/something/lib.js", "scope":"acp,external"}
  ],
```

One of many possible solutions for scope handling:

- `acp`, just minify and concat
- `external`, insert as <script> in ACP

Christmas gift from NodeBB team? :gift: :gift: :gift:

**Comment by julianlam** [comment]
:laughing: Oh boy... the feature is simple in order to reduce its learning curve. I think there was talk of an `acpScripts`... hm...

**Comment by psychobunny** [comment]
`filter:admin.scripts.get` for including external scripts into the header
`acpScripts` in `plugin.json` for minifying ACP only scripts

**Comment by NicolasSiver** [comment]
@psychobunny :+1: good, very good.
