### ISSUE TITLE
403 if login via lynx

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#3883]
When I try to login via the lynx text-based web-browser I always get `403 Forbidden`.

See https://community.nodebb.org/topic/7038/question-regarding-accessibility/6

**Comment by barisusakli** [comment]
Likely because the csrf token is added to the login POST request via javascript.

**Comment by frissdiegurke** [comment]
Nvm then, didn't think about login is restricted to javascript... sorry.
