### ISSUE TITLE
ability to edit skin colors

### ISSUE THREAD

**Issue by mttprvst13** [NodeBB/NodeBB#3886]
I think it would be cool, but might take a little bit, if you made it so that admins could make custom skins by just changing the colors, and setting if it is a round or square skin, so like the Cerulean skin VS. the Cosmo theme. I know its asking for a bit much, but I think it would look cool. I want a blue based skin(with the background blue, and the navbar blue), but I noticed that it is just Bootwrap skins, so I think this would be a very cool addition.

**Comment by Holyphoenix** [comment]
You can easily override css from the admin panel.  I'm not against this feature, but would it really be used?

**Comment by mttprvst13** [comment]
That's true, but it would be easier with like a color picker, and recently/commonly used colors.

**Comment by sorvani** [comment]
Admins like me would use this feature. I can edit css. I really, really, do not want to.

**Comment by julianlam** [comment]
A dedicated skinning manager may be completely out of scope (plugin request?)

But what if core had the ability to modify a given bootstrap skin's `variables.less`... that might open it up to small changes.

@psychobunny ?

**Comment by sunsetbrew** [comment]
The problem with the global css changes is that it plays havok with different skins.  I would like to be able to create a new skin, ideally based off an existing one so updates would automatically apply.   For example, the default theme may use Cyborg + a background image.  But if the user selects a different theme, the background image should not apply because it would look terrible.

**Comment by pichalite** [comment]
@sunsetbrew this commit https://github.com/NodeBB/nodebb-theme-persona/commit/9476854b2809c8fa79283b5af3a33b20723d14bb will help you do that.

this adds a class to the body tag named after the skin used so you can apply updates specific to the skin.

**Comment by sunsetbrew** [comment]
Ooo, that is awesome.  So we will see in the next update. :)

**Comment by psychobunny** [comment]
I think the change @pichalite did + ACP custom CSS panel is good enough
