### ISSUE TITLE
Have you planned to update the Dockerfile?

### ISSUE THREAD

**Issue by rspt** [NodeBB/NodeBB#3890]
Thanks!

**Comment by edasque** [comment]
To what?

**Comment by rspt** [comment]
Sorry, maybe it was unclear.

You have a [Dockerfile](https://github.com/NodeBB/NodeBB/blob/master/Dockerfile) and automated builds on [Dockerhub](https://hub.docker.com/r/nodebb/docker/).

The Dockerfile is up-to-date but not really useful if you want to package a real docker-app.
The builds on Dockerhub are not updated since 8 months.

Do you plan to change these?

**Comment by edasque** [comment]
I think that it's possible with the existing Dockerfile but the automated builds on Dockerhub haven't been switched to using it as per https://github.com/NodeBB/NodeBB/pull/3160

**Comment by rspt** [comment]
I understand the motivation for a simple generic Dockerfile at root, as pointed in #3160, but if we have a more complete Dockerfile and a tagging system for the automated build on Dockerhub it could be even better.

Is it better if I join the discussion #3160 and close this one?

**Comment by julianlam** [comment]
Yes please.
