### ISSUE TITLE
Plugin warning shows wrong switch and doesn't correct user on trying to reset wrong type (minor)

### ISSUE THREAD

**Issue by robjens** [NodeBB/NodeBB#3892]
I was thrown off guard for a small bit because the error output which (friendly!) shows the line that a plugin is misbehaving, displays the `-p` switch. But in my case, it was actually a theme. It even got confirmed by the system (wrong). Ideally, the feedback would be contextual (read: detect the `nodebb-theme-` convention) and show `-t` in those cases and provide a helpful string (lookup?) when one tries to use a flag on a plugin 'type' which doesn't exist by that name (although I guess technically, themes are plugins but the have a different naming convention, for one, and are easily detectable). E.g. `can't find plugin by the name of .... Are you sure you don't want a theme?`. That or, it could be corrected automatically, if `-p` lookup fails, do `-t` lookup and if found reset that one (not sure the motivation for splitting them up in terms of command line switches, just suggesting a few options).

Current output:
```
% ./nodebb reset -p nodebb-theme-sevenmaterial                                                    :(
23/11 14:07 [937] - info: [database] Checking database indices.
23/11 14:07 [937] - info: [reset] Plugin `nodebb-theme-sevenmaterial` disabled
```

Hmm now on second glance, I notice the `: (` on the end of my cli. I guess the exit code is returning correctly in the shell, but the Node process isn't terminated.

**Comment by julianlam** [comment]
Yes, it's a blind set removal of plugin `X` from `plugins:active`, though I imagine a check wouldn't really break the bank in terms of performance :smile:
