### ISSUE TITLE
menu gets cut (outside of screen) in the user section

### ISSUE THREAD

**Issue by beingalink** [NodeBB/NodeBB#3894]
[screenshot](https://www.dropbox.com/s/6dwjfrivjt7bs06/Screenshot%202015-11-23%2013.01.12.png?dl=0)
This is in a maximized window on a 13" screen. Tested in chrome, firefox and safari.
NodeBB 0.9

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/204
