### ISSUE TITLE
Exclude content from the last post preview

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3896]
Hi,

Is it possible from the _plugin_ to exclude stuff, so it will not show in last post preview?

<img width="425" alt="screen shot 2015-11-23 at 7 28 21 pm" src="https://cloud.githubusercontent.com/assets/135263/11354308/772da8d0-9218-11e5-8c56-444a533568d1.png">

Is it `filter:parse.raw`? I mean, If I remove content via this filter, everything will be fine, or there is edge cases?

**Comment by psychobunny** [comment]
What if you added a class to it and then selected from the post preview to display none? To make it compatible on all themes might have to make the preview a component as well

**Comment by NicolasSiver** [comment]
So `filter:parse.raw` isn't a solution?

Class will not help, It looks like you sanitize content, there is no `div`:

<img width="297" alt="screen shot 2015-11-23 at 7 41 17 pm" src="https://cloud.githubusercontent.com/assets/135263/11354543/331da314-921a-11e5-8c7c-9c0699fa00ba.png">

**Comment by julianlam** [comment]
Nope, `raw` is used in the composer preview only, as far as I know...

**Comment by barisusakli** [comment]
You can use [`filter:teasers.get`](https://github.com/NodeBB/NodeBB/blob/master/src/topics/teaser.js#L83) and strip tags like [this](https://github.com/NodeBB/NodeBB/blob/master/src/topics/teaser.js#L76-L77)
