### ISSUE TITLE
"in:category-{cid}" flag for search

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3903]
We already have an "in:topic-`tid`" modifier in search to search for text inside of a particular topic (though that is disabled by default).

**Should we have an "in:category-`cid`" to quickly search for topics only within a category?**

### Rationale

Say I'm looking for a specific plugin's debut post in the [Plugins Category](https://community.nodebb.org/category/7/nodebb-plugins). I'd prefer to click the search box and search only within that category, but leave the option open to search forum-wide if I wanted to (just delete the pre-inserted string).

**Comment by vikeen** [comment]
I can see the need, but maybe filtering a forum wide search by category solves this just as easily?

**Comment by vikeen** [comment]
Perha[s just grouping results by category too.

**Comment by julianlam** [comment]
Yeah, we already have the capability to search under a single category, so it would basically be a shortcut to those search options.

**Comment by julianlam** [comment]
No real interest, plus it would be code that is not immediately apparent in functionality.
