### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by michaeltse** [NodeBB/NodeBB#3904]
I am following the guideline at https://docs.nodebb.org/en/latest/installing/cloud/heroku.html
But I have an error after finishing all the steps, please help
https://polar-chamber-3661.herokuapp.com/

<img width="1209" alt="screen shot 2015-11-28 at 1 00 53 am" src="https://cloud.githubusercontent.com/assets/1107532/11445899/7e57e8fe-956b-11e5-82d2-2e6af4fec9d5.png">

**Comment by julianlam** [comment]
Hi there, please post installation questions in [our support forum](https://community.nodebb.org), thanks! :smile:
