### ISSUE TITLE
Upgrade nodebb-plugin-sso-github to use passport-github2

### ISSUE THREAD

**Issue by yyx990803** [NodeBB/NodeBB#3905]
Currently, the `nodebb-plugin-sso-github` plugin relies on `passport-github` strategy, which is out of date and does not handle email addresses correctly with GitHub API v3. Most importantly, users without a public email address on GitHub are never able to validate their account because the email is sent to the wrong address.

This issue has been fixed in the fork of the original strategy: https://github.com/cfsghost/passport-github and is available on npm as `passport-github2`. This is now the recommended github strategy to use (as it is linked on the official Passport website).

It would be great to upgrade the plugin to use the more up-to-date strategy.

**Comment by julianlam** [comment]
v1.0.3
