### ISSUE TITLE
huge profile icon 128x128 thumbnail in post list view in 0.9.1

### ISSUE THREAD

**Issue by luofan189** [NodeBB/NodeBB#3909]
in 0.9.0, the profile icon thumbnail in a post list view is 52X52 (image size is 128x128). This seems be broken in 0.9.1, the thumbnail is now 128x128 (huge thumbnail in post list view). It seems that the css class for the thumbnail changed from ```profile-img``` to ```img-rounded```. User without a real profile image icon shows the right size 52x52 though.

<img width="373" alt="screen shot 2015-11-27 at 7 57 08 pm" src="https://cloud.githubusercontent.com/assets/1351099/11449144/b41ae6dc-9541-11e5-9cf0-eb9bcbfca74b.png">

**Comment by julianlam** [comment]
Hi there, what theme are you using?

**Comment by luofan189** [comment]
@julianlam I tested with lavender 3.0.0

**Comment by julianlam** [comment]
Fixed in v3.0.1 of Lavender theme, package.json dependency backported to v0.9.x
