### ISSUE TITLE
Rewards: enable status of rules not shown in ACP

### ISSUE THREAD

**Issue by wellenreiter01** [NodeBB/NodeBB#3910]
The status of the rewards is not shown in ACP. 
When accessing Extend->Rewards all rules are shown as passive with a green enable button. (attached forum3.png)
If the enable button is pressed the color of the button changed to orange, but the text remains 'enable'.
(attached forum4.png)
After saving and leaving the rewards section and returning to the section again, it again shows the green enable  buttons.
That way it is not possible to see the active status of rewards rules in ACP

![forum4](https://cloud.githubusercontent.com/assets/3430012/11458173/5215ae9c-96bb-11e5-91d9-879cad51dc3a.png)

 
![forum3](https://cloud.githubusercontent.com/assets/3430012/11458171/460c905c-96bb-11e5-9c95-4a2170c61096.png)

**Comment by wellenreiter01** [comment]
May be i should mention, that rewards-essentials is installed

**Comment by julianlam** [comment]
I'd recommend using material design toggles here instead of enable/disable buttons, if at all possible. The UX is better in my humble opinion.

**Comment by julianlam** [comment]
Closed via 452bb953c953e66b912022e24ebc2139860316d3
