### ISSUE TITLE
Notification Grouping

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3912]
Right now individual notifications are sent for each event, and the system does not have a facility to group them.

For example, if you follow a topic and 6 users reply to it, you will get six notifications. If you follow multiple active topics, this pretty much renders the notifications dropdown useless.

----

For this round, we'll focus on the following notifications:

* [x] Upvoting/Favouriting a topic
* [x] Gaining followers
* [x] User has replied to a topic you follow
* [x] Flagging

**Comment by Kowlin** [comment]
Doesn't the notifications for flagging also be included for this?

**Comment by julianlam** [comment]
Updated, thanks.

**Comment by martyalicante** [comment]
What about mentions

**Comment by julianlam** [comment]
One thing at a time guys :)

On Wed, Dec 2, 2015, 8:34 PM marty <notifications@github.com> wrote:

> What about mentions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NodeBB/NodeBB/issues/3912#issuecomment-161487826>.
>
-- 
*Julian Lam*
*Co-Founder, NodeBB Inc.*
36 King Street East, Toronto, ON
M5C 3B2, Canada

**Comment by Kowlin** [comment]
Haha, but wasn't Mentions a core plugin instead of being in the actual core?
