### ISSUE TITLE
Move 'chat page behaviour on mobile' from core to theme

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#3915]
creating an issue for this so that it doesn't get lost

https://github.com/NodeBB/NodeBB/commit/7fae82a9bd18fafa08b246e1f1c86a4accca01ed

**Comment by julianlam** [comment]
Thanks @pichalite :smile:

**Comment by julianlam** [comment]
Let me know if that is sufficient

**Comment by pichalite** [comment]
perfect :+1:
