### ISSUE TITLE
Parent category privileges 

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3917]
Users still can reach categories, even when parent category privileges are removed and parent category is disabled

**Comment by julianlam** [comment]
This is intentional, in order to both simplify and allow for more complicated privilege setup. 

Am open to adding a warning in the interface, if necessary.

**Comment by NicolasSiver** [comment]
I think It's a big Privacy problem.

**Comment by NicolasSiver** [comment]
Also, as an administrator, you have to go to every category, and remove privileges. It's hard to say good user experience ;)

**Comment by julianlam** [comment]
Not of properly configured. The only issue I see is the possibility of a forum being exposed due to not being aware of this behaviour... in which case a warning will suffice.

**Comment by julianlam** [comment]
Could add a reset button to restore default category privileges...

**Comment by Kowlin** [comment]
The reset button seems like a good idea.

**Comment by NicolasSiver** [comment]
Not just being aware.
Taking into consideration another forum engines and work with trees, It's hard to predict, that if you have disabled parent category, children are still accessible.

**Comment by julianlam** [comment]
One particular example involves categories created and accessible to certain group members, but the parent category itself contains no privileges whatsoever. 

This can only be achieved with our system.

**Comment by NicolasSiver** [comment]
As for me It's a reinvention of wheel ;)
You are reinventing how parent-child relationship works.
There is no common sense in access to children if parent is _disabled_.

1. NodeBB has enable/disable feature. It should work as enable/disable, explicitly. Otherwise name it in another way.
2. NodeBB has privileges. They should propagate, it means you should evaluate access through tree. It isn't a good area for intentional simplification.

**Comment by lots0logs** [comment]
> Also, as an administrator, you have to go to every category, and remove privileges. It's hard to say good user experience ;)
> You are reinventing how parent-child relationship works.
> There is no common sense in access to children if parent is disabled.

Well said @NicolasSiver ! :smiley:

**Comment by barisusakli** [comment]
When you are on /manage/categories if you disable a parent it disables it's children as well no? Then they shouldn't be accesible. Privileges don't descend into children though.

**Comment by julianlam** [comment]
I think what @NicolasSiver is saying is that while enable/disable propagates down through the children, privileges do not, and that it is this disconnect that is leading to a user-unfriendly interface.

Given his opinion and @lots0logs' affirmation, I'm willing to look into solutions...

I was thinking of the following:

1. A "reset to default" button that changes the privileges back to the default upon category creation... that is: Registered users can find/access/create/reply, and guests can find/access
1. An "inherit from parent" button that changes a child category's (if a parent is available) privileges to match it's parent.

**Comment by pichalite** [comment]
@julianlam You are going to change privilege checks to verify parent category permissions first and then category permissions right?

Probably good time to implement this? #2779

**Comment by robjens** [comment]
From what I see, this is 'fixed' already? Since when I disable a category, any subcategories are instantly disabled too. Not a direct link, or any other form makes it possible for me to reach the child category, which is what TS described.

Talking about user friendliness btw, I'll throw in a minor if you don't mind: the categories edit/add page doesn't have a way to go back.

I'm not sure how many people want to stay on the categories page, after saving but I've found very little cause for doing such a thing. Imho, it would be friendlier to return to the categories page, instead of having me click **2 times extra** (1 save, 2 click Manage and 3 click Categories).
