### ISSUE TITLE
Restrict file types for regular file uploads

### ISSUE THREAD

**Issue by dmyates** [NodeBB/NodeBB#3918]
When the option "Allow users to upload regular files" is turned on, it seems to be possible for users to upload files of any type. It would be nice if there was a way of restricting this feature so that, for example, users can upload images to go with their posts but not other files. Maybe some way of manually setting allowed extensions or mimetypes, or even of setting it so that the same processing is done on uploaded files as appears to be done on user avatars?

EDIT: I see this was possible in version 0.8.1. The filetypes field isn't there in 0.9.1 any more though.

**Comment by jacques-** [comment]
Seems like this is a security issue as you could upload html with script content as a XSS vector.

**Comment by jacques-** [comment]
Seems like this might be a potential security issue.

What happens if you upload html with <script>?

**Comment by julianlam** [comment]
Intentionally removed, but now re-added as it still is useful.
