### ISSUE TITLE
Pagination setting is occasionally disregarded

### ISSUE THREAD

**Issue by jhalt** [NodeBB/NodeBB#3920]
I have noticed a few cases where my pagination setting was ignored and pages loaded with infinite-scrolling instead of pagination.

I have reproduced the issue twice, but I don't have exact steps to reproduce -- it seems to happen at random. Similarly, this has happened for a friend of mine as well.

**Comment by psychobunny** [comment]
When this happens again, can you double check if you're logged in or not?

**Comment by jhalt** [comment]
I will attempt to reproduce and report back.
