### ISSUE TITLE
Standard user permission error on viewing post votes

### ISSUE THREAD

**Issue by sorvani** [NodeBB/NodeBB#3922]
If you are a standard user, and you accidentally click on the post rating when attempting to up/down vote a post, you receive a permission error. This causes some confusing that something is not working.

![img](https://i.imgur.com/DoQEsCu.jpg)

If you are an admin, you get this instead.

![img](https://i.imgur.com/wF9UiYE.jpg)

The error should really not even get shown to a normal user as it only causes confusion.

http://mangolassi.it/topic/7086/permission-error-when-clicking-on-the-upvote-post-count

**Comment by julianlam** [comment]
I agree that a positive action is better than a negative one, but users should be able to view upvotes by default, so that seems to be a bug...

**Comment by julianlam** [comment]
Actually, I was totally under the impression that users could always open the modal. Turns out this is not the case, so I will adjust the behaviour to do nothing if the label is clicked.
