### ISSUE TITLE
Question: Best sequence of events for Docker-based launch

### ISSUE THREAD

**Issue by edasque** [NodeBB/NodeBB#3924]
Hi,

I have been working on a set of smart Docker images (nodebb + redis) for deploying a nodebb application at scale.

the last line of the nodebb Dockerfile launches the app but it has to work in different situations:
* In most cases there is no config.json (so I think ```./nodebb setup``` has to be part of it)
* In some cases an existing redis database is paired with a new nodebb version so I think ```./nodebb upgrade``` has to be run
* The app has to be launched and never quit through restarts & reloads (so I think it has to be ```./nodebb start``` and not ```node app.js```)
* ideally the console would show a log of the application

Right now I use:
```./nodebb setup ; ./nodebb upgrade ; ./nodebb start;```

But it's occasionally behaving badly. I would love some feedback on how to best address the different cases.

**Comment by edasque** [comment]
@julianlam can you chime in?

**Comment by julianlam** [comment]
Not sure about all scenarios, but your best bet would be:

`node loader.js`

If Docker handles the logging via stdout, then run it as `node loader.js --no-silent --no-daemon`
