### ISSUE TITLE
Weird behavior of use_port

### ISSUE THREAD

**Issue by ishitatsuyuki** [NodeBB/NodeBB#3925]
The use_port seems to be deprecated now, but it is needed for some conditions.

My condition:
1. Web server running on a abnormal port.
2. NodeBB is proxied through nginx.
-> "Trust proxy" can't be enabled without modifying source

I must specify the port in url or it will cause problem(mismatch) in OAuth URL. But by specifying it, trusted proxy will be disabled and IP logging will not work.
I don't think there is a better way to configure.

Also, I'm not sure why [this](https://github.com/NodeBB/NodeBB/blob/f702717e6162df3d6cdd937700953c643421c0e8/app.js#L125) work, but I think that is faulty too.

**Comment by julianlam** [comment]
Hi there @ishitatsuyuki, thanks for reporting this issue.

You are correct in noting that "Trust proxy" is only enabled if port is disabled. This was an assumption that we made because typical nginx installations are listening on port 80.

Perhaps we can add a dedicated config option for this...

**Comment by julianlam** [comment]
@ishitatsuyuki If you specify a non-standard port in `config.json`, it will enable `trust proxy` by default. No need to specify `port` in `config.json` if you're listening on `4567`.

In any case, I'll add a new option into`config.json`.
