### ISSUE TITLE
Add emailInterval to settings tab

### ISSUE THREAD

**Issue by danger89** [NodeBB/NodeBB#3926]
Currently the emailInterval is hard defined in the code ([src/user/email.js](https://github.com/NodeBB/NodeBB/blob/master/src/user/email.js#L35)) Line 35.
```var emailInterval = 10```

I think it's a good idea to define this value somewhere else and make it easier to change via the backend.

Kind regards,
Melroy van den Berg

**Comment by julianlam** [comment]
Hello Melroy.

Certainly, let's take a look.
