### ISSUE TITLE
Hamburger slide out display issue

### ISSUE THREAD

**Issue by sjennison** [NodeBB/NodeBB#3928]
When the vertical content of the page is short, the slide-over animation only covers the vertical content, making it look quite bad.

![](https://goo.gl/photos/M4x3n6pKAXKgJduk9)
EDIT: image tag doesn't work...
https://goo.gl/photos/M4x3n6pKAXKgJduk9

It works fine if the content is larger than the viewport though...

![](https://goo.gl/photos/4JNF9m8qsDdv8XNT7)

https://goo.gl/photos/4JNF9m8qsDdv8XNT7

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/183
