### ISSUE TITLE
x-frame-options "ALLOW FROM" is ignored by Chrome/Chromium

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#3937]
Chrome requires the `Access-Control-Allow-Origin` header to be set with the value of the origin you want to allow. I was previously setting this with Nginx but recently the custom headers I have set by Nginx are not making it to the client. It appears NodeBB is dropping them and only including these two:
```
x-frame-options: https://antergos.com
x-powered-by: NodeBB
```

**Comment by akhoury** [comment]
and Safari, [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options#Browser_compatibility)

`ALLOW FROM` is not a good solution yet.


related: https://github.com/NodeBB/NodeBB/pull/3899
related: https://github.com/NodeBB/NodeBB/issues/2151
