### ISSUE TITLE
notifications.json in nodebb-plugin-mentions overrides core

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3939]
Causes the translations in `public/languages/en_GB/notifications.json` to disappear

https://github.com/julianlam/nodebb-plugin-mentions/commit/4b3f69c7308e581974b1e5670c2c1424dc1149a2

**Comment by julianlam** [comment]
Didn't know they overwrote the file. Makes sense, will rename.

**Comment by julianlam** [comment]
v1.0.12 of mentions
