### ISSUE TITLE
Apple Touch Icon path incorrect

### ISSUE THREAD

**Issue by alexschomb** [NodeBB/NodeBB#3940]
There is an error in `/src/middleware/middleware.js` which results in loading the logo file instead of the uploaded Touch Icon for the `example.com/apple-touch-icon` path.

To make it work you'd have to replace `brand:logo` with `brand:touchIcon`:
```
middleware.routeTouchIcon = function(req, res) {
	if (meta.config['brand:touchIcon'] && validator.isURL(meta.config['brand:touchIcon'])) {
		return res.redirect(meta.config['brand:touchIcon']);
	} else {
		return res.sendFile(path.join(__dirname, '../../public', meta.config['brand:touchIcon'] || '/logo.png'), {
			maxAge: app.enabled('cache') ? 5184000000 : 0
		});
	}
};
```

Still. I don't think this works as described in the backend admin interface which states:
"If no touch icon is specified, NodeBB will fall back to using the favicon."

Shouldn't the route reflect this in any way? `brand:favicon`? Is this even possible? AFAIK the uploaded favicon is in the `ico` format.

**Comment by julianlam** [comment]
To my knowledge the apple touch icon fell back to using the favicon if no touch icon was defined. A holdover from when nobody had touch icons at all. 

Backwards compatibility shouldn't be an issue and iPhones should load .ico files just fine.

**Comment by alexschomb** [comment]
I just deleted the uploaded touch icon on my v0.9.1 installation and it serves `/logo.png` instead of the current uploaded `favicon.ico`. `middleware.js` reflects this fact:

```
...
else {
        return res.sendFile(path.join(... meta.config['brand:touchIcon'] || '/logo.png') ...
```

**Comment by julianlam** [comment]
The other rationale is that favicons are usually square. Logos are not (or rather, there is no restrictions specifying that they ought to be)

**Comment by julianlam** [comment]
Looks like a bug :smile:

**Comment by alexschomb** [comment]
That's another construction site. There shouldn't be non-square touch icons either.
