### ISSUE TITLE
how

### ISSUE THREAD

**Issue by Xuchenhao** [NodeBB/NodeBB#3945]
I have two nodebb forum.and i wanner to merger it in one. How to do that?

**Comment by akhoury** [comment]
there is no easy to do that, you could possibly write a plugin for the [importer plugin](https://github.com/akhoury/nodebb-plugin-import),, something like `nodebb-plugin-import-nodebb` but I would still need to add a feature to "merge" users, either by email or by username, use the merge when importing all other records, which is NOT an easy feature to add to be honest.

**Comment by psychobunny** [comment]
I'm closing because this isnt an "issue" (bug or feature request). I'd repost in our community forum and maybe somebody can help; if you'd like us to try and figure a solution for you email us at sales@nodebb.org and we can give it a shot
