### ISSUE TITLE
Strange values in Forum Trafic

### ISSUE THREAD

**Issue by AsBilou** [NodeBB/NodeBB#3949]
Hi,

Since you enable the possibility to view the forum trafic by mounth, i noticed strange values in my dashboard.

There on a clean install (0.9.1 updated to 0.9.2 on branch master):
![freshinstall](https://cloud.githubusercontent.com/assets/1552356/11776955/5a449204-a24b-11e5-90f2-2dba450353f5.png)

And there on my active forum (0.9.0 updated to 0.9.1 and 0.9.2 on branch master) :
![activeforum](https://cloud.githubusercontent.com/assets/1552356/11776958/5fa88f52-a24b-11e5-9600-9b7966fc41cc.png)

**Comment by psychobunny** [comment]
That's a hell of a lot of pageviews you got there. :p

**Comment by julianlam** [comment]
Can anybody else confirm? Quite weird behaviour...

**Comment by AsBilou** [comment]
I don't know what happened whit my nodebb forum but an other clean instal made the day when i opened this issue have the same issue. 

![traffic_0 9 2](https://cloud.githubusercontent.com/assets/1552356/11959494/e5615be6-a8cd-11e5-91d3-6b450dcbf7ae.png)

It's a clean install, based on 0.9.2 master branch on December 16 2015. I browse 3 time the main page and never come back until today.

**Comment by robjens** [comment]
![image](https://cloud.githubusercontent.com/assets/11848802/11963824/64bed8ba-a8e1-11e5-8652-babe51450fa1.png)

Brand new install... nothing particular to notice here. This was a clone off the master/checkout branch

**Comment by AsBilou** [comment]
Wait few days And come back to your dashboard. 
I've got the data at the begining.

**Comment by AsBilou** [comment]
Came back to my dashboard this morning and see others stange value :/

![traffic_23_12_15](https://cloud.githubusercontent.com/assets/1552356/11973052/23c3d3aa-a955-11e5-8c03-7953ec45bd70.png)

Here is my full log : 

>NodeBB v0.9.2 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

>Clustering enabled: Spinning up 1 process(es).

>15/12 14:20 [5188] - [32minfo[39m: Time: Tue Dec 15 2015 14:20:22 GMT+0100 (CET)
15/12 14:20 [5188] - [32minfo[39m: Initializing NodeBB v0.9.2
15/12 14:20 [5188] - [32minfo[39m: NodeBB Ready
15/12 14:20 [5188] - [32minfo[39m: Enabling 'trust proxy'
15/12 14:20 [5188] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:4569
15/12 15:04 [5188] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
15/12 15:04 [5188] - [32minfo[39m: [app] Database connection closed.
15/12 15:04 [5188] - [32minfo[39m: [app] Web server closed to connections.
15/12 15:04 [5188] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (5188) has exited (code: 0, signal: null)

>NodeBB v0.9.2 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

>Clustering enabled: Spinning up 1 process(es).

>22/12 17:00 [7509] - [32minfo[39m: Time: Tue Dec 22 2015 17:00:20 GMT+0100 (CET)
22/12 17:00 [7509] - [32minfo[39m: Initializing NodeBB v0.9.2
22/12 17:00 [7509] - [32minfo[39m: NodeBB Ready
22/12 17:00 [7509] - [32minfo[39m: Enabling 'trust proxy'
22/12 17:00 [7509] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:4569

**Comment by pichalite** [comment]
don't have this issue on pichalite.com but happened on a test setup on cloud 9.

The difference between the two is... pichalite.com uses mongo and the test is setup using redis.

<img width="847" alt="screen shot 2016-01-02 at 4 40 01 pm" src="https://cloud.githubusercontent.com/assets/10014774/12076782/ebd61520-b16f-11e5-97be-672d77d0c575.png">

**Comment by lots0logs** [comment]
I also have this issue. I'm using Redis (which appears to be relevant)
