### ISSUE TITLE
nodebb 0.9.2 - moving  post or posts at a time 

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#3951]
### moving one post at a time have an issue:

suppose you have topics without any reply to it, actually this topic has only one post,
**you can't move this post to another existing topics**

In fact, **I talk about upgrading the database design of nodebb forum**, for the next version!

    The strength of the current design is that, now you can easily move topics,
     because in practice there are no dependencies between topics and categories.
     (Each category is just a container for topics, nothing more)

    I think this policy should be applied to posts and topics,
     in which case you can apply any changes on posts and topics easily.

I'm taking about better **database design** and better **user experience**:

    A practical example:
    Suppose you have 10 topics in each one chapter of "x" is taught,
     I think it is better that they come together to teach full "x" to have a complete topic.

>A better community platform for the modern web.
NodeBB is a next generation forum software that's free and easy to use.A better community platform for the modern web.
NodeBB is a next generation forum software that's free and easy to use

### there isn't any future to merge multiple topics together!

**Comment by akhoury** [comment]
original topic: https://community.nodebb.org/topic/7235/nodebb-0-9-2-moving-a-post

**Comment by akhoury** [comment]
what is the ask here?

**Comment by julianlam** [comment]
Topic merging, I think...

Please see #3106

**Comment by julianlam** [comment]
Though pursuant to the conclusion reached in #3106, I think perhaps we could consider topic merging in core.

**Comment by sohrabafard** [comment]
@akhoury @julianlam Thanks for your helpful response, yes I'm taking about topic merging and moving multiple posts at a time to existing topics.

**remark.** topics that user marks for merge, have different insertion times so user maybe choose newest topic as destination for merged topics. in the other words we should handle  **time line of posts in merged topic**.
