### ISSUE TITLE
Admins can leave the administrator group on group/details page

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#3952]

**Comment by julianlam** [comment]
Hm, system groups should not have join/leave buttons on `groups/details.tpl`. Thanks.

**Comment by julianlam** [comment]
Cannot reproduce due to [this code](https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/helpers.js#L134-L136)

Can you confirm that the button shows up for you?

**Comment by barisusakli** [comment]
There is a grant/rescing kick button for group owners. So if you are the owner of the admin group you were able to kick yourself.
