### ISSUE TITLE
feature request: showing admin session on ACP that we can terminate it!

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#3959]
related to:
https://github.com/NodeBB/NodeBB/issues/3958
https://github.com/NodeBB/NodeBB/issues/2329

**Comment by julianlam** [comment]
Once #2329 is complete, this issue is resolved as well, so it is a duplicate. Thanks, though!

**Comment by julianlam** [comment]
Please post your support in #2329 :smile:

**Comment by sohrabafard** [comment]
:+1:

**Comment by sohrabafard** [comment]
:+1:
