### ISSUE TITLE
Notification Grouping only groups similar notifs once

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#3965]
![selection_044](https://cloud.githubusercontent.com/assets/923011/11909454/db350dbe-a5b4-11e5-9624-13930b5f4a67.png)

Here, you can see that @pichalite and 9 others replied, but the 9 actually refers to the count of *all* "topic replied to" notifications, and the other topics that have been replied to aren't grouped at all (see: "Show us your rig" notifications)

So only the first unique set is grouped.

**Comment by sohrabafard** [comment]
Also group all notification about flagged posts!

**Comment by julianlam** [comment]
Backported to v0.9.x
