### ISSUE TITLE
XMLHttpRequest vs ajax

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#3974]
Why do not you use `XMLHttpRequest`, instead of  `$.ajax` ?

**Comment by julianlam** [comment]
Hi @sohrabafard -- `$.ajax` is provided by jQuery as an abstraction to make `XMLHttpRequest`s. There's no need to make the low level call on our own as it is time consuming.

Please see: https://en.wikipedia.org/wiki/Abstraction_principle_(computer_programming)

Unless I am mistaken, the potential gain from writing up an XMLHttpRequest vs. simply using `$.ajax` is miniscule, if there is one at all.
