### ISSUE TITLE
Spamming View Count

### ISSUE THREAD

**Issue by jbob182** [NodeBB/NodeBB#3984]
Commit: 8c84ce991495aef0dfe83171a0b6d3f0a52cafb2
Tested on: Chrome

If you hold `f5` (refresh) for a few seconds while on a topic, the view count will increase by by 30 or so. Obviously the longer you hold it, the more view the topic will gain. We tested this on one of our topics and reached 5.5k views in under a few minutes.

If the forums is using Apache to proxy the websockets, this can slow down the entire site with only a single user spamming. nginx appears to handle it properly though.

**Comment by julianlam** [comment]
Discussed and rejected as view count is a vanity metric and limiting counts based on session id increases complexity for minimal gain.

Also, #3975

**Comment by akhoury** [comment]
@julianlam do you think nodebb should I least throttle the same uid within a minute (or some magic number of seconds) or so?

**Comment by psychobunny** [comment]
I think it's better off being done on nginx, we limited amount of requests per second for DoS protection, that would cover this as well
