### ISSUE TITLE
NodeBB's requests exceed default Apache2 MaxKeepAliveRequests

### ISSUE THREAD

**Issue by Robotia** [NodeBB/NodeBB#3985]
I had been receiving 503 service unavailable on many WebSocket requests while using ProxyPass with Apache2.

By default, Apache2 allows 100 maximum keepalive requests. I found that raising this to 1000 eliminated all 503s.

Can this be added to the guide for ProxyPass on Apache2?

**Comment by psychobunny** [comment]
Feel free to add a note to our documentation at https://docs.nodebb.org/en/latest/configuring/proxies/apache.html

There's a link on the top right to simply edit in GitHub's editor, should be straightforward. Thanks!
