### ISSUE TITLE
Navigation header icons cannot be changed after selecting "No icon"

### ISSUE THREAD

**Issue by frankdiox** [NodeBB/NodeBB#3986]
NodeBB 0.9.2

In admin page General > Navigation, when changing a header icon, if you select `NO ICON` the icon preview obviously disappears. The problem is that the clickable div to open the selection dialog is the icon itself, so at this point there is no way to open again the selection dialog.

**Comment by julianlam** [comment]
Well, that's an embarrassing bug :smile:

Can you select it in the meantime by using the tab key?

**Comment by frankdiox** [comment]
No, I think the only way is deleting that section and creating it again so it will show the default icon where you can click. It's not an important bug but I thought it would be better to report it :sweat_smile:
