### ISSUE TITLE
tiny url

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#3990]
for sharing a particular  post of a topic, its good idea that we have ability to get a short url to that post!

**Comment by akhoury** [comment]
Sounds like a plugin. Because you're gonna to generate that tiny URL against a specific service and each has it own API

**Comment by julianlam** [comment]
Correct, the url provided is the *canonical* link, and if you'd like to make a plugin to alter this URL, let us know and we can add in the plugin hook.
