### ISSUE TITLE
group banners (full scale)

### ISSUE THREAD

**Issue by robjens** [NodeBB/NodeBB#3991]
How much I really love the group hero banners NodeBB is using, and special thanks to you guys for being lightning fast implementing the last obstacle in my way (drag/drop not working in Linux properly, so you added a upload button), there is something I noticed just now.

When looking at the group page, the banners all load in full/hi-res. Although this is something which will hopefully become less of a bandwidth pain due to caching, I do not think it is very smart to load these group thumbnails full scale, hi-res. It will really kill slower connections should people have used large enough banners. Oh, and not forget handhelds. The themes are almost all nice and friendly towards mobile devices, downloads/requests should be too.

Is there any (Imagemagickless) conversion we could apply? E.g. use https://github.com/EyalAr/lwip to resize those images after upload and serve up a limited size til or thumb instead of the full size image?

Thoughts?

**Comment by Kowlin** [comment]
A thing that is to be considered is the forum's max upload size (what applies for those kinds of images) The default images are not big at all, as example one of those is only 33,4KB. What I personally like to see is a size limit for those banners that doesn't affect other uploaded files.

**Comment by julianlam** [comment]
Image can be resized... would be nice to see if srcset can be used on background images.
