### ISSUE TITLE
User with no existing password cannot change password

### ISSUE THREAD

**Issue by Pappmann** [NodeBB/NodeBB#3993]
User with no existing password cannot change password.

Showing password too short or incorect.

**Comment by Froxz** [comment]
Have same trouble after login with SSO, user password change page is shown but cant change it. 

Maybe it is better to add like "middleware" if password doesnt exist deny GET/POST on password change.

Also same with email if user logged in with SSO (So no Password disable change email)

Or add a button disable change email in ACP (like username change disable)

**Comment by Pappmann** [comment]
Thx
