### ISSUE TITLE
Local login disabled

### ISSUE THREAD

**Issue by Froxz** [NodeBB/NodeBB#3995]
When Local Login is disabled in ACP still is shown if you path parameter to URL like
```js
http://domain.com/login?local=1
```
I think is pointless if Local login is disabled

**Comment by barisusakli** [comment]
It is for admins to login when they go to /admin

**Comment by Froxz** [comment]
@barisusakli Yeah I understand it but is still available to all users )))) 
so is not disabled, and it can be brute force. As now happens to me already 4 days))) And there is no way to put captcha or something I tried to restrict connections fron Nginx, but still they brute me(((

**Comment by barisusakli** [comment]
It is availabe because we don't know if a user is admin before they login. If local login is disabled regular users can still try to login but they won't be able to because of [this](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/authentication.js#L252-L254).
