### ISSUE TITLE
Invalid csrf token error on email confirm

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#4000]
invalid csrf token

some users send email to us that they can confirm their email address!
all of them use chromium as web browser,we recommend them to use Firefox!

**we have this error just on chromium web browser**

forum config:

varnish port 80 - deliver websocket and socket.io request to nodebb on port 4537 and other request to nginx on port 8080

nginx port 8080 - serve static files and proxy other request to nodebb on port 4537

we run nodebb using `./nodebb start` command!

**Comment by julianlam** [comment]
Needs confirmation as I cannot reproduce. Email confirmation is also a GET, not a POST, so CSRF wouldn't normally be applied anyway.
