### ISSUE TITLE
Problem using Custom CSS in NodeBB 0.9.3

### ISSUE THREAD

**Issue by frankdiox** [NodeBB/NodeBB#4001]
NodeBB v0.9.3

I'm using a logo in my NodeBB forum and I'm trying to resize it after the hamburger-menu button appears.

I am using [calc](http://caniuse.com/#search=calc) in this way:

```
@media (max-width: 768px) {
  ...
  .header .forum-logo {
    max-width: 75%; // <-- This is a fallback
    max-width: calc(100% - 100px);
    ...
  }
}
```

It works perfectly if I write it directly using developer console, so the browser supports it. However, if I write it in NodeBB's Custom CSS section looks like it is somehow preprocessed and the final value looks like `max-width: 75%; max-width: calc(0);`, what is an invalid value for `calc`.

Any ideas?
Thanks.

**Comment by barisusakli** [comment]
custom css input is actually accepts less so it gets rendered and minified, maybe that's why it's not working.

Does this work

```
@media (max-width: 768px) {
  ...
  .header .forum-logo {
    max-width: 75%; // <-- This is a fallback
    max-width: calc(~"100% - 100px");
    ...
  }
}
```

**Comment by frankdiox** [comment]
@barisusakli Oh! I didn't know it supports LESS. That works perfectly, the final value is `max-width: calc(100% - 100px);` as expected. The editor complains about `Expected RBRACE` so I just escaped the tilde character: `max-width: calc(\\~"100% - 100px");` and works well. Thank you very much!
