### ISSUE TITLE
Reload and intervals

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#4002]
There is a problem with `Reload` in ACP.
If Reload is triggered, context of previously loaded plugins isn't destroyed.

How to reproduce: 
1. In hook `static:app.load` start interval.
2. Reload forum.
3. Now you can see 2 intervals.

**Comment by barisusakli** [comment]
I kind of fixed this using the `filter:plugins.clearRequireCache` hook in my rss plugin. Check out https://github.com/barisusakli/nodebb-plugin-rss/blob/master/index.js#L39.

A better hook might be `static:app.reload` which gets fired before the reload process so plugins can stop intervals etc.

**Comment by julianlam** [comment]
Yeah, as @barisusakli pointed out, we re-require any module files on reload, so any context is lost and not cleaned up. Advised to listen to the hook fired in clearRequireCache to clean up...

Though perhaps we could introduce another hook named better....

**Comment by yariplus** [comment]
I've been doing it this way, is this bad?
```
pubsub.on('meta:reload', function () {
	if (scheduler) clearTimeout(scheduler);
});
```

**Comment by barisusakli** [comment]
That should work, but since it's not a filter, there is a slight chance that the plugin is reinitizalized first and meta:reload triggered after.

**Comment by yariplus** [comment]
Ah, good to know, that wouldn't matter for the way I'm using it, but for others I imagine that is definitely not intended.

+1 for `static:app.reload`

**Comment by NicolasSiver** [comment]
I have used this filter: `filter:plugins.clearRequireCache`
