### ISSUE TITLE
cant upload group cover if `Allow users to upload regular files` is disabled

### ISSUE THREAD

**Issue by Froxz** [NodeBB/NodeBB#4006]
If in Settings -> Posts -> Upload settings
```js 
Allow users to upload regular files
```
Is disabled, it is not possible to change Group cover picture, even if the user is superuser (built in admin) 

Maybe is better (to split) to create a new setting for Groups Pictures in Settings -> Groups?

**Comment by barisusakli** [comment]
Upload code needs some refactoring, that setting was meant to effect uploads through the composer but right now its used for all uploads like the group cover. Also installing a plugin like `nodebb-plugin-imgur` by passes that setting.
