### ISSUE TITLE
private group - security

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#4008]
we have a private group, somebody join his account to this group without owner Approve!!!

**Comment by NukeRusich** [comment]
Please provide more information.

**Comment by julianlam** [comment]
As @nukerusich says, we'll need more information. Which group was it, do you have private groups enabled?

**Comment by sohrabafard** [comment]
Yes, a private group had enabled!

group list:

![group list](https://cloud.githubusercontent.com/assets/9453178/12009758/f960cf2e-ac9b-11e5-878b-926a9ab18110.JPG)

private group was enable:

![private group](https://cloud.githubusercontent.com/assets/9453178/12009762/1403a1bc-ac9c-11e5-8d16-555db3f66130.JPG)



This group:
http://forum.sanatisharif.ir/groups/%D8%AD%D8%A7%D9%85%DB%8C%D8%A7%D9%86-%D8%A2%D9%84%D8%A7%D8%A1

**Comment by barisusakli** [comment]
It was a logic error in the group.join method, allowing non-admins to join private groups. Fixed on master and 0.9.x https://github.com/NodeBB/NodeBB/commit/9043a40c358c19658b8468387a253bc01e599905
