### ISSUE TITLE
"Allow users to upload topic thumbnails" doesn't work

### ISSUE THREAD

**Issue by machado2** [NodeBB/NodeBB#4019]
I enabled this setting, and tried all the themes I could find, and couldn't make topic thumbnails work.

**Comment by machado2** [comment]
It worked when I allowed users to upload regular files. I think it could be

**Comment by machado2** [comment]
Wait, it changed it to quickly, when I tried uploading a jpeg it said:

ERROR
w and h must be numbers

**Comment by barisusakli** [comment]
The theme needs to be modified to display the topic thumbnail, right now persona only displays the user images.

**Comment by machado2** [comment]
Your answer addressed it's behavior when I uploaded with an URL, but uploading the image from my local drive there was this message:

ERROR
w and h must be numbers

Is it related to persona too?

**Comment by pichalite** [comment]
@barisusakli are you sure Persona doesn't support topic thumbnails? Works for me on persona.

**Comment by barisusakli** [comment]
Yeah looks like it is supported in persona.
