### ISSUE TITLE
No scroll in the composer window on Android

### ISSUE THREAD

**Issue by machado2** [NodeBB/NodeBB#4020]
When writing or editing a post larger than the space available to the composer window, in an Android phone, it's very hard to scroll up or down. I tested it on a Galaxy S3 running Kitkat.

**Comment by ReyKoxha** [comment]
I can confirm the same. Using a Huawei Honor 7, Meizu MX3 and Pro 5.

**Comment by martyalicante** [comment]
Happens on ios too
Iphone 5s
Ipad air

**Comment by julianlam** [comment]
http://webm.host/04dbe/

Seems okay on my end... Xiaomi Mi4i, Cyanogenmod 12.1

**Comment by machado2** [comment]
I did some more tests and found that it works sometimes, then it fail again.

**Comment by julianlam** [comment]
Yes I've noticed it fails occasionally, but I have yet to determine a reproducible set of steps.

**Comment by martyalicante** [comment]
Try quote long texts and will usually fails

**Comment by julianlam** [comment]
@psychobunny I can trigger this with a long paste, see here: https://dl.dropboxusercontent.com/u/54884397/composer.webm

**Comment by julianlam** [comment]
On paste, looks like it needs to recalculate the textarea height... maybe? :smile:

**Comment by psychobunny** [comment]
Yeah that's probably the case, it resizes on keystroke only atm
