### ISSUE TITLE
Unread cutoff too low?

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#4022]
This looks like a bug to me: https://github.com/NodeBB/NodeBB/blob/master/src/topics/unread.js#L15

Anything that's older than two days without any interaction drops off the /unread list. Was that supposed to have more zeros?

**Comment by barisusakli** [comment]
This is intentional, on a busy forum the amount of /unread topics can easily skyrocket. I added a ACP setting to increase the 2 day limit though.

**Comment by bdharrington7** [comment]
Awesome, thanks Baris!

-Brian
