### ISSUE TITLE
Ability to bulk actions on users

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4027]
A way to filter users and make actions with them like

Delete all users
Delete all pending confirmation users
Confirm all users

Or advanced example like..
Find all banned users and unban them 
filter users with 0 posts and not logged in 1 year and be able to delete them

Etc

In general could be an enhancement on user actions without the need of select them 1by1

**Comment by julianlam** [comment]
I'd go for adding more filter to users :y:

Some people might even find use for things like... filtering users to show those registered w/in the past 7 days, and then extracting their emails to send them a welcome message, etc...

**Comment by ianchildress** [comment]
I recently migrated from mybb to nodebb. In 8 days I have 12 pages of users that are all spam accounts with 0 posts. I'm currently using the "No posts" filter and selecting the first 5 rows (all that fits on my screen) by click and dragging the box around the users. Then I go up to the "Delete User" option. It's time consuming.
