### ISSUE TITLE
Check if email format is valid on register page

### ISSUE THREAD

**Issue by ishitatsuyuki** [NodeBB/NodeBB#4028]
Running master @ 00a22e9
Many of my users are entering invalid email by a feature of smartphone keyboards, which automatically inserts space after period.
We should at least check if it doesn't contain invalid character and contains atmark.

**Comment by julianlam** [comment]
We won't change the regex mostly because it's ultimately unnecessary overhead that does not deter spammers. 

That said, the field for email should be of type `email`, so that's a potential improvement
