### ISSUE TITLE
Code wrapper - horizontal scroll bar.

### ISSUE THREAD

**Issue by wayneworkman** [NodeBB/NodeBB#4031]
Hello, we use NodeBB over at forums.fogproject.org

It'd be amazing if the code boxes had a horizontal scroll bar. Right now, I have to select text and then drag right slowly to see further right.

**Comment by psychobunny** [comment]
![](http://i.imgur.com/ILWMK9k.png)

They do for me, on latest persona/core (I'm pretty sure it has been the case for a while). As I'm typing this I realize you're probably on a Mac

**Comment by barisusakli** [comment]
Doesnt work on multiline cide blocks fir me

**Comment by pichalite** [comment]
I was looking at this issue couple of days ago. Works for me on a Mac.

**Comment by wayneworkman** [comment]
The issue does not appear with a single line if code. It's for very long,
very wide blocks of code.
