### ISSUE TITLE
Admin page: "null

### ISSUE THREAD

**Issue by ishitatsuyuki** [NodeBB/NodeBB#4032]
-Accidentally mistyped the title.

Running master: the connection column says "null" after a little period

**Comment by barisusakli** [comment]
Please provide more info, git hash, a screenshot etc.

**Comment by ishitatsuyuki** [comment]
![s60107-181337](https://cloud.githubusercontent.com/assets/12389383/12166599/75d6cbc2-b56a-11e5-9089-aca64c8a0335.jpg)
master @ 57918332

**Comment by barisusakli** [comment]
What is your socket.io version? `npm ls socket.io`?
