### ISSUE TITLE
Validation/password reset emails are not sent to some email addresses

### ISSUE THREAD

**Issue by rfc2822** [NodeBB/NodeBB#4034]
I'm using NodeBB 0.9.3. Email sending (without external mailer) works (for instance, my own forum emails are delivered instantly). Most people can register without problems, but for some users, the validation emails are not sent. I have looked into the mail server logs, and NodeBB doesn't even try to send these emails (but only for some addresses, others work fine). The email addresses which do not work are in no way questionable or strange-looking.

So, when I look at Manage / Users, about 10% are not validated, and even when I explictly do "Edit / Send Validation Email", no email is sent.

Is this a known problem? Can you check whether you have the same problem (higher rate of unvalidated emails)? How can I help debugging?

**Comment by julianlam** [comment]
Hm, that's odd. Can you let us know an email that does not work?

**Comment by rfc2822** [comment]
Most of them are normal @hotmail.fr and @gmail.com addresses, so there's nothing special … I couldn't see anything wrong or special on these email addresses. sometext@hotmail.fr, sometext@gmail.com, … (other providers too)

**Comment by barisusakli** [comment]
@rfc2822 can you modify this line https://github.com/NodeBB/NodeBB/blob/v0.9.x/src/emailer.js#L118 to

```
console.log('sending email', data);
transports[transports.gmail ? 'gmail' : 'direct'].sendMail(data, function(err) {
    console.log(err);
    callback(err);
});
```

Then try `Send Validation Email` from ACP for one of the emails that doesn't work and check the server logs.

**Comment by rfc2822** [comment]
No luck:
```
12/1 11:06 [92615] - verbose: [emailer] Sending email to uid 1034
null
```

**Comment by rfc2822** [comment]
Additional info: validation emails seem to work when I activate "Route through Gmail service" in NodeBB

**Comment by barisusakli** [comment]
Wait so you dont see the output of this `console.log('sending email', data);` ?

**Comment by rfc2822** [comment]
> Wait so you dont see the output of this console.log('sending email', data); ?

The output is posted above – `console.log(err);` writes "null".

**Comment by barisusakli** [comment]
Yeah but what about the output of `console.log('sending email', data);`? It should display the data for the email etc.

**Comment by rfc2822** [comment]
Ah, change it to… … ok, wait please

**Comment by rfc2822** [comment]
```
sending email { to: 'usersemailaddress@gmail.com',
  from: 'Bitfire App Forums<dev-null@bitfire.at>',
  subject: 'Welcome to Bitfire App Forums',
  html: '<style type=\'text/css\'>.emoji { height:16px; width:16px; vertical-align:middle; margin-bottom:-1px; }</style>\n<p>Hello Günter,</p>\n\n<p>\n\t<strong>Thank you for registering with Bitfire App Forums!</strong>\n</p>\n\n<p>To fully activate your account, we need to verify that you own the email address you registered with.</p>\n\n<blockquote>\n\t<a href="https://forums.bitfire.at/confirm/a3a591d5-829f-4644-8acc-ab255e37cf71">Click here to confirm your email address</a>\n</blockquote>\n\n<p>\n\tThanks!<br />\n\t<strong>Bitfire App Forums</strong>\n</p>\n',
  template: 'welcome',
  uid: 1034,
  pid: undefined,
  fromUid: undefined,
  text: 'Hello username,\n\nThank you for registering with Bitfire App Forums!\n\nTo fully activate your account, we need to verify that you own the email address\nyou registered with.\n\nClick here to confirm your email address\n[https://xxxxx/confirm/xxxxxxxxx]Thanks!\nBitfire App Forums' }
12/1 11:21 [92804] - verbose: [emailer] Sending email to uid 1034
null
```

**Comment by barisusakli** [comment]
Looks good to me, and no errors from nodemailer, so not sure why your users aren't receiving the email.

**Comment by rfc2822** [comment]
> Looks good to me, and no errors from nodemailer, so not sure why your users aren't receiving the email.

As said above, they're not event sent to the mail server… other emails from NodeBB are, and everything works when using Gmail sending in NodeBB :/

**Comment by barisusakli** [comment]
I was reading the documentation on nodemailer. Apparently `direct` isn't reliable so some emails not going out is expected behaviour. 

>Using direct transport is not reliable as outgoing port 25 used is often blocked by default. Additionally mail sent from dynamic addresses is often flagged as spam. You should really consider using a SMTP provider.

**Comment by rfc2822** [comment]
I have just found out that it works with `sendmail`! I suggest to make the transport a choice in NodeBB settings.

**Comment by julianlam** [comment]
Whether we use `direct` or `sendmail`, it doesn't answer the question of why some mails are sent, but others aren't...

Also, I don't believe `sendmail` is installed by default on Ubuntu... unless the `sendmail` transport uses something else?

**Comment by rfc2822** [comment]
>Whether we use direct or sendmail, it doesn't answer the question of why some mails are sent, but others aren't...

Well, I have just looked in my mail server logs to see which emails are sent. So I have only seen the emails sent to my domain, but not to others (because those were sent directly, bypassing the mail server and thus also bypassing its logs).

The answer for the question, why some emails didn't get *delivered*, is in my opinion that some JS library can never fulfill the complex tasks of an SMTP MTA. Maybe the remote servers use greylisting, maybe there were temporary problems, TLS problems, misconfiguration somewhere, bugs… In my opionion, `direct` just should **never** be used. It causes more problems than not sending emails at all: you believe that emails are being sent, but they are not (at least not reliably).

> Also, I don't believe sendmail is installed by default on Ubuntu... unless the sendmail transport uses something else?

Do you mean the sendmail package or a sendmail executable? As soon as any mail server, mail relay software etc. is installed, a sendmail executable is installed too.

**Comment by rfc2822** [comment]
By the way, my emails are now not being sent again … NodeBB error message: "spawn sendmail ENOENT"

**Comment by Whiplash88** [comment]
I have this issue also. I've had my users switch to our nodeb boards and out of 50 people there were 10 who did not get an email. Even after multiple validation requests.

No discrimination between domains.

My solution has been to use the mailgun plugin which allowed these users to receive a confirmation email.

**Comment by julianlam** [comment]
Thanks @Whiplash88. @rfc2822 using a third-party emailer is a good interim solution, at the very least. It does look like we'll have to remove mail sending via `direct`...

**Comment by fenwick67** [comment]
+1 bit me too, same sort of symptoms (intermittent functionality).

**Comment by julianlam** [comment]
I'd probably utilise a third party mailer. The `direct` mailer is notoriously unreliable, even the documentation recommends against using it.

**Comment by rfc2822** [comment]
`sendmail` works for me at the moment…

**Comment by nhlpl** [comment]
Some hosts reject mail from servers without SPF and DMARC domain records. Those two and DKIM can be configured by Ajenti Server Admin Panel.

Sender Policy Framework (SPF)
DomainKeys Identified Mail (DKIM)
Domain-based Message Authentication, Reporting and Conformance (DMARC)

Node.js and NodeBB are are not the source of the problem.

**Comment by rfc2822** [comment]
> Node.js and NodeBB are are not the source of the problem.

Sending mail directly and not via an MTA *is* the source of many problems.

**Comment by nhlpl** [comment]
Thanks for letting me know. 

Similar issue was resolved here: https://github.com/NodeBB/NodeBB/issues/3061#issuecomment-95107510

**Comment by rfc2822** [comment]
Does this issue still need confirmation and/or more info?

**Comment by julianlam** [comment]
Looks to be closable then :smile:
