### ISSUE TITLE
Scroll to first unread post when clicking on thread title

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#4035]
The most intuitive behavior for clicking on the title of a thread seems to be going to the first unread post: https://www.surveymonkey.com/results/SM-5KHWMQHJ/

bookmarks can be utilized to facilitate this UX across devices. 

With the current system of clicking a dialog to go to first unread, I've noticed with infinite scroll, navigating to the actual first unread can be a bit wonky which might be due to the fact that recording the saved place occurs by sending the index of the topmost visible post, whereas the actual last unread is at the *bottom* of the window, which can be off by quite a bit between a high-res computer screen and a mobile phone. It might also be some weirdness in how the window does scrolling so it might be less of an issue by rendering the links to the threads with the unread post index appended to the url: 
`www.nodebb-community.com/topic/<topic num>/<slug>/<last unread>`

**Comment by psychobunny** [comment]
I also agree with this, there was another polarized discussion elsewhere on another issue I think.

If you've already read OP there's no reason for you to go back there - you want to read latest post not reread from page 1. If you do, use the navigation

The second part is probably a UX fail on my part though

**Comment by bdharrington7** [comment]
> If you've already read OP there's no reason for you to go back there

Well not only that, but it's easy to get there (OP) if you really want to, by clicking the nav buttons, and you  don't have to depend on a dialog to pop up to get you there (which seems to also not show up sometimes for I have no idea why)

**Comment by albertdev** [comment]
Any update on how to get this done? Can it be done through a setting or theme change?

Apart from it being confusing for users which are used to different forum software, the current solution breaks my workflow. I use an addon called [Vimperator](http://vimperator.mozdev.org/) which allows me to browse using only my keyboard. However, the little dialog doesn't work for me: that dialog's "Click here" link / button is not recognized as an "actionable" target and hence I cannot activate it using just the keyboard.

Switching to "unread on title click" would fix that as well.

Oh and BTW: if someone still needs a link to the first post, maybe change the small "thread creation time" to a link to the first post (you know, the small text under the title reading "a day ago").

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/pull/261
