### ISSUE TITLE
Monthly visitor graph is broken

### ISSUE THREAD

**Issue by pixeldesu** [NodeBB/NodeBB#4036]
It seems that the monthly visitor graph is either calculated wrong or something else is an issue here. The actual view count (which is shown at the bottom) is 1895.

![](https://jii.moe/NJJ5DKuDx.png)

Running the latest stable version of NodeBB (v0.9.3) on a FreeBSD machine.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/3949 packported to 0.9.x
