### ISSUE TITLE
Invalid file type on upload when using comma delimited 

### ISSUE THREAD

**Issue by Whiplash88** [NodeBB/NodeBB#4037]
Hey guys,

0.9.x

Maybe you can help me with this. I'm receiving this error:
http://i.imgur.com/BLYAUS6.png

```Invalid file type. Allowed types are: jpg&#44; png```

This is what i have in the field where to specify upload restrictions:
http://i.imgur.com/nT5KT2w.png

**Comment by Whiplash88** [comment]
My solution has been to just allow all files types.

**Comment by barisusakli** [comment]
What version/git hash?

**Comment by barisusakli** [comment]
Looks like fixed on https://github.com/NodeBB/NodeBB/issues/4011, try putting in `.jpg, .png` if you are on 0.9.x
