### ISSUE TITLE
Something wrong with user count

### ISSUE THREAD

**Issue by ishitatsuyuki** [NodeBB/NodeBB#4038]
```
ACTIVE USERS
2 Users
2 Guests
4 Total
2 Connections
```
No screenshot, but trust me.
Running master @ af60fbe
Seems related to recent socket.io problems. The connection wasn't less than online users a weeks ago (git pulling every day). It should not be less than users. (User without a connection?)
Another evidence: If I check from the "Users" panel, only me is online, but it shows 2.

**Comment by nhlpl** [comment]
There are always only 2 Guests here.
https://community.nodebb.org/users/online
