### ISSUE TITLE
Hashing long passwords may possibly slow down nbb

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#4041]
1. Enforce a maximum character limit for passwords on registration (ex. 255)

2. When checking credentials on login, immediately deny a password string exceeding that limit

See also: https://github.com/NodeBB/NodeBB/issues/261

**Comment by frissdiegurke** [comment]
`255` still seems low nowadays, I'd promote sth. like `4096` or at least `1024`.

**Comment by psychobunny** [comment]
4096 was something the original reporter just brought up as well. If this is how long your forum password is I'd love to see your bank password but fair game haha

**Comment by frissdiegurke** [comment]
My passwords are all generated using a self-written generator. So it's always as long as allowed by the application... My bank unfortunately allows just 20 chars (few years ago it did only allow up to 6 chars numerical) :P 
It's not like I'd need a couple of hours to login on forums xD
