### ISSUE TITLE
Should I be able to create 2 (or more) groups with the same name but different case?

### ISSUE THREAD

**Issue by akhoury** [NodeBB/NodeBB#4046]
Was able to create group `Administrators` and `aDministrators` etc..., however they all share the same route `/groups/administrators`.

if this is a bug, maybe you should `utils.slugify()` the slugs [here](https://github.com/NodeBB/NodeBB/blob/8e5d26ec369760fd9a3d1611f3cc9d368cedd668/src/meta.js#L31-L38)

```javascript
	Meta.userOrGroupExists = function(slug, callback) {
		async.parallel([
			// async.apply(user.existsBySlug, slug),
			async.apply(user.existsBySlug, utils.slugify(slug)),
			// async.apply(groups.existsBySlug, slug)
			async.apply(groups.existsBySlug, utils.slugify(slug))
		], function(err, results) {
			callback(err, results ? results.some(function(result) { return result; }) : false);
		});
	};
```

**Comment by barisusakli** [comment]
Definitely a bug, another version of it was reported and fixed here https://github.com/NodeBB/NodeBB/issues/3961

**Comment by barisusakli** [comment]
backported to 0.9.x as well

**Comment by akhoury** [comment]
ah nice, my bad, I shouldve tested against latest. Thanks for backporting too.
