### ISSUE TITLE
Session Cookie Should be set with "secure"

### ISSUE THREAD

**Issue by ip6li** [NodeBB/NodeBB#4047]
NodeBB does not set flag "secure" on session cookie. That could be a security flaw.

**Comment by julianlam** [comment]
Are you using NodeBB with http or https?

**Comment by ip6li** [comment]
I am using NodeBB with https, but https is terminate on a reverse proxy. Internal connection rev-proxy->nodebb is http.

**Comment by ip6li** [comment]
If you use Nginx a intermediate fix is to configure following in Nginx:

    proxy_cookie_path / "/; secure";

I know that's a really dirty solution, but it will work until NodeBB fixes that.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/3435

Looks like we have secure and trust_proxy options already.
