### ISSUE TITLE
Problem with Strings in notifications

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#4049]
<img width="306" alt="screen shot 2016-01-12 at 7 52 22 am" src="https://cloud.githubusercontent.com/assets/135263/12264002/9701dcde-b901-11e5-9041-3494f8556ced.png">

I see such notifications on NodeBB Community.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/4033
