### ISSUE TITLE
Last seen is incorrect

### ISSUE THREAD

**Issue by LordZardeck** [NodeBB/NodeBB#4051]
As you can see, even though i'm logged in, it's not updating my last seen. The user adjacent to my profile picture just sent me a chat message 2 minutes ago, but it shows he was last seen 6 hours ago

![latest users rc dev fourm 2016-01-12 15-42-12](https://cloud.githubusercontent.com/assets/1145989/12279221/372219e0-b943-11e5-9f6c-749fe8471e4a.png)

Using v0.9.3 with material design theme

**Comment by psychobunny** [comment]
If the user was 'appearing offline' it won't update their last seen. And I don't think it would make sense DB wise for us to keep track of last seen for each individual user

Let me know if that's not the case, closing for now

**Comment by LordZardeck** [comment]
@psychobunny I think it's confusing to have that if it's not accurate. What is "last seen" supposed to mean then?

**Comment by psychobunny** [comment]
It works accurately unless you're not appearing offline (want to hide your online status)

**Comment by LordZardeck** [comment]
@psychobunny I'm not hiding my status. Neither is the other user.

**Comment by psychobunny** [comment]
It's the other user that matters, please confirm then post your git hash I'll try to reproduce

**Comment by psychobunny** [comment]
Your original screenshot shows him appearing offline, can you show a version where he is appearing online but still says 6 hours ago?

**Comment by LordZardeck** [comment]
@psychobunny Yes, neither of us are hiding our status. Commit `cccc567854c1d351d15cd93140441692b92196bc`. I'll ask him to get online and i'll get you a screenshot

**Comment by psychobunny** [comment]
Okay cool, I just realized your last online isn't being updated either, missed that from your earlier report

**Comment by barisusakli** [comment]
https://community.nodebb.org/users the times here are showing when the user has registered, there is no `last seen` time on any of the `/users/<slug>` pages.

**Comment by LordZardeck** [comment]
I would chalk this up to bad UIX then. Recommend fix: add the word "Registered" before the time statement. That way it's clear as to what that refers to.

**Comment by LordZardeck** [comment]
Although looking at the user profiles, there is a "last online" property showing. I can confirm that what is showing on the users list is the join date, I think it would make more sense for that to be a "last seen" value. That however is a theme issue rather than a NodeBB issue, am I correct?

**Comment by pichalite** [comment]
@LordZardeck I mostly follow persona as guidance to decide what to display. Persona displays join date... so does material theme.

Not sure if "last seen" is appropriate for that page as the users are ordered by join date.

**Comment by LordZardeck** [comment]
@pichalite, yes I was confused as to what was displayed. I can confirm that the last seen is updating correctly.
