### ISSUE TITLE
Themes other than Persona and Lavender don't work on master

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4056]
None of the themes work on master except Persona and Lavender. Not even vanilla.

**Comment by pichalite** [comment]
actually lavender is not exactly working. you get a working vanilla theme when you use lavender. Switching to vanilla shows persona templates.

**Comment by julianlam** [comment]
This may be related to the change I made to put the theme in `plugins:active`. When you try to reorder plugins, is the theme shown?

**Comment by julianlam** [comment]
Also, the change is supposed to be backwards compatible, due to the upgrade scriptscript.

**Comment by julianlam** [comment]
script*, friggin' SwiftKey...

**Comment by pichalite** [comment]
I remembered you made a commit for that... yes I see the theme in the plugin reorder modal... it's the first in the order.

**Comment by pichalite** [comment]
I see you removed a few lines of code from templates.js that might be causing this issue

**Comment by julianlam** [comment]
Can you post a screenshot of the broken theme? Was working fine with everybody's dev builds here...

**Comment by julianlam** [comment]
I did? That sounds highly suspicious to me :wink:

**Comment by pichalite** [comment]
This is what I see when I activate material theme or vanilla

<img width="1280" alt="screen shot 2016-01-13 at 8 50 09 pm" src="https://cloud.githubusercontent.com/assets/10014774/12316061/4d7e390e-ba37-11e5-89f3-e55ba8d518ba.png">

**Comment by julianlam** [comment]
@pichalite I think I may know why... do you have a `templates` option defined in your theme? 

Until I can fix the code to assume, please add it to your `plugin.json` :smile:

**Comment by pichalite** [comment]
ok... it works after I add `templates` option to `plugin.json`

**Comment by julianlam** [comment]
Will need to update behaviour to assume the templates directory is `templates` for a theme

**Comment by pichalite** [comment]
fixed in this commit https://github.com/NodeBB/NodeBB/commit/8f47a0c653ca22577aac7d933d22a1d647294b9c
