### ISSUE TITLE
[prio, security hole] groups, users, profiles, emails etc. are visible for guests

### ISSUE THREAD

**Issue by Pappmann** [NodeBB/NodeBB#4060]
i have all guest handles disabled, in "General/Navigation" is all enabled only for registered users.

**Anonymous Users can see /groups, /users, /user/username, can see user emails, see followers etc.**

thats a big security hole for a closed small community , where no anonymous user has to know who is registered in this forum!

**Comment by globalcow** [comment]
In the section 'Account settings' in Settings > User you have to activate 'Make user info private'

**Comment by julianlam** [comment]
Individual users can also show/hide their emails, and this is private by default.

**Comment by Pappmann** [comment]
Why closed? Groups users user profiles are always visible for guests. E-Mail users complete Name has to be visible only for registered users!

**Comment by Pappmann** [comment]
Plesse make forum show error message vor redirect to home page when guest what to view link to /groups /users /user... Etc.

**Comment by globalcow** [comment]
@Pappmann: I cannot confirm your issue. I have a forum which is closed down for guests, and it is not possible to access groups or users as you mentioned it. Make sure you activated 'Make user info private' in the admin control panel.

**Comment by julianlam** [comment]
![selection_073](https://cloud.githubusercontent.com/assets/923011/12450163/eabfe420-bf4f-11e5-8a75-4ad5a7589b0a.png)

**Comment by julianlam** [comment]
As @globalcow says, we cannot confirm this is an issue. If with the option **enabled**, user info is leaked, please let us know again via this issue.
