### ISSUE TITLE
Escaping $$ inside a code block

### ISSUE THREAD

**Issue by tekojo** [NodeBB/NodeBB#4061]
On NodeBB 0.8.2
The following post:
```
unix:DEFINES += VERSION=\\\"$$VERSION\\\"
```

Gives:
unix:DEFINES += VERSION=\\\"$VERSION\\\"

So it loses one $, which is bad as it's code and still easily looks correct to a human reader.

**Comment by psychobunny** [comment]
Just for anybody looking at this issue:

This passes t.js (see above reference). Today I tested with markdown disabled and it still breaks, so I'm confounded as to what's actually causing this

**Comment by barisusakli** [comment]
This also happens outside of code blocks.

```
`unix:DEFINES += VERSION=\\\"$$VERSION\\\"`
unix:DEFINES += VERSION=\\\"$$VERSION\\\"
```

Produces 
![image](https://cloud.githubusercontent.com/assets/2583394/13400399/32c9e06a-df10-11e5-815b-1f2a05a5907e.png)

The /api/ route has the correct output though.

```
"content": "<p><code>unix:DEFINES += VERSION=\\\\\\&quot;$$VERSION\\\\\\&quot;</code><br />\nunix:DEFINES += VERSION=\\&quot;$$VERSION\\&quot;</p>\n",
```

**Comment by barisusakli** [comment]
This can be just reproduced by posting `$$$` it will be collapsed to `$`

**Comment by barisusakli** [comment]
See here https://github.com/psychobunny/templates.js/issues/43#issuecomment-190312445
