### ISSUE TITLE
Let MD resolutions use mobile composer

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4071]
As ipad and some other tablets experience with composer is very bad (cant dragg it to make it bigger, flickering, dissapearing, etc) could let MD resolutions use mobile composer. It works better.

**Comment by julianlam** [comment]
@martyalicante To my knowledge, the iPad should already load the mobile composer in portrait mode, but not landscape mode, can you confirm this is the case?

**Comment by martyalicante** [comment]
Yes. That is correct
Portrait mode isnt very popular on ipad anyways

**Comment by julianlam** [comment]
The `md` resolution is still used by screens of smaller resolutions, including non-maximized windows on laptops, so unfortunately, I can't make this change.
