### ISSUE TITLE
Untranslatable string /src/user/digest.js

### ISSUE THREAD

**Issue by globalcow** [NodeBB/NodeBB#4074]
In line https://github.com/NodeBB/NodeBB/blob/master/src/user/digest.js#L25 is the fixed string 'day' used. It can be translated.

**Comment by julianlam** [comment]
Hello @globalcow -- the variable highlighted in the link you pasted is only used internally, and so it is not intended to be translated. Can you show me where it is used on the client-side in English, where it should be localised?

**Comment by globalcow** [comment]
Hi @julianlam. I am working with the german translations. When a receive a digest email, I get the following content:

> Es gab keine aktiven Themen in den letzten **day**

English translation is:
> There were no active topics in the last **day**

I could not find any missing strings on transifex and I thought I had narrowed down the error to the mentioned file.

Another possibility I could think about, there is no `public/vendor/jquery/timeago/locales/jquery.timeago.de-short.js` in the nodebb resources. Could this be the reason?

**Comment by globalcow** [comment]
I took a closer look and I think I am right. The digest template uses the {interval} parameter. This parameter is set in https://github.com/NodeBB/NodeBB/blob/master/src/user/digest.js#L46 to the value 'day'.

**Comment by julianlam** [comment]
Thanks @globalcow, strings added to Transifex :)

**Comment by globalcow** [comment]
Hi @julianlam. Great. Trank you. However, it is really difficult to translate it that way, as the whole sentence varies depending on the type of interval. At least in the German language 😕

**Comment by globalcow** [comment]
Or it should be agreed on, that *digest.day* and so on does not mean just 'day' but the expression 'last day'

**Comment by julianlam** [comment]
Oh yes, I can see how that would be confusing.

**Comment by julianlam** [comment]
Not sure how it looks for `de`, but it's possible to change the order as the strings relate to the sentence before it:

![selection_074](https://cloud.githubusercontent.com/assets/923011/12451287/7a5df152-bf56-11e5-8c6d-bf1acb583984.png)

In this case, if I wanted to swap the order around, I'd change string 22 to read: `In the past %1, there have been no active topics`

Perhaps that is good enough for you?

**Comment by julianlam** [comment]
For `de`, you would just change it to "tagen", as those strings are used in that context only.

**Comment by globalcow** [comment]
Yes, of course this is possible. 
'tagen' would mean in the past day**s**. In this context you just mean in the past day (so just one day)? Same is true for week and month?

To translate this correctly, I have to include the translation of 'past' in the interval messages. If this is not a problem and it is made sure, that it will be only used in this context, than this will work!

Actually, I have done the german translation like this in transifex, perhaps you can take a look?

**Comment by julianlam** [comment]
Looks good to me :smile:
