### ISSUE TITLE
Category privileges set at user level should override the privileges the user gets from the groups they are a member of

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4075]
Category privileges set at user level should override the privileges the user gets from the groups they are a member of.

**Comment by julianlam** [comment]
Privileges are additive, that may be the cause of confusion... if their user privilege is restrictive but their group privilege is liberal, they'll obtain the liberal set (plus whatever privileges the user privilege contains that the group privilege does not)

**Comment by pichalite** [comment]
I think it should just ignore their group privileges if they have privileges setup at the user level. This gives more flexibility.

**Comment by julianlam** [comment]
Unfortunately I feel the need for this level of complexity is outweighed by the effort required to maintain it, and makes it more difficult to understand the system as it's rules would then be "privileges are additive *unless you give priviliges to a user*, in which case they override everything prior"
