### ISSUE TITLE
A wee spelling error in initial post after setup v0.9.3

### ISSUE THREAD

**Issue by ZenOokami** [NodeBB/NodeBB#4076]
The initial post made when you create the forum has a slight spelling error for "administrator" and is missing an "r".

This isn't a major issue, but I figured might as well throw it out there :)

I'm loving the system thus far, learning a lot as well. Keep up the great work you beautiful minds!
![image](https://cloud.githubusercontent.com/assets/2906275/12404424/78f7d722-be09-11e5-83f5-f4b8097a8925.png)

**Comment by barisusakli** [comment]
Hi thanks for reporting already fixed here https://github.com/NodeBB/NodeBB/commit/cbcae33173f0447582c5b5cfd92554eca31ab298
