### ISSUE TITLE
After installing a forum via web installer, get 503 excessive load warning page

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#4080]

**Comment by julianlam** [comment]
Should've been resolved here? 3a520cdfbf2548c88a52c801db5bdec2c825b365

**Comment by psychobunny** [comment]
Still an issue, just repro'd again

**Comment by julianlam** [comment]
Image is outdated :smile:

**Comment by psychobunny** [comment]
ha. right. guess I'll reopen this every month until we update the image :P
