### ISSUE TITLE
Post click turn to login if window is small although having set guests can post and reply in a categorie

### ISSUE THREAD

**Issue by SinalVee** [NodeBB/NodeBB#4083]
if click post button in large window(width > 992px), it's ok. But when click in mobile or a little window(width < 992px, div class turn to col-xs-*), console got this error.
```
nodebb.min.js?ed0abb5a-ce26-42e7-a159-ab911eff9f4b:3
GET http://127.0.0.1:4567/api/compose?p=/category/5/anyone&_=1453356494977 401 (Unauthorized)
```

**Comment by barisusakli** [comment]
Caused by https://github.com/NodeBB/NodeBB/blob/master/src/routes/index.js#L30 only logged in users can go to the `/compose` route which is probably not what we want.
