### ISSUE TITLE
2 issues with v0.9.3

### ISSUE THREAD

**Issue by micpringle** [NodeBB/NodeBB#4086]
Hello,

Whilst setting up an instance of NodeBB using v0.9.3 I've come across two issues thus far, both of which are documented, and I was wondering if you were planning on releasing an interim update to v0.9.3 that has fixes for both these issues, since anyone getting started with NodeBB at this time will likely use this release and face the same problems.

The two issues I'm referring to are:

1.  [fatal error: nan.h: No such file or directory](https://community.nodebb.org/topic/7302/fatal-error-nan-h-no-such-file-or-directory)
2. #3979

The first prevents NodeBB from being installed, and the second prevents visiting any discussions once you've worked around the first.

Would be great to get a v0.9.4 release with these issues fixed. :+1:

**Comment by barisusakli** [comment]
@julianlam  can we release 0.9.x  as 0.9.4? Since there seems to be a few fixes that are back ported there. https://github.com/NodeBB/NodeBB/commits/v0.9.x

**Comment by julianlam** [comment]
:+1:

**Comment by julianlam** [comment]
v0.9.4 interim release launched.
