### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by layernull** [NodeBB/NodeBB#4087]
When I start nodebb via `./nodebb dev` I get no errors, everything seems to work just fine.
However, when I start nodebb via `./nodebb start` or `node app start` I get "Cannot GET /"

My setup
- Debian 8.2
- NodeJS 4.2.5 LTS
- MongoDB 3.2.1 WireTigger
- NodeBB v0.9.3
- Nginx 1.6.2-5

Additional modules: custom homepage, does not make a difference if I disable this or not

Any ideas what might be the cause for this odd behavior?

**Comment by julianlam** [comment]
Check for errors in the nodebb log in `logs/output.log`

**Comment by layernull** [comment]
I did, I see no errors, only a few warnings. Really strange. This is the full content of 'logs/output.log' when running './nodebb start'

    ~/NodeBB/logs$ tail -f output.log
     21/1 10:49 [3784] - info: [database] Checking database indices.
     21/1 10:49 [3784] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
     21/1 10:49 [3784] - warn: [plugins/load] The following plugins may not be compatible with your 
        version of NodeBB. This may cause unintended behaviour or crashing. In the event of an   
    unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
     * nodebb-plugin-composer-default
     * nodebb-plugin-markdown

    21/1 10:50 [3784] - info: NodeBB Ready
    21/1 10:50 [3784] - info: Enabling 'trust proxy'
    21/1 10:50 [3784] - info: NodeBB is now listening on: 0.0.0.0:4567

**Comment by layernull** [comment]
Fixed it by downgrading nodeBB to the actual v0.9.3 revision. 
I also downgraded NodeJS 4.2.5 LTS to 0.1.9 LTS at the same time because of rebuild issues (out of memory)
