### ISSUE TITLE
If someone types string like [[global:login]] when post, it will be translated to the string setting in language/*/*.json file

### ISSUE THREAD

**Issue by SinalVee** [NodeBB/NodeBB#4091]
e.g
I type `[[global:403.login]]`, it show `[[global:403.login]]` in the preview panel.
But after I post, it turns to `“Perhaps you should <a href='%1/login'>try logging in</a>?”`.
I think these string should not be translated.

**Comment by SinalVee** [comment]
And i didn't allow HTML in markdown setting, `Perhaps you should <a href='%1/login'>try logging in</a>?` still display as html, the `a` tag can be click.

**Comment by julianlam** [comment]
Hm... this is a tricky issue. While the translation of language keys in post content is definitely unexpected, it is not harmful to NodeBB.

We translate the outgoing html in one pass, and there is no way we can distinguish what is post content and what is not, so it all gets translated. We can't think of a simple/elegant/scalable way to do this.

Before, actually, we'd have the keys translated, but ajaxified content *untranslated*, which is even more unexpected, so I believe we now translate post content on client-side load as well so the experience is the same on both cold load and not.

**Comment by julianlam** [comment]
Closed via 99315e1c737c4a6261407bee18ae326be9e69171
