### ISSUE TITLE
XSS in Chat

### ISSUE THREAD

**Issue by gartnera** [NodeBB/NodeBB#4092]
You can XSS someone by sending them a chat message containing a script tag. From what I can tell, the input validation was removed here: https://github.com/NodeBB/NodeBB/commit/af50ade0662eb0ca084576469f9a2f7702817918

**Comment by ArcticRaz0r** [comment]
I haven't been able to reproduce the issue, the script tags are being escaped normally. Were you following any particular steps?

**Comment by barisusakli** [comment]
Did you disable the markdown plugin? That might explain the issue since the chat message won't be parsed as a post.

**Comment by gartnera** [comment]
Oh yeah, I enabled the nodebb-plugin-composer-redactor editor. In doing such, it required me to disable the markdown plugin. Is there a way to enable input validation just for chat?

**Comment by julianlam** [comment]
I thought redactor came with its own html sanitizer, actually...

**Comment by gartnera** [comment]
Yeah it does, but the editor only replaces the post editor, not the the chat editor (AFAIK). I'm not familiar with the code of either project.

**Comment by psychobunny** [comment]
Moved this to the redactor repo, since the issue is more specific to that plugin:
https://github.com/NodeBB/nodebb-plugin-composer-redactor/issues/37
