### ISSUE TITLE
unstyled user icons in acp>manage>group

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#4096]
![image](https://cloud.githubusercontent.com/assets/2583394/12530016/d6574822-c1d7-11e5-94c5-a7dc3f0708fa.png)

**Comment by barisusakli** [comment]
When you search for users the results dont display proper images as well

**Comment by julianlam** [comment]
Cannot repro *fully* on my de:

* Search dropdown shows avatars, but user icons are empty
* Member list is ok

![selection_080](https://cloud.githubusercontent.com/assets/923011/12552633/e64189fe-c340-11e5-833c-fc0e1585c026.png)

**Comment by pichalite** [comment]
@julianlam this issue happens when you search in the "Member List" section.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/4110/files

**Comment by pichalite** [comment]
this needs to be reopened. original issue is still not fixed. the pull request only fixes the issue mentioned by julian on his comment about user icons
