### ISSUE TITLE
Suggestion - Grouping registration requests

### ISSUE THREAD

**Issue by Incognitov** [NodeBB/NodeBB#4098]
Hey,

We've restricted registration requests to avoid spam bots and such alike.

![](http://i.imgur.com/a2xl3xI.png)

This tends to be quite "spammy" in our notifications and can end up taking a huge amount of space, would it be possible to merge them together to give something like: "User1 and 10 other users sent registration requests."? Or something along those lines. Perhaps a toggle even if administrators prefer to have them separate or grouped.

Thanks.

**Comment by julianlam** [comment]
Yup, can do. Thanks for the suggestion!
