### ISSUE TITLE
Post index

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#4099]
One question about about post index
why a post url is something like 
https://community.nodebb.org/topic/id/something/18

and then post index is 17 for that post

i know main post is index 0, then 1,2 etc 
but in my opinion 1 should be first instead of 0, to keep same number of the url

**Comment by barisusakli** [comment]
We use 0(false) for main post as it lets us distinguish it from the other replies in the templating engine.

**Comment by martyalicante** [comment]
Could use 1 for check it instead of 0 😂

**Comment by julianlam** [comment]
@martyalicante Not in templates.js :laughing:
