### ISSUE TITLE
pagination block shows up empty

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#4104]
![image](https://cloud.githubusercontent.com/assets/2583394/12550157/8f37e232-c36a-11e5-99d6-24e4354d233b.png)

**Comment by julianlam** [comment]
Looks to be regression from 32466d8bb183d986e7ee17845627f3dc9b25c310

**Comment by pichalite** [comment]
@julianlam fix doesn't seem to work on hard refresh.

**Comment by pichalite** [comment]
issue only on /categories route

**Comment by psychobunny** [comment]
I confirm this as well

**Comment by julianlam** [comment]
Can't reproduce, are you sure your themes are up to date?

**Comment by julianlam** [comment]
@pichalite In material, you'll need [this changeset](https://github.com/NodeBB/nodebb-theme-persona/commit/074e30a6411d4ece13b4565384367f85c45274fe)

**Comment by julianlam** [comment]
Confirmed working in Vanilla, Lavender, and Persona.

**Comment by pichalite** [comment]
@julianlam I was only looking at https://community.nodebb.org not material theme. May be the community is not updated to latest?

**Comment by psychobunny** [comment]
my bad, I had updated the community and still reproduced the error - that's because I forgot to restart after updating

Doing too many things at the same time :P

**Comment by julianlam** [comment]
Cool, thanks for following up :smile:
