### ISSUE TITLE
Mentions translation broken

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4107]
![image](https://cloud.githubusercontent.com/assets/10014774/12566761/2d2e32a2-c370-11e5-81c7-f294cf00b2fe.png)

**Comment by pichalite** [comment]
looks like it's only for topics with `( )` in the title

**Comment by ReyKoxha** [comment]
Confirming this.

**Comment by julianlam** [comment]
Thanks guys :smile:
