### ISSUE TITLE
Forum wiped clean

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/NodeBB#4108]
When I've tried to login to my NodeBB instance deployed on a VPS, I was unable to do so, and all the users, categories, topics and so worth were wiped completely clean.

Upon restarting NodeBB, I was greeted with this:

<img width="1433" alt="screen shot 2016-01-26 at 14 57 44" src="https://cloud.githubusercontent.com/assets/5879873/12583139/78ede9f4-c441-11e5-822d-cddb626e6470.png">

I was also able to notice that Redis contains no data at all, except some session keys.

**Comment by julianlam** [comment]
Secure your Redis server, as it is open on all ports with likely no password. Restore backups.

http://redis.io/topics/security

**Comment by mrgame64** [comment]
I noticed, but the fun part is that everything is behind a firewall.

**Comment by julianlam** [comment]
Depending on the settings, perhaps something got through, or an exposed piece of software allowed shell access.

_To our knowledge_, no such vulnerability exists in NodeBB, and while it is possible [using Redis to save a public key to the disk to allow shell access](http://antirez.com/news/96), that's unfortunately not something we can fix besides stressing that Redis (and your server) be secured as tightly as possible.

**Comment by mrgame64** [comment]
Looks like I have no choice but to reinstall everything and secure Redis better next time.
Thank you for your time!

**Comment by brandonros** [comment]
What is the protocol for restoring NodeBB from a redis dump? I'm listing all keys and hashes, but I can't find any that seem to be NodeBB specific.

**Comment by brandonros** [comment]
I hope this helps somebody.

Keys:

* user:*
* widgets:*
* userslug:uid
* username:sorted
* username:uid
* uid:*
* topics:*
* topic:*
* tid:*
* settings:*
* sess:*
* schemaDate
* posts:*
* post:*
* plugins:*
* navigation:*
* ip:*
* groupslug:*
* groups:*
* group:*
* events:*
* event:*
* fullname:*
* email:*
* cid:*
* category:*
* categories:*
