### ISSUE TITLE
Tags with a space do not add - to the URL

### ISSUE THREAD

**Issue by sorvani** [NodeBB/NodeBB#4109]
Example: On the mangolassi.it community you can search for the tag "open source"

![img](https://i.imgur.com/D8pJ3nT.jpg)

clicking the link works but ends up putting the good old %20 in the URL.

`http://mangolassi.it/tags/open%20source`

So if I try to type a quick URL for someone i cannot unless I know the magic of URL encoding (users certainly do not).

Additionally, if you try to put it in a markdown link tag it still breaks on the space as can be seen by what this user did with the "how to" tag.

![img](https://i.imgur.com/9Qi38fJ.jpg)

**Comment by barisusakli** [comment]
Not sure if this can be fixed without changing `open source` to `open-source` on tag creation.

**Comment by julianlam** [comment]
According to the latest [CommonMark Spec](http://spec.commonmark.org/0.24/#links), this behaviour is intended:

> a sequence of zero or more characters between an opening < and a closing > that ((contains no spaces\*\*, line breaks, or unescaped < or > characters, or...
> *-- [CommonMark Spec v0.24](http://spec.commonmark.org/0.24/#links)*

If the link is modified in the composer to have a %20, then it will satisfy those rules and be detected.
