### ISSUE TITLE
Why does a topic.title need a valid slug?

### ISSUE THREAD

**Issue by akhoury** [NodeBB/NodeBB#4111]
For example, say i have this topic
```
  title: ":|",
  content: "foo bar ok 10x bai"
```
 when [slugifying](https://github.com/NodeBB/NodeBB/blob/fcb381f922840f2904b51cc1865946954246c021/src/topics/create.js#L29-L31) this title, it ends up with an empty string and then an `[[error:invalid-title]]` gets thrown.

During some imports, I found some examples of such titles (and few other invalid slug-characters) - so I decided to be forgiving and skipped the `if (! slug.length)` check, so each of these titles' slugs looked like this: `"{tid}/"` and the URL routing still worked just fine.

**Comment by psychobunny** [comment]
As an aside: nbb default title limit is > 8 chars, so it would be a stretch to have an invalid slug like that normally

**Comment by akhoury** [comment]
well, right before an import,  I backup the original config, then I override them with [these](https://github.com/akhoury/nodebb-plugin-import/blob/b064d6fb9707eb3190a6b35c4accc2b26d1aa5d0/server/importer.js#L87-L119) - so that makes the minimum acceptable length of a topic's title at `0` :D 

I do that, so i can import as much as possible

**Comment by akhoury** [comment]
but regardless, say it's `:|:|:|:|:|:|:|:|:|:|:|:|`

**Comment by psychobunny** [comment]
Sorry I meant the slug is checked on post, so outside of an import, its not possible normally (again, just a side note)

**Comment by barisusakli** [comment]
I can see some of the client side code breaking if the url is not structured as `topic/<id>/<slug>/<post_index>`

**Comment by BenLubar** [comment]
What Discourse does for this is to set the slug to "topic". So you'd end up with `topic/12/topic/345`.

My Discourse importer handles this by appending some text to any title that would have a zero-length slug.

**Comment by psychobunny** [comment]
Makes sense to me
