### ISSUE TITLE
document.title is not guaranteed to be updated on action:ajaxify.end

### ISSUE THREAD

**Issue by akhoury** [NodeBB/NodeBB#4113]
Is there another event to listen to to guarantee that the `document.title` has changed ?

* paste it in your console here https://community.nodebb.org
* click around a bit, it doesn't happen all the time.

```javascript
$(window).on('action:ajaxify.end', function(ev, data) {
  console.log('immediate: document.title', document.title);
  setTimeout(function() {
    console.log('after 2s: document.title', document.title);
  }, 2000)
});
```
### Screenshot.
![screen shot 2016-01-27 at 12 43 42 am](https://cloud.githubusercontent.com/assets/1398375/12605058/1d7b52f2-c48f-11e5-897b-e88a2cfd22b3.png)

**Comment by barisusakli** [comment]
Could be as simple as moving https://github.com/NodeBB/NodeBB/blob/master/public/src/ajaxify.js#L156 above ajaxify.end

**Comment by akhoury** [comment]
nah, .. [refreshTitle](https://github.com/NodeBB/NodeBB/blob/0368280e52a504cd40846e29bc0ca56301753d78/public/src/app.js#L324) is async
