### ISSUE TITLE
Broken compatibility with node 0.10

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#4116]
https://github.com/NodeBB/NodeBB/commit/afbbb33878fb877f8c71770884c0f35a561ef1a2#diff-def3c88e0b2c884e3b869b33317bbbbbR168
uses `fs.access`, which is from 0.12

Not sure if this was a mistake or if you plan to change the dependencies.

**Comment by akhoury** [comment]
break it !! break it !!! break it !!

**Comment by akhoury** [comment]
well, maybe not for 1.0

**Comment by barisusakli** [comment]
Dont think we need to break anything here just use [file.exists](https://github.com/NodeBB/NodeBB/blob/master/src/file.js#L70)
