### ISSUE TITLE
Uncaught TypeError :: RegExp.prototype.sticky getter called on non-RegExp object

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#4118]
@barisusakli @julianlam @psychobunny  This happens only with Chrome/Chromium both in the frontend and the backend. It breaks script execution for the entire page (obviously). I'm thinking that since I haven't made any changes to the ACP, we can rule out my theme modifcations as the culprit. 

You can see it for yourselves [here](https://forum.antergos.com). Do you guys have any ideas as to what might be causing this?

**Comment by pichalite** [comment]
@lots0logs a simple google search provided this solution

http://stackoverflow.com/questions/33728084/whatsapp-web-regexp-issue-in-google-chrome

**Comment by julianlam** [comment]
Mmhm, I can't seem to get the error on my chrome, so perhaps it is the experimental flag as @pichalite has discovered...

**Comment by lots0logs** [comment]
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/12647775/87ee9942-c59c-11e5-93be-e238957cfb94.gif)
