### ISSUE TITLE
Disable Ajax & Additional Widgets

### ISSUE THREAD

**Issue by ReyKoxha** [NodeBB/NodeBB#4119]
There should be a possibility to disable Ajax effects easily over the AdminCP.
Currently this is only possible by modifying several files.

Also there should be more widget positions.
For example, after the first post.

These changes would increase the overall "ad-friendliness" and allow to use other ads than Google AdSense.
This would also make the current AdSense plugin useless.

**Comment by pitaj** [comment]
What do you mean by disable Ajax? Do you want to disable infinite scrolling? Do you want to disable the single page functionality altogether?

Why would you want to do so?

**Comment by ReyKoxha** [comment]
Ajaxfication overall.

Because of issues with advertisments, like AdSense, Media.net or whatever else you want to use.

Giving the possibility to disable the effect easily (without modifiying the ajaxify.js and the composer), would make NodeBB more ad and therefore webmaster friendly. Additionally it would spare the devs plenty of time to work on ad plugins or anything like that.

**Comment by pitaj** [comment]
You want it to be note ad friendly? As in, you want more page loads?

**Comment by ReyKoxha** [comment]
You don't seem to understand the problem.
The Ajax effect causes ads NOT to work as most of the ad code is not capable to realize a page change, when using Ajax.

So far only DFP supports it, but even there I noticed certain issues. Now imagine if a webmaster doesn't wants to use Google AdSense.

What do you suggest?

For me personally there is no issue here as I already have my own, fully working solution, however, if you check the NodeBB Community Forums, many people face this "problem" and seek a way how to make it work.

**Comment by pitaj** [comment]
Hmm

**Comment by nhlpl** [comment]
> Also there should be more widget positions.
For example, after the first post.

I agree with this one. Very useful.

Could you please share some details about your own solution? You know, it's open source project after all.

**Comment by pitaj** [comment]
I believe this could be done by removing the ad and adding it back on every page change. Disabling one of the best features of the site is a bad solution.

**Comment by pitaj** [comment]
@nhlpl widget positions are determined by the theme. 

Right now, the widget system is being reworked entirely.

**Comment by julianlam** [comment]
Disable ajaxify? Sure. Add this to your custom html, to be executed on document ready (maybe):

`$(document.body).off('click', 'a');`

**Comment by ReyKoxha** [comment]
@pitaj, I weren't talking about disabling it, rather to give the possibility to do so. But if Julian doesn't think its worth doing so I should close this issue.
