### ISSUE TITLE
access denied in navigating directly to user settings link from notification email

### ISSUE THREAD

**Issue by jeffbski** [NodeBB/NodeBB#4120]
The link that Nodebb notification emails include to be able to change your email preferences doesn't work when clicked or accessed directly. 

If you try to navigate to the `/user/foo/settings` directly you get 

```
Access Denied

You seem to have stumbled upon a page that you do not have access to.
```

One can navigate to `/user/foo` directly and then use the menu to go into the settings, but just can't go directly there via the url. 

Maybe there is a route missing that should allow one to go directly there? (because it would be useful to be able to go directly to the settings from the email link, rather than having to explain how to get into settings from the user profile).

**Comment by barisusakli** [comment]
This seems to work on `https://community.nodebb.org` what version are you running? Can you post a link to your forum?

**Comment by jeffbski** [comment]
You are right it does seem to work on the nodebb community forum. 

I am using a pretty recent commit off of master 4440865ec41a0d16b8a080b7dba9f8e53de5aea9

Unfortunately, my forum is not publicly available.

I wonder if possibly there is a nodebb setting that can cause this? maybe I have something configured that prevents it, but it is weird in that you can get to it using the nodebb menu but not from a direct navigation. 

I can see if a more recent version of master works.

**Comment by jeffbski** [comment]
It appears that this is being caused by the plugin session-sharing which I am using. When it is enabled and the session-handling option is set to `revalidate` rather than trust, then I get this error when trying to navigate directly. If I change the session-handling to `trust` then it works properly.

I will log an issue in the session-sharing plugin repo and close this one.
