### ISSUE TITLE
It would be nice to have a way to initiate a chat from the chat page

### ISSUE THREAD

**Issue by jeffbski** [NodeBB/NodeBB#4121]
It was a little confusing for me to figure out how to use the chat functionality. 

When I went to the chat page, I assumed that I should be able to initiate a chat with someone from that page, but I could not find a way to do so. For a new user, this is really confusing since they don't see any existing chats in there either.

I later figured out that I have to go to the users page and click on a user and them use the menu from there to initiate a chat.

So that works but it is not super intuitive. 

I would suggest that if we could have some mechanism for initiate a chat from the chat page that would be very helpful, especially for new users.

Thanks for all your work on this wonderful software. It is amazing.

**Comment by julianlam** [comment]
I agree, and it's something I intended to do with the chat, but didn't get around to doing.

Good suggestion :smile:

**Comment by jeffbski** [comment]
With the way that normal topics update to replies over web sockets, they become more powerful and I use chat less and less, but it is still useful for private conversations.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/4165

**Comment by jeffbski** [comment]
Could someone release a new version of persona (to npm) containing this new feature and update the this package.json to pull it in?

It has been committed, but not published so it doesn't work unless you manually install the new persona.

**Comment by barisusakli** [comment]
New theme versions published

**Comment by jeffbski** [comment]
Thanks @barisusakli
