### ISSUE TITLE
Cover image move doesn't have a save button to persist change

### ISSUE THREAD

**Issue by jeffbski** [NodeBB/NodeBB#4122]
When you move a cover image for a profile, it says to move and click save, but once you start the move there is no save button on the profile page. 

So navigating away and back it obviously loses the changes.

I'm guessing there used to be a save but it isn't displaying for some reason.

**Comment by julianlam** [comment]
Hey there, what theme are you using?

**Comment by jeffbski** [comment]
I am on a recent version of master just using the default theme, Persona. I am also using the default skin.

**Comment by pichalite** [comment]
@jeffbski did you try it on https://community.nodebb.org and does it work?

**Comment by jeffbski** [comment]
It works on community.nodebb.org and actually I found that if I increase the width of my window, it works on my site too. It looks like there is a problem in the layout when the site title is longer, like mine is CodeWinds Community.

When you shrink the window width to about 1000 px then, the buttons seem to have too much margin and thus expands down into the image and hides the save button.

See the attached screenshot. I had just put the cover in move mode, and there is no save button visible due to the layout issue.

If I expand the screen width then the buttons move up and I can again see the save button.

![moving-cover](https://cloud.githubusercontent.com/assets/5689/12658393/6f3c329c-c5ce-11e5-93cf-abf13bc193f8.png)

**Comment by jeffbski** [comment]
it actually moves the toolbar onto a whole new row rather than being in a single row at the top thus hiding the save button.

**Comment by jeffbski** [comment]
I assume that if you use a longer site title you can reproduce the issue

**Comment by julianlam** [comment]
Aah, _that_ bug. The workaround for now is to update the nav settings to limit the options present in the navbar. I'd recommend removing the "search" button as the search bar makes it superfluous. Possibly "tags", if you don't use them.

To be honest, we don't quite know the best way to handle situations where there are too many items in the nav and it drops down to a second row.,,

**Comment by jeffbski** [comment]
ok. Good idea. Thanks for the work around idea. I may also just shrink the name in the short term.

**Comment by pichalite** [comment]
@julianlam how about an option in the ACP to specify a short title for smaller screens?

**Comment by jeffbski** [comment]
That might be a good way to go. Nice idea.

**Comment by julianlam** [comment]
Was just thinking that... could be a checkbox to "not show on smaller screens", which would basically just append `hidden-md` to the class...

**Comment by pichalite** [comment]
well in the case of the material theme, we have the notification, chat and profile options on the header on `xs` screens as well so shorter title option might serve more cases? :smile:
