### ISSUE TITLE
When going to the "Skins" page, it never loads.

### ISSUE THREAD

**Issue by SirGamer** [NodeBB/NodeBB#4124]
Read above, and this it what it says too " Loading Themes"...

**Comment by pichalite** [comment]
@SirGamer more detail would be helpful like NodeBB version and or git hash

do you see any errors in the NodeBB log or in the browser console?

**Comment by SirGamer** [comment]
Nope, no errors in the NodeBB log nor the browser console.

VERSION: NodeBB v0.8.2.

**Comment by pichalite** [comment]
well the bootswatch api that NodeBB was using in that version is not available anymore. it's switched here to use latest.

https://github.com/NodeBB/NodeBB/issues/3964

you will have to upgrade NodeBB to latest version or patch it yourself using the code from the commit that closed this issue.
