### ISSUE TITLE
Getting an error while trying to use the NodeBB console

### ISSUE THREAD

**Issue by SirGamer** [NodeBB/NodeBB#4125]
Content-Type specified (plain/text) must be 'application/json'

**Comment by pichalite** [comment]
what are you trying to do when you get this error. need more details.

**Comment by SirGamer** [comment]
I just open the console, and I get this.

**Comment by psychobunny** [comment]
Can you post a screenshot? Or even better, if the site is live post the url so we can have a look

**Comment by SirGamer** [comment]
So, you're saying that you see my admin password? :O

**Comment by SirGamer** [comment]
http://sys65894.leet.cc/.

**Comment by barisusakli** [comment]
Try our community forums for more help. You might need to update your forum.
