### ISSUE TITLE
Chat close/fullscreen icons not displaying on IE 11 and Chrome on Win 7, also chat full-screen broken on IE 11

### ISSUE THREAD

**Issue by jeffbski** [NodeBB/NodeBB#4128]
The chat floating window close and full-screen icons do not show up on IE 11 and Chrome using Windows 7.

OS:          Windows 7 Service Pack 1
IE:           11.0.9600.18163
Chrome:  47.0.2526.111

Maybe it is because a certain css property is not supported to do the greying effect for those icons?

You can click them if you know where they are and just click blindly.

Also another issue on IE 11.0.9600 the full screen chat is also badly broken. It doesn't have any text input to be able to respond to a chat.

This is all using the NodeBB master at commit 4440865ec which is fairly recent.

I am using the default layout Persona and default skin.

Below is a screenshot of the floating chat in IE 11 without the close, full-screen icons

![chat-dialog](https://cloud.githubusercontent.com/assets/5689/12684674/c7177726-c685-11e5-91ce-250f4ac2c197.png)

And here is a screenshot in IE 11 after clicking full-screen for chat (by guessing where the icon is) and it has no way to reply to the chat.

![chat-full-screen](https://cloud.githubusercontent.com/assets/5689/12684696/e6bf91e4-c685-11e5-8a9a-9a3c3f43a093.png)

**Comment by pichalite** [comment]
@jeffbski it's better to post theme related issues on the persona theme's github page

https://github.com/NodeBB/nodebb-theme-persona

regarding full screen chat; it's not broken... persona is only setup to have chat on a modal window on small and xs (extra small -- mobile) screens. Clicking on the full screen icon only displays your recent chats list. You can't use full screen chat on these screen sizes.

**Comment by jeffbski** [comment]
Thanks @pichalite I can post the issue on the persona site, but I guess originally I wasn't sure that it was a theme issue. 

I guess if persona doesn't support full screen at certain sizes then it probably shouldn't show the full-screen icon at those sizes so people wouldn't try clicking it, maybe hidden via media-query.

I'll create some issues on persona and then can link to and close this one here.

**Comment by pichalite** [comment]
I agree that the icon needs to be different

**Comment by jeffbski** [comment]
Moved this issue to the Persona issues list

https://github.com/NodeBB/nodebb-theme-persona/issues/228
https://github.com/NodeBB/nodebb-theme-persona/issues/229
