### ISSUE TITLE
[Question] Is it possible at all to change the login buttons path, in the top right.

### ISSUE THREAD

**Issue by Gacnt** [NodeBB/NodeBB#4130]
I'm using `nodebb-plugin-session-sharing` so I can login on my main site and then use that login on the forums, and it works fantastically. I've disabled registration so the registration button is gone from the header because I want people to register through my site and be able to use the forums instead of registering in both places.

But my question is, since this is all setup and working fine and logins work, can I change the default `login` path to point to my sites login instead of trying to go the the NodeBB login page? I went through all the setting and tried googling, but to no avail.

Thanks.

**Comment by barisusakli** [comment]
Change it in your theme, if you are using persona edit https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/partials/menu.tpl#L115
