### ISSUE TITLE
Editing previous Chat text does not get updated fully

### ISSUE THREAD

**Issue by wrapperband** [NodeBB/NodeBB#4131]
**NodeBB 0.9.3**
Problem : In the chat module, when editing a previous line of text, then send, the change is not reflected on screen.   
If you re-edit the line of text, you see (the database?) or the edited version is still retained
restarting the chat box and the updated text is shown

NodeBB/public/src/modules/chat.js

*Possibly last relevant  change in this chat.js code* :   https://github.com/NodeBB/NodeBB/commit/3d79e0750b417b835681a3331abdb46e8d99932e

*This appears to be the "function" handling editing a previous chat line* chat.js on line 267
chatModal.find('[component="chat/messages"]')
					.on('click', '[data-action="edit"]', function() {

*This is the last change/ issue I can see, that has potential to cause a bug in this area of code*
send messages  :   https://github.com/NodeBB/NodeBB/commit/d8810ceae90c050eb9770a3e0d5eeff90cac362

**Comment by pichalite** [comment]
what git revision are you on?

`git rev-parse HEAD`

**Comment by wrapperband** [comment]
I don't have admin access to that level of the server. I'm reporting the issue to save the Op time. I'll find out and update this post.

**Comment by wellenreiter01** [comment]
Answering for wrapperband:

_what git revision are you on?_

cf5decf5de6f3b1e0690d2c4deab1565c21989ef

_npm ls nodebb-theme-persona_

nodebb-theme-persona@4.0.45

**Comment by pichalite** [comment]
I asked for the git revision and persona version coz the code pointed in the first post is not part of NodeBB v0.9.3

**Comment by wrapperband** [comment]
I was just pointing to NodeBB/public/src/modules/chat.js    

From the test message in the box : 
"Type chat message here, press enter to send"

It was the closest code I could find, as I might have been able to push a fix if it was an obvious screen update missing.

Where is the chat box code then?

**Comment by pichalite** [comment]
the file you pointed is the correct one but the commit you referenced is not part of NodeBB v0.9.3. That commit was made as part of group chat changes.

Anyway, I can confirm that this is an issue on master too but only happens on the modal window. expanded chat seems to be fine.

**Comment by wrapperband** [comment]
Interesting to see what it turns out to be : thanks...
