### ISSUE TITLE
Unable to access registration queue v0.9.3

### ISSUE THREAD

**Issue by jscheepers** [NodeBB/NodeBB#4133]
I recently upgraded to NodeBB v0.9.3 and while everything appears to be working as expected, we are unable to access the registration queue in the admin panel to approve new registrations.

The only output I receive is from nginx:
2016/02/01 10:32:14 [error] 395#0: *18 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: example.forum.org, request: "GET /api/admin/manage/registration?_=1454314598644 HTTP/1.1", upstream:  http://x.x.x.x:4567/api/admin/manage/registration?_=1454314598644", host: "example.forum.org", referrer: "https://example.forum.org/admin/manage/registration"

And my browser ends up with a '504 Gateway Time-out'.

I decided to post this as a bug report as all google searches return issues with socket.io, however _everything_ else on the forum is functioning as expected, just not the registration queue. I am also not able to find any other logs or output regarding this. Nodebb logs return nothing relevant.

**Comment by barisusakli** [comment]
So there is nothing in logs/output.log?
Can you post your git hash?

**Comment by jscheepers** [comment]
Git hash: cf5decf5de6f3b1e0690d2c4deab1565c21989ef

I ended up installing a new version of nodebb and linking the database to it and all started working as normal. 

To answer your question, there was no log output regarding the accessing of the registration queue.
