### ISSUE TITLE
Glitched category?

### ISSUE THREAD

**Issue by Incognitov** [NodeBB/NodeBB#4134]
On our forums we seem to have a category which is completely irremovable and we have tried everything that we can to remove it.

![](http://i.imgur.com/EATSj6e.png)

As you can see there is a category in the middle which seems to be faded out, and it is not available in the admin panel either to be managed. We have literally tried everything we can to remove it but got no results. The category seems to be a category we had, but subsequently we disabled then deleted it, and what is shown above is what we got.

**Comment by pichalite** [comment]
try the solution mentioned here https://github.com/NodeBB/NodeBB/issues/3797

**Comment by ProjectInfinity** [comment]
@pichalite How would one do that if we use Redis as opposed to MongoDB?

**Comment by barisusakli** [comment]
use `zrange cid:0:children 0 -1` then remove the ones that are invalid by `zrem cid:0:children <id_of_category>`.

Feel free to ask on our forums if you can't figure it out.
