### ISSUE TITLE
Opening composer sends to parent page

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#4135]
Important bug on mobile
Opening composer on a category on mobile will send back to home

**Comment by julianlam** [comment]
Hm, this bug is still open on master?

**Comment by julianlam** [comment]
Ah, yes, yes it is.

**Comment by julianlam** [comment]
@barisusakli fixed it in nodebb/nodebb-plugin-composer-default@c5f601c989264bac66b5be7db660b7dba1e124dc but didn't publish.

v3.0.2
