### ISSUE TITLE
Viewport shifting on page load

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4136]
All pages are flickering and moving after loading on ios
Tested with the community forum
Probably some sidebar issue

**Comment by psychobunny** [comment]
Do you know when this started? Haven't touched the sidebar in a long time, might be something else?

**Comment by pichalite** [comment]
@psychobunny I think I know what he means. After the page load is complete, the page either scrolls a bit up or whatever it does to hide the top navbar. It's not smooth and looks weird.

**Comment by barisusakli** [comment]
Could it be https://github.com/NodeBB/NodeBB/blob/master/public/src/app.js#L219 ?

**Comment by martyalicante** [comment]
Around 3weeks maybe? 1 month max
I can make a video but didnt hace the time
What pichalite says is correct

**Comment by psychobunny** [comment]
Then I don't think it's what baris posted because that was there for a long time now

**Comment by barisusakli** [comment]
Is this only happening on ios+safari? Is chrome fine?

**Comment by pichalite** [comment]
happens on ios+chrome too

**Comment by exomarty** [comment]
Solved for me on ios

**Comment by julianlam** [comment]
Thanks @exomarty, glad the viewport shifting fixes have been resolved.
