### ISSUE TITLE
new tabbed ACP, first page change fails 

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#4138]
I think since 0.9.3, this issue has appeared in ACP.

Scenario:
Going to ACP in a new tab.
Go to any ACP page.

It will fail unless F5
Going fine when same tabbed ACP.

Tell me wich part to check to post debugs.

**Comment by julianlam** [comment]
Hey there, can't seem to reproduce this. On master, the ACP responds fine. Do you see any errors in client-side web inspector when you run in dev mode?

**Comment by tedr56** [comment]
That's a strange thing.
I last updated to b1d6d81.
I've launched NodeBB in dev mode.

I've the same behaviour describe as above.
Unless!
I open the mozilla debug console.
Then first page change works.

However in nodebb dev debug I have this.
```
2/2 18:00 [23715] - warn: [plugins] Expected method for hook 'filter:admin.header.build' in plugin 'nodebb-plugin-youtube-lite' not found, skipping.
2/2 18:00 [23715] - warn: Route requested but not found: /csrf.js
2/2 18:00 [23715] - warn: Route requested but not found: /translator.js
```
I assume this must be plugin related.

I forgot to mention.
After F5, the page appearing is the last requested one.
And after that, all pages are normally accessible.
But then, only this appears in dev debug
```
2/2 18:04 [23715] - warn: [plugins] Expected method for hook 'filter:admin.header.build' in plugin 'nodebb-plugin-youtube-lite' not found, skipping
```

**Comment by psychobunny** [comment]
I can't reproduce this either, maybe remove plugins one at a time and see if that's what's causing it?

**Comment by tedr56** [comment]
I just upgraded to e9c488d but I still have the same behaviour, even with another computer (both on Firefox).
The only error I get is this on start
```
24/2 15:17 [4819] - error: ENOENT: no such file or directory, open '/home/tchernobob/NodeBB-Logs'
```
This happens because I restored my nodebb on another user account and obviously the path is wrong.
I don't know if this can be related.

Btw, I haven't found how to change this back to a correct path.

And I also have a bunch of these
```
info: Imgbed: cache miss
```
https://gist.github.com/tedr56/130f33e9f2848b1a480a

**Comment by julianlam** [comment]
Hm... to my knowledge, NodeBB doesn't store path information, so you can relocate the folder anywhere you want, and it should work... I can't say the same for any dependencies, so have you tried `npm rebuild`, or even just a nuke of the `node_modules/` folder and `npm install` again?

**Comment by tedr56** [comment]
I'll try that

**Comment by tedr56** [comment]
I just `rm -r node_modules/` `./nodebb reset -p` `npm install`.
But unfortunatly, even with no plugins, I have the same behaviour.
(And still the logs error)
I agree this is very weird.

**Comment by nhlpl** [comment]
`npm cache clean` helps?

It's a file/folder permission problem. You can use your datastore imported from a backup with a freshly installed NodeBB. An easy way to find an issue. I mean install it somewhere else (localhost, cloud) and see if you can reproduce it using your cloned datastore.
