### ISSUE TITLE
New tab when exiting ACP

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#4139]
From the top acp menu,
going back to the forum open a new tab.

I've been avoiding to use it by opening ACP in a new tab.
And closing ACP tab, to return to forum.
But now the #4138 appeared.

I think there is a ui design flaw here.
With a same tab opening, the user can still open forum in new tab with middle click or context menu.

**Comment by julianlam** [comment]
You know... this has always bothered me.

**Comment by tedr56** [comment]
Glad to hear it. :)

Le ven. 5 févr. 2016 à 16:16, Julian Lam <notifications@github.com> a
écrit :
