### ISSUE TITLE
topic title escape bug in composer

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#4141]
https://community.nodebb.org/topic/7823/discussion-nodebb-plugins-themes-section

Click reply title shows up as `Replying to "Discussion: NodeBB Plugins&#x2F;Themes section"`

**Comment by pichalite** [comment]
happening in notifications too

<img width="308" alt="screen shot 2016-02-03 at 9 25 29 pm" src="https://cloud.githubusercontent.com/assets/10014774/12806664/cf1c33a4-cabc-11e5-8138-cfee90cad871.png">

**Comment by barisusakli** [comment]
Could be related to the recent translator changes.

**Comment by pichalite** [comment]
@barisusakli  Is this fixed? I am seeing the issue on the community

![image](https://cloud.githubusercontent.com/assets/10014774/13360352/a95ab0ce-dc6d-11e5-9e0b-21076e585407.png)

**Comment by barisusakli** [comment]
Looks good to me on chrome 

![image](https://cloud.githubusercontent.com/assets/2583394/13363707/82f856b4-dcd3-11e5-825b-f9babfe48700.png)

**Comment by pichalite** [comment]
Hmm the screenshot was taken on chrome too. Doesn't happen now, not sure what happened that time.

**Comment by nhlpl** [comment]
It was wrong for about an hour. Some other topics too.
