### ISSUE TITLE
Increase number of notifications

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#4144]
Any reason to cap it at 20?
i usually have 40-50 notifications a day

maybe a good number could be 99+ instead of 20+
possible enhance
thanks

**Comment by psychobunny** [comment]
Solution: check notifs more often :D

I think we chose 20 because it seems to be the standard? Like Facebook I believe 

Maybe can be configured in ACP

**Comment by martyalicante** [comment]
I do several times a day :sob:  

![captura de pantalla 2016-02-03 a las 23 00 30](https://cloud.githubusercontent.com/assets/10746278/12798484/fb163dda-cac9-11e5-99c1-3ef0d7695553.png)

facebook is 99 btw

**Comment by psychobunny** [comment]
It might have been 20 in the past, that's where we were taking some design inspiration from. 99 seems okay, I'll make the change unless @barisusakli @julianlam have some reason against

**Comment by julianlam** [comment]
No objections, `99+` will work as any more and it'll be three digits (which then again, `20+` is three digits, so...)

**Comment by barisusakli** [comment]
Should up the unread counter to 99+ as well then.

**Comment by psychobunny** [comment]
![](http://i.imgur.com/NsFTE0p.png)

fwiw. switching to 99 anyways and let's see if anybody person complains :trollface:

**Comment by martyalicante** [comment]
did you tried to restart your Facebook? :dancer: 

![captura de pantalla 2016-02-09 a las 1 43 44](https://cloud.githubusercontent.com/assets/10746278/12904290/b3679e12-cece-11e5-9f5f-1112951d2cb5.png)
