### ISSUE TITLE
Incorrect path to category images

### ISSUE THREAD

**Issue by welchr** [NodeBB/NodeBB#4156]
I'm having an issue where category images aren't appearing - the paths seem to be incorrect. 

I'm on the master branch at commit cc3175a.

My category image URLs look like this: 

```
<div class="icon pull-left" style="background-color: #AB4642; color: #fff; background-image: url(/uploads/category/category-9.png); background-size: cover;"></div>
```

My forum config uses this: 

```
    "url": "http://www.mysite.net/forums",
    "use_port": false,
    "port": "4567",
    "bind_address": "127.0.0.1",
```

So /forums isn't getting put in front of the background-image URL path like it should be. This doesn't appear to be the case with other URLs, like the profile image: 

```
<img component="header/userpicture" src="/forums/uploads/profile/2-profileimg.jpg" alt="User name">
```

Any ideas?

**Comment by julianlam** [comment]
Hm, you probably need to re-upload your category images. They may have been uploaded when you didn't have the subfolder in `url`.

**Comment by julianlam** [comment]
... and yes, while it'd be better to automatically use the subfolder if present, I can't think of a way to make this change without breaking category images in all current subfolder installs...

**Comment by welchr** [comment]
I thought I had tried that, but maybe the page was cached? In any case, that worked - many thanks!
