### ISSUE TITLE
Hook Request :: controllers/authentication :: filter:register.beforeLogin

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#4157]
### Use Case
Make it possible to prevent automatic login after successful registration. This would help me prevent spam bots from being able to post in our forum (since we're not using local login and instead use SSO only). Though now it just occurred to me that the fact they are logged in automatically when local login is disabled is probably a bug :question:

**Comment by julianlam** [comment]
> Though now it just occurred to me that the fact they are logged in automatically when local login is disabled is probably a bug

Disabling local login just means the username/password form is hidden and not processed. Users can still log in via SSO :smile:

**Comment by julianlam** [comment]
Also I believe login is conducted by the SSO plugin, so perhaps that needs to be updated instead of core, e.g. https://github.com/julianlam/nodebb-plugin-sso-facebook/blob/master/library.js#L81-L86

Make that something like

```
async.waterfall([
	async.apply(Facebook.login, profile.id, profile.displayName, email, 'https://graph.facebook.com/' + profile.id + '/picture?type=large', accessToken, refreshToken, profile),
	async.apply(Facebook.filterSpamUsers)
], callback);
```

And in `filterSpamUsers`, execute `callback(new Error('spam-user'));` or something to reject the SSO login attempt.

**Comment by julianlam** [comment]
I don't think we can add it to core because the actual logging in is handled by the call to `passport.authenticate()`, which is outside of NodeBB. :frowning:

**Comment by lots0logs** [comment]
@julianlam I'm using a custom SSO plugin that I wrote to integrate with [Auth0](http://auth0.com). No other SSO plugins are enabled so everything goes through Auth0 (except registrations but thats a long story in of itself lol) When I looked at the code in core it is specifically calling a function `registerAndLoginUser` (or something to that effect). My thinking was that I could just return an error before the actual call to `login` is made if there were a filter at that point. So, what do you think? Would that not do what I am trying to do?

**Comment by lots0logs** [comment]
@julianlam @barisusakli @psychobunny ?

**Comment by lots0logs** [comment]
Hey @julianlam, do you have a sec to look back at my last response and tell me what you think? Now that this issue is closed I know chances are slim that I will be able to get your attention :disappointed: I was going to try and send you a PM on community.nodebb.org but the google sso is disabled again so I cant access my account :grimacing:

**Comment by lots0logs** [comment]
@psychobunny 
![xl6zty3n](https://cloud.githubusercontent.com/assets/4675662/12909236/a4f30d58-cec4-11e5-9f1a-610dee2736e6.jpeg)

**Comment by psychobunny** [comment]
Great. Look at what you've done, now this is going to be assigned to me :p

(This is Julian territory, hope he bails me out)

**Comment by lots0logs** [comment]
Nah, @julianlam wouldn't do that to you...would he? :laughing:

**Comment by lots0logs** [comment]
Pssst... @julianlam :bowtie:

**Comment by julianlam** [comment]
Ah, here it is. Thanks! Will look into it after lunch. pinky swear.

**Comment by pichalite** [comment]
lol

**Comment by lots0logs** [comment]
:laughing: cool, thanks man.

**Comment by julianlam** [comment]
> `registerAndLoginUser`

Can do, but again, `registerAndLoginUser()` is not called on SSO registration/login, so this hook wouldn't even fire when a spammy user registers using your custom SSO plugin... unless you're somehow calling the registration controller from your plugin?

**Comment by lots0logs** [comment]
Well, actually I have nodebb handling registrations and then the accounts get automatically copied over to auth0 when the user signs in for the first time. I'm doing it like that for the time being because I have nodebb behind Cloudflare protection (from spam bots) and there isnt currently a way I can do that with auth0. We were getting hammered by spam when I first tried to let auth0 handle registration and logins :unamused:

**Comment by julianlam** [comment]
Hook into `filter:register.check`, and set `res.locals.processLogin` to `false` :smile:

**Comment by lots0logs** [comment]
Thanks. I owe you one! :beers:

**Comment by lots0logs** [comment]
@julianlam It doesn't work :expressionless: Here's what I have in the plugin:
```
"hooks": [
		{ "hook": "static:app.load", "method": "init" },
		{ "hook": "filter:auth.init", "method": "getStrategy" },
		{ "hook": "filter:auth.list", "method": "getAssociation" },
		{ "hook": "filter:admin.header.build", "method": "addMenuItem" },
		{ "hook": "filter:user.delete", "method": "deleteUserData" },
		{"hook": "filter:register.check", "method": "noLoginAfterRegister"}
	]
```
```javascript
Auth0.noLoginAfterRegister = function(params, callback) {
		params.res.locals.processLogin = false;
		callback(null, params);
	};
```
I also tried this...
```javascript
Auth0.noLoginAfterRegister = function(params, callback) {
		params.res.locals.processLogin = false;
		setTimeout(function() {
			callback(null, params);
		}, 1500);
	};
```

**Comment by julianlam** [comment]
Odd... can you `console.log(params.res.locals);` in your hook? Is `processLogin` there? It should be true to start off.
