### ISSUE TITLE
Animated Cover Photo

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4164]
Here you can see many animated images used as a cover photo.
https://community.nodebb.org/user/xen

NodeBB > Profile
Upload picture
You may only upload **PNG, JPG, or BMP** files

At this moment you can upload very large **animated GIF** (445 KB, 500x500px).
https://community.nodebb.org/user/nhl-pl

**Comment by julianlam** [comment]
Thanks @nhlpl as always :smile:
