### ISSUE TITLE
Include hidden users on guest count

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4166]
possible enhancement
Not sure if this is already done
Users tend to hide his online status, but if all people is hidden is seems like no one is browsing the forum. could add hidden people to guest count or  just put some global connected indicator on users online page 

https://community.nodebb.org/users/online

**Comment by julianlam** [comment]
This is a good idea :smile:

**Comment by pichalite** [comment]
admins and global mods can see hidden users too on the /users/online route

this probably counts hidden users twice for them or no?

**Comment by pichalite** [comment]
by counting twice I mean, they show up on the online list and are also counted as guests

**Comment by barisusakli** [comment]
If the user is admin or global mod `hiddenCount` will be 0

**Comment by pichalite** [comment]
damn it... that's what happens when you only see the lines changed. :disappointed:  Thank you Baris.
