### ISSUE TITLE
[Question] Is it possible to add a custom nav button to navigate to a different part of the site

### ISSUE THREAD

**Issue by Gacnt** [NodeBB/NodeBB#4167]
When I try to add a new button I end up with the button always going from `/forums/>` I would like to be able to make it go to the home page `/` but no matter what I get the `/forums` prefix I'm guessing because of the config, how might I fix this?

**Comment by julianlam** [comment]
I'm assuming this is because you are on a subfolder config? 

Have you tried putting in an absolute url?

**Comment by Gacnt** [comment]
@julianlam Yes I am on a subfolder config, and after putting in an absolute url like `http://google.ca' I get http://site.com/forums/http://google.ca
