### ISSUE TITLE
[Question] Is it possible to give post specific privileges?

### ISSUE THREAD

**Issue by Gacnt** [NodeBB/NodeBB#4168]
I have a section in my forum where I would like only a certain group to be able to read / comment on posts.

But I want registered-users to be able to post in there, but not be able to read the posts.

I set the privilege to Access & Read to unchecked, and Create Topics to checked but when a registered-user goes in to the section, they dont get a create post button and something about no permissions. Any idea how I can achieve this?

**Comment by Gacnt** [comment]
Basically I'm wondering if it's possible to make a section, where a person can only see the topics they've created, but people with higher privileges in that section can see everybodys topics.

I wanted to make a section for applications and make it so applicants could only see their own posts, so they could comment on their own posts and talk to the admins, but don't want them to see other peoples.

But I want the admins to be able to see and be able to comment on all posts. Is this possible to do in the current state?

**Comment by pichalite** [comment]
Basically you need to make a category like a support forum. It's not possible to achieve this by just modifying the permissions. You will need a plugin to achieve this.

**Comment by julianlam** [comment]
There is the [support forum plugin](https://github.com/julianlam/nodebb-plugin-support-forum), though I don't believe it is compatible with the latest version. You can install it manually and give it a shot.

**Comment by julianlam** [comment]
Otherwise, yes, it'd be something you'd have to do via a plugin.
