### ISSUE TITLE
Favicon wrong Count

### ISSUE THREAD

**Issue by AndiKnight** [NodeBB/NodeBB#4169]
![image](https://cloud.githubusercontent.com/assets/14957191/12929117/639633fa-cf71-11e5-8283-bbf9e9e5c25e.png)

After reading notifications this -1 appears instead of nothing

**Comment by psychobunny** [comment]
Can you reproduce this often, or a one-time bug?

**Comment by AndiKnight** [comment]
This was the 6th time in 2 weeks.

**Comment by AndiKnight** [comment]
And again 
![image](https://cloud.githubusercontent.com/assets/14957191/12934534/92ff3876-cf8f-11e5-85f8-2655f9abbae7.png)

**Comment by barisusakli** [comment]
What is your git hash&browser?

**Comment by AndiKnight** [comment]
root@sondorsforum:~/nodebb# git rev-parse HEAD
34a725c9da4a2d53428699f0302abe6d24b12326
 
-
Chrome 48.0.2564.103 m
