### ISSUE TITLE
Guidelines that pertain to scale?

### ISSUE THREAD

**Issue by faddat** [NodeBB/NodeBB#4172]
Hi guys, do you have any hardware capacity guidelines for scale?  I am running on Scaleway and I'm not even sure.... for example-- how many simultaneous users a single scaleway can support.  

Thanks for any info!

**Comment by julianlam** [comment]
Hi there -- we are not familiar with Scaleway, so we cannot say. At this time, the latest version of NodeBB (v0.9.3+, actually) can easily support up to 7k views per hour (which is *roughly* 2 requests/sec). Tweaking your server can increase this number further, though we typically combine this with a load balancer for better reliability :smile:

**Comment by faddat** [comment]
I'd love to make you familiar with scaleway, they are a host based in Paris that rents ARM boards, so scaleway is rather different from most hosting providers in a few ways-- their hosting costs three euros a month, and you have an ARM cpu.  They're actually faster than many VMs but aren't toooo speedy, and come with 2gb of RAM.  If you want to try it out, hit me up on hangouts: faddat@gmail.com I'll gladly provision one for you to mess with.  

Also I'd love to talk with you about the Dockerfile situation.  

Also also I'd like to talk with you about your plans for the future of NodeBB.  Some folks are asking me if I can extend it, and I'd like to extend it in ways that enhance the mainline and benefit the community, so I'm hoping that it is something that we can collaborate on.  There are some thorny design issues that the client doesn't know are thorny buried in the request, and I'd love your take on them.  

Thanks!

-Jake
