### ISSUE TITLE
Delete user without delete his posts

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/NodeBB#4176]
Sometimes you may have to delete an user but that will remove all his posts and threads, including other people posts.
There a big change other people posted great content on that user thread and is not nice to delete it.

Possible options:
1- delete user and set all his post like guest user
2- delete all his post but dont delete threads, just delete first post of the thread
3- delete user without delete his posts

thank you for reading

**Comment by psychobunny** [comment]
I feel like deleting users should only be used for spammers/bots, while banning is more appropriate for the use case above (when the poster has created topics that brought a good level of discussion but is no longer welcome on your board)

Open to debate though, is there a use case that I didn't think of?

**Comment by martyalicante** [comment]
Some people ask for account delete eventually or if you have the toogle of account delete active they can do it theirself and delete other people content. Dont need to be a troll or banned people.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/2832
