### ISSUE TITLE
Merge translations

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#4178]
If two plugins provide translation-files named the same the one loaded later overwrites those from the first plugin.
In my example I'd like multiple plugins to define translations for `[[emojiCategories:...]]`.
Thus the translations would need to get merged.

I also think this could prevent some "weird" plugin-incompatibilities if two plugins just choose the same key-name.

**Comment by julianlam** [comment]
Yes, I agree that we should merge them. In the case of key conflicts, the order of plugins will be observed -- plugins loaded *after* others will overwrite existing keys.
