### ISSUE TITLE
add this repository as an automated build on the Docker Hub

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4184]
Suggested settings:

    [X] When active, builds will happen automatically on pushes.
    
    Type      Name              Dockerfile Location    Docker Tag Name
    Branch    master            /                      latest
    Branch    /^v[0-9.]+.x$/    /                      (leave blank)
    Tag       /^v[0-9.]+/       /                      (leave blank)
    
    node [Add Repository Link]

Docker Hub will automatically build new versions of NodeBB. No further maintenance will be required. I can update the install documentation if this sounds ok.

**Comment by nhlpl** [comment]
Some Docker related discussion took place here:
https://github.com/NodeBB/NodeBB/pull/4114
and earlier
https://github.com/NodeBB/NodeBB/pull/3160

You can submit your own pull request to update NodeBB documentation.
https://github.com/NodeBB/nodebb-english/pulls

**Comment by psychobunny** [comment]
@BenLubar were you planning on doing this? No qualms here, we don't use docker for development so go for whatever works best

**Comment by BenLubar** [comment]
@psychobunny it would have to be whoever has control of the "nodebb" account on Docker Hub.

https://hub.docker.com/u/nodebb/

**Comment by psychobunny** [comment]
Well then. Neither I nor @julianlam know who actually owns that account. Probably some third party developer active on our community?

I'm going to close this issue then (sorry for the aggressive close, I just want to get this tracker focused on actual bugs. feel free to re-open this discussion on our community though)
