### ISSUE TITLE
cannot upload profile image

### ISSUE THREAD

**Issue by kiochan** [NodeBB/NodeBB#4186]
Hello,
I'm running NodeBB v0.9.3. on ubuntu 14

I have a problem with uploading of image.
When I'm uploading the image for the profile,
it will show me "error uploading, code : 0"

The follow logs are here:
15/2 08:06 [15188] - info: NodeBB Ready
15/2 08:06 [15188] - info: Enabling 'trust proxy'
15/2 08:06 [15188] - info: NodeBB is now listening on: 0.0.0.0:29131
15/2 08:06 [15188] - info: [plugins/spam-be-gone] Settings loaded
15/2 08:10 [15188] - error: TypeError: path must be a string
at TypeError (native)
at Object.fs.unlink (fs.js:975:11)
at /home/studioasc/chat/src/user/picture.js:210:15
at /home/studioasc/chat/node_modules/async/lib/async.js:52:16
at /home/studioasc/chat/node_modules/async/lib/async.js:696:30
at /home/studioasc/chat/node_modules/async/lib/async.js:167:37
at Immediate._onImmediate (/home/studioasc/chat/node_modules/async/lib/async.js:1206:34)
at processImmediate [as _immediateCallback] (timers.js:383:17)
TypeError: path must be a string
at TypeError (native)
at Object.fs.unlink (fs.js:975:11)
at /home/studioasc/chat/src/user/picture.js:210:15
at /home/studioasc/chat/node_modules/async/lib/async.js:52:16
at /home/studioasc/chat/node_modules/async/lib/async.js:696:30
at /home/studioasc/chat/node_modules/async/lib/async.js:167:37
at Immediate._onImmediate (/home/studioasc/chat/node_modules/async/lib/async.js:1206:34)
at processImmediate [as _immediateCallback] (timers.js:383:17)
15/2 08:10 [15188] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
15/2 08:10 [15188] - info: [app] Database connection closed.
15/2 08:10 [15188] - info: [app] Web server closed to connections.
15/2 08:10 [15188] - info: [app] Shutdown complete.
[cluster] Child Process (15188) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
15/2 08:10 [15252] - info: Time: Mon Feb 15 2016 08:10:55 GMT+0900 (JST)
15/2 08:10 [15252] - info: Initializing NodeBB v0.9.3
15/2 08:10 [15252] - warn: You have no mongo password setup!
15/2 08:10 [15252] - info: [database] Checking database indices.
15/2 08:10 [15252] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.

15/2 08:10 [15252] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p PLUGINNAME to disable it.

nodebb-plugin-markdown
nodebb-plugin-emoji-extended
nodebb-plugin-composer-default
How can i fix this?

**Comment by iDevPro** [comment]
Me too :(

**Comment by iDevPro** [comment]
Fix here:
```
function(next) {
                                file.isFileTypeAllowed(data.file.path, next);
                        },
```
