### ISSUE TITLE
Template Engine issue

### ISSUE THREAD

**Issue by iDevPro** [NodeBB/NodeBB#4190]
Have NodeBB from GIT

In file public/templates/topic.tpl:                        
`[[global:posted_ago, <a class="permalink" href="{config.relative_path}/topic/{slug}/{function.getBookmarkFromIndex}"><span class="timeago" title="{posts.relativeTime}"></span></a>]]`

But in browser i see: 
`написал <a class="permalink" href="/forum/topic/2/военная-техника-времен-второй-мировой-войны/1"><span class="timeago" title="2016-02-16T09:40:04.352Z"></span></a> `

Why template not return HTML ?

**Comment by pichalite** [comment]
You are using the master branch of NodeBB and a version of the theme that's not compatible with the master branch. There was a change on master branch to not send in html in language key params.

Update the theme to the version compatible with the master branch.

**Comment by julianlam** [comment]
Thanks @pichalite :smile:
