### ISSUE TITLE
Error write EPIPE when trying to approve user in registration queue

### ISSUE THREAD

**Issue by ds-terrytate** [NodeBB/NodeBB#4193]
Whenever I try to click the check mark for a user on the registration queue, I get a little error popup in the lower left that says "Error write EPIPE".

After that, if I try to approve the user again, it simply says "Error email taken". However, the user seems to actually be created successfully, and I can assign them to groups, etc. The email that would normally be sent to the user that their registration was successful won't be sent, though.

I'm not seeing anything in the server log about this error, unfortunately. Seems like a redis error but the redis logs also show nothing that is helpful (maybe the verbosity level isn't high enough.) If I can provide any other helpful information please let me know.

I'm at commit 0516418 on the master branch. 

In any case, many thanks for these awesome forums. They are really great!

**Comment by barisusakli** [comment]
If the user is created but still visible in the registration queue, then it seems to be failing at the email sending step [here](https://github.com/NodeBB/NodeBB/blob/master/src/user/approval.js#L89), are you using a email plugin or the local emailer? Is test emails working from the ACP?

**Comment by ds-terrytate** [comment]
I think that's on the right track. I tried sending the test email (I'm routing through a Gmail account), and now I get a pop-up in the lower left saying: 

```
Unsupported configuration, downgrade Nodemailer to v0.7.1 to use it
```

It looks like somehow I have nodemailer 2.0 installed (not sure if nodebb upgrade did that, or I did it by mistake): 

```
nodebb@0.9.3 /home/nodebb/nodebb
└── nodemailer@2.0.0
```

**Comment by ds-terrytate** [comment]
I think the problem is that the code in src/emailer.js that is trying to do SMTP transport is using syntax for the old nodemailer (0.7), and the code for the sendmail transport is using the nodemailer 2.0 syntax. 

I patched src/emailer.js to require: 

```
    sendmailTransport = require('nodemailer-sendmail-transport'),
```

And then modified the gmail part to be: 

```
    // Enable Gmail transport if enabled in ACP
    if (parseInt(meta.config['email:GmailTransport:enabled'], 10) === 1) {
      fallbackTransport = transports.gmail = nodemailer.createTransport(smtpTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        auth: {
          user: meta.config['email:GmailTransport:user'],
          pass: meta.config['email:GmailTransport:pass']
        }
      }));
    } else {
      fallbackTransport = transports.sendmail;
    }
```

And now it works and I can receive the test email. The small syntax change is just constructing the smtpTransport() object, rather than specifying it as a string 'SMTP' in the createTransport call.

**Comment by julianlam** [comment]
Any chance you can make that a pull request? :wink:

**Comment by ds-terrytate** [comment]
I tried. :) My first pull request. Please let me know if I've missed anything.
