### ISSUE TITLE
AWS and Dynamodb

### ISSUE THREAD

**Issue by ifuyivara** [NodeBB/NodeBB#4196]
What would it take to make NodeBB work with Dynamodb? Where do I start to make that happen? Should I just add it to the /src/database folder and use the redis one as a guide?

**Comment by psychobunny** [comment]
The mongo adapter was based on redis, so you can use that as a guide on how to manipulate data in order for it to output in the way redis would.

If you make a post on our [community](https://community.nodebb.org/), maybe somebody else who has experience with Dynamodb might also join your project. Or post there if you run into any issues setting up the adapter. Good luck!

**Comment by liesislukas** [comment]
I'm interested in this. Did anyone make any progress? I have experience with dynam, redis, and mongo, yet totally new to nodebb.
