### ISSUE TITLE
Clearing chat history

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4199]
https://community.nodebb.org/chats

Use "Enter username to search" to add at least 2 new recipients to the chat history.
one starting with the letter A
one starting with the letter B
one starting with the letter C
Delete usernames beginning with A, B, C using "x" button.

Repeat it (add and remove).

Sometimes **two clicks on "x"** (and not just one click) are necessary to remove a conversation.

**Comment by pichalite** [comment]
can't reproduce this

**Comment by nhlpl** [comment]
At this moment it works in a different way (removing archive chats) but can be reproduced. Two or three clicks are needed when no instant delete worked (client side). You can see a refresh going between you and NodeBB after next tries.

I have seen a similar issue when chatting with one of your users. Many messages send by me (Europe) and by second user (India) blocked WebSockets. Too many messages error.

It means a slow connection (3G, mobile) is needed to reproduce.

Thanks for testing it and closing it. It works fine. I'm not a developer and it's hard for me to tell what is important and what is not.
