### ISSUE TITLE
Replying to Test 1, 2, 3 encoding

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4208]
https://community.nodebb.org/topic/7947/test-1-2-3

![testreply](https://cloud.githubusercontent.com/assets/11160550/13174946/5f3246ee-d707-11e5-8e83-8bf00ba085a9.jpg)

**Comment by barisusakli** [comment]
This also broke because the translator escapes html now. Also related https://github.com/NodeBB/NodeBB/issues/1951 and https://github.com/NodeBB/NodeBB/issues/2994

**Comment by julianlam** [comment]
@barisusakli that's odd, since the translator escaping html shouldn't actually do anything to commas...

**Comment by barisusakli** [comment]
It doesn't but commas are turned into `&#44;` in composer [here](https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer.js#L372) and after that the translator turns `&` into `&amp` resulting in `&amp44;`
