### ISSUE TITLE
Ask as Question vs normal topic

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4212]
https://community.nodebb.org

1)
Ask as Question converted to a normal topic still shows SOLVED or UNSOLVED label.

2)
There is no way to mark SOLVED back to UNSOLVED.

3)
Topic Tools > Make this a normal topic should clear SOLVED/UNSOLVED data.

**Comment by pichalite** [comment]
not sure what version of the `nodebb-plugin-question-and-answer` plugin the community is using but the latest version of the plugin does not have any of these issues.

**Comment by barisusakli** [comment]
Community was on version 0.0.14 upgraded to 0.0.16.
