### ISSUE TITLE
Notifications: minor issue on the client side

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4215]
https://community.nodebb.org/notifications

You can get "2" in place of "1" (see below) by using unread radio button near to "started following you | 2h"

![twoinone](https://cloud.githubusercontent.com/assets/11160550/13185946/fb01633e-d743-11e5-8f84-7c878e239841.jpg)

At the current stage it goes to "off" state (see below) after some browsing and clicking on unread message and user profile. Requires many tries to reproduce.

![twoinone2](https://cloud.githubusercontent.com/assets/11160550/13185949/fecaeeae-d743-11e5-8f29-8f4c792054d0.jpg)

After a page refresh it works and counts fine.

**Comment by pichalite** [comment]
I am not able to reproduce this.

**Comment by nhlpl** [comment]
Reproced it again. Have had to click many times on a radio button and wait for it to change its state to off.

Non-issue so it can be closed.
