### ISSUE TITLE
Invisible tags can be found

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4217]
https://community.nodebb.org/tags

1)
As a Guest "s+s" tag can be found using built-in search. Tag was used in deleted topic started in hidden category Testing Ground.

2)
You can open and read your own deleted topics with tags but can't display them using tags (displayed in tags list after using search).

**Comment by pichalite** [comment]
I think the first one should be okay. The fact that the tag is added to a topic in a hidden category doesn't make the tag itself hidden as the same tag can be used for other topic that's not in a hidden category.
