### ISSUE TITLE
New Topic should be invokable anywhere.

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#4223]
Right now, the app.js new topic function is bound to '#content #new_topic', but nothing requires it to be called from there. It should be available as app.newTopic or something similar. Possibly with a default cid parameter, since right now the default is hard-coded as the first available category with privileges.

**Comment by julianlam** [comment]
Sounds like a good thing to add :smile:

**Comment by yariplus** [comment]
Cool, I'll can make a PR then.

**Comment by pichalite** [comment]
`#content #new_topic` is used by the "New Topic" button on the `/recent` page I think

**Comment by yariplus** [comment]
Yeah, I won't change that selector, just move the function out so it can be called anywhere.
