### ISSUE TITLE
Group name in lower case

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4229]
https://community.nodebb.org/groups/administrators

Please change default group name from administrators to Administrators. 
https://github.com/NodeBB/NodeBB/blob/86d70eca746783f35317d0d217a5cd34f34d8fbd/src/privileges/users.js

![lowadmin](https://cloud.githubusercontent.com/assets/11160550/13197636/f4a43876-d7f3-11e5-8c7e-276e9079558c.jpg)

**Comment by nhlpl** [comment]
NodeBB 1.0.1 version, v1.x.x branch

Admin > Manage > Groups > administrators
System Group name cannot be changed

![adm](https://cloud.githubusercontent.com/assets/11160550/13899644/c842d664-edf3-11e5-80cd-9ff1494d5870.jpg)

**Comment by julianlam** [comment]
The "title of members" can be changed to be capitalised, so there's no ill effect from having it lower case.
