### ISSUE TITLE
Banned users profiles

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4231]
https://community.nodebb.org/topic/474/how-to-making-a-custom-nodebb-theme/17
https://community.nodebb.org/user/wbmstr

You can follow a banned user.
You can send a chat message to a banned user.
You can browse all profile categories.

I think banned users should be inactive for non-admin users like me on your forum. Simply treated like Guests or deleted accounts.

It makes sense to leave it as it is for admins and mods.

**Comment by julianlam** [comment]
Thanks @pichalite :smile:
