### ISSUE TITLE
Follow tooltip

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4232]
https://community.nodebb.org/users

Please add tooltip for a follow button in user profile. Similar to those showing username on top of avatar and online/offline indicator.

**Comment by julianlam** [comment]
What would this tool tip say? I feel it's fairly apparent in functionality, plus there is a success alert when clicked...

**Comment by nhlpl** [comment]
Just like here on GitHub it would be helpful to provide "Follow" label.

Not all users are geeks and some communities members do not know how social media sites looks like.

If you like how it is please close this issue. Thanks.

**Comment by psychobunny** [comment]
Seems like even GH doesn't follow that standard 100%, ex. subscribe, watch buttons don't have labels but follow and star does. In any case, going to move this to Persona since it's more of a theme thing
