### ISSUE TITLE
New posts redirected to other topics

### ISSUE THREAD

**Issue by XenTerSeO** [NodeBB/NodeBB#4235]
1. Write a post.
2. Click on timeago.

If you refresh the page - it works correct.

**Comment by nhlpl** [comment]
Clicking on a new reply timestamp here.
https://community.nodebb.org/topic/7950/yen-ask-as-question-pound-cent/2

Redirected to:
https://community.nodebb.org/topic/2/test/1

**Comment by barisusakli** [comment]
Interesting bug :laughing:
