### ISSUE TITLE
Minor chat online/offline indicator

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4238]
https://community.nodebb.org/chats

Issues:

1)
See an image for online/offline indicator tooltip,

![chattooltip](https://cloud.githubusercontent.com/assets/11160550/13203573/d5ad44b2-d8bb-11e5-821a-f6c2d14fd749.jpg)

2)
Online/offline status is not updated in real time (Home / Chats). I have seen one of the admin users for the whole chat session with one of your new users and it was not updated (Do not disturb for admin user). Confirmed it on the Online Users page (offline and not DnD).

**Comment by psychobunny** [comment]
I can't reproduce this (used two users, toggled one offline/online and it updated in real-time for me)

**Comment by nhlpl** [comment]
Thanks for your input. It's time to close the issue.
