### ISSUE TITLE
turkish character issue (link)

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#4240]
ex:

title: Şemsiye açık
link: /1/%C4%B1%C5%emsiye-a%C3%A7al%C4%B1%C5%9F%C4%B1k

It should have been:

title: Şemsiye açık
link:  /1/semsiye-acik

ş - s
ç - c
ğ - g
ı - i

**Comment by nhlpl** [comment]
NodeBB doesn't transliterate URLs (slugs).

Look here:
https://github.com/NodeBB/NodeBB/issues/3097

**Comment by julianlam** [comment]
Thanks @nhlpl -- @pikshub the characters in the slug are preserved as they do not impact NodeBB itself, though when copied and pasted, if the destination does not support unicode (among other factors...), it may also encode the characters.

Perhaps we can make this a toggle-able setting in the slugify method... though it does take additional effort to transliterate the slug.

**Comment by nhlpl** [comment]
One of the most must-have of the must-have features in the NodeBB.

I agree with Nicolas: 
> slugs are really good candidate for core improvement 

https://community.nodebb.org/topic/4162/translit-slug/24

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/3129
