### ISSUE TITLE
Topic followers count

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4242]
A good adition could be to show number of followers on a topic and a list of top followed topics

**Comment by yariplus** [comment]
Like this idea. Also, renaming `watch` to `follow`

**Comment by nhlpl** [comment]
> Also, renaming watch to follow

A small reminder from Area 51. Editable language strings https://github.com/NodeBB/NodeBB/issues/1643 enhancement is planned to be introduced somewhere in the future after release of NodeBB 1.0.0.

**Comment by psychobunny** [comment]
Closing this as not an issue _for core_, but a good idea for sure. Let's continue discussion at https://github.com/NodeBB/nodebb-theme-persona/issues if necessary, and ideally some kind of design input would be best
