### ISSUE TITLE
Chromium-only frontend errors

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#4257]
On latest master and https://community.nodebb.org as well I encounter these errors on client side (all pages):
```
nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17734 Uncaught TypeError: RegExp.prototype.sticky getter called on non-RegExp object(anonymous function)
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17734(anonymous function)
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17750

sounds.js?8a663870-f483-41c1-8994-49d0b98258e4:11 Uncaught TypeError: Cannot read property 'on' of undefined(anonymous function)
 @ sounds.js?8a663870-f483-41c1-8994-49d0b98258e4:11k.execCb
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17448$.check
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17437(anonymous function)
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17442(anonymous function)
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17427(anonymous function)
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17442z
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17426$.emit
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17442$.check
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17438$.enable
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17442$.init
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17436F
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17433k.completeLoad
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17447k.onScriptLoad
 @ nodebb.min.js?8a663870-f483-41c1-8994-49d0b98258e4:17448
```

Chromium 48.0.2564.103

**Comment by barisusakli** [comment]
Only chromium? Works for me on chrome.

**Comment by frissdiegurke** [comment]
just checked with firefox and chrome, does work there without errors.
Browser cache and even cookies/localstorage cleaned. Still happening, so chromium only.
I'm just updating to Chromium 48.0.2564.116, will check back then.

**Comment by frissdiegurke** [comment]
Still there with Chromium 48.0.2564.116.

**Comment by frissdiegurke** [comment]
And since it prevents login/logout it's pretty crucial O-o

**Comment by nhlpl** [comment]
Windows 7, Chrome 48.0.2564.116 
Clear all history, clear all cache, clear all cache
It works fine

Linux only issue?

**Comment by frissdiegurke** [comment]
It seems to first occur somewhere between `chromium-47.0.2526.111-1-x86_64` (latest version within my cache that does **not** show above errors) and `chromium-48.0.2564.82-1-x86_64` (first version within my cache that does show above errors). And I checked a commit state ~1 month before today and it already occurred.

Could somebody please confirm this (Linux x86_64 Chromium `>=48.0.2564.82-1` please)? I somehow can't believe that I did not take any notice of this bug since 16/01/24 (the date I updated between the both versions of chromium mentioned above).
I mean, I'm browsing NodeBB on a near daily basis using the features of the shortcuts plugin which gets broken by the errors... The only other package logs of the last 10 days are `sdl` related (only installs, no updates) and I doubt this has anything to do with it.

I'm confused.

**Comment by frissdiegurke** [comment]
o_O #4118 sorry, seems to be my fault.

> ![home-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/12647775/87ee9942-c59c-11e5-93be-e238957cfb94.gif)

invalid.
