### ISSUE TITLE
disable private option on groups if system level private groups is turned off

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4258]
suggested on the community. may be a good idea?

https://community.nodebb.org/topic/6958/registred-user-can-join-private-groups/12

**Comment by julianlam** [comment]
Hm, yes and no. The danger is that if the global option is ever disabled, then all groups become public, which is deserving of a warning (which I believe one exists).

In any case, if system level private groups are disabled, the option still ought to be changeable, but with a note specifying that it doesn't do anything as private groups are disabled at the system level.

**Comment by pichalite** [comment]
Which ever works better to let the admin know that the system level setting is turned off.

Should be added to client side groups too I think.
