### ISSUE TITLE
Upload modal for fav icon displays the same modal as site logo upload

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4260]
https://community.nodebb.org/topic/7993/receive-error-when-uploading-favicon-image

![image](https://cloud.githubusercontent.com/assets/10014774/13328844/cda0d0b2-dba5-11e5-9a4b-8db4dc4317bc.png)

**Comment by psychobunny** [comment]
https://github.com/NodeBB/NodeBB/issues/4268
