### ISSUE TITLE
Deleted user becomes a Guest

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4261]
https://community.nodebb.org

1) ~~Firefox 44.0.~~2 All browsers, create new account
2) delete new account

![wowerror](https://cloud.githubusercontent.com/assets/11160550/13333112/a6e0f1c2-dc05-11e5-8cef-066cc07acca5.jpg)

**Comment by pichalite** [comment]
weird... works fine on my test install

**Comment by nhlpl** [comment]
Tested it again after recent community forum updates, no email confirmation and disabled Firefox extensions. Successfully reproduced.

**Comment by pichalite** [comment]
yeah I was able to reproduce it on the community... may be an issue with the community

**Comment by barisusakli** [comment]
Does it happen on all browsers? When you f5 are you logged out?

**Comment by nhlpl** [comment]
Refresh doesn't help. All Chromium based browsers too. Chrome, Opera, Opera beta and as earlier tested Firefox.

**Comment by pichalite** [comment]
this issue doesn't seem to be fixed. works fine if you register using the form on /register route. if you use an sso to register then you run into this issue. needs to be reopened.
