### ISSUE TITLE
Minor Email Confirmed page

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4262]
https://community.nodebb.org/confirm/

`<title> | NodeBB</title>`

Please add text to page title i.e. `Email Confirmed | NodeBB`.

**Comment by psychobunny** [comment]
thanks. btw, you can use the label on the right `low priority` instead of prepending "Minor" to your topic title. nothing major really, just helps with filtering issues :)

**Comment by pichalite** [comment]
don't think we are allowed to add labels.

**Comment by psychobunny** [comment]
Oh? Seems legit. Sorry

**Comment by pichalite** [comment]
I would add "High Priority" label to all of them if I have access :trollface:
