### ISSUE TITLE
Mention autocomplete

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4265]
https://community.nodebb.org/recent

1) new topic button,
2) use composer and hit @
3) try to type a part of usernames pasted below.

NGÔ THIÊN TÂN
KHỔNG XUÂN TRUNG
NGÔ

Testuser Ngô cannot be mentioned using autocomplete.

![ngomention](https://cloud.githubusercontent.com/assets/11160550/13334469/57cdb7b2-dc0c-11e5-9e8b-f3436fca43dd.jpg)

**Comment by julianlam** [comment]
Hm, that's a tricky one, since we just limit the autocomplete list so it does not become inundated with choices :smile: 

We seem to have quite a lot of vietnamese users, so I'm not quite sure what to do here...

**Comment by julianlam** [comment]
![selection_103](https://cloud.githubusercontent.com/assets/923011/13335296/6507d346-dbde-11e5-82e2-eb79437ce4d7.png)

Seems to work here to filter through the list, so you'll just need to use the appropriate character, as we do not have any transliteration lib right now.

**Comment by nhlpl** [comment]
I have tried to use arrows with no success.

**Comment by julianlam** [comment]
The thing is we can't just list all of the matches, because that wouldn't be scalable if you had many thousands of users. Simply typing @ng... might cause your browser to try to load thousands into that list, which is frankly a waste of resources when you could just type one more letter and whittle down that list some more...

**Comment by pichalite** [comment]
I agree with @julianlam on this... loading all the possible matches is not good.

**Comment by nhlpl** [comment]
I have not tested it with something longer. Only two letters, my bad.

Thanks for your explanation. As usual happy to read experienced users and developers.
