### ISSUE TITLE
UI issues ACP ->General -> Sounds

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4266]
I think this button needs a different color other than white

![image](https://cloud.githubusercontent.com/assets/10014774/13336166/84da1ba8-dbc9-11e5-9e19-285335d1a9ae.png)

Clicking on "Upload new sound" button displays "Upload picture" modal

![image](https://cloud.githubusercontent.com/assets/10014774/13336196/b238a9e8-dbc9-11e5-9384-218bfb7ad81b.png)

**Comment by psychobunny** [comment]
https://github.com/NodeBB/NodeBB/issues/4268
