### ISSUE TITLE
Refactor upload picture modal 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#4268]
New parameters for:

* Custom title/description/button ("Upload picture", "Upload sound", etc.)
* Custom file requirements ("You may only upload .X, .Y, .Z") - no need to enforce, just accept an array to display. (Assume that server will check)
* Custom callback (see comment + hax in the upload picture modal callback currently)

Related:
https://github.com/NodeBB/NodeBB/issues/4266
https://github.com/NodeBB/NodeBB/issues/4260

**Comment by psychobunny** [comment]
Also, we accept BMP files :troll: what is this, 1995? :P

**Comment by julianlam** [comment]
:trollface: why not, bmp is a simple image encoding, that's why it's supported universally haha

**Comment by psychobunny** [comment]
![](http://gamesdbase.com/Media/SYSTEM/Atari_ST/Snap/big/Magic_Pockets_-_1991_-_Renegade_Software.jpg)

Bitmap Brothers :tm:
