### ISSUE TITLE
Uploading, updating and create new topic not working

### ISSUE THREAD

**Issue by Nisthar** [NodeBB/NodeBB#4269]
Hi, I am hosting my app on openshift free. At first, all things were working. I created a new account and tested the create topic and updating the user details. All worked normal. But after a day, some more members (around 5 members have joined) and now i can't post any new thread. When i do its giving me "You do not have enough privilege to post". When i tried to update my profile details, its giving me empty error boxes.

Is this an error with nodebb?

Sorry for the bad english.

**Comment by nhlpl** [comment]
Seems to be fixed.
https://community.nodebb.org/topic/7990/cant-update-user-profile-getting-error/10
