### ISSUE TITLE
Long password crashes registration form

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4273]
https://community.nodebb.org/register

Extra long password > Register Now
5x times longer password > Register Now

`Registration Error
Error: misconfigured csrf<br> &nbsp; &nbsp;at getsecret (/home/nodebb/community.nodebb.org/node_modules/csurf/index.js:190:11)<br> &nbsp; &nbsp;at Object.csrf [as applyCSRF] (/home/nodebb/community.nodebb.org/node_modules/csurf/index.js:56:18)<br> &nbsp; &nbsp;at Object.middleware.buildHeader (/home/nodebb/community.nodebb.org/src/middleware/header.js:23:14)<br> &nbsp; &nbsp;at /home/nodebb/community.nodebb.org/src/routes/index.js:206:15<br> &nbsp; &nbsp;at Layer.handle_error (/home/nodebb/community.nodebb.org/node_modules/express/lib/router/layer.js:58:5)<br> &nbsp; &nbsp;at trim_prefix (/home/nodebb/community.nodebb.org/node_modules/express/lib/router/index.js:300:13)<br> &nbsp; &nbsp;at /home/nodebb/community.nodebb.org/node_modules/express/lib/router/index.js:270:7<br> &nbsp; &nbsp;at Function.proto.process_params (/home/nodebb/community.nodebb.org/node_modules/express/lib/router/index.js:321:12)<br> &nbsp; &nbsp;at next (/home/nodebb/community.nodebb.org/node_modules/express/lib/router/index.js:261:10)<br> &nbsp; &nbsp;at Layer.handle_error (/home/nodebb/community.nodebb.org/node_modules/express/lib/router/layer.js:54:12)`

![regerror](https://cloud.githubusercontent.com/assets/11160550/13353777/e056873c-dc96-11e5-97ee-b5ef427015ab.jpg)

**Comment by julianlam** [comment]
... certainly did not expect "password too long" to be a bug :laughing:

**Comment by julianlam** [comment]
Can't reproduce, I get a "password too long" error when I use the password

`longpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpasswordlongpassword`

**Comment by nhlpl** [comment]
You have to try twice (try again after password too long) with new Captcha..
