### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#4279]
I upgraded master. Nothing is open. Login do not know. There is an error in the log.

site: timuu(.).com

The attempted login:

```
26/2 11:55 [11872] - error: /login
 invalid csrf token
```

**Comment by nhlpl** [comment]
Your site is in maintenance mode.

**Comment by pikshub** [comment]
I would update again. Wait a sec and above the search icon, etc. Try clicking. You understand the problem.

**Comment by pikshub** [comment]
Now you can look @nhlpl

**Comment by julianlam** [comment]
Please direct configuration and setup issues on [our support forum](https://community.nodebb.org), thanks.

**Comment by nhlpl** [comment]
WebSockets (WS) can be a source of your issue.

As Julian said please use community forum.

**Comment by pikshub** [comment]
https://community.nodebb.org/topic/8006/
