### ISSUE TITLE
Guest

### ISSUE THREAD

**Issue by Luchanso** [NodeBB/NodeBB#4283]
I got to guest access write and create topics in category. But it is not work only from mobile version.

When guests is trying to create post or reply to topic, it redirects to the login page.

Category setting:
![image](https://cloud.githubusercontent.com/assets/2098777/13373440/6f27c0ce-dd79-11e5-94d4-761f309b07e3.png)

Redirects, (in error message "Please Log In").
![image](https://cloud.githubusercontent.com/assets/2098777/13373461/bd6ea3ec-dd79-11e5-9d6b-ca51e0a266a5.png)

Example category https://bnch.ru/category/9/ (Do not be afraid to make posts)

**Comment by pichalite** [comment]
seems to be fixed on master. you will have to wait for v1.0.0 to be released.
