### ISSUE TITLE
No Post Tools after posting a reply

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4284]
https://community.nodebb.org/topic/7947/test-1-2-3/11

Testing Ground
Add a reply to existing topic
No tools to edit a post
It works fine after a page refresh

Something missing here.

![posttools](https://cloud.githubusercontent.com/assets/11160550/13378787/ecdb386e-de11-11e5-9c3c-fb00f153e954.jpg)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/4280
