### ISSUE TITLE
1.x.x default plugins are "not compatible"?

### ISSUE THREAD

**Issue by ahwayakchih** [NodeBB/NodeBB#4287]
version: fb4f1e1315bed7b425756ad25a396c42b2ba3891
when: right after fresh install, no additional plugins or themes were added

Looks like default plugins need to be updated too, because this shows up in log:

```
The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-theme-persona
  * nodebb-plugin-mentions
  * nodebb-widget-essentials
  * nodebb-rewards-essentials
  * nodebb-plugin-soundpack-default
```

**Comment by samhax** [comment]
+1
Happens to me on the master branch.

**Comment by psychobunny** [comment]
https://github.com/NodeBB/NodeBB-rewards-essentials/commits/47310a00c9df581b45973ad6b794ce2db0ba8aa4
