### ISSUE TITLE
ajaxify.currentPage should not include the query string

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#4289]
Ex. forum.url/?loggedIn will return `?loggedIn`, which is unexpected (should be '')

Can also add ajaxify.queryString, but that's not as important because you can get it yourself (but not a bad option to have)

**Comment by psychobunny** [comment]
Reverted, this broke `ajaxify.refresh()` :-1:

**Comment by BenLubar** [comment]
@psychobunny I think GitHub misunderstood your revert commit message.

**Comment by julianlam** [comment]
:laughing:

**Comment by psychobunny** [comment]
Seems legit. Haha
