### ISSUE TITLE
Convert profile image uploads to PNG

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4292]
Two users on your community forum have had problems with uploading PNG avatars.

https://community.nodebb.org/topic/8053/nodebb-1-0-0-load-avatar-error-502/3
and
https://community.nodebb.org/topic/8008/latest-version-error-when-uploading-default-profile-image-error-uploading-code-0
and
https://community.nodebb.org/topic/8012/error-invalid-format-0

An error comes from an option "Convert profile image uploads to PNG" as reported in first linked post.

**Comment by julianlam** [comment]
Thanks for distilling those issues into this bug report @nhlpl :smile: 

----

Hm, so when the option is **enabled**, image uploads fail? Is the source image a png, and does it only happen with pngs?

**Comment by nhlpl** [comment]
NodeBB v0.9.x branch, 0.9.4 version
Tested using cloud hosting

Cannot reproduce. It works fine.

Should be tested on:
NodeBB v0.9.x, Windows
NodeBB v1.x.x Linux

**Comment by julianlam** [comment]
Thanks :smile:
