### ISSUE TITLE
Online and offline for one user in one topic

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4293]
https://community.nodebb.org
After refresh it works fine
Low priority
Tested for many times 0.9.x and 1.x.x

Find a topic with your own post and add new reply. Check online/offline indicators (image below).

Previous post date and time (green, online)
Sat Feb 27 2016 09:45:46 GMT+0100

New post date and time (black, offline)
Tue Mar 01 2016 16:00:27 GMT+0100

![onoffreply](https://cloud.githubusercontent.com/assets/11160550/13430957/b0690070-dfc7-11e5-8cbd-8128bef09788.jpg)

**Comment by barisusakli** [comment]
Seems to work for me, are you waiting more than 5 mins before posting?

**Comment by nhlpl** [comment]
Yes, it takes me some time to think how to write in English.

I guess if something is working should not be changed. So please close it if there is no easy fix.

Thank you! :)
