### ISSUE TITLE
Allow uploading GIFs when using third-party image store (such as imgur)

### ISSUE THREAD

**Issue by tomamoto** [NodeBB/NodeBB#4295]
Details are mostly contained in [this Post](https://community.nodebb.org/topic/7798/uploading-of-gifs/13).  Essentially, those of us who want to be able to upload gifs, particularly to third-party image hosts as with nodebb-plugin-imgur, are not able to do so and are still receiving an **Unsupport MIME Type: images/GIF** error when trying to upload through the conventional image button in our posts.  While we can support users manually uploading and then embedding the resulting URL manually, one of the main ideas of this plugin is to simplify and streamline this process.  Is it possible to fix this bug and allow GIF uploads when we are not using jimp/locally stored images?

**Comment by Nisthar** [comment]
+1 for this feature

**Comment by julianlam** [comment]
Thanks Baris :)

**Comment by Nisthar** [comment]
@julianlam Do i need to update nodebb or the plugin to have this feature?

**Comment by tomamoto** [comment]
@barisusakli Cheers, and thank you!

**Comment by tomamoto** [comment]
@barisusakli Wanted to thank you again.  Just upgraded my production site to 1.0.2 this afternoon and this fix works like a charm!  Animated GIFs can now be uploaded by my users as they would any other image type without receiving any MIME Type errors.  

I will note for anyone reading this in the future that I am using nodebb-plugin-imgur and that I believe the built-in image processor (jimp?) used for locally stored images would likely still return the MIME type errors originally described.

**Comment by barisusakli** [comment]
@tomamoto yes that's correct, if you don't use plugin-imgur jimp will try to process the image and it will fail since it doesn't support gifs.
