### ISSUE TITLE
'Disable social buttons' in ACP>Settings>General without function in v1.0.0

### ISSUE THREAD

**Issue by globalcow** [NodeBB/NodeBB#4296]
It seems that the setting 'Disable social buttons' in ACP>Settings>General is without function in version 1.0.0. I have to disable the social buttons via ACP>General>Social separately.

**Comment by barisusakli** [comment]
@psychobunny I think it's safe to remove the disable social buttons option since its in ACP>General>Social now

**Comment by psychobunny** [comment]
Ah oops. I had removed the setting in the upgrade script but never removed the button
