### ISSUE TITLE
Cold load doesn't scroll to named anchors.

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#4298]
With named anchors e.g.,

`<a id="newsletter"></a>`

Loading `http://example.com/page#newsletter` will scroll on ajaxify, but not on cold load.

**Comment by yariplus** [comment]
Also, maybe related, any admin page with hashes e.g. `/admin/extend/plugins#installed` doesn't load the header title and navbar when cold loading. But! It does activate the correct bs tab, so I guess that's good. :)

**Comment by psychobunny** [comment]
I could be wrong here, but I think the latter is fixed on the latest commits.

I do have a feeling I know what's causing the original problem though

**Comment by psychobunny** [comment]
I'm not sure what changed, but it's working for me now, both cold load and ajaxify
