### ISSUE TITLE
Edit remark seems to be broken on v1.0

### ISSUE THREAD

**Issue by leader21** [NodeBB/NodeBB#4300]
Hey guys! 
After the update to v1.0.0 today there seems to be an issue with the edit remark.
after editing a post the remark is looking like that : 
![](http://www.youscreen.de/ctgvvskda49.jpg)

Is it already known?
was searching for that in the issues but did not find anything at first glance.
using the lavender theme.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/4301
