### ISSUE TITLE
Special character ' > &#x27;

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4306]
https://community.nodebb.org/chats
https://community.nodebb.org/user/bill-o-neill

Please check /user/bill-o-neill and image below.

![billo](https://cloud.githubusercontent.com/assets/11160550/13498932/526ebbf4-e15c-11e5-8a75-d9cd8357f4d9.jpg)

**Comment by nhlpl** [comment]
This bug still exists.

Find a chat room with some messages or only hello sent to you.
Add Bill O'Neill to a chat room (as a second user).
Try to remove newly added user.
Ctrl + r (will show &#x27; in username).

![bill](https://cloud.githubusercontent.com/assets/11160550/13536823/40ca9cf6-e242-11e5-97c3-45365f9b6734.jpg)

**Comment by pichalite** [comment]
@nhlpl are you testing on community.nodebb.org? it may not be updated to latest master.

**Comment by nhlpl** [comment]
Profile is fixed and bug no longer exist in some other places. It can be reproduced only in a given scenario.

If you can please test it using latest code. Thank you.
