### ISSUE TITLE
/groups/foo is needlessly slow

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4307]
The query is used by NodeBB: (db.getSortedSetRevUnion)

```javascript
db.objects.aggregate([{$match: {_key: {$in: db.objects.find({_key: 'group:foo:members'}, {_id: 0, value: 1}).map(function(uid) { return 'uid:' + uid.value + ':posts'; })}}}, {$group: {_id: {value: '$value'}, totalScore: {$sum: '$score'}}}, {$sort: {totalScore: -1}}, {$limit: 10}, {$project: {_id: 0, value: '$_id.value'}}]).toArray()
```

It takes several minutes (or hours, I haven't had it finish yet) to execute.

However, because two users cannot make a post with the same ID, this can be simplified to:

```javascript
db.objects.find({_key: {$in: db.objects.find({_key: 'group:foo:members'}, {_id: 0, value: 1}).map(function(uid) { return 'uid:' + uid.value + ':posts'; })}}, {_id: 0, value: 1}).sort({score: -1}).limit(10).toArray()
```

which takes 340ms and returns exactly the same results.

**Comment by barisusakli** [comment]
I think if we refactor https://github.com/NodeBB/NodeBB/blob/master/src/database/mongo/sorted.js#L119 to work with an array of keys, we can just use that instead of `getSortedSetRevUnion` since we don't care about summing the scores.

**Comment by barisusakli** [comment]
Alright I switched `db.getSortedSetRevUnion` to `db.getSortedSetRevRange` in the groups code.

Obvisouly this only works when the sorted sets don't share ids as you pointed out if they do there will be duplicates in the return, but the two cases we use union were both using sets that had distinct values.
