### ISSUE TITLE
on mobile every 2nd post is empty

### ISSUE THREAD

**Issue by leader21** [NodeBB/NodeBB#4308]
our forum users issued that on mobileswith browser chrome and firefox every 2nd post of any thread is empty. the same behavior when running nodeBB in a firefox or chrome window! 
have a look at the pics below. 
![](http://www.youscreen.de/chguhyvoe01.jpg)
![](http://www.youscreen.de/ckdsuadjz35.jpg)

![](http://www.youscreen.de/ncxljaaog01.jpg)

theme lavender, node bb v1.0.0

**Comment by pichalite** [comment]
@leader21 sent a PR to lavender theme to fix the issue. not sure if the fix will be released for NodeBB v1.0.0 as there are already changes made to the theme for next release.

It's a one line change... you can make the change on your installation as a stop gap.
