### ISSUE TITLE
v1.x.x outdated shrinkwrap

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#4310]
As of cc6d4f5d43d96ce6daeb2498bd33fbf7b96500d7 The shrinkwrap of the `v1.x.x` branch is out of date and prevents starting a clean setup.

Thanks to [community/tomanagle](https://community.nodebb.org/user/tomanagle) for reporting ([topic](https://community.nodebb.org/topic/8078/nodebb-will-only-start-in-dev-mode))!

**Comment by julianlam** [comment]
Thanks, compiling new shrinkwrap file now. Will be glad when I don't have to do this any longer :rage2:

**Comment by julianlam** [comment]
55b43dc
