### ISSUE TITLE
Confirm email when logged out

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4314]
https://community.nodebb.org/confirm/

Create new account
Logout
Confirm email

`Invalid Data
There was a problem validating your email address. Perhaps the code was invalid or has expired.`

Not true. Account is now validated.

**Comment by pichalite** [comment]
not able to reproduce this using the steps.

registered new account
logged out
clicked link in email to confirm.... no errors, confirmation was successful

![image](https://cloud.githubusercontent.com/assets/10014774/13580824/c105cd38-e458-11e5-9161-afbb38f07c5a.png)

**Comment by nhlpl** [comment]
Thanks for testing pichalite! Tried it again and you're right.

Closing this issue.

**Comment by ItsDizzy** [comment]
I am not sure why, but after I restarted NodeBB, i started to have the same issue, I know this is an old issue...
I am running NodeBB 1.4.2 if that matters.
