### ISSUE TITLE
url's without http:// or https:// don't work in posts

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4315]
https://community.nodebb.org/topic/8116/url-test

**Comment by pichalite** [comment]
looks like an issue with url's using markdown syntax. just typing `google.com` works but `[link](google.com)` doesn't

**Comment by julianlam** [comment]
This is due to relative url support. You cannot reliably tell a relative url from an absolute one, so it is treated as relative.

**Comment by pichalite** [comment]
then why not treat both same way. one works but the other doesn't

**Comment by julianlam** [comment]
You cannot simply because there's no auto detection of relative urls in
post text. :)

Either way it's an issue with markdown-it, so I'd recommend you bring it up
with @puzrin

**Comment by puzrin** [comment]
I dont' know how markdown-it is used in nodebb, and how linkifier was initialized.

https://github.com/markdown-it/linkify-it#api you can reconfigure `linkify-it` instance in `markdown-it` to detect such types of links. See [live demo](http://markdown-it.github.io/linkify-it/) to test different modes.

**Comment by puzrin** [comment]
Sorry, i mussunderstood ticket question

Probably, someone chaned default validator to be more strict https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L32-L40

**Comment by julianlam** [comment]
@puzrin Sorry to re-open, but when you mention the linkifier, that is specifically for instances where links are **not** defined in link syntax, right? e.g. `www.google.com`?

Is there a way to have `[google.com](google.com)` work to send users to `http://google.com` (or more likely `//google.com`)?

Perhaps I would have to modify the link parser in this case...

**Comment by julianlam** [comment]
Also fixed in 81bbe93640fef46c69f64afa943afc9e0b1d4629

**Comment by puzrin** [comment]
Formally, that's relative paths and you ask about additional transform that should happen after markdown parse. But you can hack exported [normalizeLink](https://github.com/markdown-it/markdown-it/blob/6.0.2/lib/index.js#L47), for example.
