### ISSUE TITLE
Allow users to upload topic thumbnails

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4319]
https://community.nodebb.org/topic/8029/can-not-reset-topic-thumbnail-after-the-topic-is-created
NodeBB v0.9.x, v1.x.x

Admin > Settings > Post > Upload Settings > Allow users to upload topic thumbnails

Please update themes to allow uploading topic thumbnails or remove this feature from Admin.

**Comment by pichalite** [comment]
persona already has topic thumbnail support. these pull request should add support for vanilla and lavender.

https://github.com/NodeBB/nodebb-theme-vanilla/pull/66
https://github.com/NodeBB/nodebb-theme-lavender/pull/65
