### ISSUE TITLE
Question: same experience for edit of custom fields

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#4323]
Hello guys,

What am I missing? I'm trying to create same page when user edits custom fields as you have for password, username, email, password, i.e. you have a cover. But I have this:

<img width="1167" alt="screen shot 2016-03-07 at 10 58 25 pm" src="https://cloud.githubusercontent.com/assets/135263/13591620/5d89a6f2-e4b8-11e5-8fdc-5997397da694.png">

I'm using the same method as you are for fetching user data, I have cover related data in payload.
Also I'm using the same template: 

```
<div class="account">
    <!-- IMPORT partials/account/header.tpl -->

    <div class="custom-fields"></div>
</div>
```

It's a latest thing that I would like to improve before I can release update to `custom-fields` plugin.

Code related to page generation: https://github.com/NicolasSiver/nodebb-plugin-ns-custom-fields/blob/master/plugin/routes.js#L45-L77

**Comment by barisusakli** [comment]
What do you see when you inspect the html? Is the markup there? You should have `<div class="cover" component="account/cover" style="background-image: url({cover:url}); background-position: {cover:position};">`

Also check the `/api//user/:userslug/edit/custom-fields` route to make sure data is there.

**Comment by NicolasSiver** [comment]
Layout related stuff:

<img width="414" alt="screen shot 2016-03-08 at 8 42 34 pm" src="https://cloud.githubusercontent.com/assets/135263/13622679/5abddeb4-e56e-11e5-9296-ea3afab1d43f.png">

**Comment by NicolasSiver** [comment]
There is API response:

<img width="499" alt="screen shot 2016-03-08 at 8 43 29 pm" src="https://cloud.githubusercontent.com/assets/135263/13622701/76a7f7e0-e56e-11e5-878c-14cb715e4bad.png">

**Comment by NicolasSiver** [comment]
Weird, but side-menu is also different for custom section:

#### Editing Username

<img width="188" alt="screen shot 2016-03-08 at 8 47 04 pm" src="https://cloud.githubusercontent.com/assets/135263/13622775/0fe0fa88-e56f-11e5-9ddd-7875f65a1656.png">

#### Editing Custom Fields

<img width="188" alt="screen shot 2016-03-08 at 8 47 15 pm" src="https://cloud.githubusercontent.com/assets/135263/13622777/1646d802-e56f-11e5-9c29-4de0e46d7065.png">

**Comment by NicolasSiver** [comment]
Another one observation, I have such thing only for `/custom-fields` route:

<img width="419" alt="screen shot 2016-03-08 at 9 00 13 pm" src="https://cloud.githubusercontent.com/assets/135263/13622950/e2e1f2d8-e570-11e5-949a-c691793843b7.png">

**Comment by barisusakli** [comment]
Oh I think I know whats wrong, `userData` needs to be the root object.

Take a look here https://github.com/NodeBB/NodeBB/blob/master/src/controllers/accounts/edit.js#L39

**Comment by NicolasSiver** [comment]
Thanks for the hint.
I will do changes soon.
