### ISSUE TITLE
Guest posting and flags

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4324]
NodeBB v0.9.x branch, 0.9.4 version

Admin > Settings > Guest Handles > Allow guest handles
Admin > Manage > Categories > Edit > Privileges > Group > guests > Create Topics / Reply to Topics

View Forum / Forum index
Post a reply as guest
Flag this post/reply as spam

Admin > Manage > Flags > Dismiss or Delete
Error (see image below)
Dismiss all works fine

![flagerror](https://cloud.githubusercontent.com/assets/11160550/13596259/b3accba0-e511-11e5-9bfe-8db90267f9ef.jpg)

**Comment by pichalite** [comment]
seems to be fixed. cannot reproduce in master.

**Comment by nhlpl** [comment]
Thank you for testing. Seems to be an error which comes from an old MongoDB version.

Closing this issue.
