### ISSUE TITLE
GIF profile image upload

### ISSUE THREAD

**Issue by Nisthar** [NodeBB/NodeBB#4325]
How can i upload gif image for profile image in my forum?

Also i would like to know if i can upload gif image for profile signature.

**Comment by julianlam** [comment]
@Nisthar At this point it is not supported out of the box. I do not know if imgur handles profile image uploads as well, but if it does, then you can use the imgur plugin.

**Comment by Nisthar** [comment]
@julianlam Yes. I am using imgur plugin. I can upload gif in topics, etc as of recent updates. But its showing "Unsupported mime type gif". I thought its not a problem with the plugin but with the core.

**Comment by Nisthar** [comment]
@julianlam I can change profile image to gif image if i upload using url.

**Comment by nhlpl** [comment]
You're using v0.9.4 and it was changed in v1.0.0. No longer an issue.

**Comment by Nisthar** [comment]
@nhlpl Yes. I know my version didn't support gif uploading. But i changed the code following @barisusakli's commit. Now i can upload gif images. But not for profile images. I can do it if i upload it from url. So it must be a filter in the core.

**Comment by Nisthar** [comment]
@barisusakli Thanks. I'll update my code files.

**Comment by Nisthar** [comment]
@barisusakli Thanks. I'll update my code files now.

Also i would like to know if i can upload gif image for profile signature. I tried adding the direct link in the signature, But its displaying the raw link instead of the gif image.

**Comment by nhlpl** [comment]
@Nisthar 
This is not a support forum. Please do not disturb Baris and other developers. Use community forum instead.

Thank you.

**Comment by Nisthar** [comment]
@nhlpl Sorry, I don't meant to disturb the developers. Yes, I asked the two question on the beginning. It would have been nice if they include that feature too. Because many other forum softwares like xenforo has that feature of uploading or displaying the gif image in the signature of users.

**Comment by barisusakli** [comment]
Maybe check these settings in the ACP
![image](https://cloud.githubusercontent.com/assets/2583394/13611342/c49a2ecc-e56a-11e5-9a61-7166c2a31928.png)

**Comment by Nisthar** [comment]
@barisusakli I think it will disable the signatures section completely.

**Comment by Nisthar** [comment]
![My settings](http://i.imgur.com/NQ2V3z9.jpg)

**Comment by pichalite** [comment]
@Nisthar use mark down image syntax and it will show image instead of link in signature.

` ![image alt](image link)`

**Comment by Nisthar** [comment]
@pichalite Thanks. Its working. Didn't tried that before.
