### ISSUE TITLE
error on acp in chart.js

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#4327]
```
Uncaught TypeError: Cannot read property 'clientWidth' of null
s.getMaximumWidth@ chart.min.js?v=7fdcdff3-1d1a-46da-95ce-df30d4ebd5d5:10
a.resize@ chart.min.js?v=7fdcdff3-1d1a-46da-95ce-df30d4ebd5d5:10
(anonymous function) @ chart.min.js?v=7fdcdff3-1d1a-46da-95ce-df30d4ebd5d5:10
s.each @ chart.min.js?v=7fdcdff3-1d1a-46da-95ce-df30d4ebd5d5:10
(anonymous function) @ chart.min.js?v=7fdcdff3-1d1a-46da-95ce-df30d4ebd5d5:10
```

**Comment by julianlam** [comment]
What page do these errors appear on? We use charts in dash and category analytics, though in both cases, I see no error.

**Comment by barisusakli** [comment]
Not sure about the exact repro steps, but when I got them I wasn't on the dashboard or category analytics page. Could be that dashboard was loading and I switched to another page and got the error.

The dashboard auto updating graphs could be related.
