### ISSUE TITLE
Hide group label for hidden groups

### ISSUE THREAD

**Issue by globalcow** [NodeBB/NodeBB#4328]
For group labels (which are shown behind the username) the user can choose only visible groups he belongs to. However, if a group's visibility is changed from public to hidden, the group labels are still visible. Is this meant like this?

**Comment by barisusakli** [comment]
Did you disable the `Show Badge` setting for the group?

**Comment by globalcow** [comment]
No, I did not. If I do, the labels are not visible anymore ...
However, it is a little bit strange, that the label stays visible if the group is hidden. The user will not be able to see this in his profile settings. If he is for example member of just one group, and this group gets hidden, there will be no label available in the profile settings, even if one is shown behind the username. This could be confusing.
This is not meant as bug report, but as question, if this behavior is desired :-)

**Comment by barisusakli** [comment]
Yes I think this was by design. The show badge option was added to decouple the badges from the groups visibility. So you can have hidden groups but still display the badge. Or visible groups but disable the badge etc.

**Comment by globalcow** [comment]
Ok, I understand! Thank you!
