### ISSUE TITLE
btn-info and panel-info Color Mismatch

### ISSUE THREAD

**Issue by Holyphoenix** [NodeBB/NodeBB#4330]
I noticed when creating a widget with a Panel Header container that the colors seemed to be messed up.  I looked over everything and found that I couldn't make it purple because the purple is the info color for a button, but not the color for a panel. And the panel uses the color for the class panel-info whilst the color choice uses the color for btn-info.   

![image](https://cloud.githubusercontent.com/assets/3467817/13617808/2b5dacb2-e546-11e5-9678-37be0f0ed11b.png)

![image](https://cloud.githubusercontent.com/assets/3467817/13617830/4443ceaa-e546-11e5-9bc4-5e52fb667550.png)

**Comment by julianlam** [comment]
Issue here is that the panel has its bootstrap variables overwritten, but these aren't carried over to the non-admin side.

**Comment by psychobunny** [comment]
Yeah, it's a change I want to make, a bit of voodoo required to add the client side CSS into the admin CSS

**Comment by barisusakli** [comment]
Not an issue anymore since 3.2 uses default variables
