### ISSUE TITLE
Minification script

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#4332]
Guys, it looks disturbing, doesn't it?

```
8/3 20:54 [44037] - verbose: [plugins] /.DS_Store replaced by nodebb-plugin-ns-custom-fields
8/3 20:54 [44037] - verbose: [plugins] /partials/.DS_Store replaced by nodebb-plugin-ns-custom-fields
8/3 20:54 [44037] - verbose: [plugins] /partials/account/.DS_Store replaced by nodebb-plugin-ns-custom-fields
8/3 20:54 [44037] - verbose: [plugins] Loading templates (nodebb-plugin-ns-awards)
8/3 20:54 [44037] - verbose: [plugins] /.DS_Store replaced by nodebb-plugin-ns-awards
8/3 20:54 [44037] - verbose: [plugins] /partials/.DS_Store replaced by nodebb-plugin-ns-awards
```

.DS_Store stuff
Log is from the boot stage.

**Comment by julianlam** [comment]
Does your plugin emit that log? What is it replacing?

**Comment by NicolasSiver** [comment]
No, I don't have such login in plugins. I started to notice such stuff, after v1.0 and introduction of acpScripts for plugins.

Reproduce:

- visit plugin via Mac Finder
- use this plugin (activate)
- restart NodeBB

**Comment by julianlam** [comment]
Doesn't seem like a log we output...

**Comment by barisusakli** [comment]
It is in core
https://github.com/NodeBB/NodeBB/blob/master/src/plugins.js#L188-L190
