### ISSUE TITLE
My users default settings can't be set from ACP

### ISSUE THREAD

**Issue by Nisthar** [NodeBB/NodeBB#4333]
This is my ACP settings:

![My ACP Settings](http://i.imgur.com/Q3rfKuV.jpg)

This is the settings of a new user registered in my site:

![Users settings](http://i.imgur.com/iDcJyCN.jpg)

**Comment by pichalite** [comment]
https://community.nodebb.org is the correct place to post these. not here.

**Comment by Nisthar** [comment]
@pichalite Oh Okay. How can i delete this issue?

**Comment by pichalite** [comment]
you can't delete them. just leave it closed.
