### ISSUE TITLE
Suggestion: "Mark all chats read"

### ISSUE THREAD

**Issue by Incognitov** [NodeBB/NodeBB#4335]
In the notifications bar, you'll know that there's two actions which you could possibly do.

![](http://imgur.com/sCYNIfA.png)

The "Mark all notifications read" feature is extremely useful, as it helps me easily remove the unnecessary notifications and if for any reason they were glitched, It clears that as well.

![](http://imgur.com/ykE3FGx.png)

Unfortunately I can't do the same with chats, which is somewhat annoying because I don't want to go through each chat individually and if any are glitched I can't do anything about it. So I have two questions.

1) Could "Mark all chats read" become a feature?
2) What is a fix for me to remove the notifications of chats although I've read them all?

Thanks.

**Comment by barisusakli** [comment]
Mark all chats read makes sense.

**Comment by julianlam** [comment]
Opening a chat should mark the corresponding notification read. Does it not do that at the moment, @Incognitov ? If that is the case, I can fix that portion.

**Comment by Incognitov** [comment]
@julianlam: Weirdly it doesn't. I have 5 notifications in my chat bar yet none are unread. If I get another real chat message it will show as 6 as if 5 is the default (0?), and if I read that real message it'll go back   to 5 again. Nothing I can do about it, even tried clearing all my chats. And sometimes rarely the notification changes, as before it was a glitched 3.

**Comment by julianlam** [comment]
Just to clarify, you have a counter on the *notifications* icon, not the *chat* icon, right?

**Comment by Incognitov** [comment]
Chat icon.
