### ISSUE TITLE
How to check if the user is guest or registered?

### ISSUE THREAD

**Issue by Nisthar** [NodeBB/NodeBB#4342]
How can i check if the visitor is a registered user or a guest ?

I am looking for server side solution for my plugin :+1:

I am using the hook "filter:parse.post". I tried the code 
`var cls = module.parent.require('./middleware/cls');`
But its giving me error "module not found".

Testing the plugin in 1.0.0 version. But my site is running under 0.9.4 version where i'll be using the plugin.

**Comment by nhlpl** [comment]
yariplus already found a source of your issue.
https://community.nodebb.org/topic/8176/how-to-check-if-a-visitor-is-registered-or-a-guest/13

It was merged here:
https://github.com/NodeBB/nodebb-english/pull/78/files

**Comment by julianlam** [comment]
Thanks @nhl.pl!

**Comment by Nisthar** [comment]
@nhlpl I am new to plugin development (and git)

cls is not working for me. What is the solution for this?

**Comment by julianlam** [comment]
Are you on master branch? Also, best to keep these questions to the community. Thanks.

**Comment by Nisthar** [comment]
No. I am using 1.0.0 version for testing the plugin. But the plugin will be actually used in 0.9.4 version.

**Comment by Nisthar** [comment]
@julianlam I already asked in community. But there is no solution from there.

**Comment by julianlam** [comment]
Doesn't the data returned by the post filtering hook already contain a uid?

**Comment by Nisthar** [comment]
@julianlam No. I tried `data.uid`. But its always undefined even if i login or not. (I am using "filter:parse.post")

**Comment by julianlam** [comment]
Then use the pid and call getPostField to find the uid.

**Comment by Nisthar** [comment]
@julianlam  Could you post an example on how to do that? or tell me where i can find the getPostField function.

**Comment by qgp9** [comment]
@julianlam 
filter:parse.post gives only postData and I guess postData.uid may be a uid of author, isn't it?
@Nisthar wants to have uid of *current user* who made request to recognize he/she is guest or not.

**Comment by julianlam** [comment]
Consider filter:post.getPosts instead. That may be what you're looking for.

**Comment by Nisthar** [comment]
@julianlam What objects does it give? How can it be achieved through it filter:post.getPosts ?

**Comment by Nisthar** [comment]
@julianlam Ok. Got it working now. Thanks.

**Comment by qgp9** [comment]
@julianlam It works, Fantastic!
What about if filter:parse* can have a `uid` information also. ;)

**Comment by julianlam** [comment]
Not likely to happen as the cls changes will make this moot, thanks though :smile:
