### ISSUE TITLE
[BUG]I cant update the code

### ISSUE THREAD

**Issue by Hsinky** [NodeBB/NodeBB#4343]
hello,i want add some code to page ,but when i updated the code ,restart the server,it dosen't work,
my os is win8，the vision of the nodebb is 1.0.0
![1](https://cloud.githubusercontent.com/assets/10111222/13669904/8a388786-e701-11e5-952a-91a672aa1b45.png)

**Comment by julianlam** [comment]
Hello there, please ask configuration questions at https://community.nodebb.org, or the unofficial Chinese speaking community at https://nodebb.org.cn
