### ISSUE TITLE
ACP missing translation strings

### ISSUE THREAD

**Issue by ZerataX** [NodeBB/NodeBB#4345]
While checking on the german translation I noticed that pretty much the whole ACP doesn't have strings for translation on transifex, which ends in rare occasions of german between lots of english:
![palemoon_2016-03-10_18-08-41](https://cloud.githubusercontent.com/assets/5024958/13677669/4952eee8-e6eb-11e5-8ec2-e6f917f9560e.png)

**Comment by pichalite** [comment]
actually ACP is not internationalized. Managing groups in ACP is probably the only place where you may see text translated because groups re-uses code & templates from the client side which is internationalized.

**Comment by ZerataX** [comment]
I don't mind if it isn't translated, because my users will never touch it, but I would definitely prefer a full english interface over a mixed language interface.

**Comment by pichalite** [comment]
I agree.
