### ISSUE TITLE
Can't ./nodebb upgrade

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#4352]
I can no longer `./nodebb upgrade` if one of the plugins is a git repo. It used to just skip upgrading for git repos.

```
yari@yaricraft:~/nodebb$ ./nodebb upgrade
1. Bringing base dependencies up to date... OK
2. Checking installed plugins for updates... Warning: An unexpected error occured when attempting to verify plugin upgradability

Error: Unexpected token u
```

**Comment by julianlam** [comment]
Thanks, didn't test using a git repo as plugin. :laughing:

I personally use npm link.

**Comment by julianlam** [comment]
@yariplus Tested on node v0.12 (with npm@2) and node v5 (with npm@3), both don't error out the way you pasted, so I can't reproduce that exact issue.

The upgrade itself doesn't work though, so will patch that.

**Comment by yariplus** [comment]
Thanks. I tried on a fresh install and it does fix it, but I'm still getting 'Unexpected token u' on my main install. I'll post another issue if I can figure out what's causing it.
