### ISSUE TITLE
Deleting users has changed?

### ISSUE THREAD

**Issue by Incognitov** [NodeBB/NodeBB#4354]
We just updated from the Master branch and we discovered that when deleting users it seems to be soft deleting them rather than fully deleting all traces of users as before. It essentially does nothing further than a ban now. Instead, we see this with users we "deleted":

![](http://imgur.com/gFbnsWW.png)

It is possible we could have caused this but I was interested whether this was a new change. But if it is, I think people would still be interested in permanent deletion. I was wondering perhaps there could be a "soft delete" feature which deletes as shown in the screenshot above, and a "hard delete" feature which removes absolutely all data of the user (as before)?

**Comment by barisusakli** [comment]
Deleting from the ACP seems fine, deleting from the users profile doesnt seem to do anything.

**Comment by julianlam** [comment]
This is a breaking change that we've missed, adding label for plugin developers.
