### ISSUE TITLE
Problems with spacing

### ISSUE THREAD

**Issue by Incognitov** [NodeBB/NodeBB#4355]
With the new children categories visible on the home page, it seems to have created an issue with spacing of text in our categories:

![](http://imgur.com/1eJirK9.png)

As you can see, comparatively to the outer categories surrounding the central ones, there is a space between the description and children. I checked with the official NodeBB forums and this doesn't seem to be the norm. I can also of course hide the children categories from the home page manually as a temporary fix with some CSS declarations:

![](http://imgur.com/dMvxwQH.png)

However you can still slightly see that there is a problem with spacing of those two central categories when compared to the outer ones, as the description is closer to the title than the others.

P.S: Upon inspection, I believe a < br > has somehow managed to get into those categories. You can have a look for yourself as well: http://forum.leet.cc.

Thanks.

**Comment by barisusakli** [comment]
Looks good to me on our community forum. Are you sure you don't have new lines in your category descriptions? Also make sure you have latest core and persona since this is only available on master.

**Comment by ProjectInfinity** [comment]
Hey, I'm the one that manages the server that is having the issues shown here. I pulled from master just yesterday evening and I tried removing all the text in the description, saving, then reloading and writing a new description.

**Comment by nhlpl** [comment]
It seems to be a problem related to nodebb-plugin-gravatar or some other non-default plug-in.

For example avatar size on community forum is 46 x 46 px (category view) and on your forum 32 x 32 px.

**Comment by barisusakli** [comment]
After you pull master you also need to run `npm i` to install the themes.

**Comment by ProjectInfinity** [comment]
@nhlpl Turns out I had plugin-gravatar-cn as opposed to plugin-gravatar. That has been fixed, but the spacing issue seems to exist still.

@barisusakli Just took it down, pulled from git again, ran nodebb upgrade, then ran npm i. Issue persists.
