### ISSUE TITLE
jquery.timeago.tr-short.js

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#4357]
http://site/vendor/jquery/timeago/locales/jquery.timeago.tr-short.js?_=1457879457152 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by julianlam** [comment]
https://github.com/rmm5t/jquery-timeago/tree/master/locales

Please make a pull request here, to add the tr.short file, thanks! 

https://github.com/rmm5t/jquery-timeago/tree/master/locales

**Comment by julianlam** [comment]
You'll want to copy the existing en.short file and adjust it for Turkish

**Comment by pikshub** [comment]
thank you

**Comment by julianlam** [comment]
We can leave this open :smile: once you make the pull request and it gets merged, I can update timeago on our end.

**Comment by pikshub** [comment]
sorry :/

**Comment by pikshub** [comment]
https://github.com/NodeBB/NodeBB/pull/4358
