### ISSUE TITLE
Disable translation within code blocks of posts

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#4362]
When posting sth. like `` `[[xy:z]]` `` it gets translated thus only `z` is visible within the code tag.

See https://community.nodebb.org/topic/8224/testing-code-blocks

**Comment by julianlam** [comment]
This is technically difficult to do because the outgoing html for the entire page is translated at once. 

We just simply *can't tell* what is post content and what isn't :smile:

(well, not without an html parser, which would add a lot of overhead...)

**Comment by frissdiegurke** [comment]
Maybe replacing `[` and `]` with `&#91;` and `&#93;` would solve this?
