### ISSUE TITLE
Cannot use websocket to fetch page `0` of some paginated functions

### ISSUE THREAD

**Issue by AccaliaDeElementia** [NodeBB/NodeBB#4364]
The test used by some paginated loadMore* functions in the websocket disallows passing in the number `0` for the parameter `after`

As seen below:
https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/notifications.js#L18
https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/topics/infinitescroll.js#L91
https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/topics/infinitescroll.js#L102

these functions test the validity of the after parameter by inspecting the truthiness of the provided number, this fails for `0` as `0` is falsy in JavaScript.

I recommend replacing the `!data.after` test with `!utils.isNumber(data.after) || parseInt(data.after, 10) < 0` which accepts `0` as an input, and also rejects the nonsensical (but still truthy) negative numbers.

**Comment by julianlam** [comment]
Thanks for the debugging, and pull request @AccaliaDeElementia! :smile: Will wait for @barisusakli to hop on and validate before merging.
