### ISSUE TITLE
2FA QR Code doesn't contain secret key data (WinPhone)

### ISSUE THREAD

**Issue by RaceProUK** [NodeBB/NodeBB#4373]
I'm using the Microsoft Authenticator app on Windows Phone, which is functionally identical to how Google Authenticator works, but it doesn't parse the QR code correctly when setting up two-factor authentication; the error received is "The code you scanned does not contain valid account and secret key data". Thing is, it does pick up the account name (raceprouk@community.nodebb.org), just not the secret key.

Is this an issue with the QR Code itself, or is it specific to Windows Phone? Also, is it possible to add another way to get the secret key without relying on a QR code, for those that don't have a camera available or where the QR code doesn't work?

**Comment by julianlam** [comment]
Not quite sure... it happens with the iOS authenticator app as well, though as yet unable to ascertain the cause.

**Comment by julianlam** [comment]
julianlam/nodebb-plugin-2factor#13

Try Azure Authenticator?

**Comment by RaceProUK** [comment]
Azure Authenticator works, though I can imagine there's still a cause for confusion, given the standard Microsoft Authenticator doesn't work. But I guess that's an issue for the plugin, not for the core product :smile:
