### ISSUE TITLE
Gmail routing password in clear text in DB saved ?!?

### ISSUE THREAD

**Issue by ogerly** [NodeBB/NodeBB#4375]
Gmail Routing

"_key":"config" ..... ,"email:GmailTransport:pass":"PASSWORD IN CLEAR TEXT !!","email:GmailTransport:user":"username"

In ACP under Settings / Email I have entered the possibility Gmail routing.
These data are stored in clear text in the database ??
the allowed because not be stored in clear text.

**Comment by julianlam** [comment]
Yes? How else can a password be stored for use in an api call?

**Comment by ogerly** [comment]
Yes you are right. but there must be a solution.
it is not good that the password must be free to read.
I am times thoughts

the only it would be to encrypt and decrypt.
with a used by the internal system general key
