### ISSUE TITLE
Arabic in tags messses up Topic view

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#4379]
Tags containing Arabic (or any other RTL language I suppose.)

in the topic list, the X of "X minutes ago" should be next to "minutes ago" in at least one formation or another. I'm guessing  it should really be to the right as it would for a topic with more 'regular' tags.

![screenshot from 2016-03-18 16 05 25](https://cloud.githubusercontent.com/assets/3939886/13883869/536d1078-ed23-11e5-9750-4d4ee8ba5d49.png)

**Comment by barisusakli** [comment]
This is what I get with a arabic tag, my language is set to english though, are you changing the language to arabic as well?
![image](https://cloud.githubusercontent.com/assets/2583394/13956020/9636670e-f04f-11e5-9385-fdf1718c853b.png)

**Comment by pauljherring** [comment]
No - set to English

Like my R2L bug I'll see if I can post what I was pasting:

بول

Visible here: https://what.thedailywtf.com/tags/%D8%A8%D9%88%D9%84

**Comment by barisusakli** [comment]
https://community.nodebb.org/recent

Seems to work fine here, maybe you have some custom css that is causing it?

**Comment by pauljherring** [comment]
Ah - you have an "About" in yours - it only seems to be apparent when the "....ago" starts with a number. "About a minute ago" appears to the right. "4 minutes ago" gets split.

![screenshot from 2016-03-22 15 10 13](https://cloud.githubusercontent.com/assets/3939886/13956342/3f4435b6-f040-11e5-8cdf-e6c13fdd7b0a.png)

**Comment by pauljherring** [comment]
> https://community.nodebb.org/recent

It's when it starts with a number:

![screenshot from 2016-03-22 15 11 47](https://cloud.githubusercontent.com/assets/3939886/13956376/6c08c544-f040-11e5-91c9-b1812060d6ba.png)
