### ISSUE TITLE
Subcategory icons on the main page

### ISSUE THREAD

**Issue by Dynosore** [NodeBB/NodeBB#4381]
I noticed that if you upload a image for your category icons, that subcategories shown on the main page beneath their parent category do not fixing a scanned copy of the background image. If you use a font awesome icon and a uploaded image then the icon is shown.

Shouldn't these icons be scaled down and displayed - or allow the ability for a font awesome icon to be shown in place of the uploaded icon when viewed as a sub category, but not be shown overtop the uploaded icon when viewed as a category.

Thoughts?

**Comment by barisusakli** [comment]
Can you post a screenshot of what you mean? I think the subcategories on the homepage don't use the images at all since they are really small.

**Comment by TheVigilanteTech** [comment]
@Dynosore, why not use a font awesome icon for each category, and then use custom CSS to prevent it from rendering on the categories listing?

I'm linking samples from our forum.
### Categories Page
![](http://i.imgur.com/RzWrRaq.png)

### Recent Page
![](http://i.imgur.com/M4who0n.png)

**Comment by WarbleSync** [comment]
Any update on this?  I'm working on a theme based of persona and would like scaled down versions of the category background to show instead of font awesome icons.  Is this happening in {function.generateChildrenCategories}?  Where can I edit that function?
