### ISSUE TITLE
Hide Global Moderators group by default

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4384]
NodeBB 1.0.1 version, v1.x.x branch, fresh install

Low priority

Global Moderators (System Group) should be hidden by default when no global mods were added to the group (0 users on the group counter). I mean many small communities can live without adding any user to this group.

I know it can be manually disabled here:
Admin > Manage > Groups > Edit > Global Moderators > [Hidden
(please fix **[Hidden** text in Admin)

![hiddeng](https://cloud.githubusercontent.com/assets/11160550/13899773/95d08cd2-edf6-11e5-9728-6b408d48791a.jpg)

![zerousers](https://cloud.githubusercontent.com/assets/11160550/13899709/1ebb2ebe-edf5-11e5-8d0c-fd4e26a849e8.jpg)

**Comment by barisusakli** [comment]
As you said an admin can just hide it if they want, not really an issue.
