### ISSUE TITLE
searchable drop down menus

### ISSUE THREAD

**Issue by Ewan-Walker** [NodeBB/NodeBB#4385]
It would be very nice to (by default) have searchable drop down menus for all things drop down at length.

E.g. when creating a category you just have a mass of boards shoved into a select box and must filter through them all.

**Comment by psychobunny** [comment]
Sorry for the late reply here, but this really belongs in our theme repositories. Somehow this went under the radar and wasn't addressed.

Neat idea, but definitely the wrong tracker here. Open to ideas, please post on https://github.com/NodeBB/nodebb-theme-persona/issues
