### ISSUE TITLE
Guest label in first post

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4387]
NodeBB 1.0.1 version, v1.x.x branch

New topic
Quote
Delete reply
Purge reply
Ctrl+r (Refresh) for two and more times

`@Guest` label can be seen every second page refresh.

![testguest](https://cloud.githubusercontent.com/assets/11160550/13900010/31de4b78-edfc-11e5-9d78-a9aa38da268f.jpg)

**Comment by pichalite** [comment]
can you reproduce this on the community? I followed your repro steps but could not reproduce it.

you are seeing the guest label on the first post in the topic?

**Comment by nhlpl** [comment]
Steps to reproduce:
1) Use only admin user (no other users registered)
2) New topic
3) First reply to newly created topic
4) Topic Tools > Delete Posts > Click on reply to add this post to the list
5) Use Purge button
6) Check opening post or refresh page (see image below)

![topicguest](https://cloud.githubusercontent.com/assets/11160550/13913403/8aca8558-ef46-11e5-845a-88c8be5b1706.jpg)

**Comment by barisusakli** [comment]
What is your templates.js version? `npm ls templates.js` ?

**Comment by nhlpl** [comment]
templates.js@0.3.3

**Comment by nhlpl** [comment]
Upgraded to NodeBB 1.0.2 and this issue still exist. The only difference is I needed two page refreshes instead of single page refresh. After that it shows every second refresh.

**Comment by barisusakli** [comment]
Can't reproduce with those steps on master. Does it happen on master for you as well?

**Comment by nhlpl** [comment]
Okay, closing.

Will test it using NodeBB 1.0.3 when ready.

**Comment by nhlpl** [comment]
Works fine on a newly installed NodeBB.

NodeBB v1.0.3-auto.0, fresh install (today)
Node.js 0.10.43, NPM 3.8.2
MongoDB 3.2.3
