### ISSUE TITLE
Introduce CHANGELOG.md

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#4389]
Hello guys,

Would you mind to introduce Changelog?
It will help much. 

Thanks.

**Comment by nhlpl** [comment]
I love seeing all new features on screenshots and videos.

i.e.
Admin > Plugins > Composer (Default) > Use a seperate route for the composer
Reload
New topic > Reply

Great thing for busy developers and forum admins.

**Comment by julianlam** [comment]
Easy way to see changed features :smile: 

https://github.com/NodeBB/NodeBB/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aenhancement+milestone%3A1.0.1+is%3Aclosed+

**Comment by NicolasSiver** [comment]
No, it isn't ;)
