### ISSUE TITLE
Search menu item disabled by default

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4390]
NodeBB 1.0.1 version, v1.x.x branch, MongoDB 3.2.3, fresh install

Low priority

Admin > General > Navigation > Save
Enables `/search` route by just saving form for the first time

Disabling it manually works fine.

**Comment by barisusakli** [comment]
@psychobunny as soon as you click save in navigation pane [this](https://github.com/NodeBB/NodeBB/blob/master/install/data/navigation.json#L81-L85) disappears from the data.
