### ISSUE TITLE
Weird infinite UI loop that prevents users from scrolling down further in the topic

### ISSUE THREAD

**Issue by asdf-tdwtf** [NodeBB/NodeBB#4395]
See title and this video: https://vid.me/80ih

Happened on Opera 36 on Linux in this thread, at post 135:
https://what.thedailywtf.com/topic/19201/hahah-it-s-still-shit/133
(Sorry for the inflammatory thread title, it's TDWTF.)

Slowly scroll down to post 135 to reproduce.

**Comment by nhlpl** [comment]
It works fine for me. You've posted a link to post 133 and think it should be first post to reproduce loading more content.

Windows 7, Opera 36.0.2130.29

Okay, going from top to the bottom freezes scroll (sometimes jumping between posts). But just for few seconds to load more posts. Similar behavior going from the page footer to the page header. Page loading not smooth at all.

Slow moving will not reproduce this effect. For me it can be reproduced going fast from last post to the first post and vice verca.

**Comment by asdf-tdwtf** [comment]
No wonder - the post that triggered this behavior has since been deleted. I'll ask the admins what the post content was.

**Comment by asdf-tdwtf** [comment]
OK, he filled the post with as many @-mentions as he could. For some reason, the first long post full of mentions didn't break the topic, but the second one did.

**Comment by barisusakli** [comment]
I think it makes sense to limit the number of mentions you can make in one post.
