### ISSUE TITLE
UI/UX: Inconsistent behavior when clicking on OP's avatar

### ISSUE THREAD

**Issue by asdf-tdwtf** [NodeBB/NodeBB#4396]
Clicking on the OP's avatar takes you to the OP's profile page (expected), unless you're in the unread tab, where it's used for selecting threads to mark as read (totally undiscoverable and unexpected). This is inconsistent and highly confusing.

Suggested solution: When "Mark as Read > Selected" is clicked, add buttons to each thread in the unread list. When you click on the OP's avatar in the unread list, go to the user's profile page, as always.

**Comment by asdf-tdwtf** [comment]
The topic selection has another problem by the way: The "Mark as Read" button doesn't scroll with the list, so if I select a lot of topics in a long list, I have to scroll all the way up to mark them as read. Implementing my solution would also get rid of that problem.

**Comment by coldandtired** [comment]
Also, the tooltip showing the username only appears if the mouse is over the edge of the image, and not if the mouse is over the part where the tick in a circle is (even when the avatar is still visible).

**Comment by julianlam** [comment]
Hey guys, this is actually a theme-specific issue. On Persona, we override the click action for the avatar to be a checkbox, whereas in vanilla, a checkbox is just placed next to the avatar.

@psychobunny has seen this issue and will likely take your opinions into consideration for the next theme in the works :smile: 

In the meantime, your theme can be modified so the checkbox is not integrated with the avatar.

**Comment by psychobunny** [comment]
I'm on mobile, re-opening so I can ban hammer this myself on desktop..
I mean, copy/paste this on the theme tracker as this is a legitimate issue that I want to address.
