### ISSUE TITLE
UI/UX: Chat bubble not dismissed when reading chat (Desktop)

### ISSUE THREAD

**Issue by asdf-tdwtf** [NodeBB/NodeBB#4397]
When a new chat message appears, both a chat bubble with an unread counter and a notification in the top bar appear. When you click on the "chats" icon in the top bar and go to the chat to read the new messages, the chat bubble doesn't automatically disappear. It will continue to sit there and show the same unread counter until you open it.

**Comment by psychobunny** [comment]
fixed in 963d13795bcd00b98312cd9557d9a09b9870f23b
