### ISSUE TITLE
Incorrect notification text (multiple posts liked in same thread)

### ISSUE THREAD

**Issue by asdf-tdwtf** [NodeBB/NodeBB#4398]
![bug](https://cloud.githubusercontent.com/assets/17952607/13901724/42c7f994-ee2d-11e5-88a0-5daff64d1fbd.png)

Post has one upvote, notification text claims otherwise. Maybe it was actually trying to tell me that three different posts were upvoted?

**Comment by asdf-tdwtf** [comment]
In case it isn't obvious: The notification is pointing to the post whose like count I hovered in the screenshot.

**Comment by julianlam** [comment]
Fixed in e481ed2

@BenLubar
