### ISSUE TITLE
Topic title cut off on upvote notifications

### ISSUE THREAD

**Issue by loopback0** [NodeBB/NodeBB#4399]
As shown here:

https://what.thedailywtf.com/topic/19199/topic-title-cut-off-for-upvote-notifications/2

![image](https://cloud.githubusercontent.com/assets/8740474/13901777/b5bf69d4-ee26-11e5-82ba-9efc2ac3fd77.png)

**Comment by nhlpl** [comment]
Related: https://github.com/NodeBB/NodeBB/issues/4318

It seems topic title with `,` works fine and seperated by `.` not.

**Comment by BenLubar** [comment]
Fixed in julianlam/nodebb-plugin-mentions#64, NodeBB/NodeBB#4419
