### ISSUE TITLE
Can't quote the first character in a post

### ISSUE THREAD

**Issue by loopback0** [NodeBB/NodeBB#4401]
https://what.thedailywtf.com/topic/19255/can-t-quote-the-first-character/2

an't select the first character without it selecting the rest.

Screenshots are selecting right-to-left to show the effect but it happens left-to-right too.
![image](https://cloud.githubusercontent.com/assets/8740474/13901919/c99c9ad0-ee2b-11e5-83f9-d74a28f79950.png)

![image](https://cloud.githubusercontent.com/assets/8740474/13901922/cea364fa-ee2b-11e5-8920-a1393c8b4480.png)

**Comment by BenLubar** [comment]
That's a problem with our local CSS, not a NodeBB bug.

**Comment by loopback0** [comment]
Yeah, what @BenLubar said.
