### ISSUE TITLE
Terms of use not disabled

### ISSUE THREAD

**Issue by loopback0** [NodeBB/NodeBB#4402]
Low priority, obviously.

https://what.thedailywtf.com/topic/19249/minor-terms-of-use

On sign up:
![image](https://cloud.githubusercontent.com/assets/8740474/13902017/b25a0f66-ee2f-11e5-9f76-272565976c65.png)

Admin:
![image](https://cloud.githubusercontent.com/assets/8740474/13902020/c3fde5bc-ee2f-11e5-9204-e9f7f6043709.png)

**Comment by nhlpl** [comment]
Cannot reproduce.

NodeBB 1.0.1 version, v1.x.x, fresh install
Persona 4.0.99, MongoDB 3.2.3

Default settings do not show this box/text field.
Enabling and disabling works as it should.

**Comment by pichalite** [comment]
check your db to see what's set as termsOfUse

for mongo db use `db.objects.find({"_key":"config"}).pretty();`

**Comment by barisusakli** [comment]
This is the terms of use `"termsOfUse": "<p></p>",`, possibly there is a newline in that box in the ACP.
