### ISSUE TITLE
High (stacking) on likes (bubble)

### ISSUE THREAD

**Issue by dkfellows** [NodeBB/NodeBB#4403]
Something weird happens with the stacking of the like/dislike notification bubble in some circumstances. In this picture, my mouse pointer is nowhere near any of the controls in view; the bubble shouldn't be showing.

![image](https://cloud.githubusercontent.com/assets/1155878/13902169/a184333c-ee35-11e5-8618-5ed1f4f2dbb3.png)

It also shouldn't be stacked on top of the title bar. It should have gone away when I clicked on the dislike button. When I hover over the number, it should show me updated information. It definitely shouldn't continue to show when I scroll the page up further, but it does (giving an even more confusing picture, as I can't see why the bubble is appearing at all any more) and then the bubble interferes with the buttons in the title bar. The stacking looks really weird!

**Comment by psychobunny** [comment]
Hmm. I can't seem to repro this, can you show me the post where this happens? Also what browser are you using?

And are you using the default skin? Thanks

**Comment by psychobunny** [comment]
Nevermind, I figured out how to repro
