### ISSUE TITLE
Duplicate reply loaded through live update

### ISSUE THREAD

**Issue by thecartman82** [NodeBB/NodeBB#4404]
![image](https://cloud.githubusercontent.com/assets/13422207/13904079/578006b2-ee94-11e5-9589-4b8f556b4470.png)

The original thread:
https://what.thedailywtf.com/topic/19281/nodebb-misfeatures

I have reloaded the thread, and the duplicate cleared.

The poster says they didn't do anything special:
https://what.thedailywtf.com/topic/19284/duplicate-reply-when-loaded-live

Unfortunately, I didn't think to check the console before I reloaded.

**Comment by asdf-tdwtf** [comment]
I don't have the exact steps to reproduce either, but I've seen it in multiple topics.

**Comment by BenLubar** [comment]
I wonder if it has to do with the crashing.

**Comment by barisusakli** [comment]
We filter the posts [here](https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic/posts.js#L97) was this happening while using infinitescroll or pagination?

**Comment by sjennison** [comment]
I've seen it happen with infiniscroll, can't speak to pagination as I don't have that enabled...

**Comment by sjennison** [comment]
It seems to be related to very iffy connections, either due to the server going down or because my school's wifi is terrible.
