### ISSUE TITLE
Topic status bar sometimes counts incorrectly

### ISSUE THREAD

**Issue by asdf-tdwtf** [NodeBB/NodeBB#4405]
I think I'm on the bottom of the thread, but the status bar doesn't agree:

![bug3](https://cloud.githubusercontent.com/assets/17952607/13904592/2d7f8a9c-eea6-11e5-9447-102a21748ea3.png)

**Comment by julianlam** [comment]
[This code](https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/navigator.js#L108-L119) determines which post is used when calculating the number at the top.

At the top it ought to be 1, and at the bottom it ought to be the last post, so just need some tweaks.
