### ISSUE TITLE
Downvoted posts don't show voters

### ISSUE THREAD

**Issue by FrostCat** [NodeBB/NodeBB#4406]
![image](https://cloud.githubusercontent.com/assets/13651354/13905194/97de6112-ee86-11e5-961e-4c39211b7599.png)

Compare a post with lots of upvotes:

![image](https://cloud.githubusercontent.com/assets/13651354/13905196/ae327d86-ee86-11e5-82a5-82d393b91e0e.png)

**Comment by thecartman82** [comment]
That's probably by design

**Comment by yariplus** [comment]
Yeah, showing downvotes would be bad, and lead to downvote wars.

**Comment by barisusakli** [comment]
This is by design, we only show the upvoters in the tooltip, an admin can click on the number and see all the upvoters/downvoters/
