### ISSUE TITLE
Scrolling randomly (usually up) the thread when composing a reply on Safari (and other mischeviousnesses) (iPhone, iOS 9.0.2)

### ISSUE THREAD

**Issue by cartmanwtf** [NodeBB/NodeBB#4409]
When composing a reply to a topic, before any text is present in the compose box (so, you have to click the global reply button), a lot of nasty things happen:

1. Scrolling up the thread.
2. Compose box appears.

<img src="https://cloud.githubusercontent.com/assets/17355156/13906086/98a93584-eece-11e5-9b9b-a4a8a1b4a54f.png" width="300" />

3. When I click on the reply box, the keyboard pops up and compose window hides: there is only blank screen showing.

<img src="https://cloud.githubusercontent.com/assets/17355156/13905992/6276c0b2-eece-11e5-8a78-d108b424b5a0.png" width=300" />

4. When I start entering text, the compose view reappears. (With the just entered text being hidden behind the keyboard, but that's a whole .

<img src="https://cloud.githubusercontent.com/assets/17355156/13906006/6f80819e-eece-11e5-8224-f87ce9f3e577.png" width="300" />

(Here I already scrolled down to make it viewable.)

**Comment by cartmanwtf** [comment]
Ok, did much more testing and it seems it's always scrolling upwards, so it doesn't happen in short threads. The thing is, in longer threads, it does stop at *some* point: not the whole way up at the first post but somewhere lower. It might be that when it scrolls up and posts aren't loaded yet and I start typing: then it is possible to write posts. However, if I close the keyboard, e.g. to upload a picture and try to start typing again, the whole thing repeats.

**Comment by bdharrington7** [comment]
Reported this on the theme's GitHub here: https://github.com/NodeBB/nodebb-theme-persona/issues/272

**Comment by bdharrington7** [comment]
This has been fixed by https://github.com/NodeBB/nodebb-plugin-composer-default/commit/f8ad3b44ef6c342765a7b3bfd9b54afd15b160a4
