### ISSUE TITLE
Chats are not showing on Safari iOS 9.0.2 (iPhone)

### ISSUE THREAD

**Issue by cartmanwtf** [NodeBB/NodeBB#4410]
On Safari (iOS 9.0.2, iPhone), chats don't show.

Steps to reproduce:

1. Open a chat.
2. See, there's nothing there, aside from the chat name.

<img src="https://cloud.githubusercontent.com/assets/17355156/13906117/41d97bb4-eecf-11e5-8960-bbab566c7c60.png" width="300" />

**Comment by EyeMWing** [comment]
Same on Android 6.0.1 Chrome 49.

It displays briefly before disappearing in a puff of JavaScript.

**Comment by EyeMWing** [comment]
This appears to happen only when clicking a notification about a chat message. The actual chats UI leads you to a chat popover that actually works.

**Comment by cartmanwtf** [comment]
Well, I'm sure that the one I posted I got when clicking on a chat in the chat-list, but I can't reproduce it right now, as you say.

It could get fixed, I think there was an update performed in the meantime.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/4393
