### ISSUE TITLE
Quotes have larger font in preview than in actual posts

### ISSUE THREAD

**Issue by loopback0** [NodeBB/NodeBB#4413]
On TDWTF:
![image](https://cloud.githubusercontent.com/assets/8740474/13906158/c9740880-eec7-11e5-9c74-944ab2b2d7ec.png)

On NodeBB Community:
![image](https://cloud.githubusercontent.com/assets/8740474/13906162/dd040c7e-eec7-11e5-948b-bce49280bf35.png)

The font size used in the post is the same as the "said" line.

**Comment by BenLubar** [comment]
Also, the last paragraph of a quote has the wrong margin in the preview.
