### ISSUE TITLE
Composer undo stack doesn't work properly in Chrome

### ISSUE THREAD

**Issue by TheCatPlusPlus** [NodeBB/NodeBB#4420]
All programmatic composer actions (toolbar buttons, selective quoting) break the undo stack. All I can undo is manual operations like inserting or removing text, and that doesn't interact very well with the programmatic stuff (one thing I haven't captured: type something, insert bold, type something else, select everything, click bold and then undo — pretty much destroys the text):

https://www.youtube.com/watch?v=WiVoPCy0kKM

Tested on:
* Chrome 49.0.2623.87 m on Windows
* chromium-browser 48.0.2564.116 Ubuntu 15.10 (64-bit) on Linux

For comparison Firefox 47.0a2 (2016-03-20) on Windows behaving correctly:

https://www.youtube.com/watch?v=rovrxRWGp9E

Running NodeBB 1.0.1, nodebb-plugin-composer-default 3.0.10, nodebb-theme-persona 4.0.99.

**Comment by psychobunny** [comment]
Related: http://stackoverflow.com/questions/7553430/javascript-textarea-undo-redo

**Comment by julianlam** [comment]
Yes, I ran into this issue with tabIndent.js... simply put, every time you set the text area's `.value`, you lose the edit history.

Options to proceed are:
* Refactor to use `.createEvent()` which is kind of weird (not broadly supported, diff. behaviour on some browsers, etc)
* Maintain our own edit stack in session storage... which I think is easiest, but then you add additional _stuff_ that can be bugged and require fixing.

Probably going to proceed with the latter anyway.

**Comment by julianlam** [comment]
I hadn't read the SO link @psychobunny posted, it actually looks promising, so will try that first.

**Comment by julianlam** [comment]
Creating our own event is cumbersome, and doesn't always work (not quite sure why). Plus this is a solved problem for Firefox, so [waiting on upstream to fix](https://bugs.chromium.org/p/chromium/issues/detail?id=348505).
