### ISSUE TITLE
Add and delete tag to get tag 0

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4431]
NodeBB 1.0.2 version, v1.x.x branch

Low priority
It works fine after visiting empty tag (0)

New topic
Add tag NodeBB
Edit topic and remove tag NodeBB
Open `/tags` route (see image below)

Page refresh doesn't help but visiting empty tag removes it from the tag list.

![nodebb0](https://cloud.githubusercontent.com/assets/11160550/13932315/be5d47e6-efa7-11e5-9ee2-03313760b926.jpg)

**Comment by pichalite** [comment]
I think it's OK to leave the tag after it's removed from the topic. Deleting the tag altogether after visiting the tag page... that's interesting functionality.
