### ISSUE TITLE
Pinned topics and sorting

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#4433]
NodeBB 1.0.2 version, v1.x.x branch
https://community.nodebb.org/category/2/general-discussion

Sort by > Oldest to Newest OR Most posts
Admin > Settings > Post > Default Topic Sorting > Oldest to Newest

Please make pinned topics on top of the page for both alternative sorting options.

**Comment by Captain1** [comment]
By the way, I want add another feature: get pinned topics in each categories via domain/api/category_name/pinned_topics. Hopes anyone could help to add this api endpoint.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/c33d3e874a688857368147d81e7a61d4b0a444be

**Comment by nhlpl** [comment]
I have tested it again and reported issue still exists.

1) Please open:
https://community.nodebb.org/category/21/tutorials

2) Sort by > Most posts

3) Please compare pinned topics with normal topics and look on posts column.

![mostposts](https://cloud.githubusercontent.com/assets/11160550/21400603/386fc63a-c7b1-11e6-9fef-357ef88ec146.png)

Expected to see 67, 10, 6, 3 insted of 6, 10, 67, 3.

**Comment by barisusakli** [comment]
Gonna open another issue for this, its not exactly the same issue.
