### ISSUE TITLE
ACP, Question: Is it possible to expose global modules earlier?

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#4436]
Hello guys,

Is it possible to expose objects like `socket`, `app`, etc. - earlier? 
Nowadays, with ES6, and high-order functions, It's really hard to design ACP application, where global objects will be used and first time accessed in `init` method. 

By wrapping code in _define_, it means all es6 imports do stuff before `init` method.

**Comment by NicolasSiver** [comment]
As an example, with _browserify_ it isn't an issue: https://github.com/NicolasSiver/nodebb-plugin-ns-custom-fields/blob/master/client/acp/index.js

because you can "bootstrap" stuff in _init_ method, because of _require()_ flexibility.

**Comment by NicolasSiver** [comment]
Or I'm missing something, and `socket`, `app` and etc, aren't available as _define dependencies_ and should be used as global entities (i.e. `global.socket`, `global.app`)?

**Comment by barisusakli** [comment]
Right now socket and app are global objects and not used with require

**Comment by NicolasSiver** [comment]
Hm, I see. Thank you.
