### ISSUE TITLE
Registration queue grouping still spammy.

### ISSUE THREAD

**Issue by ProjectInfinity** [NodeBB/NodeBB#4438]
The grouping of registration notifications were a good addition, but it is still really spammy. It would be nice if you could hide the additional entries in the notifications list when there is a grouped queue notification being displayed.

Thanks.

![screenshot](http://puu.sh/nPNn6/cae7aa6295.png)

**Comment by julianlam** [comment]
Oh, that's weird, those duplicates should've been removed...
