### ISSUE TITLE
chats interact poorly with clustering

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4440]
Messages sent to a user attached to another instance on the cluster do not arrive until the user refreshes.

**Comment by barisusakli** [comment]
You need to configure redis to pass messages to other nodes.

Add a redis block to config.json with the connection details 

```
"mongo": {}
"redis": {}
```

**Comment by pichalite** [comment]
don't forget to install the required modules

`npm install redis connect-redis socket.io-redis`
