### ISSUE TITLE
Post teaser includes images even though they're not shown

### ISSUE THREAD

**Issue by loopback0** [NodeBB/NodeBB#4441]
![image](https://cloud.githubusercontent.com/assets/8740474/13969505/40534df8-f07b-11e5-8bde-c4d65bcabc37.png)

This is the teaser snippet on a post. It includes the <img> tag from the post which causes the browser download the image, despite the image not being shown. This makes the download size of the topic quite large in some instances.

Quotes get removed, images should too.

```
		<div class="col-md-3 col-sm-3 teaser hidden-xs">
			<div class="card" style="border-color: #BF1E2E">
												<p>
					<a href="/user/aliceif">
												<img title="aliceif" class="user-img" src="/uploads/profile/834-profileimg.png" />
					</a>
					<a class="permalink" href="/topic/19393/test-image-for-size-test/2">
						<span class="timeago" title="2016-03-22T19:32:02.353Z"></span>
					</a>
				</p>
				<div class="post-content">
					<p>@benlubar, how does this affect front page size? <img src="https://allrgb.com/images/shards.png" alt="a big-ass image"/></p>

				</div>
			</div>
		</div>
```

**Comment by pichalite** [comment]
@barisusakli commit breaks lavender theme as lavender is setup to preview images as well on the categories page

**Comment by loopback0** [comment]
I believe this is superseded by #4594

**Comment by GitPuffy** [comment]
I do not believe this issue has been resolved or the nodebb-theme-lavender (Lavender) theme.

On my main page (home route) images in sub-categories are not being shown.
