### ISSUE TITLE
Highlight color of unread notifications

### ISSUE THREAD

**Issue by FrostCat** [NodeBB/NodeBB#4442]
I realize this is a bit of bikeshedding, but the tannish color is one that common Dell monitors are particularly bad at rendering, meaning that the color fades drastically if you're not looking straight at it.  Since a LOT of people use Dell computers, a color that works better with them should at least be considered--possibly something like the blue used as "last read post" indicator in topics.

Hotmail used the same color to indicate unread messages for YEARS, and I've observed the problem with a variety of Dell monitors and laptop displays.  (I will point out that the color's much more readable on some other brands of monitor like the ASUS I use at home.)

**Comment by psychobunny** [comment]
Hey, I imagine you're from tdwtf - its a simple css change an admin can make in the control panel. In any case, style-specific issues is best reported in the theme repository at

https://github.com/NodeBB/nodebb-theme-persona/issues

FWIW I agree, blue might be best
