### ISSUE TITLE
last read post indicator disappears too soon

### ISSUE THREAD

**Issue by FrostCat** [NodeBB/NodeBB#4444]
If you have a slowish internet connection and/or are reading a topic with a lot of images, the way posts stream in when you jump to the last read post means the browser may reflow the page repeatedly, which can push the indicator up to a couple of viewports' worth of space beyond the bottom of the window.  When this happens, the indicator has usually faded away before you can find it.  At the very least the indicator should probably stick around for, say, 5 seconds after it's come into view, and not after the post it's marking loads.  Also, it may be reasonable to simply leave the indicator there and not fade it out at all, for various reasons.

**Comment by pichalite** [comment]
I think this is already fixed here #4430
