### ISSUE TITLE
scrolltoPost broken?

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4452]
seems like writing a new post is not sending you to your post on 1.x.x

**Comment by nhlpl** [comment]
Please check this setting:
Profile > Settings > Browsing Settings > After posting a reply, show the new post

**Comment by exomarty** [comment]
i dont have that setting @nhlpl

**Comment by nhlpl** [comment]
I have this setting on NodeBB v1.0.2 installed from v1.x.x branch and in NodeBB v1.0.3-auto.0. It fine when using Opera.

What is your browser?

**Comment by exomarty** [comment]
chrome

**Comment by exomarty** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/10746278/13999887/cfabc3ae-f13e-11e5-9110-fd8da197a83f.png)

**Comment by nhlpl** [comment]
Confirmed.

NodeBB v1.0.2
Use `Reply` on the top of the page and `After posting a reply, show the new post` setting is ignored.

**Comment by nhlpl** [comment]
@exomarty 
NodeBB v1.0.2, Material Design 2.6.4 doesn't have this option.

Please test it using default themes and Persona in first place.

Thank you.

**Comment by pichalite** [comment]
@nhlpl he is using persona. that's not material design theme

**Comment by exomarty** [comment]
ok i see it now, change it back to default persona
had to mark and save it several times to make it work
think the option should be on admin zone too to make it default for all

![screenshot_5](https://cloud.githubusercontent.com/assets/10746278/14000751/e3c29544-f142-11e5-9cd6-8abd5adaa0bd.png)

**Comment by nhlpl** [comment]
@pichalite 
Thanks for letting me know. Still learning.

I have found one more bug.

@exomarty 
Profile > Settings > Language > en_GB

**Comment by exomarty** [comment]
i dont use english
anyways seems like the option needs to be unmarked > save > marked > save to make it work from default cause it doesnt work for me on community too

**Comment by julianlam** [comment]
Yeah seems like a bug. The default behaviour is not set properly if the value is undefined

**Comment by julianlam** [comment]
Paging @boomzillawtf for possible fix/PR? :angel:

**Comment by boomzillawtf** [comment]
Huh...I thought it was defaulting to the original behavior. Unfortunately, I'm about to be out of town until next Tuesday and won't be able to do anything serious about it until then.
