### ISSUE TITLE
Feature Request: password:disableEdit

### ISSUE THREAD

**Issue by alexschomb** [NodeBB/NodeBB#4459]
We can opt out the edit function of username and email address, why not add this for passwords, profile picture and maybe profile fields (input disabled) as well?

This would certainly help admins running nodeBB with external authentication methods so they don't have to edit the source code after each update.

**Comment by pauljherring** [comment]
Sorry - why is stopping people changing their authentication credentials a thing? It's like, I dunno, using fingerprints as authentication (http://blog.dustinkirkland.com/2013/10/fingerprints-are-user-names-not.html). Once someone else has them, someone else can authenticate as you, and you can't stop them by changing your fingerprints.

**Comment by alexschomb** [comment]
There are scenarios where one would integrate nodeBB into an existing environment using SSO services or LDAP or a centralized SQL database (my case). Indeed it wouldn't hurt if the users changed their password in nodeBB, but it would be confusing for them because it would have no function at all. When they sign in again the password would be checked against the remote database / SSO service and not against the changed password in the nodeBB (redis) database.

**Comment by alexschomb** [comment]
thanks! that was fast :)
