### ISSUE TITLE
Clear browser cookies upon account deletion

### ISSUE THREAD

**Issue by skyrets** [NodeBB/NodeBB#4460]
Cookies need to be cleared upon account deletion. If not, nodebb shows nothing (shows navbar only) in our browser, even force refresh doesn't help.

**Comment by pichalite** [comment]
is the account using social login Facebook, google+ etc.?

**Comment by skyrets** [comment]
Yep, account is using facebook social and email.

**Comment by barisusakli** [comment]
I think this should be fixed once https://github.com/julianlam/nodebb-plugin-sso-facebook/commit/418e17b80b218794d0fd315c6592ff853b2324c9 is published.

It needs to be added to other sso plugins as well.

**Comment by barisusakli** [comment]
We do delete sessions on account delete, but the sso plugins weren't adding the session info on account creation.

**Comment by julianlam** [comment]
v5.1.0

**Comment by julianlam** [comment]
sso-google v1.2.0
sso-twitter v2.2.0
sso-google v1.1.0
sso-oauth v0.3.0
