### ISSUE TITLE
sockets closed issue

### ISSUE THREAD

**Issue by iDevPro** [NodeBB/NodeBB#4462]
```
https://domain.tld/groups?sort=count
//result: server 127.0.0.1:27017 sockets closed
```

**Comment by barisusakli** [comment]
nodebb version? git hash?

**Comment by iDevPro** [comment]
hash: 3d815fff722f8181788a55222ba15d990a574b7b
v1.0.1

**Comment by iDevPro** [comment]
```
group:{"name":"cid:5:privileges:groups:topics:reply","slug":"cid-5-privileges-groups-topics-reply","createtime":1455571405123,"userTitle":"cid:5:privileges:groups:topics:reply","description":"","memberCount":2,"deleted":0,"hidden":1,"system":1,"private":1,"disableJoinRequests":0} type:object

group:{"memberCount":-5} type:object // this call error 

24/3 21:58 [27453] - error: TypeError: This library (validator.js) validates strings only
```

**Comment by barisusakli** [comment]
Yes that group shouldn't be visible to regular users, where do you see it?

**Comment by iDevPro** [comment]
Nav -> Groups -> Set sort (Count)

**Comment by barisusakli** [comment]
Is this a fresh install or did you ugprade from an older version ie 0.9.x? You will probably have to remove that group from the db manually. 

If you are using mongodb do

```
db.objects.remove({_key:"groups:visible:memberCount", value":"cid:5:privileges:groups:topics:reply"});
```

If you are using redis do 

```
zrem groups:visible:memberCount cid:5:privileges:groups:topics:reply
```

Also update to latest stable which is 1.0.2

**Comment by iDevPro** [comment]
SyntaxError: Unexpected string

**Comment by barisusakli** [comment]
Sorry made a typo in the query it should be 
`db.objects.remove({_key:"groups:visible:memberCount", "value":"cid:5:privileges:groups:topics:reply"});`

**Comment by iDevPro** [comment]
error: TypeError: This library (validator.js) validates strings only :(

**Comment by barisusakli** [comment]
Yeah you seem to have a ghost group in your database `group:{"memberCount":-5} type:object // this call error `.

You will have to remove that or update to master to get rid of that crash.

**Comment by iDevPro** [comment]
<img width="844" alt="2016-03-24 22 40 53" src="https://cloud.githubusercontent.com/assets/1888230/14029147/8554478a-f211-11e5-8fae-ea2737fe210d.png">

I have this records with -5

**Comment by barisusakli** [comment]
You can safely remove all `cid:*:privileges:*` groups from `groups:visible:memberCount`

**Comment by iDevPro** [comment]
ok, but how i can remove system groups from this page ?)

**Comment by barisusakli** [comment]
Using the query 
```
db.objects.remove({_key:"groups:visible:memberCount", "value":"cid:5:privileges:groups:topics:reply"});
```
Just replace the value with the name of the group.

**Comment by iDevPro** [comment]
No, i want remove this groups from list on this page :)

**Comment by iDevPro** [comment]
Ohh, i remove some groups :(

**Comment by iDevPro** [comment]
/admin/manage/groups%7Bgroups.nameEncoded%7D 

but can update as /admin/manage/groups/administrators :))))
