### ISSUE TITLE
profile mobile layout 

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4464]
a little messed

![screenshot_8](https://cloud.githubusercontent.com/assets/10746278/14015298/492fdfe8-f1b8-11e5-8a89-ca4857331c81.png)

![screenshot_9](https://cloud.githubusercontent.com/assets/10746278/14015399/ed0a8fb4-f1b8-11e5-802b-fec658fa0e90.png)

**Comment by julianlam** [comment]
iPhone 5, I presume? :smile:

**Comment by exomarty** [comment]
5s and 6s. Similar results :dancer:

**Comment by julianlam** [comment]
The 6 has a higher resolution, and should not exhibit the bug in the top picture, at least...?
