### ISSUE TITLE
dropdown menus can go off-screen

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4471]
Reported in https://what.thedailywtf.com/topic/19330/mentioning-people-on-mobile-results-in-popup-going-off-screen

![](https://what.thedailywtf.com/uploads/files/1458562536741-screenshot_2016-03-21-12-11-18.png)

Ref: apapadimoulis/what-bugs#5

**Comment by julianlam** [comment]
We were on jquery textcomplete v0.7.3 :smile: 

@yuku-t released 1.3.1 a couple days ago with a new carat position detection library, and that seems to work much better.

It still clips if the list opens below the keyboard/viewport, but... that's a minor issue I think :smile:
