### ISSUE TITLE
Ipad sidebar bug 

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4483]
![image](https://cloud.githubusercontent.com/assets/10746278/14126806/e3564972-f613-11e5-9fce-79f4cf3b977b.jpeg)

**Comment by pichalite** [comment]
this issue belongs on the persona theme repository. https://github.com/NodeBB/nodebb-theme-persona

**Comment by barisusakli** [comment]
Is it happening on en_GB as well?

**Comment by exomarty** [comment]
Yes @barisusakli 
Actually not sure if this is new feature but ipad use desktop layout so never used navbar

**Comment by pichalite** [comment]
the navigation links are not displaying text because the "Text Class" for navigation items is set to be "visible-xs-inline" by default in ACP so they only show up on xs screens. The sidebar should probably be disabled sm and larger layouts coz the navigation items are already on the header.
