### ISSUE TITLE
Localhost links in emails

### ISSUE THREAD

**Issue by crobinson42** [NodeBB/NodeBB#4494]
I have configured `config.json` appropriately but I still seem to see links with `localhost:4567` in emails (ie: weekly digest email).

config.json
```
{
    "url": "http://community.therms.io",
    "secret": "xxxxxxx- xxx-x x--53064",
    "database": "mongo",
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "xxxx",
        "password": "xxxx",
        "database": "nodeBB"
    }
}
```

**Comment by julianlam** [comment]
Have you restarted your NodeBB after changing `config.json`?

**Comment by julianlam** [comment]
Please continue this discussion in our support forum, if the problem persists after a restart. Thanks!

**Comment by crobinson42** [comment]
I restarted via the admin panel ‘restart’ button. Does that not update the configs?
