### ISSUE TITLE
colorpicker script included on group page for owners but not colorpicker css

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4502]
Group owners see this at the bottom of the groups pages. For example, admins see it at the bottom of `/groups/administrators`:

![screenshot 2016-04-07 at 10 25 32](https://cloud.githubusercontent.com/assets/4257305/14356604/29fe6b3c-fcab-11e5-8fe2-30e12e3797a2.png)

Adding `/vendor/colorpicker/colorpicker.css` as a stylesheet using Chrome's developer tools fixes this.

**Comment by RaceProUK** [comment]
Oh, so _that's_ what it is!
