### ISSUE TITLE
Is there any plan to build mobile client ?

### ISSUE THREAD

**Issue by Samurais** [NodeBB/NodeBB#4514]
I know the experience is good with mobile browser. But it would be even great if we have iOS App. 
So, is there any plan to build it ?

**Comment by nhlpl** [comment]
Julian already answered here:
https://community.nodebb.org/topic/8179/is-there-any-development-plan-for-app-ios-android/6

**Comment by julianlam** [comment]
Thank you @nhlpl :smile:

**Comment by Samurais** [comment]
@nhlpl thanks.
