### ISSUE TITLE
Why the restrictive license?

### ISSUE THREAD

**Issue by lbmn** [NodeBB/NodeBB#4518]
Why the restrictive GPLv3 license?  This is very unusual for the NodeJS ecosystem, which strongly perfers the perfect MIT license.  The statist anti-market ideology that was behind the GPL fad has only hurt the Free Software movement, and thankfully it is now in decline.

For [pacifist philosophical reasons](http://forum.freestateproject.org/index.php?topic=19771.0), I would never use anything that came with legal threats backed by force.  This position is increasingly common, especially for Node developers.  Just one example, [quoting a top node module dev](https://qnalist.com/questions/5523655/preferred-license-for-node-modules):

> I have zero dependencies on GPL modules for that reason and won't use any npm modules that are under the GPL licence. If you like collaboration or want people to use your code you should licence it as MIT, because it's virtually the community standard. (Meteor released with GPL a while back and was hitting back by the community and changed to MIT)

You can Google for "copyleft harmful", "GPL sucks", "GPL hurts free software", etc to find a lot more arguments from people of many different philosophical backgrounds.  You are alienating a significant and **growing** fraction of your potential users and contributors, many of whom have switched to NodeJS exclusively due to licensing!

See [copyfree.org/standard/licenses](http://copyfree.org/standard/licenses) for a large selection of licenses that are **genuine** Free Software.

No disrespect intended.  I hope you won't respond with hostility.  Obviously you can do whatever the heck you want.  Have a nice day.

**Comment by psychobunny** [comment]
Hi, so we have a very modular plugin and theming system, and those modules are ok to have any license you wish (all my plugins are MIT, FWIW)

If you customize your forum like that, you don't have to worry about releasing your code nor would we ever want to sue you for anything like that. There are plenty of highly customised NodeBB instances that go that route.

We also have a commercial license available if you really need it (we have to eat somehow!)

**Comment by psychobunny** [comment]
Closing because it's not an actual issue per se, although the topic is more than welcome to be discussed on our community forum :)
