### ISSUE TITLE
When grunt reloads NodeBB, verbose logging terminates

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4520]
Perhaps @frissdiegurke can reproduce and fix :wink:

**Comment by frissdiegurke** [comment]
https://github.com/NodeBB/NodeBB/blob/master/Gruntfile.js#L16-L18

:stuck_out_tongue:

**Comment by frissdiegurke** [comment]
Use that either for the initial call too or don't use it...
