### ISSUE TITLE
profile links preview on signature

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4524]
this breaks a little the layout

![screenshot_7](https://cloud.githubusercontent.com/assets/10746278/14571757/467b954a-034b-11e6-8785-18bf33fefcc1.png)

**Comment by pichalite** [comment]
iframely should probably ignore links in signatures

**Comment by julianlam** [comment]
Tough problem here is that we only have `filter:parse.post` and `filter:parse.raw`, though I suppose iframely should not parse links from `parse.raw`?

/cc @nleush for comments

**Comment by nleush** [comment]
`filter:parse.raw` used for preview in editor...

So I'm confused about decision for this case.

**Comment by julianlam** [comment]
Right... that slipped my mind. I suppose it's between:

* not having IFramely parsing on `parse.raw`, or
* we add additional hooks for parsing
* we filter out html in signature

**Comment by julianlam** [comment]
@barisusakli Should we add a new hook `filter:parse.text`, for use in the places where we "parse as post" right now:

* category description
* profile "about me"
* terms of use
* group description
* chat message (may want to break this out to `filter:parse.chat`
* signature (may want to break this out to `filter:parse.signature`)

**Comment by barisusakli** [comment]
we already have `filter:parse.signature` We can add a `filter:parse.aboutme` and that should solve the problem?
