### ISSUE TITLE
Reputation stats are shown in profile even if reputation system is deactivated

### ISSUE THREAD

**Issue by globalcow** [NodeBB/NodeBB#4525]
I have the reputation system deactivated in my forum. However, in the user profile the reputation is still displayed without the actual number. See attached screenshot (german). NodeBB 1.0.3

<img width="644" alt="nodebb_profile" src="https://cloud.githubusercontent.com/assets/2294737/14575086/e6d1a976-035f-11e6-9525-1626d63606c7.png">

**Comment by julianlam** [comment]
Can you let us know if this is persona theme a fork of it?

**Comment by globalcow** [comment]
It's the original persona theme.

**Comment by globalcow** [comment]
The problem still exists in 1.1.0

**Comment by julianlam** [comment]
Thanks @globalcow

**Comment by pichalite** [comment]
Can't reproduce... works fine for me on NodeBB v1.1.0.

**Comment by globalcow** [comment]
@pichalite @julianlam I am using NodeBB v1.1.0 and the persona theme v4.1.7 and the error still exists. Is there anything I can check or could have done wrong?

**Comment by pichalite** [comment]
@globalcow check the api for the user profile and see what value you have for `reputation:disabled`

e.g;
https://community.nodebb.org/api/user/pichalite

**Comment by globalcow** [comment]
@pichalite I checked the api and everything was ok. But I found a plugin which I modified and which modifies the profile template. That's why a never got the new version of the profile template :-( So, everything works fine now! Thank you very much for your help!
