### ISSUE TITLE
Composer needs big improvements or refactor on mobile

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4526]
i did this videos 8 months ago
https://community.nodebb.org/topic/6355/in-page-composer-is-it-possible/7
since this time many editions been made to nodebb and some to composer but its still terrible on mobile

i did now 2 new videos, so here is the proof of current situation
did the test on last ios 9.3.1 with safari and chrome browser on iPhone 5s, i have ipad2 and iphone6s and results are similar or worst

tried to quote long post, short ones and made some replies to test all kind of situations with always random results.
thanks for your time and this amazing software

https://www.youtube.com/watch?v=B8fUJeg3Y6o
https://www.youtube.com/watch?v=0amN7MLjj2I

**Comment by pitaj** [comment]
When I get a chance, I'm going to refactor it with a strong use of CSS. That should make things about 100x better. The planned refactor is *third* on my list, after a personal project and finished the calendar plugin.

**Comment by exomarty** [comment]
100x better sounds good to me 😄 
we waiting some kind of solution to update to 1.0

**Comment by exomarty** [comment]
Wondering if this will happen any soon.ñ or i'm alone in this battle :D Ping @julianlam and RFC

**Comment by pitaj** [comment]
You're gonna have to give us some time. These things don't happen quickly,
especially when people are busy.

**Comment by psychobunny** [comment]
Check out composer 4.0.3, seems to be pretty good on both iOS and Android :+1: 

Re-open individual issues on nodebb-plugin-composer-default if you find any
