### ISSUE TITLE
nodebb auto restart every time when users click notifications.

### ISSUE THREAD

**Issue by dongyueLi** [NodeBB/NodeBB#4527]
Im running with the nodebb 1.0.2.

Every time when users click the notification button, nodebb will auto restart. And the notification loads nothing, you can not see the notifications.

log is reported as follow:

Type Ctrl-C to exit

16/4 21:13 [1334] - info: [app] Database connection closed.
16/4 21:13 [1334] - info: [app] Web server closed to connections.
16/4 21:13 [1334] - info: [app] Shutdown complete.
[cluster] Child Process (1334) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
16/4 21:14 [1352] - info: Time: Sat Apr 16 2016 21:14:00 GMT+0800 (CST)
16/4 21:14 [1352] - info: Initializing NodeBB v1.0.2
16/4 21:14 [1352] - info: NodeBB Ready
16/4 21:14 [1352] - info: Enabling 'trust proxy'
16/4 21:14 [1352] - info: NodeBB is now listening on: 0.0.0.0:4567
16/4 21:17 [1352] - error: TypeError: Cannot call method 'replace' of undefined
    at S.decodeHtmlEntities (/nodebb/node_modules/string/lib/string.js:140:13)
    at /nodebb/src/notifications.js:453:60
    at Array.forEach (native)
    at /nodebb/src/notifications.js:426:20
    at Array.reduce (native)
    at Object.Notifications.merge (/nodebb/src/notifications.js:403:28)
    at /nodebb/src/user/notifications.js:96:19
    at fn (/nodebb/node_modules/async/lib/async.js:746:34)
    at /nodebb/node_modules/async/lib/async.js:1213:16
    at /nodebb/node_modules/async/lib/async.js:166:37
TypeError: Cannot call method 'replace' of undefined
    at S.decodeHtmlEntities (/nodebb/node_modules/string/lib/string.js:140:13)
    at /nodebb/src/notifications.js:453:60
    at Array.forEach (native)
    at /nodebb/src/notifications.js:426:20
    at Array.reduce (native)
    at Object.Notifications.merge (/nodebb/src/notifications.js:403:28)
    at /nodebb/src/user/notifications.js:96:19
    at fn (/nodebb/node_modules/async/lib/async.js:746:34)
    at /nodebb/node_modules/async/lib/async.js:1213:16
    at /nodebb/node_modules/async/lib/async.js:166:37
16/4 21:17 [1352] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
16/4 21:17 [1352] - info: [app] Database connection closed.
16/4 21:17 [1352] - info: [app] Web server closed to connections.
16/4 21:17 [1352] - info: [app] Shutdown complete.
[cluster] Child Process (1352) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
16/4 21:17 [1413] - info: Time: Sat Apr 16 2016 21:17:53 GMT+0800 (CST)
16/4 21:17 [1413] - info: Initializing NodeBB v1.0.2
16/4 21:18 [1413] - info: NodeBB Ready
16/4 21:18 [1413] - info: Enabling 'trust proxy'
16/4 21:18 [1413] - info: NodeBB is now listening on: 0.0.0.0:4567
blacklist returned: undefined
16/4 21:23 [1413] - error: TypeError: Cannot call method 'replace' of undefined
    at S.decodeHtmlEntities (/nodebb/node_modules/string/lib/string.js:140:13)
    at /nodebb/src/notifications.js:453:60
    at Array.forEach (native)
    at /nodebb/src/notifications.js:426:20
    at Array.reduce (native)
    at Object.Notifications.merge (/nodebb/src/notifications.js:403:28)
    at /nodebb/src/user/notifications.js:96:19
    at fn (/nodebb/node_modules/async/lib/async.js:746:34)
    at /nodebb/node_modules/async/lib/async.js:1213:16
    at /nodebb/node_modules/async/lib/async.js:166:37
TypeError: Cannot call method 'replace' of undefined
    at S.decodeHtmlEntities (/nodebb/node_modules/string/lib/string.js:140:13)
    at /nodebb/src/notifications.js:453:60
    at Array.forEach (native)
    at /nodebb/src/notifications.js:426:20
    at Array.reduce (native)
    at Object.Notifications.merge (/nodebb/src/notifications.js:403:28)
    at /nodebb/src/user/notifications.js:96:19
    at fn (/nodebb/node_modules/async/lib/async.js:746:34)
    at /nodebb/node_modules/async/lib/async.js:1213:16
    at /nodebb/node_modules/async/lib/async.js:166:37
16/4 21:23 [1413] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
16/4 21:23 [1413] - info: [app] Database connection closed.
16/4 21:23 [1413] - info: [app] Web server closed to connections.
16/4 21:23 [1413] - info: [app] Shutdown complete.
[cluster] Child Process (1413) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
16/4 21:23 [1435] - info: Time: Sat Apr 16 2016 21:23:57 GMT+0800 (CST)
16/4 21:23 [1435] - info: Initializing NodeBB v1.0.2
16/4 21:24 [1435] - info: NodeBB Ready
16/4 21:24 [1435] - info: Enabling 'trust proxy'
16/4 21:24 [1435] - info: NodeBB is now listening on: 0.0.0.0:4567

**Comment by julianlam** [comment]
Please update to v1.0.3 and try again, thanks!

**Comment by dongyueLi** [comment]
Thank, upgrading fix it!
