### ISSUE TITLE
 Unable to parse library for: nodebb-plugin-markdown

### ISSUE THREAD

**Issue by dongyueLi** [NodeBB/NodeBB#4528]
I just upgrade my nodebb to 1.0.3. when I restart, it says:

Type Ctrl-C to exit

    at /nodebb/node_modules/nodebb-plugin-markdown/index.js:4:19
    at Object.<anonymous> (/nodebb/node_modules/nodebb-plugin-markdown/index.js:239:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
16/4 22:05 [1567] - warn: [plugins] Unable to parse library for: nodebb-plugin-markdown
16/4 22:05 [1567] - info: NodeBB Ready
16/4 22:05 [1567] - info: Enabling 'trust proxy'
16/4 22:05 [1567] - info: NodeBB is now listening on: 0.0.0.0:4567

The markdown can not be used now. For now when I post, I can not use Markdown plugin....

**Comment by julianlam** [comment]
Reinstall markdown library from npm to see if issue persists.

**Comment by dongyueLi** [comment]
Hi Julianlam,

Thank you, it works again! Reinstall it from npm and restart nodebb!
