### ISSUE TITLE
need a property in 

### ISSUE THREAD

**Issue by Samurais** [NodeBB/NodeBB#4531]
hi, folks

in this file, we need a key. ```digest.subject ```.

https://github.com/NodeBB/NodeBB/blob/master/public/language/zh_CN/email.json#L19

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/blob/master/public/language/en_GB/email.json#L34

@julianlam just needs to be pushed to transifex/

**Comment by julianlam** [comment]
Available for translation now, thanks.
