### ISSUE TITLE
TypeError: Cannot read property 'messageId' of undefined 0.9.x

### ISSUE THREAD

**Issue by thelaw44** [NodeBB/NodeBB#4533]
Still can't find a way to solve this issue. I am getting restarts rapidly. 

Maybe deleting all chats will solve this but couldn't find a way to do it too. If someone share me a method to do it I will be really happy

Let me share logs from ./nodebb dev
```
messages:uid:3:to:106
17/4 15:56 [13159] - error: TypeError: Cannot read property 'messageId' of undefined
    at /home/HFL/Forum/NodeBB/src/messaging.js:286:54
    at fn (/home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:746:34)
    at /home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:1213:16
    at /home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:166:37
    at /home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:706:43
    at /home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:1206:34)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
TypeError: Cannot read property 'messageId' of undefined
    at /home/HFL/Forum/NodeBB/src/messaging.js:286:54
    at fn (/home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:746:34)
    at /home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:1213:16
    at /home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:166:37
    at /home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:706:43
    at /home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/home/HFL/Forum/NodeBB/node_modules/async/lib/async.js:1206:34)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
17/4 15:56 [13159] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
17/4 15:56 [13159] - info: [app] Database connection closed.
17/4 15:56 [13159] - info: [app] Web server closed to connections.
17/4 15:56 [13159] - info: [app] Shutdown complete.

```

**Comment by julianlam** [comment]
Are you unable to update to v1.x.x?

**Comment by thelaw44** [comment]
Yes unfortunately, coded lots of things behind now I am really stuck :(

**Comment by thelaw44** [comment]
At the moment secured server from crashing with modifying the messaging.js a bit.

` if(messages[0]){
                                                async.waterfall([
                                                        async.apply(db.sortedSetRank, key, messages[0].messageId),
                                                        function(index, next) {
                                                                // Continue only if this isn't the first message in sorted set
                                                                if (index > 0) {
                                                                        db.getSortedSetRange(key, index-1, index-1, next);
                                                                } else {
                                                                        messages[0].newSet = true;
                                                                        return next(undefined, messages);
                                                                }
                                                        },
                                                        function(mid, next) {
                                                                Messaging.getMessageFields(mid, ['fromuid', 'timestamp'], next);
                                                        }
                                                ], function(err, fields) {
                                                        if (err) {
                                                                return next(err);
                                                        }

                                                        if (
                                                                (parseInt(messages[0].timestamp, 10) > parseInt(fields.timestamp, 10) + (1000*60*5)) ||
                                                                (parseInt(messages[0].fromuid, 10) !== parseInt(fields.fromuid, 10))
                                                        ) {
                                                                // If it's been 5 minutes, this is a new set of messages
                                                                messages[0].newSet = true;
                                                        }

                                                        next(undefined, messages);
                                                });
                                              }`

**Comment by julianlam** [comment]
Backported a3dc427e671ce8af059a8ceb85fe99192f41544e
