### ISSUE TITLE
bug report 

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#4538]
chrome console:
    http://forum.sanatisharif.ir/uploads/_imported_profiles/_3_x6ixh.jpg Failed to load resource: the server responded with a status of 503 (Service unavailable)
http://forum.sanatisharif.ir/api/widgets/render?v=a2b9a28c-9075-4fc7-b131-9…locations%5B%5D=footer&locations%5B%5D=header&template=categories.tpl&url= Failed to load resource: the server responded with a status of 503 (Service unavailable)
http://forum.sanatisharif.ir/templates/modules/taskbar.tpl?v=a2b9a28c-9075-4fc7-b131-9a0dfa8b30b8 Failed to load resource: the server responded with a status of 503 (Service unavailable)
nodebb.min.js:11 Uncaught Error: Unable to load template: modules/taskbar (Service unavailable)$.ajax.error @ nodebb.min.js:11u @ nodebb.min.js:1f.fireWith @ nodebb.min.js:1$ @ nodebb.min.js:3i @ nodebb.min.js:3
nodebb.min.js:4 WebSocket connection to 'ws://forum.sanatisharif.ir/socket.io/?EIO=3&transport=websocket&sid=C4jVT9v2s2v0gTWsAACM' failed: Error during WebSocket handshake: Unexpected response code: 503
nodebb.min.js:8 Uncaught Error: Load timeout for modules: buzz,mousetrap
http://requirejs.org/docs/errors.html#timeoutB @ nodebb.min.js:8d @ nodebb.min.js:9(anonymous function) @ nodebb.min.js:9
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgY97C&sid=C4jVT9v2s2v0gTWsAACM Failed to load resource: the server responded with a status of 503 (Service unavailable)
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgY9FC&sid=C4jVT9v2s2v0gTWsAACM Failed to load resource: the server responded with a status of 503 (Service unavailable)
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgY9-m&sid=cAYIbbH2P21nv6JUAACO Failed to load resource: the server responded with a status of 503 (Service unavailable)
nodebb.min.js:4 WebSocket connection to 'ws://forum.sanatisharif.ir/socket.io/?EIO=3&transport=websocket&sid=cAYIbbH2P21nv6JUAACO' failed: WebSocket is closed before the connection is established.
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgY979&sid=C4jVT9v2s2v0gTWsAACM Failed to load resource: net::ERR_EMPTY_RESPONSE
http://forum.sanatisharif.ir/src/modules/buzz.js?a2b9a28c-9075-4fc7-b131-9a0dfa8b30b8 Failed to load resource: net::ERR_EMPTY_RESPONSE
nodebb.min.js:8 Uncaught Error: Script error for: buzz
http://requirejs.org/docs/errors.html#scripterrorB @ nodebb.min.js:8k.onScriptError @ nodebb.min.js:9
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgYBmQ&sid=L0i_5Y44nftambcnAACP Failed to load resource: net::ERR_EMPTY_RESPONSE
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgYDRA Failed to load resource: the server responded with a status of 503 (Service unavailable)
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgYE5M Failed to load resource: the server responded with a status of 503 (Service unavailable)
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgYFR3 Failed to load resource: the server responded with a status of 503 (Service unavailable)
http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgYGlA Failed to load resource: the server responded with a status of 503 (Service unavailable)
XHR finished loading: GET "http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgYI0n".
nodebb.min.js:4 WebSocket connection to 'ws://forum.sanatisharif.ir/socket.io/?EIO=3&transport=websocket&sid=QgmQziFuB_vaS9mMAACa' failed: Error during WebSocket handshake: Unexpected response code: 503
XHR finished loading: GET "http://forum.sanatisharif.ir/socket.io/?EIO=3&transport=polling&t=LGgYIjr&sid=QgmQziFuB_vaS9mMAACa".

**Comment by julianlam** [comment]
No client-side errors reported by two staff members, please investigate your ISP as possibly blocking websockets or websocket-like data.
