### ISSUE TITLE
the back key sometime works well， sometime can not work

### ISSUE THREAD

**Issue by gaokaigithub** [NodeBB/NodeBB#4541]

**Comment by psychobunny** [comment]
Can you provide some more detailed reproduction steps please?

**Comment by gaokaigithub** [comment]
just like this
![default](https://cloud.githubusercontent.com/assets/17917275/14624039/7cf0a4c4-0609-11e6-92cc-ff7e6c135e45.PNG)

**Comment by psychobunny** [comment]
Any errors in your browser console?

**Comment by gaokaigithub** [comment]
there is an error
![123](https://cloud.githubusercontent.com/assets/17917275/14624163/d34335ca-060a-11e6-9caf-d9452f99b0a1.PNG)

**Comment by psychobunny** [comment]
fixed on latest master

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/9d6532fe7ba133ef9fe4c9fb8b80ed5b98c3d0d3

**Comment by pichalite** [comment]
what happens to this enhancement https://github.com/NodeBB/NodeBB/commit/3390b7d7f6e9b4f6bd5f0bc6a5d554c21eb2b9ff that introduced this regression now that most of it is reverted?

**Comment by julianlam** [comment]
Enhancement should be intact, I don't think my moving that specific block impacted the functionality of the code.
