### ISSUE TITLE
ACP: Add button to revoke all session

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#4544]
When you change the domain name for the session cookie within the ACP, you still have old cookies with the old domain remaining. This is until a session gets invalid and express.js creates a new session thought.
This is one reason one could use a "revoke all sessions" button within the ACP.
Maybe you should also consider doing this action automatically on the restart after domain change.

**Comment by ArcticRaz0r** [comment]
Bump. It's actually a really good idea, it would avoid us the trouble of having to manually access the DB
