### ISSUE TITLE
Admin Invite behaviour is not immediately apparent

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4545]
When enabling "Admin Invite" as a registration option, it is not immediately apparent how invitations can be sent out.

An "invite" button gets added to `/users`, but:

* [ ] it should also be in `/admin/manage/users`
* [ ] *optionally*, there should be help text explaining how to invite users

**Comment by pichalite** [comment]
:+1:

**Comment by julianlam** [comment]
Also I think it would be a good step to splice out invite functionality out of the "Registration Types" setting, since some forums may want to use "Admin Approval" but also invite users...
