### ISSUE TITLE
unread is not localized

### ISSUE THREAD

**Issue by rjvdboon** [NodeBB/NodeBB#4552]
For the unread page the following resources only exist in en_GB:
```
	"all-topics": "All Topics",
	"new-topics": "New Topics",
	"watched-topics": "Watched Topics"
```
They also do not show at Transifex, so I can't provide the Dutch translation, causing the unread page to have a dropdown `["all-topics", "new-topics", "watched-topics"]` instead of `["Alle topics", "Nieuwe topics", "Gemarkeerde(?) topics"]` (where 'topics' could be translated as 'onderwerpen' as well, not sure what is the consensus...)

**Comment by julianlam** [comment]
Odd... in any case, the `unread` asset has been pushed up to Transifex now.

**Comment by julianlam** [comment]
Thanks for reporting! :smile:
