### ISSUE TITLE
ACP: Show "Settings" button in plugin list

### ISSUE THREAD

**Issue by rbeer** [NodeBB/NodeBB#4563]
Hi there!
I got another UX itch. :smiling_imp:

How about adding a "Settings" buttons in the list of "Installed Plugins" to plugins that add a menu item?
As activation of a plugin goes
- "Activate"
- _reload_
- _refresh page_ (i.e. land in the list again),

the user might be tempted to scroll to the plugins entry to check its status after the reload.

Unfortunately, adding another button to the horizontal layout could displace the description to a point where it becomes rather crowded (mobile and smaller screens; not so much an issue on HD resolution).

![composed_h_mobile.png](http://i.imgur.com/L0UPpjX.png)

Generally placing the buttons vertically doesn't look that bad, though.

![composed_v_mobile.png](http://i.imgur.com/sGt8wPH.png)

I mocked up one button white, one blue, 'cause I thought yet another button color would look like a paint bucket had exploded. Although the black (vs. otherwise white) font-color seems even more disturbing.

---

Much less a matter of taste is the empty page, when clicking "Upgradable Plugins" while all are up to date.

![empty_upgradable.png](http://i.imgur.com/lSQ2WL6.png)

---

I'd care about the changes. Just wanna make sure, I don't go all YAGNI again. :smile: 

---

NodeBB/NodeBB@ae607b4
GNU/Linux Debian, NodeJS v5.10.1, Chrome 50.0.2661.86

**Comment by psychobunny** [comment]
Sounds like a good idea :)

**Comment by rbeer** [comment]
Rainy sunday, here I come! :smiley:
I'll PR it then.

**Comment by pichalite** [comment]
👍 yes blue ones please

**Comment by julianlam** [comment]
> I mocked up one button white, one blue, 'cause I thought yet another button color would look like a paint bucket had exploded

I believe our friends at Discourse refer to it as clown vomit :smile:
