### ISSUE TITLE
Scrolling category list when moving topic

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/NodeBB#4564]
If you have a lot of categories at your site, they might not all fit on the page when moving a topic:

![image](https://cloud.githubusercontent.com/assets/13367628/14767569/f5d321dc-09f6-11e6-907f-78461d19c047.png)

I think it would be better to limit the size and make the category list scroll, keeping the close and move buttons visible at the bottom.

**Comment by asdf-tdwtf** [comment]
Not entirely unrelated: The category selector in /unread can also get pretty large, and doesn't even show the hierarchy. Maybe the category selector should look like a file browser: By default, only the top-level categories are shown, and those can be expanded to show the subcategories.
