### ISSUE TITLE
postbar harcoded?

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4565]
not sure why adding post-bar.tpl ads the postbar on first post and on the bottom of page, how can i achieve to have only one like it was on previous versions?
i think it gets duplicated by nodebb code and not managed by the theme 

thank you

**Comment by julianlam** [comment]
Yes this is correct, [this method](https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic/posts.js#L335-L343) ensures that there is always a post bar under the main post, and hides the post bar if there are fewer than two replies.

**Comment by exomarty** [comment]
https://community.nodebb.org/topic/8588/upgrade-nodebb-to-latest-version-on-docker/2

I see two bars there

**Comment by julianlam** [comment]
Might be two posts total

**Comment by pichalite** [comment]
you will see two post bars if there is atleast one reply. May be that needs to be increased?

https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic/posts.js#L338

**Comment by exomarty** [comment]
any reason to hardcode this in core instead of theme?
...for custom themes, i like having only 1 postbar and maybe i want it before first post, or only at the end, that append will always set it after first post,
or maybe i want two differentes bars layouts
that way we have to create new classes and templates to bypass this 

thanks for the replies

**Comment by psychobunny** [comment]
Sounds like something that could be moved into themes, although because all three core themes have the same post bar layout it would be the same code copied three times. Could be made modular maybe...
