### ISSUE TITLE
Group public chat room

### ISSUE THREAD

**Issue by lnxseed** [NodeBB/NodeBB#4579]
The present group chat only private chat room . it is good if add group public chat room, it is a fixed room for group members.
https://community.nodebb.org/groups/gnu-linux-user

**Comment by julianlam** [comment]
Hi there @lnxseed -- I feel that this may be better done as a plugin, as the groups are kept deliberately simple. Perhaps @Schamper's shoutbox plugin can be modified to introduce a widget to enable a shoutbox on a per-group basis?

**Comment by Schamper** [comment]
That's kinda the direction I was taking it towards the last time I worked on it (as in, actually allowing multiple shoutboxes per page, permission based was the next step). It wasn't quite there yet, but at least it's closer that it ever was :)

**Comment by FaizanZahid** [comment]
Sounds good  @schamper .. Looking forward towards it
