### ISSUE TITLE
image upload problem

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#4580]
29/4 00:07 [3875] - verbose: Saving file 1461902835930-4tlybqz.jpg to : /home/yasin/nodebb/public/uploads/files/1g
29/4 00:07 [3875] - error: TypeError: Object #<Object> has no method 'parse'
    at /home/yasin/nodebb/src/controllers/uploads.js:75:24
    at fn (/home/yasin/nodebb/node_modules/async/lib/async.js:746:34)
    at /home/yasin/nodebb/node_modules/async/lib/async.js:1213:16
    at /home/yasin/nodebb/node_modules/async/lib/async.js:166:37
    at /home/yasin/nodebb/node_modules/async/lib/async.js:706:43
    at /home/yasin/nodebb/node_modules/async/lib/async.js:167:37
    at /home/yasin/nodebb/node_modules/async/lib/async.js:1209:30
    at /home/yasin/nodebb/src/controllers/uploads.js:188:3
    at ReadStream.<anonymous> (/home/yasin/nodebb/src/file.js:31:3)
    at ReadStream.emit (events.js:117:20)
TypeError: Object #<Object> has no method 'parse'
    at /home/yasin/nodebb/src/controllers/uploads.js:75:24
    at fn (/home/yasin/nodebb/node_modules/async/lib/async.js:746:34)
    at /home/yasin/nodebb/node_modules/async/lib/async.js:1213:16
    at /home/yasin/nodebb/node_modules/async/lib/async.js:166:37
    at /home/yasin/nodebb/node_modules/async/lib/async.js:706:43
    at /home/yasin/nodebb/node_modules/async/lib/async.js:167:37
    at /home/yasin/nodebb/node_modules/async/lib/async.js:1209:30
    at /home/yasin/nodebb/src/controllers/uploads.js:188:3
    at ReadStream.<anonymous> (/home/yasin/nodebb/src/file.js:31:3)
    at ReadStream.emit (events.js:117:20)
29/4 00:07 [3875] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
29/4 00:07 [3875] - info: [app] Database connection closed.
29/4 00:07 [3875] - info: [app] Web server closed to connections.
29/4 00:07 [3875] - info: [app] Shutdown complete.
[cluster] Child Process (3875) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
29/4 00:07 [3893] - verbose: * using configuration stored in: /home/yasin/nodebb/config.json
29/4 00:07 [3893] - info: Time: Fri Apr 29 2016 00:07:16 GMT-0400 (EDT)
29/4 00:07 [3893] - info: Initializing NodeBB v1.0.3

**Comment by barisusakli** [comment]
Is this happening when you upload an image to a post? What is your nodebb git revision & nodejs version?

**Comment by pikshub** [comment]
1. Yes
2. commit:  1d5635761163facac81c81f429ee94893c302914 / up composer
3 : node: v0.10.33

**Comment by pikshub** [comment]
the problem is ongoing.

**Comment by pikshub** [comment]
node: v6.0.0
fix the problem. Thank you.
