### ISSUE TITLE
ability to disable CSRF token.

### ISSUE THREAD

**Issue by Caes95** [NodeBB/NodeBB#4581]
Hi would be wonderful if in the ACP we could disable the CSRF token.

Thanks you.

**Comment by psychobunny** [comment]
why?

**Comment by Caes95** [comment]
bad way to solve a forbidden problem, sorry.

**Comment by LudwikJaniuk** [comment]
I'd like to be able to disable it to be able to freely post to my forum with scripts. So that's one reason...

**Comment by pitaj** [comment]
You want to use the write API plugin for that.

**Comment by LudwikJaniuk** [comment]
Oh there is a plugin for that, how nice, thank you

**Comment by guijun** [comment]
looking for a way to disable csrf because I want to login user with bearer token 。。。

**Comment by julianlam** [comment]
You cannot log in the user with a bearer token, that is meant for the write API.

You are probably looking for the session-sharing plugin.
