### ISSUE TITLE
Category Mods should be able to view a list of flagged posts

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4586]
Probably the flags page for global mods/admins, but extended down to individual category mods.

`/category/1/announcements/flags`?

**Comment by psychobunny** [comment]
hmm, what if I was mod for multiple categories? I'd rather not go to each category to see flags, one centralized place would be best

**Comment by julianlam** [comment]
:+1: probably easier to keep it centralised

**Comment by barisusakli** [comment]
This seems to be done ? @julianlam

**Comment by julianlam** [comment]
Yes thanks :smile:

**Comment by julianlam** [comment]
I'm on mobile now, can you tag this for 1.3?

**Comment by barisusakli** [comment]
done 💯
