### ISSUE TITLE
Unify build hooks?

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#4587]
The same format is being used for 90% of the build hooks, yet no build hook exists for many routes.

By modifying a few anomalies, I think the same function could be called in the render middleware for every route's build hook. Which would reduce code and ensure a build hook exists for every route.

The existing hooks follow the format
`plugins.fireHook('filter:' + template + '.build', {req: req, res: res, templateData: data}, next);`

Which can be called in the render middleware instead repeating it for every controller.

Only a few routes are different:
`filter:search.build` and 'filter:popular.build'
These have missing or extra parameters. These extra parameters could easily be added to the templateData or removed since they already exist in the req object.

There's also 'filter:composer.build' which is strange since it's not a route (and would not be affected by the change.), and `filter:header.build` which is depreciated.

I did try it on my forum by editting the render middleware, and it worked as expected, aside from the anomalies above.

```
		res.render = function(template, options, fn) {

			var self = this,
				req = this.req,
				defaultFn = function(err, str){
					if (err) {
						return next(err);
					}

					self.send(str);
				};
			options = options || {};

			plugins.fireHook('filter:'+ template +'.build', {req: req, res: res, templateData: options}, function(err, options) {
				options = options.templateData;

				...

			});
		};
```

**Comment by barisusakli** [comment]
This makes sense, i think there was a similar pr as well.

**Comment by yariplus** [comment]
Ahh right, is this the one? Just over a year old! ;) I knew I saw this somewhere before.

https://github.com/NodeBB/NodeBB/pull/2936

His method is a bit different. I think injecting the template in the hook is better, and more compatible.
