### ISSUE TITLE
disable mobile-web-app-capable meta tags

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#4589]
These meta tags: `apple-mobile-web-app-capable` and `mobile-web-app-capable`, being set to "yes",  make for a bad experience on iOS for NodeBB. 

* Links meant to open in a new page are opened in the same window
* no back / forward, so you can't return to the forum
* certain plugins are affected (i.e. iFramely youtube embeds will open in the youtube app as soon as it's rendered)

While nice, if the software is designed for such a view, it doesn't seem ideal for NodeBB.
These should be either disabled or configurable

**Comment by julianlam** [comment]
I still feel as though this is actually more of a theme related issue, so I'd prefer it if a theme could manually invoke the config instead of making it an explicit ACP option.

**Comment by julianlam** [comment]
Looking into this now, this can be altered based on theme:

`filter:meta.getMetaTags` passes in an array of tags. Find the `mobile-web-app-capable` tag (and the apple variant), and set their values to `no`, or remove them from the array altogether.
