### ISSUE TITLE
Sub/child groups

### ISSUE THREAD

**Issue by globalcow** [NodeBB/NodeBB#4592]
Hi,
I would like to have a parent group which automatically collects all users from sub or child groups. E.g. all member of group A, B and C should be members of group D without assigning them to group D manually.
Is there any possibility to realize this?

**Comment by julianlam** [comment]
We want to keep the groups logic simple (because it's a bit hairy already), so this would probably be best achieved as a third-party plugin. You'll want to listen to the relevant hooks to add users to the appropriate parent groups, and track parent-child relationships.
