### ISSUE TITLE
Clicking the "improved" notifications takes you to the wrong page

### ISSUE THREAD

**Issue by loopback0** [NodeBB/NodeBB#4601]
This notification:

![image](https://cloud.githubusercontent.com/assets/8740474/15053549/0ff7f382-12fb-11e6-920d-f57a1d9cfb5c.png)

Goes here:

![image](https://cloud.githubusercontent.com/assets/8740474/15053553/171c8f60-12fb-11e6-9625-69e08d1aa38c.png)

And not to the relevant post.

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-mentions/issues/68
