### ISSUE TITLE
Pagination results in blank page on N+1

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4604]
NodeBB seems to have issues with counting.  If I have pagination on, and the last post on the screen is the last post in the thread which is also the rollover point to a new page, the paging counter at the bottom will show N+1 pages.  Clicking on "Next" goes to the next page which is, of course, blank.

**Comment by barisusakli** [comment]
How many posts are in the topic? What is your posts per page setting? Do you have a link to a topic that has the issue?

**Comment by halcyon1234** [comment]
Many posts, and not many, since it's happened more than once.  I don't have a link atm, since it happens transitory.  I'm set to 20 per page.

**Comment by barisusakli** [comment]
Was possibly relateted to https://github.com/NodeBB/NodeBB/issues/5223
