### ISSUE TITLE
enhancement: "replies to this post"

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4608]
There is currently a button to go to the post that a post is replying to, but there's no UI for going in the opposite direction. It'd be nice if a post showed:
- The number of direct replies
- A fast way to jump to those replies

ref: apapadimoulis/what-bugs#34
/cc @halcyon1234

**Comment by julianlam** [comment]
This is a neat idea... we currently store the relationship one way (posts record their `toPid` value), but not the other way around...

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/5050
