### ISSUE TITLE
404 error for jQuery plugin

### ISSUE THREAD

**Issue by loopback0** [NodeBB/NodeBB#4617]
When loading the pages. Happens on both the NodeBB Community and TDWTF.

![image](https://cloud.githubusercontent.com/assets/8740474/15123589/73299018-161c-11e6-8975-5baa96f1b116.png)

![image](https://cloud.githubusercontent.com/assets/8740474/15123600/769e7416-161c-11e6-88f7-bde4ec19bccf.png)

Minor as it doesn't seem to stop anything working, but still.

**Comment by julianlam** [comment]
Yeah this is OK... it tries to load the short language strings, and falls back to English if they don't exist.

Could possibly send back English as fallback instead...
