### ISSUE TITLE
Client-side action:topic.loaded does not have topic ID

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4619]
Userscript below.  Event has no tid in it.  data is null.

var $ = unsafeWindow.jQuery;

$(document).ready(function()
{

    $(window).on('action:topic.loaded', function(event, data) 
    {
        console.log(event);
        console.log(data);

    });
    
});

**Comment by julianlam** [comment]
It can be added... but is it necessary?

I only ask as you can call `ajaxify.data.tid` to retrieve the tid when the hook is fired.

**Comment by halcyon1234** [comment]
I could use ajaxify.data.tid.  Is there any risk with referring to a "global" variable inside a hook-- stale data, concurrency issues, etc?

(Use case is "When a specific tid is loaded, perform an action")

**Comment by julianlam** [comment]
Technically, there's a risk, but in practice, unlikely, as you'd have to load two topics in quick succession.

Probably easier to pass the tid
