### ISSUE TITLE
Browser identification doesn't recognise IE on Windows Phone correctly

### ISSUE THREAD

**Issue by RaceProUK** [NodeBB/NodeBB#4625]
![image](https://cloud.githubusercontent.com/assets/10373748/15178392/2d05184e-176d-11e6-91f3-f4a71bbf2268.png)

This is a session on a Windows Phone 8.1 device

**Comment by pichalite** [comment]
The browser on windows phone identifies itself as Safari. Don't think this can be fixed.

**Comment by RaceProUK** [comment]
The user agent string contains the phrase 'Windows Phone' with the version, which is enough to work out the browser: on WP7 and 8, the browser is IE, and on WP10, it's Edge. No other browsers are available for those platforms.

**Comment by pichalite** [comment]
Sure but you will have to keep doing that for future versions of windows phone too if it still keeps reporting as Safari. My question is; is it worth doing it?

**Comment by RaceProUK** [comment]
In the interests of showing correct information to the user, yes. Besides, done right, the check won't have to be changed when WP11+ comes out, as they will almost certainly use Edge, just like WP10.

**Comment by julianlam** [comment]
We actually use a dependency for this, so it may have been fixed upstream... otherwise it's not something we can actively address in NodeBB.

https://github.com/NodeBB/NodeBB/blob/master/src/webserver.js#L17

**Comment by RaceProUK** [comment]
Wow… totally forgot I even filed this!

Reported upstream:
https://github.com/biggora/express-useragent/issues/76

**Comment by RaceProUK** [comment]
Also did a thingy:
https://github.com/biggora/express-useragent/pull/77

**Comment by julianlam** [comment]
:+1: :100:
