### ISSUE TITLE
Chat integrations

### ISSUE THREAD

**Issue by alexschomb** [NodeBB/NodeBB#4628]
I know that's a lot to ask so better put it on your mid-term todo list ;)

It would be nice to have chat integrations with other chat services like Rocket.Chat, XMPP, IRC or similar.  Maybe you could make the chat / direct messages feature modular so there could be plugins that replace it with other services.

**Comment by psychobunny** [comment]
Going to close this one - the idea is great, and we'll be happy to help anybody who'd like to integrate other chat systems with NodeBB (please contact us on our community forum), but this is far too open-ended for a bug tracker.
