### ISSUE TITLE
Listen on only one interface

### ISSUE THREAD

**Issue by Antoine-Pous** [NodeBB/NodeBB#4630]
Hi,

my server had 17 interfaces (17 IP) and i don't find anything in configuration documentation about how to listening only one interface like eth0:1.

Have you a trick about that?

**Comment by julianlam** [comment]
Hey there, you'll want to use the `bind_address` option in your `config.json`

**Comment by Antoine-Pous** [comment]
`bind_address` is not documented in the config file section :/

https://docs.nodebb.org/en/latest/configuring/config.html

This work perfectly, thank you !
