### ISSUE TITLE
Current dockerfile will not be able to pass setup stage

### ISSUE THREAD

**Issue by Haocen** [NodeBB/NodeBB#4633]
Thanks to config.json being reset after each rebuild of container.
Some files, like plugins installed and configuration files should be specified as volume.
Can anybody kindly tell me what files need to be preserved after each restart? Besides config.json?
My temporary solution is to specify the whole /src/usr/app as volume. Really bad practice, lost huge benefit of using docker.

**Comment by julianlam** [comment]
@BenLubar?

**Comment by BenLubar** [comment]
It'd be nice to have the config.json file stored in some subdirectory that would be able to be persisted. Additionally, having a list of installed plugins in there would be nice for switching containers without having to redo everything.

Right now, I have `echo 1 > pidfile && exec node loader.js` as my Docker startup command for the NodeBB containers I'm running and they aren't remade for each update (which is the Docker way).

**Comment by BenLubar** [comment]
https://github.com/BenLubar/NodeBB/commit/c76a139adf41ac8c39d13a1cd1e910620ff1aa88 solves the config file part, but not the plugins yet. Ideally the plugins should be done in a way that lets plugins that aren't from NPM work.

**Comment by BenLubar** [comment]
@Haocen In the last week or so, we've been using https://github.com/boomzillawtf/tdwtf to manage our Docker container. You could probably do something similar for yours. Basically, we no longer use NodeBB's plugin installation/update buttons, and updates are fully installed before the forum switches over to the new instance.

**Comment by Haocen** [comment]
Sounds like a solution, thank you for letting me know.
