### ISSUE TITLE
Sort topics by votes

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#4635]
It could be interresting to be able to sort topics by upvote, downvote or vote ratio.

Made the default sort type and order available into the category configuration can be usefull.

**Comment by JonathanWatkins** [comment]
I would also like something like this but would we also need nested posts replies. I worry that it becomes hard to reply to user posts as the order of posts becomes broken if we are ordering on votes.

**Comment by Antoine-Pous** [comment]
Currently i need this feature for suggestions forums.

People cannot reply, just create topic and vote for the best requests. But i'm sure this can be usefull for a lot of another usages.

**Comment by JonathanWatkins** [comment]
from @bri in the forums

> After some searching it looks like some people got close with the q&a plugin: https://www.npmjs.com/package/nodebb-plugin-question-and-answer

**Comment by jimmykane** [comment]
Any update on this? 
Guys I feel that nodeBB either is going very slow either it's tailored too much. 

I don't understand why there are votes but no sorting on them....

**Comment by jimmykane** [comment]
As a new user: 

I got to ACP and then I go to post settings. Fine.
Then I see: 

<img width="1230" alt="screen shot 2017-11-15 at 19 48 54" src="https://user-images.githubusercontent.com/1268723/32854330-8ecaf24e-ca3e-11e7-858c-0fd0db2ab529.png">

I am like: 'Alright great that needs to stay like this'

I go to my category only to find out that I cannot sort by votes but I can sort by post count. 

and then I say to my self: 'What a beautiful world' :-p 

Now seriously what am I missing here?

**Comment by barisusakli** [comment]
Looks like a typo in the ACP, fixed here https://github.com/NodeBB/NodeBB/commit/9e5a8856d1e0afb1dfd349f7c14c6569f3648626

**Comment by jimmykane** [comment]
Shouldn't this be closed by now ?
