### ISSUE TITLE
Topic tools button displayed even if it is empty.

### ISSUE THREAD

**Issue by Haocen** [NodeBB/NodeBB#4636]
Not sure if this is theme related problem, I'm using material theme.
<img width="374" alt="topic tools" src="https://cloud.githubusercontent.com/assets/10842569/15235406/fc4ab340-1888-11e6-90b6-f7c68aaa01d6.png">
The topic tool button is empty, but got displayed anyway.

**Comment by julianlam** [comment]
Hi there, please report this bug on the material theme repository. Thanks!

**Comment by Haocen** [comment]
Hi, I just tested with Persona theme but the problem is still persist.
I've allowed guest to post topic in this category but not to reply, there is no other change made to cause the problem.

**Comment by julianlam** [comment]
Thanks for the follow-up
