### ISSUE TITLE
When the window is snaped to a side, we get the mobile composer on desktop PCs/laptops

### ISSUE THREAD

**Issue by machado2** [NodeBB/NodeBB#4637]
Even on a full screen monitor, snapping the browser window to the left or right of the screen is getting this mobile composer that is meant for phones and devices with a very small screen.

**Comment by julianlam** [comment]
Yes, unfortunately we cannot help this, as the mobile detection works by checking window width. There will be better ways to determine desktop vs. mobile in the future, but currently, there are no cross-browser compatible methods to confidently make this determination.

Please see [this MDN article](https://developer.mozilla.org/en-US/docs/Web/Guide/Mobile/Separate_sites).

We refuse to use user-agent detection as it is easily outdated. CSS media queries don't work (as all phones report themselves as `screen`, just like desktops to, and nobody uses `handheld`).

The last solution is viewport width.
