### ISSUE TITLE
Confirm login to access /admin does not accept SSO

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4638]
> When trying to go to /admin, and you're prompted to confirm the account, it will not accept G+ (which is acceptable for a normal login) as a viable source of credentials - a password is required.
>
> Either
> 1) If it's supposed to be allowed, it needs fixing
> 2) If it's not supposed to be allowed, stop showing them.

ref: apapadimoulis/what-bugs#128
/cc @pauljherring

**Comment by julianlam** [comment]
I would imagine that SSO is less safe, and we'd only want to show the password prompt if the user account has a password, but I could be wrong... 

SSO could be just as safe... except you're putting the burden of authentication on someone else, and trusting that provider...

**Comment by pauljherring** [comment]
Hmm. Experimenting..

1) Delete cookies.
2) Log in as admin from the [Login to post] -> G+
3) Logged in. Can post.
4) Try /admin
5) Get login screen again
6) Hit G+ only to cycle round again (problem in first post)
7) Logout
8) Log in as admin from the [Login to post] -> G+
9) Fail to login - cycle round  again to login screen


Even if SSO shouldn't be used to confirm access to /admin, I believe steps 2->3 should be identical to 8->9.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/1972
if the user doesn't have a local password they won't get the confirmation screen.

**Comment by pauljherring** [comment]
So - the SSO won't be shown on the confirmation screen if there _is_ a local password?

**Comment by barisusakli** [comment]
As of [this](https://github.com/NodeBB/NodeBB/commit/a4031df9b2a2b22bf11e29430c6b55972a50d654) commit SSO logins wont show up.
