### ISSUE TITLE
Timeago bug

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4640]
timeago on teaser and other places has a noticeable lag 

If you select non english language
go to recents 
refresh page f5
you will see the string in english then it will change to your current language

also it could be insterestig allowing to use custom locale strings from themes so we can replace that long strings like "less than a minute ago" that breaks mobile layouts

**Comment by julianlam** [comment]
Hi @exomarty, unfortunately we cannot resolve this issue as english is the built-in language, and we do not know the user selected language until after the page has loaded.

When loaded, we can determine the language and then request the language files, and that round-trip is the cause for the delay.

**Comment by exomarty** [comment]
why there is no delay on other texts? only on timeago

**Comment by julianlam** [comment]
It is due to the round-trip request made to fetch the actual language files for timeago... whereas for other text, this can be determined via server side and sent pre-translated

**Comment by exomarty** [comment]
weird :cry: 

![z1ooxucmad](https://cloud.githubusercontent.com/assets/10746278/15555020/0a39a144-22c7-11e6-8290-f55e4cff1d2b.gif)

what about livestamp and moment, are they faster?

thank you for the support
