### ISSUE TITLE
Add basepath to config.json

### ISSUE THREAD

**Issue by Antoine-Pous** [NodeBB/NodeBB#4642]
Hi,

in the config.json i have set this url `"url":"http://domain.tld/forums"`, but the forum was unable to load all files.

Currently i use mod_proxy (apache2), the proxy set the base path to `http://domain.tld/forums`

```
  <Proxy *>
    Order deny,allow
    Allow from all
  </Proxy>

  RewriteEngine On

  RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
  RewriteCond %{QUERY_STRING} transport=websocket    [NC]
  RewriteRule (.*)            ws://127.0.0.1:6548/$1 [P,L]

  ProxyPass /forums/ http://127.0.0.1:6548/ retry=0
  ProxyPassReverse /forums/ http://127.0.0.1:6548/
```

The problem is it seem the base path is hardcoded, so the NodeBB ressources are available on `http://domain.tld/forums/forums/*`.

I have try with `"url":"http://domain.tld"` but the problem is the same, ressources are called from `http://domain.tld/*` and not from `http://domain.tld/forums/*`

I think the best way to fix it is adding `basepath` parameter to `config.json` and change `url` for `domain` or `public_address`.

The simpliest way is to make all routes **relative** to the `url` parameter.

**Comment by julianlam** [comment]
Hi there -- NodeBB does support subfolder installs, and in this case, you'll want to modify your proxy settings in Apache so that the `forums/` is stripped when passed to NodeBB, and then you will not see the "double `forums/`" issue.

Unfortunately I have no experience with Apache, only nginx. I would recommend you post about this on the [community support forum](https://community.nodebb.org). Thanks!

**Comment by Antoine-Pous** [comment]
The problem is that NodeBB should not have this behavior. Many projects using NodeJS and WebSockets does not have this problem because they use the baspath independently of the domain name.

**Comment by dHumanities** [comment]
I use nginx as proxy.
Does anyone know how to change the confirmation url in email template ? It points to 127.0.0.1:4567 ...
