### ISSUE TITLE
Sorting topics by daily posts

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#4644]
**Is this possible?**
 
![screen shot 2016-05-15 at 1 49 34 am](https://cloud.githubusercontent.com/assets/113159/15272269/5bd12044-1a3f-11e6-9ccf-ddeae2c682af.png)

**Comment by barisusakli** [comment]
Not available in core but can be done with a plugin. The sorted set that contains the topics is `topics:tid` where the score is the topic creation timestamp.

So you can get topic ids posted a current day with. 

```
var today = new Date();
var tomorrow = new Date();
today.setHours(0,0,0,0);
tomorrow.setHours(24,0,0,0)
db.getSortedSetRevRangeByScore('topics:tid', 0, -1, tomorrow.getTime(), today.getTime(), callback);`
```

It is possible to adjust the timestamps to get ids from the past 5 days with the same method.
