### ISSUE TITLE
Feature request: vanity page

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4647]
Just calling it what it is...

want a page that has my Liked posts, which can be :

sorted by score (highest to lowest, or lowest to highest)
sorted by date of post
sorted by date of last Like

Full text of post in each LI element

**Comment by julianlam** [comment]
Have you tried looking at `/best`?

**Comment by halcyon1234** [comment]
Took me a while to find /user/USERNAME/best

Could there also be the score there?  Or even better, the down (score) up widget, to allow voting on that page?
