### ISSUE TITLE
Custom homepage "none" doesn't obey ignored categories

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4648]
My settings homepage is set to "Custom" with route of "none".  I honestly don't know when this got set, or if I set it, or what that even means.

Anyways, when I click "home", that listing shows me all posts from all categories, even categories I've chosen to ignore.  (/unread, for example, does not show those posts form those categories).

**Comment by pichalite** [comment]
what do you have set as "Home Page Route" in ACP -> General ->Home Page?

**Comment by pichalite** [comment]
definitely a bug on the user settings page. Selecting "None" for homepage does not stay as none after save and reload. Goes to "Custom" option with "Custom Homepage Route" set to "none".
