### ISSUE TITLE
Mobile pagination navigation is nigh useless

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4649]
The bottom-of-page mobile navigation is kinda useless.  It shows:

Back Arrow
current page number
Next Arrow

And that's it. (There may be a ... but I can't remember?) 

There is no indication of if Back or Next even work.  There's no indication as to the number of pages.

There is WAY more than enough screen width to add more buttons, and make them standard to standard pagination navigation.

Back Arrow (or hidden/grey out if first page)
The first couple pages
...
The page before this page
This page (highlighted)
The next page

(And then if not close to the last page:
...
The page before last page
The last page
)
Next arrow

Also, the ... pops up a dialog that says "Jump to page number...", but with no indication as to which page I'm on right now, and how many pages there are.

"Jump to page number (1 to $LastPageNumber):
(textbox)
Currently on page $CurrentPage
(button)
"

**Comment by barisusakli** [comment]
See here https://github.com/NodeBB/NodeBB/issues/3286

I agree the previous one that showed everything was better even though it looked a bit weird.

**Comment by julianlam** [comment]
Feel free to revert, though we're at a lack of a better option at the moment...
