### ISSUE TITLE
Add vote permissions

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#4652]
Hi,

can you add some permissions please ?

Users permissions:
- Can vote, allow the user to vote in this category
- Reply to own topic, allow the user to reply only on his own topics
- Topic creation limit, (int) maximal topic amount for the user in the category
- Topic/reply flood limit, (int) seconds between posts in the category

Category setting:
- Topics are category, show the topics with tiles, usefull when the category is dedicated to documentations.

**Comment by julianlam** [comment]
> Can vote, allow the user to vote in this category

☝️ This is the only one that is feasible in core. The rest are either not possible (as permissions are on/off), or too obscure to be beneficial in core (better off as plugins).
