### ISSUE TITLE
Refactor language files to allow plugins to add/replace values

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4655]
Currently language files are kept in `public/language/:code`, where `code` is a language code such as `en_GB`, etc.

Plugins can currently add new files to the language system by specifying the key `languages` in `plugin.json`:

``` json
{
  ...
  "languages": "public/languages"
  ...
}
```

... at which point the files in `path/to/plugin/public/languages` will be served.

Plugins can also define a `defaultLang`, and if the language isn't found, then it falls back to the `defaultLang`.

----

There is now a need to be able to easily replace the existing language keys via plugin, in a future-proof manner. It is possible in the current system to replace, for example, `en_GB/notification.json`, with your own in your plugin, but if new keys are added, then they are not propagated to the plugin, so that is not **future-proof**.

**Comment by julianlam** [comment]
Current WIP state works except for `defaultLang` integration... unsure if I should make the default always `en_GB`.

**Comment by julianlam** [comment]
Maybe [here](https://github.com/NodeBB/NodeBB/blob/language-mergability/src/plugins/load.js#L238), if `defaultLang` is specified, I can add the data to all NodeBB supported languages...

**Comment by julianlam** [comment]
For those users who are using nginx or other proxy server to serve static assets, please exclude the "language" folder from this list. See https://github.com/NodeBB/nodebb-english/commit/2218d38ff8d42e823b4c0ddb429478154a4bd876

**Comment by pitaj** [comment]
How do I define custom translations now? The functionality appears to be broken now or something. Do you have an example of  a plugin doing translation now? The old way no longer works for me.

**Comment by julianlam** [comment]
Translations are handled the same way, the commits here only change the way it is implemented so you can define a "notifications.json" in your plugin, and it won't overwrite core's `notifications.json`.

**Comment by pitaj** [comment]
Hmmm. Well, it isn't working for me. Have you tested it? My plugin is symlinked into the node_modules directory. Maybe that's it?

**Comment by julianlam** [comment]
Yes, it works fine [in mentions](https://github.com/julianlam/nodebb-plugin-mentions/blob/master/languages/en_GB/notifications.json).

**Comment by pitaj** [comment]
That doesn't show it working for completely new files. ex: `[[my_plugin:description]]` Does it still work correctly when adding completely new prefixes?

**Comment by julianlam** [comment]
yes, go up a directory.

**Comment by pitaj** [comment]
I needed to set a `defaultLang`, or it would give me this error:

```
error: [translator] Could not load `calendar`: ENOENT: no such file or directory, open '/home/pitaj/webdev/nodebb/public/language/en_GB/calendar.json'. Skipping...
```
