### ISSUE TITLE
./nodebb start should show error it it fails

### ISSUE THREAD

**Issue by kdpuvvadi** [NodeBB/NodeBB#4659]
when i enter ./nodebb start on CLI and hit enter it just shows  

`

> Starting NodeBB
>   "./nodebb stop" to stop the NodeBB server
>   "./nodebb log" to view server output
>   "./nodebb restart" to restart NodeBB

`
but in reality it doesn't start sometimes, i can see the in the log.but not at cli.

**Comment by barisusakli** [comment]
Just use `./nodebb start && ./nodebb log` to see the output. `./nodebb start` is used to start nodebb in production mode so it doesn't block the cli. You can use `./nodebb dev` or grunt to start and see the output as well.
