### ISSUE TITLE
Link-back button for quotes pushes post content to the right

### ISSUE THREAD

**Issue by Jckf** [NodeBB/NodeBB#4661]
As the title says. This happens only in Firefox on Linux as far as I can tell, but I only have Firefox on a Linux machine, so my testing ability is limited. NodeBB v1.x.x from Git (cloned 2 days ago). Firefox v46 on Linux Mint.

![13223571_883768368417052_887130045_o](https://cloud.githubusercontent.com/assets/1040070/15355140/5f711f38-1cf1-11e6-948a-5988d299a7e7.jpg)

**Comment by mgrytbak** [comment]
The same thing is occurring in Firefox 46.0.1 under Windows and OSX aswell.

**Comment by julianlam** [comment]
Hello guys, what theme are you using on that install?

Can you please run `git rev-parse HEAD` so we can try to reproduce?

**Comment by Jckf** [comment]
Persona + Yeti.

a196c834d9aab4e1c27965dcca623ce12e61b4ae
