### ISSUE TITLE
Modify data arguments when firing filter:user.profileLinks

### ISSUE THREAD

**Issue by jarey** [NodeBB/NodeBB#4665]
I think would be nice to extend the arguments when firing the hook and add the callerUID and the uid of the user profiled thats being loaded.

It would be nice to have that that in the filter in order to manage the profile links in the filter.

For example i think theres no way to add a new user profile link, that is visible only to the public and not by the user itself ( like the chat link for example).

I could make the change if you are oke with it and make a pull request. Just need to tell me how you want to pass the parameters, in a new object or in 2 different parameters to the function.

The modification would not break any existing plugins or functionality.

The only affected point in the code would be:

https://github.com/NodeBB/NodeBB/blob/master/src/controllers/accounts/helpers.js#L145

and 

https://github.com/NodeBB/NodeBB/blob/master/src/controllers/accounts/helpers.js#L42

in both cases the data i'm talking about is avaliable.

Thanks.

**Comment by barisusakli** [comment]
This would break all plugins using `filter:user.profileLinks` and there is quite a few of them https://github.com/search?q=filter%3Auser.profileLinks&type=Code&utf8=%E2%9C%93

**Comment by jarey** [comment]
I can achieve the purpose of my plugin client-side. So i can close this issue, thay said, it still for me a lack of information in this hook. It maybe can be bypassed by adding new flags to the link object and processing it in the tpl with conditional logic, or the one suggested by myself that I consider the best option.

It would break, existing plugins as you said. Needing a minor change to all.

Close the issue if you dont consider it viable.

**Comment by barisusakli** [comment]
I think it makes sense to add more info to this hook, we will just do it in a major release I guess.
