### ISSUE TITLE
post edit time limit isn't checked when opening the composer to edit a post

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4668]
Users are still presented the option to edit a post even when it's weeks past the timeout. They make their edits and submit, only to be given an error message saying they aren't allowed to do the thing they were just prompted to do.

ref: apapadimoulis/what-bugs#71
/cc @Choonster

**Comment by darktrge** [comment]
This patch introduces a new bug. Admins&mods also cannot edit the post after timeout expires.

**Comment by barisusakli** [comment]
Thanks fixed in https://github.com/NodeBB/NodeBB/commit/2c5464760d3f62ac63d8747760995e5ef47ac4fa

**Comment by machado2** [comment]
why do we even have a time limit? if the post is mine I should be able to edit/delete it whenever I want

**Comment by julianlam** [comment]
That is up for the administrator to decide. 

It is easy for a troll to change their post content after the fact, and the edit threshold prevents this.

**Comment by machado2** [comment]
I forgot there are forums for people that doesn't appreciate a good trolling.
