### ISSUE TITLE
composer design ideas

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4670]
enhancement for mobile layout so this kind of stuff doesnt happen

![1463704053612-screenshot_2016-05-20-02-30-06](https://cloud.githubusercontent.com/assets/10746278/15450757/6049ff2c-1fa5-11e6-8b05-b88847b1c372.png)

![compo2](https://cloud.githubusercontent.com/assets/10746278/15450753/27be194a-1fa5-11e6-8313-4a20090eac86.png)

what do you think?

**Comment by julianlam** [comment]
I love it!

I'm not entirely sure whether the swiping left and right in the toolbar will be readily apparent, but this is a good step in the right direction.

Pinging @psychobunny and @pichalite for comments

**Comment by exomarty** [comment]
I'm glad you like it @julianlam. Hope more people can comment about it so we can discuss improvements :)
About the swipe bar could have some line or dots of status to be readily apparent to the user

**Comment by exomarty** [comment]
RFC :cry:

**Comment by julianlam** [comment]
Label added :smile: Perhaps post it to the community forum to drive traffic here?

**Comment by pichalite** [comment]
add `needs more info` label as well :trollface:

**Comment by psychobunny** [comment]
4.0.3 adds swipe for toolbar, moves category selector out of the body, and various mobile fixes. Thanks @pichalite
