### ISSUE TITLE
Read API: Return all users

### ISSUE THREAD

**Issue by alexschomb** [NodeBB/NodeBB#4672]
I found that ``http://myforum.com/api/users/`` returns the newest 24 users only. This is corresponding to the users overview in the frontend that requires the user to press the ``load more`` button to show additional users. Is there a way to return all users of a nodeBB via API?

**Comment by julianlam** [comment]
Hi @alexschomb -- not out-of-the-box, although the reason is that such a route would require a lot of processing (pulling the relevant user data and formatting it, etc), and thus the route would not be very performant. Perhaps there are pagination options...

**Comment by julianlam** [comment]
Appending `?page=2` works well, though I'll add a bit of metadata into the API return to make it more REST compliant...

**Comment by loversama** [comment]
That'd be awesome I was just reading this myself thinking the same thing.. being able to use NodeBB as an API for other things has made expansion so much more easier, good to see API improvements are still being made :))

**Comment by julianlam** [comment]
The `pagination` block is already in the API return, so you can use that and construct the url with the `qs` value.

**Comment by julianlam** [comment]
NodeBB now returns the `X-Total-Count` header, if that's useful to you :stuck_out_tongue:

**Comment by alexschomb** [comment]
Sorry, that was my fault. I was too stupid to work with the ``page`` query parameter. Still, the ``X-Total-Count`` is a great improvement. Thanks for your help! 👍
