### ISSUE TITLE
Docker images are quite aged

### ISSUE THREAD

**Issue by faddat** [NodeBB/NodeBB#4673]
have a look:  https://hub.docker.com/r/nodebb/docker/tags/

is this as it should be, and we expect users to make their own, or....?

**Comment by julianlam** [comment]
Have you tried https://hub.docker.com/r/benlubar/nodebb/?

**Comment by faddat** [comment]
No, I have not-- the idea with the docker images being on Docker hub is to create an "official" docker image that tracks the repo.  This way users always get a known quantity.
