### ISSUE TITLE
I'd like to see a better permission system implemented.

### ISSUE THREAD

**Issue by KieronWiltshire** [NodeBB/NodeBB#4674]
The permission system in nodebb isn't very flexible, and doesn't allow plugins to specify their own permissions. I purpose a new permission system that gives administrators and plugin developers full control over what permissions they grant and revoke, this should include the default groups too as they're awful to work with imo.
![image of groups](http://i.imgur.com/LBrGxnm.png)

Here you can see I'm not happy with the system groups, and I want more freedom to change how things work. Now fortunately I have developed a module that I believe could be useful.

I'd also like to know what other people think of this system vs a [new](https://github.com/KieronWiltshire/ezpermissions) one?

**Comment by pitaj** [comment]
Plugins actually can add permissions using the following hooks:

- `filter:privileges.list` for user-specific privileges
- `filter:privileges.groups.list` for group privileges
- `filter:privileges.list_human` and `filter:privileges.groups.list_human` for human-readable strings representing those privileges

**Comment by julianlam** [comment]
Thanks @pitaj, this should be addressed now 😄
