### ISSUE TITLE
Clear fold content to stop rendering JavaScript and CSS!

### ISSUE THREAD

**Issue by soarteam** [NodeBB/NodeBB#4679]
nodebb.min.js file is too large, and before the file is not loaded, the page will not display anything, it is recommended asynchronous loading!
We need to stylesheet.css and nodebb-plugin-markdown/styles/railscasts.css file be optimized to enhance nodebb load faster!

**Comment by soarteam** [comment]
CSS resource page has a blocking script resources and two blocked presented. This causes a delay in the page rendering process.
Before the following resources loaded on the page does not present any direct fold content. Try to suspend or stop asynchronous loading of resources!

**Comment by soarteam** [comment]
Recommendations will need to load all the CSS and JS compression, can be compressed as if nodebb images from imgur enough.

**Comment by julianlam** [comment]
JavaScript and CSS are already minified, and we load a single minified file to decrease round trips to the server.

We will examine additional optimisations as they are tested and proven on other sites. In the meantime we appreciate your input and will consider our options towards speeding up the site.
