### ISSUE TITLE
We recommend optimizing admin/widgets operate on the phone!

### ISSUE THREAD

**Issue by soarteam** [NodeBB/NodeBB#4681]
widgets on your phone completely unable to control, hope nodebb can be optimized.

**Comment by ArcticRaz0r** [comment]
There isn't much there can be done, I suppose. The mobile browsers themselves have a lot of limitations that make it hard to make Widgets usable in the ACP

**Comment by psychobunny** [comment]
I'm closing this one unless somebody has a good design in mind. Moving around widgets in the control panel happens so rarely that it's probably not worth the effort to optimize for mobile
