### ISSUE TITLE
Requires longer topic title when I reply to the post. 

### ISSUE THREAD

**Issue by AndrewPlakhotnyi** [NodeBB/NodeBB#4683]
Forum is just installed : forum.hand2note.com

![image](https://cloud.githubusercontent.com/assets/8612908/15539697/325db502-22ae-11e6-895c-6c377b6daf9c.png)

**Comment by barisusakli** [comment]
Are you on 1.0.3 or master?

**Comment by AndrewPlakhotnyi** [comment]
NodeBB v1.0.3

**Comment by AndrewPlakhotnyi** [comment]
You may create test topic in our forum if it helps you to reproduce the problem

**Comment by barisusakli** [comment]
Only seems to happen if composer is on a separate route.

**Comment by barisusakli** [comment]
Can you run `npm ls nodebb-plugin-composer-default` in your nodebb folder and let me know the output.
