### ISSUE TITLE
certain content freezes safari

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#4685]
https://community.nodebb.org/topic/8597/1-million-%C5%82-question-for-everyone

**Comment by pichalite** [comment]
![image](https://cloud.githubusercontent.com/assets/10014774/17671064/d1cb0012-62c9-11e6-8a68-b13c458fd55d.png)

**Comment by barisusakli** [comment]
Thanks @pichalite can you also post the device + safari version.

**Comment by psychobunny** [comment]
Looks like `${INSTALL_DIR}` also has this issue

**Comment by julianlam** [comment]
:clap:

**Comment by julianlam** [comment]
Not fixed in latest `master` because `master` still installs templates.js v0.3.6 😄
