### ISSUE TITLE
We are willing to undertake NodeBB Chinese community!

### ISSUE THREAD

**Issue by soarteam** [NodeBB/NodeBB#4691]
Ado. Why can the Chinese community entrust to us?
1，Chinese users first open the web page in 1 seconds or less. And do not use the territory of China server.
        such as: 
                   MCLW： mc.soaryun.com

2，Strong management team: "SoarTeam" is initiated by the team to undertake community, we also undertake Caustic Kloxo-MR ... social in China.
And we also have NodeJS / PHP / JAVA / C ++ / C # ... programmer can NodeBB reinvigorate.

3，Preliminary molding NodeBB-CN circles: In our chat tool "QQ", we have set up NodeBB group, and there are more owners join.

This is shaping our existing site, is still growing!
http://mc.soaryun.com
http://qtdream.com
http://moeclub.net
http://intio.org
......

**Comment by soarteam** [comment]
Of course, just because we do these things just personal preference.

**Comment by julianlam** [comment]
Thank you for the offer. At the present time our Chinese-speaking community is maintained by @fiag and Haowei (whose github username I do not recall at the moment), and it is done completely outside of NodeBB itself.

Perhaps you can talk to them and work together.

**Comment by soarteam** [comment]
Actually ... Why do I want to do it, is because they can not reach @fiag, he can not be said to be a very long time to maintain the community. Now not open community, and even his own website to open it.
@julianlam

**Comment by soarteam** [comment]
This has worried us for a long time.
If you want, you just need to tell us agree. The next thing only to us. We will first complete Chinese help documentation.

**Comment by julianlam** [comment]
Please reach out to us at support@nodebb.org

**Comment by soarteam** [comment]
OK

**Comment by fiag** [comment]
Sorry for the broken. 
And I will fix it in a couple days.

**Comment by fiag** [comment]
The Chinese community already has been fixed.
Thanks @soarteam. BTW I notice that @soarteam has a project [NodeBB-CN[(https://github.com/soarteam/NodeBB-CN), maybe we can work together,  and make a merge request on the [ACP i18n](https://github.com/NodeBB/NodeBB/pull/3557). Look forward to your reply.

**Comment by soarteam** [comment]
@fiag 当然可以，nodebb.cn 也是我们的，你万年不上线我也找不到你人，你要用nginx反代的话就去把nodebb的流量限制关掉，不然天天503

**Comment by soarteam** [comment]
@fiag 留下你的QQ

**Comment by fiag** [comment]
@soarteam 我在 nodebb.org.cn 上 QQ 留私信给你了
