### ISSUE TITLE
Post templates

### ISSUE THREAD

**Issue by wayneworkman** [NodeBB/NodeBB#4692]
Hello from forums.fogproject.org

This is a feature request. We would like to have a template system for posting in the forums.

This can potentially benefit all NodeBB forums sites who use this project in a technical support manor.
It will dramatically cut down on moderators and developers having to ask the same questions over and over again, and allow quicker resolutions to problems, quicker response times, and cut down on excessive posting, DB usage, and traffic to sites.

Please see this link for additional details:
https://forums.fogproject.org/topic/7579/two-forum-related-questions

Thanks,
Wayne

**Comment by julianlam** [comment]
Hey there Wayne, you'll want to use nodebb-plugin-canned-responses :smile:
