### ISSUE TITLE
Changing what happens when notifications appear on mobile...

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4695]
When a notification is received, we automatically execute a toaster alert, and on desktop this works reasonably well.

However, on mobile, the toaster takes up a non-insignificant portion of the screen. If you happen to be composing a post, and a notification occurs, the alert takes up a good 50% of the screen!

I'd like to change this but am open to suggestions... right off the bat I'm thinking that if a notification is received while on mobile, we should show a little icon in the taskbar, that can be invoked when desired.

... and also hidden from composer, because when I'm writing a post I don't care much about notifications...

Thoughts?

**Comment by yamikuronue** [comment]
My thoughts: I don't find the toaster useful even on desktop. The little icon in the corner is non-obtrusive while I'm reading, but the flicker of the number changing does sort of catch the eye so I know to check it later, much like having the number of unread emails in my gmail tab. So for me, just having the number somewhere in the UI is fine.

**Comment by pichalite** [comment]
The toaster just stays for about 3 seconds. if we add it to the taskbar... that kind of makes it sticky. I will already have it in the notifications list, why would I want it again in the taskbar?

Just make it hidden when composing on mobile. I think eliminating the toaster altogether for notifications is not a bad idea either.

**Comment by AccaliaDeElementia** [comment]
Having the toaster disableable for all users would be a good thing.... 

what about allowing users to enable desktop notifications? those work pretty well in most mobile browsers now (being translated to actual native notifications) as well as desktop browsers and may be a decent replacement for the toaster.

**Comment by jaloopa** [comment]
How about making the top bar visible for a second if it's not already and upping the number? Ideally without scrolling the page. Far less intrusive than the toaster (which is useless in dark themes anyway)

**Comment by julianlam** [comment]
Sounds like there's near-universal dislike or disinterest for the toaster on desktop, so that's good to know.

I'm perfectly fine with making this change and making the notifs counter update without some flashy hand-waving "YOU HAVE NEW NOTIFICATIONS" toaster, though keep in mind that **there is no taskbar** in mobile, so you won't actually know you have new notifications on mobile unless you specifically open the menu hamburger (on vanilla) or swipe open the menu (on persona).

Does that change your opinion on how the behaviour ought to be on mobile?

**Comment by Tsaukpaetra** [comment]
Well on my current theme it seems the number of notifications is displayed (somewhat incorrectly) next to the hamburger button. I think if we're disabling the toaster, might as well animate that little bubble (possibly making the title bar visible for the few seconds)

What's funny is that the notifications bubble is a different color in the "taskbar" on mobile, though I'm sure that's just weird theme styling on the custom theme.

**Comment by exomarty** [comment]
i dont see a real problem here
on desktop it could be more beatiful like 
http://codepen.io/mallendeo/pen/jmtaB

on mobile
something like we have now. the red number on the nav bar and a "new" tag on the left if new notifications happen
also incrementing the number could have some animation

http://codepen.io/ryanmorr/pen/RPZZjd

**Comment by arasbm** [comment]
I agree that on the mobile the notification should be very minimal and in the case of composing it should be queued or delayed until after user submits or discards their post. While a user is writing a post that is the most important task on hand and should not be interrupted -- even on desktop, in my opinion.

**Comment by yariplus** [comment]
I dislike the toaster on desktop and mobile. I think the bubble or an animated bubble is more than enough for either.

**Comment by pitaj** [comment]
:+1: for toaster removal as far as notifications go. I get desktop and mobile notifications anyways. I think toasters are useful for errors, but not much else.
