### ISSUE TITLE
action:topics.loaded not fired on topics list?

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4698]
Unless I'm doing something wrong, I don't see the event actions:topics.loaded when I navigate to (or refresh) /unread, or any other endpoint like /recent or homepage.

Greasemonkey script:
```
var $ = unsafeWindow.jQuery;  
$(document).ready(function()
{
 var $ = unsafeWindow.jQuery;  
   console.log("doc ready");

    $(window).on('action:topics.loaded', function(event, data) 
    {
        console.log("topics loaded", event, data);
    });

   console.log("wire ready");
    
    
});
```

Result:
doc ready
wire ready

I don't see "topics loaded"

**Comment by julianlam** [comment]
hmm... recent fires `topics:loaded` on infinite scroll loading of more topics... is that what you're referring to?

On initial load of `/recent`, I don't have that action firing...

**Comment by halcyon1234** [comment]
This is a client-side hook, yes?  (I'm using pagination instead of infiniscroll).

I don't see "topics:loaded" in the hooks wiki

https://github.com/NodeBB/NodeBB/wiki/Hooks

Could fire on /recent and /unread?

**Comment by halcyon1234** [comment]
(It may be possible it's just the instance itself https://what.thedailywtf.com/unread if so I'll re-file the bug downstream)

**Comment by julianlam** [comment]
It's a client-side hook, yes... though with pagination enabled, we don't fire that hook at all.

**Comment by halcyon1234** [comment]
Could you fire that hook, so I can run a userscript on topics lists?

**Comment by julianlam** [comment]
Yes, makes sense, we should fire it on unread/recent pages.
