### ISSUE TITLE
Creating a new category and selecting both optional parameters

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#4701]
Select a category for both options (Parent Category and Clone Settings From Category)

Settings are successfully cloned but the new category does not become a child of the chosen category.

**Comment by barisusakli** [comment]
Happens because cloning from another category also clones the parentCid setting which overrides the parent. I guess gotto disable optional parent selection if category is being cloned.

**Comment by psychobunny** [comment]
Or I guess if parent selection is chosen, don't clone parentCid?
