### ISSUE TITLE
Uploaded image appears blank

### ISSUE THREAD

**Issue by JonathanWatkins** [NodeBB/NodeBB#4704]
On commit 61404be94b1ad0487256065a4030c1a9df8b54cd

After uploading images, I often cannot see them on the page. The src attribute of the image is blank and opacity:0.

<img width="1023" alt="screen shot 2016-05-29 at 07 58 55" src="https://cloud.githubusercontent.com/assets/1997938/15633699/04f1ef06-25ac-11e6-90a7-e42eb46a1f54.png">

If I update the src attribute to the same as data-src and remove the opactity: 0 then the image becomes visible again. Any ideas why?

<img width="1174" alt="screen shot 2016-05-29 at 07 59 18" src="https://cloud.githubusercontent.com/assets/1997938/15633702/0dcd2690-25ac-11e6-8f1f-f3401062cb23.png">

**Comment by julianlam** [comment]
Please report your NodeBB hash

**Comment by JonathanWatkins** [comment]
what's that? where can I find it?

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/blob/master/.github/CONTRIBUTING.md

**Comment by JonathanWatkins** [comment]
Thanks 61404be94b1ad0487256065a4030c1a9df8b54cd

**Comment by JonathanWatkins** [comment]
BTW nodebb is great!

**Comment by barisusakli** [comment]
Happens on latest master as well. If the window doesn't have a scrollbar the image doesn't load if you make the window shorter and cause a scroll even the image loads.

**Comment by julianlam** [comment]
Ah, thanks for triaging @barisusakli, makes sense.

**Comment by julianlam** [comment]
I can't reproduce this issue... on a new NodeBB, posting a picture as the OP, without any additional posts (so no scrollbar), the image loads immediately on ajaxify and cold load.

**Comment by barisusakli** [comment]
I was able to repro when replying to a topic with just OP. Will get a screenshot

**Comment by barisusakli** [comment]
![image](https://cloud.githubusercontent.com/assets/2583394/16634254/7fac3412-43d5-11e6-8dba-50cdb3a6fd79.png)

**Comment by julianlam** [comment]
So this is just on reply, not on topic creation... gotcha. Thanks.
