### ISSUE TITLE
bookmarks notifications

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4706]
bookmarks is a private area so notifications to the poster had sense with favourites but not with bookmarks
RFC

**Comment by julianlam** [comment]
Unless I misunderstand your meaning, bookmarks and favourites are identical in NodeBB, unless you're talking about the "last unread post", which we also refer to as a bookmark.

**Comment by exomarty** [comment]
yeah i know is the same feature but changing its name it changes his meaning too

previously adding a favourite was like "i like this, i will save it and send notification to the poster"
now is just bookmarks, "i want to save this for the future"

and my list of bookmarks is private, why send notification to other person?

**Comment by barisusakli** [comment]
I agree we shouldn't generate a notification when someone favorites(bookmarks) a post.
