### ISSUE TITLE
sidebar issue

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4707]
just cosmetic but its still buggy on mobile

it will only happen on short content pages like a thead with only 1 post while you open close the sidebar

![sin titulo-7](https://cloud.githubusercontent.com/assets/10746278/15636432/a594c378-25fe-11e6-8e86-13df48b98865.png)

**Comment by pichalite** [comment]
duplicate... already reported on the theme's repo

https://github.com/NodeBB/nodebb-theme-persona/issues/183
