### ISSUE TITLE
opening a topic page in background tab in Firefox 46.0.1 makes the page bugged

### ISSUE THREAD

**Issue by darktrge** [NodeBB/NodeBB#4709]
Steps to reproduce:
open e.g. /recent
1)right-click on any topic->open in new tab
2)switch to the new tab
3)open console
4)you can see the error:
Error: Script error for: composer/formatting
http://requirejs.org/docs/errors.html#scripterror
5)try to click reply--->nothing happens. 
Page needs to be refreshed in order to restore it to fully functional state.
This doesn't seem to happen when regularly traversing pages in nodeBB.

I noticed this happening only in Firefox.
Any idea what's causing this?

**Comment by julianlam** [comment]
> Any idea what's causing this?

Not particularly, no, but this explains why one of the top routes that fail is the "composer/formatting" module.

Thanks for the report.

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-canned-responses/pull/4
