### ISSUE TITLE
Moving topics between NodeBB instances

### ISSUE THREAD

**Issue by alexschomb** [NodeBB/NodeBB#4710]
I know there have been several issues for moving a whole NodeBB database from one database to another. I'd like to do something different. My NodeBB has a sub-category with threads & posts that need to be moved to a different forum. But only this subset should be exported/imported. Is there any recommended solution?

**Comment by psychobunny** [comment]
This is pretty tough, unless you want to make all of the posts authored by the Guest user and give up data like votes and bookmarks 

I'm closing as it's not an "issue", please repost on our community forum. Alternatively, shoot an email at sales@nodebb.org if you'd like to commission the migration, thanks

**Comment by alexschomb** [comment]
I think you're right. This is not an issue. Thanks for clarification. Because of time constraints I'm going to transfer the posts by hand and adjust database settings accordingly.
