### ISSUE TITLE
Include upvoters and downvoters in post information

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#4721]
I have a use case where, as a registered user, I'd like to see all upvoters *and* downvoters. Could we make this an option?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/4688

**Comment by bdharrington7** [comment]
@barisusakli why I meant was, the actual names, I don't think this was intended by #4688

**Comment by barisusakli** [comment]
In that case it can be done as a plugin.
