### ISSUE TITLE
Separate route selector 

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4726]
Is it possible to add a toogle option to use this only on mobile while keeping default composer on desktop?
been testing and works very good on the phone without the known problems of floating composer mobile
could be a great custom fix till composer mobile is fixed

![screenshot_8](https://cloud.githubusercontent.com/assets/10746278/15842168/f2f3e8a2-2c56-11e6-8251-05a74a1191fc.png)

**Comment by pichalite** [comment]
is this still required?

**Comment by exomarty** [comment]
Prob not
