### ISSUE TITLE
Feature request: regular file upload permission by groups 

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/NodeBB#4730]
I've had this consideration myself and saw a post [within the community](https://community.nodebb.org/topic/8991/uploads-for-non-admins-mods) shortly after:
You currently can either allow regular (non-image) file uploads or disallow. There is no option to allow it for certain groups/users and/or for certain categories.

I'm missing this for the following reasons:
 * I don't want anyone to use file-space on my server
 * I want to be sure not getting any legal trouble because of uploaded files (thus only allowing for those I trust)

Another use-case I can think off is that you might want to allow `.doc` files within Category A and `.whatever` in Category B, but not vice versa. Therefore it would be great to have specific upload settings per category.
But this last one is not important for me, just a thought.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/d2cbd7e6dcbd76bcfbe26c9a45bfbc9012dba4ae
