### ISSUE TITLE
Registration Queue Display on Mobile is Incorrect

### ISSUE THREAD

**Issue by AmrEldib** [NodeBB/NodeBB#4733]
In NodeBB v1.0.2, When approving registrations on the mobile browser (Firefox for Android), the display doesn't respond correctly.
I have to scroll to the right to view all info and buttons.
Approval and rejection buttons are too small, and too close to each other. It's very difficult to click the correct one.
See the screenshot
![nodebb registration queue display bug](https://cloud.githubusercontent.com/assets/769272/15868074/f67246ec-2c9a-11e6-993a-2e5312a919a9.png)

**Comment by julianlam** [comment]
Hi Amr, this has already been addressed in the latest version of NodeBB  :smile:
