### ISSUE TITLE
Notifications in Darkly Theme are Unstyled, Show up Completely White

### ISSUE THREAD

**Issue by AmrEldib** [NodeBB/NodeBB#4735]
In NodeBB v1.0.2 darkly theme, unread notifications show up completely white; white text on white background.
This applies for toast notifications, and unread notifications in the notifications drop down list (when you click on the bell icon in the top right).

**Comment by julianlam** [comment]
Changed the notifications dropdown text colour to grey, otherwise the toaster notifications seems ok now.

![selection_047](https://cloud.githubusercontent.com/assets/923011/16012403/5c55425a-3157-11e6-8db4-9a0f80623ff1.png)

Upgrading your NodeBB shortly.

**Comment by BenLubar** [comment]
![screenshot 2016-06-14 at 10 49 59](https://cloud.githubusercontent.com/assets/4257305/16049563/c705a15a-321d-11e6-923e-701515c33966.png)

`#333333` text on a `#303030` background is pretty hard to read.

**Comment by julianlam** [comment]
Sure is :frowning:

**Comment by barisusakli** [comment]
![image](https://cloud.githubusercontent.com/assets/2583394/16304783/aa1d3e92-395f-11e6-94db-3cbfbe01dfb5.png)
