### ISSUE TITLE
Blacklist/Whitelist Email registration.

### ISSUE THREAD

**Issue by mastacontrola** [NodeBB/NodeBB#4736]
Email is a typical form of registration for Forums.  Particularly management of registration is a very difficult process.  However, there are many commonalities of "spam" email address registering.

I have attempted to search, but failed thus far, on seeing a plugin or system that allows you to blacklist specific domains.  We've seen an upshot of "spam" accounts created using various atypical domain names (that many are created with blank information and one or two following through and posting spam to our forums).

By having a mechanism to enable specific allowances/disallowances of email we can (hopefully) limit false created accounts leaving names available for "real" users.

**Comment by Lorindellia** [comment]
Do you mean ***@hotmail.com or by ip? I think you should try for mac address or api less likley to prevent legit users; and less easily thwarted.

**Comment by barisusakli** [comment]
Closing this as it can be done with a plugin easily, just use the hook `'filter:register.check'` and compare the incoming email against email whitelist/blacklist.
