### ISSUE TITLE
Disable "Create topics" Privilege for parent category not working

### ISSUE THREAD

**Issue by thphuc** [NodeBB/NodeBB#4748]
I have category structure like this: Mobile > Android/iOS.
I disabled (unchecked and saved) "Create topics" under privilege of Mobile category.
But when I open Mobile category, I still can create new topic.
Is this a bug or I did something wrong in Settings? Please help.

**Comment by pichalite** [comment]
Are you logged in as an admin user when you open the mobile category?

**Comment by thphuc** [comment]
Yes, I was. Is that the problem?

**Comment by pichalite** [comment]
Admins get all permissions. You can't remove them. This is not an issue.

**Comment by psychobunny** [comment]
Thanks @pichalite
