### ISSUE TITLE
CTRL-Enter does not grey out SUBMIT button (composer)

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4755]
Reply to a message.

Press CTRL-Enter

Looks like nothing's happening.

Click Submit

Message submits (from CTRL-Enter)-- but I also get a "YOU CANNOT POST MORE THAN ONCE IN 10 SECONDS"-- because the SUBMIT tried to submit a second time.

**Comment by julianlam** [comment]
Pinging @frissdiegurke

**Comment by frissdiegurke** [comment]
Fixed within `nodebb-plugin-shortcuts@1.1.2`.
FYI: It's been because of the hidden mobile submit button that received the `click` event instead of the visible desktop one. Thus the mobile one got disabled instead.
Thanks for report.
