### ISSUE TITLE
Feature Request: Separate mentions from group-mentions

### ISSUE THREAD

**Issue by yamikuronue** [NodeBB/NodeBB#4761]
I'm a moderator on a NodeBB instance, and I typically get a number of mention notifications in a day. I'd like to be able to distinguish in the notification when someone typed `@mods` and when they typed `@yamikuronue` so I know if they wanted me specifically or any moderator (as the latter is usually answered by the time I get there).

**Comment by julianlam** [comment]
Makes sense -- can you re-post this issue to julianlam/nodebb-plugin-markdown?

**Comment by yamikuronue** [comment]
Assuming you meant mentions and not markdone, done :)

**Comment by julianlam** [comment]
Yes, mentions :+1: thanks!

**Comment by julianlam** [comment]
Eh, while I'm here -- any idea what you want the text copy to be for the two variants?

**Comment by pichalite** [comment]
How about "username mentioned you using @group-name in topic-name?

**Comment by yamikuronue** [comment]
I would just go with "username mentioned @mods in topic-name", because it did and because I know I'm a member of the group.

**Comment by halcyon1234** [comment]
> I would just go with "username mentioned @mods in topic-name", because s/he did and because I know I'm a member of the group. 

I was just thinking the exact same thing, was going to post a bug about that, and saw yours.

So +1 to that format.  ++InformationDensity

**Comment by halcyon1234** [comment]
> I would just go with "username mentioned @mods in topic-name", because s/he did and because I know I'm a member of the group. 

I was just thinking the exact same thing, was going to post a bug about that, and saw yours.

So +1 to that format.  ++InformationDensity
