### ISSUE TITLE
Composer doesn't close after changing page

### ISSUE THREAD

**Issue by ArcticRaz0r** [NodeBB/NodeBB#4762]
Once the composer is opened, it does not close upon clicking a link to another page on the forum.
(source: affects http://community.nodebb.org/ )

**Comment by pichalite** [comment]
@ArcticRaz0r that's not an issue. it's designed to be like that.

**Comment by ArcticRaz0r** [comment]
@pichalite It still feels really weird to me (some of the moderators of my forum complained as well). What was the purpose behind this design choice?
Also, is it possible to turn it off?

**Comment by pichalite** [comment]
I believe it is designed so that you don't loose anything you typed in the composer if you navigate away and for situations where you may want to look at another topic or something while still composing.

**Comment by ArcticRaz0r** [comment]
Explained like that makes sense. Still, it's an unusual feature.
But just like you said, it's not an issue. Thanks for the explanation :)
