### ISSUE TITLE
Time limit for email confirmation is still in effect after changing email

### ISSUE THREAD

**Issue by ArcticRaz0r** [NodeBB/NodeBB#4763]
I registered on community.nodebb.org through GitHub's SSO and was assigned a Github noreply email address. I was unable to post anything without email confirmation, so I changed the email.
Despite that, I was forced to wait to request another confirmation email.

**Comment by julianlam** [comment]
Working as intended, when an email is changed, a confirmation email is automatically sent out, and resets this counter.

Let me know if this is in error.
