### ISSUE TITLE
"Global Moderators" and "administrators" not showing in category privileges matrix by default

### ISSUE THREAD

**Issue by ArcticRaz0r** [NodeBB/NodeBB#4764]
Guests and registered users are by default present in the categories' privileges matrix, but this isn't the case of *administrators* and *Global Moderators* who, by logic, should be present in every privilege matrix, even with "disabled" checkboxes, but still visible.

**Comment by julianlam** [comment]
Hi there --

There may be a case for including "global moderators" in the list, though administrators is superfluous, since admins always have privileges to all categories.

**Comment by ArcticRaz0r** [comment]
Makes sense indeed. Could this be called an "enhancement"?

**Comment by pichalite** [comment]
@julianlam don't the "global moderators" have the same privileges as administrators when it comes to categories?

**Comment by barisusakli** [comment]
Yeah global mods get all privileges as well.
