### ISSUE TITLE
Feature Request: "Reply to Later"

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4765]
Background/User Story: Writing on mobile sucks. Hard.  Harder than the suckiest suck that ever sucked on Suckworld in the dimension of Suck.

What I'm saying is that it's not good.  At all. Ever. And never will be.

So here I am, on mobile.  Browsing through a thread LIKE A BOSS.  There's a post I want to reply to, but I can't/won't because I don't like inflicting self-torture.  So I figure "Meh, I'll reply later".

But instead of just stopping there, I keep reading the thread.  And find another post.  And another, etc.

Soon my brain runs out of RAM, I can't remember which posts I want to reply to, or what I wanted to say.  Even once I get back to my PC with a sensible sized screen and a physical input device, I still don't remember which posts.  And I sure as krunk am not scrolling back through hundreds to find them.

This happens every day, a lot, to many users.  So here's a proposed solution:

REPLY TO LATER!

It can either but a button, or a checkbox in the upper right, or in the stupid Hamburger menu.  Doesn't matter.  You mark a post as "Reply to Later".  Ideally, that also shows you a small, one-line input where you can scribble a note.  Example:

http://i.imgur.com/WxvgNJu.png

The lightbulb (example glyph) is a state toggle button.

Now have an endpoint called /replylater or something really clever like that.  It will be a list of the posts I was going to reply to, complete with the REPLY/QUOTE buttons.  To make things smart, the list should show like:

Thread Title
[Reminder Note]
POST
Reply/Quote/Hamburger

If I reply, the post is removed from the list. If I hamburger then deselect the Reply Later, it disapears from this list.

Now I can read-only on Mobile as much as I want, and know what to reply to once I'm back on a proper computer.

**Comment by halcyon1234** [comment]
Inline of mockup:
<img src='http://i.imgur.com/WxvgNJu.png' />

**Comment by julianlam** [comment]
Definitely doable as a plugin (and I'd recommend it to be a plugin, as well), given that the functionality may not be intuitive to first-time users, and _may_ clutter the interface.

Given that the composer can be opened on any page (and can be used to reply to a specific post/topic), this should be straightforward to do if there are any interested parties.

**Comment by Tsaukpaetra** [comment]
@Lorne-Kates said in [The Official Status Thread](/topic/12236/the-official-status-thread/46864):
> Feature request: "Reply To Later"

Or maybe just simply "Don't open composer when in multi-quote mode", so you add your post quotes now and it stacks up in the composer, and when you're ready, click the Red Boob to actually formulate your replies.

But, that would require the appearance of the Red Boob on <del>mobile</del><ins>small width mode</ins>.

**Comment by Tsaukpaetra** [comment]
Or. OR!!! Just had an epiphany!

Expose the Red Boob functionality in the composer! It's still there (just hidden because CSS), so maybe if we have it instead be in the big expanse that is between the "Cancel" and "Submit" buttons the user could minimize the composer after typing up their reply to a particular post, and when adding another response it (as in current functionality) appends it to the composer and shows it again.

**Comment by barisusakli** [comment]
I think the drafts in harmony are good enough for this
