### ISSUE TITLE
Open modal - shift to padding-right: 15px;

### ISSUE THREAD

**Issue by KitsuneSolar** [NodeBB/NodeBB#4770]
Hi!
When open a modal window there is a shift to `padding-right: 15px;`.

![screenshot from 2016-06-20 13-18-42](https://cloud.githubusercontent.com/assets/12877339/16190952/79962116-36ea-11e6-98b0-3ed0f14e48d7.png)

**Comment by julianlam** [comment]
This is due to the scrollbar introduced by Bootstrap and is out of our control.

Sorry about that.

**Comment by KitsuneSolar** [comment]
@julianlam hack:

```
body {
  &.modal-open {
    padding-right: 0 !important;
  }
  div.bootbox {
    &.modal {
      padding-right: 0 !important;
    }
  }
}
```

?
