### ISSUE TITLE
Respect ignore for recent view

### ISSUE THREAD

**Issue by BarabasGitHub** [NodeBB/NodeBB#4774]
When ignoring a category of a forum it still shows up in the **recent** view, while it doesn't show in the **unread** view. This is counter-intuitive and I'd like to see this enhanced such that **ignore** is also respected for the **recent** view.

**Comment by BarabasGitHub** [comment]
I think these issues are related #3128 #4388

**Comment by exomarty** [comment]
Agree

**Comment by exomarty** [comment]
@barisusakli  @julianlam I think this could be nice to be included and it is next step for a correct topic filtering like unread already does 
what do you think?

**Comment by arasbm** [comment]
I would also like the ability to exclude a category (and all it's subcategories) from recent view. I would also like to exclude those from daily digest if possible.

## Here is our use case:
We would like to create a repository of tool at our makerspace. I created a category called [list of tools](https://community.kamloopsmakerspace.com/category/11/list-of-tools) with several sub categories, each representing a section of our makerspace. Every time someone wants to document a tool, they would make a post to the appropriate subcategory. We don't want those post to flood the main communication, but we would like it still to be integrated into the forum.
