### ISSUE TITLE
could not enter admin page with sso login

### ISSUE THREAD

**Issue by ewfian** [NodeBB/NodeBB#4778]
when i login with sso method use third party account ,i want to enter admin page it tells :
```
/%5Bobject%20Object%5D 未找到
您访问的页面不存在。返回首页。
```

but when i use [ /login?local=1](/)with my nodebb account to login ,it wokrs well.

**Comment by mralexgray** [comment]
i can confirm the admin page seems to have an entry point bug / different "logged in" checking heuristics.

i can easily go to "my profile", while still being asked for crews when going to ACP.

**Comment by lots0logs** [comment]
RE: #1972

**Comment by julianlam** [comment]
> Your SSO plugin will need to call onSuccessfulLogin when authentication completes.

From #1972.

**Comment by ewfian** [comment]
thanks
