### ISSUE TITLE
Delete account option

### ISSUE THREAD

**Issue by machado2** [NodeBB/NodeBB#4781]
It would be cool if I could delete my account in NodeBB forums, like I can do in Reddit. In Reddit's case, all posts are anonymized, replacing the username with [deleted].

This would help to maintain people's right to be forgotten, and would help preventing leaking personal information after a user is doxxed. A long history of posts makes anyone easy to identify on online communities, and that's bad for privacy.

**Comment by pichalite** [comment]
this option is already available for a long time now. It's available in the "Edit Profile" page.

**Comment by pichalite** [comment]
@machado2 FYI, site admins can disable this option. If you don't see this option, your admin has disabled user account deletion.

**Comment by julianlam** [comment]
Thanks @pichalite
