### ISSUE TITLE
Reply/Preview box cut off in Chrome

### ISSUE THREAD

**Issue by TheOnlyRealTodd** [NodeBB/NodeBB#4782]
I am using Chrome Version 51.0.2704.103 m and when I am replying (without maximizing the reply box at the bottom) to a thread, eventually when I fill up the reply area, the text continues to go off of the screen at the bottom but I cannot see it until I maximize the reply box. This seems very awkward and would be much better if there were a way to scroll down to see what I am typing without having to click the arrow button to expand the box up.

**Comment by TheOnlyRealTodd** [comment]
![nodebb bug](https://cloud.githubusercontent.com/assets/19983799/16315287/7cc44df6-3936-11e6-8f74-cd0adfc359a6.jpg)

**Comment by pichalite** [comment]
@TheOnlyRealTodd click and hold the maximize button and drag the composer until you see the reply box in full and leave it. The composer should stay at that position after that.
