### ISSUE TITLE
manually approve topics.

### ISSUE THREAD

**Issue by Caes95** [NodeBB/NodeBB#4792]
It is quite useful that users can make publications in some categories and then have to be approved by a moderator / administrator.

**Comment by pitaj** [comment]
You could use two categories: *submitted* and *approved*, and move topics from *submitted* to *approved*.

**Comment by Caes95** [comment]
The point is that in the same way, the publications will be visible to other users, and that is what is to be avoided, that when publishing in a category moderate, the publication is not visible to users until it is approved.

**Comment by pichalite** [comment]
this is probably useful if done as a plugin and not a feature in core.

**Comment by julianlam** [comment]
I agree that this is better served as a plugin :+1:
