### ISSUE TITLE
plugin.json meta-data should be made available in Plugin/Widget library

### ISSUE THREAD

**Issue by mralexgray** [NodeBB/NodeBB#4793]
Frequently.. I'll do something like the following in my WIdget/Plugin `init`..

```
fs.readFile(path.resolve(__dirname,'plugin.json'), function(e,data){
      Widget.meta = JSON.parse(data)
})
```

and later...

```
Widget.defineWidget = function(widgets, callback) {
	widgets.push({
		widget: Widget.meta.name.toLowerCase(),
		name: Widget.meta.name,
		description: Widget.meta.description,
      		content: Widget['widget']
	})
	callback(null, widgets)
};
```
We already carefully worded, named, and tended to the `plugin.json` file.  Let it help us..
- eliminate duplicate, error-prone, redundant info
- this data is _already loaded_, somewhere - by the time it's needed by us, in `library`
- could either be a property of `app`, or `params`, or `whatever'`

**Comment by barisusakli** [comment]
You can just `var pluginData = require('plugin.json');`
