### ISSUE TITLE
Why do we need plugin.json?  Just use package.json.

### ISSUE THREAD

**Issue by mralexgray** [NodeBB/NodeBB#4794]
In the same vein as #4793, why does this file (`plugin.json`) even need to exist?  Most often.. most of the fields are shared between the two.. and all of the _unique, additional_ stuff could simply be merged into the `package.json` file..  

I am somewhat new to `nodebb`, and am sorry if this is erroneous, previously debated, or has a clear "raison d'être" - that I'm missing..  
- Maybe `npm` doesn't like `package.json` to be co-opted for third-party uses?
- Maybe this has to do with `nodebb`'s package manager - but still, that's all the more reason to build on TOP of the familiarity and success of `package.json`, not in addition to!?

The current redundancy with these files fosters errors, confusion, frustration, and frankly, it kills babies.  

Thoughts?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/2578

I think the reason we have a plugin.json is to have a clear distinction of what belongs to nodebb and what belongs to npm. plugin.json should only contain the info required for the nodebb core.

**Comment by mralexgray** [comment]
That issue was simply closed - without a resolution... as was this one.  Is it not clear why this is a recurring issue? Or is it simply a "won't fix"? (labeling an issue as such is a welcome clarification, if so). ;-)
