### ISSUE TITLE
topics.changeWatching doesn't include callback arguments?

### ISSUE THREAD

**Issue by halcyon1234** [NodeBB/NodeBB#4797]
```
     window.socket.emit('topics.changeWatching', 
        {
            tid: tid,
            type: type
        }, 
        topicChangeWatchCallback);
```
Calls:
```
function topicChangeWatchCallback(a,b,c)
{
    console.log("done ", a, b, c);
}
```

which results in:
```
done null null undefined
```

Would be nice if there were actual values in there.  Like the tid that was ignored / watched / unwatched, etc.

**Comment by MegaGM** [comment]
There is no other arguments except possible error in callback to the `changeWatching` socket method.

> Would be nice if there were actual values in there. Like the tid that was ignored / watched / unwatched, etc.

If in your callback you get no error, then it means exactly "the tid was ignored / watched / unwatched, etc."

> null null undefined

Seems weird, it should be `undefined undefined undefined`, since `action` hooks don't return anything.

https://github.com/NodeBB/NodeBB/blob/master/src/plugins/hooks.js#L133

**Comment by halcyon1234** [comment]
Yes, but WHICH tid was effected?  It's an ansychronous callback.

Not quite sure where I'm hooking into in your link to get the result?

**Comment by barisusakli** [comment]
Well you have the tid that was effected since you are already passing it to the socket.emit.

```
 socket.emit('topics.changeWatching', { tid: tid, type: type }, function(err) {
       if (!err) {
           console.log(tid, type);
       }
 });
```

**Comment by MegaGM** [comment]
In some particular use cases you may run into a error "Uncaught ReferenceError: tid is not defined".
In this case consider JavaScript `.bind()` method. It will force the function not to forget about `tid` even if it'll lose it's scope.

```js
socket.emit('topics.changeWatching', { tid: tid, type: type }, topicChangeWatchCallback.bind(tid)});
```

Anyway, this issue doesn't seem like an issue of NodeBB itself. It's rather a question about usage. For this kind of questions, please, use the forum https://community.nodebb.org/
