### ISSUE TITLE
Forum timestamps became HTML after upgrade

### ISSUE THREAD

**Issue by Robotia** [NodeBB/NodeBB#4798]
Hello,

I recently upgraded from 0.9.4 (fde31d51125e69056c8d90fb1dc56bc50a8e0437) to 1.0.4-auto.9 (5d49af2f2a4476126bfb7f819fc26bb338b116bc). 

After upgrading, I noticed that the timestamps and post links became HTML, as though they were in a code tag:

> User administrators posted `<a class="permalink" href="/forum/topic/253/hmm/11"><span class="timeago" title=""></span></a> `

This occurs both when viewing the post and when looking at the info under post titles in a category.

Did I upgrade incorrectly? Is there anything I can do to fix this? Thanks!

**Comment by barisusakli** [comment]
Are you using a custom theme? If so switch to persona and try again.

**Comment by Robotia** [comment]
Thanks @barisusakli, I should've investigated that first.

Turns out I was just using an outdated version of the material theme plugin.
