### ISSUE TITLE
Just installed NodeBB locally and cannot to register

### ISSUE THREAD

**Issue by Krakean** [NodeBB/NodeBB#4799]
Hello.
Trying to install NodeBB on Windows using this manual - https://docs.nodebb.org/en/latest/installing/os/windows8.html
Everything is done (NodeJS 0.12.15, Redis 3.0.503). NodeBB version - from master branch (commit 3bebc3ce09) v1.0.3 - http://i.imgur.com/T0iXHSu.jpg
Seems to work fine, except that I cannot register as first user - http://i.imgur.com/dklOeyO.jpg - doesn't matter what I type in username, its just says that is too long.

**Comment by julianlam** [comment]
The first user should be configured during the `./nodebb setup` step, not by registering on NodeBB itself. As the admin user, you should be able to configure the username length settings. Not sure why they seem to be set incorrectly in your install.
