### ISSUE TITLE
user has title "cid:33:privileges:topics:read"

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4808]
https://what.thedailywtf.com/topic/20359/i-have-a-tag-next-to-my-name

![](https://i.imgur.com/G8YWvsu.png)

This happened after I added user-specific permissions for a category. The user's profile edit page does not show any options for titles (the only option is No Title).

**Comment by barisusakli** [comment]
@BenLubar you can probably select no title in their user profile page and hit save as an admin to remove the title.
