### ISSUE TITLE
Downtime visibility

### ISSUE THREAD

**Issue by yamikuronue** [NodeBB/NodeBB#4811]
The forum I moderate is struggling with some performance issues (aka "cooties"), and while we're trying to get to the bottom of it, users are losing confidence that their post will go through. 

When the socket loses connectivity, there is a very tiny spinner that appears in the corner, out of the way. Can this be something more intuitive instead, like the submit button greying out in the composer, or a toaster with something to the effect of "Please wait while we reconnect"? That way users know what to look for/wait for if they're concerned their post might get "lost".

**Comment by yamikuronue** [comment]
From one of my users:

>I'd reply there but then I'd have to remember my password. Instead of a toaster, I'd rather see a text message, maybe next to the submit button--and/or even the submit button changing color significantly or something (that is, rather than just the faded blue it gets now when you click it, actually becoming grey or red or something.)

**Comment by MegaGM** [comment]
For lazy one - make a new "special" kind of alerts 
`app.alert({type:'offline'})`
or even the easiest:
```js
socket.on('connect') => app.alert({type:'success'}) // only if it was after reconnecting
socket.on('reconnecting') => app.alert({type:'error'})
socket.on('disconnect') => app.alert({type:'error'})
```
But I'm not quite sure whether will it be appropriate for phones.

**Comment by julianlam** [comment]
>  (that is, rather than just the faded blue it gets now when you click it, actually becoming grey or red or something.)

My concern is that such a change would not be intuitive to the end user. Why would the submit button change colour? There's not much precedent for something like this :smile:

**Comment by yamikuronue** [comment]
Desaturated or grey is a pretty well known sign for "You can't click this right now". Red is also a universal sign for "Stop before you click this", but it's more used for things like "think twice, this will delete your data"

**Comment by julianlam** [comment]
It is, I just mean there's no intuitive message to the end user that they can't submit *because the forum is down*

**Comment by psychobunny** [comment]
Well I suppose this gets into that slippery slope where in the end all action buttons should change state when an action is happening while the forum goes down.

Aside from making sure the post doesn't actually get lost (that shouldn't be a problem, since it's stored locally) - maybe just fade out the screen a bit with a message going "Forum went down, please wait" etc? The reconnecting spinner on the top right may just not be obvious enough. Just a thought.

**Comment by yamikuronue** [comment]
>The reconnecting spinner on the top right may just not be obvious enough.

Personally, it was months before I even noticed the thing existed, and that's only because another user pointed it out to me. 

I do like the fadeout idea

**Comment by julianlam** [comment]
The fadeout would work, except then we'd have to discuss whether that's too overt of a message to send.

**Comment by BenLubar** [comment]
How about only doing the fade out when the user is interacting with NodeBB? If the forum server is restarted while the user is reading and they're not at the end of the infinite scroll "page", there's no need to tell them the server went down until they try to load more posts or upvote/reply to a post.

**Comment by MegaGM** [comment]
Fadeout when "composer is opened" only?

**Comment by julianlam** [comment]
@MegaGM In that case, I would be interrupted in the middle of my post composing to be told that NodeBB is down... and I'd probably want to continue posting.

**Comment by MegaGM** [comment]
`app.alert()` is the best way after all :dancer:
