### ISSUE TITLE
Streamed-in users on /users/sort-* do not have pretty printed numbers

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4819]
Example page: https://what.thedailywtf.com/users/sort-reputation

![](https://what.thedailywtf.com/uploads/files/1467625130252-fmt.png)

Only the first 24 have commas.

ref: https://what.thedailywtf.com/topic/20400/discoursistent-number-formatting

**Comment by pauljherring** [comment]
https://github.com/NodeBB/NodeBB/commit/aadd8835945d4088a6472526082b3fdbe8a82249

**Comment by barisusakli** [comment]
^^
