### ISSUE TITLE
Duplicated userslugs

### ISSUE THREAD

**Issue by vctfernandes** [NodeBB/NodeBB#4821]
Hey guys,

I have NodeBB running with a custom SSO login/registration using nodebb-plugin-sso-oauth.
Whenever my user already has a nickname on my site's social profile, profile.displayName will receive this name, when it's a new user, however, my site will simply pass 'User' to NodeBB.
Usually, it should number these users accordingly: User1, User2, etc... However, I've noticed that there is a number of users with username "User123" and userslug "user123", for example. This generates an issue where users can't access their own profiles, getting "access denied" errors.

Can anyone help me here?

**Comment by julianlam** [comment]
> Usually, it should number these users accordingly: User1, User2, etc... 

Usually according to whom? NodeBB will append three random numbers to a username if a username already exists with that slug. You should ideally always pass a unique username in, otherwise NodeBB will rename them upon user creation in order to avoid conflicts.

**Comment by vctfernandes** [comment]
Oh, got it. I thought that it would avoid duplicates automatically... Maybe that's a useful little feature for the future?

**Comment by julianlam** [comment]
Yeah, NodeBB _does_ avoid duplicates, is what I was trying to say. We just prefer to append 3 random numbers to the end, instead of using an incrementing number.

**Comment by vctfernandes** [comment]
Let's say that a user register withs User and gets, for example, User123 but User123 is already taken. Shouldn't NodeBB look for a new random number?

**Comment by julianlam** [comment]
Yes, NodeBB should keep trying new combinations until an unused username is found.

**Comment by vctfernandes** [comment]
Well, then I'm at a loss here... How come I have multiple equal duplicated usernames in my database?
Sorry, I'm just trying to understand what I did wrong here.
