### ISSUE TITLE
Create ISSUE_TEMPLATE.md for this repository

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4825]
For example: https://github.com/twbs/bootstrap/blob/master/ISSUE_TEMPLATE.md

... because bug reports without git hashes and proper descriptions are unfortunate :unamused:

**Comment by psychobunny** [comment]
Our `ISSUE_TEMPLATE.md` should look have 20 line breaks (so that the textarea looks blank) followed by a line going "Ah, nevermind, please close this issue"
