### ISSUE TITLE
navigation open in new tab overriden by user settings

### ISSUE THREAD

**Issue by phit** [NodeBB/NodeBB#4826]
### Version
1.0.3

### Reproduction
* set your user settings to open external links in new tab
* create a navigation item that is an external link and set it to not open in a new tab

### What you expected
clicking the navigation item opens the link in the same tab, navigation is outside the post area and shouldn't be affected by the user setting

### What happened instead
clicking the navigation item opens the link in a new tab and ignores what was set in the admin control panel for the navigation item making the whole setting rather pointless

**Comment by phit** [comment]
I believe I found a solution, the issue is actually theme related.
I'll open a pull request for the default themes.

**Comment by pitaj** [comment]
I'd expect user settings to override settings set in the ACP as far as link targets go.

**Comment by julianlam** [comment]
Normally, I would as well, but I have a feeling that when the option is selected, the expectation is that it applies only to user generated content (posts/topics/etc), and not other content provided by NodeBB...

**Comment by julianlam** [comment]
Actually, that introduced a regression, reverted for now.
