### ISSUE TITLE
Some of the incoming messages from "modules.chat.get" method does not contain roomId

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB/NodeBB#4834]
* [ ] NodeBB version: 1.0.3, git hash: 281db92279cef4749415c721f466413cad049989
* [ ] To call ```'modules.chat.get'``` function using javascript.
* [ ] all the message must contains an valid ```roomId```
* [ ] some does not contains ```roomId```.

**Comment by barisusakli** [comment]
Don't you already have the roomId, you should be passing it to `modules.chat.get` when you are making the call.
