### ISSUE TITLE
[1.0.3][mobile][admin] can't save Category changes

### ISSUE THREAD

**Issue by NaGeL182** [NodeBB/NodeBB#4836]
* [ ] v1.03; a196c834d9aab4e1c27965dcca623ce12e61b4ae
* [ ] Created a new category on Mobile (Sony XPeria Z1, Chrome, Android 5.1), edited the settings, hit save, nothing happened.
* [ ] I expected that the settings gets saved.
* [ ] I didn't save.

**Comment by NaGeL182** [comment]
ok I updated to 1.1.0; 296dc77c7bb2bbf92f711089d77e4f32f729951f

and the problem seems to be fixed.

**Comment by julianlam** [comment]
Thanks @NaGeL182
