### ISSUE TITLE
Badge appearing to users who have individual privileges over categories.

### ISSUE THREAD

**Issue by vctfernandes** [NodeBB/NodeBB#4837]
Hey guys, I'm using NodeBB 1.0.3 - a196c83

When I give an individual user privileges over a category, through ...admin/manage/categories/18#privileges, a badge appears right to his name with the text: "CID:18:PRIVILEGES:FIND". I'm guessing this shouldn't be happening, right? I'm using the persona theme.

PS: 18 is the CID of the category which I used to perform these tests.

**Comment by pichalite** [comment]
I think this is already fixed on master. You will have to wait for v1.1.0 for the fix to be available in a stable release or apply that fix manually to your installation.

https://github.com/NodeBB/NodeBB/issues/4808

**Comment by psychobunny** [comment]
That's correct, thanks @pichalite

We're likely releasing 1.1.0 tomorrow, but the current master is basically as stable as the 1.1.0 release

**Comment by vctfernandes** [comment]
Great! Thanks, guys!

**Comment by gdjam** [comment]
@psychobunny  wow, very cool ! 
The 1.1.0 will be released tomorrow? And the 1.0.4 is not ready for releasing ?  

i'm using 1.0.4_auto_11 these days~ 
looking forward to the 1.1.0 ! 👍

**Comment by vctfernandes** [comment]
Just so you guys know, @pichalite and @psychobunny 

Updated to 1.1.0 and the badge keeps appearing unless I untick the "Find Category" privilege.
