### ISSUE TITLE
Login redirect fail when disabling local login and registration  

### ISSUE THREAD

**Issue by rckrdstrgrd** [NodeBB/NodeBB#4840]
* [ ] NodeBB version 1.0.3 and git hash f475068010f5db60ba9fc88760303e146cf76fa2
* [ ] Install a SSO plugin. Disable local login and registration. Go to /login. 
* [ ] The user is redirected to the SSO provider for authentication
* [ ] The user is redirected to a 404 ( /%Object%object) 

When the login controller redirects to the external authentication provider it passes a object, `{external: data.authentication[0].url}`, to helpers.redirect(). 

https://github.com/NodeBB/NodeBB/blob/master/src/controllers/index.js#L121-L123

However, helpers.redirect() do not handle a object, it only supports a url as a string. So the redirect fails. 

https://github.com/NodeBB/NodeBB/blob/master/src/controllers/helpers.js#L53

**Comment by julianlam** [comment]
Thanks, confirmed. Seems low priority, however, since it happens on direct access only.
