### ISSUE TITLE
[Feature Request] Health Check url

### ISSUE THREAD

**Issue by digitalLumberjack** [NodeBB/NodeBB#4843]
Hi, we are planning on using nodebb for our forum, and it's really a great piece of work guys :)

We are setting an H.A. rancher environment and we would like to have a health check url to "ping" the containers from rancher.
The main issue with "/" is that every ping is counted in analytics, and right now i ping the **GET "/recent.rss" "HTTP/1.0"** but that means we cannot disable rss.

**Comment by julianlam** [comment]
If you're doing a simple uptime check, then any route will work (we just ping `/`, personally)...

Otherwise, I'd recommend you write a plugin that will expose such a route, e.g.

``` js
plugin.init = function(params, callback) {
	params.router.get('/ping', function(req, res) {
		res.sendStatus(200);
	});

	callback();
};
```

**Comment by julianlam** [comment]
Closing this issue, unless there is a specific defect or others want such a route bundled into core :smile:

**Comment by julianlam** [comment]
Oh, actually, I just re-read your issue and you mentioned "that every ping is counted in analytics", which is a legitimate issue.

**Comment by BenLubar** [comment]
Does the login page have analytics?

**Comment by julianlam** [comment]
It should. Any route that invokes `helpers.setupPageRoute` will have pageview analytics recorded.

@digitalLumberjack Could you try `/sitemap.xml`?

**Comment by digitalLumberjack** [comment]
Same thing as the feeds : the sitemap can be disabled.
I don't know how works standard pages but that would be nice to be sure
that when the healthcheck page returns a 200 , it means that node bb can
serve http requests but also have a mongodb connection ok.

**Comment by julianlam** [comment]
How about `/favicon.ico`?

**Comment by BenLubar** [comment]
Does `/favicon.ico` query the database at all?

**Comment by julianlam** [comment]
Database, no, though it will return if nodebb is up, but shouldn't increment the site view counter.

That said if NodeBB can't connect to the database it shouldn't start up anyway...

**Comment by barisusakli** [comment]
Why are we not adding a `/ping` or `/healthcheck` into core that does not increment analytics?

**Comment by julianlam** [comment]
We could, actually. Just depends if there's a real need for it.

**Comment by digitalLumberjack** [comment]
Great :)

**Comment by BenLubar** [comment]
It doesn't look like it touches the database at all.
