### ISSUE TITLE
language problem

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#4845]
http://imgur.com/5xsXjdp

**Comment by julianlam** [comment]
What posessed you to ignore the placeholder text when writing your issue? :frowning:

Need git hash for debugging purposes.

**Comment by julianlam** [comment]
Thanks in advance :smile:

**Comment by pikshub** [comment]
8fd5236

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/blob/master/public/language/tr/category.json

Added, thanks :smile:
