### ISSUE TITLE
Not able to log on with IE11 (or older)

### ISSUE THREAD

**Issue by trendzetter** [NodeBB/NodeBB#4846]
* version 1.1.0 & 1.0.3
* Exact steps to cause this issue
    1. install
    2. try to log in
* What you expected
    * Being logged on
* What happened instead
    * Got forbidden in a new tab (status 403)

**Comment by trendzetter** [comment]
login is ok with chrome and firefox btw

**Comment by psychobunny** [comment]
I didn't have a problem with 
IE 11.494.10586.0 on Windows

What version of IE11 do you have?

**Comment by psychobunny** [comment]
This commit https://github.com/NodeBB/NodeBB/commit/bb7303834f440a3e222fa64e294b6bf1a3f3fbf8

potentially fixes your issue. Can you upgrade and try again?

**Comment by trendzetter** [comment]
I will! But I only can when returning from vacation. Thanks in advance!

**Comment by itsGhost** [comment]
https://reece.sx/sqeS62FPNjXqKA0
(Internet explorer about)

Confirmed working on the latest "build" 

PEBKAC

**Comment by julianlam** [comment]
Thanks all.

**Comment by trendzetter** [comment]
I would like to reopen this issue

**Comment by trendzetter** [comment]
I am getting 
```
28/7 11:33 [27689] - error: /login
 invalid csrf token
```
In the logs and still the same issue. I already tried to revert to the default theme and skin but it looks horrible in IE and it doesn't allow me to log on.

**Comment by julianlam** [comment]
Reporter IE version:

![](https://cloud.githubusercontent.com/assets/6834530/17210798/5e3fdecc-54c5-11e6-96c7-2f316df61f89.PNG)

@trendzetter can you provide an image of what the login page looks like?

**Comment by trendzetter** [comment]
![knipsel](https://cloud.githubusercontent.com/assets/6834530/17211748/86e7d400-54cb-11e6-9715-3ae55466fb91.PNG)

**Comment by trendzetter** [comment]
I thought it might help if I tried a different version of node. I am running debian 8. I tried all versions of node from nodesource and the 0.10.29~dfsg-2 included with debian and the additional nodejs-legacy package but always the same result.

**Comment by trendzetter** [comment]
As I am able to log on https://community.nodebb.org/login I suspect the issue is the way it is installed. I think I applied the install instructions very strict. Did them over but no progress.

**Comment by pichalite** [comment]
Do you see any errors in the browser console? Try disabling all plugins and see if it works.

**Comment by trendzetter** [comment]
I disabled all plugins on the fresh install and the opened the IE developers console. There was no logging written to the console during rendering of the homepage nor during failed login. The only logging I get is at the server side:
```
28/7 15:47 [1879] - error: /login
 invalid csrf token
```
I tried logging on using firefox using an incorrect password it didn't write these lines. The "invalid csrf token" seems an indication of the underlying cause. I saw you need to update your nginx config to avoid this error when upgrading from earlier versions of nodebb. I am not upgrading and using nodejs directly for now.

**Comment by trendzetter** [comment]
I think I found something for your knowledge base. For some reason all our computers have "compatibility mode" enabled for intranet sites. 
All is OK and working great when I disabled the setting like this:
![knipsel](https://cloud.githubusercontent.com/assets/6834530/17215403/0274219e-54dd-11e6-8e7d-7fa865fde367.PNG)
I hope this helps someone else too.

**Comment by pichalite** [comment]
so, this can be closed?

**Comment by trendzetter** [comment]
Issue solved. Please close, thanks.

**Comment by HadeAs** [comment]
> I think I found something for your knowledge base. For some reason all our computers have "compatibility mode" enabled for intranet sites.
> All is OK and working great when I disabled the setting like this:
> ![knipsel](https://cloud.githubusercontent.com/assets/6834530/17215403/0274219e-54dd-11e6-8e7d-7fa865fde367.PNG)
> I hope this helps someone else too.

hi. i met same issue as you, i saw this comment, and want a try. but i can not see the pic in this comment. could you tell me how to do by text. thks lot!!!
