### ISSUE TITLE
Github SSO doesn't get the user email

### ISSUE THREAD

**Issue by digitalLumberjack** [NodeBB/NodeBB#4847]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash : v1.1.0
* Exact steps to cause this issue
    1. Install github sso plugin
    2. Activate your plugin with credential
    3. Connect with github sso login
* What you expected
    * User real email fetched, in oder to use it for notifications and updates.
* What happened instead
    * users.noreply.github.com email created because the email is not returned in the profile from github if it's not public. It must be fetched from the api. The main issue is that users.noreply.github.com is not an domain (nslookup users.noreply.github.com returns NXDOMAIN) so we cannot send email to anyuser@users.noreply.github.com.

I contacted github because i though it was an issue from their dns, but they do not allow people to send emails on this domain.

Thank you!

**Comment by julianlam** [comment]
Hi there, can you please re-post this onto the issue tracker for the Github SSO plugin? Thanks! :smile:

**Comment by julianlam** [comment]
https://github.com/julianlam/nodebb-plugin-sso-github/issues

**Comment by digitalLumberjack** [comment]
Sorry i don't know why but i though the issues are deactivated on this repo :( 
My bad :)

**Comment by julianlam** [comment]
Oddly, they were. In any case I have re-activated them :smile:

**Comment by digitalLumberjack** [comment]
This explain that :P
