### ISSUE TITLE
User can't "insert image" in post

### ISSUE THREAD

**Issue by vctfernandes** [NodeBB/NodeBB#4852]
NodeBB 1.0.3 - a196c83

Hey guys,

I'm having an issue where a single user can't insert image in his posts, every other user can do this with no problems, he's the only one having this issue. I've tried debugging it, but I have little information here:
His browser indicates a 500 error on /api/post/upload
No error appears on my logs
I'm using nodebb-plugin-composer-redactor

Anyone ever faced an issue like this? I don't even know what to look for lol

**Comment by pitaj** [comment]
If he's the only one getting this problem, I'd ask for his browser, OS, and internet provider. I'd also ask him to reset his cache and cookies for your site, as that could also cause issues.

**Comment by vctfernandes** [comment]
Actually, I've logged in to his computer by using TeamViewer and tried it myself through an anonymous window, so no cookies/cache involved :(
Still using his computer, I tried with another account and it worked flawlessly.
UPDATE: Using the secret login plugin, I logged to his account on my computer, and there was no issue at all.

The mystery goes on...

**Comment by gcshri** [comment]
Do you see this in dev mode?

19/7 06:20 [14824] - error: /api/post/upload
 invalid csrf token

**Comment by gcshri** [comment]
Apparently not supported in redactor.

https://github.com/NodeBB/nodebb-plugin-composer-redactor/issues/2#issuecomment-131546266

**Comment by julianlam** [comment]
@gcshri Looks like you'll have to use the imgur plugin so Redactor can work with uploaded images. Let me know if there's anything else.
