### ISSUE TITLE
Invalid user sessions after v1.0.3->v1.1.0 upgrade

### ISSUE THREAD

**Issue by jbob182** [NodeBB/NodeBB#4854]
Info:
- NodeBB version 1.1.0 (296dc77c7bb2bbf92f711089d77e4f32f729951f)
- Prior NodeBB version 1.0.3 (61404be94b1ad0487256065a4030c1a9df8b54cd)

After upgrading our forums  from 1.0.3 to 1.1.0 all user sessions are invalid.  When a user browsers the forums they receiving this notification: 
![session-notification](https://cloud.githubusercontent.com/assets/1146681/16859374/e6f3c5a8-49f3-11e6-9bff-dca46a20e2f0.PNG)

When they attempt to sign in, they are unable to do so and are prompted with the following message:
![invalid-session-login](https://cloud.githubusercontent.com/assets/1146681/16859375/e96146bc-49f3-11e6-9180-331a5607a77c.PNG)

Is there any quick fix we can perform? Else we will need to revert our forums tonight  inorder to allow daily operations to resume.

**Comment by pichalite** [comment]
this should fix your issue... add that rule to nginx and restart

https://github.com/NodeBB/NodeBB/issues/4734

**Comment by julianlam** [comment]
Thanks @pichalite

**Comment by jbob182** [comment]
That did it, thank you!
