### ISSUE TITLE
User profile -> ban user has confusing and wrong instructions

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4855]
https://github.com/boomzillawtf/tdwtf/tree/4866fca68b869575725e29627b5768ea868aa7fc
3df7bae08cea1dbb848500c4a4affb8533541743

Attempt to permanently ban a user from their profile page.

![](https://what.thedailywtf.com/uploads/files/1468598206253-screenshot-2016-07-15-at-10.56.13.png)

Instead of a permanent ban, this actually results in a ban that lasts 0 hours.

**Comment by julianlam** [comment]
Thanks, looks like a fairly pressing issue. In the meantime, might I suggest a 365 day ban?

**Comment by BenLubar** [comment]
Permanent bans from the admin panel work as expected.

**Comment by psychobunny** [comment]
I would just add a new button for permanent ban that calls the same method that the ACP does, instead of going for this 0 = permanent stuff

**Comment by pauljherring** [comment]
> In the meantime, might I suggest a 365 day ban?

Ah. We'll let you know how that works with Discourse in about [8 weeks](https://meta.discourse.org/users/pjh/activity)...

**Comment by julianlam** [comment]
Oddly I couldn't reproduce on my end, but nevertheless, I've applied a fix, please let me know if it works.

**Comment by BenLubar** [comment]
![screenshot 2016-10-28 at 10 44 05](https://cloud.githubusercontent.com/assets/4257305/19812562/a4373af0-9cfb-11e6-9640-bf3315214f30.png)

The ban was done by a global mod.
