### ISSUE TITLE
admins cannot revoke sessions owned by other users

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4856]
https://github.com/boomzillawtf/tdwtf/tree/4866fca68b869575725e29627b5768ea868aa7fc
3df7bae08cea1dbb848500c4a4affb8533541743

Sessions cannot be revoked for other users because this line retrieves the current user's sessions:
https://github.com/NodeBB/NodeBB/blob/3df7bae08cea1dbb848500c4a4affb8533541743/src/controllers/accounts/session.js#L19

Instead of `req.uid`, it should use `req.locals.uid`, which is set by [`middleware.exposeUid`](https://github.com/NodeBB/NodeBB/blob/3df7bae08cea1dbb848500c4a4affb8533541743/src/middleware/middleware.js#L267)

**Comment by pauljherring** [comment]
Ouch. So you couldn't have done it when I asked anyway?

**Comment by julianlam** [comment]
Thanks for triaging this but :smile:
