### ISSUE TITLE
regression: permanent bans expire immediately

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#4857]
https://github.com/NodeBB/NodeBB/blob/5ecbbd228d0ff8971f5e8f5b1612e7f53da2ac8a/src/user.js#L269-L284

If the ban is permanent, the callback is called with (null, null). Date.now() < null is <del>true</del><ins>false</ins>.

Additionally, the err argument is never checked.

**Comment by julianlam** [comment]
I assume you meant `Date.now() < null` is false, so they're `!stillBanned`, but nevertheless, this is a bug.

**Comment by BenLubar** [comment]
whoops! fixed.
