### ISSUE TITLE
Annoying bug in the recent releases!

### ISSUE THREAD

**Issue by xidui** [NodeBB/NodeBB#4862]
The browser back button not working if I do the following thing:

* NodeBB version 
1.0.3 and 1.1.0 both have this issue, versions before them I did not tested.
* Exact steps to cause this issue
    1. start noddbb at machine_ip:4567
    2. setup noddbb with default setting(mongodb)
    3. start nginx on the machine
    4. go to machine_ip
    5. go to any category
    6. click the browser back button and you will find that did not work. **The url at browser changed but the page did not change at all.**

* Something more
    1. if I go to machine_ip:4567, this issue disappear
    2. not only this page, other pages may also cause this problem
    3. some of the back button works well.
    4. this issue not always occur, it happens sometimes.

Thank you!

**Comment by xidui** [comment]
the nginx config is as follow:
```
```
upstream io_nodes {
    ip_hash;
    server 127.0.0.1:4567;
}

### the https server
server {
    # listen on ssl, deliver with speedy if possible
    listen 80;
    server_name <machine_ip>;


    # Socket.IO Support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    access_log /root/access.log;
    error_log /root/error.log;

    gzip            on;
    gzip_min_length 1000;
    gzip_proxied    off;
    gzip_types      text/plain application/xml application/x-javascript text/css application/json;

    location @nodebb {
        proxy_pass http://io_nodes;
    }

    location ~ ^/(images|language|sounds|templates|uploads|vendor|src\/modules|nodebb\.min\.js|stylesheet\.css|admin\.css) {
        root /public_bak;
        try_files $uri $uri/ @nodebb;
    }

    location / {
        proxy_pass http://io_nodes;
    }
}

 ```
```

**Comment by xidui** [comment]
Seems that if there is a proxy, the back button sometimes does not work well.

**Comment by julianlam** [comment]
Whenever the back button does not work, there is likely a client-side error displayed in the browser console. Please report that error. If it only occurs with nginx acting as a proxy, then I would presume it is a configuration error, and not an error with NodeBB itself.

**Comment by xidui** [comment]
@julianlam 
Sorry for the wrong information at first, I copied the while public data from the old forum which has this issue. So If I visit via nginx, this error always occur and disappear if I visit directly.

After that, I dug more information with the bug. And finally located that it was [nodebb-plugin-gravatar](https://github.com/julianlam/nodebb-plugin-gravatar) that cause this issue.

In my new environment, the error appear if I enable this plugin and disappear after I disable it.

Seems that you are also the author of that plugin, do you know why this occur?
 I also found that the websites response faster after I disable it.

**Comment by xidui** [comment]
@julianlam 
You can try [here](https://discuss.leetcode.com), the bug still exists. 
After enter the home page, then click `facebook` category, then click the back button. You can see that bug.

**Comment by xidui** [comment]
Found that the nodebb-plugin-gravatar plugin is blocked from China. This may cause the issue.

If I access with a proxy, it disappear.
