### ISSUE TITLE
[1.1.0] Setup: during web setup the admin password length is not checked

### ISSUE THREAD

**Issue by stevelacy** [NodeBB/NodeBB#4867]
Please include the following information when submitting a bug report/issue:

* NodeBB v1.1.0
* git hash 8584f9ac3c9d141f5c94a95b92cc7328037af7aa
* Exact steps to cause this issue
    1. clean clone
    2. npm install
    3. ./nodebb
    4. create admin account with a password of `admin` (to short)
* What you expected
    * An error message to be shown and the account to not be created.
* What happened instead
    * An error was thrown to the console (as expected) but the account was created anyway.
    * I could not log in to the admin account as the account was already created, but the password was to short.

Cheers

**Comment by julianlam** [comment]
Thanks for reporting, I can see how this would be an issue.
