### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by gdjam** [NodeBB/NodeBB#4869]
I have met the `csrf-invalid` problem!

`"csrf-invalid": "We were unable to log you in, likely due to an expired session. Please try again"`

I tried to clean all the cache and cookies of the chrome and restart, but still happened!

NodeBB: `V1.1.0` in github tag
Mongodb: `3.2.7`
SSL: no
Upgraded from: fresh installed

**Comment by julianlam** [comment]
Please alter your nginx config as defined here:

https://blog.nodebb.org/nodebb-v1-1-0-release/

**Comment by TheDevXen** [comment]
I am still getting the same error even after altering the nginx configuration
