### ISSUE TITLE
[1.1.0] Admin: modal overlay blocks usage on smaller screen

### ISSUE THREAD

**Issue by stevelacy** [NodeBB/NodeBB#4872]
Please include the following information when submitting a bug report/issue:

* NodeBB v1.1.0
* git hash 8584f9ac3c9d141f5c94a95b92cc7328037af7aa
* Exact steps to cause this issue
    1. Using a 940p width split screen I opened the Users page on the Admin panel.
    2. Click `new user`.
* What you expected
    * The modal z-index to be over the rgba overlay and the ability to interact with the modal.
    * Clicking the rgba overlay should close both the overlay and the modal.
* What happened instead
    * I was not able to interact with the modal due to the overlay being the wrong z-index.
    * This only happens when I resize the screen to be under 992px wide.

Wider than 992px

![selection_0152016dt](https://cloud.githubusercontent.com/assets/5648999/17004318/4df06a42-4e89-11e6-9025-fdd1820a9042.png)

Smaller than 992px
![selection_0162016dt](https://cloud.githubusercontent.com/assets/5648999/17004331/5d02aa4a-4e89-11e6-9905-5d69100b06b9.png)

Cheers

**Comment by julianlam** [comment]
Let me know if other modals suffer the same behaviour.
