### ISSUE TITLE
How to get NodeBB with mongo up and running in dockerized form for AWS

### ISSUE THREAD

**Issue by jahbini** [NodeBB/NodeBB#4873]
I have created a Dockerfile and docker-compose yml file to bring up my forum based commodity institute -- currently locate at forum.bamboosnow.com (pre-alpha as of July 21, 2016)

https://github.com/jahbini/nodebb-docker-aws

**Comment by pichalite** [comment]
Please use the community for questions on how-to's and help on NodeBB. https://community.nodebb.org
