### ISSUE TITLE
Multiple composer toggle on clicking new topic

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/NodeBB#4878]
Please include the following information when submitting a bug report/issue:
- NodeBB version and git hash: whatever's on community.nodebb.org on July 22nd
- Exact steps to cause this issue
  1. Can click multiple times on new topic on "Recent" page
  2. Click new topic in a category, navigate to another category and click new topic again
- What you expected
  - Only one fa-joylent AKA "red boob" visible at the bottom right
- What happened instead
  - Got a new one for each click

![image](https://cloud.githubusercontent.com/assets/13367628/17060455/1aa6c6c0-4ff8-11e6-9c68-d140726f6805.png)

**Comment by julianlam** [comment]
Thanks @boomzillawtf -- the first is definitely a bug. The second isn't, though it bears some explanation.

When you open the composer, it is tied to the cid you are composing to, **or** the topic you're replying to. If you click "new topic" again, and that composer is open, it will just focus on that one that is open.

So going to a different category and clicking "new topic" will just open a new composer tied to the new category you are in :smile:

**Comment by DoctaJonez** [comment]
Hi @julianlam,

The second one indicates a usability problem.  Are you guys considering changing the behaviour at some point so it is more intuitive?

**Comment by julianlam** [comment]
We're at time flip-flopping between removing the "multi-composer" portion of the composer completely (as a great majority of users don't even know it exists), and adding additional UX hints, though for the latter, we're open to ideas as we have none at the moment :smile:

**Comment by julianlam** [comment]
We could add a little circle at the top-right of the "red-plus" to show the category icon/image...

*cue jokes about tumours*

**Comment by pichalite** [comment]
The first thing I would suggest is to change the + icon as it does not represent what the button does.

**Comment by barisusakli** [comment]
I vote for removing multi composer and red boob.

**Comment by julianlam** [comment]
So given that there's talk for removing the multiple composer (which is fine, I think)... what would the new behaviour be if you have a composer open, and you click "New Reply" in a different topic?

**Comment by pichalite** [comment]
I guess... close the existing one and open new reply.

**Comment by yariplus** [comment]
@julianlam It should just warn you "Are you sure you want to discard your current post?" same as it does when clicking Discard button now.

**Comment by julianlam** [comment]
latest master && composer-default v6.3.10 :tada:

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/64457213-05bbc200-d0c0-11e9-816c-86c3121cd4fd.png)

Composer taskbar icon has an "active" indicator and adjusts background-colour, icon, and image when switching categories.
