### ISSUE TITLE
User registration failure with TOS enabled.

### ISSUE THREAD

**Issue by tailot** [NodeBB/NodeBB#4883]
Nodebb version 1.1.0 and 1.1.1-auto

User registration failure with TOS enabled. The user remains stuck to pending.

To replicate the problem:
- Enable a TOS on /admin/settings/user
- Create a user with a local registration

Regards
Vincenzo Tilotta

**Comment by barisusakli** [comment]
Seems like the redirect to /register/complete doesn't work.

**Comment by julianlam** [comment]
Thanks @barisusakli

**Comment by julianlam** [comment]
Not sure why, but works fine if I revert 98368bbb6a43be6f9666b3057a50ff189b9c52cc.
