### ISSUE TITLE
New users are admonished for following directions

### ISSUE THREAD

**Issue by Pascal666** [NodeBB/NodeBB#4885]
NodeBB v1.1.0
git hash 296dc77c7bb2bbf92f711089d77e4f32f729951f

If Require Email Confirmation is enabled at /admin/settings/user , immediately after creating a new account the user has an orange notice in the lower right corner stating "Your email has not been confirmed yet, please click here to confirm your email.".  If they click there they then get a red notice saying:

ERROR
Confirmation email already sent, please wait 10 minute(s) to send another one.

**Comment by BenLubar** [comment]
Responsible code is here: https://github.com/NodeBB/NodeBB/blob/b08696515fdd5395138d650198f7874df04e6b3c/public/src/app.js#L488-L502

**Comment by julianlam** [comment]
Looks to be a UX issue that should be addressed, thanks @Pascal666 :smile:

**Comment by Pascal666** [comment]
I would think that the "please click here to confirm your email" message should never show up if clicking it would just result in an error.  Perhaps in that case the second half of that message should start more along the lines of "please check your email".

**Comment by julianlam** [comment]
Actually, @psychobunny noticed that on a certain other forum, if the email domain matched one from a common list (think Hotmail, Gmail, etc.), it would go as far as showing them a link to their mail client :smile:

**Comment by pichalite** [comment]
@julianlam that's probably overkill.
