### ISSUE TITLE
Feature Request: Link to Home page at top of admin console

### ISSUE THREAD

**Issue by Pascal666** [NodeBB/NodeBB#4890]
Most pages have a large link to the home page in the top left, the exception being the admin console.  It would be nice to have one there too.  Thank you.

**Comment by pichalite** [comment]
it's already available in the top right corner

![image](https://cloud.githubusercontent.com/assets/10014774/17114290/173928c6-5263-11e6-966d-c909cbbcbef9.png)

**Comment by Pascal666** [comment]
Thank you.  Did not know that.

It would still be nice if it was more consistent throughout the site.  From a noob standpoint that link is less than obvious.  I've spent many hours in there lately, often cursing the lack of a link.
