### ISSUE TITLE
Modal voters language phrases

### ISSUE THREAD

**Issue by KitsuneSolar** [NodeBB/NodeBB#4891]
![screenshot-2016-07-26-18-49-04](https://cloud.githubusercontent.com/assets/12877339/17145301/54fd3076-5362-11e6-8908-33f8c0bb24b0.png)

NodeBB v1.1.0
Clean install.

**Comment by julianlam** [comment]
Can you test on master? This may have been fixed already...

**Comment by pichalite** [comment]
https://github.com/NodeBB/NodeBB/pull/4848

**Comment by KitsuneSolar** [comment]
Closed!
