### ISSUE TITLE
Not able to log on with IE11 (or older)

### ISSUE THREAD

**Issue by trendzetter** [NodeBB/NodeBB#4893]
* NodeBB version: master git hash af75a887b5a0ca007a7d802231654f0626cfec39
* node -v

v6.3.0
* redis-cli -v

redis-cli 3.2.1
* Exact steps to cause this issue
    1. Fresh install
    2. try to log on using IE
* What you expected
    * The admin is logged on
* What happened instead
    * in the log:
```
28/7 12:42 [28253] - error: /login
 invalid csrf token
```
    * in the browser: New tab with "Forbidden" 
I logged on using Firefox and Chrome without issues.

I notice the design of the page in IE is also very skewed.

![knipsel](https://cloud.githubusercontent.com/assets/6834530/17210798/5e3fdecc-54c5-11e6-96c7-2f316df61f89.PNG)

**Comment by trendzetter** [comment]
I logged an earlier issue but it was closed before I was able to test the solution. The proposed solution did not work: **https://github.com/NodeBB/NodeBB/issues/4846**
Closing issues without the reporters confirmation is bad practice.

**Comment by julianlam** [comment]
Thanks for giving us all of 1 hour and 16 minutes' (at 5:44am, no less) warning to re-open an issue before you resubmitted it again.

**Comment by trendzetter** [comment]
I don't want to be difficult. I am unfamiliar with you regulations and unsure how to best pass my test results on to you. I really hope to get this running in IE, not because I am a fan of IE but because I need to convince the management of the company too.
