### ISSUE TITLE
Navbar pagination buttons

### ISSUE THREAD

**Issue by crobinson42** [NodeBB/NodeBB#4899]
I just performed an `update` to the most recent version. I notice my navbar is pushed down due to the placeholder of this:

```
<ul class="nav navbar-nav navbar-right pagination-block visible-lg visible-md">
					<li class="dropdown">
						<i class="fa fa-angle-double-up pointer fa-fw pagetop"></i>
						<i class="fa fa-angle-up pointer fa-fw pageup"></i>

						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<span class="pagination-text">1 out of 1</span>
						</a>

						<i class="fa fa-angle-down pointer fa-fw pagedown"></i>
						<i class="fa fa-angle-double-down pointer fa-fw pagebottom"></i>

						<div class="progress-container">
							<div class="progress-bar" style="width: 100%;"></div>
						</div>

						<ul class="dropdown-menu" role="menu">
  							<input type="text" class="form-control" id="indexInput" placeholder="Enter index">
  						</ul>
					</li>
				</ul>
```

I found it in these files:

```
admin@therms:~/web/community.therms.io$ grep -rnw '.' -e "fa fa-angle-double-up pointer fa-fw pagetop"
./node_modules/nodebb-theme-material-dark/templates/partials/menu.tpl:52:                    <i class="fa fa-angle-double-up pointer fa-fw pagetop"></i>
./node_modules/nodebb-theme-vanilla/templates/partials/menu.tpl:180:						<i class="fa fa-angle-double-up pointer fa-fw pagetop"></i>
./node_modules/nodebb-theme-persona/templates/partials/menu.tpl:166:						<i class="fa fa-angle-double-up pointer fa-fw pagetop"></i>
./public/templates/header.tpl:238:						<i class="fa fa-angle-double-up pointer fa-fw pagetop"></i>
./public/templates/partials/menu.tpl:180:						<i class="fa fa-angle-double-up pointer fa-fw pagetop"></i>
```

It's visible ONLY after logging here: `http://community.therms.io`

Can anyone point out why this positioning is?

**Comment by pitaj** [comment]
You probably want to take this to the `nodebb-theme-material` repo. This seems like a theme-specific issue.

**Comment by pichalite** [comment]
@pitaj not really. The code he posted above doesn't belong to the material theme. It's persona.

**Comment by pitaj** [comment]
@pichalite The website http://community.therms.io is running Material.

**Comment by crobinson42** [comment]
I changed the theme to material because of this issue.

**Comment by crobinson42** [comment]
The issue with the html I posted is it's being read like `display:block` & `display:hidden` causing a new row to push down, even when it's not visible. Any ideas?

**Comment by pitaj** [comment]
I dunno. I'd have to see it myself. I guess mess around with CSS in the developer tools and see if you can get it to look right?

**Comment by crobinson42** [comment]
What are the requirements for a PR if I find a fix?

**Comment by pitaj** [comment]
You have to sign the contract. And have code that works.

**Comment by pichalite** [comment]
@crobinson42 there is only so much space in the header. You have a rather large title. Consider using a smaller one or other options to fit everything that's needed. This is not an issue as far as I know.

**Comment by crobinson42** [comment]
You got it. Thanks for your thoughts.
