### ISSUE TITLE
Client-side filter hooks proposal

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#4900]
At the moment, there are client-side action hooks, but these are inadequate for may of the use-cases of hooks in a NodeBB sense. I propose the creating of a full hooks system, separate from jQuery events. 
## Types

**HookType : String**
- if `'static'`  
  Hook only occurs once per page load
- if `'action'`  
  Given the result of an action, but can not modify the action taken
- if `'filter'`
  Given the data before an action is taken. Can mutate the given data or cancel the action by providing null to the `next` callback function
- any other value throws an error

**HookName**
- Can only contain alphanumeric plus period, underscore, and dash (`_`, `-`)
- Usually namespaced to the general area of effect (`composer`, `posts`, etc)

**HookID : String**
- RegExp: `/^(static|action|filter):([a-zA-Z0-9._\-]*)$/`
  - [1]: HookType
  - [2]: HookName
- Split on `:` to separate HookType and HookName in runtime
## Public Methods

All methods of `window.app`.

**`.plugins.fireHook(id[, data][, callback])`**
- `id` : HookID
- `data` : Object
  - Contains all data relevant to hook event
  - `event` field reserved for a relevant DOM event
- `callback(err, filteredData)` : Function
  - `err` : Error | null  
    An error returned when one of the plugin handlers encountered an error, null for no error
  - `filteredData` : Object | null  
    The modified object returned from the plugin handlers in the case of no errors
  - Called after all registered hook handlers have been called
  - Mandatory if type is `filter`

**`.plugins.registerHook(id, handler[, priority])`**
- `id` : HookID
- `handler(data, next)` : Function
  - `data` : Object  
    Data passed to `fireHook` or from previous handler function
  - `next(err, filteredData)` : Function
    - `err` : Error | null  
      null for no error, an error object to indicate the plugin encountered an error when executing the hook
    - `filteredData` : Object  
      Modified data object filtered by the plugin. Falsy to indicate cancellation of the action
- `priority` : Integer  
  - The priority of the plugin's filter behavior
  - Lower numbers indicate higher priority
  - No priority is treated as lowest priority

**Comment by julianlam** [comment]
> Can mutate the given data or cancel the action by providing null to the next callback function

There are a couple placed in the server-side where this pattern is done as well, so that works for me.

In general, we'd want to limit it to the `app` global, so as to not pollute the global namespace.

**Comment by pitaj** [comment]
@julianlam Yeah, in this case, `app.plugins.fireHook` and `app.plugins.registerHook`

**Comment by MegaGM** [comment]
The concept itself sounds good to me, even though it will make NodeBB even more confused and hard to comprehend.

**Comment by pitaj** [comment]
@MegaGM Well now is the time to propose an alternate way to do what I need. 

I want to add a confirmation to the submit action on the composer when an event is deleted. 
https://github.com/pitaj/nodebb-plugin-calendar/blob/1.0.x/src/client/setupComposerButton.js#L50

**Comment by yariplus** [comment]
Just throwing this out there, but it is possible to do this with the existing jQuery system.

```
$(window).on('filter:composer.submit', {priority: 1}, function (event, data, next) {
  data.isTrueTrue = true;
  next(null, data);
});
```

You can throw random data to the event, and in fireHook(), sort the events by the priority passed in, and call their handlers in that order.

**Comment by pitaj** [comment]
@yariplus the issue with using jQuery is that when firing the hook you still have to call the handlers one by one and then call the main callback, whereas without using jQuery events it's actually simpler since you don't have to call internal jQuery methods to grab the event handlers.

**Comment by yariplus** [comment]
@pitaj Yes, I'm aware, I agree now.

I like that `app.plugins` is similar to what is on the server-side. And it's much more readable than `$(window).on` and `$(window).trigger`.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/01c9b1847ec7521c5a99505e00e591e2f83143b2#diff-5093b43fee154244daa3166abb06967ce26143553eafce199ad003e72cee82f9
