### ISSUE TITLE
search is not working

### ISSUE THREAD

**Issue by michalliu** [NodeBB/NodeBB#4902]
My site is http://cn.mqmaker.com search isn't working for me.

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
nodebb rev: c3fc1347ec850d0b2f94b4e12db94f6dc1d4b808

* Exact steps to cause this issue
    1. Click search button

* What you expected
    Search should work

* What happened instead
    an exception is thrown

> MongoError: exception: $sort key ordering must be specified using a number
>     at Function.MongoError.create (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
>     at queryCallback (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:200:36)
>     at Callbacks.emit (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/callbacks.js:55:3)
>     at null.messageHandler (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:314:23)
>     at Socket.<anonymous> (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
>     at Socket.emit (events.js:95:17)
>     at Socket.<anonymous> (_stream_readable.js:748:14)
>     at Socket.emit (events.js:92:17)
>     at emitReadable_ (_stream_readable.js:410:10)
>     at emitReadable (_stream_readable.js:406:5)
>     at readableAddChunk (_stream_readable.js:168:9)
>     at Socket.Readable.push (_stream_readable.js:130:10)
>     at TCP.onread (net.js:528:21)
> 

And this error

> MongoError: exception: invalid operator: $search
>     at Function.MongoError.create (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
>     at queryCallback (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:200:36)
>     at Callbacks.emit (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/callbacks.js:55:3)
>     at null.messageHandler (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:314:23)
>     at Socket.<anonymous> (/root/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
>     at Socket.emit (events.js:95:17)
>     at Socket.<anonymous> (_stream_readable.js:748:14)
>     at Socket.emit (events.js:92:17)
>     at emitReadable_ (_stream_readable.js:410:10)
>     at emitReadable (_stream_readable.js:406:5)
>     at readableAddChunk (_stream_readable.js:168:9)
>     at Socket.Readable.push (_stream_readable.js:130:10)
>     at TCP.onread (net.js:528:21)
> 2/8 20:09 [2092] - error: [plugins] filter:search.query,  exception: invalid operator: $search

**Comment by michalliu** [comment]
BTW: There are two search buttons at the nav menu, neither one is working.

**Comment by barisusakli** [comment]
What is your mongodb version?

**Comment by michalliu** [comment]
> root@d6a98b68a462:~# mongod --version
> db version v2.4.10
> Thu Aug  4 01:19:59.096 git version: nogitversion

**Comment by michalliu** [comment]
> root@d6a98b68a462:~/nodebb# ./nodebb log    
> 
> Type Ctrl-C to exit
> 
> 2/8 19:58 [1955] - info: [database] Checking database indices.
> 2/8 19:58 [1953] - info: [database] Checking database indices.
> [outdated] mongodb installed v2.1.22-alpha4, package.json requires ~2.1.3
> 2/8 19:58 [1955] - warn: One or more of NodeBB's dependent packages are out-of-date. Please run the following command to update them:
> 2/8 19:58 [1955] - warn:     ./nodebb upgrade
> [cluster] Child Process (1955) has exited (code: 0, signal: null)
> [outdated] mongodb installed v2.1.22-alpha4, package.json requires ~2.1.3
> 2/8 19:58 [1953] - warn: One or more of NodeBB's dependent packages are out-of-date. Please run the following command to update them:
> 2/8 19:58 [1953] - warn:     ./nodebb upgrade
> [cluster] Child Process (1953) has exited (code: 0, signal: null)

**Comment by michalliu** [comment]
I aslo tried to run nodebb upgrade, it seems not helpful

> root@d6a98b68a462:~/nodebb# ./nodebb upgrade
> 1. Bringing base dependencies up to date... OK
> 2. Checking installed plugins for updates... OK
> 3. Updating NodeBB data store schema...
> 4/8 01:29 [2378] - info: [database] Checking database indices.
> 4/8 01:29 [2378] - info: Beginning database schema update
> 4/8 01:29 [2378] - info: [2015/12/15] Chats upgrade skipped!
> 4/8 01:29 [2378] - info: [2015/12/23] Chats room hashes upgrade skipped!
> 4/8 01:29 [2378] - info: [2015/12/23] Adding theme to active plugins sorted set skipped!
> 4/8 01:29 [2378] - info: [2016/01/14] Creating user best post sorted sets skipped!
> 4/8 01:29 [2378] - info: [2016/01/20] Creating users:notvalidated skipped!
> 4/8 01:29 [2378] - info: [2016/01/23] Creating Global moderators group skipped!
> 4/8 01:29 [2378] - info: [2016/02/25] Social: Post Sharing skipped!
> 4/8 01:29 [2378] - info: [2016/04/14] Group title from settings to user profile skipped!
> 4/8 01:29 [2378] - info: [2016/04/19] Users post count per tid skipped!
> 4/8 01:29 [2378] - info: [2016/04/29] Dismiss flags from deleted topics skipped!
> 4/8 01:29 [2378] - info: [2016/05/28] Giving topics:read privs to any group that was previously allowed to Find & Access Category - skipped!
> 4/8 01:29 [2378] - info: [2016/06/13] Store upvotes/downvotes separately skipped!
> 4/8 01:29 [2378] - info: [2016/07/12] Upload privileges skipped!
> 4/8 01:29 [2378] - info: [upgrade] Schema already up to date!
> OK
> 
>                                                             NodeBB Upgrade Complete!

**Comment by pichalite** [comment]
MongoDB version 2.6 or greater is required for NodeBB. You have 2.4.10 installed. Upgrade your mongodb installation.

**Comment by julianlam** [comment]
@michalliu Most likely you have multiple versions of MongoDB installed, so you'll want to resolve that and ensure a newer version of MongoDB is running.
