### ISSUE TITLE
Odd Home Page Problem Defaulting to Blank Custom Setting

### ISSUE THREAD

**Issue by scottalanmiller** [NodeBB/NodeBB#4903]
NodeBB 1.1.0 
296dc77c7bb2bbf92f711089d77e4f32f729951f

https://mangolassi.it/topic/10079/same-bugs-for-days-now

Users and finding their home pages set to /custom but without having set it and with the field blank so the page just errors out.  We've had a few reports of this.

**Comment by sorvani** [comment]
I was not getting the error page the other users were, but when I went to check settings to corroborate the reports I noticed mine set to custom and blank.

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/c042d16f404ea421bc2c10bc08113c8ae76c8e83#commitcomment-18536057

**Comment by barisusakli** [comment]
This is already fixed in https://github.com/NodeBB/NodeBB/commit/c042d16f404ea421bc2c10bc08113c8ae76c8e83#commitcomment-18536057
