### ISSUE TITLE
Unable to reply to topics 

### ISSUE THREAD

**Issue by JonathanWatkins** [NodeBB/NodeBB#4904]
Nodebb hash 296dc77c7bb2bbf92f711089d77e4f32f729951f

As admin on the forum go to IOS mobile in chrome or lastpass browser go to any topic that I do not own and the reply to topic button does nothing. If I add a custom header script to the site so I can see errors, when I first load a topic that I don't own I see the window.error gives me this error message.

TypeError: undefined is not an object (evaluating 't.addButtonDispatch')  

or sometimes this

TypeError: undefined is not an object (evaluating 'formatting.addButtonDispatch')

This does not happen on the desktop or on pages I own.

**Comment by barisusakli** [comment]
Is it happening at https://community.nodebb.org/ ?

**Comment by psychobunny** [comment]
Also, what's the version of your chrome browser?

**Comment by barisusakli** [comment]
Should fix this, let us know if you still experience it.
https://github.com/NodeBB/nodebb-plugin-composer-default/commit/b1a21a449c1c355096f21d4278a436a5fcce8714
