### ISSUE TITLE
Can not be translated phrases: move post pop up

### ISSUE THREAD

**Issue by KitsuneSolar** [NodeBB/NodeBB#4905]
![screenshot-2016-08-03-01-18-31](https://cloud.githubusercontent.com/assets/12877339/17347401/598b6548-5918-11e6-933d-24d49635558d.png)

Hi!
Phrases "Topic ID" & "Enter topic ID" can not be translated.

**Comment by BenLubar** [comment]
https://github.com/NodeBB/nodebb-theme-persona/blob/5bd48efd445677b2c883cb69494983e8d31f5e7f/templates/partials/move_post_modal.tpl#L10-L11 should be using these strings: https://github.com/NodeBB/NodeBB/blob/7f689c2afd4e186b17b31c067b746c44e3d8caa3/public/language/en_GB/topic.json#L3-L4

**Comment by KitsuneSolar** [comment]
@BenLubar , @pichalite thanks!
// Closed!
