### ISSUE TITLE
why set returnTo in session when api route is not authorized?

### ISSUE THREAD

**Issue by manV** [NodeBB/NodeBB#4906]
I am hitting this case where I have a custom home page(completely separate from NodeBB), where I am using /api/me to display Logged in user's username and profile picture and if the user is not logged in, I am sending him/her to the login page. Now because returnTo is set on unauthorized, after login the users are going to /me page which does not exists as returnTo is getting set on /api/me call because of the line in the link.

https://github.com/NodeBB/NodeBB/blob/fcf145fc81a12df2ab2d68b15252d1a180662791/src/controllers/helpers.js#L39

**Comment by barisusakli** [comment]
Yeah that route is just an /api route so it shouldn't use the regular helpers.notAllowed() which is for regular pages.
