### ISSUE TITLE
Disabled plugins selector

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4908]
![screenshot_6](https://cloud.githubusercontent.com/assets/10746278/17383572/f20538da-59d6-11e6-9009-32236c35010f.png)

another filter for disabled plugins, possible enhancement

**Comment by julianlam** [comment]
Okay... this time I have to ask why? The page is already very confusing, and we discussed removing the active filter just yesterday.

**Comment by exomarty** [comment]
i find active filter very usefull, actually i only use that
if you have many plugins is faster to search with active filter  also you have a better global vision on all stuff running 
about disabled same case, less usefull but nice if you want to clean some old plugins
