### ISSUE TITLE
Chat modal not working on account info page

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4910]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.0
* Exact steps to cause this issue
    1. Go to user profile, clic account info to see ips,flags...
    2. Then open menu again and click chat with user
* What you expected
    * chat to be opened
* What happened instead
    * nothing

Thank you!

**Comment by pichalite** [comment]
Seems to be fixed on master.
