### ISSUE TITLE
Improve topic forking UI

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4911]
Currently:

![selection_067](https://cloud.githubusercontent.com/assets/923011/17409555/c6dd6cba-5a3d-11e6-9ff0-cca3ca7ebee6.png)

**Comment by julianlam** [comment]
New:

![selection_068](https://cloud.githubusercontent.com/assets/923011/17409571/da80f2f0-5a3d-11e6-9467-a4604bf23c9e.png)

Open to suggestions for improvements, of course.

**Comment by barisusakli** [comment]
:+1:

**Comment by pichalite** [comment]
@julianlam fork modal should be closed on ajaxify.

**Comment by julianlam** [comment]
Makes sense :laughing:

**Comment by pichalite** [comment]
require translator as well in fork.js (instead of global) while you are at it :smile:
