### ISSUE TITLE
Terms of use not appearing when pressing "Register"

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#4914]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash * NodeBB version and git hash : 1.1.0 - 296dc77c7bb2bbf92f711089d77e4f32f729951f

* Exact steps to cause this issue
    1. Enable Terms of Use
    2. On another browser (Chrome or Firefox) go to register - terms of use box is not showing at this stage. Fill out details.
    3. Pressing register seems to do nothing. However if clicking the forum name link or refresh, the terms of use appears.

Using theme persona. Also have the spam-be-gone plugin enabled, but disabling it makes no difference.

site https://retropie.org.uk/forum/

**Comment by joolswills** [comment]
Also to note this definitely worked before  - I don't think I have changed anything except for upgrading to v1.1.0

**Comment by joolswills** [comment]
As I think this was working before, I will duplicate the forum setup and git bisect it (when I have a free moment).

**Comment by julianlam** [comment]
@joolswills Thanks, pretty sure I know where this regression came from. Can take a look at it next time I'm in office.

**Comment by barisusakli** [comment]
Sounds like https://github.com/NodeBB/NodeBB/issues/4883 might be already fixed on master.

**Comment by joolswills** [comment]
I can confirm that has fixed it. I have cherry-picked the commit to a temporary branch for now.

Should I be using the automatically tagged releases ? This is quite a serious problem as it affects users being able to register, so it would be good to have a  v1.1.1 or similar with the fix.

**Comment by joolswills** [comment]
thanks

**Comment by barisusakli** [comment]
Either 1.1.1 or it should be backported.
