### ISSUE TITLE
Notification: user_mentioned_you_in

### ISSUE THREAD

**Issue by KitsuneSolar** [NodeBB/NodeBB#4915]
Hello! At mention the user, he receives a notification containing:

> user_mentioned_you_in

![screenshot-2016-08-06-18-29-16](https://cloud.githubusercontent.com/assets/12877339/17457549/baf79520-5c03-11e6-9241-bf7d41192861.png)

**NodeBB 1.1.0**

**Comment by KitsuneSolar** [comment]
Error found!

https://docs.nodebb.org/en/latest/scaling/index.html#sample-nginx-configuration-with-all-of-the-above-applied

```
    location ~ ^/(images|language|sounds|templates|uploads|vendor|src\/modules|nodebb\.min\.js|stylesheet\.css|admin\.css) {
        root /path/to/nodebb/public/;
        try_files $uri $uri/ @nodebb;
    }
```

Remove `language`, restart NGINX, clear browser cache and good work!

**Comment by jarey** [comment]
Seems that the NGINX modification (or the restart) is need on community.nodebb.org since the issue was reproducing on the site (at least 21 days ago).
