### ISSUE TITLE
Categories description bug

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4916]
Please include the following information when submitting a bug report/issue:

* NodeBB version 1.1.0
* Exact steps to cause this issue
    1. On categories list default description text are inside a div while new categories seems there a "p" element added

![screenshot_1](https://cloud.githubusercontent.com/assets/10746278/17459889/b669de38-5c4d-11e6-85b6-02aa3017129d.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/10746278/17459890/b951863c-5c4d-11e6-8e63-979070dafb9f.png)

that makes difference on padding and aligment stuff

Thank you!

**Comment by barisusakli** [comment]
I think this is already fixed here https://github.com/NodeBB/NodeBB/issues/4355

Are you reproducing it on a new install or just seeing it at https://community.nodebb.org/

**Comment by exomarty** [comment]
Nodebb version 1.1.0 on new install as i say on my post

**Comment by exomarty** [comment]
Screen is from community but it happens on my install too
