### ISSUE TITLE
upload_path not end with `/uploads` cause upload crash

### ISSUE THREAD

**Issue by gogoout** [NodeBB/NodeBB#4917]
* NodeBB version : 3fbdd2b9d283df49320a1894e714319eea834104
* Exact steps to cause this issue
    1. set upload_path in `config.json` to `/someFloder/uploads/bbs`
    2. Then, upload an image, and wait for nothing happened

Seems like the problem is caused by https://github.com/NodeBB/NodeBB/blob/master/src/controllers/uploads.js#L102
`fullPath = path.join(nconf.get('base_dir'), nconf.get('upload_path'), '..', fileObj.url);`

As the `fileObj.url` is something like `/uploads/xxxx/xxxxx.xxx`, it will be fine using the default `upload_path`(`public/uploads`) but it will break if `upload_path` is changed to some path not ended with `/uploads`

**Comment by barisusakli** [comment]
Seems like `upload_path` needs to start with `/public`. And you need the regular folders created in `upload_path` or uploads won't work.
