### ISSUE TITLE
Secure /reset from "leaking" email address info

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4918]
If an email is found in the database, you get "password reset sent". If not, you get an error alert saying the email doesn't exist.

A malicious user may use this as an interface to determine which emails are registered.

Suggestions:

1. The server response should always be the same, an `.alert-info` saying "If this email address is found in our records, we will send a password reset request"
2. If you hit the /reset route over a certain threshold, you should be blocked from using the form.

**Comment by pichalite** [comment]
👍
