### ISSUE TITLE
npm v3.x breaks numerous plugins on NodeBB upgrade

### ISSUE THREAD

**Issue by tehspaceg** [NodeBB/NodeBB#4920]
- NodeBB version: v1.1.1
- git hash: 
```$ git rev-parse HEAD
ff70f36e1a1ab4b52d02bbe939af1bca41afdec5```

- This thread on the NodeBB forums explains in detail what occurred: https://community.nodebb.org/topic/9330/composer-lagging/26

* Exact steps to cause this issue
- Prereq: have an older NodeBB version. I was on v1.1.0
    1. Upgrade to Node.js latest (utilized ```sudo n latest```)
    2. Run through the upgrade process
    3. Note errors related to the composer in the NodeBB logs
* What you expected
  - The upgrade would work without any issues
  - NodeBB documentation would call out any issues with specific Node.js versions OR having a requirement for a specific version
* What happened instead
  - Tribal knowledge from @pichalite was spread to inform me that npm v3 handled dependencies differently

**Comment by tehspaceg** [comment]
I wasn't sure if this issue belonged in the composer repo or if it is better suited here. 

The base issue appears to be that npm v3 handles dependencies differently.
> npm v3 installs dependencies in the root node_modules directory. Composer is looking for the file in it's own node_modules directory.

For now, a stop gap would be to put a warning in the documentation that only Node.js up to LTS is supported. Going forward, support for the newer npm release in Node.js latest will have to be added.

**Comment by julianlam** [comment]
Seems like only the composer is broken, no?

**Comment by tehspaceg** [comment]
> Seems like only the composer is broken, no?
I didn't test all plugins, so I am not certain. I don't know if the individual modules are looking for their dependencies in their folder of if the overall application is looking for dependencies.

**Comment by julianlam** [comment]
Thanks -- at this time it seems like only composer-default is broken because it specifies inclusion of a js lib via a `node_modules/` path from within itself. Other plugins do not do this, but we'll see if I can come up with a solution in the meantime.

**Comment by julianlam** [comment]
Oh, and as for @pitaj coding with Node v4/v5 syntax... that's entirely his perogative :wink: 

Currently NodeBB _should_ support down to Node.js 0.10/0.11, though I will admit it hasn't been tested on those environments for quite some time.

**Comment by julianlam** [comment]
... oh, and we're using npm@2.1.6 on our community forum's server :laughing:

**Comment by julianlam** [comment]
@tehspaceg Please try updating to latest NodeBB commit (19b4679c0e79e43e90ada34ff57864212a69fd3a or later) and see if this issue is resolved, thanks.

**Comment by julianlam** [comment]
@pitaj

**Comment by tehspaceg** [comment]
@julianlam, I can try and give it a go tonight. I run a small forum, so everything is done in prod :D. I already moved down to npm 2.x / Node.JS 4.x

**Comment by pitaj** [comment]
I can try it out on my dev env today.

**Comment by julianlam** [comment]
Thanks guys :smile:
