### ISSUE TITLE
[NodeBB 1.1.1] In-Topic Searching: no-plugins-available

### ISSUE THREAD

**Issue by KitsuneSolar** [NodeBB/NodeBB#4923]
After enable "In-Topic Searching" & search any, i get error "no-plugins-available".

Topic:
https://community.nodebb.org/topic/9340/in-topic-searching-no-plugins-available

**NodeBB v1.1.0 & v1.1.1**

**Comment by julianlam** [comment]
I don't believe dbsearch supports in topic searching.

**Comment by KitsuneSolar** [comment]
@julianlam how do I use "In-Topic Searching" ?

**Comment by pichalite** [comment]
https://github.com/julianlam/nodebb-plugin-solr supports In-Topic searching.

**Comment by KitsuneSolar** [comment]
@pichalite thanks!
