### ISSUE TITLE
Verification e-mail doesn't arrive?

### ISSUE THREAD

**Issue by thadeuszlay** [NodeBB/NodeBB#4925]
nodeBB version: v1.x.x
git hash: ff70f36e1a1ab4b52d02bbe939af1bca41afdec5

Is it just me or do the verification e-mails (the ones you supposed to get after signing up) never arrive?

I sign up on 
https://community.nodebb.org/category/3/nodebb-development

as well as on my local branch and on cloud9.

**Comment by pichalite** [comment]
Did you check your spam folder?

Do you have an emailer plugin setup or sendmail installed to use local email on your local or cloud9 setup?

**Comment by thadeuszlay** [comment]
@pichalite Yes, I checked the spam folder. Nothing from nodeBB when I registered in the community form.
https://community.nodebb.org/category/

**Comment by julianlam** [comment]
Hi @thadeuszlay, I'm tracking delivery, opens, and clicks for emails sent on August 9th (roughly 10 minutes after you initially submitted this issue):

![selection_075](https://cloud.githubusercontent.com/assets/923011/17604573/6b20820c-5fe4-11e6-8d08-3e3ed80940a5.png)

For your own installs, you'll have to ensure "require email confirmation" is enabled. Otherwise welcome emails (which are the email confirmation emails) won't send.

**Comment by thadeuszlay** [comment]
Where do I set it? In the settings, in profile edit? I clicked on confirm email and a notification would appear saying an email was sent.

**Comment by julianlam** [comment]
![selection_076](https://cloud.githubusercontent.com/assets/923011/17604910/df7abcd4-5fe5-11e6-94d0-95ddb0912ec3.png)

**Comment by thadeuszlay** [comment]
That looks like the admin page. I only have access to it when I'm the owner of the nodeBB instance.

But I'm talking about https://community.nodebb.org/

I click on the notification and got the message "Confirmation e-mail sent". Then I'd look up on my e-mail account but couldn't find any nodebb e-mails.

**Comment by julianlam** [comment]
Our mail service reports that there was an email sent, delivered, and read by you, was this not from the community forum?

**Comment by thadeuszlay** [comment]
No it wasn't.

I signed up to:
1) https://community.nodebb.org/ and
2) https://nodebb.org/

I assume both are different instances of nodeBB. I didn't receive so far
any e-mails from #1 and I checked every folder, including the spam. I
thought I made a mistake and therefore also signed up for #2.
