### ISSUE TITLE
CSS aren't applied?

### ISSUE THREAD

**Issue by thadeuszlay** [NodeBB/NodeBB#4926]
nodeBB version: v1.x.x
git hash: ff70f36e1a1ab4b52d02bbe939af1bca41afdec5

I wanted to add some CSS to my nodeBB. But it seems the changes aren't applied to my site. I added the CSS in admin-> Appearance-> Custom HTML & CSS-> Custom CSS tab. I tried to add "!important" because I thought it would be ovewritten (I know it says that the CSS is added after all the other CSS). I also restarted nodeBB. 

This is the CSS:

```
body {
    background-color: red !important;
    
}
div.navbar.navbar-inverse.navbar-fixed-top.header {
    height: 10px !important;
}
```

**Comment by pichalite** [comment]
@thadeuszlay Did you turn this toggle on and hit save on the admin-> Appearance-> Custom HTML & CSS-> Custom CSS tab?

![image](https://cloud.githubusercontent.com/assets/10014774/17536810/92f5ebda-5e4c-11e6-8037-4fac711a9f7c.png)

**Comment by thadeuszlay** [comment]
@pichalite .... now I did. And it works. Thanks. m_._m

**Comment by pichalite** [comment]
I would suggest using the community for these questions. https://community.nodebb.org/
