### ISSUE TITLE
/register/complete route is skipped after reloading NodeBB (terms of use set in ACP)

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4929]
Please include the following information when submitting a bug report/issue:

NodeBB v1.1.2

Restarting NodeBB doesn't have the issue.

**Comment by julianlam** [comment]
Skipped? :ship it:

**Comment by pichalite** [comment]
User is not asked to accept "Terms of Use".

**Comment by julianlam** [comment]
Fixed:tm:
