### ISSUE TITLE
Migration error from 1.1.0 to 1.1.2

### ISSUE THREAD

**Issue by Toolito** [NodeBB/NodeBB#4932]
I have an error when I try to upgrade v1.1.0 to v1.1.2
I am using benlubar/nodebb docker package, which takes the last version of NodeBB.

![](https://i.imgur.com/UzcsKzp.png)

To upgrade NodeBB I've done these steps: 
- Removes NodeBB totally
- Reinstall NodeBB with the new version
- Relinked config.json
- Relinked redis data folder

Do you think it is an error in my database, or in the migration script code ?

Thank you!

**Comment by barisusakli** [comment]
You seem to be on master, it is fixed now you can git pull and try again.
