### ISSUE TITLE
[[error:theme-not-found]] since upgrading to 1.1.2

### ISSUE THREAD

**Issue by sgshawnblanchard** [NodeBB/NodeBB#4937]
Nodebb v1.1.2

since upgrading to version 1.12,  when running `./nodebb start` I receive the below error: 

> NodeBB v1.1.2 Copyright (C) 2013-2014 NodeBB Inc.
> This program comes with ABSOLUTELY NO WARRANTY.
> This is free software, and you are welcome to redistribute it under certain conditions.
> For the full license, please visit: http://www.gnu.org/copyleft/gpl.html
> 
> Clustering enabled: Spinning up 1 process(es).
> 
> 12/8 12:06 [10750] - info: Time: Fri Aug 12 2016 12:06:12 GMT-0500 (CDT)
> 12/8 12:06 [10750] - info: Initializing NodeBB v1.1.2
> 12/8 12:06 [10750] - error:  Error: [[error:theme-not-found]]
>     at site-forum/src/meta/themes.js:142:21
>     at site-forum/node_modules/async/dist/async.js:3679:13
>     at site-forum/node_modules/async/dist/async.js:486:20
>     at iterateeCallback (site-forum/node_modules/async/dist/async.js:867:28)
>     at site-forum/node_modules/async/dist/async.js:847:20
>     at site-forum/node_modules/async/dist/async.js:3676:17
>     at site-forum/node_modules/async/dist/async.js:339:31
>     at site-forum/src/database/redis/hash.js:31:4
>     at site-forum/src/database/redis/hash.js:37:4
>     at Multi.callback (site-forum/src/database/redis/hash.js:66:4)
>     at multi_callback (site-forum/node_modules/redis/lib/multi.js:89:14)
>     at Command.callback (site-forum/node_modules/redis/lib/multi.js:116:9)
>     at normal_reply (site-forum/node_modules/redis/index.js:714:21)
>     at RedisClient.return_reply (site-forum/node_modules/redis/index.js:816:9)
>     at JavascriptRedisParser.Parser.returnReply (site-forum/node_modules/redis/index.js:188:18)
>     at JavascriptRedisParser.execute (site-forum/node_modules/redis-parser/lib/parser.js:415:12)
> [cluster] Child Process (10750) has exited (code: 0, signal: null)

I am using redis as the database and was running version 1.1.0 without issue.

The default theme I was using is nodebb-theme-material.  I did try running `./nodebb reset -t` and resetting the them back to Persona, but same error occurred on restart.

thanks

**Comment by julianlam** [comment]
Resolved on latest master.
