### ISSUE TITLE
Template account info permissions

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4940]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2

Not sure about this page  https://community.nodebb.org/user/exodo/info

is this supossed to be visible by every user?
should be only for global mods and admins

![ips](https://cloud.githubusercontent.com/assets/10746278/17641081/31b4f19a-6112-11e6-9ab9-fcaa4722aa6a.png)

**Comment by pichalite** [comment]
It's only visible for admins, global mods and the users themselves. Not visible for every one.

**Comment by exomarty** [comment]
I know that but why user themselves?
Can i see if someone flag my posts?
I dont see the point of that page for a normal user

**Comment by pichalite** [comment]
What's wrong in seeing which of my posts are flagged? It doesn't show who flagged it.

**Comment by exomarty** [comment]
Nothing wrong
It can be nice feature on some comunities and a problem maker on others. I would suggest make it optional and hide ban button to users

just my opinion anyways just wanted to know about this page as i cant use it because crashing my installation. Already made another issue
Thank you
