### ISSUE TITLE
Can't use saved password to re-login

### ISSUE THREAD

**Issue by Pascal666** [NodeBB/NodeBB#4943]
After sitting idle for a while, when I next try to do something I am directed to /login with the username already filled in and not editable.  When I click on the password box Chrome asks which user's password I want to use, but nothing happens when I select one.  If I logout and then visit /login it displays with the username editable and the saved password fills in fine.  I've not run into this issue with any other websites.

git hash c0a4bf91f3241be113726ddea147bc2f4d1dc681

**Comment by julianlam** [comment]
Hi @Pascal666, what password manager are you using? The situation you are describing does not reproduce on LastPass.

**Comment by pichalite** [comment]
I don't use lastpass or other password managers but if you have the browser save the password then you won't be able to have the password filled in by the browser.

**Comment by Pascal666** [comment]
@julianlam Chrome
@pichalite Yes, that is what I am seeing.  Works fine at the normal login page but not at the one that already has the name filled in but not editable.

The later page is also missing the "Alternative Logins" box.  Prefilling the username makes sense, but IMHO that really should be the only difference between the two pages.  As it is, after getting that page I have to logout, then go back to the normal login page.  The point of asking the user to re-login is in case it is no longer the same user, in which case the new user would have to do the same two additional steps.

**Comment by pichalite** [comment]
The issue seems to be related to the username field being set to readonly for re-login to ACP. readonly attribute is removed in this commit https://github.com/NodeBB/nodebb-theme-persona/commit/066c3f821e667b8016a6a745c1f299134ea2478e

You will have to wait for next NodeBB release or apply the change on your instance manually if you need it now.
