### ISSUE TITLE
Ignore buttons on topic teaser

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4946]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
Some plugins like ns-spoilers add button to posts
can you avoid topic teaser to show buttons at all like you already do with images etc

![screenshot_5](https://cloud.githubusercontent.com/assets/10746278/17685535/328fe1f6-6365-11e6-8184-c777a3ec121b.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/10746278/17685538/368f8446-6365-11e6-9310-a74e4346f691.png)

Thank you!

**Comment by barisusakli** [comment]
You can do this with custom css, 

```
.teaser .post-content .btn {
    display: none;
}
```
