### ISSUE TITLE
Searching on navbar should follow user preferences

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4952]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
* Database Mongo
* Exact steps to cause this issue
    1. Set user preference to search topic title only
    2. Then, I did a search with search box on navbar
* What you expected
    * Expected to follow user preferences
* What happened instead
    * It always search title and posts content

I know in /search if work ok but on navbar the expected behaviour is to follow user preferences on my opinion
I see this like a good improvement
additional admin option to set default options for search
I use solr btw

**Comment by pichalite** [comment]
> Set user preference to search topic title only

Where is this set?

**Comment by pichalite** [comment]
nvm.... found it.
