### ISSUE TITLE
Incompatibility with synchronous DFP rendering

### ISSUE THREAD

**Issue by ReyKoxha** [NodeBB/NodeBB#4953]
Whenever someone wants to make use of synchronous rendering with DFP, the page only loads the ad.
The error is definitely not on my end nor on Google's (tried to resolve it with DFP support).

Current NodeBB version: 1.1.2 (latest master)
Issue appeared on previous NodeBB versions (0.9.x) as well.

Side note:
I also noticed that scripts like BlockAdBlock stopped working as well since 0.9.4. I do not know what major changes were done back then, but it seems like there is something wrong with the DOM structure.

**Comment by julianlam** [comment]
Showing advertising via DFP is not a core functionality of NodeBB, and so it would be up to whoever implements the script to debug it. There's no plugin for DFP as far as I know, let me know if I am wrong.

... but even if I am, that would be an issue for that repository, not this one.

**Comment by ReyKoxha** [comment]
So you say monetization is not a major point in web developement?

I would suggest that this bug should be dealt with low priority, but shouldn't be ignored overall as the issue obviously only occurs with NodeBB and can be seen as "essential" to increase the usage of NodeBB for more common forums.
