### ISSUE TITLE
Drop support for old nodejs versions

### ISSUE THREAD

**Issue by lo1tuma** [NodeBB/NodeBB#4956]
NodeBB still supports nodejs `0.10` and `0.12` which are both in maintenance mode and for both versions the maintenance mode will be discontinued by the end of the year. See also the official LTS schedule for more details:

![node-lts-schedule](https://cloud.githubusercontent.com/assets/169170/17733750/69a47f26-6478-11e6-8e4c-ed244cf66506.png)

I’m not sure what the general policy for NodeBB is, until when node versions are supported. So I think it would be a good idea to clarify this.

I would suggest to drop support for node `0.10` and `0.12` now (as this is a breaking change it requires a new major release) and for node `4` in April 2017.

**Comment by julianlam** [comment]
For those joining this RFC, please add a :+1: or :-1: reaction to cast your vote. I'd recommend a ratio of at least 2:1 in favour of dropping support for v0.x, but that's just an arbitrary threshold, nothing binding.

As for my opinion, I am in favour, as there's no pressing reason to support a version of Node.js that even the Node.js foundation does not support. I have always been in favour of tracking NodeBB compatibility/requirements to the following:

* Must work on Node.js LTS version
* Most throughly tested on Ubuntu LTS version

/cc @pitaj for a consenting opinion.

**Comment by pitaj** [comment]
I agree, I think it's silly to support versions of Node which are not supported by even the NF. I think it's a good idea to just support the oldest LTS version at any given major release.

**Comment by julianlam** [comment]
As for dropping v4 support at a later date, that's less important, as I don't know of any v5/v6 specific features that we'd want to take advantage of.

No, we're not switching to arrow functions :stuck_out_tongue:

**Comment by julianlam** [comment]
Thanks for everybody's (unanimous) input! 😄

**Comment by lo1tuma** [comment]
FWIW the [`package.json`](https://github.com/NodeBB/NodeBB/blob/90ba8c6077af16d111569b2fb015fda4b9094e37/package.json#L102) still defines node version to be `>= 0.10.0` in the `engines` field.

**Comment by julianlam** [comment]
Thanks, added an additional check so that NodeBB won't run on older versions (< 4, basically)

**Comment by julianlam** [comment]
Actually, there's no real reason to actively _stop_ NodeBB from running, so I'll just throw a warning instead.
