### ISSUE TITLE
Latest Flags problem

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#4960]
There is no way the flagged post. 

ie: 

URL: x.com/post/

?

commit: 8d745ceb074e8f81834bc5008e1f3bf60d047836

**Comment by barisusakli** [comment]
Not sure what the problem here is?

Posts can be accesssed with `x.com/post/<pid_of_post>`. Admins and global moderators can see a list of flagged posts at `x.com/posts/flags`

**Comment by pikshub** [comment]
@barisusakli x.domain/user/y.user/info sayfasında sorun var. Yapılan bayraklamaya gitmek istenildiğinde yolu düzgün değil. (x.domain/post/)

Fakat dediğin yoldan yani x.com/posts/flags girildiğinde yol doğru.
