### ISSUE TITLE
Notification group sends you to last post of topic

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4963]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
* Database (mongo or redis) and it's version. Mongo
* Exact steps to cause this issue
    1. Example i have a mention on a topic
    2. Then that topic gets other replies
* What you expected
    * Click on notification send me to the mention
* What happened instead
    * it sends me to the end of topic

Thank you!

**Comment by pichalite** [comment]
already fixed on master https://github.com/NodeBB/NodeBB/issues/4469

**Comment by psychobunny** [comment]
Should be yeah, thanks @pichalite and of course @julianlam who fixed it
