### ISSUE TITLE
Failed to load resource composer

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4964]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
* Database (mongo or redis) and it's version. mongo
* Exact steps to cause this issue
    1. sometimes getting this error safari mobile on unknown circunstances and composer wont open

only solution is to reload page, i can stil navigate tho

https://i.imgur.com/amtP1sy.png

https://community.nodebb.org/topic/9404/tracking-composer-not-opening/6

Thank you!

**Comment by barisusakli** [comment]
The url for the composer.js in [this](https://i.imgur.com/amtP1sy.png) picture is weird. It tries to load from

https://forum.com/topic/1/title/composer.js which is 404

**Comment by exomarty** [comment]
yes, that is weird, i think it can be because a plugin
i was testing on my dev environment and searched for composer,js 
found this

![screenshot_1](https://cloud.githubusercontent.com/assets/10746278/17976925/d9216b8e-6aef-11e6-9940-928be83c6372.png)

**Comment by julianlam** [comment]
Well, do you get this error if you disable ns-spoiler?

**Comment by exomarty** [comment]
testing it now, not easy to get the error but i happens twice a day maybe

**Comment by exomarty** [comment]
still no error on my side but disabling spoiler on production server didnt stop from getting this error logs

![screenshot_4](https://cloud.githubusercontent.com/assets/10746278/17981786/629a7d50-6b05-11e6-9519-2d57b946d9f9.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/10746278/17981788/649d0e42-6b05-11e6-9190-f6d094b377c0.png)

**Comment by barisusakli** [comment]
I'm not sure why it happens but I've seen that error when the composer r.js files are required on page load instead of when the composer is opened. Sent a PR to the plugin https://github.com/NicolasSiver/nodebb-plugin-ns-spoiler/pull/4/files. Let us know if you get the error again after disabling the plugin or updating the plugin.

**Comment by exomarty** [comment]
really thank you for the effort @barisusakli 
i just cloned your repo to test it out
anyways i wrote today, i had spoiler already disabled but this night some users came with the error too
so maybe other plugins use the same technique

i see this on my production server 

![screenshot_7](https://cloud.githubusercontent.com/assets/10746278/17990106/1fb80c9a-6b33-11e6-8ba8-8060f7b5222d.png)

**Comment by exomarty** [comment]
https://github.com/julianlam/nodebb-plugin-canned-responses/blob/master/static/lib/main.js#L11

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-canned-responses/pull/6 @julianlam
