### ISSUE TITLE
delay image loading setting causes empty image urls

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#4976]
Enable Delay Image Loading in user settings

Go to the below topic

https://community.nodebb.org/topic/9416/plugins-texts-not-translated-on-cold-refresh

Slowly scroll down until all the images load. Except the first image all the other ones have `about:blank` in the anchor tag

![image](https://cloud.githubusercontent.com/assets/2583394/17973458/318294f6-6aeb-11e6-8261-04ecb908ec90.png)

**Comment by julianlam** [comment]
Bug confirmed :sweat:
