### ISSUE TITLE
[RFC] native electron client

### ISSUE THREAD

**Issue by Radiergummi** [NodeBB/NodeBB#4980]
I'm currently using [Electron](https://github.com/electron/electron) to build a desktop client for an Express app which just transforms API JSON responses into views.  
Now I was thinking it would be great to have a boilerplate, customizable NodeBB client built with Electron. It could be customized to fit the board style, use real OS notifications, open chats in real modal windows, integrate better file browsing and upload and so on. I bet gaming board developers would also be pleased to have native Steam integration etc.

Would anyone be interested in building such a client together?

**Comment by barisusakli** [comment]
Hello,

This is probably better asked in our community forum at https://community.nodebb.org, we try to keep the issues here specific to nodebb core bugs & features.

**Comment by akhoury** [comment]
+1 @Radiergummi good idea, but yea, take it to the community site

**Comment by Radiergummi** [comment]
@akhoury I have: https://community.nodebb.org/topic/9448/native-electron-client :wink:
