### ISSUE TITLE
Add config option for custom session name

### ISSUE THREAD

**Issue by Radiergummi** [NodeBB/NodeBB#4989]
* NodeBB version: Any

Due to security reasons, I'd like to customize the cookie name NodeBB sends to clients. The current `express.sid` is hard-coded in several places in core. Would it be possible to use something like `<domain.tld>.sid` as default, or allow changing the name in the advanced configuration?

**Comment by barisusakli** [comment]
You can place it in config.json as `"sessionKey":"myforum.com.sid"` if it's not set `express.sid` will be used.

**Comment by Radiergummi** [comment]
You da real MVP, @barisusakli :ok_hand:
