### ISSUE TITLE
admin/extend/widgets doesn't work

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#4996]
Uncaught TypeError: $(...).draggable is not a function

**Comment by julianlam** [comment]
Does your PR fix this?

**Comment by pichalite** [comment]
No, there are more issues on that page. Not just the .draggable thing.

**Comment by pichalite** [comment]
Updated the PR to remove $(...).draggable is not a function error on the admin/extend/widgets page. The page is not working as expected though.
