### ISSUE TITLE
Smoothness error logs

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5001]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
* Database mongo
I have many of this daily

![screenshot_1](https://cloud.githubusercontent.com/assets/10746278/18137049/361159c4-6fa7-11e6-8525-ec82f27050e3.png)

Thank you!

**Comment by barisusakli** [comment]
Please post your nodebb git hash. This is most likely related to https://github.com/NodeBB/NodeBB/commit/0afa55517f358542ef148c453af67fdf308e7e00

**Comment by exomarty** [comment]
git rev-parse HEAD
c0a4bf91f3241be113726ddea147bc2f4d1dc681

**Comment by julianlam** [comment]
Are they still happening on the latest `master`?

**Comment by exomarty** [comment]
i dont know :/

**Comment by julianlam** [comment]
Clear the logs and see after 24 hours?

**Comment by exomarty** [comment]
i dont have any master install, only testing stable versions, no time for both
errors been cleared several times and they keep coming but not much, only 10 each one  by day

**Comment by julianlam** [comment]
Thanks... if this does still occur after upgrading to latest, please ping us to reopen :)
