### ISSUE TITLE
local upload url on windows is wrong

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5006]
https://community.nodebb.org/topic/9510/image-upload-locally-on-windows

**Comment by hediet** [comment]
This issue is still not fixed: https://github.com/NodeBB/NodeBB/blob/master/src/controllers/uploads.js#L125
Changing that line to `fileObj.url = dirname + "/" + basename + '-resized' + extname;` should do it.

**Comment by barisusakli** [comment]
@hediet can you open a separate issue for it?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5511
