### ISSUE TITLE
Improvements on two words+ search

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5007]
First of all i use solr
I think it would be nice to have a way to get exacts results while searching several words
my example would be simple, searching just topic titles

Lets say i want to search -metal gear solid-

I want results from that topic not from "metal music", "top gear" or anything else

with current way, i will get all that results but sorted by date, reply, category, etc

example, iget first two results nice cause they are newer topics

![screenshot_13](https://cloud.githubusercontent.com/assets/10746278/18211003/a107036a-713b-11e6-9598-2d38a9112a10.png)

i know there is an option to use "" to search exact words , in this case it could be nice
using "metal gear solid" would do the trick
but wont work with some other searches

example.

"best users" search wont show a topic like

< best nodebb users >
< between all users yariplus is the best >

and doing the search without "" will show anything like it was shown before

my opinion, would be nice to add option to sort by best match or just get exact results while usign several words people expect result from word 1 + word 2

thank you, sorry long post :dancer:

**Comment by julianlam** [comment]
Actually, this may have been addressed already. Before, we would conduct the search via `term || term || term`, and re-sort the results by timestamp. Now, the default is to not sort the results at all, and depend on dbsearch or solr to rank the results accordingly, which they do already.

So latest master should have this reflected already.

**Comment by exomarty** [comment]
waiting then for 1.2.0 or so :)
