### ISSUE TITLE
Outgoing links are not working

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB/NodeBB#5011]
* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory) b72a928900f96f71b302b01e35bce62bc626d669
* Database mongodb
* Exact steps to cause this issue
    1. Outgoing warning page shows incorrectly.
* What you expected
    * the normal links
* What happened instead
![image](https://cloud.githubusercontent.com/assets/2796406/18228567/28a0c10c-7287-11e6-98c5-c10e19343aab.png)

    * the /outgoing route

**Comment by barisusakli** [comment]
Please provide more info. What is the bug and how do we reproduce it?

**Comment by jiangcaiyang** [comment]
It is not the "/outgoing" links but the links which I am going to visit.

**Comment by julianlam** [comment]
@barisusakli closed the issue, so it is likely fixed. Let us know if it is still reproducible on latest `master`.

**Comment by stevefermi** [comment]
I think the problem is still reproducible.
here's an example page http://www.inog.site/outgoing?url=http%3A%2F%2Fwww.pgyer.com%2Finog

**Comment by barisusakli** [comment]
https://github.com/pichalite/nodebb-theme-material/pull/53

**Comment by stevefermi** [comment]
@barisusakli It works! it's the theme's fault.
