### ISSUE TITLE
Awarding Users Reputation via Rewards Rules Doesn't Trigger Other Rewards Rules

### ISSUE THREAD

**Issue by deiden26** [NodeBB/NodeBB#5016]
NodeBB Version: 1.1.2
Git Hash: c0a4bf91f3241be113726ddea147bc2f4d1dc681
DB: Mongo

1. Create a rule that awards points (e.g. If User's Point Count Is > 0 Then Award Reputation Amount of reputation 1)
2. Create a rule that is triggered based on reputation (e.g. If User's Reputation Is >5 Add to Group Test Group 1)
3. Trigger rule created in step 1 until rule created in step to should trigger
4. Experience nothing happening
5. Up vote the user until the rule created in step 2 should trigger
5. Experience rule 2 triggering

**Comment by pichalite** [comment]
@deiden26 this issue belongs in the rewards plugin repo https://github.com/NodeBB/nodebb-rewards-essentials

**Comment by deiden26** [comment]
Thanks. Didn't realize rewards weren't core
