### ISSUE TITLE
Delay iframe load

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5023]
Suggestion
Delay iframely load with option like delay option for images. Very useful on mobile
As many of us use plugins to see embed services like iframely can en up with long loading times on some topics

**Comment by pitaj** [comment]
Isn't this an issue specific to the iframely plugin? Take your issue there.

In fact, there's already an issue for lazy loading: NodeBB/nodebb-plugin-iframely#12

**Comment by exomarty** [comment]
I dont use iframely. Thete is a bunch of plugins to embed services on nodebb.

**Comment by pitaj** [comment]
It should still be left to that individual plugin.

**Comment by exomarty** [comment]
That issue is 9 months ago likely wont happen. 
Others embeds are smaller plugins and there are many for a single service or abandoned. 
I think it would be a nice adition to have it on the core as an optional user preference or on a single plugin for that feature. 
Also i like the way it works with images adding a delay is different from lazy load.

**Comment by pitaj** [comment]
The problem is that each plugin might do embeds differently, some with
iframes, some with direct embeds. This might be possible but the solution
would be very hacky.

**Comment by exomarty** [comment]
What is direct embed?
Probably can handle the main services with iframe,video and audio tags

**Comment by julianlam** [comment]
@pitaj is correct, we want to have core limit its heavy-handedness in terms of what plugins can do. Even if we *wanted* to do something to throttle the load of iframes, it would be (as @pitaj says) a hacky effort, because it would be something done *after* the iframe already loads.

**Comment by julianlam** [comment]
It is most definitely a per-plugin issue.
