### ISSUE TITLE
Enhancement: when the (last undeleted|only) post in a topic is deleted, delete the topic

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#5025]
When we get spambots, our users report the spam and our moderators delete it using the flags page. That works great for topics where the spambot has become the butt of a joke in the short time its post was up because deleting the spambot's post doesn't delete the topic where the discussion happened. However, when there hasn't been a discussion, we are left with a topic with no posts. Automatically deleting the topic in this case is definitely what the user wants the forum to do in this case.

**Comment by julianlam** [comment]
I remember calling for this long ago... even back in 2014. I do not recall now the exact reason we did not do so.

@barisusakli, do you remember? It certainly makes sense for me...
