### ISSUE TITLE
menu bar not working on mobile view

### ISSUE THREAD

**Issue by spicewiesel** [NodeBB/NodeBB#5026]
Hi there.

One of the most admired features of NodeBB was the great mobile page, my users loved it. Since an update to v1.x.x it no longer works correctely. The menu button is not respondand and so no user can navigate on the system. I unfortunately cannot tell which upgrade broke it, but we are on v1.1.2 now.

thanks in advance!
Til

* NodeBB v1.1.2 - c0a4bf91f3241be113726ddea147bc2f4d1dc681
* MongoDB 2.6.12
* Exact steps to cause this issue
    1. Open your NodeBB on mobile browser (android/iphone)
    2. Try to click the menu button to navigate
* What you expected
    * Menu bar should slide/open
* What happened instead
    * nothing

Thank you!

**Comment by psychobunny** [comment]
What's your theme version?

**Comment by spicewiesel** [comment]
nodebb-theme-persona
Installed 4.1.19 | Latest 4.1.19

**Comment by psychobunny** [comment]
Is your forum live, can we have a look?

**Comment by spicewiesel** [comment]
yes, of course. It's https://community.berlinreds.de

thanks for the help!

**Comment by pitaj** [comment]
@spicewiesel Your site is having issues with WebSockets at the moment. I'd suggest fixing that before anything else.

**Comment by pitaj** [comment]
Your theme Javascript doesn't seem to be included in your minified JS file.

**Comment by barisusakli** [comment]
Please continue this discussion at https://community.nodebb.org
