### ISSUE TITLE
Can't zoom on mobile

### ISSUE THREAD

**Issue by whjms** [NodeBB/NodeBB#5027]
Please include the following information when submitting a bug report/issue:

As a mobile (Android/lightning browser) user I would like to be able to zoom so that I can read some posts (people on the forum I browse like to play with `<small>` tags) and zoom in on image previews without having to load the full image.

Attempting to zoom the page with a pinch gesture does not affect the page zoom.

I understand that this is probably an intentional design choice, but I don't really understand the reasoning behind it -- in my opinion, being able to zoom is one aspect of mobile web applications that native apps are missing.

**Comment by psychobunny** [comment]
I was apprehensive at first, but then I tested it out and it actually seems quite okay. So why not...

**Comment by julianlam** [comment]
Can we get this in a branch (or on try) so iOS and WP users can test?
