### ISSUE TITLE
Startup command for selecting a theme 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5047]
Ex. `./nodebb start -t = "nodebb-theme-bananas"`

Okay, why did "vanilla" autocorrect to bananas on my phone. Leaving as is. :trollface:

**Comment by julianlam** [comment]
`./nodebb reset -t nodebb-theme-whatever`?

**Comment by psychobunny** [comment]
But something that doesn't touch the DB. I think it might be better as a config option instead actually

**Comment by psychobunny** [comment]
Reset command is good enough -- I can't even remember who was it that wanted this option in the config, @cnvo ? In any case, reopen if it's ever really needed
