### ISSUE TITLE
Documentation missing for redis setup.

### ISSUE THREAD

**Issue by worp1900** [NodeBB/NodeBB#5049]
There is no documentation for setting up nodebb with redis in the documentation link from the README (https://docs.nodebb.org/) (might be unique for Ubuntu, haven't checked the others):

https://docs.nodebb.org/en/latest/installing/os/ubuntu.html - uses mongodb as a default, mentions

> If you want to use Redis or another database instead of MongoDB please look at the Configuring Databases section.

https://docs.nodebb.org/en/latest/configuring/databases.html - mentions redis being the default and only providing documentation about mongodb.

Please adjust.

**Comment by worp1900** [comment]
@barisusakli This issue still exists.
https://nodebb.readthedocs.io/en/latest/configuring/databases.html lists redis as default and links to the setup guides.
https://nodebb.readthedocs.io/en/latest/installing/os/ubuntu.html The setup guides use mongo.

**Comment by barisusakli** [comment]
Not sure why I closd this

**Comment by barisusakli** [comment]
I think the new home for documentation is at https://docs.nodebb.org/ and https://docs.nodebb.org/configuring/databases/

**Comment by psychobunny** [comment]
Looks like it was re-added here: https://github.com/NodeBB/docs/commit/751b56e297df9ef28dfc687b677b66d17200627a

https://docs.nodebb.org/configuring/databases/redis/
