### ISSUE TITLE
admin/manage/users/search XSS

### ISSUE THREAD

**Issue by andrewaeva** [NodeBB/NodeBB#5060]
Git hash fdd85140587799a442edb9f3ca1b8ecaf4ea0bb9
* Database (mongo or redis) and it's version.
    * redis 3.2.0
* Exact steps to cause this issue
 * Change user email to `2@ya.ru\"><svg/onload=alert(1)> ` `http://192.168.189.133:4567/user/:userslug/edit/email`
 * Admin go to `http://192.168.189.133:4567/admin/manage/users/search`
 * Search users by username or email 
 * Javascript executed
* What happened instead
    * Javascript executed
![ss 2016-09-27 at 12 58 19](https://cloud.githubusercontent.com/assets/3368345/18868778/1c1b0f54-84b2-11e6-8fac-1dec8aae1ab4.png)

Thank you!

**Comment by julianlam** [comment]
Hello there. While this ought to be fixed, we don't consider admin panel to be end-user facing, so it is less urgent.

However, thank you for reporting!

**Comment by andrewaeva** [comment]
But we can easy attack admins.
It's more critical than users :)

**Comment by julianlam** [comment]
If somebody manages to access the ACP via a user account, an XSS is the least of your problems there :wink:

**Comment by andrewaeva** [comment]
You probably misunderstood me.
Any user can change the email and this will lead to XSS in admin panel.
Therefore, any user can attack the admin.

**Comment by julianlam** [comment]
Ah, I see, this is more important now. In the future please report these issues to security@nodebb.org :+1:

**Comment by andrewaeva** [comment]
Okey

**Comment by julianlam** [comment]
@andrewaeva Once again thank you for your work rooting out these bugs 😄  It is much appreciated.

Also, nice avatar!
