### ISSUE TITLE
1.2.0 - all chats can be viewed by admins/mods on the profile page, but not in the pop-out

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#5073]
These URLs are accessible to any administrator or global moderator on community.nodebb.org:

https://community.nodebb.org/user/ben-lubar/chats
https://community.nodebb.org/user/ben-lubar/chats/1882

However, opening the chat in the pop-out mode gives a not-allowed error.

**Comment by theportablegeek** [comment]
Has this been integrated as a plugin?
