### ISSUE TITLE
admins and global mods can access chat history

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5075]

**Comment by alff0x1f** [comment]
Hmm, I update my forum to v.1.2.0 and not realize how I can access to chat history (other users I assume). This feature implemented or not?

**Comment by pichalite** [comment]
You will have to go to the chats route directly. There is no link that takes you there. Navigating to the route `/user/[username]/chats` will let you access them.

That said this have been taken out in NodeBB v1.2.1 so that this can be implemented using plugins if required.

**Comment by alff0x1f** [comment]
@pichalite I try open and get 404. Open with admin account. My version v1.2.1:
Failed to load resource: the server responded with a status of 404 (Not Found) 
http://my-site.ru/user/alff0x1f/chats

Or it will work only with with plugin, not in default forum?

**Comment by pichalite** [comment]
@alff0x1f as I said, it's been removed out of core in v1.2.1. It won't work on the default forum. you will need to build a plugin to get it working.

**Comment by alff0x1f** [comment]
Ah, "taken out", sorry, now I understand before.
