### ISSUE TITLE
Crash when forking from large topic

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/NodeBB#5077]
Please include the following information when submitting a bug report/issue:

* NodeBB version 1.2.0 a93ee979267285182a2352e4a6b58345a52a277d
* Mongo 3.2.10
* Exact steps to cause this issue
    1. We have a topic with ~55K posts and over 600 users have bookmarks (last read markers)
    2. Fork the topic and select at least one post.
* What you expected
    * New topic created, old posts were moved out of the original topic.
* What happened instead
    * NodeBB crashes with out of memory error (currently running in a 4GB vm)

I tracked this down to `src/topics.js:Topics.updateTopicBookmarks`. In particular, using `posts.getPostIndices` inside `async.map`. A more scalable approach would be something like `async.eachLimit` and moving the stuff that uses the result of `async.map` into an `async.waterfall` within the `async.eachLimit`.

https://what.thedailywtf.com/topic/21071/fork-you-nodebb/

**Comment by barisusakli** [comment]
Let me know if above commit fixes the issue.

**Comment by boomzillawtf** [comment]
Yes, that seems to have done it!
