### ISSUE TITLE
favicon problem

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#5080]
favicon does not change. The default seems

https://github.com/NodeBB/NodeBB/commit/aca0a893e7ab52003e016eec382ea3f0d3610ba7

**Comment by pikshub** [comment]
@julianlam yep. timuu(.)com

**Comment by pikshub** [comment]
@julianlam up up up sweetie

**Comment by julianlam** [comment]
When you go back to the general settings, is the favicon set?

When you uploaded one, did you hit save afterwards?

**Comment by pikshub** [comment]
1. I set there.
2. I confirm once or twice. The problem continues.

**Comment by gnucoder** [comment]
Hello,

I've upgraded to 1.3.0 and still have the favicon issue :(
