### ISSUE TITLE
Request: New chat button

### ISSUE THREAD

**Issue by yamikuronue** [NodeBB/NodeBB#5084]
Okay, so I'm really pissed off right now, so bear with me: chat UX is awful.

I'm a moderator on a forum. I'm also a frequent user of that forum. I want to just start a chat with someone. I don't want to be forced to only have had one chat with them ever. I don't want the message I got when I was playing a forum game of Mafia to suddanly be the place to have a serious discussion about their behavior in the community. I don't want that group chat that one time we were drunk last year with two other people to suddanly become the place I warn them about excessive flagging for spurious purposes. I don't want to have to search through hundreds of chats to find the one that has their name on it. I just want a button that opens a new chat, add the users I want, and we're chatting! That's all!

**Comment by julianlam** [comment]
> so bear with me: chat UX is awful.

Agreed, the chat UX does need a fair bit of work. A `+ New Chat` button would do well, and all it really has to do is open a new chat and allow you to add a user.

@barisusakli how difficult is this? I know there's a limitation in that you can't send chat messages (or maybe even open a chat modal) without two users in a chat, perhaps a modal with a user search, and it forces a new chat?

**Comment by barisusakli** [comment]
This might be quite easy, the current chat button on user profile opens an existing chat if there is one, or creates a new chat https://github.com/NodeBB/NodeBB/blob/master/public/src/client/account/header.js#L35-L46 we just need to create a new chat button that calls `app.newChat()`
