### ISSUE TITLE
Mute notifications

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/NodeBB#5086]
The current ignore thread function prevents it from showing up in unread but users still get notifications from the thread.

We have a lot of users who would like for a way to mute notifications from a thread and in some cases entire categories.

**Comment by barisusakli** [comment]
What notification are they getting? I am assuming its mention or upvote notifications?

**Comment by yamikuronue** [comment]
Mention and upvotes, yes.

**Comment by pitaj** [comment]
![image](https://cloud.githubusercontent.com/assets/803701/19126388/f6fdc314-8af7-11e6-8732-f0056d40104c.png)

So just extend "Ignore" to categories and make it ignore upvotes and mentions?

**Comment by AccaliaDeElementia** [comment]
If i might inject my two cents here?

I personally would love to be able to Mute entire categories such that any thread created in them or moved to them disappears into a black hole, never to be seen nor heard from again by me. But at the same time i often use the ignore topic feature as implemented as a temporary "i need to pay less attention to this topic for a while, but if someone wants me i want to know about it"

I think these two use cases are both valid uses and should be supported.

to that end i would propose a relabeling of existing watch statuses and adding an additional one:

* Watching
    * This is as it is today, every new post generates a notification
* Normal
    * This replaces "Not Watching" today. you'll get notifications as normal
* Not Watching
    * This replaces ignoring today, You won't see the topic in Unread, and you won't get reply notifications, but you will get like and mention notifications
* Ignoring
    * This thread just disappeared, it does not show up in unread, it does not generate any kind of notification whatsoever.

I think this will resolve the issue as described by @boomzillawtf as well as preserving the "i just need a break" use case that I use the ignore functionality for today.

Thoughts?

**Comment by halcyon1234** [comment]
Plusone to a fourth level of "Ignore" vs. "Blackhole the muffin fluffer!"

**Comment by FoxBlackcinder** [comment]
Also, if we could have the "blackhole" option prevent the thread/category from showing up in the Recent list of topics, that would be wonderful.

**Comment by psychobunny** [comment]
If I `@mentioned` somebody, I'd expect them to receive a notification. So even if you're ignoring that category (but not necessarily ignoring me), I as a user should probably know you're never going to see it. How does this work UX wise then?

**Comment by FoxBlackcinder** [comment]
Maybe the @-mention could just not become a link? How easy would that be to
implement?

**Comment by psychobunny** [comment]
Unfortunately that doesn't necessarily convey to the "mentioner" that the other was not mentioned.

**Comment by FoxBlackcinder** [comment]
I guess it probably would be easier to just give a toaster saying "hey your
@-mention won't work" when they go to click submit

**Comment by boomzillawtf** [comment]
Is it that big a deal why someone ignores it? Sometimes people have a zillion notifications and just clear them all and go about their business.

**Comment by psychobunny** [comment]
@boomzillawtf I'm mentioning you now and I would hope you get my response to this unless you've ignored this category :trollface: - if I actually did have something important to add to this, I'd like to know if you've gotten it or not

In @FoxBlackcinder's scenario, I'd get an alert telling me you've ignored this category. I suppose that works, but that sounds annoying to me because now I'm going to have to PM you perhaps?

I understand the reason for muting though. I'm just trying to wrap my head around the UX for the mentioner.

**Comment by FoxBlackcinder** [comment]
I mean if you send someone a PM about a topic or category they've ignored
that defeats the purpose of ignoring it and is kind of a dick move.

**Comment by boomzillawtf** [comment]
Yeah, @psychobunny, I get that, but you can't make me! :-P

If the person has ignored a topic and muted notifications, then they really don't care about anything that's added to it. It's not important to them and they don't want to see it. I think the person's desire to "forget" about a topic is more important than another person's desire to send a message.

If it's really important, like an apology or something, then a PM is appropriate and possibly worth "violating" their desire to ignore the topic at hand.

**Comment by FoxBlackcinder** [comment]
Also do we have an ignore user functionality? I haven't found any.

**Comment by yamikuronue** [comment]
I got a whole bunch of emails about this thread -- if I don't care anymore, I can send them right to my junkmail without necessarily seeing the messages, whether you said my name or not.

If someone calls my cellphone, I can send it right to /dev/null without answering. They can leave a message and I can delete it. Many phones will let me make my phone not ring for certain numbers, even. 

This isn't any different: someone wants my attention, but I don't have to listen.

**Comment by AccaliaDeElementia** [comment]
I'll second @yamikuronue here, the total mute functionality is an escape mechanism for a user to completely reject a topic they do not wish to interact with at all.

For example, Accalia does not wish to receive any notification for any activity in a topic discussing the latest presidential debate. if Andrew wishes to summon her to that thread, he is free to do so, but as Accalia does not wish to be notified of that thread no notification should be sent. If it's that important for Andrew to contact Accalia a chat will suffice, or failing that opening a new topic that has not been blacklisted by Accalia.

I do agree that there should be multiple levels of suppressing notifications, with the current "ignore" functionality being an important level. But i don't agree that the user generating the notification should have any indication that their notification was automatically rejected. after all the system automatically discarding the notification is no different than the user simply never acting on the notification from the point of view of the person generating the notification.

---

I also think that an Ignore User functionality is a discussion for a different issue. @FoxBlackcinder If you wish to propose an Ignore User feature I believe it would be best to open a new Github issue so we can keep this discussion on topic.

**Comment by julianlam** [comment]
Hi all,

I think introducing an enhanced "ignore" level for topics is overkill only because the great majority (and I'm speaking with no data whatsoever, just how I feel about it) of users wouldn't use such a functionality. In that sense, I am against adding additional maintained code that would be used by a very small subset of users.

That said, it would be better for a plugin to introduce this workflow if necessary... which brings me to my second point, that mentions [is a plugin](https://github.com/julianlam/nodebb-plugin-mentions), meaning even if we introduced this setting, it wouldn't do anything because the appropriate changes would have to be added to mentions too. Then we have a situation where an "ignore" level is present, but the code governing that is in a different repo from mentions, and if mentions are disabled, then the ignore level is completely useless.

That said, one *could* forego adding an additional level, and just have mentions check if a user is ignoring a topic. If so, no mention, otherwise, mention.

**Comment by halcyon1234** [comment]
So where would the logic fit into the chain?

I @mention someone
A notification is raised
A notification is delivered to a user
The UI shows that notification in a toaster
The notification is now in the /notification list

Would it make the most sense to:

1. When the notification is raised by @mentioning, see where the notification originated from.  If it is from a "blackholed" place, cancel the notification?
2. When the notification is received, check where the notification came from.  If it is from a "blackholed" place, make it "read", delete it, and don't send it to the toaster?

**Comment by julianlam** [comment]
I'd rather prevent a notification to be sent out altogether. Currently topic reply notifications check the topic status. Mentions does not. Mentions can. 😄

**Comment by halcyon1234** [comment]
So in the mentions plugin, the function 
`function sendNotificationToUids(postData, uids, nidType, notificationText)`

In there, in the waterfall, I would put in another filter similar to
`Privileges.topics.filterUids('read', postData.tid, uids, next);`

Except it would be (pseudocode)
`FilterOutUIDsThatAreIgnoringThisTopicOrCategory(postData, uids, next)`
?

**Comment by julianlam** [comment]
@halcyon1234 Similar logic to what [is employed here](https://github.com/NodeBB/NodeBB/blob/master/src/user/notifications.js#L202-L244)

Does this mean you're volunteering to submit a PR? 🚎

**Comment by halcyon1234** [comment]
If I'm on the right path, then yeah I may try my hand at a small change.  Seems like a good entry point.

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-mentions/commit/40571115c069fa5e2192804f3c8ce15b0fbd02af
