### ISSUE TITLE
./nodebb setup fails for Fedora 23

### ISSUE THREAD

**Issue by MrHanachoo** [NodeBB/NodeBB#5087]
Version: v1.2.0
Git hash: 3c5d7f36b2284270a3de23b61f7f6f2abe49a3e2
DB: redis v3.0.6
OS: Fedora 23
* Steps to reproduce:
    1. I follow this installation doc https://github.com/NodeBB/nodebb-english/blob/master/installing/os/centos.rst
    2. I run _./nodebb setup_ 
* What is expected:
    * setup completed successfully.
* What happened instead
    * I get the following output:

> /10 22:50 [23394] - warn: Your version of Node.js is too outdated for NodeBB. Please update your version of Node.js.
> 5/10 22:50 [23394] - warn: Recommended >=4, 0.10.42 provided
> 
> 5/10 22:50 [23394] - info: NodeBB Setup Triggered via Command Line
> 
> Welcome to NodeBB!
> 
> This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
> Press enter to accept the default setting (shown in brackets).
> 
> 5/10 22:50 [23394] - info: Now configuring redis database:
> Configuration Saved OK
> Populating database with default configs, if not already set...
> 
> /media/mydrive/dev/js/projects/NodeBB/public/src/modules/translator.js:38
> 	var assign = Object.assign || jQuery.extend;
> 	                              ^
> ReferenceError: jQuery is not defined
>     at /media/mydrive/dev/js/projects/NodeBB/public/src/modules/translator.js:38:32
>     at /media/mydrive/dev/js/projects/NodeBB/public/src/modules/translator.js:31:21
>     at assign (/media/mydrive/dev/js/projects/NodeBB/public/src/modules/translator.js:32:5)
>     at Object.<anonymous> (/media/mydrive/dev/js/projects/NodeBB/public/src/modules/translator.js:36:3)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)

This is the config.json file:
`{
    "url": "http://localhost:4567",
    "secret": "secret_key",
    "database": "redis",
    "port": 4567,
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "password": "passwd",
        "database": "0"
    }
}`

**Comment by pitaj** [comment]
It specifically says what's wrong:

> warn: Your version of Node.js is too outdated for NodeBB. Please update your version of Node.js

Install Node v4. You can use [n](https://github.com/mklement0/n-install) or [nvm](https://github.com/creationix/nvm)

**Comment by julianlam** [comment]
Thanks @pitaj
