### ISSUE TITLE
Composer select category not translated

### ISSUE THREAD

**Issue by alejandrocobo** [NodeBB/NodeBB#5090]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory): Ver. 1.2.0
* Database (mongo or redis) and it's version: redis
* Exact steps to cause this issue
    composer.select-category string not translated
* What you expected
   A translation
* What happened instead
    Shows the string  composer.select-category intead the message "select category"

![combinacion2](https://cloud.githubusercontent.com/assets/1640709/19171231/fe43d404-8c1b-11e6-97a5-48a9869dea04.png)

None translation module.json files have composer.select-category string except for en_GB

Thank you!

**Comment by pichalite** [comment]
This was fixed yesterday. Upgrade to NodeBB v1.2.1.
