### ISSUE TITLE
Request: Allow moderators to respond to flags via Chat

### ISSUE THREAD

**Issue by AccaliaDeElementia** [NodeBB/NodeBB#5094]
There are times when a user may flag a post that requires moderators to reply back to the user directly, either to open a conversation with the user regarding the issue raised in the flag, or to deal with the issue raised directly and privately.

I envision this change being a button on the "deal with this flag" screen, which currently gives the option of deleting the flagged post or dismissing the flag. This new button would:
- Create a new Chat owned by the responding moderator or admin
- Add all other moderators or admins to the chat
- Add the reporting user to the chat
- Copy the contents of the flag message as a chat message from the flagging user.

This would allow the moderation team to discuss the matter with the flagging user if necessary, while preventing the creation of unecessary chat rooms when the flag is "a spammer got through" and the response is "delete the post, ten wander off to ban the spammer"

This should be relatively unobtrusive, and give the forum moderation team a built in way to interact with users who issue flags in a more transparent manner (but only if they want to)

Thoughts? Comments? Suggestions?

**Comment by julianlam** [comment]
Not immediately opposed. What if multiple users flag a post, would the chat then be a group chat with all of those reporters?

**Comment by AccaliaDeElementia** [comment]
Hmm..... interesting question.

That depends rather on the current UX for multiple flags, but my gut says that the safest action is to have separate chats for each reporter and if the moderators decide that merging the chats would be a good idea they can add the other reporters manually to the first chat they generate.

Flags can be rather sensitive, so i would err on the side of maintaining maximum privacy for the reporting user in the case that a chat is generated from their flag.

**Comment by pauljherring** [comment]
> Add the reporting user to the chat

... or the reported user...

**Comment by AccaliaDeElementia** [comment]
@pauljherring Hmm.... Possibly, but in that case it should probably not include the text of the flag when adding the reported user.

Possibly it should be two buttons then? one for talking to the reporting user via chat as described above, and one that opens an otherwise blank chat with the mods and the reported user?

**Comment by julianlam** [comment]
I was thinking of implementing this today, but as there are already plans to re-write the entire flagging system (#5085), we'll lump these into that issue.

**Comment by julianlam** [comment]
Closed in favour of centralised tracking in #5232
