### ISSUE TITLE
ACP Default digest setting not read by emailer on digest execution

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5104]
It looks like a change was made awhile ago to allow the ACP to set a default value for the digest. However, even if set, a user wouldn't be sent a digest unless explicitly set in their user settings as the digest execution logic would read only from the list of explicit recipients.

**Comment by barisusakli** [comment]
The ACP setting only works for users created after the setting is changed.

**Comment by julianlam** [comment]
... well that just invalidated an hour's worth of work.
