### ISSUE TITLE
Creating new topics is not working properly in Safari

### ISSUE THREAD

**Issue by faif** [NodeBB/NodeBB#5105]
Reproduced using Safari Version 10.0 on macOS Sierra. Haven't tested in on mobile Safari.
On Firefox and Chrome on macOS the behaviour is the expected.

Happens both in the master and in the 1.x.x branch 
The back-end does not matter. Tried both mongo (3.2.8) and redis (3.2.4)

* Exact steps to cause this issue
    1. Click Announcements/New Topic
    2. Fill the required info and Click Submit
* What you expected
    * The topic to be created under Announcements
* What happened instead
    * I got "Error Category does not exist"

* Exact steps to cause this issue
    1. Click Announcements/New Topic
    2. Fill the required info, choose the General Discussion category and click submit
* What you expected
    * The topic to be created under General Discussion
* What happened instead
    * The topic is created under Announcements

And so forth for the rest categories... Seems to be an off-by-one error

**Comment by pejuaxel** [comment]
I confirm I am having the same issue on Safari 10.0 and macOS Sierra. Topics are created in the wrong category, even though the intended category is correctly selected in the composer.

**Comment by barisusakli** [comment]
Can you try on latest master with composer-default 4.2.9

**Comment by faif** [comment]
Tested using master with composer-default 4.2.9. The problem is fixed 👍
