### ISSUE TITLE
Show original post/topic etc dates older than month

### ISSUE THREAD

**Issue by alff0x1f** [NodeBB/NodeBB#5108]
Show original date instead relative date. Relative date is nice, but only for new post. My forum older than 9 years and if you open old topic, posts look like this: "3 year ago","3 year ago","3 year ago".... very uninformative. I offer show relative date only for dates younger 1 month (like github)

Library timeago have settings, cutoff. If nonzero, it work only for values less than it. The easiest way just set it, but but problem by default dates in tpl (persona theme) look like this:

```
<span class="timeago" title="{posts.timestampISO}"></span>
```

If timeago not work, dates will be invisible for users at all. Yes, we can change theme, but It may be sensitive for users who not update themes or use own custom themes). 

From documentation timeago:

> cutoff : Return the original date if time distance is older than cutoff (miliseconds).
> 
> ```
> // Display original dates older than 28 days
> jQuery.timeago.settings.cutoff = 1000*60*60*24*28;
> ```

**Comment by barisusakli** [comment]
Makes sense to me. We will have to update the themes though, or figure out a way to do it client side.

**Comment by alff0x1f** [comment]
Maybe possible solution. A look at timeago and found this:
```
    if (!isNaN(data.datetime)) {
      if ( $s.cutoff === 0 || Math.abs(distance(data.datetime)) < $s.cutoff) {
        $(this).text(inWords(data.datetime));
      } else {
        if ($(this).attr('title').length > 0) {
            $(this).text($(this).attr('title'));
        }
      }
    }
```
https://github.com/rmm5t/jquery-timeago/blob/master/jquery.timeago.js#L194-L202

But it word different at my nodebb, so I look at source function shorter:
```
    if (!isNaN(data.datetime)) {
      if ( $s.cutoff == 0 || Math.abs(distance(data.datetime)) < $s.cutoff) {
        $(this).text(inWords(data.datetime));
      }
    }
```
https://github.com/NodeBB/NodeBB/blob/72c75bd7813b2bb41dc175ce6f7fe9fa58eed006/public/vendor/jquery/timeago/jquery.timeago.js#L188-L192

**Comment by barisusakli** [comment]
Looks like our timeago lib needs updating then.

**Comment by julianlam** [comment]
Did @pichalite update the lib? Not sure how far he got with this.

**Comment by pichalite** [comment]
I did update the lib to latest but completing this request requires code changes in addition to updating the lib.

**Comment by julianlam** [comment]
Oops, referenced wrong issue with commit 75ff60e. Fixed in that hash.
