### ISSUE TITLE
New topics going to the wrong categories on Safari

### ISSUE THREAD

**Issue by joerick** [NodeBB/NodeBB#5119]
* NodeBB version and git hash 
    * a9d69c4779b25c80f00cece417bf7fcb4d10d18b
* Database (mongo or redis) and it's version.
    * MongoDB shell version: 2.4.9
* Exact steps to cause this issue
    1. Go to my site in Safari, http://forum.tingbot.com 
    2. Go to the 'Hodge-podge' category
    3. Press 'New topic'
    4. Enter a topic title, some text, make sure the category is still 'Hodge-podge' and press 'Submit'
* What you expected
    * I expected the post to end up in 'Hodge-podge'
* What happened instead
    * The post was submitted into 'Support'

Google Chrome and Firefox don't have this problem in my testing. This only happens in Safari.

**Comment by barisusakli** [comment]
See https://github.com/NodeBB/NodeBB/issues/5105 sounds like the same issue.

**Comment by joerick** [comment]
Fantastic! For the record, I had to change the package.json line:

    "nodebb-plugin-composer-default": "4.2.7",

to

    "nodebb-plugin-composer-default": "4.2.9",

and then do a `npm install`. Guessing this will be bumped in the next release though.

Cheers!

**Comment by widora** [comment]
+1

**Comment by widora** [comment]
It really work! thx
