### ISSUE TITLE
sharing post to facebook doesn't show image

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5121]
> The provided 'og:image' properties are not yet available because new images are processed asynchronously. To ensure shares of new URLs include an image, specify the dimensions using 'og:image:width' and 'og:image:height' tags. Learn More

**Comment by barisusakli** [comment]
https://community.nodebb.org/topic/9710/topic-thumbnail-doesn-t-show-on-facebook-share

**Comment by julianlam** [comment]
Well that's a bit of a cop-out by Facebook, isn't it.

**Comment by barisusakli** [comment]
I figured this was happening because the user was sharing a post that was in a category that is only visible to logged in users. If you share a regular post in a public category it works.
