### ISSUE TITLE
Seeing old/cached version of posts after editing

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#5123]
I have noticed I cannot see edits from other users (and myself on another device) always. I have to edit their post to see the changes they have made. Other users on the forum have reported the problem too. I couldn't reproduce it when testing with Firefox and Chrome on desktop, but I could when using my phone and desktop.

Forum: https://retropie.org.uk/forum/

* NodeBB version and git hash - 1.2.1 dfc8ceef9e4fe737f489eb8517c7477300c37d3f
* Database (mongo or redis) and it's version. mongodb 3.2.10
* Proxied from nginx

* Exact steps to cause this issue
    1. Create a post on Android (Chrome 53.0.2785.124)
    2. View the post on my desktop machine (Firefox 49), then navigate away.
    3. Edit the post on Android
    4. View the post again on desktop machine, see old version. Reloading on browser still shows old version. Editing will show the updated content.

**Comment by barisusakli** [comment]
Are you running multiple nodebb processes? Do you have redis setup as well?

**Comment by joolswills** [comment]
5 nodebb processes + single redis

**Comment by barisusakli** [comment]
So you have the redis config block in your config.json? When a post is edited we publish a message tru redis so all caches are cleared. https://github.com/NodeBB/NodeBB/blob/master/src/posts/edit.js#L18-L20

I will see if I can repro.

**Comment by joolswills** [comment]
I don't have any redis configuration in the config.json.

just 

```
{
    "url": "https://retropie.org.uk/forum",
    "bind_address": "127.0.0.1",
    "secret": "XYZ",
    "database": "mongo",
    "port": [4567, 4568, 4569, 4570, 4571],
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "SOMETHING",
        "database": "SOMETHING",
        "password": "SOMETHING"
        "poolSize": "5"
    }
}
```

there is some data in redis though from nodebb as i can see from redis-cli

**Comment by barisusakli** [comment]
You should add a redis block to your config so it is used to pass messages between nodebb process, it should look like 

```
{
    "url": "https://retropie.org.uk/forum",
    "bind_address": "127.0.0.1",
    "secret": "XYZ",
    "database": "mongo",
    "port": [4567, 4568, 4569, 4570, 4571],
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "SOMETHING",
        "database": "SOMETHING",
        "password": "SOMETHING"
        "poolSize": "5"
    },
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "database": "SOMETHING",
     }
}
```

**Comment by joolswills** [comment]
Will do.

Why is redis being used without it then ?

**Comment by barisusakli** [comment]
Not sure, it shouldn't be used if there is no redis block, could the data be from an older install? You can check if redis is doing anything with the MONITOR command.
```
redis-cli
select <db>
MONITOR
```

**Comment by joolswills** [comment]
Yeah - I don't think it is being used. I think I was testing nodebb with redis before I went with mongodb.

Is redis required then even when using mongodb for this to work correctly ? I don't remember reading that when I set it up.

**Comment by joolswills** [comment]
and adding the redis configuration block, won't stop data being saved in mongodb ? This is a production forum, so I'm keen not to break anything :-)

**Comment by barisusakli** [comment]
I just added some info into the docs https://github.com/NodeBB/nodebb-english/commit/81fb71ce518c6c8dd9dc1e8bdaf906a8080b4489

With "database": "mongo" it will still use mongodb but will use redis for pubsub and as a session store, so users will have to relogin.

**Comment by pichalite** [comment]
As long as `"database": "mongo"` this remains, adding redis block shouldn't change anything about mongo being the main db.

Looks like redis is required for running multiple nodebb processes. You don't remember reading about it coz its not mentioned in the docs. That needs to be added to the docs.

**Comment by joolswills** [comment]
Thanks. Will add the redis configuration and do some testing.

**Comment by pichalite** [comment]
Don't forget to restart nodebb after adding the redis block :smile: .

**Comment by joolswills** [comment]
Thanks. testing.

The sessions were stored in mongodb before ? Will they be removed or can I remove them manually? - I see redis being used now for sessions etc.

**Comment by barisusakli** [comment]
There should be a `sessions` collection in your mongodb you can remove that.

**Comment by joolswills** [comment]
Thanks. I can confirm this is resolved with the redis configuration.
