### ISSUE TITLE
Code (backtick) wrapped items (triple or single)

### ISSUE THREAD

**Issue by mastacontrola** [NodeBB/NodeBB#5126]
* Version: v1.2.1 -- dfc8ceef9e4fe737f489eb8517c7477300c37d3f
* Mongo version 3.0.12

* Exact steps to cause this issue
    1. Create a code segment by using backtick text backtick or triple backtick enter text enter triple backtick.
    1. * For items like shell scripts with if statements (e.g.)
    1. ** `if [[ -z $abc ]]; then`
    1. ** ```if [[ -z $abc ]]; then```
* What you expected
Raw output of what was typed between.

* What happened instead
Spaces between [[ -z and c ]] are being stripped out.

**Comment by mastacontrola** [comment]
Going to upload some screen shots.

**Comment by mastacontrola** [comment]
What it looks like:
![image](https://cloud.githubusercontent.com/assets/7305838/19443924/755cd804-945c-11e6-9290-87afca4354f9.png)

What it looks like when in editing mode: 
![image](https://cloud.githubusercontent.com/assets/7305838/19443979/9d26c052-945c-11e6-9732-013e5c70c287.png)

**Comment by pichalite** [comment]
Did you try this on the community site? Are you able to reproduce it there?

**Comment by julianlam** [comment]
No changes to markdown-it. Sounds like a translator issue. /cc @pitaj

**Comment by pitaj** [comment]
Not reproducing on try: 

https://community.nodebb.org/topic/9722/test-5126

This is fixed on master.

**Comment by julianlam** [comment]
Thanks @pitaj
