### ISSUE TITLE
Add port settings and url to default config.json

### ISSUE THREAD

**Issue by alff0x1f** [NodeBB/NodeBB#5134]
When user install new forum, master propose this value:
```
...
URL used to access this NodeBB (http://localhost:4567)
...
```

And default config.json looks like this:
```
{
    "url": "http://localhost:4567",
    "secret": "00000000-0000-0000-0000-000000000000",
    ...
```
I think master must ask url with default value http://example.com and also port with value 4567  
And result config.json must look like this: (because nodebb anyway listen 0.0.0.0:4567):
```
{
    "url": "http://example.com",
    "port": "4567",
    "secret": "00000000-0000-0000-0000-000000000000",
    ...
```
Second config much clear and obvious for users, IMHO.

Ps My story: When i was newbie, first I change it to http://server_ip:4567. Later install nginx and change it to http://127.0.0.1:4567 (because think its listen address). Later notice smiles and something else doesn't work (path to smiles was http://127.0.0.1:4567) and I change it to http://mysite.com:4567, smile still doesn't work, I change it to http://mysite.com. 
And after that think that nodebb support only one instanse per machine(because config not contain port and second instance doesn't start (because port busy by first instance). Only later I found settings "port"

**Comment by julianlam** [comment]
While the desired end result of many installations is typically `http://example.org`, that is, access *without* the port number, we prioritise ease of setup over eventual configuration.

So in the case of a new installation, going through the default setup values should net you an installation that is accessible, and does so, at `http://localhost:4567`.

Going without port in `url` requires that a reverse proxy be used (not necessary, and increases the barrier to entry for a new install), and the instance is unusable without one set up (websockets won't work, etc, as the url is portless, but nothing is listening on port 80).

Thanks for your contribution, but at this time I don't think we'll change the way the setup script is handled.
