### ISSUE TITLE
Admin panel layout breaks when touch scrolling on Chrome

### ISSUE THREAD

**Issue by sjennison** [NodeBB/NodeBB#5138]
NodeBB v1.21, commit a9d69c4779b25c80f00cece417bf7fcb4d10d18b

When using touch-to-scroll on Chrome Windows in the admin panel, the page layout will break if you swipe upwards.

![image](https://cloud.githubusercontent.com/assets/5776850/19563833/76127d80-96af-11e6-96c1-ba8df2bb63e4.png)

DB: Mongo (shouldn't be relevant...)

Expected: The page shouldn't break :)

**Comment by pitaj** [comment]
Looks like the slideout menu is activating, which removes the `position: fixed from` the header menu. Should be able to fix this by adding a screensize check when the slideout menu is setup.

**Comment by julianlam** [comment]
Slideout menu is configured here: https://github.com/NodeBB/NodeBB/blob/master/public/src/admin/admin.js#L163-L168

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/5425
