### ISSUE TITLE
Chat notification when people leave 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5148]
Ex. "Xyz has left this chat"

**Comment by BartVB** [comment]
Complicating factor is that you don't really *leave* a chat in NodeBB. You can close the chat window  but that doesn't really mean you've left. Messages that are send after closing the window still arrive.

**Comment by julianlam** [comment]
Closing the modal only hides the chat, correct... though I believe x-ing out of the chat via the `/chats` page from the chats list actually removes you from the chat.

**Comment by BartVB** [comment]
It might remove you from the chat technically but it won't stop the other party from sending messages because their chat window won't be closed. I would just get a new 'there is a chat message' notification if I had closed my chat window.

I won't really like the `Bla has left` addition. Then closing a window becomes a conscious thing. I.e. is this an 'appropriate' time to close this chat/conversation.

Maybe a more versatile solution would be read indication?

**Comment by pauljherring** [comment]
There are two different sorts of X's on the chat window, clicking the cog will give you the second set:

**Comment by BartVB** [comment]
There is a big difference between 1:1 and group chats in this context.

You can't remove your 'chat partner' in a 1:1 and you can't remove yourself.

In a groupchat it would indeed be useful to see that a user was removed or has removed themself from the chat.

**Comment by pauljherring** [comment]
>**You can't remove your 'chat partner'** in a 1:1 and you can't remove yourself.

Possibly it's because I'm an admin or mod, but

![image](https://user-images.githubusercontent.com/3939886/29139801-12693940-7d40-11e7-97df-c494c71ee60d.png)

**Comment by BartVB** [comment]
Try clicking the X :) You'll get a message that you can't remove the last participant in a chat.

**Comment by pauljherring** [comment]
> You'll get a message that you can't remove the last participant in a chat.

Which probably needs another issue ticket - it shouldn't be there if it doesn't do anything... :laughing:

**Comment by pichalite** [comment]
@BartVB There is an option for every user to leave any chat room. You won't find it in the chat modal window. It's on the list you see in the route `/[userslug]/chats`.

Using a screenshot from @pauljherring's other issue to show what I mean. In the screenshot, there is an 'x' in the top right corner of every chat room. That is what lets you leave a room.

![image](https://user-images.githubusercontent.com/10014774/29183953-5a3f87e6-7db9-11e7-9320-e362763f93e8.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/7771
