### ISSUE TITLE
Union sorted sets by range

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#5153]
https://github.com/NodeBB/NodeBB/blob/master/src/database/redis/sorted.js#L119-L133

I feel like these could use the same `sortedSetRange` as the other `getSortedSet[Rev]Range[WithScores]` methods.

@barisusakli

**Comment by barisusakli** [comment]
The params order is different for the byscore methods I think.

**Comment by pitaj** [comment]
@barisusakli why close? It should still be an option even if that particular helper function isn't used IMO
