### ISSUE TITLE
Allow SSO plugins to redirect users back to the page they were on

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5156]
In cases where a guest navigates to a page that requires authentication, they should be redirected to said page after authentication has succeeded.

This is done for local login, but SSO plugins were left out, and always redirected the user back to `/`

**Comment by pichalite** [comment]
@julianlam this breaks login for ACP.

**Comment by pichalite** [comment]
`TypeError: Cannot read property 'replace' of undefined
    at Controllers.login (/home/ubuntu/workspace/src/controllers/index.js:107:43)`
