### ISSUE TITLE
Restart required is always marked true for plugin settings save

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#5162]
https://github.com/NodeBB/NodeBB/blob/master/src/meta/settings.js#L33

Always marked true even when restart is not required.

**Comment by pitaj** [comment]
Maybe a good solution to this would be to allow plugins to pass in a `quiet` parameter. Maybe overload `set` to receive to accept an options object with keys `hash`, `values`, and `quiet`?

**Comment by julianlam** [comment]
The whole restart required system needs re-thinking. It's not been reliable because it's hard to tell what settings changed need restarts, and which don't.

Open to suggestions :\

**Comment by pitaj** [comment]
Sounds like it would require a settings API that allows certain fields to be marked as "restart required", maybe like this:

```
Settings.init('nodebb-plugin-markdown', {
  allowHTML: {
    type: Boolean,
    default: false,
    restartRequired: true,
  },
});
```

**Comment by julianlam** [comment]
Unfortunately I don't think plugin authors will follow that... it's too complicated and authors will do the bare minimum to get a plugin working. It's just human nature :smile:

**Comment by pitaj** [comment]
Depending on whether you think `restartRequired` should default to `true` or `false`, you could have a shorthand for that like this:

```js
Settings.init('nodebb-plugin-markdown', {
  allowHTML: false,
});
```

Which would expand to this, assuming `restartRequired` defaults to `true`:

```js
Settings.init('nodebb-plugin-markdown', {
  allowHTML: {
    type: Boolean,
    default: false,
    restartRequired: true,
  },
});
```

**Comment by julianlam** [comment]
I've decided to go with the original suggestion by @pitaj to implement a `quiet` Boolean. If optionally passed in, reloadRequired will not be set to true.
