### ISSUE TITLE
Login is very slow

### ISSUE THREAD

**Issue by Tach-Yon** [NodeBB/NodeBB#5163]
I was trying to implement an external login API, but after trying a few things I have noticed the login is extremely slow, and not only from the API, even logging in through the main website. I tried without the proxy and it still is very slow upon logging, taking around 5-8 seconds to log in at times.

**Comment by julianlam** [comment]
Digital Ocean 16.04? Try 16.10 or replace bcryptjs with bcrypt. :smile:

**Comment by julianlam** [comment]
Known issue by the digitalocean team by the way.

**Comment by Tach-Yon** [comment]
@julianlam Wasn't using Digital Ocean by the way, it was simply the bcryptjs. Solved now, thank you very much.
