### ISSUE TITLE
Feature Request: CDN Usage should be configurable

### ISSUE THREAD

**Issue by ip6li** [NodeBB/NodeBB#5167]
NodeBB v1.2.1
MongoDB 3.2.10

NodeBB includes some files from external CDN (e.g. gstatic.com) which includes tons of tracking scripts. That may be illegal in EU due to privacy laws.

It should be configurable from where yet CDN based date are requested.

**Comment by pauljherring** [comment]
I believe the usual "We use cookies" boilerplate would suffice to mitigate any of the EU privacy stuff. 

Whether something like https://cookieconsent.insites.com/documentation/compliance/ should be included is probably more pertinent.

**Comment by julianlam** [comment]
@pauljherring 👏 

What a site. Implementing.
