### ISSUE TITLE
cannot edit nodebb source

### ISSUE THREAD

**Issue by mtrabelsi** [NodeBB/NodeBB#5173]
I'm facing a problem with the source code, whenever I  made a change on it, and I restart the server, the code is reset and back to original ( ignore my changes with some script ), so at this point there are two possibilities :

1.  It's a bug, Or
2. It's intended to make the code change not possible. So, in that case is this really GNU V3 license ?

Anyone from the community can clarify things to us? ( we don't want to abuse :) )

Thank you!

**Comment by pichalite** [comment]
@mtrabelsi are you changing files in public/templates folder? If yes, then you are modifying temporary files that will be overwritten on restart. Modify the source files instead.

**Comment by mtrabelsi** [comment]
@pichalite : Yes, but I still don't understand.. Where can we edit template files ( *.tpl ) if public/templates folder is overwritten, there is no other views files.

thanks for the quick response!

**Comment by pichalite** [comment]
Themes should be under node_modules/[theme-name]/templates. So, for the default theme persona, that would be node_modules/nodebb-theme-persona/templates.

**Comment by julianlam** [comment]
Correct, thanks @pichalite. Individual plugins or themes can modify and provide template files, so that is where the editable source lies.
