### ISSUE TITLE
[Feature request] Filtering digest categories per group

### ISSUE THREAD

**Issue by Wardormeur** [NodeBB/NodeBB#5177]
Hi there!
First of all, thanks for your awesome work :+1: 
We have local group for an international forum and we'd like to filter the digest based on the group you belong to. 
Specs : 
* Anybody should see the categories
* Anybody shouldn't not receive notification for the categories
* Anybody belonging to a group associated to this category should receive digest for the linked  category
If not part of the core, the other option could be to cover this by a plugin that auto watch a section linked to a group ?

**Comment by julianlam** [comment]
Hello there, unfortunately this doesn't look like something we'd put in core, as it is far too specific to apply to all installations.

I'd recommend you reach out to our developer community at https://community.nodebb.org and see if somebody there is willing to spec out this work for you 😄
