### ISSUE TITLE
 DeprecationWarning

### ISSUE THREAD

**Issue by evoixmr** [NodeBB/NodeBB#5184]
DeprecationWarning: Using Buffer without new will soon stop working. Use new Buffer(), or preferably Buffer.from(), Buffer.allocUnsafe() or Buffer.alloc() instead.

DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Version 1.2.1
Mongo
Error show on terminal after nodebb start and also on error log

**Comment by pitaj** [comment]
What version of Node.js? Also, can you tell if this is originating within NodeBB, or is it from one of the sub-modules?

**Comment by evoixmr** [comment]
nodejs v7.0.0
I aslo get this error as soon as I start nodebb -> (node:21516) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by psychobunny** [comment]
Any chance for a full stack trace? We don't officially support nodejs v7 though, I suggest downgrading for now

**Comment by evoixmr** [comment]
I did not really see any issue. I still downgraded to v6.9.1. No more error message.

**Comment by evoixmr** [comment]
I can not opdate the to firefox -50 because it need libicui18n.so.58 which nodejs v6 does not support.

Nodebb 1.3.0 fail with this error on nodejsv7: (node:5018) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

Please fix, I need to upgrade the following files: nodejs icu hunspell firefox

**Comment by pitaj** [comment]
It is just a warning, so you should be fine. It's deprecated, not removed.

**Comment by evoixmr** [comment]
Nodebb 1.3.0 does not start with nodejs v7/

**Comment by pitaj** [comment]
Well it's not the deprecation that's causing that. Please post a full log.

**Comment by evoixmr** [comment]
at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/home/evoixmr/nodebb/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/jhade/bb/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
[cluster] Child Process (13912) has exited (code: 0, signal: null)

**Comment by evoixmr** [comment]
I upgraded everything and it worked, this was the only warning on the log:
(node:1457) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

This is the warning on terminal after nodebb start:
(node:5018) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

I

**Comment by gogoout** [comment]
same problem +1
I'm currently using 7.0.4 to run nodebb. 
Using command `./nodebb start` will log this warning in the terminal and I have to manually ctrl+c cancel it.
Everything other seems work fine except for upstart script.

Here is my script:
```
description "nodebb-bbs"
start on startup
stop on runlevel [016]
respawn
setuid nodebb
script
        cd /www/path-to-bbs
        ./nodebb start
end script
```

Using `sudo service start nodebb` can't start nodebb correctly and  an empty `pidfile` is created in the nodebb folder.
Thus nodebb will not able to start by the command `./nodebb start`. I have to manually remove the pidfile.

Downgrade to node v6.9.4 , everything act normal.

I not sure if the DeprecationWarning is causing this.  In my case, the warning is caused by the fllowing code in loader.js. 
```
fs.writeFile(__dirname + '/pidfile', process.pid);
```

Anyone can help if there is any workaround in the upstart script?
