### ISSUE TITLE
Block user from sending chats

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#5187]
In addition to "only users I follow can send me chats", it would be useful to be able to block specific users from adding you to a chat.

ref: https://github.com/apapadimoulis/what-bugs/issues/158
/cc @yamikuronue

**Comment by psychobunny** [comment]
What would the messaging be like for the person sending the chat?

"Sorry, this person blocked you, please complain on the forum" :D

**Comment by BenLubar** [comment]
I assume it would use `[[error:chat-restricted]]` like the other reasons for not being able to add someone to the chat.

**Comment by yamikuronue** [comment]
Another option: just don't send it to the recipient, but leave the UI the same as if you weren't blocked. That way for the sender it's identical to the recipient choosing not to respond, which is the only solution currently open to the recipient, but without flashing the (potentially hostile or obscene) message on the recipient's screen.

**Comment by julianlam** [comment]
That kind of restriction falls over when you have to also consider group chats, since we'd have to add in message filters to remove messages from blocked individuals... and showing the chat restricted message would just serve as a shortcut to determining who has blocked you.

That said, right now this is handled by the ignore-users plugin, is it not? I am not opposed to putting this in core.

**Comment by BenLubar** [comment]
> ignore-users plugin

There's one of those now?

**Comment by barisusakli** [comment]
If you enable `only users I follow can send me chats` other users shouldn't be able to add you to rooms unless they are an admin or global mod.
https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/modules.js#L173-L175

**Comment by pauljherring** [comment]
> If you enable only users I follow can send me chats other users shouldn't be able to add you to rooms unless they are an admin or global mod.

That's the whitelist mentioned in the OP. I believe a blacklist option was being requested.

**Comment by yamikuronue** [comment]
As paul says. I don't want to have to follow 1,000 users so I can avoid messages from 1 or 2. And then I'd have to keep on top of following every new user who might want to get ahold of me in the future. Ick.

**Comment by julianlam** [comment]
We'll be adding this in a future version of NodeBB, thanks.

As for group chats, I imagine the block wouldn't apply, because then you'd lose context. If you don't want to hear from someone you blocked, in a group chat, then you should just leave the group chat.

**Comment by BenLubar** [comment]
@julianlam I'd imagine the block would work by preventing the blocked user from adding the user that blocked them to a chat.

**Comment by exomarty** [comment]
plugin ignore users already do that

**Comment by julianlam** [comment]
As ignore-users supports this, I'm hesitant to add it to core. Let me know if the plugin does not work as intended and we can definitely reopen.
