### ISSUE TITLE
Location jumps with mobile composer

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/NodeBB#5189]
Please include the following information when submitting a bug report/issue:

*  v1.2.1 1c4effbdf8398a67999cd00a580d596374d196fc
* Mongo 3.2.10
* Exact steps to cause this issue
    1. Use a mobile device or shrink browser window to xs size
    2. Go in the middle of a long topic, where neither the bottom nor the top are loaded.
    3. Compose and submit a reply to a post.
* What you expected
    * Composer is dismissed and the page is at the same point in the topic as when I clicked "Reply."
* What happened instead
    * The page is centered somewhere above the post I replied to.

**Comment by julianlam** [comment]
Hm, this is odd. The more I think about it the more I would rather not have "scroll to new reply" be standard. If you disable that option, does this bug no longer occur?

![image](https://cloud.githubusercontent.com/assets/923011/20604988/23c60a44-b237-11e6-93d5-e86c3c5872c1.png)

**Comment by boomzillawtf** [comment]
No, I have had "scroll to new reply" turned off since it became a thing.

**Comment by pauljherring** [comment]
> No, I have had "scroll to new reply" turned off since it became a thing.

Confirming, both the behaviour, and 'scroll to reply' status.

**Comment by Tsaukpaetra** [comment]
FYI still happening.

**Comment by albertdev** [comment]
I have "After posting a reply, show the new post" as unticked / OFF but I also use Pagination, 20 posts per page.

When I dismiss the composer or press "Reply" I always get sent to the top of the last-seen page.

**Comment by julianlam** [comment]
So I can reproduce, so that's good at least. Odd how it's happening on mobile.

We've never noticed it before, as we all have "scroll to new reply" enabled (not that you guys need to hear more excuses or anything...)

**Comment by julianlam** [comment]
As @albertdev and izzion(@ tdwtf) also state, it happens on composer discard as well, so my gut feeling is opening the composer mucks the scrollTop about.

**Comment by julianlam** [comment]
Right, so as it turns out, when the composer opens, we hide the topic content (something to do with scrolling, and back button, and safari, and such), and re-expose it on composer discard or post.

Doing so set scrollTop to 0, which triggered infinite load of the previous page's topics. So the logic was working fine, it was sending you to the same `scrollTop` position you were at before, except now there just happens to be another 20 or so posts prepended to the top of the page, hence the jellypotato 🥔
