### ISSUE TITLE
Global Moderators have permissions over admins

### ISSUE THREAD

**Issue by Phattie** [NodeBB/NodeBB#5202]
Not much to this one, merely that members of the Global Moderators group are able to modify admin profiles, as well as see their IP addresses and even revoke their sessions.

Global Moderators shouldn't be able to do _anything_ to administrators, let alone log them off. The triple dot in an admins profile should only show the default options (chat, follow, topics etc...). To a Global Moderator, an admin should appear as though they are a regular user - the minimum of information showing and no option to modify anything.

Hope this gets fixed soon because I'd like to roll this out to my community but I can't while the permissions are in this state.

**Comment by julianlam** [comment]
@barisusakli This seems like a good point to make. Perhaps we should abstract out the calls to `user.isAdminOrGlobalMod` into something similar to `.canEdit`?
