### ISSUE TITLE
Auto zoom issue

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5206]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory) 1.3.0
* Database (mongo or redis) and it's version. Mongo
* Exact steps to cause this issue
    1. there is an issue on ios mobile where selecting a dropdown makes the page to zoom a bit and do strange things like not allowing to go up or down on the page or the sidebar coming in action eventually
 gladly the new smooth dropdown works ok so i can reproduce this only on pages like /search

    2. This also applies to the new chats system, after type a message it zooms in and gets crazy a bit :)
    
Some screens
Tested it on community.nodebb and on my install
![image](https://cloud.githubusercontent.com/assets/10746278/20263080/5b330b1e-aa65-11e6-9561-d67d909919c2.png)

![image](https://cloud.githubusercontent.com/assets/10746278/20263167/ba64e512-aa65-11e6-8b9e-582cd6799da2.png)

Thank you!

**Comment by exomarty** [comment]
Another screen of the zoomed layout
![image](https://cloud.githubusercontent.com/assets/10746278/20263358/a3dfc09a-aa66-11e6-9f74-4cd81a6c2824.png)


Btw it was working ok before the new chat layout

**Comment by julianlam** [comment]
Not entirely sure this is a bug. We removed the zoom restriction, so that you are free to zoom into elements, as there are cases where this behaviour is desired. iOS zooms in to form inputs to make it easier to interact with, because the font size in those elements is less than 16px (which is a completely arbitrary number that Apple uses, and only Apple).

Open to suggestions for fixing, but if it zooms in on input selection, then zoom out when you're done.

**Comment by pichalite** [comment]
I would suggest to set the font size to 16px for input elements on mobile. The page zooms to weird levels on iOS.

**Comment by exomarty** [comment]
it doesnt zoom out @julianlam 
it is near impossible to write a chat with the new layout

**Comment by julianlam** [comment]
@exomarty I mean, zoom out yourself... unless this is not possible?

**Comment by exomarty** [comment]
it is possible but not easy
and if i have to zoom out each time i send a message i wont bother using that feature

**Comment by pichalite** [comment]
Seriously @julianlam... your response is zoom out yourself? :fail:

**Comment by psychobunny** [comment]
@pichalite setting font size to 16px fixes the problem?

**Comment by pichalite** [comment]
Yes. iOS doesn't zoom if input font size is minimum of 16px.

**Comment by psychobunny** [comment]
Cool, let's not close this until we ensure all inputs are that size. This kind of belongs in the theme repo though, but keep it here for now :+1:

**Comment by exomarty** [comment]
Solved it on my custom theme with this addition on less files
.form-control { font-size: 16px; }
it could be handled by media queries too if only need it for mobiles
