### ISSUE TITLE
The entire contents can not be displayed

### ISSUE THREAD

**Issue by DQing** [NodeBB/NodeBB#5208]
## In the production of forms because too much content, resulting in information can not all show
as the follow [picture](http://139.199.154.100/wp-content/uploads/2016/11/iss.png)

and my code is:

`|姓名   |性别   |手机   |邮箱 | github帐号| 本论坛帐号|金数据帐号 | trello帐号| 简书地址 | 备注 |角色|年纪|aa|
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 李鹏 | 男 | 185910000000 | 132613527328@163.com  | freewind 1111111111 |freewind111111  |nowind_le11111e@qq.com | 111freewind | [TW李鹏11111111111| 1111111|11111111|1111111|11111111111|
|   |   |   |   |   |   |   |   |   | | | | 
|   |   |   |   |   |   |   |   |   | | | |`

**Comment by BenLubar** [comment]
Is the solution to this a horizontal scrollbar?

**Comment by barisusakli** [comment]
I think so 💡

**Comment by barisusakli** [comment]
Just gonna leave this here as well
![image](https://cloud.githubusercontent.com/assets/2583394/20647125/8c574492-b494-11e6-91ae-9efff7f03686.png)

**Comment by BenLubar** [comment]
@barisusakli that also happens with the updated composer if you have a long word in a post, like a link to a GitHub comparison page.
