### ISSUE TITLE
No Composer works

### ISSUE THREAD

**Issue by freakyy85** [NodeBB/NodeBB#5210]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
Latest Version, https://github.com/NodeBB/NodeBB.git downloaded from there today. (yesterday too) i did a pull request just also today.
* Database (mongo or redis) and it's version.
redis,   Installed: 2:2.8.17-1+deb8u5

* Exact steps to cause this issue
    1. get branch 1.x.x (and same problem with master)
    2. I started app.js using plesk node.js support
    3. I went to the URL and set up redis, my login name etc.
    4. logged in - tried to post something - not possible
* What you expected
    * i expected a composer to come up
* What happened instead
    * I get this error on both master and 1.x.x: 
config['composer-default'] is undefined
The plugin is enabled though.

Thank you!

**Comment by freakyy85** [comment]
No matter what composer plugin i install, and if i uninstall the others - none works.

**Comment by julianlam** [comment]
Hello @freakyy85 -- we can't reproduce this on our environments. We'll need a full stack trace please (frontend, since that seems to be the error?)

**Comment by freakyy85** [comment]
hi. i dont know how i can do a stacktrace? oO im new to all this node.js stuff. and i dont know javascript.

**Comment by freakyy85** [comment]
I'm using Plesk Onyx with the Node.js extension. Just enabling node.js for the vhost. I can set the environment to development but I still don't know how I can get "stacktrace".

**Comment by jarey** [comment]
If the error is produced on client side as Julian suggest, you only new to open your browser console (ctrl+shift+i) go to console tab and check if an error is showed when trying to use the composer. If that happens just click on the error and copy the stacktrace.

**Comment by freakyy85** [comment]
TypeError: config['composer-default'] is undefined
<anonym>
nodebb.min.js:12
v.event.dispatch()
nodebb.min.js:2
v.event.add/g.handle()
nodebb.min.js:2
.trigger()
nodebb.min.js:3
.trigger/<()
nodebb.min.js:3
.each()
nodebb.min.js:1
v.prototype.each()

**Comment by freakyy85** [comment]
the same thing happens with ms edge and firefox.

**Comment by freakyy85** [comment]
TypeError: config['composer-default'] is undefined
<anonym>
nodebb.min.js:12
v.event.dispatch()
nodebb.min.js:2
v.event.add/g.handle()
nodebb.min.js:2
.trigger()
nodebb.min.js:3
.trigger/<()
nodebb.min.js:3
.each()

this is when using reply.

**Comment by yariplus** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/blob/1ee1c65265ac0ce67f32c8ff4820b5b0b5bcaacc/static/lib/client.js#L37

This is the line here. However, it is correctly defined for me.

**Comment by freakyy85** [comment]
I can't help. I don't know javascript but it doesnt work for me.

**Comment by freakyy85** [comment]
the url is https://forum.nextgamers.eu

**Comment by freakyy85** [comment]
hm sadly it just wont work. but id really like to use nodebb ;(

**Comment by pichalite** [comment]
Your setup seems to have multiple issues not just composer.

First of all do you know if your host supports websockets? Websockets are required for NodeBB to work. This is not a bug. Just issues with your setup.

**Comment by freakyy85** [comment]
well it's debian 8.6 i think it supports websockets? I dont know why it shouldnt? 
what other issues does the setup have?

**Comment by pichalite** [comment]
Are you using a proxy server to route requests to NodeBB like nginx or apache? If yes, are they setup for Socket.IO support?

**Comment by freakyy85** [comment]
Well I'm using apache2.4 and plesk onyx. Plesk onyx lets you setup node.js in a vhost i dont know if it supports sockets.io. I'm asking in their forums. will post back if i know more.

**Comment by freakyy85** [comment]
The plesk support says:
When you run "NPM install" all required components should be installed. If you check node_modules directory for you nodebb, you will see

drwxr-xr-x 4 user_yrppmfmulk psacln 4096 Nov 17 12:02 websocket-driver
drwxr-xr-x 3 user_yrppmfmulk psacln 4096 Nov 17 12:02 websocket-extensions

at least.
And of course, you can install it for you nodebb manually with

-sh-4.2$ /opt/plesk/node/6/bin/npm install websocket

**Comment by freakyy85** [comment]
i now installed websocket manually but still it doesnt work still gives that error message: 
cant connec tto wss://mydomain.tld/...

**Comment by freakyy85** [comment]
in the node_modules directory there are: 
websocket/            websocket-driver/     websocket-extensions/

**Comment by pichalite** [comment]
This issue tracker is not for installation support. Close this and continue the conversation on https://community.nodebb.org

**Comment by freakyy85** [comment]
Ok thank you.
