### ISSUE TITLE
Separate build step for NodeBB

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5211]
At some point @pitaj is going to go nuts and add webpack into NodeBB, but **in the meantime**, it may be better practice to split out NodeBB's application starting step from the build/compilation step, so:

`./nodebb build` and `./nodebb start`

Rationale:
* Allows more robust handling of NodeBB for hosting setups that do not rely on `loader.js`
* Allows us to simplify `loader.js` code and remove all of the code related to passing compiled css/js data back and forth
* Increases startup speed by removing the largest blocking chunk of code from running during startup (this is technically a cop-out), thereby reducing downtime on forum restarts (this is most definitely **not** a cop-out)

Steps:
* [x] Move compilation logic to a separate file (`build.js` maybe?)
* [x] Add build step to the end of `./nodebb upgrade` and `./nodebb setup`
* [x] Change NodeBB startup so compilation does not take place
* [x] Deprecate `--from-file`
* [x] `./nodebb` executable integration
* [x] Break out `meta.css.minify` to accept targets (client and acp)
* [x] Add "rebuild assets" button to ACP dashboard next to "restart"
* [x] ~~Update documentation for this new update workflow~~ Not necessary as `./nodebb setup` and `./nodebb upgrade` autobuild. Restart button builds now as well.
* [x] Update loader.js to not pass in `--from-file`
* [x] Update loader.js and cluster logic to no longer pass js/css back and forth (@barisusakli)
* [x] Add test for build step (@barisusakli)
* [x] Fix Gruntfile.js (@psychobunny :trollface: )

**Bonus points**:
* [ ] Warn user if they need to rebuild their assets (e.g. if they activated a plugin or something) -- not quite sure how to detect this at the moment...
* [x] Consider optimising build step so that plugins and themes do not have to be completely loaded/initialised
* [x] ~~Consider optimising plugin/theme initialisation so that it no longer needs to parse js/css/tpl files~~ Not worth doing as the benefit is minimal

**Comment by pitaj** [comment]
I'd suggest not breaking existing workflows. Maybe have `./nodebb start
--prebuilt` or something which doesn't build before startup.

**Comment by julianlam** [comment]
Existing workflows won't break, end result is `./nodebb start` would end up being much faster, and setup and upgrade flows will automatically build assets for you.

We would have to add in a button to execute asset building from the ACP, though, as a restart itself won't be enough.

**Comment by pichalite** [comment]
The new button should probably be "Build & Restart" instead of just "Build Assets". Can't think of a scenario where you would build but not restart. :thinking:

**Comment by julianlam** [comment]
@pichalite That is a good point. I guess this is a re-introduction of the "reload" button 😆  Except "reload" now "restarts", and "restart" would now "build & restart" :shipit:

**Comment by julianlam** [comment]
@psychobunny When you get to doing the last item, please take a look at 9bf0f6c5cdfc320bd47ee967d19e6507438fec25

**Comment by pichalite** [comment]
🔜

**Comment by lo1tuma** [comment]
I already really like the direction of this issue 👍 . But I wonder if the rebuild assets functionality is really needed. Without this feature we could make a lot of dependencies devDependencies (e.g. `less`, `postcss`, `uglify` etc) which would result in much smaller docker images. If you would use a custom build process instead of the one nodebb ships then you could even profit from faster install times (`npm install --production` would’t install stuff like `uglify`).

Another counter-argument is that the immutable infrastructure approach is on the rise where mutating build artifacts at runtime would be a bad practice.

**Comment by julianlam** [comment]
@lo1tuma Thanks for the feedback. A lot of why we do the things we do in NodeBB is because we want to appeal to the lowest (or "lower", in any case) common denominator for admins, in order to reduce barrier to entry.

To that end it _does_ increase the amount of wheel reinvention, but the benefits are somebody new to Node.js (or even just NodeBB) can get up and running with a few simple `apt-get` and `npm i` commands and a `./nodebb setup`.

If we ended up embracing other build methodologies, we'd end up requiring users pre-configure their servers, install things like grunt, or gulp, custom-tailor a taskrunner file, etc, which make the initial setup *much more complex*, but also runs the risk of not running properly on different environments.

**Re: Immutable infrastructure** -- definitely appealing, and is part of why this issue exists. `./nodebb build` is a separate "task" from the actual NodeBB app, so you can more easily bundle it into existing build tasks... etc.

At any rate, it's a heck of lot easier to do it now than it was when it was bundled into `node app.js` 😄

**Comment by lo1tuma** [comment]
@julianlam Thanks for the response. So it seems like my requirements are probably a bit different than those from the rest of the nodebb users. What I need is actually more like a framework (`nodebb-framework` maybe? 😄 ) than a ready-made application. Basically nodebb without build tasks, cluster-management and pre-installed default plugins/themes.

Also I wouldn’t recommend installing the build tools on the same server where nodebb is running. In many cases build tools have not been implemented with security in mind, so it increases to attack surface on the server. I would recommend to build on a separate machine, preferable a CI/CD pipeline like jenkins.

Anyway, thats out of the scope of this issue. I already appreciate the work that has been done so far 😉 .

**Comment by julianlam** [comment]
> Also I wouldn’t recommend installing the build tools on the same server where nodebb is running. In many cases build tools have not been implemented with security in mind, so it increases to attack surface on the server.

That is a good point to consider. It is important to ensure our build tools (whether they're baked-in or built atop of NodeBB) are securely implemented.

I hope we can both agree that NodeBB would work _better_ with build tools like grunt or gulp after this refactor, than before... I see it this way:

* Before: NodeBB sidesteps build tools, tries not to affect their operation
* After: NodeBB allows build tools to better integrate with their operation

**Comment by julianlam** [comment]
> Consider optimising build step so that plugins and themes do not have to be completely loaded/initialised

While implementing this task (and the other related task), I've discovered that the actual act of loading the css/less/js file paths into memory takes about 6.7msec, which is really not worth the effort unless I already happen to be doing it.
