### ISSUE TITLE
Multi Select threads for moderation

### ISSUE THREAD

**Issue by Xseba360** [NodeBB/NodeBB#5216]
Since I switched my forums from MyBB to NodeBB I've really been lacking the feature to select multiple threads from the category view and move/lock them. This would really make the moderation easier 😄

**Comment by pichalite** [comment]
It's already available. Just not apparent. In category view click on the avatar to select a topic and use "Topic Tools" to pin/lock/move/delete multiple topics.

You can also hold Shift key to select multiple topics in a range.

**Comment by Xseba360** [comment]
Oh wow, How come I didnt notice that, Thanks. This should be more obvious haha 😃
