### ISSUE TITLE
Translations seem not correctly escaped

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#5220]
Please include the following information when submitting a bug report/issue:

**NodeBB:**
- **version** 1.3.0 
- **hash** 5e47ea5996c57087fa3421d1ce253472d83d1eaf
- **db** Redis 3.2.5

I have upgraded NodeBB from 1.0.3 to 1.3.0 from git branch 1.x.x. Upgrade seem OK but on each pages i got JS error.

 #```calledPage:13 Uncaught SyntaxError: missing ) after argument list```

I have looked the detail of this error and it appear that the French translation is not escaped.

```Javascript
var config = JSON.parse('{"relative_path":"","version":"1.3.0","siteTitle":"******","browserTitle":"******","titleLayout":"&#123;pageTitle&#125; | &#123;browserTitle&#125;","showSiteTitle":true,"minimumTitleLength":"5","maximumTitleLength":"255","minimumPostLength":"8","maximumPostLength":"32767","minimumTagsPerTopic":"0","maximumTagsPerTopic":"2","minimumTagLength":"3","maximumTagLength":"30","hasImageUploadPlugin":false,"useOutgoingLinksPage":true,"allowGuestSearching":true,"allowGuestUserSearching":true,"allowGuestHandles":false,"allowFileUploads":true,"allowTopicsThumbnail":false,"usePagination":false,"disableChat":false,"disableChatMessageEditing":false,"socketioTransports":["polling","websocket"],"websocketAddress":"","maxReconnectionAttempts":5,"reconnectionDelay":1500,"topicsPerPage":20,"postsPerPage":20,"maximumFileSize":"2048","theme:id":"nodebb-theme-lavender","theme:src":"https://maxcdn.bootstrapcdn.com/bootswatch/latest/cyborg/bootstrap.min.css","defaultLang":"fr","userLang":"fr","loggedIn":true,"cache-buster":"7e405c42-d1e3-46d0-8fe6-ba9ed2139286","requireEmailConfirmation":false,"topicPostSort":"oldest_to_newest","categoryTopicSort":"newest_to_oldest","csrf_token":"yi2h2HGU-FAULRFnU4aR7rtTdQUwBAdwBm84","searchEnabled":false,"bootswatchSkin":"default","cookies":{"enabled":false,"message":"Ce site utilise des cookies pour vous permettre d'avoir la meilleure expérience possible.","dismiss":"Compris !","link":"En savoir plus"},"openOutgoingLinksInNewTab":true,"topicSearchEnabled":false,"delayImageLoading":false,"composer-default":{},"disableMasonry":false,"markdown":{"highlight":1,"theme":"railscasts.css"}}');
```

Look at `Ce site utilise des cookies pour vous permettre d'avoir la meilleure expérience possible.`.

Due to this bug all buttons and interface interactions are broken, i can't install/manage plugins, maintenance mode or any other things.

Thank you for your help !

**Comment by julianlam** [comment]
Interesting... does this happen on `en_GB`?

**Comment by antoine-pous** [comment]
I think, i can't test now.

For me the problem is due to the conversion string to JS object in plain text.

I have fixed the bug by escaping the the quote with `\\`, but this should be managed directly by the core.

You can see the PR #5221
