### ISSUE TITLE
Skin Whitelist & Skin Based Custom CSS

### ISSUE THREAD

**Issue by phit** [NodeBB/NodeBB#5222]
Would be nice if administrators could whitelist certain bootswatch skins to be available to users. So you could focus on optimizing for example for two themes (ie one light, one dark), additionally maybe even add a option for custom CSS based on the user selected skin.

**Comment by pichalite** [comment]
@phit you can add custom CSS based on user selected skin now. NodeBB adds a specific class to the body tag based on user selected skin. If the user selects `slate` skin, body tag will have `skin-slate` class. You can add your custom CSS based on this class so it only applies for that particular skin.

**Comment by phit** [comment]
can this be reopened? this still doesn't allow me to only give people access to a specific skins only

**Comment by psychobunny** [comment]
If you really really want to hide individual skins, you can do so via CSS by hiding individual options in the select dropdown 

I wouldn't mind accepting a PR for this though,

**Comment by phit** [comment]
I ended up editing `src/controllers/accounts/settings.js` and removing all the themes I don't want my users to use, since hiding dropdown options [isn't supported](https://www.google.com/search?q=display+none+option+value) in all browsers (or buggy in Edge for example)
