### ISSUE TITLE
first page of paginated topic shows up to n+1 posts; last page shows up to n-1 posts

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#5223]
Pagination currently starts counting from the first reply, not the OP, so with 5 posts per page, the first page shows 6 posts and a new page will be created at the end when the last page is filled, not when there is a post that would fit on it.

/cc @halcyon1234

**Comment by barisusakli** [comment]
Are you saying there is an empty page at the end?

**Comment by BenLubar** [comment]
Yes. There is an empty page if the number of replies is a multiple of the number of posts per page.

**Comment by barisusakli** [comment]
Hmm, can't reproduce it here https://community.nodebb.org/topic/149 with 5 posts per page.

I end up with 3 pages with 6,5,5 posts on each like you said but there is no 4th page.

We might be able to fix it so it shows 4 pages with 5,5,5,1 posts on each respectively.

**Comment by BenLubar** [comment]
Hmm, if you can't reproduce it on a topic created in NodeBB, it might be because the topic on WTDWTF was imported and some computed value is off by one.

(queries from a backed-up version of the database so nobody posts in between)

```
> db.objects.findOne({_key: 'topic:12236'})
{
        "_id" : ObjectId("56de5701f848f35aaeb6ba21"),
        "_key" : "topic:12236",
        "tid" : 12236,
        "uid" : 626,
        "cid" : 8,
        "mainPid" : "12236",
        "title" : "The Official Status Thread",
        "slug" : "12236/the-official-status-thread",
        "timestamp" : 1405715268528,
        "lastposttime" : 1478796175303,
        "postcount" : 57879,
        "viewcount" : 888669,
        "locked" : 0,
        "deleted" : 0,
        "pinned" : 0,
        /* omitted: a bunch of keys starting with _imported_ */
        "teaserPid" : "1036721"
}
> db.objects.count({_key: 'tid:12236:posts'})
57876
```

Well, that definitely explains it. postcount and the number of replies definitely shouldn't differ by 3. What's the difference supposed to be?

**Comment by barisusakli** [comment]
```
>db.objects.count({_key: 'tid:12236:posts'})
57876
```

This is the real number of replies so that's correct.

```
> db.objects.findOne({_key: 'topic:12236'})
{
  ...
        "postcount" : 57879,
 ...
}
```

postcount should be reply count + 1 so 57877

**Comment by BenLubar** [comment]
Ok, so I did this:

```
db.objects.aggregate([{
	$match: {
		_key: 'topics:tid'
	}
}, {
	$project: {
		_id: 0,
		topicKey: {
			$concat: ['topic:', '$value']
		},
		repliesKey: {
			$concat: ['tid:', '$value', ':posts']
		}
	}
}, {
	$lookup: {
		from: 'objects',
		localField: 'topicKey',
		foreignField: '_key',
		as: 'topic'
	}
}, {
	$lookup: {
		from: 'objects',
		localField: 'repliesKey',
		foreignField: '_key',
		as: 'replies'
	}
}, {
	$project: {
		topic: {
			$arrayElemAt: ['$topic', 0]
		},
		expected: {
			$size: '$replies'
		}
	}
}, {
	$project: {
		topic: '$topic',
		expected: {
			$add: ['$expected', {
				$cond: {
					if: {
						$gt: ['$topic.mainPid', 0]
					},
					then: 1,
					else: 0
				}
			}]
		}
	}
}, {
	$project: {
		tid: '$topic.tid',
		url: {
			$concat: ['https://what.thedailywtf.com/topic/', '$topic.slug']
		},
		postcount: '$topic.postcount',
		expected: '$expected',
		problem: {
			$ne: ['$topic.postcount', '$expected']
		}
	}
}, {
	$match: {
		problem: true
	}
}])
```

and the result:

```
[
        {
                "expected" : 104,
                "tid" : 21152,
                "url" : "https://what.thedailywtf.com/topic/21152/testing-candidate-s-mettle-s02e04",
                "postcount" : 105,
                "problem" : true
        },
        {
                "expected" : 1,
                "tid" : 21056,
                "url" : "https://what.thedailywtf.com/topic/21056/micro-and-macro-in-purple",
                "postcount" : 0,
                "problem" : true
        },
        {
                "expected" : 3,
                "tid" : 21055,
                "url" : "https://what.thedailywtf.com/topic/21055/micro-and-macro-in-purple",
                "postcount" : 2,
                "problem" : true
        },
        {
                "expected" : 58360,
                "tid" : 12236,
                "url" : "https://what.thedailywtf.com/topic/12236/the-official-status-thread",
                "postcount" : 58362,
                "problem" : true
        }
]
```

I've fixed them with `$inc` in the MongoDB shell, but it's strange that only four topics were affected and only one of them was an imported topic.

**Comment by barisusakli** [comment]
Nice aggregation 🤓 

Yeah I am not sure why the postcount in the topic is going out of sync with the real value. We increment it on every new post and only decrement when a post is purged.

A process crash could cause it if happens after the post is added to `tid:<tid>:posts` and before the $inc of postcount.

**Comment by boomzillawtf** [comment]
What about:
* forking a topic?
* moving a post to a different topic?

**Comment by barisusakli** [comment]
Both of those use the same method `Topics.movePostToTopic` and we decrease increase here https://github.com/NodeBB/NodeBB/blob/master/src/topics/fork.js#L114-L119.

I did try moving and forking and it seems to properly adjust the postcount

**Comment by barisusakli** [comment]
Let us know if you can repro with an action in core.
