### ISSUE TITLE
Password too short!

### ISSUE THREAD

**Issue by ResponsiveWebApps** [NodeBB/NodeBB#5224]
Someone else install a Nodebb instance for me to use.
In the Admin account settings, it asks for a password.
I typed in a password that is 5 characters long.
After Nodebb is installed, I tried to log in as Admin but recieved the error. 

> Login Unsuccessful
> Password too short!

Trying to reset password gives me an error of "Invalid e-mail."

The problem is that settings allows you to set a 5 character long password.

**Comment by Radiergummi** [comment]
Yeah, that's because the password length is compared as `password.length < config.minimumPasswordLength`. Therefore, the minimum is 6 chars.

**Comment by julianlam** [comment]
Bug here does seem to be that when using the installation interface (not `./nodebb setup`, but the web interface), it will allow fewer characters and fail to create the admin account altogether.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/4867
