### ISSUE TITLE
Plugins getting deleted automatically

### ISSUE THREAD

**Issue by ranjithkumar8352** [NodeBB/NodeBB#5227]
Hello, I've installed NodeBB on Heroku. I'm using MongoDB from [mlab](https://mlab.com/)

Everything is working fine but installed plugins are getting deleted automatically after some time. Only default plugins remain. All other admin settings and plugins settings are saved, only plugins are getting deleted.

I've installed plugins like google analytics, social login plugins(Google, Github, Twitter). All of them are gone after some time. This happened 3 to 4 times. First I thought I deleted them by mistake but it happened again today.

I installed all the plugins this morning and activated. When I logged in the afternoon they are gone.

Can you please help me resolve this?

NodeBB: 1.2.1
git hash: d748c5cd6269d1f4c1b4faf43499067d952edf91
MongoDB : 3.2.10
Forum link : https://forum.codingislove.com

Thank you!

**Comment by barisusakli** [comment]
Try putting the plugins in your package.json, this belongs in http://community.nodebb.org
