### ISSUE TITLE
changing language to russian causes timeago links to disappear

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5228]
1. change language to russian 
2. click /recent page link in header

![image](https://cloud.githubusercontent.com/assets/2583394/20519884/6325a22a-b0ad-11e6-9e7a-3e438759aa38.png)

**Comment by ResponsiveWebApps** [comment]
Is there a package being used to convert the time stamp into something that says "1 hour ago"? it probably doesnt convert it into other languages.  
Option 1: Somehow fix it that it still says in English "1 hour ago".
2: Just shows the time and date as normal.
3: Find or make a package that converts into dozens of languages. 
4: Find away to translate it into any language, even if it is not a correct translation.

**Comment by julianlam** [comment]
Hm, regression found

**Comment by julianlam** [comment]
6f1e5a8
