### ISSUE TITLE
Profile page pagination 

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5233]
If infinite scroll is disabled, profile page's posts should use pagination instead

(Internal note: HS#6355)

**Comment by pichalite** [comment]
@psychobunny persona already has that right?

**Comment by psychobunny** [comment]
Vanilla seems to be working as well... seems like a custom theme issue, my bad

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/d22776d8be8614c42477d04669e54d0ef70d8431 :trollface:

**Comment by BenLubar** [comment]
@barisusakli this is a bit inconsistent: https://what.thedailywtf.com/user/hitoshirenu-shourai

![image](https://cloud.githubusercontent.com/assets/4257305/20861796/71b0b60e-b95e-11e6-83b3-0dc8099e843a.png)

Not really an information leak since we already have cached post counts, but...

**Comment by psychobunny** [comment]
That's an interesting point actually... that page would already look broken sans-pagination because of the `143 posts`...

**Comment by barisusakli** [comment]
I think the issue here is the user has a lot of posts in a private category
