### ISSUE TITLE
new_chat_with appears in dropdown instead of "Start new chat with X"

### ISSUE THREAD

**Issue by psloh** [NodeBB/NodeBB#5235]
Thanks again for your great software! I just made a fresh install via git, and it appears to be v1.3.0. My git hash is 4db89407c4dbe9850d925bd9529a1d106419531f. I'm using MongoDB, version 2.6.10.

When I view another user's profile page, the top item is labeled "new_chat_with" instead of "Start new chat with X":

![admin expii forum - google chrome_141](https://cloud.githubusercontent.com/assets/9962856/20600889/d9aeb158-b223-11e6-8e6a-123fd4d5691a.png)

This isn't a terrible bug, but I thought to let you know as this is probably a very easy fix.

Thank you!

**Comment by julianlam** [comment]
Already fixed in d19171decc6478489b13bf12e05954415322017f

**Comment by psloh** [comment]
Thank you, and so sorry for bothering you. Your work is truly excellent.
