### ISSUE TITLE
Timestamps wrong on cold load

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#5237]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
  * https://github.com/boomzillawtf/tdwtf/tree/1fbe251d5911c228fcdcc60234fa434605210d7d
  * https://github.com/NodeBB/NodeBB/tree/d4638ffc15b1c62f7a960499838d42735aeb12c9
* Database (mongo or redis) and it's version.
  * **MongoDB** 3.2.10
  * Redis 3.2.4
* Exact steps to cause this issue
    1. Load https://what.thedailywtf.com/popular in a new tab
        * The timestamps of the topics initially load as "2 years ago"
        * Within a fraction of a second, the timestamps change to "2014-07-18T20:27:48.528Z"
    2. Click on "Day" and then go back to "Popular"
        * The timestamp is now in the expected format "18 Jul 2014, 15:27"

ref: https://what.thedailywtf.com/topic/21465/time-keeps-on-breaking-breaking-breaking

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5236 dupe?

**Comment by BenLubar** [comment]
Hmm, I tried the latest master and my staging instance just hangs. I'll try to bisect.

**Comment by BenLubar** [comment]
@barisusakli https://github.com/NodeBB/NodeBB/commit/c33d3e874a688857368147d81e7a61d4b0a444be#commitcomment-19974668
