### ISSUE TITLE
socket.io-client 1.7.0+ dist path change breaks NodeBB

### ISSUE THREAD

**Issue by stuwil** [NodeBB/NodeBB#5241]
Versions: master (2e28a8f7c75d5fbd2c4def4dc376132c961d63d9), v1.3.0 (4db89407c4dbe9850d925bd9529a1d106419531f)

socket.io 1.7.0 and higher (NodeBB package.json in above versions specifies latest from major version 1.x.x) changes the location of the client file from `./node_modules/socket.io-client/socket.io.js` to `./node_modules/socket.io-client/dist/socket.io.js` (see socketio/socket.io#2766).

socket.io client fails to load from the [old path](https://github.com/NodeBB/NodeBB/blob/2e28a8f7c75d5fbd2c4def4dc376132c961d63d9/src/meta/js.js#L19), lots of things break in NodeBB...

**Comment by ET-Bent** [comment]
Unsure if related but when installing NodeBB on a clean Ubuntu 16.04.1 server strictly following the docs I cannot log in. 

I get this in the browser:

![selection_085](https://cloud.githubusercontent.com/assets/5788982/20707569/3e87db0c-b62c-11e6-92f1-2d772db20297.png)

**NodeBB's log shows:**

```
29/11 12:00 [29315] - error: /login
 invalid csrf token
```

Tried installing NodeBB multiple times in multiples fresh Ubuntu instances. Always the same issue. Registering also throws the same error.

Same issue happens with and without NGINX reverse proxy (as some older issues were related to this). Not related to the browser, happens with Firefox, Chrome, Opera.

**Steps to reproduce:**

- Install latest NodeBB to fresh Ubuntu 16.04.1 server following the official docs
- Run `./nodebb setup` and follow the wizard
- Open NodeBB in a browser (`http://SERVERIP:4567`)
- Login with credentials used in wizard above.

**Latest log:**

```
NodeBB v1.3.0 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

29/11 11:54 [29167] - info: Time: Tue Nov 29 2016 11:54:11 GMT+0100 (CET)
29/11 11:54 [29167] - info: Initializing NodeBB v1.3.0
29/11 11:54 [29167] - info: initializing NodeBB ...
29/11 11:54 [29167] - info: [plugins/emoji-one] Initial startup detected. Downloading emojione assets...

29/11 11:54 [29167] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-composer-default

29/11 11:54 [29167] - info: Routes added
29/11 11:54 [29167] - info: NodeBB Ready
29/11 11:54 [29167] - info: Enabling 'trust proxy'
29/11 11:54 [29167] - info: NodeBB is now listening on: 0.0.0.0:4567
29/11 11:54 [29167] - info: [plugins/emoji-one] Emoji are ready.
29/11 11:54 [29167] - error: /login
 invalid csrf token
29/11 11:58 [29167] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
29/11 11:58 [29167] - info: [app] Database connection closed.
29/11 11:58 [29167] - info: [app] Web server closed to connections.
29/11 11:58 [29167] - info: [app] Shutdown complete.
```

**Comment by barisusakli** [comment]
@ET-Bent what is the value of `url` in your config.json? Your issue is unrelated to this one.

**Comment by stuwil** [comment]
@barisusakli I was actually seeing this as well in my staging environment due to this same issue.

**Comment by julianlam** [comment]
Still get a `29/11 10:44 [42958] - warn: Route requested but not found: /socket.io.js.map` on latest...

**Comment by ET-Bent** [comment]
@barisusakli It was localhost, it was `SERVERIP` it was `my.domain.tld` (when testing with NGINX), it was `127.0.0.1` always resulting in the same issue.

**Comment by barisusakli** [comment]
@ET-Bent open a new issue, post the repro steps along with config.json etc.

**Comment by windht** [comment]
Same Problem Here.
 However, a simple fix for now is changing the package.json file to use older versions of socket
```
"dependencies": {
    .....
    "socket.io": "1.4.8",
    "socket.io-client": "1.4.0",
   ....
}
```
After changin the above lines, rerun `npm install` to make modules go backward.
Then do a restart, things will work the same.

**Comment by liuminghao233** [comment]
try  npm remove socket.io@1.7.1

and then npm install socket.io@1.4.8

edit package.json doesn't work .
