### ISSUE TITLE
Store pinned topics in new zset

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5243]
This has already been done, I'm just filing this here as a breaking change

**Comment by psychobunny** [comment]
https://github.com/NodeBB/NodeBB/commit/c33d3e874a688857368147d81e7a61d4b0a444be#commitcomment-19974668

**Comment by pichalite** [comment]
@psychobunny incorrect milestone?

**Comment by psychobunny** [comment]
thanks, updated
