### ISSUE TITLE
Unable to Login ("forbidden") and "error: invalid csrf token" after installation

### ISSUE THREAD

**Issue by TBG-FR** [NodeBB/NodeBB#5244]
Hi,

I recently re-installed NodeBB for some reasons (errors, errors, errors...)
And all apparead to work properly, until we tried to login...

On login, a message appears, it says "Forbidden".
I checked the logs, the error is "error: invalid csrf token"

I searched a lot on the web, especially on Github Issues, but I didn't managed to fix it, and I need your help...

```
Versions (npm version) :
nodebb: '1.3.0'
npm: '4.0.2'
```

Thanks in advance !

**Comment by windht** [comment]
It is the socket io version problem.
Check here. I have encountered the same problem and fixed now.
[https://github.com/NodeBB/NodeBB/issues/5241](url)

**Comment by sorvani** [comment]
Still having problems after switching to master.

**Comment by TBG-FR** [comment]
Solved it with https://github.com/NodeBB/NodeBB/issues/5241#issuecomment-264072473
Thanks a lot for your help !
