### ISSUE TITLE
Include Portuguese (Portugal) in the next release

### ISSUE THREAD

**Issue by neutral-proton** [NodeBB/NodeBB#5251]
Hi,
I have just completed the translation to Portuguese (Portugal) using transifex website (https://www.transifex.com/nodebb/nodebb/translate/#pt_PT/) reaching 100% translation.
Could you please review it so that this language would make it in the next release?

Thanks in advance,
neutral-proton

**Comment by julianlam** [comment]
Certainly, and thank you for your contributions! 😄
