### ISSUE TITLE
Category custom global CSS class

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#5257]
Hi!

Can you add a global CSS class for the category?

Currently we can add custom class, but this is not really useful when we want create a design especially for the category.

With the global CSS class added to the body (for all pages related to the category) we can made it easily and prefix all rules for the custom design with `.customCategoryGlobalClass`.

Thank you !

**Comment by psychobunny** [comment]
This should be possible already unless I'm misunderstanding something:

* `.page-category { }` to style any category page
* `.page-category-1 { }` to style category ID 1's page
* `.page-category-announcements { }` to style category named "announcements"

**Comment by antoine-pous** [comment]
The problem is simple. The category is not present when you read topic and on modals. So i can't customize the category and all the components for this category.
