### ISSUE TITLE
forum did't start v1.4.0 (error: TypeError: Cannot read property 'toString' of undefined)

### ISSUE THREAD

**Issue by alff0x1f** [NodeBB/NodeBB#5264]
* NodeBB v1.4.0 (d120ee8) 
* mongodb
* Exact steps to cause this issue
    1. Update forum from v1.3.0 to v1.4.0
    2. ./nodebb start
* What you expected
    * expert sucesfull start
* What happened instead
    * start crash with error:

```
7/12 12:22 [16827] - info: Time: Wed Dec 07 2016 12:22:28 GMT+0000 (UTC)
7/12 12:22 [16827] - info: Initializing NodeBB v1.4.0
7/12 12:22 [16827] - warn: You have no mongo password setup!
7/12 12:22 [16827] - info: [database] Checking database indices.
7/12 12:22 [16827] - info: [database] Checking database indices done!
7/12 12:22 [16827] - info: initializing NodeBB ...
7/12 12:22 [16827] - error: TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (/home/user/NodeBB/src/languages.js:80:38)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (/home/user/NodeBB/src/languages.js:80:38)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
7/12 12:22 [16827] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
7/12 12:22 [16827] - info: [app] Database connection closed.
7/12 12:22 [16827] - info: [app] Web server closed to connections.
7/12 12:22 [16827] - info: [app] Shutdown complete.
[cluster] Child Process (16827) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
```

**Comment by barisusakli** [comment]
Is this happening on master as well?

**Comment by alff0x1f** [comment]
Doesn't test. 
I update v1.2.1 -> v1.3.0 (it works) and immediately update from v1.3.0 to v1.4.0 (since this version didn't work, I revert all changes back to v1.2.1.). Make second try to update tomorrow.

**Comment by alff0x1f** [comment]
Try update v1.3.0 to v1.4.0 again and get same error. 
After it I update v1.4.0 to 975141b, make ```./nodebb upgrade``` (success) and after start I get this:

```
15/12 16:41:24 [23810] - info: Time: Thu Dec 15 2016 16:41:24 GMT+0000 (UTC)
15/12 16:41:24 [23810] - info: Initializing NodeBB v1.4.0
15/12 16:41:25 [23810] - warn: You have no mongo password setup!
15/12 16:41:28 [23810] - info: initializing NodeBB ...
15/12 16:41:28 [23810] - error: [plugins] NodeBB encountered a problem while loading plugins ENOENT: no such file or directory, open '/home/user/NodeBB/public/language/en_US/language.json'

15/12 16:41:28 [23810] - error:  Error: ENOENT: no such file or directory, open '/home/user/NodeBB/public/language/en_US/language.json'
    at Error (native)
[cluster] Child Process (23810) has exited (code: 0, signal: null)
```

**Comment by barisusakli** [comment]
@julianlam, @pitaj  any idea why there is request to en_US instead of en-US?

**Comment by alff0x1f** [comment]
May be try turn off all plugins?

**Comment by alff0x1f** [comment]
Try upgrade again, but before disable all plugins and update directly from v1.3.0 to master (975141b). Command ```./nodebb upgrade``` was successful.

Get same error after start - ```no such file or directory, open '/home/user/NodeBB/public/language/en_US/language.json' ```

It it be useful - before update default forum language was Russian.

**Comment by julianlam** [comment]
When you upgrade, can you paste the upgrade log here? As part of the upgrade script, existing user language settings should have been updated.

Do you have any plugins or themes that explicitly set a user's language?
