### ISSUE TITLE
How to give manually reputation points to user

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#5266]
* NodeBB version : 1.4.0 d120ee86cfe2a55efcd3982cc3e8fa3f71284602
* Database : Redis 3.2.5

I would like know how to give manually reputation to a specified user, currently my community grew and i would like start events with some reputations points as reward.

I don't find anything on the ACP to do that.

Thank you!

**Comment by julianlam** [comment]
Hi @antoine-pous -- there is no way to do so without diving into the database manually.
