### ISSUE TITLE
Custom category class name on categories, topics list and topic read

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#5267]
* NodeBB version 1.4.0 d120ee86cfe2a55efcd3982cc3e8fa3f71284602
* Database Redis 3.2.5.
* Exact steps to cause this issue
     Set custom CSS class `hots` to `category #1` named `Heroes Of The Storm`
* What you expected
    * [x] Get `.hots` on component `categories/category` on `/categories`
    ```html  
        <div component="categories/category" class="col-md-3 col-xs-6 hots category-item" data-cid="1" data-numrecentreplies="0" style="position: absolute; left: 0px; top: 0px;"></div>
    ```
    * [ ] Get `.hots` on body when we read the topic list on `/category/1`
    ```html
    <body class="page-category page-category-1 page-category-heroes-of-the-storm hots" style="padding-bottom: 281px;"></body>
    ```
    * [ ] Get `.hots` on body when we read the topic on `/topic/1`
    ```html
    <body class="page-topic page-topic-1 page-topic-my-heroes hots" style="padding-bottom: 281px;"></body>
    ```

Why i ask this feature ? Simple. I would like build one design for each category game, design related to the game who change every component design. The best way to do that is add custom class on the body for prefixing all rules with `.hots`.

Thank you!

**Comment by julianlam** [comment]
On category pages, you'll notice that `body` has a class you can use:

e.g. in [General Discussion](https://community.nodebb.org/category/2/general-discussion)

The classes `page-category page-category-2 page-category-general-discussion skin-default` are available, so you'd use `page-category-general-discussion`, or in your case, `page-category-heroes-of-the-storm`.

**Comment by antoine-pous** [comment]
yeah and when i'm read a topic how i can know the category?
