### ISSUE TITLE
Lang support for categories

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#5268]
Can you add an option to set the lang for each category?

This should be set on component `categories/category` like this
```html
 <div component="categories/category" lang="en" [...]></div>
```

Topic list an topic read
```html
<html lang="en">
```

A global parameter should be usefull for forums with only one lang, but for multilingual forums add the possibility to set it directly on the category settings is the best way.

So we can have French/Esperanto/English primary categories and subforums correctly configured.

Add another option to force the interface translation related to the category settings, if the user hasn't configured it, should be awesome.

**Comment by julianlam** [comment]
No, unfortunately this is not supported (and won't be in core), as it is very limited in use. Languages are defined globally and can be overridden by user setting, and if further overrides are required, I would recommend either building a plugin to do so...
