### ISSUE TITLE
Compose Box Not Scrolling With Long Content

### ISSUE THREAD

**Issue by obsidianspider** [NodeBB/NodeBB#5269]
Please include the following information when submitting a bug report/issue:

running nodebb 1.4.0 - d120ee86cfe2a55efcd3982cc3e8fa3f71284602
mongo db 3.2.11
persona theme

When I click on "New Topic" or "Reply" and compose a message that has a lot of text and also contains an image, the compose box on the left and preview on the right no longer scroll. The scrolling also appears to break when using a lot of text. 

![screen-shot-lots-of-text](https://cloud.githubusercontent.com/assets/21102979/21013969/0513e47e-bd2a-11e6-834c-9879c5e7da5b.png)

![screen-shot-compose-not-scrolling](https://cloud.githubusercontent.com/assets/21102979/21013924/c912c116-bd29-11e6-89ef-edeb394b41c4.png)

I expected the boxes to scroll as they used to in the past.

Instead the scrolling in the compose area stops and the entire page scrolls, but the compose area doesn't move so you can't see your work.

**Comment by pitaj** [comment]
What browser?

**Comment by obsidianspider** [comment]
Firefox 48.0.2 on OS X 10.7.5, though others have reported it as well, not sure of their environment.

**Comment by meleu** [comment]
Same on Debian/Firefox 48.

**Comment by pitaj** [comment]
Yeah this is a know issue on Firefox. Are you on composer v4.3.0?

**Comment by joolswills** [comment]
v4.3.0 is the version.

Will update as mentioned above.

**Comment by joolswills** [comment]
@obsidianspider I have updated the version of composer on our set-up - please can you let me know if it fixes it for you.

**Comment by obsidianspider** [comment]
@joolswills I just tried a post with an image in Firefox and it appears to be working now. 
![screen shot 2016-12-09 at 12 48 00 pm](https://cloud.githubusercontent.com/assets/21102979/21058818/d3b10e36-be0d-11e6-832d-2aa88cc70a09.png)
