### ISSUE TITLE
issues with redis while trying to upgrade nodebb

### ISSUE THREAD

**Issue by babatundebusari** [NodeBB/NodeBB#5270]
while trying to upgrade nodebb from version 1.0.3 to 1.3.0 and got this error message
by the way this is using docker

ran the below command inside the docker container

`./nodebb upgrade`

output

```
1. Bringing base dependencies up to date .. OK
2. Checking installed plugins for updates.. OK
3. Updating NodeBB data store schema..
....
....

TypeError: cannot assign to read only property 'path' of NODEBB_REDIS
...
...
...
Error: undefined
```

NODEBB_REDIS is the variable used for the remote redis host/endpoint

Can anyone please help with this error?

**Comment by barisusakli** [comment]
Is there no stack trace?

**Comment by babatundebusari** [comment]
@barisusakli 

```
1. Bringing base dependencies up to date .. OK
2. Checking installed plugins for updates.. OK
3. Updating NodeBB data store schema..
/app/node_modules/redis/lib/createClient.js:62
                options.path = port_arg;
                                      ^

TypeError: cannot assign to read only property 'path' of NODEBB_REDIS
        at createClient (/app/node_modules/redis/lib/createClient.js:62:26)
        at Object.exports.createClient (/app/node_modules/redis/index.js:1081:41)
        at Object.module.connect (/app/src/database/redis.js:85:16)
        at Object.module.init (/app/src/database/redis.js:47:24)
        at upgrade (/app/app.js:285:28)
        at Object.<anonymous> (/app/app.js:75:2)
        at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)

Error: undefined
```

**Comment by stuwil** [comment]
@babatundebusari Can you clarify what docker image are you using?

@barisusakli The docker image [linked in the docs](https://nodebb.readthedocs.io/en/latest/installing/docker.html) is really outdated (using NodeBB v0.5.0) as it hasn't been updated in a year, and according to https://github.com/NodeBB/NodeBB/issues/4184, isn't under control of the core team either (pinging @xaoseric, do you have access to this?). Would you accept a pull request to remove it from the docs to avoid confusion?

**Comment by babatundebusari** [comment]
@stuwil 
i don't think it has anything to do with the docker image
because i used the same image a localhost redis and it works; upgrade went successfully

but now for PROD using a remote redis host, it is flipping out.

From the error message posted above, no chance as to what is causing it?

**Comment by stuwil** [comment]
@babatundebusari Need to see the Dockerfile you're using so we're on the same page, and how you're invoking it - are you passing NODEBB_REDIS as an env var, or is that the name of the linked redis instance?

**Comment by stuwil** [comment]
As this doesn't appear to be a bug, we should probably continue on the community. Looks like [this is your post](https://community.nodebb.org/topic/9951/issues-with-redis-while-trying-to-upgrade-nodebb)...

**Comment by psychobunny** [comment]
Thanks all, this is definitely a configuration issue as opposed to a bug, I will close - please use the community for these sort of issues :)

Happy to reopen if there is indeed an issue with the core code.
