### ISSUE TITLE
Investigate scattered reports of restart button in ACP not actually building assets

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5275]
:shipit:

**Comment by exomarty** [comment]
Maybe this change 
https://github.com/NodeBB/NodeBB/issues/5209

**Comment by julianlam** [comment]
@baris potentially fixed here: c32e6aaabb1da60edeeeb5531ae47f7481fed720

**Comment by yariplus** [comment]
Works

**Comment by exomarty** [comment]
how did you tried it on production?

**Comment by yariplus** [comment]
Yes, I had two forums with the problem, updated to master, and now changing themes in the ACP works without issues.
