### ISSUE TITLE
Topics with drafts should have a little draft icon next to them

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5284]
Much like when I have a draft of an email saved, and my inbox would show if a specific email had a reply draft saved, perhaps we should do something similar with topics that have drafts written up?

![image](https://cloud.githubusercontent.com/assets/923011/21168205/42b51316-c180-11e6-8782-d375d68089b4.png)

☝️ hastily mocked up mockup.

**Comment by julianlam** [comment]
Pinging @psychobunny and @pichalite for their thoughts, design-wise.

**Comment by psychobunny** [comment]
Plugin territory, your words :D
