### ISSUE TITLE
updateProfile multiple security vulnerabilities

### ISSUE THREAD

**Issue by segura2010** [NodeBB/NodeBB#5287]
I was thinking about making a pull request fixing the vulnerabilities, but i don't know if my fixes are correct or will break something, so I am just reporting the vulnerabilities.

## XSS vulnerability

There is a XSS vulnerability in the "picture" field of an user (see https://github.com/NodeBB/NodeBB/blob/ecef0c6ad55f99f08011f3df81526213314249d1/src/user/profile.js#L17). As you can see, an user can send an URL to fill the "picture" field. A malicious user could send something like: 

```
socket.emit("user.updateProfile",{"uid":"USER_UID","fullname":"","website":"","birthday":"","location":"","groupTitle":"","signature":"","aboutme":"","picture":'invalid_URL"onerror="alert(1);"'})
```

## File Deletion

A malicious user could be able to delete any file in the system providing a malicious "uploadedpicture" field on updateProfile request. Then, the user can force the deletion of the picture (see: https://github.com/NodeBB/NodeBB/blob/ecef0c6ad55f99f08011f3df81526213314249d1/src/socket.io/user/picture.js#L87). It can be achieved sending these request:

```
socket.emit("user.updateProfile",{"uid":"USER_UID", "uploadedpicture":"../app.js"})
socket.emit("user.removeUploadedPicture",{"uid":"USER_UID"})
```
(Be careful, this example removes the app.js file in the root of NodeBB)

Both vulnerabilities can be fixed removing "uploadedpicture" and "picture" from "fields" array (https://github.com/NodeBB/NodeBB/blob/ecef0c6ad55f99f08011f3df81526213314249d1/src/user/profile.js#L17), but i'm not sure if there is any feature which requires it.. :)

**Comment by segura2010** [comment]
@barisusakli super fast!! Nice!! :D I have a few more vulnerabilities, but im not at the computer now.. I will report these tomorrow :)

**Comment by julianlam** [comment]
@segura2010 please report all future vulnerabilities to security@nodebb.org

**Comment by segura2010** [comment]
@julianlam ok! :)

**Comment by julianlam** [comment]
@segura2010 We haven't received any email about the other issues you've uncovered, just wanted to follow up 😄

**Comment by segura2010** [comment]
@julianlam sorry, i've had a few busy days :(

Give me a few minutes, I'm writing the email :)
