### ISSUE TITLE
When starting/restarting nodebb the categories are often missing from homepage

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#5296]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash: v1.4.1 - 3309f2910d2aa56f06d92a1912dc10ce30da10e2
* Database (mongo or redis) and it's version. Mongodb 3.2.11
* Nginx nginx version: nginx/1.10.2 (from dotdeb.org)

when doing `./nodebb start` or `./nodebb restart` the categories are often missing from the homepage. I have to stop and restart and after a few attempts it looks ok. Sometimes it has what looks like some broken html/template code in it too.

eg see
![screenshot_2016-12-20_00-37-24](https://cloud.githubusercontent.com/assets/5365574/21334100/8c26cc62-c64c-11e6-8f72-37ff65baf57b.png)

proxying to nodebb from nginx - nodebb config

```
{
    "url": "https://retropie.org.uk/forum",
    "bind_address": "127.0.0.1",
    "secret": "REMOVED",
    "database": "mongo",
    "port": [4567, 4568, 4569, 4570, 4571, 4572],
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "REMOVED",
        "database": "nodebb",
        "password": "REMOVED"
    },
    "redis": {
        "host":"127.0.0.1",
        "port":"6379",
        "database": 0
    }
}
```

**Comment by joolswills** [comment]
In fact I seem unable to get the categories to appear currently after 4 or 5 attempts. Assuming it's some cache issue is there any way to "clear it" without restarting ?

**Comment by joolswills** [comment]
did another `./nodebb upgrade; ./nodebb restart` and they came back. not sure the upgrade was needed but thought it might clear some cache. As I remember when I have had this before restarting was enough (but took a few attempts).

**Comment by julianlam** [comment]
I'm sorry, but we need more information than that. Symptoms are not enough for us to debug, and we need reliable reproduction steps otherwise there is no way we can fix something we cannot see.

**Comment by joolswills** [comment]
I appreciate that - but I am not sure what more I can provide as it's not something that happens everytime. I'm wondering if it's some race thing due to the fact I have multiple nodebb processes.

Is there something I can provide further that would aid in debugging (I am a developer, but not very familiar with nodejs). eg some data from a cache or something.

**Comment by joolswills** [comment]
I could duplicate the set-up and get it into the state where the categories don't appear and provide remote access if that would help.

**Comment by julianlam** [comment]
At this time it seems like a configuration issue, so I would recommend preparing a database dump and continuing this on the forum until a set of reproduction steps can be obtained.

**Comment by joolswills** [comment]
I will close then. Why do you think it's a configuration issue though ?

**Comment by barisusakli** [comment]
Try disabling the recent cards plugin and test again. The way that plugin rewrites categories.tpl might be causing this.

**Comment by joolswills** [comment]
@barisusakli thanks - will try that.

**Comment by joolswills** [comment]
@barisusakli I can confirm btw that disabling the recent cards plugin solves it - would you like me to open a ticket against that plugin?

**Comment by pitaj** [comment]
Yes, please.

**Comment by barisusakli** [comment]
Yeah this is know issue, already filed on the plugins tracker.
