### ISSUE TITLE
Restarting system duplicates assets

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5318]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.4.1
* Database Mongo
* Exact steps to cause this issue
  
Seems like the new build feature is not working perfect.
restarting my system with restart button on admin panel makes the assets to be duplicated
example: writing a post ends with a duplicated post, ignore user plugin inserts two ignore buttons, etc

to restart correctly i have to...
stop nodebb, start again and run build on the console :/
Thank you!

**Comment by pichalite** [comment]
Already fixed here. Upgrade to 1.4.2.

https://github.com/NodeBB/NodeBB/issues/5300
