### ISSUE TITLE
tag enhancement - allow copy / paste list of tags instead of typing each one out.

### ISSUE THREAD

**Issue by dede5** [NodeBB/NodeBB#5323]
The current tagging system is good until....you're writing lots of topics.

Please allow copy / paste list of tags instead of typing each one out.

**Comment by pichalite** [comment]
@dede5 Don't think this is possible. NodeBB allows multi-word tags. If you copy/paste tags list, how does NodeBB determine where a tag starts and where it ends?

**Comment by barisusakli** [comment]
You can paste this into the tag input and hit enter `tag1, second tag, tag3` and they will turn into 3 tags.
