### ISSUE TITLE
[Enhancement] Make the express.sid cookie expiry more precise

### ISSUE THREAD

**Issue by DomLennonZA** [NodeBB/NodeBB#5334]
Hi,

We are using a custom SSO plugin for our authentication. Part of what we want to do is refresh our token every _N_ number of minutes. I think the best way of doing this would be to expire the _express.sid_. At the moment this is only configurable by the day. Can we make it more precise, i.e. giving it the minutes, days and months?

If this is the best case, I am happy to do the work, my only concern is the translations. How do you go about adding the translations?

**Comment by julianlam** [comment]
Hi @DomLennonZA -- are you perhaps referring to the internal config `meta.config.loginDays`?

Briefly looking over the code, I can see that we use this config and save it in the `express.sid` cookie as part of the `maxAge` property, so this can be made more specific as you've recommended.

However, some technical deficiencies identified (none of which are your fault, but do need to be resolved before going further):

1. Both Redis and MongoDB ought to read from this config, but do not, and assume `14` (days).
1. `maxAge` is used server-side, `maxAge` *and* `expires* is used client-side. Should either use one, the other, or both (what is best practice here?)
1. Unsure of behaviour if "Remember Me" option is checked vs not, needs testing.

Then and only then can we update the logic so we pass in `loginSeconds` or the like.

----

... in the meantime have you tried putting in a float in the `loginDays` field? :shipit:

**Comment by DomLennonZA** [comment]
Putting a float in wont work because the code that sets the max age parses it as an _int_. Is it possible for me to assign this to myself?

**Comment by julianlam** [comment]
Unfortunately not, but feel free to open a PR 😄

**Comment by DomLennonZA** [comment]
@julianlam So I understand why Redis and Mongo default to the 14 days. Meta relies on the database, so we cant grab settings from meta until we have initialized our database. Yay, chicken and egg problems.

There are 2 solutions:

- We grab the config value in database `init()` function. This is kind of dirty because we bypass Meta and if we were to ever make changes to it, we would need to replicate those. 
- We add another step in the `start.js` initialization right after we get the configs. This will set up the `sessionStore` properties in the current database. 

Right now I am working on the second way, but if you can think of a better way, let me know.

**Comment by DomLennonZA** [comment]
Closed with https://github.com/NodeBB/NodeBB/pull/5356

**Comment by julianlam** [comment]
:+1:
