### ISSUE TITLE
[Enhancement] Ban reasons

### ISSUE THREAD

**Issue by DomLennonZA** [NodeBB/NodeBB#5336]
Add the ability to add a ban reason when banning a user. The admin/moderator doing the work can either select a predefined reason that can support translations, or the admin/moderator can write a custom reason.

Predefined reasons can be:

- Spam
- Abuse

**Comment by julianlam** [comment]
We do have ban reasons, actually... they're available when banning a user via their profile, or from ACP when doing a temporary ban.
