### ISSUE TITLE
[Enhancement] Disable tag notifications for some groups

### ISSUE THREAD

**Issue by DomLennonZA** [NodeBB/NodeBB#5337]
Add a setting to groups to disable notifications when the group they are part of is tagged. The main reason for this is the forum we are currently running contains a group with all of our employees in it to show users. We dont mind people tagging the group, we just dont want all of our employees being spammed when its mentioned.

**Comment by pitaj** [comment]
Seems reasonable to me. Adding a watching, not watching, ignoring dropdown on the group page would be a satisfactory solution, right?

**Comment by julianlam** [comment]
> Adding a watching, not watching, ignoring dropdown on the group page would be a satisfactory solution, right?

Oh lord, that sounds like overkill.

I was actually thinking just a "notify members on group mention" option in the group settings...

**Comment by pichalite** [comment]
The setting should either be on the mentions plugin settings page or added to group administration section by the plugin coz the setting doesn't make sense without the plugin.

**Comment by pitaj** [comment]
@pichalite I agree.

**Comment by DomLennonZA** [comment]
@pichalite The mentions plugin doesnt seem to have a settings page. Are you proposing creating one then? 

Would you like me to pick up the task? How exactly does getting a task assigned to you work here? :D

**Comment by DomLennonZA** [comment]
Bump @pichalite @julianlam @pitaj 

> @pichalite The mentions plugin doesnt seem to have a settings page. Are you proposing creating one then?

**Comment by DomLennonZA** [comment]
The _nodebb-plugin-mentions_ library currently has a notion of `noMentionGroups`, this is just not exposed to an admin in any way. There two options are:

- Add a field to the group administration page with a flag stating if the group is _mentionable_.
- Create an ACP settings page for the mentions plugin that grabs all the groups and you can set it in there.

What would the preference be here?

**Comment by pichalite** [comment]
> Add a field to the group administration page with a flag stating if the group is mentionable.
This has to be done by the mentions plugin but right now there is no way for plugins to add settings to group administration section. So, creating ACP settings page for mentions plugin is my suggestion.

**Comment by DomLennonZA** [comment]
Closing this as it is a task currently open in the mentions plugin. https://github.com/julianlam/nodebb-plugin-mentions/issues/85
