### ISSUE TITLE
[Enhancement] Add a new hook for manipulating routes

### ISSUE THREAD

**Issue by DomLennonZA** [NodeBB/NodeBB#5341]
Sorry if this is already available. We want to be able to disable certain routes, i.e. the user's profile page. The reason for this is we have a profile page on our website and don't want to introduce confusion. Right now we are getting around this by just returning a 404 from the page controller. 

Since we are doing this in multiple places we want to make a plugin where we can specify exactly which pages we want to disable. 

What I have tried so far is using the _static.app.load_ and registering the routes in there, telling Express to just send a 404. This works fine when browsing directly to the URL, however, when navigating from within NodeBB the RegEx I provide to Express doesn't get matched as the path is just _/api/_.

My idea for the implementation would be to add another middleware in _webserver.js_ above all the other middlewares. This would fire an event called something like _middleware.page.request_. We could then hook into this and apply whatever logic we need.

I am unsure of any other benefits we could gain from this, but I'm sure there may be.

**Comment by barisusakli** [comment]
Sounds like `filter:router.page` should be able to do what you need. Check `req.path` in the hook, make sure you account for both `/user` and `/api/user` and then return 404.

**Comment by DomLennonZA** [comment]
@barisusakli That's exactly what I needed. I guess my only critique then is that it's not mentioned in the [hooks page](https://github.com/NodeBB/NodeBB/wiki/Hooks) :)

**Comment by barisusakli** [comment]
That page is generated by a automated script I guess the regex doesn't catch all hooks. @psychobunny
