### ISSUE TITLE
Admin Panel is broken

### ISSUE THREAD

**Issue by thelemonenergy** [NodeBB/NodeBB#5343]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
NodeBB 1.4.2
Hash d5fb6dac38e4fb102dcd0a0256238019da1e84cf

* Database (mongo or redis) and it's version.
MongoDB 2.6.10

* Exact steps to cause this issue
    1. First I did this...
First I Backuped the whole Database and Restored it on a new Vserver and copied the public/uploads 
folder with uploaded images
I freshly installed nodebb on the new server before, jumping to a new release
    2. Then, I clicked on this item...
Then it worked totally with all posts and users existing
* What you expected
    * e.g. I expected *abc* to *xyz*
I expected it to work with maybe a little missing user content
* What happened instead
    * e.g. Instead, I got *zyx* and NodeBB set fire to my house
Instead the administrative things do not work anymore:
I can go to /admin but it will not open anything but the admin Dashboard. If i click onother thing like /Manage/cathegories the Body remains empty.

I did things wrong there i think, but i really need help with fixing it without loosing posts or accounts.
Maybe someone can tell me a way to reinstall and then only restore posts and accounts.

**Comment by pichalite** [comment]
@thelemonenergy this issue tracker is for bugs and change requests. Post on the community https://community.nodebb.org for help with setup.

**Comment by julianlam** [comment]
Thanks @pichalite
