### ISSUE TITLE
Navigating away after modifying category privileges shows unsaved changes warning

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#5344]
Navigating away after modifying category privileges shows unsaved changes warning even though the there is a note on the page that says changes take effect immediately and saving is not required.

The changes do take effect immediately so there are no unsaved changes.

**Comment by sp-Carlos-Escura** [comment]
I added a comment in commit that fixes the issue. 
Now also prevents the error if the category has any Whitetag

**Comment by pichalite** [comment]
@sp-Carlos-Escura you should send a PR with the fix for tags. Also this issue is specific to category privileges and not category page in general.
