### ISSUE TITLE
Issue domain name

### ISSUE THREAD

**Issue by ZerGabriel** [NodeBB/NodeBB#5347]
Please tell me how to make what my website did not work http://ip:4567/ a http://forum.mydomainname.ru/

I have the following settings:
{
"url": "http://forum.mydomainname.ru",
"secret": "censor",
"database": "mongo",
"port": 80,
"mongo": {
"host": "127.0.0.1",
"port": "27017",
"username": "censor",
"password": "censor",
"database": "censor"
}
}

nginx, apache httpd is not installed.
VPS, Debian GNU/Linux Jessie. Linux 3.6.x
NodeBB 1.4.2
Installed only NodeJS, MongoDB.
I use http://www.cloudflare.com as DNS.
I have recorded a cloudflare DNS record.
I don't use https, only http.

Please explain how that would make my site work as http://forum.mydomainname.ru/

**Comment by julianlam** [comment]
https://docs.nodebb.org/en/latest/configuring/proxies/nginx.html
