### ISSUE TITLE
Buttons and Other Text Labels Not Displaying

### ISSUE THREAD

**Issue by t0rched** [NodeBB/NodeBB#5348]
Fresh install of latest stable, and I have this on most all of my buttons in ACP:
![bug](https://cloud.githubusercontent.com/assets/20378331/21746336/d57a443e-d506-11e6-8bd2-cba14145196a.png)

**Comment by pitaj** [comment]
Check out this thread: https://community.nodebb.org/topic/10031/issue-with-admin-panel-since-upgrade-to-1-4-2/36
