### ISSUE TITLE
Auto unban not working

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5350]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.4.2
* Database mongo
* Exact steps to cause this issue
    1. Banned user for 2 days
    2. Waited 4 days and still is banned
* What you expected
    * To be unbanned
* What happened instead
    * No unban, tested to ban just 1 hour and still ddidnt work

Thank you!

**Comment by julianlam** [comment]
User is unbanned when they try to log in again, not automatically on expiration.

**Comment by exomarty** [comment]
Good to know Thanks
