### ISSUE TITLE
Can't access to categories

### ISSUE THREAD

**Issue by Yann151924** [NodeBB/NodeBB#5351]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
 Version 1.4.2 and b1b9174479fa5806b4b30276ae3e10027d2074f5
* Database (mongo or redis) and it's version : redis version 3.2.6
* Exact steps to cause this issue
    1. Just go ACP->Manage->Categories and nothing happen
    2. Try refreshing the page but nothing to

I have this error on chrome console :

`acp.min.js?v=b94d75de-1bd5-4e3d-b8a0-b5547a7bb736:3 GET https://forum.mineaurion.com/api/language/fr/admin%2Fadmin  404 (Not Found`)

`acp.min.js?v=b94d75de-1bd5-4e3d-b8a0-b5547a7bb736:3 GET https://forum.mineaurion.com/api/language/fr/admin%2Fmenu 404 (Not Found`)

`acp.min.js?v=b94d75de-1bd5-4e3d-b8a0-b5547a7bb736:3 GET https://forum.mineaurion.com/api/language/fr/admin%2Fmanage%2Fcategories 404 (Not Found`)

* What you expected
    Categories edit page
* What happened instead
    Blank page

I don't know if it's a misconfiguration but it happen when i upgrade to the latest version.

Thank you!

**Comment by julianlam** [comment]
Can you please try with latest commit in `master`? This may have already been fixed.

**Comment by Yann151924** [comment]
On `master` don't have the issue, and my forum is a bit faster :).

I fallback to branch `v1.x.x`, when do you release a new version ?
