### ISSUE TITLE
User slug not generating link to user profile on a post reply.

### ISSUE THREAD

**Issue by jarey** [NodeBB/NodeBB#5363]
Just saw the issue on the community.nodebb.org site:

Can be reproduced/seen on this post: https://community.nodebb.org/topic/10098/loading-nodebb-in-my-site-through-iframe

I think the problem should be the space or ' character present in the username but don't really know.

Thank you!

**Comment by julianlam** [comment]
I think it might be due to the `'` in the username 😬

**Comment by pichalite** [comment]
This belongs in the mentions plugin repo.

**Comment by jarey** [comment]
Sorry, will move the issue to the corresponding repo.

**Comment by jarey** [comment]
Moved to: https://github.com/julianlam/nodebb-plugin-mentions/issues/89
