### ISSUE TITLE
Question: What filter hook to use to filter categories?

### ISSUE THREAD

**Issue by QwertyZW** [NodeBB/NodeBB#5367]
I'm looking to write a plugin that filters the categories, google searches yielded no results.

The relevant hook that I've already tried is

`filter:category.get`

But that only goes off when a given category is accessed.

Any advice?

**Comment by pitaj** [comment]
FFR, a better place to ask is on our [community forums](https://community.nodebb.org). 

What kind of filtering are you doing? I'd try `filter:categories.build` if you want to do something special, otherwise you may want to use the privilege system.

**Comment by QwertyZW** [comment]
Just something as simple as hiding categories. Nothing privileged related. Just to make the category list more readable
