### ISSUE TITLE
Associate the several logins

### ISSUE THREAD

**Issue by diasdavid** [NodeBB/NodeBB#537]
It seems that there isn't a way to link the several logins after they are created, for example I have my login with user and password , named "daviddias" and when I try to login with twitter I get this answer

```javascript
{
  "error": "Username taken!"
}
```

**Comment by julianlam** [comment]
78863a438f32e3f2f826e8c815d2fe4ca6a2b920

Facebook: julianlam/nodebb-plugin-sso-facebook@d99f3dbc921e145b47d9aaea410efe9c3774577c

**Comment by julianlam** [comment]
About to close this after 1 year and 10 months :smile: 

![selection_067](https://cloud.githubusercontent.com/assets/923011/10028327/c2319bee-6139-11e5-82b2-827ca93021de.png)

**Comment by julianlam** [comment]
It is up to individual SSO plugins to add entries to this list. You can see how it is done in this changeset:

https://github.com/julianlam/nodebb-plugin-sso-google/commit/63fe92738d3ea64c02ef6d3a165d7277b4ddae22

**Comment by psychobunny** [comment]
Haha :clap:
