### ISSUE TITLE
Question: Where to add custom node.js code?

### ISSUE THREAD

**Issue by vtrenten** [NodeBB/NodeBB#5370]
I had a bit of code that integrates with my monitoring software for servers, It supports node.js programs. 

npm package: node-dogstatsd

```
 var StatsD = require('node-dogstatsd').StatsD;
 var dogstatsd = new StatsD();
 
 # Increment a counter.
 dogstatsd.increment('page.views')
```

**Comment by julianlam** [comment]
You will want to create a plugin for this: docs.nodebb.org/en/latest/plugins/create.html
