### ISSUE TITLE
Admin panel language strings are not sent to the browser.

### ISSUE THREAD

**Issue by Xseba360** [NodeBB/NodeBB#5372]
* NodeBB 1.4.2 d5fb6dac38e4fb102dcd0a0256238019da1e84cf
* redis 3.2.4
* Exact steps to cause this issue
    1. Upgraded from NodeBB 1.4.0 to 1.4.2
    2. Opened Admin panel
    3. The strings are not translated.
        ![http://i.imgur.com/YSRxToL.png](http://i.imgur.com/YSRxToL.png)

* When i started investigating the issue i noticed the language strings are not sent to the browser
![http://i.imgur.com/dFIejPP.png](http://i.imgur.com/dFIejPP.png)

Thank you!

**Comment by pitaj** [comment]
I believe this is fixed in `master`. ffa2bd14f85929e7fa08eb5badfa8d9cb155e4ef

**Comment by Xseba360** [comment]
Okay, I'll wait for a next release and report back if this is not fixed. Thanks!
