### ISSUE TITLE
How can I combine nodebb and my node app?

### ISSUE THREAD

**Issue by ayxos** [NodeBB/NodeBB#5375]
there is a node app A which has a '/forum/' endpoint where i want to run nodebb. i want to have one single node app, delegating the /forum stuff to nodebb and handling the rest of the app by its own. I have been reading a lot of issues but i cannot find something simliar. 
Can you help me?

Thanks

**Comment by julianlam** [comment]
Hello there, this is an issue tracker for bugs with NodeBB. Please check out our [community forum](https://community.nodebb.org) for installation/configuration related discussion. Thanks!
