### ISSUE TITLE
ACP Translation on transifex?

### ISSUE THREAD

**Issue by Pappmann** [NodeBB/NodeBB#5388]
When will be released the translations for ACP on https://www.transifex.com/nodebb/nodebb ?

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/604206843e3998924d05e3d1d51b620030ad3aa6

**Comment by julianlam** [comment]
Thanks, Misty couldn't push to `master` because of a config issue, resolved now.
