### ISSUE TITLE
Accessing language files

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#5396]
`26/1 08:31:15 [12224] - [33mwarn[39m: [deprecated] Accessing language files from `/api/language` is deprecated. Use `/assets/language/[langCode]/[namespace].json` for prefetch paths.`

There is continuous this error in logs.

**Comment by pitaj** [comment]
This isn't an error. It's a deprecation warning. Even when this deprecated path is removed, it is unlikely to break things.

**Comment by julianlam** [comment]
Hey @pitaj -- it's a deprecation warning, but isn't the underlying issue that something is calling it (for example, a plugin?)

Is it not possible to add an indication of who's calling it?

**Comment by pitaj** [comment]
The is an indication in the assets route pr
