### ISSUE TITLE
Suggestion: Add Open Search Capability

### ISSUE THREAD

**Issue by henrikekblad** [NodeBB/NodeBB#5399]
Would be excellent to hook up the search engine to the open search spec:
https://www.chromium.org/tab-to-search

Just a matter of a new link tag in head
 ```
<link type="application/opensearchdescription+xml" rel="search" href="osd.xml"/>
```

...pointing to a new route presenting this info:

```
<?xml version="1.0"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
 <ShortName>Search My Site</ShortName>
 <Description>Search My Site</Description>
 <Url type="text/html" method="get" template="http://my_site/search?term={searchTerms}&in=titlesposts"/>
</OpenSearchDescription>
```

**Comment by julianlam** [comment]
Love the idea -- definitely think it would be a nice addition, though it's low priority at the moment 😄

**Comment by henrikekblad** [comment]
Understandable. Good to have a quick one in the backlog for a rainy day. 

Keep up the good work @julianlam!

**Comment by julianlam** [comment]
#5501

**Comment by julianlam** [comment]
Thanks to @RoiExLab for the implementation 😄
