### ISSUE TITLE
Update New Translation

### ISSUE THREAD

**Issue by a632079** [NodeBB/NodeBB#5401]
Hello，our team have completely translated english to chinese.I hope you can give our team a Reviewer and help us review correctly.Thanks you.

**Comment by julianlam** [comment]
Thank you for you and your team's efforts in localising NodeBB into Simplified Chinese! It is much appreciated.

I have made you a reviewer on the Transifex team. Please let me know your team members' Transifex usernames if you would like them promoted as well.

**Comment by julianlam** [comment]
Unfortunately I do not speak or write Chinese (and even if I did, I'm from HK, 😄 ) -- however I am confident you and your team will do a good job.
