### ISSUE TITLE
Feature Request: Sort By Last Online on Users Page

### ISSUE THREAD

**Issue by michaelpfaff** [NodeBB/NodeBB#5402]
Would like to suggest a feature / enhancement. Some of my users have requested a Last Online sort option alongside the Online, Top Posters, etc. section of the Users page. Would love to see this added. 

On that note, the ability to organize / turn off some of those sort options in the ACP.

**Comment by barisusakli** [comment]
The online page is already sorted by online time, it just updates every [5 mins](https://github.com/NodeBB/NodeBB/blob/master/src/user/online.js#L29-L33). You can hide those tabs with css or override the template to reorder.

**Comment by michaelpfaff** [comment]
What? No. This is a request to have all listed users sorted by most recent login. The online page only shows current users online. Come on now.
