### ISSUE TITLE
deprecate 'action:plugin.activate' and 'action:plugin.install'

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5407]
If a plugin has a handler for 'action:plugin.activate' it is not called when you activate the plugin because the plugin is not initialized yet.

We need to register the hooks for a plugin when they are being activated(or installed) before firing that hook.

This also happens for the `action:plugin.install` hook.

**Comment by Telokis** [comment]
@barisusakli Why did you remove them, I don't understand. I have a plugin that is based on `action:plugin.install`. https://github.com/Telokis/nodebb-plugin-save-plugins

**Comment by barisusakli** [comment]
They weren't working, that's why they were removed, even if your plugin was listening to these hooks it wouldn't be called.

**Comment by barisusakli** [comment]
I see your plugin was using it for a different purpose so we might bring the hook back for that use case.

**Comment by Telokis** [comment]
I never thought it would be used as a trigger for the plugin itself. To me it really was meant to be something for plugins to manage other plugins (not themselves).
Same thing goes for `action:plugin.active`. Maybe we could rename/clarify them so that nobody does this confusion? (Are there people who were misleaded by those?)

**Comment by barisusakli** [comment]
Yeah they were used by some plugins to do initialisation on plugin install or activate but obviously they weren't working because a plugin  doesn't have it's hook listening when it is newly installed or activated.

I brought back those hooks though so it will work for your use case.

**Comment by Telokis** [comment]
Thank you very much!
I thought `static:app.load` was meant to do plugin init. Is that wrong?

**Comment by barisusakli** [comment]
That's correct although that hook gets fired on every app startup unlike just `action:plugin.install` or `action:plugin.activate`
