### ISSUE TITLE
Admin area layout is totally broken on ipad

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#5410]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.4.2
Navigating up and down on ipad in admin area ends with broken layout

will post photo later
Thank you!

**Comment by pichalite** [comment]
@exomarty do you have screen shots?

**Comment by exomarty** [comment]
There you go
![image](https://cloud.githubusercontent.com/assets/10746278/22575803/54023422-e9b8-11e6-943f-0b3a05cd0352.jpeg)
![image](https://cloud.githubusercontent.com/assets/10746278/22575807/595be102-e9b8-11e6-802d-f814ca953a5a.jpeg)

**Comment by pitaj** [comment]
This is due to the touch events activating the slide-in menu which changes some CSS and messes stuff up.

**Comment by julianlam** [comment]
I wouldn't call the **totally broken**... it only happens when you switch from mobile mode to desktop.

**Comment by exomarty** [comment]
No @julianlam it happens everytime i load the page and i go down and then up which is always you try to setup something them you go up to go to another section or restart the node

**Comment by julianlam** [comment]
No @exomarty -- cannot reproduce without an orientation change. Not saying this isn't a bug, but that it is low priority.

**Comment by exomarty** [comment]
Not calling it high prior
I always use ipad horizontally, is strange that you cant reproduce it 
I use ios9 and ipad air and safari
