### ISSUE TITLE
Inertial scroll not working in admin panel

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#5415]
NBB version: 1.4.3
Browser: iOS safari

Inertial scrolling in the admin panel hasn't been working for quite a few versions now (as long as I can remember, since the latest big rewrite of the ACP) for the main view. Inertial scrolling works for the pop out menu, just not the main panel. Low priority but I thought I would write it down

**Comment by julianlam** [comment]
Thanks @bdharrington7 -- looks like something that could potentially be fixed as the sidebar in ACP is the same as the sidebar in Persona.

@psychobunny @pichalite , any thoughts?

**Comment by pichalite** [comment]
The library used for the sidebar is same but the sidebar is actually causing the scrolling issues. The layout of the header & menu needs to be looked at to fix this. May be some CSS too.

**Comment by pichalite** [comment]
Fix was simpler than I thought.
