### ISSUE TITLE
The value 'upload_path ' in config.json doesn't work as expected.

### ISSUE THREAD

**Issue by hao-lee** [NodeBB/NodeBB#5416]
Hi,
I wanted to use another directory to save uploaded files, so I followed [this tutorial](https://docs.nodebb.org/en/latest/configuring/config.html) and changed the value of `upload_path` to `/../uploads` in config.json. And then I encountered an error. You could read [this post](https://community.nodebb.org/topic/10201/upload-folder-not-changed) for more details. Thanks!

Other information:
* NodeBB version: v1.4.2
* Database: MongoDB

![](https://piccdn.freejishu.com/images/2017/02/06/AaGU.jpg)

**Comment by a632079** [comment]
@pitaj Maybe the sounds also need be repaired

**Comment by pitaj** [comment]
Should be fixed in #5420

**Comment by hao-lee** [comment]
Thank you for all your hard work!
