### ISSUE TITLE
Suggestion: cookie "loggedin" when the visitor is logged in (and deleting the same cookie when visitor is logged out)

### ISSUE THREAD

**Issue by vstoykovbg** [NodeBB/NodeBB#5418]
This cookie will allow Nginx to differentiate anonymous visitors from logged in visitors in order to serve static cache files.

This cache can be made by another application.

Here is example code from `nginx.conf` (WP Super Cache):

```
set $cache_uri $request_uri;
```
...

```
# Don't use the cache for logged-in users or recent commenters
if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+
                     |wp-postpass|wordpress_logged_in") {
    set $cache_uri 'null cache';
}
```
...

```
# Set the cache file
set $cachefile "/wp-content/cache/supercache/$http_host/$cache_uri/index.html";
if ($https ~* "on") {
    set $cachefile "/wp-content/cache/supercache/$http_host/$cache_uri/index-https.html";
}

# Add cache file debug info as header
add_header X-Cache-File $cachefile;

# Try in the following order: (1) cachefile, (2) normal url, (3) php
location / {
    try_files $cachefile $uri $uri/ /index.php;
}
```

I just found out that NodeBB is using two cookies: `io` and `express.sid` not only if the user is logged in, but for all users. There should be another cookie, which is present only when the visitor is logged in (i.e. `loggedin`) in order such caching to work.

Another way of caching is using `proxy_cache` [(Guide)](https://www.nginx.com/blog/nginx-caching-guide/).

I have idea of using `proxy_cache` plus a daemon, which will watch for changed topics and will delete specific cache files.

**Comment by julianlam** [comment]
@vstoykovbg Are you running into limits in terms of how much content NodeBB can parse? WP Super Cache generates static html files for nginx to serve because the php preprocessing takes a long time out-of-the-box (same goes for something like Drupal).

NodeBB is optimized from the start to not need anything like this, and should be working very fast from the start.

**Comment by vstoykovbg** [comment]
Yes, it is faster, but is not as fast as serving static files.

[I have no idea what I am doing](http://i.imgur.com/JyzDFyX.jpg), but I tried to guess:

```
req.cookie('loggedin', '1');
```
and

```
res.cookie('loggedin', '1');
```

did not work (I tried to insert them within the `authenticationController.onSuccessfulLogin` function).

What is the correct way to create a cookie?
