### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5419]
I found some issues when upgrading from 1.4.2 to 1.4.3 related to the current translation.
There are a couple issues with the current translation...
The first thing I noticed, is that there are some translations missing; e.g. [these lines](https://github.com/NodeBB/NodeBB/blob/master/public/language/en-GB/admin/general/dashboard.json#L26-L30) are only present in the en-GB translation...
**_ALL OTHER_** translations including en-US **_DO NOT_** have this line, resulting in nodeBB showing the raw string e.g. `restart-not-required` for example, this is fixed easily.
Another thing I found, is also related to the translation but in another way. I noticed this, because the version check no longer worked for me, since english isn't my native language.
Inside the dashboard.js file, there is a line which gets the span with the id `version` and compares it against the newest github version ([line](https://github.com/NodeBB/NodeBB/blob/926186108b0170499cd9bcead7d0f748a3111c16/public/src/admin/general/dashboard.js#L54)).
Using the german translation (could be any other translation, but thats the one I used) this id is **_NOT EXISTING_**, because somebody - I'll call him @nodebb-misty messed up and escaped the backslash inside the translation file ([proof](https://github.com/NodeBB/NodeBB/blame/master/public/language/de/admin/general/dashboard.json#L15))
I hope this gets fixed soon...
Thanks for your attention

**Comment by julianlam** [comment]
a122aad54d7418226f59e353b97a191a45afadeb

Extra `\` issue is from extra backslash in translation itself, not NodeBB. Fix it there.

**Comment by RoiEXLab** [comment]
Thanks for your quick response and action!
