### ISSUE TITLE
invoke http://localhost:4567/assets/language/zh_CN/global.json is response 404

### ISSUE THREAD

**Issue by phyer** [NodeBB/NodeBB#5423]
in version 1.4.3 
http://localhost:4567/assets/language/**zh_CN**/global.json can not be found.
but **zh-CN** folder canbe found in "public/language/" folder,
something wrong?

**Comment by jiangcaiyang** [comment]
Before this problem, try ```./nodebb upgrade``` first.

**Comment by julianlam** [comment]
Yes, likely you will need to run `./nodebb build`. Let us know if this problem persists.

**Comment by phyer** [comment]
Yes, resolved by this way, Thanks
