### ISSUE TITLE
Posting a reply to a long topic does not scroll to post properly

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5428]
* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
    * b1511a18709c0e4d32031bb6b78f0bee961a5a5c
* Exact steps to cause this issue
    1. Enter a topic with more replies than the pagination limit
    2. Ensure that the topic is loaded from the first post, so there are posts in that topic that have not loaded yet (beyond the first "page")
    3. Reply to OP
* What you expected
    * Posts that were unloaded (e.g. post indices 21 and onwards) are loaded, followed by the new reply
* What happened instead
    * Notice that you are sent to the bottom of the page, but IS is not triggered, so posts are missing. When scrolling, IS is triggered immediately (but does behave normally)

**Comment by julianlam** [comment]
@boomzillawtf This may be of interest to you?

**Comment by boomzillawtf** [comment]
This sounds very familiar, but I haven't allowed that behavior since https://github.com/NodeBB/NodeBB/pull/4372
