### ISSUE TITLE
Stick with HTML conventions

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5432]
I know, that this isn't a high priority issue, but I just wanted to note that there are a couple issues regarding html standards with NodeBB.
(I'm using the [NodeBB Community Forum](https://community.nodebb.org) as reference)
Using the [W3C HTML-Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fcommunity.nodebb.org%2F), you can see, that there are a couple of "violations" regarding the html specification.
Most of them can easily be resolved. NodeBB is using custom attributes like "component" and others.
HTML5 has a solution for that, it's called [data-attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes).
I'm sure you heard of it, but if you don't it's basically a "legal" way to assign custom data to html tags.
This data can be easily retrieved and accessed via css and javascript.
This way we get rid of half of the violations.
Other issues are:
- Invalid placement of tags, for example any tag that is not `li` inside an `ul` or `ol` tag _**OR**_ the `script` tag **_AFTER_** the `html` tag at the end of every document
- Duplicate attibutes
- Missing attributes
- Attributes with invalid content (btw. a form tag without an action tag points to the current document itself)

I like NodeBB and I know this is a picky request, but I still hope this will be taken seriously...

**Comment by psychobunny** [comment]
Agreed and we'll address this in the next theme (the component errors would be easily find and replaceable, but we'd like to not break child themes so easily)

That said, this issue belongs on the theme repository itself, so feel free to repost there, thanks

**Comment by psychobunny** [comment]
Btw, duplicate attributes is a real problem we need to fix immediately, please let us know in the issue and we'll address

**Comment by RoiEXLab** [comment]
Thanks! I'll do that
