### ISSUE TITLE
nodebb-plugin-imgur: no symbol percent

### ISSUE THREAD

**Issue by KitsuneSolar** [NodeBB/NodeBB#5433]
- NodeBB v1.4.3
- NodeJS v6.9.5
- nodebb-plugin-imgur v1.0.18

No symbol percent (`%`). Instead of him: `&#37;`

![furdom org_-_2017-02-12 08-06-09](https://cloud.githubusercontent.com/assets/12877339/22859813/c36e303a-f102-11e6-909f-dc14b613eba0.png)

**Comment by barisusakli** [comment]
Fixed in https://github.com/NodeBB/NodeBB/issues/5400, will be avaiable in 1.5.0
