### ISSUE TITLE
Special characters formatted wrongly in notifications

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5437]
Minor issue...
Just noticed this. My forum has a forward slash in it's title.
As I got a "Desktop Notification" a la HTML5, the title contained `&#x2f;` instead of  `/`.
I believe this is the case for any other special characters as well...

**Comment by pitaj** [comment]
This is an issue with the desktop notifications plugin, not with NodeBB core, if I'm not mistaken.

**Comment by RoiEXLab** [comment]
Whoops, my mistake... Installed this right at the start, tricked me into believing this was a core functionality...
This plugin should be integrated anyway 😛

**Comment by RoiEXLab** [comment]
Opened https://github.com/psychobunny/nodebb-plugin-desktop-notifications/issues/25
