### ISSUE TITLE
Dynamically retrieve translations on restart

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5438]
The current translation system, is tied to the current release of nodebb...
If you want an updated translation, you'd either need to wait for a new release/patch of NodeBB or switch to the master branch, which may cause trouble when your using a live forum.
Since the translations JSON files are stored on github anyway, I'd find it useful, if those translation files would get retrieved, and applied to the local nodebb installation, whenever nodebb re-minifies/rebuilds all css and js files...
Of course a fallback translation is useful, for the rare case that the Github servers are down...

**Comment by julianlam** [comment]
No, I'm sorry, but it is a bad idea to have all installations of NodeBB reliant on an additional third-party data source on build.

Build times are slow enough as it is, there is absolutely no way I am turning the build step into a **half-hour** long process!
