### ISSUE TITLE
NodeBB cant display uploaded image in post!

### ISSUE THREAD

**Issue by sackery** [NodeBB/NodeBB#5441]
I upload an image in a post, when submit the image not show anymore, but the image uploaded on server.

**Comment by pitaj** [comment]
Does it show in the preview? Are there a errors client-side or in the server logs?

**Comment by pikshub** [comment]
http://imgur.com/a/Tnlrb

No visuals. No log.

**Comment by pitaj** [comment]
And there's no errors in the browser console, either?

**Comment by pikshub** [comment]
@pitaj no.

post content: 

![0_1487299085161_tumblr_olbucldZL91qzhjh2o1_500.jpg](/assets/uploads/files/1487299086798-tumblr_olbucldzl91qzhjh2o1_500.jpeg)


exp: 

<div class="content" component="post/content" itemprop="text">
	<p></p>

</div>

**Comment by pikshub** [comment]
The problem is browser cookies. Everything was fine when cleaned

**Comment by vstoykovbg** [comment]
Same problem here. Image is uploaded successfully, however it did not present in the code:

<img src="http://i.imgur.com/GR012T8.png" />
<img src="http://i.imgur.com/mjuWrSf.png" />
<img src="http://i.imgur.com/zglzz4F.png" />

**Comment by vstoykovbg** [comment]
I think the bug is somewhere in the client's code.

See how it works only when address contains the domain name:

<img src="https://i.imgur.com/qKqYDIt.png" alt="bug" />

**Comment by barisusakli** [comment]
I can repro this on latest master.

**Comment by pikshub** [comment]
not fixed

**Comment by pitaj** [comment]
You tried latest master?

**Comment by pikshub** [comment]
@pitaj yeah. online problem: https://timuu.com/post/22153

content: 

```
"![0_1487437786285_dev_games.jpg](/uploads/files/1487437791358-dev_games-resized.jpg) 

ben gölge ile karakterlerin üzerindeki derinlik etkisine bayılıyorum. kafamdaki pek olmadı, biraz pozlayıp gölgelendirmeye çalıştım kafamdakini anlatabilmek için."
```

**Comment by pitaj** [comment]
Did you edit the post? The issue was a backend issue. You may need to edit the post in order to trigger a re-parse. Also, I'm getting constant "Session Mismatch" errors on your site.

**Comment by pikshub** [comment]
@pitaj I thought I solved the problem of "Session Mismatch". It means he's still on.

**Comment by pikshub** [comment]
@pitaj 

This way it gets fixed:
https://github.com/NodeBB/NodeBB/issues/5441#issuecomment-280870057

**Comment by pitaj** [comment]
I'm not sure what you mean. Are you saying that adding the domain name fixes it? We know that, but the commit baris made to master should have fixed it entirely. Are you on the master branch? If not, you won't have this fix. This fix hasn't been released yet.

**Comment by pikshub** [comment]
yes repro on latest master but not fixed. the problem continues.

**Comment by pitaj** [comment]
Ok so I've figured out what caused this. If you edit the image url to start with `/assets/uploads` instead of `/uploads` then that should fix your issue. I'll see if I can push a fix to `nodebb-plugin-markdown` to fix it entirely, since it is a regression.

**Comment by pikshub** [comment]
Thank you for feedback. It takes too long to be edited. It's the best I can get backup.

**Comment by pikshub** [comment]
https://community.nodebb.org/topic/10270/

**Comment by julianlam** [comment]
What's the issue here @pitaj, the fallback in `uploads` not working with Markdown?

**Comment by pitaj** [comment]
No the issue is that markdown removed links not matching `nconf.get('upload_url')`, which is set to `/assets/uploads`, so existing uploads to `/uploads` are removed

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-markdown/commit/7655e48b73d4a49668d77627b6d3a121c6fc35f2
