### ISSUE TITLE
no such file /nodebb/build/public/language

### ISSUE THREAD

**Issue by mingjiu** [NodeBB/NodeBB#5442]
when I run node app.js,
```
13/2 17:43:12 [22252] - error: [plugins] NodeBB encountered a problem while loading plugins ENOENT: no such file or directory, scandir 'xxx/nodebb/build/public/language'
13/2 17:43:12 [22252] - error:  Error: ENOENT: no such file or directory, scandir 'xxx/nodebb/build/public/language'
    at Error (native)
```

how I get "build" this directory

**Comment by pitaj** [comment]
Try `./nodebb build`

**Comment by mingjiu** [comment]
I have tried it.
`
rdadm@qklink1:~/mj_installer/nodebb$ sudo ./nodebb build
sudo: ./nodebb: command not found
`

**Comment by mingjiu** [comment]
rdadm@qklink1:~/mj_installer/nodebb$ ls
app.js     config.json  Gruntfile.js  LICENSE    logs         nodebb      NodeBB.zip    package.json  public     src
bcrypt.js  Dockerfile   install       loader.js  minifier.js  nodebb.bat  node_modules  pidfile       README.md  test
rdadm@qklink1:~/mj_installer/nodebb$ sudo ./nodebb install
sudo: ./nodebb: command not found
rdadm@qklink1:~/mj_installer/nodebb$

**Comment by pitaj** [comment]
Don't run these commands with sudo.

**Comment by mingjiu** [comment]
i get it.
i run this commands
`node nodebb build`
