### ISSUE TITLE
Allow custom file extensions on upload

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5448]
While working with NodeBB, I came across the issue, that all files are named .bin after being uploaded, if their file extension (client side) is not matching any mime type.
I'm currently trying to setup a PBF system, which would require users to upload savegames with a custom format...
As you may have guessed those svegames are renamed into .bin instead of keeping their extension.
I see why it is useful to change the file extension depending on the mime type, to prevent abusing the forum as file storage for stuff malware etc.
I'd really like to see an option inside the admin panel, to allow custom file extensions which shall not be changed.

**Comment by RoiEXLab** [comment]
Because you guys were taking to long to respond, I (learned how to and) wrote myself a plugin which fixes this issue ^^
https://github.com/RoiEXLab/nodebb-plugin-custom-file-extensions
This plugin is not working for user uploads though, because the content type isn't changed.
Any Ideas on how to change the content type when a file is being uploaded?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5484
