### ISSUE TITLE
Add tls options for redis db

### ISSUE THREAD

**Issue by patiernom** [NodeBB/NodeBB#5449]
For me it would be nice to have an option to enable **tls** in Redis database, 
maybe configurable from config.json file.

For my project i have made this change directly into NodeBB's source code:
```
options.tls = { 
  servername: redis_socket_or_host
};
```
In file _**src/database/redis.js**_ at line 88

But it would be better a thing of this kind in config.json file:
```
"redis": {
  "host": "<host_name>",
  "port": <port_num>,
  "password": "<password>"
  "tls": {
    "servername": "<redis_socket_or_host>"
  }
}
```

Thanks

**Comment by barisusakli** [comment]
You can do this via config.json now.

It follows the same structure as we had for mongodb.

```
"redis": {
  "host": "<host_name>",
  "port": <port_num>,
  "password": "<password>",
  "options": {
      "tls": {
         "servername": "<redis_socket_or_host>"
       }
   }
}
```
