### ISSUE TITLE
Package Manager options

### ISSUE THREAD

**Issue by liberaltech** [NodeBB/NodeBB#5471]
Is there a NodeBB Marketplace or plugin directory/catalog?
I was wondering is there will ever be a package manager for NodeBB?

A simple searchable directory would help a lot of people find plugins or contribute plugins which do not already exist. 

I started a wiki out of the existing plugins in this is something you are wanting to incorporate into NodeBB.

[Plugins](https://github.com/liberaltech/NodeBB-Plugins/wiki/NodeBB-Plugins)
[Themes](https://github.com/liberaltech/NodeBB-Plugins/wiki/Nodebb-Themes)

I want to eventually create subcategories from the "Plugin" repo.

**Comment by julianlam** [comment]
Hey there @liberaltech, that is a good question. Right now, we have the NodeBB Package Manager, which tracks the appearance of new packages on npm, and let's you know which version of each plugin to install (as different plugin versions are compatible with different NodeBB versions).

https://packages.nodebb.org/stats

While we don't have a searchable repository, each NodeBB install retrieves the maintained list from the nbbpm, and is available in the "Extend -> Plugins" page in your ACP 😄

**Comment by julianlam** [comment]
As for a theme or plugins marketplace -- this is an idea that has been floated internally recently, and we'd like to do something like this in the short/medium-term.
