### ISSUE TITLE
Restrict accepted socket.io domains on start

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5472]
It looks as though when socket.io is started, it listens for connections from all origins by default, even though NodeBB may elect not to (via cookieDomain, etc).

Suggest adding a restriction to follow the `cookieDomain` setting, or if not set, then to infer an origin restriction based on the configured `url`.

Allow an override via `socket.io:origins` as well, and only apply origin restriction in production mode so as to not accidentally lock someone out of their forum.

**Comment by phit** [comment]
would be nice if you could mark this as breaking, because it wasn't I didn't see this before updating from 1.4.0 to 1.4.4

**Comment by barisusakli** [comment]
Yeah this seems to have some issues see #5486 as well

**Comment by phit** [comment]
thanks, as a quick fix I set this in my config.json

```
"socket.io": { 
     "origins": "*:*"
}
```

**Comment by barisusakli** [comment]
Does it not work if you put all the urls you use like @julianlam suggested in his original post?

```
 "socket.io": {
    "origins": "http://forum.example.org:* http://boards.example.org:*"
  }
```

**Comment by phit** [comment]
No, it didn't. I assume that's because I'm using apache2 as a reverse proxy.
```
    RewriteEngine On
    RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
    RewriteCond %{QUERY_STRING} transport=websocket    [NC]
    RewriteRule /(.*)           ws://localhost:4567/$1 [P,L]
```
But even if it did, I have no idea what the origin is in the case of this software which runs on Minecraft servers and connects to NodeBB via a plugin https://github.com/yariplus/minecraft-nodebb-integration

**Comment by segura2010** [comment]
Another way to fix this security issue is to send the user cookie/token in the first websocket message. So the server can use it to authenticate the user and NodeBB forums will not have problems with the configuration if they use different subdomains.

**Comment by julianlam** [comment]
@phit glad to hear it works now. We do our best to ensure that breaking changes are kept in a separate branch for a later release, but this one was a bit higher priority as there are potential security implications (again, thanks @segura2010 for helping us find this one).

Once #5486 is resolved, it should be backwards compatible...

**Comment by yariplus** [comment]
Is there a way to add origin urls from a plugin?

**Comment by julianlam** [comment]
@yariplus I'm not sure, have you tried calling `.origins()` against the exported server instance via a plugin? My guess is it may override existing values.

```
var sockets = require('../socket.io');
var server = sockets.server;

server.origins('http://example.org:*');
```

**Comment by segura2010** [comment]
@julianlam I believe that calling origins override the existing values. To avoid problems with plugins which could disable this security measure, I think there is a better approach which is used in other platforms (Periscope, Slack..). They send the cookie/token in the first message of the Websockets protocol or in the GET params of the websocket URL (wss://domain/path?token=something). Then they can use this token in order to authenticate the user instead of reusing the HTTP cookie.

This fix I propose won't break plugins and if some plugin is broken it is easy to fix. :)

**Comment by julianlam** [comment]
Thanks @segura2010 -- will need to investigate this solution further 😄

**Comment by julianlam** [comment]
[Untested solution](https://groups.google.com/forum/#!topic/nodejs/2dSONMs651YZ)

`io.connect('http://localhost:8080?token=foobarbaz');`

and read from server via

`socket.handshake.query.token`

**Comment by pitaj** [comment]
Query string is encrypted when using https

**Comment by julianlam** [comment]
Sure is, but doesn't mean I should try it anyway 😄  (Can't assume people will set up https as well).

Also, no clue where I'd even find `express.sid` from client-side, as the cookie we save is not js-readable ;)

**Comment by pitaj** [comment]
Possibly the csrf uuid?

**Comment by julianlam** [comment]
Perhaps if on header render, it includes a short-lived token/nonce of some sort that can be used to authenticate a request and _verify_ that the socket call came from NodeBB, as opposed to outside.

But that's still not safe I think... malicious website could just direct user to xhr load the forum and grab the nonce...

**Comment by pitaj** [comment]
well if external websites can xhr into nodebb the CORS is set up wrong.

**Comment by julianlam** [comment]
👏  Good enough for me... any objections?

**Comment by RaceProUK** [comment]
Heyo!

Just a quick question: for those of us who run bots, it appears this change has prevented them being able to function correctly. On our instance, we use bots to help manage forum games e.g. Mafia, and we'd quite like to be able to use them again. Any advice? 😇

**Comment by barisusakli** [comment]
@RaceProUK did you try 

```
"socket.io": {
    "origins": "http://forum.example.org:* http://boards.example.org:*"
  }
```

Add the origin of the bot in that list and try agian

**Comment by RaceProUK** [comment]
We'll give it a try, but I don't know how well it'll work (the bots are typically hosted on services like Amazon AWS).

**Comment by julianlam** [comment]
Either define the hosts as Barış suggests, or use *:* to allow all origins....

That said this solution is temporary until we can figure out a more elegant solution

**Comment by yamikuronue** [comment]
@julianlam Can you keep SockDrawer informed when you decide on an elegant solution? We keep finding out about these changes because our forum admins pull an update and all our bots break :) You can reach out to anyone at https://github.com/orgs/SockDrawer/people, but I suggest myself, RaceproUK, or Accalia as the most responsive.

**Comment by segura2010** [comment]
For these who are having problems with bots, if your forum is working fine but the bot isn't you should try to add an Origin header in your bot. The WebSockets library that you use for your bot should allow to put headers, so you should set the Origin's header with the domain of your forum or the domains configured with:

    "socket.io": {
        "origins": "http://forum.example.org:* http://boards.example.org:*"
    }

I believe that it should fix the problems :)

**Comment by RaceProUK** [comment]
Update: It appears that the `*:*` workaround suggested above works 🙂

**Comment by AccaliaDeElementia** [comment]
@barisusakli actually what we did was add the forum URL as the Origin header in our requests (as you can see in https://github.com/SockDrawer/SockBot/commit/20057d7ced20e56969e499938ccc00a316224a73)

that will probably work for any nodejs based plugins, and other languages will likely have similar mechanisms for setting websocket headers.

I'm pretty sure that CORS would have prevented that trick in a web browser, but once we step outside the browser CORS becomes significantly weaker i guess.

**Comment by pitaj** [comment]
@AccaliaDeElementia that's a much better solution to the wildcarding. Wildcarding will open your users to CSRF attacks, which is why we introduced this security feature in the first place. Since servers don't have your users' session, that can't be used as an attack vector. I would highly discourage using the wildcard origin until we implement a different socket authentication strategy.

**Comment by AccaliaDeElementia** [comment]
@pitaj, I'm not sure that you need additional security, at least for applications like Sockbot.

I mean, in order for sockbot to successfully log on we need to:

* retrieve `/api/config` to get initial cookies and CSRF token [source](https://github.com/SockDrawer/SockBot/blob/master/providers/nodebb/index.js#L175)
* Use the CSRF token and initial cookies to post credentials to `/login` [source](https://github.com/SockDrawer/SockBot/blob/master/providers/nodebb/index.js#L220)
* Use the cookies set by login to pass to the websocket, along with the custom sockbot user agent, and now the Origin header [source](https://github.com/SockDrawer/SockBot/blob/master/providers/nodebb/index.js#L266)

given that browsers won't allow overriding the `referrer` nor the `origin` headers  (AFICT) that aspect cannot be bypassed by a browser script, meaning that this approach is only viable to non browser applications...

I mean i'm not objecting to security and all, but i'm not sure what additional measures would provide in the way of additional security.

**Comment by pitaj** [comment]
@AccaliaDeElementia  The extra security would only be helpful in the case where the site must have a wildcard origin acceptance, which is why I said to not use wildcard origins until the extra security is implemented.
