### ISSUE TITLE
Meta Tag content escaped too often

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5479]
NodeBB offers settings to choose a forum title & description which are also added as meta tag into the head tag.
I noticed this: a `/` was turned into `&amp#x2F`. Why? Because meta.settings.title already escaped the slash and [here it's done again](https://github.com/NodeBB/NodeBB/blob/b5f8fc815e4eee6166fb3db929b067206a2a7a3f/src/controllers/categories.js#L16).
Same with description.
Both of them are double escaped
I would even argue, that the raw slash should be inside the meta tag/the content attribute. The paths etc are also using unescaped slashes since they are enclosed in double quotes anyway.
og:site_name og:image and og:title are using single escaped strings.

**Comment by julianlam** [comment]
The likely explanation is that it is overeager sanitization in an attempt to curb an XSS vulnerability that was discovered. That said, a single round of sanitization is sufficient.

I believe the sanitization method we run handles both `/` and `"`, so it is neither or both. Most sites handling decoding of the meta tag will decode &#x2F properly.

**Comment by RoiEXLab** [comment]
Ok. In this case only the double escaped strings need to be changed...

**Comment by RoiEXLab** [comment]
But yeah, single escaping makes sense for tags being influenced by the user...

**Comment by RoiEXLab** [comment]
@julianlam Just an addition: It would already be enough to just esape chars with "regular html expressions" like `&quot; &amp; &lt; &gt; ...`. The slashes would still remain...
