### ISSUE TITLE
change unread count in header based on route

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5485]
Especially in larger communities the unread page can be spammed with lots of unimportant content which a user doesn't always wants to read.
My suggestion would be to reduce the content of the unread page to followed topics/topics the user created or replied to and "special categories" with announcements etc. which are able to be selected by the server admin.
This way the user only sees "important topics" listed there, because you can't expect a member of a large community to read every single post.
They will most likely just mark all as read to get rid of the little number indicating how many posts are unread. 

But maybe my opinion is stupid. What are your thoughts on this?

**Comment by barisusakli** [comment]
https://community.nodebb.org/unread/watched shows unread topics that you are following. If you enable follow topics on reply and follow topics I create then you pretty much get what you want.

**Comment by RoiEXLab** [comment]
Good suggestion, but changing the route to this link in the navigation isn't getting rid of the number indicating how much unread topics there are...

**Comment by RoiEXLab** [comment]
E.g. If there are no unread topics you follow, but 3 unread topics in general it will still show 3

**Comment by barisusakli** [comment]
This would require changing how we handle the unread count, right now it's just the global unread count that is displayed in the header. We would have to change it based on the route that the navigation item is pointing at.
