### ISSUE TITLE
Socket.io origins code doesn't work with subfolder installs

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5486]
https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/index.js#L36-L56

**Comment by julianlam** [comment]
Thanks -- unfortunately cannot reproduce. On an affected instance, I changed the nginx config to have this line:

`proxy_pass http://104.236.140.141:4567;`

instead of before:

`proxy_pass http://104.236.140.141:4567/forum`

When located inside `location /forum`, it works as expected.

**Comment by julianlam** [comment]
`E_NOREPRO` 😬

**Comment by simon-s9** [comment]
I got this error with a fresh install on Ubuntu16

**Comment by Julien00859** [comment]
I got the error with a fresh install

configurations and logs [on the forum](https://community.nodebb.org/topic/10309/connection-has-been-lost-error-after-update-to-v1-4-4/20)
