### ISSUE TITLE
Seeing scoped npm packages

### ISSUE THREAD

**Issue by pebcakerror** [NodeBB/NodeBB#5488]
v1.4.3 98f2fd62a549d53803110281a9e97584688c973b

My organization is using [scopes](https://docs.npmjs.com/misc/scope) to have 'private' packages published to our private registry. (Our private registry is still public so this still meet's NodeBB's GPL 3 license)

This means the plugin name comes through as `@acmecorp/nodebb-plugin-pluginname`. This in turn means the plugin isn't seen by NodeBB and not listed in the admin installed packages and therefore can't be activated.

Though a little less common, scoped packages are a standard part of npm. NodeBB should be able to handle this use case.

I suppose ideally NodeBB should just handle scoped package natively. Though it would also achieve the same thing if there were a way to manually tell NodeBB about any plugin, theme, widget, or reward that doesn't currently fit the expected naming convention.

**Comment by julianlam** [comment]
@inspiredbytes -- I agree that NodeBB should handle scoped packags, although I will admit that this is a comparatively low priority item.

If the scoped items are public, then I see no reason nbbpm (and nodebb) shouldn't read them properly. However, I'd need to ensure that they're listed in the packages listing published by npm, otherwise they won't be discoverable for nbbpm to index them.

**Comment by julianlam** [comment]
As @pitaj pointed out to me elsewhere -- are you actually **unable** to activate a plugin if it is scoped?

**Comment by inspiredbytes** [comment]
@julianlam NodeBB doesn't see the package, therefore doesn't list it in the admin, therefore can't be activated. So, correct, cannot be activated

**Comment by julianlam** [comment]
😬  Thanks for confirming.

**Comment by inspiredbytes** [comment]
would something like `npm ls --parseable --depth=0` be more useful than walking through the list of files in https://github.com/NodeBB/NodeBB/blob/master/src/plugins.js#L327

**Comment by fbatschi** [comment]
Is there any progress on this? 

A theme with a name from a scoped org is shown in the backend for activation, but when trying to activate the path does not work (omits the @organisation in the file path)

**Comment by julianlam** [comment]
@pitaj was there a regression? Last I checked, we still had to create a symlink to the scoped package directory.

**Comment by pitaj** [comment]
@julianlam I don't know, it might be worth converting the logic to async/await and adding some tests.

@fbatschi how are you activating? What file path are you referring to?

**Comment by fbatschi** [comment]
@pitaj For instance put `@bytepark/nodebb-theme-hyper` into package.json (which is a pure clone of the slick theme), do a `nodebb upgrade`. The package gets downloaded to `node_modules/@bytepark/nodebb-theme-hyper`

When you go to the ACP , you see the theme in the list of themes (although the first problem is, that the screenshot is not shown as it searches for /css/previews/nodebb-theme-hyper).

When you then try to use the theme in the Theme panel you receive an error saying

```
no such file or directory, open '/usr/src/app/node_modules/nodebb-theme-hyper/theme.json'
```
which is correct, as the theme.json is actually in `/usr/src/app/node_modules/@bytepark/nodebb-theme-hyper/theme.json`

So it does not take into account the @ scope of the theme at this moment and looks in the wrong path (although the id in theme.json is defined as `@bytepark/nodebb-theme-hyper`).

**Comment by pitaj** [comment]
Can you open a new issue, since your problem appears to only be about themes, not all plugins. This issue covers plugins.
