### ISSUE TITLE
User avatars on NodeBB servers with paths do not display properly

### ISSUE THREAD

**Issue by BrokenR3C0RD** [NodeBB/NodeBB#5491]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory): NodeBB 1.4.4, git hash 2e47cf4db31edfa3d9a38b7bd21d16cdadbd8dee
* Database (mongo or redis) and it's version: MongoDB v3.2.12, ef3e1bc78e997f0d9f22f45aeb1d8e3b6ac14a14 (from Ubuntu packages)
* Exact steps to cause this issue
    1. Created a NodeBB instance with a path set (ProxyPass'd with Apache)
    2. Set an avatar for my user
* What you expected
    * Avatar should be visible
* What happened instead
    * The image had the subpath repeated (e.g., /forum/uploads/profile1-profileavatar.jpeg becomes  /forum/forum/uploads/profile1-profileavatar.jpeg), and the image does not display properly. This does not appear  to occur with cover images

Thank you!

**Comment by andreassemborg** [comment]
+1

**Comment by julianlam** [comment]
Please share your `config.json` and Apache proxy configuration. Keep in mind we don't usually debug Apache installs, as we use nginx here.

**Comment by andreassemborg** [comment]
I am sorry for hijacking this thread – I experience the same issue though. This is my setup:

$ git rev-parse HEAD
92691782e654ed110836b4aa18b810d56270ca1b
NodeBB v1.4.4.

MongoDB shell version v3.4.2
git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b

`{
    "url": "https://domain.com/forum",
    "secret": "xxx",
    "database": "mongo",
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "xxx",
        "password": "xxx",
        "database": "nodebb"
    }
}
`

`location /forum {
                proxy_pass http://127.0.0.1:4567;
                proxy_set_header   X-Forwarded-Ssl    on;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                add_header Pragma public;
                add_header Cache-Control "public";
        }`

**Comment by BrokenR3C0RD** [comment]
@julianlam Sorry, but due to this issue, I changed my NodeBB install to redirect to a subdomain. I no longer have the original files.
