### ISSUE TITLE
IE 9 comment

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5494]
Not sure if this is the right place to open this issue, but since this is affecting all default nodebb themes, I think this Repository isn't completely wrong...
I noticed that there is html comment inside every head:
```
<!--[if lt IE 9]>
  	<script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.3.0/es5-shim.min.js"></script>
  	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script>
  	<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
  	<script>__lt_ie_9__ = 1;</script>
<![endif]-->
```
I believe this is a legacy snippet which was once used to "fix" the compatibility issues with IE versions before 9.
Since this script is obviously not working anymore (it's a comment and not using the templating syntax either), I'd vote to remove this snippet.

**Comment by julianlam** [comment]
Removing this is fine, as we only support IE11+ now.

**Comment by RoiEXLab** [comment]
Ok, closing this issue since this is a task for the individual themes...
