### ISSUE TITLE
[deprecated] Accessing font-awesome.min.css

### ISSUE THREAD

**Issue by Pappmann** [NodeBB/NodeBB#5495]
Using Nodebb latest master at a3b4c83e8b901f1a98ef22b662ba9443d1302e20

The following warning is in log after every nodebb start:

3/3 18:21:03 [2856] - warn: [deprecated] Accessing `vendor/fontawesome/css/font-awesome.min.css` from `/` is deprecated. Use `/assets/vendor/fontawesome/css/font-awesome.min.css` to access this file.

**Comment by pitaj** [comment]
I assume you aren't running on a subfolder. Can you try clearing your cache?

**Comment by Pappmann** [comment]
is fixed, there was the wrong path in "custom html"
