### ISSUE TITLE
live streaming of posts - only works a small percentage of the time

### ISSUE THREAD

**Issue by dede5** [NodeBB/NodeBB#5502]
**Problem** Live streaming of messages fails most of the time
**Desire** Have live streaming of messages work all the time - eg like a chat

**Setup**
NodeBB version 1.4
MongoDB Version 3.0.14

**Exact steps to cause this issue**
1. I am logged in with my registered account in the firefox browser. I am a guest on the chrome browser.
2. Both browsers are on the same topic url
4. The guest posts a reply to the thread on the chrome browser

**What you expected**
I expected the registered account on the firefox browser to get a notification and to see the reply live stream.

**What happened instead**
I got a notification both in the top right notification bell[red icon] and the bottom right [notification message]. However, the reply did not live stream. This lack of live streaming even happens when I am replying with my registered account. I often do not see the reply that I sent.

Note, sometimes it seems to work, but only after some "cool down" period when I don't post for a while.

I tried discussing this at nodebb forum. https://community.nodebb.org/topic/10337/real-time-streaming-not-sure-if-my-nodebb-installation-is-working/

Thank you!

**Comment by psychobunny** [comment]
Can you reproduce this on a known working installation of NodeBB ex. https://community.nodebb.org/category/4/testing-ground ?

This sounds like potentially a configuration issue... do you see any errors in the browser's console for example?

**Comment by dede5** [comment]
It happens there for me too. Some things I noticed:

● Replies don't stream in usually. I need to f5 refresh.
● I don't get notifications of replies whether I am logged in [or if I do, it takes a long time] or when I initially log in - despite there being replies.
● My browser seems fine. I am on Firefox v 43 [very old] though. Not sure if that makes a difference?

**Comment by barisusakli** [comment]
Seems to work on our environments, maybe try updating your browser.
