### ISSUE TITLE
Just did a fresh installation ob ubuntu16 server. Keep getting "Looks like your connection to NodeBB was lost, please wait while we try to reconnect."

### ISSUE THREAD

**Issue by simon-s9** [NodeBB/NodeBB#5507]
Please include the following information when submitting a bug report/issue:

NodeBB version: 1.4.4 92691782e654ed110836b4aa18b810d56270ca1b
Database: mongo
1. Installed from scratch on new ubuntu16 vm, using this [tutorial](https://docs.nodebb.org/en/latest/installing/os/ubuntu.html).
2. Followed all the steps in the tutorial.
3. Started the script.
4. Keep getting this message: 
![screenshot from 2017-03-06 19-04-57](https://cloud.githubusercontent.com/assets/14272055/23617946/d59cac24-029f-11e7-8308-426afd7cc320.png)
![screenshot from 2017-03-06 19-04-43](https://cloud.githubusercontent.com/assets/14272055/23617974/e9fc318a-029f-11e7-9ca5-26426ad4cf4d.png)
5. Nginx config: 
![screenshot from 2017-03-06 19-06-56](https://cloud.githubusercontent.com/assets/14272055/23618177/8a351162-02a0-11e7-884f-9f70c0ff2f3a.png) 
Port 8080 here is also configured in config.json.

Expected: to see the forum working.
Actual: 
1. **Looks like your connection to NodeBB was lost, please wait while we try to reconnect.** does not disappear.
2. Saving in admin section doesn't work.
3. Might be some other issues as well.

**Comment by julianlam** [comment]
What is your config.json?

**Comment by simon-s9** [comment]
Changing the `url` from 127.0.0.1 to hostname.com in config.json solved the issue. Closing.
