### ISSUE TITLE
session conflict

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#5508]
Hi,
I am in need for an emergency help guys .
My forum is facing session conflicts . In the other words when users login they will be recognized as some else and they could even log-in as admin with full access! This happens a lot when the forum hit gets high(so many online users).By the way It uses Mongo db and also Redis cache.
Since I use this forum as a communication and commenting system beside my website it is really kind of you if you pay attention to my critical case.
(master version)
Thanks

https://community.nodebb.org/topic/10348/session-conflict

**Comment by julianlam** [comment]
Hello there,

Unfortunately we do not offer configuration support for instances that we do not manage directly. Please continue this discussion in the forum thread.
