### ISSUE TITLE
captcha doens't appear in "invite only"

### ISSUE THREAD

**Issue by gswey** [NodeBB/NodeBB#5515]
nodebb version 1.4.3 (wget from github and not git clone), mongodb version 3.4.2

i sent invitations
people who receive them go to the link `...register?token=...&email=...`
so they fill the form but on the line captcha they cannot check the box **i'm not a robot** because it doesn't appear, and then a error message appear **captcha not verified, are you a robot ?**
in fact, `<div id="spam-be-gone-recaptcha-target"></div>` is empty

the plugin i use is `nodebb-plugin-spam-be-gone`

**Comment by barisusakli** [comment]
Does captcha show up for regular users who go to `/register`?

**Comment by gswey** [comment]
what do you mean ? it's a new forum and i'm at the moment the only user
do you want to make the test with my forum ?

**Comment by barisusakli** [comment]
What I meant was do if you see the captcha if you go to /register as a non-logged in user. You might have to disable invite only.

**Comment by gswey** [comment]
yes i gave the test
when user registration is normal captcha works (you can check !)
but in invite only only label 'captcha' appear
is it this test you wanted ?

**Comment by barisusakli** [comment]
Yes that helped me reproduce the issue.

**Comment by gswey** [comment]
my profile on community is https://community.nodebb.org/user/bzweo

**Comment by gswey** [comment]
thanks for your work !!!
