### ISSUE TITLE
Email template generates broken image links

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5522]
Was noticing this for a while now...
Email templates basically retrieve the post HTML by using `{postBody}` inside the template file.
This inserts HTML when being processed with the correct image tags, but without the base_url appended to those tags!
For example:
```
SomePost Text
SomeImage:
<img src="/assets/uploads/files/somefilename.png">
```
is generated instead of
```
SomePost Text
SomeImage:
<img src="{base_url}/assets/uploads/files/somefilename.png">
```
While looking at the post html on the website the base_url can easily be omitted, but when viewing using you mail client, this mail client can't know about the server...

**Comment by joolswills** [comment]
Have had a user report this on our forum - https://retropie.org.uk/forum/topic/10095/forum-subscription-emails-broken-images

>Just something that's bugging me and maybe a config thing: any images in a post are placed in the email html, but have the wrong source url. Eg, something like:

>http:///forum/assets/uploads/files/1493925908207-nes-mini-new-carousel-2-resized.png

>it looks like it's missing the retropie.org.uk part. Perhaps something in the board config?
