### ISSUE TITLE
"Session Mismatch" error

### ISSUE THREAD

**Issue by streaps** [NodeBB/NodeBB#5528]
I'm getting a session mismatch error, if cookies are disabled in the browser:

**Session Mismatch**
"It looks like your login session is no longer active, or no longer matches with the server. Please refresh this page."

This also shows up in the Google search index. It happens on my install, but also on community.nodebb.org. 

You don't have to be logged in to get this error. Just go to https://community.nodebb.org/ and the next link you click will return this error. (You have to disable all cookies in the browser first).

NodeBB should not display this error on every page again and again, just because I have disabled cookies in my browser or I'm a search engine bot. A warning could be displayed on the login page though, if cookies are disabled.

My NodeBB version: 1.4.3
Database: MongoDB

**Comment by julianlam** [comment]
@streaps -- thank you for the report, this is indeed a significant regression.

**Comment by streaps** [comment]
@julianlam 

that was fast :). thank you.
