### ISSUE TITLE
Analytics charts error after upgrade to 1.4.4

### ISSUE THREAD

**Issue by vctfernandes** [NodeBB/NodeBB#5529]
Hey guys,

I've just upgraded to 1.4.4 from 1.2.2 following the standard procedure and since that, the traffic analytics chart (dashboard) won't load.

There's the following error in the browser console:
[Error] ReferenceError: Can't find variable: o
	(anonymous function) (Chart.js:3:7449)
	each (Chart.js:3:8424)
	transition (Chart.js:3:7102)
	draw (Chart.js:3:5125)
	(anonymous function) (Chart.js:2:31692)
	each (Chart.js:3:8293)
	drawDatasets (Chart.js:2:31603)
	draw (Chart.js:2:31452)
	render (Chart.js:2:31111)
	startDigest (Chart.js:2:24223)
	(anonymous function) (Chart.js:2:23697)

DB: MongoDB 3.4.2

Any clues to why this is happening?

**Comment by julianlam** [comment]
@vctfernandes Nope, haven't been able to repro locally. Glad you can. Please build your assets in dev mode (`./nodebb build --dev`) and try loading the ACP again.

Please provide the stack trace again.

**Comment by julianlam** [comment]
There is a possible this has been resolved with c199075d98efcc82be512f6efda64b349dcb73e3, so this issue needs confirmation.

**Comment by vctfernandes** [comment]
@julianlam, `./nodebb build --dev` did solve it 😄
I did ran `./nodebb build` before and had no success, but NodeBB wasn't running, now it was (when I ran `./nodebb build --dev`).
Weird 🤔 
Anyway, thank you so much 👍

**Comment by julianlam** [comment]
Oh, that's not actually a solution, it was meant to build the client-side files without minifying, so we'd be able to get a better idea as to what the stack trace was.

Odd... if you `./nodebb build` again the problem comes back?

**Comment by vctfernandes** [comment]
@julianlam: yes, it comes back... minification issue, perhaps?

**Comment by julianlam** [comment]
That seems to be the case, although unfortunately I am still unable to reproduce with a minified client-side payload 😕

**Comment by julianlam** [comment]
Pinging @scottalanmiller, are you able to try this change on your instance?

**Comment by phit** [comment]
Seeing the same error on 1.4.4, running `./nodebb build --dev` resolves it, I tried patching my `public/src/admin/general/dashboard.js` with https://github.com/NodeBB/NodeBB/commit/c199075d98efcc82be512f6efda64b349dcb73e3 and then running `./nodebb build` but it still gives me the same error.

**Comment by phit** [comment]
Here's a diff of [`/node_modules/chart.js/dist/Chart.min.js`](https://github.com/NodeBB/NodeBB/blob/v1.x.x/src/meta/js.js#L87) and the Chart.js generated by NodeBB
https://gist.github.com/phit/07237d65663e939cd4deae87c8408121

**Comment by julianlam** [comment]
Thanks @phit. I can't imagine why the minification step would cause such issues, though I do know that we use `Chart.js` and not `Chart.min.js`, and minify it ourselves...

@pitaj can you confirm this logic, and see if you can skip the minification for modules that have `.min` in them? Then we can pass in `Chart.min.js`.......

**Comment by barisusakli** [comment]
@phit @vctfernandes can you try `./nodebb build` after applying https://github.com/NodeBB/NodeBB/commit/8d7283e6c7b1f74c9fefd7eb369dcf07388137d6

**Comment by phit** [comment]
@barisusakli that resolved it 👍

**Comment by vctfernandes** [comment]
That's it! Thanks, everyone! 👍👍👍👍
