### ISSUE TITLE
Redirect after email confirmation

### ISSUE THREAD

**Issue by ayxos** [NodeBB/NodeBB#5530]
Version: NodeBB v.1.4.4

I am using the hook ¨action:user.email.confirmed¨

i want to redirect after email confirmation but i have an error because next is not a function (is undefined)

here is the method: https://github.com/ayxos/nodebb-plugin-ns-login/blob/master/plugin/index.js#L34

     onRegisterConfirmed: function(data, next) {
                console.log('register confirmed!', data, next);
                // next is undefined
                data.referrer = 'https://interpretame.com';
                next(null, data)
     }

Can you help me please?

**Comment by pitaj** [comment]
I don't believe there is a filter hook for this, only an action hook.

**Comment by ayxos** [comment]
Ups thanks, my typo writing the issue. Still, is there something that I can do to redirect via this action hook?

**Comment by barisusakli** [comment]
Try using `filter:confirm.build`, you have access to req and res in there. `req.uid` is the uid of the user.

**Comment by ayxos** [comment]
I have already tried it but did not work. At the end i have modified 'src/controllers/index.js'

    Controllers.confirmEmail = function (req, res) {
            user.email.confirm(req.params.code, function (err) {
                    if (!err) {
                            res.redirect('https://www.interpretame.com/confirm');
                    } else {
                            res.render('confirm', {
                                    error: err ? err.message : '',
                                    title: '[[pages:confirm]]',
                            });
                    }
            });
    };

It worked!

**Comment by ayxos** [comment]
i have an error 

    Can't set headers after they are sent.

**Comment by ayxos** [comment]
fixed! the problem was the render call (due to the middleware)

     Controllers.confirmEmail = function (req, res) {
          	user.email.confirm(req.params.code, function (err) {
               res.redirect(!err ? 'https://www.interpretame.com/confirm' : 'https://www.interpretame.com/confirm_error');
         	});
     };
