### ISSUE TITLE
NodeBB no longer navigable when cookies are disabled

### ISSUE THREAD

**Issue by streaps** [NodeBB/NodeBB#5536]
Maybe this bug is related to #5528

After an ugrade to release 1.4.5 the "Session Mismatch" errors are gone, but now I see no content at all. If I click on a category, I get an empty page (only the top menu bar is displayed). Tested in Firefox with cookies disabled.

**Comment by pitaj** [comment]
Are there any errors in the JavaScript console client side?

**Comment by streaps** [comment]
Indeed:

DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: https://example.com/forum/assets/nodebb.min.js?v=189tutscah1:14]  nodebb.min.js:15:786

**Comment by julianlam** [comment]
Hello @streaps, my apologies on taking so long to issue a fix, pages should be navigable again w/o cookies 😄

**Comment by streaps** [comment]
I just upgraded to 1.4.6, but it's still the same problem. The error message in Chrome is

```
nodebb.min.js?v=7al8hgvug5n:15 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:14:18944
    at dispatch (https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:2:12500)
    at g.handle (https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:2:10421)
    at Object.trigger (https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:3:9403)
    at https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:3:9945
    at Function.each (https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:1:2990)
    at v.fn.init.each (https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:1:1079)
    at v.fn.init.trigger (https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:3:9921)
    at Object.ajaxify.end (https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:11:9816)
    at https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:11:9488
    at https://example.com/forum/assets/nodebb.min.js?v=7al8hgvug5n:15:361(anonymous function) @ nodebb.min.js?v=7al8hgvug5n:15
```

**Comment by julianlam** [comment]
@pitaj

**Comment by pitaj** [comment]
Do you have `LocalStorage` disabled in your browser, too? Do you mind clicking on the error location in your console and capturing the code context?

**Comment by julianlam** [comment]
If cookies are disabled, local storage is out too. I tagged you as I'm thinking it may be the sounds code you worked on recently?

**Comment by streaps** [comment]
> Do you mind clicking on the error location in your console and capturing the code context?

https://github.com/NodeBB/NodeBB/blob/v1.4.6/public/src/modules/translator.js#L483

**Comment by pitaj** [comment]
That's not really helpful, but thanks anyways, it's not your fault.

Anyways, I reproduced this bug.
@julianlam It's the localStorage code in `public/src/client/category.js`, `public/src/client/topic.js`, and possible some other places, too

**Comment by ishwinder** [comment]
Can this issue occur somehow in v1.8.2 as well .. Google bot is unable to crawl my 1.8.2 site and i suspect that this issue can be a potential candidate to dig further ?

**Comment by julianlam** [comment]
When you say Googlebot is unable to crawl, how do you know this is the case? What errors are shown in the webmaster console? Have you submitted your sitemap.xml to google?

**Comment by ishwinder** [comment]
Yups, I have submitted my sitemap.xml to google. Google webmaster shows that all the pages are redirecting to /user(which inturn is not found). Googlebot simulator tools like https://technicalseo.com/seo-tools/fetch-render/ show that the error is "Session Mismatch Error".

**Comment by ishwinder** [comment]
This is the flow in the logs(simulating googlebot from webmaster tools), just in case it helps in deciphering the issue .. The bot requested the url /category/6/ipo and nodebb goes to /login and then inturn to /user ..

66.249.79.71 - - [17/Apr/2018:09:55:21 +0000] "GET /category/6/ipo HTTP/1.1" 302 56 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.84.7 - - [17/Apr/2018:09:55:21 +0000] "GET /assets/language/en-US/modules.json?v=7uii96pf4j3 HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Search Console) Chrome/41.0.2272.118 Safari/537.36"
66.249.79.71 - - [17/Apr/2018:09:55:21 +0000] "GET /login HTTP/1.1" 302 56 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.84.11 - - [17/Apr/2018:09:55:21 +0000] "GET /assets/src/modules/mousetrap.js?v=7uii96pf4j3 HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Search Console) Chrome/41.0.2272.118 Safari/537.36"
66.249.84.7 - - [17/Apr/2018:09:55:21 +0000] "GET /assets/src/modules/scrollStop.js?v=7uii96pf4j3 HTTP/1.1" 200 361 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Search Console) Chrome/41.0.2272.118 Safari/537.36"
66.249.84.11 - - [17/Apr/2018:09:55:21 +0000] "GET /assets/src/modules/sounds.js?v=7uii96pf4j3 HTTP/1.1" 200 932 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Search Console) Chrome/41.0.2272.118 Safari/537.36"
66.249.84.9 - - [17/Apr/2018:09:55:21 +0000] "GET /assets/src/client/chats/messages.js?v=7uii96pf4j3 HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Search Console) Chrome/41.0.2272.118 Safari/537.36"
66.249.84.7 - - [17/Apr/2018:09:55:21 +0000] "GET /assets/src/client/chats/recent.js?v=7uii96pf4j3 HTTP/1.1" 200 1009 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Search Console) Chrome/41.0.2272.118 Safari/537.36"
66.249.84.11 - - [17/Apr/2018:09:55:21 +0000] "GET /assets/src/client/chats/search.js?v=7uii96pf4j3 HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Search Console) Chrome/41.0.2272.118 Safari/537.36"
2018-04-17T09:55:23.037Z [15944] - warn: Route requested but not found: /user/
66.249.79.75 - - [17/Apr/2018:09:55:23 +0000] "GET /user/ HTTP/1.1" 404 - "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

**Comment by julianlam** [comment]
Sounds like perhaps spiders aren't allowed in via your category permissions. Can you double-check this in Manage -> Privileges?

**Comment by ishwinder** [comment]
Yups, this was the issue .. Never knew about this setting in admin panel. Thanks a lot for helping !!
