### ISSUE TITLE
NodeBB keeps losing connection

### ISSUE THREAD

**Issue by Telokis** [NodeBB/NodeBB#5537]
* NodeBB version is tag "v1.4.5" from the Releases
* Redis 3.2 (same issue with mongo, however)
* Exact steps to cause this issue
    1. Launch NodeBB
* What you expected
    * No error message
* What happened instead
    * Connection lost
    * Lot of console error messages
  `Failed to load resource: the server responded with a status of 400 (Bad Request)`
  `GET http://myserver/socket.io/?EIO=3&transport=polling&t=xxxxx 400 (Bad Request)`

Thank you!

**Comment by labs00** [comment]
I have met the same problem,  don't know why

**Comment by Telokis** [comment]
@labs00 Which version did you try ?

**Comment by pitaj** [comment]
Do you have a reverse proxy? What's your nodebb config? Redact any sensitive information.

**Comment by Telokis** [comment]
I tried on my dedicated server through a container image I made (https://hub.docker.com/r/ninetainedo/nodebb/).

I don't think I have a reverse proxy, how could I know?

My config is nothing special, almost default one but `redis` as db host since it is another container.
However, I have all ports blocked on my computer except those that I explicitly allow. This may be the issue ?
I only expose port 4567 from the container.

**Comment by Telokis** [comment]
Do I need any port/protocol except 4567/tcp ? Now I have a reverse proxy setup and nothing has changed at all. Seems like websocket doesn't work at all.

**Comment by Telokis** [comment]
I just tried to run the same container on my windows computer and I have the exact same issue. But this time there is no firewall or whatever so I think the issue is elsewhere.
Maybe the problem comes from the container itself but it seems kinda strange I think.

**Comment by mrrinot** [comment]
Same problem unfortunatly :/

**Comment by julianlam** [comment]
Have you tried changing `socket.io:origins` setting in `config.json` to `*:*`?

This is a temporary step to aid in debugging... if it doesn't change anything, revert the change.

**Comment by Telokis** [comment]
@julianlam  Alright, thanks to your indication, I managed to fix the issue.
Setting `socket.io:origins` didn't change anything but I noticed the `url` parameter pointing to `localhost`.
I changed it to be `https://mydomain.com` and now it is working.

I have a last question before closing this issue : is there a parameter I could pass to `url` so that it would forever work no matter what domain I am using ?

**Comment by pitaj** [comment]
Can you give an example?

**Comment by Telokis** [comment]
Well, let's say tomorrow I change my domain from `example.com` to `hello.com`, would I have to update `url` in the config?
If I do, is there a way to pass something like `*` so that any domain will match?

By the way, do I need to open any port in order for NodeBB to send verification emails? I don't seem to receive mine.

**Comment by pitaj** [comment]
> Well, let's say tomorrow I change my domain from `example.com` to `hello.com`, would I have to update `url` in the config?

Yes
> If I do, is there a way to pass something like `*` so that any domain will match?

No, and for security reasons you shouldn't anyways.

> do I need to open any port in order for NodeBB to send verification emails

I'm not sure. I'm don't know much about sendmail or email in general, but I'd imagine it's most likely being caught by your spam filter. If not, maybe search "sendmail ports". Assuming you're not using a plugin mail provider.

**Comment by Telokis** [comment]
Alright, thank you for the answers regarding `url`. I'll update it if it happens, it's not that bad.

About the mailing system, do I have to configure anything in the admin panel in order to be able to send mails? I'm not using a plugin or anything. Just the default "verification mail" option.
