### ISSUE TITLE
Japanese ACP translations broken

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#5538]
![image](https://cloud.githubusercontent.com/assets/803701/24135656/b31c5bae-0dd0-11e7-9391-f2d53702e8c2.png)

Appears to be due to this invalid HTML in `public\language\ja\admin\menu.json`

    "search.search-forum": "フォーラムで<strong></ strong>を検索",

**Comment by julianlam** [comment]
👋  @pitaj please confirm

**Comment by pitaj** [comment]
That should fix it, but I think the translation is still wrong.
