### ISSUE TITLE
JS stops working because of non escaped quote

### ISSUE THREAD

**Issue by An-dz** [NodeBB/NodeBB#5545]
* NodeBB v1.4.5 (d19e59f)
* Database: redis 3.2.8
* Exact steps to cause this issue
    1. Login as admin and open the admin panel
    2. Open Settings->Cookies
    3. Write one or several single quotes in the acceptance message
* What you expected
    * The site continues to work
* What happened instead
    * JS stopped working

The text is used un-escaped in the JS front so the `var config = JSON.parse('*')` line obviously stops working. I had to manually edit the value on the database to be able to get NodeBB working again.

**Comment by pitaj** [comment]
By "JS stops working", do you mean that there's a NodeBB error on startup? You aren't talking about a client-side error, correct?

**Comment by julianlam** [comment]
He means client-side. Repro'd, will fix shortly.

**Comment by An-dz** [comment]
That was fast. 👍 Great job.
