### ISSUE TITLE
Verification email never received

### ISSUE THREAD

**Issue by Telokis** [NodeBB/NodeBB#5546]
Using NodeBB v1.4.5 from the releases, I turned on the email verification option and tried to create a new account.
But the mail never arrived to my mail box.
Since I am behind a reverse proxy and inside a containerized version, I am wondering if there is some port I need to open or some additional configuration in order for the mails to be properly sent.

**Comment by pichalite** [comment]
NodeBB can't send emails on it's own. You need to either have sendmail configured to handle the emails or have a emailer plugin installed.

**Comment by julianlam** [comment]
As @pichalite says, we rely on system provided `sendmail` executable by default, but prefer use of third-party emailers like SendGrid or MailGun as they have better deliverability/reputation than a self-hosted box (which has no reputation at all).

**Comment by pitaj** [comment]
By default NodeBB should be able to send emails on a generic Linux server. If you have an Ubuntu VM, most likely it will work out of the box, since sendmail is part of the distro.

Check the NodeBB log and look for errors involving `sendmail`

**Comment by Telokis** [comment]
Would installing `nodebb-plugin-emailer-sendgrid` be enough?

I have an error with sendmail: `Error: spawn sendmail ENOENT`

**Comment by julianlam** [comment]
https://holarails.wordpress.com/2013/11/17/configure-sendmail-in-ubuntu-12-04-and-make-it-fast/

**Comment by Telokis** [comment]
Alright I've tried to setup sendmail but it doesn't seem to work.
Will it work out of the box if I use a plugin instead ?
