### ISSUE TITLE
Missing translation for "admin/settings/general:outgoing-links.whitelist" for non-english languages

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5547]
Tested on latest master.
Transifex isn't updated yet...

**Comment by julianlam** [comment]
@pitaj and what is @nodebb-misty going to do 😆

**Comment by pitaj** [comment]
Should make Misty automatically update transifex when assigned to an issue

**Comment by julianlam** [comment]
Latest source strings pushed to Transifex.
