### ISSUE TITLE
Urgent: NodeBB site won't load, upgrade fails on error

### ISSUE THREAD

**Issue by btw6391** [NodeBB/NodeBB#5548]
This morning I was updating a plugin when my NodeBB site crashed. I ran NodeBB in development mode but didn't notice any errors. I uninstalled the plugin anyways and ran again with no errors but the site still fails to load.

I tried upgrading NodeBB to see if that would bring a fix and was met with this error-

```
24/3 17:41:36 [22700] - error: [meta/js] Could not compile nodebb.min.js: SyntaxError: Unexpected character '`'
24/3 17:41:36 [22700] - error: Build failed: Error: SyntaxError: Unexpected character '`'
    at ChildProcess.<anonymous> (/var/www/nodebb/src/meta/js.js:268:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:689:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

Anyone experienced something like this before?

**Comment by pitaj** [comment]
Try disabling all plugins

**Comment by btw6391** [comment]
@pitaj Thank you! When I initially ran `./nodebb reset -p` it got the site back up and running but when I clicked on my admin link, it crashed again.

I had to then re-run `./nodebb reset -p` along with `./nodebb upgrade` which seems to have done the trick... Surprised this was all caused by a bad plugin.
