### ISSUE TITLE
Themes don't apply

### ISSUE THREAD

**Issue by tenten8401** [NodeBB/NodeBB#5553]
* NodeBB version and git hash:
v1.4.5 / d19e59f1e13f4a22eb44d5334b2a81d99e030b36
* Database
Mongo 3.2.12
* Exact steps to cause this issue
1. Download  theme using npm (I'm using `npm install nodebb-theme-material`)
2. Select theme in Appearance > Themes
3. Restart NodeBB
* What you expected
   Expected the theme to apply properly
* What happened instead
   I'm being greeted with the default theme, not working even when clearing cache.

**Comment by pitaj** [comment]
Have you tried running `./nodebb build`? and were there any errors? It's possible that the material theme you installed is incompatible with your version of NodeBB.

**Comment by tenten8401** [comment]
It turns out I needed to start it up in developer mode to actually get it to work properly, along with half of the other extensions that I thought were just broken. Strange.
