### ISSUE TITLE
How to get user's (has logged in) uid or email?

### ISSUE THREAD

**Issue by a632079** [NodeBB/NodeBB#5555]
I found that sso-github and sso-google are using email what comes from oauth api.
However,This API can't get email address.so,I can't let this plugin use profiles to bind user.
Could you tell me whether some apis is exist(e.g. if you logged in,you can get your email or uid).

**Comment by a632079** [comment]
![0_1490613912244_20170327192329.png](https://i.imgur.com/bwsjPVe.png) 
This API can't provide user's email.
Like PHP BBS,it will provide a variable to save user's profile(include uid,email).
I want to know how to get user's (has logged in) uid or email.

**Comment by psychobunny** [comment]
Maybe this can be useful:

https://github.com/julianlam/nodebb-plugin-sso-twitter/blob/master/library.js

Twitter doesn't expose email addresses either, and we also have logic to link your existing account to it as well.

Going to close as these questions are best suited for our community, please post there if you have additional questions: https://community.nodebb.org/
