### ISSUE TITLE
filter:post.get hook not fired for the preview

### ISSUE THREAD

**Issue by Telokis** [NodeBB/NodeBB#5564]
I'd like to make a plugin that filters what users see on posts so I need to hook into `filter:post.get` and `filter:post.getPosts` but neither of those is fired when I'm on the homepage of the forum even though there is the preview of the topic available for users to read.
I'd really like to alter this preview and PitaJ said that this might be a bug.

**Comment by pichalite** [comment]
@Telokis post previews on the categories page are called teasers. You will want to use the filter `filter:teasers.get` for them. `filter:post.get` is not fired for teasers.

**Comment by pitaj** [comment]
Unfortunately, `filter:teasers.get` does not provide a `uid` in the callback, unlike `filter:post.getPosts`

**Comment by pichalite** [comment]
@pitaj Check again... it does provide uid.

**Comment by pitaj** [comment]
Not the requesting `uid`. I'm looking at it right now.

https://github.com/NodeBB/NodeBB/blob/master/src/topics/teaser.js#L97

**Comment by pichalite** [comment]
well then adding the requesting `uid` to the filter should be enough.

**Comment by Telokis** [comment]
By the way, is there an universal solution to get the current user infos from any hook in a plugin?
I saw [this pull request](https://github.com/NodeBB/NodeBB/pull/4162) about cls to retrieve the current user but, as of 1.4.5, it doesn't work anymore. Any alternative?

**Comment by pitaj** [comment]
@telokis nope. I wish.

**Comment by pitaj** [comment]
`uid` added in 8119b8c4ae3b7ca52c38f6b8b5080b8658880506
