### ISSUE TITLE
Re-design moderation assignment flow

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5569]
It has been brought to our attention (multiple times, really) that our workflow for assigning moderator, global moderator, and administrative roles is highly confusing (This may be an understatement).

The current flows are:
* Grant Admin:
    * ACP -> Manage -> Users -> Make Admin, **OR**
    * ACP -> Manage -> Groups -> Administrators -> Add user to group
* Grant Global Mod: ACP -> Manage -> Groups -> Global Moderators -> Add user to group
* Grant Moderator: ACP -> Manage -> Categories -> Privileges -> Find user -> Add moderate bit

😬 

----

The proposed solution would be a single page abstraction showing all **current** admins, global mods, and mods, and allowing new users to be added to this page.

Only admins can access this page, and only **users** can be granted various roles. For reasons outside the scope of this issue, you can grant groups the moderate bit, but that use case is far and few between and is likely to cause even more confusion if added here.

The existing flows will still work (as they are a direct representation of how they are managed in the backend), so this page is merely an abstrated (and nice looking) front-end.

**Comment by pitaj** [comment]
Maybe this is an opportunity to change the global moderation permission from a single group to an actual permission, and to instead implement this page as a "global permissions" page.

**Comment by julianlam** [comment]
That works for me... with an upgrade script it wouldn't be breaking either.

**Comment by pitaj** [comment]
Global permissions:
- Moderate
- Upload images
- Upload files

Not sure if the other permissions should be global. It may be best to just make every permission a global permission. Not every global permission would be a local permission.

**Comment by barisusakli** [comment]
Chat should be a global permission as well 👼

**Comment by julianlam** [comment]
Ban could also be a good privilege to expose.

**Comment by nomisum** [comment]
what about a permission to add/remove guys from [certain] groups?

(this is actually an use case for us, because we have fixed groups and add people manually)
