### ISSUE TITLE
drag pictures and upload in editor doesn't work

### ISSUE THREAD

**Issue by isLishude** [NodeBB/NodeBB#5581]
version: 1.4.5

my old nodebb version like 1.2.0 can drag pictures to editor,but current version doesn't support.

Should I install any plugins?

thx!

**Comment by pitaj** [comment]
Are there any errors in the browser console or the NodeBB log?

**Comment by isLishude** [comment]
@pitaj  no errors,when drag pics to editor,chrome will open the pic in this tab and will not upload pic.

**Comment by isLishude** [comment]
@pitaj previous when open editor  ,the editor will pop up from below,and now just open editor in new window

**Comment by pitaj** [comment]
Do you have the **Use a separate route for the composer** setting enabled? It's on the _ACP -> Plugins -> Composer_ page

**Comment by isLishude** [comment]
just now I close separate route,and create new topic,the console reports this error
```
TypeError: Cannot read property 'indexOf' of undefined
    at c (nodebb.min.js?v=kjd0aao10g8:13)
    at Object.i.initialize (nodebb.min.js?v=kjd0aao10g8:13)
    at nodebb.min.js?v=kjd0aao10g8:12
    at nodebb.min.js?v=kjd0aao10g8:15
```

**Comment by isLishude** [comment]
@pitaj  I solved this , because of many useless plugins,just now i uninstall them.

thx a lot!
