### ISSUE TITLE
Running an upgrade should also append its output to logs

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5584]
When running `./nodebb upgrade`, the output should also append to `logs/output.log` just as it does for `./nodebb start`. These logs can be viewed by running `./nodebb log`.

Good for beginners, feel free to ask here for tips on getting started.

**Comment by asamolion** [comment]
Hi @psychobunny,

I'm interested in doing this. Can you point me in the right direction?

**Comment by mani9896** [comment]
Hey I am a newbie, and would like to contribute in fixing this problem.  A little guidance would be appreciated

**Comment by Saksham-1612** [comment]
Hey I am a newbie can i contribute to this problem.

**Comment by pitaj** [comment]
@Saksham-1612 Hi! We're always open to contributions. Let me know if you have any questions.

**Comment by Noothan-am** [comment]
hey @psychobunny, is this issue still open can i get more details?

**Comment by shadow0500** [comment]
@psychobunny To enhance the logging capabilities of your NodeBB installation, you can consider using a logging library such as Winston or Bunyan. These libraries provide more advanced features such as log rotation, log levels, and customizable log formats.

To use a logging library, you can install it using npm and then update your NodeBB configuration to use the library. Once configured, your NodeBB application will use the logging library to generate logs.

Additionally, you can also consider using a logging service such as Papertrail or Loggly to centralize your logs and make it easier to search and analyze them. These services provide features such as real-time log streaming, search filters, and alerts.

**Comment by ssy2306** [comment]
Hey, I would like to contribute to the #5584

**Comment by neha-gunta** [comment]
Is the issue still open?

**Comment by julianlam** [comment]
If you can fix it, open a pull request 👌

**Comment by neha-gunta** [comment]
By output, do we mean the console.log output? If yes, So is the task about logging them using the winston logger?
If no, can you please elaborate on the output part. TIA!

**Comment by julianlam** [comment]
There is existing logic that takes stdout and stderr and redirects them to output.log. you would probably want to remove that in favor of the Winston configuration.
