### ISSUE TITLE
Strange thread-breaking poison payload

### ISSUE THREAD

**Issue by yamikuronue** [NodeBB/NodeBB#5588]
We discovered, quite by accident, that the string `('[[notifications:whaaargarbl,')` (or any similar) will break the text for the buttons for an entire page of the thread. Subsequently exiting and re-entering the thread will reveal the same breakage **if and only if** the poison payload is on the DOM; wrapping to another page or entering with infiniscroll low enough that it does not display reverts the buttons to normal. In infiniscroll mode, scrolling back up to see the poison payload again will break that post and any above it (as they stream in), but scrolling back down to the bottom and observing a post streaming in there does not break (probably because the payload is no longer on the DOM). Navigation to other threads reveals them to be fine (unless some jerk posted the payload there too ;) )

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1219256/24978642/6a3618a4-1f9f-11e7-9668-2df65a72393e.png)

**Comment by julianlam** [comment]
Pending confirmation this bug is now blocking v1.5.0 release.

**Comment by yamikuronue** [comment]
You may want to drop by, by the way.... our users have gone off the rails :)

**Comment by yamikuronue** [comment]
So another one was found:  a certain payload makes posts after it not appear. I believe it is `[[a:a,`. Posting `]]` will end the effect.

**Comment by yamikuronue** [comment]
Oh god it works in the thread list we're doomed

**Comment by pitaj** [comment]
Sssh bb is ok

**Comment by yamikuronue** [comment]
My forum is on fire, we're all dying of laughter over here XD

**Comment by pitaj** [comment]
The reason this happens is because `[[abc.xyz, arg1, arg2]]` is the token for a translation. You might try adding `nodebb-plugin-beep` and adding `[[` to the list of censored words. 

ONLY AS A VERY TEMPORARY SOLUTION.

After a restart, this should re-render `[[` as `**` so the translator won't get confused. I'll fix this issue in full tonight.

**Comment by yamikuronue** [comment]
They turned the whole page red by interrupting a code block with the opener such that the codeblock is never closed. It's weirdly pretty :) 

![image](https://cloud.githubusercontent.com/assets/1219256/24981036/d541a934-1fa8-11e7-83bd-52fc42b65e63.png)

**Comment by RaceProUK** [comment]
I uh… kinda spectacularly broke the topic list testing this 😊

Glad to see a fix is on its way 😄

**Comment by yamikuronue** [comment]
Is this fix causing this issue for me? 

![image](https://cloud.githubusercontent.com/assets/1219256/25005103/84f48c3a-2025-11e7-8bf5-107813abe5bb.png)

**Comment by pauljherring** [comment]
en-x-pirate:
![image](https://cloud.githubusercontent.com/assets/3939886/25005422/d9cbbf14-2050-11e7-983d-bea3c2a93437.png)

en-GB:

![image](https://cloud.githubusercontent.com/assets/3939886/25005451/eedcef72-2050-11e7-8571-6c31e5790e49.png)

**Comment by yamikuronue** [comment]
For context, here's an old screenshot of what it looked like before the fix was applied, so you can sort out what's new and what's an existing bug:

![image](https://cloud.githubusercontent.com/assets/1219256/25005822/6a093986-2028-11e7-9b97-d54746980b2b.png)

**Comment by pitaj** [comment]
I did change it so the whole thing shows up when there are arguments to the token. You get more information that way. I could change it so it doesn't show the brackets though.

**Comment by yamikuronue** [comment]
But now we just have weird brackets... and also, the fix doesn't seem complete, because I'm still seeing red text on certain sandbox threads after the fix was applied. I'm not quite sure how they're doing it though.

**Comment by pitaj** [comment]
Ya o noticed that the brackets show up facing the wrong way, I'll probably just remove them.
