### ISSUE TITLE
Script injection into topic titles

### ISSUE THREAD

**Issue by RaceProUK** [NodeBB/NodeBB#5592]
This is a sort of follow-on from issue #5588

Because the translator runs on topic titles, it's possible to inject script that an unsuspecting user might click.

Example: `[[global:404.message, javascript:alert('EVIL!);//]]`

The translator replaces that title with the text `You seem to have stumbled upon a page that does not exist. Return to the home page.`, and the link is set to the JS snippet (the `//` is to swallow the trailing slash that may get appended).

It's also possible to inject malicious URLs this way, which is probably the greater worry.

**Comment by RaceProUK** [comment]
Additional info: We already have the fix for #5588 installed.

**Comment by julianlam** [comment]
Is this a regression caused by the fix?

**Comment by RaceProUK** [comment]
Honestly, I'm not sure: I never tried it before the fix was applied

**Comment by RaceProUK** [comment]
Also, this can be done with post bodies too, it's just been confirmed.
