### ISSUE TITLE
ACP dashboard chart shows incorrect data

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#5606]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash
   latest master  b33d25b0b8f512b9244898bae9c22b9f8683b6d2
* Database (mongo or redis) and it's version.
   Mongo v3.2.1
* Exact steps to cause this issue
    1. Go to ACP -> Dashboard
    2. Click on "Page views This Month" link below the forum traffic chart.
* What you expected
    * Expected to see traffic data for this month. (Should see April 2017 data today)
* What happened instead
    * Chart displays data for last 30 days instead of the current month's data

* Exact steps to cause this issue
    1. Go to ACP -> Dashboard
    2. Click on "Page views Last Month" link below the forum traffic chart.
* What you expected
    * Expected to see traffic data for last month. (Should see March 2017 data today)
* What happened instead
    * Chart displays data for 30 days before the last 30 days instead of last month's data

**Comment by barisusakli** [comment]
I guess the chart should show from the first day of month instead of starting at today - 30days

**Comment by pichalite** [comment]
Yes.

**Comment by julianlam** [comment]
Since we have a date picker now, I changed it to be "Last 7 days" and "Last 30 days".

**Comment by pichalite** [comment]
This is not fixed. Tried on latest master. Count on chart doesn't match number shown below the chart. 

<img width="843" alt="screen shot 2017-05-13 at 10 23 25 pm" src="https://cloud.githubusercontent.com/assets/10014774/26031504/fd77dabe-382a-11e7-8df0-572c72607968.png">

**Comment by julianlam** [comment]
@pichalite Did I squash it this time? 😄
