### ISSUE TITLE
Need Requester UID In 'filter:post.get' Hook

### ISSUE THREAD

**Issue by GenesisX** [NodeBB/NodeBB#5610]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
73d934f5ae039e7845df0dd84a89d7b48e5c645d
* Database (mongo or redis) and it's version.
Redis server v=3.2.8

Need to access requester uid inside [filter:post.get](https://github.com/NodeBB/NodeBB/blob/master/src/posts/create.js#L104) hook, which will be similar to [filter:post.getPosts](https://github.com/NodeBB/NodeBB/blob/master/src/posts.js#L68)

**Comment by julianlam** [comment]
@barisusakli this should be modified to take a single data argument I suppose?
