### ISSUE TITLE
"Invalid data" message when upvoting

### ISSUE THREAD

**Issue by machado2** [NodeBB/NodeBB#5613]
When I upvote stuff I get the "invalid data" box on the instance on what.thedailywtf.com. (don't know about version, only that the database is mongodb)

Seen it only on my phone with an unreliable internet connection, but frequently.

**Comment by barisusakli** [comment]
Can't repro on  our env.

**Comment by machado2** [comment]
There is another user complaining about this here:

https://what.thedailywtf.com/topic/17088/in-other-news-today/3413

Does it count as confirmation?
