### ISSUE TITLE
Error: localStorage behaved unexpectedly

### ISSUE THREAD

**Issue by giangnm** [NodeBB/NodeBB#5622]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.4.6 and git hash fa13e9acc0bf6412dd506b5bb1e0991a1bf415b2
* Database redis.
* I have installed fresh version of NodeBB, it's run well on browser but got this error in console:

![image](https://cloud.githubusercontent.com/assets/3450836/25312209/a6e89d02-283d-11e7-9075-0b0e57675f2e.png)

Does anyone faced this and how to fix it?

Thank you!

**Comment by pitaj** [comment]
What browser are you using? What version? Do you have cookies disabled?

**Comment by pitaj** [comment]
Never mind, I was able to repro

**Comment by giangnm** [comment]
Pulled master, re-build, restart, the error has gone. Thank you.
