### ISSUE TITLE
Blank log file when running loader.js manually

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5623]
Not sure if this is the right place to post this...
Somewhat related #5498 
In the docs for nodebb installation you set up a systemd service in order to automatically restart nodebb in case of a crash.
The basic command used to start nodebb is something like this: `node loader.js`
For whatever reason this method of starting nodebb prevents nodebb from writing to the log file and therefore displaying it in the ACP.
Bri from the nodebb community forum came up with a [workaround](https://community.nodebb.org/topic/10575/empty-log/4) for this but it's not the best solution.

**Comment by julianlam** [comment]
That's sort of to be expected... log file output is not enabled if you use `--no-silent` flag, as it is then output to stdout.

You're supposed to use `journalctl` to look at the logs, no?

Keep in mind I'm not really a fan of journalctl, but that's what there is with systemd 😆
