### ISSUE TITLE
Small Default avatars on 1.4.6 

### ISSUE THREAD

**Issue by brickcap** [NodeBB/NodeBB#5625]
Please include the following information when submitting a bug report/issue:

* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory) -- 1.4.6 (5f634518c980518ac265faac66fd46a823e58e8c)
* Database (mongo or redis) and it's version: mongodb
* Exact steps to cause this issue
    Default Avatars look weired (see the attached screenshots for the comparision)
* What you expected
     I expected the Avtars without profile pictures to look as they did in prior versions
* What happened instead
     Instead nodebb made them smaller
![1 4 4](https://cloud.githubusercontent.com/assets/2066516/25332909/dc88a7cc-2905-11e7-820e-2f0b297d5481.png)
![1 4 6](https://cloud.githubusercontent.com/assets/2066516/25332910/dc8ad88a-2905-11e7-8fb8-fc860928bfe5.png)

 

Thank you!

**Comment by andy1247008998** [comment]
It's very likely caused by nodebb-theme-persona.

BTW: Have you tried deleting and purging posts with this theme?
I cannot purge posts. It says "Invalid date".

**Comment by brickcap** [comment]
@andy1247008998 good idea. I was looking for a fix in css but let me try to change to a different theme first and see what comes out of it. Thanks for the suggestion!

**Comment by margussipria** [comment]
I have this same problem, changing theme didn't help. Problem is only at profile page. Uploaded avatars does not have this problem.

**Comment by brickcap** [comment]
Thanks!!
