### ISSUE TITLE
Allow full SMTP configuration from ACP

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#5628]
Hi!

Currently we can't configure directly our mailserver, we can use only gmail natively, but with small modifications you can provide a better mail support:

You can add the server/port fields to the ACP then we can set our cutsom POP/IMAP/SMTP informations.

Currently some plugin exists, but this should be supported natively, like any other CMS.

Thank you!

**Comment by julianlam** [comment]
The default mail behaviour is the _fallback_, that is, sending using sendmail. Gmail routing works in some cases, but not all.

However, if you want full SMTP setup, you can definitely still use plugin-emailer-local. That should be compatible with latest version of NodeBB... and if not, please do let us know so we can take a look.

Thanks!

**Comment by antoine-pous** [comment]
Did you read the ticket?
