### ISSUE TITLE
Notification is loading forever

### ISSUE THREAD

**Issue by livoras** [NodeBB/NodeBB#5629]
git hash: fb2f857af2be85971f9a2d83c5458176b174c604
Mongo: MongoDB shell version v3.4.1
NodeJS: v7.8.0

![image](https://cloud.githubusercontent.com/assets/6436132/25443205/b7fe5a20-2ad9-11e7-8ff3-8a5082402bc0.png)

It's just loading forever and there're no any error messages.

**Comment by julianlam** [comment]
the >>>>>>> is concerning. Are you on a custom theme?

**Comment by livoras** [comment]
@julianlam It's just a post's content below the popup.

**Comment by livoras** [comment]
@julianlam I deleted the whole database and reset the whole project. This issue stays still. I want to post the lasted screenshot, but it seems github has some problems with uploading files...I'll post it laster.

**Comment by livoras** [comment]
![image](https://cloud.githubusercontent.com/assets/6436132/25444556/288c45fa-2ade-11e7-810f-2b195bb48926.png)

**Comment by pitaj** [comment]
Just to confirm: Any there zero error messages server side or in your browser?

**Comment by livoras** [comment]
@pitaj No any error messages in the browser and server side.

**Comment by livoras** [comment]
Is there anything wrong with `public/src/modules/notifications.js` file? I add some `console.log` in  it but actually nothing is printed out. No any modules are using it?

**Comment by livoras** [comment]
PS: I am using grunt the start the project.

**Comment by pitaj** [comment]
Can you try running `./nodebb build` then `./nodebb dev` and see if the same issue occurs?

**Comment by livoras** [comment]
Yes, it still occurs and no errors during these processes or running.

**Comment by pitaj** [comment]
Have you tried switching to `en-GB`?

**Comment by julianlam** [comment]
I can't reproduce either on zh-TW...

![image](https://cloud.githubusercontent.com/assets/923011/25450574/4d1b9aac-2a8d-11e7-80bc-3dff8231319e.png)

**Comment by julianlam** [comment]
Checked out that commit on `v1.x.x` branch, ran `yarn` on directory with no `node_modules/`, still cannot reproduce

**Comment by pitaj** [comment]
I'm also unable to repro

**Comment by livoras** [comment]
I deleted the `node_modules` and re-installed all the modules and it worked...Thanks @julianlam @pitaj  for replying and sorry for bothering.
