### ISSUE TITLE
user.getSettings seem not efficient

### ISSUE THREAD

**Issue by topm01** [NodeBB/NodeBB#5634]
Hi all,

I just see user.getSettings used a lot in nodebb, but it seem not so  efficient 
because every time it call, it will have to read database
but "user setting object" already read at start point like controller part..
if pass setting object to the follow sequence  ,will it be a good soluation ?
thanks!!

**Comment by pitaj** [comment]
It's possible to add a caching mechanism for user settings as well as many other DB calls, but it may not be worth it. Databases are pretty fast and usually not much of a bottleneck.

**Comment by topm01** [comment]
hi thanks for your reply!!
as my experience in develop php mysql web application
a lot of time we have  to face the database bottleneck issue..
so php have session object or gloabl oject help us read user information
so is that because mongodb is faster ? 
or only use redis have this  benefits?

thanks you very much!
