### ISSUE TITLE
Avatar's style seems broken.

### ISSUE THREAD

**Issue by livoras** [NodeBB/NodeBB#5635]
git hash: fb2f857
Mongo: MongoDB shell version v3.4.1
NodeJS: v7.8.0

![image](https://cloud.githubusercontent.com/assets/6436132/25522264/d7bb35c0-2c34-11e7-9814-16831e992ed9.png)

**Comment by topm01** [comment]
public/less/generics.less
add
        &.avatar-xl {
                width: 128px;
                height: 128px;
                .user-icon-style(128px, 7.5rem);
        }
may  fit it

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5625
