### ISSUE TITLE
Widgets content not being crawled by Search Engines

### ISSUE THREAD

**Issue by faisalzahid** [NodeBB/NodeBB#5643]
_Copying the details i posted on community https://community.nodebb.org/topic/10578/widgets-content-not-being-crawled-by-search-engines/3_ 

This follows along the lines of https://github.com/NodeBB/NodeBB/issues/1428. For websites that heavily rely on custom widgets and the custom home page, SEO for brand relevant keywords get severely affected because the content is not present in the source code and is loaded after the page load.

E.g this website http://definedictionarymeaning.com doesn't show anything on the home page on the google webmasters tool. The content is loaded via http://definedictionarymeaning.com/api/widgets/render?v=77j2miltru6&locations[]=sidebar&locations[]=footer&locations[]=header&locations[]=content&template=homepage.tpl&url=&isMobile=false afterwords.

* NodeBB v1.4.6.

    **Ideally change widget rendering code so that cold loads renders the widgets server side and ajaxifying renders them client side just like regular pages.**

**Comment by Fiiily** [comment]
C'mon, make them cold load!

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/5817
