### ISSUE TITLE
Text input is treated like number on a plugin settings page

### ISSUE THREAD

**Issue by amargon** [NodeBB/NodeBB#5645]
Hello!

I made a Discord notification plugin that has Webhook ID among other settings.
ID input type is [text](https://github.com/amargon/nodebb-plugin-discord-notification/blob/master/public/templates/admin/plugins/discord-notification.tpl#L7), but when the plugin settings page loads, it treats ID like number and rounds it:

XXXXXXXXXXXXXXX144 –> XXXXXXXXXXXXXXX140
XXXXXXXXXXXXXXX377 –> XXXXXXXXXXXXXXX400

So users get wrong ID saved when they change other notification settings.

There is nothing in my code that converts text to numbers.
It doesn't look like a browser bug.
Webhook ID is stored as text in DB (Mongo).
So…  Could anything be wrong with the standard «Load and display settings» process when it comes to numbers passed as text?

My NodeBB is 1.4.5, Mongo 3.4.2.

**Comment by barisusakli** [comment]
Can you put a console.log  here https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/admin.js#L185-L191 and see if the values passed in to the set method is correct?

**Comment by amargon** [comment]
ID is text, as intended (I removed actual ID and Token for security reasons):

```
May 03 20:18:53 amargon nodebb[18908]: { WebhookID: 'ID',
May 03 20:18:53 amargon nodebb[18908]:   WebhookToken: 'Token',
May 03 20:18:53 amargon nodebb[18908]:   MaxLength: '200',
May 03 20:18:53 amargon nodebb[18908]:   PostCategories: '["20"]',
May 03 20:18:53 amargon nodebb[18908]:   TopicsOnly: 'on' }
```

Actually all the settings are of string type now :) and all «numbers» seem to be converted to actual integers.
Is it intended behaviour?

**Comment by barisusakli** [comment]
So the ID is correct in the set method? Is it also correct in the database? You can check by doing 

`db.objects.find({_key: "settings:<your_plugin_key>"}).pretty();`

If it's not rounded in the db then we can look at what happens when it is being retrieved.

**Comment by amargon** [comment]
Yes, ID is correct in the database too.

**Comment by barisusakli** [comment]
Check if its retrieved correctly here https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/admin.js#L186, and then on the client side. It is probably getting rounded somewhere.

**Comment by amargon** [comment]
Get method returns correct ID.
Is there an example on how to debug Settings.load() client-side?

**Comment by barisusakli** [comment]
console.log here https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/settings.js#L389

**Comment by amargon** [comment]
Ah! Here it gets rounded: https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/settings.js#L464

**Comment by barisusakli** [comment]
That's weird, is the value a string when it goes into json.parse

**Comment by pitaj** [comment]
It appears that your solution would be to put a letter at the beginning of the string to avoid it being cast into a number.

You could prepend an `x` for instance.

**Comment by barisusakli** [comment]
The real question is why is the settings module doing this

```
var value = "12313123123123123123123";
value = JSON.parse(value);
```

**Comment by amargon** [comment]
I’d better use full webhook URL as a workaround instead of separate ID and Token fields.
After all, when you create a webhook in Discord you get an URL, so it will be easier to configure the plugin.

But yes, the real question is why text field becomes integer number :)

**Comment by barisusakli** [comment]
seems like added here to fix multiselect dropdowns https://github.com/NodeBB/NodeBB/commit/d096a639d6d51c02b71c243dc8b1b29f94a73007

**Comment by barisusakli** [comment]
@amargon can you try changing that code to 

```
if (!utils.isNumber(values[key])) {
    values[key] = JSON.parse(values[key]);
}			
```

**Comment by pitaj** [comment]
Or you could try `isFinite` instead of `utils.isNumber`

**Comment by amargon** [comment]
Well, the problem is not in numbers per se.
As it turned out, type conversion is intended behaviour of the Settings.load() method. Discord IDs are just an edge case, because they’re 64-bit integers in all their glory :)

I forked my notification plugin from existing (and pretty old) Slack plugin.
Current NodeBB documentation suggests using sync/persist methods instead of load/save.

If I switch my plugin to current settings framework, will I be able to keep ID as string and still use multiselect dropdowns?
