### ISSUE TITLE
Plugin - Add custom fields to postData

### ISSUE THREAD

**Issue by romeo-nxp** [NodeBB/NodeBB#5646]
* NodeBB version 1.4.6
* Exact steps to cause this issue
    1. First I build a plugin to add a new field(a combobox is same with categories) to composer.
    2. Then, I could save and update this new field successfully with 2 hooks: filter:topic.create and filter:topic.edit.
    3. When I edit the topic which already has my new field(by click Edit in Tools), I don't see that new field in postData object. So my privacy combobox can't set selected item.

My code(the same with categoryList)
```
define('composer/privacyList', function () {
	var privacyList = {};

	privacyList.init = function (postContainer, postData) {
             //alert(JSON.stringify(postData));
             //I want postData has my new field here

             //do more things
        }       
       return privacyList;
}
```

* What you expected
    * How can I set the new field to postData before edit composer appear?
    * What's hook i can use on this case?

Thank you!

**Comment by barisusakli** [comment]
If you are saving your field into the topic it will be available in the topic data and not `postData`.

Go to `/api/topic/3` and you should see your new `field:value` pair there. To access it client side you can do `console.log(ajaxify.data.myCustomField);`
