### ISSUE TITLE
Groups.join error when running setup

### ISSUE THREAD

**Issue by TK20466** [NodeBB/NodeBB#5647]
Hi all,

I'm trying to get NodeBB up and running on the Microsoft Azure Web Apps.  I've created a MongoDB DocumentDB on their portal, and supplied the connection info to the config. I had to make a minor edit to include `?ssl=true`, which may be the cause of this issue.

Below is the requested information.  Any advise on what to look/try next?  

* v1.4.6 latest release, fb2f857
* MongoDB v3.2.0 (Running on Microsoft Azure) in SSL
* Exact steps to cause this issue
    1. Edited `src/database/mongo.js` to add `connString += "?ssl=true";` for Microsoft Azure SSL requirements.
    2. Ran `node app.js --setup`
* What you expected
    * Installation of defaults for database
* What happened instead
    * I receive the following error: 
`3/5 19:08:43 [15880] - error: [groups.join] Could not create new hidden group: Syntax error, incorrect syntax near '43'.`
    * `'43`' is not always the same number when deleting/creating new DB to retry.

Thanks so much for your time!

**Comment by TK20466** [comment]
I installed the same version of MongoDB on my local PC, ran the setup fine, and then copied the DB to the Azure DocumentDB with a dump/restore, and it appears to work fine now.  I can investigate further if the team would like to leave this issue open.

**Comment by barisusakli** [comment]
This error doesn't really help `3/5 19:08:43 [15880] - error: [groups.join] Could not create new hidden group: Syntax error, incorrect syntax near '43'.`

That error points to https://github.com/NodeBB/NodeBB/blob/fb2f857af2be85971f9a2d83c5458176b174c604/src/groups/membership.js#L51

which means there is already a group with that name in the database, was the database empty when you ran setup? You can put in some extra console.logs to retry, but if it works on a empty local database, there isn't much we can do.

**Comment by TK20466** [comment]
The database was, indeed, empty... or at least as far as Azure was suggesting it was a fresh collection and a fresh database.  Since uploading the database copy worked, I'll go ahead and close this issue.  Thanks again for replying :)
