### ISSUE TITLE
Category read/write permissions system

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#565]
Expanding on #148 (wow, are we really at 500+ issues already...):

Categories will be the first to be "limited":
- Whitelist only, default is r/w all
- If a group is added to "read", they can enter and browse posts, but cannot post new topics (or reply to existing topics)
- If a group is added to "write", they can create new topics (and reply to existing topics). They are also automatically added to "read"
- If more than zero groups are in "read", the category becomes inaccessible to everybody except those in the whitelist

**Comment by olivierlambert** [comment]
Hi!

Is this feature will be released in a 0.6.2 soon?

Keep up the good work! :+1:

**Comment by julianlam** [comment]
This feature is already completed

**Comment by olivierlambert** [comment]
Oh sorry. I probably miss it. I think I've got a bug, or I misunderstood the thing: I would like to create a category limited to a certain group (not visible for others). Is it in "Category Permissions"? If yes, I can find any user nor any existing groups.
