### ISSUE TITLE
Uploaded image from mobile has incorrect orientation in desktop view

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#5652]
This is probably some configuration in the jimp module, but here's what I'm seeing:
When I upload an image from my iPhone in portrait mode, the picture has the correct orientation on the phone (Safari), but not on the desktop browser (Chrome). This is due to exif data not being used to re-orient the image (or being ignored?). Jimp [says that this is automatically applied](https://github.com/oliver-moran/jimp/blame/631359a24fd1a42e2720703c766827a6b0727f50/README.md#L102), so is there a custom configuration being used? 

* NodeBB version and git hash: 1.4.6 `fb2f857af2be85971f9a2d83c5458176b174c604`
* Database: Mongo 3.2.13
* Exact steps to cause this issue
    1. I uploaded an image from my iPhone that I had just taken with the camera in portrait mode
* What you expected
    *  I expected the image to be correctly oriented on the phone and desktop versions
* What happened instead
    * Instead, I got a sideways image on the desktop view... and NodeBB set fire to my house

**Comment by barisusakli** [comment]
This happens on images uploaded to posts?

**Comment by pitaj** [comment]
What does the image look like on mobile? Can you provide some screenshots, thanks!

**Comment by bdharrington7** [comment]
@barisusakli yes, uploaded images (right to the server, not to imgur or s3)

Here's what I'm seeing (incorrect orientation): 
![image](https://cloud.githubusercontent.com/assets/4553795/25835077/de035684-3430-11e7-9933-eccd153dd385.png)

And here's the mobile version (correct orientation):
![image](https://cloud.githubusercontent.com/assets/4553795/25835100/165b04e6-3431-11e7-854b-967600944817.png)

When I get the exif data, the original image is reported as having exif data that instructs to rotate 90 CW:
![image](https://cloud.githubusercontent.com/assets/4553795/25835200/a593a67c-3431-11e7-976b-a4bf50e5533e.png)

**Comment by pitaj** [comment]
It's a browser issue, nothing we can really do. 
https://bugs.chromium.org/p/chromium/issues/detail?id=56845

**Comment by bdharrington7** [comment]
Erm, well, there's not *nothing* that can be done. If you read the last comment on that "fixed" bug, the suggestion in [comment 75](https://bugs.chromium.org/p/chromium/issues/detail?id=56845#c75) says the fix would be to process the image according to the exif data (and then strip it out), which is something I was under the impression that Jimp was claiming to do.

**Comment by julianlam** [comment]
@bdharrington7 is right, blaming upstream is not a solution

**Comment by barisusakli** [comment]
@bdharrington7 can you check the uploaded image and see if it has been resized down? We have code in core that resizes images to a smaller version on upload. Maybe this code is stripping the exif data somehow.

**Comment by barisusakli** [comment]
I think this is the case https://github.com/oliver-moran/jimp/issues/89

**Comment by bdharrington7** [comment]
The image was resized, but it appears to have the same exif data. Here's a zip of both the resized image and the image as it was saved on the server. Unfortunately I don't have the original anymore...

https://www.dropbox.com/s/i3pf7ckrnng4u1o/sample.zip?dl=1

**Comment by manolino** [comment]
Check #5892

**Comment by barisusakli** [comment]
Need to confirm if this is fixed with an image that has exif rotation.

**Comment by julianlam** [comment]
@bdharrington7 I took a picture right side up, sideways, and upside down. In all three cases, the exif data reported the following orientation:

`exif:Orientation: 1`

So, I presume jimp handled it correctly and rotated it when parsing.

> ... and NodeBB set fire to my house

As for your house, I'm not sure what to do about that, maybe call your insurance company :fire: :house_with_garden:
