### ISSUE TITLE
ERR value is not a valid float

### ISSUE THREAD

**Issue by Fiiily** [NodeBB/NodeBB#5654]
Running NodeBB v1.4.5 (d19e59f1e13f4a22eb44d5334b2a81d99e030b36) on Redis 3.0.6, viewing some threads results in an "ERR value is not a valid float" error showing on the client's screen. Naturally, I checked the NodeBB logs to see this error:
```
node_redis: Deprecated: The ZADD command contains a "null" argument.
This is converted to a "null" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.

```
I googled around and what do you know- it has to do with something being null. Now, I looked around in my database and saw a bunch of stuff set to null in the purged topics section (which seems pretty normal) so I'm wondering- is this a problem with NodeBB or Redis or me? I didn't do any updates or anything or install any new plugins. Speaking of plugins, here's my list:
```
         - nodebb-plugin-sso-steam-v2
         - nodebb-theme-juicy
         - nodebb-plugin-canned-responses
         - nodebb-plugin-composer-default
         - nodebb-plugin-dbsearch
         - nodebb-plugin-emoji-extended
         - nodebb-plugin-markdown
         - nodebb-plugin-mega-colors
         - nodebb-plugin-mentions
         - nodebb-plugin-soundpack-default
         - nodebb-rewards-essentials
         - nodebb-widget-essentials
         - nodebb-widget-ns-stats
         - nodebb-plugin-emoji-one
         - nodebb-plugin-soundpack-aosp
         - nodebb-plugin-custom-pages
         - nodebb-widget-steamserverstatus
         - nodebb-plugin-cards
         - nodebb-plugin-emoji-static
         - nodebb-plugin-youtube-embed
```
Any clues?

**Comment by barisusakli** [comment]
1.5.0 should address this.
