### ISSUE TITLE
how to use the sendmail service

### ISSUE THREAD

**Issue by ychost** [NodeBB/NodeBB#5672]
i try some email plugins but not work for me ,my centos has alreadly installed sendmail and it work successfully,but i can't use it for nodebb. 
log:
 1 has no email, not sending.

**Comment by bdharrington7** [comment]
Please at least post the plugins you tried and the configurations, as well as the Nodebb version, hash, etc.

Just a side note, setting up email to send from the local machine can be problematic, in the sense that your emails can be sent to spam, etc. A recommended approach is to use one of the email services like sendgrid or mailgun

**Comment by julianlam** [comment]
Yes, we recommend using sendgrid or mandrill plugin. emailer-local will also work to use sendmail service.
