### ISSUE TITLE
Long pause after coming back from disconnected internet

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#5673]
I've seen this for a while, possibly since I deployed NodeBB on a server, but I'm guessing this has something to do with the way websockets falls back to long-polling when the connection is interrupted. 

If I have the forum open in my browser, after waking my computer (so, on my fast home connection), I can see the "new notifications" badge, but when I click on it, it sits loading for at least 5 seconds, and will not show anything no matter how many times I click on the notifications button. If I wait long enough, I get the "Looks like you've been disconnected..." message, and then it takes another couple of seconds to load, and then finally the notifications can load when I click on the notifications icon. 

The errors in my console before some time before I opened dev tools, but before this problem resolved:

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
/socket.io/?EIO=3&transport=polling&t=LlsK4F4&sid=3D3zy8OvCOZXZv3GAACP Failed to load resource: net::ERR_INTERNET_DISCONNECTED
/socket.io/?EIO=3&transport=polling&t=LlsWErH&sid=3D3zy8OvCOZXZv3GAACP Failed to load resource: net::ERR_TIMED_OUT
```

So again I'm pretty sure that this is socket.io behavior. Is there a way to detect focus and "jumpstart" the connection?

* NodeBB version and git hash: 1.4.6, `fb2f857af2be85971f9a2d83c5458176b174c604`
* Database: Mongo 3.2.13

**Comment by pitaj** [comment]
When the socket disconnects, it will poll every couple seconds or so until it reconnects. It's possible to modify this polling interval to make it more instant.

Looks like [these options](https://socket.io/docs/client-api/#manager) will allow this. It's a question of where and how we'll make these settings available.

**Comment by julianlam** [comment]
Looking at [`public/src/sockets.js`](https://github.com/NodeBB/NodeBB/blob/master/public/src/sockets.js#L11-L16), we retry connections [every **1.5 seconds** unless overridden in ACP](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/api.js#L49).

If after [five (5) attempts](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/api.js#L48) (so, 7.5s) there is still no connection, it waits 10 times the delay (15s) and tries again.

Shortening that delay to 5s would not be too bad, and might make NodeBB's reconnection seem a little more responsive.

**Comment by julianlam** [comment]
The thing is, if you're seeing the "new notifications" badge when you first resume your PC, then the socket connection is fine (because as far as I know, we use websockets to report new notifications). Perhaps you're disconnecting for some reason 😬

**Comment by bdharrington7** [comment]
@julianlam so there's a reason that notifications  are present on wake, it's because (I'm pretty sure) macs open a network connection once in a while during sleep, which gives an opportunity for the connection to be reestablished and get those notifications. But if I wake my computer after a longish period of network disconnectivity (?), I encounter this behavior.

I'm pretty sure I've seen the behavior where a web app will do something when the page regains focus, and I know I've seen web apps that do something when focus is *lost*, so the trigger exists, I was just wondering if the socket.io library had the capability to receive a message like "hey, something happened that I know about that you don't, why don't you try to connect again?"

**Comment by barisusakli** [comment]
@bdharrington7 https://github.com/NodeBB/NodeBB/blob/master/public/src/sockets.js#L26-L29

Try lowering the reconnectionDelay in the ACP, right now it seems to wait 1.5 x 10 seconds before trying to reconnect again.
