### ISSUE TITLE
Allow the use of full database uri

### ISSUE THREAD

**Issue by buckle2000** [NodeBB/NodeBB#5674]
NodeBB version 1.5.0

Can we have an optional field
`config.json/database.uri`
that overrides other settings when exists?

So it's easier to support connect strings like
`mongo://un:pw@hostname1,hostname2`

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-english/commit/6618d5af45c3184cd792d2872fba552235e0d722
