### ISSUE TITLE
MongoDB duplicate auth

### ISSUE THREAD

**Issue by buckle2000** [NodeBB/NodeBB#5675]
Who wrote this?
Why do you auth twice?
https://github.com/NodeBB/NodeBB/blob/master/src/database/mongo.js#L106-L113
this should be removed.

Username and password are already included:
https://github.com/NodeBB/NodeBB/blob/master/src/database/mongo.js#L79

This took me a day try to find out what's wrong with my database.

Nevertheless, it is a great project.

**Comment by julianlam** [comment]
`connString` method of connecting to Mongo was added after NodeBB first began supporting MongoDB, hence why there is a separate section for auth.

If the older discrete call to `db.authenticate` is not required, then it should be removed (cc @barisusakli )

**Comment by buckle2000** [comment]
It is not required.
Actually, it causes auth error on my machine connecting to cluster db.

**Comment by barisusakli** [comment]
Seems like we can remove it, if username and password is in config.json they are always passed to the connect method in the connection string.
