### ISSUE TITLE
possible bug in flagging

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5680]
Assuming the below code.

```
//uid 2 is flagging pid 10 and pid 10 is owned by uid 1
var pid = 10;
var uid = 2;
flags.create('post', pid, uid, 'spam', callback);
```

This creates a sorted set entry in the database with the key `'flags:byTargetUid:1'` since pid 10 is owned by uid 1. The value of that entry is the unique `flagId` which is just some some integer, let's say it's 3.

When you visit the /info page of uid 1 there is a [call](https://github.com/NodeBB/NodeBB/blob/master/src/user/info.js#L48) to get flags for that user.

Which goes on to call [`getFlagMetaData`](https://github.com/NodeBB/NodeBB/blob/master/src/user/info.js#L81) this function assumes all values added to `flags:byTargetUid:1` are post ids, but in reality they are flagIds. So what ends up happening is it returns the data for pid 3 instead of pid 10.

**Comment by julianlam** [comment]
Thanks for the thorough triage @barisusakli, you're correct, I was expecting `pids` when I had `flagIds`.
