### ISSUE TITLE
Avatars are not being resized prior to crop 

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#5681]
* NodeBB 1.5.0 (291df36c3db451e79ac555c948ebb09830dad9b5)
* MongoDB 3.4.4
* Exact steps to cause this issue
    1. Edit Profile > Change Picture > Upload New Picture.
    1. Choose a square, large image (much bigger than the allowed avatar size) and click "Upload".
    1. Cropper shows and the maximum dimensions of the cropping frame is equal to the Profile Image Dimension (128 px by default) even though the image has correct aspect ratio and doesn't need any cropping.

* What you expected
    * I expect that I am able to freely choose any square area in the image cropper without any restrictions on the dimensions and scaling down to Profile Image Dimension happens AFTER.
    * Alternatively image should be resized to Profile Image Dimension prior to showing cropper.
* What happened instead
    * Cropper does not allow me to increase cropping area beyond what can be seen on the screenshot below. This forces me to prepare avatar in right (scaled down to 128 px) dimensions before uploading to NodeBB (and makes the cropper feature somewhat useless). See:
![nodebb avatar cropper](https://cloud.githubusercontent.com/assets/591754/26104126/abb109ee-3a3c-11e7-8b9a-e73bb801fce1.png)

PS. I think that was addressed in #1515 but seems like a regression hit when you switched away from ImageMagick

Thank you!

**Comment by barisusakli** [comment]
@attis looks like you can use the mousewheel to zoom out/in with the croppper

**Comment by pitaj** [comment]
We should probably have some kind of explanation for that.

**Comment by barisusakli** [comment]
Yup that modal needs a help text

**Comment by attis** [comment]
@barisusakli Oh my, this actually works! Thanks. I would have never thought of that, which probably means that a help text on this is badly needed.

By the way, even though scrolling with mousewheel does solve my original problem, it still looks kinda weird and ugly:
<img width="616" alt="zrzut ekranu 2017-05-16 o 20 31 13" src="https://cloud.githubusercontent.com/assets/591754/26122300/4dabca92-3a77-11e7-80c1-2ed20bcb5103.png">

All that empty space around does give me a feel that something is not entirely right with that cropper...
Of course the help text would be a good stopgap solution for now, I think.

**Comment by julianlam** [comment]
Yes, definitely need to add help text, I will do it now. This _bug_ caused confusion when I uploaded my avatar with the cropper as well.

**Comment by julianlam** [comment]
Cropper has been updated to zoom a bit better at start. Let me know if this helps.
