### ISSUE TITLE
Cannot access directly to topic without category access

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#5684]
* NodeBB version: 1.4.6 fb2f857af2be85971f9a2d83c5458176b174c604
* Database : Redis 3.2.8
* Exact steps to cause this issue
    1. Create an hidden category
![selection_317](https://cloud.githubusercontent.com/assets/7486600/26151272/56abdd90-3b02-11e7-9c79-6890b028fc3f.png)
    2. Access directly to the topic
* What you expected
    * Accessing to the topic, but cannot browse the category
* What happened instead
    * Cannot read the topic with direct link

Thank you!

**Comment by barisusakli** [comment]
What's the use case here? This is an easy enough fix, but I am wondering why you would like to give access to topics inside a category but disallow access to the category itself.

**Comment by antoine-pous** [comment]
Sometimes we write news/tutorials and we request some members advice during a short time. So a group called `Alpha readers` would access to this ressources if we give a link. But we wont allow them to browse the category.

Before giving the link it could take several days ;)
