### ISSUE TITLE
unable to set pagination options

### ISSUE THREAD

**Issue by tehspaceg** [NodeBB/NodeBB#5685]
* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory)
NodeBB 1.5.0 (hit hash: `972e9a0303e49d17076fcaa3a358a904297981f6`)
* Database (mongo or redis) and it's version.
`Redis server v=3.2.8 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=11aa79fd2425bed9`
* Exact steps to cause this issue
    1. Login to NodeBB
    2. Click the profile icon and select Settings
    3. Enable "Pagination"
    4. Hit Save
    5. Refresh the page and observe that the Pagination option does not stick
    6. Navigate to any long forum post and observe that the option is not enabled
* What you expected
    * The Pagination option saves properly
    * Pagination is enabled
* What happened instead
    * The Pagination option is not saved
    * Pagination is not enabled

**Comment by barisusakli** [comment]
This was fixed here
https://github.com/NodeBB/NodeBB/commit/db532fbb0d8cd237cec461f6498c68a34032a46b (master)
https://github.com/NodeBB/NodeBB/commit/ca0ab7633fcb24c7e31bcb644b2289c503f465a8 (1.5.x)
