### ISSUE TITLE
Regarding New List of Object for User

### ISSUE THREAD

**Issue by dannyweb8** [NodeBB/NodeBB#5691]
Hi Team
I very impressed by NodeBB, Fast, Beautiful and Stable
I have a question that I wanna put an Object called "Business" for User, and one User have many Businesses, 
One Business contains field bellow
Company Name,
Industry,
Story,
Website ...

So do we have any instruction to do that?. I really really need this one to be done.

Thanks
Danny

**Comment by barisusakli** [comment]
Hello, please post these kinds of questions on our community forum. https://community.nodebb.org
