### ISSUE TITLE
WARN: Output exceeds 32000 characters

### ISSUE THREAD

**Issue by andy1247008998** [NodeBB/NodeBB#5695]
Version: 1.5.x

Parsing upgrade scripts... OK | 28 script(s) found
  → [2015/12/23] Chat room hashes...
 skipped
  → [2015/12/15] Upgrading chats...
 skipped
  → [2016/2/25] Social: Post Sharing...
 skipped
  → [2015/12/23] Adding theme to active plugins sorted set...
 skipped
  → [2016/1/14] Creating user best post sorted sets...
 skipped
  → [2016/1/20] Creating users:notvalidated...
 skipped
  → [2016/1/23] Creating Global moderators group...
 skipped
  → [2016/5/28] Giving topics:read privs to any group that was previously allowed to Find & Access Category...
 skipped
  → [2016/4/14] Group title from settings to user profile...
 skipped
  → [2016/6/13] Store upvotes/downvotes separately...
 skipped
  → [2016/4/19] Users post count per tid...
 skipped
  → [2016/4/29] Dismiss flags from deleted topics...
 skipped
  → [2016/8/5] Removing best posts with negative scores...
 skipped
  → [2016/7/12] Giving upload privileges...
 skipped
  → [2016/9/22] Category recent tids...
 skipped
  → [2016/8/7] Granting edit/delete/delete topic on existing categories...
 skipped
  → [2016/10/8] Favourites to Bookmarks...
 skipped
  → [2016/10/14] Sorted sets for post replies...
 skipped
  → [2016/11/22] Update global and user language keys...
 skipped
  → [2016/11/25] Sorted set for pinned topics...
 skipped
  → [2017/2/28] Upgrading config urls to use assets route...
 skipped
  → [2017/2/25] Update global and user sound settings...
 skipped
  → [2017/4/16] Delete accidentally long-lived sessions...
 skipped
  → [2017/4/14] Set default allowed file extensions...
 skipped
  → [2016/12/7] Migrating flags to new schema...
 skipped
  → [2017/3/22] Update moderation notes to zset...
 skipped
  → [2017/2/27] New sorted set posts:votes...
 skipped
  → [2017/4/26] Remove relative_path from uploaded profile cover urls...
 skipped
Upgrade complete!

20/5 17:38:09 [5088] - info: [build] Building javascript
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
20/5 17:38:24 [5088] - info: [build] js => Completed in 14.889s
20/5 17:38:24 [5088] - info: [build] Building client-side CSS

**Comment by julianlam** [comment]
This is a warning from the minifier and can be safely ignored.
