### ISSUE TITLE
Looks like your connection to NodeBB was lost, please wait while we try to reconnect.

### ISSUE THREAD

**Issue by caiya** [NodeBB/NodeBB#5697]
i run the app, and it prompts "Looks like your connection to NodeBB was lost, please wait while we try to reconnect."
what is the matter?
Thank you!

**Comment by julianlam** [comment]
Please direct all configuration questions to our community forum at https://community.nodebb.org, thanks!

**Comment by julianlam** [comment]
(That said, check config.json `url` value.)
