### ISSUE TITLE
New chat messages goes unnoticed on Android

### ISSUE THREAD

**Issue by machado2** [NodeBB/NodeBB#5701]
When you receive a new chat message, there is no notification, and if you don't scroll all the way down in the navigation side bar there is no clue you received it. This happened on TDWTF instance.

**Comment by julianlam** [comment]
Hm that is correct (insomuch that it is a correct interpretation of what is happening)... on desktop we show the chat bubble, but these bubbles are hidden on mobile as there is a lack of screen real estate.

What would be your suggestion here from a design POV?

**Comment by machado2** [comment]
Idea 1: 2 entries (Notifications and Chats) under Unread in the Navigation pane, with a counter bubble, and clicking on them would scroll down to these itens.

Idea 2: Chats could be more attention grabbing, since someone maybe waiting for you to reply. Something on the left side of the hamburguer menu could be appropriate.

Idea 3: Copy facebook messsenger's idea of an overlay avatar notification for chats, that you can drag to another place, or throw out of the screen to dismiss.

**Comment by julianlam** [comment]
Re: idea 2, we already have something left of the hamburger for active notifications, unfortunately.

and idea 3... good lord I hate the chat heads 😬

**Comment by pitaj** [comment]
Another option:

1. Move our existing hamburger to the left side of the screen as is conventional elsewhere.
2. Make a new menu icon thingy on the right side of the screen for only chats
3. Have the unread chats number be on that on instead

Here's a mockup:

![image](https://cloud.githubusercontent.com/assets/803701/26741604/4aca140a-4797-11e7-9fa9-037083b7cfd6.png)

**Comment by julianlam** [comment]
@pitaj How easy is it to swap the menus? Could that be made a toggleable option?

**Comment by pichalite** [comment]
New menu has so many issues now. Better to make it work properly before thinking about toggleable options.

**Comment by julianlam** [comment]
> New menu has so many issues now. 

I'd recommend you open a new issue for any bugs you're seeing regarding the new sidebar menu. It may not be in `master` but it'll still help us track them.

**Comment by pitaj** [comment]
Swapping the menus is easy. The hardest part is probably adding the option in the first place.
