### ISSUE TITLE
Looks like your connection to NodeBB was lost, please wait while we try to reconnect.

### ISSUE THREAD

**Issue by SiriMhM** [NodeBB/NodeBB#5712]
Hi, I am using NodeBB v1.5.x (installed it by using git clone -b v1.5.x https://github.com/NodeBB/NodeBB.git $HOME/nodebb).
My git hash is: 541b0487efaf74949582471ecbe503a023d83236
Database: MongoDb v3.4.4

I followed this installing guide:

https://nodebb.readthedocs.io/en/latest/installing/os/ubuntu.html

1. The installation seems to be fine for me, but I cannot create Threads and so on..
2. I always get the notification:
**Looks like your connection to NodeBB was lost, please wait while we try to reconnect.**

The failing request is:

**https://mydomain-blabla.com/socket.io/?EIO=3&transport=polling&t=LnB7HOV
(400 Bad Request)**

What could that be ? Faux-pas in configuration?

I tried the following for config.json:

```
{
    "url": "https://blabla-blabla.com",
    "secret": "a16778d7-cb95-4b85-954d-487b8b5c3737",
    "database": "mongo",
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "",
        "password": "",
        "database": "nodebb"
    }
}
```

As well I tried:
  `  "url": "https://blabla-blabla.com:PORT",`

and I tried:

`    "url": "https://localhost:PORT",`

`    "url": "localhost:PORT",`

But it always shows the above described error.

**Comment by pitaj** [comment]
Please use https://community.nodebb.org for support when installing. Issues are mainly for bug reports and feature requests.
