### ISSUE TITLE
update nodemailer

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5714]
requires node 6.0+
`Sendmail transport built-in, no need for external transport plugin` so looks like we don't need ` "nodemailer-sendmail-transport": "1.0.0",` anymore

**Comment by pitaj** [comment]
This will require us to drop support for node.js v4, correct? Should this wait until the next major release, then? Possibly v2.0.0?

**Comment by barisusakli** [comment]
Yes this needs to happen when we drop support for nodejs 4. Should group it with other breaking changes like https://github.com/NodeBB/NodeBB/issues/5435.

**Comment by julianlam** [comment]
This can be done now against `develop` if you'd like. Just needs proper milestone.

**Comment by julianlam** [comment]
As we've dropped support for Node.js v4, can you take a look at this again @pitaj ?

**Comment by pitaj** [comment]
It's already done in develop. 23e7222dfa82303e523b85c9a64cc3e694cbea33
