### ISSUE TITLE
use category dropdown for category selection

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5722]
instead of 

![image](https://cloud.githubusercontent.com/assets/2583394/26597556/606f75e2-4540-11e7-9c2c-dc2bca6b22bd.png)

**Comment by pitaj** [comment]
Maybe we could use a bs drop-down instead of a select, though, to keep the colors and icons visible? Make it a component so we can use it in the composer, too. That would be nice

**Comment by julianlam** [comment]
If we are throwing out ideas let's make it searchable too :P
