### ISSUE TITLE
GPL license question

### ISSUE THREAD

**Issue by topm01** [NodeBB/NodeBB#5724]
###  Hi sir,

I just try to use nodebb in my commercial website(Not sell or distribute nodebb)
if i change some of client code in nodebb.min.js did it mean i need to publish my whole nodebb source code in human readable mode ,because GPL will infect it  , it is not good for any commercial  website use it ..
any one know about this ...

**Comment by topm01** [comment]
Is that possible release nodebb clients source nodebb.min.js  etc.. under MIT or BSD ..
then GPL will not infect whole server source  code..

**Comment by pitaj** [comment]
`nodebb.min.js` is generated in the build step of NodeBB (run manually by `./nodebb build`). It is a bundle involving many different module sources. It could very well be that what you're editing is part of an MIT licensed module in which case you don't have to worry.

Whether or not the GPL will cover an editing of compiled NodeBB source files for a commercial use, I cannot say. Consult a lawyer.

**Comment by julianlam** [comment]
As the code is not being redistributed, there is no need to supply the source code.

If you're doing more than hosting your own NodeBB forum, then it gets to be a grey area.

**Comment by topm01** [comment]
thank you sir for your kindly reply..
then i understand!!

**Comment by topm01** [comment]
Sir i just got another question, if i use nodebb in my self hosted  commercial site ,as  author(julianlam ) say it  legal use it without  publish my modifed source code
but if i someday i need to sell my company, what will it result.... (can i sell my company)
