### ISSUE TITLE
Additional actions should trigger event logging

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5729]
Continuation of #5585, the following actions should cause a new event to be logged

* [x] Password change
* [x] Theme change (from both ACP and command line)
* [x] Permanent bans
* [x] Temporary bans
* [x] Username changes
* [ ] Invocation of settingsv1 or settingsv2 (use `text` to show which obj changed! :shipit: )

**Comment by barisusakli** [comment]
password change https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/user/profile.js#L113-L118

**Comment by julianlam** [comment]
Excellent thanks, was just rambling into issue box before I left for the day :smile:

**Comment by julianlam** [comment]
User Bans done https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/user/ban.js#L27-L32
