### ISSUE TITLE
Compress Profile Images

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5730]
I just ran Google PageSpeed Insights on my own website and the [community.nodebb.org Website](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcommunity.nodebb.org) and the results are pretty bad.
A thing that could easily be improved is automatic compression of lossless image formats like png.

**Comment by pitaj** [comment]
A better utility is [Lighthouse](https://developers.google.com/web/tools/lighthouse/), where the results are similarly bad. Some of these issues are due to Facebook buttons and Google analytics, but others are big deals.

**Comment by Radiergummi** [comment]
@pitaj have you looked at https://github.com/lovell/sharp already? It's the most brilliant node.js image editing library I've come across yet.

**Comment by julianlam** [comment]
We use jimp because it has no need for compiled binaries. If sharp is similar​ we can consider it to replace jimp

**Comment by Radiergummi** [comment]
Sharp has no external dependencies, though it brings libvips as a compiled binary. I remember the problems with lwip, so I can understand the resentment, but looking at the benchmarks [here](http://sharp.dimens.io/en/stable/performance/) and my own experience with Sharp, it is blazingly fast. According to their charts, sharp is around 27x faster than jimp.

**Comment by julianlam** [comment]
No objections to having somebody give this a try in a branch and open a PR 😄 

I'm not tied to jimp personally, though it's served us faithfully so ar.

**Comment by julianlam** [comment]
Odd, image resizing [has been working since February](https://github.com/NodeBB/NodeBB/commit/ef90702049a023dc0f0c633879a542691370393e) :wink:
