### ISSUE TITLE
Admin panel : jQuery is not defined

### ISSUE THREAD

**Issue by flexbrane** [NodeBB/NodeBB#5737]
- **NodeBB version:** 1.5.1
- **NodeBB git hash:** e64104786ffdd8471119dc54660c3fc12f3202a1
- **Database type:** redis
- **Database version:** 3.2.9

- **Exact steps to cause this issue:**
	1. `git clone --branch v1.5.1 https://github.com/nodebb/nodebb /nodebb`
	2. `npm install --production`
	3. `npm install <PLUGIN LIST>`
	4. Start Nodebb
	5. Connect as admin

- **What you expected:**
I expected the admin interface work

- **What happened instead:**
Instead, I got `Uncaught ReferenceError: jQuery is not defined` in the developper console.

- **Console in Chrome:**
![image](https://cloud.githubusercontent.com/assets/14235706/26780668/16bc6356-49eb-11e7-99fd-d2cf05fa6462.png)

- **Console in Firefox:**
![image](https://cloud.githubusercontent.com/assets/14235706/26780853/ea67e6e4-49eb-11e7-92a4-a464d74ad7fb.png)

**Comment by julianlam** [comment]
Looks like you didn't  ./nodebb build

**Comment by flexbrane** [comment]
Actually, `./nodebb upgrade` seemed to do it.

I add it, but same problem.

**Comment by flexbrane** [comment]
And all build are complete, according to logs.

**Comment by pitaj** [comment]
What are the contents of nodebb.min.js in the build/public directory?

**Comment by flexbrane** [comment]
I put the content here : https://paste.ee/p/69esp

**Comment by pitaj** [comment]
Do you get 404s when visiting `/assets/nodebb.min.js`

**Comment by pitaj** [comment]
Try running `./nodebb stop && ./nodebb build && ./nodebb start`, and trying again one more time. If it still doesn't work, try disabling plugins with `./nodebb reset -p`

**Comment by flexbrane** [comment]
Indeed, with `./nodebb reset -p` it is working. The problem is caused by a plugin?

**Comment by flexbrane** [comment]
I try to remove and then activate all plugins. Now it is working.

Thank you for your help.
