### ISSUE TITLE
Admin panel: update of NodeBB is not announced in Japanese lang setting

### ISSUE THREAD

**Issue by yosukey** [NodeBB/NodeBB#5738]
NodeBB version: 1.5.0

NodeBB v.1.5.1 has released already, but an announcement for a new version is not displayed in admin panel in Japanese as an attachment image file. When I switch to English mode, I can see the notification for the new version, 1.5.1. 

<img width="430" alt="ss" src="https://cloud.githubusercontent.com/assets/762699/26810462/d7da1018-4aa6-11e7-9f8d-aaa1ce591a76.png">

**Comment by RoiEXLab** [comment]
Just as I expected: The html in the Japanese translation is invalid, it contains too many spaces.
This should be an easy fix...

**Comment by barisusakli** [comment]
This should be fixed on transifex Japanese translation?

**Comment by RoiEXLab** [comment]
@barisusakli Yes, but for me I'm always getting server errors when trying to access the japanese translation...

**Comment by julianlam** [comment]
@yosukey @RoiEXLab Can you confirm this is resolved?
