### ISSUE TITLE
Make app.user globally accessible by templates just like config

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5744]
This is simple to implement, but really needs to be tested properly across all routes that have a `user` object already, just in case.

This is technically breaking, because if a plugin had a `user` object in its API data already, this would override it.

**Comment by julianlam** [comment]
Could the user data just be put inside the template object?

**Comment by julianlam** [comment]
Sorry to interrupt again, but some more stray thoughts:

1. `user` may be used in some routes as either the calling user, or the target user, so that is a source of some confusion
1. Consider saving the user data in `req.session` so as to not repeatedly retrieve user data?

**Comment by pitaj** [comment]
There's already a `uid` value in `config`. Maybe we could just provide `config.user`. Alternatively, we could provide the user object under a different name like `loggedInUser`.

**Comment by julianlam** [comment]
Would personally prefer `tplVals.session.user`

**Comment by pitaj** [comment]
`tplVals`? So you'd write `{tplVals.session.user.username}`? Or are you just saying it should be `{session.user.username}`?

**Comment by julianlam** [comment]
The latter 😁

**Comment by barisusakli** [comment]
all routes have `loggedInUser` starting in 3.0
