### ISSUE TITLE
Invalid csrf token after upgrading to 1.5.1

### ISSUE THREAD

**Issue by btw6391** [NodeBB/NodeBB#5753]
- **NodeBB version:** v1.5.1 (from v1.4.5)
- **NodeBB git hash:** e64104786ffdd8471119dc54660c3fc12f3202a1
- **Database type:** mongo
- **Database version:** v3.4.4
- **Exact steps to cause this issue:**
 Followed the upgrade documentation steps exactly (https://docs.nodebb.org/configuring/upgrade/)
	1. Stopped my forum
	2. Backed up my mongoDB
        3. Ran `git fetch, git checkout v1.5.x, git merge origin/v1.5.x`
        4. Ran `./nodebb upgrade`
        5. Tried to log into my forum and received a "forbidden" page, console log shows `error: /login
 invalid csrf token`

Not sure what went wrong or how to fix it. Seems this used to be an earlier issue but can't find a definitive solution in older posts

**Comment by barisusakli** [comment]
Check the url in config.json to make sure it  matches the url you use to access the forum. Also check your cookieDomain setting in the database.

`db.objects.findOne({_key: "config"}).cookieDomain`

**Comment by btw6391** [comment]
Not sure what exactly I did but the issue is fixed now!
