### ISSUE TITLE
Minor bug in admin/settings/user page. 

### ISSUE THREAD

**Issue by bravominski** [NodeBB/NodeBB#5757]
- **NodeBB version:** 1.5.1
- **NodeBB git hash:** 3fe512d684d4eb8637ede6318741b0ad6ae5d51f

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

While translating to Korean, I realized I cannot really find "# of days invitations expire in." anywhere in actual web page. 
And then realized...
<img width="1283" alt="screen shot 2017-06-14 at 5 00 25 pm" src="https://user-images.githubusercontent.com/9323428/27122133-c3ee2f92-5124-11e7-98ff-2b1bcecfc87b.png">

that something went wrong and the rendering actually showed key, not value in json file.
![screen shot 2017-06-14 at 5 00 34 pm](https://user-images.githubusercontent.com/9323428/27122363-6bb32926-5125-11e7-90b7-178e3c871517.png)

It will be nice if anyone could take a look at this and check.

Thanks :)

**Comment by pitaj** [comment]
You're probably on an older commit that hadn't added translations to those files yet. That's what shows up when the, I guess in your case, `ko` language doesn't have that translation in those files.

**Comment by psychobunny** [comment]
I was just looking this up, looks okay in latest master

**Comment by bravominski** [comment]
got it thanks :)
