### ISSUE TITLE
No sounds

### ISSUE THREAD

**Issue by estebanconstante** [NodeBB/NodeBB#5758]
- **NodeBB version:** 1.5.1
- **NodeBB git hash:** e64104786ffdd8471119dc54660c3fc12f3202a1

- **Database type:** mongo
- **Database version:** 3.4.4

- **Exact steps to cause this issue:**
No sound, didn't know we had sound until I got notifications in the nodeBB official forum.

I don't find a setting to turn on the sounds.

**Comment by psychobunny** [comment]
In the ACP, what does General -> Sounds look like?

**Comment by estebanconstante** [comment]
My bad, it's showing up. I only saw the "Play" button the first time but got blind to the dropdown.
