### ISSUE TITLE
NodeBB start and log in Dockerfile

### ISSUE THREAD

**Issue by yao23** [NodeBB/NodeBB#5759]
- **NodeBB version: 1.5.0** 
- **NodeBB git hash:** 

- **Database type:** mongo
- **Database version: 3.2** 

- **Exact steps to cause this issue: Upload docker image to Google Cloud**

- **What you expected: 200 status code**

- **What happened instead: 502 status code**

I add the following code in Dockerfile, but how to run './nodebb log' after start (ENTRYPOINT is used only once in Dockerfile)

```
#start nodebb
ENTRYPOINT ["./nodebb", "start"]
```

**Comment by BenLubar** [comment]
Here's the Dockerfile we're using at What the Daily WTF: https://github.com/boomzillawtf/tdwtf/blob/master/Dockerfile

All you really need is `CMD ./nodebb upgrade && echo 1 > pidfile && exec node loader.js`

**Comment by julianlam** [comment]
Thanks for helping out @BenLubar -- hope that helps @yao23
