### ISSUE TITLE
Refactor all the code to use ES6 classes/module system

### ISSUE THREAD

**Issue by stevefan1999** [NodeBB/NodeBB#5762]
Let's not use `module.exports` and IIFE/function classes anymore, use `import export` and `class` instead
Yes it will be a 100% API break but it then NodeBB could be modernized.

**Comment by Radiergummi** [comment]
1. Using the new module loader API would require using Babel for the whole code base, just for syntax sugar. Plus, it doesn't allow for dynamic module imports, which is used around the core I think.
2. Using classes won't break API compatibility, after all it's just syntax sugar and produces plain old objects.
3. NodeBB can be modernized without changing the core files to use the latest language features. CommonJS modules will probably supported the next 20 Node.js versions from now, just to keep compatibility with legacy modules.

I agree using classes for some functionality would make it somewhat easier to read, but that's not a necessity nor a high priority issue.

**Comment by psychobunny** [comment]
I'm just closing this because there is no plan to do this anytime soon. Let's talk about it for NodeBB 2.0, and feel free to open a discussion on our community forum :)
