### ISSUE TITLE
Forking a topic does not recalculate existing posts' "replies" zsets/counts

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5766]
- **NodeBB version:** v1.4.2 though I presume this has not been addressed since
- **NodeBB git hash:** 390c0ba7883bf278bb0c969dcbe507bd536661f5

- **Database type:** mongo
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**
1. Create a topic
1. Reply directly to topic so that the OP has "Replies: 1" underneath it
1. Fork out that reply to a new topic
1. Observe that OP still has "Replies: 1" underneath it and clicking it loads the post that is no longer in said topic

- **What you expected:** For "Replies: 1" to disappear

- **What happened instead:** See above.

**Comment by barisusakli** [comment]
This was briefly discussed here https://github.com/NodeBB/NodeBB/pull/5050#issuecomment-249427238 @BenLubar 's reasoning was replies to replies were still working even if the reply was not in the same topic anymore.

**Comment by BenLubar** [comment]
Example of a topic with replies in a different topic:

https://what.thedailywtf.com/topic/19454/nodebb-updates/221

For some reason, each other-topic reply is counted twice (they only show up once, though) and if the last post in a topic has replies, scrolling down causes some weirdness (loading the first few posts of the current topic as replies and eventually removing all posts from the page), but we'd like to keep the ability to reply in a different topic.

**Comment by julianlam** [comment]
Okay fair enough. In my use case, I was forking all posts out of a topic so that OP was left alone, but was surprised when the "replies" link was kept.

Makes sense with explanation however.

**Comment by barisusakli** [comment]
@BenLubar 
>For some reason, each other-topic reply is counted twice (they only show up once, though)
So `pid:1:replies` has 3 posts but the count shows 6? 

I am trying to figure out why that happens. https://github.com/NodeBB/NodeBB/blob/master/src/topics/posts.js#L442 this specifically sets the count to the # of elements in the sorted set so not sure how it happens.

**Comment by pitaj** [comment]
Would someone mind opening a separate issue for that?

**Comment by barisusakli** [comment]
Could be custom code that is causing it, I can't reproduce it by moving a post to another topic.

**Comment by BenLubar** [comment]
Here's the code that hides replies from categories the user can't see in the count: https://github.com/boomzillawtf/tdwtf/blob/df9d603c8d0aa74d1b99cbc01c159de77212746b/plugins/nodebb-plugin-tdwtf-customizations/index.js#L405-L489

As far as I can tell, it shouldn't cause doubled reply counts in different topics since it doesn't cause it on replies within the same topic, and those numbers should be computed via the same code path, but having more eyes on my code would be nice.

**Comment by barisusakli** [comment]
>data.posts[reply.idx].replies.count++;
would cause it if there is an issue in the logic, or duplicate pids in `replyPids`.
