### ISSUE TITLE
If digest frequency is set in ACP, users who have no explicit settings do not get said digests

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5770]
- **NodeBB version:** v1.5.1
- **NodeBB git hash:** 05434afed161e048feabd04cca69170640b30fe0

- **Database type:** mongo
- **Database version:** 3.2.9

- **Exact steps to cause this issue:**

* Set ACP digest frequency to anything but `off`
* Create a new user but do not save any settings (in /user/whatever/settings)
- **What you expected:**

* Receive a digest at whatever time
- **What happened instead:**

* ... did not receive digest

**Comment by julianlam** [comment]
The ACP settings to set default user settings work fine, they are invoked properly and override user settings hash when requested via `User.getSettings` via `getSettings()`.

However the digest logic doesn't check individual user settings, but rather the `digest:day:uids` zset directly, and unless you **explicitly** set digest frequency in your dashboard, you are not added to said zset, hence you do not receive the digest.

**Comment by julianlam** [comment]
Initial attempt at code was deemed unscalable.

**Comment by lunar-debian** [comment]
Sadly, it seems I'm still experiencing the issue.

I'm far from familiar with the codebase and node.js development in general but the code now seems to call `User.getMultipleUserSettings` which, contrary to `User.getSettings` does not call `User.onSettingsLoaded` where the default value for `dailyDigestFreq` gets looked up. What do you think?

**Comment by julianlam** [comment]
This issue has been resolved for quite some time ... What hash are you on?

**Comment by lunar-debian** [comment]
Currently running 316fe2773c. The default is currently set to send weekly digest. I had only one email sent last Sunday while there was already about 40 accounts.

**Comment by julianlam** [comment]
How are you determining the number of emails sent? There's an output in the logs for the digest, so I'm wondering if that's reporting a different number.

To give you some context of the actual fix regarding settings. **Yes**, getMultipleUserSettings does not call `User.onSettingsLoaded`, and this is intentional because this is how I can determine whether a user has explicitly set their digest settings or not. Specifically if it is **not** set, then I can add them to the recipient list if the system default for digests is set.

In the old logic, there was no handling of users who didn't have the option set at all, so nobody except those who explicitly opted-in, received digests.

You may also want to check the users' settings hashes to see if they've turned off digests.

**Comment by barisusakli** [comment]
`User.onSettingsLoaded, and this is intentional because this is how I can determine whether a user has explicitly set their digest settings or not.` Actually this was a regression caused by me I fixed it in https://github.com/NodeBB/NodeBB/commit/6c755869cda921f02a49646ef14d14ba6776d59a, so maybe this is fixed now on master @lunar-debian

**Comment by julianlam** [comment]
Neat, thanks @barisusakli hope that fixes it.

**Comment by lunar-debian** [comment]
Thanks! I'll tell you on Sunday if that fixed it, but according to my understanding of the code, that ought to work. :)

**Comment by lunar-debian** [comment]
12/11 10:00:03 [19809] - info: [user/jobs] Digest (week) scheduling completed. 55 email(s) sent.

Case closed. Thanks!
