### ISSUE TITLE
RTL setting doesn't apply for the first few milliseconds

### ISSUE THREAD

**Issue by orweinberger** [NodeBB/NodeBB#5772]
- **NodeBB version:** 1.5.1
- **NodeBB git hash:** e64104786ffdd8471119dc54660c3fc12f3202a1

- **Database type:** mongo
- **Database version:** 3.2.14

When NodeBB is set to the Hebrew language, the RTL CSS setting is off for the first few milliseconds when loading a page via refresh (F5), does not happen when switching between pages without refreshing them. I took a video demonstrating the issue

![awesomescreenshot-2017-06-25t08-43-04-843z](https://user-images.githubusercontent.com/1876045/27514743-49e9953a-599c-11e7-84db-a7dcd8505ad9.gif)

**Comment by orweinberger** [comment]
Thanks for the fix @barisusakli but the issue still persists, I'm using the lavender theme and when I view the HTML source of the loaded page I can see:

```
<html lang="he" >
```

None of the direction CSS, and the view still flickers when loaded via refresh.

**Comment by pitaj** [comment]
Did you pull down the latest NodeBB master branch?

**Comment by orweinberger** [comment]
Oh, no I did not. I will and update if this issue is resolved, thanks.

**Comment by orweinberger** [comment]
@pitaj @barisusakli This is still occuring, even after updating the lavender theme and pulling from master and rebuilding. I now have this in my HTML tag:

```
<html lang="he" data-dir="rtl" style="direction: rtl;" >
```

However, still experiencing the same behavior of flickering text directions on reloads.

**Comment by barisusakli** [comment]
Does the same flicker happen on the persona theme as well?

**Comment by orweinberger** [comment]
No, but I do get some flickering in other areas, seems like the dates are flickering between English and Hebrew. But RTL-wise looks OK I think.
![awesomescreenshot-2017-07-05t05-35-16-256z](https://user-images.githubusercontent.com/1876045/27850408-153c37fc-615d-11e7-9466-cbaec293acf1.gif)

**Comment by barisusakli** [comment]
Seems like this happens because the correct configs for timeago are loaded after the page is loaded.

https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/translator.js#L607-Lundefined

We could possibly include the correct script file in <head> depending on user language and remove that code from client side.

**Comment by barisusakli** [comment]
@orweinberger above commit should fix the timego strings starting in english and then changing. The issue with lavenders categories page is probably related to the masonry plugin that it uses.

**Comment by barisusakli** [comment]
This fixes the issues in lavender as well.
https://github.com/NodeBB/nodebb-theme-lavender/commit/9ae5299055c7de73798a6f266373ead6ecccc12e 
https://github.com/NodeBB/nodebb-theme-lavender/commit/146f34de345809eae7c3e1238dba8c6cf1468846

**Comment by orweinberger** [comment]
I can confirm this is now resolved, thanks @barisusakli
