### ISSUE TITLE
Cannot find 2FA screens on Transifex

### ISSUE THREAD

**Issue by orweinberger** [NodeBB/NodeBB#5781]
- **NodeBB version:** v1.5.1
- **NodeBB git hash:** e64104786ffdd8471119dc54660c3fc12f3202a1

Looks like the both the 2FA login and setup screens are not available for translations. Can they be added so I could translate them?

![image](https://user-images.githubusercontent.com/1876045/27596943-a68b884c-5b69-11e7-84f9-a28c0fce4597.png)

**Comment by pichalite** [comment]
@orweinberger That's because 2FA is not part of the core. It's a plugin. Plugins handle i18n on their own.

Refer to the plugin repo on how to translate. https://github.com/julianlam/nodebb-plugin-2factor/blob/master/TRANSLATE.md

**Comment by orweinberger** [comment]
Got it, thanks!
