### ISSUE TITLE
Open drafts should be saved in session storage and re-opened.

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5784]
We already save drafts, and it works quite well. However, today I clicked on an uploaded file and the file loaded in the same tab 😦 

We should fix that, but also, if I start a reply (or compose a new topic) and leave the page, going back to the page via cold load should re-open those drafts.

Should be as simple as saving the tids (for replies)... may be harder for new topics, not sure yet.

**Comment by pitaj** [comment]
LocalStorage, then. SessionStorage only works until the tab is closed

**Comment by julianlam** [comment]
sure, localStorage works too.
