### ISSUE TITLE
Problem with posting after migrating to new server

### ISSUE THREAD

**Issue by estebanconstante** [NodeBB/NodeBB#5786]
- **NodeBB version:** 1.5.1
- **NodeBB git hash:** e64104786ffdd8471119dc54660c3fc12f3202a1

- **Database type:** mongo  & redis
- **Database version:** mongodb version v2.6.10
Redis server v=3.2.9 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=323de15877fe2ae6

- **Exact steps to cause this issue:**

I migrated my mongodb to another server, everything looks fine except when trying to post, suddenly I post other people's posts.

In the nodebb log I'm getting:

> 8/6 17:04:20 [28108] - error: /auth/facebook/callback
 InternalOAuthError: Failed to fetch user profile

- **What you expected:**

- **What happened instead:**

**Comment by estebanconstante** [comment]
I'm also getting:

> MongoError: Index with name: content_text_uid_1_cid_1 already exists with different
 options

**Comment by pitaj** [comment]
Try disabling `nodebb-plugin-sso-facebook`

**Comment by julianlam** [comment]
Your indices are messed up, when you migrated, the target already had indices so you need to clear them with `db.objects.dropIndexes()` and recreate them by restarting NodeBB.
