### ISSUE TITLE
Footer copyright wrongly implies forum content ownership

### ISSUE THREAD

**Issue by r4co0n** [NodeBB/NodeBB#5788]
In a default NodeBB installation, the footer says 'Copyright <SomeYear> NodeBB". This is a problem, because if I am using NodeBB, I expect my content to be under my personal copyright, and not NodeBB's. However, the footer lets anyone surfing my website assume that NodeBB is the copyright holder of the content I produced in the software.
I changed my footer to "Copyright something | Running on NodeBB Forums | Contributors" and left your links intact.
In my eyes, using something like "powered by" is better for all users. Plus, you don't get the DMCA takedown notices for my content ;)

Cheers, keep up the great work

**Comment by pitaj** [comment]
Just to clarify: you're suggesting a different default?

**Comment by r4co0n** [comment]
Yes, exactly. In my opinion the content management software should not claim copyright of the content. I think the current default can become to a problem for the people using the package as well as for those holding the NodeBB trademark.
