### ISSUE TITLE
nodebb socket.io 403 forbidden

### ISSUE THREAD

**Issue by Kirk-Wang** [NodeBB/NodeBB#5791]
- **NodeBB version:** 1.5.1
- **NodeBB git hash:** 

- **Database type:** mongo
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

Request URL:http://172.27.20.12:4567/socket.io/?EIO=3&transport=polling&t=LptQWyc
Request Method:GET
Status Code:403 Forbidden
Remote Address:172.27.20.12:4567
Referrer Policy:no-referrer-when-downgrade

**Comment by pitaj** [comment]
Make sure that the `url` property in config.json is equal to the address you use the access the forum.

**Comment by Kirk-Wang** [comment]
@pitaj thks! I saw the  [Restrict accepted socket.io domains on start](https://github.com/NodeBB/NodeBB/issues/5472)~~I have been resolved.
