### ISSUE TITLE
The hook filter:messaging.parse does not include the recipient uid

### ISSUE THREAD

**Issue by orweinberger** [NodeBB/NodeBB#5795]
- **NodeBB version:** v1.5.1
- **NodeBB git hash:** 02c679d5c9dd6761a0b99b4ac60bafb364ebd4ce
- **Database type:** mongo

When the `filter:messaging.parse` fires, it includes the sender uid in both the `fromuid` and `uid` fields. I'm guessing the `uid` field should have included the recipient uid, or perhaps another field `touid` to include the recipient uid?

**Comment by orweinberger** [comment]
I just realized that a chat can include several members, so I'm no longer sure about the `touid`, maybe it should be an array? My specific use case is that I would like to be able to receive and respond to chats via a plugin, if I don't have the `touid`, I can't tell if the chat message was sent to my plugin user.

**Comment by pitaj** [comment]
I believe that `uid` is just the `uid` that initiated the socket or http request. It would then most likely always be the same, but I see no reason to change it. You can use the `roomId` field along with I think `messaging.getUidsInRoom` or `messaging.getUsersInRoom`
