### ISSUE TITLE
action:chat.sent never fires

### ISSUE THREAD

**Issue by orweinberger** [NodeBB/NodeBB#5796]
- **NodeBB version:** v1.5.1
- **NodeBB git hash:** 02c679d5c9dd6761a0b99b4ac60bafb364ebd4ce
- **Database type:** mongo

I'm trying to bind a plugin to the `action:chat.sent` hook, but can't get it to fire at all. As a workaround I'm using the `filter:messaging.parse` hook and basically filter out whatever isn't `isNew: true`.

**Comment by pitaj** [comment]
`chat.sent` is a client-side action

**Comment by pitaj** [comment]
`action:messaging.sent` would be a useful hook, though.

**Comment by julianlam** [comment]
You'll want to use `filter:messaging.save`... did you need an action hook?
