### ISSUE TITLE
Hiding certain api fields

### ISSUE THREAD

**Issue by estebanconstante** [NodeBB/NodeBB#5799]
- **NodeBB version:** 1.5.1

Is it possible to hide certain fields from an API request?

for example, doing:
http://localhost/api/user/admin

will show me a lot of data.

I want to restrict that data to show only certain fields.

Is it possible?

Can you direct me to it?

**Comment by estebanconstante** [comment]
I found I can do it by editing src/controllers/user.js -> userController.getUserDataByUID

Is there an easier way that doesn't have to do with editing the main code?

**Comment by barisusakli** [comment]
It is possible with a plugin, just use the hook `filter:<template>.build` and set the data to undefined. In the case of the user route it would be `filter:user.build`.

```
myPlugin.onUserBuild = function (hookData, callback) {
    hookData.templateData.website = undefined;
    callback(null,  hookData);
}
```
