### ISSUE TITLE
Pagination randomly not working

### ISSUE THREAD

**Issue by Meilu** [NodeBB/NodeBB#5801]
- **NodeBB version:** NodeBB v1.5.1. 
- **Database type:** mongo
- **Database version:** 3.2.13

- **Exact steps to cause this issue:**
  1. First i clicked on a category with alot of topics and several pages
  2. Then, I clicked on any page on the bottom of the page (http://i.imgur.com/5m1yCpF.png)
  3. It opened the page for 1 second or less
  4. it then refreshes and always goes back to page 1
- **What you expected:**
I expected to go to the page where i wanted to go, and not be redirected to page 1
- **What happened instead:**
I was redirected back to page 1.

This does not happen all the time, only once in a while, it also happens in different categories randomly.
It happens on all browsers.

**Comment by barisusakli** [comment]
What is your git revision I believe this is already fixed.

**Comment by barisusakli** [comment]
Try with 1.5.2 and let us know if not fixed.
