### ISSUE TITLE
Passport Session remains the same

### ISSUE THREAD

**Issue by estebanconstante** [NodeBB/NodeBB#5803]
- **NodeBB version:** 1.5.1

Hey guys, I'm currently implementing "passport-facebook-token" strategy in my server, and so far it does authenticate with Facebook.

However, when it gets to:
`		authenticationController.onSuccessfulLogin(req, user.uid, done.bind(null, null, user));
` 
req.user.uid gives me another uid (the one I first logged with).

After researching for hours, I've found that req contains a passport session and this doesn't get reset when I log out.
 

I've implemented this strategy using router.post instead of the router.get, (when I use .get I can pass the access_token through /auth/facebook/token?access_token=<token> but when I do it, I get logged in but I get an error as well saying the route was incorrect).

I've been reading comments on the forum, searched on google, here, read the code, and so far I'm lost. I don't know what else to do, any help?

**Comment by julianlam** [comment]
How are you logging out? You should be calling `app.logout()` to properly dispose of the session...

**Comment by estebanconstante** [comment]
Ok, seems I've found the reason.

When you logout normally, a cookie persists with the session:
"express.sid"

Any way to remove it? Or is it there for a particular reason?

**Comment by julianlam** [comment]
It persists because it is tied to the server side session object. When you log out this object is cleared (and shouldn't contain any user info), but anons are still given a _session_.

**Comment by julianlam** [comment]
There's no side effect to removing `express.sid`, the use will just get a new one when they next access the site 👍
