### ISSUE TITLE
one_reply_to_this_post not show text

### ISSUE THREAD

**Issue by lyquocnam** [NodeBB/NodeBB#5806]
<img width="1130" alt="screen shot 2017-07-08 at 10 09 22 am" src="https://user-images.githubusercontent.com/8347826/27982194-379e81cc-63c6-11e7-9b4c-d229cc5c88c6.png">

**Comment by EnDylan** [comment]
Have to tried restarting NodeBB (Directly from the ACP). This will rebuild its assets and hopefully fix that.

**Comment by lyquocnam** [comment]
@EnDylan i tried restart many times and restart in commandline too, but still not work !

**Comment by EnDylan** [comment]
May I have the link to your forum?

**Comment by lyquocnam** [comment]
this proplem still in here @EnDylan https://vue.vn/topic/22/bai-1-gioi-thieu-ve-quasar-framework/4

**Comment by pichalite** [comment]
@lyquocnam what version of NodeBB and persona theme are you using?

**Comment by lyquocnam** [comment]
latest, nodebb 1.5.1 and persona 5.0.3

**Comment by pichalite** [comment]
That language string is missing in release 1.5.1 for vietnamese. It's added to master after 1.5.1 was released and should be available in next release.

You can also add it to your setup manually.

**Comment by lyquocnam** [comment]
thanks so much @pichalite

**Comment by lyquocnam** [comment]
@pichalite i tried setup manually: 
- edit `nodebb/build/public/language/vi/topic.json`.
- restart forum many times ( restart by command line too)
but still not change !
<img width="1224" alt="screen shot 2017-07-09 at 12 39 46 pm" src="https://user-images.githubusercontent.com/8347826/27991521-d02dbfb0-64a3-11e7-9f9f-03ee86721174.png">

**Comment by pichalite** [comment]
@lyquocnam anything in the build directory is overwritten on build/restart.

Change it in top level public directory. For you it's `nodebb/public/language/vi/topic.json`

**Comment by lyquocnam** [comment]
ok this work ! thanks @pichalite
