### ISSUE TITLE
Docker image: nodebb configuration support ?

### ISSUE THREAD

**Issue by digitalLumberjack** [NodeBB/NodeBB#5808]
### For discussion: 

Hi, I created a docker image supporting some options that can ease the deployment of a nodebb instance.

You can configure with this image:
- port and hostname
- administration account (for first start)
- smtp
- secret
- db connection
- S3 bucket for uploads
- plugins (on build or on runtime)

It's far to be perfect, but do you think that could be interesting for the community ?

You can find sourcesof the project here :  
https://gitlab.com/recalbox/ops/nodebb

**Comment by barisusakli** [comment]
Hi please post this on our community, if you haven't already https://community.nodebb.org
