### ISSUE TITLE
Some meta tag content wrong on UTF-8

### ISSUE THREAD

**Issue by lyquocnam** [NodeBB/NodeBB#5812]
this is some meta tags error content. It relate to forum SEO, please check it.
![image](https://user-images.githubusercontent.com/8347826/27993019-06cdeb5e-64cb-11e7-8a5f-032c76599a4b.png)

**Comment by barisusakli** [comment]
What git hash is this happening on?

**Comment by barisusakli** [comment]
Nvm I see this happens because we call validator.escape on the  content value.

**Comment by lyquocnam** [comment]
hope this will be fixed soon :)
