### ISSUE TITLE
Custom robot.txt save does not work

### ISSUE THREAD

**Issue by lyquocnam** [NodeBB/NodeBB#5813]
Hi author, i tried to custom robot.txt in `settings> Web Crawler` with content:
```
User-agent: *
Disallow: /admin/
Allow: /
Disallow: /cdn-cgi/l/email-protection
Disallow: /groups
Disallow: /users
Disallow: /user
Sitemap: https://vue.vn/sitemap.xml
```
i tried to save but still not change, everything has gone...

**Comment by julianlam** [comment]
Have you tried restarting NodeBB?

**Comment by lyquocnam** [comment]
Yes, i tried many times.
So i created file Robots.txt in `nodebb/public/Robots.txt`, and try save again in AdminCP -> restart -> it's work ! But when reload adminCP settings page, Robots settings not load.

**Comment by barisusakli** [comment]
Looks like the value is saved but on reload the input is empty in the ACP.
