### ISSUE TITLE
Hashtag on topic

### ISSUE THREAD

**Issue by lyquocnam** [NodeBB/NodeBB#5816]
Hi author, if we can simple add tag by hash into topic content, that's perfect.
ex: I have some demo content:
--> Today, i'm not go to `#school` because i'm scare my `#teacher`.
when click to hashtag, it will link to tag school.

**Comment by julianlam** [comment]
At this time, tagging in posts is not supported as tags are per topic, not per post. This can be done best in a plugin and will not be included in core.
