### ISSUE TITLE
Update docs URLs in ACP

### ISSUE THREAD

**Issue by dnkls** [NodeBB/NodeBB#5819]
Hello.
I just upgrdae the new version ( A new version (v1.5.2) has been released. Consider upgrading your NodeBB.)

But when i clin for upgrade i redirect to (https://docs.nodebb.org/en/latest/upgrading/index.html)
404 Not Found

How upgrade to 1.5.2?

**Comment by pauljherring** [comment]
While that's being fixed, there are instructions at https://docs.nodebb.org/configuring/upgrade/

**Comment by pitaj** [comment]
We do need to update the URLs used in the ACP.

- `admin/extend/plugins:docs-info`
- `admin/general/dashboard:upgrade-available`
