### ISSUE TITLE
Improper post visibility

### ISSUE THREAD

**Issue by ELadner** [NodeBB/NodeBB#5820]
- **NodeBB version:** 1.5.1
- **NodeBB git hash:** ``e64104786ffdd8471119dc54660c3fc12f3202a1``
- **Database type:** mongo
- **Database version:** v3.2.15
- **Exact steps to cause this issue:**
  1. Create a category - _SuperSecret_
  2. Create a group _Spies_ with some members (UserA).  
  3. Assign _Spies_ to _SuperSecret_ on the Privs tab with everything but purge and moderate.
  3.  Revoke all other permissions on the group.   Guests, registered users, no privs.
  4. As UserA, post a new topic in _SuperSecret_.
  5. As another regular user (UserB) not in _Spies_, look at UserA's profile page.

- **What you expected:**  UserA's post to a protected category shouldn't show up to general users on the user profile page of UserA under "Posts Made By UserA"
- **What happened instead:**      The topic, it's title and the first 8-10 lines are visible on UserA's profile page under "Posts Made By UserA", even though UserB has no ability to see that Category (doesn't show up in the category list, permission denied if direct navigating, etc.).

Thank you!

**Comment by barisusakli** [comment]
Can't repro, when I post a topic in a category that is hidden from registered-users they don't see that topic on my profile. Are you sure UserB doesn't have the `read` privilege to the category the topic is in. Post a screenshot of your privilege tab for the SuperSecret category.

**Comment by ELadner** [comment]
I can't seem to repro it either now.
