### ISSUE TITLE
Ignore code tag content in lastest post

### ISSUE THREAD

**Issue by lyquocnam** [NodeBB/NodeBB#5822]
![image](https://user-images.githubusercontent.com/8347826/28165117-a5db612a-67fc-11e7-9760-4582e212b914.png)
Hi author, can we ignore content in `code` tag from latest post in categories or home ?
many reason for this, and i think about security too.

**Comment by julianlam** [comment]
What security issues?

I do not think we will filter out code from the teaser, sorry.

**Comment by lyquocnam** [comment]
why don't do that @julianlam ? when show content, it look to bad 👎

**Comment by julianlam** [comment]
It looks equally bad to show the code or remove it altogether, and so we opted to simply remove formatting.
