### ISSUE TITLE
Google not mark forum description.

### ISSUE THREAD

**Issue by lyquocnam** [NodeBB/NodeBB#5823]
![image](https://user-images.githubusercontent.com/8347826/28165245-36ee5546-67fd-11e7-9882-72f7d0a699e4.png)
Hi author, i see it's now show forum's description, it show a comment of some topic.
This my not good for seo...

**Comment by julianlam** [comment]
We do not choose what Google decides to put as the search result description. Rest assured it is fine for SEO.
