### ISSUE TITLE
Adding a user to a PM

### ISSUE THREAD

**Issue by aStonedPenguin** [NodeBB/NodeBB#5829]
- **NodeBB version:** Replicated on 1.4.6-1.5.x
- **NodeBB git hash:** 956df9d7d7677e313b7f11c848be5e7b772327d7
- **Database type:** redis
- **Database version:**  3.0.6
- **Exact steps to cause this issue:** 
Chat with someone over PM and add a new user
- **What you expected:**
For the new user to be able to see the full PM history
- **What happened instead:**
The new user cannot see the PM history

I don't know if this is intentional but other softwares such as IPB do show added users the full PM history.

**Comment by pitaj** [comment]
WhatsApp, for one, behaves in the same way.

**Comment by KingofBeast** [comment]
CCing new people in a chain of emails lets them see all of the emails.

**Comment by julianlam** [comment]
It seems there is no real standard on this behaviour, although I will say this... _not_ knowing is not necessarily better either.

Some notification to the end user should be present, like a help tooltip or otherwise...

**Comment by barisusakli** [comment]
This was by design.
