### ISSUE TITLE
ACP Categories icon bug

### ISSUE THREAD

**Issue by aStonedPenguin** [NodeBB/NodeBB#5832]
- **NodeBB version:** 1.5.x
- **NodeBB git hash:** 956df9d7d7677e313b7f11c848be5e7b772327d7
- **Database type:** redis
- **Database version:**  3.0.6
- **Exact steps to cause this issue:** 
Add a category with no icon and a subcategory with an icon
- **What happened instead:**
The chat bubble from the category with no icon overlays on the subcategories with icons

![image](https://fi1.es/EOf7K/download)

**Comment by barisusakli** [comment]
Can you inspect the html in post a screenshot? I can't reproduce this on master.

**Comment by aStonedPenguin** [comment]
![image](https://fi1.es/wtaQm/download)

**Comment by barisusakli** [comment]
I think your wording was incorrect, it looks like if a category has a background image it shows the image and the icon. Did you actually remove the icon for that category? You have to select the empty icon in the category details.
