### ISSUE TITLE
phpbb(php7) 2.5X faster than nodebb

### ISSUE THREAD

**Issue by topm01** [NodeBB/NodeBB#5833]
- **NodeBB version:** 1.5.2 
- **Database type:** mongo  
- **Database version:** 2.6.12
 
- **Exact steps to cause this issue:**
   load categories page as home page for ab speed test
   both phpbb and nodebb with no any topics
- **What you expected:**
  should nodebb tuning for performance?
- **What happened instead:**
  ab test only about 200 request/second
  but same categories count as home page, phpbb with php7  about 500 request/second

**Comment by akhoury** [comment]
why does the [loader](https://github.com/NodeBB/NodeBB/blob/master/loader.js#L138) require multiple ports? u don't need it with [`cluster`](https://nodejs.org/api/cluster.html)

this works fine for me

```javascript 
const cluster = require('cluster');
const os = require('os');
const cores = os.cpus().length;
const isDebugMode = typeof v8debug === 'object' || /--(debug|inspect)/.test(process.execArgv.join(' '));

if (cores > 1 && !isDebugMode) {
    if(cluster.isMaster) {
        console.log(`Master ${process.pid} is running`);
        for (let i = 0; i < cores; i++) {
            cluster.fork();
        }
        cluster.on('exit', function(worker, code, signal) {
            console.log(`worker ${worker.process.pid} died`);
        });
    } else {
        require('./app');
    }
} else {
    console.log(`Master ${process.pid} is running`);
    require('./app');
}
```

**Comment by julianlam** [comment]
You don't _need_ to have multiple ports, but we support it if you want to handle multiple instances of NodeBB on the same server.

We don't use cluster as it was not performant when we tested it. It had issues working with socket.io and had some overhead that was better managed by nginx (or a separate load balancer if necessary)

**Comment by akhoury** [comment]
but by default, someone deploying nodebb on a 8 cores single-machine, would the 8 cores be utilized?

**Comment by julianlam** [comment]
No, in such a scenario, the recommended course of action is to change `port` to show eight port numbers, and use nginx to route requests to those 8 instances of NodeBB (managed by `loader.js`).

Default will listen to one port by default, 4567.

**Comment by akhoury** [comment]
got it.

**Comment by topm01** [comment]
## # Sorry sir as i know mongo db can use multi cpu core to read data , but why nodebb have multi instances( multi port ) mongodb seem use only  one core ... 
any one know why

**Comment by barisusakli** [comment]
@topm01 default nodebb install only uses 1 process, does your php installation have more than 1 processes?

**Comment by topm01** [comment]
yes sir i have same instance count

**Comment by julianlam** [comment]
Please consult the [documentation on scaling NodeBB](https://docs.nodebb.org/configuring/scaling/)
