### ISSUE TITLE
Mixed SI and IEC units

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#5835]
- **NodeBB version:** 
- **NodeBB git hash:** https://github.com/NodeBB/NodeBB/tree/45d940ad2bccc9ccd10718424d62485679836959

- **Database type:** irrelevant
- **Database version:** 

- **Exact steps to cause this issue:**

/admin/settings/uploads:

- **What you expected:**

Consistent units for limits, either all KB or all KiB.

- **What happened instead:**

![image](https://user-images.githubusercontent.com/3939886/28262718-f1019534-6adb-11e7-9007-07526ff47fb4.png)

![image](https://user-images.githubusercontent.com/3939886/28262796-4f5b4f8a-6adc-11e7-8641-0cff01ac6c74.png)

There may be other places.

**Comment by pitaj** [comment]
What should they all say?

**Comment by barisusakli** [comment]
The code multiplies these values by 1024, so I guess the correct term is KiB for all and kilobytes should say [kibibytes](https://en.wikipedia.org/wiki/Kibibyte), even though that sounds funny 😆

**Comment by pauljherring** [comment]
If you're going to start using KiB in an attempt to be 'correct' because you're using a 2<sup>x*10</sup> multiplier, then it's spelt in full `kibibytes`, and use that - and `KiB` - everywhere it applies.

If you're using 10<sup>x\*3</sup> multipliers, or being lazy with 2<sup>x\*10</sup>, use `Kb` and `kilobytes` everywhere.

Mixing and matching sets off my CDO, and prompts commentary over on our forum. :slightly_smiling_face:
