### ISSUE TITLE
Passanger (production mode) + nodeBB "Looks like your connection to NodeBB was lost, please wait while we try to reconnect."

### ISSUE THREAD

**Issue by alienfromouterspace** [NodeBB/NodeBB#5837]
**Related to** https://github.com/NodeBB/NodeBB/issues/5535 (last posts)

- **NodeBB version:** 1.5.2
- **NodeBB git hash:** 018d5d7819ce7429f41f02533effb8a3d191ac9d
- Passenger v5.0.30
- Node.js v7.9.0
- OS: FreeBSD 10.3-STABLE

- **Database type:** mongo 
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**
Install nodebb and start it using Passenger in production mode.

- **What you expected:**
To log into and to use nodebb as supposed to be used.
- **What happened instead:**
At the login screen I see message "Looks like your connection to NodeBB was lost, please wait while we try to reconnect." poping out in right bottom corner of browser window.

I can log in successfully, as an admin but I cannot add any topic.
When I go to location when I am supposed to add ne topic nothing happens after clicking button"New Topic". When I turn on webconsole in my browser I see messages:

>GET XHR http://mydomaingoeshere.com/socket.io/ [HTTP/1.1 403 Forbidden 16ms]

printed every few seconds.

My config.json is
```
{
    "url": "http://localhost:4567",
    "secret": "XXX",
    "database": "mongo",
    "mongo": {
        "host": "databaseserver.domain.com",
        "port": "27017",
        "username": "YYY",
        "password": "ZZZ",
        "database": "QQQ"
    }

```

- **Dirty workaround I found:**
Start nodebb using developement Passenger mode. Works fine and without error messages, seems functional. Downside is that passenger prints extended log of applications when problems happen.
That may be security risk etc.

**Comment by julianlam** [comment]
In your config, change the `localhost` address to be `http://mydomaingoeshere.com`

**Comment by julianlam** [comment]
Please follow-up on the [community support forum](https://community.nodebb.org) as this is not a bug.
