### ISSUE TITLE
Logout button does not match thematic elements (Persona)

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5844]
![selection_005](https://user-images.githubusercontent.com/923011/28525402-1f64d1ae-7052-11e7-8504-0a90a65a6349.png)

Paging @An-dz :smile:

**Comment by julianlam** [comment]
![selection_006](https://user-images.githubusercontent.com/923011/28525513-800d74de-7052-11e7-90e2-39e4a53c5928.png)

:point_up: The following CSS fixes, though will defer to designer as to whether this is appropriate :smile:

**Comment by An-dz** [comment]
The mobile view? [Here's a fix](https://github.com/An-dz/nodebb-theme-persona/commit/2fcca522a67f9aadb60300c3fa83ac512db1b47d)
