### ISSUE TITLE
Make ban duration visible to moderators/admins

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#5845]
- **NodeBB version:** 1.5.2
- **NodeBB git hash:** f59f48c

- **Database type:** N/A
- **Database version:** N/A

- **Exact steps to cause this issue:**

Ban a member for 1 day.
or
Perma-ban a member.

- **What you expected:**

Find somewhere how much longer is left on the ban/find expiry time for the ban on their `/user/name` page.

- **What happened instead:**

Unable to locate either of the above.

**Comment by julianlam** [comment]
People these days... not using their brains to remember how long they banned someone...

Just kidding :laughing:

**Comment by pauljherring** [comment]
Well it happens so infrequently on ours, and we have so many mods able to do it...

:smirk: 

Something else that came up - (and this possibly warrants a separate issue report, if it's going to be addressed) - beyond unbanning someone for a few seconds, there doesn't appear to be any way of changing the duration of the ban while it's still in effect.

**Comment by julianlam** [comment]
Was a corresponding commit made to vanilla too @barisusakli ?
