### ISSUE TITLE
TypeError: tags.concat is not a function

### ISSUE THREAD

**Issue by Woofik** [NodeBB/NodeBB#5846]
#

- **NodeBB version: 1.5.3**
- **NodeBB git hash: 7e2883e** 

- **Database type: mongo**
- **Database version: 3.4.6** 

Forum don't start after update.

`error:  TypeError: tags.concat is not a function
    at Object.plugin.addPrefetchTags [as method] (/opt/nodebb/node_modules/nodebb-plugin-composer-default/library.js:61:14)`

**Comment by barisusakli** [comment]
Can you run `npm i` and restart? See if it happens again.

**Comment by Woofik** [comment]
npm i - ok, but same error. nodebb restarts with this error on each request. Work if nodebb-plugin-composer-default is disable.

**Comment by Woofik** [comment]
git reset --hard origin/v1.5.x  (7e2883e) - error
git checkout v1.5.3 (f6890cd) - work
