### ISSUE TITLE
If ACP login times out, ajaxifying to another ACP page doesn't return user to target post-login

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5847]
- **NodeBB version:** v1.5.3 (develop)
- **NodeBB git hash:** 875672522ea4f35a589b199799a01340d7e8e38a

- **Database type:** redis
- **Database version:** N/A

- **Exact steps to cause this issue:**

    - Open ACP page
    - Wait for ACP to time out (security feature)
    - Navigate to another ACP page
    - Be redirect to login page, log in
- **What you expected:**

    - Redirected back to the page I wanted to go
- **What happened instead:**

    - Sent to the corresponding `/api` route instead

**Comment by barisusakli** [comment]
This was only reproducible on a sub folder installation.
