### ISSUE TITLE
One-stop shop for watched/ignored categories

### ISSUE THREAD

**Issue by TwelveBaud** [NodeBB/NodeBB#5851]
- **NodeBB version:** 1.5.2
- **NodeBB git hash:** f59f48c6e1f8262ddc66f4ad09ed19461156be9e
- **Database type:** mongo
- **Database version:** unknown

In other forum software that supports watching or ignoring categories/fora, there's typically a master list of watched/ignored categories/fora on a page in user settings, In Discourse, for example, the bottom of the settings page has two content-editable areas, one for watched categories, one for ignored categories, that show all the categories you're currently doing that to and allow you to type to add new ones.

In NodeBB, it looks like you have to go to each category from the master category list to see whether it's being watched, not watched, or ignored, or to change that setting. There doesn't appear to be another way to get that information, whether as a browser (navigating between pages) or as a program (parsing JSON from each specific category's endpoint).

Please make a place which displays category visibility settings for all categories, and preferably some way to change them from there.

**Comment by julianlam** [comment]
We think this is a fantastic idea, by the way @TwelveBaud! It's on our to-do list (basically, every open `enhancement` issue), but is not prioritised at the moment.
