### ISSUE TITLE
Terms and Conditions for installed plugins from ACP

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#5853]
In the `LICENSE` or similar file in most plugin repositories, people usually have a spiel about no guarantees, no warranties, if this plugin blows up your 50m$ business it's not our fault, etc, etc.

But it's never actually messaged to the end-user who downloads the plugin from the ACP, which is most important of all.

Something like a modal with an "I agree" that pops up before you install a plugin that basically links that file would be a great MVP for this. Potentially in the future (out of scope for this issue) we can also tap into hooks like, let's say `filter:register.complete` and bring up extra warnings ex.

> This plugin accesses registration data, potentially including passwords

Back to the original point, this enhancement is to protect plugin authors first.

**Comment by yariplus** [comment]
Since usually terms and conditions are covered in the license, I would think adding the license type to the plugin listing in the ACP would be enough as far as protecting devs.

**Comment by julianlam** [comment]
![selection_022](https://user-images.githubusercontent.com/923011/28930550-51f65f7e-7841-11e7-82ac-ed325fcdddb0.png)

**Comment by julianlam** [comment]
... well, except "Save" would be "Confirm"
