### ISSUE TITLE
View [Flagged User] goes nowhere

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#5858]
- **NodeBB version:** 1.5.2
- **NodeBB git hash:** f59f48c

- **Database type:** -
- **Database version:** -

- **Exact steps to cause this issue:**

- Flag a user
- Go to the flag at /flags/\<number>

Click View Profile under Flagged User

![image](https://user-images.githubusercontent.com/3939886/28965206-dc324cb8-7907-11e7-91bf-f3a84f363cb3.png)

- **What you expected:**

To go to /uid/\<number>

- **What happened instead:**

Taken to /uid without the \<number>

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5775
