### ISSUE TITLE
how to use mlab database with nodeBB

### ISSUE THREAD

**Issue by hackertron** [NodeBB/NodeBB#5860]
Hello i want to launch a nodeBB instance on heroku . I am using free dynos and a free database from mlabs. I have successfully deployed the nodeBB on heroku and i have installation page which is asking for database configurations .

i am providing the db url  
example : 
host : db1244:mlab.com:15493
port : 15493
username :  something
password : something
dbname : nodebb

but it's not working . 

error : There was an error connecting to your database. Please try again.

**Comment by pitaj** [comment]
Please use our community forum for these types of questions: https://community.nodebb.org
