### ISSUE TITLE
Stop chat search list resetting when one is selected

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#5862]
- **NodeBB version:** 1.5.3
- **NodeBB git hash:** 5a52e6f

- **Database type:** -
- **Database version:** -

- **Exact steps to cause this issue:**

1. Chats > See All chats
2. Enter a username in the [Enter a username to search]
3. Click on username to perform search
4. Scroll down lots to find an old conversation
5. Select an old conversation

- **What you expected:**

For the left panel to remain as it is, with the conversation selected still visible so you can continue to scroll further back if that wasn't the one wanted.

- **What happened instead:**

Panel resets to the original search with only the first conversations showing, the scrolling in (4) has to be performed again.

**Comment by julianlam** [comment]
Makes sense to me :+1:

**Comment by julianlam** [comment]
@pauljherring Just following up as I can't reproduce *exactly* what you described... then again I do not have as many chats on your env as you do.

I searched `PJH` and found your icon in dropdown, and clicking it doesn't "perform a search". It just opens the latest conversation with you.

However I did notice that if the conversation were very old (that is, below the fold), then the div isn't scrolled down to the active chat. Is that what you mean?

**Comment by pauljherring** [comment]
After step 1:
![image](https://user-images.githubusercontent.com/3939886/29136561-8daf2c3c-7d35-11e7-8d05-7fd77b902fa8.png)

Step 2:
![image](https://user-images.githubusercontent.com/3939886/29136615-b110c208-7d35-11e7-9974-2543ed7a35cf.png)

Step 3: I've just realised - the search doesn't actually do anything extra to the left pane, the click just adds the scrollbar to the left pane and populates the right hand pane (with only some of what I'd expect) - I might be misunderstanding this interface...
![image](https://user-images.githubusercontent.com/3939886/29136834-54375cf8-7d36-11e7-8600-8e43299c9c68.png)

Step 4: Notice the scrollbar and position of the cursor.
![image](https://user-images.githubusercontent.com/3939886/29136932-a152e7e6-7d36-11e7-8253-84cbdecf70d3.png)

Note also, despite my commentary at step 3, Boomzilla's comment in the left pane doesn't appear in the right pane.

Step 5: Note the scrollbar on the left pane - the left pane has reset.
![image](https://user-images.githubusercontent.com/3939886/29137053-fd216976-7d36-11e7-8040-c0395acd79b9.png)

**Comment by pauljherring** [comment]
Note that it the reset of the left hand pane at step 5 that I'm asking to stop happening.

**Comment by julianlam** [comment]
How'd you get from Step 3 to Step 4, scroll down on the left-hand side?

**Comment by pauljherring** [comment]
> scroll down on the left-hand side?

Pull the cursor down or tap the scroll bar beneath the cursor to page down.

**Comment by julianlam** [comment]
Some thoughts while I'm planning my route of attack:

* The reason why the list resets is becausee I `ajaxify.go` to the new chat when the left-hand menu is clicked
* I do that because at the time, I probably felt like there was too much to change on the page, and it wasn't worth adding additional client-side logic to update only the messages
* The page has gotten simpler now and the only element left is the breadcrumb, which upon reflection is pretty useless (clicking "Chats" just unloads the active chat, but you're still on the same page)

So I may remove the breadcrumb altogether, but this makes it a breaking theme change and so will go out with v1.6.0

**Comment by julianlam** [comment]
For theme authors, apply the following three commits (or changesets, rather) to your theme to assume compatibility:

1. https://github.com/NodeBB/nodebb-theme-persona/commit/7fda45959464cdd8822b4b677659a16602b16f70 (components and new partial)
1. https://github.com/NodeBB/nodebb-theme-persona/commit/9552bf086e12afe4d443833be377112a0e4293f9 (removing breadcrumbs from template)
