### ISSUE TITLE
A specific combination of if statements breaks the page

### ISSUE THREAD

**Issue by zombachu** [NodeBB/NodeBB#5863]
- **NodeBB version:** v1.5.3
- **NodeBB git hash:** 4dc23c4dfeef9c19163097e5156124d217efdd72

- **Database type:** mongo
- **Database version:** v3.4.6

Sorry if this was supposed to go in benchpressjs' issues instead...

I've been making a custom theme based on Persona and I encountered a weird error when theming the topic items in a category. I reduced my code to these problematic if statements:

```
<!-- IF ../teaser.pid -->
    <!-- IF ../teaser.user.picture -->
    <span>This teaser's user has a picture.</span>
    <!-- ENDIF ../teaser.user.picture -->
<!-- ELSE -->
    <span>This post has no replies.</span>
<!-- ENDIF ../teaser.pid -->
```

If I remove the else, then it renders as expected. If I delete the outer if/else and just have the picture check, then it also renders as expected. If I remove the inner if statement so just the pid check remains, then it renders as expected. I also did some limited testing with an inner if statement testing different values and those rendered as expected as well. When the page breaks it leaves fragments of the if statements in the rendered page source but I don't receive any errors in the logs.

Attached are pics of my site when the page is rendered properly, and when it breaks from adding the above if statements. (please excuse the ugly unfinishedness of it all)
![screen shot 2017-08-08 at 11 44 22 pm](https://user-images.githubusercontent.com/7826590/29115799-8c59b524-7c94-11e7-807e-7a30c1ba97ef.png)
![screen shot 2017-08-08 at 11 41 28 pm](https://user-images.githubusercontent.com/7826590/29115810-9382ff54-7c94-11e7-9eae-3fcf3a710ec7.png)

**Comment by MegaGM** [comment]
@zombachu could you, please, provide the error stack trace from the console? (Ctrl + Shift + J in Chrome)

**Comment by zombachu** [comment]
@MegaGM Like I said there's no error in the logs... That means both the browser's console and NodeBB's server logs. Sorry if I wasn't clear in my original post.

**Comment by julianlam** [comment]
Hm, looks like you're on latest v1.5.x... any chance you can try the `benchpress` branch?

**Comment by zombachu** [comment]
@julianlam That worked!

**Comment by bojars** [comment]
Any chance that benchpress branch will go into master soon?

**Comment by julianlam** [comment]
It will go into develop first, then master, at v1.6.0
