### ISSUE TITLE
[User (x)] in chat shouldn't have the (x) if they're the 'last user' 

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#5868]
From #5148
Clicking the cog in a chat produces a user list of everyone in the chat (with the exception of yourself)

![image](https://user-images.githubusercontent.com/3939886/29140200-9491e290-7d41-11e7-937e-5095f9046c0e.png)

Clicking the (x) next to any user will remove them from that chat.

Except if there's only one there:

![image](https://user-images.githubusercontent.com/3939886/29140211-a8b430b6-7d41-11e7-9a94-d0ef8f5789e5.png)

Clicking the (x) brings up an error.

![image](https://user-images.githubusercontent.com/3939886/29140268-d6686a04-7d41-11e7-9f6d-df187c540df5.png)

If the (x) isn't allowed, it really shouldn't be a visible option.

**Comment by julianlam** [comment]
Hey, I bet I can fix this with  CSS...
