### ISSUE TITLE
Accounts that reset password via email shouldn't really need to also separately confirm email address 

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#5869]
- **NodeBB version:** 1.5.3
- **NodeBB git hash:** 5a52e6f

- **Database type:** -
- **Database version:** -

- **Exact steps to cause this issue:**

1. Tried to log into an account I hadn't used since migration (i.e. NodeBB didn't have confirmation of email,) couldn't remember password
2. Asked for a password reset email to be sent
3. Receive email, use link
4. Set new password
5. Login

- **What you expected:**

Nothing more regarding maintenance of the account

- **What happened instead:**

A prompt to confirm the email address on the account - the one that  NodeBB sent the password reset token to (3), which was then used (4)

**Comment by barisusakli** [comment]
So resetting password should also confirm the email :shipit:

**Comment by pauljherring** [comment]
Well, technically merely visiting the URL to reset  the password should be sufficient (as it is for the confirmation email,) but I suspect the number of people who
- haven't already confirmed
- request a password reset
- go to the URL
- but don't actually reset

is vanishingly small.
