### ISSUE TITLE
/post/<pid> should not redirect if user does not have read access to topic

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5872]

**Comment by pauljherring** [comment]
... what should it do instead?

**Comment by barisusakli** [comment]
Should return not found I think. This is reported here https://community.nodebb.org/topic/11112/invalid-redirect-to-private-topics.

If a topic owner deletes their topic, and there is a link to a post in that topic such as `/post/123` it was redirecting and showing access denied.
