### ISSUE TITLE
Support for Sass

### ISSUE THREAD

**Issue by axynos** [NodeBB/NodeBB#5874]
I saw the previous issue (#3737) about it and saw that support for sass would be considered when bootstrap 4 hits beta.

That has now happened, so I'd like to make a request for this again.

In a perfect world, I'd ask for the ability for theme devs to choose their own framework to use (I personally love iota-CSS and would prefer to use it over bootstrap 4) but I'm not sure how tied in bootstrap is to everything.

**Comment by pichalite** [comment]
@axynos Unfortunately bootstrap is tied in to too many things in NodeBB. Not easy to remove the dependency.

**Comment by julianlam** [comment]
It is not **impossible**, but as @pichalite says, it is _not easy_. 

@pitaj @yariplus perhaps one of you can investigate the feasibility of doing SASS... if the writing is truly on the wall for LESS.

**Comment by pitaj** [comment]
It would make everything easier if the CSS framework was tied to the theme and only the theme, but supporting plugins makes things more difficult. 

If we want to go that way, we could deprecate using bootstrap entirely and load it when needed.

**Comment by Foorack** [comment]
Any update on this?
Considering of using NodeBB and interested in designing a theme using Bootstrap 4.

**Comment by Foorack** [comment]
@julianlam Any updates on this? Bootstrap 4 was released in January. If usage of bootstrap is not deprecated then can it at least be updated?

**Comment by pitaj** [comment]
Bootstrap 4 is a huge breaking change, it would break all plugins.

**Comment by Foorack** [comment]
Any update on this? If it is not going to be removed, is there at least any planned upgrade path to Bootstrap 4?

**Comment by phit** [comment]
two years later, still no plans for bootstrap 4?

**Comment by julianlam** [comment]
We do, actually!

We have a development branch going that integrates webpack and BS4. It is not anywhere near production ready and breaks almost everything, but alas, such is the price of progress...

**Comment by phit** [comment]
breakage is expected, good to hear there's progress, I should have checked the active branches before posting
