### ISSUE TITLE
Inline action history in topics

### ISSUE THREAD

**Issue by zombachu** [NodeBB/NodeBB#5877]
### The basics

One feature that I think would be really cool to have is an inline action history in topics like GitHub has for issues:

![screen shot 2017-08-14 at 4 01 46 pm](https://user-images.githubusercontent.com/7826590/29299458-6fba4350-810a-11e7-87da-f1f69ac691c3.png)

It's a little awkward (and shouldn't be needed to be done in the first place, IMO) for forum mods to perform an action on a topic *and also* create a new post declaring their action.

### The pitch

This feature would have the following benefits:

- Removing the need for those mod posts
- Putting an action in context with the surrounding posts
- Preserving the history of a topic
- Displaying who performs the action for those that don't already track of that
- Adding the possibility of even more features

This feature request is asking a lot but hopefully these additions could be a part of a bundled plugin or NodeBB itself. I think it would set NodeBB apart from other forums software more than it already is, as I haven't really seen this in anything else besides Discourse.

### The details

I think that the following would be good things to track in a topic's history (in addition to the person who did it, timestamps, and relevant information):

- Locking a topic
- Pinning a topic
- Moving a topic
- Deleting a topic
- Restoring a topic
- Changing a topic's tags
- Changing a topic's title

Global configuration options:

- A toggle to disable this entirely
- A toggle to hide who performed the actions
- A toggle to choose whether to display the actions inline or in a separate view
- A setting to set the default notification status for users (more on this in a sec)
- A permission to be able to see the actions

User options:

- A notification setting with the options:
  - Not receiving any notifications at all from actions
  - Receiving notifications from actions performed on the user's topics
  - Receiving notifications from actions performed on any topics the user participates in

Other features that might work well with this (should I make separate issues for these?):

- A global moderation log with all actions performed by users of specified ranks (And being able to filter this by user and/or category)
- An option to provide a reason at the time of performing an action (to also be displayed inline with the action)

---

I know it'll be a bit of work and will likely require a major, plugin-breaking API change, but I would love to see this added to NodeBB in the future!

**Comment by julianlam** [comment]
Thanks for the contribution, and the detailed write-up! This is definitely a good idea and I believe we already have the basics available via a plugin. Perhaps @psychobunny can confirm?

It'd be nice to bundle it with all installs.

**Comment by nhlpl** [comment]
https://github.com/psychobunny/nodebb-plugin-events

**Comment by julianlam** [comment]
:+1: thanks @nhlpl

**Comment by zombachu** [comment]
@julianlam @nhlpl Ah, thanks! That's exactly what I was looking for. I tried searching for an existing plugin but couldn't find anything through the ACP's interface.

@julianlam @psychobunny Should I make a new issue on that project with the items on this list that haven't already been added, or should I just leave it here?

**Comment by julianlam** [comment]
Issuing directly against the plugin is best, thanks :smile:
