### ISSUE TITLE
Blank site

### ISSUE THREAD

**Issue by cljnilsson** [NodeBB/NodeBB#5882]
I am trying to test NodeBB locally but I am greeted with a almost entirely blank page.

https://i.gyazo.com/9921de9742d512a11bb98d578bd66558.png

I start the application by using "node app" and I get the following output:
16/8 13:05:05 [9352] - info: NodeBB v1.5.3 Copyright (C) 2013-2017 NodeBB Inc.
16/8 13:05:05 [9352] - info: This program comes with ABSOLUTELY NO WARRANTY.
16/8 13:05:05 [9352] - info: This is free software, and you are welcome to redistribute it under certain conditions.
16/8 13:05:05 [9352] - info:
16/8 13:05:05 [9352] - info: Initializing NodeBB v1.5.3 http://localhost:4567
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
16/8 13:05:08 [9352] - info: [socket.io] Restricting access to origin: http://localhost:*
16/8 13:05:08 [9352] - info: Routes added
16/8 13:05:08 [9352] - info: NodeBB Ready
16/8 13:05:08 [9352] - info: Enabling 'trust proxy'
16/8 13:05:08 [9352] - info: NodeBB is now listening on: 0.0.0.0:4567

I get no error in my mongod window.
2017-08-16T13:05:08.651+0200 I ACCESS   [conn11] Successfully authenticated as princ                                             ipal username on nodebb

And this is my config.json
{
    "url": "http://localhost:4567",
    "secret": "a5d486e1--------------------------",
    "database": "mongo",
    "port": 4567,
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "myusername",
        "password": "mypassword",
        "database": "nodebb"
    }
}

**Comment by barisusakli** [comment]
It seems like you didn't run `./nodebb build` before starting nodebb.
These questions are better suited for https://community.nodebb.org.
