### ISSUE TITLE
npm start is not working 

### ISSUE THREAD

**Issue by Yangyeswar20** [NodeBB/NodeBB#5883]
Hi,
i am using React and gulp js in my project.

while start my application using the command **npm start** or while checking npm version **npm -v** getting below error.

C:\>npm -v
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules
\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external com
mand,
operable program or batch file.
2.15.11

by the way its showing npm version, but i am getting that 'CALL..... error for all npm command.

i tried uninstall and reinstalled the node, again same error.

can someone help to resolve that issue?

![8-17-2017 3-27-18 pm](https://user-images.githubusercontent.com/31096385/29407073-b568d0da-8360-11e7-9ed3-796f25d88dc5.png)
)

**Comment by barisusakli** [comment]
This is not an issue related to NodeBB itself, you can ask these questions on https://community.nodebb.org or stackoverflow.
