### ISSUE TITLE
Hide functionality that a user doesn't have access to

### ISSUE THREAD

**Issue by BartVB** [NodeBB/NodeBB#5885]
An example of this is the 'Flag this post for moderation'. On community.nodebb.org I have this option, I can give a reason why I want to flag this post and when I try to send the report I get:

`You do not have enough reputation to flag this post`

That's fine, but this frustrates users and hiding functionality like this makes the interface easier to use for new users.

**Comment by MegaGM** [comment]
+in the popup on a user's page ![](http://i.imgur.com/9poXu56.png)
