### ISSUE TITLE
Opening multiple tabs of NodeBB will open multiple composer windows if composer is open on one

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5886]
**Steps**:

1. Open NodeBB, open composer
1. Open NodeBB in another tab

**Expected**: NodeBB to load

**Observed**: NodeBB loads and composer opens, so composer is open on both tabs

----

Possible resolutions:

1. Inhibit opening of draft if composer is already open (need to track open state but also update when tab closed?)
1. Update composer contents across all open tabs

**Comment by pauljherring** [comment]
This was going to be something I was going to raise, but never got round to; its an inconvenience on desktop. It's impossible on mobile where the whole screen is the composer and the only apparent option is to discard (with the fear that doing so in the second tab might discard or invalidate the composer in the first. )

Use case: open 2nd mobile tab to copy something else from the thread.
