### ISSUE TITLE
[Request] Option to refresh page when connection is lost

### ISSUE THREAD

**Issue by aStonedPenguin** [NodeBB/NodeBB#5895]
A lot of people use Cloudflare and other services that present a challenge page when a DDoS attack or any other sort of suspicious action occurs. When this happens NodeBB becomes unusable until the page has been completely refreshed and the user has passed the challenge page. Most users however do not know all they need to do is refresh the page and are left wondering why nothing will load.

A simple setting to completely refresh the page after X failed re-connection attempts would remedy this.

As simple as it is, as unique of an issue it is and considering how many people use services like Cloudflare this should be an option in NodeBB.

**Comment by julianlam** [comment]
>A simple setting to completely refresh the page after X failed re-connection attempts

The problem with this strategy is that you're assuming that a hard reload will fix the connection issue after a number of failed reconnection attempts, when more often than not, the server's just plain **down** and an f5 will lead to a "page cannot be found"/"page could not be loaded" error, which is arguably worse.

Imagine a scenario where a user is reading a long paragraph and server disconnects, and after a number of failed reconnections, the page reloads and the user loses his place. :grimacing: 

Does this happen often with your site? If it does, can you please send a HAR so we can inspect the requests when CloudFlare's DDoS challenge logic kicks in?

There's probably something we can listen for that specifically says "CF is throwing challenge pages now", and can condition again, so we don't reload pages when the server's **down** down.

**Comment by julianlam** [comment]
[Download as HAR, instructions](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)

**Comment by nsuchy** [comment]
As @julianlam said it could cause problems in some cases, however in a Cloudflare like setup where browser check just got activated this could be useful. I'd say add a setting where forum admins can turn the option to offer a hard refresh it on or off.

**Comment by nsuchy** [comment]
On an added note Cloudflare's checking your browser screen returns HTTP Status 503 or if they "CAPTCHA" your request it'll return HTTP Status 403.
