### ISSUE TITLE
Upgraded to 1.5.0, missing buzz.js

### ISSUE THREAD

**Issue by nWidart** [NodeBB/NodeBB#5900]
- **NodeBB version:** 1.5.0
- **NodeBB git hash:** 625fa75decfbcecc7db8b1720528dbd26ca4165a
- **Database type:** mongo
- **Database version:** v2.6.12
- **Exact steps to cause this issue:**

```
# Inside nodebb directory
$ git fetch
$ git checkout v1.5.x
$ ./nodebb upgrade
```

Output up upgrade script:
![image](https://user-images.githubusercontent.com/882397/29665699-9fef0146-88d5-11e7-9a8b-50891c2cbc6a.png)

When trying to login, I'm getting:

```
GET http://forum.asgardcms.com/src/modules/buzz.js?fa9619c9-e5ba-4867-8595-ed43fc865588 

nodebb.min.js?fa9619c9-e5ba-4867-8595-ed43fc865588:8 Uncaught Error: Script error for: buzz
http://requirejs.org/docs/errors.html#scripterror
    at B (nodebb.min.js?fa9619c9-e5ba-4867-8595-ed43fc865588:8)
    at HTMLScriptElement.onScriptError (nodebb.min.js?fa9619c9-e5ba-4867-8595-ed43fc865588:9)
```

- **What you expected:**

Being able to login.

- **What happened instead:**

Error mentioned above.

I read about the changed build process and issue #5452 though not sure what it implies. My nginx config doesn't have anything from the docs:

```
server {
    listen 80;
    server_name forum.asgardcms.com;
    # FORGE CONFIG (DOT NOT REMOVE!)
    include forge-conf/asgardcms.com/server/*;

    location / {
        proxy_pass http://forum.asgardcms.com:4567/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

Edit I added the config from the 1.4.3 blog post, but same error:

```
location ~ ^/assets/(.*) {  
  root /home/forge/nodebb/;
  try_files /build/public/$1 /public/$1 @nodebb;
}

location /plugins/ {  
  root /home/forge/nodebb/build/public/;
  try_files $uri @nodebb;
}
```

It even added  more errors:

```
Uncaught Error: Mismatched anonymous define() module: function (){return n.hljs}
```

The page with full errors can be seen here: http://forum.asgardcms.com/login
The login with github works, and I'm able to access the admin panel. The backend has a bunch of new 404's:

![image](https://user-images.githubusercontent.com/882397/29666491-c5851d5c-88d8-11e7-9be1-56feb15e152d.png)

Thanks,

**Comment by nWidart** [comment]
Found the solution:

Once logged in the backend, I restarted the forum which triggered the asset build process. This should have been done via the upgrade command from my understanding but didn't completely.

No more errors available in console new, and login seems to work.

Some minor styling issues but that's on me to fix. :)

**Comment by julianlam** [comment]
@nWidart Glad to hear the issue was resolved :smile:
