### ISSUE TITLE
RSS Feed Authentication only works for topics/categories not Recent

### ISSUE THREAD

**Issue by king-cat** [NodeBB/NodeBB#5903]
I think this was intended behavior, or at least an oversight, not a bug. I would like to request the Recent feed be added to the capability of using the RSS token.

Alternatively, if someone can give me a rough overview of what needs to be added and where I can do it myself and submit a PR. I tried looking at the original PR for adding rss tokens but so much was added it's unclear what exactly would need to be ported to the recent feed to get it to work.

I'm on nodebb 1.5.3 with redis if that matters.

**Comment by julianlam** [comment]
I don't believe the `/recent` branch is hidden from guests, so it is always accessible. Hence no need for the user auth token. Correct me if I'm wrong :smile:

**Comment by zetas** [comment]
That recent branch is not hidden no, but it wont show any posts that aren't visible to guests so... it kinda is hidden lol. You just get an empty response.

**Comment by king-cat** [comment]
That recent branch is not hidden no, but it wont show any posts that aren't visible to guests so... it kinda is hidden lol. You just get an empty response.
