### ISSUE TITLE
[Documentation Update] - Ubuntu LTS install, systemd config

### ISSUE THREAD

**Issue by mrbc42** [NodeBB/NodeBB#5910]
- **NodeBB version:**  v1.5.3.
- **NodeBB git hash:** b1b02bda7e253e316cafc85c7ca9189c2b15f463

- **Database type:** mongo
- **Database version:** 3.2.16

- **Exact steps to cause this issue:**
Referring to current install docs located here: [nodebb-systemd](https://docs.nodebb.org/configuring/running/)

1. Instructions dont work for systemd (auto start on reboot) due to config file error.
2. [service] section of config file should look like this 
```
[Service]
Type=simple
User=nodebb

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=nodebb

Environment=NODE_ENV=production
WorkingDirectory=/opt/nodebb
ExecStart=/usr/bin/node loader.js --no-daemon --no-silent
Restart=always
```
instead of this
```
[Service]
Type=simple
User=myuser
WorkingDirectory=/path/to/nodebb
ExecStart=/path/to/nodebb/nodebb --no-silent --no-daemon
Restart=always
```

- **What you expected:** expected nodebb to auto restart after server reboot.

- **What happened instead:**  With current published config in [docs,](https://docs.nodebb.org/configuring/running/) systemd did not autorestart nodebb on Ubuntu LTS (currently 16.04.3) after reboot.

Copied this config from [here](https://community.nodebb.org/topic/10648/nodebb-service-failing-to-start-after-server-reboot) so it may need to be vetted by someone smarter than me to be sure its 100% correct.

Once the extra lines were added in the config, systemd worked as expected and nodebb came up automatically after server reboot.

**Comment by julianlam** [comment]
Thanks. The placeholders will be kept since they're different on all installs, although the /usr/bin/node I've replaced with `/usr/bin/env node`. Testing now...
