### ISSUE TITLE
Forum search with ".92" results in server restart

### ISSUE THREAD

**Issue by cetkoprodanovic** [NodeBB/NodeBB#5911]
- **NodeBB version:**  v1.5.3.
- **NodeBB git hash:** d76a67a084f95cf569a9ca8516a6fb20c8929bfd

- **Database type:** redis
- **Database version:** 3.2.3

- **Exact steps to cause this issue:** One of our users searched for ".92" string on forum

- **What you expected:** Expected normal execution of search operation. App expected to work normal. 

- **What happened instead:** NodeBB server restarted.

**Comment by barisusakli** [comment]
Can you post the stack trace from logs/output.log

**Comment by cetkoprodanovic** [comment]
31/7 07:39:39 [16209] - error: NodeBB address in use, exiting...
[cluster] Child Process (16209) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
31/7 07:39:39 [16228] - info: Initializing NodeBB v1.5.3
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
31/7 07:39:41 [16228] - info: [socket.io] Restricting access to origin: http://forums.powerarchiver.com:*
31/7 07:39:41 [16228] - warn: [plugins/nodebb-plugin-spam-be-gone] Hook `action:flag.create` is deprecated, please use `action:flags.create` instead.

31/7 07:39:41 [16228] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-markdown
  * nodebb-plugin-blog-comments

31/7 07:39:41 [16228] - info: [Newsletter] Initializing Newsletter...
31/7 07:39:41 [16228] - info: [plugins/spam-be-gone] Settings loaded
31/7 07:39:41 [16228] - info: Routes added
31/7 07:39:41 [16228] - info: NodeBB Ready
31/7 07:39:41 [16228] - info: Enabling 'trust proxy'
31/7 07:39:41 [16228] - error:  Error: listen EADDRINUSE 0.0.0.0:4567
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
31/7 07:39:41 [16228] - error: NodeBB address in use, exiting...
[cluster] Child Process (16228) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
31/7 07:39:42 [16256] - info: Initializing NodeBB v1.5.3
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
31/7 07:39:43 [16256] - info: [socket.io] Restricting access to origin: http://forums.powerarchiver.com:*
31/7 07:39:43 [16256] - warn: [plugins/nodebb-plugin-spam-be-gone] Hook `action:flag.create` is deprecated, please use `action:flags.create` instead.

31/7 07:39:44 [16256] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-markdown
  * nodebb-plugin-blog-comments

31/7 07:39:44 [16256] - info: [Newsletter] Initializing Newsletter...
31/7 07:39:44 [16256] - info: [plugins/spam-be-gone] Settings loaded
31/7 07:39:44 [16256] - info: Routes added
31/7 07:39:44 [16256] - info: NodeBB Ready
31/7 07:39:44 [16256] - info: Enabling 'trust proxy'
31/7 07:39:44 [16256] - error:  Error: listen EADDRINUSE 0.0.0.0:4567
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
31/7 07:39:44 [16256] - error: NodeBB address in use, exiting...
3 restarts in 10 seconds, most likely an error on startup. Halting.

NodeBB v1.5.3 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

1/8 03:42:23 [16578] - info: Initializing NodeBB v1.5.3
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
1/8 03:42:24 [16578] - info: [socket.io] Restricting access to origin: http://forums.powerarchiver.com:*
1/8 03:42:24 [16578] - warn: [plugins/nodebb-plugin-spam-be-gone] Hook `action:flag.create` is deprecated, please use `action:flags.create` instead.

1/8 03:42:25 [16578] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-markdown
  * nodebb-plugin-blog-comments

1/8 03:42:25 [16578] - info: [Newsletter] Initializing Newsletter...
1/8 03:42:25 [16578] - info: [plugins/spam-be-gone] Settings loaded
1/8 03:42:25 [16578] - info: Routes added
1/8 03:42:25 [16578] - info: NodeBB Ready
1/8 03:42:25 [16578] - info: Enabling 'trust proxy'
1/8 03:42:25 [16578] - error:  Error: listen EADDRINUSE 0.0.0.0:4567
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
1/8 03:42:25 [16578] - error: NodeBB address in use, exiting...
[cluster] Child Process (16578) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
1/8 03:42:25 [16607] - info: Initializing NodeBB v1.5.3
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
1/8 03:42:27 [16607] - info: [socket.io] Restricting access to origin: http://forums.powerarchiver.com:*
1/8 03:42:27 [16607] - warn: [plugins/nodebb-plugin-spam-be-gone] Hook `action:flag.create` is deprecated, please use `action:flags.create` instead.

1/8 03:42:27 [16607] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-markdown
  * nodebb-plugin-blog-comments

1/8 03:42:27 [16607] - info: [Newsletter] Initializing Newsletter...
1/8 03:42:27 [16607] - info: [plugins/spam-be-gone] Settings loaded
1/8 03:42:27 [16607] - info: Routes added
1/8 03:42:27 [16607] - info: NodeBB Ready
1/8 03:42:27 [16607] - info: Enabling 'trust proxy'
1/8 03:42:27 [16607] - error:  Error: listen EADDRINUSE 0.0.0.0:4567
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
1/8 03:42:27 [16607] - error: NodeBB address in use, exiting...
[cluster] Child Process (16607) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
1/8 03:42:28 [16622] - info: Initializing NodeBB v1.5.3
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
1/8 03:42:29 [16622] - info: [socket.io] Restricting access to origin: http://forums.powerarchiver.com:*
1/8 03:42:29 [16622] - warn: [plugins/nodebb-plugin-spam-be-gone] Hook `action:flag.create` is deprecated, please use `action:flags.create` instead.

1/8 03:42:30 [16622] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-markdown
  * nodebb-plugin-blog-comments

1/8 03:42:30 [16622] - info: [Newsletter] Initializing Newsletter...
1/8 03:42:30 [16622] - info: [plugins/spam-be-gone] Settings loaded
1/8 03:42:30 [16622] - info: Routes added
1/8 03:42:30 [16622] - info: NodeBB Ready
1/8 03:42:30 [16622] - info: Enabling 'trust proxy'
1/8 03:42:30 [16622] - error:  Error: listen EADDRINUSE 0.0.0.0:4567
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
1/8 03:42:30 [16622] - error: NodeBB address in use, exiting...
[cluster] Child Process (16622) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
1/8 03:42:30 [16650] - info: Initializing NodeBB v1.5.3
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
1/8 03:42:32 [16650] - info: [socket.io] Restricting access to origin: http://forums.powerarchiver.com:*
1/8 03:42:32 [16650] - warn: [plugins/nodebb-plugin-spam-be-gone] Hook `action:flag.create` is deprecated, please use `action:flags.create` instead.

1/8 03:42:32 [16650] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-markdown
  * nodebb-plugin-blog-comments

1/8 03:42:32 [16650] - info: [Newsletter] Initializing Newsletter...
1/8 03:42:32 [16650] - info: [plugins/spam-be-gone] Settings loaded
1/8 03:42:32 [16650] - info: Routes added
1/8 03:42:32 [16650] - info: NodeBB Ready
1/8 03:42:32 [16650] - info: Enabling 'trust proxy'
1/8 03:42:32 [16650] - error:  Error: listen EADDRINUSE 0.0.0.0:4567
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
1/8 03:42:32 [16650] - error: NodeBB address in use, exiting...
3 restarts in 10 seconds, most likely an error on startup. Halting.

**Comment by barisusakli** [comment]
Looks like your forum is restarting because there is something else listening on port 4567. Try ./nodebb stop and ./nodebb start again.
