### ISSUE TITLE
SortedSet negative range inconsistencies.

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#5912]
- **NodeBB version:** 1.5.3
- **NodeBB git hash:** 4dc23c4dfeef9c19163097e5156124d217efdd72

- **Database type:** mongo or redis
- **Database version:** Mongo v3.2.13

- **Exact steps to cause this issue:**

Call getSortedSetRange or getSortedSetRevRange with a negative range. e.g.
`db.getSortedSetRange('key', -15, -1, callback)`

- **What you expected:**

Should return the range as described in redis docs: https://redis.io/commands/zrange

- **What happened instead:**

Using redis, it works as expected, but when using Mongo it returns an error:
`MongoError: skip value must be non-negative`

**Comment by pitaj** [comment]
So that would get the last 14 (15?) items in the list? Looks like we'd have to get the length of the list in mongo and then calculate the skip parameter.

Or we could `getSortedSetRevRange('key', 0, 15)` and reverse the result.

**Comment by yariplus** [comment]
Yes, (14).

```Or we could getSortedSetRevRange('key', 0, 15) and reverse the result.```

This is what I'm doing now. We would have to do some manipulation of the numbers. So (-15, -1) would become (0, 14)

```
redis> ZRANGE myzset 0 2
1) "one"
2) "two"
3) "three"
redis> ZREVRANGE myzset 0 1
1) "three"
2) "two"
redis> ZRANGE myzset -2 -1
1) "two"
2) "three"
```

**Comment by yariplus** [comment]
Of course, the other option would be to just return an error in redis, to make usage consistent.
