### ISSUE TITLE
Digest email stuck on old version if Settings -> Email is ever saved

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5914]
**This is a blocker for v1.6.0**

Due to the way the email template override is saved, the digest template will be set as a custom email template in the database, even if it was not actually changed. This has been the case since 21 Sept 2015 (https://github.com/NodeBB/NodeBB/commit/109fe895b3398c7f78020fad628394d3e69c5e37)

Therefore, even after upgrading to v1.6.0, the old digest template will still be used.

It will be either one of:
* https://github.com/NodeBB/NodeBB/blob/75917e25b3b5ad7bed8ed0c36433fb35c9ab33eb/src/views/emails/digest.tpl
* https://github.com/NodeBB/NodeBB/blob/9b02bb8f51f0e47c6e335578f776ffc17bc03537/src/views/emails/digest.tpl
* https://github.com/NodeBB/NodeBB/blob/3314ab4b83138c7ae579ac1f1f463098b8c2d414/src/views/emails/digest.tpl
* ~~https://github.com/NodeBB/NodeBB/blob/4855e6949817211a56f0f57ac1449880afbd13a6/src/views/emails/digest.tpl~~~ Turns out this commit was before 109fe895b3398c7f78020fad628394d3e69c5e37

Recommend an upgrade script to check the digest override and match it to the above four versions (via md5 hash) and clear it if a match is found.

Underlying issue needs to be fixed too, while we're at it, but that can wait until after launch :smile:

**Comment by julianlam** [comment]
This could happen to the `banned` template as well, as that was a new tpl introduced in 1.5.x

**Comment by julianlam** [comment]
Related to #3818, but @barisusakli resolved it so only those four templates will be seen.

**Comment by pitaj** [comment]
Maybe a better fix would be a "use custom template" toggle for each email type. That way we don't need to keep a log of older templates.

**Comment by julianlam** [comment]
You'd still need one because you don't know which templates were custom on purpose. So you'd need to keep a track of the old ones anyways

**Comment by julianlam** [comment]
Confirmed that the hashes are identical on MongoDB as well.
