### ISSUE TITLE
Keep scripts order on the build process.

### ISSUE THREAD

**Issue by revir** [NodeBB/NodeBB#5921]
- **NodeBB version:** v1.5.3
- **NodeBB git hash:** 4dc23c4dfeef9c19163097e5156124d217efdd72

- **Database type:** mongo
- **Database version:** 3.4.1

Some plugins, such as composer-redactor, may rely on the correct client scripts load order, otherwise some variables would be used before defined.

I changed the `async.each` to `async.eachSeries` in the function of `getScripts` of the file src/plugins/data.js. I used this mean:  

    sed -i "s/async.each/async.eachSeries/g"  nodebb/src/plugins/data.js

Could this be a bug of nodebb's build process? Or only me found this problem exists?
Hope this could help.

**Comment by barisusakli** [comment]
Sounds like a bug to me, @pitaj

**Comment by julianlam** [comment]
Ah, initially, I was unsure of whether changing an `each` to an `eachSeries` is the correct approach, but I an mistaken, and it seems to be the correct solution here.

The `getScripts` call merely populates an array of scripts to be passed to the minifier, and the expectation here is to have them be built in the same order they are passed-in by the plugin.

**Comment by julianlam** [comment]
Soundpacks, modules, and static directories are fine to continue using `each`, so only `getScripts` needs to be changed. This is fine to be committed to `master` for v1.6.0.
