### ISSUE TITLE
Missing translation "error:goback"

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5922]
Re: [this commit by @An-dz for the noscript pull request](https://github.com/NodeBB/NodeBB/pull/5565/commits/b773c79f0fd26f1c963fd001810a9d5c2a45b380)

Introduced the language tag `[[error:goback]]` with no corresponding entry in `public/languages/en-GB/error.json`, seems unintentional although am opening this issue to see if @An-dz has any input on what that text was _supposed_ to say.

**This is a blocker for v1.6.0**

**Comment by julianlam** [comment]
Explicitly notifying @An-dz via comment.

**Comment by julianlam** [comment]
Also of note is that the specific change set is:

``` diff
+	<!-- IF returnLink -->
+	<p>[[error:goback]]</p>
+	<!-- ENDIF returnLink -->
```

Which is odd, because if a returnLink is specified, how come there's no `<a>`, just a `<p>` with the "Go back" text?

**Comment by julianlam** [comment]
`returnLink` is explicitly passed as boolean here: https://github.com/NodeBB/NodeBB/blob/4976d1301358573f53862692c84ae3359fe040b7/src/controllers/helpers.js#L29

**Comment by An-dz** [comment]
Sorry, it was holiday here in my country.

Anyway, I don't think it was the right approach, with the `a` tag you are actually going "forward" to a new page, which means you lose all the input you had entered. The message was to instruct the user to use the "back function" on their browser so whatever was typed in the previous page is still there, restored by the browser. Without scripts you don't have `history.go(-1)`.

**Comment by julianlam** [comment]
Thoughts, @pitaj? I did notice that entered text is lost when using that link.

**Comment by pitaj** [comment]
I don't see any other option besides just not having the link.

**Comment by julianlam** [comment]
@an-dz is suggesting we simply instruct the user to press "back" so form inputs are preserved.
