### ISSUE TITLE
How do we implement SSO when our apps login system is not OAuth based but JWT based?

### ISSUE THREAD

**Issue by aligajani** [NodeBB/NodeBB#5926]

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!

**Comment by julianlam** [comment]
You'll want to use [nodebb-plugin-session-sharing](https://github.com/julianlam/nodebb-plugin-session-sharing) :smile:
