### ISSUE TITLE
.jst content-type is incorrect

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#5934]
Should be `application/javascript`, currently it's `application/octet-stream`

**Comment by tehspaceg** [comment]
It looks like CSS is impacted too. It might be worth either changing the proxy config settings to specify the content type, or set it on the file end. Proxy config might be an easier stop gap.

https://community.nodebb.org/topic/11228/browser-console-errors-after-v1-6-0-upgrade/

**Comment by pitaj** [comment]
If you do have the `/assets` block in nginx this will happen I think, because there's no content type to be forwarded so it has to guess itself.

**Comment by tehspaceg** [comment]
I've got the ```/asset``` block per the documentation for NodeBB.

**Comment by gramakri** [comment]
We hit this in the cloudron app as well. Cloudron sets the 'nosniff' header in the reverse proxy. Removing the header works around the issue but this is not viable for Cloudron because those headers are set across all apps. Is there any other workaround other than removing this header?

**Comment by pitaj** [comment]
You have to set the content-type for `.jst` files to be `application/javascript`

**Comment by julianlam** [comment]
@pitaj shouldn't *we* be setting this mine type?

**Comment by julianlam** [comment]
MIME :rage2:

**Comment by gramakri** [comment]
Just guessing here: since nodebb seems to use the 'mime' module and I cannot find .jst listed in https://github.com/broofa/node-mime/tree/master/types, it seems we have to use https://github.com/broofa/node-mime#mimedefinetypemap-force--false ? I can give this a shot later today if my guess is anywhere correct :)

**Comment by pitaj** [comment]
I've been working on doing that, I was just saying if they wanted a better temporary solution.

**Comment by gramakri** [comment]
Thanks for the fix! Will this be applied to the 1.6.x branch?

**Comment by julianlam** [comment]
@gramakri No, it will be applied in v1.6.1, to be launched 11 October.

**Comment by gramakri** [comment]
Thanks for the release. I can confirm the fix work on the Cloudron.
