### ISSUE TITLE
Test Email inconsistencies | Dummy Data vs Real Data

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5936]
Just noticed this, when sending test emails because the new templates look so good 😄 
Every template is being sent, just not the digest template.
Tested on 1.6.0

**Comment by julianlam** [comment]
Actually they do, they just aren't getting sent because there are no new topics in the past day for you... It's a silly limitation that we ought to get fixed :smile:

**Comment by RoiEXLab** [comment]
😄 
All other mails just send dummy test data, but this one actually requires posts?
Well that's what I call inconsistent ^^

**Comment by julianlam** [comment]
They used to send dummy data... If at all possible we try to send real data so the test email contains real:tm: content

Not all of the templates are updated to send real data, however :smile:

**Comment by RoiEXLab** [comment]
I'll edit the issue then
