### ISSUE TITLE
Websocket: Single Click is logged multiple times in the console

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5937]
Noticed in 1.6.0:
The Server is behind an Nginx-Reverse-Proxy (that connects via HTTPS 1.1 to node, but accepts HTTP 2 connections) if that changes anything.

When clicking the Save button *_ONCE_* in the ACP Widget menu, I get the following server log:
[Gist](https://gist.github.com/RoiEXLab/bcfc7449318231ce97dcdbbaff0a48cb)
Best case: Some of the logging is buggy (jounralctl log btw.)
Worst case: The request is actually sent multiple times and uses up uneccessary resources

I observed similar behaviour in other parts of the ACP as well.
Socket.io protocols are of course active

**Comment by julianlam** [comment]
... that's a lot of logs :grimacing:

**Comment by RoiEXLab** [comment]
Well for most cases it's just printed 2-5 times, but when I explicitly created an example it was this extreme ^^

**Comment by RoiEXLab** [comment]
I moved the log to a gist, in order to keep this issue readable

**Comment by RoiEXLab** [comment]
Thanks @barisusakli 👍
I'd appreciate it if you could have a look at my PR over at the widget-essentials Repository

**Comment by RoiEXLab** [comment]
@barisusakli Perhaps wort noting that the following logs are still being logged multiple times:
```
io: 0 on [ { type: 2,
    nsp: '/',
    id: 28,
    data: [ 'plugins.mentions.listGroups' ] } ]
```
and
```
io: 0 on [ { type: 2, nsp: '/', id: 26, data: [ 'meta.rooms.leaveCurrent' ] } ]
```
Not that big of a deal though

**Comment by barisusakli** [comment]
Yeah those are meant to be called multiple times afaik.

**Comment by RoiEXLab** [comment]
Yes, but shouldn't the logs differ then?
Instead of printing the exact same thing x times?

**Comment by barisusakli** [comment]
Not sure, plugins.mentions.listGroups probably happens in the autocomplete dropdown of mentions, is it getting triggered on every keypress? If so it can be cached and only called once when the dropdown opens.

meta.rooms.leaveCurrent should be called whenever you switch pages

plugins.composer.renderPreview' should be called whenever a change happens in composer text

**Comment by RoiEXLab** [comment]
I'm not sure when exactly they're being triggered, but I'm pretty sure they are being logged multiple times per page.
I will check this later
