### ISSUE TITLE
Client side widget handling doesn't translate the widget HTML

### ISSUE THREAD

**Issue by voanhcuoc** [NodeBB/NodeBB#5942]
**NodeBB version:** 1.5.2

I create a plugin containing a widget with render-function:

```javascript
plugin.renderButton = function renderButton(widget, callback) {
  widget.req.app.render('widgets/button', (err, html) => {
    if (err) throw err;
    widget.html = html;
    callback(null, widget);
  });
};
```

The template is rendered successfully. But it isn't translated as I had expected.
In [src/middleware/render.js](https://github.com/NodeBB/NodeBB/blob/master/src/middleware/render.js#L90) , it seem like `res.render` is for rendering whole page only with header and footer. Using `widget.res.render` failed to render widget template.

So I think `app.render` should be altered to execute translation.

**Comment by pitaj** [comment]
I think that widgets are only _not_ translated if they're inserted after load. For instance, the global sidebar widgets are inserted with JS after the page loads, so they aren't translated. Widgets in, for instance, the global header on persona, are translated.

This issue is caused by [widgets.js line 44](https://github.com/NodeBB/NodeBB/blob/master/public/src/widgets.js#L44) not translating the HTML before insertion.

**Comment by voanhcuoc** [comment]
You're right, from v1.5.3 widget are translated client-side. It solve my issue.

And widgets are all inserted client-side so javascript turned on is needed anyway.

In the future, if server-side insertion is implemented (when javascript is disable), _translation should happen in app.render_.

**Comment by pitaj** [comment]
I think all widget areas _but the global sidebar_ in Persona are inserted from the server side, and are translated. I tested this by putting `You are on the {title} page` in an HTML widget in the global header. In most cases, like on the categories page, title is a translation token like `[[pages:categories]]`. This is translated when I access every page. I also put an identical widget in the global sidebar, and that one is _not_ translated.

**Comment by voanhcuoc** [comment]
Ok, it works magically one more time. Idk what to say.

**Comment by pitaj** [comment]
I'm going to re-open this under a different name as a reminder to fix the client-side global untranslated issue.
