### ISSUE TITLE
Manually invoke server-side translation in plugin

### ISSUE THREAD

**Issue by voanhcuoc** [NodeBB/NodeBB#5943]
**NodeBB version:** 1.5.2, 1.5.3, 1.6.0

Reproduce: Manually invoke `translator.translate` in plugin server-side code
- When `defaultLang` is present, keys is always translated to `defaultLang`, whichever language is in user setting.
- When `defaultLang` is not present, translation failed.

Expect: translate to language in user setting

**Comment by pitaj** [comment]
What is your test case? On server-side, the default falls back to the server's `defaultLang` set in the aCP, not the user's `defaultLang`

**Comment by julianlam** [comment]
As @pitaj says, we need more info... that is, what language key are you translating... core translation key or one specific to a plugin? They are handled differently...

**Comment by voanhcuoc** [comment]
Translation key in the same plugin as `translator.translate` invocation. 
I suppose it _should_ always resolve to _the language in user setting_ . 
Otherwise plz provide option to explicitly declare which one: `user`, `default`, `pluginDefault`, 'fr', 'vi', ...

**Comment by pitaj** [comment]
Please provide what key you used, what you expected to happen, what actually happened, and other specific information related to the translation like your plugin setup, the userLang, and defaultLang

**Comment by voanhcuoc** [comment]
`plugin.json`

```json
  "library": "./library.js",
  "languages": "language",
  "defaultLang": "en-US"
```

`language/en-US/test.json`

```json
  "greeting": "Hi there !"
```

`language/fr/test.json`

```json
  "greeting": "Salut !"
```

`language/vi/test.json`

```json
  "greeting": "Xin chào !"
```

_ACP setting:_ `fr`

_User setting:_ `vi`

Anywhere in the server code, e.g. in `library.js` :

```javascript
const translator = module.parent.require('../public/src/modules/translator');
translator.translate('[[test:greeting]]', (translated) => {
   console.log(translated)
});
```

#### What happened

* all language files went to the build directory `build/public/language`
* `translated` is `"Hi there !"` , i.e. plugin's `defaultLang` , although both language in user and ACP settings is present

#### What I expected

* `translated` is `"Xin chào"` , i.e. user setting language
* if there isn't (`language/vi/test.json` removed) , fallback to ACP setting language
* if there isn't too (`language/fr/test.json` removed) , fallback to plugin's `defaultLang`

#### Suggestion

If second argument passed to `translator.translate` is a `String` but not a `Function`, it's considered the language to translate to, then `callback` will be the third argument:

```javascript
// Specific language
translator.translate('[[test:greeting]]', 'fr', (translated) => {
  console.log(translated)
})
// => Salut !

// User setting
translator.translate('[[test:greeting]]', 'userLang', (translated) => {
  console.log(translated)
})
// => Xin chào !

// ACP setting
translator.translate('[[test:greeting]]', 'acpLang', (translated) => {
  console.log(translated)
})
// => Salut !

// Current API left intact
translator.translate('[[test:greeting]]', (translated) => {
  console.log(translated)
})
// => Hi there !
```

**Comment by pitaj** [comment]
That's how it currently works, besides the `userLang` and `acpLang` keywords.

**Comment by pitaj** [comment]
It uses `translator.getLanguage()` to decide what language to use. I would check what that is. Also, check the associated language files in `build/public/language`

**Comment by voanhcuoc** [comment]
All language files is present in `build/public/language`

**Comment by pitaj** [comment]
No, I mean, check what they contain. Make sure the `fr` file has the expected values.

**Comment by voanhcuoc** [comment]
All files contain expected value.
BTW, I found an (ugly) way out, here's the simplest widget renderer possible that take a template and translate it:

```javascript
plugin.renderLeechButton = (widget, callback) => {
  const req = widget.req;
  const app = req.app;
  const uid = req.uid;
  app.render('widgets/leech-button', (err, html) => {
    user.getSettings(uid, (err, settings) => {
      const userLang = req.query.lang || settings.userLang;
      translator.translate(html, userLang, (translatedHTML) => {
        widget.html = translatedHTML;
        callback(err, widget);
      });
    });
  });
};
```

How hassle !

Translation should be automatic #5942

**Comment by pitaj** [comment]
> `translated` is `"Hi there !"` , i.e. plugin's `defaultLang`, although both language in user and ACP settings is present

I'm gonna add some tests for the ACP `defaultLang` not applying and see if I can confirm that bug.

> Update : WAT, it's actually implemented , why deprecate it at all ? Please left it intact ! Dev need a way to explicitly declare what language to translate to.

Specifying a language in `translator.translate` is not deprecated. `TODO: Deprecate?` in the source means *"Maybe we will deprecate this some day"*, in which case you'd use `Translator.create(language).translate(...)` which is used within the older `translator.translate(...)`, an API provided for backwards compatibility.

**Comment by voanhcuoc** [comment]
Hey, it works correctly, translating to ACP `defaultLang`.
Shame on me, idk what I did wrong in the first place.
`Translator` can get to the request context, so it cannot automatically get `userLang`. It's natural.

Tks u very much for kindly support.
