### ISSUE TITLE
Pagination settings don't take

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#5944]
1,6
- **NodeBB git hash:** 02370b30d934006fe1db8575cccf6a42ac71431e

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**

1. Went to settings
2. Changed the topics per page and posts per page to 50 and click save. 
3. After refresh the values revert back to 20. 
- **What you expected:**
I expected the values to remain at 50 and take effect.

- **What happened instead:**

They didn't.  It only shows me 20 topics per page and not 50.

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/blob/master/src/user/settings.js#L109

Takes `Math.min` of the set value or the default, which means it gets overridden in settings page (and possibly more pages?)

**Comment by pitaj** [comment]
Yeah it looks like it should use `Math.max` instead

**Comment by barisusakli** [comment]
@dangerusslee if you want users to be able to go over the 20 limit, you need to change the value in the acp first from 20 to 50, users can only select a value between 1 and  <acp pagination setting>

**Comment by pichalite** [comment]
@barisusakli you should probably add that ACP setting value to the label in user settings page so they know the range. Right now there is no way to tell unless you know what the code is doing.

**Comment by barisusakli** [comment]
@pichalite will do for 1.6.2

**Comment by dangerusslee** [comment]
Shouldn't there be a default and a max in acp?
