### ISSUE TITLE
Allow the use of different template engine in plugin

### ISSUE THREAD

**Issue by voanhcuoc** [NodeBB/NodeBB#5949]
So now I gave up using templates.js. For me it's so confusing.

I've try to use another template engine, but builder throw away files with extension other than `.tpl`. So I ended up parsing template manually.

I expect builder not to skip file by extension in the template dir, which should have only template file at all. So that I can use `app.engine()`  to automatically parse my own template.

**Comment by pitaj** [comment]
I don't think will ever be possible, it would be a serious increase in complexity if we tried to support every single templating engine. What templating engine do you want to use and why?

NodeBB now uses BenchpressJS as the templating engine. It support templates.js syntax while also enabling a new syntax more like other popular templating engines.

It comes with much better documentation compared to templates.js, check it out: 
https://github.com/benchpressjs/benchpressjs/tree/master/docs

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
