### ISSUE TITLE
SMTP Emailer

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#5951]
@Dravere 

- [x] Add option for selecting security setting
- [x] Typo at [emailer.js line 66](https://github.com/NodeBB/NodeBB/blob/master/src/emailer.js#L66)
  `serice` => `service`
- [x] Allow for use without authentication
- [x] Move "custom" setting to top of dropdown
- [x] Update descriptions to tell admin that a restart is required to apply settings
  Possibly make it so restart is not required?
- [x] Update email-local readme to tell admins to use the core ACP settings for the same features

ref NodeBB/nodebb-plugin-emailer-local#18

**Comment by Dravere** [comment]
Do you want this in separate pull-requests? I might have time tomorrow to tackle those issues.

**Comment by pitaj** [comment]
Whatever is easier for you. I might work on some tonight, I'll give you the branch if I do end up working on it.

**Comment by Dravere** [comment]
I started working on this: https://github.com/Dravere/NodeBB/tree/smtp-emailer-issue-5951

First three points are done. Quick question though: How should the translation be done? Should I just add the strings to the en-GB/.../email.json language file? Should I also add them to en-US/.../email.json and since I know German also de/.../email.json? What is the proper procedure?

I'm now also going to start working in a different branch on point four. I'll look into if it is possible to apply those settings without a restart. Would be the nicest.

**Comment by pitaj** [comment]
The proper procedure is only to add them to `en-GB` translation files, and then those changes get propagated through transifex to other languages automatically.

**Comment by julianlam** [comment]
@pitaj @Dravere please be sure to ping me when the PR is merged so I can manually push it up to tx. @nodebb-misty is *supposed* to push changes to `en-GB` up to Transifex, but I don't think it is working right now.

**Comment by julianlam** [comment]
@pitaj Additionally, please relocate the "custom" settings option to the top of the dropdown :smile:

**Comment by Dravere** [comment]
Ok, I think I have also a solution for point four. All it basically needs is to extract the creation of the `fallbackTransport` into its own function. Then call it from `Emailer.registerApp` and from the `pubsub` `conf-update` callback registered in there.

No restart and no reload needed.

I'll provide a pull-request as soon as the other one passes.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/5954 is merged

**Comment by Dravere** [comment]
Pull request suggestion for deprecation notice on the plugin:  https://github.com/NodeBB/nodebb-plugin-emailer-local/pull/19

I would suggest to also release it to NPM so the readme is updated on https://npmjs.com.

**Comment by julianlam** [comment]
v1.0.1 of plugin published

**Comment by julianlam** [comment]
Translations sources pushed.

**Comment by pitaj** [comment]
All done
