### ISSUE TITLE
no support / installation guide is absent for the beginners  

### ISSUE THREAD

**Issue by crocuz** [NodeBB/NodeBB#5952]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

**Comment by pitaj** [comment]
Providing literally zero information beyond the title for such an issue is not how you get changes made. Try again with a new issue.

**Comment by crocuz** [comment]
There are erronious desriptions regarding the installation on windows 10 x64 in all references:
no file or
no such commands or
the path is incorrect.
Nobody will use the system without the correct technical desciptions.
Moreover,
the basic requrements regarding the use of the databases mismatch:
optins: redist / mongodb.
The desrption of the installation of both DB incorrect completely.

**Comment by pitaj** [comment]
https://github.com/NodeBB/docs/issues is a better place for documentation issues. The Windows 10 guide is wrong in many places, and could use a complete overhaul, I agree.

**Comment by crocuz** [comment]
The developer *pitaj* sends** false information regarding above:
Again, it is waste of time to deal with this incomplete product.

**Comment by pitaj** [comment]
The "product" is completely free _if you install it yourself_. We only charge if you use the official hosting services or for other official support.

**Comment by crocuz** [comment]
waste of time

**Comment by pitaj** [comment]
@crocuz if you are having problems with a forum hosted by NodeBB, Inc. you should contact support@nodebb.org 

Github issues are not the place to go for support. If you had read the first line when creating a new issue, you'd have seen this:

> == Github Issues are for bug reports and feature requests only ==
> == Please visit https://community.nodebb.org for other support ==

**Comment by crocuz** [comment]
i do not need to write twise. see your forum at your own site.
