### ISSUE TITLE
Support disassociation of SSO accounts in core

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5955]
Either by simply removing the reference in the database, or potentially allowing it to be done on the remote end as well...

**Comment by a632079** [comment]
Yes, It's a good way to enhance user experience.

-----
And I recommend allow plugins to let user register a account via register page or choose to bind a exist user(While pass the sso and openid is not binded to user)

**Comment by phit** [comment]
👍 should definitely be a thing

**Comment by julianlam** [comment]
Workin' on it :smile:

**Comment by julianlam** [comment]
* [x] Facebook (julianlam/nodebb-plugin-sso-facebook#8c8fce2842a29bb92f9e5f60484a794b433e50a0)
* [ ] Twitter
* [ ] Google

**Comment by julianlam** [comment]
There's also a regression where the associations list in `user/edit` doesn't actually reflect the correct association state, these commits fix that up as well.
