### ISSUE TITLE
Change file save

### ISSUE THREAD

**Issue by natashasweety7** [NodeBB/NodeBB#5960]
Hi, 

I found a website rec voice https://webaudiodemos.appspot.com/Au...der/index.html and I want to change how you save a file audio. When the user close microphone, I want to show me a box dialog "Do you want save audio" Yes or No

Thanks in advance
[Natasha ](https://mindmajix.com/node-js-training)

**Comment by julianlam** [comment]
Hi @natashasweety7 -- unfortunately we do not support this in core, but it would be a custom plugin that would allow this functionality. You can ask for this to be built in our community support forum, helpful members there will provide quotes for you.

Thanks
