### ISSUE TITLE
How to add a translation string?

### ISSUE THREAD

**Issue by sznowicki** [NodeBB/NodeBB#5968]
Hello everone.

How do I add translation string? I'd like to propose new header as in https://github.com/NodeBB/NodeBB/pull/5966 but it's being rejected automatically.

Should I ask someone to add it via transifex or there is some special way to do it?

**Comment by sznowicki** [comment]
The other pull request is not rejected (en/GB file change only). I guess this information should be somewhere in the contribution how to ;)

**Comment by pitaj** [comment]
Just only provide en-GB translations
