### ISSUE TITLE
custom JS in themes need to be wrapped in window load event

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5972]
this is a breaking change for themes? @julianlam

**Comment by julianlam** [comment]
I don't believe so, as the changes have already been made in core.

However if you have custom js relying on globals, then yes, they _do_ need to be wrapped in that event listener.

**Comment by pitaj** [comment]
Maybe we should auto-wrap it?

**Comment by barisusakli** [comment]
It breaks on community since it uses jquery in customjs, gotto wrap or move it before closing body tag

**Comment by pitaj** [comment]
Moving it before closing body tag won't work since the scripts are `async defer` I think.

**Comment by julianlam** [comment]
Pushed to v1.7.0

**Comment by barisusakli** [comment]
#5980
