### ISSUE TITLE
Attempting to upvote own post should show error in addition to showing voting summary window

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5973]
NodeBB/nodebb-theme-persona#379

**Comment by julianlam** [comment]
Best would be to use `app.alertError()` to display a friendly message about this.

Utilise translation keys by creating a new key in `public/language/en-GB`

**Comment by psychobunny** [comment]
> in addition to showing voting summary window

I'm not sure of this, if we're changing things I'd prefer to remove this and have the voting summary window show up only when clicking the number. It's a bit of hoop jumping required to override displaying that modal when I switch the upvote button to "Likes" in certain themes/plugins

**Comment by julianlam** [comment]
Right, makes sense. I just recall the original impetus behind showing the summary window on upvote was because it's better to show "something" instead of an error \*shrugs\*

**Comment by asamolion** [comment]
Hi there, 

I've fixed the issue and created a pull request. Please take a look.

https://github.com/NodeBB/NodeBB/pull/6102
