### ISSUE TITLE
User's fullname not provided

### ISSUE THREAD

**Issue by Sumolari** [NodeBB/NodeBB#5975]
- **NodeBB version:** 1.6.0
- **NodeBB git hash:** 02370b30d934006fe1db8575cccf6a42ac71431e

- **Database type:** mongo
- **Database version:** 2.6.10

- **Exact steps to cause this issue:**

1. Log in with an admin account
2. Enable displaying your full name
3. Set your full name  to something
4. Go to any page displaying your full name (for instance a topic you started)

- **What you expected:** your full name appears

- **What happened instead:** your username appears but your full name doesn't

Additionally when trying to show currently logged in user full name (for instance in user menu next to user status) it is not set regardless user's settings.

Changing `src/middleware/header.js:83` and adding:

```javascript
fullname: '[[global:guest]]',
```

Makes it available.

**Comment by pitaj** [comment]
What do you mean by "header"? Can you provide a screenshot?

**Comment by Sumolari** [comment]
I'm working on a custom theme inheriting from `persona` theme. My themes' `menu.tpl` has something like:

```javascript
<li class="dropdown-menu__user-info">
    <a href="{relative_path}/user/{user.userslug}">
        <p class="name-and-status">
            <i
                component="user/status"
                class="fa fa-fw fa-circle status {user.status}"
            ></i>
            <b class="fullname">{user.fullname}</b>
            {user}
        </p>
        <p class="name">
            <span class="username">@<b>{user.username}</b></span>
        </p>
    </a>
</li>
```

My intention is showing user's full name if they have chosen to make it visible and have it set. My user has both: a non-empty public full name but it is not part of the `user` object that I can use in `menu.tpl`.

This also affects other partials I haven't modified yet like topic's one: my username appears instead of my full name.

**Comment by pitaj** [comment]
So you're saying it isn't provided to that template. Okay.

**Comment by barisusakli** [comment]
I noticed /api/topic always has the `fullname` in the data even if the show full name is turned off in user settings, so that's something else that needs to be fixed.
