### ISSUE TITLE
Absolute symlinks

### ISSUE THREAD

**Issue by IUnknown68** [NodeBB/NodeBB#5979]
**NodeBB version:** 1.6.0
**NodeBB git hash:** 02370b30d934006fe1db8575cccf6a42ac71431e
**Database type:** mongo
**Database version:** 3.4.9

**Steps to reproduce:**

1. Install NodeBB.
2. Move the installation folder to another location
3. Run NodeBB: `./nodebb dev`
4. Open the admin interface
5. Go to "Appearance" -> "Custom HTML & CSS"

**Expected result:** The ACE-editor appears and custom CSS can be entered.
**Actual result:** The editor never loads.
**Cause:** Symlinks in `build/public/src/modules/` (and possibly other locations) are broken.

I understand, that moving a NodeBB installation is not a designated action. However, I think it's good style to use relative symlinks, so in case one actually has to move an installation, it is possible with minimal effort.

**Comment by julianlam** [comment]
If you  move a NodeBB installation, you should run `./nodebb build` again so symlinks are regenerated.

**Comment by IUnknown68** [comment]
@julianlam Ok, understood, thx!
