### ISSUE TITLE
Split up customJS into customJS/customHTML

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5980]
customJS is currently appended directly into `<head>` and is useful for one-off custom js scripts, meta tags, link tags, etc., which is great for users who don't want to commission/create a new theme just to introduce meta tags or something.

However, there are some problems with it:

* It is considered blocking and could potentially impede page load, leading to a longer overall page load time
* It is not currently possible to link out to external scripts that support module-loader detection, because require.js is detected but there is no context for the externally loaded script, so the dreaded [mismatched anonymous define error occurs](http://requirejs.org/docs/errors.html#mismatch)
* The variable is `customJS` and yet we allow HTML?

It is probably a good idea to split this up into separate JS and HTML blocks, some benefits include:

* Being able to asynchronously load custom JS (improving our lighthouse score, see #5733)
* Handy dandy side effect: External scripts included in customHTML that require module loading will finally work, because **require.js will not have been loaded yet**

Unfortunate downside:
* This is a breaking change and so will only appear in v1.7.0

**Comment by julianlam** [comment]
* [ ] Upgrade script to parse out stuff **not** in `<script>` tags into `customHTML`
* [ ] Ensure that external script calls are not parsed out into `customHTML`
* [ ] Support for customHTML in themes and core
* [ ] ACP controls for customHTML

**Comment by julianlam** [comment]
Closed via #5981

**Comment by barisusakli** [comment]
Seems custom JS is not executing on cold load.

**Comment by barisusakli** [comment]
Sample code that doesn't run on cold load
```
$(window).on('action:ajaxify.end', function(ev, data) {
	if (ajaxify.data.template.name === 'categories') {
		alert('you are on categories.tpl');
	}
});
```

**Comment by julianlam** [comment]
Odd, thanks, will take a look

**Comment by julianlam** [comment]
Moving `app.load()` from ajaxify.end to footer.js worked, but this had a negative impact on page load times. Will investigate other solutions but we may have to call it and say `action:ajaxify.end` cannot be used in customJS field.

**Comment by julianlam** [comment]
I reverted the previously linked commit here: ae261e073bd7ee885520db4a9b5e5d492263d897

**Comment by barisusakli** [comment]
Well it _can_ be used, the above code sample just needs to be rewritten to something like this:
```
function doStuffOnPageLoad() {
    if (ajaxify.data.template.name === 'categories') {
        alert('you are on categories.tpl');
    }
}

doStuffOnPageLoad();

$(window).on('action:ajaxify.end', function(ev, data) {
	doStuffOnPageLoad();
});
```

**Comment by julianlam** [comment]
Personally, I'd like to limit the breaking changes, but yeah -- that'd be the changes required if a fix can't be found.
