### ISSUE TITLE
Plugin development - convention over configuration

### ISSUE THREAD

**Issue by voanhcuoc** [NodeBB/NodeBB#5982]
Some suggestion that I would like to see in the next major release.

### plugin.json

Compatible changes:

* `build`: _build root directory_ that contains all code and resource to be loaded, relative to _plugin root directory_, default to `./` (_plugin root directory_). `library`, `less`, `acpLess`, `scripts`, `acpScripts`, `template`, `language`, `staticDirs` will be relative to this directory.
  **Use case:**
  * Without `build`, as usual:
  ```
  lib/
  static/
  languages/
  library.js
  package.json
  plugin.json
  ```
  * `plugin.json`: `{ "build": "dist" }`
  transpile from `src` dir to `dist` dir:
  ```
  src/
  |- lib/
  |- static/
  |- languages/
  |- library.js
  dist/
  |- lib/
  |- static/
  |- languages/
  |- library.js
  .babelrc
  package.json
  plugin.json
  ```
  
* `library`: module that export hook (honestly it should be `entry` or `hooks` or `main`), relative to _build root directory_, default to `library.js` (honestly it should be `entry.js` or `hooks.js` or `main.js`)

* `module`: relative to _plugin root directory_

* `templates`: relative to _build root directory_. Default to `templates/`

* `languages`: relative to _build root directory_. Default to `languages/`

* `staticDirs`: relative to _build root directory_. Default to `[ "static": "static" ]`

* `description`: default to `package.json`'s `description` field.

* `id`: default to `package.json`'s `name` field.

* `url`: default to `package.json`'s `repository -> url`.

Breaking changes:

* `less`: array of less files (without `.less` extension) or directories contains them, that is served to user, relative to _build root directory_, default to `[ "static/client" ]`
  **Use case:**
  Without `less`:
  ```
  <build root>/
  |- static/
  |  |- client.less
  ```
  or
  ```
  <build root>/
  |- static/
  |  |-client/
  |  |  |- a.less
  |  |  |- b.less
  |  |  |- c.less
  // all these files will be loaded
  ```

* `acpLess`: similar to above, default to `[ "static/admin" ]`.

* `scripts`: array of client javascript files (without `.js` extension) or directories contains them (similar to `less`), that is compiled to user bundle. Relative to _build root directory_. Default to `[ "static/client" ]`.

* `acpScripts`: similar to above, default to `[ "static/admin" ]`.
* remove `hooks`: `library` should only export hooks, that we can use naming convention like this:
  ```javascript
  module.exports.static__app_load = function init(params) {}
  // or
  module.exports['static:app.load'] = function init(params) {}
  // if hook functions need a name, it will be the name after `function`, e.g. `init` above
  ```
  I don't see `priority` has any sane usage.

So what ? Without any `plugin.json` at all, we have sane default code base. Want to use transpiler, add `build` property, want to use AMD modules, add `modules` property. 

Want scale up the code base from:

```
static/
|- admin.js
|- admin.less
|- client.js
|- client.less
library.js
package.json
```
to:
```
src/
|- static/
|  |- admin/
|  |  |- main.js
|  |  |- main.less
|  |  |- helpers.js
|  |  |- mixin.less
|  |- client/
|  |  |- main.js
|  |  |- main.less
|  |  |- helpers.js
|  |  |- mixin.less
|- lib/
|- library.js
test/
build/
.babelrc
gruntfile.js
package.json
plugin.json
```
just add a one-line `plugin.json`: `{ "build": "build" }`

**Comment by julianlam** [comment]
In genera, I am **against** convention as I prefer configuration. It is just a user preference, and so this is unlikely to be added. I see the benefits although I feel that personal convention managed via configuration is more fluid and open-ended.

You are of course, free to disagree :smile:

**Comment by voanhcuoc** [comment]
But, as I point out, people still have a way to config their own convention if they want. So this is still open-ended.
