### ISSUE TITLE
About Me / Signature should be disabled for banned users

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#5991]
Currently, a banned user's about me on their profile page will show up, and their signature will be displayed on their posts. These should be disabled if the user is banned.

**Comment by julianlam** [comment]
Makes sense... :+1:

**Comment by pauljherring** [comment]
Make it an option?

1) There may have been long-standing members who have been perma-banned for which this could remove context.
2)  What does this add for short-term bans?

And yes, I do have a couple of people in mind while writing this.
