### ISSUE TITLE
If a custom home page is set in the ACP (General -> Homepage), page is redirected, not directly rendered

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5993]
e.g. if I set the home page to `/user/admin`, then navigating to my forum at http://localhost/forum will redirect me to http://localhost/forum/user/admin.

This doesn't happen if I set the homepage to a non-custom option, like "Recent". Not sure if this is too difficult to resolve for custom pages?

**Comment by Jenkler** [comment]
If it is possible to patch this fairly easy, could we merge this patch to 1.6.1?

**Comment by barisusakli** [comment]
This is difficult to fix for custom pages, it is easy for pages like `recent` because we just call `res.render('recent', data)`. When the custom page is `/user/admin`  `res.render('/user/admin', data);`  does not work since there is no template named '/user/admin`.

**Comment by pitaj** [comment]
We could overwrite `req.url`

**Comment by Jenkler** [comment]
But when we specify the template /user/admin in custom pages the template shoud exist or is that a special template? 
Why not do as in the old custom homepage plugin with a static page called something like homepage.tpl and write in the doc that homepage is used for the / page!
Overwriting req.url sounds like a quickfix if that works.

**Comment by barisusakli** [comment]
@Jenkler try custom-homepage@0.2.3 it should work on 1.6.0+

**Comment by Jenkler** [comment]
Thanks @barisusakli, Yes custom-homepage@0.2.3  works for 1.6.1 :)
But it would be nice to have one plugin for all if that would be possible.

So what do we think, is it possible to get custom-pages to work this way also? Or is it a downside to modify nodebb core to fix this?
