### ISSUE TITLE
Connecting and disconnecting to NodeBB repetitively

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#5995]
- **NodeBB version:** 1.6.1
- **NodeBB git hash:** master version
- **Database type:** mongo
- **Database version:** 3.2

- Exact steps to cause this issue:

With all browsers, trying to open the forum.

- **What you expected:**

See no error after opening the page.

- **What happened instead:**

After opening the page, facing with losing connection error: 

![2017-10-19_232433](https://user-images.githubusercontent.com/31972226/31791424-59fe19a2-b525-11e7-8ce8-487896f16016.png)

I found an error in browser Console, I think it might be helpful: 

````
api/user/%D9%87%D9%85%D9%81%DA%A9%D8%B1%DB%8C Failed to load resource: the server responded with a status of 404 (Not Found)
cs.js:34 Uncaught TypeError: str.replace is not a function
at Object.trim (cs.js:34)
at Object.getText (cs.js:128)
at HTMLDocument.mousedown (cs.js:60)

**Comment by pitaj** [comment]
That doesn't look like the whole error. When did this start happening?

Is the `url` value in config.json exactly the same as the URL at which you access your site?

**Comment by mohammadhassan99** [comment]
@pitaj 

> That doesn't look like the whole error. When did this start happening?

One of our users has been involving with this problem for nearly 6 hours. Notice that It doesn't happen all the time but when It happens, It is continuously.

> Is the url value in config.json exactly the same as the URL at which you access your site?

Yes, they are same.

**Comment by julianlam** [comment]
Just one? If that's the case then it's an issue with them, not NodeBB. Check for server side error logs, maybe NodeBB is crashing

Closing this as it is likely not a defect and better served in our community forum.

**Comment by julianlam** [comment]
I'd advise you to start a topic there if you have not already... And paste link to forum please, that may be helpful
