### ISSUE TITLE
isPrimary and isCluster no longer work

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#5998]
due to changes in nconf, `nconf.get('isPrimary')` no longer gets the correct value, `nconf.get('isprimary')` works

**Comment by pitaj** [comment]
Reminder to add tests

**Comment by barisusakli** [comment]
regressed here https://github.com/NodeBB/NodeBB/commit/d98b3e8056e8dd049292e1d816ca7b71139230de
