### ISSUE TITLE
JSON strings inserted into template must not be escaped

### ISSUE THREAD

**Issue by voanhcuoc** [NodeBB/NodeBB#6004]
- **NodeBB version:** 1.6.1

- **Exact steps to cause this issue:**
1. Assign any string with `"` character to any property of `config` object on server
```javascript
// hook `filter:config.get`
export const appendConfig = (config, callback) => {
  config.test = { quote: '"' };
  callback(null, config);
}
```
2. Go to browser and load any page.
3. Inspect

- **What you expected:** global `config` is parsed normally

- **What happened instead:** parse error at `"` character ([here](https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/header.tpl#L12)), so global `config` is `undefined`

Look like the template engine unescaped json strings before insert, which should have been left intact as it was already formatted properly by `JSON.stringify` to be parsed by `JSON.parse`.

P/S: Any single-quote will also break the code, as it break JSON string down to pieces
```javascript
var config = JSON.parse('{ "test": "'123'" }');
```

JSON strings shouldn't be inserted directly to code. It should be loaded via ajax and trigger `action:config.loaded` hook.

**Comment by barisusakli** [comment]
@voanhcuoc let me know if above commit fixes your issue, we want to load the config on cold load since quite a bit of client side code and plugins might depend on it, loading the page and then making another ajax request to load the config would just delay all that stuff.

While debugging this I also noticed another fix but it requires changing the header.tpl for all themes. It looks like this in header.tpl

```
<script id="config-data" type="application/json">{{configJSON}}</script>
<script>
...
var config = JSON.parse(document.getElementById('config-data').innerHTML);
...
</script>
```
With this '"' and ''' work without escaping.

**Comment by voanhcuoc** [comment]
Parse error with different character.

I think more `replace`s is not the way out. It will let to more subtle bugs.

I suggest the use of `jsesc`

```
> jsesc = require('jsesc')
{ [Function: jsesc] version: '2.5.1' }
> o = {test:{quote:'"'}}
> console.log(jsesc(JSON.stringify(o)))
{"test":{"quote":"\\""}}
undefined
> JSON.stringify(o)
'{"test":{"quote":"\\""}}'
```

**Comment by barisusakli** [comment]
@voanhcuoc switched to jsesc, what was the character that caused the parse error?

**Comment by voanhcuoc** [comment]
Fixed. Thanks.
The former parse error cause by `/`, that is `replace`d by `\/`.

**Comment by voanhcuoc** [comment]
Wait. You forgot the admin header.
