### ISSUE TITLE
Custom Header HTML descriptor is wrong

### ISSUE THREAD

**Issue by maenthoven** [NodeBB/NodeBB#6006]
- **NodeBB version:** 1.6.x

Descriptor says the following:

> Enter custom HTML here (ex. JavaScript, Meta Tags, etc.), which will be appended to the `<head>` section of your forum's markup.

This is simply incorrect given that the HTML is inserted into the `<body>` tag.

**Comment by julianlam** [comment]
The HTML is added before the head tag, if you put in HTML that doesn't belong there, browsers tend to move it into the body element. Check your page source?

Either way this gets refactored heavily in develop anyway so it's a non issue.

**Comment by julianlam** [comment]
Thank you for reporting however 🙂
