### ISSUE TITLE
Admin CP hovering over things breaks it and makes it have a black background, causing graphical bugs

### ISSUE THREAD

**Issue by Kaydax** [NodeBB/NodeBB#6007]
- **NodeBB version: 1.6.1** 
- **NodeBB git hash: 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf** 

- **Database type: Mongo** mongo or redis
- **Database version: v3.4.9** 

- **Exact steps to cause this issue:**
My problem is that when i hover over things a black background appears, sometimes it gets worse if I do it too much.

1. Goto ACP
2. Goto a place like the categories and edit one.
3. Try to select an icon
- **What you expected:**

For it to work like normal and not bug out
- **What happened instead:**
This is what happens: 
![image](https://user-images.githubusercontent.com/11893096/31978966-30847832-b912-11e7-8c4d-e20dbe75eeb6.png)

**Comment by julianlam** [comment]
Any custom themes and/or plugins? `./nodebb plugins`

**Comment by Kaydax** [comment]
I am using only stock plugins apart from NodeBB Material Theme, but even when I have the default theme it still causes this issue.

Here is the plugins list though:
`         - nodebb-theme-material
         - nodebb-plugin-composer-default
         - nodebb-plugin-markdown
         - nodebb-plugin-mentions
         - nodebb-widget-essentials
         - nodebb-rewards-essentials
         - nodebb-plugin-soundpack-default
         - nodebb-plugin-emoji-extended
         - nodebb-plugin-emoji-one
         - nodebb-plugin-dbsearch
         - nodebb-plugin-spam-be-gone
`

**Comment by Kaydax** [comment]
The material theme does not change Admin CP

**Comment by pitaj** [comment]
What browser? Can you try a different browser? Try incognito / private mode in your browser, as well.

**Comment by Kaydax** [comment]
It seems to only be doing it on Chrome 61

**Comment by pitaj** [comment]
What extensions do you have running in Chrome, if any?

**Comment by Kaydax** [comment]
Right now Ublock Origin and Vinesauce Twitch Notifications

**Comment by pitaj** [comment]
Did you try incognito mode? Chrome 62 has been released, maybe try updating?

**Comment by Kaydax** [comment]
Im updating now, seeing if that fixes it

**Comment by Kaydax** [comment]
Ah yep, seems to have done the trick, updating was the key
