### ISSUE TITLE
Fully support npm@5 and yarn

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#6008]
These two package managers will automatically prune out all extraneous modules in `mode_modules` whenever they install a package.

To be compatible with this behavior, a few things must change with how NodeBB handles plugin installation, etc.

- [x] Distribute a new file, `package-default.json`, instead of `package.json`
- [x] On first run, copy `package-default.json` to `package.json` and run `npm install`
- [x] When installing plugins, use `npm install --save`, so they get stored in `package.json`
- [x] When removing plugins, use `npm uninstall --save` so they get removed from `package.json`
- [x] Change `./nodebb upgrade` to do two more things:
  1. `git pull` to pull the latest `package-default.json`
  2. Overwrite all properties (besides `dependencies`) in `package.json` based on the new values in `package-default.json`
- [x] Update documentation
  + New update workflow
    `./nodebb upgrade` vs `git pull && ./nodebb upgrade`
    `git fetch && git checkout v1.6.x && ./nodebb upgrade`

**Comment by a632079** [comment]
I think this a good way by using a extension dir to save plugins or themes. Then just use script run  `npm link` to link plugins

**Comment by julianlam** [comment]
Unfortunately an extension dir won't interface with npm properly, so we opted for `package.default.json` approach instead.

**Comment by BenLubar** [comment]
- [ ] Update Dockerfile so it builds with the renamed `package.json` file.

**Comment by BenLubar** [comment]
https://hub.docker.com/r/benlubar/nodebb/builds/bbpda5nyfjyk5xbubhgepge/

Looks like the build has been fixed.

**Comment by julianlam** [comment]
Good to know, thanks @BenLubar
