### ISSUE TITLE
Small visual issue (only reproducible in the mobile version of NodeBB)

### ISSUE THREAD

**Issue by kenygamer** [NodeBB/NodeBB#6009]
https://m.imgur.com/a/mUoYL

As you may see, there's no spacing between the alert box and the New Topic button. This is a *minimal* error and it is reproducible in the latest NodeBB version (I'm up to date).

Linux Ubuntu 16.04.3 LTS
8 GB RAM • 8 Cores Cores / 4 Threads • 240 GB SSD • 2.1 GHz

**Comment by pichalite** [comment]
@kenygamer This should be reported in the persona theme repo here https://github.com/NodeBB/nodebb-theme-persona
