### ISSUE TITLE
Post Queue hard to use on mobile

### ISSUE THREAD

**Issue by gwynnarth** [NodeBB/NodeBB#6016]
- **NodeBB version:** 1.6.0
- **NodeBB git hash:** 02370b30d934006fe1db8575cccf6a42ac71431e
- **Database type:** mongo + redis
- **Database version:** 3.4.9 + 3.2.4
- **Exact steps to cause this issue:**
1. Have a post waiting for approval in Post Queue.
1. Click the notification on mobile to open Post Queue page.
- **What you expected:**
I am able to read and interact with entries in Post Queue.
- **What happened instead:**
Post Queue is almost unusable on mobile. Text does not wrap - whole post text is rendered in one line:

![post-queue-on-mobile-1](https://user-images.githubusercontent.com/591754/32221180-d9342e74-be34-11e7-9ccc-f379619367d1.jpeg)

 Additionally swiping left immediately opens side menu which makes it even more frustrating and hard to interact with, since it leaves a tiny scrap of screen left to use:

![post-queue-on-mobile-2](https://user-images.githubusercontent.com/591754/32220843-859f33c2-be33-11e7-80a6-e6fbd9353d03.jpeg)

Ideally text should wrap to minimize horizontal scrolling + side menu should not be triggered by swiping.

Thanks!

**Comment by julianlam** [comment]
Hm... is the post queue easier to use from the admin panel?

**Comment by attis** [comment]
Only marginally. Text does not wrap either - the only difference is that in the ACP the menu slides out from the left, not right - so scrolling text forward is possible. However scrolling back to the left shows the same issue.

Plus, Global Moderators don't have access to post queue in ACP anyway :(

**Comment by barisusakli** [comment]
Desktop
![image](https://user-images.githubusercontent.com/2583394/100530915-e5e15400-31c5-11eb-9118-f41a09891d3b.png)

Mobile
![image](https://user-images.githubusercontent.com/2583394/100530921-0c9f8a80-31c6-11eb-802d-44e9dbcc8523.png)
