### ISSUE TITLE
Dynamic favicon causes heavy recompression of original image

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6017]
- **NodeBB version:** 1.6.0
- **NodeBB git hash:** 02370b30d934006fe1db8575cccf6a42ac71431e
- **Database type:** mongo + redis
- **Database version:** 3.4.9 + 3.2.4
- **Exact steps to cause this issue:**
1. Visit forums as a logged in user with JS turned on
- **What you expected:**
Favicon is not visually distinguishable from what administrator uploaded via ACP
- **What happened instead:**

The dynamic favicon feature causes a heavy recompression and size reduction of the input favicon.

Here's the comparison of the forum vs "regular" favicon:
![faviconcvslb](https://user-images.githubusercontent.com/591754/32221474-f476167e-be35-11e7-98b9-7820d946bbd6.png)

Notice the jagged and aliased Opera logo in the left tab vs the smooth in the right tab.

The static is 96x96px: https://forums.opera.com/favicon.ico?v=787a580mou7

The dynamic is 16x16:
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABaElEQVQ4ja3STUsCURQG4BH3bUrNj3EUc3TwM23EEEHEDLoYIYr+vVZhixYtAiEMaqVtJCoIbSNEiwg1Sq3FvG06oxMzLqIDz+ae+5577zAc9981zZcFSElAjGhJCUxzB56lYWSK48VQX+BxuGrW6CflkX54e2esiBGQq2BQpN4xx5lPrCsgl7Hw269r7wlf/jDIZCub0jnD1HLYQe7zeUHtfIhRvG9IKqMn3iU2lW5ARDcg4iYUmu979QVBRpFM02jAoFDY7cXiIGrjyesHeYlnmdEAjuO453QaRF189PhABtHM/rIB41wORF28dXtBeoGU4RNmlUrxs1gEURvXLi/aTv6H2/AjolxWwBjAGFAqzfd1fDJ/bneAdERZ1smb1DBjmNTrvKbbEqTRqc0GMqvV1B8J1ap5MaxUq0PdK565AsOG1QLSFoNYDIIxPCSz+mGqpiPMNyzrOLKsaTQsNlw4o66l4b/UN09W+XwivwPkAAAAAElFTkSuQmCC
```

Is there some performance considerations that prevent NodeBB from retaining original favicon dimensions? I suspect that leaving it as 96x96 would be enough to make the problem go away.

Thanks!

**Comment by pitaj** [comment]
The library we use, tinycon, appears to automatically scale based on the device pixel ratio. There may be an update to fix it, or we could use a different library.

**Comment by aStonedPenguin** [comment]
An option to just totally disable it would be nice too.

**Comment by julianlam** [comment]
According to a related issue in tinycon (tommoor/tinycon#85), the logic in Tinycon is setting the image by finding the first favicon link (which also happens to be the smallest).

**Comment by julianlam** [comment]
As @pitaj says, the device pixel ratio is used and then the source favicon is downsampled when resized down to the favicon size as represented by the browser.

So in my case, it's 19px, in yours, it's 16, because the favicon itself is never actually bigger than 19px (or 16px) on screen anyways.

That said, the downsampling process seems to the to blame here, in that it's doing a terrible job of it :wink:

**Comment by julianlam** [comment]
https://devdocs.io/dom/canvasrenderingcontext2d/imagesmoothingquality#Browser_compatibility

Neat, let's see if this helps.

**Comment by julianlam** [comment]
**Before**
![selection_090](https://user-images.githubusercontent.com/923011/32337037-4b67ee3e-bfc7-11e7-9048-96edc8333b85.png)

**After**
![selection_091](https://user-images.githubusercontent.com/923011/32337039-4ceeb350-bfc7-11e7-95d7-16b22b258696.png)

**Firefox :cry: **
![selection_092](https://user-images.githubusercontent.com/923011/32337074-64f2e606-bfc7-11e7-93fd-e2ad6c7fdaf5.png)

**Comment by julianlam** [comment]
![selection_093](https://user-images.githubusercontent.com/923011/32337333-1487f868-bfc8-11e7-9348-bdaaa8557289.png)

Ah, better with

```
ctx.imageSmoothingEnabled = true;
context.imageSmoothingQuality = 'high';
```

**Comment by julianlam** [comment]
Updating Tinycon seems to make it look much better actually, let me commit that first and @attis can give it a try.

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/2123e2f74ceeabcdc7f0d903db80b37f463f445e

**Comment by julianlam** [comment]
:point_up: Thanks @barisusakli

**Comment by attis** [comment]
@julianlam do you want me to cherry-pick that commit into our branch to see how it behaves live?

**Comment by julianlam** [comment]
@attis Yes please, that'd be much appreciated :smile:

**Comment by attis** [comment]
Deployed on production.

I think it looks better indeed, but I am testing this on a different screen (working remotely today) and now the icon I get is 32x32 px so this might be a contributing factor too. I will get back to this on Monday to see how it looks on my office display panel.

<img width="74" alt="icons-after-update" src="https://user-images.githubusercontent.com/591754/32369827-1851ab6a-c08b-11e7-80ba-13fc38d06610.png">

Left: forums, right: blogs (untouched original favicon).
