### ISSUE TITLE
Adding a "Reason" when flagging a profile does not work

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6018]
- **NodeBB version:** 1.6.0
- **NodeBB git hash:** 02370b30d934006fe1db8575cccf6a42ac71431e
- **Database type:** mongo + redis
- **Database version:** 3.4.9 + 3.2.4
- **Exact steps to cause this issue:**
1. Use flagging functionality to report a user.
1. Provide additional comment in "Reason for reporting this content":
![flagging-1](https://user-images.githubusercontent.com/591754/32221716-e74edad4-be36-11e7-88af-3280b02602f4.png)

- **What you expected:**
That information is visible when examining flagged content. For example as a "Note" attached to it.
- **What happened instead:**
I cannot find that information anywhere:
![flagging-2](https://user-images.githubusercontent.com/591754/32221771-07e617a8-be37-11e7-956d-ca6c3e3debc8.png)

Thanks!

**Comment by julianlam** [comment]
Hi @attis, thanks for reporting, looks like you definitely found a bug. Will try to reproduce and patch today.

**Comment by julianlam** [comment]
@attis I am unable to reproduce, although at this time it looks to be a UI issue. Specifically, if you input a custom flag description, and then use either of the "Spam" or "Offensive" buttons, it will overwrite the custom description.

Better verbiage is needed, as well as a visual delineation of the two options, as they are strictly "quick report" buttons.

**Comment by attis** [comment]
Ah. Indeed I did not understand that these are mutually exclusive. Fix looks good :)
