### ISSUE TITLE
utils.stripTags removes wrong tags

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#6023]
```
var a = '<img src=""></img> derp <i class="foo"></i>';
var b = utils.stripHTMLTags(a, ['i']);
//b is now ` derp `
```

Same issue as https://github.com/jprichardson/string.js/pull/181

**Comment by pitaj** [comment]
Need to add some whitespace stuff in there as well. It's also possible to use html-sanitize instead.
