### ISSUE TITLE
All non NPM plugins removed when updating a plugin

### ISSUE THREAD

**Issue by aStonedPenguin** [NodeBB/NodeBB#6032]
- **NodeBB version:** 1.6.1
- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** redis
- **Database version:** 4.0.1
- **Exact steps to cause this issue:**
Install a custom non NPM plugin
Update an existing plugin (pretty sure uninstalling works too)

- **What you expected:**
It not to delete hours of work

- **What happened instead:**
It deleted every non NPM plugin

**Comment by julianlam** [comment]
Fixed already in master, for 1.7.0 thanks

**Comment by aStonedPenguin** [comment]
That's something that really should have been pushed to stable branches as well...

**Comment by julianlam** [comment]
The fix was literally finalised today. We don't push experimental bug fixes to stable branches.

It will land in 1.7.x on the 15th.

**Comment by julianlam** [comment]
I'm sorry to hear you lost a lot of work. I know it can be frustrating.

In the future perhaps you can use `npm link` or `yarn link`? It will prevent npm or yarn from touching your code :smile:

**Comment by pitaj** [comment]
This is _only_ an issue with npm@5, and was their change, not ours.
