### ISSUE TITLE
DoS Issue

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6041]
- **NodeBB version:** 1.6.1
- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**

1.  Create a post with a certain string
2.  I believe even the preview window breaks it.

- **What you expected:**
I expected the forum not to go down. 

- **What happened instead:**
CPU Usage goes to 100% and does not come down in a reasonable time.  Forum becomes unresponsive to all users and had to be hard killed (kill -9). 

I am not attaching the text I was posting for obvious reasons, but would be happy to provide it privately to the devs.

**Comment by pitaj** [comment]
Email security@nodebb.org with the payload and other relevant information please.

**Comment by julianlam** [comment]
As @pitaj notes, please do provide us with the payload by emailing us at security@nodebb.org

I am curious if it reproduces here as well: https://markdown-it.github.io/

**Comment by dangerusslee** [comment]
I sent the file over.  

Come to think of it, it may be iframely related...

**Comment by julianlam** [comment]
Hey there, just a note to let you know that we still have not received the
payload example from you.

**Comment by dangerusslee** [comment]
I sent it yesterday, and again today.  Please check your spam filter.  

But like I said this is probably related to iframely, and the site without the plugin probably doesn't crash.

**Comment by julianlam** [comment]
@dangerusslee no luck... Nothing in my spam filter except for spam :smile:

Can you upload it as a text file to send.firefox.com and send the link to us?

**Comment by dangerusslee** [comment]
Sent

**Comment by julianlam** [comment]
Received 👍

**Comment by julianlam** [comment]
Bounced upstream: https://github.com/NodeBB/nodebb-plugin-iframely/pull/34/files
