### ISSUE TITLE
flags page needs pagination

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#6043]

**Comment by julianlam** [comment]
:bell: **Breaking changes**:

* Two new lines [in themes' flag templates](https://github.com/NodeBB/nodebb-theme-persona/commit/86c023ec3f6a31e10519647fc5d7a0af455a56ef)
* `Flags.list` no longer returns a straight Array with flag objects. It returns `{ flags: Object, page: Number, pageCount: Number }` now.
