### ISSUE TITLE
Being sent to last unread position should be accompanied by a notice of what happened

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6055]
Ever since that change to the default behaviour to clicking a topic, I am thrown off whenever it happens.

**To recap**: Clicking on a topic can do one of two things

1. Send you to the first post in that topic
1. If you have read this topic before, send you to the last unread post in that topic

If the latter option is invoked, an `app.alert` should be thrown to inform the user of what happened, and on click, should send the user back to the first post in the topic.

**Comment by voanhcuoc** [comment]
Opposite option :

1. Send you to the first post in that topic
2. If you have read this topic before, an `app.alert` be thrown, and on click, should send the user down to the last unread post in that topic

User can choose which behaviour in settings !

**Comment by julianlam** [comment]
Right, I understand that an option will be advantageous. Will look into allow this to be specified in user settings.

**Comment by pichalite** [comment]
My vote is for 
> If you have read this topic before, send you to the last unread post in that topic

**Comment by julianlam** [comment]
![image](https://github.com/NodeBB/NodeBB/assets/923011/aeebffbf-abc0-44b2-bf8c-3a51af3ff6e9)
