### ISSUE TITLE
Logo needs cachebuster

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6056]
- **NodeBB version:** 1.6.1

- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**
1.  Upload a logo
2.  Visit the site without doing a hard refresh

- **What you expected:**  I expected the new logo to show up.  

- **What happened instead:**  The old logo was still showing up due to being cached in the browser.

**Comment by pitaj** [comment]
I believe this is a theme-specific issue
