### ISSUE TITLE
Weird artifacts when trying to use icons

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6062]
- **NodeBB version:** 1.6.1

- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**
1.  Try to pick an icon (for example for the top nav bar).
2.  Mouse over some of the icons

- **What you expected:**  I expected the item to be highlighted.

- **What happened instead:**  There are black bars appearing all over that window, and everything just sort of moves around crazily.  

![image](https://user-images.githubusercontent.com/24903887/32753994-21d00e74-c89d-11e7-9cbd-9d0b91df5cf5.png)

**Comment by pitaj** [comment]
Are you running any bootswatch skins?

**Comment by dangerusslee** [comment]
spacelab is the current default

**Comment by barisusakli** [comment]
Can confirm it happens on persona no skins as well.

![image](https://user-images.githubusercontent.com/2583394/32761460-70a40e96-c8c1-11e7-8a41-e8dfe2f04587.png)

**Comment by pitaj** [comment]
What browser?

**Comment by barisusakli** [comment]
Version 61.0.3163.100 (Official Build) (64-bit)

Now downloading an update, going to try again.

**Comment by barisusakli** [comment]
Seems fine in Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by dangerusslee** [comment]
I can confirm this is fixed in the latest version of chrome.
