### ISSUE TITLE
Infinite Scroll ACP setting does not work

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/NodeBB#6064]
- **NodeBB version:**  1.6.1

When in ACP I enable:

<img width="748" alt="screen shot 2017-11-14 at 12 11 01" src="https://user-images.githubusercontent.com/1268723/32777022-eb78a4ce-c934-11e7-908f-eaacb0b1a98d.png">

This has no effect. I can still see pagination and if I change the pagination settings does not have any effect as well. 

What am I missing here? 

Theme persona.

**Comment by dangerusslee** [comment]
Have you checked your personal preferences?

**Comment by jimmykane** [comment]
Yeah, that was it. However this cascading preference seems a bit tricky. 
Somehow this setting persists it's vale upon user creation.
