### ISSUE TITLE
Toaster alerts with timeouts should show time remaining (via graphical progress bar)

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6069]
Here's a really bad GIF of what it's supposed to look like :stuck_out_tongue: 

![optimised](https://user-images.githubusercontent.com/923011/32850881-769f58fa-ca01-11e7-862a-86c208a47935.gif)

**Comment by julianlam** [comment]
* [x] Achieve via CSS transitions, minimal JS required
* [ ] ~Allow pause on hover~ (A bit too difficult to do, more research needed)
* [x] Progress bar colour changes depending on alert state
* [x] Updated alert should reset progress bar

**Comment by julianlam** [comment]
I don't consider this a breaking change for themes as if they do not apply the code, the progress bar simply will not exist.

**Comment by pitaj** [comment]
For pause on hover, you just need to get the current width with `getBoundingClientRect()` and set the CSS width to that. You may consider using `transform` instead of `width` as well as it's more easily optimized.

**Comment by julianlam** [comment]
No way to alter pseudo-element via DOM manipulation. Nice try though :wink:

**Comment by julianlam** [comment]
**Theme devs** :point_up: This commit contains the code you need to add to your theme. Adjust the variables for your theme's colours/variables.

**Comment by pitaj** [comment]
If it requires theme changes anyways, you may as well add a new element for the progress bar.
