### ISSUE TITLE
Problem with emojis

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6074]
- **NodeBB version:** 1.7.0
- **NodeBB git hash:** master version
- **Database type:** mongo
- **Database version:** 3.2

- Exact steps to cause this issue:

Post a comment in topic

- **What you expected:**

See no problem.

- **What happened instead:**

I see emoji, but you can see the problem below 👇 

![2017-11-16_214723](https://user-images.githubusercontent.com/31972226/32908129-e63df6a0-cb17-11e7-93f3-50cd150bba28.png)

Notice that for updating to 1.7 , I used this instruction: 
```
npm i -g npm@5
npm i -g n
n 8
git pull origin master
./nodebb upgrade
```

**Comment by pitaj** [comment]
Run `./nodebb plugins` to show us all the plugins you have installed currently, thanks

**Comment by pitaj** [comment]
This is most likely a bug with [nodebb-plugin-emoji-extended](https://github.com/NodeBB-Community/nodebb-plugin-emoji-extended). A new emoji plugin (which fixes this issue) will be released soon, and will be coming with NodeBB v1.7.1

**Comment by mohammadhassan99** [comment]
![photo5796657381202045945](https://user-images.githubusercontent.com/31972226/32909792-ba609c86-cb1c-11e7-8005-6ecc94072afa.jpg)

Do I need to remove a plugin?

**Comment by julianlam** [comment]
Do you have both `emoji` and `emoji-extended` enabled?

**Comment by mohammadhassan99** [comment]
@julianlam Hello, Yes you are right. Now It is fixed.

Thanks 😉 🙏
