### ISSUE TITLE
Homepage hook 'action:homepage.get:*' does not add buildHeader middleware.

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#6076]
- **NodeBB version: *master*
- **Database version: *any* 

Not technically a bug, but plugins depend on it being added and will now have to call manually.

**Comment by pitaj** [comment]
I'm guessing you mean that the buildHeader middleware isn't called before the hook is fired, correct?

**Comment by barisusakli** [comment]
That's correct, previous `/` was a fullblown route with couple of middlewares, not it just rewrites url so the middlewares are called after the url is rewritten, but the plugin hook is fired before.

**Comment by yariplus** [comment]
Additional issue, when manually calling buildHeader, ajaxify to the homepage no longer works properly. (gets stuck with client error `i.template is undefined`)

When echoing data from res.render, the correct variables are set in `template` and `res.locals`

**Comment by yariplus** [comment]
Using `filter:homepage.get` and a regular route without using the hook, everything works normally.
