### ISSUE TITLE
Email title contain HTML characters after upgrading to 1.7.0

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/NodeBB#6080]
Look at this: 

<img width="557" alt="screen shot 2017-11-17 at 12 39 55" src="https://user-images.githubusercontent.com/1268723/32945632-750bb332-cb94-11e7-8ba2-a1f8e08c84e2.png">

This is on the title of the email 

pasting the raw: 

`<strong>Mff73</strong> has posted a reply to: <strong>Text Notifications</strong>`

Why did this break? 

Hello?

**Comment by barisusakli** [comment]
Are you on 1.7.0 or latest master?

**Comment by jimmykane** [comment]
@barisusakli  yes I am

**Comment by jimmykane** [comment]
<img width="394" alt="screen shot 2017-11-17 at 13 47 27" src="https://user-images.githubusercontent.com/1268723/32947984-e069a84c-cb9d-11e7-9c68-d37cf3b99bdc.png">

**Comment by barisusakli** [comment]
post `git rev-parse HEAD`

**Comment by jimmykane** [comment]
@barisusakli I would not lie to you. I am asking the administration atm to do this. 
Sorry but I don't have ssh rights on our server for this project. 

The upgrade happened by the IT team after the release of 1.7.0, yesterday. I cannot think of any reason to not be running master and the latest code since this is how the upgrade is done. 

However, I am awaiting their response just in case. 

Does this make sense?

**Comment by barisusakli** [comment]
It's ok, the stable release is 1.7.0 which is not the same as latest master, this is a bug on master.
