### ISSUE TITLE
Scrolling doesn't work on mobile for accounts that have sticky management privileges.  

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6081]
- **NodeBB version:** 1.6.1

- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**
1.  Log into nodebb with a privileged account that can manage sticky threads.  
2.  Try to scroll past the sticky threads.  

- **What you expected:**  I expected to be able to scroll.  

- **What happened instead:**  Instead the page doesn't scroll.  (The sticky reordering does not work either).  I can only scroll if I use the margins on the left and right.

**Comment by julianlam** [comment]
Try upgrading Chrome on mobile... It may have been resolved upstream

**Comment by dangerusslee** [comment]
I am on the latest version.  Previously I wasn't able to replicate on a higher model phone, but now I realize it was because I was not logged into a privileged account.  Yesterday I was able to replicate it on a Galaxy S7 Edge.

**Comment by pitaj** [comment]
I can reproduce this here, but only in FF mobile: https://community.nodebb.org/category/2/general-discussion

If I try to scroll by only dragging from the pinned topic listing. 

It didn't occur in chrome for me.

**Comment by dangerusslee** [comment]
@pitaj are you logged into the same account on chrome?

**Comment by julianlam** [comment]
I am now able to reproduce -- Chrome 62.0.3202.84

**Comment by julianlam** [comment]
I have a sneaking suspicion it is related to this: http://tonsky.me/blog/chrome-intervention/

**Comment by pitaj** [comment]
I can reproduce on Chrome as well, I wasn't logged in at the time, my bad.

I don't know if it's related to the passive event listeners thing, as it's touch events (as opposed to scroll events) that are being cancelled I think.

**Comment by julianlam** [comment]
:+1:
