### ISSUE TITLE
a run error （centos 6.9），who can help

### ISSUE THREAD

**Issue by wozitaoran** [NodeBB/NodeBB#6085]
- **NodeBB version:** 1.6.1
- **NodeBB git hash:** [https://github.com/NodeBB/NodeBB/commit/1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf]

- **Database type:**  redis
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**

	1. First I follow https://docs.nodebb.org/installing/os/centos/   step by step
	2. Then, after this step ./nodebb setup

- **What you expected:**
e.g. I expected no error
- **What happened instead:**
Instead, I got this：
./nodebb setup

/root/nodebb/nodebb/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
NodeBB could not be initialised because there was an error while loading dependencies.
Please run "npm install --production" and try again.

For more information, please see: https://docs.nodebb.org/installing/os/

SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/nodebb/nodebb/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

 Thank you!

**Comment by wozitaoran** [comment]
111

**Comment by pitaj** [comment]
What version of node are you using? `node -v`

**Comment by wozitaoran** [comment]
node -v
v0.10.48

**Comment by wozitaoran** [comment]
I use this ：
curl https://raw.githubusercontent.com/creationix/nvm/v0.13.1/install.sh | bash
source ~/.bash_profile
nvm list-remote
nvm install v0.12.7 # as of this writing check the result of the list-remote to see all choices

**Comment by pitaj** [comment]
You better upgrade node, then. `npm install 8` should work. Might need to do `nvm use 8` too.

**Comment by wozitaoran** [comment]
thanks，after do this ，it‘s ok  
nvm install v8.0.0
nvm use v8.0.0
