### ISSUE TITLE
"TypeError: Cannot read property 'message' of undefined" when developing using Grunt

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6086]
- **NodeBB version:** 1.6.1

- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**
1. Run Grunt in the nodebb folder
2. Not sure what actually triggers it, seems to be a bit random, but seems to happen right after a rebuild

- **What you expected:** I expected the server to keep running.  

- **What happened instead:**  It threw and error and shutdown.  

```
18/11 16:30:16 [2896] - warn: Route requested but not found: /assets/socket.io.js.map
18/11 16:30:16 [2896] - error:  TypeError: Cannot read property 'message' of undefined
    at fs.readFile.e (C:\web\nodebb\NodeBB\node_modules\benchpressjs\build\lib\express.js:44:66)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
18/11 16:30:16 [2896] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
18/11 16:30:16 [2896] - info: [app] Database connection closed.
18/11 16:30:16 [2896] - info: [app] Web server closed to connections.
18/11 16:30:16 [2896] - info: [app] Shutdown complete.
```

**Comment by pitaj** [comment]
That's a really weird issue. The error thrown shouldn't ever be `undefined`, and I have no idea how it could be.

**Comment by barisusakli** [comment]
Unless something is doing `throw undefined` I don't see how that can happen. Can you post your nodejs version as well. @dangerusslee

**Comment by dangerusslee** [comment]
v6.11.3 ono windows

**Comment by pitaj** [comment]
Can you try deleting `build` and `node_modules` and then running `npm install` and trying grunt again?

**Comment by dangerusslee** [comment]
@pitaj Thank you, I've done that and haven't hit that bug since.  So it may have just been a problem with my workspace.  Closing until I can reproduce.

**Comment by dangerusslee** [comment]
Got the error again today.  

```
22/11 07:10:15 [23892] - warn: Route requested but not found: /assets/socket.io.js.map
22/11 07:10:16 [23892] - error:  TypeError: Cannot read property 'message' of undefined
    at fs.readFile.e (C:\web\nodebb\NodeBB\node_modules\benchpressjs\build\lib\express.js:44:66)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
22/11 07:10:16 [23892] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
22/11 07:10:16 [23892] - info: [app] Database connection closed.
22/11 07:10:16 [23892] - info: [app] Web server closed to connections.
22/11 07:10:16 [23892] - info: [app] Shutdown complete.
```

**Comment by rakeshmishrait** [comment]
TypeError: Cannot read property 'message' of undefined
fv.io.js:1

**Comment by pitaj** [comment]
Open an issue on the bench press repo
