### ISSUE TITLE
Wrench is deprecated in favor of fs-extra

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6089]
- **NodeBB version:** 1.6.1

- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**
1.  Ran npm build

- **What you expected:** Everything to be installed with no warnings

- **What happened instead:** Received the following warning

```
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.```
<!-- Thank you! -->

**Comment by julianlam** [comment]
Will be removed with emoji-extended replacement.
