### ISSUE TITLE
Plugin management page doesn't work when there is no internet

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6090]
- **NodeBB version:** 1.6.1

- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**
1.  Turned off internet
2.  Log into ACP
3.  Go to plugins/install plugins page (/admin/extend/plugins)

- **What you expected:** I wasn't expecting to be able to find new plugins from the internet, but I though I would be able to activate or deactivate ones I already had.  

- **What happened instead:** Go a page that said no plugins found and received the following in the logs:

```
8/11 22:33:08 [14284] - error: Error parsing plugins : getaddrinfo ENOTFOUND packages.nodebb.org packages.nodebb.org:443
```

**Comment by pitaj** [comment]
I think it's fair to assume that any forum would be connected to the internet. If you wish to activate or deactivate a plugin, you can use `./nodebb activate` and `./nodebb reset -p` respectively.

**Comment by JonasT** [comment]
> I think it's fair to assume that any forum would be connected to the internet.

Why? It's not such an unexpected idea that it might be used in some sort of company network, in which case it might be firewalled and only connected for the occasional update, and/or the company web uplink might temporarily break. Not that it sounds like a super common use case, but it sounds like something worth fixing to me
