### ISSUE TITLE
Log should be using the local locale date format

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6091]
- **NodeBB version:** 1.6.1

- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**
1. Run grunt

- **What you expected:** I was expecting the log to have US dates as is the locale on my PC.  

- **What happened instead:** Instead I got european dates (18/11 instead of 11/18)

```
18/11 22:30:45 [14284] - info: NodeBB Ready
```

**Comment by pitaj** [comment]
We ought to just use ISO 8601: YYYY-MM-DD

**Comment by julianlam** [comment]
I am also in favour of an ISO date format.
