### ISSUE TITLE
I want to remove register button,but i do not know what to do

### ISSUE THREAD

**Issue by lxt410725** [NodeBB/NodeBB#6095]
![image](https://user-images.githubusercontent.com/23032062/33057846-b85efcee-cec7-11e7-8a22-35390d71cb2e.png)

**Comment by pitaj** [comment]
Two Options:

1. In the Admin Control Panel, under Settings -> User, you can change the **Registration type** of the forum to "Invite Only" or "No Registration". This will disable the registration button.

2. You can add the following CSS in the Admin Control Panel under Appearance -> Custom Content, which will only hide the button, but still allow uses to register if they reach the `/register` page some other way.
```css
.navbar-nav > li > a[href="/register"] {
  display: none;
}
```
