### ISSUE TITLE
Requirements node.js 8.9.0 or greater

### ISSUE THREAD

**Issue by moguv587** [NodeBB/NodeBB#6097]
please update README.md
v1.7.0 need node.js 8.9.0 or greater

**Comment by julianlam** [comment]
Our testing encompasses node 6, 7, and 8. So we do not require higher than 8.9.0. Please report the error you see, otherwise this is an invalid bug, sorry.

**Comment by julianlam** [comment]
Testing suite: https://travis-ci.org/NodeBB/NodeBB/

**Comment by moguv587** [comment]
I tried installing tonight, but I didn't save debug, I started using 6.1, but failed, after I upgraded 8.9.0, “npm install" was installed successfully

**Comment by julianlam** [comment]
We will need the install log in order to inspect the failure.
