### ISSUE TITLE
NodeBB requires external CDN resources for installer to work [reliability & security nitpick]

### ISSUE THREAD

**Issue by JonasT** [NodeBB/NodeBB#6098]
NodeBB as deployed via the docker image appears to require external resources from maxcdn.bootstrapcdn.com, fonts.googleapis.com and code.jquery.com to work. This is not a good thing because it makes a NodeBB instance rely on external CDN providers the forum admin might not even be aware of, and it requires a more unsafe custom CSP to allow those resources to load. It'd be better if those could somehow packaged with NodeBB on deployment (especially since the versions appear to be pinned anyway).

- **NodeBB version:** the docker container launch log doesn't say, so I don't know
- **NodeBB git hash:** no idea, but nodebb/docker hash is sha256:d7fc601bcfff2a6e52a846a2a37b426509b3ccfba27035b27b9c36f76bb244d8
- **Database type:** mongo or redis
- **Database version:** 4.0.2

- **Exact steps to cause this issue:**
1. Launch nodebb/docker from DockerHub
2. Browse to installer with proxy that inserts CSP without unsafe-inline
3. See broken design and errors in the browser console
- **What you expected:**
works without custom external allowed script hosts in CSP, no access to external CDNs
- **What happened instead:**
requires external CDN access combined with CSP entries for those hosts

Edit: updated the issue text now that I know what the issue is

**Comment by JonasT** [comment]
Ah, it actually might be the problem that NodeBB tries to load scripts from maxcdn.bootstrapcdn.com, fonts.googleapis.com and code.jquery.com and inject it into the page.

Is there some way to get a properly baked NodeBB that doesn't depend on external services? (I'd want that for redundancy alone)

**Comment by pitaj** [comment]
They aren't "injected into the page". They are included in the page when it is sent to the browser. You can see the source here:

https://github.com/NodeBB/NodeBB/blob/master/src/views/install/index.tpl

**Comment by JonasT** [comment]
It'd be nice if NodeBB  could run without the use of such external CDNs, both from a reliability and security standpoint. Is this currently possible?

**Comment by julianlam** [comment]
You mean loading the Roboto font from Google's servers? We're looking to remove that requirement in our next theme, so... yes :smile:

**Comment by pitaj** [comment]
It's only the web installer at the moment that uses these external resources. The Persona theme still uses Robot but as julian mentioned, that will be removed in the next theme

**Comment by JonasT** [comment]
@julianlam I listed all the affected resources on the install page at least. It's not just the google font dependency, but also jquery and bootstrap are linked externally. This means even if I run a really big forum in cooperation with whatever CDN provider I choose, I have dependencies on external CDNs I might not even know about (the average NodeBB admin is probably not aware of this) so it'd be nice if that could be removed/fixed
