### ISSUE TITLE
Docker image on dockerhub nodebb/docker doesn't output nodebb version and nodebb git hash on start

### ISSUE THREAD

**Issue by JonasT** [NodeBB/NodeBB#6099]
Docker image on dockerhub nodebb/docker doesn't output nodebb version and nodebb git hash on start, but instead just `nodebb_1  | Starting NodeBB` without any version info. Since you want the version info for tickets, I suggest this should be changed so people can easily supply it especially in cases where they can't even get past the install.

- **NodeBB version:** don't know
- **NodeBB git hash:** don't know
- **Database type:** mongo or redis
- **Database version:** 4.0.2
- **Exact steps to cause this issue:**
1. Get docker image nodebb/docker from dockerhub
2. Run it and check logs
- **What you expected:**
Log shows NodeBB version and NodeBB git hash
- **What happened instead:**
Log doesn't show neither NodeBB version nor NodeBB git hash

**Comment by julianlam** [comment]
How does docker receive version info? The version info is output in the logs on start:

```
$ ./nodebb dev

NodeBB v1.7.0 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).
```

**Comment by JonasT** [comment]
docker just stores whatever the stdout/stderr shows. However, the image is currently not running `./nodebb dev` but the command `./nodebb start` which has the following output:

```
Attaching to tethercodeforum_nodebb_1
nodebb_1  | 
nodebb_1  | Starting NodeBB
nodebb_1  |   "./nodebb stop" to stop the NodeBB server
nodebb_1  |   "./nodebb log" to view server output
nodebb_1  |   "./nodebb restart" to restart NodeBB
nodebb_1  | 
nodebb_1  | 21/11 21:56:56 [22] - info: Launching web installer on port 4567
nodebb_1  | 21/11 21:56:56 [22] - info: Web installer listening on http://0.0.0.0:4567
nodebb_1  | 21/11 22:15:00 [33] - info: NodeBB Setup Triggered via Command Line
nodebb_1  | 
nodebb_1  | Welcome to NodeBB!
nodebb_1  | 
nodebb_1  | This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
nodebb_1  | Press enter to accept the default setting (shown in brackets).
nodebb_1  | 
nodebb_1  | 21/11 22:15:00 [33] - info: Now configuring redis database:
nodebb_1  | Configuration Saved OK
nodebb_1  | Populating database with default configs, if not already set...
nodebb_1  | 21/11 22:15:03 [33] - error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
nodebb_1  |     at Object._errnoException (util.js:1024:11)
nodebb_1  |     at _exceptionWithHostPort (util.js:1046:20)
nodebb_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

**Comment by pitaj** [comment]
Probably should be running `node loader --no-silent --no-daemon`

**Comment by JonasT** [comment]
Having worked with the docker image some more, the version IS output later when the actual forum starts. However, it isn't when the installer starts so if some showstopper bug happens in the installer, people can't properly report back the broken version. So it'd be useful if this was changed!

**Comment by SharksevenRo** [comment]
perhaps you want to link the redis instance was in another container.
so you can
use --link the redis, and use alias to link。
if you link with ip 127.0.0.1 or localhost it means link a redis instance in the container where your nodebb in。it's the point.

**Comment by JonasT** [comment]
@SharksevenRo are you commenting on the correct ticket? This one is about the version output of NodeBB when launching.
