### ISSUE TITLE
For NodeBB running inside docker, the redis host should default to "redis" rather than "127.0.0.1"

### ISSUE THREAD

**Issue by ghost** [NodeBB/NodeBB#6100]
For NodeBB running inside docker, the redis host should default to "redis" rather than "127.0.0.1". Usually, it'd be running in another container with another IP, and both with `docker link` and other mechanisms (docker internal DNS via docker-compose, ..) a redis instance meant to be used by NodeBB will in the vast majority of cases have the hostname "redis".

Therefore, it'd be a nice touch if the installer could somehow be launched in the Docker image in a way that makes it aware it is in docker, and default to the docker-friendly default of "redis". It's not a big problem of course, just a small suggestion to streamline the setup in docker.

- **NodeBB version:** don't know / latest nodebb/docker image
- **NodeBB git hash:** don't know / latest nodebb/docker image
- **Database type:** mongo or redis
- **Database version:** 4.0.2
- **Exact steps to cause this issue:**
1. Fetch and launch nodebb/docker image from dockerhub to get to the installer
- **What you expected:** redis database host defaults to "redis"
- **What happened instead:** redis database host defaults to "127.0.0.1"

**Comment by julianlam** [comment]
In general I'm opposed to adding environment specific detection as if I have to support one, then I have to support all of them :laughing: excuse the slippery slope argument but I think you can agree that the less overhead the better?

**Comment by JonasT** [comment]
@julianlam I never suggested environment detection and that would be IMHO not a good approach to solve this. The issue stems not from a lack of "docker detection" (is such a thing even reliably possible?) but that all well-designed docker containers use a custom startup wrapper specifically for docker which can support additional environment options or better defaults.

Therefore, I suggest such a wrapper should be added and the install script launcher simply needs an argument to be passed another default by such a wrapper.

**Comment by julianlam** [comment]
`redis__host=redis redis__port=1234 ./nodebb start`

Environment variables can be passed in and will show up in the install wizard. Feel free to send PR for this.
