### ISSUE TITLE
Issue in my logs

### ISSUE THREAD

**Issue by 5out420** [NodeBB/NodeBB#6103]
PitaJ from NodeBB forums recommended I let you know about this.

I get this in my logs.

node_redis: Deprecated: The HDEL command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.

Do I need to do anything?

**Comment by julianlam** [comment]
Hi there,

When do you get this log, on NodeBB startup, or when you navigate to a specific page?

**Comment by 5out420** [comment]
Do you still need more information on this because I have to go through my history and figure out when exactly it happened if you do? I'm pretty sure it was on slog after an upgrade command following a hard git command.

**Comment by julianlam** [comment]
Nope, I don't think so :smile:

**Comment by barisusakli** [comment]
It should be fine on 1.7.1, let us know if you see those warnings again.
