### ISSUE TITLE
Scrolling to last post doesn't work and leads to JS error (reproduced on community.nodebb.org)

### ISSUE THREAD

**Issue by JonasT** [NodeBB/NodeBB#6104]
When trying to scroll down to the last post here, I get a javascript error and an infinite loading icon: https://community.nodebb.org/topic/180/who-is-using-nodebb

This is the result in a screenshot (nothing ever happens from that state and it'll never scroll down):

![scrollbug](https://user-images.githubusercontent.com/1573352/33135045-a02993f2-cfa1-11e7-851c-e541e8dbd3f4.png)

Try this for yourself in Firefox Nightly if you want (probably also reproducible in FF57 / stable I would assume).

- **NodeBB version:** whatever runs on community.nodebb.org as of 2017-11-22
- **NodeBB git hash:** see above
- **Database type:** see above
- **Database version:**  see above
- **Exact steps to cause this issue:**
1. Use Firefox Nightly (might also be reproducible in Firefox Stable in the very latest version)
2. Go to https://community.nodebb.org/topic/180/who-is-using-nodebb
3. Click scroll to last post button in the top bar
- **What you expected:** works and scrolls down
- **What happened instead:** doesn't work (doesn't scroll down), browser console shows js error

**Comment by julianlam** [comment]
No repro on FF 57.0 :frowning:

**Comment by JonasT** [comment]
When I use this link it works fine: https://community.nodebb.org/topic/180/who-is-using-nodebb/451
Refresh also works fine. However, END does not (breaks similarly to button with infinite loading symbol and error on browser console).

> No repro on FF 57.

In that case it might be a nightly-specific problem :confused:

**Comment by pitaj** [comment]
I can't reproduce this on nightly, either.

**Comment by aStonedPenguin** [comment]
Gives me the same error on Nightly 59.0a1 (2017-11-19)

**Comment by pitaj** [comment]
I cleared my cache, opened https://community.nodebb.org/topic/180/who-is-using-nodebb/, and clicked on the "go to bottom" button and everything worked.

I'm on 59.0a1 (2017-11-22)

**Comment by JonasT** [comment]
Ok I just upgraded to 59.0a1 (2017-11-22) (64-bit) and tried this on a completely fresh wiped profile. It is still broken. So it's not related to my settings or addons.

Time to share some more system info I guess:

Operating system: GNU/Linux Fedora 27 (AMD64)
Desktop: GNOME 3.26.2 Xorg Session
GPU: Radeon R7 240 ("radeon" linux driver)
CPU: AMD Ryzen 5 1600

**Comment by pitaj** [comment]
Alright, I managed to reproduce this in Chrome incognito mode.

You can only reproduce this in guest mode, which is why we weren't able to reproduce it yet. It's only a bug in the pre-release Persona running on community

**Comment by pitaj** [comment]
It should be fixed now.
