### ISSUE TITLE
Linked plugins should not be added to package.json on upgrade

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6107]
In a case of protecting the user from themselves... under the following scenarios, a broken `package.json` will be generated:

1. `git clone` a private repo (or one that is not published in npm, in any case)
1. `yarn link` or `npm link` from inside of said clone
1. `yarn link <pkg>` or `npm link <pkg>` from inside NodeBB
1. `./nodebb upgrade`

The `preserveExtraneousPlugins` method will take the newly linked plugin and append it to `package.json`, which will cause `npm i --production` to fail as it is not a published plugin.

**Comment by pitaj** [comment]
Woah woah woah, `npm install` will sometimes prune out linked packages if they aren't in package.json

**Comment by julianlam** [comment]
I have not recently seen this happen (in my experience, in any case), do you have a source for this?

There's an npm issue from 2015 detailing how linked packages' dependencies get shifted around, but that's unrelated to this.

**Comment by julianlam** [comment]
Also if we allow them to be added to `package.json`, then `npm install` just errors out, which is of course, undesirable...

**Comment by pitaj** [comment]
Only if the version in package.json doesn't exist in the npm registry, which to be fair happens pretty often

**Comment by pitaj** [comment]
There isn't a better solution, unfortunately.
