### ISSUE TITLE
Docker container requires /usr/src/app/ as volume to not break, but also it builds stuff into this directory during image build and expects it to be there

### ISSUE THREAD

**Issue by ghost** [NodeBB/NodeBB#6109]
The docker container requires /usr/src/app/ as volume to not break (because during install, things appear to be placed there which lead to an internal server error when they are gone - also config.json needs to be persistant for the database secret). However, the docker container also builds stuff into this directory during image build and expects it to be there.

This makes the setup rather bothersome and bad, because the following steps appear to be required:

1. Build the container
2. Launch it WITHOUT /usr/src/app/ as a volume and copy out the contents
3. Destroy the container again
4. Recreate & relaunch the container with /usr/src/app/ as a volume pointing to the directory where you copied the old /usr/src/app/ contents into

(this is because specifying anything at volume during container creation time will mount an empty directory on top of whatever was previously there, so unless your volume was prefilled by the user with anything - not usually the case - it will simply be an empty directory on first container launch)

What the Dockerfile actually should be doing is this:

1. Have a custom wrapper launch  script (e.g. shell script which ends with `exec ./nodebb start` and which can do stuff before that)
2. The Dockerfile should move /usr/src/app/ to something like /usr/src/default-app/ at the end of the build procedure
3. The custom wrapper script should check at launch if /usr/src/app/ is empty, and if yes copy the contents of /usr/src/default-app/ into it
4. The custom wrapper could also specify more sane docker defaults for the installer while at it, for example "redis" as a default database host

This would allow people to specify `/usr/src/app` as a volume for persistence and still have things "just work" at first container launch with the volume getting properly populated with a NodeBB installation in case it's still empty.

Alternatively, nodebb installation should only do changes in the database such that it's enough to specify the file /usr/src/app/config.json as a volume. (which again should probably be overwritten by NodeBB at start if completely empty with a new valid config)

- **NodeBB version:** git master
- **NodeBB git hash:** cdc00cc0f276880336e0133988c64f816828032c
- **Database type:** redis
- **Database version:** 4.0.2
- **Exact steps to cause this issue:**
  Variant 1:
  1. Launch docker container without any volumes
  2. Start installation with redis properly persisted
  3. Throw away container & recreate & relaunch it
  4. Database is no longer recognized (config.json with secret is gone)

  Variant 2:
  1. Launch docker container without /usr/src/app/config.json as a volume and a valid config.js
  2. Start installation with redis properly persisted
  3. Throw away container & recreate & relaunch it
  4. There is now an internal server error because files are missing that were added to /usr/src/app   during install (not during the docker build earlier!)

  Variant 3:
  1. Launch docker container with /usr/src/app as a volume:
  2. Doesn't launch properly
- **What you expected:** either specifying /usr/src/app as a volume, or /usr/src/app/config.json as a volume, or none of the two should work by default without any additional steps
- **What happened instead:** none of those works

**Comment by JonasT** [comment]
PS: I would be interested in writing & testing such a script as soon as some other basics are sorted out (see #6108 ), if you need someone to look into this.

**Comment by JonasT** [comment]
I did now prepare a branch for a new pull request which also fixes this: https://github.com/JonasT/NodeBB/blob/docker-startup-script/docker-startup.sh

It is based on #6108 so as soon as that is merged, I will make a followup pull request to introduce a startup bash script to fix this issue here (and #6100 along with it).

**Comment by BenLubar** [comment]
https://github.com/boomzillawtf/tdwtf/blob/0395c099dae333c8cf67874aef48717997bfd438/Dockerfile#L34-L38

**Comment by JonasT** [comment]
The watchdog is going to get SIGKILL'ed on termination, and might leave anything launched by the bash as zombies (unless people remember to use --init at container creation time). I really recommend using tini in the image.

**Comment by BenLubar** [comment]
If the container's PID 1 terminates (which is `node loader.js`), won't everything get cleaned up by the host's init process? I see five zombie processes on the machine running that docker container in production and they're all listed as `node` and their parent processes are all the `node loader.js` process.

I think all we need to do is make https://github.com/NodeBB/NodeBB/blob/d8fbd51e93626d13cd4c42975a1b76993d3bc591/loader.js#L54 close the handle to the subprocess somehow.

**Comment by JonasT** [comment]
@BenLubar that can work to some extent, but it's also about sub subprocesses with something in between dying/crashing. As soon as you run more than one process in a container, the best thing to do is really to slap tini into it. It's small, it's not hard to add and it doesn't do anything more than deal with this properly in the corner cases your code might not catch

**Comment by JonasT** [comment]
Or summed up: yes you can readopt all the processes in loader.js and close them, but that's basically what tini already does. So you can reimplement it, or just use tini for it.

**Comment by grischa** [comment]
So far I have it working quite well with environment variables (no config.json) and a volume on `/usr/src/app/public` for uploads.

And for a fresh db, I had to docker exec once to run setup `./nodebb setup`

My Dockerfile:
```Dockerfile
FROM nodebb/docker:v1.9.3
RUN npm install && npm cache clean --force

# to fix the bug https://github.com/NodeBB/NodeBB/issues/6493
RUN npm install benchpressjs

VOLUME /usr/src/app/public

CMD ./nodebb upgrade && ./nodebb start
```

and for K8s the env:
```yaml
          env:
            - name: url
              value: 
            - name: secret
              value: 
            - name: "database"
              value: "mongo"
            - name: "port"
              value: "4567"
            - name: "mongo__host"
              value: 
            - name: "mongo__port"
              value: "27017"
            - name: "mongo__username"
              value: 
            - name: "mongo__password"
              valueFrom:
                secretKeyRef:
                  key: mongodb-password
                  name: 
            - name: "mongo__database"
              value: 
```

The downside is that starting takes a bit long.

However, I have not been running it for a long time, I may have missed some details and it will crash and burn. Any warnings appreciated.

**Comment by JonasT** [comment]
@grischa packaged like that it won't shutdown properly. (it will be killed off rather than get a SIGTERM, and may leave orphans / zombie processes around) That's why using something like `tini` is a good idea.

**Comment by grischa** [comment]
Thanks @JonasT, I will just add it to the Dockerfile then.

```Dockerfile
# Add Tini
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]
```

I'm just adding all the snippets here, to help other people, and also in the hope that it might help someone to develop a Kubernetes-friendly official Docker image one day.

I think it's not too far away. Major issues left are the database dependent build step and first use manual setup.

**Comment by JonasT** [comment]
That sounds good! But you should still change your `CMD` to something like this: `CMD ["bash", "-c", "./nodebb upgrade && exec ./nodebb start"]`

Explanation:

If you don't use the `["a", "b", ...]` syntax, your process will be wrapped by `sh` or some other shell (which leads again to the shell getting SIGTERM, but your process getting killed because most shells don't handle this properly by default). By specifying explicitly the bash and using `exec`, you're making sure that the process gets replaced by your standalone nodebb without any shell wrapping remaining, so that nodebb will get its SIGTERM directly and shut down properly.
