### ISSUE TITLE
Latest NodeBB crashes in docker when attempting to set site logo

### ISSUE THREAD

**Issue by JonasT** [NodeBB/NodeBB#6116]
The latest NodeBB keeps crashing in docker if I try to specify a site logo. 

```
nodebb_1  | 26/11 06:33:17 [75] - error:  TypeError: Cannot read property 'height' of null
nodebb_1  |     at /usr/src/app/src/meta/configs.js:86:44
nodebb_1  |     at Jimp.<anonymous> (/usr/src/app/src/image.js:117:4)
nodebb_1  |     at Jimp.throwError (/usr/src/app/node_modules/jimp/index.js:85:44)
nodebb_1  |     at ReadFileContext.<anonymous> (/usr/src/app/node_modules/jimp/index.js:201:44)
nodebb_1  |     at ReadFileContext.callback (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:78:16)
nodebb_1  |     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

- **NodeBB version:** v1.7.0
- **NodeBB git hash:** d34f3c72479c12ae00757e586db795a39952fbe0 (run inside a docker container)
- **Database type:** redis
- **Database version:**  4.0.2
- **Exact steps to cause this issue:**
   1. Start forum in docker container & finish install if necessary
   2. Go into admin settings, enter the "General" settings, enter this as "Site Logo" > "Image":
       `https://example.com/blagif.svg`
        and press the "Save" button in the bottom-right corner **at least 5 times** with a short pause
        (~1 second) between each button press
   4. Congratulations! Your forum is now dead
- **What you expected:** works or gives some proper error on settings save when image cannot be retrieved, but keeps running
- **What happened instead:** crashes

**Comment by JonasT** [comment]
The "Save" button might not work as intended due to #6119 as I just realized - so take the steps to reproduce with a grain of salt and let me know if it works for you. Nevertheless, the backend should never crash from this so something appaers to be broken/bugged.

**Comment by pitaj** [comment]
I can't reproduce this outside a Docker container, I'll see if I can get Docker set up to try it out there.

**Comment by barisusakli** [comment]
The code doesn't seem to check for errors, probably the file doesn't exist so it is crashing.
```
image.size(path.join(nconf.get('upload_path'), 'system', 'site-logo-x50.png'), function (err, size) {
	data['brand:emailLogo:height'] = size.height;
	data['brand:emailLogo:width'] = size.width;
        next(err);
});
```

**Comment by barisusakli** [comment]
@JonasT try with above commit to see if you get an error and check if that `site-logo-x50.png` file exists.

**Comment by barisusakli** [comment]
Now that I look at this closer, `https://example.com/blagif.svg` as brand:logo will always error since the code tries to load from local

**Comment by JonasT** [comment]
@barisusakli ah that makes sense. I assumed it was for entering an URL that NodeBB will then fetch or directly embed, I didn't realize it was meant for an actual local file path on the server. Maybe some sort of warning/error would be nice then for that case

**Comment by barisusakli** [comment]
Yeah it should show an error now instead of crashing when that file does not exist. Let us know.
