### ISSUE TITLE
The default theme's small subtitles on the categories page are just a tad too small to be readable

### ISSUE THREAD

**Issue by JonasT** [NodeBB/NodeBB#6117]
Edit: I initially mentioned CSP (Content Security Policy) here but it turns out that was unrelated

Somehow, the default theme's small subtitles on the categories page are just a tad too small to be readable when setting up a new NodeBB instance from git master. On community.nodebb.org on the other hand it appears to be fine, also see here in comparison:

![font_sizes](https://user-images.githubusercontent.com/1573352/33238286-fe88f172-d28a-11e7-9032-0c2eee734adb.png)

Edit: removed unrelated rambling by me about CSP

- **NodeBB version:** v1.7.0
- **NodeBB git hash:** 1fa683502cd3c8e2f95650fea7e6c0caa21cce51
- **Database type:** redis
- **Database version:** 4.0.2
- **Exact steps to cause this issue:**
  1. Launch new NodeBB instance
- **What you expected:** Forum category descriptions are readable
- **What happened instead:** Forum isn't remain fully readable as illustrated in screenshot

**Comment by pitaj** [comment]
Can you try it without blocking external resources? I'm thinking this may be unrelated to blocking the Roboto font as my local test environment displays this way normally, even when the Robot font is loaded.

**Comment by julianlam** [comment]
This is unrelated to CSP.

**Comment by JonasT** [comment]
Interesting hm.. so is the font just that small by default? Does community.nodebb.org have another theme than the default theme then, since it looks fine there?

**Comment by julianlam** [comment]
We applied a hotfix for the theme (though I'm looking into fixing it properly now. It's a regression.)

**Comment by julianlam** [comment]
Regression from nodebb/nodebb-theme-persona#383

**Comment by julianlam** [comment]
:rage2: https://github.com/NodeBB/NodeBB/commit/f225aa25de643ef83aaf2b5ab240d2dc97ec0c4d
