### ISSUE TITLE
community.nodebb.org shows up as unsafe due to mixed content on start page

### ISSUE THREAD

**Issue by JonasT** [NodeBB/NodeBB#6118]
The page community.nodebb.org shows up as unsafe due to mixed content on the start page:

![insecure](https://user-images.githubusercontent.com/1573352/33238503-6fcb7e0a-d28f-11e7-93ff-9a56acab8a4c.png)

Maybe you should use the nodebb-plugin-camo yourself? (since that appears to circumvent this problem)

As a small side note: maybe proxying contents should even become the default and not require a separate port? This could also be done through some subfolder URL, which would make it easier to setup than a separate proxy daemon with a separate port.

- **NodeBB version:** whatever runs on community.nodebb.org as of 2017-11-26
- **NodeBB git hash:** see above
- **Database type:** see above
- **Database version:** see above
- **Exact steps to cause this issue:**
  1. Visit https://community.nodebb.org
- **What you expected:** shows up as secure

- **What happened instead:** shows up as insecure

**Comment by akhoury** [comment]
not sure if you can anything about this, since users can share their own uploaded images, externally via markdown syntax, the post that's causing this insecure message (at the time of this comment) is 
https://community.nodebb.org/topic/11561/cannot-see-new-mobile-theme

**Comment by JonasT** [comment]
@akhoury well one way to avoid this would be the nodebb-plugin-camo (which proxies all user content to HTTPS)

**Comment by pitaj** [comment]
This isn't a NodeBB issue IMO, bring up the issue on the forum itself.
