### ISSUE TITLE
Yet another external CDN reference: storage.googleapis.com/code.getmdl.io/1.3.0/material.min.js

### ISSUE THREAD

**Issue by JonasT** [NodeBB/NodeBB#6119]
Yet another external CDN reference: storage.googleapis.com/code.getmdl.io/1.3.0/material.min.js

- **NodeBB version:** v1.7.0
- **NodeBB git hash:** 1fa683502cd3c8e2f95650fea7e6c0caa21cce51
- **Database type:** redis
- **Database version:** 4.0.2
- **Exact steps to cause this issue:**
   1. Enter "General" admin settings
- **What you expected:** no external CDN script loading attempt
- **What happened instead:** external CDN script loading attempt

**Comment by pitaj** [comment]
There's no need for multiple issues for the same thing. #6120
