### ISSUE TITLE
[Security problem] It seems like many places in the core and also plugins like to pull in style and scripts(!) from external CDNs as they like

### ISSUE THREAD

**Issue by JonasT** [NodeBB/NodeBB#6120]
Both core components and plugins should **not** unnecessarily access external CDNs because apparently they can't be bothered to package themselves properly.

Example 1: theme font
Example 2: "General" settings page > https://storage.googleapis.com/code.getmdl.io/1.3.0/material.min.js
Example 3: nodebb-camo -> `Content Security Policy: The page’s settings blocked the loading of a resource at https://cdn.jsdelivr.net/clipboard.js/1.5.9/clipboard.min.js?v=qoiik7cikts`

This starts to look to me like quite the epidemic and I get the feeling if I keep looking, I will find tons of other places and plugins doing this kind of screwup.

**I suggest you need a basic underlying policy change here, including for any sort of approved plugins.** (or in other words: if plugins are found to violate this, they should get a deadline to fix this and if they don't, they should get *removed*.)

In my humble opinion, you should have strict policies to avoid external CDN access at any cost unless really required - you have a box of pandora here where a concerned system administrator can't even reliably get an *overview* on which huge plethora of CDNs NodeBB depends on with the current install.

External CDNs:

- can go down (suddenly parts of your scripts just disappear with all sorts of undefined behavior)
- can get hacked (you pull in *scripts with unrestricted browser tab access* with `material.min.js`, and so does e.g. the `nodebb-camo` plugin) - or does your require.js do proper cryptographic signature checks on the downloaded scripts?
- can slow down page load time considerably if they are under temporarily heavy load without this being necessarily on the radar of the site admin if it's some random external CDN they weren't even aware NodeBB referenced
- ..

All in all, this is not acceptable for hosting a trustable and reliable application, and it seems simply reckless to me. *Please* fix this, and I really shouldn't need to make a ticket for every tiny resource affected.

- **NodeBB version:** v1.7.0
- **NodeBB git hash:** 1fa683502cd3c8e2f95650fea7e6c0caa21cce51
- **Database type:** redis
- **Database version:** v1.7.0
- **Exact steps to cause this issue:**
  1. Install NodeBB and browse around, check browser console / network / set strict CSP policy
- **What you expected:** tons of external CDN pulls *including .js files* (which is totally unacceptable)
- **What happened instead:** not one single external CDN pull, that's what a proper install & packaging process is for. **It's not that hard.**

**Comment by JonasT** [comment]
If at all, make CDNs an option. But as a default source especially for scripts with full page access, I would suggest to implement a policy that this is an absolute no-go and should never happen.

**Comment by JonasT** [comment]
For what it's worth, I did poke around some more and at least so far, in the core I haven't encountered more external CDN references and I did file a bug for the camo plugin to get rid of this particular instance as well: https://github.com/panascais/nodebb-plugin-camo/issues/11

However, due to the nature of them being possibly hidden on every possible sub page I can't be sure without scanning the entire source and of course the popular plugins are an entirely different beast.

**Comment by pitaj** [comment]
We don't control what scripts plugins provide and we don't audit plugins that appear in the list in the ACP. Popular CDNs like the ones in your examples can have higher uptimes than most self-hosted websites. 

There's no such thing as _restricted_ browser tab access, every scripts has equal access to your webpage. It's one of the realities of the web. 

I don't have a problem with CDNs but I realize some people dislike external resources of any kind. You can set a [`Content-Security-Policy`](https://content-security-policy.com/) header in your reverse proxy if you wish to restrict scripts from outside sources.

**Comment by JonasT** [comment]
> Popular CDNs like the ones in your examples can have higher uptimes than most self-hosted websites.

I am aware of this, but it is completely irrelevant for all the points I brought up..  and in the end it's also completely irrelevant because if your self-hosted site is down, it doesn't help you at all if some low importance external CDN resource is still up.

> There's no such thing as restricted browser tab access, every scripts has equal access to your webpage. 

Sure. That's exactly why hidden external CDN links that aren't clearly obvious to the admin are so dangerous. That's precisely why I made this ticket, and why I think this should be much more visibly discouraged for plugin devs (and eliminated from the core).

> I don't have a problem with CDNs but I realize some people dislike external resources of any kind. You can set a Content-Security-Policy header in your reverse proxy if you wish to restrict scripts from outside sources.

I already did, if it wasn't obvious by all the tickets I made for this. **However, a lot of stuff breaks.** I can't currently use the camo plugin settings, I have a suspicion the others don't save properly, the main category page has pretty much unreadable text and for some tickets I'm not sure the reproduction stuff works properly for others because I'm not sure the CDN blocks are involved. Until this is more comprehensively addressed, this is more of a theoretical solution rather than a practical way to solve this. Also, it still subjects people to the potential issues of external CDN links that didn't add a restrictive CSP on top.

**Comment by pitaj** [comment]
> a lot of stuff breaks

You may consider adding exceptions for well-known external resource domains like `fonts.googleapis.com`, `fonts.gstatic.com`, `cdn.jsdelivr.net`, etc in the meantime. You can even specify the exact script paths you want allowed.
