### ISSUE TITLE
Mail not sent

### ISSUE THREAD

**Issue by SnosMe** [NodeBB/NodeBB#6121]
- **NodeBB version:** 1.7.0
- **Node.js version:** 8.9.1 LTS
- **Exact steps to cause this issue:**
Send test email from admin dashboard
- **What you expected:**
Email sent
- **What happened instead:**
`Error: 3074975488:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:825:`

**Comment by pitaj** [comment]
What are your email settings? The error message implies that either your settings are incorrect or possibly your version of OpenSSL is out of date.

**Comment by SnosMe** [comment]
I am using Gsuite smtp relay. In fact, this is the [problem](https://github.com/nodejs/node/issues/16196) of Nodejs. And it can be fixed, for example, apply this config to `axios`
```
httpsAgent: new https.Agent({ ecdhCurve: 'auto' })
```
Since we send mail, I think the main reason is `Nodemailer`, and we need to give it something similar

**Comment by pitaj** [comment]
Gonna close this unless someone runs into it again. I think it's fixed.
