### ISSUE TITLE
Problem with username history

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6124]
- **NodeBB version:** 1.7.0
- **NodeBB git hash:** 373ee17a126b3e390fa2a4446ca537a6c2f14155
- **Database type:** mongo
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**

1- I went to Account info page
2- I saw username history
- **What you expected:**

I expected to see only username changelog.
- **What happened instead:**
As you can see below, it lists a lot of usernames, and they are same but I only changed my username one time !

**[Screenshot](https://user-images.githubusercontent.com/31972226/33244476-16ee0518-d30d-11e7-9161-25ebf50344b4.png)**
🤔

**Comment by barisusakli** [comment]
@mohammadhassan99 run `db.objects.remove('user:<user_id>:usernames');` in mongodb to remove the username history. Replace `<user_id>` with your user id.

**Comment by mohammadhassan99** [comment]
@barisusakli Thanks, but a lot of users have this problem. Could you please guide me to delete their username history too?

**Comment by pitaj** [comment]
To do it for every user, it should be
```
db.objects.remove({
  key: {
    $regex: /user:[0-9]+:usernames/
  }
})
```
