### ISSUE TITLE
Double quotes in display name cause JavaScript errors

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/NodeBB#6125]
- **NodeBB version:** 1.7.0
- **NodeBB git hash:** [5354ac6b10ccc474e4fc0d054acd5cde7fa10b61](https://github.com/boomzillawtf/tdwtf/tree/39d614acf72b76ec446f024060b6b1787c8f2494)
- **Database type:** mongo
- **Database version:** 
```text
db version v3.4.2
git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: debian81
    distarch: x86_64
    target_arch: x86_64
```
- **Exact steps to cause this issue:** [anonymized]

1. User set "full name" field to `John "some word in quotes" Smith`
2. Forum gets updated to 1.7.0

- **What you expected:**

User can still use forum.

- **What happened instead:**

User can no longer use forum until an administrator replaces the quotes with the Unicode curly quote equivalents.

**Comment by julianlam** [comment]
We've been trying to reproduce this issue, but to no avail on our community forum... could it be one of the plugins you have deployed?
