### ISSUE TITLE
The sidebar swipes the opposite 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6127]
- **NodeBB version:** 1.7.0
- **NodeBB git hash:** dbdc05404daeac7021b60f22f7c18588ca126cfd
- **Database type:** mongo
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**

1- I opened my forum with mobile browser.
2- Tapped chat icon that is on the top-left.

![photo5827917003585859209](https://user-images.githubusercontent.com/31972226/33294644-c9d3ad98-d3e6-11e7-8893-b1448cd9f5f0.jpg)

- **What you expected:**

I expected the chat sidebar to swipe from left to right.

- **What happened instead:**

The chat sidebar swiped from right to left.
**Notice that this also happens to other sidebar and my forum uses fa-IR language.**

**Comment by pitaj** [comment]
Ok it's because of the language choice being right-to-left. I'm on it.

**Comment by mohammadhassan99** [comment]
@pitaj Thanks, I have another problem too. That is due to right-to-left problem. These words are not right-to-left aligned.

![photo5828183523486444744](https://user-images.githubusercontent.com/31972226/33295112-f8be67e0-d3e8-11e7-9d7c-576579053ae5.jpg)

**Comment by pitaj** [comment]
For that issue, I'd suggest opening an issue at https://github.com/NodeBB/nodebb-theme-persona/issues

**Comment by pitaj** [comment]
Fixed at https://github.com/NodeBB/nodebb-theme-persona/commit/a38221f1c90ae7a4bcc916920a4e89aa87ea5d8b

**Comment by mohammadhassan99** [comment]
@pitaj I updated NodeBB but it didn't fix.

**Comment by pitaj** [comment]
A version of persona with the fix hasn't been released yet
