### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6128]
- NodeBB version: 1.7.0
- NodeBB git hash: dbdc05404daeac7021b60f22f7c18588ca126cfd
- Database type: mongo
- Database version: 3.2.11
- Exact steps to cause this issue:

In ACP, I went to setting > notification and set uid value.

- What you expected:

 I expected to redirect to home page.

- What happened instead:

I saw json in result.

**Comment by barisusakli** [comment]
Setting that uid makes the welcome notification come from that user, can you give more reproduction steps? What did you do to get json result?

**Comment by mohammadhassan99** [comment]
@barisusakli I only set this:


![photo_2017-11-28_21-14-55](https://user-images.githubusercontent.com/31972226/33335071-3400bfa4-d481-11e7-97bb-ac4c980ad274.jpg)

**Comment by barisusakli** [comment]
Setting the notification link to a topic sends me to that topic, I don't get a json result.

**Comment by mohammadhassan99** [comment]
@barisusakli Thanks, the problem solved after using these commands: 
``./nodebb stop``
``./nodebb build``
``./nodebb start``
