### ISSUE TITLE
Rules and restrictions for selecting username

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6129]
- **NodeBB version:** 1.7.0
- **NodeBB git hash:** dbdc05404daeac7021b60f22f7c18588ca126cfd
- **Database type:** mongo
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**

Tagged one of our users with this username: `` _MILAD_ ``

- **What you expected:**

I expected to see user's name linked with his account page.

- **What happened instead:**

I just saw his name only, the word is not linked with account page!

![2017-11-28_165958](https://user-images.githubusercontent.com/31972226/33322159-931e3fda-d45d-11e7-81c5-eda40246158d.png)

Why this happens? how can we solve this?
Do we have any rules and restrictions for selecting usernames?

**Comment by barisusakli** [comment]
Seems like markdown plugin is processing the text before the mentions plugin. Maybe increasing the priority of the `filter:parse.post` hook in mentions would fix this.

**Comment by julianlam** [comment]
Might be related to the username... `_MILAD_`. Can you share the link to his account profile on your forum @mohammadhassan99 ?

**Comment by mohammadhassan99** [comment]
@julianlam Yes of course: https://forum.sanatisharif.ir/user/_milad_

**Comment by mohammadhassan99** [comment]
@julianlam Yes of course: `` https://forum.sanatisharif.ir/user/_milad_ ``

**Comment by julianlam** [comment]
Does the mention work with `@milad` or `@-milad`?

**Comment by mohammadhassan99** [comment]
@julianlam 

![2017-11-28_211855](https://user-images.githubusercontent.com/31972226/33335270-d22a4a06-d481-11e7-9e4b-7c38adac3185.png)

**Comment by julianlam** [comment]
Okay, thanks, I will try to reproduce on my end.

**Comment by julianlam** [comment]
Looks like we may have to disallow use of `_` in slugs, I've made the change in #6133, will merge if tests pass...

**Comment by voanhcuoc** [comment]
> disallow use of _ in slugs

This restriction is just a workaround. Discourse allow underscore, so do you. string after `@` should be handled out of markdown context.

**Comment by julianlam** [comment]
The development of logic to handle the @ sign followed by underscore requires more research than I can do at the moment. Feel free to try it out and submit a PR, but I'm not too familiar with building markdown-it plugins.
