### ISSUE TITLE
emoji box doesn't open completely (emoji v2) 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6131]
- **NodeBB version:** 1.7.0
- **NodeBB git hash:** a849a772bf8924181013bbd8f566a79321c0ab45
- **Database type:** mongo
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**
1- In editor, clicked on emoji icon
2- the emoji box opened

- **What you expected:**
I expected to see the box opened completely.

- **What happened instead:**
It didn't open completely, as you can see below.

![2017-11-28_211340](https://user-images.githubusercontent.com/31972226/33336225-7db86aa4-d484-11e7-9678-07b48cf1882f.png)

**Comment by pitaj** [comment]
I'm not sure what you mean by "didn't open completely". What you're seeing is essentially correct, though there may be a slight bug in the CSS for RTL languages. 

For instance, this is what I see, which is the expected layout:
![image](https://user-images.githubusercontent.com/803701/33337318-de9ab746-d42f-11e7-8d9b-64e012183f00.png)

**Comment by pitaj** [comment]
Also, please open future issues related to emoji v2 on the Github page for it: https://github.com/nodebb/nodebb-plugin-emoji

**Comment by mohammadhassan99** [comment]
@pitaj I mean the word "people" is not clear and also in [NodeBB forum](https://community.nodebb.org/), I see a scroll bar in emoji box but I cant see the scroll bar in my emoji box !
And also one other problem: I can't move the emoji box and It opens exactly on the right of the screen!

![2017-11-28_221401](https://user-images.githubusercontent.com/31972226/33338023-0a34cf04-d48a-11e7-9856-3169b8dddbd7.png)
Scroll bar in NodeBB forum ☝️ 

![2017-11-28_221458](https://user-images.githubusercontent.com/31972226/33338054-198fbbc6-d48a-11e7-9708-861af4e3afc3.png)

my emoji box ☝️ 

I think now you can understand what I mean.

**Comment by pitaj** [comment]
You can fix this by running `npm i --save nodebb-plugin-emoji@latest`

**Comment by julianlam** [comment]
Won't this revert if he runs ./nodebb upgrade?

**Comment by pitaj** [comment]
Ya, so don't do that until 1.7.2

**Comment by mohammadhassan99** [comment]
@pitaj @julianlam Ok, thank you all 😊 🙏
