### ISSUE TITLE
package.json file not found error when npm install command

### ISSUE THREAD

**Issue by hayrullahcansu** [NodeBB/NodeBB#6141]
- **NodeBB version:** 1.7.x
- **NodeBB git hash:** 

- **Database type:** mongo
- **Database version:** 

- **Exact steps to cause this issue:**
	1   i cloned 1.7.x version
        2   then i tried node app.js --setup
        3   i got error that is like this "Error: Cannot find module 'nconf'"
        4   run npm install to fix this error, but 1.7.x branch has no package.json because .gitignored this item. 
        5  i fixed error by adding package.json manually and run npm install again.

- **What you expected:**
I expected adding package.json to 1.7.x and remove it from gitignore file
- **What happened instead:**

**Comment by pitaj** [comment]
Use `./nodebb setup` instead
