### ISSUE TITLE
CLI setup does not work in 1.7.1

### ISSUE THREAD

**Issue by gramakri** [NodeBB/NodeBB#6142]
- **NodeBB version: 1.7.1 (github released tarball)** 
- **Database type:** mongo

On Cloudron, we do the initial setup using `/app/code/app --setup "${setup}"  --series`. Trying to debug the issue, it appears there is a spurious `prestart.loadConfig` introduced by https://github.com/NodeBB/NodeBB/pull/6058 at https://github.com/NodeBB/NodeBB/blob/master/src/cli/setup.js#L22. Not sure how that can work since prestart.loadConfig does not take a callback - https://github.com/NodeBB/NodeBB/blob/master/src/prestart.js#L27

**Comment by pitaj** [comment]
You're correct, that does appear to be a bug. However, it shouldn't prevent the setup from running, it will just prevent the build from running after the setup completes as far as I can tell. 

That's what you'd think would happen anyways, but it appears that it doesn't error or even hang after the setup function completes (when it is called via `./nodebb setup` or `node app --setup`), which is extra weird. That must be why this bug wasn't caught earlier.

Can you provide the error you get?

**Comment by gramakri** [comment]
The error I get is:

```
21:31:03 [main] => Running initial setup
21:31:04 [main] 3/12 05:31:04 [9] - info: NodeBB v1.7.1 Copyright (C) 2013-2017 NodeBB Inc.
21:31:04 [main] 3/12 05:31:04 [9] - info: This program comes with ABSOLUTELY NO WARRANTY.
21:31:04 [main] 3/12 05:31:04 [9] - info: This is free software, and you are welcome to redistribute it under certain conditions.
21:31:04 [main] 3/12 05:31:04 [9] - info:  
21:31:04 [main] 3/12 05:31:04 [9] - info: NodeBB Setup Triggered via Command Line
21:31:04 [main] 
21:31:04 [main] Welcome to NodeBB!
21:31:04 [main] 
21:31:04 [main] This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
21:31:04 [main] Press enter to accept the default setting (shown in brackets).
21:31:05 [main] 3/12 05:31:05 [9] - info: 
21:31:05 [main] Now configuring mongo database:
21:31:05 [main] Configuration Saved OK
21:31:05 [main] 3/12 05:31:05 [9] - info: [database] Checking database indices.
21:31:05 [main] 3/12 05:31:05 [9] - info: [database] Checking database indices done!
21:31:05 [main] Populating database with default configs, if not already set...
21:31:06 [main] 3/12 05:31:06 [9] - warn: [cache-buster] could not read cache buster Error: EISDIR: illegal operation on a directory, read
21:31:06 [main]     at Error (native)
21:31:06 [main] Previous theme detected, skipping enabling default theme
21:31:07 [main] Categories OK. Found 4 categories.
21:31:07 [main] Administrator found, skipping Admin setup
21:31:07 [main] 3/12 05:31:07 [9] - info: Global Moderators group found, skipping creation!
21:31:07 [main] Enabling default plugins
21:31:07 [main] 3/12 05:31:07 [9] - info: [install/defaultPlugins] customDefaults
21:31:07 [main] 3/12 05:31:07 [9] - info: [install/enableDefaultPlugins] activating default plugins 0=nodebb-plugin-composer-default, 1=nodebb-plugin-markdown, 2=nodebb-plugin-mentions, 3=nodebb-widget-essentials, 4=nodebb-rewards-essentials, 5=nodebb-plugin-soundpack-default, 6=nodebb-plugin-emoji, 7=nodebb-plugin-emoji-android
21:31:07 [main] 3/12 05:31:07 [9] - warn: You have no mongo username/password setup!
21:31:07 [main] 3/12 05:31:07 [9] - error: NodeBB could not connect to your Mongo database. Mongo returned the following error MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
21:31:07 [main]     at Pool.<anonymous> (/run/nodebb/node_modules/mongodb-core/lib/topologies/server.js:336:35)
21:31:07 [main]     at emitOne (events.js:96:13)
21:31:07 [main]     at Pool.emit (events.js:188:7)
21:31:07 [main]     at Connection.<anonymous> (/run/nodebb/node_modules/mongodb-core/lib/connection/pool.js:280:12)
21:31:07 [main]     at Connection.g (events.js:291:16)
21:31:07 [main]     at emitTwo (events.js:106:13)
21:31:07 [main]     at Connection.emit (events.js:191:7)
21:31:07 [main]     at Socket.<anonymous> (/run/nodebb/node_modules/mongodb-core/lib/connection/connection.js:187:49)
21:31:07 [main]     at Socket.g (events.js:291:16)
21:31:07 [main]     at emitOne (events.js:96:13)
21:31:07 [main] 3/12 05:31:07 [9] - error: [build] Encountered error preparing for build MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
```

**Comment by pitaj** [comment]
Ok, so the error there implies one of several possible failures:
- Mongo isn't running
- The mongo db connection information is incorrect
- The information isn't being passed correctly through the nodebb code

According to those messages, NodeBB is trying to connect to mongo at `127.0.0.1:27017`. Is that correct, or have you specified a different mongo connection that is, because of some hidden error, not being used here?

**Comment by gramakri** [comment]
@pitaj Yes, I have specified a mongo connection which is different from the defaults.

What happens above is that prestart.loadConfig is called with the callback as the configFile argument from https://github.com/NodeBB/NodeBB/blob/master/src/cli/setup.js#L22. Then, https://github.com/NodeBB/NodeBB/blob/master/src/prestart.js#L30 ends up resetting the configs and thus the mongo connection variables I had set initially are gone.

**Comment by gramakri** [comment]
@pitaj Debugging a little more, prestart.js ends up resetting the config. Interestingly, builds.buildAll, gets called despite the fact that prestart.loadConfig does not call any callback (is this async feature or some other bug somewhere?) I see that the error then comes from builds.buildAll -> beforeBuild -> db.init

**Comment by pitaj** [comment]
Yeah I don't know why it doesn't just hang there. My intuition is that nconf is executing the `configFile` as a function when it gets passed there, but I can't find any references for why that is.

Anyways, I'm working on a fix. In fact, I'm gonna make it possible to just call `./nodebb setup [initial config JSON]` instead of needing to use `node app --setup [initial config JSON]`.
