### ISSUE TITLE
tags link are not working in your own installed nodebb

### ISSUE THREAD

**Issue by DavidGOrtega** [NodeBB/NodeBB#6145]
![image](https://user-images.githubusercontent.com/414967/33602435-994bd528-d9af-11e7-9713-c7e062f88d06.png)

![image](https://user-images.githubusercontent.com/414967/33602475-b03e7cb8-d9af-11e7-9486-1a5f44b7a8fa.png)

As you can see in the URL I have followed the databse tag which is meant to be 19 tagged posts https://community.nodebb.org/tags/database  and the results page is empty

**Comment by barisusakli** [comment]
I think this is fixed on latest master, I updated our forum as well. Let us know if it happens again.
