### ISSUE TITLE
admin account was locked, how to unlock it? use forget password and send email can not receive email.

### ISSUE THREAD

**Issue by linfanboss** [NodeBB/NodeBB#6148]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

**Comment by pitaj** [comment]
https://community.nodebb.org/topic/1888/account-locked-temporarily-issues/14
