### ISSUE TITLE
Cannot tag users which have underline character 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6149]
- **NodeBB version:** 1.7.1
- **NodeBB git hash:** a77a681156d5e607f97789b061f162b507872e4f
- **Database type:** mongo
- **Database version:** 3.2.11

@julianlam @barisusakli Hello, a week ago I posted [an issue](https://github.com/NodeBB/NodeBB/issues/6129) about tagging users which have ``_`` in their usernames (first character). But now a strange problem happend. Now users which have ``_`` won't receive notification and their usernames are not linked with profile page. **No matter ``_`` is the first character or not!**

What cause this problem? markdown-it?

**Comment by julianlam** [comment]
`_MILAD_` needs his username re-slugged. Change his username to something else, then back again.

**Comment by mohammadhassan99** [comment]
@julianlam Thanks for fixing this problem. Now ``_MILAD`` username also can be tagged and it links to profile page 😃
