### ISSUE TITLE
Error: Cannot find module './user' when calling module.parent.require('./user');

### ISSUE THREAD

**Issue by hayrullahcansu** [NodeBB/NodeBB#6151]
- **NodeBB version:** 1.7.x
- **NodeBB git hash:** 
- **Database type:** mongo 
- **Database version:** 

- **Exact steps to cause this issue:**

      1.) i development a custom plugin as hello world level.
      2.) a tested it working.
      3.) then i deleted project. 
      4.) i started again from the beginning.
      5.) i get error when nodebb building.  (./nodebb dev)

`var User = module.parent.require('./user');`  not working
this is a nodebb-plugin-quickstart controller. 
![image](https://user-images.githubusercontent.com/10001588/33684590-d67bf2da-dadf-11e7-8add-df4e0b248792.png)

this is a error log
![image](https://user-images.githubusercontent.com/10001588/33684756-65ff8de0-dae0-11e7-9cd5-715fd4820ec9.png)

**Comment by barisusakli** [comment]
Try `require.main.require('./src/user');`, these questions are better for https://community.nodebb.org

**Comment by hayrullahcansu** [comment]
its working thanks !
