### ISSUE TITLE
How to support Chinese search？

### ISSUE THREAD

**Issue by Relsoul** [NodeBB/NodeBB#6153]
- **NodeBB version:**   1.7.1
- **Database type:**  redis 
- **Exact steps to cause this issue:**

**Comment by julianlam** [comment]
Hi @Relsoul -- at current, Chinese text search is not supported via the native database search engine, but is supported via `nodebb-plugin-solr`. Let me know if the plugin does not work for you. Thanks!

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
