### ISSUE TITLE
Ability to find user via UID

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6154]
Hello,

I often find myself in a need of determining username when having only UID available - for example logs show some error related to that user. It would be great if `/admin/manage/users/search` allowed searching via UID because now it involves either scanning through `/admin/manage/users/latest` manually or querying database myself.

Thanks!

**Comment by julianlam** [comment]
Hi @attis, does the `/uid/<uid>` secret route help at all? :smile:

**Comment by attis** [comment]
I certainly does! Feel free to close this issue if you want :)
