### ISSUE TITLE
On mobile the admin left pane has the search link 2 times

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/NodeBB#6156]
Version 1.7.2 

Take a look at the following screenshot. 

<img width="191" alt="screen shot 2017-12-08 at 20 20 53" src="https://user-images.githubusercontent.com/1268723/33781564-6aaa5d9a-dc55-11e7-933e-b09c2d899637.png">

The search link is there 2 times. Not a biggy but worth mentioning

**Comment by barisusakli** [comment]
Can you take a look at /admin/general/navigation and see if you can disable the search item there. That should get rid of the extra search icon I think.

**Comment by jimmykane** [comment]
Thanks @baris. Forgot to resolve this. That was the issue.
