### ISSUE TITLE
More friendly support for yarn and pnpm

### ISSUE THREAD

**Issue by a632079** [NodeBB/NodeBB#6157]
Nodebb use npm as default package manager now, it 'ok. but, I can't let it use yarn as default package manager. It usually means that I can't use nodebb init command or nbpm, upgrade scripts (with no options) if I want to use yarn.
Yarn is not completely compatible with npm. After running `yarn install` and running `npm install` again
It will remove packages installed by yarn.
Now, I just could run this script in fish shell for init.:
```
git clone -b v1.7.x https://github.com/NodeBB/NodeBB.git nodebb; and cd ./nodebb ;and cp install/package.json package.json ;and yarn install --production ;and ./nodebb setup
```
And run this for plugins update:
```
yarn  upgrade-interactive
```

I hope you can support select yarn as default package manager.(by command options , by `config.json` etc.)

-----------------------------------------
To DO list:
* [x] ignore `yarn.lock`
* [ ] Add a option in `config.json` to use `yarn` instead `npm` as default.

**Comment by pitaj** [comment]
> After running `yarn install` and running `npm install` again. It will remove packages installed by yarn.

I don't see how this could be the case. Both `npm install` and `yarn install` are dependent on the contents of `package.json` for what npm should look like. If anything, `npm install` would reinstall every package that yarn just installed.

**Comment by a632079** [comment]
@pitaj ahh，Please forgive my English is not good.  If you use npm(usually run by nodebb) after using yarn, It will remove packages installed by yarn and reinstall these. It means that the next time you use yarn, it will also reinstall all the packages. it could be a vicious circle.

**Comment by pitaj** [comment]
Ok, so not so much a problem, more of a wasteful annoyance. Regardless, I do think the feature has relevance. It'll be additional future-proofing. 

I'd actually like to see yarn become the default package manager that NodeBB uses, and this feature would allow a much easier transition.

**Comment by a632079** [comment]
Ahhh, had you seen `pnpm` before? It's a good packages manager, which seems quicker than yarn and npm.
I think is a similar issue.
A list to support it.
[ ] `ignore shrinkwrap.yaml`
[ ] Add a option in `config.json` to use `pnpm` instead `npm` as default
