### ISSUE TITLE
Show unsubscribe link in all configurable email (digest+post+chat?)

### ISSUE THREAD

**Issue by mfalkvidd** [NodeBB/NodeBB#6160]
In NodeBB v1.7.2, only notification emails set the showUnsubscribe parameter (see https://github.com/NodeBB/NodeBB/blob/c839d1cbc0abde6944975ee71d6a6b5894b735d2/src/notifications.js#L226 )

This means no other emails show the unsubscribe link. Maybe that's ok for most of the emails (since they actually can't be turned off), but the following emails are configurable so they should show the unsubscribe link:
- digest
- notif_post
- notif_chat
- (maybe some of the other emails?)

We got a complaint from a forum user who expected an unsubscribe link in the digest email.

Perhaps all outgoing email should include some sort of footer text? For notifications that can't be turned off the text could say something like "This is an important notification regarding your account at {url} and cannot be turned off."

Our workaround for now is to remove the IF clause from the digest email template. I also changed the link from
`{url}/uid/{uid}/settings`
to
`{url}/uid/{uid}/settings#dailyDigestFreq`
to make it easier for the user to find the right setting (they have to scroll down quite a bit otherwise)

**Comment by barisusakli** [comment]
notif_post and notif_chat are no longer used(notification.tpl replaced them), added the setting to digest
