### ISSUE TITLE
users had problems registering with v1.7.2

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#6162]
```
NodeBB version: v1.7.2
NodeBB git hash: 5ff5b6c699827efce6823277b95869a776477dd3
nodejs version: 8.9.3-1nodesource1
Database type: mongodb
Database version: v3.4.10
Exact steps to cause this issue:
Users reported unable to register
```

Had a couple of emails after updating to v1.7.2 about being unable to register. I was aware of a registration related commit - reverting it resolved the issue.

I reverted this commit - fd78eb6d5786b068bd7a7cb674f9f3ca84ac37c5

emails i got - note that there was 13 hours with no users, so it does look like no-one was able to complete registration

>Good night. I'm sending this situation to this e-mail cause registering to the forum isn't possible. I'm trying to register my e-mail to the forums, but the proccess always stop in the middle. I fill my e-mail, username, password, agree with the terms, but then, the browser returns to forum main page and nothing happen. i don't receive any e-mail, i can`t login... so i would like to know how can i solve this problem and do my register properly.

and

>I have been trying to register into the RetroPie forum but as soon as I enter my email, username, etc... and verify that I am not a robot (accepting the terms of use, too!), I am immediately taken back to the thread I visited last, and no confirmation email is sent to my address.
So, is registration disabled somehow?

We have a forum terms of user and a google captcha. Captcha is via spam-be-gone - I assume it's an issue related to compatibility with that plugin ? (if confirmed I can report it there, but it's a common plugin so posting here first).

**Comment by joolswills** [comment]
Just to confirm - reverting that commit resolved the issue and users were able to register. I suspect it may be related to the plugin as mentioned, but don't have a copy of the forum to test/verify (although that would be useful for debugging issues I guess).

**Comment by barisusakli** [comment]
@joolswills let me know if you still have this problem on master

**Comment by joolswills** [comment]
I don't have registration queue enabled. Will test and get back to you.

**Comment by joolswills** [comment]
Tested on master and was able to register fine. Thanks.
