### ISSUE TITLE
Online users ACP difference

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#6164]
Using NodeBB version 1.7.1 (but also noticed this with version since 1.4.5 or something) I noticed this small difference:
When looking at yourforum.com/users?section=online I see (just now) 3 users on the forum, 2 Guests and myself.
However when I look at the ACP dashboard I see "2 Users, 2 Guests, 4 In Total, 4 Connections".
The question of course is: Which display is actually being correct?
I'd assume that in the ACP my own account is counted twice?

**Comment by barisusakli** [comment]
The acp values use websocket connections to show those numbers, the client side online users page only shows active users(users who used ajaxify) in the past 5 minutes.
