### ISSUE TITLE
Default digest newsletter header too wide on mobile

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6165]
- **NodeBB version:** Whatever's deployed on community.nodebb.org
- **NodeBB git hash:** 🤷‍♂️

The digest e-mail I received from community.nodebb.org looks good on desktop client, but on a mobile the header is too wide which produces the following effect:

![img_0116](https://user-images.githubusercontent.com/591754/33906429-306835fa-df82-11e7-8eb9-fecd7c43d642.PNG)

**Comment by julianlam** [comment]
Header no longer in use in digest :smile:
