### ISSUE TITLE
Auto-hiding navbar persists if browser resized

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6170]
- **NodeBB version:**  v1.7.2
- **NodeBB git hash:** n/a

- **Database type:** mongo or redis
- **Database version:** Both

- **Exact steps to cause this issue:**
1. Resize screen to toggle mobile view
1. Refresh page
1. Note that upon scrolling down, navbar hides, and re-appears when scrolling up
1. Resize screen to desktop view
1. Note that auto-hiding navbar still persitss
- **What you expected:**

Expected navbar to stop auto-hiding in desktop mode, and resume auto-hiding in mobile mode.
- **What happened instead:**

It decides "mobile" or "desktop" based on initial page load, and does not change behaviour based on viewport changes.

**Comment by petergood** [comment]
I think this bug is more related to Persona and the library it uses to hide the navbar, Pulling.

**Comment by pitaj** [comment]
Pulling doesn't hide the navbar

**Comment by petergood** [comment]
The problem is here: https://github.com/NodeBB/nodebb-theme-persona/blob/master/lib/persona.js#L14
The script only checks the size of the viewport on initialisation.
