### ISSUE TITLE
Slideout menus interference on Post Queue page

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6173]
- **NodeBB version:** 1.7.2
- **NodeBB git hash:** 5ff5b6c699827efce6823277b95869a776477dd3

On mobile, if you are at queued posts page, when you slide the text to the sides to read it, notifications or chat panels show up:

![1513334134614-screenshot_20171215-083404-resized](https://user-images.githubusercontent.com/591754/34038507-e1046e22-e18c-11e7-83a7-08a552b2ebad.png)

**Comment by pitaj** [comment]
Need to add the ignore class in Persona.

**Comment by barisusakli** [comment]
Actually the post queue is here https://github.com/NodeBB/NodeBB/blob/master/src/views/admin/manage/post-queue.tpl

**Comment by dangerusslee** [comment]
This is also an issue on the flags page
