### ISSUE TITLE
Enable soft deletion of chat messages

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6181]
Right now chat message deletion is final, it is removed from the database completely. For posterity reasons, keeping this data is desirable, so we want to change the logic so that deleted messages are not perma-deleted, and can be restored at a later time if needed.

**Comment by mohammadhassan99** [comment]
Hi @julianlam , you mean it can be restored by the users ? 😃

**Comment by julianlam** [comment]
Yes, deleted messages no longer are purged from the database
