### ISSUE TITLE
Error when banning a user

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6182]
- **NodeBB version:** 1.7.2
- **NodeBB git hash:** 2053472ef3505a01ce19bfb38d4dff8829591d91
- **Database type:** mongo
- **Database version:** 3.2.11
- **Exact steps to cause this issue:**

1- Went to user profile
2- Tried to ban the user

- **What you expected:**

I expected to see no error

- **What happened instead:**

An error occured: 
``` 
error 
message limit reached
```

**Comment by barisusakli** [comment]
I can't seem to reproduce. That error message doesn't seem to be in core as well.

**Comment by mohammadhassan99** [comment]
@barisusakli 

![photo_2017-12-22_12-47-09](https://user-images.githubusercontent.com/31972226/34292465-4cbb8982-e716-11e7-8df1-9bbf187410e1.jpg)

**Comment by barisusakli** [comment]
Are you using a 3rd party emailer? Seems like banning a user sends an email and if you reached your email limit you might be getting this error message.

**Comment by mohammadhassan99** [comment]
@barisusakli Yes you are right. We use mailgun. But I think It should show a warning that you reached email limit and ban user without sending email? Don't you think so? I mean that reaching email limit shouldn't stop banning!
