### ISSUE TITLE
Plugin upgrade logic no longer works

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6183]
- **Exact steps to cause this issue:**

1. Downgrade a plugin to an older version (e.g. nodebb-plugin-tenor-gif@1.0.0)
1. Run `npm i`

- **What you expected:**
  - `nodebb-plugin-tenor-gif@1.0.2`

- **What happened instead:**

```
$ ./nodebb upgrade -p

Updating NodeBB...
1. Checking installed plugins for updates...
OK
  OK
```

... and v1.0.0 is still installed

----

The reasoning behind this is that the change to adhere to npm@5's new logic meant that all dependencies are saved into `package.json`.

The package upgrade logic compares `package.json` with what is in `node_modules/` and diffs them to see which plugins are considered "extraneous", and checks only those for upgrades.

... for obvious reasons, now that everything is in `package.json`, it and `node_modules/` are now in sync and there are never any extraneous plugins.

**Comment by psychobunny** [comment]
OK
