### ISSUE TITLE
timeago strings are not translated

### ISSUE THREAD

**Issue by thalic** [NodeBB/NodeBB#6187]
In 1.7.2 timeago strings are not translated (tested with german translation)

**Comment by thalic** [comment]
Only if  "pagespeed EnableFilters inline_javascript;" is enabled.

**Comment by julianlam** [comment]
Sounds like a configuration issue with your proxy, no?

**Comment by mohammadhassan99** [comment]
@julianlam I had this problem too, but as @sohrabafard said in **[this issue](https://github.com/NodeBB/NodeBB/issues/6075)**, I used his tip and now I have no problem.

**Comment by julianlam** [comment]
Much like we discourage the use of CloudFlare Rocket Loader (as it messes up our scripts), use of Google PageSpeed is similarly discouraged as its improper handling of our minfile seems to be a bug on their end.
