### ISSUE TITLE
Crawlers or error requests skew up the Dashboard data

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/NodeBB#6193]
Latest version (was always the case) 

Take a look at this

<img width="856" alt="screen shot 2017-12-21 at 21 58 15" src="https://user-images.githubusercontent.com/1268723/34274739-3fa74bb8-e69a-11e7-9db5-19146cc4c983.png">

Sorry, but what am I supposed to understand from this graph apart from that I had a crawler or some scanning related activity (kiss). 

Can't a more clever algorithm for scaling Y and the 2 sets be used?

**Comment by julianlam** [comment]
> Can't a more clever algorithm for scaling Y and the 2 sets be used?

Yes, and I bet [Chart.js](http://www.chartjs.org/) has support for it. We'd appreciate a PR if you can submit one.

As for the crawlers, we'd like to segregate them to a different user bucket, though this is also on the backlog.

**Comment by jimmykane** [comment]
Ah, I have worked with chart.js. I'll take a look into it. Most work would be to reproduce the data I suppose.

**Comment by julianlam** [comment]
@jimmykane That's great to hear 😄 Since we already have two distinct data sets, I don't think there will need to be any changes besides some config changes in the client side.

[Likely around here...](https://github.com/NodeBB/NodeBB/blob/master/public/src/admin/general/dashboard.js#L220)

**Comment by jimmykane** [comment]
Oh! Top! 🕺
