### ISSUE TITLE
Email Notification Subject no longer shows thread title

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6202]
- **NodeBB version:** v1.7.3
- **NodeBB git hash:** 0020b8a18b7ad9345162a5843817458724dafc14

- **Database type:** mongo
- **Database version:** v3.4.9

- **Exact steps to cause this issue:** 
Email notification subject regressed to not show the thread title.  

- **What you expected:**  I expected the thread title to continue to be in the email subject.  

- **What happened instead:**

Instead it just says You have a new Notification from Forum Name.

**Comment by dangerusslee** [comment]
Is 1.8.0 going to be the next release?

**Comment by barisusakli** [comment]
Yes
