### ISSUE TITLE
Older Versions CSRF Token

### ISSUE THREAD

**Issue by t0rched** [NodeBB/NodeBB#6205]
- **NodeBB version: v1.0.3 or Less** 
- **Database type: Mongo** 

Can't get any version at or below 1.0.3 to work. Invalid CSRF token on initial admin login. 

Using SSL, have forwarded HTTPS with nginx proxy. 

config.json ... https://mydomain.com
nginx proxy... http://localhost:4567

Valid SSL etc...

Only need this to use nodebb-plugin-import. Says to start with v1.0.3 and upgrade after import.

**Comment by t0rched** [comment]
Nevermind. Dug this up in an older post somewhere, fixes the issue:
`cp node_modules/socket.io-client/dist/socket.io.js node_modules/socket.io-client/`

**Comment by julianlam** [comment]
Unfortunately that version is far too old for us to support, sorry!

But thanks for sharing the workaround 🙂
