### ISSUE TITLE
Ampersands in tags need to be escaped.  

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6212]
- **NodeBB version:** v1.7.3
- **NodeBB git hash:** 0020b8a18b7ad9345162a5843817458724dafc14

- **Database type:** mongo
- **Database version:** v3.4.9

- **Exact steps to cause this issue:** 
Create a tag with an & in it.  

- **What you expected:** I expected the & to be propery escaped in html as in 

`
&amp;
`

- **What happened instead:**

Instead it wasn't escaped and edge wasn't happy.  

	
`
<a href="/tags/books&mags"><span class="tag small" style="">books&mags</span></a>
`
`
HTML1402: Character reference is missing an ending semicolon ";".
`

**Comment by barisusakli** [comment]
Seems like there are multiple places that this is causing issues.

One is in the head section in the `<title>` tag;

```
HTML1402: Character reference is missing an ending semicolon ";".
<title>Topics tagged under "some&tag" | brower &amp; title</title>
```

The browser title is properly escaped but the title is unescaped by the translator module. https://github.com/NodeBB/NodeBB/blob/master/src/middleware/header.js#L114

Second one is in the topic listing

```
HTML1423: Malformed start tag. Attributes should be separated by whitespace.
<meta itemprop="name" content="Topics tagged under "some&tag"">
```

Again seems like translator is turning `&amp;` into `&`
