### ISSUE TITLE
Category Sort by vote does not work correctly when moving topics

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6214]
- **NodeBB version:** v1.7.3
- **NodeBB git hash:** 0020b8a18b7ad9345162a5843817458724dafc14

- **Database type:** mongo
- **Database version:** v3.4.9

- **Exact steps to cause this issue:** 
Sorted by Votes and then moved a thread out of the category.  

- **What you expected:** I expected thread to be gone

- **What happened instead:**

.  Instead it is still there (and missing from the new category).  Also I think nodeBB froze the pipes in my house.  Ever since I noticed this bug, there has been no water in one of the bathrooms.   Please fix it soon, I really need a shower.  

If you need inspiration, my plugin was working pretty well until this got introduced into core.  
https://github.com/dangerusslee/nodebb-plugin-category-sort-by-votes-next

**Comment by barisusakli** [comment]
Sorry can't help with frozen pipes 😆

**Comment by dangerusslee** [comment]
:-)

Won't you need some sort of reindex to delete any left overs and add new values?

**Comment by barisusakli** [comment]
I don't think its worth the effort, you can fix the topic by moving it back to the old category and moving again.

**Comment by dangerusslee** [comment]
I could, but since this has been out for a while, I don't even know what threads belong in which categories.  There could be hundreds or thousands of threads that have been moved, but will not show up properly under this sort method.  

I would rather not manually muck around with nodebb to fix it.

**Comment by barisusakli** [comment]
I will see if I can write a upgrade script for 1.8.0 so old references are fixed
