### ISSUE TITLE
Weird listing when sorting by votes

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/NodeBB#6215]
NodeBB version 1.7.3

I have the following categories

Feedback Category
| generic posts  on the above category
|--> Issues (sub-cat of feedback)
|--> Feature requests (sub-cat of feedback)

When I go to feedback (the parent category) and I use sort by votes I get all the threads of it's subcategories as well. 

Is this something by design or a bug?

**Comment by barisusakli** [comment]
Sounds like a bug, did you move topics from category to category by any chance? See https://github.com/NodeBB/NodeBB/issues/6214

**Comment by dangerusslee** [comment]
@jimmykane Don't forget that you had my plugin installed, so there may be some left over data as well.  

@barisusakli This is another reason the reindex is needed.  And not only on upgrade, as some people may not notice that the sort by vote is  now built into core, so the disabling of that plugin will likely happen after the upgrade scripts have ran.

**Comment by jimmykane** [comment]
@barisusakli and @dangerusslee  indeed that is the issue. 

Fortunately, I can move some topics around to fix it for now. 

@barisusakli we can close this as doup of #6214

**Comment by barisusakli** [comment]
@jimmykane I went ahead and fixed some of the references, let me know if you notices any issues.

**Comment by jimmykane** [comment]
@barisusakli you are the best! I ll take a look as soon as I am home.
