### ISSUE TITLE
Ability to edit tags

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6216]
- **NodeBB version:** v1.7.3
- **NodeBB git hash:** 0020b8a18b7ad9345162a5843817458724dafc14

- **Database type:** mongo
- **Database version:** v3.4.9

- **Exact steps to cause this issue:**  Try to edit a tag from the ACP.  

- **What you expected:** I expected there to be some way to edit it.  

- **What happened instead:**

Instead I wasn't able to edit it anywhere, so bug #6212 is continuing to cause issues until it's either a. fixed and I'm able to update to the new version or b.  I figure out how to do it manually from mongo.

**Comment by barisusakli** [comment]
By edit you mean changing the name of the tag and have it applied to all topics that were using that tag?

**Comment by dangerusslee** [comment]
@barisusakli Exactly.
