### ISSUE TITLE
Thread tool's "Mark unread for all" capitalization

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6217]
- **NodeBB version:** v1.7.3
- **NodeBB git hash:** 0020b8a18b7ad9345162a5843817458724dafc14

- **Database type:** mongo
- **Database version:** v3.4.9

- **Exact steps to cause this issue:** Click thread tools.  

- **What you expected:** I expected "Mark unread for all" to be capitalized the same way as the other menu items - each letter being capitalized such as "Mark Unread For All"

- **What happened instead:**

Instead it wasn't.

**Comment by julianlam** [comment]
`topic.json` pushed to Transifex
