### ISSUE TITLE
RethinkDB and SQLite support

### ISSUE THREAD

**Issue by PassTheMayo** [NodeBB/NodeBB#6218]
- **Exact steps to cause this issue:**
        1. Start the NodeBB setup
        2. Continue with your information untill...
        3. Oh no!
        4. It can't be!
        5. ...are you serious?
        6. ...
        7. There's no RethinkDB? or even SQLite?

- **What you expected:** I expected there to be some sort of other method of storing data other than Redis or Mongo. Not everyone likes that method of storage, like me. I prefer RethinkDB, and I would submit a pull request if I could figure out how you can make a custom storage system, but I'm on a Chromebook at the minute, and am unable to do so. SQLite is also another decent storage system, and is very easy to use, but that isn't an option. ;-;

- **What happened instead:** There was only *gasp* Mongo and Redis *shockers*!

**Comment by julianlam** [comment]
Hi there,

We're aware that NoSQL solutions may not be everyone's cup of tea, and so eventual implementation of a relational database adapter is on the backlog of tasks. While I can't promise any sort of time line at the moment, please be assured that you're not the only person who's asked 😉

**Comment by PassTheMayo** [comment]
Ok, thank you!
