### ISSUE TITLE
Test connection button on install page

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#6223]
Can you add a button to the installation page to test the connection to the db before submitting the form?

**Comment by pitaj** [comment]
Good idea

**Comment by antoine-pous** [comment]
And maybe tell the user if the DB used is not empty, no need to block the user, just give the information could avoid mistakes.

**Comment by barisusakli** [comment]
![image](https://github.com/NodeBB/NodeBB/assets/2583394/8d3e1c8a-5759-4274-88d4-760136ad16e2)
