### ISSUE TITLE
Page selector interferes on iPhone X

### ISSUE THREAD

**Issue by aStonedPenguin** [NodeBB/NodeBB#6224]
- **NodeBB version:** Whatever https://community.nodebb.org/ is running & older versions

It's probably worth accounting for considering the popularity of Apple devices.

![img](https://i.imgur.com/cBBCzCV.jpg)

**Comment by pitaj** [comment]
What do you mean by "interferes"? Please follow the template.

**Comment by julianlam** [comment]
I think based on the image he means the black bar is shown (when it should be hidden)...

**Comment by aStonedPenguin** [comment]
The black bar on the bottom replaces the home button on the iPhone X. There's no way of removing it or hiding it.

**Comment by pitaj** [comment]
Does the black bar interfere with the pagination, or does the pagination interfere with the black bar? Also, isn't the bar just a placeholder and everything is done with swipes?

**Comment by aStonedPenguin** [comment]
The black bar interferes and it is just a placeholder yes. It's definitely more an Apple being a pain issue rather than a nodebb issue but regardless it should still be addressed so everyone has a good user experience.

**Comment by pitaj** [comment]
So to be clear: the black bar doesn't interfere with any functionality, it's just visually unappealing.

**Comment by aStonedPenguin** [comment]
Yep

**Comment by julianlam** [comment]
> The black bar on the bottom replaces the home button on the iPhone X. There's no way of removing it or hiding it.

This is a stupid design decision. Just like the camera dipping into the screen space. Just dumb. We're restricted in vertical screen space as it is.
