### ISSUE TITLE
Failed search by UID in ACP returns the guest user

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6225]
- **NodeBB version:** v1.7.3
- **NodeBB git hash:** 0020b8a18b7ad9345162a5843817458724dafc14

- **Database type:** mongo
- **Database version:** v3.4.9

- **Exact steps to cause this issue:**  Try to search for a user in ACP using the uid field.  Put in a text that won't match like "a"  

- **What you expected:** I expected no results.  

- **What happened instead:**

Instead the guest user (uid=0) was found. 

  
  
![image](https://user-images.githubusercontent.com/24903887/34799576-55ab1e5a-f62e-11e7-9dcd-bdbeab8fc3ac.png)

**Comment by pitaj** [comment]
Can probably fix this by changing it to a number field.
