### ISSUE TITLE
Use group badge when they're @mentionned into a post

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#6230]
Hi!

Currently when we mention a group the forum display `@groupname`, can you replace it with the badge used on user profiles?

This will allow us to distinct when the post mention a user or a group. Sometime users have a similar nickname than groups and we can easily make a mistake :/

Thank you !

**Comment by barisusakli** [comment]
`plugin-mentions-group` class can be used to style the group mentions now
