### ISSUE TITLE
NodeBB community register

### ISSUE THREAD

**Issue by syde-sb** [NodeBB/NodeBB#6231]
I didn't get verification email. I tried to change email but not working.

**Comment by julianlam** [comment]
Check your junk mail.bin?

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
