### ISSUE TITLE
Disable globally categories icons

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#6234]
Hi!

Can you add an option into the forum settings to disable all categories icons?

When we don't use them it's annoying to remove them each time.

Thank you!

**Comment by julianlam** [comment]
Could you not clone an existing category (without an icon) instead? Seems that would be the easiest way to do it instead of introducing an admin option just to **not** set an icon on category creation.

**Comment by pitaj** [comment]
You can also house the icons with the custom CSS functionality.
