### ISSUE TITLE
Setup Failing

### ISSUE THREAD

**Issue by JohnCWakley** [NodeBB/NodeBB#6237]
- **NodeBB version: 1.7.3** 
- **NodeBB git hash: dabb1e8d6dbeb143976a9ad76d0233daae450467** 

- **Database type: mongo**
- **Database version: v3.4.10 (git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9)** 

- **Exact steps to cause this issue:**
Following the instructions at: https://docs.nodebb.org/installing/os/ubuntu/

1. Execute setup

- **What you expected:**
I expected the setup process to execute successfully.

- **What happened instead:**
```
$ ./nodebb setup
package.json not found.
Populating package.json...
OK
Dependencies not yet installed.
Installing them now...

net.js:701
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:701:11)
    at Object.installAll (/home/XXXXX/nodebb/src/cli/package-install.js:33:17)
    at Object.<anonymous> (/home/XXXXX/nodebb/src/cli/index.js:41:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

- **Notes:**
I'm running Ubuntu 16.04 LTS, fully patched on a DigitalOcean Droplet with 3gb RAM, 1gb swap.

Thank you!

**Comment by JohnCWakley** [comment]
I have solved my issue by first running:
$ npm install

After that, setup executed as expected.

I'm not sure if npm install is a missed step in the instructions, or if it is intended to execute within setup. But I'm sure others will be running into this and this is what worked for me.

I apologize if I have wasted anyone's time.

Thank you!

**Comment by pitaj** [comment]
This is a known bug on the current v1.7.x branch.

More info in #6221

**Comment by pitaj** [comment]
Gonna keep this open to track the issue

**Comment by JohnCWakley** [comment]
Ah, right on, my bad... 😁
