### ISSUE TITLE
Unneeded modal when editing Categories

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#6239]
NodeBB version: master
Database type: mongo

When creating or editing a Category in the ACP, and after making a change, toggling between the tabs for `Category Settings` or `Privileges` causes a `Do you want to navigate away from this page?` modal, when no page navigation is occurring.

**Comment by barisusakli** [comment]
Can you test on master? The privileges tab is removed and has its own page now.

**Comment by yariplus** [comment]
Sorry, it's still happening on master. Did you mean a different branch?

![](https://puu.sh/z2cxy/41d4ff96cd.png)

**Comment by barisusakli** [comment]
Hmm if you are on master, there shouldn't be `Privileges` tab, did you  run `./nodebb build`?

**Comment by yariplus** [comment]
Ahh, derp. It's good now. ;)
