### ISSUE TITLE
 Cannot find module 'colors'

### ISSUE THREAD

**Issue by id-owner** [NodeBB/NodeBB#6244]
![error](https://user-images.githubusercontent.com/32885967/34979159-7afd3bfa-fadb-11e7-8798-9f9f41a37d68.png)

**Comment by id-owner** [comment]
>npm init 
>npm install colors

**Comment by julianlam** [comment]
Follow issue template, what's the commit hash?

**Comment by julianlam** [comment]
Looks like this may be latest `v1.7.x`: https://github.com/NodeBB/NodeBB/blob/v1.7.x/src/cli/index.js#L31-L48
