### ISSUE TITLE
Email notifications for chat messages have "<strong>" in their titles 

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/NodeBB#6246]
Latest nodebb 1.7.3 

when I get a notification about a chat message the title contains HTML characters. 

<img width="602" alt="screen shot 2018-01-16 at 13 18 37" src="https://user-images.githubusercontent.com/1268723/34988685-ca65e7c6-fabf-11e7-83b7-7618ad55381b.png">

**Comment by barisusakli** [comment]
fixed in master https://github.com/NodeBB/NodeBB/commit/48cff9bfcb4efc4accac80517a7abe613a64e6b9
