### ISSUE TITLE
Manage upload through the ACP

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#6247]
Hi!

Currently we cannot manage uploads through the ACP, this kind of feature could be really usefull for:

1. Uploads other kinds of files like fonts, archives etc...
2. Delete unused/unwanted files
3. Allow groups to upload only some files exts and give more choices to trusted users

I know, this can be done with an (s)ftp access, but using a native feature is clearly the best way to do it.

Thank you!

**Comment by julianlam** [comment]
@antoine-pous I agree -- being able to administer uploaded files would be helpful (especially if the file is no longer being referenced in the post itself, aka an orphaned attachment).

Thanks for the suggestion 😄
