### ISSUE TITLE
Uploading files to a new topic - not working

### ISSUE THREAD

**Issue by Silvia-t** [NodeBB/NodeBB#6252]
Hi all,

I've found a bug when trying to upload files to a new topic -- it doesn't work. You need to post a silly message first and then, on the second post, you can attach the files. Also, when the upload fails, it doesn't give any feedback to the user (it shows the blue bar at the top as if uploading, but then nothing happens).

These are the details of my forum:

- NodeBB version: v1.7.1
- NodeBB git hash: c4a8138dedb96f4b0d93e8e6f9d0b77ffe3b5615
- Database type: mongo 
- Database version: v3.2.17

To reproduce the issue:
1. Create a new topic and upload / attach any file. 

Thanks :)

**Comment by barisusakli** [comment]
Since you are on 1.7.1 you need to select a category first before uploading and have the upload privilege for that category. Let me know if its still not working after that.

**Comment by Silvia-t** [comment]
Thanks for your quick answer @barisusakli 

I'm not too sure I understand what you say.

I go to a category (eg. Testing) and then click on 'New Topic'. I then write a topic name (eg. test) and try to upload a file, and it doesn't work. Please see screenshot below.

![image](https://user-images.githubusercontent.com/23095224/35042869-20e14f60-fb82-11e7-9918-3017772e5a37.png)

Am I missing something?
Thanks.

**Comment by barisusakli** [comment]
Oh seems like you are using the redactor composer, can you give the default composer a try and see if it works there? Maybe it's a bug in the redactor composer.

**Comment by Silvia-t** [comment]
Aha!!! :+1: 
That's what it was!! :smile: 

Thanks @barisusakli I will report the bug to the redactor composer. I've changed it to the default composer now!
