### ISSUE TITLE
The link `https://bootswatch.com/united/bootstrap.min.css` was not found.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [NodeBB/NodeBB#6260]
NodeBB version: 1.5.0
Database type: redis

I just install it with docker, and now it require this lingk: `https://bootswatch.com/united/bootstrap.min.css`
![image](https://user-images.githubusercontent.com/12682063/35159028-ef1bbcc4-fd73-11e7-886c-1ce46436c758.png)
The link was not found and caused the installing failed, for no style and the button always disabled.
![image](https://user-images.githubusercontent.com/12682063/35159056-084a46a2-fd74-11e7-93be-02dfc1a8ab04.png)

I found this link maybe move to here: `https://bootswatch.com/4/united/bootstrap.min.css`, with just a version code `/4`.

**Comment by julianlam** [comment]
Latest uses https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/united/bootstrap.min.css, and has been for awhile. Where did you install it on Docker Hub?

**Comment by julianlam** [comment]
FYI the official Docker image is here: https://hub.docker.com/r/nodebb/docker/ 👍

**Comment by zhengxiaoyao0716** [comment]
@julianlam thanks, but I need a smaller size image with `alphine linux`, for my service has not enough storage space.
![image](https://user-images.githubusercontent.com/12682063/35178833-bf5a61ec-fdc9-11e7-8d09-ddc31b0c8514.png)
![image](https://user-images.githubusercontent.com/12682063/35178835-ca506d12-fdc9-11e7-8df3-bf2591e4aff7.png)
