### ISSUE TITLE
Detect when NodeBB process is managed with forever

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#6261]
Currently when the forum is started with forever the plugins installation can became a problem. The restart feature seem broken and the forum don't apply the changes.

Each time i had to connect on the servers through ssh to manually rebuild the forum and restart the forever process.

- **NodeBB version:** Any
- **NodeBB git hash:** Any

- **Database type:** Any
- **Database version:** Any

- **Exact steps to cause this issue:**
1. Install NodeBB (any version)
2. Start NodeBB with `$ forever start app.js`
3. Install a plugin
4. Restart the forum from ACP
- **What you expected:**
1. Start build
2. Use SIGKILL when the build is finished, so forever can restart the process
- **What happened instead:**
Nothing, the plugin is correctly installed trhough NPM but it's not applyed to the forum.

Thank you!

**Comment by julianlam** [comment]
If you use `app.js`, there is no connection to the loader.js and forum restarts will not work. 

I realise this is what we recommend in the docs, but it should not be the case, so I will be removing it now.

**Comment by antoine-pous** [comment]
What should i use? There is a good way to use nodebb with forever?

**Comment by julianlam** [comment]
https://docs.nodebb.org/configuring/running/#forever-daemon

Built-in executable is best: `./nodebb start` `./nodebb stop`
