### ISSUE TITLE
Rework categories as links

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#6262]
- **NodeBB version:** master
- **NodeBB git hash:** 2b95dfde915bb50a5ebb4566344694ff9d7af4db
- **Exact steps to cause this issue:**

	1. Set a sub-category as a link to an internal page made with custom-pages.
	2. Click link from categories page or parent category page.

- **What you expected:**

Link should go to the internal page in the same window.

- **What happened instead:**

From the category page: link opens in a new window.
From the categories page: link opens in the same window.

Behaviour needs to be consistent, and acp needs a toggle to set the link as internal or external.

**Comment by julianlam** [comment]
> acp needs a toggle to set the link as internal or external.

This can be detected, no?

**Comment by julianlam** [comment]
I can't reproduce this issue...

I created two subcategories,

* "Internal Link", pointing to `/tags`, and
* "External Link", pointing to `http://example.org`

On both `/` and `/categories`, clicking the former ajaxified to the tags page, and clicking the latter opened example.org in a new window.

**Comment by julianlam** [comment]
Loaded up custom-pages, created new page `/about`, set it as the link for the subcategory, still no reproduction

**Comment by yariplus** [comment]
Sure thing.

The external link is set to
`https://www.yaricraft.com/rules`

If you go to `https://www.yaricraft.com/categories` and click the `Server Rules` category, it opens in the same tab.

If you go to `https://www.yaricraft.com/category/3/slimefun-server` and click the `Server Rules` category, it opens in a new tab.

**Comment by yariplus** [comment]
> >    acp needs a toggle to set the link as internal or external.
>
> This can be detected, no?

It can be yes. Internal or external is the wrong wording, the toggle should be for `open in a new window`, just like in the options for navigation items.

**Comment by julianlam** [comment]
@yariplus Thanks, I've successfully reproduced now. Turns out I was clicking on the wrong link 😄
