### ISSUE TITLE
Add a button to recalculate all reputations

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#6263]
Hi!

Sometime we made changes to reputation, this allow us to manage it with more rightness. But we haven't the capability to recalculate the reputation, so some users lost the advantage of the new politic.

Can you add this kind of feature into the rewards page on the ACP?

Thank you!

**Comment by julianlam** [comment]
Can you tell me more about how your reputations have changed? We don't require the need to recalculate reputation as it is supposed to be calculated properly all the time.

If it goes out of sync, the best way to deal with it would be a one-time script to fix the error or re-calculate based on post reputation.

**Comment by aStonedPenguin** [comment]
Sometimes plugins and users mess with stuff they shouldn't. Other forum software like IPB give you the ability to recalculate just about everything from the ACP.

This would be a good feature to have.
