### ISSUE TITLE
ACP Redirect Loop After Successful SSO Login

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#6264]
After updating to the latest master branch, I am unable to get into the ACP. After successfully logging in with SSO, it keeps redirecting to the `/login` endpoint. Basically, this is what happens:

1. Signed In With SSO
2. Redirects to `/auth/auth0/callback` with token
3. Redirects to `/login`
4. Repeat steps 2-3 over and over.

I have confirmed that my SSO plugin is doing what is is supposed to do and it is successfully calling the `done()` callback with the UID. I know there was an older issue that caused a redirect loop due to missing the `onSuccessfulLogin()` callback. I fixed that problem and it has been working fine for over a year so this is a different issue. There is no output while this redirect loop is happening when running `./nodebb dev`.

- **NodeBB version:** 1.7.3 
- **NodeBB git hash:** ae6a1b975dbced42f78f766cbf617146d8a49320
- **Database type:** redis
- **Database version:** 3.2.8

**Comment by lots0logs** [comment]
Of course I debugged this for hours before opening this issue and then solve the problem 30 minutes later. Not even sure what made it start working :grimacing:

**Comment by barisusakli** [comment]
Which SSO plugin are you using? This could be related to the crash you are seeing in the middleware/user.js file.

**Comment by lots0logs** [comment]
@barisusakli I'm using `nodebb-plugin-sso-auth0` (It's a plugin I created). I'm no longer seeing that error I mentioned so I think you are right as I made a change to the sso plugin after reporting the error. Thanks for following up!! :smiley:

**Comment by barisusakli** [comment]
Yup that would do it, if the sso plugin wasn't calling onSuccessfulLogin `req.session.meta` isn't created and that would cause that crash. Good to hear it is resolved 👍

**Comment by vctfernandes** [comment]
I'm having the same issue after I upgraded to 1.7.5... any tips on how this can be solved? I'm having a hard time debugging it.

**Comment by julianlam** [comment]
Only via SSO? What version did you upgrade from?

**Comment by vctfernandes** [comment]
Yes, only SSO. I upgraded from 1.6.1.

**Comment by julianlam** [comment]
Possibly clear cookies... Make sure X-Forwarded-Proto is set if using nginx, and check url value in config.json

**Comment by julianlam** [comment]
Which SSO plugin? I'm not aware of any SSO issues so far...

**Comment by vctfernandes** [comment]
I'm using nodebb-plugin-sso-oauth.
Not cookies (tested no anonymous window)
Nginx is Ok
Url value also ok, as it's untouched from before upgrade

**Comment by vctfernandes** [comment]
The curious part is that SSO login works perfectly... It's just trying to open the ACP that causes the issue.

**Comment by vctfernandes** [comment]
More information: it only happens with one of my admins... The other accounts work fine.

**Comment by barisusakli** [comment]
@vctfernandes can you compare the the admin user's `password` field in the database?

**Comment by vctfernandes** [comment]
Bad user had password field. I deleted it and was able to enter ACP. However, it stopped working again 😢

**Comment by barisusakli** [comment]
It still happens when the user doesn't have a password field? What about if you logout and login again? Make sure https://github.com/julianlam/nodebb-plugin-sso-oauth is the latest version as well. The plugin should call `onSuccessfulLogin` to set the login time.

If all else fails you can disable the reauth requirement in the acp at /admin/settings/user#account-protection, set `Admin relogin duration` to 0

**Comment by vctfernandes** [comment]
It happened once with user not having a password field. Not being able to reproduce it again.
I'm using the SSO plugin latest version.
Actually, things might be making more sense now:
I have `Admin relogin duration` set to 60, so when I logged in as another admin, I didn't require reauth, probably that's why it worked with that account and didn't with my usual account. So it's probably not user specific. Makes any sense?

**Comment by zerefel** [comment]
Experiencing the same issue and I can confirm the steps to reproduce as suggested by @vctfernandes. 
1) SSO Login
2) Set password if it doesn't exist 
3) Try to access ACP -> can't access, get redirected to /login
4) Remove password from DB
5) Logout then Login again using SSO
6) Can access ACP
