### ISSUE TITLE
Categories breadcrumb

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#6269]
Breadcrumbs should have a `categories` breadcrumb for situations where `Home` is not the categories page.

**Comment by julianlam** [comment]
👍👍

**Comment by yariplus** [comment]
I would say it should just check the Homepage setting and add the breadcrumb if something other then categories is selected.

**Comment by barisusakli** [comment]
Hmm so I changed the homepage to /recent and went to /categories, and it does show the breadcrumb, maybe I am missing something. 
![image](https://user-images.githubusercontent.com/2583394/35188976-39fe1cb4-fe0f-11e7-92a6-676f64744041.png)

**Comment by yariplus** [comment]
@barisusakli It's when you go to any page other then `categories`

https://community.nodebb.org/topic/11796/testing

For example, this page should have breadcrumbs:
`Home / Categories / Testing Ground / Testing`

**Comment by yariplus** [comment]
Actually, this wouldn't apply to `/recent` `/popular` etc..

Only the category and topic pages I think.

**Comment by julianlam** [comment]
Yeah, basically where the traditional schema is

`Home > Category > Topic`

If `/` is set to something other than `/categories`, then the schema should read

`Home > Categories > Category > Topic`

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/blob/master/src/controllers/helpers.js#L132-L137

Well, this is awkward 😛

**Comment by barisusakli** [comment]
relevant issue https://github.com/NodeBB/NodeBB/issues/4555

**Comment by julianlam** [comment]
👍 Yeah thought it sounded familiar. It looks like this code might've become obsolete when custom home page got refactored slightly.

**Comment by julianlam** [comment]
Not sure why the existing logic only invoked when homePageRoute was set to a custom value, but now it should always work if it's not `categories`
