### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by jimmyc2018** [NodeBB/NodeBB#6270]
I'm trying to follow this tutorial: [https://www.installing.in/how-to-install-nodebb-on-ubuntu-14-04/](https://www.installing.in/how-to-install-nodebb-on-ubuntu-14-04/)
I'm stuck close to the end of the tutorial at:
`npm install --production`

Here's what's happening:
```
root@homebase:/var/www/nodebb# ^C
root@homebase:/var/www/nodebb# npm install --production
root@homebase:/var/www/nodebb# npm start
npm ERR! Linux 4.13.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/nodebb/npm-debug.log
root@homebase:/var/www/nodebb# ^C
root@homebase:/var/www/nodebb#
```
I'm using DigitalOcean's Droplet service.
Ubuntu 17.10 x64
MEMORY 1 GB
vCPUs 1vCPU
SSD DISK 25 GB
TRANSFER 1 TB

**Comment by pitaj** [comment]
Try following the install guide here: https://docs.nodebb.org/installing/os/ubuntu/
