### ISSUE TITLE
NodeBB Installation Tutorial Question

### ISSUE THREAD

**Issue by jimmyc2018** [NodeBB/NodeBB#6271]
I'm following the official tutorial: [https://docs.nodebb.org/installing/os/ubuntu/](https://docs.nodebb.org/installing/os/ubuntu/)

I'm stuck at: **_"Enable database authorization in the MongoDB configuration file /etc/mongod.conf by uncommenting the line security and enabling authorization:"_**

I COPIED THIS PERFECTLY:
```
security:
  authorization: enabled
```
I hit ENTER, and get this:

```
root@bank:~# security:
security:: command not found
root@bank:~#   authorization: enabled
authorization:: command not found
root@bank:~# security:
security:: command not found
root@bank:~# security:
security:: command not found
root@bank:~#   authorization: enabled
```
I tried it several times.

 **What am I doing wrong?**

**Comment by pitaj** [comment]
No, you have to edit the file `/etc/mongod.conf`. Please take these types of questions to the community forum: https://community.nodebb.org
