### ISSUE TITLE
RSS :: HTML Shouldn't Be Included In Post Titles

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#6272]
Currently, the RSS feed retains HTML in post titles. Most (if not all) feed readers these days do not support HTML in the title and will display it as code. This issue appeared after updating from 1.5.x to 1.7.x.

- **NodeBB version:** 1.7.3
- **NodeBB git hash:** da981c8d74a568fc8a08b948a3652c71eac648a2
- **Exact steps to cause this issue:**
  1. Activate the Questions & Answers plugin.
  2. Ask A Question.
  3. Check the RSS feed.
- **Additional Information:**
  * ![2018-01-21_07-44-24-pm](https://user-images.githubusercontent.com/4675662/35201794-d87f83a8-fee3-11e7-88e6-483b0ab77129.png)
  * ![2018-01-21_07-46-44-pm](https://user-images.githubusercontent.com/4675662/35201797-dda96876-fee3-11e7-80c4-9400ed81b448.png)

**Comment by pitaj** [comment]
Can you give an example of the HTML code showing up in the RSS reader vs how it shows up on the forum?

**Comment by lots0logs** [comment]
I updated the issue description. Cheers!

**Comment by alihasana** [comment]
Dear team,

Me too have same problem

![image](https://user-images.githubusercontent.com/32835040/35525239-35d735a0-0524-11e8-822a-0111e3fd1ac0.png)

**Comment by lots0logs** [comment]
Hmm..yours appears to be related to the post content. Most feed readers actually do properly support HTML in the item content. Not sure what could be causing your issue :thinking:

**Comment by alihasana** [comment]
I hope this is the problem of theme Persona

**Comment by lots0logs** [comment]
@barisusakli It doesn't look like your fix covers the recent feed (maybe others as well but I'm only using the recent feed personally)

**Comment by barisusakli** [comment]
They all use the same function https://github.com/NodeBB/NodeBB/blob/master/src/routes/feeds.js#L289, so /recent.rss is escaped as well. Which tags are still displaying? Right now it only strips these https://github.com/NodeBB/NodeBB/blob/master/public/src/utils.js#L523-L531

**Comment by lots0logs** [comment]
Ah, I see. Its just the `<i>` tag (you can see it in my original description). The `<span>` tag is now being stripped I just realized when I looked again at my original description of the issue.

**Comment by barisusakli** [comment]
Everything should be stripped now on feeds.
