### ISSUE TITLE
./nodebb start command stuck at “Populating database with default configs, if not already set...”，and didn't bind address at all(but data already found on redis database)

### ISSUE THREAD

**Issue by cnritng** [NodeBB/NodeBB#6273]
NodeBB version:1.7.3
NodeBB git hash:e16bec61d5aafc3cb7ad814d540e41a4f4e8b821
Database type:redis
Database version:Redis server v=3.2.10 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=c8b45a0ec7dc67c6

Exact steps to cause this issue:step by step from the official installation guide on centos

What you expected:
nodebb should bind on ip:port after start

**Comment by julianlam** [comment]
Can you paste the full startup log please?

**Comment by cnritng** [comment]
@julianlam  here is the start log:
Hit Ctrl-C to exit


[cluster] Child Process (20334) has exited (code: 0, signal: null)

NodeBB v1.7.3 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

2018-01-22T22:14:09.739Z [6371] - info: Initializing NodeBB v1.7.3 http://ip:port

**Comment by barisusakli** [comment]
That's not the entire log, you can post for help on https://community.nodebb.org/category/16/technical-support
