### ISSUE TITLE
Post Notifications should include topic title in title

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#6278]
Hi, I just noticed this a couple days ago, when I got a lot of post notifications of my forum:
I'm using GMail, and gmail groups mails by the subject of the mail.
For example github mails have more or less this scheme: `[repoOwner/repoName] IssueName (#IssueNumber)`.
This makes all mails regarding this issue appear next to each other, while NodeBB notification mails have all the exact same title and are therefore completely mixed and it's hard to keep track of the context if 3 or more topics had replies at more or less the same time.

**Comment by julianlam** [comment]
@RoiEXLab Makes sense, putting the topic title would be helpful 👍

**Comment by barisusakli** [comment]
What git hash? This might be already fixed. https://github.com/NodeBB/NodeBB/commit/d2ffdbda7ddee4e8313dc49c4027420b6b8e44ed

**Comment by RoiEXLab** [comment]
@barisusakli version 1.7.3 from the 1.7.x branch,
haven't had the time to update to 1.7.4 yet ^^

**Comment by RoiEXLab** [comment]
@barisusakli Will update and see if it's included now, seems like it from your diff.
Will reopen if it's not working out like I want it to ^^
