### ISSUE TITLE
Private messages shouldn't give you a notification via notifications

### ISSUE THREAD

**Issue by aStonedPenguin** [NodeBB/NodeBB#6279]
It's redundant to give a second notification when the chats system itself already notifies you.

**Comment by pitaj** [comment]
I believe this is done in order to have email notifications for chat messages.

**Comment by barisusakli** [comment]
Can configure it on user settings page, but yeah the notification is created so it can be sent as email.
![image](https://user-images.githubusercontent.com/2583394/35409942-ba9158f2-01e1-11e8-9f47-ca85e50fd5e3.png)
