### ISSUE TITLE
User setting permissions in the plate is invalid

### ISSUE THREAD

**Issue by liu868588** [NodeBB/NodeBB#6280]
NodeBB version : v1.7.x
Database : mongodb
I want setting user privileges in the categories.   eg:create topics,reply to topics...

**Comment by petyunchik** [comment]
I can confirm that.
After updating to v1.7.4 privileges tab disappeared

**Comment by liu868588** [comment]
Now , what's setting user privileges in the categories? In 1.7.4

**Comment by barisusakli** [comment]
Go to manage>privileges

**Comment by liu868588** [comment]
![oj46 19970sn oddl6 3h](https://user-images.githubusercontent.com/10568931/35420776-523d4c2c-027a-11e8-9878-14549c1737cc.png)
![v7hebujwpc 4 i tmp4 e1](https://user-images.githubusercontent.com/10568931/35420781-5b2b96c2-027a-11e8-86fc-e807fb880907.png)

**Comment by julianlam** [comment]
Permissions are additive. Because the registered users group has the topic creation privilege, liuzy does too. This is expected behaviour

**Comment by liu868588** [comment]
thanks,But i want setting liuzy is not create topics in the Blogs

**Comment by julianlam** [comment]
This is not possible with the existing privileges system. You will need to remove the topic creation privilege for all registered users, and add those users you wish to post.

**Comment by liu868588** [comment]
If so,All newly registered users is not create topics in the Blogs
