### ISSUE TITLE
Cannot see deleted topic while I am administrator

### ISSUE THREAD

**Issue by jimmykane** [NodeBB/NodeBB#6282]
Hi there, 

NodeBB 1.7.3 

On a deleted (merged) topic I cannot see the content but only a message

`This topic has been deleted. Only users with topic management privileges can see it.`

**Comment by barisusakli** [comment]
That's because all the posts have been moved to the topic you merged into, I will just purge the topic so this doesnt confuse anyone, see also https://github.com/NodeBB/NodeBB/issues/6248

**Comment by jimmykane** [comment]
Great. No issues here was a bit confusing. However it would be nice to have
the backtrack link of where it's merged.
