### ISSUE TITLE
Copyright, Trademark and Registered symbols are too big

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6285]
- **NodeBB version:** v1.7.3
- **NodeBB git hash:** 0020b8a18b7ad9345162a5843817458724dafc14

- **Database type:** mongo
- **Database version:** v3.4.9

- **Exact steps to cause this issue:** Posted a post with Copyright©, Registered® or Trade Mark™ symbol.   

- **What you expected:** Expected it to show up in superscript in a slightly smaller font.  

- **What happened instead:**

Instead it turns into big bold emojis like this:
![image](https://user-images.githubusercontent.com/24903887/35467920-ed714190-02e2-11e8-904f-5cffc459edab.png)

**Comment by pitaj** [comment]
Disable "Replace common ASCII characters like <code>:)</code>, <code>-_-</code>, etc" in the Emoji plugin settings page.

**Comment by dangerusslee** [comment]
@pitaj that didn't seem to help

**Comment by pitaj** [comment]
I edited my comment to correct myself, so make sure you did what it says now. Also, you'll need to restart NodeBB for the change to be put into effect.

**Comment by dangerusslee** [comment]
@pitaj thank you the updated comment worked
