### ISSUE TITLE
Using NodeBB in collaboration with Tor

### ISSUE THREAD

**Issue by stevefan1999** [NodeBB/NodeBB#6286]
Hello, I was looking to use NodeBB for a simple hidden Tor service, everything runs smoothly but it comes with a problem in `config.json`. The `url` field in `config.json` is not recognizing my Tor service. Also I don't have a single-point URL since it runs in both "clearnet" and "darknet" simultaneously. What should I put in the field in order to have a transparent URL? (e.g. use the root domain address as the URL)

**Comment by pitaj** [comment]
That's a tough one. I'm not super knowledgeable with TOR, but I thought it supported accessing non-hidden services. I thought the purpose of a hidden service was so people don't know where the service is located. If your site is available via cleanspace, what is the point of the hidden service?

**Comment by julianlam** [comment]
I'm assuming the issue is that web sockets won't work because the url is set to the clearnet url. 

You'll need to specify "socket.io:origins" in config.json

**Comment by stevefan1999** [comment]
@julianlam Nope. SIO is working (albeit not well and have to resort to XHR polling AFAIK). However assests required using a fixed `url` specified in `config.json`
This problem is shown in the emoji plugin.

**Comment by stevefan1999** [comment]
I fixed it by disabling security origin in "socket.io:origins", I missed one '*', I thought it was **":\*"** but actually it is **"\*:\*"**

In theory, by disbling <meta og> tags should give my site a full protection against address leaking. Haven't try it in hidden service mode yet, but I'm pretty sure NodeBB will run under that full 100% with Nginx as a reverse proxy.

Closing it as resolved.

**Comment by pitaj** [comment]
Just FYI, doing that results in your users being open to cross-domain websocket attacks, which is why there's a restriction in the first place. Also, parts of NodeBB or plugins which use the URL parameter will fail.

I still don't understand why you want to run it as both a hidden service and as a normal site.
