### ISSUE TITLE
Google Search Result enhancements

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#6292]
I just came across a guide by google on how to add additional Metadata and format the markup to result in nicer Google Search results. [The Full List can be found here.](https://developers.google.com/search/docs/guides/search-gallery)
I want to point out that Items that seem useful for every forum website to me:
 - [Breadcrumb](https://developers.google.com/search/docs/data-types/breadcrumb), it just looks nicer in the search results
 - [Logo](https://developers.google.com/search/docs/data-types/logo). Who doesn't want an info card with the appropriate logo when the search result is being displayed?
 - [Sitelinks Searchbox](https://developers.google.com/search/docs/data-types/sitelinks-searchbox), NodeBB already has a search function, why shouldn't it made available from the search results?

I'm sure many NodeBB users would appreciate this, and all of those features should be fairly easy to implement, given that NodeBB already has all the information hidden in the Markup.

**Comment by aStonedPenguin** [comment]
My sites google raking as taken a significant dive since switching from to NodeBB from IPB despite increased traffic. Some improvements on that front would be nice.

**Comment by FaizanZahid** [comment]
totally agree with this points.

**Comment by barisusakli** [comment]
breadcrumbs are added
https://github.com/NodeBB/nodebb-theme-harmony/blob/main/templates/partials/breadcrumbs-json-ld.tpl

for logo and searchbox, you can use the ACP and add the required markup into the <head>, see below.

![image](https://github.com/NodeBB/NodeBB/assets/2583394/49413496-8f29-4e42-a888-1b7ab98be19b)
