### ISSUE TITLE
broken link in CLA :microscope: 

### ISSUE THREAD

**Issue by MegaGM** [NodeBB/NodeBB#6293]
:microscope:  https://cla-assistant.io/NodeBB/NodeBB :microscope:

**Comment by julianlam** [comment]
Seems to work here?

**Comment by MegaGM** [comment]
The link is in CLA itself.
Right before the header
> 2. Grant of Rights

**Comment by julianlam** [comment]
Thanks, the proper url is at https://github.com/NodeBB/NodeBB/blob/master/.github/CONTRIBUTING.md

**Comment by julianlam** [comment]
@psychobunny fixed it now 😄
