### ISSUE TITLE
No image uploads after upgrade to v1.7.4

### ISSUE THREAD

**Issue by victorelec14** [NodeBB/NodeBB#6294]
![nodebb no uploads](https://user-images.githubusercontent.com/543450/35626117-04615b5a-0695-11e8-806e-f5848a8de158.png)

- **NodeBB version:** v1.7.4
- **NodeBB git hash:** --

- **Database type:** redis
- **Database version:** 3.2.10

- **Exact steps to cause this issue:** Upgrade from v1.7.3 to v.1.7.4

- **What you expected:**
 yesterday i upgrade nodebb from v.1.7.3 to v1.7.4 ( from merge), now cannt upload iamges and a icon ust not set in Bar ( empty "li" tag )
- **What happened instead:** all users cann`t upload images

```
<li tabindex="-1">
	<i class="fa fa-th-large topic-thumb-btn topic-thumb-toggle-btn hide" title="Agregar miniatura a este tema"></i>
</li>
```

**Comment by barisusakli** [comment]
Can you check `/admin/manage/privileges` and make sure registered users have upload image privilege?

**Comment by victorelec14** [comment]
hi, i have this now:

![dddd22](https://user-images.githubusercontent.com/543450/35627703-00420ee8-069a-11e8-959b-cf61b9f97eaf.png)

**Comment by barisusakli** [comment]
Seems to work fine for me I get the icon when I enable topic thumbs.

![image](https://user-images.githubusercontent.com/2583394/35632630-2883a602-0675-11e8-865c-55a899243bda.png)

What theme and composer are you using?

**Comment by victorelec14** [comment]
The last version of composer (default ) and persona theme.

The problem ist with upload files, and when i deactive thumbs them i see empty li tag (no icon set)

i cann give you Admin permissions in my nodebb.

> nodebb-plugin-composer-default
> Default composer for NodeBB
> Instalados 6.0.8 | Ultimos 6.0.8


> nodebb-theme-persona
> Persona theme for NodeBB
> Instalados 7.2.16 | Ultimos 7.2.16

**Comment by barisusakli** [comment]
No need I was able to reproduce it.

**Comment by victorelec14** [comment]
hi, i have upgraded to the new version v1.7.5 but the bug persist :S

**Comment by barisusakli** [comment]
What is your composer version now?

**Comment by victorelec14** [comment]
is the same version and upgrade have not upgraded.


nodebb-plugin-composer-default
Default composer for NodeBB

Instalados 6.0.8 | Ultimos 6.0.8

--------------
 ./nodebb upgrade

Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...  started
- fuse.js@3.2.0 node_modules/fuse.js
nodebb@1.7.5 /home/aaaaaa/nodebb
└── nodebb-plugin-emoji@2.1.3


3. Checking installed plugins for updates...  OK
4. Updating NodeBB data store schema...
Parsing upgrade scripts...
OK | 0 script(s) found, 46 skipped
Schema update complete!


5. Rebuilding assets...  started
2018-02-12T21:34:03.946Z [23672] - info: [build] Building in parallel mode
2018-02-12T21:34:03.951Z [23672] - info: [build]         plugin static dirs  bui                                                         ld started
2018-02-12T21:34:03.957Z [23672] - info: [build]          requirejs modules  bui                                                         ld started
2018-02-12T21:34:03.959Z [23672] - info: [build]           client js bundle  bui                                                         ld started
2018-02-12T21:34:03.962Z [23672] - info: [build]            admin js bundle  bui                                                         ld started
2018-02-12T21:34:03.963Z [23672] - info: [build]         client side styles  bui                                                         ld started
2018-02-12T21:34:03.965Z [23672] - info: [build] admin control panel styles  bui                                                         ld started
2018-02-12T21:34:03.967Z [23672] - info: [build]                  templates  bui                                                         ld started
2018-02-12T21:34:03.968Z [23672] - info: [build]                  languages  bui                                                         ld started
2018-02-12T21:34:03.969Z [23672] - info: [build]                     sounds  bui                                                         ld started
2018-02-12T21:34:05.083Z [23672] - info: [build]                     sounds  bui                                                         ld completed in 1.109sec
2018-02-12T21:34:06.054Z [23672] - info: [build]         plugin static dirs  bui                                                         ld completed in 2.103sec
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
2018-02-12T21:34:10.802Z [23672] - info: [build]           client js bundle  build completed in 6.843sec
2018-02-12T21:34:11.108Z [23672] - info: [build]            admin js bundle  build completed in 7.146sec
2018-02-12T21:34:14.122Z [23672] - info: [build] admin control panel styles  build completed in 10.157sec
2018-02-12T21:34:14.150Z [23672] - info: [build]         client side styles  build completed in 10.187sec
2018-02-12T21:34:14.160Z [23672] - info: [build]                  languages  build completed in 10.192sec
2018-02-12T21:34:14.174Z [23672] - info: [build]                  templates  build completed in 10.207sec
2018-02-12T21:34:20.312Z [23672] - info: [build]          requirejs modules  build completed in 16.355sec
2018-02-12T21:34:20.317Z [23672] - info: [build] Asset compilation successful. Completed in 16.362sec.


                                                        NodeBB Upgrade Complete!

**Comment by barisusakli** [comment]
It should be 6.0.13, what is the version in install/package.json and package.json for nodebb-plugin-composer-default?

**Comment by victorelec14** [comment]
Package.json

`{
  "name": "nodebb",
  "license": "GPL-3.0",
  "description": "NodeBB Forum",
  "version": "1.7.5",
  "homepage": "http://www.nodebb.org",
  "repository": {
    "type": "git",
    "url": "https://github.com/NodeBB/NodeBB/"
  },
  "main": "app.js",
  "scripts": {
    "start": "node loader.js",
    "lint": "eslint --cache ./nodebb .",
    "pretest": "npm run lint",
    "test": "nyc --reporter=html --reporter=text-summary mocha",
    "coveralls": "nyc report --reporter=text-lcov | coveralls && rm -r coverage"
  },
  "dependencies": {
    "ace-builds": "^1.2.9",
    "async": "2.6.0",
    "autoprefixer": "7.2.4",
    "bcryptjs": "2.4.3",
    "benchpressjs": "^1.2.0",
    "body-parser": "^1.18.2",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.7.1",
    "colors": "^1.1.2",
    "commander": "^2.12.2",
    "compression": "^1.7.1",
    "connect-ensure-login": "^0.1.1",
    "connect-flash": "^0.1.1",
    "connect-mongo": "2.0.1",
    "connect-multiparty": "^2.1.0",
    "connect-redis": "3.3.3",
    "cookie-parser": "^1.4.3",
    "cron": "^1.3.0",
    "cropperjs": "^1.2.2",
    "csurf": "^1.9.0",
    "daemon": "^1.1.0",
    "express": "^4.16.2",
    "express-session": "^1.15.6",
    "express-useragent": "1.0.8",
    "graceful-fs": "^4.1.11",
    "html-to-text": "3.3.0",
    "ipaddr.js": "^1.5.4",
    "jimp": "0.2.28",
    "jquery": "^3.2.1",
    "jsesc": "2.5.1",
    "json-2-csv": "^2.1.2",
    "less": "^2.7.3",
    "lodash": "^4.17.4",
    "logrotate-stream": "^0.2.5",
    "lru-cache": "4.1.1",
    "material-design-lite": "^1.3.0",
    "mime": "^2.2.0",
    "mkdirp": "^0.5.1",
    "mongodb": "2.2.33",
    "morgan": "^1.9.0",
    "mousetrap": "^1.6.1",
    "nconf": "^0.9.1",
    "nodebb-plugin-adsense": "1.0.0",
    "nodebb-plugin-align-center": "^0.1.3",
    "nodebb-plugin-chats-global": "1.0.0",
    "nodebb-plugin-composer-default": "6.0.8",
    "nodebb-plugin-composer-embedly": "0.0.7",
    "nodebb-plugin-dbsearch": "2.0.9",
    "nodebb-plugin-embed-combo": "0.1.11",
    "nodebb-plugin-emoji": "^2.1.0",
    "nodebb-plugin-emoji-android": "2.0.0",
    "nodebb-plugin-emoji-extended": "1.1.1",
    "nodebb-plugin-emoji-one": "^2.0.0",
    "nodebb-plugin-google-analytics": "0.5.9",
    "nodebb-plugin-iframely": "^0.7.8",
    "nodebb-plugin-image-size": "^0.1.2",
    "nodebb-plugin-imgbed": "^1.0.2",
    "nodebb-plugin-imgshow": "0.0.14",
    "nodebb-plugin-markdown": "8.2.2",
    "nodebb-plugin-mega-colors": "0.10.24",
    "nodebb-plugin-mentions": "2.2.2",
    "nodebb-plugin-ns-embed": "2.1.1",
    "nodebb-plugin-recent-cards": "^0.5.0",
    "nodebb-plugin-seo-slug-friendly": "0.0.8",
    "nodebb-plugin-soundpack-default": "1.0.0",
    "nodebb-plugin-spam-be-gone": "0.5.1",
    "nodebb-plugin-youtube-embed": "0.6.6",
    "nodebb-rewards-essentials": "0.0.11",
    "nodebb-theme-lavender": "5.0.1",
    "nodebb-theme-persona": "7.2.16",
    "nodebb-theme-slick": "1.1.4",
    "nodebb-theme-vanilla": "8.1.7",
    "nodebb-widget-essentials": "4.0.1",
    "nodebb-widget-ns-stats": "^1.0.3",
    "nodebb-widget-recent-news": "0.0.9",
    "nodemailer": "4.4.1",
    "passport": "^0.4.0",
    "passport-local": "1.0.0",
    "postcss": "6.0.15",
    "postcss-clean": "1.1.0",
    "promise-polyfill": "^7.0.0",
    "prompt": "^1.0.0",
    "redis": "2.8.0",
    "request": "2.83.0",
    "rimraf": "2.6.2",
    "rss": "^1.2.2",
    "sanitize-html": "^1.16.3",
    "semver": "^5.4.1",
    "serve-favicon": "^2.4.5",
    "sitemap": "^1.13.0",
    "socket.io": "2.0.4",
    "socket.io-client": "2.0.4",
    "socket.io-redis": "5.2.0",
    "socketio-wildcard": "2.0.0",
    "spdx-license-list": "^3.0.1",
    "toobusy-js": "^0.5.1",
    "uglify-js": "^3.3.4",
    "validator": "9.2.0",
    "winston": "^2.4.0",
    "xml": "^1.0.1",
    "xregexp": "3.2.0",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "coveralls": "^3.0.0",
    "eslint": "^4.14.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "grunt": "^1.0.1",
    "grunt-contrib-watch": "^1.0.0",
    "jsdom": "^11.5.1",
    "mocha": "^4.1.0",
    "mocha-lcov-reporter": "^1.3.0",
    "nyc": "^11.4.1",
    "smtp-server": "^3.4.1"
  },
  "bugs": {
    "url": "https://github.com/NodeBB/NodeBB/issues"
  },
  "engines": {
    "node": ">=6"
  },
  "maintainers": [
    {
      "name": "Andrew Rodrigues",
      "email": "andrew@nodebb.org",
      "url": "https://github.com/psychobunny"
    },
    {
      "name": "Julian Lam",
      "email": "julian@nodebb.org",
      "url": "https://github.com/julianlam"
    },
    {
      "name": "Barış Soner Uşaklı",
      "email": "baris@nodebb.org",
      "url": "https://github.com/barisusakli"
    }
  ]
}{
  "name": "nodebb",
  "license": "GPL-3.0",
  "description": "NodeBB Forum",
  "version": "1.7.5",
  "homepage": "http://www.nodebb.org",
  "repository": {
    "type": "git",
    "url": "https://github.com/NodeBB/NodeBB/"
  },
  "main": "app.js",
  "scripts": {
    "start": "node loader.js",
    "lint": "eslint --cache ./nodebb .",
    "pretest": "npm run lint",
    "test": "nyc --reporter=html --reporter=text-summary mocha",
    "coveralls": "nyc report --reporter=text-lcov | coveralls && rm -r coverage"
  },
  "dependencies": {
    "ace-builds": "^1.2.9",
    "async": "2.6.0",
    "autoprefixer": "7.2.4",
    "bcryptjs": "2.4.3",
    "benchpressjs": "^1.2.0",
    "body-parser": "^1.18.2",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.7.1",
    "colors": "^1.1.2",
    "commander": "^2.12.2",
    "compression": "^1.7.1",
    "connect-ensure-login": "^0.1.1",
    "connect-flash": "^0.1.1",
    "connect-mongo": "2.0.1",
    "connect-multiparty": "^2.1.0",
    "connect-redis": "3.3.3",
    "cookie-parser": "^1.4.3",
    "cron": "^1.3.0",
    "cropperjs": "^1.2.2",
    "csurf": "^1.9.0",
    "daemon": "^1.1.0",
    "express": "^4.16.2",
    "express-session": "^1.15.6",
    "express-useragent": "1.0.8",
    "graceful-fs": "^4.1.11",
    "html-to-text": "3.3.0",
    "ipaddr.js": "^1.5.4",
    "jimp": "0.2.28",
    "jquery": "^3.2.1",
    "jsesc": "2.5.1",
    "json-2-csv": "^2.1.2",
    "less": "^2.7.3",
    "lodash": "^4.17.4",
    "logrotate-stream": "^0.2.5",
    "lru-cache": "4.1.1",
    "material-design-lite": "^1.3.0",
    "mime": "^2.2.0",
    "mkdirp": "^0.5.1",
    "mongodb": "2.2.33",
    "morgan": "^1.9.0",
    "mousetrap": "^1.6.1",
    "nconf": "^0.9.1",
    "nodebb-plugin-adsense": "1.0.0",
    "nodebb-plugin-align-center": "^0.1.3",
    "nodebb-plugin-chats-global": "1.0.0",
    "nodebb-plugin-composer-default": "6.0.8",
    "nodebb-plugin-composer-embedly": "0.0.7",
    "nodebb-plugin-dbsearch": "2.0.9",
    "nodebb-plugin-embed-combo": "0.1.11",
    "nodebb-plugin-emoji": "^2.1.0",
    "nodebb-plugin-emoji-android": "2.0.0",
    "nodebb-plugin-emoji-extended": "1.1.1",
    "nodebb-plugin-emoji-one": "^2.0.0",
    "nodebb-plugin-google-analytics": "0.5.9",
    "nodebb-plugin-iframely": "^0.7.8",
    "nodebb-plugin-image-size": "^0.1.2",
    "nodebb-plugin-imgbed": "^1.0.2",
    "nodebb-plugin-imgshow": "0.0.14",
    "nodebb-plugin-markdown": "8.2.2",
    "nodebb-plugin-mega-colors": "0.10.24",
    "nodebb-plugin-mentions": "2.2.2",
    "nodebb-plugin-ns-embed": "2.1.1",
    "nodebb-plugin-recent-cards": "^0.5.0",
    "nodebb-plugin-seo-slug-friendly": "0.0.8",
    "nodebb-plugin-soundpack-default": "1.0.0",
    "nodebb-plugin-spam-be-gone": "0.5.1",
    "nodebb-plugin-youtube-embed": "0.6.6",
    "nodebb-rewards-essentials": "0.0.11",
    "nodebb-theme-lavender": "5.0.1",
    "nodebb-theme-persona": "7.2.16",
    "nodebb-theme-slick": "1.1.4",
    "nodebb-theme-vanilla": "8.1.7",
    "nodebb-widget-essentials": "4.0.1",
    "nodebb-widget-ns-stats": "^1.0.3",
    "nodebb-widget-recent-news": "0.0.9",
    "nodemailer": "4.4.1",
    "passport": "^0.4.0",
    "passport-local": "1.0.0",
    "postcss": "6.0.15",
    "postcss-clean": "1.1.0",
    "promise-polyfill": "^7.0.0",
    "prompt": "^1.0.0",
    "redis": "2.8.0",
    "request": "2.83.0",
    "rimraf": "2.6.2",
    "rss": "^1.2.2",
    "sanitize-html": "^1.16.3",
    "semver": "^5.4.1",
    "serve-favicon": "^2.4.5",
    "sitemap": "^1.13.0",
    "socket.io": "2.0.4",
    "socket.io-client": "2.0.4",
    "socket.io-redis": "5.2.0",
    "socketio-wildcard": "2.0.0",
    "spdx-license-list": "^3.0.1",
    "toobusy-js": "^0.5.1",
    "uglify-js": "^3.3.4",
    "validator": "9.2.0",
    "winston": "^2.4.0",
    "xml": "^1.0.1",
    "xregexp": "3.2.0",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "coveralls": "^3.0.0",
    "eslint": "^4.14.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "grunt": "^1.0.1",
    "grunt-contrib-watch": "^1.0.0",
    "jsdom": "^11.5.1",
    "mocha": "^4.1.0",
    "mocha-lcov-reporter": "^1.3.0",
    "nyc": "^11.4.1",
    "smtp-server": "^3.4.1"
  },
  "bugs": {
    "url": "https://github.com/NodeBB/NodeBB/issues"
  },
  "engines": {
    "node": ">=6"
  },
  "maintainers": [
    {
      "name": "Andrew Rodrigues",
      "email": "andrew@nodebb.org",
      "url": "https://github.com/psychobunny"
    },
    {
      "name": "Julian Lam",
      "email": "julian@nodebb.org",
      "url": "https://github.com/julianlam"
    },
    {
      "name": "Barış Soner Uşaklı",
      "email": "baris@nodebb.org",
      "url": "https://github.com/barisusakli"
    }
  ]
}`


Install/package.json

`{
    "name": "nodebb",
    "license": "GPL-3.0",
    "description": "NodeBB Forum",
    "version": "1.7.5",
    "homepage": "http://www.nodebb.org",
    "repository": {
        "type": "git",
        "url": "https://github.com/NodeBB/NodeBB/"
    },
    "main": "app.js",
    "scripts": {
        "start": "node loader.js",
        "lint": "eslint --cache ./nodebb .",
        "pretest": "npm run lint",
        "test": "nyc --reporter=html --reporter=text-summary mocha",
        "coveralls": "nyc report --reporter=text-lcov | coveralls && rm -r coverage"
    },
    "dependencies": {
        "ace-builds": "^1.2.9",
        "async": "2.6.0",
        "autoprefixer": "7.2.4",
        "bcryptjs": "2.4.3",
        "benchpressjs": "^1.2.0",
        "body-parser": "^1.18.2",
        "bootstrap": "^3.3.7",
        "chart.js": "^2.7.1",
        "colors": "^1.1.2",
        "compression": "^1.7.1",
        "commander": "^2.12.2",
        "connect-ensure-login": "^0.1.1",
        "connect-flash": "^0.1.1",
        "connect-mongo": "2.0.1",
        "connect-multiparty": "^2.1.0",
        "connect-redis": "3.3.3",
        "cookie-parser": "^1.4.3",
        "cron": "^1.3.0",
        "cropperjs": "^1.2.2",
        "csurf": "^1.9.0",
        "daemon": "^1.1.0",
        "express": "^4.16.2",
        "express-session": "^1.15.6",
        "express-useragent": "1.0.8",
        "graceful-fs": "^4.1.11",
        "html-to-text": "3.3.0",
        "ipaddr.js": "^1.5.4",
        "jimp": "0.2.28",
        "jquery": "^3.2.1",
        "jsesc": "2.5.1",
        "json-2-csv": "^2.1.2",
        "less": "^2.7.3",
        "lodash": "^4.17.4",
        "logrotate-stream": "^0.2.5",
        "lru-cache": "4.1.1",
        "material-design-lite": "^1.3.0",
        "mime": "^2.2.0",
        "mkdirp": "^0.5.1",
        "mongodb": "2.2.33",
        "morgan": "^1.9.0",
        "mousetrap": "^1.6.1",
        "nconf": "^0.9.1",
        "nodebb-plugin-composer-default": "6.0.8",
        "nodebb-plugin-dbsearch": "2.0.9",
        "nodebb-plugin-emoji": "^2.1.0",
        "nodebb-plugin-emoji-android": "2.0.0",
        "nodebb-plugin-markdown": "8.2.2",
        "nodebb-plugin-mentions": "2.2.2",
        "nodebb-plugin-soundpack-default": "1.0.0",
        "nodebb-plugin-spam-be-gone": "0.5.1",
        "nodebb-rewards-essentials": "0.0.11",
        "nodebb-theme-lavender": "5.0.1",
        "nodebb-theme-persona": "7.2.16",
        "nodebb-theme-slick": "1.1.4",
        "nodebb-theme-vanilla": "8.1.7",
        "nodebb-widget-essentials": "4.0.1",
        "nodemailer": "4.4.1",
        "passport": "^0.4.0",
        "passport-local": "1.0.0",
        "postcss": "6.0.15",
        "postcss-clean": "1.1.0",
        "promise-polyfill": "^7.0.0",
        "prompt": "^1.0.0",
        "redis": "2.8.0",
        "request": "2.83.0",
        "rimraf": "2.6.2",
        "rss": "^1.2.2",
        "sanitize-html": "^1.16.3",
        "semver": "^5.4.1",
        "serve-favicon": "^2.4.5",
        "sitemap": "^1.13.0",
        "socket.io": "2.0.4",
        "socket.io-client": "2.0.4",
        "socket.io-redis": "5.2.0",
        "socketio-wildcard": "2.0.0",
        "spdx-license-list": "^3.0.1",
        "toobusy-js": "^0.5.1",
        "uglify-js": "^3.3.4",
        "validator": "9.2.0",
        "winston": "^2.4.0",
        "xml": "^1.0.1",
        "xregexp": "3.2.0",
        "zxcvbn": "^4.4.2"
    },
    "devDependencies": {
        "coveralls": "^3.0.0",
        "eslint": "^4.14.0",
        "eslint-config-airbnb-base": "^12.1.0",
        "eslint-plugin-import": "^2.8.0",
        "grunt": "^1.0.1",
        "grunt-contrib-watch": "^1.0.0",
        "jsdom": "^11.5.1",
        "mocha": "^4.1.0",
        "mocha-lcov-reporter": "^1.3.0",
        "nyc": "^11.4.1",
        "smtp-server": "^3.4.1"
    },
    "bugs": {
        "url": "https://github.com/NodeBB/NodeBB/issues"
    },
    "engines": {
        "node": ">=6"
    },
    "maintainers": [
        {
            "name": "Andrew Rodrigues",
            "email": "andrew@nodebb.org",
            "url": "https://github.com/psychobunny"
        },
        {
            "name": "Julian Lam",
            "email": "julian@nodebb.org",
            "url": "https://github.com/julianlam"
        },
        {
            "name": "Barış Soner Uşaklı",
            "email": "baris@nodebb.org",
            "url": "https://github.com/barisusakli"
        }
    ]
}
`

**Comment by victorelec14** [comment]
nodebb/node_modules/nodebb-plugin-composer-default

`{
  "_args": [
    [
      {
        "raw": "nodebb-plugin-composer-default@6.0.8",
        "scope": null,
        "escapedName": "nodebb-plugin-composer-default",
        "name": "nodebb-plugin-composer-default",
        "rawSpec": "6.0.8",
        "spec": "6.0.8",
        "type": "version"
      },
      "/home/crypto/nodebb"
    ]
  ],
  "_from": "nodebb-plugin-composer-default@6.0.8",
  "_id": "nodebb-plugin-composer-default@6.0.8",
  "_inCache": true,
  "_location": "/nodebb-plugin-composer-default",
  "_nodeVersion": "8.9.0",
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/nodebb-plugin-composer-default-6.0.8.tgz_1515003657557_0.18373738322407007"
  },
  "_npmUser": {
    "name": "baris",
    "email": "barisusakli@gmail.com"
  },
  "_npmVersion": "5.5.1",
  "_phantomChildren": {},
  "_requested": {
    "raw": "nodebb-plugin-composer-default@6.0.8",
    "scope": null,
    "escapedName": "nodebb-plugin-composer-default",
    "name": "nodebb-plugin-composer-default",
    "rawSpec": "6.0.8",
    "spec": "6.0.8",
    "type": "version"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/nodebb-plugin-composer-default/-/nodebb-plugin-composer-default-6.0.8.tgz",
  "_shasum": "c63115ddfe4b6e5c252acf55bed60d6ea0483967",
  "_shrinkwrap": null,
  "_spec": "nodebb-plugin-composer-default@6.0.8",
  "_where": "/home/crypto/nodebb",
  "author": {
    "name": "NodeBB Team",
    "email": "sales@nodebb.org"
  },
  "bugs": {
    "url": "https://github.com/NodeBB/nodebb-plugin-composer-default/issues"
  },
  "dependencies": {
    "screenfull": "3.0.0"
  },
  "description": "Default composer for NodeBB",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "integrity": "sha512-KACAuw1kYIRsAH8QmnSy+2H8zMiOpaNp87QOA4ih+zqMFmxqGvlGXldo7KEMGzIs/Q7um8oqysZRTQf8mpRtBw==",
    "shasum": "c63115ddfe4b6e5c252acf55bed60d6ea0483967",
    "tarball": "https://registry.npmjs.org/nodebb-plugin-composer-default/-/nodebb-plugin-composer-default-6.0.8.tgz"
  },
  "gitHead": "ef190359125e808573250b0ce259f86fcd85e884",
  "homepage": "https://github.com/NodeBB/nodebb-plugin-composer-default#readme",
  "keywords": [
    "nodebb",
    "plugin",
    "composer",
    "markdown"
  ],
  "license": "MIT",
  "main": "library.js",
  "maintainers": [
    {
      "name": "psychobunny",
      "email": "andrew@nodebb.org"
    },
    {
      "name": "baris",
      "email": "barisusakli@gmail.com"
    },
    {
      "name": "julianlam",
      "email": "julian@nodebb.org"
    },
    {
      "name": "pitaj",
      "email": "p.jaszkow@gmail.com"
    }
  ],
  "name": "nodebb-plugin-composer-default",
  "nbbpm": {
    "compatibility": "^1.8.0"
  },
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/NodeBB/nodebb-plugin-composer-default.git"
  },
  "version": "6.0.8"
}
`

**Comment by barisusakli** [comment]
Looks like this wasn't included in 1.7.5, you can wait for 1.8.0 or switch to master.

**Comment by victorelec14** [comment]
hi, will it be included in version 1.7.6 or 1.8.0 ? thx

**Comment by barisusakli** [comment]
It will be in 1.7.6

**Comment by victorelec14** [comment]
i have now the 1.8.0 version but i don`t see the Upload button... , i can only upload files with copy paste (automatic upload) but not select a file from PC  :S

![image](https://user-images.githubusercontent.com/543450/37559824-e54816e4-2a2c-11e8-9a27-399eeaf54a17.png)

**Comment by victorelec14** [comment]
Reopen ?

**Comment by barisusakli** [comment]
What version of composer-default? Did you give users the upload image privilege on manage > privileges?

**Comment by barisusakli** [comment]
If you are on 1.8.x branch git pull and run `./nodebb upgrade` again composer default version should be  6.0.17

**Comment by victorelec14** [comment]
@barisusakli  

nodebb-plugin-composer-default
Default composer for NodeBB
Installed: 6.0.16 | Lasted: 6.0.16


Manage > privileges:

![image](https://user-images.githubusercontent.com/543450/37661230-9a2c5e20-2c54-11e8-8199-83509a289592.png)

**Comment by victorelec14** [comment]
[root@server2 nodebb]# ./nodebb upgrade

Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...  started

3. Checking installed plugins for updates...  OK

A total of 1 package(s) can be upgraded:

  * nodebb-plugin-youtube-embed (0.6.6 -> 0.6.7)

Proceed with upgrade (y|n)? y

Upgrading packages...

4. Updating NodeBB data store schema...
Parsing upgrade scripts...
OK | 0 script(s) found, 50 skipped
Schema update complete!


5. Rebuilding assets...  started
2018-03-20T14:39:59.996Z [21778] - info: [build] Building in parallel mode
2018-03-20T14:39:59.999Z [21778] - info: [build]         plugin static dirs  build started
2018-03-20T14:40:00.003Z [21778] - info: [build]          requirejs modules  build started
2018-03-20T14:40:00.005Z [21778] - info: [build]           client js bundle  build started
2018-03-20T14:40:00.007Z [21778] - info: [build]            admin js bundle  build started
2018-03-20T14:40:00.008Z [21778] - info: [build]         client side styles  build started
2018-03-20T14:40:00.009Z [21778] - info: [build] admin control panel styles  build started
2018-03-20T14:40:00.011Z [21778] - info: [build]                  templates  build started
2018-03-20T14:40:00.012Z [21778] - info: [build]                  languages  build started
2018-03-20T14:40:00.013Z [21778] - info: [build]                     sounds  build started
2018-03-20T14:40:01.313Z [21778] - info: [build]                     sounds  build completed in 1.3sec
2018-03-20T14:40:03.850Z [21778] - info: [build]         plugin static dirs  build completed in 3.851sec
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
2018-03-20T14:40:23.671Z [21778] - info: [build]           client js bundle  build completed in 23.667sec
2018-03-20T14:40:23.672Z [21778] - info: [build]            admin js bundle  build completed in 23.664sec
2018-03-20T14:40:27.899Z [21778] - info: [build] admin control panel styles  build completed in 27.889sec
2018-03-20T14:40:28.625Z [21778] - info: [build]         client side styles  build completed in 28.617sec
2018-03-20T14:40:28.732Z [21778] - info: [build]                  languages  build completed in 28.72sec
2018-03-20T14:40:28.750Z [21778] - info: [build]                  templates  build completed in 28.739sec
2018-03-20T14:40:31.653Z [21778] - info: [build]          requirejs modules  build completed in 31.65sec
2018-03-20T14:40:31.678Z [21778] - info: [build] Asset compilation successful. Completed in 31.656sec.


                                                   NodeBB Upgrade Complete!

[root@server2 nodebb]#

**Comment by victorelec14** [comment]
i found the problem ...

/admin/plugins/composer-default

when "Use a separate route for the composer" is active then Uploads don't run and icon is not in place.

**Comment by barisusakli** [comment]
composer-default should be 6.0.17.

Run git pull then ./nodebb upgrade and try again.

**Comment by victorelec14** [comment]
now is OK, thx !!
