### ISSUE TITLE
Error after upgrading NodeBB

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6305]
- **NodeBB version:** 1.7.4
- **NodeBB git hash:** adc705439079175306fb3a1d81819e75840d88f1
- **Database type:** mongo
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**
After running ``./nodebb upgrade``command, we get error:
```
2018-02-04T20:52:02.389Z [7571] - info: [build]         plugin static dirs  build completed in 0.851sec
Witout from option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to undefined to prevent this warning
Witout from option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to undefined to prevent this warning
2018-02-04T20:52:07.588Z [7571] - info: [build]           client js bundle  build completed in 6.042sec
```

**Also we have another strange problem:
After upgrading, we get 503 error repetitively.**

**Comment by julianlam** [comment]
That's not an error, just a warning. Excessive 503 is related to service unavailability, perhaps crashing NodeBB? Examine logs.

Best continue on forum, thanks.
