### ISSUE TITLE
Some bootswatch skins broken

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6306]
This is what https://community.nodebb.org/ looks like right now if you select Spacelab. 

![image](https://user-images.githubusercontent.com/24903887/35782399-5df4fe50-09c5-11e8-9031-0a4e7b1dad0c.png)

**Comment by pitaj** [comment]
Will be fixed by #6304

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/d16667a5fb8f5bb9458c8e94dfb60cdb50a27011

**Comment by shvrdavid** [comment]
I see that this issue is closed, but seems to be far from corrected.   https://forum.smithmicro.com/topic/3612/broken-style-sheet-in-graphics-forum-header-issue

**Comment by psychobunny** [comment]
Hi, @shvrdavid, I assume you've applied the fix or updated to 1.7.5?

**Comment by shvrdavid** [comment]
Not yet, seems like the thing to do thou, lol
