### ISSUE TITLE
Notification email link doesn't work

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6310]
- **NodeBB version:** 1.7.4
- **NodeBB git hash:** 8c5aa740cab65a269856ab7b7f1224504e5cb53b
- **Database type:** mongo
- **Database version:** 3.2.11

Hi, I found that the notification email link doesn't work. When I click on it, I get no response. Also the link address starts with https://email.mg.sanatisharif.ir and our forum address is https://forum.sanatisharif.ir .

**Comment by sohrabafard** [comment]
https://email.mg.sanatisharif.ir/c/eJxdjkEKwyAURE8Tl6I_av0LFylt7vGTaBW0KZpQ6OkrXRaGWQxvhtmcWjB4wZIDIa0AYaSVBjSX3NzuWslZT3g1qC0OSpQHb_SkI7VINQWeKotOC4vrSIAiBLOCNyS1WcQmEReAS2DZxeN4tWGcBpi7wl7P8j_U8zNt3TWq8QflvL99bay6EnnxsdKHaj-xxkIp98oXy2k5Ug

it must be

https://forum.sanatisharif.ir/c/eJxdjkEKwyAURE8Tl6I_av0LFylt7vGTaBW0KZpQ6OkrXRaGWQxvhtmcWjB4wZIDIa0AYaSVBjSX3NzuWslZT3g1qC0OSpQHb_SkI7VINQWeKotOC4vrSIAiBLOCNyS1WcQmEReAS2DZxeN4tWGcBpi7wl7P8j_U8zNt3TWq8QflvL99bay6EnnxsdKHaj-xxkIp98oXy2k5Ug

**Comment by julianlam** [comment]
That looks to be an url changed by your email client. What email client are you using?

**Comment by mohammadhassan99** [comment]
@julianlam We use mailgun

**Comment by julianlam** [comment]
@mohammadhassan99 That is your email plugin for NodeBB. I'm asking you what email client you are using to read emails... However, I am not familiar with Mailgun and do not know whether they change urls as well.

You may want to take this up with their support, as the `email.mg` suggests their involvement.

**Comment by mohammadhassan99** [comment]
@julianlam Excuse me, we use Gmail App.

**Comment by julianlam** [comment]
I see, thank you. I don't believe it would be Gmail's fault, so we can rule it out for now. Possibly mailgun, then.

**Comment by mohammadhassan99** [comment]
Hello @julianlam , we made contact with Mailgun support and asked about this issue. Here is the answer they given: 

![photo_2018-02-09_01-44-11](https://user-images.githubusercontent.com/31972226/36001218-d5eae8a2-0d3a-11e8-96d3-8cb24b29830c.jpg)

**Comment by julianlam** [comment]
The `email.mg` url you are seeing is an url substitution that mailgun likely does for safety. If you click on the link, it goes to mailgun and **then** redirects you to the forum, so this is out of our control, sorry.

To my knowledge this is not something handled by NodeBB nor the mailgun email plugin.
