### ISSUE TITLE
Moderators don't get flag notification 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6314]
Hi, I wonder why our administrator receives post flag notification but moderators don't get it.

**Comment by barisusakli** [comment]
How did you make the user a moderator? Did you add the user and gave them moderator privilege or did you assign them to a group that has moderator privilege?

**Comment by mohammadhassan99** [comment]
@barisusakli Cannot say for sure! Sometimes assigning to group and sometimes give moderator privilege. Does it make difference?
