### ISSUE TITLE
Ability to update online users on socket connected

### ISSUE THREAD

**Issue by quickerlab** [NodeBB/NodeBB#6316]
I'm trying connect NodeBB via a client. After connected to socket.io server, I can see online count increased on dashboard, online hint and online status from /api/users.
But the user can't seen in Home->Users/section=online.

So I want to know if is it possiable update online users in these calls?
1. socket connect and seesion valid
2. user.setStatus<online>

**Comment by barisusakli** [comment]
Didn't add it to #1 when users are on bad connections it can cause tons of connect/disconnects in a short span of time.
