### ISSUE TITLE
User email format not checked

### ISSUE THREAD

**Issue by oyyq99999** [NodeBB/NodeBB#6317]
- **NodeBB version:**  1.7.4
- **NodeBB git hash:** 8e61d739c76a49895db1f874ec4c6259b89b2c26

- **Database type:** mongo
- **Database version:** 3.4.10

- **Exact steps to cause this issue:**

	1. goto edit email(/user/\<username>/edit/email)
	2. enter email as `a@example.com;b@example.com`
	3. you will get emails sent to both addresses, and your login email would be `a@example.com;b@example.com`as a whole

- **What you expected:** not validated email

- **What happened instead:** email sent and can be verified

**Comment by julianlam** [comment]
Are there any other ways to include multiple emails besides using a semicolon?

**Comment by pitaj** [comment]
Unfortunately validating emails is very hard. If the emailer chooses to accept that email as one or two there isn't anything we can do.

The only thing we can really do is send a validation email when the user email setting is  changed.

**Comment by julianlam** [comment]
Correct. We do not validate emails. However if there is the capability of putting in two emails, then the separator should be disallowed
