### ISSUE TITLE
Rewards module not working.

### ISSUE THREAD

**Issue by christancho** [NodeBB/NodeBB#6320]
- **NodeBB version:** V1.7.3
- **NodeBB git hash:** e16bec61d5aafc3cb7ad814d540e41a4f4e8b821
- **Database type:** mongo 
- **Database version:** 3.2.17

- **Exact steps to cause this issue:**

	1. I configured the rules on Extend>Rewards
	2. No reputation is added to the user based on post count.
      

- **What you expected:**
I expected that NodeBB to increase user's reputation

- **What happened instead:**
Nothing

**Comment by julianlam** [comment]
Can you show us the rules configured?

**Comment by psychobunny** [comment]
Hi this has been resolved with latest plugin and latest nodebb. I notice you are on 1.7.3 so I'll close unless you can provide more info, thanks.
