### ISSUE TITLE
Double button "search" in Navbar (Mobile)

### ISSUE THREAD

**Issue by victorelec14** [NodeBB/NodeBB#6321]
- **NodeBB version:** v1.7.4 and v.1.7.5
- **NodeBB git hash:** 

- **Database type:**  redis
- **Database version:** 3.2.10

- **Exact steps to cause this issue:**

- **What you expected:**
Open Navbar in Mobile devices give double "Search" (buscar) button.
This are for Logged and not logged users.

- **What happened instead:**

![doble_navbar](https://user-images.githubusercontent.com/543450/36122458-adf34454-1049-11e8-9421-47b434b204f2.png)

**Comment by julianlam** [comment]
Do you have two search buttons configured in the navigation settings? Perhaps for one you can hide on mobile. Check to see that the behaviour is identical on both.

Perhaps one opens the search bar on desktop... that one should be hidden on mobile.

**Comment by victorelec14** [comment]
this ? 

![nodebb_search](https://user-images.githubusercontent.com/543450/36124509-9bc80060-1050-11e8-9606-4cc0015e086a.png)

**Comment by julianlam** [comment]
Hm, looks like you only have one. Will see if I can reproduce

**Comment by RoiEXLab** [comment]
@julienlam The default search bar turns into a button on mobile because the header is too small, that's why the second button is showing up
