### ISSUE TITLE
Important Information Field

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#6325]
I'm not sure if this already has been requested at some point, but I think it would be nice, if NodeBB had a way to notify users of important events on the start page (or even every page), much more visible than a pinned post.
Important Events could be for example:
Scheduled Server Restarts, expected downtimes, issues with related services that people were about to report to the forum, but perhaps also shoutouts to the community for reaching a donation goal or something.

**Comment by pitaj** [comment]
How is this not solved by a simple text widget on the home page?

**Comment by RoiEXLab** [comment]
@pitaj hmm that might work out as well. 
I originally thought of something that would pop up as some sort of notification, similar to how travis does it, but works for guests as well...

**Comment by psychobunny** [comment]
I've seen nicely designed html widget headers on some of our clients with maintenance alerts, etc. Could do something better but plugin territory imo
