### ISSUE TITLE
Issue with the website design.

### ISSUE THREAD

**Issue by LMADoneur** [NodeBB/NodeBB#6327]
![image](https://user-images.githubusercontent.com/29049402/36300372-6605dbc4-1301-11e8-9cd2-2e5a9bdf6602.png)

I have this issue with google chrome (no issue on Canary)
![image](https://user-images.githubusercontent.com/29049402/36300450-a3139146-1301-11e8-8079-4281df5c5abe.png)

**Comment by barisusakli** [comment]
Sounds like https://github.com/NodeBB/NodeBB/issues/6306, clear cache and make sure you are on 1.7.5 or latest.
