### ISSUE TITLE
Favicon changes not kicking in

### ISSUE THREAD

**Issue by asthomasdk** [NodeBB/NodeBB#6328]
- **NodeBB version: 1.7.5** 
- **Database type: mongo**
- **Running in a Docker environment**

1. Log in as an admin user and go to Settings, General
2. Click on the favicon field, choose a file to upload and press upload
3. The file seems to be uploaded, and a file name like this is shown: `/assets/uploads/system/favicon.ico?v=1518772791076`
4. Pressing the save button gives the error "Changes not saved: NodeBB encountered a problem saving your changes". 

Refreshing the browser and restarting NodeBB makes no difference - the default favicon is still showing. 

Logging into the NodeBB system and checking uploaded files, I can see that the favicon has been uploaded to the `public/uploads/system` directory. 

A quick hack to resolve this for now has been to manually copy the uploaded file into the root of the `public` directory.

**Comment by barisusakli** [comment]
>Changes not saved: NodeBB encountered a problem saving your changes
This means there is an error on the server side, can you apply this commit and try saving again. https://github.com/NodeBB/NodeBB/commit/825c493c409004ede26ddfdfa67d56f5a458d194

**Comment by asthomasdk** [comment]
Made the change, rebuilt and restarted. 

I now get this error when trying to save the favicon.ico file I uploaded. 

```
Changes Not SavedNodeBB encountered a problem saving your changes. (ENOENT: no such file or directory, open '/usr/src/app/public/uploads/system/site-logo-x50.png')
```

**Comment by barisusakli** [comment]
Have uploaded a site logo to your forum before?

**Comment by asthomasdk** [comment]
Yes - logos are no problem. 

It looks like it is only the favicon that is an issue.

**Comment by barisusakli** [comment]
That's weird then, when you upload a site log it should resize that and place it at `/public/uploads/system/site-logo-x50.png` can you try uploading a site logo again and then uploading the favicon and save. See if that still gives an error.

**Comment by asthomasdk** [comment]
Changing the site logo works fine. 

Subsequent change to favicon to a different .ico file also seems to work - at least saves without errors. But - it does not change the favicon.

**Comment by barisusakli** [comment]
Might have to restart the forum since the favicon is cached.

**Comment by asthomasdk** [comment]
Been there, done that ;-)

**Comment by barisusakli** [comment]
You can check if the new file was uploaded by going to `yourforum.com/favicon.ico` as well.

**Comment by asthomasdk** [comment]
Afraid it hasn't changed.

**Comment by barisusakli** [comment]
What about when you add a cache buster like `yourforum.com/favicon.ico?v=123` ?

**Comment by asthomasdk** [comment]
No difference

**Comment by pitaj** [comment]
What about the actual file on the server? Can you check whether the favicon.ico file is the one you want?
