### ISSUE TITLE
admin/extend/widgets error in 1.7.5 clean install

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#6331]
- **NodeBB version:** 1.7.5
- **NodeBB git hash:** b126d7ef0921ea8b3579b719c87ad8a21be38cf4

- **Database type:** mongo 
- **Database version:** v3.6.2

- **Exact steps to cause this issue:**

	1. CLEAN install of nodebb 1.7.5
	2. Then, I clicked /admin/extend/widgets

- **What you expected:** widgets

- **What happened instead:**
 Internal Error.
Oops! Looks like something went wrong!
/api/admin/extend/widgets
templatesOnDemand.source-template-empty

**Comment by barisusakli** [comment]
@awunnenb can you apply the following commit and let me know the error you get. https://github.com/NodeBB/NodeBB/commit/e36657d48c2e3c1924cc43b9d14767899a380e50

**Comment by awunnenb** [comment]
commit e36657d48c2e3c1924cc43b9d14767899a380e50
Author: Barış Soner Uşaklı <baris@nodebb.org>
Date:   Mon Feb 19 11:17:15 2018 -0500

error:templatesOnDemand.source-template-empty, /opt/testforum/build/public/templates/admin/defaultwidget.tpl

**Comment by awunnenb** [comment]
defaultwidget.tpl and categorieswidget.tpl with 0 Bytes
