### ISSUE TITLE
Forum Stats widget does not seem to work in 1.7.5

### ISSUE THREAD

**Issue by henrikekblad** [NodeBB/NodeBB#6335]
- **NodeBB version:** 1.7.5
- **Persona version:** 7.2.16 (trying to upgrade to latest messed up forum) 

- **Database type:** redis

	1. First I did this after upgrading to 1.7.5

**Comment by barisusakli** [comment]
Can you provide some more details? I tried the forum stats widget on latest and it works fine on persona theme. Maybe a screenshot of what is wrong?

**Comment by henrikekblad** [comment]
It just doesn't show up. Not a trace of it in the generated DOM.

It used to be just above the copyright message:
https://forum.mysensors.org/categories

<img width="772" alt="screen shot 2018-02-22 at 00 08 05" src="https://user-images.githubusercontent.com/5717075/36510778-8f99407c-1764-11e8-8a0c-18ff3ba1939f.png">

Not sure if this should worry me (about "/api/widget/render")
<img width="1245" alt="screen shot 2018-02-22 at 00 11 06" src="https://user-images.githubusercontent.com/5717075/36510905-f7f9c3b2-1764-11e8-83c5-02b3ed2f9411.png">

Nothing in the syslog

**Comment by barisusakli** [comment]
Looks like the widget html is empty some reason. Do you have other plugins that might interfere? What is the output of `./nodebb plugins`? Do you have the template file in `/build/public/templates/widgets/forumstats.tpl`

**Comment by henrikekblad** [comment]
Hmm... is this right?

~/NodeBB/build/public/templates/widgets$ cat forumstats.js                                                                                                                     > !function(e){"object"==typeof module&&module.exports?module.exports=e():"function"==typeof define&&define.amd&&define(e)}(function(){return function(e,n,o,t,f){}})

**Comment by barisusakli** [comment]
This is what the `forumstats.js` contains for a working widget.

```

(function (factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else if (typeof define === 'function' && define.amd) {
    define(factory);
  }
})(function () {
  function compiled(helpers, context, guard, iter, helper) {
       return '<div class="row forum-stats">\r\n\t<div class="col-md-3 col-xs-6">\r\n\t\t<div class="stats-card ' + helpers.__escape(guard(context && context['statsClass'])) + '">\r\n\t\t\t<h2><span class="stats" title="' + helpers.__escape(guard(context && context['online'])) + '">' + helpers.__escape(guard(context && context['online'])) + '</span><br /><small>[[global:online]]</small></h2>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class="col-md-3 col-xs-6">\r\n\t\t<div class="stats-card ' + helpers.__escape(guard(context && context['statsClass'])) + '">\r\n\t\t\t<h2><span class="stats" title="' + helpers.__escape(guard(context && context['users'])) + '">' + helpers.__escape(guard(context && context['users'])) + '</span><br /><small>[[global:users]]</small></h2>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class="col-md-3 col-xs-6">\r\n\t\t<div class="stats-card ' + helpers.__escape(guard(context && context['statsClass'])) + '">\r\n\t\t\t<h2><span class="stats" title="' + helpers.__escape(guard(context && context['topics'])) + '">' + helpers.__escape(guard(context && context['topics'])) + '</span><br /><small>[[global:topics]]</small></h2>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class="col-md-3 col-xs-6">\r\n\t\t<div class="stats-card ' + helpers.__escape(guard(context && context['statsClass'])) + '">\r\n\t\t\t<h2><span class="stats" title="' + helpers.__escape(guard(context && context['posts'])) + '">' + helpers.__escape(guard(context && context['posts'])) + '</span><br /><small>[[global:posts]]</small></h2>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n';
     }

  return compiled;
});
```

I think your js file didn't have the same content?

**Comment by henrikekblad** [comment]
No, mine looks like this:

> !function(e){"object"==typeof module&&module.exports?module.exports=e():"function"==typeof define&&define.amd&&define(e)}(function(){return function(e,n,o,t,f){}});

Is this generated? From what?

**Comment by barisusakli** [comment]
It is created the from the tpl file that you posted. Does your tpl file have those weird characters or was that a copy paste error?  ` │··································`

**Comment by henrikekblad** [comment]
No, sorry, it was from my mosh console.

**Comment by barisusakli** [comment]
It looks as if yours was minified, are you running anything that would minify that file? @pitaj any ideas?

**Comment by pitaj** [comment]
The files are automatically minified by benchpress, but it should have a lot more code than what's there.

**Comment by pitaj** [comment]
I'd suggest running `./nodebb build tpl` and trying again.

**Comment by henrikekblad** [comment]
... and stats came back! Thanks @pitaj! 

Somehow the build done at restarts must have failed... and I have restarted multiple times since the upgrade. 

Did another restart and the forumstats.js seems to be build correctly.

Strange... but I'm happy.
