### ISSUE TITLE
Problems with logging

### ISSUE THREAD

**Issue by GitLaboratory** [NodeBB/NodeBB#6339]
**Node.js**
- 8.9.4

**NodeBB**
- 1.7.5

**PM2**
- 2.4.5

**Error from log:**
```
error: /admin/advanced/logs

Error: ENOENT: no such file or directory, open 'logs/output.log'
```

**Run command:**
```
pm2 start "app.js"
```

**Comment by GitLaboratory** [comment]
![default](https://user-images.githubusercontent.com/2738607/36930796-41b87c32-1edb-11e8-9470-c58e3e675537.png)

**Comment by julianlam** [comment]
Please ensure that the user running NodeBB has write access to the `logs` directory.
