### ISSUE TITLE
admin login fails with invalid csrf token after clean install v1.7.5

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#6341]
- **NodeBB version:** 1.7.5
- **NodeBB git hash:** bce640e51485c322e25543d51403f92339d90a88

- **Database type:** mongo
- **Database version:** v3.6.3

- **Exact steps to cause this issue:**

1. clean install ubuntu 16.04
2. install build-essential
3. clean install nodejs v8.9.4
4. clean install mongodb v3.6.3
5. git clone latest nodebb (bce640e)
6. cd /opt/nodebb
7. ./nodebb setup
8. setup finished without errors
9. start ./nodebb start
10. log ./nodebb log
11. setup nginx with ssl instructions from https://nodebb.readthedocs.io/en/latest/configuring/proxies/nginx.html
12. restart nginx with success
13. browse to my new nodebb forum, everything seems to be ok
13. click login and use admin credentials created with setup

- **What you expected:**
expected succesful admin login 
- **What happened instead:**
login fails with invalid csrf token

LOG:
2018-03-04T15:14:11.066Z [2015] - info: [socket.io] Restricting access to origin: https://<mynodebb.url>:*
2018-03-04T15:14:11.342Z [2015] - info: Routes added
2018-03-04T15:14:11.345Z [2015] - info: NodeBB Ready
2018-03-04T15:14:11.352Z [2015] - info: Enabling 'trust proxy'
2018-03-04T15:14:11.357Z [2015] - info: NodeBB is now listening on: 0.0.0.0:4567
2018-03-04T15:15:13.333Z [2015] - error: /login
 invalid csrf token

**Comment by julianlam** [comment]
Please paste the contents of your nginx configuration as well as your `config.json`

**Comment by awunnenb** [comment]
{
    "url": "https://<my.url>",
    "secret": "e69d145a-94c2-4114-bd51-09c5cf6b7ac6",
    "database": "mongo",
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "",
        "password": "",
        "database": "nodebb",
        "uri": ""
    },
    "type": "literal"
}

**Comment by awunnenb** [comment]
`server {

    server_name <mydomain>;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<mydomain>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<mydomain>/privkey.pem; # managed by Certbot
    
    # enables all versions of TLS, but not SSLv2 or 3 which are weak and now deprecated.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    # disables all weak ciphers
    ssl_ciphers 'AES128+EECDH:AES128+EDH';

    ssl_prefer_server_ciphers on;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://127.0.0.1:4567;
        proxy_redirect off;

        # Socket.IO Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

}

server {

    if ($host = <mydomain>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;

    server_name <mydomain>;
    return 404; # managed by Certbot

}
`

**Comment by julianlam** [comment]
The configs look fine. Let me know your site url and add my public key so I can inspect your configs without redactions:

`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJtoHRgs+yAgzFkBV1BZWoMyBkAd9JOvsuj5WH2A0EMesEjqAcdd3Fb4MJ/SKdV/oJCxU8F7ZyeY5yHK9aBdJrFlKDlMNoWAryoq50hGHYxGNnh2IPYV2XU2Hdar+0xxj8IsBTYM2ooB6T1EiC8NcvQ3vslIv0jkriK3sDHuD7QzECdut2J/2ROIDjJ9XLj1OVrVBj0bE6Bb8nPb64JpujNOkp9L0Z4gcQsCCzt7EUAoOufn3L2Y38GIpBAhba/IiHeYe8Uf+++cCFoTGh+2mvoC0TpTVt1hUn9Ma2YYKWVBxYRX/3PvW0+MDHUOXKUhdaiC+xmAsZq91mHb4E092d`

**Comment by awunnenb** [comment]
I can't give you access to the server of my customer, sorry. But the problem is very easy to reproduce. Nodebb 1.7.5 will never run on ubuntu 16.04 and nginx 1.12.x after clean install. There so many problems with clean install since 1.7.5. I have only one ubuntu server with nodebb upgrade from 1.6.x to 1.7.5. Upgrade nodebb works fine but clean install 1.7.5 never works for me, sorry.

**Comment by julianlam** [comment]
Unfortunately I cannot reproduce on my end, so this will require additional information from another individual.

**Comment by julianlam** [comment]
Ideally, spin up another server that I can access :+1:

**Comment by awunnenb** [comment]
same problem without nginx and direkt connect to nodebb on port 4567

**Comment by awunnenb** [comment]
git clone -b v1.7.0 https://github.com/NodeBB/NodeBB.git nodebb

everything works fine.

**Comment by awunnenb** [comment]
nodebb 1.7.0 installed
git fetch
git reset --hard origin/master
./nodebb upgrade

everything works fine with 1.7.5

so i have to install 1.7.0 first and upgrade to 1.7.5 works fine.

clean install of 1.7.5 fails on ubuntu 16.04, with node  v8.9.4 and mongodb v3.6.3

has anybody testet clean install on ubuntu and this version 1.7.5 ???

**Comment by blagoeres** [comment]
I have the same problem on `v1.10.x` branch, but only on HTTP, not on HTTPS. If I enable HTTPS via Let's Encrypt, I can login just fine.

Here is a screen recording https://www.youtube.com/watch?v=aRQjiM53z-g

 Here is `output.log`:

![screen shot 2018-07-03 at 10 34 41 am](https://user-images.githubusercontent.com/15614178/42208562-c67009c8-7eac-11e8-8dcf-58899d545983.png)

**Comment by angristan** [comment]
I have the issue with a clean install on 1.11.0 and 1.11.0.
