### ISSUE TITLE
Categories content - Missing translation

### ISSUE THREAD

**Issue by AlexGalax** [NodeBB/NodeBB#6342]
- **NodeBB version:** 1.7.5
- **NodeBB git hash:** 7df191412de9dfd88c3c9b919b6989fd18b5d445
- **Database type:** mongo
- **Database version:** v3.4.7
- **Exact steps to cause this issue:** filling category content (title, description) with translation tag `[[foo:bar]]`
- **What you expected:** translation
- **What happened instead:** `Missing translation "foo:bar"`

Thank you!

**Comment by julianlam** [comment]
Which translation key are you using? If you're using foo:bar then it's working as intended as that key doesn't exist.

**Comment by AlexGalax** [comment]
oh man, stupidity issue by me. sorry and thanks for quick reply!
