### ISSUE TITLE
The masonry.js not loaded if page refreshes directly

### ISSUE THREAD

**Issue by georgezhang** [NodeBB/NodeBB#6344]
- **NodeBB version:** 
v1.7.x
- **NodeBB git hash:** 

7df191412de9dfd88c3c9b919b6989fd18b5d445
- **Database type:** mongo or redis
mongo
- **Database version:** 

3.2.9
- **Exact steps to cause this issue:**

1. Activate plugin nodebb-theme-lavender;
2. create multiple categories and topics;
3. Access to http://localhost:4567/categories directly from URL in browser.
More detail on https://community.nodebb.org/topic/11983/the-masonry-js-not-loaded-if-page-refreshes-directly

- **What you expected:**

Masonry effect should apply like clicking Categories Button on navigation.

- **What happened instead:**

The masonry.js or its initial script was skipped. Masonry effect doesn't seems to be applied.

**Comment by julianlam** [comment]
@georgezhang Can you submit a pull request with the above commits?
