### ISSUE TITLE
Opening notifications or chats dropdowns before page has fully loaded does not properly load notifications/chats respectively

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6354]
A bit of a UX bug... if you're too quick to open the notifications or chats dropdowns when cold loading the page, the dropdown will open (via bootstrap handlers), but the event listener to actually load the notifications/chats is not added yet, and so the loading spinner stays until the dropdown is closed and re-opened.

**Comment by julianlam** [comment]
:bell: Not really a breaking change for theme developers

... although there's a class you may want to add if you have your own `templates/partials/menu.tpl`

**Comment by FaizanZahid** [comment]
I totally agree with this thing I have noted this as well
