### ISSUE TITLE
[New Features] Merge Topic as Comment

### ISSUE THREAD

**Issue by victorelec14** [NodeBB/NodeBB#6356]
NodeBB have a function to Fork a comment to a new Topic but why not a inverse function, a Topic to comment (from another topic) a "Merge Function" ??

this is useful when you create the threads of which there is already an open thread and not need delete this post.

**Comment by victorelec14** [comment]
ohhh this function exist (sorry), but only in categories, maybe is better add it in to topic page (tools button) ?.

**Comment by julianlam** [comment]
It is in the categories page because you are clicking which topics you want to merge, and so you'd need to be in the categories page to do this.
