### ISSUE TITLE
Problem with editing and edit history 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6359]
- **NodeBB version:** 1.7.5
- **Database type:** mongo 
- **Database version:** 3.2.11

Hi, I noticed some problems while working with edit history tool and editing. I understood that:
1- The history doesn't show the full post text if the text is long (it is incomplete).
2- Also if I post a picture, it doesn't show in edit history.
3- When I write a long paragraph and edit that post, for the first time I get **[this error](https://user-images.githubusercontent.com/31972226/37453465-fbdb8f3a-284c-11e8-8aca-2a4c0da264eb.jpg)**, but at second attempt it will be edited.

**Comment by julianlam** [comment]
How long is your post content? Can you paste the raw input here?

**Comment by mohammadhassan99** [comment]
@julianlam Yes of course. For example I pasted this: 

The M1918 is a selective fire, air-cooled automatic rifle using a gas-operated long-stroke piston rod actuated by propellant gases bled through a vent in the barrel. The bolt is locked by a rising bolt lock. The gun fires from an open bolt. The spring-powered cartridge casing extractor is contained in the bolt and a fixed ejector is installed in the trigger group. The BAR is striker fired (the bolt carrier serves as the striker) and uses a trigger mechanism with a fire selector lever that enables operating in either semi-automatic or fully automatic firing modes. The selector lever is located on the left side of the receiver and is simultaneously the manual safety (selector lever in the "S" position – weapon is safe, "F" – fire, "A" – automatic fire). The "safe" setting blocks the trigger.

The weapon's barrel is screwed into the receiver and is not quickly detachable. The M1918 feeds using double-column 20-round box magazines, although 40-round magazines were also used in an anti-aircraft role; these were withdrawn from use in 1927. The M1918 has a cylindrical flash suppressor fitted to the muzzle end. The original BAR was equipped with a fixed wooden buttstock and closed-type adjustable iron sights, consisting of a forward post and a rear leaf sight with 100 to 1,500 yard (91 - 1,372 m) range graduations.

As a heavy automatic rifle designed for support fire, the M1918 was not fitted with a bayonet mount and no bayonet was ever issued.[12] Only one experimental bayonet fitting was ever made for the BAR by Winchester.[12] This was a standard, M1917 bayonet fitted at the Winchester factory with a special muzzle ring. The bayonet was attached to a standard M1918 BAR by means of a special experimental flash hider assembly.[12] This prototype bayonet-flash hider assembly came from the Winchester in-house factory museum in New Haven, Connecticut with a tag printed on one side Winchester Repeating Arms Co./New Haven Conn., and handwitten on the other side: combined flash hider, front sight and bayonet mount for Browing Automatic Rifle Model 1918 with bayonet and scabbard and the date - September 7, 1918.[12] There is no evidence whatsoever of military adoption nor a military stock number, name, or classification.[12]

**Comment by julianlam** [comment]
Thanks, am in the midst of re-designing the diffs system to handle larger post bodies. Unexpected behaviour! :smile:

**Comment by mohammadhassan99** [comment]
@julianlam And also it doesn't show the pictures 🤔

**Comment by julianlam** [comment]
... yes :smile:

**Comment by mohammadhassan99** [comment]
😄 
@julianlam Something I noticed recently. When you scroll down the whole posts will be shown. Please **[see this Gif](http://uupload.ir/files/oqr_video_2018-03-15_202144.gif)**
