### ISSUE TITLE
(suggestion) On NodeBB 1.8, do not activate Composer Redactor on Chat (by default)

### ISSUE THREAD

**Issue by floufille** [NodeBB/NodeBB#6364]
- **NodeBB version:** 1.8
- **NodeBB git hash:** 2244026e7babab7b72180393c8707208323ced57

- **Database type:** mongo 
- **Database version:** v3.6.3

- **Exact steps to cause this issue:**

The server is configured with : Persona Theme and Composer Redactor

The Composer Redactor is activated on chat, and the fact the "enter key" do not send the message disturb users.

- **What you expected:**

- **What happened instead:**

Enter key sends message. Or Composer Default activated on chat by default

**Comment by julianlam** [comment]
Thanks, will try to fix in redactor so enter sends message.

In the meantime you can downgrade to v3.1.0 of redactor plugin.

**Comment by floufille** [comment]
At this time, i just migrate my test server. So, i will try this trick this week.

If we can keep the redactor plugin on chat (with upload image feature) without the "enter key" trouble, it will be so nice !
(at least, have the two features at the same time, no matter the solution)

**Comment by julianlam** [comment]
Now of course, fixing it got exponentially harder because Redactor rewrote their plugin, we can't get one open-sourced for us because of their licensing terms, and so we can't upgrade.

They also have no link to old documentation. Nice of them :+1:

**Comment by floufille** [comment]
Downgrade the Redactor plugin does not solve the issue.

If the lack of documentation of Composer Redactor is a big trouble. If there is a way to keep the default redactor in chat, and keep the Composer Redactor in forum. It will be OK for me.

**Comment by julianlam** [comment]
Did you run NodeBB build? Because the code to actually implement redactor in the chat isn't in that version.

**Comment by floufille** [comment]
I thought update the version in the package.json file and run ;./nodebb stop;./nodebb build;./nodebb start
was sufficient (but actually no)

```
/data/nodebb/repository$ grep composer-redactor package.json
    "nodebb-plugin-composer-redactor": "^3.1.0",

```

I did not find the documentation for downgrading a plugin.

**Comment by pitaj** [comment]
Do this:
```
npm i nodebb-plugin-composer-redactor@3.1.0 --save
./nodebb stop && ./nodebb build && ./nodebb start
```

**Comment by floufille** [comment]
It works well. Thanks !

**Comment by floufille** [comment]
Any news of this issue ? (enter keys does not send message in chat with composer redactor).

The trick to downgrade to 3.1.0 does not work well with nodebb 1.10.x.

**Comment by floufille** [comment]
I've commented in the file : "./node_modules/nodebb-plugin-composer-redactor/static/lib/redactor.core.js" 

The section which active composer in chat : 

$(window).on('action:chat.loaded', function (e, containerEl) {
and : 
 $(window).on('action:chat.sent', function (e, data) {

So, for now, i can upgrade to nodebb 1.10.x.

**Comment by julianlam** [comment]
:+1: That is a sufficient workaround for now. I'd like to eventually keep it working, although with "enter to send" functionality. So far I am unable to get it working, and with the upgrade path blocked by Imperavi (and their old docs removed), it is hard for me to maintain this plugin now.

Likely we'll move to a different WYSIWYG composer.

**Comment by julianlam** [comment]
Active development on the Redactor plugin has ceased while we undergo active development of the [Quill Composer plugin](https://github.com/nodebb/nodebb-plugin-composer-quill)

Note that as of writing, the plugin is not production ready.

**Comment by julianlam** [comment]
The above quoted workarounds (updating the file to not add redactor to chat, and/or rollbacks to old version of Redactor) are now the recommended courses of action if you would not like Redactor present on chat boxes.
