### ISSUE TITLE
Seeing which mods banned the user and force the reason for ban.

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6367]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

Right now, most of the time we don't see which moderator banned this particular user and mods sometimes forget to give reasons while banning. They must be always required to give reason while banning each user.

**Comment by FaizanZahid** [comment]
it would be nice to always see, which mod banned a user.

**Comment by pauljherring** [comment]
While not the most user-friendly UI (good luck paging through the history,) if you go to /admin/advanced/events and search for `user-ban`, you can find out who performed the ban, but not the reason (nor any duration, actually - the test below was a ban for one hour; there's no discernable difference between this and one of our spammers.)

![screenshot from 2018-03-17 16-26-11](https://user-images.githubusercontent.com/3939886/37557670-00a80264-2a00-11e8-8cfe-13ec5da99782.png)

**Comment by mohammadhassan99** [comment]
Already we have this suggestion: 

https://github.com/NodeBB/NodeBB/issues/6290

I think it is a good idea.

**Comment by julianlam** [comment]
Thanks @mohammadhassan99 -- we'll track it there.

**Comment by julianlam** [comment]
For the record I also think this is a good idea :+1:
