### ISSUE TITLE
Can't edit some topics

### ISSUE THREAD

**Issue by Alisummer** [NodeBB/NodeBB#6370]
- **NodeBB version:1.8.0** 
- **NodeBB git hash:bbcaff821fe8bff51dbad5817fcacc5f7f8b7ec3** 

- **Database type:mongo** mongo or redis
- **Database version:3.2.19** 

- **Exact steps to cause this issue:**
Edit some topics and save them

- **What you expected:**

Topics were edited
- **What happened instead:**

Btree::insert: key too large to index, failing nodebb.objects.$_key_1_value_-1 2856 { : "post:10:diffs", : "Index: =================================================================== --- +++ @@ -1,18 +1,18 @@

![-512a9d65acb1fbf3](https://user-images.githubusercontent.com/7764726/37567054-3849a43c-2afc-11e8-87b5-79231bf86a0f.jpg)

**Comment by psi1424** [comment]
me too

![capture](https://user-images.githubusercontent.com/6489925/37578183-bfc9e0e4-2b69-11e8-8e38-e89ff9e2ff6a.PNG)

**Comment by julianlam** [comment]
This is fixed and will be released with 1.8.1 on Wednesday
