### ISSUE TITLE
Keep crashing after running a while

### ISSUE THREAD

**Issue by SaitDev** [NodeBB/NodeBB#6375]
- **NodeBB version:** 1.8.0
- **NodeBB git hash:** 2244026e7babab7b72180393c8707208323ced57

- **Database type:** redis
- **Database version:** 3.2.9

- **Exact steps to cause this issue:**
    * clone ver v1.8.x
    * install plugins/theme via npm: nodebb-plugin-custom-homepage, nodebb-plugin-custom-pages, nodebb-plugin-imgur, nodebb-plugin-poll, nodebb-plugin-reputation-rules, nodebb-theme-material
    * copy my config.json
    * ./nodebb setup
    * node app.js
    * wait few mins 
- **What you expected:**
    * keep running
- **What happened instead:**
    * nodebb crash

*trace back*: https://pastebin.com/hZfYEjs2

**Comment by julianlam** [comment]
How do you connect to Redis? Perhaps show `config.json`? Did this happen only recently, or new install?

**Comment by SaitDev** [comment]
Upgraded from 1.5.x, didnt happen that time. After upgrade i got this issue.
`config.json` https://pastebin.com/uqnnY2Mf

**Comment by SaitDev** [comment]
Sorry, update missing step, hope this help you reproduce the issue: I also install few plugins :arrow_up: :arrow_up: Maybe cause by any of them?

**Comment by barisusakli** [comment]
Are there other errors in your log before the one that you pasted?

**Comment by barisusakli** [comment]
You can try with https://github.com/NodeBB/NodeBB/commit/3c4b4f5263ca2c5d6bd60f437f14df52da4776d8 and see if you still get the error.

**Comment by SaitDev** [comment]
Seem fixed now. Test run well for few hours
