### ISSUE TITLE
NodeBB no button is working on Mobile phones

### ISSUE THREAD

**Issue by sherkhanz** [NodeBB/NodeBB#6382]
Hi, 

Good day. I just installed NodeBB serveral times both 1.7 and 1.8 and both are having non functional buttons on mobile device. I know it's not a bug as it's too critical for normal functionality of forum and multiple versions can't have it. But on other hand I am not able to debug it. 

System info is:

NodeBB version: 1.8.1
NodeBB git hash: 2b27f1f398f73ec215a584b27f72dd588f8f0b85
Database type: mongo
Database version: b version v3.2.19

- **Exact steps to cause this issue:**

Logged In via phone on chrome and Firefox
Navigated to General Setting, categories and themes. 
On former two, button in the right lower corner isn't working for saving and adding resepectively
Activate button theme shows confirmation dialog but nothing happens on confirmation

I checked ./nodebb log but no error is there. 
Also when siteoads, it shows an error message about being disconnected from nodebb. Backend log shows nothing related to it. 

The app is online and I can provide credentials in private if someone wanna have a look.

Thanks alot for the great software and great suppprt.

**Comment by julianlam** [comment]
The disconnection message suggests that perhaps NodeBB is crashing or the url set in config.json is incorrect

**Comment by sherkhanz** [comment]
Thanks a lot. That was quick and effective. Never got the problem getting sorted so fast on GitHub. 

Thanks 👍👍👍

**Comment by sherkhanz** [comment]
Thanks a lot. That was quick and effective. Never got the problem getting sorted so fast on GitHub. 

Thanks 👍👍👍
