### ISSUE TITLE
Ability to copy topic and each post URL to clipboard for easily sharing.

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6387]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

This happens to us many times, most of the time we are using the forum and we want to share a topic or an individual post with someone who are not on social media such as whatsapp or send someone some thing in email. 

This is a tiny enhancement, clicking on the 3 dot ham burg menu should have 1 more option saying "Copy URL" that will copy that specific post/topic URL to user's clipboard, so that they can easily share it with anyone who is not on social media. All sites like Google docs, Quora and Facebook do this.

See this example:
![image](https://user-images.githubusercontent.com/9073066/37825173-ce88b306-2e86-11e8-8c11-a366b8cb76c5.png)

Thanks guys! you guys are the best!

**Comment by pauljherring** [comment]
You mean like most browser's in-built technology for doing this?

![image](https://user-images.githubusercontent.com/3939886/37826105-2119e5b0-2e8a-11e8-8cfd-93286935c904.png)

**Comment by FaizanZahid** [comment]
Umm not really because, if you are on mobile device, you cant do this.

Just look at google sheets and google docs, just like we can share a URL of google sheet or docs with anyone by clicking copy URL, the same thing.

**Comment by FaizanZahid** [comment]
Doing this will make it easier for mobile users to share topics/posts, right now they have to manually select all the url in address bar and then copy manually. which is quite cumbersome for most users, as you know users r super lazy.

**Comment by pauljherring** [comment]
> Umm not really because, if you are on mobile device, you cant do this.

Umm really, you can. 

Look - there's even a `Share Link` option!

![image](https://user-images.githubusercontent.com/3939886/37826954-60a0ab94-2e8d-11e8-8d84-f0bd8a34526d.png)


> right now they have to manually select all the url in address bar and then copy manually

No they don't.

**Comment by julianlam** [comment]
PJH is correct, we've supported this for quite some time :smile:

**Comment by julianlam** [comment]
Specifically the timestamp contains the direct link, much like how it is done by Facebook Twitter etc

**Comment by FaizanZahid** [comment]
Well PJH how did you opened that popup ? our forum is on webview so we don't see any such option to copy link within the webview.

**Comment by FaizanZahid** [comment]
i was saying to let users copy the post url when they r on the post page, tapping on it for so long does not show this popup when on a topic page itself. It does not come up the hover popup on webview on android.

**Comment by julianlam** [comment]
Long press on the link should open context menu similar to any other right-click action, no?

**Comment by FaizanZahid** [comment]
Well it works if we r browsing the site on google chrome on mobile, but with android webview app it does not work. our website app is just opens the site in android webview so in that case long tap does not work there.
