### ISSUE TITLE
Allow users to add more custom tags to whitelisted category tags

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6389]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

Right now, if i set 1 whitelist tag on a category in ACP, then when users are posting in that category, they can only use that ONLY 1 Predefined tag while making topics. How can we allow users to have that compulsory tag  (the whitelisted tag) and also allow users to add their own min compulsory tags. As we have forced users to add atleast 4 tags to each topic. but if we whitelist 1 tag for a category they can't add ANY OTHER new custom tag.

**Comment by barisusakli** [comment]
You can't at least not without writing some custom plugin, the tag whitelist is to prevent adding custom tags.
