### ISSUE TITLE
Support for ES6

### ISSUE THREAD

**Issue by max06** [NodeBB/NodeBB#6391]
Like mentioned in #5864, uglify-js doesn't play very well with ES6.

I started developing some plugins, all using a lot of ES6 syntax. It worked pretty well while I was using `grunt watch` - but `./nodebb build` fails.

Please add support for ES6.

**Comment by julianlam** [comment]
https://github.com/mishoo/UglifyJS2/issues/448

@pitaj Can you investigate feasibility of using `uglify-es` in our minifier? Maybe it is faster too :smile:

**Comment by julianlam** [comment]
Closed via PR #6402
