### ISSUE TITLE
Nodebb shows most guests as online

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6397]
- **NodeBB version:** Any
- **Database type:** All
- **Exact steps to cause this issue:**

1. Create a topic that guests can reply in it.
2. A guest replies in that topic and exit forum.
3. Another guest with different IP address replies in that topic.

Notice: now if the first guest is offline and the second is online, you see both of them showed online in the topic.

- **What you expected:**

I expected the first guest to be shown offline.

- **What happened instead:**

It showed it online.

**Comment by pitaj** [comment]
What do you mean by "showed online"?

**Comment by mohammadhassan99** [comment]
@pitaj I mean the status shows that the guest is online

![2018-03-25_200930](https://user-images.githubusercontent.com/31972226/37876896-9342516a-3068-11e8-8424-526862c47bb5.jpg)

**Comment by barisusakli** [comment]
This is a bug, guests should always show up offline

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/59dc4024b9361ecfbd842ac6de5b8aec94a12a61
