### ISSUE TITLE
Fully disable email notification

### ISSUE THREAD

**Issue by SaitDev** [NodeBB/NodeBB#6398]
I wanna disable email subscribe for user, no option for email notification on their setting page.

**Comment by pitaj** [comment]
Why?

**Comment by SaitDev** [comment]
To reduce the cost. The email should only be used for register and password recover :smile: 
On other side, on `/admin/settings/email` there is an option `Disable subscriber notification emails` but seem only disable the *Digest* job . The title doesnt really make sense

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/8200
