### ISSUE TITLE
Nodebb misrecords device

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6401]
Hi, I've found something interesting. I thought it would be good to share with you if you consider that as a bug. 
When you open Nodebb with mobile browsers (Android phones) in desktop view and log in, you will see that Nodebb thinks it was Linux not Android.

![2018-03-26_222655](https://user-images.githubusercontent.com/31972226/37924021-e9d25e5c-3145-11e8-8bb5-e97e3286ee42.png)

**Comment by pauljherring** [comment]
> mobile browsers (Android phones) in **desktop view**

> Nodebb thinks it was Linux not Android.

You're asking your browser to lie to the server, and expecting the server to pick up on that lie and ignore it?

**Comment by pitaj** [comment]
Chrome changes the user agent string when is desktop view. There's no way to fix this on the NodeBB end.
