### ISSUE TITLE
Render failed for template <head>

### ISSUE THREAD

**Issue by lusiwei** [NodeBB/NodeBB#6406]
- **NodeBB version:** 1.8.1
- **NodeBB git hash:** 9277eaaf00701bfd3ebb164e2fc2256f4245d766

- **Database type:** mongo
- **Database version:** v3.6.3

- **Exact steps to cause this issue:**
When I try to join a custom html, js. Then click Save to refresh my website and see the **Internal Server Error** error

- **What you expected:**
I expect to add some effect to my nodebb forum

- **What happened instead:**
After I run the **/nodebb log** command,I found the following error
```
Render failed for template <head>
  <link rel=:
 ReferenceError: Render failed for template <head>
  <link rel=:
 key is not defined
    at compiled (evalmachine.<anonymous>:10:344)
    at runtime (/home/nodebb/node_modules/benchpressjs/build/lib/runtime.js:64:16)
    at Promise.try.then.templateFunction (/home/nodebb/node_modules/benchpressjs/build/lib/compile-render.js:46:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
*  I found the following error when I visited my site
![深度截图_选择区域_20180329010843.png](https://i.loli.net/2018/03/29/5abbcc4a39369.png)

**Comment by julianlam** [comment]
Is the ACP still accessible? Then you can fix the syntax error

**Comment by pitaj** [comment]
Try running `./nodebb build` and restarting

**Comment by lusiwei** [comment]
# @julianlam 
ACP  cannot be accessed

**Comment by pitaj** [comment]
Did you try `./nodebb stop && ./nodebb build && ./nodebb stop`?

**Comment by lusiwei** [comment]
@pitaj I have tried, still useless

**Comment by julianlam** [comment]
Are you on Mongo or Redis?

**Comment by lusiwei** [comment]
@julianlam mongo

**Comment by pitaj** [comment]
First, get whatever is in your `customHTML` and `customJS` fields by opening a mongo shell (`mongo nodebb` probably) and running this:

    > db.objects.find({ _key: 'config' }, { customHTML: 1, customJS: 1, _id: 0 })

It should output something like this:

    { "customHTML" : "<html><tags><go><here>", "customJS" : "javascript.stuff(); goes.here();" }

Please provide us with the result that gets output here so we can reproduce and fix this problem.

Then clear those fields by running this:

    > db.objects.update({ _key: 'config' }, { $set: { customHTML: "<html><tags><go><here>", customJS: "javascript.stuff(); goes.here();" } })

Which should output something like this:

    WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })

Then you should be able to restart NodeBB.

**Comment by pitaj** [comment]
I just edited my post to correct this:

    > db.objects.update({ _key: 'config' }, { $set: { customHTML: "<html><tags><go><here>", customJS: "javascript.stuff(); goes.here();" } })

To this:

    > db.objects.update({ _key: 'config' }, { $set: { customHTML: "", customJS: "" } })

I want to make sure you didn't miss that in the case where you're following an email chain.
