### ISSUE TITLE
RSS feeds, redux. Threads to start with...

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#6407]
Not sure if it's my reader or NodeBB with this one, but the fact that my reader has little problem with lots and lots of other feeds, I'm going to try here first.

I have other RSS issues (subscribing to categories and subscribing to stuff that requires login,) but I'll limit reports to just this for the moment

- **NodeBB version:** TDWTF.
- **NodeBB git hash:** 

- **Exact steps to cause this issue:**
1. Subscribe to a thread: (https://what.thedailywtf.com/topic/20319.rss in my case)
2. Pointed my RSS reader ([ttrss](https://tt-rss.org/) at it.

- **What you expected:**
A single RSS item per post.

- **What happened instead:**
A single RSS item per apparent post date, but each containing the contents of the last post in the thread.

Each of these:

![image](https://user-images.githubusercontent.com/3939886/38088550-1cf642d4-3354-11e8-806e-94aeb8d6e774.png)

Contains the identical from a post from  Fri, 01 Jul 2016 01:36:03 GMT (the one highlighted it seems)

![image](https://user-images.githubusercontent.com/3939886/38088616-4e615e1c-3354-11e8-8660-91bf0b456900.png)

Links do appear to go directly to the right posts however.

**Comment by pitaj** [comment]
Ah, so it's off by one? Would you prefer the date not be included in the title or what title structure would you prefer?

**Comment by pauljherring** [comment]
Is what off by one? 

**_All_** 5 titles in the first screenshot contained the text of the second screenshot.

**Comment by pauljherring** [comment]
Is what off by one? 

**_All_** 5 titles in the first screenshot contained the text of the second screenshot.

**Comment by pauljherring** [comment]
Further investigation with a random reader on the internet:

http://www.feedbucket.com/?src=https://what.thedailywtf.com/topic/20319.rss&start=0

Latest post there (4-Jul-16) matches with the latest post in TTRSS (the penultimate post is the one in the screenshot above) - latest post at the time of writing on that thread is 30-Mar-18. 9379 posts in the thread.

**Comment by pauljherring** [comment]
Further investigation with https://what.thedailywtf.com/topic/20884.rss which Firefox is able to make something of, but TTRSS refuses to accept by being stricter (using https://fakecake.org/myfeedsucks/):

![image](https://user-images.githubusercontent.com/3939886/38143531-d46272f0-3438-11e8-8ba0-07a63aae7c62.png)

**Comment by barisusakli** [comment]
Is this still an issue? Can you check with https://community.nodebb.org/topic/15078.rss

**Comment by pauljherring** [comment]
Testing with a few of my own from TDWTF... I'll report back.

I don't, however, be able to able to subscribe to feeds that require one to be logged in even when using URLs of the form https://what.thedailywtf.com/topic/24143.rss?uid=16&token=<uuid> (taken from the RSS icon at the top of the page.)

**Comment by pauljherring** [comment]
> https://what.thedailywtf.com/topic/24143.rss?uid=16&token=[uuid] 

In fact, going to that URL (with the UUID supplied) in a private browser window takes me to the login page.

**Comment by pauljherring** [comment]
Another: https://what.thedailywtf.com/topic/16270.rss (publicly available)

Feed only (at least intially) shows the first (oldest) 26 posts, most recent dated `<pubDate>Thu, 04 Jun 2015 17:25:32 GMT</pubDate>`

The most recent post on that thread (currently) is today (18th Nov 06:49) - 4601 posts later.

I'd expect the most recent X posts to be on the feed.

**Comment by barisusakli** [comment]
@pauljherring thanks for testing, I have fixed both issues. tokens should work with private categories again and the feed should display the latest replies instead of oldest.
