### ISSUE TITLE
Upgrading with Docker?

### ISSUE THREAD

**Issue by poVoq** [NodeBB/NodeBB#6417]
Somehow it doesn't work to upgrade NodeBB when running through Docker.

I have a working 1.7.5 installation with Redis as the database, but when I re-create the docker image using the latest or latest:1.8.x images the dashboard keeps on saying that I have 1.7.5 instead of 1.8.1 installed.

I also tried to follow this:
https://docs.nodebb.org/configuring/upgrade/
i.e. "./nodebb upgrade"
inside the docker image (which really should not be the correct docker way) and while it does seem to upgrade some plugins etc. the dashboard keeps insisting that I am on version 1.7.5.

Any idea what could be causing this? Thanks for the help.

**Comment by julianlam** [comment]
Can you paste the output of `./nodebb upgrade`? Did you check out v1.8.x?

**Comment by poVoq** [comment]
Yes, I checked out v.1.8.x

output is here:
https://pastebin.com/4MAEweQY

thanks for looking into it.

**Comment by margussipria** [comment]
Last time I had problem upgrading I asked [here](https://community.nodebb.org/category/16/technical-support), I think you can receive help more quickly there, but lets try here.

When you are upgrading to newest version, how did you switch to use new version? I  did same think yesterday (with my own docker images, so if they build 1.7.5 and tagged it with 1.8.2 then there could be issue).

If you used outside volumes for config and uploads you can do this:
1. stop instance `docker stop nodebb` (name of container)
2. setup to new version by accessing setup
3. (delete stopped container)
4. create new container with same name (or new name if you want to leave that one for backup) **using original volumes and links**! 

If all the content is in docker container, you have to either export it from container to volume or do git dance by fetching new tag and running npm install in that container, your output it self does not give any clue which version of container you are actually running. `Updating NodeBB...` **SHOULD** have previous version number and new version number for helping out.

**Comment by poVoq** [comment]
Yes, completely recreating the container but using permanent volumes is what I am doing. That is what makes this error so strange.

**Comment by LeonAppDev** [comment]
> Just saw this issue. What I'm doing is creating my own docker image and I have an `entrypoint.sh` for it.
> 
> `entrypoint.sh`
> 
> ```shell
> #!/bin/bash
> 
> set -Eeuo pipefail
> 
> if [ -f /data/config.json ]; then
>     /data/nodebb upgrade -sb
> fi
> 
> exec "$@"
> ```
> 
> And my `Dockerfile` at the moment:
> 
> ```dockerfile
> FROM node:8
> 
> ENV NODE_ENV=production \
>     daemon=false \
>     silent=false
> 
> WORKDIR /data
> COPY entrypoint.sh /data
> 
> RUN wget https://github.com/NodeBB/NodeBB/archive/v1.9.3.tar.gz \
>     && tar xzf v1.9.3.tar.gz --strip-components 1 \
>     && rm v1.9.3.tar.gz \
>     && cp /data/install/package.json /data/package.json \
>     && npm install \
>     && npm install nodebb-plugin-cppnet-markdown \
>                    nodebb-plugin-cppnet-solr \
>                    nodebb-plugin-ban-privileges \
>                    nodebb-plugin-math-captcha \
>                    nodebb-plugin-emoji-one \
>                    nodebb-plugin-gdpr \
>     && npm cache clean --force \
>     && chmod +x /data/entrypoint.sh
> 
> ENTRYPOINT [ "/data/entrypoint.sh" ]
> CMD [ "node", "loader.js" ]
> 
> # the default port for NodeBB is exposed outside the container
> EXPOSE 4567
> ```
> 
> It is still not perfect, but it works. And I can just generate a new Docker image and replace it on the server. The `entrypoint.sh` will make sure to upgrade the database and build the templates. It also won't try to look for updated plugins and thus wait for input during startup, because NodeBB ask the administrator during startup if the plugin upgrade should be done.
Thanks for sharing, I will have a try later

**Comment by loversama** [comment]
Thanks for the solutions posted, can we please get an "Auto Upgrade" I can't imagine a situation whereby we would want to manually press yes to each upgrade on this list or at lest have it so nodebb still starts with the old plugin rather then just hanging the script..

> > Just saw this issue. What I'm doing is creating my own docker image and I have an `entrypoint.sh` for it.
> > `entrypoint.sh`
> > ```shell
> > #!/bin/bash
> > 
> > set -Eeuo pipefail
> > 
> > if [ -f /data/config.json ]; then
> >     /data/nodebb upgrade -sb
> > fi
> > 
> > exec "$@"
> > ```
> > 
> > 
> > And my `Dockerfile` at the moment:
> > ```dockerfile
> > FROM node:8
> > 
> > ENV NODE_ENV=production \
> >     daemon=false \
> >     silent=false
> > 
> > WORKDIR /data
> > COPY entrypoint.sh /data
> > 
> > RUN wget https://github.com/NodeBB/NodeBB/archive/v1.9.3.tar.gz \
> >     && tar xzf v1.9.3.tar.gz --strip-components 1 \
> >     && rm v1.9.3.tar.gz \
> >     && cp /data/install/package.json /data/package.json \
> >     && npm install \
> >     && npm install nodebb-plugin-cppnet-markdown \
> >                    nodebb-plugin-cppnet-solr \
> >                    nodebb-plugin-ban-privileges \
> >                    nodebb-plugin-math-captcha \
> >                    nodebb-plugin-emoji-one \
> >                    nodebb-plugin-gdpr \
> >     && npm cache clean --force \
> >     && chmod +x /data/entrypoint.sh
> > 
> > ENTRYPOINT [ "/data/entrypoint.sh" ]
> > CMD [ "node", "loader.js" ]
> > 
> > # the default port for NodeBB is exposed outside the container
> > EXPOSE 4567
> > ```
> > 
> > 
> > It is still not perfect, but it works. And I can just generate a new Docker image and replace it on the server. The `entrypoint.sh` will make sure to upgrade the database and build the templates. It also won't try to look for updated plugins and thus wait for input during startup, because NodeBB ask the administrator during startup if the plugin upgrade should be done.
> > Thanks for sharing, I will have a try later

Thanks for the solutions posted, can we please get an "Auto Upgrade" I can't imagine a situation whereby we would want to manually press yes to each upgrade on this list or at lest have it so nodebb still starts with the old plugin rather then just hanging the script..
