### ISSUE TITLE
Bug Replying to Forum Posts - Position of Toolbar/Editor Based on Reply

### ISSUE THREAD

**Issue by TroikaTronix** [NodeBB/NodeBB#6418]
- v1.8.1
- **NodeBB git hash:** - a9f574de6a566a58b24d126b44a56718d181e989 (unsure if this is correct because I'm not the expert..  we downloaded the 1.8.1 build released a few days ago)
- **Database type: mongo
- **Database version:db version v3.2.19
- **Exact steps to cause this issue:**
1) Open a forum post that has several replies.
2) Go to the bottom post, hit reply. The toolbar/editor will either be off the screen or unusable.
3) Refresh the page to start over.
4) Scroll up to the first post
5) Hit reply
6) The toolbar/editor will be usable. Click Discard to close the reply
7) Scroll to the second post.
8) Hit reply
9) The toolbar/editor may be usable, but will be further up the screen.

- **What you expected:**

I expected to be able to reply to the post regardless of which post in a thread I replied to.

- **What happened instead:**

The reply editor and/or toolbar is either off the screen or unusable

Here is a screen capture when replying to the first post:
https://troikatronix.com/files-temp/nodebb-reply-to-first-post.png

Here is a screen capture after scrolling down a bit and replying to the second post:
https://troikatronix.com/files-temp/nodebb-reply-to-second-post.png

Here is a screen capture when replying to the last post:
https://troikatronix.com/files-temp/nodebb-reply-to-last-post.png

**Comment by barisusakli** [comment]
Seems fine on composer-default so seems like only effecting redactor?

**Comment by julianlam** [comment]
I was just thinking the same... will try to reproduce.

**Comment by TroikaTronix** [comment]
Would be great to have a solution for this. It's affecting a lot of users, as you can see in these links. (https://community.troikatronix.com/topic/5144/new-forum-issues/5, https://community.troikatronix.com/topic/5131/forum-update-everyone-please-read/19)

By the way, there is a workaround. It goes like this:

1) Hit reply button... editor fills the frame.
2) Hit the little red button with the "speech balloon" and three dots to hide the reply
3) Scroll to the first post
4) Hit the red button again
5) Now you can successfully enter text, apply formatting, etc.

**Comment by TroikaTronix** [comment]
FYI, we just installed v1.8.2 and it did not solve this issue.
