### ISSUE TITLE
Deleted chat message isn't instantly deleted in recipient chat

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6422]
When deleting a chat message, the recipient message is not deleted until a page refresh or switching chat message windows. 

Also the teaser content in recent rooms list isn't updated if it was the last message sent that was deleted.

Is this by design?

**Comment by mohammadhassan99** [comment]
@uplift Yeah, also I made a gif about it here 👇 
https://github.com/NodeBB/NodeBB/issues/6192
