### ISSUE TITLE
Characters like £ and ' come out like :undefined:’:undefined:

### ISSUE THREAD

**Issue by Starystars67** [NodeBB/NodeBB#6428]
- **NodeBB version:** 1.8.2
- **NodeBB git hash:** 29b7af80f5248bad0b91631807a424b8314e6d0e

- **Database type:** Mongo
- **Database version:** 3.6.2

- **Exact steps to cause this issue:** Create a post that contains a single ' for something like I'm or use currency like £1 then click post and bam you end up with I:undefined:’:undefined:m or :undefined:£:undefined:1

- **What you expected:** i expected I'm and £1

- **What happened instead:** i got I:undefined:’:undefined:m or :undefined:£:undefined:1

**Comment by julianlam** [comment]
https://community.nodebb.org/topic/12164/testing-some-odd-character-stuff :frowning: 

Unfortunately cannot reproduce.

**Comment by Starystars67** [comment]
On my previous version (1.8.0) the issue was not there if that helps and here is a list of plugins
"nodebb-plugin-composer-default": "6.0.19",
    "nodebb-plugin-dbsearch": "2.0.13",
    "nodebb-plugin-emoji": "^2.2.0",
    "nodebb-plugin-emoji-android": "2.0.0",
    "nodebb-plugin-markdown": "8.4.2",
    "nodebb-plugin-mentions": "2.2.4",
    "nodebb-plugin-soundpack-default": "1.0.0",
    "nodebb-plugin-spam-be-gone": "0.5.3",

**Comment by julianlam** [comment]
Try also running `./nodebb build && ./nodebb restart`

**Comment by Starystars67** [comment]
Feel a little stupid now, issue seems to be with that emoji plugin I had so ill go over to them and report. Thanks for your time I unintentionally wasted
