### ISSUE TITLE
GDPR Info Page (Administrators)

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6429]
For administrator reference, a page in the ACP would be helpful to show compliance and collected information:

* [ ] List of all data kept (e.g. all user profile fields)
* [ ] List of all data stores (redis or mongo, db store host IP address)
* [ ] Link to nodebb.org privacy policy

**Comment by FaizanZahid** [comment]
Very nice to have , especially after facebook's data issue :)

**Comment by julianlam** [comment]
This is not needed for GDPR compliance, I have decided... unless someone can give me a reason for it.

Consent form during registration + appropriate user tools should be sufficient.
