### ISSUE TITLE
Data collection consent on user registration

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6432]
Strict consent should be given by the user upon registration.

* Registration interstitial to store consent in user hash:
    * [x] ... for data collection
    * [x] ... for email notifications
* [x] Detail where these settings can be modified (specifically email notifications)
* [x] Display current digest setting value (system default)
* [x] Deny registration if no consent / Save consent values to database

**Comment by paviro** [comment]
I just updated to the latest version. Is there anyway to force existing users to consent before they are allowed to continue to use the forum?

**Comment by julianlam** [comment]
Hello @paviro -- because we don't want to make the change too jarring for existing forums looking to upgrade, we don't present the consent pages to existing users, although they can always do so via the "Your Rights & Consent" page in their user profile pages.

In advance of the GDPR deadline, we'll create an optional plugin that will allow administrators to toggle a forced check on login, so that existing users can provide their consent before continuing to use the forum.

**Comment by paviro** [comment]
The plugin sounds perfect thank you! Will there be a way to sort users after consent state on the user admin page?

**Comment by julianlam** [comment]
Yes, that's the idea. You'd be able to view and download a list of all users who have/have not consented.

Should a site want to become GDPR compliant, they may have to elect to delete all users who have not consented. Obviously not the most ideal solution, though we present the option to be thorough.

**Comment by johnmanko** [comment]
https://retropie.org.uk/forum/topic/18187/this-community-forum-collects-and-processes-your-personal-information-wont-stop-popping-up/8

> Article 4(11) states:
> 
>     ‘consent’ of the data subject means any freely given, specific, informed and unambiguous indication of the data subject's wishes by which he or she, by a statement or by a clear affirmative action, signifies agreement to the processing of personal data relating to him or her;
> 
> Article 7(4) states:
> 
>     When assessing whether consent is freely given, utmost account shall be taken of whether, inter alia, the performance of a contract, including the provision of a service, is conditional on consent to the processing of personal data that is not necessary for the performance of that contract.
> 
> Finally, Recital 43 states:
> 
>     Consent is presumed not to be freely given if it does not allow separate consent to be given to different personal data processing operations despite it being appropriate in the individual case, or if the performance of a contract, including the provision of a service, is dependent on the consent despite such consent not being necessary for such performance.
> 
> By blocking access via a tracking wall until consent is given, this forum may be violationg the cited articles of the GDPR.
