### ISSUE TITLE
Ability to download all user contributions (user readable and machine readable variants)

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6441]
The GDPR lists two rights, the **Right to Access** and the **Right to Data Portability**.

In both cases, an export of:
* [x] all posts in CSV format
* [x] an archive of all uploaded images
* [x] A CSV file containing their user profile data and settings

... should suffice.

* [x] Integrate into Your RIghts & Consent page

**Comment by FaizanZahid** [comment]
This is a very good thing to have , just like facebook download user's data tool :)
