### ISSUE TITLE
Open Graph Image URL is not correct, when installed at subpath

### ISSUE THREAD

**Issue by winfredkqin** [NodeBB/NodeBB#6442]
- **NodeBB version: 1.7.5
- **NodeBB git hash:  87c5dd34ea0171ac295bbf3c8d73c68076bc5c57

- **Database type:** mongo
- **Database version: 3.2.11 

I've installed NodeBB at:
https://forum.unbelievable.sale/zh-Hans/

After uploaded a image (1200x630 according to FB suggestion) via Admin -> Settings -> General -> og:image

I found the image is not showed in FB sharing. I've checked with the front-side source code, then found:

```
<meta property="og:type" content="website" />
<meta property="og:title" content="谜之折扣" />
<meta property="og:url" content="https://forum.unbelievable.sale/zh-Hans/zh-Hans/" />
<meta property="og:description" content="「谜之折扣」论坛 (Unbelievable.SALE Forum) 是一个由用户驱动的本地商家打折信息分享社区。由香港简繁商务 (Leismore Ltd.) 运营。" />
<meta property="og:image" content="https://forum.unbelievable.sale/zh-Hans/zh-Hans/assets/uploads/system/og-image.jpeg?v&#x3D;1523270837274" />
<meta property="og:image:width" content="200" />
<meta property="og:image:height" content="200" />
```
The og:image URL is not set properly:

`https://forum.unbelievable.sale/zh-Hans/zh-Hans/assets/uploads/system/og-image.jpeg?v&#x3D;1523270837274`

Should be:

`https://forum.unbelievable.sale/zh-Hans/assets/uploads/system/og-image.jpeg?v&#x3D;1523270837274`

And also, the og:image:width and og:image:height are fixed to 200px, which is not correct. Please give us an option to set it manually or set according to actual image size.

My request:

- Hope the URL issue could be fixed
- Hope width & height could be set by user or set according to image actual size

Currently:

- og:image URL is not correct
- og:image:width / height is not correct

Thanks for your wonderful work! Love NodeBB!

**Comment by julianlam** [comment]
The addition of the height/width can be found via #5404, seems to have been some stub code that was left incomplete.
