### ISSUE TITLE
Allow to use Promise as a type of hook method.(Also Support Callback)

### ISSUE THREAD

**Issue by a632079** [NodeBB/NodeBB#6444]
ES6 brinsg `Promise`, a syntactic sugar of callback-function, support more friendly error handler without dropping handing stack.
For example,
```
Promise.resolve(1)
  .then(d => {
    throw new Error("crash")
  })
  .catch(e => {
     console.log("can catch err, without dropping stack. %s", e.message)
  })
```
A suggested method:
```
class A {
  static getUser(params) {
    return new Promise((ok, err) => {
       // handle
    })
  }
  static async getData(params) {
     return data
  }
}
module.exports = A
```
A common method:
```
module.exports = {
  getUser: (params) => {
    return new Promise((ok, err) => {
      // handle
    })
  }
  getData: async (params) => {
    // handle
  }
}
```
We might can support it via `typeof` and `method.length`

**Comment by a632079** [comment]
Oh, I think it's good use of Promise that use `global.Promise = require('bluebird')`

**Comment by a632079** [comment]
@julianlam 😄  Promise is also a good-future way, right? Although, it's just a sugar of callback.
I perfer true async which is depended on coroutine (Like `fibjs`) , not native Promise.
But Nodejs and ES haven't thought those now. `Callback` is more faster than `Promise/AsyncFunction`.
`Promise` is created to solve callback hell, without deeper design to become faster.

even so, i think it is a `enhancement` edition to NodeBB, to better error handing

**Comment by julianlam** [comment]
Ha! Don't get me started on the purported use case of promises to *solve* callback hell. One can easily argue that `async.waterfall` already adequately solves this problem...!

**Comment by pitaj** [comment]
Just FYI, by supporting async/await you are supporting promises and vice versa. 

There's a connect or express middleware that enables support for promises there. We would need to support promises in hook handlers and maybe socket handlers, though.

**Comment by pitaj** [comment]
Also, async/await is shipped currently in Node 8.

**Comment by a632079** [comment]
😸 I don't mean let NodeBB rewrite All Part with `Promise` . Might it's better to use `util.callbackify` to combility with asyncFunction/Promise

**Comment by a632079** [comment]
![](https://i.imgur.com/DjN38H6.png)
