### ISSUE TITLE
npm install failure.

### ISSUE THREAD

**Issue by XRealismX** [NodeBB/NodeBB#6451]
cd /opt/nodeBB
ls
app.js      Gruntfile.js  LICENSE    logs    nodebb.bat    public     src
Dockerfile  install       loader.js  nodebb  node_modules  README.md  test
npm install
..................] / normalizeTree: sill install loadCurrentTree

[              ....] | fetch: sill doParallel fetch 0

npm WARN enoent ENOENT: no such file or directory, open '/opt/nodeBB/package.json'
npm WARN nodeBB No description
npm WARN nodeBB No repository field.
npm WARN nodeBB No README data
npm WARN nodeBB No license field.

**Comment by pitaj** [comment]
What installation instructions are you using?

**Comment by XRealismX** [comment]
https://www.vultr.com/docs/how-to-install-nodebb-on-centos-7

**Comment by XRealismX** [comment]
I am using digital ocean I tried the nodebb installation instructions and I had no luck.

**Comment by julianlam** [comment]
Please use the installation instructions on https://docs.nodebb.org

**Comment by pitaj** [comment]
DigitalOcean uses Ubuntu, so you should be able to use [the official install docs](https://docs.nodebb.org/installing/os/ubuntu/)

**Comment by XRealismX** [comment]
This is what happens when I type `sudo apt-get install -y mongodb-org` its on the installation instructions.


```
root@ubuntu-s-1vcpu-1gb-nyc1-01:~# sudo apt-get install -y mongodb-org
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package mongodb-org
root@ubuntu-s-1vcpu-1gb-nyc1-01:~#
```

**Comment by XRealismX** [comment]
That part worked

**Comment by pitaj** [comment]
Would you mind providing the full output of those commands?

**Comment by XRealismX** [comment]
Oh I did not know the sudo tee was connected

**Comment by XRealismX** [comment]
I just did it like this
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse"

**Comment by pitaj** [comment]
Oh, yes, you have to pipe it into tee

**Comment by XRealismX** [comment]
I will see if it works

**Comment by XRealismX** [comment]
I am not sure how to configure to nginx b/c I want to link it to my domain I own.

**Comment by pitaj** [comment]
Please bring other config-related questions to https://community.nodebb.org

**Comment by pitaj** [comment]
Please bring other config-related questions to https://community.nodebb.org
