### ISSUE TITLE
Ability to auto suggest users and topics in private chat by appending with @ sign 

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6454]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

So basically if the user just like they're able to mention other users while making topics even within private chat sometimes we need to link Andre forever uses when we are chatting to another person so they should be like in auto suggestion for usernames when we type at symbol @ and then user for e.g

I m chatting with Alex.

Alex want to learn about canada. And I know a person who is from canada Tina-canadian.

So I can reply Alex as contact @tina-canadian she is from canada and can help u.

Similarly users should be able to to suggest topics from topic titles within private chat.

**Comment by mohammadhassan99** [comment]
@FaizanZahid 
Yeah it's useful 👌 👍
