### ISSUE TITLE
/api/search -  Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by victorelec14** [NodeBB/NodeBB#6457]
- **NodeBB version:** v1.8.2
- **NodeBB git hash:** 

- **Database type:** redis
- **Database version:**  3.2.10

- **Exact steps to cause this issue:**
	1. click on the Search Button ( nodebb/search )        

- **What you expected:** 
 - Nothing :) 

- **What happened instead:**

![image](https://user-images.githubusercontent.com/543450/38778211-12482f5e-40b6-11e8-840d-2f1fbab963ab.png)

**Comment by victorelec14** [comment]
nodebb/api/search?_=1523793995776
`{
"path": "&#x2F;api&#x2F;search",
"error": "Cannot read property 'length' of undefined"
}
`

**Comment by barisusakli** [comment]
https://github.com/barisusakli/nodebb-plugin-dbsearch/issues/39
