### ISSUE TITLE
[New feature] Post Queue Preview

### ISSUE THREAD

**Issue by victorelec14** [NodeBB/NodeBB#6458]
maybe is better a Post Queue Preview function, on mobile version have you a very big Scroll and in desktop is only unformatted text and sometimes i don't understand the new post.

![image](https://user-images.githubusercontent.com/543450/38778297-29bf35c2-40b8-11e8-8f4a-e95a6dfe3162.png)

thanks

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/6528
