### ISSUE TITLE
Multiple users with same username/email

### ISSUE THREAD

**Issue by SaitDev** [NodeBB/NodeBB#6459]
- **NodeBB version:** 1.8.2
- **NodeBB git hash:** 29b7af80f5248bad0b91631807a424b8314e6d0e

- **Database type:** mongo
- **Database version:** 3.4.13

- **Exact steps to cause this issue:**
User registered them, so I dont have exactly steps
- **What you expected:**
Prevent creating new account with exist username or used email

- **What happened instead:**
Some accounts were registerd with same email address, 2 of them has same username

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/8291
