### ISSUE TITLE
Hooks wiki page not updated?

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6461]
While browsing the hooks I noticed that it seems the page hasn't been regenerated since at least Jun 2, 2017. They point to wrong lines and I'm kind of expecting that some are missing or deprecated? Would be nice if this would be fixed.

**Comment by Dravere** [comment]
Seems someone updated it? Thank you! Really helpful to have up-to-date hooks page for plugin development.

Not sure if this issue can be closed? Is the auto generation still not working and it was just a manual update and this issue tracks now this? So I'm not closing it yet. Feel free to do with it, whatever you deem correct :smile:

**Comment by julianlam** [comment]
I believe @psychobunny brought the daemon up again.

**Comment by WPF-ZzZz** [comment]
https://github.com/NodeBB/NodeBB/wiki/Hooks -> some of hooks return 404

**Comment by psychobunny** [comment]
Thanks, will look into this

**Comment by psychobunny** [comment]
Should be good now :)
