### ISSUE TITLE
Add user blocking tools to NodeBB core

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6463]
Quite a heavily sought-after feature that is not well-served by existing plugins, a decision was made to bring this functionality into core.

**Comment by FaizanZahid** [comment]
In case you missed my last reply, posting here again:

Many Thanks for your responses. Here are my thoughts:

Current Problems:

Some users are racist and abuse other users, or use the voting system abusively to massively downvote others. if they get into a fight with some other user. This causes other good normal users to leave the site after seeing so much hatred ness and fights on the forum.

Solution:

All the top forums and sites like Fb, reddit solves this by having user blocking/ignoring feature.

Here is what the use case i think should be:

If I have blocked a user named e.g john, =>

I should not be able to see his topics, posts, profile, his messages in shoutbox. (That user should be non-existent to me on the forum.

Vice versa, If I have blocked John, John should not be able to see my profile, my shoutbox messages, my posts, topics, etc.

To prevent people from misusing and blocking too much other users, we can have something like what facebook does:

Once you have blocked a user, you need to wait atleast 24 hours before you can unblock them. (Better if we can change that timer in ACP)
You need a min of some reputation threshold to be able to block users. (Should be editable in ACP)
These are just my ideas, i know some things may not be possible technically, but if we are able to achieve a simple user blocking functionality by which one can block another user and then does not see his content or profile (vice versa) then I think that would be grand and can reduce hatred, bullying and racism from our forums :)

PS: Great work on introducing it in core.

**Comment by FaizanZahid** [comment]
Also, one more thing I thought was,

Users should not be able to block admins. Or may be they can ban some mods and not all moderators?

But I think they should be able to block a number of moderators but not all of them.

**Comment by FaizanZahid** [comment]
U can see users feedback here as well https://chatrooms.talkwithstranger.com/topic/15680/tws-user-block-feature-to-be-introduced-soon/2

**Comment by julianlam** [comment]
Thanks @FaizanZahid -- will take some of those suggestions into consideration. Makes sense not to be able to blocks admins/mods :smile:

**Comment by fais3000** [comment]
Fantastic guys. This'll be quite helpful!

**Comment by julianlam** [comment]
> Once you have blocked a user, you need to wait atleast 24 hours before you can unblock them. (Better if we can change that timer in ACP)

Just wondering what this accomplishes... the way we do blocking, it's more like a visibility filter, the end user doesn't _know_ they're blocked.

**Comment by FaizanZahid** [comment]
@julianlam  Basically that is how the Facebook block mechanism works.

I'll explain why it is supposed to work like that.

but i need to understand what do you mean by viibility filter? How can i test the use case of the block feature in action? the idea of blocking is that, if a user A is a BadHarrassingUser then other normal good users of the forum don't want to see HIS replies, his topics and/or his public chat and normal users want to hide their profiles from this BadHarrassingUser.. so it is fine if BadHarrassingUser does not know if he is blocked, but others who blocked him should have invisible presence of their profile and his profile and of their replies/topics and his replies/topics/public chat etc.

**Comment by julianlam** [comment]
User blocking tools are managed by individual users. If I don't like BadHarrassingUser, I can add him to my "blocks" list (via /me/blocks) and I will no longer see his posts or access his profile, nor can he send me chat messages.

To my knowledge, that user will not know they are blocked, they simply will not be receiving any responses from you as you won't know they are talking to you :smile:

**Comment by FaizanZahid** [comment]
Thanks Julian, after testing the block feature here are my thoughts after discussing with our users too:

1. When we have blocked a person everything seems to work fine , DM, topics, and posts. but we can still see a that user chatting the shoutbox. i think there should be option to hide or show this banned user chat in shoutbox?
2. when a user is blocked by me, and he sends me a message, i still get a notification of this new DM, though there is no content in the msg itself but the chat notification remains. so may be needs to be fixed?

**Comment by julianlam** [comment]
#6514 

Shoutbox integration is up to the plugin authors to integrate with blocking tools.
