### ISSUE TITLE
Please add mentions to default notification settings

### ISSUE THREAD

**Issue by juan-g** [NodeBB/NodeBB#6465]
- **NodeBB version:** 1.8.1 
- **NodeBB git hash:** 9277eaaf00701bfd3ebb164e2fc2256f4245d766
- **Database type:** mongo
- **Database version:** 3.6.3
1. Mentions not working for new members.
   - **Exact steps to cause this issue:**
     Mention a new member.
   - **What you expected:**
     The member receives a notification.
   - **What happened instead:**
     The member doesn't receive a notification.
2. Mention notifications are disabled by default.
   - **Exact steps to cause this issue:**
     Look at the settings of any new member.
   - **What you expected:**
     Mention notifications enabled by default.
   - **What happened instead:**
     Mention notifications disabled by default.
     _When someone mentions you: None_
3. Currently no way to prevent this problem.
   - **Exact steps to cause this issue:**
     Go to **NodeBB Admin > Settings > User > Default notification settings**
   - **What you expected:**
     Options for _When someone mentions you_
   - **What happened instead:**
     No options for _When someone mentions you_

**Comment by barisusakli** [comment]
Latest should already have this.

![image](https://user-images.githubusercontent.com/2583394/39089732-e7fcedbc-459b-11e8-89c2-43091e9b4a05.png)

**Comment by juan-g** [comment]
You are right, just updated from 1.8.1 to 1.8.2 and it's there. :+1:  (I didn't update before because I didn't find it in the long list of fixed issues for [1.8.2](https://github.com/NodeBB/NodeBB/releases/tag/v1.8.2)). Thank you!

**Comment by juan-g** [comment]
Reopening. After setting default notifications for mentions, I've added a test user, still getting "None". So the new mentions setting for default notifications is not working.
