### ISSUE TITLE
50x Errors Page with Autoreload

### ISSUE THREAD

**Issue by victorelec14** [NodeBB/NodeBB#6467]
![image](https://user-images.githubusercontent.com/543450/39124222-f16d217c-46fa-11e8-9523-8637a11861ce.png)

Is maybe better when the all Server Errors (50X) have a Autoreload (5 seconds try again).

then the all visitor stay on the web and dont go ..

**Comment by victorelec14** [comment]
???

**Comment by julianlam** [comment]
Yes, the above explanation is correct, the idea is to limit reloads. The site itself is saying that there are too many connections, and it is best to try again later, not that the site is _down_, per se.
