### ISSUE TITLE
Ability to mark/move a topic/post as posted by anonymous/guest after posting it as a logged in user.

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6470]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

So they say give man a mask and he will tell you the truth!

I think it would be great to have this feature where if you have posted something as a logged in user then you should be able to go back to that topic or post from your login account and move that topic or post to be posted as anonymous user or from a guest account ....

for example if you no longer want your yourself to be associated with that topic but you think that the discussion was really good and u dont want to delete that topic but you decide to make the topic as anonymous instead of being associated with your login username..

so the topic still remains but all your replies and posts in that topic/posts get converted as if they were posted from a guest account.

This will be a cool feature to give users 100% anonymity whenever they feel like.

On top of this I also think that the logged in users should also be able to post a topic as a anonymous or guest user even when they're logged in from their accounts.

Currently a logged in user has to explicitly log out and post a topic as a guest in the anonymous guest category and then log back in to use the forum normally.

**Comment by pauljherring** [comment]
>On top of this I also think that the logged in users should also be able to post a topic as a anonymous or guest user even when they're logged in from their accounts.
>
> Currently a logged in user has to explicitly log out and post a topic as a guest in the anonymous guest category and then log back in to use the forum normally.

Or open a private browser window/multi-account container, where none of that is necessary.

**Comment by julianlam** [comment]
Hi @FaizanZahid I believe this is best served as a plugin as the potential use case for it is small and does not justify the development and maintenance.
