### ISSUE TITLE
Increase the pagination count for /recent and .popular pages

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6474]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

For e.g if you guys goto https://chatrooms.talkwithstranger.com/recent?page=10

it says no topics, and if we go on https://chatrooms.talkwithstranger.com/recent

and see at bottom u will see it only shows pages till page number 7. This is causing Google to  crawl empty page and hence give us Ads warning that page has no content.

How can we increase node bb pagination count so that it still shows older topics on ]
https://chatrooms.talkwithstranger.com/recent?page=8
https://chatrooms.talkwithstranger.com/recent?page=9
https://chatrooms.talkwithstranger.com/recent?page=10
https://chatrooms.talkwithstranger.com/recent?page=11
https://chatrooms.talkwithstranger.com/recent?page=12

and so on....

right now it says no content on those pages, but in reality we do have content.

also if we see https://chatrooms.talkwithstranger.com/popular?page=2 or whatever page as logged out user, it always shows the content of the first page i.e https://chatrooms.talkwithstranger.com/popular

**Comment by pauljherring** [comment]
Isn't the whole point of those pages that they show posts that actually _are_ recent/popular?

**Comment by pitaj** [comment]
I believe the sitemap is supposed to handle exposing those other pages. Is that not happening?

**Comment by pauljherring** [comment]
> older topics

Well, yes. They aren't recent, so shouldn't be on something called "recent." 

Aren't there other routes to whatever it is you want indexing, like - say - Categories, or Tags?

> reddit front page or google homepage

They don't claim to be 'recent' - they're more of an index. Like Categories.
