### ISSUE TITLE
Different language settings for ACP doesn't stick

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6476]
- **NodeBB version:** 1.8.2
- **Database type:** mongo
- **Database version:** 3.6.3
- **Exact steps to cause this issue:**
  1. Be an administrator
  1. Go to your profile settings
  1. Change the language for the ACP to another than your default one. I for example have as default de and tried to set the ACP to en-US
  1. Go to the ACP and notice that it is a mess of both languages already in the dashboard. The title is German, some text and buttons English, menus are English, the captions of "Active Users" is German, etc.
  1. Navigate to a settings page (e.g. Settings -> General)
  1. Notice it is German
  1. Hit F5
  1. Notice it is English
  1. Navigate to the same settings page again
  1. Notice it is German
- **What you expected:** That the ACP would be English if I have the settings set to English.
- **What happened instead:** A huge mess between my main language and the ACP language.

**Comment by Dravere** [comment]
@barisusakli After testing this, it works much better now. But there are still some oddities. So it isn't entirely fixed. Some examples (default language is de, ACP is set to en-GB):

* In the Dashboard nearly everything is en-GB. Only in the box "active user" the title is in en-GB but the captions below the numbers are in de.
* When I go to manage the privileges, by default everything is en-GB. But when I change a privilege parts of the page become de. The buttons become de, the text at the bottom becomes de and the privilege categories (viewing privileges, posting privileges, moderation privileges) become de.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/6546
