### ISSUE TITLE
Admins unable to change user emails.

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6478]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

Please see details here https://community.nodebb.org/topic/12276/admins-unable-to-change-user-emails/3

**Comment by barisusakli** [comment]
I believe this was fixed here https://github.com/NodeBB/NodeBB/pull/6445 @pitaj

**Comment by FaizanZahid** [comment]
i think emails are more imp then usernames, because if users put a wrong email to register and later we turn on email confirmation, they can no longer change their email to use the forum.

**Comment by barisusakli** [comment]
@pitaj Yeah both use the same method https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/user/profile.js#L18
