### ISSUE TITLE
Unable to remove/kick user from chat room

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6479]
https://community.nodebb.org/topic/12279/unable-to-remove-users-from-within-a-chatroom-after-creating-the-room-as-owner

Looks like it was forgotten when chat UI was redone.

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/39439355-4b1c863e-4c75-11e8-95dd-23dae38afbf4.png)

**Comment by FaizanZahid** [comment]
Thanks for the fix!

**Comment by fais3000** [comment]
@julianlam Noticing a weird bug here. Chat owner is unable to see kick list 

Steps to replicate on version (1.9.3).

1. Create a chat group
2. Invite few people
3. Remove one of the person, through the kick button
4. Refresh the page. 
5. Go to users list on chat. 
6. Can't see the kick button.

On the same topic we've some other chat sessions with owner who left the chat, current users are unable to edit room name or kick any one. Even forum administrator is unable to do any change. Which brings me to final question. Is there a way from database to directly set permissions to chat session/group id to another user or delete a chat group?

Thanks

**Comment by julianlam** [comment]
:point_up:
