### ISSUE TITLE
Accidentally deleted guests group

### ISSUE THREAD

**Issue by eshohet** [NodeBB/NodeBB#6481]
- **NodeBB version:** Latest
- **NodeBB git hash:** 9d0802edd36f531fdd3803972ccfcc2d4522d27f

- **Database type:** redis
- **Database version:** not relevant

- **Exact steps to cause this issue:**

Start a new forum
Rename "guests" to "guests2"
Delete guests2

Guests now can't see any forums posts

**Comment by aStonedPenguin** [comment]
This is why groups shound't be hard coded.

**Comment by pitaj** [comment]
Can you add the group back by creating `guests3` and renaming it to `guests`?

**Comment by eshohet** [comment]
Yes, but that won't solve the problem of guests not being able to see any
posts.

**Comment by pitaj** [comment]
Have you checked the privileges to see if the group has those privileges?

**Comment by eshohet** [comment]
I'm not exactly sure how to do that, I was able to resolve this issue using the spider migration script (with some modifications). Is there a way to see what groups have what permissions in the ACP?

**Comment by pitaj** [comment]
Yeah you go to Manage > Privileges I think.

**Comment by eshohet** [comment]
Never saw that menu item before! There's only chat, upload files, and upload images.

How does one enable reading of categories & topics?

**Comment by julianlam** [comment]
There is a dropdown menu at the top right where you can adjust privileges for each category :smile:

**Comment by pitaj** [comment]
There's a drop-down at the top right I think, where you can select a category for which you select privileges.

**Comment by eshohet** [comment]
Damn, never would have guessed that. Awesome, thank all of you for the help!

**Comment by barisusakli** [comment]
guests group shouldn't be visible in the UI, where did you delete it?

**Comment by eshohet** [comment]
Hmm, in Manage > Groups.

I don't see guests here anymore. I must have created the group myself first, then renamed it, then deleted it, then tried to remake it and it failed.

My apologies for not remembering the initial flow I went through to encounter this bug.

**Comment by barisusakli** [comment]
@eshohet thanks, that narrows it down.
