### ISSUE TITLE
v1.9.0: Word "false" appears at the bottom when reloading

### ISSUE THREAD

**Issue by juan-g** [NodeBB/NodeBB#6484]
- **NodeBB version:** v1.9.0 
- **NodeBB git hash:** 136aa65d1bc8f5b7564b03df1ecef6de542662b0
- **Database type:** mongo
- **Database version:** v3.6.3
- **Exact steps to cause this issue:**
	1. Reload (with e.g. F5 or Ctrl+R) any forum page on v1.8.2: It's OK.
	2. Upgrade to v.1.9.0.
	3. Reload any forum page.
- **What you expected:** Page OK as before.
- **What happened instead:** The word "false" appears at the bottom of the page when reloading.

**Comment by barisusakli** [comment]
What is your persona version? `npm ls nodebb-theme-persona` ?

**Comment by juan-g** [comment]
```
nodebb-theme-persona@9.0.3 
```

**Comment by julianlam** [comment]
Does the problem go away if you `./nodebb build tpl` and reload NodeBB? We can't reproduce it here.

**Comment by barisusakli** [comment]
@juan-g FYI that false was removed here https://github.com/NodeBB/nodebb-theme-persona/commit/1b1ec220f079eb60fccd5535a4d7ba159e85423b#diff-ce16d4659e7701391a1f4b4b3f908cb5, so make sure your footer.tpl does not have that.
