### ISSUE TITLE
User blocking code allows you to block yourself

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6487]
... at which point you will be unable to access the user profile in order to unblock yourself :trollface:

**Comment by julianlam** [comment]
Backported to v1.9.0

**Comment by FaizanZahid** [comment]
@julianlam  hey man!

I just was trying to experiment the  block feature and i found i can block admins and global mods from my blocklist.

this shouldn't be case for sure. :)

![image](https://user-images.githubusercontent.com/9073066/39673046-1e01cae4-512d-11e8-9011-4efd20102c9c.png)

**Comment by julianlam** [comment]
The latest commits on master branch should resolve this (mods and admins will no longer be blockable)

**Comment by julianlam** [comment]
Backported to v1.9.0 now
