### ISSUE TITLE
[GDPR] New exporting features are failing with database error

### ISSUE THREAD

**Issue by paviro** [NodeBB/NodeBB#6490]
- **NodeBB version:** v1.9.0
- **NodeBB git hash:**  'cf9de8a0c7e315d9b697461b5f6cacc210019155'
- **Database type:** mongo and redis
- **Database version:** mongo (3.6.4) - redis (4.0.9)
- **Exact steps to cause this issue:**
	1. Go to the new "Your rights and consents" page
	2. Export my posts and file uploads
- **What I expected:**
Getting a file with all my posts and a valid zip file.
- **What happened instead:**
![same schema](https://user-images.githubusercontent.com/992826/39727687-02d83492-5254-11e8-8025-eb2736fbbcf2.png)
The zip file is broken as well and can't be extracted.

**Comment by julianlam** [comment]
What kind of errors do you see when you try to extract the zip file? Unfortunately that's not much to go on...

**Comment by paviro** [comment]
Sorry used the Mac Archiver and it didn't report anything helpful. Trying to extract it via the command-line it appears the file is empty:
`warning [1_uploads.zip]:  zipfile is empty`

**Comment by julianlam** [comment]
Ah okay, thanks. I'll give it a look-through.

**Comment by julianlam** [comment]
Are there any server-side logs? Unfortunately I can't reproduce the archive issue.

**Comment by julianlam** [comment]
Try adding a `console.log(files);` after this line, restarting NodeBB, and seeing what shows up when you try to download the file.

Don't forget to delete the cached file in `/build/export/` first.

**Comment by paviro** [comment]
After which line I am supposed to add the debug output?

**Comment by julianlam** [comment]
Sorry about that -- after [this line](https://github.com/NodeBB/NodeBB/blob/master/src/user/uploads.js#L38)
