### ISSUE TITLE
Error in translations for PL and RO (unclosed <strong>)

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6492]
- **NodeBB version:** latest master

There's a bug in translations for Polish (`notifications:user_flagged_post_in`) and Romanian (`groups:invited.notification_title`): instead of closing `</strong>` there is another opening `<strong>` that causes browsers to all all sort of weird stuff to correct the error. As a result the corresponding part of the forums is rendered incorrectly.

Attaching patch for clarity.

PS. Not sure if that's the right place to submit an issue with translation. If there's a better way to report it please let me know!

[Fix_unclosed_strong_in_translations__PL__RO.patch.txt](https://github.com/NodeBB/NodeBB/files/1987204/Fix_unclosed_strong_in_translations__PL__RO.patch.txt)

**Comment by barisusakli** [comment]
@attis I think fix needs to be made at transifex, https://www.transifex.com/nodebb/nodebb

**Comment by attis** [comment]
OK I *think* I fixed it in Transifex. Any way to verify?

**Comment by julianlam** [comment]
Translations are auto pulled every morning and should be available on latest master

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/dae1e26

**Comment by attis** [comment]
LGTM
