### ISSUE TITLE
Problem with template rendering after some inactivity

### ISSUE THREAD

**Issue by Gwynnbleid1** [NodeBB/NodeBB#6493]
- **NodeBB version:** 
./nodebb info

  version:  1.9.0
  Node ver: v8.11.1
  git hash: cf9de8a0c7e315d9b697461b5f6cacc210019155

  database: mongo
        version: 3.6.4
        engine:  wiredTiger

- **NodeBB git hash:** 
cf9de8a0c7e315d9b697461b5f6cacc210019155

- **Database type:** mongo or redis
mongo

- **Database version:** 
mongod --version
db version v3.6.4
git version: d0181a711f7e7f39e60b5aeb1dc7097bf6ae5856
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64

- **Exact steps to cause this issue:**
1. I have Installed 1.8 version as in install tutorial for ubuntu
2. I changed branch to 1.9 and updated using ./nodebb update option
3. Forum build and runs normally but only for some time (few hours)

IMPORTANT: for now I'm the only person using it and I have been testing forum using two accounts (one admin and one standard) using two desktop browsers (chrome and firefox) and chrome on android. 

- **What you expected:**
That it will work fine without frequent restarting

- **What happened instead:**
after sometime I get internal server error message in browser and this in log: (./nodebb log)
```
Render failed for template <footer id="footer" :
 Error: Render failed for template <footer id="footer" :
 Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at evaluate (/home/matys/nodebb/node_modules/benchpressjs/build/lib/evaluate.js:17:6)
    at precompile.then.code (/home/matys/nodebb/node_modules/benchpressjs/build/lib/compile-render.js:34:74)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-05-09T11:35:34.313Z [2078] - error: /categories
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Error: Render failed for template <footer id="footer" :
 Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at evaluate (/home/matys/nodebb/node_modules/benchpressjs/build/lib/evaluate.js:17:6)
    at precompile.then.code (/home/matys/nodebb/node_modules/benchpressjs/build/lib/compile-render.js:34:74)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Error: Render failed for template <footer id="footer" :
 Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at evaluate (/home/matys/nodebb/node_modules/benchpressjs/build/lib/evaluate.js:17:6)
    at precompile.then.code (/home/matys/nodebb/node_modules/benchpressjs/build/lib/compile-render.js:34:74)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by pitaj** [comment]
Looks like it may be an issue with your global footer widget. Can you provide the contents of it, and whether you changed it or not?

**Comment by Gwynnbleid1** [comment]
I don't even know how to change it. I have been playing with this forum for few days. 
I have only changed language to polish, configured emails, changed some topics names and posted 15 posts or so... I will try to get the content of this footer.

**Comment by co-owner** [comment]
me too.

**Comment by Per0x** [comment]
Same problem for me that appeared by itself again this morning.

error: /categories
 Render failed for template <div class="panel ui:
 Error: Render failed for template <div class="panel ui:

**Comment by barisusakli** [comment]
@Per0x you are not running latest right?

**Comment by Per0x** [comment]
@barisusakli I'm running 1.9.3, but it was the same before upgrade on 1.9.2.

**Comment by barisusakli** [comment]
checkout master or install benchpress 1.2.2, see if you get the error again

**Comment by Per0x** [comment]
I reinstalled everything with a backup and for now I no longer have the internal server error.
To be confirmed over time, but maybe it was a problem with docker since the container settings only had been imported from a previous container.

**Comment by barisusakli** [comment]
What version of benchpress?

**Comment by Per0x** [comment]
The default one. I reinstalled a clean nodeBB 1.9.3 but without importing a previous docker container settings. (i.e. by completely removing the previous docker containers with their settings)

**Comment by barisusakli** [comment]
1.10.0 is release let us know if you encounter this again after you upgrade.

**Comment by Per0x** [comment]
Everything seemed fine since the last time, and I did the upgrade to 1.10.0 and the same error reappeared :(
