### ISSUE TITLE
Export is giving same schema error and only exporting the first user ID profile

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6494]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

One of our global moderator reported following bug:

export posts option is not working
"{"path":"/api/user/uid/6599/export/posts","error":"Not all documents have the same schema."}"
gives this error

and export profile option is exporting @sarah 's profile only, in our case I guess Sarah's profile is the user id first profile.

**Comment by julianlam** [comment]
Thanks for reporting, will be fixed in next release for tomorrow
