### ISSUE TITLE
No hook when renaming Chat Room

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6501]
We have a plugin that strips out censored words in text. We use the hooks to censor the words but there doesn't seem to be a hook for when the room is renamed. Currently we use 'filter:messaging.getRecentChats' but this only works on page load. If a room is renamed and its updated through web sockets then there is no hook.

Can this be added in or have I missed a hook that can be used.

**Comment by julianlam** [comment]
Action hook `action:chat.renameRoom` added.

**Comment by julianlam** [comment]
Just updated it to match other similar calls, sends `roomId` and `newName`.

**Comment by FaizanZahid** [comment]
@uplift  which exact plugin are you using the censor the words? we used beep and in appropriate banned words plugin but both had few issues with redirect if some banned words come in url and is replaced by *

**Comment by uplift** [comment]
@FaizanZahid - its an in-house plugin that the team I work with maintain. I haven't used either of those plugins so I wouldn't be able to tell you how they differ.
