### ISSUE TITLE
Ability to assign or change chatroom group owners or have multiple chatroom group owners

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6503]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

So basically we created our private message group for only our mods, but later we want to kick out some of the mods, but issue is. the user who creater and was the owner of this group chat has left the site and is not coming back again, therefore, he can't assign us as the chat group owners, means other's can't kick other users out.

i think there should be option in the manage chatroom an option for a group owner, to assign a new group owner and revoke access. or may be have multiple chat group owners ?

**Comment by julianlam** [comment]
Typically, the chat room owner is re-assigned if the owner leaves (automatically goes to the next oldest member).

@barisusakli perhaps this needs re-thinking, and changing owner can be done at the "Add Members" modal?

**Comment by barisusakli** [comment]
Maybe it makes sense for admins to be able to change owners if they are in the room?

**Comment by julianlam** [comment]
Yes, I tend to agree, admins should be able to view the buttons to change (or add additional?) owners, as can the room owner themselves.

**Comment by FaizanZahid** [comment]
Yes i agree, admins should be able to do that for all groups. and if admins are not in a chat group, then atleast the initial owner should have the powers to assign new owners and multiple owners.

because right now if user A was owner, and he does not use the forum any more, (but he never left the chat) then currently it is unable to assign any group owners in the room at all coz the owner never left and other users can never become owner.

Just like there is option to kick, there should be option to make owner  along side.

**Comment by FaizanZahid** [comment]
Hi Guys, 

if you need any more info regarding this, please feel free to ask.. thanks
