### ISSUE TITLE
Some translations text are missing. Apply for adding resources to Transifex.

### ISSUE THREAD

**Issue by a632079** [NodeBB/NodeBB#6505]
* NodeBB Version: 1.9.x
* Current Node.js Version: 8.11.1
Admin-mods 's translation resources was missing.
Screenshot:
![default](https://user-images.githubusercontent.com/16975812/39953974-ae8ccc8e-55e8-11e8-9229-5d7866a84990.png)
* Firefox Console
![default](https://user-images.githubusercontent.com/16975812/39953977-bc6fefb6-55e8-11e8-95e1-ac7531801d08.png)
![default](https://user-images.githubusercontent.com/16975812/39953993-fc7d40ea-55e8-11e8-94ba-0f47256809aa.png)

* transifex. Can't find that resources

**Comment by julianlam** [comment]
Ready for translation, sorry about that!
