### ISSUE TITLE
How to prevent spam topics as from anonymous guest users?

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6506]
So since we turned on the anonymous guest posting feature, which means giving guests access to a special category in which they can make anonymous posts and topics without logged in.

Users were using it alright untill now, when some user started using some bot or automated script to mass post multiple topics and having the same post content "redirecting to his own spam site"

This is also one thing, i think again, that logged in users should also have an option while making a new topic or post to go anonymous. And post a topic or post anonymously. That way we dont have to worry about this spam stuff as node bb already has a fantastic spam prevention system for logged in users.

I also think that there should be an option to blacklist a specific URL in the ACP panel, such that whenever that URL is appeared or anyone tries to post, node bb should re write it and say URL Removed or just not let it post if the content contains a blocked URL.

Why is this needed? many spammers started abusing the forum by copying and pasting their 1 website link so many times in different topics and post and comments in the hope of getting traffic to their site from the forum... 

if we can just blacklist a particular URL in the ACP, then they should not be able to post it anywhere, such as bio, posts, messages, topics etc. that way mods dont have to worry about banning a user for posting spam content, they can simply ban the URL from being posted.

**Comment by julianlam** [comment]
For URL blocking, you can investigate plugin-beep, which is typically used for censoring curse words but can also work in this scenario I think. With respect to spam, I'd recommend you try using spam-be-gone. There's not much we can do otherwise because they are not user accounts, and so we cannot apply new user posting limits to them.
