### ISSUE TITLE
Categories dropdown is not responsive for long category names

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6510]
Please see attached image, we have long category names and on mobile drop down is not responsive I cannot scroll horizontal.

You can try opening this page as a guest from mobile and tap on categories dropdown to see the bug.

https://chatrooms.talkwithstranger.com/recent

**Comment by barisusakli** [comment]
Until it is fixed in persona, you can add a custom CSS rule
```
.category-dropdown-menu {
  max-width: 300px;
  .category a {
      white-space: normal;
   }
}
```

**Comment by FaizanZahid** [comment]
Thanks. i will also add the ref of this on persona github so we can get it fixed in person, thanks!

**Comment by pitaj** [comment]
Fixed in persona
