### ISSUE TITLE
Allow area or panel for adding and writing Group Rules for each group

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6517]
Node bb's groups are cool once they are associated with category, we are going towards scaling our forum.

We think on the group landing page, group owners and admins should be able to add list of group rules  which will be visible to new users (outside group) or joined users within the group. **It can be as simple as a text area or numbered list of rules.**

This is very imp so that let's say if its a group like r/funny as on reddit, they have their own group rules, and if someone posts something which is NOT FUNNY, it get immediately deleted by the r/ mods.

Node bb already has category based mods, but we just need a field to put group rules against each group so that new users must follow those rules unless their topics won't be published if their posts don't match the requirements of group rules.

**Comment by pauljherring** [comment]
Would a pinned post in the category not suffice for this?

**Comment by FaizanZahid** [comment]
Pinned post would be like an additional thing for extended rules but also
pinned post won't be visible to a person unless he she has joined the
group. Coz not all associated categories and their posts will be accessible
to non joined users.

See this on desktop https://www.reddit.com/r/funny/

On right side u will see some useful stats of this sub reddit, rules,
online here, mods of this category and so on. Node bb already has most of
these so just showing them in a panel would make it complete.

**Comment by barisusakli** [comment]
Why not just use the group description?
![image](https://user-images.githubusercontent.com/2583394/40579375-faeccbe0-60f3-11e8-8444-773d2625ba98.png)

**Comment by FaizanZahid** [comment]
ok i will use that, thanks
