### ISSUE TITLE
New reply and topic buttons don't work

### ISSUE THREAD

**Issue by Varunram** [NodeBB/NodeBB#6521]
NodeBB version: 1.7.3
npm version: 3.10.10
NodeBB git hash: 2661a31227c54c6a2716f2d41d4ff644a3652a29 
Database type: mongo
Database version: db version v3.2.19 
Exact steps to cause this issue: Everything was working fine till a couple of days back, suddenly node crashed and we start to get this error

Nothing there in the logs, nothing there when I run `./nodebb dev`, any suggestions as to why this might happen along with potential mitigation ideas?

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
