### ISSUE TITLE
Raw formatting in Post Queue. Again (I think)

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#6528]
- **NodeBB version:** 1.9.3
- **Exact steps to cause this issue:**
1. Go to /post-queue with a queued post present

- **What you expected:**

Actually, I expected what I actually got:

Narrow view:
![screenshot from 2018-05-28 14-38-27](https://user-images.githubusercontent.com/3939886/40617352-f94ef202-6285-11e8-86bd-56f18ae56be7.png)

Zoomed out:
![screenshot from 2018-05-28 14-38-44](https://user-images.githubusercontent.com/3939886/40617364-0202178a-6286-11e8-8ab6-5d414cf8b6e7.png)

What I'd like however is something like:

![screenshot from 2018-05-28 14-46-23](https://user-images.githubusercontent.com/3939886/40617413-2433f56c-6286-11e8-94fe-c68790ee459a.png)

I'd appreciate insights as to why `raw` (only) was chosen for the format for the post queue, instead of either cooked or an option to display either.

Admittedly, most things that end up in the queue are *usually* readable, with a bit of effort, but scanning through that lot for potentially spammy stuff, when in fact most of it was in fact (slightly badly formatted)  code caused me to simply approve it then examine it rather than making the decision on that screen.

**Comment by barisusakli** [comment]
Yeah we can definitely parse the raw text.
