### ISSUE TITLE
It is not possible to use < and > in signatures

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6543]
* **NodeBB version:** 1.9.3
* **Database type:** mongo
* **Database version:** 3.6.4
* **Exact steps to cause this issue:** Use something like this in your signature:  
`println("<hi>");`
* **What you expected:** Just display `println("<hi>");`. Simply encode `<` as `&lt;` and `>` as `&gt;`
* **What happened instead:** It outputs `println("");`

This isn't a very important issue. It was reported to me by a user and I took a look at it. Looking at the code it seems to happen in `Posts.parseSignature` calling `sanitizeSignature` calling `utils.stripHTMLTags`. 
https://github.com/NodeBB/NodeBB/blob/af58717d9cb9cf6c6ade1cb4187143bcb12a63d6/public/src/utils.js#L332

This `stripHTMLTags` function is kind of strange. You pass it the text and the tags to be stripped. The tags are sanitized to put into the Regex, but that Regex has an alternate path that will strip out any HTML looking tags anyway. So the second parameter is completely useless. It will always strip out anything that only looks vaguely similar to an HTML tag.

And by vaguely I really mean vaguely: https://jsfiddle.net/3srgwa1a/

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/blob/731aa8912a3cf88ba19e877a5b7ac580bb5c9966/src/user/profile.js#L49

It looks like it is sanitized on the way in here...

**Comment by julianlam** [comment]
... this goes back to 5 years ago (!!) when the file was first refactored. I see no reason to strip all HTML tags since it is sufficiently escaped now.

**Comment by julianlam** [comment]
It may be that we used to strip all HTML tags as a blanket effort to curb XSS...
