### ISSUE TITLE
?pretty=1 in API routes to display prettier JSON output

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6554]
An obvious low-hanging fruit, but many developers come to NodeBB (and Node.js and client-side js in particular) fresh and do not have the same setup that we have. Some see an impenetrable block of JSON output to be a stumbling block and don't automatically think "oh I didn't install my json viewer plugin". Others might not want to install such a plugin for a variety of reasons.

So, if `?pretty=1` is added to an API call, return it with 4 space indentation :+1: 

* [x] `?pretty=1`
* [x] Mention this in docs.nodebb.org in a number of places so it has visibility among newcomers

**Comment by barisusakli** [comment]
https://github.com/NodeBB/docs/commit/24e9a402fd3cb8b9ee0eb81e6168fc4b23078166
