### ISSUE TITLE
Ignore user UI

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#6560]
The ignore user Ui is a bit confusing

i have to go to my profile, then click on blocks and search for the user

i suggest adding a button to ignore the user on that user profile, like the button to follow 

![screenshot_13](https://user-images.githubusercontent.com/10746278/41129911-894056e0-6ab4-11e8-91e9-f29627ec44eb.png)

and also here
![screenshot_14](https://user-images.githubusercontent.com/10746278/41129932-a46d3046-6ab4-11e8-94d5-bc22f7d8732f.png)

thank you

also the current UI on blocks page is a bit confusing 
why i have to search again for an user to unblock it? a simple button should do the trick
why blocking an user doesnt allow me to check his profile?

**Comment by julianlam** [comment]
You're right, a block button here would be helpful:

![selection_434](https://user-images.githubusercontent.com/923011/42293556-2316f5e0-7fa9-11e8-9bdd-14c29cc98a15.png)

I also don't see any reason to continue blocking the profile, so we can add the unblock button there as well.

**Comment by julianlam** [comment]
Account pages are no longer inaccessible when a user is blocked.

**Comment by julianlam** [comment]
:point_up: theme changes for this issue

**Comment by exomarty** [comment]
👏👏
