### ISSUE TITLE
Link to og:image includes the relative path twice when viewing a topic

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6568]
- **NodeBB version:** 1.9.3
- **Database type:** mongo or redis
- **Database version:** mongo
- **Exact steps to cause this issue:**
1. Install in a subfolder
1. View a topic
1. Look at the source
1. Notice the wrong url for og:image and og:image:url
- **What you expected:** The right url
- **What happened instead:** It included the subfolder twice

Also as a side note: Why is it using the profile avatar as the og:image? It is my forum, if it is linked I want it to be advertised with my forum logo and not the avatar of a random user :wink:

**Comment by barisusakli** [comment]
@Dravere it uses these images https://github.com/NodeBB/NodeBB/blob/master/src/controllers/topics.js#L288-L300, the idea was to display the image of the user who made the post.
