### ISSUE TITLE
Please provide the analytics counter directly

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6569]
Would it be possible to store the counters in memory and provide them via a function? Should be easy to implement and I would volunteer to do it.

The reason for this is that I would like to export those counters to an external monitoring system. Actually I'm already doing it with my [plugin](https://www.npmjs.com/package/nodebb-plugin-prometheus). I'll announce it in the NodeBB community forum in a few days if everything stays stable :smiley: 

Currently it is just a bit awkward. There is for once a 10 seconds delay and I need to accumulate every hour. Also when restarting there is no good way to reset the counter. That the analytics counters would reset at a restart is no problem. Prometheus can deal with this. But it needs a proper zero counting point when resetting which is currently quite difficult to achieve. Also it would remove all those database calls.

Are there any objections for something like this?

**Comment by julianlam** [comment]
Continued discussion to be held at #6573

**Comment by julianlam** [comment]
See #6575
