### ISSUE TITLE
Add Filter to getCategories

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6570]
We have a use case where we want a category but dont want it displayed in the main category list. Would it be possible to add a filter hook around the below line so we can remove it?

https://github.com/NodeBB/NodeBB/blob/e7cd552e3399e9a782c081b88b942b184a544da7/src/controllers/categories.js#L24

(Edited as previous location would cause issues)

**Comment by barisusakli** [comment]
Why not use `filter:categories.build`?

**Comment by uplift** [comment]
Ah that works! Didn't think to look at templateData, too focused on categories data. Cant see the forest for the trees as they say.  Thanks
