### ISSUE TITLE
User can not be deleted from the database for session sharing

### ISSUE THREAD

**Issue by maulikmmodi** [NodeBB/NodeBB#6572]
I am using nodebb as the forum of my product. I have included the session sharing plugin for nodebb. So, my product is app.homeschoolpanda.com and forum is forum.homeschoolpanda.com.

The problem is, when I removed user from the database(mongodb). After that it is not letting that user to share the session. I have tried different ways, but I can not update that.

![nodebb-sso](https://user-images.githubusercontent.com/12855612/41347617-ced70bf0-6f27-11e8-93b5-4925e1942262.png)

I just want to remove this user and start again for this. How can I do that?

**Comment by julianlam** [comment]
It is not recommended for you to do direct database manipulation, as you will leave dangling references and run into situations such as these.

Please re-create the missing user hash (you can copy the details from an existing user, if that helps), and delete the user properly via the ACP. Hopefully the only thing you deleted was the `user:<uid>` object...

**Comment by maulikmmodi** [comment]
How do I do that? Re-create hash and delete user via ACP. When I deleted it from the admin, I still show that info as a guest user.

**Comment by julianlam** [comment]
If the user is properly deleted, they should then be able to re-login via session-sharing. If you're still seeing issues with session mismatch, then you may have to delete the remoteId-to-uid reference (which is by default found in `appId:uid`.

**Comment by maulikmmodi** [comment]
Nope, still not working. It will create a new entry when I try to log in. **How can I delete user completely from the database?** Because after this, it is showing under guest in admin search. I tried to change the email Id and the name, but it is taking the userId only. 

I just want to get rid of this user. Can you give me exact steps to do that?
