### ISSUE TITLE
can not post new post 

### ISSUE THREAD

**Issue by zc1024** [NodeBB/NodeBB#6577]
Hello ,I run the NodeBB server on Ubuntu 16.04 using mongodb.
And I run it successfully. I registed a new account.
But I can not post new post. Click the new post button does not work.
Can you  help me?
Thanks

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
