### ISSUE TITLE
Disable new user restrictions for moderators

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6578]
It doesn't make a lot of sense that moderators have those restrictions (xx seconds between postings) applied to them, does it? A moderator is a trusted user and thus no longer a new user anyway. They should be excluded from that restriction.

**Comment by barisusakli** [comment]
Admins and mods should already be exempt from those restrictions, https://github.com/NodeBB/NodeBB/blob/master/src/user/posts.js#L28

**Comment by Dravere** [comment]
That line of code explains everything. It is per category. It is highly likely for some special circumstances that the moderator didn't have the privileges in the specific category when they reported the problem. So for now this issue can be closed as it was a misunderstanding on my part. I think it is perfectly reasonable to have it per category.

Thank you!

**Comment by barisusakli** [comment]
Yes it is per category unless the user is a Global Moderator then they are considered a moderator of all categories.
