### ISSUE TITLE
Day, Week, Month setting for Top topics page like in popular topics

### ISSUE THREAD

**Issue by vennmann** [NodeBB/NodeBB#6579]
Hi I see day, week, month options for popular topics

eg, https://community.nodebb.org/popular

But is there a way to configure the same for top topics page

In here - https://community.nodebb.org/top

I think it would be good to show the topics sorted by top votes according to day, week, and month.

Also in the email digest if we can configure the top topics by day or week as well , currently there is only latest topics for digest. Can we set it up such that everyone who signed up for digest receives the top topics of the day from the whole forum ?

Any idea how long it will take for this feature request ? Happy to pay for this work.

**Comment by vennmann** [comment]
Is this already live here, https://community.nodebb.org/top
That's awesome.
Also the corresponding RSS feed needs to be updated like in popular ?
https://community.nodebb.org/popular/daily.rss

**Comment by barisusakli** [comment]
Yes /top.rss needs to be updated

**Comment by FaizanZahid** [comment]
So what's the difference between /popular topics and /top topics?
