### ISSUE TITLE
The page skin changes when you select the online status even though it is off.

### ISSUE THREAD

**Issue by RikoDEV** [NodeBB/NodeBB#6591]
- **NodeBB version:**  1.9.3
- **NodeBB git hash:** ec4754078b8187a3dfe022a5b263cda89899a3b1
- **Theme:** Persona
- **Database type:** mongodb
- **Database version:** 3.6.5

**Exact steps to cause this issue:**

- Disable skin selection for users in ACP.
- Force default forum skin for all users.
- Click on the avatar on the forum's main page.
- Choose any online / offline / afk status.
- Go to user settings page.
- Go to any subpage, such as categories.
- After selecting the status for an unknown reason, the forum skin changes to blue.

After reloading the page using the F5 shortcut, the skin returns to the default appearance.

- **What you expected:**
The skin should not change when you change the status.
- **What happened instead:**
Skin changes to blue, even though it is disabled in the forum administrator settings.

Video: https://www.youtube.com/watch?v=-VD_GbNxaAE

**Comment by barisusakli** [comment]
@RikoDEV thanks for the detailed steps and the video 👍
