### ISSUE TITLE
Plugin hook for user password change/reset

### ISSUE THREAD

**Issue by csprl** [NodeBB/NodeBB#6592]
I have developed an external service that relies on NodeBB for authentication and it would be useful to be able to perform actions (force a reauthentication for example) if a user changes or resets his password. As far as I can tell there isn't a plugin hook for this currently.

**Comment by julianlam** [comment]
@csprl I'd be okay with adding an action hook for things like changes and resets (although I believe a successful reset is just a password change, so it'd be a little harder to distinguish).

However, I am against passing the password nor the hashed value through to plugins, as it can be potentially misused.

`plugins.fireHook('action:password.reset', { uid: 1 });`, `plugins.fireHook('action:password.change', { uid: 1 });`?

**Comment by csprl** [comment]
Sounds good! Personally I don't need the plugin itself to see the password and I fully agree with you that it's better to not let plugins have that data. The action hooks you proposed would be perfect!
