### ISSUE TITLE
Migration for issue #6539

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6596]
In issue #6539 the GDPR issue with `ip:recent` is solved. Shouldn't there be a migration for it as well? Hashing all existing entries in `ip:recent`? Because for one it would solve the issue of already stored IP addresses but it also wouldn't count the same IP address twice (for example in all time unique visitors).

**Comment by julianlam** [comment]
Yes, you're right, there should be one, which I'll add today :+1: nice catch
