### ISSUE TITLE
Add/Delete Topic Tags Hook

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6597]
Is it possible to add hooks to the adding and deleting of tags on topics?

**Comment by barisusakli** [comment]
You can use `filter:topic.edit` for this? Just load the topics tags if you need them in the hook.

**Comment by uplift** [comment]
I don't see a way to use this when a topic is deleted. Am I missing something?

I'm currently using action:topic.save for the adding but by time action:topic.delete is called the tags are already deleted.

Bit of background for what we're are trying to do:-
For a certain category/group of categories we want to record the tag count for the topics inside those categories (separate to the main count). Using action:topic.save I'm able to record the count on add but I have no way to record the count on delete if that makes sense.

**Comment by barisusakli** [comment]
Oh I thought you were trying to detect tags being added/removed from topics. Btw deleting a  topic doesnt seem to touch tags, did you mean purge?

**Comment by uplift** [comment]
Yes sorry purge, not delete. It was action:topic.purge  hook I tried not the delete one above.
