### ISSUE TITLE
how can i render 4 articles from common category ?

### ISSUE THREAD

**Issue by ZQ-jhon** [NodeBB/NodeBB#6600]
The four pics come form the common category , i render them the latest 4 items

like this:  

[photo](https://i.imgur.com/pVQu4Zz.png)

need i modify it's controller ? or other way ?

thanks

**Comment by julianlam** [comment]
You may want something like the [recent-cards](https://github.com/NodeBB-Community/nodebb-plugin-recent-cards) plugin.
