### ISSUE TITLE
how can i render 4 articles form common category

### ISSUE THREAD

**Issue by ZQ-jhon** [NodeBB/NodeBB#6604]
like this:
![image](https://user-images.githubusercontent.com/26297704/41816181-d29fab3e-77b0-11e8-9001-1291c320add6.png)

the four articles in common row ，they come form common category , and the one is latest，the four is earliest.
Thank you!

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
