### ISSUE TITLE
Critical situation 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6619]
- **NodeBB version:** 1.10.0
- **Database type:** mongo
- **Database version:** 3.2.11

Hi, we have a critical situation here. In order to increase the speed, We replicated mongodb (master/slave mode; whotout sharding). It increased the speed for a few months But now it seems that the database is missing and all of the users, topics etc. ?? 
I don't know what cause this problem. Can we find out whether the database is missing or not?

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
