### ISSUE TITLE
Can't install plugin in 1.10.0

### ISSUE THREAD

**Issue by Per0x** [NodeBB/NodeBB#6620]
- **NodeBB version:** 1.10.0
- **NodeBB git hash:** 

- **Database type:**  redis

When I click on install button for all plugins, the prohibited sign appears when the button is hovered with the mouse, and nothing happens.

**Comment by RikoDEV** [comment]
The same issue in mongo database.

**Comment by protesqu** [comment]
Same here, can't install anything
