### ISSUE TITLE
PostgreSQL status

### ISSUE THREAD

**Issue by venmade** [NodeBB/NodeBB#6621]
I plan to go from xenforo 2 to nodebb, I have a of small questions::
1. What is the status of PostgreSQL integration at the moment?
https://github.com/NodeBB/NodeBB/pull/5861
I'm not good at dealing with mongodb, but I had to work with PostgreSQL, it also works well with ispmanager as opposed to mongodb.
therefore, this issue is important enough :)

2. how are things going with the plugins and the update system?

**Comment by hmqgg** [comment]
The PR #5861 works well, although there are some bugs.
MongoDB may be faster than PG for hosting nodeBB, you can search BenLubar's benchmark in GitHub Gist to learn more.

Plugins and update works, because of nodeBB's outstanding database interface design 💯 .
