### ISSUE TITLE
Should User Blocks be visible to all?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6624]
At the moment as far as I can tell (correct me if I'm wrong as I'm early in adding the feature into our theme), everyone's blocked list is visible to all users that can view the profile. Should this be the case?

If it is then the search and toggle block section shouldn't be displayed to all users, only on your own block page. In which case everyone else just sees your blocked user list. Currently anyone that views your blocked list can search and click toggle block but it doesn't do anything and displays no error.

Could the ability to allow people to see the block list or not be an optional config?

**Comment by barisusakli** [comment]
What version of NodeBB? The blocks is should be private afaik.

**Comment by uplift** [comment]
Nodebb 1.10.0. Just updated today. I'll double check my update see if something has gone awry.

**Comment by barisusakli** [comment]
I see one problem on the persona theme, the blocks menu item is visible to everyone but clicking it results in access denied, the link shouldn't be visible to regular users at all.

**Comment by uplift** [comment]
Should Admins and Mods be able to see all users blocked list? Just tested a non admin account and it works as you say it should and the menu item is now hidden with your commit but my main admin account still sees the blocked list pages for all users. Is that correct behaviour?

**Comment by barisusakli** [comment]
Yes admins/mods should see it

**Comment by uplift** [comment]
Should the search/toggle be visible to admins/mods on the blocks page? The admins/mods cant toggle so it being visible is superfluous. Happy for this to be closed if you think it should remain.

**Comment by barisusakli** [comment]
If it's visible to admins and mods it should be be toggleable as well, I will fix that too.
