### ISSUE TITLE
ip:recent usage?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6629]
Hi, while testing the upgrade to nodebb 1.10.0, we've come across an issue with the upgrade script that hashes the past ip addresses in ip:recent. Due to the large number in the ip:recent dataset, it'll take hours to process it all.  

We plan to truncate the dataset to the past month of records. From my understanding of the codebase, this is all it is used for when calculating the analytics of unique visitors in the admin panel. Is my understanding correct or have I missed a usage that I need to consider before running the upgrade?

**Comment by barisusakli** [comment]
Yes you can truncate it to the last month
