### ISSUE TITLE
Enhancement: Auto lock stale threads

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6630]
At the moment, there is just a warning when someone tries to reply to a stale thread. Would it be possible for an option in the admin panel to automatically lock these threads instead of a warning?

**Comment by julianlam** [comment]
You'll want to check out [the Archiver plugin](https://github.com/julianlam/nodebb-plugin-archiver) :smile:

**Comment by uplift** [comment]
Ah thanks 👍
