### ISSUE TITLE
Editing topic title changes for all edit history

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6632]
On Node 1.10.0 if you edit the topic title it changes it across all the edit history. Is this expected behaviour?

**Comment by julianlam** [comment]
Currently, yes... we don't save the topic history yet.

**Comment by uplift** [comment]
Thanks :)

**Comment by uplift** [comment]
Has this been fixed or has it been closed as a wont fix/future work? Just so I can update our internal issue tracking. Thanks

**Comment by julianlam** [comment]
Hi @uplift -- at this time, we're not planning on saving topic title in history if only because it is not a trivial change (requires a bit of a refactor to accomplish)

Perhaps I may have been a little overzealous about closing... :thinking:

**Comment by julianlam** [comment]
But for now, it is in the backlog and not slated for actual development at least until 2019.

**Comment by uplift** [comment]
That's fine. There's no urgency as far as I'm concerned as its a minor bug. Just needed to report back to my internal test team if it wasn't going to be fixed.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/10900
