### ISSUE TITLE
Still send chat messages to a user you've blocked

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6633]
On Nodebb 1.10.0, when you block a user, you can still send them messages on chat even tho they can't reply. Shouldn't blocking block both sides from interacting like they have both blocked each other but only give the blocker the option to unblock?

**Comment by julianlam** [comment]
No, you're right, this sounds like an oversight :+1:

**Comment by julianlam** [comment]
Actually, after giving this a bit of thought, I think that the action of blocking is private, and by limiting communication between two individuals both ways, you'd be unintentionally leaking the block state to the person that is blocked.

The way it is now, you'll not be able to see any of their messages (as they are blocked), but they can continue to see yours, even if you send new ones, as you are not blocked to them.
