### ISSUE TITLE
Can't upvote/downvote posts as guests

### ISSUE THREAD

**Issue by vennmann** [NodeBB/NodeBB#6635]
Set the priveleges at category level for guests to allow upvote and downvote posts.
Still asking to login, when attempting to do this.

**Comment by julianlam** [comment]
Yeah, in this case I think the bug is that guests can be given the upvote/downvote privilege. That should not be the case.

I don't think we'll add the ability to have guests upvote, as by nature of them being guests, their existence (and footprint) is ephemeral.
