### ISSUE TITLE
Advanced private files feature

### ISSUE THREAD

**Issue by Per0x** [NodeBB/NodeBB#6637]
Hello,
Currently the "Make uploaded files private" feature applies to all files including images. It would be very practical to be able to specify the extensions of private files or not in order for example to be able to limit the download of.txt .pdf .exe etc but to let display all the images for the guests.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/85a55d1740dbbb224cd4aa0e5974cf0650fcd06e
