### ISSUE TITLE
Can't Minimize Chat Modal

### ISSUE THREAD

**Issue by protesqu** [NodeBB/NodeBB#6642]
**NodeBB version:** v1.10.1
**Database type:** redis

Hey, I just noticed that minimizing doesn't work on chat modals in my site, and I was wondering if anyone else is having this issue.

**Comment by julianlam** [comment]
Oh dear... looks like a regression.

For now, you can click the icon at the bottom right of the screen to minimize a chat.

**Comment by protesqu** [comment]
Alright. Thank you, Julian
