### ISSUE TITLE
Consider using User.isPasswordCorrect() instead of lower-level Password.compare()

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6646]
In this section: https://github.com/NodeBB/NodeBB/blob/ec91ef1c644044bba44198b031913655e784b4bb/src/controllers/authentication.js#L401-L403

And Password.compare() is called later on:
https://github.com/NodeBB/NodeBB/blob/ec91ef1c644044bba44198b031913655e784b4bb/src/controllers/authentication.js#L427-L429

* This was added before User.isPasswordCorrect(), a higher-level method, was introduced.
* Would be ideal to reduce the method complexity by calling User.isPasswordCorrect() as well. 
* Additionally, the latter method has a delay on incorrect password attempt.
* Lastly, it seems `passwordExpiry` isn't even used in the method

**Comment by protesqu** [comment]
This function sounds like a very important addition, many thanks!
