### ISSUE TITLE
User.getUidByUsername behaves case-sensitive

### ISSUE THREAD

**Issue by LudwikJaniuk** [NodeBB/NodeBB#6656]
- version: 1.8.2
- **NodeBB git hash: 9da3be5af63f4a842e47bf54bb09e00acd1de8cf** 
- **Database type:** mongo
- **Database version:** 3.2.20
- **Exact steps to cause this issue:**
Lookup a user with the User.getUidByUsername function, giving a different capitalization than was used when registering. e.g. the user registered as "John" and I look up "john"
- **What you expected:**
To get the user anyways, because usernames should not be case sensitive (https://github.com/NodeBB/NodeBB/issues/2079)
- **What happened instead:**
It gave me the global test user.

**Comment by julianlam** [comment]
This is by design as the username to uid hash saves them with case sensitivity. Perhaps you'd be better served using `user.getUidByUserslug` instead?

**Comment by LudwikJaniuk** [comment]
Yeah, I can probably use that, thanks.
