### ISSUE TITLE
Does authentication route only support callback-based passport strategies?

### ISSUE THREAD

**Issue by LudwikJaniuk** [NodeBB/NodeBB#6660]
- version: 1.8.2
- **NodeBB git hash: 9da3be5af63f4a842e47bf54bb09e00acd1de8cf** 
- **Database type:** mongo
- **Database version:** 3.2.20
- **Exact steps to cause this issue:**
Trying to use the `'filter:auth.init'` hook to add a custom auth strategy. For the sake of experimentation right now, it simply logs the claimed user in. No password, no oauth.
- **What you expected:**
In my case, the `url` field on strategy is relevant, but the `callbackURL` field is not in use. I expected that to be enough to have a functioning login strategy.
- **What happened instead:**
When I use the endpoint I provide for login, it does log in, but two things happen:
 * I get the "Session Mismatch" popup
 * I also get a 404.

Investigating the code (here: https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L62), it kind of looks like nodebb is assuming every strategy will have a callback, and I get the two errors I mentioned because some important stuff is only done in the callbackURL listener (like sending a rendered response, and maybe updating the cookie correctly). 

Is that the case, is the code making that assumption? Or am I missing something? 

Also, is there maybe a reasonable way to work around this? Or is this use case not really feasible?

**Comment by julianlam** [comment]
It depends on what kind of login you want to eventually implement. `filter:auth.init` is meant to be used with passport-based authentication schemes (and the best way to implement that would be to fork something like the [Facebook SSO](https://github.com/julianlam/nodebb-plugin-sso-facebook) plugin or similar.

Perhaps you want `action:auth.overrideLogin`?

**Comment by LudwikJaniuk** [comment]
Well, this is what threw me off, because I am indeed using a passport-based strategy. Specifically, passport-custom (https://github.com/mbell8903/passport-custom). But it's one that does not connect to an external service, just uses my custom logic. 

Should I be able to use any passport-based strategy at all, or only ones that rely on an external site and a callback?

**Comment by julianlam** [comment]
Hm, that should still work. Your `url` would be the endpoint exposed by your NodeBB to kickstart the SSO process. Whatever you pass in here is mounted by the NodeBB router, e.g.

https://github.com/julianlam/nodebb-plugin-sso-facebook/blob/master/library.js#L131

https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L63

The actual logic for this is handled in your SSO plugin, and should redirect to the remote endpoint for authentication. In your case you want to just return a user.

At this point it should redirect the user back to the `callbackUrl`, which will again call the logic in your SSO plugin to log in the actual user.

https://github.com/julianlam/nodebb-plugin-sso-facebook/blob/master/library.js#L86-L127

**Comment by LudwikJaniuk** [comment]
Yeah, what I do is I just return the user in my custom logic. I don't see how I can redirect them myself tho, since I never get the `res` object, only `req`.

**Comment by julianlam** [comment]
As far as I know, both `req` and `res` are passed through...

```
passport.authenticate(strategy.name, {
	scope: strategy.scope,
	prompt: strategy.prompt || undefined,
	state: req.session.ssoState,
})(req, res, next);
```

**Comment by LudwikJaniuk** [comment]
Hmm, might be specific to that custom strategy then. Will check on it soon.

**Comment by LudwikJaniuk** [comment]
So I looked into the abstract `passport-strategy` package (https://github.com/jaredhanson/passport-strategy) to check on the general API. That package does not give a passport implementer access to `res` directly, but you can redirect via a function. I think if you're not using an external service with callback, that passport will just pass control to the next handler. It expects something like:

```
app.post('/login',
  passport.authenticate('custom', { failureRedirect: '/login' }),
  function(req, res) {
    res.redirect('/'); // I can't add this part from a plugin
  }
);
```
But the nodebb implementation does this:
```
router.get(strategy.url, Auth.middleware.applyCSRF, function (req, res, next) {
						req.session.ssoState = req.csrfToken();
						passport.authenticate(strategy.name, {
							scope: strategy.scope,
							prompt: strategy.prompt || undefined,
							state: req.session.ssoState,
						})(req, res, next);
} /* NOTE: Nothing here to add a handler from the plugin */);
```
The simplest workaround would be to implement my own strategy from `passport-strategy` which redirects to the homepage or something. This means that `passport-custom` isn't usable from NodeBB, because Nodebb requires you to either redirect to something external or redirect/respond directly from the strategy. Have I got it right? 

An alternative would be if nodebb's hook accepted a "successHandler" (or even "successRedirect") that is called when (if) the strategy passes control to the next handler. Not sure which solution is more hacky or more maintainable.

**Comment by LudwikJaniuk** [comment]
What turns out to work quite well is simply relying on the callback directly for my custom auth. That is, I never visit the regular url, just the callback at once. Then I don't get the 404 or session mismatch.

**Comment by jeremysnyder** [comment]
@LudwikJaniuk Would you be able to share your solution?  I am trying to do something that I think is similar, and am having trouble figuring out what you mean by "relying on the callback directly".  I know it's been a long time since, just thought I would ask.

**Comment by LudwikJaniuk** [comment]
Haha, doesn't hurt to ask ;) I sadly can't find the code anymore, but what i think I meant by relying on the callback directly is "having the user/client go to the callback URL directly". I don't remember the exact details. It was likely hacky...
