### ISSUE TITLE
Users don't have Account info button but they can access info page

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6678]
**NodeBB version: 1.10.1**
Hi, why users cannot see their account sessions? Does it have any configuration?

**Comment by pitaj** [comment]
It should be at https://your.site/me/info or "Account Info" in the user menu. If they aren't working then your reverse proxy probably isn't set up correctly. Regardless, Github is for bug reports and feature requests only. Please go to https://community.nodebb.org with any questions you're having.

**Comment by mohammadhassan99** [comment]
Hi @pitaj , i think the issue should be opened. Because we realized that our users don't have the Account info button in /user page. But they have access to their Account info page if they type the address manually. Our mods and Admins have Account info button but users don't

**Comment by pitaj** [comment]
https://github.com/NodeBB/NodeBB/blob/b88a8de6a159d0b2cd5114e084b38c82c24d5a2a/src/controllers/accounts/helpers.js#L62

It looks like you're correct.

**Comment by julianlam** [comment]
Account Info is not allowed to end users. Sessions should be moved out.

**Comment by mohammadhassan99** [comment]
Why? It is some how a security issue that they can find out who log in their account.

**Comment by pauljherring** [comment]
> It is some how a security issue that they can find out who log in their account.

I think it's the other stuff in `Account Info` that the user shouldn't/doesn't need access to - thus the suggestion to move sessions to a different page to which the user should have access to.

**Comment by mohammadhassan99** [comment]
> I think it's the other stuff in Account Info that the user shouldn't/doesn't need access to - thus the suggestion to move sessions to a different page to which the user should have access to.

I agree with you. But I still think that ```Login Sessions``` is useful and the user has the right to access that.

**Comment by pauljherring** [comment]
> But I still think that Login Sessions is useful and the user has the right to access that.

What part of what I wrote says that they shouldn't have that right?

**Comment by mohammadhassan99** [comment]
> What part of what I wrote says that they shouldn't have that right?

Generally I said 😃 . I didn't mean that.
