### ISSUE TITLE
Bug at ban function (temp. ban)

### ISSUE THREAD

**Issue by necrosoul** [NodeBB/NodeBB#6685]
- **NodeBB version:** 1.10.1
- **NodeBB git hash:** n/a

- **database:** mongodb
- **** version of mongodb like in documentation of nodebb.

- **Exact steps to cause this issue:** Temporary ban dont working at all.

- **What you expected:** Temporary ban should be fixed.
If i ban some users for 1 hour or for  5 hours - after 1 hour or 5 they should be UNBANNED automatically. 

- **What happened instead:** Temp. ban workin like perm. ban.  This is bad and ruin my forum.

**Comment by julianlam** [comment]
Unbans are processed at the login step, so when the user's ban expires, they will be able to log in again. At that point their account will have the ban flag lifted.
