### ISSUE TITLE
firefox about:config pref causes problems with Netgate's forum

### ISSUE THREAD

**Issue by jawz101** [NodeBB/NodeBB#6686]
It was recommended I post an issue here by Julian with the NodeBB project about an issue I observed while using the new Netgate forum (pfSense)

originally reported here: https://forum.netgate.com/topic/131636/new-forum-and-firefox/3

My original description of the issue:

> I just wanted to note if you use Firefox and tinker with your about:config settings the new forum does not like setting network.http.sendRefererHeader = 1 (send referer with links only). The default is network.http.sendRefererHeader = 2 which means send a referer with links and images. This is the first site I've ever come across having troubles with not sending a referer header for images but I wanted to pass it along.

> I'm unable to click reply until I reset this about:config pref. The first thing I noticed, though, was the error msg "Looks like your connection to Netgate Forum was lost, please wait while we try to reconnect." in a little pop-up alert in the lower right-hand corner of the page.

Also can't mark all topics as read.  Basically many functions on the site just stop working.

And Julian's comment: 
> Hi there -- Julian from NodeBB here. Interesting report re: sendRefererHeader.
> 
> We don't account for the browser forcing a header, but to my knowledge the only mucking around with referrer is appending noreferrer to links pointing externally. What do you see when it happens?
> 
> Feel free to file a bug at our GitHub repo if you can easily reproduce it. Thanks.

Steps to reproduce:
1) install firefox
2) in the address bar type about:config > enter and change the preference network.http.sendRefererHeader from 2 to 1
3) browse https://forum.netgate.com

Screenshot:
![screenshot_2018-08-05 new forum and firefox](https://user-images.githubusercontent.com/14151703/43681597-93284cb0-9847-11e8-8bc4-4af88100ce8e.png)

**Comment by julianlam** [comment]
https://github.com/socketio/socket.io/issues/3306

**Comment by barisusakli** [comment]
Browsing with `network.http.sendRefererHeader 1`  seems to be fine on latest nodebb + firefox
