### ISSUE TITLE
Error at edit post 

### ISSUE THREAD

**Issue by necrosoul** [NodeBB/NodeBB#6694]
- **NodeBB version:** 1.10.1
- **NodeBB git hash:** n/a

- **Database type:** mongo DB
- **Database version:** 3.6 (or 3.4)

- **Exact steps to cause this issue:**

- **What you expected:** I want to remove this error and to have ability to change post.

- **What happened instead:** i cant edit post after adding some text.

Check this file from my database, try to copy it to your forum (post message) and try to edit post via post-edit button.
[error.txt](https://github.com/NodeBB/NodeBB/files/2274009/error.txt)

I dont understand why my forum topic crashed after i write somethin bigger.

You must enable html tags to test it better, and mongodb database.

Here  text file from where u can copy and paste into new topic

[textthis.txt](https://github.com/NodeBB/NodeBB/files/2274185/textthis.txt)

Please fix this bug.

I found reason why topic design is crashed.
This is Sanitize-html plugin

If i writed text after `<h5><span class="label label-primary">Что еще нужно знать о таблицах?</span></h5>`

i get error.

// Problem at text after `<h5><span class="label label-primary">Что еще нужно знать о таблицах?</span></h5>`  if i write it - topic crashed.

When i disable sanitize - topic showing without bugs or if i disable markdown plugin - topic seems to be good.
BUT! buttons dont workin at all. i cant edit this.

so.. plugins is fine.
problem is at forum.

**Comment by barisusakli** [comment]
No error messages in logs?

**Comment by necrosoul** [comment]
@barisusakli  where is log? i checked ./nodebb dev and if i press post menu button - window is not open. And at nodebb dev (log) i seen nothing about this.

**Comment by necrosoul** [comment]
@barisusakli  i created new txt file which represents where is bug located.

I deleted good stuff and remains only bugged text
[bugshere.txt](https://github.com/NodeBB/NodeBB/files/2274444/bugshere.txt)

Maybe it is markdown conflict? or something else?

**Comment by necrosoul** [comment]
@barisusakli  @julianlam 

found bugged text (more accurate)

this is text which cause bug

`То есть использовать для выравнивания нужно блочный элемент `<div>`Это нужно только для заголовка таблицы (верхняя строка) другие строки могут обходится и без этого элемента.`

**Comment by barisusakli** [comment]
@necrosoul I posted that content here with no problems https://community.nodebb.org/topic/12734/test-topic/4. Do you have markdown plugin disabled?

**Comment by necrosoul** [comment]
> @necrosoul I posted that content here with no problems https://community.nodebb.org/topic/12734/test-topic/4. Do you have markdown plugin disabled?

Hello! 
I use 
- Sanitize HTML plugin
- default composer and markdown plugin enabled (with unsanitized html checked)

That is it.

And in sanitize html i put <div> code with options.

**Comment by barisusakli** [comment]
That could be your problem try unchecking unsanitized html and try again.

**Comment by necrosoul** [comment]
> That could be your problem try unchecking unsanitized html and try again.

Maybe but this could be work with unsanitized html.
Only this tag corrupting topic if i dont use <xmp></xmp> tag
test it. 

problem if i use <div> without closing tag. but if use <xmp> <div> </xmp> all is ok. But automatically adding closing div after div tag.

**Comment by julianlam** [comment]
Sounds like it might be an issue with the sanitizehtml plugin.

When you start NodeBB, start it with `./nodebb dev`, and then try again. You should then be able to see the error messages as they come in.

**Comment by necrosoul** [comment]
> Sounds like it might be an issue with the sanitizehtml plugin.
> 
> When you start NodeBB, start it with `./nodebb dev`, and then try again. You should then be able to see the error messages as they come in.

Maybe it is plugin error, but i cant use < code > tag too at div tag and few other tags.  

When i started nodebb dev - no errors. But if i use without closing tag - post being to be bugged and i cant edit it and topic too. only delete.

Same bug was after creating post with redactor- composer and switchin back to default. same bugged post.

Try to test it Julian. default markdown + composer default + sanitize html (div tag + attributes like style ) and try to add only opening DIV

**Comment by julianlam** [comment]
So, to be clear, you're saying that if you don't specify a closing tag, then the HTML following the post is bugged?

**Comment by julianlam** [comment]
Unfortunately, the sanitizehtml plugin is not meant to "correct" html, and it is up to your community to ensure that non-bugged html is entered when allowing HTML input.

... and I recognise that that's a crazy requirement, but this is exactly the reason why we use markdown and WYSIWYG editors, so that no direct HTML input is allowed. :frowning:

**Comment by necrosoul** [comment]
> So, to be clear, you're saying that if you don't specify a closing tag, then the HTML following the post is bugged?

YEs.. but no.

I writed CODE tag and DIV tag was in this CODE tag. but without closing div.

SO i mean that CODE tag need to clear DIV like clearin other tags.. but DIV cant be cleared.



> and I recognise that that's a crazy requirement, but this is exactly the reason why we use markdown and WYSIWYG editors, so that no direct HTML input is allowed.

It is bad, cause cant use bootstrap elements, without them is bad.

NodeBB supports bootstrap but you cant use it,, it is sad.

**Comment by julianlam** [comment]
There are very *very* few reasons why a forum needs to allow HTML input.

You can use code fences and backticks to write code in Markdown. Likewise, Redactor and Quill support code blocks.

You can write all the bugged HTML you want in those code blocks, they will be properly handled.

You're asking me to proactively fix an issue where someone enters in bugged HTML, **after** you have removed every single post-processing plugin that would catch something like this. It's not happening.

**Comment by necrosoul** [comment]
> There are very _very_ few reasons why a forum needs to allow HTML input.

Julian here is link - see what i need in HTML

https://bootswatch.com/3/cerulean/

that is all.

for example like here - https://blizzardfans.ru/topic/9/гайд-по-редактору-сообщений-и-использование-спец-кодов/2

this is nice.

// i am not a programmer or developer.
i cant write some plugins.. 




> You're asking me to proactively fix an issue where someone enters in bugged HTML, **after** you have removed every single post-processing plugin that would catch something like this. It's not happening.

I just enabled HTML in markdown plugin and installed SANITIZE HTML + entered tags / attr. 

Maybe plugin is bugged, dont know. But i think error will persist if i disable sanitizer.

Hope that i was wrong.

so... NodeBB is great script. I recommend it to all. 

if this fix cant be repaired - it is bad but  i will use it.

//
Good idea to make option in markdown plugin to choose HTML tags  which will be blocked and others to be enabled (attr too).

//p.s Julian how about polls .. this is very very needed option.

good luck in development)) thx for answers.

**Comment by BenLubar** [comment]
May I suggest htmlcleaner? It's what we use on [what.thedailywtf.com](https://what.thedailywtf.com/topic/25800/6694)

**Comment by necrosoul** [comment]
> May I suggest htmlcleaner? It's what we use on [what.thedailywtf.com](https://what.thedailywtf.com/topic/25800/6694)

what is html cleaner?
