### ISSUE TITLE
Moderators don't get flag notification 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6695]
- **NodeBB version:** 1.10.1
- **Database type:** mongo 
- **Database version:** 3.2.11
Hi, moderators don't get flag notification. But I remember we had this problem and It was solved: https://github.com/NodeBB/NodeBB/issues/6314

**Comment by barisusakli** [comment]
Do they have notification enabled for flags in their user settings?

![image](https://user-images.githubusercontent.com/2583394/43900287-640f2c00-9bb2-11e8-830f-f96605fc874d.png)

**Comment by mohammadhassan99** [comment]
Seems like I was wrong. I didn't enable the notification for flags.
Thanks 😊
