### ISSUE TITLE
Admin can't view (possibly among other things) others' Custom CSS.

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#6705]
Admin cannot view another user's Custom CSS. May extend to other items on <tt>/user/`$USERNAME`/settings</tt> - I haven't checked.

Discovered, and mentioned at: https://what.thedailywtf.com/post/1398298

Screenshots posted there (note the difference in URL and the similarity in User CSS):

![screenshot from 2018-08-16 19-03-04](https://user-images.githubusercontent.com/3939886/44226421-f6519a00-a187-11e8-9156-690e38e7d419.png)
![screenshot from 2018-08-16 19-01-57](https://user-images.githubusercontent.com/3939886/44226423-f6ea3080-a187-11e8-87f2-96d06c758154.png)

**Comment by BenLubar** [comment]
This is TDWTF-specific.

**Comment by julianlam** [comment]
I don't understand the screenshots... the CSS looks the same, are you saying it should be blank for the other user?

**Comment by pauljherring** [comment]
> You should hit save so I get the benefit of your CSS too

That thought just crossed my mind - what /would/ happen?

**Comment by BenLubar** [comment]
@julianlam as I mentioned above, it's this line of code:

https://github.com/NodeBB/NodeBB/blob/f1a6537fc2dada85b539f00dd17545828f93fb49/src/controllers/accounts/settings.js#L89

It should be giving the ID of the user being edited to the hook, not the ID of the currently logged-in user.

**Comment by barisusakli** [comment]
@BenLubar the uid being viewed is in `settings.uid`

**Comment by pauljherring** [comment]
Does closure mean it's been fixed? I don't see any changes linked...

**Comment by barisusakli** [comment]
It needs to be fixed in the tdwtf plugin that adds the custom CSS, @BenLubar can update it to use the correct uid

**Comment by pauljherring** [comment]
Ah - ta.
