### ISSUE TITLE
installed node for viscose editor but cannot use node command

### ISSUE THREAD

**Issue by Tsukiij** [NodeBB/NodeBB#6707]
I downloaded visual studio code for a prep course which requires downloading node as well. However, I cannot do any exercise using the node command. 
 The result I get is 
node 01-current-year
module.js:549    throw err;
    ^

Error: Cannot find module '/Users/Tsukiyume/Downloads/bootcamp-prep-master-2/pre-work-workshops/02-values-and-types/01-current-year'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

This result shows up in both the vscode terminal and my mac terminal. Any help or suggestions is appreciated!

**Comment by julianlam** [comment]
You'll probably want to contact your professor about this.

On the other hand, this is the issue tracker for NodeBB, which uses Node.js, but is not Node.js. Sorry about that.

**Comment by Tsukiij** [comment]
The course doesn't have an onsite professor. Can you direct me to a forum?
