### ISSUE TITLE
Search: Multiple categories or searchChildren doesnt return any search results

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6712]
Using Nodebb 1.10.1 with Redis Database.

I'm fairly sure 'searchChildren' was working before the 1.10.1 upgrade from 1.8.0 we did.

Example querystring for a failing requests 

term=<TERM>&categories[]=ID&searchChildren=true
term=<TERM>&categories[]=ID&categories[]=ID

whereas the following works

term=TERM&categories[]=ID

The redis commands for a failing request look like this

["zinterstore", "nodebbpostsearch:cid:temp", 5, "nodebbpostsearch:cid:ID:id" (*5)]
["zinterstore", "nodebbpostsearch:tempFinal", 2, "nodebbpostsearch:cid:temp", "nodebbpostsearch:content:CONTENT:id"]
["zrevrange", "nodebbpostsearch:tempFinal", 0, 499]
["zremrangebyrank", "nodebbpostsearch:cid:temp", 0, 499]
["zremrangebyrank", "nodebbpostsearch:tempFinal", 0, 499]

whereas the successful request has the following commands

["zinterstore", "nodebbpostsearch:tempFinal", 2, "nodebbpostsearch:cid:ID:id", "nodebbpostsearch:content:CONTENT:id"]
["zrevrange", "nodebbpostsearch:tempFinal", 0, 499]
["zremrangebyrank", "nodebbpostsearch:tempFinal", 0, 499]

I cant see anything wrong in the code prior to that but my knowledge of redis is barely classed as knowledge.

I cant see any of the temp datasets the commands try to access, though if they are temp I might not be accessing them at the right time.

Any ideas?

**Comment by barisusakli** [comment]
What is the version on dbsearch? Can you try with 2.0.17?
