### ISSUE TITLE
Top topics in Available Widgets

### ISSUE THREAD

**Issue by vennmann** [NodeBB/NodeBB#6713]
Can we add top topics missing in available widgets?
I see all others, except this.
Also would it be a good idea to add, popular, top topics for daily, monthly as well. Currently it defaults to all
Thanks

**Comment by vennmann** [comment]
Hey guys 
I still don't see top topics in the available widgets, 
cheers

**Comment by barisusakli** [comment]
Looks like widget-essentials was published but wasnt added to package.json.
