### ISSUE TITLE
Edited Posts showing unedited content to some users

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6716]
We've been having this issue while using Nodebb 1.10.1/Redis database.

It seems to be intermittent but the edited post doesn't always show the latest edit. To the user who edited it, it will update but some users see an old edit while others will see latest edit.

It seems like a cache issue to me (maybe here - https://github.com/NodeBB/NodeBB/blob/9d202d9be938168bef064e0e8b22033aa0c2b66f/src/posts/parse.js#L41 but I havent been able to reproduce it on a debuggable environment even after removing the env check).

In an environment I did recreate the issue on, I checked and compared the API response and the only difference (excluding online status/view count) was the content property.

Do you have any ideas what might be causing this issue?

**Comment by julianlam** [comment]
Are you running multiple instances of NodeBB?

**Comment by uplift** [comment]
Yeah we having multiple instances with clustering. Server setup not my expertise but I assume the cache is per instance?

**Comment by julianlam** [comment]
Yes, this is likely the culprit... pinging @barisusakli for his thoughts... might be a small config change is required on your end..

**Comment by barisusakli** [comment]
@uplift what is your setup like? Is it multiple nodebb instances on the same server or single nodebb instances on different servers?

**Comment by uplift** [comment]
Single nodebb instance on different servers.

**Comment by barisusakli** [comment]
In that case, you can add `isCluster: true` to config.json on all those servers and that should fix the issue.

**Comment by uplift** [comment]
Thanks, I'll give that a try tomorrow and let you know. Is there any documentation on what that config does so I can evaluate any issues we might encounter on our setup? Does it just setup the pubsub provider?

**Comment by barisusakli** [comment]
Pretty much yeah, it is set automatically if you have multiple nodebb instances on a single server and use `loader.js` to start. But if you have single nodebb instances on separate servers you need to set it manually.

**Comment by uplift** [comment]
Apologies for not closing this sooner. The config seems to have done the trick.  Thanks @barisusakli and @julianlam for the help
