### ISSUE TITLE
customizing privileges for each moderator

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6718]
Hi, I couldn't find any customization for moderators. Don't you think that It is better to have customization for it?

**Comment by barisusakli** [comment]
Do you mean separate privileges for each moderation action like lock topic / pin topic etc?

**Comment by mohammadhassan99** [comment]
I mean every privileges just belong to moderators for example: Account info, post edit history , list of IPs, removing , editing and locking topics and ability to see removed posts. I think customizing each of these privileges can be an excellent idea. 
Also if we can customize these for each categories, it is very good :)

**Comment by pitaj** [comment]
There's already an issue for privilege improvements. #5736
