### ISSUE TITLE
Twitter OAuth changes

### ISSUE THREAD

**Issue by pauljherring** [NodeBB/NodeBB#6719]
`/admin/plugins/sso-twitter` links to a deprecated (as of July '18) URL: https://apps.twitter.com/

> As of July 2018, you must [apply for a Twitter developer account](https://developer.twitter.com/en/apply/user) and be approved before you may create new apps. Once approved, you will be able to create new apps from developer.twitter.com.
>
> For the near future, you can continue to manage existing apps here on apps.twitter.com. However, we will soon retire this site and consolidate all developer tools, API access, and app management within the developer portal at developer.twitter.com. You will be able to access and manage existing apps through that portal when we retire this site.

**Comment by RikoDEV** [comment]
You should report this here: https://github.com/julianlam/nodebb-plugin-sso-twitter

**Comment by pauljherring** [comment]
https://github.com/julianlam/nodebb-plugin-sso-twitter/issues/29

**Comment by julianlam** [comment]
Thanks @pauljherring
