### ISSUE TITLE
Cannot change profile picture (maximum file size error)

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6722]
- **NodeBB version:** 1.10.1
- **Database type:** mongo 
- **Database version:** 3.2.11

Hi, the maximum file size of the profile picture in our forum is 256 Kilobyte. But It doesn't allow user to upload 180 Kilobyte picture !! 
For example we tried to upload [this picture (size= 180 Kilobyte):](http://uupload.ir/files/vczb_rbvr_img_20180825_215755_441.jpg) . But it says the pic is big.

![2018-08-28_013646](https://user-images.githubusercontent.com/31972226/44686469-94384500-aa63-11e8-87e1-0bf2f3f247b1.jpg)

**Comment by mohammadhassan99** [comment]
🤔

**Comment by pitaj** [comment]
My guess is that it's converting the picture from a compressed jpg to an uncompressed png before uploading it, resulting in the sizes looking different.

**Comment by mohammadhassan99** [comment]
@pitaj So how can we confirm that? Do you have any idea?

**Comment by mohammadhassan99** [comment]
@pitaj But in result, the profile picture format is jpeg !

**Comment by pitaj** [comment]
It could just be turning down the jpeg compression, too. It's hard to say.

**Comment by barisusakli** [comment]
Yes it's the cropper, it converts the image to a base64 string and that gets caught here https://github.com/NodeBB/NodeBB/blob/master/src/user/picture.js#L92. even though the original image was <256kb the intermediate data is >256kb, haven't found an elegant fix yet.
