### ISSUE TITLE
User info broken in a subthread

### ISSUE THREAD

**Issue by Jane-N** [NodeBB/NodeBB#6724]
- **NodeBB version:** v1.7.4. and v1.10.1. (the bug is most likely in all the versions between as well)
- **NodeBB git hash:**  8e61d739c76a49895db1f874ec4c6259b89b2c26

- **Database type:** mongo 
- **Database version:** 3.2.9

- **Exact steps to cause this issue:**

1. Find a thread where users have used the small Reply button below a specific post to reply. 
2. Expand the subthread by clicking on "X replies Last Reply Y minutes ago"
3. Click on one of the avatars in the subthread to view user's info.

- **What you expected:**

To see the user's information the same way it's visible when clicking user's avatar on the "first level".
- **What happened instead:**

All it shows is the black box, the online/offline status dot, @ symbol, and words 'posts' and 'reputation'. There's no avatar, username, post and reputation count.

More info: https://community.nodebb.org/topic/12744/user-info-broken-in-subthread

**Comment by barisusakli** [comment]
Thanks fixed in persona
