### ISSUE TITLE
Benchpress Function arguments

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6725]
Nodebb 1.10.1

I have a template override of topic.tpl that has a section that looks something like this with a custom template helper function

    
       
           {function.displayStuff, ../../ }
       
    

I would expect the '../../' to pass in the parent topic to the template helper as ../../thumb works correctly in the IF statement and if I pass in ../../thumb to template helper the thumb url is passed correctly.

I also have another template that I pass a topic direct to same helper function and that displays correctly so I know the helper is registered correctly.

Am I missing a trick to passing in a parent object in an iteration?

FYI: This is the difference in the compiled template between passing '../../thumb' and '../../'

helpers.__escape(helper(context, helpers, 'displayStuff', [guard(context && context['thumb'])]))
helpers.__escape(helper(context, helpers, 'displayStuff', [guard(context && context[''])]))

**Comment by pitaj** [comment]
What is the data you're passing in, and what do you want to see? You don't need to use relative paths to access properties of the context object. You just use the property name.

Have you looked at the [benchpress docs](https://github.com/benchpressjs/benchpressjs/blob/master/docs/readme.md)?

**Comment by uplift** [comment]
Ah thanks, that did the trick! Much appreciated.
