### ISSUE TITLE
req.uid does not change on passport authentication

### ISSUE THREAD

**Issue by LudwikJaniuk** [NodeBB/NodeBB#6727]
- **NodeBB version: 1.9.3** 
- **Database type:** mongo
- **Exact steps to cause this issue:**

1. Use your own passport strategy from a plugin
2. Use the `action:middleware.authenticate` hook.
3. In the hook, call `passport.authenticate(<my strategy name>...`
4. strategy successfully returns a user, that is, logs him in
5. according to its docs, passport correctly sets `req.user` to the new user object, no problem.
        
- **What you expected:**
I expected `req.uid` to be in accordance with the new user object
- **What happened instead:**
`req.uid` looks like it's set only once (from [here]("action:middleware.authenticate")), way before authentication middleware has a chance to run. It seems like it doesn't get updated after a login.
- **Proposed fix:**
Have it be set later. Alternatively, update it after a successful login (maybe passport.login has a hook?). But that would make it even more confusing to keep "the things that should happen on login" synced.

**Comment by barisusakli** [comment]
Hmm, isn't req.uid set on every request depending on req.user?  https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L23-L31

**Comment by julianlam** [comment]
Actually, it's not, so @LudwikJaniuk's issue has some merit here.

I have a couple distinct instances where I have to set `req.uid` manually:
* https://github.com/julianlam/nodebb-plugin-session-sharing/blob/1a1196c7fc439ea9f882e0b791f45b8bc65bcf7a/library.js#L438
* https://github.com/NodeBB/nodebb-plugin-write-api/blob/4c98fbe3440d462d995a43ba4819f6d40f00646c/routes/v2/middleware.js#L30

Now, albeit the latter example is me overriding `req.uid`, so it's mainly just the session-sharing example.

**Comment by barisusakli** [comment]
Would this change work then?

```
middleware.authenticate = function (req, res, next) {
		if (req.loggedIn) {
			return next();
		}

		if (plugins.hasListeners('action:middleware.authenticate')) {
			return plugins.fireHook('action:middleware.authenticate', {
				req: req,
				res: res,
				next: function(err) {
                                      req.uid = req.user ? parseInt(req.user.uid, 10) : 0;
                                      next(err);
                                },
			});
		}

		controllers.helpers.notAllowed(req, res);
	};
```

Not sure if the next function receives any other params?

**Comment by LudwikJaniuk** [comment]
@barisusakli No, I think action hooks don't have to return anything, so that next function should be correct.

That solution would work, and it's basically what I'm doing right now - I just manually set `req.uid` in my plugin. The problem I see is that this makes the code less DRY. More importantly, as I mentioned earlier, it gets harder for someone tinkering with authentication to know what attributes they need to set.

As an example, when I was writing my plugin I wondered what I need to set to make sure an user is "logged in" properly. Going after passport docs, I thought just setting `req.user` should be enough (and passport does this by itself, so I just need to call `passport.authenticate`). It turned out I was wrong: the code also relies on `req.uid` being correct when a user is signed in. And is there perhaps something more? Maybe. I have no way of knowing still, except waiting for bugs to happen.

Ideally, there should be one central point of "logging in" in the code - `passport.authorize` works. `req.uid` as it is right now breaks this assumption. So I think it should either be moved to be later in the middleware chain (but would this break anything that relies on it?), or the solution you're proposing should be implemented, that would update `req.uid` after an auth (but are there other places that invalidate it? What about @julianlam your examples?)

**Comment by barisusakli** [comment]
I think `req.loggedIn` and `req.uid` are the only modifications that happen [here](https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L22-L33).  It sounds like that should be turned into a function and called from `action:middleware.authenticate` next function.

**Comment by LudwikJaniuk** [comment]
Yeah. I think that would be a good solution.

**Comment by LudwikJaniuk** [comment]
Why is `action:middleware.authenticate` even an action hook? While trying to write a PR here, I'm looking at that `next` function in the params. What if two plugins register for this hook? Wouldn't they both call `next`? That looks like chaos to me, so i hope there's something I'm missing...
