### ISSUE TITLE
Users changing usernames starts giving 404 on old usernames profile URLs

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6735]
Basically this is creating lots of Google search console errors as people on our forum change their usernames and then they have had made many posts with their old names, now all those old names topics/ URLs start giving 404.

E.g https://chatrooms.talkwithstranger.com/user/morf

is there any way we can redirect the old 404 broken URLs to the new username profile url ?

**Comment by julianlam** [comment]
It could be done but we didn't do it on purpose because when you change a username the old name becomes freed up for use, and so you'd run into issues where a redirect would stop working because a new user registered under that username.
