### ISSUE TITLE
Active scope plugin failed

### ISSUE THREAD

**Issue by yoyoyohamapi** [NodeBB/NodeBB#6743]
- **NodeBB version:** 1.10.1
- **NodeBB git hash:** 37ca5a1c638faa3d120ab3f40b0c9e6a7b768563

- **Database type:** mongo
- **Database version:** v4.0.1

- **Exact steps to cause this issue:**
install scoped plugin
active plugin in admin panel
- **What you expected:**
Active scoped plugin
- **What happened instead:**
jQuery selector error, because `$('#@scope/nodebb-plugin-xxx')` is invalid
see: https://github.com/NodeBB/NodeBB/blob/37ca5a1c638faa3d120ab3f40b0c9e6a7b768563/public/src/admin/extend/plugins.js#L23

**Comment by pitaj** [comment]
Yeah it should be changed to 

    [id="plugin ID"]

Instead
