### ISSUE TITLE
Support custom npm client

### ISSUE THREAD

**Issue by yoyoyohamapi** [NodeBB/NodeBB#6744]
- **NodeBB version:** 1.10.1
- **NodeBB git hash:** 37ca5a1c638faa3d120ab3f40b0c9e6a7b768563

- **Database type:** mongo
- **Database version:** v4.0.1

- **Exact steps to cause this issue:**
execute `./nodebb upgrade`
- **What you expected:**
can custom npm client (just like yarn, tnpm, etc) before `./nodebb upgrade`
- **What happened instead:**
Only npm supported

**Comment by barisusakli** [comment]
You can add `"package_manager": "yarn"` to config.json to use `yarn`
