### ISSUE TITLE
Nodebb Write Api plugin causing error due to no req.user

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6751]
NodeBB 1.10.1 
Database Redis

Not sure if this is for Nodebb core or the write api plugin.

We use session sharing plugin to log user in from their Website Account. When a user logs in for first time and hits a url that has the checkGlobalPrivacySettings middleware, then nodebb-write-api plugin throws an error.  

We have meta.config.privateUserInfo set to true so when it hits the checkGlobalPrivacySettings middleware on the first pass through req.loggedIn isn't set as req.user isn't set  in the Auth module so it calls the authenticate middleware.

https://github.com/NodeBB/NodeBB/blob/cfe0e690b5514b786b0ea56d3f65ff22718c06eb/src/routes/authentication.js#L30
https://github.com/NodeBB/NodeBB/blob/cfe0e690b5514b786b0ea56d3f65ff22718c06eb/src/middleware/user.js#L71-L73

Without the write api plugin activated it passes through the authenticate middleware with no issues and no errors. With the write api plugin activated it hits the fireHook as the plugin has a listener.

https://github.com/NodeBB/NodeBB/blob/c8d3c3197ba3025ed395e400f8cb0b312fac790e/src/middleware/user.js#L16-L30

In the write api with our current settings it falls out the bottom of the requireUser middleware and throws the error 

    {
        "code": "not-authorised",
        "message": "A valid login session was not found. Please log in and try again.",
        "params": {}
    }

https://github.com/NodeBB/nodebb-plugin-write-api/blob/1ccac757c52ebe94eadc2334404882ec619ee2ce/routes/v1/middleware.js#L101

Refreshing the page on this error loads fine as req.user is in the session then and doesn't go through authenticate middleware flow.

I see master has had some updates but I've tried them locally and it doesnt fix this issue.

Any ideas on how to fix this? Is it an issue with req.loggedIn not being set soon enough or the pugin throwing the error? Should an action hook error?

**Comment by barisusakli** [comment]
Maybe session-sharing plugin has to set req.loggedIn here as well ? https://github.com/julianlam/nodebb-plugin-session-sharing/blob/master/library.js#L438

**Comment by uplift** [comment]
Tried setting it there locally and I cant replicate the issue then. Are there any side effects with setting it there?

**Comment by barisusakli** [comment]
I think it should be fine since `req.uid` is set there as well, @julianlam can take a look as well and add it into the plugin if it's ok.

**Comment by julianlam** [comment]
Yes, @barisusakli looks to be correct. When I wrote that line, I was not aware `req.loggedIn` also needed to be set.

To be honest, we shouldn't ever be setting anything in `req` :thinking: I will add it but was there a specific reason why we didn't do `req.session.loggedIn`? We already have `req.session.uid` too.. just curious about NodeBB's often-unseen rough edges :smile:

**Comment by julianlam** [comment]
v4.2.7
