### ISSUE TITLE
User banning and session sharing

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6758]
NodeBB 1.10.1
Database Redis

In our current setup we have a Website Account (WA) which our users sign in to and using the session sharing plugin, this logs them in/creates user in the forum using a cookie.

When we ban somebody from the forum, they are only banned from the forum so they still have access and are still logged in to the rest of their WA. The way banning currently works using session sharing is that the user gets displayed a ban message and is then logged out of the forum and is then treated as a guest user on the forum.

This causes confusion as the user is presented with 'login to reply' buttons on topics even though they are logged in to their WA. As they are now a guest to the forum there is no way to identify them as a banned user compared to a genuine guest user to display another/hide button.

Whats the best way to handle this use case? Is it possible to not log them out when banned and add them to a banned group with privileges the same as a guest and then have a isBanned flag/ban data passed to templates to handle the use case?

**Comment by julianlam** [comment]
v4.3.0
