### ISSUE TITLE
checking email format when registering

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6760]
Hi, when a user want to write the email address in registering form, if he writes this: ```nodebb@gmail``` , nodebb doesn't warn the user to write the right format (nodebb@gmail.com) .

**Comment by pitaj** [comment]
Almost every email address you can think of is valid, including that one. The only way to make sure emails are valid is via email confirmation, which NodeBB supports. Otherwise, essentially all we can do is check that the field has an `@` symbol.
