### ISSUE TITLE
enhancing ip search algorithm

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6761]
Hi, in ACP when you want to search users via ip addresses, the result will be shown only when the searched ip is equal to the result. And also it will show the last ip that user had.
I think the search algorithm could be better. As you know Ips could change a little when new connection is established.
for example when you type ``` 5.127``` , nodebb shows lots of accounts with the ip that starts with ```5.127``` . Then when you type the address completely, the matched results will be shown.

**Comment by uplift** [comment]
+1 for this.

Being able to add a wildcard into the search would be useful for searching for users that create multiple accounts. We're running into this problem where its difficult to identify users using the same or similar IPs that might already have banned accounts.

**Comment by PatheticMustan** [comment]
+1 It would also be nice to search multiple IPs at once. (Like when a user has more than 3 IPs)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/8458/files
