### ISSUE TITLE
Moderators have both Account info and account/sessions

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6765]
- **NodeBB version:** 1.10.1

I didn't check for admins

![2018-09-16_001853](https://user-images.githubusercontent.com/31972226/45590093-651c4180-b946-11e8-96d9-5b80e3c7da92.jpg)

**Comment by julianlam** [comment]
Hm, you're right... looks like there's no need for mods/admins to access account/sessions :smile:
