### ISSUE TITLE
Images from recent posts

### ISSUE THREAD

**Issue by Arch1tect** [NodeBB/NodeBB#6776]
Trying to make my nodebb front page show recent topics' images like pinterest front page. I looked at `api/recent` but there's no topic content data except the title.

**Comment by julianlam** [comment]
For organisational purposes, we'll leave this issue open as it is the first issue requesting it.

Earlier changes in core codebase are now associating uploads with individual pids:

https://github.com/NodeBB/NodeBB/blob/cba5aa975ea20b509c1766f3166d048103001afe/src/posts/uploads.js#L41-L42

@psychobunny and I have discussed briefly about extending this to allow for a more dynamic home page showing uploaded images in the topic listing, category listing, etc, and **recent** is no exception.

Eventual goal is to cut out all traces of topic_thumb as it is not a well-known nor well-supported feature of NodeBB.

**Comment by chocolate012** [comment]
Waiting for this, it will help me [here](https://community.nodebb.org/topic/14522/photos-masonry-or-carousel/2?_=1582878913813)

**Comment by barisusakli** [comment]
thumbs are available on /recent and /category now 
![image](https://user-images.githubusercontent.com/2583394/236060272-a339eb66-d7a0-4354-b531-3eb51e1eef36.png)
