### ISSUE TITLE
 I can't bind url correctly

### ISSUE THREAD

**Issue by bigtaotao** [NodeBB/NodeBB#6779]
first，i edit the config.json and it look like that:
{                                                     
    "url" : "https://.myurl.com",                     
    "secret": "7dbe9e9d-c932-4a56-899b-d0bcdc3b77dc", 
    "database": "mongo",                              
    "port": "4567",                                   
    "mongo": {                                        
        "host": "127.0.0.1",                          
        "port": "27017",                              
        "username": "test",                         
        "password": "test",                            
        "database": "nodebb"                          
    }                                                 
}                                                     
i EXCEPT i can Visit the forum by “www.myurl.com" OR "myurl.com"

BUT it doesn't work

what should i do?

**Comment by bigtaotao** [comment]
when i visit by "myurl.com" it worked
but if i use "www.myurl.com",it prompt ”The connection to the test is broken, we are trying to reconnect, please be patient“

**Comment by julianlam** [comment]
You'll want to configure apache or nginx to redirect www to myurl.com, or vice versa. We can support both but it is not recommended.
