### ISSUE TITLE
Pass in List-Id and List-Unsubscribe headers in emails

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6790]
We currently do not pass any headers on to email clients or via the local fallback. We can start by sending in List-Id (a unique string for each email type/user) and List-Unsubscribe (a plain URL to the user settings page).

**Comment by julianlam** [comment]
Relies on downstream emailer plugins for support:

* nodebb-plugin-emailer-sendgrid@2.2.0 and up supports this

**Comment by BenLubar** [comment]
Would it be worth forking the amazon emailer at this point? I don't think the original author still comes here.

**Comment by julianlam** [comment]
Probably, though smoothest transition would be granting you commit and publish access to the repo and npm package respectively
