### ISSUE TITLE
noddebb login page

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#6805]
`https://forum.sanatisharif.ir/login`
![image](https://user-images.githubusercontent.com/9453178/46257292-10d79c80-c4c4-11e8-9d04-260b82c5e8a1.png)

`https://forum.sanatisharif.ir/login?local=1`
![image](https://user-images.githubusercontent.com/9453178/46257301-28af2080-c4c4-11e8-9961-54675937be95.png)

**Comment by barisusakli** [comment]
What's the issue? `?local=1` is supposed to give you the login form, even if local logins are disabled.

**Comment by sohrabafard** [comment]
fixed!

**Comment by pitaj** [comment]
What was the issue?
