### ISSUE TITLE
Profile page seems to 404 if username includes Cyrillic А

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#6808]

**Comment by pitaj** [comment]
Is it only Cyrillic or just any non-ascii character.

**Comment by julianlam** [comment]
Wow, email reply to issues is a little foobar'd :laughing:

**Comment by barisusakli** [comment]
`E_NOREPRO`
https://community.nodebb.org/user/%D0%B0%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9-%D0%BA%D0%B0%D0%BB%D0%B8%D0%BD%D0%B8%D0%BD
