### ISSUE TITLE
emoji prevents pages from loading

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#6818]
2018-10-09T02:05:59.244Z [1988] - error: /recent
 Error: ENOENT: no such file or directory, open '/home/nodebb/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'

**Comment by pitaj** [comment]
What context is this in? I imagine it only applies to pages which involve posts being parsed, right?

**Comment by barisusakli** [comment]
Any page that parses posts I believe.
