### ISSUE TITLE
[Composer] Zen Mode

### ISSUE THREAD

**Issue by cnvo** [NodeBB/NodeBB#682]
http://www.zenpen.io/

Tell me what you think of implementing that in the composer... it looks really nice; just discovered it today and is fun writing on.

**Comment by julianlam** [comment]
Re: dillinger.io
> I'm all for something like that too, except their live preview consists of making calls to a server, which then converts the markdown to HTML, and then sends it back to the client.
>
> Seems silly, considering chjj/marked is supposed to be able to work client-side.

Hehe :laughing: -- how times change... good to know 2013's @julian would find nodebb-plugin-markdown silly.

**Comment by exomarty** [comment]
@julianlam just wondering maybe button of zenmode should be hidden on mobile cause it makes nothing
not sure if its planned for the future
good work btw

**Comment by julianlam** [comment]
On mobile, Zen mode removes the address bar. Any additional space is good.

Thanks for the kind words :smile:

**Comment by exomarty** [comment]
I guess not on iOS 😢

**Comment by pichalite** [comment]
@julianlam it needs to either work on both iOS and android or hidden on mobile.
