### ISSUE TITLE
Looks like your connection to NodeBB was lost, please wait while we try to reconnect.

### ISSUE THREAD

**Issue by bpmottathai** [NodeBB/NodeBB#6833]
logs give below error
```
heroku[router]: at=info method=GET path= "/socket.io/?EIO= 3&transport= polling&t=MPk3FXO" host=forum.keralahost.in request_id=2e930357-1ffbfab-49179488a37c fwd="117.247.116.129" dyno=web.1 connect=1ms service=3ms status=403 bytes=185 protocol=http
```
Please help
First it was working fine. Then I added custom domain. Now it give this error. 
Without custom domain, it works fine.
https://forum-keralahost.herokuapp.com
Please help.

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
