### ISSUE TITLE
./nodebb setup hangs at npm dependency installation

### ISSUE THREAD

**Issue by EvaLok** [NodeBB/NodeBB#6845]
- **NodeBB version:** 
1.10.2
- **NodeBB git hash:** 
d84030d55f154b4b7ad81931498875e15d264941

- **Database type:** mongo, redis, or postgres
redis (n/a)
- **Database version:** 
4.0.11 (n/a)

- **Exact steps to cause this issue:**
```bash
./nodebb setup
```

- **What you expected:**
setup

- **What happened instead:**
freezes at npm install
```bash
$ ./nodebb setup
Dependencies outdated or not yet installed.
Installing them now...

npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
^C           ......] | extract:emoji-datasource-google: sill extract emoji-datasource-google@^3.0.0 extr
^C

```

i tried several times, and it always freezes at the `emoji-datasource-google` dependency. i also tried manually running `yarn install` and it also gets stuck

```bash
$ yarn install
yarn install v1.10.1
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning less > request > hawk > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning less > request > hawk > boom > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning less > request > hawk > sntp > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
[3/5] Fetching packages...
[##############################################################################################] 889/893
```

**Comment by EvaLok** [comment]
i was able to solve this by installing nodebb locally and copying the `node_modules` directory along with `package-lock.json` to the server, and then running `./nodebb setup`, which allowed me to get through the database and other configuration setups

**Comment by barisusakli** [comment]
sounds like a network issue, not much we can do
