### ISSUE TITLE
Markdown tables can't start with empty cells since nodebb 1.10.2

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#6856]
- **NodeBB version: 1.10.2** 
- **NodeBB git hash: ab7657d ** 
- **Database type: mongo**
- **Database version: 3.6** 
	1. First I did this: upgrade to 1.10.2
	2. Then, all existing and new Markdown tables with empty first cells where broken
- **What you expected: empty first cells**
- **What happened instead: cells moved to left side  **

Markdown tables can't start with empty cells since nodebb 1.10.2

downgrade to 1.10.1 solves the problem

**Comment by julianlam** [comment]
julianlam/nodebb-plugin-markdown#92
