### ISSUE TITLE
Cannot edit messages in chat

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6858]
- **NodeBB version:** 1.10.2
- **Database type:** mongo

Hi, when I type several messages in chatroom, just the first message is editable and deletable.

For example I sent these messages:
First: Hello
Second: How are you?

Just ```Hello``` can be edited.

**Comment by julianlam** [comment]
Yes this is an issue we're working aware of, thanks for reporting

https://github.com/NodeBB/nodebb-theme-persona/pull/431

**Comment by mohammadhassan99** [comment]
Hi @julianlam , did you solve this problem?

**Comment by julianlam** [comment]
Now tracked in nodebb/nodebb-theme-persona#442
