### ISSUE TITLE
Unread counter only updates on page change/refresh?

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#6883]
This isn't a feature request nor bug report. More a question and then it might mutate into a feature request or bug report :)

I'm noticing that if I stay on the forum, I'll get notifications via the websocket connection and I'm notified. But the indicator for unread topics goes only up, when I change the page or refresh it. Is this intentional? If it is intentional what is the reasoning for it? I would kind of like it when the unread counter updates just asynchronously without me having to refresh the page.

**Comment by barisusakli** [comment]
The unread code only pushes new topics/posts to users that have performed an action in the last 5 minutes. We added this so we don't push data to tons  users who just leave a tab open on the forum.  Although thinking about it 5 minutes is rather short maybe we can increase it to 30mins.

**Comment by Dravere** [comment]
Or could we make this a setting so forums with higher traffic could have this lower and those with lower traffic higher?

**Comment by julianlam** [comment]
What if we combined a higher threshold with page/tab focus change? No need to update if tab not in focus...

**Comment by Dravere** [comment]
But if the user would reactivate the tab, you would then ask for the amount of unread topics? Wouldn't this be more demanding than just sending out updates via websockets? A fresh request would need to actually compute and collect the information. If there is just a small packet when a new post happens that would probably be much less taxing.

**Comment by julianlam** [comment]
Yes, that is indeed true, although the number of people focusing a tab (after it having timed out) is miniscule...

**Comment by Dravere** [comment]
Do you mean by it being minuscule the amount of people focusing the tab at the same time? Thus distributing the requests for unread topics? Might be the case. I don't have any useful data on this. My forum isn't that big, we perhaps have during high activity hours up to 40 logged in users connected to it. Since unread topic notifications are only distributed to them, that doesn't look much to me. But your solution probably isn't a problem either in my case.

I guess you have better performance data to make the right choice here. It would be great if there is no timeout at all. Thus for example deactivating the updates after the tab has lost focus for 5 minutes (or even less) and then re-update it, when the focus is regained and keep updating it while it is active, would be really nice.

**Comment by barisusakli** [comment]
Increased default to 30mins, but I left the other values at 5mins this should fix the issue with only updating when you navigate. https://github.com/NodeBB/NodeBB/blob/master/src/user/online.js#L30
Before both places used 5 mins so you weren't marked as online until 5minutes has passed.
