### ISSUE TITLE
do not render widgets on some topics but render on rest to avoid google ads warnings

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/NodeBB#6886]
We are using Google ads in a widget on our topic pages, while most of our forum content is family safe, but sometimes users post mature 18+ content, google gives us warning to remove google ads from those pages, but we cannot remove ads specifically from 18+ pages, if we remove or hide the widget, then the ads are removed from ALL topics.

Is there any way we can have a tag for e.g on a topic, and those widgets will not render on those specific pages with let's say 18+ tag, if there is no such tag present on a topic then the widgets should render normally. Or lets say if a topic falls under a specific explicit category do not render that widget. @fais3000

Any ideas?

**Comment by barisusakli** [comment]
This is doable with a plugin, assuming you are using a html widget here is how you can do it.

In plugin.json, notice the priorty is 11 this is bigger than the default of 10 so your plugin will run after the regular widgets.
```
{
	"hook": "filter:widget.render:html", "method": "renderHTMLWidget", "priority": 11
},
```

In library.js

```
myPlugin.renderHTMLWidget = function (widget, callback) {
    // ignore widgets that are not on topic.tpl
    if (!widget.templateData.template.topic) {
        return callback(null, widget);
    }
    const tags = widget.templateData.tags.map(tag => tag.value);
    callback(null, tags.includes('18+') ? null : widget);
};
```

That should be it, if the topic has a tag `18+` and it is on topic.tpl html widgets will be hidden.

If you have multiple widgets on topic.tpl and you only want to hide some of them then you could give them unique titles and check that as well.

**Comment by pitaj** [comment]
Probably should use Array#some instead of mapping first

    widget.templateData.tags.some(tag => tag.value == '18+');

**Comment by FaizanZahid** [comment]
Many thanks, let me try this and update you guys. if i do these changes and then update node bb again,  will i loose my changes, right?
