### ISSUE TITLE
更新后图标路径错误，显示不出来了。favicon.ico

### ISSUE THREAD

**Issue by guzhou-git** [NodeBB/NodeBB#6888]
版本1.10.2
更新后图标路径错误，显示不出来了。favicon.ico

**Comment by pitaj** [comment]
According to Google Translate:

>Version 1.10.2
>After the update, the icon path is wrong and the display is not displayed. Favicon.ico

**Comment by julianlam** [comment]
Does it get resolved if you re-upload the favicon?

**Comment by scottalanmiller** [comment]
If I re-upload, it gives this error (from the same file I just downloaded)...

NodeBB encountered a problem saving your changes. (Input file is missing or of an unsupported image format)

**Comment by scottalanmiller** [comment]
The log shows nothing when that error happens, too.

**Comment by guzhou-git** [comment]
正确的   /favicon.ico
正确的   /assets/favicon.ico
错误的   /assets/uploads/system/favicon.ico   更新后就是这个

**Comment by barisusakli** [comment]
Works fine on latest.
