### ISSUE TITLE
 Category dropdown in ACP Manage -> Privileges is not easily discoverable

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6899]
At least two users have complained that they did not know that "Global" was a dropdown, because of its styling. If this could be changed to a boxed material theme dropdown that would be best.

Originally NodeBB/nodebb-theme-persona#434

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/48376893-44e4d680-e69a-11e8-8c27-a9c7bd83a542.png)

**Comment by pichalite** [comment]
@julianlam This is just bad.

**Comment by julianlam** [comment]
@pichalite Go fix it then
