### ISSUE TITLE
post tool box cannot be opened correctly 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#6904]
Hi, when you want to reach the post tool box, it doesn't open completely and you cannot use it (it will be disappeared). We have this problem on mobile browsers such as ```Google chrome``` ,```Firefox``` and ``` Samsung browser``` . I didn't try rest of the browsers. Also when you resize the Google chrome in PC, this happens.
Google chrome version: 70
Firefox: latest version

Please watch this 👇 

![20181031_225236](https://user-images.githubusercontent.com/31972226/47813562-b51d5f00-dd60-11e8-9fc3-25b09a72b29d.gif)

**Comment by julianlam** [comment]
nodebb/nodebb-theme-persona#436
