### ISSUE TITLE
Plugin configuration not loading 

### ISSUE THREAD

**Issue by Amestri-s** [NodeBB/NodeBB#6909]
- **NodeBB version:** 
1.10.2
- **NodeBB git hash:** 

5d3c814d57a4dc28fdc0c799c8d1f7b9325ea8e8
- **Database type:** mongo, redis, or postgres
mongo
- **Database version:** 

v3.6.8
- **Exact steps to cause this issue:**

1. First I installed both plugins
2. Then I restarted NodeBB
3. Afterwards I tried to go to the configuration page 

- **What you expected:**
I expected both of the pages to load normally so I could configure them
- **What happened instead:**
Instead, they weren't loading and the loader constantly circled ages. I also get the error below when I go directly to the page link. I tried to put this in a code block but it didn't work. Sorry!

error Internal Error.
Oops! Looks like something went wrong!

/admin/plugins/dbsearch

Failed to lookup view "admin/plugins/dbsearch" in views directory "/root/nodebb/build/public/templates"

**Comment by Amestri-s** [comment]
I don't know why but it is suddenly working now.

**Comment by julianlam** [comment]
You have to rebuild as well as restart 🙂
