### ISSUE TITLE
Cant add to Admin group in Admin Panel

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6910]
Nodebb 1.10.1

When I try to add a new user to the Admin group in Admin Panel I get a not-allowed error. I believe its the addMember function below causing the issue

https://github.com/NodeBB/NodeBB/blob/5ae87294c3cd65ccbb65e00fb08160cc07d15bdf/src/socket.io/groups.js#L74-L79

**Comment by barisusakli** [comment]
Does it work on this page `/admin/manage/admins-mods`?
