### ISSUE TITLE
Email throttling

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#6911]
Hi Devs,

Currently sendmail is configured without throttling. That may lead to email account blocking when mass emails are sent (for example during daily digest).

One way to fix this is editing src/emailer.js, line 24, as follows:

```
Emailer.transports = {
         sendmail: nodemailer.createTransport({
                 sendmail: true,
                 newline: 'unix',

                 pool: true, // use pooled connection
                 rateLimit: true, // enable to make sure we are limiting
                 maxConnections: 1, // set limit to 1 connection only
                 maxMessages: 1 // send 1 emails per second
        }),
}

```
Perhaps allow these settings to be configured from the ACP?
Thank you!
JJ.

**Comment by djensen47** [comment]
This was not my initial problem with the digest email not getting sent. _However_, this weekend, I think I experiences this problem or something similar.

**Comment by djensen47** [comment]
_Please_, _please_, implement this or something like it.

**Comment by julianlam** [comment]
What happened?

**Comment by djensen47** [comment]
Since I set up NodeBB on Nov. 13, 2018, exactly 2 weekly digests have been successful. It always fails.

**Comment by djensen47** [comment]
I made these changes and everything is working. The trouble now is that I'll have to manually do this after every release unless they are added to the ACP.

**Comment by pitaj** [comment]
Yeah some of these settings are less than ideal, I think you probably can set `maxConnections` and `maxMessages` to a higher number.

**Comment by PostMidnight** [comment]
Thank you!

**Comment by djensen47** [comment]
This is great, you all are awesome!
