### ISSUE TITLE
parent category can be draged into children ,then appear endless loop，the server down

### ISSUE THREAD

**Issue by triple-kill** [NodeBB/NodeBB#6912]
- **NodeBB version:NodeBB v1.4.5** 
- **NodeBB git hash:** 

- **Database type:** mongo
Database version:mongod --3.x 

1. First I  drag the first category to it's second category
2. Then, the hole server cpu 100%, memory 100%,then the server down
3.in this case ,i can drag like that。 i want to konw the issue is my customized code or the frame?

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!

**Comment by julianlam** [comment]
Did you need help fixing the categories via database commands?

**Comment by triple-kill** [comment]
> Hello there! 😄
> 
> This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).
> 
> Remember, this issue tracker is just for bugs and defects in NodeBB.
> 
> Thanks!



> Did you need help fixing the categories via database commands?

1. yes,i want to check if any other exists. I have find and correct one endless loop by a foolish  method iterating category by    "db.objects.find("_key":"category:1")" .

1. although   server now can run ,but there appears another problem  by fixing endless loop. The parent category which I  have fixed it's parentCategory to 0  now can not  accessed 
by registered-users even administrators. I have set the category below:
![image](https://user-images.githubusercontent.com/7363048/48042599-32abf980-e1bd-11e8-8bb7-ae12d40da48f.png)

**Comment by barisusakli** [comment]
I realized you are on a really old version (1.4.5) this might have been already fixed, https://github.com/NodeBB/NodeBB/issues/3686

I tried moving a parent to its child and wasn't able to. If you can provide clear reproduction steps we can take a look.

**Comment by triple-kill** [comment]
I will try to upgrade
