### ISSUE TITLE
Deleted Post showing in category topic list for users with privileges

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6915]
Nodebb 1.10.1

As far as I can tell it appears that deleted posts still show in a category topic listing even if the user doesnt have privileges to view deleted posts. They appear greyed out and not clickable and when you go direct to the topic url, access is denied for users that dont have privileges.

As far as I can tell in Categories.getCategoryById and Categories.getCategoryTopics there are no privileges checks?

**Comment by julianlam** [comment]
In the teaser? Posts aren't shown in topic listing (aka `category.tpl`)... 

If the topics themselves are showing, make sure the topic is also deleted. Deleting OP should also delete the topic, but only if the topic has no replies.

**Comment by uplift** [comment]
I missed a bit in the workflow. It does go through modifyTopicsByPrivilege after and changes the topic title to This topic is deleted! (We have an added bit where it adds a snippet of the post which also shows even when deleted).

Shouldnt a deleted topic not show at all in the listing? (dependent on user privileges)

**Comment by uplift** [comment]
Ah okay, that makes sense. I guess our added post snippet doesnt help with how a deleted post is displayed but I can fix that my side in the plugin.

If there is a nice way to remove it from the list and keep topic count correct, I think that would be best from visual standpoint but happy to close this for now as a none issue.

Thanks for the reply!
