### ISSUE TITLE
WebSocket issue

### ISSUE THREAD

**Issue by k0nsl** [NodeBB/NodeBB#692]
I couldn't find any other (or similar) issues on this, so here goes:

I cloned the latest code at your repo and everything works except this WebSocket issue, which I couldn't figure out, or haven't had time to look into.

This is what the Chrome console looks like:

```
event.returnValue is deprecated. Please use the standard event.preventDefault() instead.
WebSocket connection to 'ws://konsortium.k0nsl.org/socket.io/1/websocket/PPXAxHmo0J1KytAEhJRK' failed: Unexpected response code: 502 socket.io.js:2371
Uncaught SyntaxError: Invalid regular expression: /?loggedin/: Nothing to repeat VM938 ?loggedin:6
Uncaught ReferenceError: Tinycon is not defined 
```

Not sure why that is so. My nginx proxy is set up correctly as well:

```
upstream nodebb {
    #server 192.241.196.204:9000;
    server 127.0.0.1:9000;
}

server {
    #listen   80;
    listen   80;
    server_name  konsortium.k0nsl.org;


    root /home/nodebb/nodebb/public;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://nodebb/;
        proxy_redirect off;

        # Socket.IO Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

}
```

Any ideas?

**Comment by Xuanwo** [comment]
how to config in apache2?

**Comment by julianlam** [comment]
Hi there, please see our [documentation portal](https://docs.nodebb.org)

**Comment by Xuanwo** [comment]
Although I did all the in the doc, but I steel see this info:
```
 WebSocket connection to 'ws://xg.xuanwo.org/socket.io/?EIO=3&transport=websocket&sid=KN3QEZmIdfn9GQEzAACW' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Comment by dongshimou** [comment]
the same to me.
i edit ./nodebb/config.json
` "url" : "127.0.0.1:8080" ` -> ' "url" : "www.yourside.com"'
the socket.io work success.
maybe you should edit your nodebb/config.json

**Comment by WLyKan** [comment]
@julianlam @dongshimou  Is there any   detailed document on configuring nodebb and an explanation of the config.json parameter

**Comment by julianlam** [comment]
Hello there. No additional configuration is required, just make sure the `url` parameter matches the url you use to access NodeBB

**Comment by johnsmithsren** [comment]
Hello ， is this the end of the issue? now i face the same problem,  and i change the nodebb config.json,but not work

**Comment by fais3000** [comment]
@julianlam This issue has started appearing again. Happens only when https://docs.nodebb.org/configuring/scaling/ is applied and nodebb is running on 6 ports.

Happens on nodebb 1.13.4-5 and 1.14.0/1

Cloudlfare is being used with nginx/1.15.8 


No handshake issue if nodebb is running on one port.

**Comment by barisusakli** [comment]
Share your nginx config, are you using `ip_hash` to send clients to the same backend?

**Comment by fais3000** [comment]
> ip_hash

@barisusakli Yes, we are using ip_hash. I've created a dedicated issue as I was able to replicate this problem on two different server with different forums. https://github.com/NodeBB/NodeBB/issues/8491
