### ISSUE TITLE
Flag Detail Page causing server crash when reporter has blocked poster

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#6925]
In Nodebb 1.10.1

When viewing a flag detail page the forum crashes because the reporter has blocked the person being reported.

modsController.flags.detail -> 
flags.get (in src/flags.js) -> 
Flags.getTarget (in src/flags.js) -> 
posts.getPostsByPids (in src/posts.js) -> 
user.blocks.filter (which filters out the reported post causing getPostsByPids to return empty postData) -> 
topics.addPostData (in src/posts.js - which returns undefined) -> 
causes the Object.keys function below to produce this error "Cannot convert undefined or null to object"

https://github.com/NodeBB/NodeBB/blob/c8d3c3197ba3025ed395e400f8cb0b312fac790e/src/controllers/mods.js#L140

**Comment by julianlam** [comment]
:man_facepalming:

**Comment by julianlam** [comment]
Just to clarify, this occurs when the moderator viewing the page has blocked the reported individual, right?
