### ISSUE TITLE
Revamp widget visibility options to be by user group

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#6937]
Currently, the option exists to show a widget to either anonymous users or registered users only:

![image](https://user-images.githubusercontent.com/923011/48306386-a162bd00-e505-11e8-90da-3af5b1bc639b.png)

However, it would be advantageous to extend this to allow an admin to pick which groups to display a widget for.

----

From: https://community.nodebb.org/topic/13081/is-there-a-way-to-show-hide-widgets-conditionally-specifically-based-on-group-membership

**Comment by barisusakli** [comment]
Same for navigation items

**Comment by djensen47** [comment]
Is it possible to do this with the new changes:

Show this to only Group X.
Don't show this to Group X.

I kinda need the "else" condition. 😕 

One use case for this is paid members. I want to show non-paid members a subscribe button and I want to show subscribed members a thank you message (but not the subscribe).

**Comment by djensen47** [comment]
> make 2 widgets one for subsribed one for nonpaid.

I don't think this works. Unless I'm mistaken...
1. No method to automatically add new users to the unpaid group
2. No bulk add mechanism for 12k existing members

The other use case is that I want to turn off Google ads for subscribed member.

**Comment by pitaj** [comment]
There is a plugin for adding new users to groups:

https://github.com/pichalite/nodebb-plugin-assign-newuser-to-group

Not sure if it works though
