### ISSUE TITLE
Replied-to button has the wrong URL on forum installed in "subfolder"

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#6948]
- **NodeBB version:** 1.10.2 
- **NodeBB git hash:** 5d3c814d57a4dc28fdc0c799c8d1f7b9325ea8e8

- **Database type:** mongo
- **Database version:** 3.6

1. Install a Nodebb into "subfolder/subdir" like `/forums`
2. Reply to a *post* so that the result has the "in response to button"

![image](https://user-images.githubusercontent.com/527865/48418032-19e59b80-e709-11e8-8bbf-c13c230d5379.png)

      3. Hover over the link to view the URL

- **What you expected:**

The URL would start with `/forums`

- **What happened instead:**

The URL starts with `/posts`

You can see the behavior here: https://www.axisandallies.org/forums/topic/32367/new-forum-software-update/27

This is especially problematic on this post because the user split it into a new topic and now that link to go back to the original post does not work: https://www.axisandallies.org/forums/topic/32428/zombies-and-1942-scenario

**Comment by julianlam** [comment]
Confirmed! Wow, I can't believe that wasn't found earlier :)

**Comment by julianlam** [comment]
No fix for vanilla as it doesn't seem to use `toPid`s at all :thinking:
