### ISSUE TITLE
sub folder install homepage gives 404

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#6949]
https://community.nodebb.org/topic/13309/missing-a-trailing-slash-causes-404-on-forum-in-subfolder

**Comment by barisusakli** [comment]
Looks like express is removing the leading slash [here](https://github.com/expressjs/express/blob/f3fa758af9664526ee18c58764590e48f559e6ae/lib/router/index.js#L183) which causes the url requested to become `/forumcategories` instead of `/forum/categories`

**Comment by djensen47** [comment]
Still an issue for me. Try going to https://www.axisandallies.org/forums

**Comment by barisusakli** [comment]
Looks like [this](https://github.com/NodeBB/NodeBB/commit/4b486a808e455ddbed06ab1d1940093cfce96cad#diff-a73199f6b673a7742e2f8377e84da5d8) fix broke subfolder homepage 🤦‍♂️
