### ISSUE TITLE
Rename files to download

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#6953]
Hello, is there a chance that you will change the rename of files when sending them? That just would be the original file name, not for example 012345678_FileName.txt

**Comment by julianlam** [comment]
Did you want simpyl `FileName.txt`? I think that is doable...

**Comment by youhosi** [comment]
Yes, so that the name of the file being uploaded is not changed, e.g. the original file is called FileName.txt, and the file is also uploaded FileName.txt.

**Comment by julianlam** [comment]
Right, we prepend the timestamp in order to allow for multiple files of the same name (otherwise we would run into conflicts). However sending a specific filename back during download is doable, let me see.

**Comment by youhosi** [comment]
Oh yes!!! I hope that it will work, so let's do it! :smile:

**Comment by youhosi** [comment]
Unfortunately, but the fix did not improve the file transfer, the name is changed.

![zrzut ekranu z 2018-11-25 17-45-30](https://user-images.githubusercontent.com/24297084/48981749-f859bc00-f0d9-11e8-95a4-3964d22fe94a.png)

Can not get the same effect as on github? That the name would not be changed and would not add, e.g. "0_1543164207058_" such an ID.

**Comment by julianlam** [comment]
On download the name is correct, yes?

**Comment by youhosi** [comment]
Locally:
![zrzut ekranu z 2018-11-25 18-29-38](https://user-images.githubusercontent.com/24297084/48982237-2fcb6700-f0e0-11e8-8e94-12e880309d74.png)
On the production server:
![zrzut ekranu z 2018-11-25 18-29-49](https://user-images.githubusercontent.com/24297084/48982240-34901b00-f0e0-11e8-9afe-9821b2271066.png)

**Comment by julianlam** [comment]
If the fix works on local but not on production then it indicates we may have missed something... What differences are there between the environments?

**Comment by youhosi** [comment]
Three instances are in the production environment, on the local one. That's all the changes, the configuration of nginx is the same.

**Comment by youhosi** [comment]
And what do you think about improving the file display?

Instead of this: `[0_1543164207058_NodeBB](/assets/uploads/files/1543164207083-Nodebb)`
This was: `[NodeBB](/assets/uploads/files/1543164207083-Nodebb)`

**Comment by julianlam** [comment]
@youhosi Unfortunately I cannot reproduce the issue locally. When I attempt to download a file via right-click > Save As, the filename is properly truncated so the timestamp at the front is not present.

The file **display** itself is a separate issue.

**Comment by barisusakli** [comment]
The code in [here](https://github.com/NodeBB/NodeBB/commit/f96208a0c80a65ec498a8f802acc1abffe7029e0) won't work if files are served by nginx?

**Comment by julianlam** [comment]
I don't know the config off the top of my head, but maybe it is possible to configure nginx to lop off the first 14 characters of the filename (datetime and the `_`)

**Comment by julianlam** [comment]
You will need to amend your nginx config to send a content-disposition header for files in assets/uploads/files

**Comment by youhosi** [comment]
Will you give any tips? Because unfortunately, but I'm not so familiar with nginx.

**Comment by youhosi** [comment]
I can not deal with this problem, I add headers in `/assets/uploads/files/` and it does not work.. 

What's wrong here?
```
    location /assets/uploads/files/  {
            proxy_set_header Content-Disposition 'inline; filename="$1"';
    }
```

**Comment by julianlam** [comment]
Hi @youhosi -- unfortunately I am just as bad at nginx configurations are you are :smile: so I cannot provide any guidance at this time, but I will keep a lookout for potential solutions.

**Comment by youhosi** [comment]
Nginx sends headers, but still does not delete `1543194309396-` before the name.

```
➜  ~ curl -I -k http://ddl.oxidepolska.pl/1543194309396-timecontrol.zip
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Dec 2018 20:50:57 GMT
Content-Type: application/zip
Content-Length: 1234
Last-Modified: Mon, 26 Nov 2018 01:05:09 GMT
Connection: keep-alive
ETag: "5bfb46c5-4d2"
Content-Disposition: inline; filename="1543194309396-timecontrol.zip"
Accept-Ranges: bytes
```

**Comment by julianlam** [comment]
Well, yes... the nginx snippet you posted above sets the "Content-Disposition" header, but you're passing in $1, which is likely just the filename, timestamp and all.

I don't know if there's a way to actually trim off the first 14 characters for that variable, but that's where you'd need to go next with it.
