### ISSUE TITLE
Forking/Moving a topic when pagination is turned on doesn't work across pages

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#6957]
- NodeBB version: 1.10.2
- NodeBB git hash: 5d3c814
- Database type: mongo
- Database version: 3.6

1. Turn on pagination
2. Find a topic that has posts that span multiple pages
3. Go to the last post on page one
4. Click fork/move topic
5. Select the last post
6. Go to the next page

**Expected Behavior**
The fork/move topic dialog stays on screen allowing you to select posts across pages

**Actual Behavior**
The fork/move topic dialog disappears when you go to the next page.

**Comment by djensen47** [comment]
I also think that post selection is a little odd. Elsewhere on the site you click the circle (e.g., the category circle) but here we are supposed to click the text? I'm not sure exactly where I'm supposed to click. I just do it until it registers.

**Comment by barisusakli** [comment]
same issue on move posts
