### ISSUE TITLE
Allow the unloaded img src to be configurable for delayed image loading

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#6958]
The delay image loading feature is great. However, one thing that I've discovered is that you don't really know which posts have images until it suddenly pops up at you. Having a placeholder the same size of the image would be the ideal but that's a ton of work.

Instead, what if the src value of  unloaded images was configurable?

Instead of `about:blank` maybe it could be a configurable static image asset like this:
![image](https://user-images.githubusercontent.com/527865/48599602-3b1ed580-e91d-11e8-9cf3-522260557439.png)

Or it's just blank like the default.

Here's a pointer to the codebase:

https://github.com/NodeBB/NodeBB/blob/ff290880e279fbc448c0a9d0271bf11996b0a4f3/public/src/client/topic/images.js#L19

**Comment by julianlam** [comment]
You know what -- I hate the delayed image loading. It was supposed to fix the viewport shifting around before images have loaded, but it causes exactly the same issues you describe.

Now that we've improved image upload handling _somewhat_, I'm eager to look into this logic again and determine how we can improve it.

**Comment by julianlam** [comment]
related: #6150
