### ISSUE TITLE
Crash on community instance

### ISSUE THREAD

**Issue by wmertens** [NodeBB/NodeBB#6974]
- **NodeBB version:** No idea, it's happening on https://community.nodebb.org

- **Exact steps to cause this issue:**

1. Click on a subject
2. Go back in browser history

Most of the time it works fine, but I had it crash twice in a row on this line:

https://github.com/NodeBB/NodeBB/blob/64b9dabff87862a77a71fec2370b2a8d2ed4b6e4/public/src/modules/topicList.js#L226

The `selectedTerm` was undefined, and it crashed on trying to dereference `term`.

**Comment by barisusakli** [comment]
@wmertens thanks for reporting
https://github.com/NodeBB/NodeBB/commit/1454fdceff88eefe4aa21aec7c59131efc497844
