### ISSUE TITLE
Feature Request: Font Awesome 5.5

### ISSUE THREAD

**Issue by snarlynarwhal** [NodeBB/NodeBB#6976]
I just wanted to put in a request to upgrade Font Awesome to version 5.5. Right now it looks like NodeBB v1.10.2 uses Font Awesome 4.7. I just want access to the Discord icon since the login shows a [Pied Piper](https://fontawesome.com/icons/pied-piper?style=brands) icon when using [nodebb-plugins-sso-discord-alt](https://github.com/jsumners/nodebb-plugin-sso-discord-alt) since versions prior to 5.0 do not have the Discord icon.

**Comment by pitaj** [comment]
As I understand it, FA 5.x is a license and breaking change from 4.x

We could switch to forkawesome, which does have a discord icon: https://forkawesome.github.io/Fork-Awesome/icon/discord-alt/

**Comment by Armadill0** [comment]
I would love to have the latest font awesome, too. It currently has about 1500 free icons where fork awesome is stuck at roughly 800.

I'm especially missing the helicopter.

**Comment by oplik0** [comment]
Just to add a reason for the upgrade: fa5 offers a free license like it did and while the website makes it seem to be limited to 10k pageviews monthly for a free license I believe this only applies to the hosted kits. So downloading free fontawesome is still, well, free. All the assets are licensed under open licenses - fonts are SIL OFL 1.1, Code is MIT and icons are CC BY 4.0.

Also, while FA5 does have breaking changes, there is also a v4 compatibility stylesheet that allows FA4 names to work ([third step here](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#manually))
