### ISSUE TITLE
Invalid date time.

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#6983]
![zrzut ekranu z 2018-11-21 19-34-15](https://user-images.githubusercontent.com/24297084/48861673-7fe6b880-edc4-11e8-8f07-ab74baf0d7c5.png)
![zrzut ekranu z 2018-11-21 19-34-24](https://user-images.githubusercontent.com/24297084/48861674-807f4f00-edc4-11e8-9b5d-477f8a2a6933.png)

**Comment by barisusakli** [comment]
Is your forum public can I take a look?

**Comment by youhosi** [comment]
The official forum also has this problem

![zrzut ekranu z 2018-11-21 19-50-14](https://user-images.githubusercontent.com/24297084/48862467-bfae9f80-edc6-11e8-9f57-7f62320d51cb.png)

**Comment by barisusakli** [comment]
I don't get the error on https://community.nodebb.org, what language are you using?

**Comment by youhosi** [comment]
I use Polish language :)

**Comment by barisusakli** [comment]
No errors there either, could be a browser thing. What OS/browser?
![image](https://user-images.githubusercontent.com/2583394/48862907-accfa700-ed95-11e8-9dd5-2a0824d8cbbd.png)

**Comment by youhosi** [comment]
OS: elementary OS,
Browser: Chromium

**Comment by youhosi** [comment]
> OS: elementary OS,
> Browser: Chromium

**Comment by pitaj** [comment]
What version of Chromium?

**Comment by youhosi** [comment]
version is 70.0.3538.77

**Comment by barisusakli** [comment]
Can you put a break point/console.log and check value of iso?

**Comment by youhosi** [comment]
I do not know how to do this

**Comment by barisusakli** [comment]
If you have access to the source code of the forum modify [this](https://github.com/NodeBB/NodeBB/blob/master/public/src/overrides.js#L133) line and add `console.log('value of iso', iso);` before it, then rebuild and restart the forum.

You should see the output in your browser console when you get the error.

**Comment by youhosi** [comment]
outut ![zrzut ekranu z 2018-11-22 19 43 37](https://user-images.githubusercontent.com/24297084/48918751-f9e37400-ee8e-11e8-948c-adb32bcb34aa.png)

**Comment by barisusakli** [comment]
What does `lis` stand for? Is it a month name?

**Comment by youhosi** [comment]
Yes, listopad = november

**Comment by barisusakli** [comment]
@youhosi let me know if resolved, this only happens after waiting for a while for timeago to kick in and update the strings on the DOM.
