### ISSUE TITLE
Checkbox styles are not consistent in a post

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7000]
- NodeBB version: 1.10.2
- NodeBB git hash: 5d3c814
- Database type: mongo
- Database version: 3.6

1. Create a post with a checkbox list with a lot of words.

**Expected Behavior**
Font weight is the same as the rest of the post and wraps like the rest of the items in the post.

**Actual Behavior**
- Text is bold
- The entire text wraps together. (It's an inline block)
- ~~Left margin is zero. Mashed up against the checkbox~~ (I guess I imagined this?)

For example:
![image](https://user-images.githubusercontent.com/527865/49001576-ea279200-f111-11e8-81d6-af34d55249dc.png)

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/49669286-e9a2cb80-fa2e-11e8-890e-31a41617d248.png)

**Comment by djensen47** [comment]
👍 Looks good.
