### ISSUE TITLE
websocket forbidden code 4

### ISSUE THREAD

**Issue by basickarl** [NodeBB/NodeBB#7001]
I get the error message in the console: `socket.io.js:7 GET http://instanty.io/socket.io/?EIO=3&transport=polling&t=MTHEcrD 403 (Forbidden)
`
And the response:
```
{code: 4, message: "Forbidden"}
code: 4
message: "Forbidden"
```

Version of NodeBB on ubuntu: 1.10.1
nginx version: nginx/1.14.0
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by pitaj** [comment]
Make sure the `url` value in config.json is set exactly to the url at which you access the forum.

**Comment by basickarl** [comment]
Ahh thanks, now it works!

**Comment by chiragtatva** [comment]
I am facing the same issue
but there is no config.json file in my case
which part of the config code is it backend, alloworigins(array) or frontend?
@pitaj @basickarl
