### ISSUE TITLE
Email doesn't unescape ampersand and title is redundant sometimes

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7004]
- NodeBB version: 1.10.2
- NodeBB git hash: 5d3c814
- Database type: mongo
- Database version: 3.6

 **Exact steps to cause this issue:**
1. Title your forum with an ampersand like "Axis & Allies"
2.  Send a test Welcome email
3. Send a password reset email

**Expected Behavior**
- Ampersands appear as `&` and not `&amp;`
- Title is doesn't repeat itself

**Actual Behavior**
- All ampersands are displayed as `&amp;`
- Reset password and maybe others appear like so: 
![image](https://user-images.githubusercontent.com/527865/49039611-1e806a00-f175-11e8-86ce-fa4c67e7d6c1.png)

**Comment by djensen47** [comment]
It looks like there might be a regression:

![image](https://user-images.githubusercontent.com/527865/49545539-d22edb80-f892-11e8-8c48-29a973bf1ce2.png)

![image](https://user-images.githubusercontent.com/527865/49545612-06a29780-f893-11e8-95ca-d6f77716343e.png)

![image](https://user-images.githubusercontent.com/527865/49545748-5719f500-f893-11e8-9ca6-88e689a1e175.png)

**Comment by djensen47** [comment]
Or should I open a new issue?

**Comment by barisusakli** [comment]
New issue please
