### ISSUE TITLE
[Security] - Upgrade Bootstrap from 3.3.7 to 4.x.x

### ISSUE THREAD

**Issue by sp-daniel-sanchez** [NodeBB/NodeBB#7010]
- **NodeBB version:** 1.10.2
- **NodeBB git hash:** 

- **Database type:** mongo
- **Database version:** v3.0.15

- **Exact steps to cause this issue:**
The main issue here is the security vulnerability in Bootstrap 3.3.7.
Here are the details: https://snyk.io/test/npm/bootstrap/3.3.7
Is a XSS vulnerability so action should be taken as this is considered as "medium" severity.

I'm not sure if you are aware of this, so i've decided to open this issue to at least keep you informed about it. 

Thank you in advance!

**Comment by julianlam** [comment]
Thank you for reporting. Fortunately for us the vulnerability does not affect us as we do not use any of the affected modules.

Therefore we will continue to upgrade to bootstrap 4 when ready to do so.

**Comment by sp-daniel-sanchez** [comment]
Good to know. Thanks for the quick reply 👍

**Comment by julianlam** [comment]
Sorry if I was a bit brusque, hadn't had my morning coffee yet :smile:

We definitely *will* upgrade to BS4, but of course, it's a major version bump and it means almost every them in use will become broken, so we must do this carefully :grimacing:

**Comment by julianlam** [comment]
... and don't worry, we know. @renovate-bot bot reminds us every once in awhile that bootstrap and bootswatch should really be upgraded, heh.

**Comment by sp-daniel-sanchez** [comment]
If @renovate-bot knows about it i'm sure you will sooner or later upgrade Bootstrap to v4 hehehe
I knew it was something complex and also that it was under control, but just wanted to double check with you in case there was a possible vulnerability :)

Thanks again and never ask again a ticket without your morning coffe!! hahaha
