### ISSUE TITLE
Problems with translation Uploaded files in ACP.

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7015]
After switching to the category uploaded file shows the following errors in the console.

![zrzut ekranu z 2018-11-27 19-41-59](https://user-images.githubusercontent.com/24297084/49103780-8d94b600-f27c-11e8-8db4-8687e4e97bd1.png)

**Comment by pitaj** [comment]
Are you on master?

It probably just doesn't exist for your specific language, yet. The translations have to be synchronized to and from transifex, which happens periodically.

**Comment by youhosi** [comment]
Today I've added a translation to Polish, and now I just have to wait :)

**Comment by julianlam** [comment]
Fixed yesterday in 7357926fe7c1dab06f6682d1df52028af33d08aa :+1:  @nodebb-misty should pull the translations in tomorrow morning.
