### ISSUE TITLE
Improve user experience for "upload profile image from URL"

### ISSUE THREAD

**Issue by AzariahAeroborn** [NodeBB/NodeBB#7024]
- **NodeBB version:** 1.10.2?  (the last version the forum's change log lists as installed, not sure where to find better information on this, sorry)
- **NodeBB git hash:** 

- **Exact steps to cause this issue:**
1. Attempt to upload a profile picture by URL, from a target that does not have CORS set
2. Be presented with the "crop picture" option, do cropping and press "Crop and upload" 
- **What you expected:**
I expected a successful upload.
- **What happened instead:**
Received a pop-up "Unable to upload image due to misconfigured CORS", "Crop and upload" button remained disabled and the crop modal remained open.  I was unable to proceed until I manually closed the crop modal to retry.

From doing more investigation via browser console, the JS console notes the issue is because the image I'm trying to upload has no CORS header set.  This was somewhat frustrating to run into because it wasn't apparent from the initial error why it failed - if there was a CORS problem, why did my browser pull the image to crop to begin with?

I believe the behavior could be improved in one of two ways:
- Check the CORS policy first, before bringing up the image to crop, and error out there (possibly with a more verbose / clearer error message) indicating that the image won't be able to be uploaded by URL
- Change the post-crop behavior so the client sends the image URL and the desired crop coordinates to the server, and then the server does its own CURL request (possibly sending back a confirmation image before applying, to cover the potential case of image differing between my browser requesting it and the server requesting it)

There's a bit of extra discussion about this here: https://what.thedailywtf.com/topic/25952/error-uploading-profile-picture-from-url-misconfigured-cors

**Comment by pitaj** [comment]
Pretty sure this has been discussed before. I thought it was fixed already.

**Comment by pitaj** [comment]
#6175 is related I think
