### ISSUE TITLE
Suggested Topics Sidebar Widget broken on 1.11.0

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7036]
- **NodeBB version:** 1.11.0
- **NodeBB git hash:** 543336070aa47ba3b155d9524d618acbd6eb5fc6
- **Database type:** mongo
- **Database version:** 3.6.8

- **Exact steps to cause this issue:**
1. Upgrade
2. Look at the Suggested Topics sidebar widget

- **What happened instead:**

It;s not formatted properly:

543336070aa47ba3b155d9524d618acbd6eb5fc
![image](https://user-images.githubusercontent.com/527865/49299729-4cb3c180-f475-11e8-8299-f3725d233ec7.png)

**Comment by barisusakli** [comment]
Put it on the footer for, gotto render different template if widget is placed on sidebar I guess.

**Comment by pitaj** [comment]
Can probably just hide certain elements with CSS if in sidebar.

**Comment by djensen47** [comment]
Oh bummer, this didn't get fixed in 1.11.1?

**Comment by pitaj** [comment]
It will be a plugin upgrade I think so you should be able to get the fix regardless.
