### ISSUE TITLE
Reputation threshold of 0 doesn't allow signatures

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7041]
- **NodeBB version:** 1.11.0
- **NodeBB git hash:** 543336070aa47ba3b155d9524d618acbd6eb5fc6
- **Database type:** mongo
- **Database version:** 3.6.8
- **Exact steps to cause this issue:**
1. Set permissions for signatures only for select groups
![image](https://user-images.githubusercontent.com/527865/49332057-439d2000-f55b-11e8-998b-3c57b3e14ba5.png)

2. Delete the value for 'Minimum reputation to add "Signature" to user profile'

![image](https://user-images.githubusercontent.com/527865/49332122-10a75c00-f55c-11e8-8381-84915fb6cb4e.png)

3. Edit profile

- **What you expected:**

The signature form field would be available to enter values.

- **What happened instead:**

Signature form field not present. I tried force reloading the page. The only thing that worked was to set the minimum reputation to 1, which caused a different potential bug.

**Comment by pitaj** [comment]
I was unable to reproduce this. I created a new group called "Sponsor", added the Signature privilege for it, and removed the signature privilege from every other group. I added a user "derp" to that group. I logged in as "derp" and could edit the signature. When I logged in as "test" I couldn't edit the signature.

**Comment by barisusakli** [comment]
It was only happening if you emptied the reputation field and hit save.

**Comment by djensen47** [comment]
> It was only happening if you emptied the reputation field and hit save.

Correct, if you manually add 0, it seems to be okay. I learned that when writing out the steps. 😁
