### ISSUE TITLE
Invalid session problems & login link not available

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7050]
Running 1.11.0 on MongoDB with a 14 day session

It's hard to reproduce this but every since the upgrade to 1.11.0 I've noticed 2 issues with sessions:

1. The 14 day session is not respected. I had to login both this morning and this afternoon, also on Saturday. This is independent of the admin login. This is just me accessing the forums like everybody else.

2. When the session times out, the navbar does not update so it "looks" like I'm still logged in (profile picture is still in the navbar) but I'm not and there's no link to login. 

I imagine you can reproduce this by setting the session time to something very short.

**Comment by djensen47** [comment]
I was actively using the axisandallies.org/forums and I was suddenly logged out for no reason. I do have a tendency to open multiple tabs but I've enver experienced that on community.nodebb.org

**Comment by barisusakli** [comment]
Could it be related to one of these settings 

```
function setupCookie() {
	var ttl = meta.getSessionTTLSeconds() * 1000;

	var cookie = {
		maxAge: ttl,
	};

	if (nconf.get('cookieDomain') || meta.config.cookieDomain) {
		cookie.domain = nconf.get('cookieDomain') || meta.config.cookieDomain;
	}

	if (nconf.get('secure')) {
		cookie.secure = true;
	}

	var relativePath = nconf.get('relative_path');
	if (relativePath !== '') {
		cookie.path = relativePath;
	}

	return cookie;
}
```

**Comment by michael-brade** [comment]
> Running 1.11.0 on MongoDB with a 14 day session
>
> 2. When the session times out, the navbar does not update so it "looks" like I'm still logged in (profile picture is still in the navbar) but I'm not and there's no link to login.

I can confirm this. Additionally, when I log in, the navbar still shows "Register" and "Login" but no menus. I have no errors in the console or the log. I can click on the categories and read the things that are only available when you are logged in. Only after I reload the browser page does it show me the correct view.

**Comment by djensen47** [comment]
Just today @Panther2 experienced this:

> The 14 day session is not respected. I had to login both this morning and this afternoon, also on Saturday. This is independent of the admin login. This is just me accessing the forums like everybody else.

I think I might know how to reproduce it. _Maybe_. I wanted to individually message a bunch of people in a group so I Ctrl-Click each of them to open in a new tab. I proceeded to first edit their profiles (to enable multiple group badges), then I clicked back to their profile, then sent a chat message, close the chat, close the tab, and move onto the next one. After about 5-10 of these I was logged out.

**Comment by djensen47** [comment]
@barisusakli I'm using all of the default settings.

Now I'm thinking this is related to the software generate 503 message. I got a 503 and then my session was invalid and I had to login again. Furthermore, I _think_ it doesn't matter who gets the 503.

Lastly, I recently experienced this on community.nodebb.org as well

**Comment by djensen47** [comment]
As of 1:52PM Dec. 11, this issue has reached the point where I cannot login.


I login, appear to be logged in, am not actually logged in, andI get a CSRF or Invalid session error.

**Comment by pitaj** [comment]
I have no idea what's going on nor have I ever encountered this problem. Have you tried different browsers? Can you post your config.json ?

**Comment by djensen47** [comment]
I have not tried with different browsers.

Sure, I think I've posted it before ... there's nothing new:

```
{
    "url": "https://www.axisandallies.org/forums",
    "secret": "...",
    "database": "mongo",
    "port": "80",
    "trust_proxy": true,
    "isCluster": false,
    "mongo": {
        "host": "...",
        "port": "27017",
        "username": "...",
        "password": "...",
        "database": "nodebb"
    }
}
```

**Comment by djensen47** [comment]
I was skeptical but I cannot seem to reproduce the issue on Firefox (Windows). I'll keep using FF for a while to see if it occurs (or not).

**Comment by pitaj** [comment]
It sounds like maybe mongodb is choking resulting in the sessions dying.

**Comment by djensen47** [comment]
I've been watching the CPU graphs when this is all happening. I think it might actually be node choking, the CPU spikes are much more bigger on the node server. The MongoDB server has two cpus and rarely are both over taxed.

I'm thinking I might need to cluster my setup on the node side.

**Comment by pitaj** [comment]
You have to store _something_ server side in order to invalidate sessions.

**Comment by djensen47** [comment]
> You have to store _something_ server side in order to invalidate sessions.

Yeah, that makes sense. If you want to manually invalidate a session, you have to store _something_ even with JWT. 

It just seems setting up a session for every single bot hit is excessive and causes usability issues with members of the forum. If I'm asking users to randomly login once a day, this is going to cause frustration and churn.

Even worse is when the site is yours and you're locked out because of session issues, which is happening again.

**Comment by djensen47** [comment]
I know this issue has largely been ignored. Now that I've completely all the steps to roughly match what community.nodebb.org has setup, it's a bug and a pretty bad one for high volume sites.

I'm more than happy to dig into this deeper but some guidance is nice so I can start down the right path.

**Comment by pitaj** [comment]
AFAIK we've never seen these kinds of session issues before though I'm not exactly sure if your scale is exceptional or not. It makes me think there's something else going on, but I'm not sure what that could be.

Regardless, we should consider not storing sessions for bots or maybe even guests.

**Comment by djensen47** [comment]
> Regardless, we should consider not storing sessions for bots or maybe even guests.

👍 I think that might help. Checkout my traffic graph 😉 ...

![image](https://user-images.githubusercontent.com/527865/50026656-95ec3100-ff9e-11e8-8edb-2dd94a4866bd.png)

**Comment by djensen47** [comment]
The problem is now worse than it was before. Heh, maybe the problem will solve itself when all my users just leave out of frustration. 🤕 

The only thing that's different now is HAProxy vs. Nginx. HAProxy is a true proxy, performant, and IMO easier to configure, which is why I went with it. But maybe the defaults are just different enough to cause some issue. It's not a quick fix for me to switch so that's out of the cards for now.

A few more questions:

1. Would you be able to provide a sample of what the headers look like _after_ nginx has proxied the request?
2. Is there an artificial limit on the number of sessions that can be stored? 
    I ask this one because the issue was also happening with MongoDB and we thought maybe mongo was taking too long. Redis on the same instance should be faster than Mongo on a remote server. The CPUs also don't seem to be even close to maxing out, anymore, but instead of less frequent it's more frequent.
3. Where in the NodeBB source would you recommend that I start logging some data to get to the bottom of this?
4. How do I log the application generated 503 message?

**Comment by barisusakli** [comment]
```
{
    "url": "https://www.axisandallies.org/forums",
    "secret": "...",
    "database": "mongo",
    "port": "80",
    "trust_proxy": true,
    "isCluster": false,
    "mongo": {
        "host": "...",
        "port": "27017",
        "username": "...",
        "password": "...",
        "database": "nodebb"
    }
}
```

Here is our config from community for comparison.
```
odebb@dev2:~/community.nodebb.org$ cat config.json
{
    "url": "https://community.nodebb.org",
    "bind_address": "127.0.0.1",
    "secret": "xxxx",
    "database": "mongo",
    "port": [4569, 4570],
    "redis": {
        "host": "127.0.0.1",
        "port": "6380",
        "password": "xx",
        "database": "xx"
    },
    "mongo": {
        "host": "127.0.0.1",
        "port": 27017,
        "username": "xx",
        "password": "xx",
        "database": "xx"
    }
}
```

I don't think it's recommended to use port 80.

I would try using a port like 4567,4568 and proxy via nginx. You can also setup a staging server on a non-subfolder install and see if it solves your issues before trying on your production server.

**Comment by djensen47** [comment]
My config is all different now. In fact now it looks exactly the same as yours. Except I have trustProxy set to true.

Port 80 shouldn't cause the issues we're talking about BTW.

**Comment by djensen47** [comment]
New config as of **last night**:
```
{
    "url": "https://www.axisandallies.org/forums",
    "secret": "aaa",
    "database": "mongo",
    "port": ["4567", "4568"],
    "trust_proxy": true,
    "mongo": {
        "host": "10.10.10.10",
        "port": "27017",
        "username": "bbb",
        "password": "ccc",
        "database": "xxx"
    },
    "redis": {
        "host":"127.0.0.1",
        "port":"6379",
        "database": 0,
        "password": "yyy"
    }
}

**Comment by djensen47** [comment]
I've gone over bits and pieces of this here and there but here's the whole setup.

- 1GB/1CPU instance
   - HAProxy (config is on community.nodebb.org)
       - SSL termination
       - Load balancing is done by `source` which is a hash of the IP
- 2GB/2CPU instance
   - Nodebb config, see above
   - NodeBB is run by an unprivileged user and started via systemctl per the instructions in the docs
   - Redis 5.0.3 on port 6379
       `maxmemory 350000000` and `maxmemory-policy volatile-lru`
- 4GB/2CPU instance
    - Mongodb 3.6.8 on port 27017

**Comment by djensen47** [comment]
Also, when I'm logged out there are no errors in the browser console.

I have 3 wild guesses at this point:
1. Race condition. The load on the system is causing stuff to happen out of order that normally would not.
2. HAProxy config. I'm good with HAProxy but not an expert. Also HAProxy is not nginx, but I feel more comfortable with HAProxy than tearing apart my entire infrastructure to _try_ nginx.
3. Something about the subfolder installation

**Comment by djensen47** [comment]
I have so many iframely info messages, I missed something ... 🤔 

<pre>
2018-12-14T19:57:48.978Z [21506] - error: Error: Redis connection to 127.0.0.1:6379 failed - read ECONNRESET
    at TCP.onread (net.js:622:25)
2018-12-14T19:57:48.980Z [21506] - error: Error: Redis connection to 127.0.0.1:6379 failed - read ECONNRESET
    at TCP.onread (net.js:622:25)
2018-12-14T19:57:48.982Z [21506] - error: /forums/topic/7354/new-forums-software/6

AbortError: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/var/srv/nodebb/node_modules/redis/index.js:362:23)
    at RedisClient.connection_gone (/var/srv/nodebb/node_modules/redis/index.js:664:14)
    at RedisClient.on_error (/var/srv/nodebb/node_modules/redis/index.js:410:10)
    at Socket.<anonymous> (/var/srv/nodebb/node_modules/redis/index.js:279:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2018-12-14T19:57:48.983Z [21506] - error: /forums/topic/17830/xdap-02-final-draft-axis-vs-dairy-qryn-allies/576

AbortError: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/var/srv/nodebb/node_modules/redis/index.js:362:23)
    at RedisClient.connection_gone (/var/srv/nodebb/node_modules/redis/index.js:664:14)
    at RedisClient.on_error (/var/srv/nodebb/node_modules/redis/index.js:410:10)
    at Socket.<anonymous> (/var/srv/nodebb/node_modules/redis/index.js:279:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2018-12-14T19:57:49.026Z [21506] - error: /forums/topic/11338/reset

Error: misconfigured csrf
    at Object.csrf [as applyCSRF] (/var/srv/nodebb/node_modules/csurf/index.js:71:19)
    at /var/srv/nodebb/src/middleware/header.js:29:16
    at nextTask (/var/srv/nodebb/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/var/srv/nodebb/node_modules/async/dist/async.js:5334:5)
    at middleware.buildHeader (/var/srv/nodebb/src/middleware/header.js:27:9)
    at Layer.handle [as handle_request] (/var/srv/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at Immediate.next (/var/srv/nodebb/node_modules/express/lib/router/route.js:137:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2018-12-14T19:57:49.142Z [21506] - error: uncaughtException: Can't set headers after they are sent.
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/var/srv/nodebb/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/var/srv/nodebb/node_modules/express/lib/response.js:170:12)
    at defaultFn (/var/srv/nodebb/src/middleware/render.js:24:10)
    at /var/srv/nodebb/node_modules/async/dist/async.js:473:16
    at next (/var/srv/nodebb/node_modules/async/dist/async.js:5329:29)
    at /var/srv/nodebb/node_modules/async/dist/async.js:969:16
    at /var/srv/nodebb/src/middleware/render.js:104:6
    at nextTask (/var/srv/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/var/srv/nodebb/node_modules/async/dist/async.js:5331:9)
    at /var/srv/nodebb/node_modules/async/dist/async.js:969:16
    at Timeout._onTimeout (/var/srv/nodebb/src/middleware/render.js:129:4)
    at ontimeout (timers.js:502:15)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) {"error":{},"stack":"Error: Can't set headers after they are sen
</pre>

**Comment by djensen47** [comment]
Maybe a red herring but after updating to 1.11.1 the problem has not resurfaced. Usually when I post this it happens again within 20-30 minutes. I think the system is mocking me. 🤣 . Let's hope upgrading magically fixed the issue. 🤞

**Comment by djensen47** [comment]
😵 So the error didn't happen on axisandallies.org/forum but it did happen to me just now on community.nodebb.org

**Comment by djensen47** [comment]
Another possible path to reproduce the error:

1. Be logged in
2. Click the alerts icon in the toolbar
3. Click an alert that take you to a post
4. Click the categories icon in the tool bar

So far today, this 100% logs me out every time. I also have a chat open.

**Comment by djensen47** [comment]
Another weird thing is that I'm not _completely_ logged out:

![image](https://user-images.githubusercontent.com/527865/50115666-f1b3f580-01fc-11e9-964f-f8b533d07749.png)

**Comment by djensen47** [comment]
I added a response header to track the "server" (actually the instance) the response is coming from. It's called "X-Server". When I go through the workflow, *all* responses come from the same instance.

**Comment by djensen47** [comment]
Last thing, to make it stop I did the following:

1. Completely stop NodeBB
1. Completely stop Redis
1. Start Redis
1. Start NodeBB

The problem will be back in 36-48 hours.

**Comment by djensen47** [comment]
Sorry, this bug has turned into a massive stream of "consciousness" but now that I expect this problem to happen again around Wednesday evening or Thursday morning. Where do you recommend I put in some debug messages?

**Comment by djensen47** [comment]
As suspected, the issue rears it's ugly head again after about 2 days. I'm trying to do some debugging before hard bouncing the servers.

First question, when I log in is this expected behavior?

![image](https://user-images.githubusercontent.com/527865/50245211-bba27d00-0386-11e9-8df3-6c12efcb2619.png)

When I'm logged out and log in the handler for checkSession is invoked twice. It _seems_ the first one [should throw an error](https://github.com/NodeBB/NodeBB/blob/69e0dbbf4af881029d5c4226f20d6eb7debe60f7/public/src/sockets.js#L43) but it doesn't.

I checked it against community.nodebb.org and the behavior is the same except on community there is no Violation warning.

**Comment by djensen47** [comment]
@barisusakli @julianlam 

I put in some logging to see what's going on. Immediately after a reboot I saw some errors but that just might be from the few seconds of downtime.

In the meantime, I have a few more questions about your Redis setup:

1. How many sessions do you have in your Redis instance?
2. Do you have THP (transparent huge pages) disabled on your server?
3. Do you have these warnings when you start Redis:

    `WARNING: The TCP backlog setting of 511 cannot be enforced because...`
    `WARNING overcommit_memory is set to 0!`
    `WARNING you have Transparent Huge Pages (THP) support enabled in your kernel.`

Are there any _other_ settings besides the ones @barisusakli already mentioned (`maxmemory 250000000` `maxmemory-policy volatile-lru`?

**Comment by julianlam** [comment]
If all requests come from the same server, have you tried taking the server out of rotation for awhile?

Or does it happen to all servers...

Yeah that _might_ be normal behaviour, as the session itself is updated and local variables rewritten.

**Comment by julianlam** [comment]
Have you checked the TTL of various sess:* keys in your redis database?

**Comment by barisusakli** [comment]
Our forum runs latest master so spiders aren't creating sessions anymore, 17,802 sessions in 5 days 7.3mb memory usage. Before I emtied the sessions it had 300k sessions and was using 250mb memory which is the limit.

Your issues might be resolved once you apply those changes.

**Comment by djensen47** [comment]
> If all requests come from the same server, have you tried taking the server out of rotation for awhile?

I have clustering on so it's from two instances.

> Or does it happen to all servers...

All
 
> Yeah that _might_ be normal behaviour, as the session itself is updated and local variables rewritten.

Could there be a situation (beside restart) where the session update fails and then old session is removed but the new session never gets pushed to Redis? Where in the code do these session updates happen? I'd like to stick a log message there to look for failures.

> Have you checked the TTL of various sess:* keys in your redis database?

No, I'll try that.

> Your issues might be resolved once you apply those changes.

Hopefully! `info memory` shows I'm still well under the 350MB but it does show that the peak got to about 90% of that. I'm optimistic but I'd like to rule out sessions just not getting stored at all first.

**Comment by djensen47** [comment]
@baris @julianlam This doesn't seem right, I (and a few other users) have several dozen sessions for the same IP.

![image](https://user-images.githubusercontent.com/527865/50251367-8737bc80-0398-11e9-9a49-996be9540d4a.png)

**Comment by barisusakli** [comment]
Is this still happening?

**Comment by djensen47** [comment]
I still see some session errors in the logs but I have not seen this error in a long time. I think there as a change in Redis or something that fixed the thing that may have been causing the issue.
