### ISSUE TITLE
Email subjects are not escaping ampersands

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7064]
NodeBB version: 1.11.0

For example:
![image](https://user-images.githubusercontent.com/527865/49545539-d22edb80-f892-11e8-8c48-29a973bf1ce2.png)

![image](https://user-images.githubusercontent.com/527865/49545612-06a29780-f893-11e8-95ca-d6f77716343e.png)

![image](https://user-images.githubusercontent.com/527865/49545748-5719f500-f893-11e8-9ca6-88e689a1e175.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/96c1dc62762e607b073d7b534133bcfc2fe39270
