### ISSUE TITLE
Incorrect text alignment in topics

### ISSUE THREAD

**Issue by panther2** [NodeBB/NodeBB#7065]
- **NodeBB version:** 1.11.0
- **NodeBB git hash:** https://github.com/NodeBB/NodeBB/commit/543336070aa47ba3b155d9524d618acbd6eb5fc6
- **Database type:** mongo
- **Database version:** 3.6.8

Desktop browser: Chrome latest stable

In case the first line of a posting (does it have a dedicated name?) contains too much of information (user name, group titles, date of posting, username to reply to, edit symbol) the text of the posting itself will be incorrectly aligned (pressed at the right margin) - workaround is to reduce group titles until the text is displayed correctly. 

This is how it does look:

![x1](https://user-images.githubusercontent.com/20812775/49572156-17a2e580-f933-11e8-9bd5-8fb7c216dbb8.PNG)

Now I remove one group title and it looks like this:

![x2](https://user-images.githubusercontent.com/20812775/49572208-3d2fef00-f933-11e8-9a4a-1389a3131b83.PNG)

Expected behaviour would be that the text is always displayed correctly regardless of the amount of group titles... or any amount of information in that first line.

CC: @djensen47

**Comment by djensen47** [comment]
It appears to still be happening for _some_ users ...

https://www.axisandallies.org/forums/topic/33068/forums-feedback-redux/17

**Comment by julianlam** [comment]
#7447
