### ISSUE TITLE
Incorrect display of ampersands in sub-categories

### ISSUE THREAD

**Issue by panther2** [NodeBB/NodeBB#7066]
- **NodeBB version:** 1.11.0
- **NodeBB git hash:** https://github.com/NodeBB/NodeBB/commit/543336070aa47ba3b155d9524d618acbd6eb5fc6
- **Database type:** mongo
- **Database version:** 3.6.8

In case I enter a forum containing an ampersand in its name on its top-level, the ampersand is displayed correctly:

![amp1](https://user-images.githubusercontent.com/20812775/49573014-e62b1980-f934-11e8-8968-57e7487b1698.PNG)

But when I enter a sub-category, the ampersand is displayed incorrectly:

![amp](https://user-images.githubusercontent.com/20812775/49573067-05c24200-f935-11e8-8480-d53ac143f032.PNG)

Expected behaviour: Always show ampersands correctly.

CC: @djensen47

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7037
