### ISSUE TITLE
Can't access resources with Authorization token

### ISSUE THREAD

**Issue by yoyoyohamapi** [NodeBB/NodeBB#7076]
- **NodeBB version:** : 1. 10
- **NodeBB git hash:** 
- **Database type:** mongo
- **Database version:** v4.0.1
- **Exact steps to cause this issue:**

I can't access some resources by master token which is valid for [write-api](https://github.com/NodeBB/nodebb-plugin-write-api)：

```sh
curl -H "Authorization: Bearer MY_MASTER_TOKEN" https://mysite.com/api/post/pid/111
```

- **What you expected:**
resource returned
- **What happened instead:**
not found returned

**Comment by julianlam** [comment]
Fixed via eeaee8ccef325ff297c276bd7e6a8f3d6b9e8701
