### ISSUE TITLE
Navigation Admin Page

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#7077]
Nodebb 1.10.1

If in the Admin Navigation panel, you toggle a page to 'Only display to logged in users' on, does this just hide the navigation item? (We use our own header not the built in nodebb one so cant see if this is the case). We have this toggled on for a couple of pages and guest users can still visit the pages directly if they have the URL. Should this toggle stop users visiting the page?

**Comment by julianlam** [comment]
Hi there, the toggle only changes the display of the navigation item itself, and does not govern the actual access to the page
