### ISSUE TITLE
Guest block user

### ISSUE THREAD

**Issue by yoyoyohamapi** [NodeBB/NodeBB#7087]
- **NodeBB version:**  1.10
- **NodeBB git hash:** 

- **Database type:** mongo
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**
If one guest blocked a user, other guests can't see blocked user eithter.
- **What happened instead:**
User blocking by guest should not affect accessibility of other guests

**Comment by julianlam** [comment]
Should be impossible here ever since https://github.com/NodeBB/nodebb-theme-persona/commit/e0211f1d9baab1e88775695ee4e7be884bf27b68

How did the guest block a user?

**Comment by pitaj** [comment]
I don't think that's a good enough change. Someone can still send a socket or Ajax request to block a user for all guests. There should be a check server side.
