### ISSUE TITLE
can we set “Delay Image Loading”  by  administrators

### ISSUE THREAD

**Issue by pig315** [NodeBB/NodeBB#7088]
NodeBB version: : 1. 10
NodeBB git hash:
Database type: mongo
Database version: v4.0.1
Exact steps to cause this issue:

“Delay Image Loading” can set by users only

but images in topics will not load until they are scrolled into view

resource returned
the settings can set by administrators

**Comment by pitaj** [comment]
The "Delay image loading" feature has been entirely removed. #6150
