### ISSUE TITLE
When I answered the post, the views does not change

### ISSUE THREAD

**Issue by pig315** [NodeBB/NodeBB#7092]
![image](https://user-images.githubusercontent.com/45277553/49787566-fc384000-fd61-11e8-804c-b3ca3a2d0b59.png)
![image](https://user-images.githubusercontent.com/45277553/49787584-022e2100-fd62-11e8-8b5f-141925eb0e20.png)

When I answered the post, the views was 88
i want the views can display the times when Users click once plus one
how can i click it ,the views plus one

**Comment by julianlam** [comment]
View counts do not increment after you visit multiple times in succession, it is to stop people from artificially inflating the view count.
