### ISSUE TITLE
Editing a post with deep blockquote doesn't show expander

### ISSUE THREAD

**Issue by LonMcGregor** [NodeBB/NodeBB#7094]
(I don't have the version/config info, as I don't administrate the forum I found this issue on)

- **Exact steps to cause this issue:**
1. Reply to a topic with some text
2. Edit the text to include a deep block quote, e.g.
```
>> Some Text
```

- **What you expected:**
The reply fades out and when it fades back in, the blockquote is visible with a `[v]` expander
- **What happened instead:**
The reply fades out and when it fades in the blockquote is styled (the grey border is visible), but no `[v]` expander is present, so you can't see the reply until you reload the page

**Comment by boomzillawtf** [comment]
Yes. We had people report it and I confirmed it testing here:

https://community.nodebb.org/topic/13595/editing-nested-quotes
