### ISSUE TITLE
Chat editing UX could be improved

### ISSUE THREAD

**Issue by LonMcGregor** [NodeBB/NodeBB#7096]
(I don't have the version/config info, as I don't administrate the forum I found this issue on)

- **Exact steps to cause this issue:**
1. Open a chat with some messages
2. Look at the placeholder text in the new message box (type chat message here, press enter to send)
3. Click edit on one of the messages
4. Delete all the text in the text box
5. Note the placeholder text
6. start typing something
7. Note the appearance of the UI
8. Cancel editing the message

- **What you expected:**
  * You are given an  indication you are editing a previously sent message. 
  * The placeholder text should change to indicate you are editing a message(, e.g. "press enter to update"?)
  * You can cancel editing a message

- **What happened instead:**
  * There is no indication you are editing an old message, and no indication of which message is being 
edited
  * The placeholder text of an empty message box is the same for new messages and those being edited
  * You can't seem to "cancel" the flow of editing a message

**Comment by barisusakli** [comment]
![chat-edit](https://user-images.githubusercontent.com/2583394/235329816-c6ff34b3-0be2-4225-8644-a1388ca82a71.gif)
