### ISSUE TITLE
Sub-menu items of 'Topic Tools' not reachable by keyboard

### ISSUE THREAD

**Issue by DadBeef** [NodeBB/NodeBB#7100]
*NodeBB version:* 
1.10.2.
(I have no more developer information about the used NodeBB as i am not a administrator)

- **Exact steps to cause this issue:**
1. Open a existent thread
2. Go with Tab key to 'Topic Tools' button
3. Hit Cursor-Down
4. Sub-menu opens
5. Hit Cursor-Down
6. Cursor stucks in item 'Lock Topic', next item in sub-menu is not selected

See GIF ascreen recording:
![submenu-topic-tools-keybd](https://user-images.githubusercontent.com/45814538/49857499-fd657d80-fdf2-11e8-9d91-86330e6a235b.gif)

- **What you expected:**
I expected to reach all menu items in sub-menu with Cursor-Down key as in other buttons sub-menues

- **What happened instead:**
Cursor stucks in first item of sub-menu and next items can not be selected

- **Additional:**
Submenu items reachable by mouse
Keyboard access is needed for accessibility

**Comment by barisusakli** [comment]
hidden elements were causing the navigation to break
https://developer.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/ab81cca73555eda899da1c43ddbfe1bbcc64c86e
