### ISSUE TITLE
Why SSO plugins keeping lost after running a while?

### ISSUE THREAD

**Issue by johnking** [NodeBB/NodeBB#7104]
Hi there, 
First of all, thanks a lot for this wonderful project!

I found an annoying issue with self-host nodebb instance with free-tier Heroku hosting service: 
  the SSO plugins seems lost after running for a while. 

- **NodeBB version:**  v1.11.0
- **NodeBB git hash:**  919e6700176191ed09aadde6944e7e6ca5c7bf3e
- **Database type:** mongo
- **Database version:** mongod version: 3.6.6 (MMAPv1) 

- **Exact steps to cause this issue:**
	1. First I install google SSO , facebook SSO , and spam-be-gone plugins
	2. Then, I activate them with secrets
         3. they all work fine for some time

- **What you expected:**
I expected them working **continuously** ....

- **What happened instead:**
After some time, maybe hours, all the plugins UIs disappeared both from client side and ACP, and I need to **reinstall** and **reactivate** them. The good thing is all the secrets are still there when I reactivate them after reinstalling them from the ACP.

**possible reasons**
1. Were the setting/configuration of the plugins not saved into the database or configuration file? 

thanks

**Comment by johnking** [comment]
@julianlam 

Hi Julian, 
Thanks for your quick reply! So we have to install all the plugins by `npm` instead of via ACP? 

If it is the case, I wonder even in production deployment, there are downtime, and what happened for those plugins installed from ACP?  Will they be lost too?

thanks again. 

-John

**Comment by julianlam** [comment]
Well, Heroku is different in that you have to commit your code to a Heroku git repo, and you have to explicitly commit `package.json`, which contains the list of dependencies and plugins required.

When you install something via the ACP, `package.json` _in the running instance itself_ is updated, but not committed. To make it permanent, you'll have to update `config.json` with the plugin name and version, and commit it up to Heroku.

You can use the ACP or npm to install plugins locally, it does not matter, so long as the revised `package.json` get committed to Heroku.

**Comment by johnking** [comment]
Got it! thanks.
