### ISSUE TITLE
Feature: add error message for forgot password if email does not exist

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7111]
Currently when somebody enters a password that does not exist in the system, there is no error message.

I would like an option in the admin panel to enable/disable showing an error in this situation. By default it would be off. When it's on, maybe it should show a security question to help prevent bot probing.

I realize it might be considered a security risk but since I have people that joined the forums from 2001, they may not remember what email the used to sign up. I'd prefer the usability of an error message over them not knowing.

**Comment by djensen47** [comment]
Again, if agreeable to the feature, I can attempt a PR on this.

**Comment by pitaj** [comment]
> when somebody enters a password that does not exist in the system, there is no error message.

Do you mean there is no specific error message that the password was incorrect, instead just showing the generic message?

This is done because it's standard practice to not allow attackers to crawl for valid emails. Users should be able to always log in with their username if they aren't sure what their email is.

**Comment by djensen47** [comment]
I migrated 12k users from SMF to NodeBB. All new accounts were created without a password so in this case they cannot login, at all.

Yes, understood. security is about risk mitigation. This standard practice mitigates the risk of crawling for valid emails. If for some reason I need to show an error, we can mitigate the crawl risk with something like a captcha.

Or is there a way I can make a plugin to change this behavior?

I knew changing over would lose some users, it's just the way it is. But despite putting messages everywhere people just give up and don't contact me for help. I can't even rely on the logs, they go away after about 2 days and the only way to "fix" that is to hack the source code so after the next update, the "fix" goes away.

**Comment by pitaj** [comment]
> All new accounts were created without a password

So I'm guessing you're relying on people using the password reset feature to correct the authentication.

In that case, they'd have to know the email to reset their password, true. There's nothing stopping someone from entering their multiple different emails on the password reset form. If one of them works, they'll get an email.

I'm failing to really see how this can be fixed better by telling people when they've entered the wrong email. Maybe you're looking for something where people can just enter their username and get the associated email?

**Comment by djensen47** [comment]
> I'm failing to really see how this can be fixed better by telling people when they've entered the wrong email. Maybe you're looking for something where people can just enter their username and get the associated email?

Yeah, that might be a better approach. Just send a reminder to the email on file. 

Something else that might help is a custom message for either case. If I can say, "If you do not receive an email right away, please check your spam folder. If it's not there, please send and email to _________ for further assistance."

**Comment by djensen47** [comment]
Another thing that would be _super_ helpful is listing the failed email attempt in the "Events" log. Then I could go through on a weekly basis and send out message.s. Or if a bunch of different attempts are coming from the same IP, I can ban that IP.

**Comment by djensen47** [comment]
Here's what I propose: 

Close this issue and open 2:

1. Add failed password reset to the "events" log

1. Add "forgot" email feature
