### ISSUE TITLE
User settings still not completely applied after login on 1.11.1 (language issue)

### ISSUE THREAD

**Issue by panther2** [NodeBB/NodeBB#7118]
- **NodeBB version:** 1.11.1
- **NodeBB git hash:** https://github.com/NodeBB/NodeBB/commit/b0a44d866b08c1dc8b6d1c37364e8fa4fd21bf34
- **Database type:** mongo
- **Database version:** 3.6.8

Desktop browser: Chrome latest stable

Maybe a follow up to https://github.com/NodeBB/NodeBB/issues/7038 , partly fixed by https://github.com/NodeBB/NodeBB/pull/7059

On a German system the user setting for the forum language is set to "English".

After logging in there are still some buttons appearing in German:
![abbrechen](https://user-images.githubusercontent.com/20812775/50041492-2fc2e500-0056-11e9-922b-484e91c5cb85.PNG)

It needs a hard refresh again to see the expected result:
![abbrechen2](https://user-images.githubusercontent.com/20812775/50041497-3cdfd400-0056-11e9-96ee-4f600c3935a1.PNG)

(CC: @djensen47)

**Comment by julianlam** [comment]
Related commit 9432ec89d13f32c62ea66f62a8f9d380408f9592
Related issue: #7038
