### ISSUE TITLE
Guidance on general development other than plugins/widgets/hooks

### ISSUE THREAD

**Issue by johnking** [NodeBB/NodeBB#7122]
Hi there, 

  I have spent some time in studying NodeBB, and I can: 
  1. set up a nodebb instance in heroku
     - found a few issues and submitted them
  2. develop a demo plugin by following the plugin docs
     - the plugin works
  3. integrate `graphql` into nodebb
     - it works pretty well with grunt task runner

  but I don't know how to make 3) working with `nodebb cli`. 

  I have changed the file `src/webserver.js`, my question is how to make the changes working in production build?  I could not find any guidance on it. It would be great to have some introduction docs on the building/integration workflow. 

thanks a lot

-John

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!

**Comment by johnking** [comment]
@julianlam 

  I don't agree with nodebb-misty's comments and decision.  do you?  😄😄

-John

**Comment by pauljherring** [comment]
> thanks for your reply. but my question is not about plugin development

I, too, am having difficulty discerning what the bug/missing feature is - perhaps you could restate it?

**Comment by johnking** [comment]
@pauljherring 

  My question was: I made some changes in file  `src/webserver.js`, I could use command `grunt` to run a dev server and see the changes. But I don't know how to use `nodebb-cli` commands like `./nodebb build` to make the changes working. 

  I thought this was a general development question. 

thanks for your help on this. 

-John

**Comment by pitaj** [comment]
Questions which are not feature requests or bugs should be asked on https://community.nodebb.org

For the sake of convenience, I'll answer it here. If you have any follow-up questions please make a topic on the forum.

`grunt` is essentially just calling `./nodebb build` and restarting the server every time a file is modified. So, you can also just do `./nodebb build` then `./nodebb start` to start a daemon server process. To just start the server in dev mode, you can use `./nodebb dev`. All of these are documented in `./nodebb help`

**Comment by johnking** [comment]
thanks for your reply @pitaj , but it does work as expected. I am opening a new topic on community forum and post some screenshots over there. 

hopefully, you could help me over there. 

-John

**Comment by johnking** [comment]
For future readers: 

I have figured it out: 
- in `grunt` build, i.e, the dev mode, the `graphiql` is enabled and I could access it via `localhost:4567/graphql`.
<img width="1019" alt="screen shot 2018-12-16 at 14 53 23" src="https://user-images.githubusercontent.com/1787137/50058309-5a8b6700-0144-11e9-85e9-8f71771a8584.png">

- in `nodebb` build, I assume it is a production build, the `graphiql` is disabled so I could not access the interactive UI from `localhost:4567/graphql`. 

thanks all of you @pitaj, @pauljherring and bot @nodebb-misty  😄
