### ISSUE TITLE
Prevent invalid email addresses when registering and changing email addresses

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7123]
Although you could say that it's the users own fault - it shouldn't be possible to create an account with emails like:

tomrade@
something@web (notice that there is no domain ending like .com)

Around 2-4% have such an email in our forums which is pretty annoying because they can never confirm their address and they start complaining.

**Comment by tom-rade** [comment]
Please use DNS checks or at least check for a "." after the @ symbol to prevent the most common errors.

**Comment by julianlam** [comment]
Please read this to learn why we only check for `@`:

https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

The email validation is the check. If your users are frustrated they can't validate their emails then tell them to put real emails in.

**Comment by pauljherring** [comment]
> something@web (notice that there is no domain ending like .com)

>  or at least check for a "." after the @ symbol to prevent the most common errors.

There is no requirement for a period after the `@`.

```
$ dig ai MX

; <<>> DiG 9.11.3-1ubuntu1.3-Ubuntu <<>> ai MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30974
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;ai.                            IN      MX

;; ANSWER SECTION:
ai.                     86400   IN      MX      10 mail.offshore.ai.

;; Query time: 30 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sun Dec 16 11:02:02 GMT 2018
;; MSG SIZE  rcvd: 61
``
