### ISSUE TITLE
Clicking on links while registering not possible

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7125]
I have terms of use, a privacy policy and an imprint in my footer which cannot be clicked after the completing the first step (where you enter your username, email and so on) of the registration. Once a user is in the second step where a user has to check the checkboxes - any links a user clicks are redirected back to the registration page -and because of this, the terms of use, the privacy policy and imprint links are not clickable.

**Comment by tom-rade** [comment]
Push

**Comment by Filprots** [comment]
I'm suffering the same issue at the moment. Is it solved somehow?

**Comment by julianlam** [comment]
Unfortunately no, not at this time. I do realise it is a potential problem, so a workaround for now would be to host your privacy policy, TOS, etc, on an external website.

**Comment by julianlam** [comment]
Apologies for the 2 year delay :grimacing: 

This is now configurable via plugin hook. A listener registered to `filter:middleware.registrationComplete` will be passed `{ allowed: Array }`. You can push the path you'd like to allow to this array.

**Comment by julianlam** [comment]
Example listener:

```
plugin.allowTermsPage = async ({ allowed }) => {
	allowed.push('/terms');
	return { allowed };
};
```
