### ISSUE TITLE
Clicking on a topic when pagination is enabled is broken

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7126]
Enable pagination (10 posts per topic for example) and then fill out that topic until you have two buttons. Now click on an unread topic in the unread page - you will always land on the first page of the topic.

**Comment by barisusakli** [comment]
Can't reproduce, can you provide more detailed repro steps? Clicking the notification is taking me to the post that I was mentioned.

**Comment by tom-rade** [comment]
Can't seem to reproduce it right now. Sorry, will open an issue once I do

**Comment by tom-rade** [comment]
@barisusakli It doesn't happen with notifications. Now I found the issue: It's when clicking on unread topics. It's reproducable.

**Comment by tom-rade** [comment]
@barisusakli @julianlam Can you reproduce?

**Comment by pitaj** [comment]
Coming on the topic title in unread takes you to the first page. Clicking on the arrow on the right should go to the new post.

I'd that what you're saying doesn't work?

**Comment by tom-rade** [comment]
@pitaj Yeah. I thought that was bug.. My bad. I'm used to clicking on titles and always going to the page.
