### ISSUE TITLE
@ symbols in code block becomes user profile hyperlink

### ISSUE THREAD

**Issue by LonMcGregor** [NodeBB/NodeBB#7132]
(I don't have the version/config info, as I don't administrate the forum I found this issue on)

- **Exact steps to cause this issue:**
1. Make a new post
2. Add a triple-backtick code block

 \``` 

\```
3. In this, add `@param` (as would appear in some doc comments)
``` 
/* some comments @param some variable */
```

- **What you expected:**
`@param` is rendered as text
- **What happened instead:**
As there is a user called "Param", `@param` turns into a hyperlink to their user profile

**Comment by tom-rade** [comment]
In my opinion, that's how things should work. Code can also include the symbol "@" and it should not be turned into a link.

**Comment by pitaj** [comment]
Moved to the markdown repo
