### ISSUE TITLE
Missing translation for categories and unexpected socket close

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7140]
- **NodeBB version:** 1.11.1
- **NodeBB git hash:** b47f939bfcf075348b33632d8a15634f58a6eb54
- **Database type:** mongo
- **Database version:** v4.0.4
- **Exact steps to cause this issue:**
As a normal use, send a request to join a group
- **What you expected:**
An email gets sent as expected per the f4ea2c43abc9a10e96c6822c016bea2e000ccd97 change

- **What happened instead:**

Following error happened. I think it has to do with missing translations.

```
2018-12-19T11:42:51.444Z [4567/25] - error: Unexpected socket close
Error: Unexpected socket close
at Timeout.setTimeout [as _onTimeout] (/usr/src/app/node_modules/nodemailer/lib/smtp-transport/index.js:188:31)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at unrefdHandle (timers.js:520:7)
at Timer.processTimers (timers.js:222:12)

Missing translation "admin/settings/user:categoryWatchState"
Missing translation "admin/settings/user:categoryWatchState.watching"
Missing translation "admin/settings/user:categoryWatchState.notwatching"
Missing translation "admin/settings/user:categoryWatchState.ignoring"
Missing translation "notifications:notificationType_group-request-membership"
Missing translation "category:not-watching"
Missing translation "category:not-watching"
Missing translation "category:not-watching.description"
```

**Comment by pitaj** [comment]
Missing translations never result in an error.

Does sending a test email from the ACP work?

**Comment by tom-rade** [comment]
@pitaj Test mails work. But the groups broke - when I send a request, the group owner never gets any notifications or emails and the request is only visable for the person who sent it.

**Comment by tom-rade** [comment]
@pitaj Fixed by enabling a external mailserver. Error on my side. I tested on a isolated server.
