### ISSUE TITLE
Spiders should see 403 when accessing a topic that requires authentication

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#7147]
### 401 Unauthorized (RFC 7235)
> Similar to 403 Forbidden, but specifically for use when authentication is required and has failed **or has not yet been provided**. The response must include a WWW-Authenticate header field containing a challenge applicable to the requested resource. See Basic access authentication and Digest access authentication.[34] 401 semantically means "unauthenticated",[35] i.e. the user does not have the necessary credentials.

Right now we 302 the user to the login page. This works fine for browsers as it is a transparent redirect, but a spider shouldn't follow the redirect to `/login`, and should be greeted with a `401 Unauthorized` instead.

We can't serve 401 to everyone w/ redirect because browsers don't always read the `Location` header and redirect when it's not 3xx

**Comment by julianlam** [comment]
You can use `req.isSpider()` to determine whether it is a spider or not.

**Comment by pauljherring** [comment]
Are you sure you want 401?

> The response **must include a [WWW-Authenticate header field](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate)** containing a challenge applicable to the requested resource. 

I've not looked, but I'm fairly certain that is not an authentication method NodeBB uses...

**Comment by julianlam** [comment]
Mm, good point, it looks like 401 isn't what I'm looking for. Would you recommend we stick with the 302?

**Comment by pauljherring** [comment]
[403 Forbidden](https://tools.ietf.org/html/rfc7231#page-59) seems a better fit:

> If authentication credentials were provided in the request, the server considers them insufficient to grant access. The client SHOULD NOT automatically repeat the request with the same credentials. The client MAY repeat the request with new or different credentials. However, a request might be forbidden for reasons unrelated to the credentials.

**Comment by julianlam** [comment]
That works for me :+1:

**Comment by julianlam** [comment]
@barisusakli As of 9f5062682dca1ecdfc87294cb768988ddde42d54 it seems `req.isSpider()` is no longer preferred? Just wanted to ask why.

**Comment by barisusakli** [comment]
req.isSpider is called once [here](https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L33) and uid is set to -1 if it's true, so no need to call it again. Each isSpider call runs the user-agent string true ~20 regex tests.

**Comment by julianlam** [comment]
Makes sense :+1:
