### ISSUE TITLE
Prevent duplicate posts/replies

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7154]
It would be nice, if person B replies to person A, and that reply from person B only gets shown under the original post from person A. Like in a normal comment system under blogs.
Currently, duplicates of posts are shown when opening the reply-"link".

**Comment by pitaj** [comment]
Clicking the reply thing shows a list of all of the replies in order. What are you suggesting?

**Comment by julianlam** [comment]
He's suggesting a fully threaded way to display posts in a thread.

It is a huge amount of work and would require a refactor of the logic in core as well as changes in themes to support it.

There's some desire for it but at this time we will not consider adding it to our roadmap (unless the work is sponsored) as it increases the amount of stuff to maintain in core.
