### ISSUE TITLE
Set URL after logging in

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7156]
Any way to redirect the user to /unread after logging in (but for non-users show categories)

Merry Christmas

**Comment by pauljherring** [comment]
[/user/me/settings](#)

![screenshot from 2018-12-24 15-05-30](https://user-images.githubusercontent.com/3939886/50402299-81bde600-078d-11e9-806a-77fe92265480.png)

![screenshot from 2018-12-24 15-05-45](https://user-images.githubusercontent.com/3939886/50402311-a1eda500-078d-11e9-8774-19b2a2c1bb03.png)

**Comment by tom-rade** [comment]
@pauljherring Across all users tho

**Comment by pauljherring** [comment]
[/admin/general/homepage](#)

![screenshot from 2018-12-24 15-47-46](https://user-images.githubusercontent.com/3939886/50403037-5fc76200-0793-11e9-8138-91796f33a731.png)

![screenshot from 2018-12-24 15-47-55](https://user-images.githubusercontent.com/3939886/50403036-5f2ecb80-0793-11e9-8410-aded9b5c0f53.png)
