### ISSUE TITLE
Can't open composer on Android

### ISSUE THREAD

**Issue by yoyoyohamapi** [NodeBB/NodeBB#7162]
- **NodeBB version:**  1.11.1
- **NodeBB git hash:** 

- **Database type:** mongo
- **Database version:**  v4

- **Exact steps to cause this issue:**
  - click new topic/reply button

- **What you expected:**
composer open

- **What happened instead:**
  - composer doesn't open on QQBrowser, UCBrowser... but can open on Chrome
  - it's ok on IOS but not on Android, I test the [official website](https://community.nodebb.org) of NodeBB on Android, problem also exists.

**Comment by Jerry-FD** [comment]
+1 same problem

**Comment by pig315** [comment]
+1 the same

**Comment by julianlam** [comment]
![screenshot_20181225-215630](https://user-images.githubusercontent.com/923011/50430114-29bbd800-0890-11e9-901b-6dc07d7d42a3.png)

Unfortunately seems to be working fine in Firefox Mobile on my android device. Are you all accessing the site from a specific country?

**Comment by yoyoyohamapi** [comment]
> ![screenshot_20181225-215630](https://user-images.githubusercontent.com/923011/50430114-29bbd800-0890-11e9-901b-6dc07d7d42a3.png)
> 
> Unfortunately seems to be working fine in Firefox Mobile on my android device. Are you all accessing the site from a specific country?

Firefox and Chrome mobile works fine. But in china, people prefer QQ Browser, UC Browser which cannot open composer even in https://community.nodebb.org

**Comment by pitaj** [comment]
I have never heard of QQBrowser or UCBrowser in my life. I assume that the reason they aren't working is because they're using old browser engines. On iOS, every browser is essentially Safari, but on Android, it's up to them.

**Comment by julianlam** [comment]
Would be best if we could figure out what the error is, however...

**Comment by yoyoyohamapi** [comment]
upvote/downvote, quote cannot work either

**Comment by julianlam** [comment]
Regression identified: https://github.com/NodeBB/NodeBB/commit/c343b93a37cb7d50f7d610cdcd55aeb20e6310ef#diff-c4e482dcd6aa65c78062d39320d5d102R123

**Comment by yoyoyohamapi** [comment]
@julianlam Good job. Your bug fix is always fast. ☺ 👍
