### ISSUE TITLE
About nodeBB docker installation

### ISSUE THREAD

**Issue by Vast-Stars** [NodeBB/NodeBB#7173]
I want to know about https://hub.docker.com/r/nodebb/docker. Is it official？ Why are the source repository(https://github.com/NodeBB/docker-builds) doesn't exist? And is there any  guide about  installation by docker?

**Comment by julianlam** [comment]
Not sure about Docker Hub, the Dockerfile in the root of this repo should work.

**Comment by julianlam** [comment]
Docker support in NodeBB is entirely community driven, though this may change in the future.
