### ISSUE TITLE
Display "glitch" when logging in

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#7176]
This is a small, but annoying glitch I discovered after upgrading from 1.10.2 to 1.11.1.
I could also reproduce this on community.nodebb.org.

There's a super short amount of time after logging in in which it seems like all existing css is getting unloaded (except for custom css configured in the acp), therefore resulting in a weird screen for under a second. This also effects the login screen you get when logging into the ACP.

This issue is especially noticeable when logging in on a mobile phone because it takes longer for the HTML to load due to the slower processor, that's also where I noticed it the first time.

I wasn't able to take a screenshot because it's such a short amount of time, and most of the time the time-frame is almost non existent (not even 1 10th of a second if you ask me), but hopefully you should be able to reproduce this issue on your end as well.

**Comment by julianlam** [comment]
Thanks, yes, I've noticed this flash of unstyled content as well. It's to do with switching of skins, possibly. Will take a closer look.

**Comment by tom-rade** [comment]
Yep, can confirm this as well. I thought it was an error on my side.

**Comment by julianlam** [comment]
Okay, so after a bit of time looking into optimizing the reskin call, I am coming up short as to how to resolve this without causing that flash of unstyled content. It may be easiest to simply notify the user to refresh their browser if a skin was changed.

**Comment by julianlam** [comment]
Nevermind, got it :smile:

**Comment by tom-rade** [comment]
@julianlam The bug still happens with the newest master. Our forum never used any non-default skins, nor did I ever select any skins. I still get the weird CSS when logging in after hard-refreshing.

**Comment by julianlam** [comment]
Unable to reproduce at this time.
