### ISSUE TITLE
Swiping away the sidebar doesn't hide loading animation

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#7178]
I noticed this in NodeBB v1.11.1, also reproduceable on community.nodebb.org
This is a mobile-only issue I think.
When clicking on the 3 bars in the top left corner to open the sidebar, and then swiping it away, the button doesn't return to its "3 bar"-Form, but insteads remains a loading animation.
Once you click/touch somewhere else, everything looks as usual again.
Note that this issue doesn't happen if the sidebar is opened with a swipe in the first place.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7160
