### ISSUE TITLE
Re-ordering Pinned Topics no longer works

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7179]
- **NodeBB version:** 1.11.1
- **NodeBB git hash:** b0a44d866b08c1dc8b6d1c37364e8fa4fd21bf34
- **Database type:** mongo
- **Database version:** 3.6
- **Exact steps to cause this issue:**
  1. Visit a category page with a lot of pinned topics
  2. Reorder some of the pinned topics
  3. Navigate away from the category page
  4. Navigate back to that category page

- **What you expected:**
  - The pinned topics should be in the order that I created.

- **What happened instead:**

  - The topics are not re-ordered.

**Comment by djensen47** [comment]
The behavior is inconsistent. On one category, the re-order works fine. On another it doesn't work at all.

**Comment by barisusakli** [comment]
How many pinned topics are there?

**Comment by djensen47** [comment]
Broken category has 8:
https://www.axisandallies.org/forums/category/15/website-forum-discussion

The one that works has 5:
https://www.axisandallies.org/forums/category/12/welcome

**Comment by djensen47** [comment]
Actually, now it's broken for both of those categories.

Maybe the re-order only works the first time?

**Comment by barisusakli** [comment]
Can you open your network console and post the data sent from the websocket call `topics.orderPinnedTopics`

**Comment by barisusakli** [comment]
Sample output from our forum when I order topics

![image](https://user-images.githubusercontent.com/2583394/50575586-362fbb80-0dcf-11e9-8d85-2921d49d367e.png)

**Comment by djensen47** [comment]
Here's the output after I move the second one to the first position:

![image](https://user-images.githubusercontent.com/527865/50576972-6462ca80-0dd2-11e9-882c-f22892a98242.png)

**Comment by barisusakli** [comment]
And does the topic id and the order match? Or is it showing the wrong id?

**Comment by djensen47** [comment]
Yes, the order matches.

**Comment by barisusakli** [comment]
Thanks found the issue.

**Comment by djensen47** [comment]
Thanks for looking into it and Happy New Year! 🎉

**Comment by barisusakli** [comment]
@djensen47 Happy new year!

fyi this was happening due to the suggested topics widget having the same pinned topics and the jquery selector was finding those as well. Hence why you have 16 items in the array when you had only 8 pinned topics.
