### ISSUE TITLE
Source Maps cause console warnings in ACP

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#7181]
NodeBB Version: 1.11.1
Jus noticed this today when I tried to figure out why the version check was failing (I'm pretty sure 60 requests per hour are the problem, you might want to redesign the system so the request is done client side again, or NodeBB checks every minute or 2 and caches the result so the dashboard page doesn't take ages to load compared to the other pages, should I open an issue?).
When in the ACP, the browser tries to find non-existent source maps:
![Screenshot](https://user-images.githubusercontent.com/8350879/50578056-5e053a80-0e34-11e9-96ec-f6d5d49f76c7.png)
Not happening on "normal" pages.

**Comment by pitaj** [comment]
Can you provide the response body for one of those files?

**Comment by RoiEXLab** [comment]
The url just returns the default minified js

**Comment by pitaj** [comment]
No I mean one of the source map files

**Comment by RoiEXLab** [comment]
I'm not 100% sure, if this is the right URL, but it returns an empty response with status code 200:
https://forums.triplea-game.org/assets/src/modules/public/src/modules/translator.js.map

**Comment by RoiEXLab** [comment]
Ohhhh I see the problem.
The url is supposed to be https://forums.triplea-game.org/assets/src/modules/translator.js.map instead, but because of the relative path it isn't

**Comment by RoiEXLab** [comment]
Also invalid URLs in assets should probably return 404 instead of 200

**Comment by pitaj** [comment]
Pretty sure it's returning an empty response because the Regex here is wrong, should have a `$` at the end:

https://github.com/NodeBB/NodeBB/blob/ae0fe5e880683df5b0650d40d969f68ebe58f8b6/src/controllers/404.js#L12

**Comment by pitaj** [comment]
Need to change this line:

https://github.com/NodeBB/NodeBB/blob/master/src/meta/minifier.js#L235

So it uses the basename instead of the whole path, like
```js
data.filename.split(/[\/\\]/).pop() + '.map'
```

**Comment by RoiEXLab** [comment]
That's what I though 👍
