### ISSUE TITLE
Delete/Hide posts of banned users

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7182]
What should admin/mods do when a user posts inappropriate content und gets banned? His posts are still visable. Shouldn't the posts get removed/hidden too (Feature)? Or is there a current way to do this?

**Comment by pauljherring** [comment]
> *[banning users]*
> Shouldn't the posts get removed/hidden too.

Depends on why they got banned. On ours people get banned for:

1. Posting spam, if they get through all the other filters.
2. Being more obnoxious than most of the other people on the forum.

In the case of 1, the spam is usually removed manually, however occasionally all we've done if the post has generated a sensible (FSVO) conversation, the post is usually neutered to leave context.

In the case of 2, there's no real reason to remove anything, especially older posts.

So no. The default behaviour should be to do nothing with all their posts.

> Or is there a current way to do this?

Delete the user, instead of just banning them?

**Comment by tom-rade** [comment]
@pauljherring Hmm okay. But what if someone posts something very offensive and maybe rascist. Their posts should be hidden/deleted, but the account itself should only be banned. That's how I know it from most forums. Should be a feature in NodeBB I think.

**Comment by julianlam** [comment]
No, this will not be a feature. As PJH says, if they're posting a one off post that gets them banned, their prior posting history is still important and should be preserved, thus the offensive post should be deleted manually.

If their entire posting history is garbage, just delete the account entirely.

**Comment by tom-rade** [comment]
@julianlam Maybe the posts should get deleted (hidden) rather than actually permanently deleted.

Because deleting the entire account doesn't preserve their history (evience). Also hiding/non-permanent deletions won't annoy other users while preserving the important history as evidence.

**Comment by pauljherring** [comment]
If your banned user has been posting offensive stuff, and it needs to be recorded for <del>posterity</del> evidence, then the last thing you want to be doing is deleting it, and instead should be manually moving it out of sight to a hidden category for example.

But the number of use-cases, for what you appear to be asking for in a normally functioning forum, pales into insignificance to  others, such as the two I mentioned in my post, both of which involve doing little if there's a large posting history, and little if there's a small one:

1. User posts 'offensive' (whatever that means in this context, that doesn't encapsulate other items here)
    - Ban user, move relevant posts to a **new topic in a *hidden-to-normal members* category** or
    - Delete user, and all their posts
2. User posts spam as a new user
   - Ban user, delete/defang posts or
   - Delete user, and all their posts
3. User goes rogue
   - Ban user, delete/hide relevant posts, leave rest of post history alone or
   - Delete user, and all their posts (rather nuclear, but hey - the option's there)

Which use-case are you trying to describe that is not covered here? Or is it that bit in bold that you're after?
