### ISSUE TITLE
Topics, categories and users can be watching, tags can watched?

### ISSUE THREAD

**Issue by pig315** [NodeBB/NodeBB#7210]
NodeBB version: 1.11.1
Database type: mongo

Topics, categories and users can be watching, tags can watched?
![2019-01-09 11 04 17](https://user-images.githubusercontent.com/45277553/50874549-54b13a80-13ff-11e9-8cf3-0e7cbe0bb887.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7205
