### ISSUE TITLE
Allow to add custom class to navigation <li>

### ISSUE THREAD

**Issue by EnriqueAnakena** [NodeBB/NodeBB#7211]
- NodeBB version: 1.10.2
- NodeBB git hash: 5d3c814d57a4dc28fdc0c799c8d1f7b9325ea8e8
- Database type: mongo v4.0.4

- the {navigation.class} from menu.tpl can't be set anywhere.
I'm trying to create a custom main nav from a custom subTheme, and when I try to find where to add this variable in the General > Navigation  I find out that you can add this parameter but it's present on the templates.
The li tag just gets the class active when the item is active but you can't add a custom class to it.
Can you add a field to add this parameter?

Thank you so much.

**Comment by julianlam** [comment]
While this issue can be solved easily with the addition of an input field to set navigation.class, this module needs refactoring. The data in its entirety is saved as JSON in `navigation:enabled` :confused:
