### ISSUE TITLE
Chat on mobile - hard to push send button because of other user's avatar

### ISSUE THREAD

**Issue by yayacannes** [NodeBB/NodeBB#7216]
- **NodeBB version:** LAST
- **NodeBB git hash:** 

- **Database type:** mongo, redis, or postgres
- **Database version:** LAST

- **Exact steps to cause this issue:**

- **What you expected:**
no badge or other place on the screen
- **What happened instead:**
user's badge is on the send message button

**Comment by yayacannes** [comment]
SCREEN : https://screenshot.net/9w3zxb9

**Comment by pitaj** [comment]
Probably could have just changed some z-indexes :shrug:

**Comment by julianlam** [comment]
Nein, z-index changes would cause modals and drop downs to stop working with chats
