### ISSUE TITLE
Missing icon/indicator admin > general > navigation

### ISSUE THREAD

**Issue by garrettbryan** [NodeBB/NodeBB#7226]
- **NodeBB version:** v1.11.1
- **NodeBB git hash:** 53c13976b67c2c7f41428d68911f08b00cbe48e7

- **Database type:** mongo
- **Database version:** 4.0.4
![screenshot from 2019-01-11 11-18-57](https://user-images.githubusercontent.com/8527386/51047442-7bee4000-1596-11e9-9a92-86bf32cec87c.png)

- **Exact steps to cause this issue:**

- **What you expected:**
I expected to see some clickable indicator to update the nav details.

- **What happened instead:**

Instead, choosing "No Icon" removes any identifier. If this is at the end of the list then the user may overlook the option.

**Comment by garrettbryan** [comment]
Not sure why my steps didn't come through.
I used to modal to change the Icon.
I clicked no Icon.

**Comment by pitaj** [comment]
Ah so the issue is that if you set "no icon" it may be way to lose the entry in the ACP page.
