### ISSUE TITLE
Option to enable email replies

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7239]
Many many users tried to answer via email in our forum which uses simple SMTP to send emails. Would it be possible to setup POP3/IMAP for user replies? Would be a nice feature.

**Comment by julianlam** [comment]
Inbound email handling is available on the mandrill and sendgrid plugins.

**Comment by tom-rade** [comment]
@julianlam My question was regarding normal POP3/IMAP without external paid services. I mean stuff like Gmail or self-hosted mail servers, not about madrill and sendgrid.
