### ISSUE TITLE
A group owner cannot kick himself out of the group

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7242]
Just a minor issue - not very important at all, a correction of #7241. A group owner cannot kick himself out of the group.

**Comment by julianlam** [comment]
To _kick_ yourself out of a group is a pointless action. Just de-owner yourself (assign someone else as owner first), then leave the group...

**Comment by tom-rade** [comment]
@julianlam Yeah, ok. That makes sense.
