### ISSUE TITLE
Large chat rooms/notifications with many recipients hang the thread

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#7244]
NodeBB/nodebb-plugin-global-chat#5

Probably needs batching server-side.

**Comment by PostMidnight** [comment]
Hi @pitaj 

A side point: Further to batching, see https://github.com/NodeBB/NodeBB/issues/7192
Echoing the typed message to the screen (and have the client attempt pushing it to the server asynchronously with random timeout intervals), will make the user "feel" a lot better knowing his precious typed message is being broadcasted and not lost.

**Comment by arranka** [comment]
let me give an opinion
The global chat will only be on the main page foro.com
when a user enters to post on a topic they will no longer see the chat, therefore they will not be in the chat either, they will not see the chat, the users in the chat will not see this user
when the user returns to the main page foro.com will return to enter the chat
inside the chat you can see the last 15 messages to the newcomer
but if this user wants to see more messages from these 15, he could click to see the chat history file, where all the messages sent to the chat are in the last 2 or 3 days, he could even answer messages from 1 or 2 days ago

This could solve the chat for many users

The chats for groups or team please, leave them as they are, those are fine.

The global chat fixed on the forum.com page and only you can see there who wants to use it

thanks for reading me

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/11779
