### ISSUE TITLE
Post Edit UX/UI issue

### ISSUE THREAD

**Issue by fais3000** [NodeBB/NodeBB#7245]
Nodebb 1.11.1
When user try to edit a message on small screens the cursor jumps randomly making it impossible to edit a post.

Here is a screencap of when it happens.
https://chatrooms.talkwithstranger.com/assets/uploads/files/1547377895188-svid_20190113_163910_1.mp4

Users had the same issue before even with 4 or 5 smaller tags.

**Comment by pitaj** [comment]
Why would you use a video which clearly doesn't display the issue you're reporting? All that video shows is an issue where tags make it impossible to edit the content of the post, which is an issue in itself:
NodeBB/nodebb-plugin-composer-default#118

Regardless, this belongs on the composer repository. Please open a new issue when you have an example of what you're talking about.
