### ISSUE TITLE
Zen mode doesn't work on Chromium browsers

### ISSUE THREAD

**Issue by 2rara** [NodeBB/NodeBB#7247]
- **NodeBB version: 1.10.2 and the one community.nodebb.org is running on today** 
- **NodeBB git hash:N/A** 
- **Database type:N/A**
- **Database version:N/A** 
- **Exact steps to cause this issue:**
	1. Click the reply button to a forum post.
	2. Click the zen mode button.

- **What you expected:**
It goes fullscreen.
- **What happened instead:**
Nothing happens. 
Vivaldi 2.2.1388.37 and Chrome 71.0.3578.98 show the following error in the console:
´´´
Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object. screenfull.js:93
´´´

The issue is also mentioned here:
https://community.nodebb.org/topic/13448/zen-mode-issues

Thank you!

**Comment by julianlam** [comment]
nodebb/nodebb-plugin-composer-default#117
