### ISSUE TITLE
Users can see post edit history

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#7258]
- **NodeBB version:** 1.11.1
- **Database type:** mongo

https://github.com/NodeBB/NodeBB/issues/6425

**Comment by mohammadhassan99** [comment]
All users can see edit history. I think it should be limited for users or it can be optional. I also made #6425 for it and as I know, it supposed to be a privilege.


![2019-01-16_213642](https://user-images.githubusercontent.com/31972226/51270542-76e82100-19da-11e9-83bd-0cf7057fb8de.png)

**Comment by julianlam** [comment]
Right, it has been made a category privilege here so it can be specified on a per category basis. I don't see what the issue is here, is it not working?

**Comment by mohammadhassan99** [comment]
Oops, yes you're right. It didn't work at first I though it was a bug.

Thanks @julianlam :)
