### ISSUE TITLE
Server-side skin building issues

### ISSUE THREAD

**Issue by phit** [NodeBB/NodeBB#7266]
- **NodeBB version:** 1.11.1
- **NodeBB git hash:** 53c13976b67c2c7f41428d68911f08b00cbe48e7

- **Database type:** mongo
- **Database version:** 

- **Exact steps to cause this issue:**
use persona with e.g. the lumen theme
upgrade from 1.9.x
look at your theme
- **What you expected:**
to look the same as before
- **What happened instead:**
looks different/broken

another big issue for wanting to edit bootswatch themes the body classes no longer includes the actual active skin its just `skin-`, it should always have the skin name there like before even when the user is using the default skin (default being whatever I selected in the admin panel)

the easiest way to spot this is looking at the headcrumb in the category overview
before https://i.imgur.com/o9qLjRk.png
after https://i.imgur.com/RMYTPvd.png

for now i disabled users switching skin and added the old theme to the custom header
```
<link id="bootswatchCSS" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-gv0oNvwnqzF6ULI9TVsSmnULNb3zasNysvWwfT/s4l8k5I+g6oFz9dye0wg3rQ2Q" crossorigin="anonymous">
```

i also tried `npm i bootswatch@3.3.7` as 3.4.0 was installed by the `^3` set in the package.json but no luck

**Comment by barisusakli** [comment]
Seems like the body class never gets added the `skin-<skinName>` when you change the skin from the ACP.

**Comment by julianlam** [comment]
Was positive I didn't remove that logic, but I will check, thanks

**Comment by phit** [comment]
alright cherry picking these, seems to work! unfortunately there still seem to be compilation issues, lets take the case of `.breadcrumb`

https://i.imgur.com/PBbHJvP.png

the padding and background color are all messed up for it and there's tons of issues like this, neither the background nor the padding should be 0

here is the compiled bootswatch css https://github.com/thomaspark/bootswatch/blob/v3.3.7/lumen/bootstrap.css#L4697

actually i looked everywhere in all the less files that should be pulled in and nowhere i could find the reference to that `0`

**Comment by julianlam** [comment]
Breadcrumbs are wonky on lumen only?

**Comment by phit** [comment]
I do not know how other themes looked before, so I have a hard time spotting changes, another thing I've noticed are the font color being `#999` in a lot of places where it was a darker black before.

**Comment by phit** [comment]
@julianlam mind reopening so this doesn't get forgotten?

**Comment by julianlam** [comment]
Padding is defined zero here: https://github.com/NodeBB/nodebb-theme-persona/blob/master/less/header.less#L271

It seems most of the issues described here are due to overrides in Persona that _might_ no longer be needed now that skins are handled server-side.

**Comment by phit** [comment]
okay, so we just have to live will all themes being mostly broken? 
heck, even code highlight is not working, unless persona is overriding all code highlight now there's clearly an issue with the compilation

**Comment by pitaj** [comment]
The code highlighting issue seems to only apply on a hard load, not when ajaxify is involved. Just tested it on sandstone on the same topic.

**Comment by pitaj** [comment]
@phit do you mean all _skins_?

**Comment by pitaj** [comment]
Highlighting is broken even on Default, aka no skin, so something else is going on there.

**Comment by pitaj** [comment]
Could you give some specific examples besides the code highlighting?

**Comment by phit** [comment]
padding in general seems to vary wildly from the previous versions, pretty much everywhere

i mean just look at the shift in <https://github.com/NodeBB/NodeBB/issues/7266#issuecomment-455807705>

then theres random font color changes, another easy one to spot is, `a:hover` had `text-decoration: underline;` before the update with lumen now it is `text-decoration: none;`

breadcrumbs as mentioned before is the easiest to spot even if you haven't looked at the skins in detail before

**Comment by pitaj** [comment]
The thing is, these changes might actually be because now the skins are actually being applied correctly. Skins are now compiled inside less with the persona theme, so their variable changes and whatnot are more consistently applied.

I think it's likely that what used to be base bootstrap variables in the precompiled skins overriding persona variables are no longer showing up.

**Comment by phit** [comment]
sounds about right, but the result is persona overwriting the bootstrap theme and it looks terrible

the fix of applying the skin manually like I do right now shouldn't do anything, right now i put the bootstrap css after the generated stylesheet so it is overwritten and it solves all the issues I'm having..
and it makes the skin look like all other sites where i use bootstrap, persona should not change the look of a bootstrap skin so majorly

**Comment by julianlam** [comment]
@pitaj is right, it is because we are now properly loading skins and Persona is overwriting them. However that doesn't indicate a problem with the server-side skin building logic, which is why the issue was closed.

I'd recommend tracking these changes in a new issue so they can be individually looked at and fixed properly.
