### ISSUE TITLE
Granting the "moderate" privilege also grants "Reply to Topic" privilege

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#7268]
The reply privilege works well otherwise, but if moderate is given, then those users (or groups) are allowed to reply.

**Comment by julianlam** [comment]
Privileges are additive, what am I thinking :man_facepalming:

**Comment by pitaj** [comment]
Wasn't the point of this that the moderation privilege essentially automatically gives the reply privilege?

I'm not sure if that's desired behavior or not, but it doesn't have anything to do with privileges being additive.

**Comment by barisusakli** [comment]
Making someone an administrator or moderator implicitly gives them all permissions.

**Comment by pitaj** [comment]
But should it?

**Comment by barisusakli** [comment]
I think it should, it lets us make someone a mod from `/admin/manage/admins-mods` and don't have to deal with individual privileges.

**Comment by pitaj** [comment]
The alternative isn't configuring individual privileges, but setting up groups and adding users to the group.

**Comment by barisusakli** [comment]
I think that's more work, would have to create a group per category with the correct privileges then add users. Right now making someone a moderator is just giving that user the `moderate` privilege on that category without touching any groups.
