### ISSUE TITLE
Notifications can not be opened

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7269]
Hello, today I noticed that you can not open the notification window.

This is most likely due to flagging.

![zrzut ekranu z 2019-01-20 14-36-07](https://user-images.githubusercontent.com/24297084/51439892-c2dbe400-1cc0-11e9-8f95-150885b37f3e.png)

**Comment by PostMidnight** [comment]
It seems that the latest version in master fixes the above.

**Comment by julianlam** [comment]
Whoops, I typo'd the issue number in the commit:

  
https://github.com/NodeBB/NodeBB/commit/cee47f78b2af6a58d7d70457b22f986942c96540
