### ISSUE TITLE
The "flag" page does not have a full translation

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7270]
Hello, as in the topic.

The following words are not translated:

- Daily flags,
- notes,
- state,
- assignee

**Comment by julianlam** [comment]
Notes, state, and assignee are translatable: https://github.com/NodeBB/NodeBB/blob/master/public/language/en-GB/flags.json#L2

**Comment by youhosi** [comment]
@julianlam, in which case, these words are not translated.

![zrzut ekranu z 2019-01-22 18-55-28](https://user-images.githubusercontent.com/24297084/51555181-5820d900-1e77-11e9-8679-fa324db6a656.png)
![zrzut ekranu z 2019-01-22 18-55-19](https://user-images.githubusercontent.com/24297084/51555182-5820d900-1e77-11e9-98cf-75d614d8b3d4.png)

**Comment by julianlam** [comment]
What language, and when were those translations added?

**Comment by youhosi** [comment]
In Polish lang, and added year ago

**Comment by julianlam** [comment]
Ah, here it is not translated, yes:

![image](https://user-images.githubusercontent.com/923011/51557391-c8fdcc00-1e4a-11e9-9fd9-a8d14e954c8e.png)
