### ISSUE TITLE
Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7271]
During build the following warning is provided:

`Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
`
I believe this is related to autoprefixer dependency that may need updating.

**Comment by julianlam** [comment]
Report upstream please

**Comment by PostMidnight** [comment]
Done: https://github.com/postcss/autoprefixer/issues/1184

**Comment by PostMidnight** [comment]
The issue is not in autoprefixer (see: https://github.com/postcss/autoprefixer/issues/1184).
The issue is in nodebb's package.json. Looks like an older version of autoprefixer is used: (9.0.0 vs. current 9.4.6).
Running " npm update autoprefixer" fixes the issue at hand.
Kindly consider a slight change in package.json.
