### ISSUE TITLE
Outdated configuration for Nginx Scaling?

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7272]
This is the current recommended NGINX scaling settings in https://docs.nodebb.org/configuring/scaling/

```
    location @nodebb {
        proxy_pass http://io_nodes;
    }

    location ~ ^/assets/(.*) {
        root /path/to/nodebb/;
        try_files /build/public/$1 /public/$1 @nodebb;
    }

    location /plugins/ {
        root /path/to/nodebb/build/public/;
        try_files $uri @nodebb;
    }

    location / {
        proxy_pass http://io_nodes;
    }
}

```

According to wrk (load testing tool), I get 47 requests/sec without this and 44 requests/sec with the configuration to serve static files from Nginx. Usually Nginx static file serving increases this to a few hundred or even thousand requests per second.
And yes I've updated the `/path/to/nodebb/` and the paths seem to resolve correctly. I'm using this over Docker and mounting the same volumes on Nginx and NodeBB.

Is this configuration still up to date?

**Comment by julianlam** [comment]
Yes, the configuration is still up to date. Ensure the files are actually served by nginx by inspecting the headers. NodeBB sends `X-Powered-By`, whereas Nginx does not.
