### ISSUE TITLE
404 on /assets/client-noskin.css

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7276]
- **NodeBB version:** v1.11.1
- **NodeBB git hash:** 40637828af9ef89441666259326d0125a85a1b6d

- **Database type:** mongo
- **Database version:** v4.0.5
- **Theme:** Default Persona Theme
- **Skins** are disabled via Admin CP

**What happens?**
Users apparently get 404s for this path: `/assets/client-noskin.css`

**When does it happen/how to reproduce?**
- When logging in
- When logging out
- (Sometimes?) when being in /me/settings and switch back to /categories via Navigation buttons

**Comment by julianlam** [comment]
Thank you, that is helpful.

**Comment by julianlam** [comment]
Have this fixed, just want to make the code a little more efficient

**Comment by tom-rade** [comment]
@julianlam Nice. I'd rather have a later/slower, proper fix than a quick and dirty fix. Thank you :+1:

**Comment by tom-rade** [comment]
Also I'm wondering - maybe this has something to do with the CSS "glitching" bug... I'll test it after the commit is pushed.
