### ISSUE TITLE
Bad email notification formatting

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#7277]
This issue is almost 2 issues that I believe to have the same root cause.
I like that with the last big update email notifications keep their original markdown formatting.
However I noticed 2 oddities:
1. Images seem to have a fixed width. This is problematic for high resolution images especially on phones when in portrait mode, where this causes the rest of the content is made smaller to adjust for that (in the Gmail app).
2. Something seems odd when using plugins that affect the way the post is rendered. I noticed this with https://github.com/julianlam/nodebb-plugin-github-embed where in the email the profile pic is way too big and the content doesn't look like a box.

**Comment by barisusakli** [comment]
1. is fixed in https://github.com/NodeBB/NodeBB/commit/dbc4d8403d564c242c6bdfa7d478eb037976dbf1

2. requires some more work since the plugin uses custom less that core doesn't know about so it can't style those in the emails.

**Comment by julianlam** [comment]
Would perhaps a `filter:parse.email` be appropriate? Then it would be up to the individual plugins to handle support, while not breaking compatibility with existing post filtering...

**Comment by julianlam** [comment]
:point_up:
