### ISSUE TITLE
How to reset all sessions/cookies

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7280]
A question: Is there any command to delete all sessions and cookies from all users (logging them out) from both Mongo (previously used for sessions) and Redis (switched to while in production).

Some have session problems, probably due to the switch. Thank you.

**Comment by PostMidnight** [comment]
Go to ACP -> settings -> cookies -> revoke all sessions. 
I hope this is what you are looking for, good luck!

**Comment by tom-rade** [comment]
Thanks

**Comment by dac2020** [comment]
I know this is old but I cannot find anything on the Internet about this.
I somehow locked myself out of nodebb, keep getting Invalid Session after adding a domain cookie.
Now trying to find a way to clear session cookies from the command line. 
No idea if this is even the problem but trying what ever I can.
