### ISSUE TITLE
Update autoprefixer to avoid build error

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7286]
Reopening https://github.com/NodeBB/NodeBB/issues/7271 so it won't be forgotten:

During build the following warning is provided:

`Browserslist: caniuse-lite is outdated. Please run next command npm update caniuse-lite browserslist
`
Looks like an older version of autoprefixer is used in NodeBB package.json: 9.0.0 vs. current 9.4.6.
Running "npm update autoprefixer" fixes the issue at hand.

Kindly consider a slight change in package.json.

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
