### ISSUE TITLE
"Send Button" got overlapped with "Message" icon on mobile platform

### ISSUE THREAD

**Issue by kevinniu666** [NodeBB/NodeBB#7302]
- **NodeBB version:  1.11.1
- **NodeBB git hash: Used NodeBB Docker image, could not execute "git rev-parse HEAD"

- **Database type: redis
- **Database version:  5.0.3

- **Exact steps to cause this issue:**
    I tried with three devices , iPhone 6 , Xiaomi 8(Andriod) , iPad Mini, all of them have the same issue.
 1. login NodeBB with account

 2. Click on the 'Message' Icon at the top right corner of screen

![image](https://user-images.githubusercontent.com/31185341/51799504-313e1a80-225c-11e9-8e5b-b11fe5ed2aae.png)

3.Select one of the group chat in the list , i chose the first one.
![image](https://user-images.githubusercontent.com/31185341/51799505-38fdbf00-225c-11e9-9604-424b9c4ce093.png)

4.try to send a message in the group chat, you can see the ”Send" button is overlapped with "message" Icon.
![image](https://user-images.githubusercontent.com/31185341/51799508-40bd6380-225c-11e9-9518-1ca2d123b4c3.png)

- **What you expected:**
"Send” button has  sperate position in the screen and can be clicked.
- **What happened instead:**
I could not send a message as i could not click on "Send" Button(airplane icon).

Thanks.

**Comment by pitaj** [comment]
#7216
