### ISSUE TITLE
Login following password reset leads back to reset page

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7306]
Hi Devs,

This might be a bug worth of addressing. 
It took some time but I was able to reproduce it consistently on my setup and on https://community.nodebb.org

**Steps to reproduce:**

1. Log out,
2. Go to login page and press "forgot password".
3. Plug in an email address (example: "test@test.com").
4. Now go back to login page via the login link (top right corner).
5. Log in with your username and password.
6. Note that you will log in, the menu bar will show your notifications etc., however the main page will show the reset page. Furthermore, the url will point to the reset page (on the community forum the url following login is: https://community.nodebb.org/reset)

This is quite confusing for users who just completed reseting their password...

I believe this issue surfaced following: https://github.com/NodeBB/NodeBB/pull/6841.

See image attached.

![image](https://user-images.githubusercontent.com/43993784/51821443-e2d35f00-22e1-11e9-8e5a-f30965093237.png)

**Comment by julianlam** [comment]
For what it's worth, this is actually expected behaviour. The login is simply sending you back to the page you were on before you hit the login button.

However, I suppose reset shouldn't count.
