### ISSUE TITLE
Feature Request: Sort /users by last-online (and display last-online ts)

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7308]
Current Status:
/users is sorted by user-create ts. The user-create ts is further displayed below the user's avatar.

Potential Improvement:
Sort /users by last-online ts, and display the last-online ts below the user's avatar.
This might be slightly more useful, as it will allowing users to see who was last online and when.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5402
