### ISSUE TITLE
Allow users to delete their entire account (not just the profile)

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7318]
It would make a lot of sense if there was a way (like an option in the admin panel) to allow users to delete all their messages and the entire account (the way admins currently are able to do this). It would also be required by the GDPR as far as I know.

**Comment by julianlam** [comment]
> It would also be required by the GDPR as far as I know.

Contacting an administrator for account deletion satisfies the Right to be Forgotten portion of GDPR.

**Comment by julianlam** [comment]
We currently do not allow this because context is an important part of discussions, and so we feel that an administrator must do the act of deletion that removes all content for a user.

**Comment by tom-rade** [comment]
@julianlam Tho it's pretty annoying if you ask me.

**Comment by pauljherring** [comment]
> @julianlam Tho it's pretty annoying if you ask me.

How frequently has this happened so far?

**Comment by tom-rade** [comment]
@pauljherring about 20-30 times. Our forum has around 2000 members. But not all at the same time, but rather every 2-3 days which is - as I said - pretty annoying.

**Comment by pauljherring** [comment]
If you're getting that many people actively demanding that you delete their accounts, it sounds like you need more tools (or help with existing ones) to vet people coming onto the forum to begin with - deleting the accounts appears to be solving a symptom of something, rather than dealing with some underlying problem.

**Comment by tom-rade** [comment]
@pauljherring It's a political forum where people are upset very quickly. Additionally, we have many tin foil hat users that want to delete their entire accounts after trying out the forum.

But ok fine. I'll leave this closed then.
