### ISSUE TITLE
[Feature request] Threaded replies

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7319]
I know this is a lot of work, but it would be great if there was a way to make threaded replies like in mailing lists or Reddit. The UI implementation is mostly done (the answer-functionality looks great, but it's currently only possible to reply to a normal message, while it's not possible to reply to a reply - a threaded tree).

It would make huge topics very organised.

**Comment by PostMidnight** [comment]
Hi @tom-rade I did not try this plugin, so not sure if it will work or not, but take a look at:
https://github.com/NodeBB/nodebb-plugin-threaded-replies

**Comment by barisusakli** [comment]
That repo is deprecated so I deleted it, it's functionality is already added to core.

**Comment by barisusakli** [comment]
You can enable this with a plugin now. Listen for the hook `filter:config.get` and set `showNestedReplies` to true like below.

```
myPlugin.filterConfigGet = function (config, callback) {
   config.showNestedReplies = true;
   setImmediate(callback, null, config);
};
```

Keep in mind all posts will still be displayed in a flat manner.

![image](https://user-images.githubusercontent.com/2583394/56900579-244fe380-6a64-11e9-86ff-48974b8843ca.png)

**Comment by liamrosen** [comment]
@barisusakli Can you clarify your comment "You can enable this with a plugin now?" Does this mean we'd have to write a simple plugin that does this, or could we enable it as part of the config?

**Comment by barisusakli** [comment]
You need to write a plugin that does this or if you already have a theme you can do it there too

```
myPlugin.filterConfigGet = async function (config, callback) {
   config.showNestedReplies = true;
   setImmediate(callback, null, config);
};
```

**Comment by kostya-sim** [comment]
> You need to write a plugin that does this or if you already have a theme you can do it there too
> 
> ```
> myPlugin.filterConfigGet = async function (config, callback) {
>    config.showNestedReplies = true;
>    setImmediate(callback, null, config);
> };
> ```

Hi @barisusakli, I added your code to the custom javascript area of the theme, but is there away that all comments are shown by default. You have to click on each little arrow right now to open them.

**Comment by Chealer** [comment]
Thank you very much for reporting @tom-rade 

@barisusakli: Thanks but please clarify what you mean by ”all posts will still be displayed in a flat manner”. You mean the posts anterior to the plugin's activation?
