### ISSUE TITLE
Option to force users to force verification of their email before using the forum

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7320]
While on open forums like community.nodebb.org, it does not matter whether the user has an unverified account or has no account - he always has the same permissions.

But on closed forums, not-registered users should not see anything and the non-verified users should also not see anything after confirming their email. Otherwise a closed forum does not make much sense.

I'd appreciate this feature and it's very important for closed forums. Thanks you!

**Comment by PatheticMustan** [comment]
I reccomend looking at "invites", which allow you to invite by email, and only allow users to join by invite, which might be what you're looking for. There's also the option to force email verification in the ACP, somewhere in the "Settings>Users" maybe?

**Comment by barisusakli** [comment]
This should be possible not with the addition of verified/unverified user groups.  https://github.com/NodeBB/NodeBB/issues/8662
