### ISSUE TITLE
[composer/autocomplete] No composer .write element found

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7325]
Hi Devs,

Following sync to the current master, I am unable to @mention, as the mention selection window goes out of screen. In the console I am seeing: "[composer/autocomplete] No composer .write element found".

It seems this issue relates to: https://github.com/NodeBB/NodeBB/issues/7309
Perhaps the mention plugin needs updating?

**Comment by barisusakli** [comment]
composer-default or redactor? can you post a video of the bug

**Comment by PostMidnight** [comment]
I am using redactor. I know it sucks but Quill is way out... 
I just tried with plain vanilla forum with Redactor. Its very easy to reproduce.

**Comment by julianlam** [comment]
This is the autocomplete working fine on Redactor:
![image](https://user-images.githubusercontent.com/923011/52001115-adb74000-248c-11e9-8827-0a6941a1ab63.png)

The warning is irrelevant, and should not affect the autocomplete dialog opening, though it is a separate issue I'll look into.

**Comment by PostMidnight** [comment]
It does open but then it slides all the way to the left side (when in rtl).
I tried to fix it with CSS however the location (top, right, left) keep changing and the box overflows the redactor window. I'll play with it some more, but something definitely changed.

**Comment by julianlam** [comment]
The autocomplete also works fine with mentions, I tested both.

**Comment by PostMidnight** [comment]
Thank you!
Kindly see the below image. You may note the @mention window overflowed the editor both horizontally and vertically. It is instantiated with more lines that together > editor height. Furthermore, everything is pushed to the left.
![image](https://user-images.githubusercontent.com/43993784/52003884-69e52a80-24ce-11e9-936f-83a53a534080.png)

**Comment by PostMidnight** [comment]
While testing I tracked another issue.  Open redactor, fire mention but keep the mention selection window open. Now "discard" the redactor window: you will see that the @mention selection window will remain on screen (it used to close with redactor...). If you'll press one of the items on the selection box, you will see errors on console:
```
Uncaught Error: Unexpected
    at t.value (textcomplete.codemirror.min.js:1)
    at t.value (textcomplete.codemirror.min.js:1)
    at t.value (textcomplete.codemirror.min.js:1)
    at t.value (textcomplete.codemirror.min.js:1)
    at t.value (textcomplete.min.js:1)
    at t.i.emit (textcomplete.min.js:1)
    at t.value (textcomplete.min.js:1)
    at e.value (textcomplete.min.js:1)

```

**Comment by julianlam** [comment]
Unable to reproduce that issue. Ensure your core and composer-default versions are up to date.

**Comment by PostMidnight** [comment]
I just updated to the latest composer, I can confirm that the @mention selection window now closes property together with redactor. However the position as mention earlier is still wrong...

**Comment by PostMidnight** [comment]
Looking at the page code, here is the @mention selection window. Note the "right:1119.2px" statement that is largely responsible for the miss-location. 

<ul style="display: block;position: absolute;z-index: 20000;right: 1119.2px;top: 572px;margin-top: -161px;" class="composer-autocomplete-dropdown-deb914c3-d42e-4ef2-a4d3-8ec7f1914220 dropdown-menu textcomplete-dropdown"><li class="textcomplete-header">

**Comment by julianlam** [comment]
Reported upstream: https://github.com/yuku/textcomplete.contenteditable/pull/4

**Comment by PostMidnight** [comment]
Thank you so much!
Since this issue may impact others, might I suggest keeping it open till Takahashi-san has time to process the pull request?

**Comment by julianlam** [comment]
@PostMidnight it should be fine to leave this closed, I will be emailed when my PR is merged and I can bump the dependency accordingly.

**Comment by PostMidnight** [comment]
It seems Takahashi-san has processed your pull request.
The new version is working properly, at least on my setup.
Kindly bump the dependency, thanks again!

**Comment by julianlam** [comment]
:point_up:
