### ISSUE TITLE
"upvotes" and revocation "upvotes", the reputation have been increasing

### ISSUE THREAD

**Issue by mrzhqiang** [NodeBB/NodeBB#7327]
- **NodeBB version: v1.11.2** 
- **NodeBB git hash: 3a49b52ca1ad61423656920eed00400f0ae85924** 
- **Database type: redis**
- **Database version: Redis server v=3.2.11** 

- **Exact steps to cause this issue:**

	1. First I clicked on the "upvotes" button.
	2. Then, I clicked on the same button again.
        3. I found that reputation increased one on the original basis.
        4. Try again and again, and you'll get it every time.
        (I installed plugin of "Reputation Rules", so I'm not sure if it caused the problem.)

- **What you expected:**
I expected reputation is not changed when revocation some votes
- **What happened instead:**
...

**Comment by barisusakli** [comment]
Can you reproduce it on https://community.nodebb.org?

**Comment by mrzhqiang** [comment]
The bug from plugin of "Reputation Rules"
