### ISSUE TITLE
Link in queuing posts is not working properly.

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7332]
![zrzut ekranu z 2019-02-02 12-00-25](https://user-images.githubusercontent.com/24297084/52163428-2531dd00-26e2-11e9-87bf-42cf8dc34540.png)

**Comment by barisusakli** [comment]
Please provide reproduction steps.

**Comment by youhosi** [comment]
@barisusakli If you have set the Polish language then after clicking on "Settings → Post → Posting Restrictions" it moves to the link given above.

**Comment by barisusakli** [comment]
This was an issue in the translation string.  ` <a href=\\\"%1\\\">`
Fixed on transifex https://www.transifex.com/nodebb/nodebb/translate/#pl/admin-manage-post-queue/118705407
