### ISSUE TITLE
A few problems that I noticed

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7333]
- **NodeBB version:** 1.11.2
- **NodeBB git hash:** 8f69ffd41d87452132aa9ce83e683e8378fc6f53
- **Database version:** redis 4.0.9 

#### Delete topic

When deleting a topic, the information is immediately displayed that the post has been removed, and only after reload page the information about who removed it.

![zrzut ekranu z 2019-02-02 15-57-40](https://user-images.githubusercontent.com/24297084/52165611-4d7e0380-2703-11e9-947c-d83adc4d0c2b.png)

#### Widget Recent topics

If someone is on the page where he has the last topics set, and some other user will add a topic, he or she will keep the full date instead of a moment ago..

![zrzut ekranu z 2019-02-02 15-56-42](https://user-images.githubusercontent.com/24297084/52165600-34755280-2703-11e9-869f-6bd061a5a1e0.png)

#### The first topic in the category is not highlighted

After passing and returning, the "highlight" class is not added.

#### File download

Despite the setting of downloading files to private, guests can download them.

**Comment by barisusakli** [comment]
Please open widget issue in widget-essentials with more info
