### ISSUE TITLE
Titles in composer are invisible on mobile.

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7335]
![0eaf9647-92a5-4a72-a06b-62cdcd245971](https://user-images.githubusercontent.com/35382971/52220127-2b53c500-286c-11e9-9550-506c060ff272.gif)

- **NodeBB version:** 1.11.2
- **NodeBB git hash:** 3a49b52ca1ad61423656920eed00400f0ae85924
- **Database type:** mongo
- **Database version:** 3.6.10

- **Exact steps to cause this issue:**
1. I tried to make a post.
2. I typed stuff into the title, and it wasn't there! 🤯
- **What you expected:**
I expected the title to be there.
- **What happened instead:**
I didn't see the title!

**Comment by pitaj** [comment]
Need some more info:

- theme
- skin
- can you reproduce on https://community.nodebb.org ?

**Comment by PatheticMustan** [comment]
Persona Theme;
Every single theme;
Only seems to work when the composer is a separate route, and when the screen is large enough.

![281618de-b490-4277-8d54-72d7a85547e5](https://user-images.githubusercontent.com/35382971/52223715-37438500-2874-11e9-9a98-3d035519a6aa.png)
![00e08ad4-5989-44b7-9ce2-dab1653cceb9](https://user-images.githubusercontent.com/35382971/52223716-37438500-2874-11e9-93f9-5062d971fda0.png)

**Comment by pitaj** [comment]
Ah, perhaps the separate route composer is broken.
