### ISSUE TITLE
Move "Find Plugins" to top of the plugins page.

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7342]
Could the "search for plugins" be moved to the top of the "plugins" page?
To search for a plugin, you have to scroll all the way down. ;(
Just stick it at the top, and you no longer have to scroll the long list of plugins to search through the list!

**Comment by pitaj** [comment]
I believe it's displayed in the sidebar if your browser window isn't too small. We could change the order, though.

**Comment by PatheticMustan** [comment]
Sorry, I should have clarified. It's fine on Desktop, but on Mobile it's at the bottom. And it's hard to scroll with such tiny screens! :smile: Is there any way it can be formatted differently for smaller screens?
(Flexbox???)
