### ISSUE TITLE
Redis database number is now mandatory in config.json after upgrade from v1.10 to v1.11

### ISSUE THREAD

**Issue by zipang** [NodeBB/NodeBB#7352]
I managed to successfully (if not easily) apply all the update scripts from v1.10 to v1.11.
But on restarting i got this error in the log and nodebb was not available : 

```
2019-02-08T23:19:29.427Z [4567/20961] - error: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at (...)/nodebb/src/database/redis.js:189:29
(...)
2019-02-08T23:19:29.428Z [4567/20961] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
3 restarts in 10 seconds, most likely an error on startup. Halting.
```

After looking at the line in `src/database/redis.js`, i managed to see that `nconf` was expecting to read a database number inside the redis config : 
```
const keyInfo = redisData['db' + nconf.get('redis:database')];
```
Such a parameter _was not mandatory before this upgrade_, and i think it defaulted to 0 (db0)
So i managed to correct this error by adding the key `database` to my `config.json` : 

```json
(...)
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "database": 0
    }
```

Throwing an _explicit error message_ if the parameter is not found would be a better experience for the allready troubled admin who has spent the whole afternoon migrating his forum....
(i thought i had to rollback to v1.10 after all these useless efforts)
Ok... That was hard but ultimately worth the price ! :)

**Comment by pitaj** [comment]
Same as error here: https://community.nodebb.org/topic/13466/error-upgrading-from-1-10-to-1-11/11

Not sure why the property isn't included in the first place. How did you set up NodeBB?

**Comment by zipang** [comment]
Well.... with the setup script..! Not so long ago : in 2017 to be precise 
Surely now, the setup script creates a `database` entry in the redis section in `config.json`, but you must admit that somewhere in the past, it didn't and the config relied on a default value : 0 for redis.
