### ISSUE TITLE
RFC Email Verification (Allow all emails that actually are valid!)

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7353]
- **Exact steps to cause this issue:**
1: Stick in a "[valid](https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address)" email like

```"()<>[]:,;@\\"!#$%&'-/=?^_`{}| ~.a"@example.org```

- **What you expected:**
It should be valid.

- **What happened instead:**
It was not valid. ;(
![image](https://user-images.githubusercontent.com/35382971/52514111-1e710180-2bdd-11e9-9484-b51d7c7c5c51.png)

**Comment by PatheticMustan** [comment]
Maybe I'm wrong?
???

**Comment by pitaj** [comment]
The email is found to be invalid because it has a semicolon (`;`) and a comma (`,`) which are both explicitly prohibited here:

https://github.com/NodeBB/NodeBB/blob/master/public/src/utils.js#L390

This stems from a fix for #6317
