### ISSUE TITLE
Avatar of users logged with Facebook don't show anymore

### ISSUE THREAD

**Issue by zipang** [NodeBB/NodeBB#7355]
After the (infamous) upgrade to v1.11, avatars of users logged with Facebook SSO don't load anymore.
URL of these images are of the form : 
```
https://graph.facebook.com/999999999999999/picture?type=large
```
and they are currently broken..

I can observe this issue on the [nodebb community forum](https://community.nodebb.org/users) itself : 
![facebook avatars don t show](https://user-images.githubusercontent.com/658082/52524033-93554180-2c98-11e9-98d6-f4d3be92b039.png)

**Comment by pitaj** [comment]
It was happening before v1.11 for me, I'm fairly certain it occurs if you aren't signed into Facebook in the breeder you're using to access NodeBB

**Comment by zipang** [comment]
Well.... in fact i'm now logged into Facebook but i still don't see the pictures..
If i try to paste on of these picture URL in my browser, it doesn't display the image but instead proposes me to download it.. and it must first follow a 302 redirection..
And i'm pretty sure i could see these avatars before the upgrade...

**Comment by zipang** [comment]
OK ! I got it ! If i turn off the don't track function in Firefox, the images reappear !
So it's a side effect of the block trackers feature in Firefox !!
We can close this issue ! :)

**Comment by julianlam** [comment]
Ugh that's really annoying of Facebook to do... I wonder if the Facebook tab plugin fixes this issue..

**Comment by zipang** [comment]
Yep, i think that's a reaction of Facebook to prevent users to use the Don't Track feature of Firefox !! Well played Facebook... ! 👏 😲
