### ISSUE TITLE
deedle-dum notification doesn't work in /admin/general/sounds

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7363]

**Comment by barisusakli** [comment]
This seems to be an issue with https://github.com/julianlam/nodebb-plugin-soundpack-default/blob/master/sounds/notification.mp3, it doesnt play with `var a = new Audio(filePath); a.play()` while the other files play.

**Comment by oplik0** [comment]
I just checked and it seems to work fine for me on Firefox, Edge and Vivaldi. Both in locally hosted NodeBB instance almost up to date with master branch here with debugger attached and remote instance running 1.12.2 on Ubuntu.

**Comment by barisusakli** [comment]
Seems like it is working on chrome now as well.
