### ISSUE TITLE
Chat: autocomplete fails on user search

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7366]
Hi y’all.

This Issue was found on latest master, and in NodeBB community forum.

To reproduce: press the chat button 

The issue relates to autocomplete.js

`/ This is a generic method that is also used by the chat
	autocomplete.setup = function (data) {
		var element = data.element.get(0);
		var editor;
		if (element.nodeName === 'TEXTAREA') {
			var Textarea = window.Textcomplete.editors.Textarea;
			editor = new Textarea(element);
		} else if (element.nodeName === 'DIV' && element.getAttribute('contenteditable') === 'true') {
			var ContentEditable = window.Textcomplete.editors.ContentEditable;
			editor = new ContentEditable(element);
		}`

the if(element.nodeName) statement fails since element is undefined.

**Comment by julianlam** [comment]
> press the chat button

What does this even mean? There are many buttons related to chat.

**Comment by PostMidnight** [comment]
OK sorry, I thought it was self-explanatory. I'll try to improve next time.
