### ISSUE TITLE
1. Upgrade script fails: body.map is not a function; 2. Lodash vulnerabilities

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7368]
Hi,

Just synced with master and tried to build the code with ./nodebb upgrade and noticed the following:

1.,The number of vulnerabilities (moderate) increased dramatically.
Most issues stem from lodash - perhaps it should be upgraded to ver. >=4.17.5

2. The script won't finish. and looks like its related to: https://github.com/NodeBB/NodeBB/commit/264eadde178ac83f8e90ac5d552dd0a7afe55f35

See below error log:
```
3. Checking installed plugins for updates...  [4567/17294] - error: uncaughtException: body.map is not a function
TypeError: body.map is not a function
    at Request._callback (nodebb/src/cli/upgrade-plugins.js:146:27)
    at Request.self.callback (nodebb/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (nodebb/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (nodebb/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at nodebb/node_modules/async-listener/glue.js:188:31

```

**Comment by pitaj** [comment]
I doubt it's related to that commit, but maybe async changed something. Looking at the code specified by the error, looks like the code might be bugged.

You can run upgrade without the plugin check by doing `./nodebb upgrade -misb`

**Comment by barisusakli** [comment]
That error would happen if nbbpm is down or returns an invalid body I think

**Comment by robin4002** [comment]
Indeed, it's because https://packages.nodebb.org is down.

**Comment by barisusakli** [comment]
Should be back up

**Comment by PostMidnight** [comment]
Thank you! I can confirm the build script is working.
I was not aware of https://packages.nodebb.org, its does have interesting statistics. 
Please consider sharing the link on the community forum, I bet people will love it.

Will it be possible to update lodash?
