### ISSUE TITLE
Language change caused label messed up

### ISSUE THREAD

**Issue by jinfagang** [NodeBB/NodeBB#7370]
After I did a language change, the monitor and the label all messed up:

![image](https://user-images.githubusercontent.com/21303438/52767570-ded76900-3065-11e9-99fd-db06a2666fed.png)

Is there any way to fix this?

**Comment by jinfagang** [comment]
I mean, the languages inside the menu are gone, can not even change back too

**Comment by pitaj** [comment]
Try running `./nodebb build`
