### ISSUE TITLE
How to custom panel icon?

### ISSUE THREAD

**Issue by jinfagang** [NodeBB/NodeBB#7372]
![image](https://user-images.githubusercontent.com/21303438/52853007-2c7ecf00-3155-11e9-9d13-b6fdbc2524f1.png)

Thanks for this framework, it great, as show above, the icon new create are same icon, how to customize it?

And what to change if I wannt make some corner radius to panel??

**Comment by jinfagang** [comment]
BTW, what to do if I want delete or hide the icon in this theme?

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
