### ISSUE TITLE
advanced search link disappeared

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7377]
![image](https://user-images.githubusercontent.com/2583394/52894801-12a5b200-317e-11e9-9041-4c3a6af8698f.png)

**Comment by pitaj** [comment]
I can see it on community.nodebb.org
![advanced-search](https://user-images.githubusercontent.com/803701/52895339-f69e1280-3175-11e9-9f9e-cfe72fc6e541.png)

**Comment by barisusakli** [comment]
Hmm maybe chrome only, I can see it on edge

**Comment by pitaj** [comment]
Clear cache etc etc

**Comment by barisusakli** [comment]
Yeah cache disabled, chrome ver 72.0.3626.109, works in firefox as well so chrome 🐛
