### ISSUE TITLE
Add "Last-Modified" HTTP Header for /topic responses with date of last post incl. support for If-Modified-Since

### ISSUE THREAD

**Issue by Apollon77** [NodeBB/NodeBB#7380]
To allow better caching it would be extremely helpful to have the HTTP header Last-Modified in the responses for topics. Additionally also support If-Modified-Since in requests (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since).

With this existing the nginx caching could be used additionally to lower the amounts of unneeded requests (see http://nginx.org/en/docs/http/ngx_http_proxy_module.html?&_ga=2.52536360.166737005.1550357371-1263625467.1550357371#proxy_cache_revalidate)
Yes the nodebb statistics may be worthless then but it could help - also if it is maybe only to handle crawlers.

Thank you for your feedback and consideration.

**Comment by julianlam** [comment]
Hm... I don't think we even support eTags, but adding in Last-Modified and supporting `If-Modified-Since` would be a good feature to have. The nginx caching benefits are nice, but definitely would make analytics wonky. However, supporting `If-Modified-Since` can be handled quite easily in that we can send back the `304` if nothing has changed.

Currently, all ajaxify requests send in the current timestamp to force fresh content.

**Comment by julianlam** [comment]
Hang on, who _sends_ the `If-Modified-Since` header? If we have to also track page states and cache returned JSON, etc... then this gets more complicated.

If the browser handles it, then... that's easier.

**Comment by julianlam** [comment]
Scenarios in which `Last-Modified` would change:
* New reply (topic replies zset)
* Post edited (check edit history of all pids? ouch)
* Vote changes in a post (votes zset for all pids, double ouch)
* Username, user profile picture, change (username history zset for all participating users?!)
* Category metadata changes (we don't track this)
* User login state changed (can't even guard against this, an admin logging out and then accessing a cached topic would load the cached content with moderator buttons and such!!)
* Privilege set changes (we don't track these)
* Any config file changes...

There's a lot that goes on when you request a topic. Many many things invalidate the data set, and not just new posts, sadly.

**Comment by julianlam** [comment]
With regards to nginx proxy caching, the benefits are huge, but if you're working with privileged pages (hidden categories, etc.), then there could be potential unintentional informational leakage here.

**Comment by julianlam** [comment]
I should also mention I was the one who, perhaps 3 years ago, introduced an "ajaxify cache" into NodeBB for similar reasons. It took less than 24 hours before enough bugs were filed that we shelved the idea completely :laughing:

**Comment by Apollon77** [comment]
I suspected that :-( I could only other ideas like "make it available on when Redis is there because here you could simply update a "In mem" field per post or even thread on changes and use this as "last changed info" (so you would notneed to "gather" the infos on request but directly access it" to it ... that would maybe make it easier to implement, but at the cost of flexibility and "for which users the feature is usable".
Also for me personally it is kind of ok not to use this for "logged in users".

The basic "problem" we are facing are spiders like Google. Yes we already limited them and also delayed them but in fact they are making more requests then our "real" users (unimportant if logged in or not)  :-) But to limit it to bots would even more limit the feature :-(

I can understand when it is too complex to achieve

**Comment by julianlam** [comment]
If that is your main concern then if you are able, you can write a plugin to look at `req.isSpider` and send a 503 if they are accessing the site too frequently

**Comment by Apollon77** [comment]
I's not the main concern it was just the kicker to think about caching in general
