### ISSUE TITLE
[Enchancement] Markdown article page

### ISSUE THREAD

**Issue by jinfagang** [NodeBB/NodeBB#7384]
Just for some feature suggest, nodebb is very nice. I know it can writting blog but it's same typography as topic post. What I want to request is:

*a new article page which shows articles in markdown*, it has full page typography and some article info, below that is the comment. Is there feature already being developed? I really want some feature like this.
(so that users can read articles in a immersion mode)

**Comment by pitaj** [comment]
Please go into more detail? It's hard for me to know what you're talking about. How would this differ from a normal topic page?

I'm fairly certain such a feature could be implemented by a theme as simply CSS/LESS changes.

**Comment by jinfagang** [comment]
@pitaj Thanks for your reply. sorry for my bad English, Here is an example. we are actually using topic to write articles:
[here](http://talk.strangeai.pro/topic/19/linux%E7%B3%BB%E7%BB%9F%E8%BF%90%E7%BB%B4%E5%B7%A5%E5%85%B7glances/5) is topic 

[here](https://jinfagang.github.io/2018/10/07/%E7%BB%88%E4%BA%8E%EF%BC%81%EF%BC%81%EF%BC%81%E8%AE%B0%E5%BD%95%E5%A6%82%E4%BD%95%E5%9C%A8hexo-next%E4%B8%BB%E9%A2%98%E4%B8%8B%E9%85%8D%E7%BD%AEgitalk%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F/) is article 

I think last one more easy to read. If there an css can achieve this, could it be an plugin for users to decorate some pages like the article style

**Comment by pitaj** [comment]
Yep you can do it just fine with just style changes. Every category in NodeBB has a number, which we call a cid. The cid is the number after `category` in the URL. Various body classes are added for styling. Any topic under category 1 will have the class `page-topic-category-1` on the body element, so you can style the topics like this:

```less
.page-topic-category-1 {
  .topic .posts [component="post"][data-index="0"] {
    // style the main post how you want
  }

  .topic .posts [component="post"]:not([data-index="0"]) {
    // style the other posts
  }
}
```

Those are just examples, there would be a lot of style changes to achieve what you want.
