### ISSUE TITLE
Feature Request: Scale cover image so it will always "fit" the available space

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7388]
Currently the cover image scaling is set to "background-size: cover" keeping the aspect ratio - leading to image cropping.
In might be worthwhile to set the scaling to "background-size: contain;" or fit: "background-size: 100% 100%;"

**Comment by julianlam** [comment]
Maintaining aspect ratio is most important, as you can move the image with the built in tooling. If you want to override the setting for your forum, I advise you to use custom CSS in ACP.

**Comment by PostMidnight** [comment]
OK got it thank you @julianlam .

The reason I brought this up is as follows: if someone "centers" the cover image in mobile resolution, that position will not be "perfect" for desktop/tablet resolutions and vice versa.

Perhaps the coordinates of the image needs to be saved per resolution?

**Comment by julianlam** [comment]
You can't do that. There are thousands of viewport ratios in use.

**Comment by PostMidnight** [comment]
I see now. Its not simple ;) kindly excuse my ignorance.

A possible solution is to fit the image entirely while maintaining the aspect ratio, and overlay it on a black background.

.account .cover {
   background-size: contain;
   background-color: black;
}
