### ISSUE TITLE
Show users available skins? (Enhancement)

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7393]
When the user picks their skin, they don't know what any of the skins look like, and are only given a list of names.
You can see it in "/admin/appearance/skins", so can there be a separate area to edit your skin as well?

**Comment by julianlam** [comment]
The skins page in the ACP sets the default skin forum-wide. The user settings only changes it for your account. When you change it in the user settings page, the skin is loaded immediately for you to see.
