### ISSUE TITLE
Registration Queue in dashboard doesn't work

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#7400]
- **NodeBB version:** 1.11.2
- **Database type:** mongo

Hi, in dashboard when I click on ```Registration Queue``` nothing happens (link doesn't work)

![20190220_011453](https://user-images.githubusercontent.com/31972226/53268908-a5a19780-36fc-11e9-8f5c-30e3f16e4426.png)

**Comment by julianlam** [comment]
Hello there, I am able to access the page with no issues on mobile.
