### ISSUE TITLE
probelm with assigning a flagged content 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#7402]
- **NodeBB version:** 1.11.2
- **Database type:** mongo

Hi, when I want to assign a flagged content to a mod/admin, the list of mods/admins is full of users named ```Guest```. It is notable that I see admins and mods in the list too.
![2019-02-22_235648](https://user-images.githubusercontent.com/31972226/53270038-c3bcc700-36ff-11e9-8b16-80f9b1fb9778.jpg)

**Comment by mohammadhassan99** [comment]
@julianlam Now I found that my username is not in the list. Is it bug or it is not supposed to show?

**Comment by julianlam** [comment]
Fixed in 0360f6e1cb39c1704dbec66e91351161d7787bde
