### ISSUE TITLE
 RSS Feeds from single Discussion stops at 26 posts

### ISSUE THREAD

**Issue by liv-in-sky** [NodeBB/NodeBB#7407]
I have tried this on two different forums  - the nodebb and iobroker forum. - and a lot of different rss readers. in addition if you use the rss buttons in the forum (with a browser) the same behavior will appear. 

feeds like recent.rss are working well - a new post - a new rssfeed-entry is coming. 

- if you choose a rssfeed from a single discussion  (e.g. https://community.nodebb.org/topic/7227/show-us-your-rig)  the rss feeds **stop at the 26th** post. with more then 26 post per discussion the rss feeds is stop working (updating).

+ **between 1 and 26 post:** everthing is like expected - new post - new rssfeed-entry.

could you please help to change this behavior. I think rss is underrated because off **effectiveness** in day to day work. if you are using **more then one forum** and you would like to get all interessting informations at one place - **rss helps a lot** instead getting thousends of emails or surfing through different web forums to be "up to date".

**Comment by barisusakli** [comment]
This happens because the feed is hard coded to display first 26 posts [here](https://github.com/NodeBB/NodeBB/blob/master/src/routes/feeds.js#L108). 

Either need pagination for rss feeds or need to display last X posts.

**Comment by liv-in-sky** [comment]
@[barisusakli](/barisusakli)

thanx very much  - that means there is a solution for this problem - my problem: I'm not an expert to do this. could you please show me the changes to get the last x post e.g. 10 ? I hope this is not creating too much changes or effort for you.

in addition: do you know if this change would have any negative server behavior - e.g. performance,...

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/blob/master/src/routes/feeds.js#L108 changing the `false` to `true` on that line should retrieve last 26 posts without any perfrmance issues. But them you wouldn't see the older posts if there are more than 26.

**Comment by liv-in-sky** [comment]
thank you so much

I think it's ok for me to get the last x posts - for using rss in a forum ithe only (in my opinion) important issue is to get the newest x posts - the beginning of the discussion is already read because it is interessting for me - I only want to get an update about new post.

**Comment by liv-in-sky** [comment]
@barisusakli 

our admin have changed the setting - if you are interessted in - look at the iobroker forum 
 https://forum.iobroker.net/recent

problem solved - thanx again
