### ISSUE TITLE
Improve emails 

### ISSUE THREAD

**Issue by EnriqueAnakena** [NodeBB/NodeBB#7418]
IMprove the Emails allowing users to add custom subjects from ACP for each template.

**Comment by PostMidnight** [comment]
Hi @EnriqueAnakena 
You might be able to modify the subject through translations (unless the subject is hard-coded).
Look into emails.json in languages/en-US.
Copy the file to your plugin and modify as needed.
JJ.

**Comment by julianlam** [comment]
Good point, it is probably not a good idea for us to hardcode subject lines, so if there are any you want to customize, you can edit the translation files.

If there are any that are hard-coded English please point them out to us for bug fixing

**Comment by pitaj** [comment]
Or use nodebb-plugin-customize to customize translations, if you don't have a custom plugin or theme already.

**Comment by julianlam** [comment]
Thanks @pitaj that is a perfect use case for that plugin :smile:

**Comment by julianlam** [comment]
I am going to close this for now as we've come to a natural conclusion to this discussion. If there are issues with hardcoded english subjects, please open a new issue for them. Thank you.
