### ISSUE TITLE
Re-opened: Mobile menu won't open on Android Chrome

### ISSUE THREAD

**Issue by jepster** [NodeBB/NodeBB#7426]
I am re-opening the issue from https://github.com/NodeBB/NodeBB/issues/6355. 

I am still experiencing the same issue again. Thought it's fixed since 1.8.0. See issue at https://github.com/NodeBB/NodeBB/issues/6355. 

- **NodeBB version:** 1.11.2 
- **NodeBB git hash:** 

- **Database type:** mongo
- **Database version:** 
I am on a hosted system. Do not know the MongoDB verison.
- **Exact steps to cause this issue:**
Open the forum https://forum.salsainsider.de on a mobile
Click on the top left mobile menu
- **What you expected:**
The menu to open.
- **What happened instead:**
The menu button gets animated with the spinner loading icon.

It works when I resize the Chrome browser window from desktop size to mobile size. However, if I resize the browser window to mobile size and then "reload" the page, the burger menu cannot be opened.

How can I fix that?

![burger-menu](https://user-images.githubusercontent.com/628434/53700260-af0fbb80-3df0-11e9-8831-eb712fd69415.PNG)

**Comment by pitaj** [comment]
If you're serviced by the NodeBB first party hosting, please contact them directly through email. If you can not access your server there isn't much you can do to fix it, even if we knew what was wrong.

**Comment by oneplusdash** [comment]
I have this problem too.

**Comment by jepster** [comment]
I have un-installed the plugin from https://github.com/pitaj/nodebb-plugin-header-extend plugin and now the menu is appearing again.
