### ISSUE TITLE
Upload icons are confusing

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7427]
Right now there are 2 upload icons and this is confusing.

![image](https://user-images.githubusercontent.com/527865/53701346-ea8a9580-3db0-11e9-8711-5428a8180bbc.png)

The question is, which one is for images and which one is for files?

1. Why does it have to be different?
2. Assuming a good reason for 1, the current image logo is confusing. I realize #4453 changed it but the new one is more confusing. Not sure the best way to differentiate.

**Comment by julianlam** [comment]
Open to [swapping the icons](https://fontawesome.com/cheatsheet) to one that fit better for the action intended. 

There seems to be a `file-upload` icon we can use now, and `file-image` could work for images.

**Comment by djensen47** [comment]
Yeah, that looks good!

**Comment by julianlam** [comment]
Sweetness.

**Comment by julianlam** [comment]
Okay, so I couldn't actually use those icons, as we don't use FontAwesome 5, but I did approximate them with the FA4 icons and a little hacking:

![image](https://user-images.githubusercontent.com/923011/57949601-e00d7180-78b2-11e9-9ca2-ba5dff333b87.png)

**Comment by julianlam** [comment]
v6.2.13
