### ISSUE TITLE
login url error

### ISSUE THREAD

**Issue by oneplusdash** [NodeBB/NodeBB#7428]
- **NodeBB version:** 1.11.2
- **NodeBB git hash:**  2b6f1a0

- **Database type:**  redis
- **Database version:** 3.2.12

- **Exact steps to cause this issue:**

1.login page using admin account login
- **What you expected:**
****/user/admin

- **What happened instead:**
****/****/user/admin

url has some repeat

**Comment by oneplusdash** [comment]
What happened instead:
/***/***/user/admin

**Comment by pitaj** [comment]
Please make sure the `url` value in config.json matches exactly the url at which you access the site.

**Comment by julianlam** [comment]
Looks to be a configuration issue, please provide additional reproduction steps.

**Comment by oneplusdash** [comment]
> 
> 
> Please make sure the `url` value in config.json matches exactly the url at which you access the site.
https://www.akosm.xyz/login
username:admin
password;123456654321

**Comment by ufan0** [comment]
It will happen from time to time，I also encountered this problem.
