### ISSUE TITLE
Weird HTML insertion on new post

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#7432]
**NodeBB version:** 1.11.1, but should also be the case on master
**Theme:** Persona
Not sure if this is an issue with persona or core, but I'm posting this here anyways for the visibility.
I forgot to make a screenshot of this very rare occurrence but here's my theory of what I think is going on:
There is this setting for the persona theme, that allows people to hide the "Last post on category view"
![Screenshot Settings](https://user-images.githubusercontent.com/8350879/53979725-d4f9d080-410e-11e9-9dbc-c83b84bfcf3b.png)
Which, as the name implies hides this little box next to the categories:
![Screenshot Teaser](https://user-images.githubusercontent.com/8350879/53979857-1f7b4d00-410f-11e9-839b-f2830042b801.png)
There's also [this code](https://github.com/NodeBB/NodeBB/blob/master/public/src/client/categories.js) that refreshes this teaser preview whenever there's a new post.
It looks like this refresh is still happening even if there is no teaser in the first place.
So the code tries to replace a non-existing teaser. This wouldn't be a problem, however it seems that the used CSS selector still finds a valid tag, and just places the teaser inside this wrong tag, which then appears formatted badly in the middle of the category page, next to the category of the post.

I'm sorry that I can't provide a screenshot right now, but at least I'm pretty confident that my explanation is fairly accurate.

**Comment by barisusakli** [comment]
@RoiEXLab you can fix this by setting number of recent replies to 0 in the ACP for all categories. Or wait for the next release.

**Comment by RoiEXLab** [comment]
Thanks 👍
