### ISSUE TITLE
Allow weekly email digest to be resumed

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7441]
Over the past 16 weeks I've been running NodeBB and the weekly digest has failed 14 times. It's super tough to debug because I can't resume where I left off. 

It would be awesome if I could manually kick off the weekly digest and have it only attempt sending it to the folks who have not yet been attempted for that week.

**Comment by julianlam** [comment]
Hm, when you say it has failed, can you let us know what the error was?

**Comment by djensen47** [comment]
I wish I could (and I would) but my logs are currently rotating every 8-10 hours so the error message is gone. I have to time it just right for next week to get the error.

Log rotation is another issue that probably should get filed. 😕

**Comment by PostMidnight** [comment]
Hi @djensen47 I had a similar issue with (free) google mail and with Zoho. 

There is a way to throttle the data going into the mail server and slow it down significantly, see here: https://github.com/NodeBB/NodeBB/issues/6911.

However if throttling is implemented across the board. That is, without the option to turn it off via the ACP, I can imagine we'll be hunted down by frustrated Admins who manage large forums. 

Thus, for the good of mankind, I ended up switching to a paid mail provider and problems gone, or at least, bypassed ;).

**Comment by djensen47** [comment]
I'm using Sparkpost, which is paid but I'm on a legacy free plan so I get 100k/month. I'll just have to wait until next week for the error messages.

**Comment by djensen47** [comment]
No error this week because it was successful. I manually made the changes suggested by @PostMidnight in #6911 so I highly recommend that those become options in the admin console or maybe just the defaults.

**Comment by julianlam** [comment]
The way the digest works is we kickstart the process and return immediately, because the sending of digests is a batched process that works in the background. Therefore it's fairly difficult to save some sort of "progress" in order for it to resume.

If there are issues with how the digests are sent (and it causes NodeBB to crash or whatnot), then the underlying issue needs to be resolved instead.

**Comment by djensen47** [comment]
Here's and idea:

1. Send the digest email
2. Record in the database the day that is was sent for that user
3. Increment a counter in the db for the total emails sent for that digest

If there is a crash, and the admin manually hits the "continue sending button"

1. Query the db for users to send the email to but exclude records that already received _that_ digest
2. Continue as normal

**Comment by djensen47** [comment]
Here's a good reason to allow for resuming. Server crashes because it goes out of memory and it doesn't send the digest:

```
2019-03-31T14:03:38.593Z [4568/5850] - info: [user/jobs] Digest (day) scheduling completed. 5 email(s) sent.

<--- Last few GCs --->

[5845:0x36c0700] 498978057 ms: Scavenge 546.2 (588.5) -> 536.6 (592.5) MB, 113.3 / 1.7 ms  allocation failure
[5845:0x36c0700] 498978480 ms: Scavenge 550.3 (593.0) -> 539.5 (596.0) MB, 125.5 / 4.4 ms  allocation failure
[5845:0x36c0700] 498979018 ms: Scavenge 556.0 (598.5) -> 545.5 (600.5) MB, 126.0 / 3.2 ms  allocation failure
[5845:0x36c0700] 498984997 ms: Scavenge 559.5 (601.5) -> 548.5 (605.5) MB, 159.1 / 6.5 ms  allocation failure


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
 1: node::Abort() [/usr/bin/node]
 2: 0x8cce9c [/usr/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
 5: 0xa6544b [/usr/bin/node]
 6: v8::internal::MarkCompactCollector::Evacuate() [/usr/bin/node]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [/usr/bin/node]
 8: v8::internal::Heap::MarkCompact() [/usr/bin/node]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
10: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
11: v8::internal::Factory::NewMap(v8::internal::InstanceType, int, v8::internal::ElementsKind) [/usr/bin/node]
12: v8::internal::Map::RawCopy(v8::internal::Handle<v8::internal::Map>, int) [/usr/bin/node]
13: v8::internal::Map::CopyDropDescriptors(v8::internal::Handle<v8::internal::Map>) [/usr/bin/node]
14: v8::internal::Map::ShareDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Descriptor*) [/usr/bin/node]
15: v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [/usr/bin/node]
16: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [/usr/bin/node
17: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Object::StoreFromKeyed, bool*) [/usr/bin/node]
18: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/usr/bin/node]
19: v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/bin/node]
20: v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed, v8::internal::MaybeHandle<v8::internal::Object>) [/usr/bin/node]
21: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/bin/node]
22: v8::internal::KeyedStoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/bin/node]
23: v8::internal::Runtime_KeyedStoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
24: 0x137549f842fd
[cluster] Child Process (5850) has exited (code: null, signal: SIGKILL)
[cluster] Spinning up another process...
```

I just don't think it's as difficult a problem to solve. Personally, I think the digest email is a core feature of NodeBB and it works about 50% of the time. Thanks anyway.

**Comment by pitaj** [comment]
Hope about this:

- one sorted set per digest
- when digest runs, populate sorted set with uids that receive it
- change score from 0 to 1 when email is sent
- if digest is interrupted, resume by getting all the uids with a score of 0 in that set

In the future we could just generate the sets once and change them when users register, are banned, change their settings, or are deleted.

**Comment by djensen47** [comment]
@pitaj That sounds like a great plan. Would all the sorted sets need to be kept in the DB indefinitely, or could it be that the previous one is removed when the next one runs?

**Comment by pitaj** [comment]
Yeah total there would only be a single sorted set for each type: weekly, daily, whatever. Not one for each instance of the digest being emailed out.

**Comment by djensen47** [comment]
> Yeah total there would only be a single sorted set for each type: weekly, daily, whatever. Not one for each instance of the digest being emailed out.

I like it! #winning

**Comment by djensen47** [comment]
So I had another issue with this again this week and it happens about once a month. An error occurs during sending or independently of sending the weekly digest; the server crashes; and the digest is halted.

```
2019-06-16T19:05:17.681Z [4567/19270] - error: Can't send mail - all recipients were rejected: 501 5.5.2 RCPT TO syntax error {"code":"EENVELOPE","response":"501 5.5.2 RCPT TO syntax error","responseCode":501,"command":"RCPT TO","rejected":["redacted"],"rejectedErrors":[{"code":"EENVELOPE","response":"501 5.5.2 RCPT TO syntax error","responseCode":501,"command":"RCPT TO","recipient":"dedacted"}]}                                                                                                          

2019-06-16T19:06:23.493Z [4567/29660] - info: Initializing NodeBB v1.12.1 https://www.axisandallies.org/forums                                                                 
```

It's a fairly common error but it's not terribly useful and odd that the server restarts after that error.

Should I open new Github issues to address these problems?
