### ISSUE TITLE
Improved social media image preview for posts

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7444]
Lately I've been struggling setting the preferred photo for a forum post on social media. Twitter doesn't really give a choice at all. 

It seems the default `og:image` is the avatar of the poster, icon of the site, or the post thumbnail. The problem with the post thumbnail is that it is too small for social media and shouldn't be used, it looks pixelated and crappy.

This is how I would like to see `og:image` set:
1. First image of the first post of the topic. Both on initial save and on edit
2. Use the original size of the uploaded post thumbnail before cropping
3. User's avatar
4. Site favicon

**Comment by djensen47** [comment]
Part of the problem I'm having is Facebook. It insists on using og:image as at least one of the "photos" in the post. So I even though I _can_ select an image in the topic, I _must_ also use the favicon or avatar, which looks like crap when posting to Facebook.

**Comment by djensen47** [comment]
🤕 Just posted something and Facebook picked up the nice large image instead of the avatar in og:image. This is frustrating.

**Comment by julianlam** [comment]
Can you clarify what you mean by "Use the original size of the uploaded post thumbnail before cropping", is this in reference to the uploaded picture in OP from point 1?

**Comment by julianlam** [comment]
After discovering some odd behaviour and tracing it back to #4560, it seems the order can be revised down to:

1. First uploaded image in that post (or if no pid defined, first uploaded image in OP)
1. Topic thumbnail (if defined)
1. Poster avatar (or if no pid defined, OP's avatar)
1. Site-wide `og:image` as added in #4560
1. Site Logo

**Comment by julianlam** [comment]
The current logic is:

1. Topic thumbnail OR Category background image OR Post author's avatar OR global `og:image` OR site logo
1. All images uploaded, starting from top down

So we'll rewrite this completely to use post/uploads lib I think.

**Comment by julianlam** [comment]
See #7463

**Comment by djensen47** [comment]
Regarding the topic thumbnail, was it ever resized at some point? Maybe in 1.11.x? 

I realize that Facebook has been wildly inconsistent on this whole thing but I _know_ I uploaded a large thumbnail and Facebook picked up a small square, pixelated image as if it was up-scaling a 46x46 image.

Now, on 1.12.x, I can't seem to find any small resized thumbnails on my forums. It may be a none issue.

**Comment by julianlam** [comment]
Hopefully! I don't think we proactively resize any images, but I honestly don't know for sure. Would hesitate to blame Facebook as first-course of action, though...

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/blob/master/src/controllers/uploads.js#L155 thumbs are resized here
