### ISSUE TITLE
[Urgent] Quick search does not account for sites installed in subfolder

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7446]
Nodebb version: 1.12.0

1. Install NodeBB in a subdir
2. Search in the search box
3. Wait for the quick search
4. Click a link

Expected result:

Goes to topic page

Actual result:

Goes to a 404

**Comment by djensen47** [comment]
Can I turn off quick search?

**Comment by djensen47** [comment]
Will this be tied to 1.12.1 or can I updated in advance of the next patch release?

**Comment by julianlam** [comment]
There are no breaking changes so installing this theme should be fine for
you 😀
