### ISSUE TITLE
Really really long groups break things.

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7447]
- **NodeBB version:** 1.12.0
- **NodeBB git hash:** 9c4b2d9cd20a11c08a2dbaad7cbe82a489ced563
- **Database type:** mongo
- **Database version:** 4.0.6

- **Exact steps to cause this issue:**
1. Have really, really, really long group names.
2. Make a post.

- **What you expected:**
I expected my posts to be normal, and for the text to fit in the boxes.

- **What happened instead:**
The group name didn't fit in the box, and all my posts are invisible.

What the post looks like normally...
![Screenshot (103)](https://user-images.githubusercontent.com/35382971/54248582-9a7ba380-4513-11e9-80e2-f6aba53fea80.png)
After adding a ton of long group names.
![Screenshot (106)](https://user-images.githubusercontent.com/35382971/54248602-b3845480-4513-11e9-8d06-80d4b5388355.png)

And more screenshots of things not fitting where they should fit in anyways
![Screenshot (102)](https://user-images.githubusercontent.com/35382971/54248644-d878c780-4513-11e9-9e43-b4d612a25eb0.png)
![Screenshot (104)](https://user-images.githubusercontent.com/35382971/54248645-d878c780-4513-11e9-9d0b-abb5e1b3d16e.png)
![Screenshot (105)](https://user-images.githubusercontent.com/35382971/54248646-d878c780-4513-11e9-8a93-f9b7e8e99ae9.png)

Kinda related to #7065

**Comment by PatheticMustan** [comment]
Maybe instead of "Superlongnamethatshouldntbepossiblebutisindeedinfactio", it can be shortened, like "Superlongnamethatsho..."
Also, long usernames break things as well.

**Comment by pitaj** [comment]
Maybe we should add a limit to the length of group names and user names.

**Comment by PatheticMustan** [comment]
Isn't there already a limit?
(If the limit is high enough, usernames can break things too)

**Comment by julianlam** [comment]
Group names can be long, I have no objection to that.. however, I'd argue that badges should have a cap on name length. This is up to the theme to implement and I'll add it in for Persona and Vanilla.
