### ISSUE TITLE
upgrade docs need updating

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7453]
https://docs.nodebb.org/configuring/upgrade/

**Comment by RosieCode95** [comment]
yeh dont follow this unless you wanna nuke ur install

**Comment by julianlam** [comment]
What needs to be changed?

**Comment by barisusakli** [comment]
I think it is no longer necessary to go step by step when upgrading can just go to latest and run ./nodebb upgrade.

**Comment by julianlam** [comment]
> go to latest and run ./nodebb upgrade.

Yes, that's steps 3 and 4... steps 1 and 2 instruct the user to shut down NodeBB and back up the forum, which is still recommended, no?

**Comment by barisusakli** [comment]
I meant this part 

Upgrade Path
NodeBB's upgrade path is designed so that upgrading between versions is straightforward. NodeBB will provide upgrade compatibility (via the --upgrade flag) between the latest version of a lower branch and the latest version of the higher branch. For example, if v0.2.2 is the latest version in the v0.2.x branch, you can switch to the v0.3.x branch and suffer no ill effects. Upgrading from v0.2.0 to v0.3.x is not supported, and NodeBB will warn you when attempting to upgrade that you are not upgrading cleanly.

Upgrading between patch revisions
e.g. v0.1.0 to v0.1.1

Patch revisions contain bugfixes and other minor changes. Updating to the latest version of code for your specific version branch is all that is usually required.

Execute steps 1 through 3.

Upgrading between minor revisions
e.g. v0.1.3 to v0.2.0

Minor revisions contain new features or substantial changes that are still backwards compatible. They may also contain dependent packages that require upgrading, and other features may be deprecated (but would ideally still be supported).

Execute steps 1 through 4.
