### ISSUE TITLE
Can I see any users who are watched  this topic?

### ISSUE THREAD

**Issue by pig315** [NodeBB/NodeBB#7456]
NodeBB version: : 1. 11.1
NodeBB git hash:
Database type: mongo
Database version: v4.0.1
Exact steps to cause this issue:

There is a very popular topics,  users often ask me why he has been reminded.
Can I see the users who are interested in this post?

**Comment by PatheticMustan** [comment]
You want to see who viewed a post?

**Comment by pig315** [comment]
> You want to see who viewed a post?

yes，any solution? 
thank you

**Comment by PatheticMustan** [comment]
The only way I could think of is sticking some javascript together, or getting a plugin. (Don't know if a plugin like that exists though.)

**Comment by julianlam** [comment]
As detailed on the forum, watch lists are considered private information and are not intended to be made available to the public.
