### ISSUE TITLE
Textcomplete does not trigger in iPhones

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7457]
Hi Developers,

I am writing this here since the issue relates to several editor plugins.

To reproduce: use redactor and RTL language. You may use chrome emulator as well.
Press @ anywhere in the textarea. You would expect the mention dialog to come up, but nothing happens. This issue relates to: https://github.com/julianlam/nodebb-plugin-mentions/issues/111

I spent quite a bit of time digging into the code. It looks like the issue stems from textcomplete.min.js.

The search regex and strategy are registered properly (called from autocomplete.js). However, upon a key press anywhere in the redactor TEXTEDIT window, none of the callback methods are triggered ("handleChange", "handleEnter", "handleEsc", "handleHit", "handleMove", "handleSelect")

Please let me know should you need additional information.
JJ.

**Comment by PostMidnight** [comment]
The issue is in line 560 of textcomplete.codemirror.min.js:
The event is dropped for iPhones, see below:
(the comment is not mine)

`
key: "onInput",
    value: function onInput(_) {
      if (/^((?!chrome|android).)*safari/i.test(navigator.userAgent)) {
        // Safari behaves much stranger than Chrome and Firefox.
        return;
      }
      this.emitChangeEvent();
    }
`

**Comment by PostMidnight** [comment]
Removing the return brings back the selection box.

A new issue surfaced however, typing consecutive mention statements such as:
@aaaa_aaaa @bbbbbb_bbbbb
Results with:
@bbbbb_bbbbb

The second statement overrides the first. Probably the current position pre-event is not recorded on the second run.
Besides that, it looks like a home run for iPhone users.

@julianlam will it be possible to ask Takahashi-san to take a look?

**Comment by PostMidnight** [comment]
Reported upstream: https://github.com/yuku/textcomplete/issues/160

**Comment by PostMidnight** [comment]
Unfortunately, the RTL issues did not end with the changes above:

When the user inserts mention having English letters, the output looks like: somename<SPACE>@, instead of: <SPACE>somename@.

The only way to make the mention text stick to the right was to specify the language and direction as part of the inserted text, that is, in HTML. See below changes in autofill.js (mention plugin), line 72: 

```
                                 //return '@' + utils.slugify(mention, true) + ' ';
                                if(document.getElementsByTagName("html")[0].getAttribute("data-dir") === 'rtl')
                                   return '<span class="plugin-mentions-editor" dir="rtl" lang="' + document.documentElement.lang + '">@' + utils.slugify(mention, true) + '</i></span>&nbsp;';
                                else
                                   return '<span class="plugin-mentions-editor">@' + utils.slugify(mention, true) + '</i></span>&nbsp';
```

Now, since the insertion comprises HTML code, I had to change insertText to insertHTML in textcomplete.contenteditable/dist/textcomplete.codemirror.min.js

Note I copied textcomplete.codemirror.js into textcomplete.codemirror.min.js, since I could not get Webpack to work.

Fortunately @henderea posted a pull request: https://github.com/yuku/textcomplete.contenteditable/pull/3/files#diff-41e0662b7c03018941adf3197df458c4

To that end I made the following changes:

In key: "applySearchResult",

```
        if (Array.isArray(replace)) {
          var range = this.getRange();
          range.selectNode(range.startContainer);
          //this.document.execCommand("insertText", false, replace[0] + replace[1]);
          range.deleteContents();
          this.document.execCommand("insertHTML", false, replace[0] + replace[1]);
          range.detach();
          var newRange = this.getRange();
          //newRange.setStart(newRange.startContainer, replace[0].length);
          newRange.setStart(newRange.startContainer, newRange.startContainer.length);
          newRange.collapse(true);
        }
      }
    }

``` 

In key: "getCursorOffset",

```
    value: function getCursorOffset() {
      var range = this.getRange();
      //var rangeRects = range.getBoundingClientRect();
    let rangeRects = range.getBoundingClientRect();
    if (/^((?!chrome|android).)*safari/i.test(navigator.userAgent)) {
      rangeRects = range.getClientRects()[0];
    }
```

and in key: "onInput",

```
    value: function onInput(_) {
      //if (/^((?!chrome|android).)*safari/i.test(navigator.userAgent)) {
        // Safari behaves much stranger than Chrome and Firefox.
        //return;
      //}
      this.emitChangeEvent();
    }
```

Now that HTML insertion was working, I noticed that upon mention insertion, the text may overflow the redactor window causing it to go bonkers. That was resolved with the following CSS code:

```
body > div.composer.resizable {
	overflow: hidden auto;
	position: fixed;

	.composer-container {
		overflow: hidden auto;
		position: fixed;
		word-break: break-word;

		.plugin-mentions-editor {
			color: #2fa4e7;
			font-weight: bold;
		}
	}
}

```
The .plugin-mentions-editor class is used to color the mention text upon insertion, highlighting it from the normal text, I thought this could be a nice bonus.

That's it I believe. I hope you'll consider these changes positively.
JJ.

**Comment by julianlam** [comment]
This would break compatibility with composer-default as you cannot insert HTML into a standard textarea.

**Comment by PostMidnight** [comment]
Indeed, however I could not find an alternative. Note this issue is related to Redactor. We can gate composer out of the equation. Perhaps you guys have a better way to resolve the above, I could not find one.

**Comment by julianlam** [comment]
* julianlam/nodebb-plugin-markdown#105
* julianlam/nodebb-plugin-markdown#107
