### ISSUE TITLE
Tag topics without having "edit" them [feature request]

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7465]
As a moderator or an admin, I would like to be able to add tags to topics without having to edit them in the composer.

Whenever I enhance a topic, it feels like a bit of a violation to the integrity of the topic post that I have it "edit" it. For me, changing tags is changing the metadata, like the category, and not changing the content itself. It would be great if I could add and remove tags from topics.

Furthermore, I could see this feature expanding to allow non-moderator privileged users change tags or even just allow every registered member change tags.

Thanks!

**Comment by julianlam** [comment]
That's an interesting idea -- currently tags are as you describe them, _metadata_, so they're not actually associated with the topic data itself (you can look at the `topic:*` hashes, there's no tag data).

The fact that they're editable in the composer is mostly for convenience. I think a re-examination would be a good idea.

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/235387253-47fd59e5-71ce-49a8-8b81-c74ac64ba2a0.png)
