### ISSUE TITLE
Logo not appearing on emails

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7469]
- **NodeBB version:** 1.12.0

It _was_ working but now I'm not seeing the logo in emails:

![image](https://user-images.githubusercontent.com/527865/54584230-078baf00-49d4-11e9-9f76-777635dee173.png)

In general, after trying to muck with the templates, and resetting them back, I'm seeing all sorts of weirdness.

**Comment by djensen47** [comment]
This is what I used to see:

![image](https://user-images.githubusercontent.com/527865/54584337-491c5a00-49d4-11e9-8ef2-7cb77be96dba.png)

**Comment by djensen47** [comment]
Now it's bask to working again. I'm not sure what's going on. 😵

**Comment by julianlam** [comment]
Yeah... it's quite an odd bug! Some days the logo on _our_ digest disappears too!

**Comment by djensen47** [comment]
Okay, phew, it's not "just me."

**Comment by PostMidnight** [comment]
Had the same issue as well - I thought it was my self-inflicted issue as your code seems perfect. 
Ended up posting the logo on S3 and replacing the email template with a hard link. I hope this may help you @djensen47

**Comment by julianlam** [comment]
Seems the act of saving custom emails (or possibly any setting in the ACP) resets the logo to blank.
