### ISSUE TITLE
Email testing: digest sends old email

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#7470]
- **NodeBB version:** 1.12.0

1. Make a change to the digest template
    - Add "This is a test" somewehere
2. Save
3. Send
4. The change is as expected. The received email contains "This is a test"
5. Revert the digest email
6. Save
7. Send

**Expected result**

The received email is the original reverted digest without "This is a test"

**Actual result**

The received digest email still has "This is a test" therefore was not reverted.

---

If I add an extra line to the "reverted" template and save, then the digest appears as the reverted version.

**Comment by djensen47** [comment]
Those words "We hope you're enjoying ..." are _no longer in the digest email template_.

**Comment by djensen47** [comment]
It's not just the digest emails. A few days ago, old-style notification emails were getting through.

**Comment by julianlam** [comment]
I'm confused as to what the issue is... That you're not seeing the new design?

That would be because you've customised the old design, and so that persists. You'll want to revert back to default to see the new design.

If the issue is that you've changed the template and it is not shown, you may need to rebuild templates before they are seen.

**Comment by djensen47** [comment]
The issue is actually twofold:

On Sunday the new template was used even though I had modifications and did a rebuild.

Now the issue is that the old modified template is being used despite having reverted to the new one.

It's basically the opposite behavior in both instances of what I'm expecting.

Could they're be some weirdness around sending the test email.

**Comment by pitaj** [comment]
Do you have any custom email templates?

**Comment by julianlam** [comment]
> Could they're be some weirdness around sending the test email.

I don't think so... for most of the email templates, we send some generic data (so a lot of the variable fields end up blank), **but** test-sending a digest sends a real digest to the admin who is clicking the test button. It uses the same method calls a real digest uses.

Is your forum hosted on multiple servers?

**Comment by djensen47** [comment]
> Do you have any custom email templates?

I _did_ but I reverted it.

> Is your forum hosted on multiple servers?

No, the 2 Nodebb processes are running on one server.

**Comment by djensen47** [comment]
The digest was successful again today (yay) but it used the old template. So to be clear, **I reverted the digest template** last week. The text that was sent out today, is not on the digest template when I'm in the admin console. It's a little embarrassing too because it's an old end of year message.

If you let me know where I should dig around to find where this thing might secretly be living, I'll investigate. The DB schema isn't exactly browsable so what keys should I look for? Should I look on disk somewhere?

**Comment by julianlam** [comment]
@djensen47 Do you happen to also have email templates saved as custom in your theme? When `./nodebb build` is executed, the email templates are taken from the theme itself (or falls back to `src/views/emails`). When NodeBB starts for the first time, it checks for any custom emails saved in `config` and pre-compiles them, so the `.js` file is updated, but the `.tpl` file is not.

Hopefully this makes sense to @pitaj

**Comment by julianlam** [comment]
Yeah, I have no idea -- I can't reliably reproduce. If I change the email template in the ACP, the email that is sent out reflects the changes I made... I can't get it to show an older version of the email.

**Comment by djensen47** [comment]
Where is the config saved?

**Comment by pitaj** [comment]
Any customized email templates are saved under the config object in the database.

**Comment by djensen47** [comment]
I just found the old template under `build/public/templates/emails`

I does _not_ match what I see in the ACP.

**Comment by djensen47** [comment]
I stopped the server, performed `./nodebb build`, and now the old files under ` build/public/templates/emails` are gone and the email I'm expecting _is_ being sent.

Do I actually have to stop the server, rebuild, and start the server again just to change the email template?

IIRC, it wasn't always this way.

**Comment by djensen47** [comment]
Some background, I run nodebb as nodebb:nodebb and not root. I use `systemctl` to start and stop but not for `./nodebb build`.

1. I realized that nodebb was an unable to write to the build dir
2. Did a `chown -R nodebb:nodebb .` to make sure all the permissions were set properly.
3. Reverted all the templates, save, and verified no error messages in the log.
4. Sent out test messages and the digest was the old email
5. I made changes to the digest, save, and sent a test, still the old email
6. Then I filed this bug

Somehow there was some mismatch of what was being shown in ACP and what was on disk under `build` and saving the digest template neither updated the template nor produced an error in the log.

While experimenting with the rebuild I forgot that I had to chown, so my steps were somewhat similar. But this time it worked.
1. Stop nodebb
2. Build
3. Start nodebb
4. Set test email.
5. It worked.
6. Changed template. Save.
7. Send test email.
8. Change was not in email.
9. Oops.
10. Ran chown.
11. Changed email template slightly again.
12. Send test email
13. Changes were reflected properly in the email.

**Comment by djensen47** [comment]
Nope, got it. There is a bug. I cannot revert the digest email.

1. Make a change to the digest template
2. Save
3. Send
4. The change is as expected
5. Revert the digest email
6. Save
7. Send

**Expected result**

The email is the original reverted digest

**Actual result**

The digest email still has the old changes before the revert

---

If I add an extra line to the "reverted" template and save, then the digest appears as the reverted version.

**Comment by djensen47** [comment]
So, should I close this issues an open a new one? With the new steps I can reproduce the bug every time.

**Comment by barisusakli** [comment]
@djensen47 you can just edit the main post and add the reproduction steps.

**Comment by julianlam** [comment]
Confirmed reproduction of the bug.

While I'm here, might I plug the totally free plugin [nodebb-plugin-email-helper](https://github.com/julianlam/nodebb-plugin-email-helper)? Now you don't have to send emails to yourself to test whether a change worked :smile:
