### ISSUE TITLE
Manual password expiry

### ISSUE THREAD

**Issue by teotikalki** [NodeBB/NodeBB#7471]
I would like the ability to require one/multiple users to change their password upon next login. Something like:

Manage -> Users > Edit Dropdown -> 'Expire password' (more technical) or 'Force user to change password upon next login' (more descriptive)

For various reasons I often find myself creating a user with a password like 'changemenow123' and telling the person to change the password upon first login. 

I also think that having the flag would be a nice step for implementing a password security check. I tried the pwned passwords plugin and got log errors and no visible effect, but even just writing a simply script that checks the 20 most common passwords (I thought they were a Spaceballs joke until I worked for a company that used one of them for all its hardware) against the user db and flags any account using one. Then the user whose password is '1q2w3e4r5t' can have their password expired and be forced to change it at next login.
...etc...

Note: This comes up because I have a small manual list of users and no working backend ident server. When I roll out a new service I make the user account with their given credentials. (Asking users to please use the same information each time is about as successful as asking users to be sure to change their insecure temporary passwords).

I doub't that such a feature will be commonly used, but it does have uses and my instinct says that it wouldn't be a difficult implementation (not a JS expert, though, and have barely started to wrap my head around this codebase).

The settings mentioned in https://github.com/NodeBB/NodeBB/issues/2891 do not cover this case at all.

**Comment by julianlam** [comment]
You're right, the password policy settings don't allow for manual expiration, but I agree that it could be a helpful feature to add for situations where an admin changes an account password and can flag it for immediate expiry.
