### ISSUE TITLE
You can't drag widgets in mobile ;(

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7474]
1.12, kinda self-explanatory.
Mobile is deprived and sad. ;(

**Comment by pitaj** [comment]
Drag and drop on mobile is really hard to get right, especially when scrolling is involved.

**Comment by julianlam** [comment]
There are no plans to introduce drag/drop functionality on mobile. Widget management is tricky enough as it is on desktop and will likely remain there for the foreseeable future.
