### ISSUE TITLE
Logging out does not perform many important actions

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#7476]
- **NodeBB version:** 1.12.0
- **NodeBB git hash:** 9c4b2d9cd20a11c08a2dbaad7cbe82a489ced563 [9c4b2d9cd]

After upgrading NodeBB I realized that my plugin that hooks into `static:user.loggedOut` stopped working as expected. Upon further examination I found that changes introduced in 84433f29ab0a2565e6556ee6cfbbe7e30d5057c1 broke most of the actions performed later in that `async.waterfall` chain by overwriting both `req.uid` (with `0`) and `req.sessionID` (with value of the regenerated session). To make sure I instrumented the code in `authenticationController.logout` in the following way (added `console.log`s everywhere):

```
	async.waterfall([
		function (next) {
			user.auth.revokeSession(req.sessionID, req.uid, next);
		},
		function (next) {
			console.log(`Pre: ${req.uid}`);
			req.logout();
			req.session.regenerate(function (err) {
				req.uid = 0;
				req.headers['x-csrf-token'] = req.csrfToken();
				next(err);
			});
			console.log(`Post: ${req.uid}`);
		},
		function (next) {
			console.log(`Lastonline: ${req.uid}`);
			user.setUserField(req.uid, 'lastonline', Date.now() - (meta.config.onlineCutoff * 60000), next);
		},
		function (next) {
			console.log(`Online: ${req.uid}`);
			db.sortedSetRemove('users:online', req.uid, next);
		},
		function (next) {
			console.log(`Hook: ${req.uid}`);
			plugins.fireHook('static:user.loggedOut', { req: req, res: res, uid: req.uid }, next);
		},
		...
	]);
```

and here's the output:

```
opcom-forums-nodebb | Pre: 284
opcom-forums-nodebb | Post: 284
opcom-forums-nodebb | Lastonline: 0
opcom-forums-nodebb | 2019-03-20T12:55:08.137Z [4567/193] - verbose: [plugins/fireHook] action:user.set
opcom-forums-nodebb | 2019-03-20T12:55:08.138Z [4567/193] - verbose: [plugins/fireHook] action:plugins.firehook
opcom-forums-nodebb | Online: 0
opcom-forums-nodebb | Hook: 0
opcom-forums-nodebb | 2019-03-20T12:55:08.142Z [4567/193] - verbose: [plugins/fireHook] static:user.loggedOut
```

I think it's safe to assume that this is wrong and now the following functionality is broken:
* Remembering user's last online activity time.
* Removing it from users that are online.
* Any plugin that depends on being able to read correct (i.e. pre-logout) values of uid and sessionID in `static:user.loggedOut`.
* Logging out all other tabs/windows for that user+session via WebSockets.

I have a fix ready for this, but cannot open a PR before contributor agreement gets approved by my employer ;-) In any case this is quite trivially fixed by saving the original/old values of UID and SessionID and passing them wherever needed.

Regards,
Artur

**Comment by julianlam** [comment]
Let us know if you are still blocked on opening that PR :smile:

**Comment by attis** [comment]
Forwarded the agreement to our legal team. Not sure what's the ETA, though, so if you want to just go ahead and fix this yourself I wouldn't mind ;)

**Comment by barisusakli** [comment]
@attis let me know if this fixes all your use cases.

**Comment by attis** [comment]
Almost :)  If you could only add the original sessionID to the data passed into the hook, that would solve all our needs - I need that to clean up some mappings in the DB that are keyed by sessionID.

This should be a safe change since we're adding more data without modifying the existing.

Thanks for asking, BTW :)

**Comment by barisusakli** [comment]
@attis https://github.com/NodeBB/NodeBB/commit/abe4abb67411c2d6bd3d185f3e8a3ecc37335c2d

**Comment by attis** [comment]
Perfect 👌
