### ISSUE TITLE
No emoji Autocomplete in composer

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7478]
1.12, the emoji autocomplete works in quick reply, but after opening the composer, the autocomplete breaks, meaning no more auto complete. ;(

![40E638ED-C2C1-4D56-9D0A-7372AF4F82C9](https://user-images.githubusercontent.com/35382971/54718049-0b344880-4b30-11e9-8317-b36061da5803.gif)

**Comment by pitaj** [comment]
Works for me on the community forum. What theme are you using?

**Comment by PatheticMustan** [comment]
Persona, 1.12, 9c4b2d9cd20a11c08a2dbaad7cbe82a489ced563
Would starting a forum in HTTP but switching over to HTTPS later affect something?

**Comment by pitaj** [comment]
Try stopping, build, and starting NodeBB

**Comment by PatheticMustan** [comment]
Maybe there's just something strange with my NodeBB...
