### ISSUE TITLE
Half of the topic left, can the article be saved?

### ISSUE THREAD

**Issue by pig315** [NodeBB/NodeBB#7480]
NodeBB version: : 1.12
NodeBB git hash:
Database type: mongo
Database version: v4.0.1
Exact steps to cause this issue:

Half of the topic left, can the article be saved?

When the topic was half written, he left.
Can articles be saved?

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
