### ISSUE TITLE
can't change user status after logging in

### ISSUE THREAD

**Issue by jessty** [NodeBB/NodeBB#7485]
NodeBB version: latest
NodeBB git hash: latest
- **Exact steps to cause this issue:**
	1. First I logged in by password at the page(https://community.nodebb.org/login)
	2. Then, I clicked my avatar at upper right corner
        3. And, I clicked status button to change my status but failed
        4. Last I refreshed the page, clicked status button and changed status successfully
- **What you expected:**
      change status without refreshing the page 
- **Reason for the problem**

in source code: `public/src/app.js`

The function `handleStatusChange` binds click listeners on status buttons, and it is excuted once page loaded.
If user isn't logged and accesses pages, there aren‘t status buttons.
Then `handleStatusChange` fails to bind listeners.
And, the page wouldn't be refreshed after user log in,
So, there still is no listener on status buttons.
Maybe there are some other problems in no refreshing situation.

**Comment by psychobunny** [comment]
hey, thanks for making a _detailed report_, which helped me fixed this issue pretty quick (well hopefully) :)

**Comment by psychobunny** [comment]
updated community.nodebb.org as well, let us know if you can still reproduce  :)
