### ISSUE TITLE
Google indexes /compose pages

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#7493]
- **NodeBB version:** 1.12.0
- **NodeBB git hash:** 9c4b2d9

We recently got an alert from Google Search Console that our forums has pages "Indexed, though blocked by robots.txt". Upon closer inspection this seems to be the case for various `/compose` pages for different topics. Timeline suggests this started when we upgraded from 1.10.0 to 1.12.0

Google gives the following explanation of the problem:

> Indexed, though blocked by robots.txt: The page was indexed, despite being blocked by robots.txt (Google always respects robots.txt, but this doesn't help if someone else links to it). This is marked as a warning because we're not sure if you intended to block the page from search results. If you do want to block this page, robots.txt is not the correct mechanism to avoid being indexed. To avoid being indexed you should either use 'noindex' or prohibit anonymous access to the page using auth. You can use the robots.txt tester to determine which rule is blocking this page. Because of the robots.txt, any snippet shown for the page will probably be sub-optimal. If you do not want to block this page, update your robots.txt file to unblock your page.

[https://support.google.com/webmasters/answer/7440203#indexed_though_blocked_by_robots_txt](https://support.google.com/webmasters/answer/7440203#indexed_though_blocked_by_robots_txt)

Indeed I see that `/compose` is blocked in `robots.txt`, but there's no
```
<meta name="robots" content="noindex">
```
in the HTML source of `/compose`
Perhaps it should be added? Or access to `/compose` should be blocked altogether for bots?

**Comment by julianlam** [comment]
I was not even aware there is a `<meta name="robots">` tag, so I'll probably add that in.

That said, we did add `/compose` to the robots.txt, simply because it was being indexed but shouldn't be. It wasn't really a big deal (since it's not privileged information), so it doesn't need to be actively scrubbed from the search results.
