### ISSUE TITLE
Can't change the order of the categories.

### ISSUE THREAD

**Issue by huzhw8** [NodeBB/NodeBB#7504]
- **NodeBB version:** `v1.12.0`
- **NodeBB git hash:** `9c4b2d9cd20a11c08a2dbaad7cbe82a489ced563`

- **Database type:** mongo
- **Database version:** 

> dbversion v4.0.7
git version: 1b82c812a9c0bbf6dc79d5400de9ea99e6ffa025
allocator: tcmalloc
build environment:
    distmod: 2008plus-ssl
    distarch: x86_64
    target_arch: x86_64

- **Exact steps to cause this issue:**
	1. First I wanted to adjust the order of categories in `/admin/manage/categories`
	2. Then, I attempted to drag the icon of category and it works.
	3. But I can not save the changes because there is no relating button or setting. 
	4. So I quit the back-end directly but the changes did not works.

- **What you expected:**
 	The position of categories on the `/categories` would change as my setting.

- **What happened instead:**
	It did not work at all. Both the `/admin/manage/categories` and `/categories` were recovered after shut down the back-end.

Thanks!	And I exactly expect to know whether I could and how to change the order of the categories.

**Comment by psychobunny** [comment]
Hi @huzhw8 the category reordering saves automatically. If it didn't save then was there any error in your browser console or server logs?

**Comment by huzhw8** [comment]
> Hi @huzhw8 the category reordering saves automatically. If it didn't save then was there any error in your browser console or server logs?

Hi @psychobunny several hours ago I try to delete the original four categories and I found it works! It just can not change the four categories. But honestly I do not know why.
Any how, the error has been killed through an illogical way, and they can be reordered now.

**But now I have another question** that the id of categories can not change automatically after I delete the original 1 to 4 categories. In other words, now my first category's id is 5, it's url is `https://mysite.xx/category/5/**` and I do not know how to change the url of a category. What should I do?

Thx for your reply!

**Comment by pitaj** [comment]
A category's id can not be changed
