### ISSUE TITLE
Facebook sharing shows author avatar's picture

### ISSUE THREAD

**Issue by bharat-pareek** [NodeBB/NodeBB#7512]
Hi

So i have set og:image in NodeBB settings, and when i share the url on Facebook i get that image in thumbnail, but when a topic has author avatar, then the avatar is shown on Facebook.

This does not seem right as there is no point of showing avatar image, instead it should be possible to just show the default og:image if no image is found in topic content.

- **NodeBB version: v1.12.0
- **Database type:** mongo

- **Exact steps to cause this issue:**
	1. First uploaded default og:image in settings.
	2. Then, I shared a random topic link on Facebook.

- **What you expected:**
Facebook will show site's default og:image if no image is found in topic content.

- **What happened instead:**
Facebook shows author avatar as link thumbnail preview, which does not make any sense.

**Comment by julianlam** [comment]
This should have already been fixed in latest. Are you running latest master?

**Comment by bharat-pareek** [comment]
Hey thank you, i will check.

Right now i am on v1.12.0 branch.
