### ISSUE TITLE
Discrepancy between users:online and lastonline field of each uniqueuser

### ISSUE THREAD

**Issue by reliasn** [NodeBB/NodeBB#7517]
I'm using NodeBB 1.11.1 and I'm trying to understand why my ACP > Manage users > Inactive shows strange values. When I check for users that have been inactive for longer than 5 months, I get some results that do not fit my query, i.e., the user actually was online recently.

![](https://i.imgur.com/U5fl16b.png)
![](https://i.imgur.com/lAXPGKM.png)

I basically want to delete old users that have never posted anything and also haven't logged in for a while. From what I noticed, this page uses the ``users:online`` as [it can be seen here.](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/admin/users.js#L52)

And for some reason the values in there are very different from the ``lastonline`` field of a ``uniqueuser``. In one of the examples above, I found that:
**users:online** - ``Saturday, October 20, 2018 5:37:06.225 PM`` - 6 months ago
```json
{
    "_key" : "users:online",
    "value" : "2682",
    "score" : 1540057026225.0
}
```
**user:2682** - ``Saturday, January 12, 2019 7:41:50.873 PM`` - 3 months ago
```json
{
    "_key" : "user:2682",
    "acceptTos" : 0,
    "banned" : 0,
    "email" : "XXXXXXX",
    "fullname" : "XXXXXXX",
    "gdpr_consent" : 1,
    "joindate" : 1538092110724.0,
    "lastonline" : 1547322110873.0,
    "lastposttime" : 1538178010921.0,
    "picture" : "",
    "postcount" : 0,
    "profileviews" : 0,
    "reputation" : 1,
    "signature" : "",
    "status" : "online",
    "topiccount" : 0,
    "uid" : "2682",
    "uploadedpicture" : "",
    "username" : "XXXXXXX",
    "userslug" : "XXXXXXX",
    "website" : "",
    "passwordExpiry" : 0,
    "password" : "XXXXXXX",
    "rss_token" : "XXXXXXX",
    "email:confirmed" : 1,
    "groupTitle" : "[\"\"]",
    "aboutme" : ""
}
```
From what I was reading [here](https://github.com/NodeBB/NodeBB/issues/6164), these values have different sources, but I suppose they shouldn't be too different from each other if "everything goes well". On a normal user, the values have a couple milisseconds of discrepancy.

My questions are:
- What could be causing these huge discrepancies for some users? Websockets not working properly?
- Is it possible to "synchronize" these fields by making them equal like ``max(usersOnlineValue, lastOnlineValue)``?

**Comment by pitaj** [comment]
As I understand it, users:online respects the user's settings. If they're set to invisible it doesn't count.

**Comment by reliasn** [comment]
Are you referring to this status?
![](https://i.imgur.com/jOMTXn2.png)

Is it possible to disable "Invisible" if that's the reason why I'm getting these different values?

**Comment by julianlam** [comment]
Not at this time, and I don't think we'd want to customise this right now because being invisible is important for some users.

That said, you could always _hide_ the button via CSS... it would stop pretty much everybody from discovering the feature (though of course, one could still set it if they were determined to)

**Comment by pitaj** [comment]
Yep that's what I'm referring to. Anything is possible, but it isn't easy.

**Comment by barisusakli** [comment]
I see some places where `updateLastOnline` is called but `updateOnlineUsers` isn't called like when someone logs in. Going to fix those at least.
