### ISSUE TITLE
Tags Input is too short for its placeholder.

### ISSUE THREAD

**Issue by fralonra** [NodeBB/NodeBB#7529]
- **NodeBB version:** 1.12
- **NodeBB git hash:** 81d7fd04adb9770fabf8a47130dd6ab24274cdd1

- **Exact steps to cause this issue:** Just open the composer

- **What you expected:** The placeholder of the tags input should not be cut.

- **What happened instead:** Can't read the whole placeholder.

**Comment by barisusakli** [comment]
Works fine on https://community.nodebb.org, are you using a custom theme or skin?

**Comment by fralonra** [comment]
I'm not using a custom theme nor skin. The width of the input is different in different site.

**Comment by barisusakli** [comment]
Happens because of this line https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer/tags.js#L81.

**Comment by fralonra** [comment]
@barisusakli Bingo!
Find the issue happened when the language is set to `zh-CN`, `ja` and `ko`.
Set to `zh-TW` is fine, because the translation did a hack that they put spaces after the word.
https://github.com/NodeBB/NodeBB/blob/3a35b77d5f58d2c65e1e0bb4078b4a791c0dc5e7/public/language/zh-TW/tags.json#L4

**Comment by barisusakli** [comment]
Might make more sense to set the width of that input to 100% via CSS and remove that js code.
