### ISSUE TITLE
Add new hooks

### ISSUE THREAD

**Issue by viktarkaniushyk** [NodeBB/NodeBB#7532]
Good day. For the purpose of more flexible control, you could add the following hooks:

For this elements

id="move_thread_commit"
filter:topic.move

and then we merge topics
filter:topic.merge

Thanks.

**Comment by julianlam** [comment]
Any particular reason you wish for these to be filter hooks and not action hooks?

**Comment by viktarkaniushyk** [comment]
> Any particular reason you wish for these to be filter hooks and not action hooks?


At the stage of pressing the button, I need to check the permissions of the user to a specific category.

**Comment by barisusakli** [comment]
Do you want server side hooks for these? Can't do async operations in hook handlers client side.
