### ISSUE TITLE
Allow for adding tags to multiple topics?

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7536]
It would be nice to be able to add tags to multiple topics at a time, without manually editing every single post, and tagging all of them. ;(
#7465 - Adding tags outside of the composer would be nice.

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/235387284-3a39cf39-32af-4259-936b-5af83361bace.png)
