### ISSUE TITLE
ARIA Category Children Icon

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#7539]
Would it be possible to add a role="presentation" to the category children icon that are produced in the helpers? We are currently doing some ARIA work on our site and our theme can be changed to add the necessary roles and attributes but this code is abstracted away in core so we cant update.

https://github.com/NodeBB/NodeBB/blob/81f3fbdcfcdcd4ab6f1946bf1e8b1a2ae1640ef7/public/src/modules/helpers.js#L124

**Comment by julianlam** [comment]
Sure, we'll do it if you also open a PR adding some general ARIA stuff to Persona as well? :Smile:
