### ISSUE TITLE
Meta og:title not refresh when topic change

### ISSUE THREAD

**Issue by yoyoyohamapi** [NodeBB/NodeBB#7544]
- **NodeBB version:** 1.12.0

First, I move to a topic with title `A`, then I jump to another `B` topic through breadcrumbs, but the Meta `og:title` remains the same (`A`). 

When I visit one topic in an app webview, then go to another topic and share it back to app container. People would see a wrong title because the identification of the title is based on `og:title`(Open Graph Protocol).

**Comment by julianlam** [comment]
`og:title` doesn't care about SPA, it's only what the value is on a cold load. If you're seeing incorrect sharing let us know what page it is.

**Comment by pig315** [comment]
![5555xbgf6-tucy6](https://user-images.githubusercontent.com/45277553/56274803-07491580-6132-11e9-85b4-1090e51420ec.gif)
@julianlam look at this 
We also have this problem.

**Comment by pig315** [comment]
![999999](https://user-images.githubusercontent.com/45277553/56275231-e1704080-6132-11e9-98bd-f38e780a11c3.gif)
@julianlam 
in China 
we use qq , hundreds of millions of users use it for communication 
we have the same problem 
can you help me?

**Comment by julianlam** [comment]
Thanks, I'll look into it

**Comment by pig315** [comment]
@julianlam I'm okay on Android phone, but there's a problem with Apple phone.
thank you

**Comment by julianlam** [comment]
@pig315 @yoyoyohamapi I understand, looks like the qq app doesn't parse the details separately but takes it from the already-loaded HTML. That makes sense from a data conservation point of view. I will make the change to update the meta tags, although it will require some additional research...
