### ISSUE TITLE
Ban status not updated with latest ban

### ISSUE THREAD

**Issue by Dravere** [NodeBB/NodeBB#7547]
- **NodeBB version:** 1.11.2
- **Database type:** mongo
- **Database version:** 3.6.10
- **Exact steps to cause this issue:**
1. Ban an user temporarily (e.g. for a day)
2. Wait until the ban expires, but the user hasn't logged back in, thus they are still shown as banned
3. Ban them permanently
- **What you expected:** They should be marked as banned permanent.
- **What happened instead:** They still show the previous temporarily ban.

I don't know if it is necessary to wait in point 2. But it is how it happened just now in my forum.

**Comment by julianlam** [comment]
@akhoury can you take a look at this?

**Comment by akhoury** [comment]
sounds like an early exit

if banned
  don't do anything

I'll take a look

**Comment by akhoury** [comment]
that should do it
