### ISSUE TITLE
clicking new topic doesnt work on /recent if javascript is disabled

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7549]
works fine on category pages

**Comment by julianlam** [comment]
https://github.com/NodeBB/nodebb-theme-persona/compare/nojs-category-dropdown

For developer review 28 June 2019

**Comment by julianlam** [comment]
FWIW the current user dropdown at the top right of the page uses this clever hack:tm:

**Comment by julianlam** [comment]
nodebb/nodebb-theme-persona#483
