### ISSUE TITLE
NodeBB does not register plugin.

### ISSUE THREAD

**Issue by minicacristi** [NodeBB/NodeBB#7551]
- **NodeBB version:** 
v1.7.5
- **NodeBB git hash:** 

7df191412de9dfd88c3c9b919b6989fd18b5d445
- **Database type:** mongo, redis, or postgres
mongo
- **Database version:** 

3.4.4
- **Exact steps to cause this issue:**

Start from scratch. Follow the guidelines as expected in NodeBB installation guide.
Install https://github.com/akhoury/nodebb-plugin-import using their installation guide.
- **What you expected:**

The plugin to be seen.
- **What happened instead:**=

The plugin is not seen.

**Comment by pitaj** [comment]
Where are you expecting to see the plugin? Did you check to see if it is actually installed in node_modules?

**Comment by julianlam** [comment]
Run `./nodebb build` then restart NodeBB.
