### ISSUE TITLE
Using width=calc(100% - 30px) results with width=calc(70%)

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7557]
Hi Developers,

I am on the latest master.

To reproduce: Add a CSS attribute on some element as follows:
element {
   width: calc(100% - 30px).
}

Lets assume the available width is 1000px, thus, the expected result is 970px. 
However the above is compiled to calc(70%) resulting with width=700px.

Using nested calc as follows: width=calc(calc(100%) - calc(30px)) results with error during compilation.

Any idea?
Thanks!
JJ.

**Comment by julianlam** [comment]
Hi @PostMidnight -- you're writing LESS, not CSS, so in this case, you'll want to use `width: "calc(100% - 30px)"`, I believe.

**Comment by PostMidnight** [comment]
Thank you so much @julianlam you have no idea how much I struggled with this :)
