### ISSUE TITLE
Chat window resize [Event listener on element]

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7564]
Hi Developers,

I am synced with the current master. 
To reproduce the issue use chrome emulator with Nexus 5, bring up a chat window and open the keyboard and then close it. You may notice the height of the window remains the same. 

I believe the issue stems from the code below (in public/src/module/chat.js):

```
chatModal.find('.modal-content').on('resize', function (event, ui) {
                                                if (ui.originalSize.height === ui.size.height) {
                                                        return;
                                                }

                                                chatModal.find('.modal-body').css('height', module.calculateChatListHeight(chatModal));
                                        });
```

Please note that the code is trying to attach a resize event to an element. However According to http://www.quirksmode.org/dom/events/resize.html the resize event is available on the window, but not elsewhere.

To that end, changing the code above to the below resolves the resize issue:

```
window.addEventListener('resize', () => { 
  chatModal.find('.modal-body').css('height', module.calculateChatListHeight(chatModal));
});
```

Once this is fixed, the .modal-body element will stretch, and in turn will trigger the subsequent listener on the modal-body.

Kindly consider adding this fix. Thank you!
JJ.

**Comment by barisusakli** [comment]
Hmm that resize handler is definitely called in desktop mode.

**Comment by PostMidnight** [comment]
Hi @barisusakli , 
It might work in desktop, but certainly its unstable. 
Lots of posts on the net can confirm that event listeners on elements are unsupported/unstable and should not be used.
Took me a lot of time to figure out why it did not work on my cell ;) I am certain it will fail with others. Thus, I hope you'll consider my proposal. 
Kindly let me know if I can be of further help.
JJ.

**Comment by barisusakli** [comment]
Sorry wasn't clear the `resize` event is from jquery ui http://api.jqueryui.com/resizable/#event-resize and is triggered on the element when the modal is resized from the bottom right corner. It is not the window resize event.

So the fix would be to add 

```
window.addEventListener('resize', () => { 
  chatModal.find('.modal-body').css('height', module.calculateChatListHeight(chatModal));
});
```

but also keep the current `resize` event handler.

**Comment by PostMidnight** [comment]
Thank you!

**Comment by pitaj** [comment]
Do we even need an event handler? Can flexbox be used instead?

**Comment by PostMidnight** [comment]
Not sure, I tried using height=100% and it did not work well, so I went after the event handler. 
I might have done it incorrectly however.

**Comment by barisusakli** [comment]
This code is already in core https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/chat.js#L319-L321

but it wasn't scrolling to the bottom when the window was resized I am adding that in.

**Comment by barisusakli** [comment]
![resize](https://user-images.githubusercontent.com/2583394/57024125-d40e8800-6c01-11e9-8eff-fddf8a7b5df9.gif)
