### ISSUE TITLE
Does NodeBB provide RESTful API?

### ISSUE THREAD

**Issue by CoderYellow** [NodeBB/NodeBB#7566]
If not,do you have any plans to support it.I am going to develop an native Android app for NodeBB,it would be helpful to develop with RESTful API,otherwise I will need to use some libraries like `jsoup`  which is more difficult.

**Comment by pitaj** [comment]
The API is pretty restful. Everything can be done between the API and websockets.

**Comment by CoderYellow** [comment]
@pitaj  fine,are  thre any  documents about the  api,i am not farmilar with nodejs,do i need to capture the network from browser.

**Comment by julianlam** [comment]
Prepend any route with `/api` to see the underlying JSON. Use [nodebb-plugin-write-api](/julianlam/nodebb-plugin-write-api) to make requests to NodeBB.

Have fun!

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
