### ISSUE TITLE
Unable to set up registration as Admin Approval + Invite

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#7567]
The admin approval feature works well, although the invite user functionality is disabled with this option. It would be ideal if I could enable the admin approval feature while allowing invitations.

There is an "Admin Invite Only" option, but I am not sure if this is the correct option (doesn't seem to be).

**Comment by kaye1112934** [comment]
I am his wife try to fix this but github will not  let me sign in

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!

**Comment by kaye1112934** [comment]
It was in my husband stuff I am sorry I didn't mean to do anything  wrong
