### ISSUE TITLE
Feature request: limit edit for new users

### ISSUE THREAD

**Issue by mfalkvidd** [NodeBB/NodeBB#7585]
Use case: Users post innocent-looking posts and then come back later (sometimes multiple days later) to edit their posts and replace the contents with spam.

We already have the post restriction feature "Number of seconds before users are allowed to edit posts after posting".

I don't want to use this setting, because it would be a big inconvenience for legit users.

What if this setting could be applied to "New User Restrictions"? That would raise the bar, forcing dishonest users to post good contents that gets upvoted before they could edit their posts, while not affecting most users that have earned sufficient reputation.

The fight against spammers is a cat-and-mouse-game so they will probably find a way around this feature as well, but it would hopefully raise the bar a bit.

An alternative countermeasure could be to add a feature "Number of seconds after posting before users are *disallowed* to edit posts" so posts that are multiple days old can not be edited.

Reference to a similar issue: https://github.com/NodeBB/NodeBB/issues/6021

**Comment by julianlam** [comment]
Unless I'm mistaken we already have an option to disallow edits after a certain number of days, no? I'll look into it

**Comment by barisusakli** [comment]
>An alternative countermeasure could be to add a feature "Number of seconds after posting before users are disallowed to edit posts" so posts that are multiple days old can not be edited.

We have this

![image](https://user-images.githubusercontent.com/2583394/57544333-08cabf80-7325-11e9-9981-9cd6640d103a.png)

**Comment by barisusakli** [comment]
Sorry missed the first part of your post but the current ACP setting does this `so posts that are multiple days old can not be edited.` Maybe the wording is a bit weird 😆 

For example setting it to 90 will prevent users from editing their posts after 90 seconds.

**Comment by julianlam** [comment]
@barisusakli ah, got it. I'll update the source language string to make it more clear.

**Comment by julianlam** [comment]
#7590 fixes the labelling issue. I agree that a separate timeout for new users might be helpful (in @mfalkvidd's case, he could even set it to `0` for new users)

**Comment by julianlam** [comment]
8a6a58ee4383c9b0f3b344f5343adb759b0addfb
