### ISSUE TITLE
timeago locale reverts to English when logging in despite users language preference

### ISSUE THREAD

**Issue by yossizahn** [NodeBB/NodeBB#7586]
- **NodeBB version:** latest

- **Exact steps to cause this issue:**
	1. Change interface language to one that doesn't have a `-short` version of "timeago". In my case, Hebrew.
	2. Logout and then login again (using password login, thus no page reload occurs)

- **What you expected:**
timeago locale should be your preferred locale.
- **What happened instead:**
It has reverted to English. Only after refreshing the page will it show in your preferred language.

**Comment by julianlam** [comment]
Indeed, it looks like that particular conditional was added here (https://github.com/NodeBB/NodeBB/commit/cee47f78b2af6a58d7d70457b22f986942c96540) by mistake,
