### ISSUE TITLE
What do I need to do if the site needs to be relocated?

### ISSUE THREAD

**Issue by haig233** [NodeBB/NodeBB#7591]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo, redis, or postgres
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

If my site needs to be migrated, how do I keep all the data reinstalled?

**Comment by barisusakli** [comment]
Backup your database restore it on the new server. For further questions please use https://community.nodebb.org/category/16/technical-support

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
