### ISSUE TITLE
Update Readme, add install instructions

### ISSUE THREAD

**Issue by EmreSURK** [NodeBB/NodeBB#7592]
- **What you expected:**
When I clicked Documentation & Installation Instructions link from the Readme file, it should forwards me the page that includes installation instructions. 
- **What happened instead:**
When I clicked Documentation & Installation Instructions link from the Readme file, it forwards me to https://docs.nodebb.org/ address and there is no installation instruction. There some text about helping, contributing and localization, but no installation.

**Comment by pitaj** [comment]
There's a menu on the docs page

**Comment by julianlam** [comment]
Installation instructions are linked to, lower down in the readme: https://docs.nodebb.org/installing/os
