### ISSUE TITLE
Can't click input on admin panel when change language to Turkish

### ISSUE THREAD

**Issue by EmreSURK** [NodeBB/NodeBB#7594]
- **NodeBB version:** v1.12.1
- **NodeBB git hash:** 041cde4dbce64c8f748c81800fac8f6738bf0005
- **Database type:** mongo
- **Database version:** v4.0.9
- **Exact steps to cause this issue:**
1. Login as Admin
2. Navigate :/admin/settings/user
3. Scroll down User Registiration (#kullanıcı-kaydı in my local language) section. 
- **What you expected:**
All inputs should not in same link.
Switch buttons can be changeable.
- **What happened instead:**
When my mouse over input or switch, all section hovers like a link. When I click any input or switch button it navigates me to /admin/manage/users
I also added a screenshot to show how it acts. 
I m using Turkish by the way I checked, no error in the English version.
Thanks. 
<img width="1040" alt="ActsLikeALink" src="https://user-images.githubusercontent.com/9450430/57582435-71ed3700-74cd-11e9-919b-459393211ceb.png">

**Comment by barisusakli** [comment]
Fixed in translation string in transifex, there was <a> tags that weren't closed.
https://www.transifex.com/nodebb/nodebb/translate/#tr/admin-settings-user/103104806

**Comment by EmreSURK** [comment]
Thanks for the quick answer.
Can I manually install the Transifex file to my NodeBB Forum? It is possible or recommended or should I just wait for the next release?

**Comment by barisusakli** [comment]
You can fix the file until the next release on your install.
