### ISSUE TITLE
Recursive post delete

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7595]
Hi Developers,

Kindly assume the following:
User A replies to a topic.
User B replies to user A (nested reply).
User A deletes its reply.

Currently, the post made by User B remains. I had expected User-B's post to be deleted as well.

Is the current implementation correct?

**Comment by pitaj** [comment]
Nested replies don't exist in NodeBB. They are simply normal replies to the topic with the convenience of a little extra flag describing what post they were replying to. Topics have a flat, non-hierarchical structure in NodeBB.

Given that, no, it does not make sense that a reply would be deleted or hidden when the post it's a reply to is deleted. That does not occur even on places like Reddit.

**Comment by julianlam** [comment]
Yes, of course. Replies maintain relationships to each other only in the sense that a reply can say it was in reply to a different post, but there's no way someone would be able to delete "child" posts.

**Comment by PostMidnight** [comment]
Thank you. To that end, perhaps it makes sense to set post.toPid of the children of the post that was deleted to the first post?

**Comment by PostMidnight** [comment]
I am asking because if you turn on "threaded replies" the replies without the toPid pointing to an existing post will be dangling.

**Comment by pitaj** [comment]
If you don't wish to leave posts dangling, then you should disable purging.

**Comment by PostMidnight** [comment]
Hi @pitaj, 

Disable purging on a global level will work but its a little bit of an overkill :)

Instead, please consider the following minor change to src/posts/delete.js, line 71.
The code checks if the post has replies, and if so, purge is canceled with an error. 
I am only bringing in the very first reply id, so this change has very very low performance impact.


```
Posts.purge = function (pid, uid, callback) {
		let postData;
		async.waterfall([
			function (next) {
				db.getSortedSetRange('pid:' + pid + ':replies', 0, 1, function(err, set) {
					if(err)
						return next(err);
					else if (set.length)
						return next(Error('Current post has replies and thus cannot be purged'));
					else
						Posts.getPostData(pid, next);
				});
			},
```
