### ISSUE TITLE
Put the &nbsp's outside the <a> tag

### ISSUE THREAD

**Issue by jidanni** [NodeBB/NodeBB#7600]
I got an email that caused the cursor to tab to an empty area before a link instead of tabbing to the beginning of the link text, when using emacs' gnus.
I traced it down to NodeBB.
 ```
<a href="https://community.windy.com/post/22324" style="background: #222222; border: 15px solid #222222; font-family: sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" class="button-a">
<span style="color:#ffffff;" class="button-link">&nbsp;&nbsp;&nbsp;&nbsp;Click here to go to forum&nbsp;&nbsp;&nbsp;&nbsp;</span>
</a>
```
So please put the `&nbsp;&nbsp;&nbsp;&nbsp;`'s **outside** the `<a>` tag,

No I don't own the site. I just got a mail from them seemingly generated by NodeBB so found this GitHub.

**Comment by julianlam** [comment]
Before anyone changes this -- bear in mind `&nbsp;` is used specifically to add padding. It is very likely that changes to the button to use padding will fail on email clients for one reason or another.

**Comment by jidanni** [comment]
One also notes the user is surprised that clicking
https://community.windy.com/post/22324 oddly takes him to
https://community.windy.com/topic/8388/android-app-lacks-menu/5

I would just put the real destination in the mail message.

Also although
"Click here to go to forum" is technically correct
"Click here to go to the article" would be more correct, and
"Click here to go to the comment" would even be more correct.

Indeed, one would expect
"Click here to go to forum" to only go to
https://community.windy.com/
when in fact you are (thankfully instead) bringing us many leves deeper down.

**Comment by julianlam** [comment]
@jidanni Why, yes, that is a perfectly legitimate complaint, :smile: I'll get _that_ one fixed.

**Comment by julianlam** [comment]
[This article](https://litmus.com/blog/a-guide-to-bulletproof-buttons-in-email-design) suggests that a combination of table formatting and border-radius hacking can effectively work. I'll look into replacing our buttons (which are using the tabular format) to this.

**Comment by jidanni** [comment]
OK good, because otherwise, using keyboard TAB, there is no way I can then "Click here" with ENTER,
because I can't get "there":
![X0](https://user-images.githubusercontent.com/1230959/57814055-0e049000-77a5-11e9-91b8-a4beca7b5bb4.jpg)
P.S., for a button perhaps just try [HTML `<button>`](https://www.w3docs.com/learn-html/html-button-tag.html).
