### ISSUE TITLE
ERROR: No users in this room, when user leaves chat

### ISSUE THREAD

**Issue by credocleo** [NodeBB/NodeBB#7601]
It's a little odd how it works like a "chat room" (if User A starts a chat with User B, and then User A leaves the room, User B will just see an "ERROR: No users in this room" if they try to reply). If User A wants to continue the chat - it will then open up another, separate chat room (the original one won't continue). I kind of expected this to work somewhat like Facebook's messaging feature works, but the existence of a "chat room" that can start and stop working when one user leaves was a little and confusing. Is there a work around for this? 

I raised this in the NodeBB forum and @barisusakli told me to report it here in Github.

Thanks

![error no users in chat](https://user-images.githubusercontent.com/6916358/57672151-78082280-7649-11e9-89a3-492b6210f771.png)

**Comment by barisusakli** [comment]
This was added here https://github.com/NodeBB/NodeBB/pull/4250, open for discussion should you be able to message a room when there are no other users in there?

**Comment by julianlam** [comment]
I agree there's a disconnect between whether our chat system is meant to act like a chat or like an IM system.

It is reasonable to assume that that particular toaster (`Error: No users in this room`) should only be shown if things go wrong. The UI should reflect the fact that you cannot write messages, and so I think a sensible solution would be that if you are the only user left in the room, the chat input should be disabled until additional users are added to the room.

In essence, the chat room is _archived_.

**Comment by julianlam** [comment]
Alternatively, it shouldn't matter whether there is someone else in the room or not. I suppose if you want to, you could always just chat with yourself. I will investigate why the error shows up at all, and whether it needs to be there in the first place.
