### ISSUE TITLE
ReCaptcha not appears after navigation

### ISSUE THREAD

**Issue by floufille** [NodeBB/NodeBB#7611]
- **NodeBB version:**  1.12.1 

- **Database type:** mongo
- **Database version:** v3.6.12

- **Exact steps to cause this issue:**

If you go on register page. If you refresh the page, recaptcha appears.
If you navigate, for example on "user", then you go again on register, the recapatcha not appears.

The problem appears also on: https://community.nodebb.org/

I'm on Chrome 74.0.3729.157 

![nodebb](https://user-images.githubusercontent.com/36710813/57799173-baffee00-774e-11e9-99c4-c60590f5238f.png)

Thanks

**Comment by julianlam** [comment]
https://github.com/akhoury/nodebb-plugin-spam-be-gone/issues/65
