### ISSUE TITLE
handle diff.applyPatch returning false in some cases

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7619]
Originally reported here https://community.nodebb.org/topic/13966/error-uncaughtexception-source-split-is-not-a-function

Possible relevant dependecy issue https://github.com/kpdecker/jsdiff/issues/247

**Comment by sscarduzio** [comment]
Any update on this?

**Comment by barisusakli** [comment]
Seems like there is no update on the upstream dependency.
