### ISSUE TITLE
./nodebb start doesn't work

### ISSUE THREAD

**Issue by tale503** [NodeBB/NodeBB#7622]
NodeBB Setup Completed. Run "./nodebb start" to manually start your NodeBB server.
 NodeBB (v1.12.x) $ ./nodebb start

Starting NodeBB
  "./nodebb stop" to stop the NodeBB server
  "./nodebb log" to view server output
  "./nodebb help" for more commands

NodeBB (v1.12.x) $ 

./nodebb start doesn't  work, why ?

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
