### ISSUE TITLE
Online users appear offline

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7623]
Hi Developers,
My setup is synced with master.
I noted that when the user logs in, he appears to be offline. 
Note the following function:

```
middleware.pageView = function pageView(req, res, next) {
	analytics.pageView({
		ip: req.ip,
		uid: req.uid,
	});

	plugins.fireHook('action:middleware.pageView', { req: req });

	if (req.loggedIn) {
		user.updateLastOnlineTime(req.uid);
		if (req.path.startsWith('/api/users') || req.path.startsWith('/users')) {
			user.updateOnlineUsers(req.uid, next);
		} else {
			user.updateOnlineUsers(req.uid);
			setImmediate(next);
		}
	} else {
		setImmediate(next);
	}
};

```
user.updateLastOnlineTime is called without a callback. Thus, it may be executed after user.updateOnlineUsers is called. The UID may, in turn, not included in the "online" uids.

Please consider the following proposal. It seems to resolve the issue at hand.

```
if (req.loggedIn) {
		user.updateLastOnlineTime(req.uid, function(err) {
                     if(err)
                        return next(err);

    		     if (req.path.startsWith('/api/users') || req.path.startsWith('/users')) {
			user.updateOnlineUsers(req.uid, next);
		     } else {
			user.updateOnlineUsers(req.uid);
			setImmediate(next);
		     }
                });
	} else {
		setImmediate(next);
	}

```

**Comment by barisusakli** [comment]
Those two functions don't depend on each other so waiting for the callback shouldn't do anything.

Do you have reproduction steps for this? 

Both `updateLastOnlineTime` and `updateOnlineUsers` don't update values if it was already updated in the past 5 minutes. https://github.com/NodeBB/NodeBB/blob/master/src/user/online.js#L11-L42

**Comment by PostMidnight** [comment]
Hi @barisusakli 

I believe they are connected, allow me to explain.

updateLastOnlineTime sets the last online as follows: 

`User.setUserField(uid, 'lastonline', now, callback);
`

user.updateOnlineUsers reads the lastonline timestamp and the following statement

```
function (userOnlineTime, next) {
                                if (now - parseInt(userOnlineTime, 10) < 300000) {
                                        return callback();
                                }
                                db.sortedSetAdd('users:online', now, uid, next);
                        },
```

Now, if updateOnlineUsers executes before updateLastOnlineTime had a chance to update the timestamp (happens all the time for me, for some reason...), the callback will be called and the user wont be included in the online group.

Thus, we have a race.

**Comment by barisusakli** [comment]
Those two functions are using different values one is the lastonline stored in the user:<uid> hash the other is using the score in users:online sorted set.

**Comment by PostMidnight** [comment]
Got it thank you. 
Nevertheless, the behavior should be identical - that is, update timestamp first, and then use timestamp to figure out if the user should be included into the online group.
Currently (reproducible on chrome debugger), setUserField is called after the updateOnlineUsers executes, leading to users appearing offline.

**Comment by barisusakli** [comment]
@PostMidnight please provide reproduction steps so I can test this.

**Comment by PostMidnight** [comment]
@barisusakli , with pleasure:
1. Use latest master, compile and start the forum. 
2. Open chrome window, log in (any user, I used admin), and go to /users?section=online
3. Setup chrome debugger on the server code (I found this tool helpful: https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en ).
4. Insert a break-point inside User.setUserField right on the timestamp update.
5. In user.updateOnlineUsers insert a break-point on return callback() - see below:

```
function (userOnlineTime, next) {
                                if (now - parseInt(userOnlineTime, 10) < 300000) {
                                        return callback();
                                }
                                db.sortedSetAdd('users:online', now, uid, next);
                        },

```

6. Close nodebb (ctrl^C) and restart (this should classify the current logged in user as offline).
7. Refresh the window in which you logged in previously in step 2.
8. Trace the breakpoints. In my setup, updateLastOnlineTime updates the timestamps after the return callback is executed in setUserField.

Result (on my setup): even-though the /users?section=online page was refreshed, the status page does not show the logged in user.

I hope you'll be able to reproduce the issue with these instructions. Kindly let me know should you need additional information.
JJ.

**Comment by barisusakli** [comment]
>Close nodebb (ctrl^C) and restart (this should classify the current logged in user as offline).

Restarting nodebb doesn't mark users as offline, they will be still in the `users:online` set.

When I restart the server and go to `/users?section=online` the logged in user is still show as online.

**Comment by PostMidnight** [comment]
hmm. can you somehow set the status to offline before you restart the forum. One way is to wait 30min...

**Comment by barisusakli** [comment]
Why do you want to set users to offline when the forum restarts?

**Comment by PostMidnight** [comment]
Its the best way I found to reproduce the issue consistently.

**Comment by PostMidnight** [comment]
Where you able to reproduce?

**Comment by barisusakli** [comment]
Yeah, I wasn't sure what you were talking about before 😆 should work fine now.

**Comment by PostMidnight** [comment]
Thank you so much!
