### ISSUE TITLE
On group name change, navigation bar perms don't change

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7625]
- **NodeBB version:** 1.12.2
- **NodeBB git hash:** 22db818eb40f04e528d95257c5517ded8341493d

- **Exact steps to cause this issue:**
1. Create a group. (Gamees)
2. Create a new navigation bar route, and for the groups, allow Gamees to view it.
![EAFA52B6-6030-4CDA-9521-3822514F8F27](https://user-images.githubusercontent.com/35382971/58114174-32a5a100-7bc5-11e9-9022-f847ff1ff733.jpeg)

3. Change the group name (Gamees -> Gamers)

- **What you expected:**
I expected the navbar group to be updated, and say "Gamers", just like the privileges update.

- **What happened instead:**
It said "0 items", and did not update correctly. ;(

**Comment by julianlam** [comment]
Odd, why would it say "0 items", wouldn't it always show `registered-users`, as your screenshot suggests?

**Comment by PatheticMustan** [comment]
Ah, I made some screenshots to clarify

Switch groups to "Tanks"
![9AC37464-21AC-4BDE-A93F-3D1B3248BA9C](https://user-images.githubusercontent.com/35382971/58120249-d0539d00-7bd2-11e9-9a09-57a894e725ac.png)
Change name of "Tanks" to "Tanks!" or whatever else.
![7C13CB5F-4BD9-40B4-B8F8-E7D45A19BF6A](https://user-images.githubusercontent.com/35382971/58120255-d47fba80-7bd2-11e9-9b6b-461980f27226.jpeg)
Now it says 0 items.
![0DBA99BA-4AA9-4C2A-8609-826F33F31654](https://user-images.githubusercontent.com/35382971/58120262-d8134180-7bd2-11e9-9450-f6d5aed241ed.png)
