### ISSUE TITLE
Mail notification while user is online

### ISSUE THREAD

**Issue by ic3fresh** [NodeBB/NodeBB#7630]
- **NodeBB version:**  1.12.0
- **Database type:** mongo

- **Exact steps to cause this issue:**
 1. user has set mail notifications to ON (on mentions for example)
 2. user is online
 3. user is constantly watching and reading new messages
 4. user is still getting mail notification even though he had been reading messages
- **What you expected:**
 Suggestion is to give option to set mail notification send delay and before sending check if user had read the post.
If yes - do not send mail
If no - send mail

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5867
