### ISSUE TITLE
What is Uid 0

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#7643]
In the below line a zero value is passed in for the uid param of Flags.getTarget. What is uid 0? In our database it doesnt exist but for some reason 'uid:0:blocked_uids' has values in which causes issues with viewing certain flags detail pages. Just want to confirm what the intended behaviour of the zero is before I remove the values from blocked_uids list

https://github.com/NodeBB/NodeBB/blob/1d26aac8b8c45eaaf389464402c083b7a068d6b7/src/flags.js#L93

**Comment by barisusakli** [comment]
uid 0 is the guest user, but `uid:0:blocked_uids` shouldn't exists since guests shouldn't be able to block anyone.

**Comment by uplift** [comment]
Thanks for the quick reply. That's strange that guests has a blocked list. I'll dig into it further. Thanks for the information

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7087
