### ISSUE TITLE
[Feature Request]: Browse images Instagram style 

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7646]
Hi Developers,
I believe it would be beneficial to allow browsing just the images/videos that are attached to posts (Instagram style).
Thanks for your consideration,
JJ.

**Comment by julianlam** [comment]
NodeBB lightbox plugin (while outdated) would achieve this. We'll keep this in plugin-land where it belongs.

**Comment by julianlam** [comment]
https://github.com/psychobunny/nodebb-plugin-gallery
