### ISSUE TITLE
Async 3.0 breaks plugin

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7655]
Hi Developers,

My plugin requires async lib of nodebb.
Latest master stopped working (the first page did not load), and the issue was traced back as follows:

Everything works with:
https://github.com/NodeBB/NodeBB/issues/7627
git hash 6cebc7f0691ca0209e84aef404165917913eda50 

First page does not load following:
https://github.com/NodeBB/NodeBB/pull/7639
git hash 4d9bc30d1f2b1a1dd832b1a59ef708eae7e3a422 

I did notice that Topics.getTopicWithPosts does not end. In chrome debugger it seems that the 2nd stage is not hit. Note I changed the next of the first stage to next_jj so I may trigger on breakpoints.

```
Topics.getTopicWithPosts = function (topicData, set, uid, start, stop, reverse, callback) {
	async.waterfall([
		function (next_jj) {
			async.parallel({
				posts: async.apply(getMainPostAndReplies, topicData, set, uid, start, stop, reverse),
				category: async.apply(categories.getCategoryData, topicData.cid),
				tagWhitelist: async.apply(categories.getTagWhitelist, [topicData.cid]),
				threadTools: async.apply(plugins.fireHook, 'filter:topic.thread_tools', { topic: topicData, uid: uid, tools: [] }),
				followData: async.apply(Topics.getFollowData, [topicData.tid], uid),
				bookmark: async.apply(Topics.getUserBookmark, topicData.tid, uid),
				postSharing: async.apply(social.getActivePostSharing),
				deleter: async.apply(getDeleter, topicData),
				merger: async.apply(getMerger, topicData),
				related: function (next) {
					async.waterfall([
						function (next) {
							Topics.getTopicTagsObjects(topicData.tid, next);
						},
						function (tags, next) {
							topicData.tags = tags;
							Topics.getRelatedTopics(topicData, uid, next);
						},
//					], next);
//					JJ
                                        ], function(err, res) {
  next(err, res);
});
				},
//			}, next);
//			JJ
                        },  function(err, res) {
  next_jj(err, res);
});
		},
		function (results, next) {
//We never get here :(
```

Nothing in v3.0 breaking changes explains the issue at hand.

Any help will be appreciated.

**Comment by PostMidnight** [comment]
Solved. 
In my plugin in one of the functions I returned: callback(err), and err was set to false.
In async v3, returning false kills the async loop. See here:
https://github.com/caolan/async/blob/master/CHANGELOG.md

I am purposely leaving this issue open so no one else will spend 1/2 a day on this :)
Please feel free to close this issue at your convenience.

**Comment by julianlam** [comment]
> My plugin requires async lib of nodebb.

There's your problem. This used to be the recommendation but is no longer the case as underlying dependencies can change.

Rely on your own async dependency for plugins any require NodeBB only for libs and Winston
