### ISSUE TITLE
v1.12.2 with MongoDB v4 doesn't show  new data on page until switch to dev mode

### ISSUE THREAD

**Issue by szabof1** [NodeBB/NodeBB#7656]
NodeBB v 1.12.2 (git hash 22db818eb40f04e528d95257c5517ded8341493d - v1.12.x)
MongoDB v4.0.10
NodeJS v10.16.0
AWS EC2 (Amazon Linux)

This is my first install of NodeBB ever. Just started and logged in as admin and wanted to create new users. 
1. When I clicked on "CREATE"on Create New User page nothing happened, so I clicked again. Still nothing. I had to close the pop-up page manually (clicked on X).
2. The user list shown no new users and there were no new messages in the log so I decided to stop NodeBB and start it in dev mode.
3. Once in dev mode when I refreshed the admin page of users I could see the user created twice with different ids.

Then I tried to create new groups, roles, tags, new replies to out-of-box posts and I never could see any new data when NodeBB was started using `./nodebb start` but could see those data and could add new data when started using `./nodebb dev`.

What's wrong with my setup?

Thank you!

**Comment by Pummelchen** [comment]
In Chrome goto Inspect and check Console log for socket.io errors.

**Comment by szabof1** [comment]
Hi Pummelchen,

Thank you for the tip. Yeah, in the developer tools console logs there was the socket.io error and even the reason and the resolution with [this link to a super cool post ([FAQ] Websockets not working due to misconfigured origins)](https://community.nodebb.org/topic/13388/faq-websockets-not-working-due-to-misconfigured-origins).
I did the necessary corrections and everything works fine now.

Thank you very much again. :)
