### ISSUE TITLE
Topics is not load

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7657]
- **NodeBB version:** 1.12.2
- **NodeBB git hash:** 0dca13e9c22fae59704fd18d9aff0a34054fef7e

- **Database type:** redis
- **Database version:** 5.0.3

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

After updating NodeBB to the last commit, the topic does not load

Console
```
Failed to load resource: the server responded with a status of 524 ()
```

Console url: https://umod.pl/api/topic/145/wz%C3%B3r-dodawania-post%C3%B3w-w-dziale-wsparcie?_=1559313505082

**Comment by julianlam** [comment]
Getting a 502 on the forum now -- could be there is a crash that you should investigate?

**Comment by barisusakli** [comment]
Sounds like the same async 3.0 issue, make sure your plugins don't do `callback(false, data)` use `callback(null, data)` instead.

Make sure you follow this as well https://github.com/caolan/async/blob/master/CHANGELOG.md#breaking-changes

**Comment by julianlam** [comment]
Yes, if you have any plugins that rely on NodeBB's async version, they should be updated to require the old async (or update to compatibility with async@^3) :smile:

**Comment by youhosi** [comment]
@julianlam Yes yes, I am just updating the reworked Q&A :D 

Thanks @julianlam & @barisusakli :D
