### ISSUE TITLE
Improvements to Events Admin Page

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#7661]
* [x] Allow filtering by start and end date
* [x] General design overhaul (use of `span` labels, wells, move filters to sidebar)
* [x] Allow filters form to be used without javascript
* [x] Allow plugins to add different event types via new hook

**Comment by PostMidnight** [comment]
Will it be possible to show the number of logged-in users instead or in addition to the number of unique users?

**Comment by julianlam** [comment]
Hi @PostMidnight -- this issue was for the Events page in the ACP, not the dashboard :smile:

**Comment by PostMidnight** [comment]
For some reason I thought you meant network events. My bad ;)
