### ISSUE TITLE
How to restrict/ignore all types of body parser errors from the express.js/node.js? since the uncaughtException and unhandledRejection are not handling those.

### ISSUE THREAD

**Issue by TulasiramRajanna** [NodeBB/NodeBB#7662]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo, redis, or postgres
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

**Comment by barisusakli** [comment]
This isn't really related to NodeBB, maybe try the forums or SO.
