### ISSUE TITLE
Filter Hook in Notifications

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#7672]
Would it be possible to add a filter hook to after the user get notifications below?

Something like

    function (notifications, next) {
	       plugins.fireHook('filter:notifications.get', { notifications: notifications, uid: uid }, next);
	},
	function (data, next) {
		next(null, data.notifications);
	},

https://github.com/NodeBB/NodeBB/blob/25d289c6f6d8682890f217567a0ed9d2a36bd98e/src/user/notifications.js#L33-L39

**Comment by barisusakli** [comment]
`filter:notifications.get`  is already used [here](https://github.com/NodeBB/NodeBB/blob/master/src/controllers/accounts/notifications.js#L79), need a different name for this

**Comment by uplift** [comment]
Maybe filter:notifications.fetch or filter:user.notifications.get?

**Comment by barisusakli** [comment]
Can you let me know what you are trying to accomplish? Adding the hook in that function will only cause it to fire when `UserNotifications.get` is called. 

https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/notifications.js#L10-L13 

There is also user.notifications.getNotifications which is called when a certain number of notifications are being loaded. Do you want the hook to be fired in that case as well? If so I will have to add the hook into https://github.com/NodeBB/NodeBB/blob/master/src/user/notifications.js#L112 which I think makes more sense.

**Comment by uplift** [comment]
I'm trying to integrate the notification list using the socket call into our main website which is outside the bounds of nodebb/benchpress translator so I need a hook when those notifications are fetched via socket the bodyShort text is translated within nodebb server side before the reply is sent to the socket client otherwise it will display as [[TRANSLATE KEY, ..ARGS]].
