### ISSUE TITLE
Issues logging in to admin from another domain (reverse proxy NodeJS)

### ISSUE THREAD

**Issue by danstaak** [NodeBB/NodeBB#7674]
I'm using a reverse proxy ([http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware)) with Node.js to load in an instance of NodeBB.

Website URL - www.website.com/forums/
Forum URL - forum.website.com/forums/

I can't log in to the forum via the website URL (www.website.com/forums/login/)

I either experience a login form post timeout or a session mismatch error.

I can log in directly to the forum via the forum URL (forum.website.com/forums/login), but because of the config.json setup (to allow NodeBB to run on another domain), there is a problem with WebSocket and invalid sessions there.

NodeBB is running from environment variables, key:value as follows:

```
    "url": "http://www.website.com/forums/",
    "secret": "SECRET",
    "database": "postgres",
    "port": "4567",
    "postgres__host": "HOST",
    "postgres__port": 5432,
    "postgres__username": "USER",
    "postgres__password": "PASSWORD",
    "postgres__database": "DB"
```

What config settings are missing to be able to fix this? And more importantly, how can they be set as environment variables?

**Comment by pitaj** [comment]
I'm a little confused. Which URL do you want NodeBB to run under, or do you want both to work? Why aren't you using a more well supported proxy like nginx?

You may want to check out the following topic on the forum: https://community.nodebb.org/topic/13388/faq-websockets-not-working-due-to-misconfigured-origins

**Comment by danstaak** [comment]
@pitaj I want NodeBB to be accessible from 'http://www.website.com/forums/' (which it is), but I can't log in to the admin through that URL, because of some sort of config problem I think - but I'm having trouble being able to set any config settings as env vars.

Thanks for sending the article, I'll take a look.

**Comment by danstaak** [comment]
@pitaj The article you referenced didn't fix my problem, however, it did point me in the right direction to fixing.

It was a Node.js dependancy ordering problem - https://community.nodebb.org/topic/13388/faq-websockets-not-working-due-to-misconfigured-origins
