### ISSUE TITLE
Hard to change icon of group

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#7675]
v1.12.2
It's hard to change the icon of a group, when the current icon is set to "no-icon"
![image](https://user-images.githubusercontent.com/35382971/59224874-690b8600-8b9d-11e9-94b8-bc87310be788.png)

To change the icon, you're supposed to click on it. But you can't click on a 0x0 image! :O 
Maybe there can be a set 10x10 box you could click? Maybe even the buttons, like in the Group Administration Page?
![image](https://user-images.githubusercontent.com/35382971/59225045-c3a4e200-8b9d-11e9-887c-63e6243ccee3.png)
A "Change Icon" button would solve the problem. <3

**Comment by barisusakli** [comment]
It is not obvious but clicking on the `Group Icon` label opens the icon selection modal.

**Comment by PatheticMustan** [comment]
Hm...
(sorry for wasting time ;(  )
