### ISSUE TITLE
Config environment variables not working

### ISSUE THREAD

**Issue by danstaak** [NodeBB/NodeBB#7694]
I'm running NodeBB with environment variables, which in the most part work, except for anything in the socket.io object.

I currently run the following command which generates a config.json from the env vars

```
"database=value port=value postgres__database=value postgres__host=value postgres__password=value postgres__port=value postgres__username=value secret=value url=value ./nodebb setup"
```

However, trying to set the `socket.io` object key=value does not have an effect on the config.json. I've tried the following combinations, none of which create the config.json key=values for `socket.io: { address: "www.forum.com" }`

- socket.io__address
- socket_io__address
- socketIo__address
- socketioAddress
- websocketAddress

Are these key=values able to be set inline?

- **NodeBB version:** 1.12.1

**Comment by pitaj** [comment]
I don't believe those are about to be set inline. Luckily, instead of using the env vars like you currently are, you can pass a JSON string directly like `./nodebb setup [json config]`

**Comment by danstaak** [comment]
Ah OK. Thank you @pitaj (again)
