### ISSUE TITLE
Enhancement - Allow for multiple users to be bound to the same email

### ISSUE THREAD

**Issue by Lazrius** [NodeBB/NodeBB#7698]
Unless I missed this when combing over the AdminCP, there doesn't appear to be an option to allow for this. I am editing the user object a lot as part of a plugin I am designing for my community, and this allows for different 'types' of user. For this reason, it is sort of imperative that people can have multiple accounts.

Ideally, it would be possible for you to specify whether to allow this as a sort of toggle box, similar to how quite a few other BBs handle it.

If this is already possible and I simply missed it, please nudge me in the right direction, thanks.

**Comment by julianlam** [comment]
Can't say we've ever considered doing it, we just make emails unique as a matter of course. The only downside is the linking between emails to users is lost, whereas currently it is 1 to 1.

**Comment by pitaj** [comment]
In this age where Gmail and other services allow for the usage of shortcuts for multiple email addresses (for instance, `example@gmail.com` and `example+option@gmail.com` go to the same inbox) I don't see the niche benefit outweighing the cost.

**Comment by LazDisco** [comment]
I mean that's fair. I guess my thought process is that there are only a few inherit disadvantages, and this is something that would be an 'opt-in' thing for those running the board, so any warnings could be displayed there. I suppose it wouldn't be too much issue to create a plugin that can check for matching emails and append the + if needed, but was still worth suggesting.

If unnecessary, feel free to close.
