### ISSUE TITLE
Topics re-ordering on small windows

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/NodeBB#7702]
- **NodeBB version:** 1.12.2
- **NodeBB git hash:** 22db818eb40f04e528d95257c5517ded8341493d
- **Database type:** mongo
- **Database version:** 4.0.10
- **Exact steps to cause this issue:**
	1. Go to a category page with pinned topics and a small window (xs or sm bootstrap size)...
	2. Try to re-order pinned topics with click-move on pin.

- **What you expected:**
We should be able to re-order topics whatever the window size (no ?). It doesn't work also after resizing window to a largest size...
- **What happened instead:**
No move of pinned topic.

Add-on : I think the problem comes from public/src/client/category/tools.js file, in the handlePinnedTopicSort() function. At the beginning, why is there
`var env = utils.findBootstrapEnvironment();
		if (!ajaxify.data.privileges.isAdminOrMod || env === 'xs' || env === 'sm') {
			return;
		}`
?
Why not remove xs and sm conditions ? If you really want to keep them in nodebb core : 
- I think you should make something if window is resized larger...
- How can I remove these conditions from a plugin ?

Thanks !

**Comment by julianlam** [comment]
I think it makes sense to allow for topic reordering on smaller sizes, although I am not sure if there was a more technical reason that necessitated the conditional to return early. Worth investigating.

**Comment by alfazaz** [comment]
Ok. Good investigation !

**Comment by alfazaz** [comment]
Great. It works ! Thanks !!

**Comment by pitaj** [comment]
Pretty sure this was disabled because it messed with touch scrolling on mobile devices. @barisusakli can you check that it works okay?
