### ISSUE TITLE
add X days later between posts if time difference is higher than threshold

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7718]
![image](https://user-images.githubusercontent.com/2583394/60201132-9c911600-9815-11e9-94ff-b912627cf6dd.png)

**Comment by barisusakli** [comment]
Shamelessly stolen from https://github.com/boomzillawtf/tdwtf/blob/master/plugins/nodebb-plugin-tdwtf-customizations/necro.js @BenLubar

**Comment by 654wak654** [comment]
Is there a way we could modify the `necroThreshold` value from the admin panel? For now I modified  [this part](https://github.com/NodeBB/NodeBB/commit/ee4d78cae3a6ab423ce77e981b033d693beb7fd4#diff-874ef34d7e72931c9f0c2e69bca05928R263), but having it as a setting would be nice.

**Comment by julianlam** [comment]
@654wak654 :point_up:
