### ISSUE TITLE
Latest upgrade script fails with posgress

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7720]
Just updated to latest master, run ./nodebb upgrade and got the below:

Parsing upgrade scripts...
OK | 1 script(s) found, 78 skipped
  → [2019/6/23] Create zsets for user posts per category...
    [####         ] (100/269) 37% Error occurred
Error occurred during upgrade: error: null value in column "value" violates not-null constraint
    at Connection.parseE (nodebb/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (nodebb/node_modules/pg/lib/connection.js:399:19)

Note the "error: null value in column "value" violates not-null". The error is sourced from pg (postgres I/F). 

If the value you are trying to save is indeed NULL, perhaps replace it with '' 
If the issue is in the PSQL code, perhaps COALESS the null variable before saving?
COALESCE(my_null_var, '');

By the way, how can one view the script that failed (6/23)? 
Thanks!

**Comment by barisusakli** [comment]
Let me know if latest master works.

**Comment by PostMidnight** [comment]
Works like a charm thank you!
