### ISSUE TITLE
Category Selector

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7721]
Hi,
with the latest master, when I open an editor and then select a category, the console shows an error. It seems that categoryList.js fails on line 42: 

`$('[tabindex=' + (parseInt($(this).attr('tabindex'), 10) + 1) + ']').trigger('focus');
`

The error is as follows:

```
Uncaught TypeError: e.getAttribute is not a function
    at Function.fe.attr (jquery.js:1549)
    at Object.get (jquery.js:7925)
    at Function.prop (jquery.js:7909)
    at attr (jquery.js:7763)
    at W (jquery.js:3994)
    at C.fn.init.attr (jquery.js:7741)
    at categoryList.js:42
    at HTMLLIElement.<anonymous> (categorySelector.js:19)
    at HTMLDivElement.dispatch (jquery.js:5237)
    at HTMLDivElement.g.handle (jquery.js:5044)

```

It looks like I can post into the right category, but still this may be something to look at.

**Comment by barisusakli** [comment]
`$('[tabindex=' + (parseInt($(this).attr('tabindex'), 10) + 1) + ']').trigger('focus');`

I don't think this code does anything anymore, probably left over from old category selector when it was just a regular html `select`.

I am not getting any errors on https://community.nodebb.org/ though which is running latest master.

**Comment by PostMidnight** [comment]
Interestingly, in your forum, this is undefined, so you are querying $('tabindex=NaN') that's perfectly legal. In my case, this points to window and fails.

Perhaps remove the code if redundant?
