### ISSUE TITLE
Listings with * inside spoilers

### ISSUE THREAD

**Issue by Jey-Cee** [NodeBB/NodeBB#7735]
- **NodeBB version:** 1.12.2

- **Database type:** mongo
- **Database version:** 3.6.12

- **Plugin:** https://github.com/am1cable/nodebb-plugin-simple-spoiler

      1. Create Spoiler and add listing with *
	
- **What happened instead:**
The spoiler works normaly, but the footer is shown twice and it is not possible to edit any post on the thread. The menu with the three dots is empty.

I am not sure where to go with this issue, so i go here with it. Hope thats ok and anyone has an idea.

**Comment by barisusakli** [comment]
Please report this here https://github.com/am1cable/nodebb-plugin-simple-spoiler/issues
