### ISSUE TITLE
convert core modules to async/await

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7743]
Support both async/await and callbacks ie:

`topics.getTopicData(1, function (err, topicData) {});`

`const topicData = await topics.getTopicData(1);`

- [x] Dbal
- [x] Topics
- [x] Users
- [x] Posts
- [x] Categories
- [x] Groups
- [x] Messaging (@julianlam)
- [ ] Meta
- [x] Notifications
- [x] Plugins
- [x] Privileges
- [x] Search
- [x] Social
- [x] Navigation

https://github.com/NodeBB/NodeBB/pull/7736

**Comment by RoiEXLab** [comment]
Hi, just curious why you chose to configure ESLint to ignore this rule:
```
"no-return-await": "off"
```

I ran into the same rule a while ago and after understanding the reasoning it seems that this rule is very useful.

I could imagine that there's a reason why this rule is ignored, but then again I'm curious.

**Comment by barisusakli** [comment]
From what I can tell on newer versions of node `return await foo()` helps with async-stack traces, in other cases it is redundant since you would be calling await on the return promise anyways. It is also necessary if you want to catch any exceptions in the function. More useful reading here  https://stackoverflow.com/questions/44806135/why-no-return-await-vs-const-x-await

**Comment by RoiEXLab** [comment]
The stacktraces make sense, however return await in a try block is perfectly fine even with this rule turned on

**Comment by pitaj** [comment]
Essentially the reason for this is that there are cases where `return await P` works as expected, but `return P` doesn't. `return P` doesn't work correctly inside a `try` block.

Really what we should have is a rule requiring `return await` in every case, but eslint doesn't have such a rule available.

`return await P` does have a performance impact, adding an event loop tick, but I think style consistency is more important for now.
