### ISSUE TITLE
Add topicName to action:composer.topic.new

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7747]
Hi Devs,

In certain cases, a plugin may enable a user to post a message having predefined text. In these cases, it is advantageous to send the body and the title to composer, and allow the user to modify the message as needed prior to posting.

Currently action:composer.topic.new accepts a cid and body, as follows:

```
$(window).trigger('action:composer.topic.new', {
					cid: myCid,
					body: Mybody,
				});

```

Would it be possible to augment the hook, such that it may accept topicName  as well?

Thank you for your kind consideration!
JJ.

**Comment by barisusakli** [comment]
There are 3 places where I see this hook is fired, one of them is when you click `New Topic` on the recent page, the others are inside a topic when you click `Reply as Topic` and when you try to reply to a really old topic and accept creating a new topic instead of replying to the old one.

It doesn't make sense to fill the title when you click `New Topic` on the /recent page. Not sure about the other two cases either. What would the title of the new topic be when you are replying as new topic?

**Comment by barisusakli** [comment]
If we just set it to the the current topic title, I am sure people will forget to modify and post topics with identical titles.

**Comment by PostMidnight** [comment]
Hi @barisusakli thanks for responding! 

Actually, the use cases that I have in mind is a little different. Allow me to describe: 
At some point a custom plugin prepares a message (with title and body), and triggers action:composer.topic.new. The content of the message is sent to the editor, allowing the user to customize it prior to posting it to the forums. Currently, I can only customize the body, but not the title.

If you'll decide to add topicName, it could be set to null in the use cases stated in your comments above. Thus the modification to the hook won't have an impact if not used.

**Comment by barisusakli** [comment]
Well I just checked and it seems this is already possible, if you pass in `title` to `action:composer.topic.new` it will populate the title in the composer.

https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/client.js#L83-L86

**Comment by barisusakli** [comment]
In your plugin just trigger it with 

```
$(window).trigger('action:composer.topic.new', {
	cid: myCid,
	body: Mybody,
	title: myTitle,
});
```

**Comment by PostMidnight** [comment]
Thanks, I tried setting "title", but it did not work. I also tried "titleName" with no luck...

**Comment by barisusakli** [comment]
Which composer?

**Comment by PostMidnight** [comment]
I am using composer-redactor. I believe it sources latest composer. That would be nodebb-plugin-composer-default 6.2.16

**Comment by PostMidnight** [comment]
I see now that the latest composer is way ahead ;) is it possible to upgrade composer-redactor to the latest composer default?

**Comment by PostMidnight** [comment]
Upgraded manually to latest composer and it works thank you!
