### ISSUE TITLE
Ability to configure express-bodyparser 

### ISSUE THREAD

**Issue by greenhat616** [NodeBB/NodeBB#7760]
bodyparesr limit json, urlencoded 1MB defaultly. In some case, we need higher limit to support plugin api work. Now we must modify src/webserver.js to make it work. It has broken the auto update system.

**Comment by SDxBacon** [comment]
I am running into this problem too. In my case, it is quiet easy to reach the default limitation (100 KB) that parse-body defined while user trying to upload data to my server with graphql api. 

It will be great if it is possible to configure the option that applied to body-parse without modifying any file inside src folder :)

**Comment by barisusakli** [comment]
@greenhat616, @SDxBacon you can configure them with a config.json property now.
```
 "bodyParser": {
        "urlencoded": {
            "limit": "256kb"
        },
        "json": {
            "limit": "256kb"
        }
    },
```

The options are documented here https://github.com/expressjs/body-parser#bodyparserjsonoptions and https://www.npmjs.com/package/bytes#bytesparsestring%EF%BD%9Cnumber-value-number%EF%BD%9Cnull
