### ISSUE TITLE
Phone register/login/verification

### ISSUE THREAD

**Issue by greenhat616** [NodeBB/NodeBB#7761]
It's a neccessary feature, which is required in China. Chinese government announce a rule: need all people rel-name registered while they are posting a content. I have tried make a plugin,however, it's difficult.

**Comment by julianlam** [comment]
Hi there, can you reply back with information about this new ruling regarding online services in China v(in English, if possible)?

**Comment by greenhat616** [comment]
@julianlam the rule url is here: https://www.cac.gov.cn/2017-08/25/c_1121541842.htm

translated by Google:

The first is to regulate Internet follow-up commentary services, safeguard national security and public interests, and protect the legitimate rights and interests of citizens, legal persons and other organizations. According to the "Network Security Law of the People's Republic of China", the State Council on Authorizing the National Internet Information Office is responsible for Internet information content. The Notice of Management Work, which establishes these regulations.

    Article 2 The provision of post-referral services within the territory of the People's Republic of China shall comply with these Provisions.

    The post comment service referred to in these regulations refers to Internet sites, applications, interactive communication platforms, and other communication platforms that have the characteristics of news and public opinion and social mobilization functions. They serve users by posting, replying, leaving messages, and “barrage”. Provide services for publishing text, symbols, emoticons, pictures, audio and video information.

    Article 3 The National Internet Information Office is responsible for the supervision and management of the national comment service. The local Internet Information Office is responsible for the supervision and management of the post comment service in its administrative area.

    The Internet Information Offices at all levels shall establish and improve the supervision and management system that combines daily inspections and periodic inspections, and regulate the follow-up comment service activities of various communication platforms according to law.

    Article 4 If a commentary service provider provides a comment on a new product, a new application, or a new function related to the Internet news information service, it shall report it to the Internet Information Office of the state or province, autonomous region, or municipality directly under the Central Government for security assessment.

    Article 5 The commentary service provider shall strictly implement the main responsibility and perform the following obligations in accordance with the law:

    (1) According to the principle of “real name in the background and voluntary at the front desk”, the registered users shall be authenticated by the real identity information, and the users who do not authenticate the real identity information shall not be provided with the post comment service.

    (2) Establish and improve the user information protection system. The collection and use of personal information of users shall follow the principles of lawfulness, righteousness and necessity, publicly collect and use rules, expressly specify the purpose, manner and scope of the collection and use of information, and agree with the recipients. .

    (3) Where a commentary service is provided for news information, a system of pre-trial and post-issuance shall be established.

    (4) If the "barrage" method is used to provide follow-up service, the static version of the information content shall be provided on the same platform and page.

    (5) Establish and improve information security management systems such as review and management of post comments, real-time inspections, and emergency disposal, timely discover and dispose of illegal information, and report to relevant competent authorities.

    (6) Develop the security protection and management technology of post commentary information, innovate the management method of post comments, research and develop the use of anti-spam management system, improve the ability of spam disposal; timely discover the risks of security flaws and loopholes in the comment service. Take remedial measures and report to the relevant authorities.

    (7) Equipping an auditing and editing team that is compatible with the scale of services to improve the professional quality of auditing and editing personnel.

    (8) Cooperate with the relevant competent departments to carry out supervision and inspection according to law and provide necessary technical, data and data support.

    Article 6 The post comment service provider shall sign a service agreement with the registered user, clarify the service and management rules for the follow-up comments, fulfill the obligation of the relevant laws and regulations of the Internet, and conduct targeted online education.

    Users of the post comment service should be strict and self-disciplined, promise to abide by laws and regulations, respect public order and good customs, and must not publish information content prohibited by laws and regulations and relevant state regulations.

    Article 7 The commentary service providers and their employees shall not intervene in public opinion by selectively deleting and recommending comments on the basis of seeking improper interests or based on wrong value orientation.

    Post-review service providers and users must not use software, employ commercial organizations and personnel to disseminate information, interfere with the normal order of comments, and mislead public opinion.

    Article 8 If a commentary service provider publishes information content that violates laws and regulations and relevant state regulations, it shall promptly take measures such as warning, refusal to publish, delete information, restrict functions, suspend the update until the account is closed, and save relevant records.

    Article 9 The post comment service provider shall establish a user hierarchical management system, conduct credit evaluation on the user's post comment behavior, determine the service scope and function according to the credit rating, and blacklist the users who are seriously untrustworthy, and stop the column. Blacklisted users provide services and prohibit them from using the post review service by re-registering.

    The Internet Information Office of the State, the province, the autonomous region, and the municipality directly under the Central Government shall establish a credit file and blacklist management system for the follow-up comment service providers, and conduct regular credit evaluations for the post comment service providers.

    Article 10 The post comment service provider shall establish and improve the public complaint reporting system for illegal information, set up convenient complaint reporting and entry, and timely accept and dispose of public complaints and reports. The State and Local Internet Information Office shall supervise and inspect the implementation of the report in accordance with its duties.

    Article 11: The information security management responsibility of the post comment service provider is not in place. If there is a large security risk or a security incident occurs, the Internet information office of the state, province, autonomous region or municipality directly under the Central Government shall promptly interview; the post management service provider Measures should be taken as required to carry out rectification and eliminate hidden dangers.

    Article 12 If the Internet commentary service provider violates these regulations, the relevant departments shall handle it in accordance with relevant laws and regulations.

    Article 13 These Provisions shall come into force on October 1, 2017.

**Comment by greenhat616** [comment]
In other words, website offering the comment feature should require user real-name registered.
If user wasn't real-name registered, he will be forbidden to post a comment or a toptic.

Two common approaches to solving it:

* ID Card information verification: I'm not recommend it. Because the information will be Malicious used by criminals, if the data of website were exposed.
* Phone verification: It is a recommended way. Most of users in China will use phone number to log-in apps, websites. And the phone number isn't a valid identity document, which can be used to apply something without permission. What's more, The rule admitted the  real-name validation of the phone number

**Comment by julianlam** [comment]
Understood -- just keep in mind utilising a phone number to log in is not the way most North Americans log into systems. Another complication is the verification aspect requires use of a third-party phone system (e.g. Twilio), which is not a free service, therefore the site owner has to bear the cost of it.

This will ideally be feature implemented via a plugin, but is not high priority for us at the moment so it will need [sponsorship](mailto:sales@nodebb.org) before it can be completed.

**Comment by julianlam** [comment]
An additional complication to implementing login via phone number are the security concerns, as SIM spoofing has been a recent concern, leading to account hijacking even **with** the use of 2FA (this is why our 2factor plugin utilises TOTP, and not SMS-based OTP).
