### ISSUE TITLE
Deprecated features

### ISSUE THREAD

**Issue by SVNTY** [NodeBB/NodeBB#7764]
```hsts deprecated The "includeSubdomains" parameter is deprecated. Use "includeSubDomains" (with a capital D) instead. NodeBB-master/node_modules/helmet/index.js:33:28```

&&

```hsts deprecated The "setIf" parameter is deprecated. Refer to the documentation to see how to set the header conditionally. NodeBB-master/node_modules/helmet/index.js:33:28```

git HEAD

```NodeBB-master$ git rev-parse HEAD
166394415249a1c7daf46c13f09af7eafffd8fa3```


docker mongodb version


```NodeBB-master$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mongo               latest              a3639b2a0f13        3 weeks ago         412MB```

**Comment by pitaj** [comment]
Pretty sure this is fixed in latest master

#7722
