### ISSUE TITLE
Disable user to quit a group (permission) 

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/NodeBB#7770]
- **NodeBB version:** 1.12.2

From 
https://community.nodebb.org/topic/14111/disallow-user-to-quit-a-group :
It would be usable to add an option to disallow users to quit a group.

**Comment by julianlam** [comment]
@alfazaz Could you not use a hidden group in this case? I do not understand the rationale behind having a group that you can join but cannot leave.

Did you name your group "Hotel California"? :laughing:

**Comment by alfazaz** [comment]
@julianlam No Hotel California here ;-) ...

I use nodebb for the site of my class (I'm a teacher ...). My students are categorized in many groups, for example according to the year of their promotion or to their next highschool... For example, this year's students are in the "Promo 19-20" group and it's me, the administrator, who puts them there. I do not want them to leave the group (unless I remove them myself ...).

I do not want to hide these groups (promotions, highschools interact with each other etc...).

For the moment, I have hidden the possibility of leaving the group via the theme but it would be better to go through the privileges...

**Comment by julianlam** [comment]
Yes, that certainly makes sense. Just letting you know, however, that if we add this as a privilege, then it will be all or nothing across the board if you remove this privilege from `registered-users`, so not only class/promotion groups, but individual user groups created by your members, if any.

**Comment by barisusakli** [comment]
I think it makes more sense to make it a setting in the group.

**Comment by alfazaz** [comment]
Yes, it should be a privilege setting specific to each group.

**Comment by julianlam** [comment]
Makes sense, workin' on it ;)

**Comment by alfazaz** [comment]
Thanks for your work... Nodebb is already great and gets greater and greater :-)

**Comment by julianlam** [comment]
# :point_up: Breaking changes in the form of a new option for group administration on client-side.
