### ISSUE TITLE
[Feature Request] Speed up NBB by uglifing css classes

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7787]
Hi Devs,
Unless I have the incorrect settings, it looks like only JS files are uglified and minified, while the CSS classes are just minified. 
We might be able to reduce the css bundle size significantly having this feature turned on.
If this is supported, I wonder if you guys can share with us how to turn this feature on (or better, make this standard when compiling to production).
Thank you for your kind consideration!
JJ.

**Comment by pitaj** [comment]
Doing this would require not just mangling CSS classes in CSS files, but also in every template and JavaScript file that uses them. It's not something that's easily managed by an automatic process.

For instance, consider this JS code:
```
elem.addClass('every-' + interval);
```
where interval can be day, month, year, hour...

An automatic process of minification would have to detect that kind of usage in the first place, and then either mangle it or leave the possible CSS classes unmangled.

If our CSS was scoped into components in our UI then this wouldn't be nearly as hard but right now anything goes, so this request is simply not feasible.

**Comment by PostMidnight** [comment]
Indeed, dynamic classes poses a headache. Too bad it could have helped.
Thanks for the explanation @pitaj
