### ISSUE TITLE
Specific Moderation Group that doesn't receive flag notifications

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#7794]
I have a use case where we want a group that have Moderator privileges but don't receive Flagged Post/User notifications. Is there anyway to currently do this?

It appears that if a Group has Moderator privileges they'll receive flagged notifications. If there's no current way to do it could we add a filter hook in the Flags.notify function to filter the uids that the notification gets sent to?

https://github.com/NodeBB/NodeBB/blob/102d4b02477c6bf953781a7b0c1e96353b245e50/src/flags.js#L717

https://github.com/NodeBB/NodeBB/blob/102d4b02477c6bf953781a7b0c1e96353b245e50/src/flags.js#L754

**Comment by barisusakli** [comment]
You can turn off notifications for users in that group from their settings page.

![image](https://user-images.githubusercontent.com/2583394/61792516-ece69e00-adea-11e9-8ee0-7cd8571fa3f8.png)

**Comment by uplift** [comment]
Are you referring to this route '/user/:userslug/settings'?

**Comment by barisusakli** [comment]
Yes

**Comment by uplift** [comment]
Cheers. We have that page switched off but I'll look at putting a version back in. Thanks for the help!
