### ISSUE TITLE
Change Post/Topic Owner

### ISSUE THREAD

**Issue by LazDisco** [NodeBB/NodeBB#7795]
I think it would be a great feature addition to the mod tools if we mods/admins could change the ownership of topics and posts (if the post selected for a change in ownership is the OP then change the topic as well, kind of thing).

If you guys aren't willing to integrate it into core (I wouldn't blame you, seems like a lot of work), could I get some pointers on what I'd need to change in the database to achieve the desired effect?

**Comment by barisusakli** [comment]
This is added in latest https://github.com/NodeBB/NodeBB/pull/7752

**Comment by LazDisco** [comment]
Awesome, another feature inside of 1.13 that I cannot wait for! Love what you guys do. ❤️

**Comment by julianlam** [comment]
You might be waiting a little while for 1.13 since it is a version bump with a large amount of changes... but the latest master is _usually_ fairly stable.

That said, if it burns down your house, it's not our fault.
