### ISSUE TITLE
why not add official docker-compose.yml for users?

### ISSUE THREAD

**Issue by tabris233** [NodeBB/NodeBB#7801]
Users can easily build nodebb with docker-compose.yml.

Pull docker image from [hub.docker.com](hub.docker.com) will more convenient.

**Comment by pitaj** [comment]
None of the main devs use docker, an investing the time to learn it just to support this usage isn't seen as a priority. If somebody wants to add docker support and pledge to maintain it, then we'd love a pull request, but we don't know docker.

**Comment by Th3Whit3Wolf** [comment]
Is this still true? I see that you have an image on hub.docker.com and have a dockerfile?

It would be awesome to have documentation on using it via docker and docker-compose.

**Comment by tilllt** [comment]
Yes, i wondered that myself. There seems to be an official NodeBB docker image but i can find absolutely no documentation on how the image is configured, let alone a docker-compose.yml...

**Comment by mikesutton** [comment]
I'm going to try and put nodebb into production on a docker swarm.

Will contribute the docker-compose.yml when done.

**Comment by tilllt** [comment]
There is a childish hostility by some self proclaimed NodeBB advocates on the User Forum. So be aware that posting anything with the keyword "Docker" in it will trigger a shitstorm by a bunch of admins living in the past. Never experienced anything like that before, really weird.

**Comment by mikesutton** [comment]
Hmmm, thanks for the fair warning.

Will still do it but might not go on to forums. No time for BS chatter.

**Comment by psychobunny** [comment]
Hi, play nice :) I can go on the record and say that not a single person on the core NodeBB team has any issue with getting a proper docker setup going. I suppose it's just a matter of who would like to take charge of that ;D

**Comment by mikesutton** [comment]
:) always - I'll take a look at the current dockerfile, if I can improve
it, I will and I'll share the docker-compose.yml.

Is there a list of environment variables nodeBB needs that I can access
without too much research?

**Comment by fais3000** [comment]
@mikesutton I would also love to move Nodebb to a docker-compose setup, specifically for easier mongodb version upgrades. I'm a beginner at docker but I've bunch of servers running Nodebb in conventional VPS so let me try to answer with best of my knowledge.

Generally there are no OS level variables, most configurations are picked from two files.

1. config.json
2. package.json (package.json is dynamically created after the installation setup is complete)

So for docker .env we might just need to setup following.

```
{
    "url": "https://forum.example.com", // This is the host name where forum is hosted
    "secret": "63c2f418-1e6f-4bbf-23444-2323",
    "database": "mongo", // The other option here is redis
    "port": 4567,
    "mongo": { // Mongo specific stuff
        "host": "127.0.0.1",
        "port": "27017",
        "username": "nodebb",
        "password": "nodebb",
        "database": "nodebb"
    },
 "socket.io": {
    "origins": "https://forum.example.com:* http://public ip of host:*"
  }
}
```

For most part https://github.com/NodeBB/NodeBB/blob/master/docker-compose.yml seems to work. But as @tilllt pointed out, it misses the persistent/mapped volumes for configuration and database.

I found out that rocketchat has quite similar setup so we can use their docker-compose.yml as a reference.

https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml
