### ISSUE TITLE
Display Emojis in teaser (as unicode)

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7803]
Hi Devs,

I'd like to propose leaving out the emojis unicode in the teaser. I believe that doing so should not have an impact elsewhere but teaser display, but obviously that's for you to decide. 

To that end, please consider the below changes to /public/src/utils.js.

```
stripHTMLTags: function (str, tags) {
			var pattern = (tags || ['']).map(function (tag) {
				return utils.escapeRegexChars(tag);
			}).join('|');
			//return String(str).replace(new RegExp('<(\\/)?(' + (pattern || '[^\\s>]+') + ')(\\s+[^<>]*?)?\\s*(\\/)?>', 'gi'), '');
			//Allow Emoji unicode in teaser
			let content = String(str).replace(/(?:<img)(?:.+?\balt=\")([^\/"]*)(?:.+?\bclass=\")(?:.+?\bemoji [^\/"])(?:.+?\/>)/gi, "$1");
			return content.replace(new RegExp('<(\\/)?(' + (pattern || '[^\\s>]+') + ')(\\s+[^<>]*?)?\\s*(\\/)?>', 'gi'), '');
		},

```

**Comment by pitaj** [comment]
We're not going to add special cases for emoji in core. What we could accept though is a general function of replacing images with their alt attributes.

**Comment by PostMidnight** [comment]
Hi @pitaj 
Can this help?

replaceImgWithAlt: function (str) {
  return String(str).replace(/(?:<img)(?:.+?\balt=\")([^\/"]*)(?:.+?\/>)/gi, "$1");
}

**Comment by julianlam** [comment]
@pitaj I agree, a generic function to replace the image with the alt attribute is perfect, since that is exactly what it is meant to do.

**Comment by PostMidnight** [comment]
As proposed, give it a spin ;)
Kindly note - in the first proposed solution. I specifically looked for "emoji" class, to make sure conversion to ALT is made just for the emojis. We can change the 2nd solution to look for a class as well.
IMHO, having emojis in the teaser is really cool. I wonder (and this is just to feed my curiosity) if you are objecting to this notion. Specifically if there is a technical/security related issue I have neglected to consider.
