### ISSUE TITLE
custom mongodb/and apis

### ISSUE THREAD

**Issue by rozi98** [NodeBB/NodeBB#7807]
hi i have 2 prblem :

- **NodeBB version:**  **1.11.2**
git hash: `53af9ec2e806c25a2933ca8440e3f8d21e74bcd5`
- **Database type:** **mongodb**
 **Database version:** ~= 4
 i want nodebb use mywebsite userdb -
so  i create my website db and want connect nodebb  to it can u help me plz .
and i want use my theme for nodebb [its vuejs]  and i need  api ,t think nodebb-plugin-write-api can help me ,is'nt it?

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
