### ISSUE TITLE
[bug] Users which not login can not see image

### ISSUE THREAD

**Issue by jinfagang** [NodeBB/NodeBB#7810]
If not logined, image all can not show:

![image](https://user-images.githubusercontent.com/21303438/62182073-f1c9c580-b387-11e9-96a8-00c472d561c1.png)

When click:

![image](https://user-images.githubusercontent.com/21303438/62182080-f8f0d380-b387-11e9-8ef4-b95bef51022f.png)

Why visitors not register or login can not see image? Am I set something wrong?

**Comment by julianlam** [comment]
You have private user uploads enabled. Turn it off or update to latest.
