### ISSUE TITLE
uncaughtException: Callback was already called when editing message

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7811]
Hi Devs,

I am working on the quill plugin.
My system is plain vanilla nbb synced with master, with quill plugin attached.
The issue happens when I try to edit a post.

It seems that emitting 'plugins.composer.push' causes the server to default:

```
composer.editPost = function(pid) {
		socket.emit('plugins.composer.push', pid, function(err, threadData) {
			if (err) {
				return app.alertError(err.message);
			}
			threadData.action = 'posts.edit';
			threadData.pid = pid;
			threadData.modified = false;
			push(threadData);
		});
	};
```

The server seems to default right after the emit is acknowledged, that is immediatly after the following function (composer-default plugin, websockets.js) 

```
Sockets.push = function(socket, pid, callback) {
	var postData;
	async.waterfall([
		function (next) {
			privileges.posts.can('topics:read', pid, socket.uid, next);
		},
		function (canRead, next) {
			if (!canRead) {
				return next(new Error('[[error:no-privileges]]'));
			}
			posts.getPostFields(pid, ['content', 'tid', 'uid', 'handle'], next);
		},
		function (_postData, next) {
			postData = _postData;
			if (!postData && !postData.content) {
				return next(new Error('[[error:invalid-pid]]'));
			}
			async.parallel({
				topic: function(next) {
					topics.getTopicDataByPid(pid, next);
				},
				tags: function(next) {
					topics.getTopicTags(postData.tid, next);
				},
				isMain: function(next) {
					posts.isMain(pid, next);
				}
			}, next);
		},
		function (results, next) {
			if (!results.topic) {
				return next(new Error('[[error:no-topic]]'));
			}
			plugins.fireHook('filter:composer.push', {
				pid: pid,
				uid: postData.uid,
				handle: parseInt(meta.config.allowGuestHandles, 10) ? postData.handle : undefined,
				body: postData.content,
				title: results.topic.title,
				thumb: results.topic.thumb,
				tags: results.tags,
				isMain: results.isMain
			}, next);
		},
	], function(err, res) { 
              return callback(err, res);
           });
};

```

I traced the above function with a debugger. It seems to execute fine, and reaches to the callback properly.

Here is a trace:
2019-07-31T10:05:51.203Z [4567/18948] - verbose: [plugins/fireHook] filter:post.getFields
2019-07-31T10:05:52.803Z [4567/18948] - verbose: [plugins/fireHook] filter:post.getFields
2019-07-31T10:06:04.819Z [4567/18948] - verbose: [plugins/fireHook] filter:post.getFields
2019-07-31T10:06:04.821Z [4567/18948] - verbose: [plugins/fireHook] filter:post.getFields
2019-07-31T10:06:19.834Z [4567/18948] - verbose: [plugins/fireHook] filter:composer.push
2019-07-31T10:06:46.142Z [4567/18948] - verbose: [plugins/fireHook] filter:post.getFields
2019-07-31T10:07:34.296Z [4567/18948] - error: uncaughtException: Callback was already called.
Error: Callback was already called.
    at nodebb/node_modules/async/dist/async.js:320:36
    at Immediate._iteratee [as _onImmediate] (nodebb/node_modules/async/dist/async.js:1617:17)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)

Any guidance what to do next?
thanks!
JJ.

**Comment by PostMidnight** [comment]
Some updates.
I thought the issue was related to you guys promisifing the entire world, so I changed Sockets.push(). That did not help, so next I commented out plugins.firehook, and the server did not default and all is back to normal.

If we don't call firehook, any idea what will go wrong? 

Here is Sockets.push following my changes:

```
Sockets.push = async function(socket, pid, callback) {
	var postData;

	const [canRead] = await Promise.all([
		privileges.posts.can('topics:read', pid, socket.uid),
	]);

	if (!canRead) {
		return callback(new Error('[[error:no-privileges]]'));
	}

	const [_postData] = await Promise.all([
		posts.getPostFields(pid, ['content', 'tid', 'uid', 'handle']),
	]);

	postData = _postData;
	if (!postData && !postData.content) {
		return callback(new Error('[[error:invalid-pid]]'));
	}

	const [topic, tags, isMain] = await Promise.all([
		topics.getTopicDataByPid(pid),
		topics.getTopicTags(postData.tid),
		posts.isMain(pid),
	]);

	if (!topic) {
		return callback(new Error('[[error:no-topic]]'));
	}

	let res = {
		pid: pid,
		uid: postData.uid,
		handle: parseInt(meta.config.allowGuestHandles, 10) ? postData.handle : undefined,
		body: postData.content,
		title: topic.title,
		thumb: topic.thumb,
		tags: tags,
		isMain: isMain
	};

	/*
	const [res] = await Promise.all([
		plugins.fireHook('filter:composer.push', {
			pid: pid,
			uid: postData.uid,
			//handle: parseInt(meta.config.allowGuestHandles, 10) ? postData.handle : undefined,
			handle: tmp,
			body: postData.content,
			title: topic.title,
			thumb: topic.thumb,
			tags: tags,
			isMain: isMain
		}),
	]);
	 */

	return callback(null, res);
};

```

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-quill/commit/450e8a663be01aa8a426d13d63cdf3a7a0259fa4

**Comment by barisusakli** [comment]
Hooks should either use the callback style or return a promise not both.
