### ISSUE TITLE
Rename and enhance filter:composer.push

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7812]
Hi Devs,

[EDITED: Following comments made by @julianlam that we should re-use existing hook]

Quill has its own data structure called delta. Its basically a JSON string with text and attributes.
@julianlam added a field ('quillDelta') to the database in which the delta is saved along with the html content ('content') of a post, so as to maintain future compatibility with composer.
When we fetch data from the server, we need to get it in Quill format.

This issue was resolved in composer-default plugin with filter:composer.push hook (see websockets.js). Said hook is called in Socket.push at the end of the function, taking in a single search field. That would result with two calls to getPostFields, one for 'content' (as well as other fields), the other for 'quillDelta'.

A similar issue may be found in SocketPosts.getRawPost where 'content' is returned upon post reply/quote, although there a hook was not implemented.

To that end, we are proposing to rename the hook filter:composer.push to filter:composer.getcontent, and to use said hook in both Sockets.push and SocketPosts.getRawPost.

```
/src/socket.io/posts.js (replacing the call to posts.getPostFields with a hook):

SocketPosts.getRawPost = function (socket, pid, callback) {
        async.waterfall([
                function (next) {
                        privileges.posts.can('topics:read', pid, socket.uid, next);
                },
                function (canRead, next) {
                        if (!canRead) {
                                return next(new Error('[[error:no-privileges]]'));
                        }
                        //posts.getPostFields(pid, ['content', 'deleted'], next);
                        plugins.fireHook('filter:composer.getcontent', {
                            pid: pid,
                            fields: ['content', 'deleted']
                        }, next);
                },
                function (postData, next) {
                        if (postData.deleted) {
                                return next(new Error('[[error:no-post]]'));
                        }
                        next(null, postData.content);
                },
        ], callback);
};

nodebb-plugin-composer-default/websockets.js (replacing the call to posts.getPostFields with a hook):

Sockets.push = function(socket, pid, callback) {
        var postData;
        async.waterfall([
                function (next) {
                        privileges.posts.can('topics:read', pid, socket.uid, next);
                },
                function (canRead, next) {
                        if (!canRead) {
                                return next(new Error('[[error:no-privileges]]'));
                        }
                        //posts.getPostFields(pid, ['content', 'tid', 'uid', 'handle'], next);
                        plugins.fireHook('filter:composer.getcontent', {
                                pid: pid,
                                fields: ['content', 'tid', 'uid', 'handle']
                        }, next);
                },
                function (_postData, next) {
                        postData = _postData;
                        if (!postData && !postData.content) {
                                return next(new Error('[[error:invalid-pid]]'));
                        }
                        async.parallel({
                                topic: function(next) {
                                        topics.getTopicDataByPid(pid, next);
                                },
                                tags: function(next) {
                                        topics.getTopicTags(postData.tid, next);
                                },
                                isMain: function(next) {
                                        posts.isMain(pid, next);
                                }
                        }, next);
                },
                function (results, next) {
                        if (!results.topic) {
                                return next(new Error('[[error:no-topic]]'));
                        } else
                          return next(null, {
                                pid: pid,
                                uid: postData.uid,
                                handle: parseInt(meta.config.allowGuestHandles, 10) ? postData.handle : undefined,
                                body: postData.content,
                                title: results.topic.title,
                                thumb: results.topic.thumb,
                                tags: results.tags,
                                isMain: results.isMain
                        });
                },
        ], callback);
};

```

Composer and redactor will need to implement the hook, but its very basic:

```
plugin,json:
{ "hook": "filter:composer.getcontent", "method": "getContent" }

library.js:
plugin.getContent= (data, callback) => {
	posts.getPostFields(data.pid, data.fields, callback);
}


```

**Comment by pitaj** [comment]
You could make it backwards compatible by leaving the getPostFields call and passing the postData result into the hook.

**Comment by PostMidnight** [comment]
Hi @pitaj I edited the code following @julianlam 's remarks, see above. I hope it is acceptable. Comments are welcome.

**Comment by julianlam** [comment]
What is the reasoning behind you asking for this change, that Quill doesn't handle quotes properly because it can only retrieve the raw html and not the delta?

**Comment by julianlam** [comment]
I also do not understand your rationale in removing `filter:composer.push`, since it would break any existing plugins that rely on that hook at the moment.

**Comment by PostMidnight** [comment]
> What is the reasoning behind you asking for this change, that Quill doesn't handle quotes properly because it can only retrieve the raw html and not the delta?

If we get the html data in the client, we will have to feed it to quill - thereby converting html->delta. When we save a message, delta will get converted to html. Each time a conversion is made, cpu cycles are spent, and worse, items gets lost in the way. A good example is direction in RTL, some formatting I noticed, and potentially other items that will get lost but I cannot say what currently. Sticking with delta without the conversion will insure long term stability of the post.

**Comment by julianlam** [comment]
Yes, of course, and I'm seeing that Quill only gets the HTML. I just think there may be a better way to fix this...

**Comment by PostMidnight** [comment]
> I also do not understand your rationale in removing `filter:composer.push`, since it would break any existing plugins that rely on that hook at the moment.

Perhaps I misunderstood, I thought you wanted to re-use existing hook. I believe the only plugin that utilizes this hook is composer and redactor. AFAIK there are no other editors. Am I wrong?

Anyway, no harm done, I can revert the changes back and double up on the hook. No worries I am not married to composer.getcontent. LMK.

**Comment by PostMidnight** [comment]
> Yes, of course, and I'm seeing that Quill only gets the HTML. I just think there may be a better way to fix this...

There are several factors in favor of the proposed solution: First, we are fetching delta or html but not both. Furthermore, we are also saving cycles on conversion. The client code is not changing - (try replying to a message or quoting it - works perfectly). Lastly, we have a stable environment in which posts are not altered if quoted or edited.
