### ISSUE TITLE
[Enhancement] Groups Name and ID

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7822]
Hi Devs,

I believe it may be beneficial to support groups GIDs, so that when search is performed for groups, it is executed on integers rather than text.

Furthermore, at times, it is challenging to name a group in RTL language. The challenge is more on the plugin side having to read  and compare non-English letters, and lastly on the display side.

It might be useful to add a new "display" field to groups. Such field may be used by mention plugin and others, while the actual group name (that is used by the core) will contain English letters only.

For your consideration, thanks!
JJ.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7228
