### ISSUE TITLE
chat-full: composer does not have uuid

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7829]
Just noted that under the .chat-full page, the composer does not have a dataset with uuid.
I challenged composer a bit (opened multiple chat-modals overlaid over the .chat-full page), but all modals worked fine. So this is most likely a non-issue, but I am raising the flag just in case.
Have a good weekend!

**Comment by julianlam** [comment]
Hi @PostMidnight -- this is intentional, as the full chat page does not use the taskbar UUID system (of which `data-uuid` is part of). It is used in the chat modals and composer windows as they are minimizable in the taskbar.
