### ISSUE TITLE
I can't see my badge as admin

### ISSUE THREAD

**Issue by FETE-CH** [NodeBB/NodeBB#7833]
- **NodeBB version:** 
1.12.2
- **NodeBB git hash:** 

- **Database type:** mongo, redis, or postgres
mongo
- **Database version:** 
4.0.11

- **Exact steps to cause this issue:**

- **What you expected:**
I just want to see my badge.
- **What happened instead:**
I can't see my badge as admin,I don't know if it's a bug or if I set up a problem.

![image](https://user-images.githubusercontent.com/31503794/62921007-00799900-bdda-11e9-95bd-21f587948a56.png)
![image](https://user-images.githubusercontent.com/31503794/62921158-7251e280-bdda-11e9-9b0a-80ad733c77ce.png)

**Comment by FETE-CH** [comment]
我发现这确实是一个 bug，而且更糟糕的是现在只能显示一个徽章，不管我有没有开启『Allow Multiple Badges』!显示的徽章是加入的第一个的群组的徽章，如果加入其它群组后退出第一个群组，也就不能显示徽章了。

I found out that this is indeed an bug, and, worse, only one badge can be displayed now, whether or not I turn on "Allow Multiple Badges"! The badge displayed is the badge of the first group you joined, and if you quit the first group after joining another group, you cannot display the badge.

**Comment by barisusakli** [comment]
Did you select which badges to display in the user profile settings?

**Comment by FETE-CH** [comment]
> Did you select which badges to display in the user profile settings?

哦，非常不好意思！这个设置太不显眼了，以至于我刚刚才发现它。选中正确的徽章后确实可以正常显示了，非常感谢，可以关闭这个issue了。非常感谢！

Oh, I'm so sorry! This setting is so inconspicuous that I just found it. After selecting the correct badge, it can be displayed normally. Thank you very much. You can turn off this issue.Thank you very much!
