### ISSUE TITLE
Clear number of characters

### ISSUE THREAD

**Issue by mqliutie** [NodeBB/NodeBB#7840]
- **NodeBB version:** 
1.12.2
- **NodeBB git hash:** 

- **Database type:** redis
- **Database version:** 

- **Exact steps to cause this issue:**

Create tag, I input "转载" it shows error **Please enter a longer tag. Tags should contain at least %1 character(s)**. 

 I want to know how many characters is required
- **What you expected:**

Show me clear number
- **What happened instead:**

**Comment by barisusakli** [comment]
What is your minimum tag length setting at /admin/settings/tags? I get this when I try the same tag with min length 3.

![image](https://user-images.githubusercontent.com/2583394/63020572-7b8b8f80-be6c-11e9-8a06-18e9f0191ea0.png)

**Comment by mqliutie** [comment]
The min length was set by default. I didn't update it.
But the length shows correct on the docker after deploy. 
So, closed
