### ISSUE TITLE
Chat message: modules:chat.system.false

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7847]
Hi Devs,
I noticed that upon username change, the chat window is amended with " modules:chat.system.false". There is no translation string for it. 
I can eliminate it with css probably, but just wanted to make sure its not there in error.
JJ.

**Comment by barisusakli** [comment]
Can you share a screenshot?

**Comment by PostMidnight** [comment]
Yes, will do, just saw this I'll boot a clean system tomorrow and do it. I suspect it has something to do with quill. 
If I recall my previous trial correctly, I traced the issue to: system-message.tpl
It seems that when the username is changed, the system issues a message with messages.content = false.

```
<li component="chat/system-message" class="system-message clear" data-index="{messages.index}" data-mid="{messages.messageId}" data-uid="{messages.fromuid}" data-self="{messages.self}" data-break="0" data-timestamp="{messages.timestamp}">
	[[modules:chat.system.{messages.content}, {messages.fromUser.username}]]
</li>
```

**Comment by PostMidnight** [comment]
Image attached. plain nodebb + quill.
Note the format is RTL, that's why the translation is shown as '', modules:chat.system.false

It happens when a username is changed or 

![image](https://user-images.githubusercontent.com/43993784/63415345-4a7c0380-c406-11e9-801c-9a96c392cf21.png)

**Comment by barisusakli** [comment]
@julianlam I don't see any system messages for username changes, I think this might happen if the user account you were chatting with was deleted.

**Comment by PostMidnight** [comment]
Thanks @barisusakli , to that end, may I suggest that messages with false should not be rendered?

**Comment by julianlam** [comment]
Thanks, looks like a simple fix :smile:

**Comment by julianlam** [comment]
b945937

**Comment by PostMidnight** [comment]
Hi @julianlam 
sorry, but the issue is not over yet ;)
I am still getting "A Former User '' left the group on the chat window. The '' is empty - that is no name is attached to it. 
It happens when a user is removed (deleted). The group that had that user is getting this empty system message. So either a name should be added or perhaps remove this message all together?

**Comment by julianlam** [comment]
When a user is deleted we no longer have their username. That's why we use "a former user".

**Comment by PostMidnight** [comment]
In that regards, the message "A Former User '' left the group on the chat window" is not informative to the other users. Perhaps it should be omitted?
