### ISSUE TITLE
textcomplete iphone support

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7854]
textcomplete is not a core library, so I am leaving the below comments for all users who experience issue with safari.

Referencing PR https://github.com/NodeBB/NodeBB/pull/7818

This issue was previously discussed in https://github.com/NodeBB/NodeBB/issues/7457 but changes:
julianlam/nodebb-plugin-markdown#105
julianlam/nodebb-plugin-markdown#107
did not resolve the issue at hand.

Safari support requires changes in textcomplete.contenteditable as mentioned here:
(yuku/textcomplete.contenteditable#3)

Just make the changes related to Safari, leave out the HTML support.

**Comment by julianlam** [comment]
Thanks @PostMidnight -- keep in mind this is only really an issue with Quill, since default composer does not use contenteditable.
