### ISSUE TITLE
build script stuck

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7874]
Hi Devs,
Just updated to latest master. It seems that the build script is stuck. The last message I get is:

 - info: [build]         client side styles

Then (after some time) the job gets killed.
Is there anything we should do with the .less or .tpl files of the plugins, given that less was updated?
thanks!
JJ.

**Comment by barisusakli** [comment]
Could be related to the recent less 3.x upgrade try downgrading less and see if it works.

**Comment by PostMidnight** [comment]
Thanks @barisusakli still no solution. Is there any way to know which file is faulty? any way to debug the build process or get some log data?

**Comment by barisusakli** [comment]
Are you using a custom theme? Try with persona and see if the issue is resolved. It's hard to tell which file is causing it without any error messages.

**Comment by PostMidnight** [comment]
Hi I am using persona  + quill. 
Here's what I did: tried building in serial mode, (-s) and build completed, however running failed.
Downgraded to less 2.7.2 and everything works. 
Is there anything I should pay attention to wrt less? anything I should be converting?

**Comment by barisusakli** [comment]
So build works in serial mode but starting up nodebb fails? Any error messages when starting?

**Comment by PostMidnight** [comment]
Its interesting. I upgraded less to 3.10.3 (from 2.7.2)
./nodebb build -s completes (after a long time wait in "templates  build started"
Then running in production mode: 
 export "NODE_ENV=production" && node --inspect=9230 app.js now works fine.

So I removed build -s: and the job gets killed again.

**Comment by barisusakli** [comment]
You probably don't have enough memory if build is failing in parallel mode.

**Comment by PostMidnight** [comment]
ouch, ok, I'll look into this.

**Comment by PostMidnight** [comment]
Made several runs: When build is launched, cpu is at 100%, and memory maxes out at 78%, Then the job either gets killed or the cpu drops to 1.5% and the job runs forever.

With 2.7.2 working every time,  and given the above, the issue might be related to something else. Perhaps new less configuration parameters.

**Comment by barisusakli** [comment]
Maybe you can check your syslog to see if the process is killed should be at /var/log/syslog on ubuntu.

**Comment by PostMidnight** [comment]
Thanks I did (see my comment above). Indeed I had a memory issue and that was resolved with a swapfile.
