### ISSUE TITLE
Access to /user/username times out

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7884]
Can be reproduced on latest master.
Access to any users home page times out.
Can you please try on your end and let me know if you see the same?

**Comment by barisusakli** [comment]
Works fine her https://community.nodebb.org/user/baris.

**Comment by PostMidnight** [comment]
Ok thanks I'll debug and report back.

**Comment by PostMidnight** [comment]
Totally my fault (and totally unrelated to profile ;) ). Thanks!
