### ISSUE TITLE
Guests are always getting the "Log in to view" link, despite "Make uploaded files private" being disabled

### ISSUE THREAD

**Issue by deepv1** [NodeBB/NodeBB#7893]
This is related to feature #7423 .

It appears that the handlePrivateUploads function in forum/topic/posts doesn't actually check if "Make uploaded files private" is true or not.  This manifests with all unauthenticated users always getting the the "Log in to view" link for images, even if the setting is off.

**Comment by barisusakli** [comment]
@deepv1 thanks for reporting

**Comment by deepv1** [comment]
Impressive how fast you made that change.  I tested it out, and while it's now showing for unauthenticated users, I think it's always showing.   I assume ajaxify.data.privateUploads is always coming back null

**Comment by barisusakli** [comment]
You can check the value of privateUploads in your browser console, it should be true or false. 
![image](https://user-images.githubusercontent.com/2583394/64663862-29ae3900-d41b-11e9-84a7-466e67e1967d.png)

**Comment by deepv1** [comment]
Ah, you're right.  Must've had my settings cached.  It's working now, thanks!
