### ISSUE TITLE
Privileges - ACP 

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7897]
Hi Devs,
Is it possible to create "wired-and" privilege using the ACP?
Let me try to explain: Say there are two groups A and B, by wired-and I mean that access is granted iff both groups are granted said access. 
Currently if one group is granted access than access is granted (wired-or).
I hope I make sense ;)
JJ.

**Comment by pitaj** [comment]
You could have two different privileges, A and B, give one to one group and one to the other. Then in your plugin check if a user has both privileges.

I think this is highly unlikely to every be a thing in NodeBB.

And specific reason you don't just create a third group?

**Comment by PostMidnight** [comment]
Hi @pitaj , I am trying to reduce the number of groups, it requires management.
Its easier to say, if A AND B then grant, then to create a subset group. 

Checking the priv in the plugin is a great idea thank you. Might I ask for some reference?
