### ISSUE TITLE
[Enhancement] Add wildcards to privileges

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7903]
It might help adding wildcards to privileges.
Example: wiping out all privileges for a given category:

`await privileges.categories.rescind('*', category.cid, '*');
`

If there is a way to do the same with the current code, I'd love to know how. 
Thank you.

**Comment by julianlam** [comment]
I feel this adds complexity to the function for something that is not used in core. Typically we do not do this.

Best bet would be for you to iterate through `privileges.userPrivilegeList` (which contains all of the privileges), or just delete the entries from the database directly.

**Comment by PostMidnight** [comment]
OK thank you.
