### ISSUE TITLE
Forum template is broken

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#7907]
- **NodeBB version:** 1.12.2
- **NodeBB git hash:** b110aec6ed73582bcaabce3f12479b6aaa3064a3
- **Database type:** mongo
- **Database version:** 4.0.11

Hi, when users log in to their accounts, forum template is completely broken and all things are messed up. But when user doesn't log in, it works normally. All users have this problem. Tested with all browsers, nothing changed.
![20190918_152321](https://user-images.githubusercontent.com/31972226/65142692-85cf1980-da28-11e9-8829-044425b92628.gif)

Also we have this warning / error that might be relevant to this problem 👇 

![image](https://user-images.githubusercontent.com/31972226/65142757-ab5c2300-da28-11e9-9f55-7065a7156fee.png)

**Comment by mohammadhassan99** [comment]
https://github.com/NodeBB/NodeBB/issues/7919

**Comment by PatheticMustan** [comment]
In console, can you run
```
./nodebb build
./nodebb log
```
?

The log might contain useful information.

**Comment by julianlam** [comment]
Disable all plugins and re-enable one by one, figure out which one is the problematic one. This is not a NodeBB issue as far as I can tell.

**Comment by mohammadhassan99** [comment]
@julianlam Took all steps but nothing changed. Our community doesn't start with ./nodebb start. It runs by ./nodebb dev .

**Comment by pitaj** [comment]
Don't run your community with `./nodebb dev`. It disables security features! for development proposes
