### ISSUE TITLE
Color bugs in Dark Mode

### ISSUE THREAD

**Issue by ghost** [NodeBB/NodeBB#7908]
- **NodeBB version: 1.12.1** 
- **NodeBB git hash: 22db818eb40f04e528d95257c5517ded8341493d** 

- **Database type:** redis
- **Database version: Redis server v=5.0.5 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=622e52eb03461839**

I use the dark-mode plugin nodebb-plugin-night-mode which relies on default NodeBB skins.
However some buttons appear white as reported here:

https://community.nodebb.org/topic/14112/color-bugs-in-dark-mode

We need someone to check the standard NodeBB skins and check them in dark mode, usually some buttons appear white in some sections.

**Comment by barisusakli** [comment]
https://github.com/psychobunny/nodebb-plugin-night-mode/issues/2
