### ISSUE TITLE
two idle connections were not released

### ISSUE THREAD

**Issue by luiz-simples** [NodeBB/NodeBB#7910]
- **NodeBB version:** 1.12.2
- **NodeBB git hash:** f76d35b

- **Database type:** postgres
- **Database version:** 10.7

- **Exact steps to cause this issue:**
	1. Just run server

- **What you expected:**
I expected 0 connections *or* after few seconds I expected that all connections should released.

- **What happened instead:**
I set the aws serverless as database of NodeBB.
I want to pay just when someone to use, but, NodeBB always keep two active connections.

Can someone help me?

Tks

**Comment by luiz-simples** [comment]
![Captura de Tela_selecionar área_20190919181121](https://user-images.githubusercontent.com/1550859/65285540-c69f5f00-db0a-11e9-917c-117087428790.png)

**Comment by barisusakli** [comment]
This is just the way nodebb works, we connect to the database on app startup and re-use the same connection instead of connecting for each request.

**Comment by luiz-simples** [comment]
Tks @barisusakli 
It is incompatible on the way serverless database.
