### ISSUE TITLE
Skip cropper/resizer  on gifs

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#7920]
Unless there are security issues I am unaware of, it is probably okay to skip the cropper directly when uploading a GIF for use as an avatar, etc.

The downside, of course, is that you might have a massive gif :confused: 

But since jimp doesn't support gifs and probably won't, it might make sense to bypass the cropper/resizer for now.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/9a7560049a33e7586faa14942c06c0705d06ce6f
