### ISSUE TITLE
changing skins and building causes error

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#7929]
- **NodeBB version:** 1.12.2
- **NodeBB git hash:** b110aec6ed73582bcaabce3f12479b6aaa3064a3
- **Database type:** mongo
- **Database version:** 4.0.11

![image](https://user-images.githubusercontent.com/31972226/65780410-89644e00-e156-11e9-8720-5be46950f2af.png)

**Comment by pitaj** [comment]
What theme are you using? It looks like you have some invalid less styling.

**Comment by mohammadhassan99** [comment]
@pitaj Persona Theme
Simplex Skin
What do we do? How can we detect them?

**Comment by pitaj** [comment]
Try disabling all plugins and trying it again. If it builds successfully, then enable plugins one by one until it fails, and you'll know which one is responsible.

**Comment by mohammadhassan99** [comment]
@pitaj They are all tested and they have nothing to do with it. Problem is something else.

**Comment by barisusakli** [comment]
https://github.com/thomaspark/bootswatch/pull/916
