### ISSUE TITLE
Potential issue with src/topics/sorted.js

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7934]
Hi @barisusakli 

I might be mistaken, but i believe the IFstatement at the beginning of sortTids should return the tids, as follows:

```
async function sortTids(tids, params) {
		if (params.term === 'alltime' && !params.cids && params.filter !== 'watched' && !params.floatPinned) {
			return tids;
		}
```

Otherwise the subsequent call: data.tids = await filterTids(data.tids.slice(0, 200), params) will fail (data.tids is undefined).

Thanks,
JJ.

**Comment by barisusakli** [comment]
@PostMidnight thanks good catch
