### ISSUE TITLE
number of group members shows incorrect numbers

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#7958]
Here are the details:
https://community.nodebb.org/topic/14285/number-of-group-members

**Comment by AliCihan** [comment]
Can I post screenshots? Or you mean other kind of settings?

**Comment by barisusakli** [comment]
Yeah screenshot of the rewards admin page should be enough. I am assuming rewards are the only way the members are added to these groups?

**Comment by AliCihan** [comment]
Yes, for these 5 groups (we have groups from 1 to 5 stars) only way to add is through rewards system. There is "admin" addition in each one since it is the creator user. 

Also, I want to mention yesterday one member passed 500 posts limit and assigned to the 1st group, the number of members in the first group become "-7" from "-10", I think this clue might help what is going wrong. You can see the final view from our forum page. 

Sorry for the long post, I marked the screenshots with numbers on the bottom right, none of the groups look twice on the screenshots, I took screenshots accordingly... however you might see some duplicates. As I was mentioning on the forum post, nodeBB duplicated them when we have created them first, not us. We have deleted some of the duplicates but did not care for all since the order was changing each time there is a change (addition or deletion) on the page, so we stop caring since it was functioning. Addition or deletion of new reward rule might duplicate any rule, but I guess it was mostly newly added one ,so there is clearly something not right with our reward rule page.


![Screen Shot 2019-10-10 at 4 49 18 PM](https://user-images.githubusercontent.com/52054408/66605899-f88e6900-eb7e-11e9-9aae-826d0f8981fe.png)
![Screen Shot 2019-10-10 at 4 49 40 PM](https://user-images.githubusercontent.com/52054408/66605900-f88e6900-eb7e-11e9-915d-083366b42ed6.png)
![Screen Shot 2019-10-10 at 4 49 53 PM](https://user-images.githubusercontent.com/52054408/66605901-f88e6900-eb7e-11e9-83df-dfb350b1c645.png)
![Screen Shot 2019-10-10 at 4 50 08 PM](https://user-images.githubusercontent.com/52054408/66605902-f88e6900-eb7e-11e9-9e30-83ceb566a70a.png)
![Screen Shot 2019-10-10 at 4 50 21 PM](https://user-images.githubusercontent.com/52054408/66605903-f926ff80-eb7e-11e9-899c-92f105f939fb.png)
![Screen Shot 2019-10-10 at 4 50 33 PM](https://user-images.githubusercontent.com/52054408/66605904-f926ff80-eb7e-11e9-8973-575ac9113472.png)
![Screen Shot 2019-10-10 at 4 50 47 PM](https://user-images.githubusercontent.com/52054408/66605905-f926ff80-eb7e-11e9-9468-48b641d6cffc.png)

**Comment by barisusakli** [comment]
Can you also go to forum.com/api/admin/extend/rewards?pretty=1 and upload that output. If there are two identical rewards that remove the user from group A those might get executed at the same time and mess with the group membership count.

**Comment by barisusakli** [comment]
I will post instructions to fix the counts in the forum thread. This issue was happening becaues of duplicate rewards all removing the user from the same group.

**Comment by AliCihan** [comment]
Hi @barisusakli , in 1.13.2 some of the groups are still showing negative number member count. FYI.
