### ISSUE TITLE
[Enhancement] Slugify username in @mentions

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7959]
Issue relates to latest version.
Posting here as this relates to all users.

Lets assume users have the following userslugs
A Z1
A Z2
A Z3...
...
A Z1000 

Lets assume someone is trying to mention @A Z800,
Since textcomplete has limited (10 users) selection box, and since the selection box will be removed if the user entered space, selecting A Z800 will not be possible.
Slugifing the username will allow the user to enter "A-Z80" and then complete using the selection box.

**Comment by julianlam** [comment]
The usernames displayed in the textcomplete block show the user **name**, and not the slug, because the slug is not something an end user can derive with 100% accuracy on their own.

It is important to show the actual user name even if the end result is the user slug.

**Comment by PostMidnight** [comment]
Hi @julianlam 
I guess I explained the issue improperly.
I was trying to suggest that to add "-" where there is a space character, so that completion will work when there are multiple words separated by space in the mention window.
I called it slugify cause that's the function you guys use in your code.
Kindly consider.
thank you.
