### ISSUE TITLE
npm upgrade stuck: bootswatch

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7967]
The following line in package.json causes the freeze:

`
"bootswatch": "git://github.com/thomaspark/bootswatch.git#c41a8f066feb8950c6f9c6bcf5a3c37d1085404e",
`

Can you please revert to previous version where it had: 

`
"bootswatch": "^3",
`

Thank you!
JJ.

**Comment by barisusakli** [comment]
I can but then skins will stop working. https://github.com/thomaspark/bootswatch/pull/916

**Comment by PostMidnight** [comment]
ouch: any pull request will freeze.

How about moving the content of git://github.com/thomaspark/bootswatch.git#c41a8f066feb8950c6f9c6bcf5a3c37d1085404e into a local file and then copy into the library?

**Comment by pitaj** [comment]
Why is this causing a freeze? How did you come to that conclusion? What does the freeze even look like?

**Comment by PostMidnight** [comment]
npm freezes on update. With verbose turned on, I was able to identify the problematic package. It can't resolve the address as provided in the committed file.

**Comment by PostMidnight** [comment]
Anyone that has this issue:
Force clear npm cache, remove node_modules and package lock.
Checkout version just before the bootswatch, run ./nodebb upgrade.
Then pull the latest code. For some reason, the latest pull will not update the package.json, thus you'll be able to build your code with the latest master.

**Comment by pitaj** [comment]
`git pull` does not update `package.json`, it updates `install/package.json` and `./nodebb upgrade` merges that file in

**Comment by PostMidnight** [comment]
Ouch, that means I'll hit the very same roadblock shortly.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/8527
