### ISSUE TITLE
html widget box and cover photo on profile page overlaps 

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#7969]
We have two html widgets on top of the page, however on profile page the cover photo overlaps with html widget boxes and masks it. 

The situation is the same for mobile and for desktop. Sometimes when you change screen size you can see bottom of the lower widget box. 

FYI.

**Comment by AliCihan** [comment]
Problem continues... 

Here are some screenshots... here is how it should look (separate boxes)
![98294110_203066454015437_7133047097825165312_n](https://user-images.githubusercontent.com/52054408/82842851-1fe53c80-9ea9-11ea-8286-018a00190947.jpg)

here is how it looks (both boxes stays below cover picture and there is a large space under profil pic):

![100764440_248839799715062_2993673105315987456_n](https://user-images.githubusercontent.com/52054408/82842981-89fde180-9ea9-11ea-9e31-80e5e473da4b.jpg)

**Comment by barisusakli** [comment]
Let me know if you notice any side effects from this change, I suck at css so anything can happen

**Comment by barisusakli** [comment]
Reverting my changes since it breaks the profile
![image](https://user-images.githubusercontent.com/2583394/83184570-a42cff00-a0f7-11ea-9c66-5277693369ba.png)

**Comment by AliCihan** [comment]
sure, no problem... I think I got the idea, so I will try to add custom CSS to fix the look in our forum... You can close the issue if you want.
