### ISSUE TITLE
Initial chat load should not load all messages

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#7970]
Hi All,
Is there a way to purge a chat room without deleting it?
The reason is that in the absence of infinite scroll, chat rooms history takes very long time to load. 
I'd like to just purge the history from time to time.
Thank you!
JJ.

**Comment by julianlam** [comment]
What is the rationale, that chat loads slowly due to many messages?

**Comment by PostMidnight** [comment]
Yes that's the rationale.

**Comment by julianlam** [comment]
In that case, the underlying issue is that chat loads all messages currently, when it should only load the latest 20 or so

**Comment by pitaj** [comment]
Yeah we should load the first few, with a button at the top of the history after you scroll up that you can click to load the rest.

**Comment by julianlam** [comment]
Didn't we have this before? I swear there used to be buttons at the top to load past 7 days, 30 days, forever, etc...

**Comment by pitaj** [comment]
Yeah I believe those were removed in the UI refactor. They were pretty clunky.

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/66943741-cca93280-f019-11e9-92c6-d69dc29d346d.png)

chat page loads the last 50 messages and loads more as you scroll up

**Comment by julianlam** [comment]
:+1: IS is ideal here, so not entirely sure what the issue here is @PostMidnight

**Comment by PostMidnight** [comment]
Interesting, I am pretty sure more than 50messages are loaded. I don't know why, yet. I'll come up with a way to reproduce it, or I'll eat my tail. Thank you for looking into this.

**Comment by barisusakli** [comment]
Closing this, maybe open an issue on quill
