### ISSUE TITLE
dont show `x` button on chat page

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#7977]

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/66944216-bf407800-f01a-11e9-8866-25f0f19384a8.png)

Looks like this is just terrible UX, I thought `x` was supposed to leave chat, it only closes the chat window and changes the url to `https://community.nodebb.org/user/baris/chats/undefined`, refreshing page just goes to 404. The actual leave chat in the dropdown works. Not sure why the `x` is there.

**Comment by julianlam** [comment]
Hm. Technically it should go to `/chats`, not `/chats/undefined`. Then the 404 issue is resolved.

The x closes the window, that's all.
