### ISSUE TITLE
Themes can not be used when coming from a scoped npm org

### ISSUE THREAD

**Issue by fbatschi** [NodeBB/NodeBB#7983]
-  **nodebb version:**  1.12.2
-  **git hash:** 22db818eb40f04e528d95257c5517ded8341493d

- **Database type:** mongo
- **Database version:** 4.2.0

- **Exact steps to cause this issue:**

  1.  put a theme from a scoped npm org like `@bytepark/nodebb-theme-hyper` into package.json 
  2. do a `nodebb upgrade`. The package gets downloaded to node_modules/@bytepark/nodebb-theme-hyper
  3. Go to the ACP , you see the theme in the list of themes (although the first problem is, that the screenshot is not shown as it searches for /css/previews/nodebb-theme-hyper).
  4. When you then try to use the theme in the Theme panel you receive an error saying
```no such file or directory, open '/usr/src/app/node_modules/nodebb-theme-hyper/theme.json'``` 
which is correct, as the theme.json is actually in `/usr/src/app/node_modules/@bytepark/nodebb-theme-hyper/theme.json`

- So nodebb does not take into account the @ scope of the theme at this moment and looks in the wrong path (although the id in theme.json is defined as `@bytepark/nodebb-theme-hyper`).

- **What you expected:**
I should be able to use themes coming from a scoped org in npm

**Comment by rhessinger** [comment]
I'm seeing the same problem with my extensions (not theme based).  Any update on this?

**Comment by pitaj** [comment]
Scoped plugins should work, but may not show up in the plugin list. What exact issues have you seen trying to use scoped plugins? Inability to activate? Doesn't work after activation?

**Comment by rhessinger** [comment]
I recently changed an existing plugin to be a scope package, but now it fails to read my plugin.json.

**Comment by pitaj** [comment]
Can you tell me exactly what your plugin is named, including the scope? It may be possible a match regex wrongfully excludes your otherwise valid package. If you don't want to share here, you can email me or message me on https://community.nodebb.org

**Comment by pitaj** [comment]
Some changes were made in https://github.com/NodeBB/NodeBB/commit/1aa336d83740d182f117f763ea7936ab2ed2a98b that may fix your problem. Could you try latest master and see if that works?

If not, I'll look more into this in a week or two.

**Comment by rhessinger** [comment]
Hi @pitaj,

Was that for the theme thing, or do you think that will help out my issue as well?  I did send you an email with that information, not sure if you got it.

**Comment by pitaj** [comment]
The changes I made affected both plugins and themes, so please try it and see. I see your email now, it got sent to spam. I'll see if I can reproduce the issue.

**Comment by fbatschi** [comment]
Current master seems to have fixed the problem of using a theme from a scoped org for me.
