### ISSUE TITLE
Nodebb Write API returns current user in room.users

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#7987]
When using Nodebb Write API the current user is returned in the users array due to the uid not being parsed into an Int when comparing.

https://github.com/NodeBB/NodeBB/blob/500ca6658eb8e41838487fa69905846ddd7e8db3/src/messaging/rooms.js#L227

PR: https://github.com/NodeBB/NodeBB/pull/7988

**Comment by julianlam** [comment]
#7988
