### ISSUE TITLE
Creating new user (via invite) fails in IE11

### ISSUE THREAD

**Issue by mattmyne** [NodeBB/NodeBB#7996]
- **NodeBB version:** 1.12.2
- **Database type:** mongo
- **Database version:** 4.2.0
- **Exact steps to cause this issue:**
  - Send invite to e-mail address via users page
  - Following link using IE11
- **What you expected:**
  - IE11 displays the new user page with new username and password entry boxes etc.
  - Upon pressing submit, the user should proceed to the data protection/confirmation page
- **What happened instead:**
  - IE11 displays the new user page as normal
  - Upon pressing submit, the user receives a red error message saying "Bad Request. Invalid Data. Press back to return to the previous page" and the new user is not created.

My brief testing suggests this error does not occur with Edge or Safari (the only other browsers I've tested) so I suspect it is an IE issue. The error occurs with simple, alphabetic characters for username and password (so not apparently due to unusual character use).

**Comment by barisusakli** [comment]
Any errors in the browser console in IE? Do you see the token and email in the url when you go to the /register page from the email?

**Comment by mattmyne** [comment]
Yes the url shows the token and email address. There are no errors on the browser console when viewing the initial page, but after pressing the submit (Register Now) button the following errors are shown when rendering the error page:

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
register

HTML1300: Navigation occurred.
register

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
register

SCRIPT1003: Expected ':'
nodebb.min.js (1,482409)

SCRIPT5009: 'jQuery' is undefined
jquery.timeago.en.js (2,1)

SCRIPT5009: 'require' is undefined
register (227,4)

SCRIPT5009: 'define' is undefined
register (236,3)
```

**Comment by barisusakli** [comment]
Hmm is your site public? Those javascript errors would definitely cause the register to fail.

**Comment by mattmyne** [comment]
No, it's an invite-only industry association forum. I can't risk any live-debugging on it as it's now in use. I've not modified any code, so with access to IE11 the same error should be seen (it was originally reported to me by another user - I used a windows 10 virtual machine to confirm).

**Comment by barisusakli** [comment]
Yeah I tried on community.nodebb.org with IE and saw now errors.

**Comment by mattmyne** [comment]
I can't test on community.nodebb.org since there is no invite button, but I assume you generated an invite through the admin console. I don't know if that would make a difference.

**Comment by mattmyne** [comment]
Let me know if you'd like me to post an active invite url anyway if you can't replicate it at your side. I'm not sure what the security implications to our forum would be in doing so, but if the token's later cancelled I guess it's ok.

**Comment by barisusakli** [comment]
I tested locally with a valid token/email on IE11 as well and it worked. This looks like a client side error. You can email me a link at baris@nodebb.org if you don't want it to be public.

**Comment by mattmyne** [comment]
I sent you an invite to your e-mail shortly after your post, just checking you received it. The username inviting you will be "mattb".

**Comment by barisusakli** [comment]
I got it, it seems you are using the calendar plugin and it is not compatible with IE11, you can confirm by disabling it temporarily and trying the invite.  @pitaj https://github.com/pitaj/nodebb-plugin-calendar/blob/bda6829db70b32334bd154b1d6b34120398d62e0/src/client/locationHistory.js can be written to work with IE I think.

**Comment by mattmyne** [comment]
That’s great detective work @barisusakli thanks, I’m not sure I’d have made the invite page and calendar link anytime soon.

@pitaj thanks for the clarity(!) I can understand no to IE9, but perhaps IE11 would have been less of a burden to accommodate, but I appreciate lines need to be drawn.

Thanks both, I guess this issue is closed.
