### ISSUE TITLE
banning IP not working

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#7999]
- **NodeBB version:** 1.12.2 
- **Database type:** mongo

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
