### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by fast0490f** [NodeBB/NodeBB#8000]
NodeBB 1.12.2

Hi, I found incorrect behavior when recovering a password. If I enter a incorrect email (which does not exist) I get a message that the letter has been sent.

![Снимок экрана 2019-10-25 в 18 29 13](https://user-images.githubusercontent.com/11176223/67584034-75137100-f755-11e9-8926-ea4985c83e12.png)
In the admin panel, in the logs, I see that such an email does not exist

Perhaps you need to show an error for the user that this email does not exist?

This can lead to confusion for the user, as he receives a message about the successful operation, but the letter never arrives. After several retries, he will think that the forum is not working correctly

**Comment by julianlam** [comment]
Hi @fast0490f -- this behaviour is on purpose, as it discourages the use of the reset password form as a way to determine existence of a user. It is part of a security best practice that we follow, and so the messaging is purposefully opaque to support this.
