### ISSUE TITLE
Profile group tags don't show text color.

### ISSUE THREAD

**Issue by PatheticMustan** [NodeBB/NodeBB#8002]
- **NodeBB version:** 1.12.2
- **NodeBB git hash:** 22db818eb40f04e528d95257c5517ded8341493d

- **Exact steps to cause this issue:**
1. Create a group, and set the text color to literally anything. (Blue)
2. Navigate to "/user/(your username)"

- **What you expected:**
The text color of the group should be blue.

- **What happened instead:**
Text is white.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/482

**Comment by PatheticMustan** [comment]
Ah :|
Sorry!
