### ISSUE TITLE
Potential issue in privileges

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#8003]
If a group is not granted "create-topic" access privilege at the root of the category tree, the new-post category selection box will be empty.

The group's users can still post on categories in which they are allowed to post, but they have to first go to said category. 

I can't reproduce this on the community forum as i don't have the privileges, but you could. its consistent.

**Comment by barisusakli** [comment]
Git hash of nodebb and composer default? This might be already fixed.

**Comment by PostMidnight** [comment]
Just updated to latest. The issue remains.

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/67712854-25be8200-f99b-11e9-802d-9962cfeb8a1b.png)

When I remove `Create topic` privilege from `NodeBB Plugins` and allow in `Plugin Development` `NodeBB Plugins` shows up as disabled in the composer.

**Comment by PostMidnight** [comment]
Yes, that works for me as well, you must do the same test on the root directory.

**Comment by barisusakli** [comment]
What do you mean by root directory? NodeBB Plugins is a root category as in it doesn't have a parent.

**Comment by PostMidnight** [comment]
in my setup i have one root category from which all other sub categories span from.
I'll debug this tomorrow. Will try to come up with a code sub that will resolve this issue.

**Comment by barisusakli** [comment]
Ahh so you have this structure?

```
Root (no post permission)
   Sub-root (no post permission)
      child 1 ( has post permission)
      child 2 ( has post permission)
```

If that's the case I can work on a fix.

**Comment by PostMidnight** [comment]
Yes that's it, thank you. 
Sorry it took me a lot of time to understand how the code works from client to server. Furthermore, you guys are using modules and these get compiled in such a way that I can't see the code in debugger only the minified version.

**Comment by barisusakli** [comment]
Yeah I will turn it back into a recursive function so it goes true the category tree.

**Comment by PostMidnight** [comment]
Was about to suggest that. thank you so much for looking into this.

**Comment by barisusakli** [comment]
Try with nodebb-plugin-composer-default@6.3.17

**Comment by PostMidnight** [comment]
Works well thank you so much!
