### ISSUE TITLE
Options to translate server side for API/Sockets

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#8008]
Recently we've started to integrate Nodebb more into our website through the Write-API plugin and websockets the forum supplies. I was wondering if there is an easy way to translate loc strings (e.g. [[global:hello]]) before the API/socket response is sent, so the server handles it instead of the client.

If there is no current approach is there an approach you'd recommend for a plugin/PR to handle this behaviour?

**Comment by pitaj** [comment]
Can you explain your motivation for this? What are you hoping to gain?

**Comment by uplift** [comment]
I think I've got a solution that doesn't require any changes.

I didn't realize the language json files were accessible over a url (which I should have as how would the client access it) which solved my issue with including the translator module in our website as I didn't want to duplicate and sync up those json files across projects.
