### ISSUE TITLE
Daily emails: #Sent logged as zero, Emails sent to banned users

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#8010]
Hi,
The number of daily emails that were processed is showing 0 at the system logs.
Furthermore, daily emails are sent to banned users, although this was fixed here: https://github.com/NodeBB/NodeBB/issues/7261
Issues were noted on latest master.
Thank you in advance.
JJ.

**Comment by julianlam** [comment]
#7995 fixes 0 emailssent bug
