### ISSUE TITLE
[Enhancement] Automatically redirect to / if page is not found

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#8015]
May I suggest that instead of showing page-not-found error, perhaps redirect the user?

**Comment by julianlam** [comment]
No, imo, a dedicated 404 page is important to denote that a link is incorrect (or has since been taken down)

**Comment by PostMidnight** [comment]
Thanks, got it. May I ask how I should go about implementing this myself locally via plugin?

**Comment by PostMidnight** [comment]
Got it. Thanks!

If anyone is interested to implement this locally, see code below (and note how awesome nodebb is!):

Add override404 hook:

`		{ "hook": "action:meta.override404",    "method": "override404" }
`

Code for hook:

```
Plugin.override404= function (data) {
    helpers.redirect(data.res, '/');
};

```
