### ISSUE TITLE
Unsubscribe from emails without authentication

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#8016]
**NodeBB version:** 1.12.2

Feature request:

- Receive an email
- Email includes the "unsubscribe" header for email clients and services that support 1-click unsubscribes.
- Email has a link at the bottom that says unsubscribe
- Clicking the link goes to a page with two options:
    - Change your email settings (goes to current workflow that requires authentication)
    - Unsubscribe from all emails (clicking this unsubscribes the user from all digest and notifcations **without** authentication.

---

Motivation: If you have a forum that has been around for nearly 20 years and suddenly you turn on email digests,  you get a bunch of people requesting an manual unsubscribe. The login screen is too much of a barrier for them. Imagine if *you* signed up for something even 10 years ago and that site started sending you email, you'd want to just click one link and turn it off without a login.

**Comment by julianlam** [comment]
Makes sense, and is something we should definitely have

**Comment by djensen47** [comment]
Thanks! As a follow up, I think you should also support the unsubscribe header:

https://help.returnpath.com/hc/en-us/articles/222445307-What-is-the-List-Unsubscribe-header-

**Comment by julianlam** [comment]
Already do, we send the header with unsubscribable emails. Unfortunately SendGrid likes to strip out the header.

**Comment by julianlam** [comment]
:point_up: 

https://github.com/NodeBB/NodeBB/blob/9d946d1c76f36caf023fa69da8aeaccb00751a05/src/emailer.js#L204-L205
