### ISSUE TITLE
Welcome notification link broken

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#8018]
- **NodeBB version:** 1.12.2

1. Setup a NodeBB in a subfolder
2. Admin Control Panel > Settings >Notifications
3. Set the Welcome Notification Link to something like this
   - https://www.axisandallies.org/forums/topic/33112/introduce-or-re-introduce-yourself-current

Expected behavior:

New user clicks notification and it goes to that topic

Actual behavior:

This url is loaded: https://www.axisandallies.org/forums/https://www.axisandallies.org/forumstopic/33112/introduce-or-re-introduce-yourself-current

And that is a 404

**Comment by barisusakli** [comment]
Looks like absolute urls don't work right now, you can use this instead and it should work `/topic/33112/introduce-or-re-introduce-yourself-current`
