### ISSUE TITLE
Allow wildcard search for emails in ACP

### ISSUE THREAD

**Issue by djensen47** [NodeBB/NodeBB#8023]
**NodeBB version:** 1.12.2

Right now ACP > Manage > Users doesn't allow search for wildcards. I have to know the exact email, or how it starts, to find anything. I have situations where I need to look up by domain or other fragments of the email address.

Thanks!

**Comment by AliCihan** [comment]
this would be a very useful addition...

**Comment by barisusakli** [comment]
It's possible to search usernames/emails with `*partial`

![image](https://user-images.githubusercontent.com/2583394/87115663-de82d380-c241-11ea-8379-410615e9b69d.png)
