### ISSUE TITLE
Image for chat room

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/NodeBB#8025]
Hi Developers,
It could be a nice addition if a chat room will also retain a url for an image. In a similar manner to users, said image may be displayed on the room's icon when the chat is minimized.

**Comment by PostMidnight** [comment]
I was able to get it working, through a plugin.

First, in the plugin, when the room is created, add image param with the path to the image:

```
const room = {
				owner: ownerUid,
				roomId: newRoomId,
				groupChat: 1,
				roomName: roomName,
				image: pathToImage
			};
			await db.setObject(`chat:room:${newRoomId}`, room);
			await db.sortedSetAdd(`chat:room:${newRoomId}:uids`, uids.map(() => now), uids);
			await Messaging.addRoomToUsers(newRoomId, uids, now);

```

Secondly, edit /modules/chat.js so the image url will be passed to to the renderer function, as follows (line 247)

```
taskbar.push('chat', chatModal.attr('data-uuid'), {
					title: '[[modules:chat.chatting_with]] ' + (data.roomName || (data.users.length ? data.users[0].username : '')),
					roomId: data.roomId,
					icon: 'fa-comment',
					state: '',
					isSelf: data.isSelf,
					image: data.hasOwnProperty('image') ? data.image : '',
				}, function () {
					taskbar.toggleNew(chatModal.attr('data-uuid'), !data.isSelf);
					$(window).trigger('action:chat.loaded', chatModal);

					if (typeof callback === 'function') {
						callback(chatModal);
					}
				});
```

**Comment by arranka** [comment]
Can you make a list of all the improvements you propose for the chat?
put them all together in one post

**Comment by PostMidnight** [comment]
Hi @arranka see https://github.com/NodeBB/NodeBB/issues/7330

**Comment by julianlam** [comment]
Best to leave this to a plugin :+1:
