### ISSUE TITLE
Brute-force protection on login endpoint implementation

### ISSUE THREAD

**Issue by animir** [NodeBB/NodeBB#8036]
[rate-limiter-flexible](https://github.com/animir/node-rate-limiter-flexible) helps. Here is an example https://github.com/animir/express-4.x-local-example/tree/secure-login#brute-force-protection

**Comment by julianlam** [comment]
We do already have login protection in place. Thanks for the suggestion, but I wanted to ask why you think `rate-limiter-flexible` would be a superior alternative :smile:

**Comment by animir** [comment]
@julianlam The only limiting I see is against socket flood here https://github.com/NodeBB/NodeBB/blob/master/src/middleware/ratelimit.js. And it is not robust, since attacker can reconnect every 100 requests.

Could you point, where is login brute-force protection implemented?

**Comment by julianlam** [comment]
Hmm, I must have been mistaken, as you are right, I cannot find anything there now :smile: 

Looks like a worthwhile addition to the codebase.

**Comment by barisusakli** [comment]
If you try to login more than x times account gets locked out for y minutes

https://github.com/NodeBB/NodeBB/blob/master/src/user/auth.js#L25

I think limiting req/s to the /login route is better handled on the load balancer

**Comment by animir** [comment]
@barisusakli There is also [isFlooding](https://github.com/NodeBB/NodeBB/blob/master/src/middleware/ratelimit.js#L10) method, you may want to make it secure as well. Currently, it is quite easy to get around that protection.

**Comment by julianlam** [comment]
@animir The socket.io flooding protection is not actually to protect from brute force, but to handle socket.io queuing an insane amount of requests for no discernible reason.

Login is handled not through socket.io, but through regular HTTP, which is secured from brute force by the account lockout code :smile:

**Comment by animir** [comment]
@julianlam isFlooding function doesn't protect from flooding, because client can reconnect every 100 requests and get another socket

**Comment by julianlam** [comment]
@animir that's not the point. Please read my reply again.

**Comment by animir** [comment]
@julianlam I had read it. Login endpoint protected (@barisusakli pointed to it above), socket connection isn't. It is not the same issue, but still the issue.
