### ISSUE TITLE
Upgrade 1.13.0 new/old post url not working 

### ISSUE THREAD

**Issue by zaasmi** [NodeBB/NodeBB#8037]
- **NodeBB version:** 
- **NodeBB git hash:** 

- **Database type:** mongo, redis, or postgres
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
