### ISSUE TITLE
Segmentation fault when uploading photos

### ISSUE THREAD

**Issue by kenvix** [NodeBB/NodeBB#8049]
- **NodeBB version:** 1.13.0
- **NodeBB git hash:** c6ef1486dee5cfb0d435716cf7d4d718fad68359
- **Database type:** mongo
- **Database version:** 4.0.10
- **Exact steps to cause this issue:**
	1. Upload a photo
	2. Nodebb crashed with the only message `Segmentation fault (core dumped)` . It only crashes for photos, other files will not crash the server
- **What you expected:**
Upload a image successfully
- **What happened instead:**
Nodebb crashed with the only message `Segmentation fault (core dumped)`

**Comment by kenvix** [comment]
I have solved the problem by using:
```
npm uninstall benchpressjs
npm install benchpressjs@1.2.7
```

**Comment by pitaj** [comment]
It's possible, but very unlikely this was caused by benchpress. The npm install probably just fixed a different broken package. I don't recommend staying on the older version.
