### ISSUE TITLE
[HELP] User who seem to be missing in registered-users groups

### ISSUE THREAD

**Issue by sznowicki** [NodeBB/NodeBB#8052]
Hello everyone.

First I'd like to congratulate great forum software! It empowers our community already for some time and we are super happy with it.

Now the issue. I have a user who was imported from our old forum via a script that was adding users via API.

Normally those users are added to "archived" group. When they want to activate, we remove them from those group, change email and they can log in again.

Now, one user is coming back, we did as usual but he cannot login with "Local login system has been disabled for non-privileged accounts." error.

Even when I manage to log him in with some workarounds, he sees no posts whatsoever. 
If I add him to moderators group, he only sees categories that are visible for moderators only.

Given that, I suspect he somehow is not added to "registered-users" group. 

Since I have not much experience with the source code and mongo schema, I'd like to ask you for some support with that issue.

Current version: 1.13.0 (just upgraded from 1.12.x).
Url: https://zlosniki.pl

Thanks in advance for any suggestions!

**Comment by julianlam** [comment]
@sznowicki what happens when you run this MongoDB query?

`db.objects.find({ _key: "group:registered-users:members", value: "4" });` (replace `4` with the uid of the affected user)

**Comment by sznowicki** [comment]
Thanks for a quick response!

Lame question, how do I get user id?

**Comment by sznowicki** [comment]
Found it.
```db.objects.find({ _key: "group:registered-users:members", value: "48" });```

Gives:
```Fetched 0 record(s) in 112ms```

**Comment by julianlam** [comment]
`db.objects.updateOne({ _key: "group:registered-users:members", value: "48" }, { $set: { score: Date.now() } }, { upsert: true, w: 1 });`

**Comment by sznowicki** [comment]
Thanks a lot, did run the query, user now seems to be in this group, but still cannot login somehow. I'll try to investigate further, but any suggestions are of course welcomed.

**Comment by sznowicki** [comment]
After restarting nodebb process, it seems to be work just fine. Thanks a lot for support, it was super quick and super helpful.

**Comment by N07070** [comment]
Hello, 

Is there a way to add every user that is not in the registered-users group back in it ? I deleted some users by mistake. 

Cheers.

@julianlam
