### ISSUE TITLE
Strange link on top of forum traffic ACP

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#8060]
- **NodeBB version:* 1.13.0* 
- **NodeBB git hash:*c6ef1486dee5cfb0d435716cf7d4d718fad68359* 

- **Database type:** mongo + redis
- **Database version:*3.6.14* 

![image](https://user-images.githubusercontent.com/2943127/69483111-0b44c080-0e02-11ea-9cc0-c86a433aa6f1.png)

**Comment by julianlam** [comment]
It's a link to the raw JSON for the chart.
