### ISSUE TITLE
Latest Posts are old, not latest!

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8074]
- **NodeBB version:** 1.13.0
- **NodeBB git hash:** Master
- **Database type:** mongo

Hi, latest posts for each user are obsolete.

![image](https://user-images.githubusercontent.com/31972226/70169620-6a4ae500-16e0-11ea-87ea-7d30e82e483c.png)

It's noticeable that for new users, just 3 posts are shown in latest posts.

![image](https://user-images.githubusercontent.com/31972226/70169908-fa892a00-16e0-11ea-997e-7775c55c39b4.png)

you can see there are just 3 posts shown here ☝️ 
Also we have this problem in /user/posts page

**Comment by julianlam** [comment]
Can you expand more on what you mean by "obsolete"?

**Comment by mohammadhassan99** [comment]
@julianlam My mistake, I didn't use proper word for that. I mean they are old. They aren't latest posts. For example in the first screenshot you can see my latest post date is September 13. Nearly 3 months ago

**Comment by barisusakli** [comment]
Works fine here https://community.nodebb.org/user/baris. Can you reproduce on our community?
