### ISSUE TITLE
Mention notifications marked unread when they shouldn't be

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/NodeBB#8078]
- **NodeBB version:**  1.13.0
- **NodeBB git hash:** 

- **Database type:** postgres
- **Database version:**  12.1 (Ubuntu 12.1-1.pgdg18.04+1)

- **Exact steps to cause this issue:**
1. Have mention notifications from multiple topics.
2. Navigate to one of the topics.

- **What you expected:**
Notification from that topic would be marked read. Notifications from other threads would be left as unread.

- **What happened instead:**
All mention notifications were marked read.

**Comment by julianlam** [comment]
Hmm... that's a tricky one. What happens when you click on a notification is it looks at the target topic, and then goes back to your notifications list and marks any notification going to that topic as read.

I can see how that would be undesirable, I'll have to take a look...

**Comment by barisusakli** [comment]
Sounds like a regression, it shouldn't touch notifications from other topics.

**Comment by boomzillawtf** [comment]
I didn't click on a notification. I went there via the unread list. I almost never click mention notifications, because it has the strong potential to cause me to miss posts I haven't read yet, but using a normal unread link makes sure I pick up in the topic where I left off.
