### ISSUE TITLE
mongodb warnings on startup

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#8079]
(node:9403) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6

**Comment by malaohu** [comment]
(node:81442) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
(node:81442) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6

**Comment by corbolais** [comment]
Same here.

**Comment by jmwielandt** [comment]
I have this here. Using MongoDB 4.2. Windows 10 x64.

![image](https://media.discordapp.net/attachments/423647278902018063/666823291339800588/unknown.png)

**Comment by AndrewFinlay** [comment]
I'm seeing this too on v1.13.x, MongoDB 4.2, CentOS 7.

Seems to work with v1.12.x

**Comment by sohrabafard** [comment]
Same!

  version:  1.13.2
  Node ver: v12.14.1
  git hash: 71f4607db4e2252995d488b1968f7e9bb1d97efc

  database: mongo
(node:34913) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:34913) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:34913) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
        version: 4.2.3
        engine:  wiredTiger
Pageviews, last 24h (min: 567  max: 2587)
