### ISSUE TITLE
Wrong cookie being cleared on logout

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#8085]
- **NodeBB version:**  1.13.0
- **NodeBB git hash:** c6ef148

Hi,

it looks like latest refactor broke logging out in a situation where you use a non-standard session cookie name, resulting in "Session Mismatch" errors on every pageview after logging out: https://forums.opera.com/topic/37044/pop-up-it-looks-like-your-login-is-no-longer-active

After investigation I believe the culprit is the hardcoded cookie name:
[Fix_wrong_session_cookie_being_cleared_on_logout.txt](https://github.com/NodeBB/NodeBB/files/3972618/Fix_wrong_session_cookie_being_cleared_on_logout.txt)

That fixes the problem for us.

**Comment by barisusakli** [comment]
Thanks @attis
