### ISSUE TITLE
Banning users does not work

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#8086]
- **NodeBB version:** 1.13.0
- **NodeBB git hash:** c6ef148

- **Database type:** mongo + redis
- **Database version:** 3.4.23 + 5.0.4

- **Exact steps to cause this issue:**
	1. Ban user either through his profile page or via Manage > Users in ACP. Tried different types of ban (days/hours) and different values.
	2. The user receives an e-mail about being banned: 
![obraz](https://user-images.githubusercontent.com/591754/70989088-4796d400-20c3-11ea-999e-5e81dba65c28.png)

- **What you expected:**
I expect the user to be banned.
- **What happened instead:**
There is nothing in the ban history for that user:
![obraz](https://user-images.githubusercontent.com/591754/70989498-0bb03e80-20c4-11ea-873c-d18ed9cf75c7.png)
Also, verified that the user can still log in freely. Looks like the ban is not effective at all.

**Comment by barisusakli** [comment]
Tried to repro this but wasn't able to, both permanent and duration ban worked for me

![image](https://user-images.githubusercontent.com/2583394/70998876-44d9b600-20a6-11ea-8390-44136e96a833.png)

When you ban a user can you check their user object in the database with `db.objects.findOne({_key: "user:<id>"});` they should have these fields.

```
"banned" : 1,
"banned:expire" : 1576606837131
```

**Comment by attis** [comment]
Unfortunately these fields are not preset in the user object.
When I click the "Ban Account" button, these are the messages in node console:
```
opcom-forums-nodebb | 2019-12-17T13:32:39.270Z [4567/57] - verbose: [plugins/fireHook] static:sockets.validateSession
opcom-forums-nodebb | 2019-12-17T13:32:39.271Z [4567/57] - verbose: [plugins/fireHook] filter:user.hasBanPrivilege
opcom-forums-nodebb | 2019-12-17T13:32:39.272Z [4567/57] - verbose: [plugins/fireHook] filter:user.whitelistFields
opcom-forums-nodebb | 2019-12-17T13:32:39.273Z [4567/57] - verbose: [plugins/fireHook] filter:users.get
opcom-forums-nodebb | 2019-12-17T13:32:39.274Z [4567/57] - verbose: [plugins/fireHook] filter:user.whitelistFields
opcom-forums-nodebb | 2019-12-17T13:32:39.275Z [4567/57] - verbose: [plugins/fireHook] filter:user.getSettings
opcom-forums-nodebb | 2019-12-17T13:32:39.283Z [4567/57] - verbose: [plugins/fireHook] filter:users.get
opcom-forums-nodebb | 2019-12-17T13:32:39.283Z [4567/57] - verbose: [plugins/fireHook] filter:user.notificationTypes
opcom-forums-nodebb | 2019-12-17T13:32:39.283Z [4567/57] - verbose: [plugins/fireHook] filter:email.params
opcom-forums-nodebb | 2019-12-17T13:32:39.286Z [4567/57] - verbose: [plugins/fireHook] filter:email.modify
opcom-forums-nodebb | 2019-12-17T13:32:39.286Z [4567/57] - verbose: [plugins/fireHook] filter:email.send
```

And it stops here.

**Comment by barisusakli** [comment]
Looks like it is getting stuck after sending the email, I will take a look. Are you using an emailer plugin?

**Comment by attis** [comment]
Yes! That was my hunch too, now that I saw that output and indeed, disabling `nodebb-plugin-emailer-ses` and restarting NodeBB makes banning work.
What do you propose to do now? I see that you have forked https://github.com/chollis/nodebb-plugin-emailer-ses yourself long time ago. I guess the bug should be reported there, and this one should be closed, as NodeBB works fine (I think). I am not sure if the original maintainer have not abandoned the plugin, though.

**Comment by barisusakli** [comment]
I fixed it in the plugin and sent a pull request, https://github.com/chollis/nodebb-plugin-emailer-ses/pull/3 you can apply the change there until it's merged and published.

Good idea about the template I will add that in now.

**Comment by attis** [comment]
I can confirm that your commit fixes the issue for us.
Thank you very much for your help!
