### ISSUE TITLE
Fediverse (ActivityPub) Federation

### ISSUE THREAD

**Issue by teotikalki** [NodeBB/NodeBB#8095]
I'd like to request as a feature Fediverse (ActivityPub) Federation. Enabling NodeBB instances to integrate into the Fediverse would allow for content sharing with other instances with the goal of increasing user engagement and participation. 

Motivation: The decentralization of the internet is a laudable goal, both technically and politically. I'd like NodeBB to lead the way into this future.

**Comment by julianlam** [comment]
@rmdes @teotikalki :eyes: 

Only 4 years turnaround time, not bad, no? :joy:

**Comment by teotikalki** [comment]
> Only 3.5 years turnaround time, not bad, no? 😂

LMAO

In my mind's ear I heard the guy from Ghostbusters II saying 'Better late than never' when the ghost of the Titanic showed up in the harbor.
