### ISSUE TITLE
Bootswatch installing mush slow via yarn

### ISSUE THREAD

**Issue by greenhat616** [NodeBB/NodeBB#8097]
while fetching *github.com/thomaspark/bootswatch.git#c41a8f066feb8950c6f9c6bcf5a3c37d1085404e*，mush slower than other packages from npm. could you use a specfic version instead of a git repos?

**Comment by barisusakli** [comment]
Last I checked there was no release for that specific fix we need from bootswatch

**Comment by trexguo** [comment]
There are several new releases:
https://github.com/thomaspark/bootswatch/releases

**Comment by barisusakli** [comment]
I think the issue is 3.4.1+1 is not published to npm

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/8527
