### ISSUE TITLE
While Click json button, return a error（in ACP index page）

### ISSUE THREAD

**Issue by greenhat616** [NodeBB/NodeBB#8107]
Line：https://github.com/NodeBB/NodeBB/blob/5a8217de013ba14188d906c4c8db9aee792e84ee/src/controllers/admin/dashboard.js#L83

NodeBB version: v1.13.x
 
![Screenshot_20200105-143506](https://user-images.githubusercontent.com/41122242/71776217-9d76e180-2fc8-11ea-9aba-8eef94f0f3eb.jpg)

![Screenshot_20200105-143511](https://user-images.githubusercontent.com/41122242/71776218-a1a2ff00-2fc8-11ea-8f63-df5707f84c2e.jpg)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/8105
