### ISSUE TITLE
Topic access counter is broken in v1.13.1

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#8124]
- **NodeBB version:** 1.13.1
- **NodeBB git hash:** 16e8f49655d301d0e001c0a478ce6f44bf726a86

- **Installed NodeBB Plugins:** 

- **Database type:** mongo
- **Database version:**  @latest

- **Exact steps to cause this issue:**
	1. Forum access as Guest
	2. read topic

- **What you expected:** incremented access counter

- **What happened instead:** the access counter has the same value

Login as registered user, click on topic and the access counter works fine incremented as in Version 1.12.x and before. 
I think the access counter ignores the forum guests.

**Comment by barisusakli** [comment]
This is by design, guests don't increase topic and profile view counts. https://github.com/NodeBB/NodeBB/commit/cf7e0cfd2d737c6c1ce74b13cd0a24243f1ad6f8

**Comment by awunnenb** [comment]
counting only registerd users is not by design. This bug does exists since version 13. Why do you don't want to count users, if they are not logged in? Please compare with version 12.

**Comment by PatheticMustan** [comment]
This wasn't part of v12 because it was just added in v13, in the commit that barisusakli just referenced.
https://github.com/NodeBB/NodeBB/commit/cf7e0cfd2d737c6c1ce74b13cd0a24243f1ad6f8

**Comment by awunnenb** [comment]
All our customers want to see, how often a topic was clicked/readed by any user/visitor. It works fine from nodebb 1.0 to 1.12.  They don't need the information, how often a registered and logged in user has access to the topic. It seems to be our end of using nodebb now or we have to use v1.12 forever?

**Comment by barisusakli** [comment]
You can just modify this line https://github.com/NodeBB/NodeBB/blob/master/src/controllers/topics.js#L131
and change `1` to `0`. Then guests will increase the view count. You will have to reapply the change when you upgrade to later versions.

**Comment by oplik0** [comment]
Perhaps an option to change this behavior could ba added to guests setting (that category in ACP is almost empty right now anyway)? That way there would be an easy way to change this behavior while keeping the current default.
