### ISSUE TITLE
new chat shows room join message twice

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#8127]
reloading the page just shows one
![image](https://user-images.githubusercontent.com/2583394/72694759-22ebad00-3b04-11ea-870c-4dd16f15a443.png)

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/72744274-3c7c0b80-3b7b-11ea-9cf6-b1989227b385.png)

No repro -- can you provide reproduction steps?

Simply opening a chat window (from chats page) doesn't trigger.

**Comment by julianlam** [comment]
Nevermind, got it. Need to start new chat from profile page.
