### ISSUE TITLE
non-participant user bug

### ISSUE THREAD

**Issue by numanturle** [NodeBB/NodeBB#8133]
NodeBB version: **v1.13.1**
NodeBB git hash: **418c174d56a5e53f174cd531719b291522470b23** 

there is an error causing him to leave a room he did not join

value sent to the socket

["modules.chats.leave","%RANDOM_CHAT_ID%"]

https://github.com/NodeBB/NodeBB/blob/master/src/messaging/rooms.js#L116-L144

![image](https://user-images.githubusercontent.com/7007951/73013056-95240080-3e28-11ea-819c-948616cbbfa2.png)

**Comment by numanturle** [comment]
to solve the problem, it is necessary to check the participation status of the user.

**Comment by julianlam** [comment]
@numanturle Just to confirm... you're crafting this socket response to leave a room you're not even in, correct?

You can't _join_ the room, I'm hoping?

**Comment by numanturle** [comment]
@julianlam 
I can only leave the room I was never involved in.
