### ISSUE TITLE
Stuck with Invalid session warning 

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#8142]
- **NodeBB version:** 1.13.0
- **NodeBB git hash:** c6ef148
- **Database type:** mongo + redis
- **Database version:** 3.4.23 + 5.0.4
- **Exact steps to cause this issue:**
	With the changes introduced with #7982 there is a new scenario that I believe is not handled correctly:
1. Log in to NodeBB in a web browser (to have a session correctly created).
2. Destroy the session data on server-side (for example by removing relevant key from Redis or whatever session store your installation is using).
3. Go back to the browser and perform any action that sends message via WebSockets (or simply wait a bit).
4. You will receive the "Session Mismatch" box, prompting you to reload the page, but...
5. Reloading the page does not fix the problem. The popup keeps reappearing with each user action until you manually clear the session cookie from the browser.

- **What you expected:**

Reloading the page should send a `Set-Cookie` header in response that deletes the mismatching session cookie from user's browser, thus resolving the problem.

- **What happened instead:**
Without server deleting the invalid session cookie, user keeps it forever and sends with every request, so `validateSession` method from `src/socket.io/index.html` keeps throwing an Error that triggers the popup.

Some additional background: our Forums have an oAuth integration with our own IdP that allows to "remotely" delete a session. A webhook request is then sent to our Forums which invalidates NodeBB user session (on server-side) by calling `User.auth.revokeSession(...)` - effectively remotely logging him/her out of Forums. Obviously there is no way we can delete the forum's session cookie from the user browser, so the (now invalid) session cookie still persist there. In the past reloading the page after receiving the "session mismatch" popup really solved the problem, but now it's not the case.

Note: I think that the same problem can be caused (globally for all forums users!) if your session storage fails for whatever reason and gets emptied, is restarted due to software upgrade, etc.

Cheers!

**Comment by julianlam** [comment]
Thanks for reporting @attis! Sounds like you've thoroughly identified the problem for a fix 🙂

Currently I don't think the server discriminates between an outdated session (e.g. login to different account in multiple tabs) vs an invalid/expired session.

It should be fairly trivial* to send that along and act as appropriate.

\* famous last words

**Comment by julianlam** [comment]
@attis mm, so I was all set to say I couldn't repro, because I deleted the sessions but navigating elsewhere just logged me out... then it started repro'ing :roll_eyes: 

Server and client are matching, in that both seem to report that they're uid 0 (that is, logged out), but the error actually comes from socket.io, which might still think you're logged in...

**Comment by attis** [comment]
Is that released in NodeBB v1.13.2, by the way?

**Comment by barisusakli** [comment]
Doesn't look like it was in the 1.13.3 release 🤔

**Comment by julianlam** [comment]
@attis Ah I think it just didn't make the cutoff for release. If you'd like I can backport it, or you can cherry-pick it into your install, up to you.

**Comment by attis** [comment]
I'll cherry-pick then. Thanks!

**Comment by julianlam** [comment]
@attis can you try again with latest master? The commit you cherry-picked might... contain a regression that breaks registrations :grimacing:

**Comment by julianlam** [comment]
The block in `src/middleware/headers.js` should look like this now:

```
				// Ensure that the session is valid. This block guards against edge-cases where the server-side session has
		// been deleted (but client-side cookie still exists)
		if (req.uid > 0 && !req.session.meta && !res.get('Set-Cookie')) {
			res.clearCookie(nconf.get('sessionKey'), meta.configs.cookie.get());
		}
```

**Comment by attis** [comment]
Hm... good thing I have not have time to do that cherry-pick yet ;)
I think I'll just wait for it to find its way into a regular release.

**Comment by julianlam** [comment]
@attis okay. If you do want to cherry-pick it, it might require three separate commits, so that will get hairy quickly :smile:

**Comment by julianlam** [comment]
5a0c7c1497ed2de84ad317f7e3fcc6b1354b08eb introduced a regression that nullified the fix :smile: whoopsie

**Comment by julianlam** [comment]
We're running into stability issues with the re-applied fix, so it has been reverted and is pending resolution once again.

**Comment by julianlam** [comment]
@attis I think we almost finally got a handle on this :laughing:  #8338
