### ISSUE TITLE
Admin access during Maintenance Mode when accessing through Node Write API

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#8144]
Normally when running Nodebb under Maintenance Mode, Admins can access the site as normal.

When using the Write API, the req.uid isnt set by the Write API as the Write API middleware runs after the maintenance mode middleware so the maintenance message gets sent back in the json response.

Is there anyway around this so Admins can still access content when using the Write API?

**Comment by julianlam** [comment]
Hm, that's an interesting one -- definitely would be good to resolve if possible, thanks for reporting.

**Comment by julianlam** [comment]
@uplift can you let me know what route you are trying to access while maintenance mode is on? In my limited testing, the Write API does seem to function normally even with maintenance mode enabled.

I tried `PUT/DELETE /api/v2/users/:uid/follow` and `POST /api/v2/topics`

**Comment by uplift** [comment]
Its actually just GET requests. e.g. GET /api/users

Using it with Master Token and ?_uid=ID appended. Is that correct usage?

**Comment by julianlam** [comment]
Ah hm... yes, that is. Interfacing with routes provided by core using Write API bearer token *should* be supported (and of course, by your own admission, it does when not in maintenance mode), and so that's something I'll have to look at more closely, thanks.

**Comment by julianlam** [comment]
Normally middleware.pluginHooks are run on page load, but the maintenance mode middleware short-circuits this, so I am calling it in that middleware :man_shrugging:
