### ISSUE TITLE
Category selector does not exist in /compose route (on mobile)

### ISSUE THREAD

**Issue by approxinfinity** [NodeBB/NodeBB#8145]
Some but not all users are unable to post new topics after 1.13.1 upgrade (was on 1.12.x).
EDIT: I was able to reproduce by attempting to post on a phone. The category dropdown does not show in responsive design and attempting to post says category does not exist. 

- **NodeBB version: v1.13.1
- **NodeBB git hash: d1e0672fa6bfd0a80e274418fb82dce06562ad3e
- **Installed NodeBB Plugins:
	* nodebb-plugin-carousel (not installed, enabled)
	* nodebb-plugin-color (not installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emailer-mandrill (not installed, enabled)
	* nodebb-plugin-emailer-sendgrid (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-apple (not installed, enabled)
	* nodebb-plugin-emoji-fontawesome (installed, enabled)
	* nodebb-plugin-emoji-one (installed, enabled)
	* nodebb-plugin-events (not installed, enabled)
	* nodebb-plugin-google-analytics (installed, enabled)
	* nodebb-plugin-imgur (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-outside (not installed, enabled)
	* nodebb-plugin-rss (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-plugin-static-page (not installed, enabled)
	* nodebb-plugin-topic-tags (installed, enabled)
	* nodebb-plugin-vibration-notifications (not installed, enabled)
	* nodebb-plugin-youtube (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)
- **Database type: mongo
- **Database version: v3.4.3
- **Exact steps to cause this issue:**
	1. User attempted to post a new topic from inside a category
- **What you expected:**
 expected that the post would post or a category would be selectable
- **What happened instead:**
category dropdown was hidden and user received message "Error: Category does not exist" when posting

**Comment by approxinfinity** [comment]
Also, they said they were using firefox on a desktop (I don't know the OS). I am using firefox on a linux box and not hitting the issue.

**Comment by approxinfinity** [comment]
I fixed the issue with my data 
I think ! I found a category in the objects collection that had a null Id and negative post number and deleted it. A user who was affected reports he can post again. I don't know what process in some version of the board generated the record with the null id (possible creating a category, deleting its only post and deleting it? :man_shrugging: ) I wonder if there is a check on creating a topic that iterates through the collection and has issues if any of the category records has a null id and might be unnecessarily restrictive? I havent set up vscode to debug your  project yet. Anyway, cheers. As of now any fix here may not be necessary for me, just a weird way that old corrupt data could not be happy with current posting logic.

**Comment by approxinfinity** [comment]
Some users still reporting that they cannot post a new topic, still seeing a "category does not exist" error. I think this may be worth looking into?

**Comment by approxinfinity** [comment]
Deleted all of the red herring comments now that I think I've discovered the real issue. Edited above ^

**Comment by approxinfinity** [comment]
Hmm. Persona theme is the active theme. I tried this on your nodebb board but I was able to post, it did not throw the error.

**Comment by approxinfinity** [comment]
I think this may be impacted by selecting separate route on the composer options in admin. I'll try to isolate the issue for you later, but I now see the drop-down in the top bar on mobile after turning the separate route option off.

**Comment by approxinfinity** [comment]
Ok. I changed the composer to not use a separate route, and I'm able to select a category. 

You guys might want to take a look at when the composer uses a separate route and teh user is looking at a responsive layout. There's no way to progress with the post (also check behavior difference between when posting from a category vs posting from recent posts) because the category dropdown does not show.

I've switched to not use the separate route for the time being. 

Thanks!

**Comment by barisusakli** [comment]
Working fine here, 
![image](https://user-images.githubusercontent.com/2583394/74279278-a1dd9b00-4ce8-11ea-9d02-faa0e208f532.png)

If there are any JS errors when loading the composer this might happen. Fixed a issue recently that would cause this https://github.com/NodeBB/NodeBB/issues/8151. Pretty sure it's the same issue.
