### ISSUE TITLE
Some iOS 13 users cannot connect on at&t

### ISSUE THREAD

**Issue by approxinfinity** [NodeBB/NodeBB#8146]
Users are reporting this as a longstanding issue (for a year at least) that has affected them only when their device is not on wifi.

We have a thread about this on my board. Feel free to hop in on the thread if you want specific info or of course you can ask me for it. Everyone is pretty forthcoming. 

https://kubuckets.com/topic/9243/site-not-working-without-wifi

They have a running thread about this.
- **NodeBB version: v1.13.1
- **NodeBB git hash: d1e0672fa6bfd0a80e274418fb82dce06562ad3e
- **Installed NodeBB Plugins:
	* nodebb-plugin-carousel (not installed, enabled)
	* nodebb-plugin-color (not installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emailer-mandrill (not installed, enabled)
	* nodebb-plugin-emailer-sendgrid (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-apple (not installed, enabled)
	* nodebb-plugin-emoji-fontawesome (installed, enabled)
	* nodebb-plugin-emoji-one (installed, enabled)
	* nodebb-plugin-events (not installed, enabled)
	* nodebb-plugin-google-analytics (installed, enabled)
	* nodebb-plugin-imgur (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-outside (not installed, enabled)
	* nodebb-plugin-rss (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-plugin-static-page (not installed, enabled)
	* nodebb-plugin-topic-tags (installed, enabled)
	* nodebb-plugin-vibration-notifications (not installed, enabled)
	* nodebb-plugin-youtube (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)
- **Database type: mongo
- **Database version: v3.4.3
- **Exact steps to cause this issue:**
	1. User attempted to connect on iOS off of wifi
- **What you expected:**
 expected that they could connect 
- **What happened instead:**
user cannot

**Comment by pitaj** [comment]
This is exceedingly odd.

Can you ask them to try connecting to community.nodebb.org to see if it's a nodebb problem?

What's your reverse proxy setup? Do you have cloudflare or anything like that?

It sounds like a DNS or other lower layer issue. I found this thread on the ATT forums: https://forums.att.com/conversations/data-messaging-features-internet-tethering/att-wirless-users-cannot-load-my-website/5defd2d3bad5f2f606056dfe

The solution suggested there is to "remove the AAAA record from DNS setup". Maybe try that or look through the thread further. Or ask the idea who have an issue to try setting an explicit DNS like using the 1.1.1.1 app.

**Comment by approxinfinity** [comment]
Ok! I think killing the AAAA record may have done the trick (according to one user). Thank you for looking outside the bounds of nodebb and [possibly] figuring this one out.

**Comment by julianlam** [comment]
Nice job @pitaj ! :smile:
