### ISSUE TITLE
Feature Request: Prevent Currently Viewed Post Number Being Appended to URL

### ISSUE THREAD

**Issue by amp88** [NodeBB/NodeBB#8147]
Currently when scrolling through forum threads the number of the post you're viewing is automatically appended to the URL in the address bar. This generates multiple browser history entries per thread. 

Ideally this behaviour would be a toggle option which was modifiable through the User Control Panel/User Settings and its default behaviour could be set in the Administrator Control Panel.

A short video demonstrating the behaviour (on Firefox 72.0.2 (64-bit)): https://www.youtube.com/watch?v=d0OwQ3xTRaQ

Thanks.

**Comment by julianlam** [comment]
Multiple history events should not be appended, the history should be updated to reflect the new URL.

**Comment by amp88** [comment]
> 
> 
> Multiple history events should not be appended, the history should be updated to reflect the new URL.

Sorry, I don't follow. Are you saying the behaviour I'm experiencing is not as intended (i.e. I'm getting multiple history entries erroneously)?

**Comment by julianlam** [comment]
@amp88 That is correct -- we use `pushState` and `replaceState` to add/replace history items as you navigate between pages, and so reading a topic should not add additional history items, but replace the one you're currently in.

Can you reproduce this on try.nodebb.org or community.nodebb.org?

**Comment by amp88** [comment]
> 
> 
> @amp88 That is correct -- we use `pushState` and `replaceState` to add/replace history items as you navigate between pages, and so reading a topic should not add additional history items, but replace the one you're currently in.
> 
> Can you reproduce this on try.nodebb.org or community.nodebb.org?

I'm getting the same behaviour in the 'Who is using NodeBB?' thread at community.nodebb.org (i.e. multiple history items scrolling through one thread).

https://community.nodebb.org/topic/180/who-is-using-nodebb

Using Firefox 72.0.2 (64-bit) and Chrome 79.0.3945.130 (Official Build) (64-bit) on Windows 10 Pro 64-bit.

**Comment by julianlam** [comment]
Unfortunately I do not -- I only get a new history event if I hit Home/End, which is intended...

**Comment by barisusakli** [comment]
Unfortunately that's something the browser does, see https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API
```
history.replaceState() operates exactly like history.pushState(), except that replaceState() modifies the current history entry instead of creating a new one. Note that this doesn't prevent the creation of a new entry in the global browser history.
```

So scrolling down a topic will create new history entries in chrome://history

![image](https://user-images.githubusercontent.com/2583394/73782861-bfe35280-4760-11ea-9787-ad85467aca69.png)

But clicking back will go to the previous page correctly

**Comment by amp88** [comment]
> 
> 
> Unfortunately that's something the browser does, see https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API
> 
> ```
> history.replaceState() operates exactly like history.pushState(), except that replaceState() 
> modifies the current history entry instead of creating a new one. Note that this doesn't
> prevent the creation of a new entry in the global browser history.
> ```
> 
> So scrolling down a topic will create new history entries in chrome://history
> 
> ![image](https://user-images.githubusercontent.com/2583394/73782861-bfe35280-4760-11ea-9787-ad85467aca69.png)
> 
> But clicking back will go to the previous page correctly

OK, so would it be possible to allow users/forum admins to prevent that replaceState function from being called while scrolling through threads? I realise it sounds like a minor gripe, but I've ended up with literally hundreds of history entries to scroll through just from visiting 10 or so threads.

**Comment by barisusakli** [comment]
Yup it can be made an acp setting so replaceState isn't called when you scroll through threads. You can comment out [these](https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic.js#L232-L234) lines until it is implemented

**Comment by amp88** [comment]
> 
> 
> Yup it can be made an acp setting so replaceState isn't called when you scroll through threads. You can comment out [these](https://github.com/NodeBB/NodeBB/blob/master/public/src/client/topic.js#L232-L234) lines until it is implemented

OK, thank you :)

**Comment by pitaj** [comment]
Suggest making this a user settings option, not just a sitewide setting.

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/85167640-24e2a500-b237-11ea-9fb9-52ef45140841.png)

:point_up: this?

Okay, I grant that this happens at least on Chrome and Firefox, but is it a significant enough issue that it warrants an option to remove this behaviour? It doesn't show up in the back button history:

![image](https://user-images.githubusercontent.com/923011/85167794-62dfc900-b237-11ea-8883-7219e1c35845.png)

... and so I think adding an option to remove this behaviour is a tad pedantic :thinking:  but in any case, I am fine with it being a UCP option.
