### ISSUE TITLE
Cannot upload image

### ISSUE THREAD

**Issue by aunruh** [NodeBB/NodeBB#8150]
- **NodeBB version:** 1.13.1
- **NodeBB git hash:** d1e0672fa6bfd0a80e274418fb82dce06562ad3e

- **Installed NodeBB Plugins:** 
Active plugins:
	* nodebb-plugin-anti-spam-question (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emailer-mailgun (installed, enabled)
	* nodebb-plugin-emoji (installed, disabled)
	* nodebb-plugin-emoji-android (installed, disabled)
	* nodebb-plugin-emoji-extended (installed, enabled)
	* nodebb-plugin-emoji-one (installed, enabled)
	* nodebb-plugin-emoji-twitch (installed, disabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-registration-verify (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-plugin-sso-facebook (not installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, enabled)
	* nodebb-theme-persona (installed, disabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** redis
- **Database version:** Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

- **Exact steps to cause this issue:**

	1. First I respond to a post
	2. Then, I clicked "upload image"
         3. Then I upload a jpg

- **What you expected:**
I expect the jpg to show up in my post editor

- **What happened instead:**

Instead, I get this error in my browser console:

POST http://laythemeforum.com:4567/api/post/upload net::ERR_EMPTY_RESPONSE
GET http://laythemeforum.com:4567/assets/templates/alert.js?v=bp37sui2n9s net::ERR_CONNECTION_REFUSED
Unable to load template: alert
Uncaught Error: Script error for "/assets/templates/alert.js"
http://requirejs.org/docs/errors.html#scripterror
    at F (require.js:7)
    at HTMLScriptElement.onScriptError (require.js:30)
socket.io.js:7 GET http://laythemeforum.com:4567/socket.io/?EIO=3&transport=polling&t=N0Vov_b net::ERR_CONNECTION_REFUSED
GET http://laythemeforum.com:4567/assets/uploads/system/favicon.ico?v=bp37sui2n9s 404 (Not Found)

**Comment by aunruh** [comment]
I just updated to NodeBB 1.13.2

Now I get this error:

> Error
Something went wrong installing the "sharp" module /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/arminunruh/nodebb/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16) - Remove the "node_modules/sharp" directory then run "npm install --ignore-scripts=false --verbose" and look for errors - Consult the installation documentation at https://sharp.pixelplumbing.com/install - Search for this error at https://github.com/lovell/sharp/issues

When I do the above, I get this:

sudo npm install --ignore-scripts=false --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--ignore-scripts=false',
npm verb cli   '--verbose' ]
npm info using npm@6.13.4
npm info using node@v10.18.1
npm verb npm-session aa13aa8abcca75bf
npm info lifecycle nodebb@1.13.2~preinstall: nodebb@1.13.2
npm timing stage:loadCurrentTree Completed in 4188ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 74ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 2183ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2219ms
npm timing stage:loadIdealTree Completed in 5395ms
npm timing stage:generateActionsToTake Completed in 208ms
npm verb correctMkdir /home/arminunruh/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/arminunruh/.npm/_locks/staging-845a84657de48bae.lock for /home/arminunruh/nodebb/node_modules/.staging
npm timing action:extract Completed in 140ms
npm timing action:finalize Completed in 7ms
npm timing action:refresh-package-json Completed in 12ms
npm info lifecycle sharp@0.24.0~preinstall: sharp@0.24.0
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.24.0
npm timing action:build Completed in 2ms
npm info lifecycle sharp@0.24.0~install: sharp@0.24.0

> sharp@0.24.0 install /home/arminunruh/nodebb/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/arminunruh/.npm/_libvips/libvips-8.9.0-linux-x64.tar.gz
prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install info looking for cached prebuild @ /home/arminunruh/.npm/_prebuilds/39f48e-sharp-v0.24.0-node-v64-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/arminunruh/.npm/_prebuilds/39f48e-sharp-v0.24.0-node-v64-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/arminunruh/nodebb/node_modules/sharp/build/Release/sharp.node
prebuild-install info unpack required /home/arminunruh/nodebb/node_modules/sharp/build/Release/sharp.node successfully
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.24.0~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.24.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/arminunruh/nodebb/node_modules/sharp/node_modules/.bin:/home/arminunruh/nodebb/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
npm verb lifecycle sharp@0.24.0~install: CWD: /home/arminunruh/nodebb/node_modules/sharp
npm timing audit submit Completed in 641ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 641ms
npm timing audit body Completed in 2ms
npm timing action:install Completed in 1570ms
npm info lifecycle sharp@0.24.0~postinstall: sharp@0.24.0
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /home/arminunruh/.npm/_locks/staging-845a84657de48bae.lock for /home/arminunruh/nodebb/node_modules/.staging
npm timing stage:executeActions Completed in 1786ms
npm timing stage:rollbackFailedOptional Completed in 6ms
npm info linkStuff nodebb@1.13.2
npm info lifecycle nodebb@1.13.2~install: nodebb@1.13.2
npm info lifecycle nodebb@1.13.2~postinstall: nodebb@1.13.2
npm info lifecycle nodebb@1.13.2~prepublish: nodebb@1.13.2
npm info lifecycle nodebb@1.13.2~prepare: nodebb@1.13.2
npm timing stage:runTopLevelLifecycles Completed in 12561ms
npm verb saving []
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

added 1 package from 61 contributors and audited 4223 packages in 14.247s

30 packages are looking for funding
  run `npm fund` for details

found 12 vulnerabilities (2 low, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 15827ms
npm info ok

**Comment by pitaj** [comment]
Looks like you followed the instructions and they worked. Have you tried running `./nodebb build` and restarting nodebb?

**Comment by aunruh** [comment]
Hey,
I realized if I disable the plugin:

"nodebb-plugin-registration-verify"

Then the error disappears.

**Comment by barisusakli** [comment]
This could be related, https://community.nodebb.org/topic/14565/can-t-upload-logo what OS are you using?

**Comment by aunruh** [comment]
Hey 

After disabling the plugin "nodebb-plugin-registration-verify" it all worked again.
