### ISSUE TITLE
getOwnersAndMembers doesnt respect stop

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#8154]
getOwnersAndMembers only uses the passed stop argument for getting members but when it is concatenated with owners it can cause the returned array to exceed the stop number. This can result in the members being bigger than the membersNextStart value when getting group data.

Quick fix would be to set the membersNextStart to members.length instead of stop + 1

https://github.com/NodeBB/NodeBB/blob/ef964b11a866850fecf6600d19496e8ce9c4c2ce/src/groups/index.js#L131

or slice the result of getOwnersAndMembers to the stop value

https://github.com/NodeBB/NodeBB/blob/ef964b11a866850fecf6600d19496e8ce9c4c2ce/src/groups/index.js#L159

**Comment by barisusakli** [comment]
Hmm, looks like this function needs rethinking since it also doesn't work in the unlikely case of having more than `stop - start + 1` owners.

**Comment by uplift** [comment]
Relooking at it, I dont think my fixes would work anyway with SocketGroups.loadMoreMembers as that doesnt take into account the owners when getting the next set

https://github.com/NodeBB/NodeBB/blob/ef964b11a866850fecf6600d19496e8ce9c4c2ce/src/socket.io/groups.js#L341-L351

**Comment by barisusakli** [comment]
Yeah it's a bit more complicated to fix, since the owners are also in the group members set.
