### ISSUE TITLE
sub-categories show "no new posts" if the most recent post is moved to another category

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#8157]
sub-category shows "no new posts" if the most recent post is moved to another sub-category...

![Screen Shot 2020-02-11 at 9 55 56 AM](https://user-images.githubusercontent.com/52054408/74248429-902ed000-4cb5-11ea-9bec-d6b861f7171e.png)

https://community.nodebb.org/topic/14135/no-new-posts-after-spam-user-is-deleted/5

**Comment by barisusakli** [comment]
Can you post reproduction steps?

**Comment by AliCihan** [comment]
> Can you post reproduction steps?

* A new topic is created by userX under sub-category A
* An admin moved the topic into sub-category B
* Then, admin merged the topic into an old relevant topic
* New topic created by UserX is automatically deleted after merging
* Even after the topic is purged, it shows as "No new posts" in the corresponding sub-category
