### ISSUE TITLE
Members cannot unfollow banned users

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8167]
Hi, as you know when a member is banned, others who followed her cannot unfollow her. What is the reason?

**Comment by julianlam** [comment]
This is likely a bug, thanks for reporting :smile:

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/802b1e8bc03e07783dd20d60504673718580bd43#diff-f1bbe0ff71c47be6cbe0f16ba56b3326
