### ISSUE TITLE
Custom homepage route broken

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/NodeBB#8168]
- **NodeBB version:** Whatever's on community.nodebb.org February 18th, 2020
- **NodeBB git hash:** 
- **Exact steps to cause this issue:**
Set my custom homepage:
![image](https://user-images.githubusercontent.com/13367628/74835786-1a95b600-52ec-11ea-85ba-246f1a9339f6.png)

- **What you expected:**
Using community.nodebb.org I see the NodeBB development category.
- **What happened instead:**
![image](https://user-images.githubusercontent.com/13367628/74835849-38fbb180-52ec-11ea-9522-f7276b424d8a.png)

Original discussion at TDWTF here:
https://what.thedailywtf.com/topic/27053/custom-homepage-broken

**Comment by boomzillawtf** [comment]
And I discovered that categories are now in the dropdown so I don't have to use a custom route:
![image](https://user-images.githubusercontent.com/13367628/74841025-f939c780-52f5-11ea-9b45-94439f5cbbd3.png)
Except...
![image](https://user-images.githubusercontent.com/13367628/74841042-0060d580-52f6-11ea-8387-a9094f3dfcab.png)

**Comment by julianlam** [comment]
Regression via b0f3e48ac2ede6737e22f333ae6d7bbde126f16a
