### ISSUE TITLE
unable to open nodebb menu on mobile

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#8172]
version:  1.13.2
  Node ver: v12.14.1
  git hash: 71f4607db4e2252995d488b1968f7e9bb1d97efc

  database: mongo
(node:34913) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:34913) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:34913) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
        version: 4.2.3
        engine:  wiredTiger

Pageviews, last 24h (min: 567  max: 2587)

![image](https://user-images.githubusercontent.com/9453178/75044679-5476e000-54d7-11ea-8065-a04d6aa0b3d1.png)

no errors on error log:
![image](https://user-images.githubusercontent.com/9453178/75044859-8daf5000-54d7-11ea-982b-1c851d30f142.png)

**Comment by mohammadhassan99** [comment]
Any ideas?
@julianlam @barisusakli
