### ISSUE TITLE
impose restrictions on choosing username

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8194]
Hi, Some of users have underline ```_``` in first character of the username. For example ```_User_``` .
Tagging these kind of usernames are difficult and even impossible. Please impose specific restrictions on choosing username characters.

**Comment by barisusakli** [comment]
It seems to work fine here https://community.nodebb.org/post/77474

**Comment by mohammadhassan99** [comment]
@barisusakli Does your Forum use markdown as an editor?

**Comment by barisusakli** [comment]
Yes we use `nodebb-plugin-markdown`

**Comment by barisusakli** [comment]
Yeah seems like mentions for user names that start with double underscores are broken. Could be related to markdown plugin interfering since __<username>__ gets bolded. @julianlam

**Comment by mohammadhassan99** [comment]
Exactly 👌
