### ISSUE TITLE
In-progress posts resurrected from localStorage should show without visiting the topic and trying to start a new reply

### ISSUE THREAD

**Issue by Tsaukpaetra** [NodeBB/NodeBB#8197]
- **NodeBB version:** community.nodebb.com
- **NodeBB git hash:** 🤷‍♂ 
- **Installed NodeBB Plugins:** N/A
- **Database type:** I'm assuming mongo 😉 
- **Database version:** 🤷‍♂ 
- **Exact steps to cause this issue:**
1. Initiate a reply to a topic
2. Type enough that it gets saved into localStorage
3. Refresh.
4. Notice there's no indication that your work has been saved.
5. Attempt to start replying again (either by reply or quote).
6. Notice your action is basically ignored in favor of resurrecting the prior in-progress post.
7. Shrug and move on.

- **What you expected:** in-progress posts in localStorage should show up as the little task bar bubbles, and in all respects act as an in-progress post.

- **What happened instead:** the page "forgot" I had posts until I manually navigated back to the topic and happened to initiate a reply. Additionally, weird things happened with multiple composer windows, including forgetting what was actually in one of the posts...

localStorage after opening two composers in two topics and typing some stuff:
![image](https://user-images.githubusercontent.com/1989056/76138593-01d51200-6007-11ea-9c8c-7a90f86ac3fa.png)

This data is still available after a refresh, and triggering their composers does not alter the localStorage contents. Interestingly enough, the composer doesn't realize it's modified in the reloaded instance, so you can click "Discard" and it immediately does so without the confirmation, but that's another bug.

I'm also confused why the composers don't get unique IDs, but that's also (probably) irrelevant...

**Comment by julianlam** [comment]
Hm, definitely seems like a bunch of bugs for sure. These all used to work (or at least, I wrote the code for them to work) but they have regressed for whatever reason.

* [ ] Drafts should automatically come back on page reload
* [ ] Save icon should show up when draft is saved (it does right now, just once... but never again, oddly)
* [ ] A post reloaded from localStorage should be marked as "changed" and not discard instantly when the discard button is clicked

**Comment by julianlam** [comment]
Also:

* nodebb/nodebb-plugin-composer-default@e479fbe57f234def9b6fd53e297635d4482aa700
* nodebb/nodebb-plugin-composer-default@6fd3416030fb8c9165da95f4febdcc2aa9aa113d
