### ISSUE TITLE
Ability to choose what notifications can users receive (via Email)

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8200]
Hi, I think it would be great if Admin can choose what notification can users receive via Email. Because when users choose to receive emails, it costs a lot of money and we cannot afford it.

![image](https://user-images.githubusercontent.com/31972226/76165281-fc90d800-616a-11ea-8593-266f5715db79.png)

**Comment by mohammadhassan99** [comment]
Any ideas?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/5644
