### ISSUE TITLE
Not able to send invitation

### ISSUE THREAD

**Issue by magnusvhendin** [NodeBB/NodeBB#8203]
- **NodeBB version:** 1.13.2
- **NodeBB git hash:** 71f4607db4e2252995d488b1968f7e9bb1d97efc

- **Installed NodeBB Plugins:** 
	* nodebb-plugin-composer-default (installed, disabled)
	* nodebb-plugin-composer-quill (installed, disabled)
	* nodebb-plugin-composer-redactor (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emailer-sendgrid (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, disabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-ns-custom-fields (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, disabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-persona (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo

- **Database version:** 4.2.3

- **Exact steps to cause this issue:**
1. Go to /admin/manage/users
2. Click INVITE (obviously this requires the forum to have registrations set to invitation only, we have admin invites only).
- **What you expected:**
I expected to be able to send an invitation to an email.
- **What happened instead:**
The page refreshes and no more modal. I have been digging around in the source code and noticed that there is now a surrounding form tag. This was not present in previous releases. The button itself has no type, so it's treated as a submit. It should probably be set to type="button".

**Comment by barisusakli** [comment]
@magnusvhendin thanks for reporting.
