### ISSUE TITLE
Feature Request: Notification setting for group chats

### ISSUE THREAD

**Issue by Christoph142** [NodeBB/NodeBB#8204]
Hi there,
right now I'm having the problem that I can either
- choose to not get mail notifications for messages and hence don't realize somebody messaged me for days _or_
- choose to get mail notifications and get spammed by large groups

So either way it's bad.
Can we please have a distinction in settings for direct and group messages?

**Comment by julianlam** [comment]
Currently we have `notificationType_new-chat`, which is used for all kinds of chat message notifications. It seems fairly trivial to add a new one for just group chats, to allow for finer-grained control over these notifications :+1: 

@samt

**Comment by Christoph142** [comment]
Would be very much appreciated. I'm still facing the same dilemma.
