### ISSUE TITLE
How to get the direct URL for verify_mail

### ISSUE THREAD

**Issue by KyonCN** [NodeBB/NodeBB#8211]
Hi, how can i get the direct URLS for verify_email and invitation email. Because the gmail will block my button with the current tpls and then i can't click.  It looks like spam.
So I want to write the direct links in the mails.

Thank you !

**Comment by julianlam** [comment]
Hello @KyonCN -- for the `invitation.tpl`, you can use `{registerLink}` to retrieve the link for accepting the invitation. 

It is `{confirm_link}` for the email verification email. Let me know if you need more help!

**Comment by KyonCN** [comment]
> Hello @KyonCN -- for the `invitation.tpl`, you can use `{registerLink}` to retrieve the link for accepting the invitation.
> 
> It is `{confirm_link}` for the email verification email. Let me know if you need more help!

Thank you , I solve it !
