### ISSUE TITLE
Ability to (un)set noindex meta tag on specific topics (topic-level setting)

### ISSUE THREAD

**Issue by dovid-lt** [NodeBB/NodeBB#8212]
Sometimes I get requests from people to block certain topic information from Google results, but not remove the content.

It's not common, but when you need it, it's hard to find a solution!

I would be very happy for any such option.

**Comment by julianlam** [comment]
If you need to hide a specific page from Google, the easiest place would be to add an entry directly into the `robots.txt` file. Let me know if that is sufficient. Thanks!

**Comment by julianlam** [comment]
(The `robots.txt` file can be customized in the ACP)

**Comment by dovid-lt** [comment]
[Google say](https://support.google.com/webmasters/answer/9689846)


> Do not use robots.txt as a blocking mechanism.


see also [Google to stop supporting noindex directive in robots.txt](https://searchengineland.com/google-to-stop-supporting-noindex-directive-in-robots-txt-319003)

**Comment by julianlam** [comment]
@dovid-lt Thank you for the interesting articles. Note alternative # 4:

> (4) Disallow in robots.txt: Search engines can only index pages that they know about, so blocking the page from being crawled often means its content won’t be indexed. While the search engine may also index a URL based on links from other pages, without seeing the content itself, we aim to make such pages less visible in the future.

You should still be able to restrict access to the pages by using the disallow directive in `robots.txt`. This is an acceptable workaround until a proper `noindex` feature is scoped out and built. Thank you.

**Comment by dovid-lt** [comment]
Thanks @julianlam, you're right.
There is another significant drawback to using `robots.txt` which is public and transparent to the world. It is many times worse than the search results ...

**Comment by barisusakli** [comment]
GIve this a try https://github.com/barisusakli/nodebb-plugin-topic-noindex

It should add an option into the topic tools that will toggle the meta tag.

Plugin will add this to <head>
`<meta name="robots" content="noindex" />`
