### ISSUE TITLE
Filter Hook in getUserDataByUserSlug

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#8230]
Hi,

getUserDataByUserSlug seems to be used by all the Account Profile Pages. Would it be possible to add a filter hook at the end of this function to manipulate the data it gets. I'm currently doing it in a dozen different filter:[PAGE].build hooks for each of the profile pages but be nicer to just have one call in plugin.json to manipulate the data?

https://github.com/NodeBB/NodeBB/blob/740e598a5d220020808737ea51c5d6c1a5da016f/src/controllers/accounts/helpers.js#L18

**Comment by uplift** [comment]
Should the name of the filter be filter instead of filters? Im on an old version so might not be an issue on latest nodebb with name but I get unknown hook type warning with filters

**Comment by julianlam** [comment]
He's already fixed this one :)

https://github.com/NodeBB/NodeBB/commit/e93578b81d9935394d2369c43929b2bcd29f1dbd
