### ISSUE TITLE
Cancelling registration from /register/complete causes session mismatch that cannot be dismissed (error:invalid-session-text)

### ISSUE THREAD

**Issue by glassdimly** [NodeBB/NodeBB#8232]
Here's the error after all registration cancellations: "It looks like your login session is no longer active, or no longer matches with the server. Please refresh this page."

Here are the steps to replicate:
1. Register a user, but don't confirm email, and don't accept TOS at /register/complete
2. Cancel registration
3. Get error "It looks like your login session is no longer active, or no longer matches with the server. Please refresh this page."
4. Logout but error cannot be dismissed until user navigates to a new page.

I have replicated this on a stock install of Nodebb using mongo with no settings changed, with `HEAD` at commit id 455d42bcfaee0bc8a0be4402389ab47030f39a85.

Oh, and this is in Firefox Developer edition on a Mac.

**Comment by glassdimly** [comment]
The problem here is that server-side `req.signedCookies[nconf.get('sessionKey')]` in `src/session.io/index.js` line 184 returns the same key even after client-side `window.location.reload()` in `public/src/app.js` line ~268. Then, `getSession()` returns the null object for that deleted/invalidated login.

I don't really have time to keep digging and make a proper patch.

But since redirecting to another page works, I can just bounce the user to the login page after the error is triggered and add a little text about logging in. Yes, it's not translated, but the forum is english-only. So works for me. And others could leave off the note.

```
                // see @https://github.com/NodeBB/NodeBB/issues/8232
		require(['translator'], function (translator) {
			translator.translate('[[error:invalid-session-text]]', function (translated) {
				bootbox.alert({
					title: '[[error:invalid-session]]',
					message: translated + ' Log in, or continue browsing as anonymous.', // add request to log in.
					closeButton: false,
					callback: function () {
						app.logout(); // force logout
						window.location.href = '/login'; // redirect to login page
					},
				});
			});
		});
```

**Comment by pitaj** [comment]
FYI if you use app.alertError it will handle translations for you.

**Comment by julianlam** [comment]
Thanks @glassdimly -- appreciate the triage steps -- the above commit should resolve :smile:
