### ISSUE TITLE
Feature request: search subforum

### ISSUE THREAD

**Issue by felagund** [NodeBB/NodeBB#8233]
(Coming from vivaldi.net)

A feature (an easily accessible link) that would search currently opened forum and its subforums would be very useful. As it stands now, I always have to specify which forum I want to search.

**Comment by felagund** [comment]
Thank you! Now I just need to wait until it forum.vivaldi.net uppgrades:-).

**Comment by felagund** [comment]
Hm, actually, this is not really what I wanted. If I understand it correctly this commig added the checkbox in he following screenshot:
![Screenshot from 2021-01-26 19-30-27](https://user-images.githubusercontent.com/1218098/105888244-09c9e600-600d-11eb-9b6f-6ad97230e8e5.png)

This is good for advanced search, but what I would lobe to have is a easy way to search a subforum FROM a subforum. Something like this:
![Screenshot from 2021-01-26 19-32-49](https://user-images.githubusercontent.com/1218098/105888689-94aae080-600d-11eb-9e14-af513f3771a3.png)
Some other forums have this and it is a really useful feature.

**Comment by felagund** [comment]
(if a checkbox "search only currently open category and its subcategories" appeared when global search is focused, this would work too)

**Comment by barisusakli** [comment]
When you use the search input in the header inside a category it searches the current category and it's children.

![image](https://user-images.githubusercontent.com/2583394/105892503-f3f1fc00-5fdf-11eb-9e2e-8e4e1c3a6d53.png)

Unchecking that checkmark searches the entire forum

**Comment by felagund** [comment]
Aha, perfect! It just seems Vivaldi has not updated then and I misunderstood the source code of that change:-).
