### ISSUE TITLE
docker installation doesn't work out of the box

### ISSUE THREAD

**Issue by czco** [NodeBB/NodeBB#8236]
![2020-04-07_02-45-32](https://user-images.githubusercontent.com/36222477/78655181-802d0a00-787a-11ea-98ef-1d4ffcee45c5.gif)

node bb version : latest as pf April 7th 2020
docker version : latest installed using curl -sSL https://get.docker.com | sh

**Comment by dnk8n** [comment]
Why would you expect this to work? It clearly says in the comment that the templates require a reverse proxy to work.

for local dev you should add section

```
ports:
  - 4567:4567
```

Only then would http://localhost:4567 work

**Comment by czco** [comment]
@dnk8n thank you for your response but we've moved on to flarum due to some other issues found with nodebb
