### ISSUE TITLE
Fixing mongodb@2.2.36 vulnerability

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#8237]
- currently, the indirect dependency, `mongodb@2.2.36`, has a DoS vulnerability
- this is because `socket.io-adapter-mongo` has a dependency on `mubsub@1.4` which uses an outdated `mongodb` module
- [x] we should re-publish `mubsub-nbb` as `@nodebb/mubsub`  
  https://www.npmjs.com/package/@nodebb/mubsub
- [x] PR [socket.io-adapter-mongo](https://github.com/lklepner/socket.io-adapter-mongo) to use `@nodebb/mubsub`  
  lklepner/socket.io-adapter-mongo#17
- [x] after PR is merged and released, update to latest `socket.io-adapter-mongo`

**Comment by julianlam** [comment]
Thanks @pitaj :smile:
