### ISSUE TITLE
NodeBB sends notification for deleted posts/topics 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8249]
- **NodeBB version:** 1.13.2
- **Database type:** mongo

Hi, when mods or admin move a deleted post or deleted topic to another category, a notification will be sent to the owner of the topic/post. I think it can be better to not send notification for deleted posts. Because maybe we want them to not being notified. It can be optional for to send notification for these kind of topics/posts too.

**Comment by julianlam** [comment]
:+1: I don't think this needs to be made an option, simply checking if the topic is deleted (and then not notifying **or** setting the topic as moved) should suffice.
