### ISSUE TITLE
TypeError: i.hasOwnProperty is not a function from buildAvatar on img avatar after jquery update to 3.5.0

### ISSUE THREAD

**Issue by glassdimly** [NodeBB/NodeBB#8252]
We were getting that error and it was causing "new topic" to fail (do nothing) on the topic listing page, replicated on Firefox and Chrome. Being called from my modified persona theme in `templates/partials/topics_list.tpl`

```
<a href="{config.relative_path}/user/{topics.teaser.user.userslug}">{buildAvatar(topics.teaser.user, "24", true, "not-responsive")}</a>
```

```
// Line ~1507 of node_modules/bootstrap/dist/js/bootstrap.js    
var dataAttributes = this.$element.data()

    for (var dataAttr in dataAttributes) {
       // I added this for debugging
    	if (!dataAttributes.hasOwnProperty) {
    		console.log('this.$element', this.$element);
			}
     // I made this into an "else if", previously it was an "if"
      else if (dataAttributes.hasOwnProperty(dataAttr) && $.inArray(dataAttr, DISALLOWED_ATTRIBUTES) !== -1) {
        delete dataAttributes[dataAttr]
      }
    }
```
This "fixes" it in `public/src/modules/helpers.js` ~290
```
function buildAvatar(userObj, size, rounded, classNames, component) {
	var attributes = [
		'alt="' + userObj.username + '"',
		'title="' + userObj.username + '"',
		// Removed because of TypeError: i.hasOwnProperty is not a function
		// 'data-uid="' + userObj.uid + '"',
	];

```

I really have no idea why the string created by `buildAvatar` with `data-uid` could cause this problem. Apparently [some objects created with](https://github.com/domchristie/humps/issues/35) `Object.create(null);` don't have `hasOwnProperty`.

No idea if this is specific to my build--can't imagine why.

But I thought I'd post this issue along with my workaround for others.

**Comment by barisusakli** [comment]
This is weird I am not getting this issue on latest master/persona.

What modifications did you make to persona? Does it work if you use unmodified version of persona?

**Comment by glassdimly** [comment]
Yeah, it just started happening. I made various changes, but no changes to the files in question. I really can't say why this would happen. I'll dig around though.

**Comment by barisusakli** [comment]
Hmm looks like jquery 3.5.0 was released 3 days ago, that might be the reason try `npm i jquery@3.4.1` and see if it goes away.

**Comment by barisusakli** [comment]
Seems like on 3.4.1 this works
```
$('#myEl').data().hasOwnProperty('test');
```
It is undefined on 3.5.0.

**Comment by barisusakli** [comment]
https://github.com/jquery/jquery/issues/4665

**Comment by glassdimly** [comment]
Yeah, perfect. I tested that `npm i jquery@3.4.1` fixes this.

**Comment by julianlam** [comment]
jQuery now pinned to 3.5.1
