### ISSUE TITLE
ACP admins-mods allPrivileges has unnecessary back-and-forth

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8271]
In https://github.com/NodeBB/NodeBB/commit/035f624758dc4d88b32e5aecebc881d1d0fbb073 implicit moderation privileges were removed.

In order to still allow the admins-mods page to work, it seems like server-side passes a list of privileges to the client-side, so that the socket.io call to grant moderator status also grants these additional privileges that used to be implicit:

https://github.com/NodeBB/NodeBB/blob/4eafe0f0577c8f8ef77c1c8cea57c8c20bf4426f/public/src/admin/manage/admins-mods.js#L90-L95

Instead of this back-and-forth, a special case can be made for the mod privilege **server-side**, so adding a user to the `moderate` group also adds them to the appropriate user privileges groups

**Comment by barisusakli** [comment]
I took a look at this it becomes more complicated to add that special check, gonna leave it as is.
