### ISSUE TITLE
wrong post is shown when topics are clicked (in the paginated forum)

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#8278]
We use NodeBB 1.13.2, our forum is paginated, 20 posts per page... Here are some of the mistakes we have observed so far (we did not have these problems in 1.12):

* When I click the topic link on recent cards, it opens the first post on the last page, whereas it should take me to the first post I haven't read. 

* When I reply a post on a previous page (40-50 posts earlier), after posting it opens the first post on the last page, whereas it should show me my post. When I change the setting from pagination to scroll, this problem goes away (it shows my reply) since there are no pages... 

* Other members have also complained that when they click certain topics, it takes them a "specific earlier post"/"specific page" rather than the first post that they haven't read...

**Comment by barisusakli** [comment]
Is this happening on https://community.nodebb.org? Can you post a topic from your forum that this happens?

**Comment by AliCihan** [comment]
> Is this happening on https://community.nodebb.org? Can you post a topic from your forum that this happens?

no, in our forum... For example, I have sent two replies today to this topic:

https://yesilkartforum.com/forum/topic/2213/dv2021-bekleme-odas%C4%B1

In both cases, after posting forum opened the top post on the last page rather than my own reply...

**Comment by barisusakli** [comment]
Can you run a query in mongodb to check the post count of the topic?

`db.objects.count({_key: "tid:2213:posts"})`
and
`db.objects.findOne({_key: "topic:2213"}).postcount`

Let me know the output of those commands.

**Comment by freestylemaster** [comment]
@barisusakli 
Hi Baris,
Outputs as following;
15100
15101

**Comment by AliCihan** [comment]
Hi @barisusakli , we have the same problem with this topic... (the same topic ID) 

When we reply, we cannot see the reply right away if it is on the next page... we have to wait others to post more replies... Also, clicking replied posts takes you several post above... 

But this time, we have different outputs...

> db.objects.count({_key: "tid:2213:posts"})
20913
> db.objects.findOne({_key: "topic:2213"}).postcount
20910

How can we fix the discrepancy between outputs for this topic?

**Comment by barisusakli** [comment]
The command to update the topic object is

```
db.objects.update({_key: "topic:2213", {$set: {"postcount": 20910}});
```

Replace `20910` with the actual number from the result of `db.objects.count({_key: "tid:2213:posts"})`

**Comment by barisusakli** [comment]
There was a mistake in the previous query it should be 

`db.objects.update({_key: "topic:2213", {$set: {"postcount": <result> + 1}});`

Replace result with the value from `db.objects.count({_key: "tid:2213:posts"})`

**Comment by freestylemaster** [comment]
> There was a mistake in the previous query it should be
> 
> `db.objects.update({_key: "topic:2213", {$set: {"postcount": <result> + 1}});`
> 
> Replace `<result>` with the value from `db.objects.count({_key: "tid:2213:posts"})`

Thank you Baris. 

This was the output for post number;
> db.objects.count({_key: "tid:2213:posts"})
20917

Updated as following;
db.objects.update({_key: "topic:2213"}, {$set: {"postcount": 20917 + 1}});

The result looks as the following;
> db.objects.count({_key: "tid:2213:posts"})
20917
> db.objects.findOne({_key: "topic:2213"}).postcount
20918

Does this look right to you, if you don't mind confirming please.

**Comment by barisusakli** [comment]
Yes looks good.
