### ISSUE TITLE
Filter topics by uids on getSortedTopics

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8280]
Hi at all,

I'm using the topics.getSortedTopics() to get a list of topics limited to 20 results with some params (term, categories, etc). Another necessity is to filter by a list of uid. 
There are any method?

Thank you

**Comment by barisusakli** [comment]
It's not available in core buy you can use the hook `filter:topics.filterSortedTids`, pass in `uid` in the params to `topics.getSortedTopics` and then use the below hook.

```
myPlugin.filterTopicsFilterSortedTids = async function (hookData)  {
   const uid = parseInt(hookData.params.uid, 10);
   if (!uid) {
       return hookData;
   }
   const topicData = await topics.getTopicsFields(hookData.tids, ['uid', 'tid']);
   hookData.tids = topicData.filter(t => t.uid === uid).map(t => t.tid);
   return hookData;
};
```
 Adjust as necessary. You can pass in an array of uids and just check if t.uid is in that array.

**Comment by andreadragotta** [comment]
And I work! Thanks so much!

I think a wiki with some examples and frequently asked questions would probably be helpful.

Thanks for help.

**Comment by barisusakli** [comment]
We are compiling some at https://community.nodebb.org/category/26/developer-faq, fell free to post this question and your working solution there 👍
