### ISSUE TITLE
Issues in installation doc for Windows

### ISSUE THREAD

**Issue by sylque** [NodeBB/NodeBB#8285]
- **NodeBB version:** v1.13.2
- **NodeBB git hash:** a476d7261b4234820725ab2d13ffe7b34e296dbb
- **Database type:** mongo
- **Database version:** 4.2.6

I'm a newbie with NodeBB. I'm in the process of installing it under Win 10, following the official instructions [on this page](https://docs.nodebb.org/installing/os/windows/).  Here are the issues I found in the page:

## Issue 1

> **Configure a service for the mongod server**
> ...
> 3. Create a config file (C:\MongoDB\mongod.cfg) defining those paths 
`systemLog: destination: file path: C:\MongoDB\logs\mongod.log storage: dbPath: C:\MongoDB\data\db`

The above doesn't work because the config file must be formatted in a strict way. This should be replaced by something like:
> **Configure a service for the mongod server**
> ...
> 3. Create a config file (C:\MongoDB\mongod.cfg) formatted like this:
>```
>systemLog:
>  destination: file 
>  path: C:\MongoDB\logs\mongod.log 
>storage:
>  dbPath: C:\MongoDB\data\db
>```

## Issue 2

> **Configure a service for the mongod server**
> ...
> 4. Install the MongoDB service `bash mongod.exe --config "C:\MongoDB\mongod.cfg" --install`

This doesn't work for me, I get a `cannot execute binary file` error. However, the command below works like a charm:

> **Configure a service for the mongod server**
> ...
> 4. Install the MongoDB service `mongod --config "C:\MongoDB\mongod.cfg" --install`

## Issue 3

> **Installing NodeBB**
> ...
> A series of questions will be prompted with defaults in parentheses. The default settings are for a local server listening on the default port 4567 with a MongoDB instance listening on port 27017. When prompted be sure to configure the MongoDB username and password that was configured earlier for NodeBB.

This is a bit misleading, as we know very well the MongoDB username! (it was defined above as `nodebb`) I would rather say something like:

> **Installing NodeBB**
> ...
> A series of questions will be prompted with defaults in parentheses. The default settings are for a local server listening on the default port 4567 with a MongoDB instance listening on port 27017. When prompted for the MongoDB connection URI, let it blank. When prompted for MongoDB username, enter `nodebb`. When prompted for the Password of your MongoDB database, enter the password you chose earlier for user `nodebb`.

**Comment by julianlam** [comment]
Thanks for the review, I've updated the docs to better reflect your changes (most of it was formatting issues, which have been resolved).
