### ISSUE TITLE
user count mismatch

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#8287]
We have different user counts under "users" / "post count" / "reputation"... 

> db.objects.findOne({_key: "global"}).userCount;
7935
> db.objects.count({_key: "users:joindate"});
7935
> db.objects.count({_key: "users:postcount"});
7959
> db.objects.count({_key: "users:reputation"});
7969

Please check this topic: 
https://community.nodebb.org/topic/14724/is-this-a-bug-users-ranking-and-reputation

**Comment by barisusakli** [comment]
"users:reputation" can go up if a user account gets deleted and then their posts gets upvoted.
Below `uid 5622` is a deleted account but their posts were upvoted after their account was deleted.

```
> db.objects.findOne({_key: "user:5622"})
{
        "_id" : ObjectId("56deb137685e7394163001fb"),
        "_key" : "user:5622",
        "reputation" : 5
}
> db.objects.findOne({_key: "users:joindate", value: "5622"});
null
> db.objects.findOne({_key: "users:reputation", value: "5622"});
{
        "_id" : ObjectId("56deb137685e7394163001fc"),
        "_key" : "users:reputation",
        "value" : "5622",
        "score" : 5
}
```

Not sure how `users:postcount` goes up though.
