### ISSUE TITLE
2 users with 1 username and Email

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8291]
- **NodeBB version:** 1.13.2
- **Database type:** Mongo

Hi, I've seen two users listed in ```/users``` but they are same. With same username and same Email. They also have different UIDs. It means that NodeBB created two users.

![2020-05-04_151406](https://user-images.githubusercontent.com/31972226/80961716-c1382000-8e20-11ea-99ca-6cf76cc687b7.jpg)

**Comment by julianlam** [comment]
1. Is this a new user?
1. Was the user created via SSO plugin, and if so, which one?

Can you provide reproduction steps as to how to create two users at the same time?

**Comment by mohammadhassan99** [comment]
@julianlam 
1.Yes, I was looking at the list of new users and I accidentally see it.
2- Signing up is just available through Google account.

I don't know what happened. I just saw 2 users with 1 Email. That's strange.

**Comment by mohammadhassan99** [comment]
@julianlam 
1.Yes, I was looking at the list of new users and I accidentally see it.
2- Signing up is just available through Google account.

I don't know what happened. I just saw 2 users with 1 Email. That's strange.

**Comment by AliCihan** [comment]
@julianlam this happened us before. A person signed up one time but forum created two users with the same name, however only the latter one is used by forum... Here you can see:

![Screen Shot 2020-05-05 at 3 23 13 PM](https://user-images.githubusercontent.com/52054408/81107211-ce1e4780-8ee4-11ea-9201-26558c1a834a.png)

I asked the guy when this happened, he said he signed up only one time with regular sign up (no SSO).

**Comment by julianlam** [comment]
Thanks -- I don't know if we can resolve if we cannot reproduce -- we already did fix one similar issue before (which was caused by SSO), though if you can come up with reproduction steps that allow me to see this issue happening then I can try to fix, otherwise it might be hard to figure out.

**Comment by mohammadhassan99** [comment]
@julianlam maybe we can ask users to tell their experience while creating the account.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/8415
