### ISSUE TITLE
"Invalid Data" error in chat on "up arrow" keypress if no message was sent to that user

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#8293]
- **NodeBB version:** Whatever's installed on community.nodebb.org ;-) 
- **Exact steps to cause this issue:**
1. Receive a chat message from a new user that you haven't send any chat messages to.
2. Open the chat window and maximize it (the bug does not reproduce in modal version of the chat window).
3. Focus on the message input field.
4. Press UP arrow key.
- **What you expected:**
Nothing should happen
- **What happened instead:**
An error message tooltip pops up every time I press the arrow key:

![obraz](https://user-images.githubusercontent.com/591754/81048934-8b954480-8ebd-11ea-98d0-0cec757159f7.png)

I assume this is because NodeBB tries to fetch the last message that I sent to that person so that I can edit it (that's how it works in chats where both users have exchanged messages) but fails, since I have not send anything to that particular contact, yet.

**Comment by julianlam** [comment]
Ah, classic null case bug :anguished:
