### ISSUE TITLE
NodeBB doesn't show online user's session

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8301]
- **NodeBB version:** 1.13.2
- **Database type:** Mongo

Hi, when I go to ```/info``` page, I don't see user's session for almost all of them. Even though they are online.

**Comment by barisusakli** [comment]
Can you check the database if this user has any session entries? In mongodb run this
`db.objects.find({_key: "uid:<uid_of_user>:sessions"});`

**Comment by barisusakli** [comment]
There seems to be an issue though, I am looking at an online user's info page and it only shows one session that is old.

![image](https://user-images.githubusercontent.com/2583394/81482556-e7d1ce80-9205-11ea-9e54-f1426354bc5e.png)
