### ISSUE TITLE
SyntaxError while installing nodebb

### ISSUE THREAD

**Issue by jrajagopal** [NodeBB/NodeBB#8304]
NodeBB version: 1.13.3
NodeBB git hash: 5db31e7e9548760a3d0dce15504cc1729f2347af
Installed NodeBB Plugins: Not installed yet
Database type: mongo
Database version: 4.2.6
OS: Ubuntu 16.04.06 LTS (xenial)

I followed the steps outlined in https://docs.nodebb.org/installing/os/ubuntu/. I made it all the way to "./nodebb setup". Initially it said "/usr/bin/env node" not found; to get around it, I symlinked to "/usr/bin/env/nodejs".

When I ran "./nodebb setup", I got the following syntax error. At the moment, I am stuck dead in the water.

/home/ubuntu/tools/nodebb/src/cli/package-install.js:23
	const packageContents = { ...oldPackageContents, ...defaultPackageContents, dependencies: { ...oldPackageContents.dependencies, ...defaultPackageContents.dependencies } };
	                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/tools/nodebb/src/cli/index.js:8:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by jrajagopal** [comment]
I went through the code one more time. Though I am not a js developer, it is actually easy to read, and I don't see anything wrong in the way that line was written. What am I missing? Cheers for thoughts!

**Comment by pitaj** [comment]
What is the output of `node -v`?

I'm guessing your version of node is too old.

**Comment by jrajagopal** [comment]
@pitaj 
> What is the output of `node -v`?
4.2.6
> 
> I'm guessing your version of node is too old.
How does that explain the syntax error?

**Comment by jrajagopal** [comment]
@pitaj Yes I did have the wrong node version. Thanks. I can close this out now.
