### ISSUE TITLE
error:invalid-files when attaching images to post

### ISSUE THREAD

**Issue by elelel** [NodeBB/NodeBB#8310]
v13.3.3 at 5db31e7e9548760a3d0dce15504cc1729f2347af

error:invalid-files is reported when attempting to attach images to a post.
This is triggered by this check:
https://github.com/NodeBB/NodeBB/blob/bfad457275ef5f2d8ac16f6a8bee5c869a3df46f/src/middleware/index.js#L106

req.files.files is undefined in this case. It's probably caused by the posting code, but I don't know where to look for it.

- **NodeBB version:** 
- **NodeBB git hash:** 

- **Installed NodeBB Plugins:** 

- **Database type:** mongo, redis, or postgres
- **Database version:** 

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

**Comment by barisusakli** [comment]
Are you using nodejs 14? It is not supported yet. See  https://github.com/expressjs/connect-multiparty/issues/29

**Comment by elelel** [comment]
Indeed this was the problem. Current NodeJS version in Archlinux official packages is 14.2, system upgrade caused the packages to be upgraded. Downgrading to NodeJS 13.10 and it's dependencies solved the problem. Thank you

**Comment by barisusakli** [comment]
No problem, I will keep this issue open until it is fixed in the upstream dependencies.

**Comment by barisusakli** [comment]
Fixed upstream
