### ISSUE TITLE
Bad state of allowUserHomePage since 1.13.3

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/NodeBB#8311]
Hello !

I upgraded nodebb from 1.13.1 to 1.13.3 and I note a strange thing on /user/****/settings page : it shows now on 1.13.3 settings for homepage but it's not allowed in /admin/general/homepage (it was not showed as I wanted on 1.13.1).

When I look in /api/user/****/settings, it shows "allowUserHomePage":0 on nodebb 1.13.1 and "allowUserHomePage":1 on nodebb 1.13.3 : it seems that setting of /admin/general/homepage is not respected...

Is it a bug ? I understand something wrong ?

Thanks !

**Comment by barisusakli** [comment]
@alfazaz thanks for reporting

**Comment by alfazaz** [comment]
@barisusakli So quick and so great ! Thanks !!!!
