### ISSUE TITLE
Not able to merge / fork topics

### ISSUE THREAD

**Issue by Smilefounder** [NodeBB/NodeBB#8312]
- **NodeBB version:** v1.13.3.
- **Database type:** mongo
- **Exact steps to cause this issue:**
I have tried to merge/fork selected topics but not able to.

**Comment by barisusakli** [comment]
Please provide more info, what happens when you try to fork/merge, any error messages etc?

**Comment by Smilefounder** [comment]
Sorry,
Step 1: select 2 posts
Step 2: click select merge posts the error shown as below:
![image](https://user-images.githubusercontent.com/3785721/81968248-57045400-9646-11ea-9674-8b8b1933be41.png)

**Comment by barisusakli** [comment]
It's just inconsistent UX, try clicking merge topic first and then clicking the topic titles.

**Comment by Smilefounder** [comment]
It work! thanks :)
