### ISSUE TITLE
Several invalid CSRF token errors after upgrade to 1.13.2

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/NodeBB#8328]
- **NodeBB version:** 
1.13.2
- **NodeBB git hash:** 
71f4607db4e2252995d488b1968f7e9bb1d97efc
- **Installed NodeBB Plugins:** 
$ ./nodebb plugins
(node:5291) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:5291) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:5291) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
Active plugins:
	* nodebb-plugin-2factor (installed, enabled)
	* nodebb-plugin-camo (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emailer-mailgun (installed, enabled)
	* nodebb-plugin-emoji (installed, disabled)
	* nodebb-plugin-emoji-android (installed, disabled)
	* nodebb-plugin-emoji-extended (installed, enabled)
	* nodebb-plugin-emoji-one (installed, enabled)
	* nodebb-plugin-giphy (not installed, enabled)
	* nodebb-plugin-iframely (installed, enabled)
	* nodebb-plugin-image-size (installed, disabled)
	* nodebb-plugin-imagemagick (not installed, enabled)
	* nodebb-plugin-imgbed (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-night-mode (installed, enabled)
	* nodebb-plugin-ns-embed (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, disabled)
	* nodebb-plugin-spoilers (installed, enabled)
	* nodebb-plugin-tenor-gif (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-material (installed, enabled)
	* nodebb-theme-persona (installed, disabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)
- **Database type:** mongo
- **Database version:** 
$ mongod --version
db version v3.2.22
git version: 105acca0d443f9a47c1a5bd608fd7133840a58dd
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
- **Exact steps to cause this issue:**
Since upgrading from 1.12.x, a lot of my members have been noticing random problems uploading and enabling 2FA. In the logs it appears that there are a lot of `invalid csrf token` errors, even for logging out:

```
2020-05-14T22:40:17.753Z [5567/32442] - [31merror[39m: /api/post/upload
invalid csrf token
...
2020-05-15T05:58:54.333Z [5567/32442] - [31merror[39m: /logout
invalid csrf token
```
I've taken a look at the cookies stored for the forum and there's one called _csrf that *is* a session cookie, but it expires in a year. Not sure if this is the culprit, but if there's a csrf error, maybe the cookie should be deleted or force the user to log in again? Not sure what the correct course of action is, but having me tell people to log out and log in again doesn't seem like the right one :) 

- **What you expected:**
no invalid CSRF token errors
- **What happened instead:**
invalid CSRF token errors

**Comment by pitaj** [comment]
Could be related to #8142

**Comment by AliCihan** [comment]
I think the problem is figured out, waiting for the solution... I just wanted to add that we are also having the same problem... We did not have this problem in 1.12.2 , after upgrading to 1.13.2 and now 1.13.3 , we had many "invalid CRSF token errors" in logs...

**Comment by julianlam** [comment]
@bdharrington7 Does a logout/login actually resolve the issue for your users? #8142 deals with a server going missing on the server-side, and that causes the "invalid session" modal to keep popping up, so that _might_ not be the same issue...

**Comment by julianlam** [comment]
What do you see here?

![image](https://user-images.githubusercontent.com/923011/82763517-57cf7f80-9dd6-11ea-80db-09de22a706f1.png)

The expiry should be "session", and the domain should be your specific subdomain. I am not certain what happens if a different site (on the naked domain) saved a `_csrf` cookie that expired in a year, but I can imagine that would cause issues... :smile:

**Comment by bdharrington7** [comment]
> Does a logout/login actually resolve the issue for your users?

Yes, for the upload problem, I had the user log out and log in, and they could upload again.

> What do you see here?

`_csrf` is a session cookie, for sure. I think I might have been mistaken about the expiry, it seems that the Chrome extension "edit this cookie" adds that field

![image](https://user-images.githubusercontent.com/4553795/82849653-b1ef4400-9ead-11ea-8b93-8147a87c1e94.png)

I'm not using redis, so a server restart wouldn't have dropped any server tokens.

**Comment by julianlam** [comment]
@bdharrington7 Can you try latest master and let me know if the issue is resolved?

**Comment by bdharrington7** [comment]
Sorry for the delay. I've just switched over to master, now currently at
8f81651e2fd762e2200af86139e6048d49a64b67

I'll ping you here if any other issues pop up. Thanks!
