### ISSUE TITLE
Anchor links on another page

### ISSUE THREAD

**Issue by yakov-isrel** [NodeBB/NodeBB#8363]
There are posts where I use anchor links With the use of this code
`[link name](#anchor-name)`
(It works because of [this plugin](https://github.com/MinecraftForgeFrance/nodebb-plugin-extended-markdown#anchor))
I want to index with links into the anchors
I tried to do https://domain.com/post/1#anchors
It only works on a new tab
Thanks in advance

**Comment by pitaj** [comment]
Ajaxify should handle anchor tags

**Comment by oplik0** [comment]
I can confirm that it does not. Demo on community.nodebb.org:
https://community.nodebb.org/topic/14805/anchor-links-test

If you just click the first link in that post you'll get this:
![image](https://user-images.githubusercontent.com/25460763/83697678-2bdea600-a5ef-11ea-9f32-fbffedbdcd92.png)
If you open [it](https://community.nodebb.org/topic/14643/youtube-embed-test#11) in new tab or by just pasting url into your address bar (bypassing ajaxify) the anchor will work and you'll see this:
![image](https://user-images.githubusercontent.com/25460763/83697803-706a4180-a5ef-11ea-89ee-59dda6dfde06.png)
(well, if you don't block facebook etc. you'll see the video too, but I confirmed that it's reproducible on a chrome install without any addons)

**Comment by barisusakli** [comment]
Updated on our community https://community.nodebb.org/topic/14805/anchor-links-test

The anchor link should work now, althought it messes up with the history so it doesn't take you back if you try to use the back button 🤷

**Comment by julianlam** [comment]
You can use ajaxify.updateHistory for this if you want 🤔
