### ISSUE TITLE
Unprivileged user are able to search for another users

### ISSUE THREAD

**Issue by cryptoethic** [NodeBB/NodeBB#8368]
- NodeBB 1.13.3

When you select in global privilages that user are allowed to search content and are disallowed to search users users are still able to search for other users via advanced search ( example with [nodebb-plugin-dbsearch] plugin).

Reason:

searchController.search checks only for `search:content` permission

I can submit PR to resolve this issue. It should affect both core NodeBB and nodebb-persona-theme.

My suggestion is to check both permissions and return permissions dictionary for persona to render "Users" field in select or not.

![image](https://user-images.githubusercontent.com/44468286/83744268-25d2de80-a65c-11ea-82d2-88431b71dfb0.png)

Let me know what you think ;-)

Cheers!

**Comment by barisusakli** [comment]
Feel free to PR, make sure you use `Promise.all` or `utils.promiseParallel` 
```
const permissions = await utils.promiseParallel({
  users: ...
  content: ...
});
```
