### ISSUE TITLE
NodeBB incompatible with MongoDB Atlas

### ISSUE THREAD

**Issue by SimplyBallistic** [NodeBB/NodeBB#8401]
- **NodeBB git hash:**
https://github.com/NodeBB/NodeBB/tree/78b7382c3f242dc01afa52ac3555d918c092e311 

- **Installed NodeBB Plugins:** 
Default from master

- **Database type:**
mongo
- **Database version:** 
MongoDB Atlas
- **Exact steps to cause this issue:**
1. Setup NodeBB with Atlas URI e.g `mongodb+srv://admin:<password>@xxx-mxhc2.mongodb.net/nodebb_test?retryWrites=true&w=majority`

2. Try start NodeBB with `nodebb start` after setup has completed
- **What you expected:**
NodeBB To start successfully
- **What happened instead:**
NodeBB throws the following error on startup: 
```
MongoError: not authorized on admin to execute command { create: "socket.io", writeConcern: { w: "majority" }, capped: true, size: 5242880 }
    at Function.MongoError.create (C:\Users\ryan9\git\NodeBB\node_modules\mongodb-core\lib\error.js:31:11)
    at C:\Users\ryan9\git\NodeBB\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (C:\Users\ryan9\git\NodeBB\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (C:\Users\ryan9\git\NodeBB\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at TLSSocket.<anonymous> (C:\Users\ryan9\git\NodeBB\node_modules\mongodb-core\lib\connection\connection.js:333:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

I believe this error occurs because NodeBB tries to write to the `admin` database which is disabled/restricted in MongoDB Atlas. It is overall, bad practice for NodeBB to deviate from the DB name I give it (in this case `nodebb_test`) from the connection URI. Everything should be contained within this one database in MongoDB.

Changing where NodeBB saves socket.io to to a place other than `admin` would fix this issue and allow support for MongoDB Atlas users.

I'm not sure where else NodeBB saves to since I never got to launch it, but an effort to move everything to one DB with several collections to store everything will help make the DB administration a lot easier in the future :)

This issue doesn't occur on local instances of MongoDB 

P.S: If a link can be given to the place this happens in code that would be incredibly helpful, as I'm on a tight schedule. I can later provide a PR with a fix if needed.

**Comment by barisusakli** [comment]
related https://github.com/lklepner/socket.io-adapter-mongo/issues/13

**Comment by barisusakli** [comment]
So the issues seems to be in socket.io-adapter-mongo which is using an outdated package `mubsub`

If you apply the changes here https://github.com/lklepner/socket.io-adapter-mongo/pull/17/files and run npm install it should work

**Comment by barisusakli** [comment]
@SimplyBallistic after updating the packages I was able to connect to Atlas. The outdated dependency was just not handling the `/<database_name>` part properly

![image](https://user-images.githubusercontent.com/2583394/84613617-a3cf8a80-ae91-11ea-8e7f-aff8452eb856.png)

**Comment by SimplyBallistic** [comment]
@barisusakli thanks for handling this so well! Can't wait to get started with nodebb 🎉

**Comment by june07** [comment]
Still doesn't appear to be supported by Atlas!

Just spent way too long trying to get this configured (Docker, Atlas) and still no luck. Basically, the setup UI can't connect to the Atlas cluster hostname (i.e. "clusterX.abcdefg.mongodb.net" from the uri mongodb+srv://<username>:<password>@clusterX.abcdefg.mongodb.net) and even when you put in the hostname of any of the individual hosts in the cluster, primary, either secondary, it still fails!

Just to double check myself I installed with mongo running in docker and it worked fine. Such a common use case as Atlas seems like a huge gap in something...

the error message when connecting to the cluster address:
![Screenshot 2024-04-03 234217](https://github.com/NodeBB/NodeBB/assets/11353590/9d5eac17-b534-4e44-9197-1c050d1905ed)

then the error message when connecting directly to the host:

![image](https://github.com/NodeBB/NodeBB/assets/11353590/1078714b-b683-4382-b041-c331221e8723)

Anyway.  Super irritating!

**Comment by Ry-DS** [comment]
are you sure this is related to the library? It looks like it failed due to a network error. What convinces you that it's a library problem?

**Comment by june07** [comment]
Well, it doesn't appear to be a network issue as I can connect fine using mongosh as well as just a plain telnet. Using mongo I can connect, list the databases, docs, etc, without disconnect or network issues. Connects fine from the web client, the Docker host, and the Docker container...
