### ISSUE TITLE
Pre-releases on purportedly "stable" branches (e.g. v1.13.4-5)

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8416]
Hi,

I've install NodeBB following your docs and now i have the versione 1.13.4-5 instead of the stable 1.13.3

How can i fix this?

I think isn't very secure put pre-release on same branch of stable.

**Comment by julianlam** [comment]
Hi there -- our use of pre-releases is fairly novel and so we are still learning how to best approach the matter.

In the meantime, you can run `git reset --hard v1.13.3` to go back to the latest stable version.

**Comment by julianlam** [comment]
I'm going to keep this issue open for discussion, if any.

We use a bespoke (:bike: ...) bot called [Misty](https://github.com/NodeBB/misty/) to handle our releases.

Right now we just use the same logic we always use for releases, as for pre-releases. This was mostly to keep code complexity down (see the `release` executable in the misty repo)

I suppose there's no reason we have to go into the release branch at all, a pre-release could simply be a tag on the `master` branch. If there are no objections, I will do that.

**Comment by andreadragotta** [comment]
Yes but at the moment if i make git pull on 1.13.x the version is the pre-release and on a production system is a problem because i use ansible for that. 

The best way probabily is to use 1.13.x only for main release.

**Comment by julianlam** [comment]
Yes, that's what we will do. In the meantime you can `git checkout v1.13.2`

**Comment by julianlam** [comment]
The pre-releases on `v1.14.x` branch will be the last pre-releases published. From now on the behaviour will be back to how it was prior. Pre-releases will still be cut but they will simply be tags against the master branch.
