### ISSUE TITLE
mute function for users

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#8426]
A "mute function" similar to Facebook groups... 

User does not need to be banned; so muted users can still log in and browse both private/public forum categories, vote and chat; however, they cannot post or create topic. 

Voting / Chatting are up to you. For me, the most important part is that for them not being able to post. 

It can be a moderation privilege, so category moderatos can be given this milder privilege rather than banning users...

here is the related topic: https://community.nodebb.org/topic/14850/mute-function-for-users

**Comment by julianlam** [comment]
I'm going to close this one because it is best served as a plugin. Remember, closed doesn't mean we don't do it, it just means it can still be searched for and implemented if necessary :smile:

**Comment by julianlam** [comment]
Mute functionality would go hand-in-hand with a "warning system" type of plugin, so there's an intermediate level before temporary and perma-bans.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/be6bbabd0e2551fbe9571dcf3ee40ad721764543

**Comment by hello-smile6** [comment]
@barisusakli Is that the only commit that I need in order to enable mute functionality?

**Comment by hello-smile6** [comment]
Okay.
