### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8430]
- **NodeBB version:** 1.13.3

Hi, while I was viewing a user's profile I saw this:

![image](https://user-images.githubusercontent.com/31972226/85464203-9bc3c900-b5bc-11ea-8f41-29c6421508d3.png)

This user follows ```7``` users but in the profile page the number of ```followings``` are ```-3```

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/2bcf7f72d21ca528b8b43c157751056880f0e069
