### ISSUE TITLE
Error during profile picture upload.

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8433]
Hi Guys,

I've found a bug on user profile picture upload. 

When the user is without a profile picure (never uploaded, for example after registration) if i try to upload it i have this error `ajaxify.data.picture` but the image is correctly uploaded and on page reload was showed withous a problem, the only one problem is the frontend stuck after upload.

I fixed that in template using this workaround

`{ "hook": "filter:users.get", "method": "pictureWorkaround" }	`

```
Theme.pictureWorkaround = function(data, callback) {
	var responseData = []
	data.forEach(user => {
		if (user.picture == null){
			user.picture = "";
		}
		responseData.push(user);
	})
	callback(null, responseData);
};
```

**Comment by barisusakli** [comment]
@andreadragotta let me know it you still have problems after above change.
