### ISSUE TITLE
Expand or Collapse posts on Unread/Recent categories

### ISSUE THREAD

**Issue by tutgreco** [NodeBB/NodeBB#8438]
Currently when viewing either Unread or Recent categories, it shows the date that a comment was posted but not the contents of the post itself.

It would be great to have a button for expanding/collapsing posts, so that the first few lines of a post is shown. This should apply to both new threads and posts. 

This is how I would execute it, 
![image](https://user-images.githubusercontent.com/46188218/85675110-b9c92080-b6c5-11ea-91e3-0fbd296f15e0.png)

**Comment by barisusakli** [comment]
Actually the contents of the last post is included, https://community.nodebb.org/recent, maybe the theme you are using doesn't display them.

**Comment by tutgreco** [comment]
Thanks Barisusakli that's correct. :+1:
