### ISSUE TITLE
Missing HTML element link with attribute next/prev to navigate faster

### ISSUE THREAD

**Issue by GwenDragon** [NodeBB/NodeBB#8450]
- **NodeBB version:** N.A.
- **NodeBB git hash:** 
- **Installed NodeBB Plugins:** 
- **Database type:** 
- **Database version:** 

- **Exact steps to cause this issue:**
  1. NodeBB forum does not gerate HTML element link with attribute next or prev to indicate next/previous page for fast navigation and pagination buttons do not have a text indication next, >, → to indicate next page/link
  2. So such feature can not be used in Opera 12 or Vivaldi

- **What you expected:**
Forum generates links or link-text for relation navigation

- **What happened instead:**
Forum does not have links for relation navigation

**Comment by pitaj** [comment]
So are these meta tags that the browser reads? Can you link to some documentation?

**Comment by julianlam** [comment]
Can you give us an example in a Page on our forum? We should already be providing prev and next link tags for topic pages.

**Comment by GwenDragon** [comment]
https://html.spec.whatwg.org/multipage/links.html#sequential-link-types
https://blog.whatwg.org/the-road-to-html-5-link-relations#rel-first
https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html

**Comment by GwenDragon** [comment]
@julianlam Open https://forum.vivaldi.net/recent has no relation to next page.
In Vivaldi browser the next button >| shoudl not be gray.

**Comment by barisusakli** [comment]
Seems like topic category pages already have it, just missing from /recent /popular etc.

**Comment by julianlam** [comment]
:+1: thanks for reporting @GwenDragon

**Comment by GwenDragon** [comment]
Then i can wait until a next stable NodeBB release.
