### ISSUE TITLE
During registration pages aren't available

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8452]
Hi,

During registration in the checkbox area (/register/complete) if i try to open other pages i return ever on the registration page. 
This sometimes could be a problem because if i have a topics or a custom page with important info (privacy policy, terms of service, rules) is impossible to see it.

At the moment the workaroud is with a third level domain but is a little bit tricky. 

Is possible to select it in settings or you have other solutions?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7125
