### ISSUE TITLE
v1.14.0 upgrade - Cannot find module 'winston'

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#8455]
upgrading from v1.13.4 I get the error:
Cannot find module 'winston'

resolved like so:
```
npm install -g winston
npm link winston
```

**Comment by julianlam** [comment]
The winston dependency hasn't been changed for years, so I don't see why this would happen. Let me know if it occurs on a new build, we've run a couple upgrades so far without running into this issue.

**Comment by pitaj** [comment]
That's a terrible way of resolving it, btw. Just do `npm install winston`
