### ISSUE TITLE
Allow use of topic tools and multi-select from /recent, /unread, /top, etc.

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8456]
Rationale:
> Allow us to Delete/Lock/Purge posts directly in the /recent. I'm asking this because of spammers that join the forum and post in all categories. I need to enter in each category, select each post and delete/purge each one instead of doing it all from /recent.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/8477
