### ISSUE TITLE
Composer drafts save undefined handle/title for replies, and also do not save tags

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8470]
Replies do not have fields for handle and title, so when the draft is saved, it saves `undefined` string. It should not save anything at all.

Also the tags are not captured, so when the draft is assumed by a logged-in user, the tags are not preserved alongside the rest of the drafted values.

**Comment by barisusakli** [comment]
Seems like fixed here https://github.com/NodeBB/nodebb-plugin-composer-default/commit/c788aae437ddadc6fbbdef78f8c8f04e916e3ea6? @julianlam

**Comment by julianlam** [comment]
Yep fixed
