### ISSUE TITLE
/chats page height is dynamically updated using javascript

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8472]
Yuck.

Whoever wants to tackle this, `.chats-full` should be a flex item instead.

**Comment by LukeWReagan** [comment]
I want to help you with this but am having a hard time getting the app to run locally.

**Comment by julianlam** [comment]
Hey there! Have you tried the instructions over here: https://docs.nodebb.org/installing/os/ubuntu/ ?

We also have windows installation instructions, not sure what OS you're on.

**Comment by LukeWReagan** [comment]
Hey sorry for not being more specific but I did try the instructions for windows and I failed when running `nodebb setup` I can give it another try and get back to you. Once I get everything set up it should be a simple change to flex.

**Comment by 41x3n** [comment]
Is this issue already solved? I ran in the local and found the class to already have flex.

**Comment by barisusakli** [comment]
Seems like the code is still there https://github.com/NodeBB/NodeBB/blob/master/public/src/client/chats.js#L516
