### ISSUE TITLE
Read API with authentication problem

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/NodeBB#8487]
- **NodeBB version:** 1.14.1
- **NodeBB git hash:** ddf5c3bf7fad00243fc85c90f6f2a19dbb29e977
- **Exact steps to cause this issue:**
	1. Go to http://127.0.0.1:5678/admin/plugins/write-api
	2. Get my admin user token (or master token), written as XXXXX after
	3. Do a Read API request which needs authentication in command line like this one :
`curl -H "Authorization: Bearer XXXXX" http://127.0.0.1:5678/api/user/uid/1`
- **What you expected:**
I expected to get the json answer from read API...
- **What happened instead:**
I get answer "not-authorized" (but I can access it in navigator...)

Is it a bug ? If no, what is the exact way to get a read api answer as authenticated user from command line ?

**Comment by julianlam** [comment]
I believe this is already available in our development branch for v2.0. Unfortunately we do not currently have plans to merge it into the v1.x line
