### ISSUE TITLE
Controller helper for standardized button injection via plugins

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8493]
A helper method for standardising button or link injection by plugins (and into templates) would be helpful (ha get it, _help_ -ful?)

The best example of a controller calling out to plugins is in the account profile links

https://github.com/NodeBB/NodeBB/blob/3379d65f360d01c817b5806bcd6a6a4043838d2b/src/controllers/accounts/helpers.js#L86-L93

This data is _actually_ populated in `getProfileMenu`, which calls out to plugins for links to add:

https://github.com/NodeBB/NodeBB/blob/3379d65f360d01c817b5806bcd6a6a4043838d2b/src/controllers/accounts/helpers.js#L141-L192

Of note is that there is nothing in the payload that suggests it is to be a link or a button. That kind of determination is left to the template file itself. Even then, one theme might use buttons and another might use links, so let's try to keep that genericism alive.

Lastly, the controller should also call `filterLinks`, so this method ought to be moved out:

https://github.com/NodeBB/NodeBB/blob/3379d65f360d01c817b5806bcd6a6a4043838d2b/src/controllers/accounts/helpers.js#L205-L229

`filterLinks` allows plugins to define who exactly can see the link/button. Note `public` and `private` are deprecated, so do not handle them in your new helper (**... which makes this a breaking change**). `visibility` is what replaced those two properties.

----

As discussed, the best place to put this would likely be `src/controllers/helpers.js`, and the profile links would be a good place in core to start using this abstracted controller helper.

**Comment by julianlam** [comment]
Ideally, the plugin hook fired should also be standardised, so the helper would be called with some sort of identifier, e.g. `controllers.buildLinks('accounts.profile', req);`

If we do this, then the existing hook (`filter:user.profileMenu`) still needs to be called, but deprecated.

**Comment by samt** [comment]
I've committed a WIP with my work thus far on this. I wanted to make sure this was roughly what we're after.

**Comment by julianlam** [comment]
Thanks Sam, will review later today

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/compare/feat/account-button-injector
