### ISSUE TITLE
Can't select posts in "Unread" section /unread

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#8500]
- **NodeBB version:** 1.4.1

After click on posts to select, they can't stay selected.

**Comment by NormandoHall** [comment]
Hi @barisusakli . I tested that when you are an admin or moderator, can select. Normal users can´t select. Check in 1.14.2

**Comment by NormandoHall** [comment]
Hi @barisusakli . Comes again in nodeBB 1.14.3

**Comment by barisusakli** [comment]
Can you reproduce here https://community.nodebb.org/unread?

**Comment by NormandoHall** [comment]
No @barisusakli, runs ok.

**Comment by barisusakli** [comment]
Already fixed then, either wait for 1.15.0 release or apply the fix manually.
