### ISSUE TITLE
{{./value}} instead of real value in Account & Flag History

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#8501]
- **NodeBB version:** 1.4.1
- **NodeBB git hash:** ddf5c3bf7fad00243fc85c90f6f2a19dbb29e977

- **Installed NodeBB Plugins:** 
Active plugins:
        * nodebb-plugin-camo (installed, enabled)
        * nodebb-plugin-cards (installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-custom-pages (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-discord-notification (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, disabled)
        * nodebb-plugin-emoji-one (installed, enabled)
        * nodebb-plugin-giphy (installed, enabled)
        * nodebb-plugin-highlights (installed, enabled)
        * nodebb-plugin-iframely (installed, enabled)
        * nodebb-plugin-imgbed (installed, enabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-ns-embed (installed, enabled)
        * nodebb-plugin-ns-likes (installed, enabled)
        * nodebb-plugin-poll (installed, enabled)
        * nodebb-plugin-question-and-answer (installed, enabled)
        * nodebb-plugin-recent-cards (installed, enabled)
        * nodebb-plugin-solr (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, enabled)
        * nodebb-plugin-spam-be-gone (installed, enabled)
        * nodebb-plugin-sso-facebook (installed, enabled)
        * nodebb-plugin-sso-google (installed, enabled)
        * nodebb-plugin-sso-twitter (installed, enabled)
        * nodebb-plugin-tenor-gif (installed, enabled)
        * nodebb-plugin-youtube-embed (installed, enabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-va (installed, enabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)
        * nodebb-widget-ns-birthdays (installed, disabled)

- **Database type:** mongo
- **Database version:** 4.2.6

- **Exact steps to cause this issue:**
Looking Account & Flag History in reported posts
- **What you expected:**

Parsed {{./value}}
- **What happened instead:**

Raw {{./value}}

![image](https://user-images.githubusercontent.com/2943127/87362626-83a0f300-c545-11ea-834a-0ec534602069.png)

**Comment by julianlam** [comment]
Please provide the appropriate debugging information as recommended in the issue template.

**Comment by NormandoHall** [comment]
@julianlam done

**Comment by julianlam** [comment]
Yeesh, that's a lot of plugins.

It is likely https://www.npmjs.com/package/nodebb-theme-va does not contain the changes to the flags templates required, as it contained breaking changes in v1.14.x. The theme creator will have to merge Persona's flags/list.tpl and flags/detail.tpl with that theme's version of those templates.

**Comment by NormandoHall** [comment]
Sorry @julianlam but this theme is old, and I have made local changes to this VA theme. I am only overriding two templates: `templates/topic.tpl` and `templates/partials/topic/post.tpl`. Not ACP. It is necessary to copy those two templates files and added in my own theme?

**Comment by NormandoHall** [comment]
Well, I was added these two files (flags/list.tpl and flags/detail.tpl) in my own theme and still the same issue

![image](https://user-images.githubusercontent.com/2943127/87384019-202cba80-c571-11ea-9f6b-1640a02b3ca8.png)

**Comment by julianlam** [comment]
Ah, if your theme does not have these template files, then you can remove them, as it will inherit them from Persona...

**Comment by julianlam** [comment]
@NormandoHall Do you mind sharing with me the results of the `/api` route for that particular page?

**Comment by NormandoHall** [comment]
> @NormandoHall Do you mind sharing with me the results of the `/api` route for that particular page?

Yes, sure. I was emailed to you. Thanks

**Comment by barisusakli** [comment]
Did you check if it's working on persona theme?
