### ISSUE TITLE
Sitemap.xml Improvement

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8502]
Hi!

On sitemap.xml with my team i've found a couple of little improvement that could be make NodeBB more reliable for SEO purpose.

- [ ] Update sitemap when a new topic has published (and if a reply was posted). This is useful because with 1 day of cache GSC have to wait one day to see new topics. Maybe is useful an hook for sitemap cache flush.
- [x] Order the topics by create date and not only by edit date (reverse or not).
- [ ] A method to ping the sitemap to google when is updated. (ex. http://www.google.com/ping?sitemap=https://example.com/sitemap.xml). If you want to give more possibilities for the user to ping to different SE probably an idea is to have an hook after sitemap update and every user could decide which SE ping.

**Comment by julianlam** [comment]
Good suggestions here, I agree with all of them, although the sorting of topics seems like it wouldn't really affect anything, so I doubt we'd change that (adds unnecessary complexity, maybe)

Google itself says that do not crawl sitemaps more than once, so perhaps the 24h cache is sufficient but we could also ping Google every 24h.

**Comment by andreadragotta** [comment]
With the actual sorting if we have 500 sitemap when a new topic was created the 500 sitempas will be updated. And in this case google have to read 500 new sitemaps because the content change. The crawl budget is limited for each site.

The 24h ping is an error for the forums. The topics will be updated after hours after his creation date. Google indexing is based on content freshness and for nodeBB forum this is a problem.

**Comment by pitaj** [comment]
Okay so the sorting is so sitemaps change as little as possible.

**Comment by julianlam** [comment]
Yes, that part definitely makes sense to me.

**Comment by barisusakli** [comment]
Changed topics sorting order
https://github.com/NodeBB/NodeBB/commit/e045436c07159b64252b5e7adb7515037678489d

**Comment by barisusakli** [comment]
Gonna close this, the other items can be done in a plugin. Use `action:topic.post` and call `sitemap.clearCache` if you want the sitemap to be refreshed on every topic post. Or you can ping any search engine in that hook as well.
