### ISSUE TITLE
Composer issues in some android mobiles

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#8504]
- **NodeBB version:** 1.14.2
- **NodeBB git hash:** 28970b030d21a9e839804b0c40e0ed1c520502ac

- **Installed NodeBB Plugins:** 

Active plugins:
        * nodebb-plugin-camo (installed, enabled)
        * nodebb-plugin-cards (installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-custom-pages (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-discord-notification (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, disabled)
        * nodebb-plugin-emoji-one (installed, enabled)
        * nodebb-plugin-giphy (installed, enabled)
        * nodebb-plugin-highlights (installed, enabled)
        * nodebb-plugin-iframely (installed, enabled)
        * nodebb-plugin-imgbed (installed, enabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-ns-embed (installed, enabled)
        * nodebb-plugin-ns-likes (installed, enabled)
        * nodebb-plugin-poll (installed, enabled)
        * nodebb-plugin-question-and-answer (installed, enabled)
        * nodebb-plugin-recent-cards (installed, enabled)
        * nodebb-plugin-solr (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, enabled)
        * nodebb-plugin-spam-be-gone (installed, enabled)
        * nodebb-plugin-sso-facebook (installed, enabled)
        * nodebb-plugin-sso-google (installed, enabled)
        * nodebb-plugin-sso-twitter (installed, enabled)
        * nodebb-plugin-tenor-gif (installed, enabled)
        * nodebb-plugin-youtube-embed (installed, enabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-va (installed, enabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)
        * nodebb-widget-ns-birthdays (installed, disabled)

- **Database type:** mongo
- **Database version:** 4.2.6

- **Exact steps to cause this issue:**

Some users have been reported when they writing a **long** reply in composer, they can't see the text because it's hidden below the keyboard. In some devices they can scroll up de text to show the last lines hidden by keyboard, but not in all mobile devices can scroll. All using Chrome Browser. Tested with Firefox also and same issue.This issue begin in nodeBB 1.14.1 and stay in 1.14.2

Some reported devices are
Android 9, screen 5,65 inches
LG k10
Huawei
Motorola

![screenshot_20200713_015215_com android chrome](https://user-images.githubusercontent.com/2943127/87586820-86bbf080-c6b7-11ea-92d4-2a6c5e507d72.jpg)

- **What you expected:**

Write a long text and autoscroll up when text go below keyboard
- **What happened instead:**
No scroll up

**Comment by NormandoHall** [comment]
Fixed!!!

The issue was `min-height: 400px` in composer. So I added this rule to override it:

`[component="composer"].composer {min-height: unset!important;}`

Seems this issue happens on small screens

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/commit/d2c40bb087bca45b4584c14d3c3b7384f523dd12


@julianlam I think that 400px shouldn't apply to mobile composer?

**Comment by julianlam** [comment]
Yes, that looks to be a regression. Thanks for reporting Normando, and for the assist Barış 😁
