### ISSUE TITLE
new users with fake email addresses exhaust email server

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#8519]
Hello, some users (without knowing they have to confirm their email address) are registering the forum with an email address that does not exist. Sometimes it is clear for us because they use .....@gmaillll.com which is clearly fake. But sometimes it looks legitimate with ...@gmail.com but email server is failing to reach to these email addresses.

In any case, the email server is still trying to reach these email addresses and repeat this cycle for several days and this creates lots of delivery failure notifications in our inbox. We are not deleting these users simply because they can log in and provide a legitimate email address later. However, some users are preferring to do nothing, and this exhausts our email server. 

I do not know how this works, but I wonder if it would be possible to tell the forum not to reach these users anymore until they provide a new email address. Or, I am also open to other suggestions to resolve the issue.

Thanks. 

This is just an example of the gmail server response we had:

**Delivery Status Notification (Failure)**
>The response was:
>
>550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser w11sor21354836qtk.53 - gsmtp

**Comment by barisusakli** [comment]
>In any case, the email server is still trying to reach these email addresses and repeat this cycle for several days and this creates lots of delivery failure notifications in our inbox

This is not something we control.

What we can do is not send any notification emails or other emails to users who have not confirmed their email address. Maybe that would help.

**Comment by julianlam** [comment]
> What we can do is not send any notification emails or other emails to users who have not confirmed their email address. Maybe that would help.

From a UX point of view, we really should be doing this already. Good idea...!

It would also decrease our bounce rate.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/b6917b9deea052ba8518e1db47682a1b99b09ea7

**Comment by AliCihan** [comment]
Thanks. That would help us too, although it is not solving all the problems, it is definitely helping. 

For future members, I will try to add each of these email address extensions to the blocked email list, maybe this will prevent (or at least reduce) signing up with the wrong email addresses. 

Thanks.

**Comment by barisusakli** [comment]
This might also help, https://community.nodebb.org/topic/10434/registration-email-domain-blacklisting
