### ISSUE TITLE
ctrl/cmd-Enter keyboard shortcut to Submit

### ISSUE THREAD

**Issue by marcusquinn** [NodeBB/NodeBB#8526]
Almost every other app has it, so it seems to be a reasonably standard expectation.

My keyboard instincts mean I keep hitting ctrl/cmd-Enter on NodeBB Replies and 🤦 every time.

Anyone else?

**Comment by julianlam** [comment]
Makes sense to me, and the shortcuts plugin does supply that, but we can bundle it into core.

FWIW a workaround for now is tab-space

**Comment by barisusakli** [comment]
I just tried ctrl + enter here https://community.nodebb.org/topic/14843/test/2

Seems to work.

**Comment by marcusquinn** [comment]
> I just tried ctrl + enter here https://community.nodebb.org/topic/14843/test/2
> 
> Seems to work.

Hmmm, maybe that have it done via plugin 🤷‍♂️ 

I'm mostly on Cloudron.io's forum so had asked there and they pointed me here:

https://forum.cloudron.io/topic/2920/any-way-to-get-a-keyboard-shortcut-for-submit-in-nodebb?_=1595540035549

**Comment by barisusakli** [comment]
What browser are you testing with? On our community forum there is no shortcuts plugin installed it just part of the the default composer.

**Comment by marcusquinn** [comment]
> Makes sense to me, and the shortcuts plugin does supply that, but we can bundle it into core.
> 
> FWIW a workaround for now is tab-space

Yeah - since the whole world is web-appified and habits become standards, would make sense to have the same shortcut. as Discord/GitHub/GitLab etc.

And, I can see forums growing in popularity more for their more focused community without all the noise and rabbit-hole scrolling of social media - so all for anything that makes NodeBB seamless to people coming from there and reclaiming focus and community.

👍 for NodeBB from me - so just this minor but significant thing would make it a bit more seamless.

cmd-Enter

**Comment by marcusquinn** [comment]
> What browser are you testing with? On our community forum there is no shortcuts plugin installed it just part of the the default composer.

Safari / Opera on Mac

**Comment by psychobunny** [comment]
yeah the code doesn't look for cmd, we can change that pretty easily though. 
can you confirm that ctrl-enter works for you first please?

**Comment by marcusquinn** [comment]
> yeah the code doesn't look for cmd, we can change that pretty easily though.
> can you confirm that ctrl-enter works for you first please?

Ahh - just came back to say I just spotted that too. 😄 

Yeah, on Mac - ctrl-Enter works - but for Mac users cmd-Enter is the de-facto.

ctrl-Enter on Mac doesn't Submit on GitHub for example but cmd-inter seems to work almost everywhere for Mac, except NodeBB - but is sounds like it's probably an oversight and easy fix?

Love solving a detail eh 😄

**Comment by julianlam** [comment]
composer-default@6.3.53

**Comment by marcusquinn** [comment]
Thank you kindly! 👍 Happy weekend!
