### ISSUE TITLE
publish bootswatch as @nodebb/bootswatch

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#8527]
and replace https://github.com/NodeBB/NodeBB/blob/master/install/package.json#L40

**Comment by julianlam** [comment]
Why did we even need to be on a git url... Have to check and see if the fix was ever merged in

**Comment by barisusakli** [comment]
https://github.com/thomaspark/bootswatch/pull/916

The fix was merged but no new version doesn't show up as it is published as 3.4.1+1 🤔

**Comment by julianlam** [comment]
Okay. I've asked them to publish 3.4.2, if they refuse, we'll republish under our scope.

**Comment by greenhat616** [comment]
@barisusakli the version 3.4.1+1 is published correctly in bower. Howerer, the npm don't support republish the same version.

I support you publish a version as @nodebb/bootswatch, the connection to Github is usually not reliable in China.

**Comment by julianlam** [comment]
:point_up: not a fix, just something for now.

**Comment by barisusakli** [comment]
I think 2 weeks is enough time 😆
