### ISSUE TITLE
Go to the first unread post on topic click

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/NodeBB#8538]
- **NodeBB version: 1.14.2** (same bug on my own site and on nodebb community forum)
- **Exact steps to cause this issue:**
	1. Go to /unread or to a topics list.
	2. Click a topic title.
- **What you expected:**
Autoscroll to the first unread message (or the last read message *if there is no unread message*).
- **What happened instead:**
Autoscroll to the last read message, even if there are others after. It's not great when the last read message is long for example...

(If it's a desired thing, why is it like this ? It's strange no ?)

**Comment by barisusakli** [comment]
Looks like it's off by one meaning when you read up to post index 14 and click the topic again from /unread it goes to post index 13.

**Comment by alfazaz** [comment]
Thanks !! I will see in the future if all is ok.
