### ISSUE TITLE
auth.overrideLogin can not next (uid) correctly in SSO Plugin

### ISSUE THREAD

**Issue by FZenM** [NodeBB/NodeBB#8545]
NodeBB Version: 1.14.2

I have one huge problem with a custom SSO Plugin. Once someone with an existing account wants to login it always shows **"Welcome back guest"** and does not login the user correctly (no profile).

Inside the code, the next function in the auth.overrideLogin hook is called correctly with uid and [[success:authentication-successful]] after successful validation of the credentials, but not registered correctly.

If the user account is created the first time in the nodebb, then everything works as expected. But once the account already exists, it reverts to guest.

I have tried various calls, even this (partially obsolete):
```

                User.auth.clearLoginAttempts(user.uid);
                authenticationController.onSuccessfulLogin(req, user.uid, next(null, user.uid, '[[success:authentication-successful]]'));
```

to register/authenticate an existing user correctly, but it always gives me "welcome back guest".

The original code only used `next(null, user.uid)`

What do I miss?

**Comment by barisusakli** [comment]
Looks like you need to pass in the `user` object and not `user.uid` https://github.com/julianlam/nodebb-plugin-sso-facebook/blob/master/library.js#L127

**Comment by julianlam** [comment]
Let me know if this resolved your issue 👍

**Comment by FZenM** [comment]
Thanks Barisusakli and Julianlam. But no, I had tried that too. User is only an small object I had created from some info I found around. I think it might be incorrect.

Looking into the source of the nodebb [hook](https://github.com/NodeBB/NodeBB/blob/master/src/routes/authentication.js#L56)

and [locallogin](https://github.com/NodeBB/NodeBB/blob/6c00ec8435039d2b9e96f7e8963abb9f85c8f013/src/controllers/authentication.js#L360) can someone confirm it is necessary to submit a user object similar to this?

Calling it with uid used to work in the old version we where running (v0.8x) and various plugins (outdated?) seem to keep using uid as sole parameter (because nodebb knows the rest anyways).

**Comment by barisusakli** [comment]
Can you post the code of how you are using `plugins.fireHook('action:auth.overrideLogin');` this is a action hook so it doesn't expect any return values.

**Comment by FZenM** [comment]
Sure, 
```
var OverrideLogin = (function () {

//SNIP - Function Create Account if needed

    var continueLogin = function (req, username, password, next) {

        var onAuthenticationSuccessful = function (data) {
            var profile = createProfile(data.player);
            moreLogin({
                CBid: profile.id,
                handle: profile.displayName,
                email: profile.email,
                isAdmin: profile.isAdmin,
                picture: profile.picture
            }, function (err, user) {
                if (err) {
                    return next(err);
                }
                var duration = 1000 * 60 * 60 * 24 * parseInt(meta.config.loginDays || 14, 10);
                req.session.cookie.maxAge = duration;
                req.session.cookie.expires = new Date(Date.now() + duration);
                next(null, user);  //Callback holds UID if successful
            });
        };

//SNIP moreLogin authenticates and creates account if neccessary or does callback (null, uid) if successful
}
```

The whole code is also available [here](https://github.com/exozet/nodebb-plugin-gs-login/blob/develop/src/plugin/authOverrideLogin.js) but it is not maintained anymore since 5 yrs.

**Comment by FZenM** [comment]
I dont get it. Some debugging (nodebb dev) gives following output:

> 2020-08-05T10:19:34.155Z [4569/49277] - info: [gs-login] Authentication success: {"authentication":"success","player":{"id":"xxxx","displayName":"frankm","email":"frank@xxx.xxx","avatar":null}}
> 2020-08-05T10:19:34.155Z [4569/49277] - info: [gs-login] profile:{"id":"xxxx","displayName":"frankm","email":"frank@xxx.xxx","isAdmin":false,"picture":null}
> 2020-08-05T10:19:34.155Z [4569/49277] - verbose: [gs-login] Payload: [object Object]
> 2020-08-05T10:19:34.157Z [4569/49277] - info: [gs-login] user:{"uid":24588}
> 2020-08-05T10:19:34.158Z [4569/49277] - verbose: [plugins/fireHook] filter:blacklist.test
> 2020-08-05T10:19:34.191Z [4569/49277] - verbose: **[plugins/fireHook] action:user.loggedIn**
> 2020-08-05T10:19:34.253Z [4569/49277] - verbose: [middleware/autoLocale] Retrieves languages list for middleware
> 2020-08-05T10:19:34.254Z [4569/49277] - verbose: [plugins/fireHook] filter:user.getSettings
> 2020-08-05T10:19:34.254Z [4569/49277] - verbose: [plugins/fireHook] filter:user.notificationTypes
> 2020-08-05T10:19:34.255Z [4569/49277] - verbose: [plugins/fireHook] filter:config.get
> 2020-08-05T10:19:34.256Z [4569/49277] - verbose: [plugins/fireHook] filter:middleware.buildHeader
> 2020-08-05T10:19:34.258Z [4569/49277] - verbose: [plugins/fireHook] action:middleware.pageView
> 2020-08-05T10:19:34.258Z [4569/49277] - verbose: [plugins/fireHook] response:router.page
> 2020-08-05T10:19:34.271Z [4569/49277] - verbose: [plugins/fireHook] filter:privileges:isUserAllowedTo
> 2020-08-05T10:19:34.272Z [4569/49277] - verbose: [plugins/fireHook] filter:privileges:isUserAllowedTo
> 2020-08-05T10:19:34.282Z [4569/49277] - verbose: [plugins/fireHook] filter:topic.getFields
> 2020-08-05T10:19:34.284Z [4569/49277] - verbose: [plugins/fireHook] filter:privileges:isUserAllowedTo
> 2020-08-05T10:19:34.285Z [4569/49277] - verbose: [plugins/fireHook] filter:privileges:isUserAllowedTo
> 2020-08-05T10:19:34.285Z [4569/49277] - verbose: [plugins/fireHook] filter:privileges.topics.filter
> 2020-08-05T10:19:34.286Z [4569/49277] - verbose: [plugins/fireHook] filter:topic.getFields
> 2020-08-05T10:19:34.289Z [4569/49277] - verbose: [plugins/fireHook] filter:post.getFields
> 2020-08-05T10:19:34.291Z [4569/49277] - verbose: [plugins/fireHook] filter:user.whitelistFields
> 2020-08-05T10:19:34.294Z [4569/49277] - verbose: [plugins/fireHook] filter:user.getFields
> 2020-08-05T10:19:34.294Z [4569/49277] - verbose: [plugins/fireHook] filter:users.get

**Comment by julianlam** [comment]
@FZenM I take it that this is quite old code?

I have taken a look at a similar implementation that used the `action:auth.overrideLogin` hook, and the only change I made historically is adding in a call to `authenticationController.onSuccessfulLogin(req, uid);` right before I call `next(null, { uid: uid });`

Note that unlike your call, I did not pass in a callback function. I think you can `await` it and call `next` afterwards...

**Comment by FZenM** [comment]
Its crazy. So I tried that with await and had to turn the turn the heading function to async. But the "Welcome back Guest" without loading any profile remains. Keep in mind, that if the user is created new, then everything works as expected. The DEV output has changed slightly:

>  2020-08-06T09:02:39.811Z [4569/54750] - info: [gs-login] Authentication success: {"authentication":"success","player":{"id":"xxxx","displayName":"frankm","email":"frank@xxx.xx","avatar":null}}
> 2020-08-06T09:02:39.812Z [4569/54750] - info: [gs-login] profile:{"id":"xxxx","displayName":"frankm","email":"frank@xxx.xxx","isAdmin":false,"picture":null}
> 2020-08-06T09:02:39.812Z [4569/54750] - verbose: [gs-login] Payload: [object Object]
> 2020-08-06T09:02:39.816Z [4569/54750] - info: [gs-login] user:{"uid":24588}
> 2020-08-06T09:02:39.817Z [4569/54750] - verbose: [plugins/fireHook] filter:blacklist.test
> 2020-08-06T09:02:39.835Z [4569/54750] - verbose: [plugins/fireHook] filter:topics.unreadCutoff
> 2020-08-06T09:02:39.836Z [4569/54750] - verbose: [plugins/fireHook] action:user.online
> 2020-08-06T09:02:39.840Z [4569/54750] - verbose: [plugins/fireHook] action:user.set
> 2020-08-06T09:02:39.843Z [4569/54750] - verbose: [plugins/fireHook] filter:user.getSettings
> 2020-08-06T09:02:39.844Z [4569/54750] - verbose: [plugins/fireHook] filter:user.notificationTypes
> 2020-08-06T09:02:39.853Z [4569/54750] - verbose: [plugins/fireHook] filter:topics.getUnreadTids
> 2020-08-06T09:02:39.867Z [4569/54750] - **verbose: [plugins/fireHook] action:user.loggedIn**
> 2020-08-06T09:02:39.918Z [4569/54750] - verbose: [middleware/autoLocale] Retrieves languages list for middleware
> 2020-08-06T09:02:39.918Z [4569/54750] - verbose: [plugins/fireHook] filter:user.getSettings
> 2020-08-06T09:02:39.918Z [4569/54750] - verbose: [plugins/fireHook] filter:user.notificationTypes
> 2020-08-06T09:02:39.919Z [4569/54750] - verbose: [plugins/fireHook] filter:config.get
> 2020-08-06T09:02:39.919Z [4569/54750] - verbose: [plugins/fireHook] filter:middleware.buildHeader


I am about to restart the old code, but really I think it would work fine and everything would be upgraded if only this problem could be resolved.

Thanks for all the help up to now.

**Comment by julianlam** [comment]
Can you link us to your sso code?

**Comment by julianlam** [comment]
Let me know if this is still an issue and we can revisit :+1:
