### ISSUE TITLE
Post redirect to topic with 302

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8549]
Hi,

The post indexed on google use a 302 redirect but for the SEO i think is better a 301.

What do you think about that?

**Comment by julianlam** [comment]
:+1: You are correct, 302 (or 307) does not transfer SEO juice:tm:

Need to use 301 or 308. Reason why we implemented this using a 302 is in case we mucked up the logic, it would really mess up your cache, but I think we're at the point where we can send a 308 instead :smile:

**Comment by julianlam** [comment]
Mm, upon further research, we cannot do this. The posts permalink redirects you to the topic, but we cannot guarantee with **100% certainty** that the post will remain in that topic forever. Forking a topic will move posts to a new topic id, and so a 301 cached in the user's browser will forever send someone to the wrong topic. It is exceedingly difficult to remove a cached 301 from a browser, so it is best not to assume.

However, I will send a 301 for things such as referring to a topic with the incorrect/missing slug, etc...
