### ISSUE TITLE
User's info shown to unprivileged Admin/Mod in /flags

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#8591]
Hi, 

In ACP, accessibility to user's info is revoked for Mods/Admins. But they still can see Email and username history in /flags page. If we limit /info page for Mods/Admins so they don't have to see info on /flags

we use nodeBB v1.15.0-beta.5

**Comment by roghaye-m** [comment]
also show the ip blocklist and post queue  on
 sub user meno

and change owner and ip track  in posts iteam 

But they haven't privileges
I think that iteams would be hidden

**Comment by mohammadhassan99** [comment]
Hi, please reproduce.
Thanks

**Comment by julianlam** [comment]
> In ACP, accessibility to user's info is revoked for Mods/Admins

I am assuming that you mean you have not given the "admin:users" privilege to mods and admins?

Them being able to see username and email history is part of being a mod/admin, since it is important to know in case a user is changing usernames and/or emails to avoid punishment for, or association with, bad behaviour.

**Comment by roghaye-m** [comment]
> > In ACP, accessibility to user's info is revoked for Mods/Admins
> 
> I am assuming that you mean you have not given the "admin:users" privilege to mods and admins?
> 
> Them being able to see username and email history is part of being a mod/admin, since it is important to know in case a user is changing usernames and/or emails to avoid punishment for, or association with, bad behaviour.


I think we should also have a situation where it can only do things like move and  edit merge topics/posts 
This group is not responsible for reviewing reports and handle them
