### ISSUE TITLE
Block IP and /post-queue page buttons don't work

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8596]
- **NodeBB version:** v1.15.0-beta.5

Hi, we cannot block IPs. The button doesn't work. Also in ```/post-queue``` the buttons don't work.

```/Post-queue``` buttons:

![image](https://user-images.githubusercontent.com/31972226/91878240-3ebb5200-ec94-11ea-8eb9-9d9a4252d72a.png)

**Comment by julianlam** [comment]
Update to a newer beta please.
