### ISSUE TITLE
Refactor user bans to use user groups/privileges system

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#8610]
Not sure if this is the right place for this so close if not.

I've been reading up on your plans for Nodebb V2 and integrating the Write API into it. Great News!

Can I suggest that Banned users are treated as logged in but with reduced (guest) privileges going forward instead of the current approach of stopping them from logging in at all. As someone who uses Nodebb inside of a website with session sharing, it has been a PITA having a user logged in to the website but banned on the forum and having buttons like login to reply on topics show (as they arent logged in to the forum so treated as a guest but to the user they are logged in and it becomes confusing) and also updating the user when they are unbanned because there is no socket unban event as they are a guest and cant listen for such an event so they have to logout and back in to the website to catch such changes. 

I've managed to work around it in V1 but its not as simple as it could be.

Its partly related to https://github.com/NodeBB/nodebb-plugin-write-api/issues/126

Keep up the great work and I look forward to using Nodebb V2 in the future sometime 👍

**Comment by julianlam** [comment]
Hm... yes I think this is a good idea.

Right now a banned user is functionally the same as a regular user except they have a flag stating that they are banned. It would be better to move this logic into the privileges table, and have banned users as a separate user group.

Then admins can choose how to deal with banned users... maybe they can only access a special set of categories only available to other banned users :joy: the possibilities are endless.

**Comment by roghaye-m** [comment]
> Hm... yes I think this is a good idea.
> 
> Right now a banned user is functionally the same as a regular user except they have a flag stating that they are banned. It would be better to move this logic into the privileges table, and have banned users as a separate user group.
> 
> Then admins can choose how to deal with banned users... maybe they can only access a special set of categories only available to other banned users 😂 the possibilities are endless.



You can also add this option
Banned users can create posts and topics just like  normal users, but only visible to themselves and 
hide these users' posts from other users

**Comment by julianlam** [comment]
@roghaye-m That would be out of scope of this task unfortunately :smile:
