### ISSUE TITLE
Google Tag Manager Virtual Page View problem in ajaxify.end

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8613]
Hi, 

I've a problem with google tag manager and ajaxify.end. 

In my nodebb i've this piece of code:
```
$(window).on('action:ajaxify.end', function(ev, data) {
    dataLayer.push({'event': 'virtual-pv'});
});
```
But sometimes "action:ajaxify.end" not work and the dataLayer.push does not start

**Comment by barisusakli** [comment]
I can reproduce this on our community as well. Sometimes `action:ajaxify.end` fires before the listener is added. So the handler is never called.

**Comment by andreadragotta** [comment]
Ok, and how i can fix the problem with ajaxify.end?

**Comment by barisusakli** [comment]
Try using 
```
$(window).on('action:ajaxify.contentLoaded', function(ev, data) {
    dataLayer.push({'event': 'virtual-pv'});
});
```

But this needs to be fixed in core, I assume you have this code in your custom JS tab in the ACP?

**Comment by andreadragotta** [comment]
Yes, is in the JS tab in ACP.

Now try with contentLoaded

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/8615
