### ISSUE TITLE
 show user's full name as the display name

### ISSUE THREAD

**Issue by yjzzcao** [NodeBB/NodeBB#8637]
- **NodeBB version:** 1.14.3
- **NodeBB git hash:** 8479809

- **Installed NodeBB Plugins:** 

        * nodebb-plugin-cards-fullname (not installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-dbsearch (installed, disabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, enabled)
        * nodebb-plugin-gogoal-login (installed, enabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-soundpack-default (installed, enabled)
        * nodebb-plugin-spam-be-gone (installed, disabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, enabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo
- **Database version:** unkown

- **What you expected:** show user's full name as the display name

**Comment by barisusakli** [comment]
Will close once tpls are updated in persona
