### ISSUE TITLE
Cannot ajaxify to `/me`

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8656]
![image](https://user-images.githubusercontent.com/923011/93384452-d98a6380-f832-11ea-9ab3-6c445e29d16f.png)

**Comment by barisusakli** [comment]
/me (redirects to /user/<userslug>
/me/posts (redirect to /user/<userslug>/posts

/api/self (returns json data of logged in user) (this used to be /api/me, which broken the /me redirect)
