### ISSUE TITLE
New system group for verified users

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8662]
A new system group for verified users. Users will be added to this group upon successful email verification.

Upon NodeBB setup, just like `registered-users` group, a `Verified Users` group should be created.

Benefits:

1. More fine-grained control over newly registered users
1. Can limit privileges to verified users (e.g. local login)

Additional considerations:

* The new group should be a system group (see `isSystemGroup`)
* Note the casing of "Verified Users", it is different from `registered-users`
* ~How do we handle user accounts created via SSO? Assume verified?~ SSO plugins manually handle verification based on ACP option (defined within the plugin itself)
* An upgrade script is needed to create this group for pre-existing installs. Add users into this group who have the `email:confirmed` state in their user hash
* Remove saving `email:confirmed` in the user hash &mdash; **this is a breaking change**
* `Messaging.canMessageUser`, `Messaging.canMessageRoom`, `isReady` (in `src/user/posts.js`), and `canEditDelete` (in `src/messaging/edit.js`) should no longer check `meta.config.requireEmailConfirmation`, but should check if the given uid has the `chat` privilege

**Comment by pitaj** [comment]
Do we send a verification email for SSO accounts? Maybe allow the SSO provider to specify whether to consider the email verified on registration.

**Comment by julianlam** [comment]
Right now? No we do not, I think we either by default set the `verified` bit in the user hash to `1`, or it's up to the SSO plugin, I will have to double-check (although I would think it is the former)

**Comment by barisusakli** [comment]
We also have `users:notvalidated` sorted set make that a system group as well `unverified-users`?

**Comment by pitaj** [comment]
unverified-users would be identical to `Registered - Verified` right? We decided on tracking Verified instead of unverified as it's one less negative to consider in the logic

**Comment by barisusakli** [comment]
`unverified-users` (registered but not verified email)
`verified-users`(registered and verified email)
`registered-users` (all registered users, so verified-users + unverified-users)

**Comment by barisusakli** [comment]
You will be able to filter in acp by unverified users like the current `users:notvalidated` sorted set, also you can give unverified users some privileges after this change like let them vote but not let them post etc. Or give them only access to some categories.

**Comment by pitaj** [comment]
But giving them those privileges would be the same as putting those privileges on registered-users, unless for some weird reason you didn't want verified users to have those privileges.

The only real benefit I see is the filtering in the ACP.

**Comment by barisusakli** [comment]
It's not the same, if you put them on `registered-users` `verified-users` and all other groups get it too. For example 

![image](https://user-images.githubusercontent.com/2583394/95903043-a240a100-0d63-11eb-8d38-69ab65151059.png)
Only unverified users will be able to see and post in this category.

**Comment by pitaj** [comment]
We're saying the same thing, I just don't see a use case for having a category that only unverified users can post in. It's fine though, guess more flexible is better.
