### ISSUE TITLE
Quoted post shouldn't be seen if it was deleted

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8668]
Hi, I thought it would be better to show this in a screenshot:

![image](https://user-images.githubusercontent.com/31972226/93928703-97c45600-fd27-11ea-936f-a5d97db43b13.png)

When a post is deleted by user or Mod, It still can be seen if the post was quoted.

**Comment by julianlam** [comment]
Hi, unfortunately the quoted post is text, and not a reference to the deleted post, so we cannot delete it in that way.
