### ISSUE TITLE
Remove plugin.json library property

### ISSUE THREAD

**Issue by pitaj** [NodeBB/NodeBB#8686]
The `package.json` property `main` fulfills this purpose, making `library` redundant. This also will allow us to simplify our code to just `require(plugin.id)` to get the plugin libraries.

Will deprecate the existing usage, issuing a warning if requiring the plugin as above fails, forcing us to fallback to `library`. Any error will cause us to fallback to `library`, for instance several themes define `"main": "theme.less"`, which will error when required, since `theme.less` is not a valid Node module.

**Plugin Authors**:
- In `package.json`, set `"main": "your/entry/point.js"` for forwards compatibility
- In `plugin.json`, set `"library": "."` for backwards compatibility

**Comment by braco** [comment]
This convention is still in your quickstart repo:

https://github.com/NodeBB/nodebb-theme-quickstart/blob/master/plugin.json#L3

**Comment by barisusakli** [comment]
@braco 
https://github.com/NodeBB/nodebb-theme-quickstart/commit/c1fff76fcc68f0e71fd92fef2262a21463ef2f64
