### ISSUE TITLE
Write API for /api/config

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#8723]
Is it possible to call /api/config using the Write API plugin in a server to server manner (where there is no session) and not be trapped by the csurf middleware?

**Comment by julianlam** [comment]
Are you looking to update server configs?

**Comment by uplift** [comment]
Sorry, Hurriedly written question when I'm task juggling. 

I'm trying to get the config for each user using the Nodebb Write API plugin via /api/config url (for settings such as topicsPerPage etc) but as far as I can tell the user settings part of the config never get accessed as the csrf protection blocks the auth from being set i.e req.lggedIn = false and req.uid = 0, so every user just gets defaults.

https://github.com/NodeBB/NodeBB/blob/b01bc2ae0fd4741944fe656951800c2b89fa8735/src/controllers/api.js#L76-L96

**Comment by julianlam** [comment]
@uplift When you say you're using the Write API to access, I'm assuming you mean you are attempting to pass in a bearer token to access the endpoint?

**Comment by uplift** [comment]
@julianlam Yeah with master bearer token and a _uid parameter for a user

**Comment by julianlam** [comment]
Understood, reproduced on write-api. Give me a second to fix... Right now we don't run `/api/config` through authentication middleware (because express-session handles it), so write-api bearer tokens don't trigger the authentication.

Fix is actually a little more involved, but still doable I think.

**Comment by julianlam** [comment]
Write-api v5.8.1

**Comment by uplift** [comment]
@julianlam Ah my debug-fu failed me, probably should have noticed that. Great news on the fix, will pull down and give it a try. Thanks for the quick response/fix!
