### ISSUE TITLE
cant give administrators privileges

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#8728]
1. click add group
2. select administrators
3. give them signature privilege
4. click save
5. admins disappear from table & they dont get the privilege

**Comment by barisusakli** [comment]
While working on this also noticed this 
![image](https://user-images.githubusercontent.com/2583394/95518598-64253500-0991-11eb-895a-892b3750b8d6.png)

Going to fix that one as well

**Comment by julianlam** [comment]
Nice catch thank you

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/12c8b1c2bc1d4ad0cfac5e20c4746f1204efd5eb
