### ISSUE TITLE
User can create infinite active sessions which are red from the database on every login

### ISSUE THREAD

**Issue by cryptoethic** [NodeBB/NodeBB#8730]
Reference topic:

https://community.nodebb.org/topic/15049/periodical-queries-for-nodebb-sessions

In our case user created over 40k active sessions and with his each login was causing a huge lag as there was a query for every session to database.

I suggested the solution in the previously mentioned topic. Let me know what do you think about it ;-)

Best,
cryptoethic

**Comment by barisusakli** [comment]
@cryptoethic can you open a PR for adding `revokeSessionsAboveTreshold(meta.config.maxUserSessions);` maybe the default should be 10 sessions which can be configured from the ACP.

**Comment by cryptoethic** [comment]
I would love to ;)
