### ISSUE TITLE
Unable to upvote on a topic at https://community.nodebb.org

### ISSUE THREAD

**Issue by fais3000** [NodeBB/NodeBB#8756]
On this topic https://community.nodebb.org/topic/15055/upgrading-from-0-7-3-advice when i tried to upvote the post. I saw following error.

<img width="1274" alt="2020-10-12_21-01-43" src="https://user-images.githubusercontent.com/25720059/95767642-7cb58800-0cce-11eb-9a9a-cb58fec66fab.png">

**Comment by pitaj** [comment]
Can you look in the browser console for an error stack trace?

**Comment by julianlam** [comment]
It's likely related to my merging in of the write API. There's probably a server side stack trace @fais3000

**Comment by barisusakli** [comment]
@fais3000 thanks for reporting, please let us know if you notice other issues.

**Comment by fais3000** [comment]
> @fais3000 thanks for reporting, please let us know if you notice other issues.

Fixed now, thanks! 
Will let you know.
