### ISSUE TITLE
Selecting category as a homepage

### ISSUE THREAD

**Issue by cryptoethic** [NodeBB/NodeBB#8757]
Hey!

There is a bug with selecting category as a homepage:

![image](https://user-images.githubusercontent.com/44468286/95774260-5852af00-0cc0-11eb-8bd3-6339dad5a18b.png)

![image](https://user-images.githubusercontent.com/44468286/95774186-33f6d280-0cc0-11eb-9c8a-2c7ff45b074a.png)

Moreover after refreshing settings page we can see Custom homepage with category ID:
![image](https://user-images.githubusercontent.com/44468286/95774314-73bdba00-0cc0-11eb-855a-f91be4e36282.png)

---

Temporary solution is to set the homepage category only via ID:
![image](https://user-images.githubusercontent.com/44468286/95774377-98199680-0cc0-11eb-989c-26bf4c5a224a.png)

Then everything works fine ;-)

In my ACP I can see 404 errors similar to:

`/api/category/6&`
`/category/7&`

Maybe there is an error with Uri encoding? Any ideas where to look deeper into it?

Best,
cryptoethic

**Comment by cryptoethic** [comment]
Correct. In current NodeBB we have:
`homePageRoute: ((data.homePageRoute === 'custom' ? data.homePageCustom : data.homePageRoute) || '').replace(/^\//, '')`

should be like that?

`homePageRoute: ((data.homePageRoute === 'custom' ? data.homePageCustom : data.homePageRoute) || '').replace(/^\//, '').replace('&#x2F;', '/')`

**Comment by cryptoethic** [comment]
Thanks ;-)

**Comment by barisusakli** [comment]
The route was being returned as `'category/6&#x2F;testing-ground'` Pushed to fix to https://community.nodebb.org/ as well.
