### ISSUE TITLE
Problem with showing user's latest posts

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/NodeBB#8763]
- **NodeBB version:** 1.15-beta.15

- **Database type:** mongo

Hi

In our forum in user's profile, NodeBB shows ```10``` latest posts from her. But for example consider this case:
Totally, our user has ```12``` posts. When we delete ```10``` of her latest posts, in her profile, NodeBB will not show any latest post. We deleted ```10``` posts so ```2``` posts remain. We should see them in the ```latest posts``` section in her profile, but we don't.

**Comment by pitaj** [comment]
Are they in different categories? Are any deleted or in deleted topics?

**Comment by mohammadhassan99** [comment]
I evaluated this senario in 1 topic. All posts were in same topic.
