### ISSUE TITLE
NodeBB needs Rust (if not using certain platforms)

### ISSUE THREAD

**Issue by hzhang1902** [NodeBB/NodeBB#8766]
Platform: Mac OS Catalina 10.15.6
Node: v12.18.3
NodeBB: 0.14.3

I was doing a fresh install on MacOS, and ran into this error:
```
> benchpressjs@2.0.7 install ~/Documents/NodeBB/node_modules/benchpressjs
> cd rust/benchpress-rs && npm install

npm WARN deprecated neon-cli@0.4.2: Please upgrade to 0.5.0

> benchpress-rs@0.1.0 install ~/Documents/NodeBB/node_modules/benchpressjs/rust/benchpress-rs
> node scripts/install

[benchpress] No compatible pre-built native module found! { platform: 'darwin', module_version: '72' }
[benchpress] Building native module from source...
neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! benchpress-rs@0.1.0 build: `neon build --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the benchpress-rs@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

So NodeBB is using benchpressjs. It needs to compile Rust code if ```No compatible pre-built native module found```, and it will fail if Rust is not installed. The list of pre-builts can be found in ```benchpressjs/rust/benchpress-rs/pre-built```.

This should be put into docs.
Also the doc page for MacOS is very outdated, it is still recommending download v0.10.x.

**Comment by pitaj** [comment]
Rust is actually not supposed to be required for installation of benchpressjs. That was in error (it should fallback to the JS version), and I have published a new version of benchpressjs.

    npm install benchpressjs@2.0.8

Is a temporary solution to your problem. Thanks for reporting!
