### ISSUE TITLE
v1.13.x shows as pre-release version

### ISSUE THREAD

**Issue by francis826** [NodeBB/NodeBB#8769]
Following: https://docs.nodebb.org/installing/os/debian/#installing-nodebb

- **NodeBB version:** v1.13.x
- **NodeBB git hash:** 

```
$ git status
On branch v1.13.x
Your branch is up to date with 'origin/v1.13.x'.

nothing to commit, working tree clean

$ git rev-parse HEAD
f879c4a84e137413f0bdd099e020ec0658124658
```

- **Database type:** mongo
- **Database version:** 3.2+

- **Exact steps to cause this issue:**
1. git clone -b v1.13.x https://github.com/NodeBB/NodeBB.git nodebb
2. cd nodebb
3. ./nodebb setup
4. ./nodebb start

- **What you expected:**

Stable version

- **What happened instead:**

`package.json` is saying this: 

```
{
  "name": "nodebb",
  "license": "GPL-3.0",
  "description": "NodeBB Forum",
  "version": "1.13.4-5",
  "homepage": "http://www.nodebb.org",
  "repository": {
    "type": "git",
    "url": "https://github.com/NodeBB/NodeBB/"
  },
```

The web interface is warning me:

> You are running NodeBB v1.13.4-5.
> This is a pre-release version of NodeBB. Unintended bugs may occur.

**Comment by francis826** [comment]
To reproduce, you can use the `node` docker image:

```
$ docker run -it node /bin/bash
```
```
root@63b82b094fb5:/# node --version
v14.13.1
root@63b82b094fb5:/# git clone -b v1.13.x https://github.com/NodeBB/NodeBB.git nodebb
Cloning into 'nodebb'...
remote: Enumerating objects: 278, done.
remote: Counting objects: 100% (278/278), done.
remote: Compressing objects: 100% (236/236), done.
remote: Total 199845 (delta 89), reused 117 (delta 42), pack-reused 199567
Receiving objects: 100% (199845/199845), 58.08 MiB | 23.13 MiB/s, done.
Resolving deltas: 100% (154888/154888), done.
root@63b82b094fb5:/# cd nodebb/
root@63b82b094fb5:/nodebb# ./nodebb setup
package.json not found.
Populating package.json...
OK

...

Welcome to NodeBB v1.13.4-5!
```

**Comment by julianlam** [comment]
Thanks -- the prerelease versions should not be shown, we have updated our deployment process accordingly and force-pushed the `v1.13.x` branch back to the original v1.13.3 release.
