### ISSUE TITLE
carousel slider not working after updating to nodebb version 1.14.3

### ISSUE THREAD

**Issue by alankrit29** [NodeBB/NodeBB#8770]
- **NodeBB version:**  1.14.3
- **NodeBB git hash:** 668ad8abf753ffca24b31e07a390bb2c52d2d3c9

- **Installed NodeBB Plugins:** 
	* nodebb-plugin-align-center (installed, enabled)
	* nodebb-plugin-category-notifications (installed, enabled)
	* nodebb-plugin-category-optin (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-desktop-notifications (installed, enabled)
	* nodebb-plugin-email-blacklist (installed, disabled)
	* nodebb-plugin-emailer (installed, disabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-emoji-static (installed, enabled)
	* nodebb-plugin-lightbox (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-math-captcha (installed, enabled)
	* nodebb-plugin-mega-colors (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-ns-custom-fields (installed, enabled)
	* nodebb-plugin-ns-points (installed, enabled)
	* nodebb-plugin-reactions (installed, enabled)
	* nodebb-plugin-recent-cards (installed, enabled)
	* nodebb-plugin-sanitizehtml (installed, enabled)
	* nodebb-plugin-share-post-icons-cn (installed, enabled)
	* nodebb-plugin-shortcuts (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-plugin-subcategories-checker (installed, enabled)
	* nodebb-plugin-topic-tags (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-persona-v1 (installed, disabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongodb
- **Database version:** 3.6.9
- **Exact steps to cause this issue:**
We have a forum based on nodebb. Recently we have upgraded nodebb to latest version 1.14.3. Since then, carousel slider on forum stopped sliding to next tiles. I can only see four tiles on the slider bar as it is not sliding anymore. I am not getting any errors at nodebb logs. Please check.
- **What you expected:**
Carousel slider should work properly on clicking arrow button on the either side.
- **What happened instead:**
Slider should move on clicking arrow buttons but same tiles/sections are reappearing.

**Comment by barisusakli** [comment]
Are you using this pluginhttps://github.com/NodeBB-Community/nodebb-plugin-recent-cards, what version?

**Comment by alankrit29** [comment]
Thank you for your response.
nodebb-plugin-recent-cards version is 2.0.7.
Refer https://prnt.sc/v0llqr

Thanks.

**Comment by barisusakli** [comment]
>Carousel slider should work properly on clicking arrow button on the either side.
This is most likely because you need latest nodebb fixes specificially this one https://github.com/NodeBB/NodeBB/commit/6669b23d9aa8c6570841ebd660e205b087061d6a

You can either update core nodebb or downgrade the recent cards plugin to 1.0.13 and wait for 1.15.0 to release.
