### ISSUE TITLE
 Make a difference style between the main post of the topic and other posts in that topic

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#8778]
- **NodeBB version:** 1.15.0-beta.29

In the latest update, the toolbar is placed at the top of the pages Similar to the photo below
![image](https://user-images.githubusercontent.com/37838903/96617925-199ca480-1311-11eb-8979-8478d217d055.png)

Previously, this toolbar was used as a separator of the main topic post from other posts
But now there is no clear separator between these posts

Maybe the different styles of the main post can play this role

do you agree?

**Comment by barisusakli** [comment]
We should also find a subtle way to highlight posts from OP.
