### ISSUE TITLE
move all topic doesn't work

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#8779]
- **NodeBB version:** v1.15.0-beta.29

- **Installed NodeBB Plugins:** 

- **Database type:** mongo
- **Database version:**  4.2.3

- **Exact steps to cause this issue:**

	1. First ,I went to a category
	2. Then, I clicked on topic Tools and move all

- **What you expected:**

I expected after selecting the new category and clicking the Move button
Move all topics to a new category, but nothing happened by clicking

Also, do not move by selecting a few topics and repeating the previous steps

I think this button(Move All) does not work at all
- **What happened instead:**
nothing

**Comment by barisusakli** [comment]
@roghaye-m thanks for reporting 👍
