### ISSUE TITLE
Feature Request: Make it easier to upvote / downvote (larger targets)

### ISSUE THREAD

**Issue by lonkle** [NodeBB/NodeBB#8782]
It's impossible to hit the upvote, downvote, or the number (to tell you who "voted" on your post), while on mobile. Even as big a screen as the iPhone 11.

I'd suggest making the icons more obvious and the target's much bigger (if only for mobile, they're easy enough to hit on desktop but upvoting / downvoting could still get a little more polished defined / even on desktop). Not a lot of people use the votes on my board because of how hard they are to use.

**Comment by julianlam** [comment]
@lonkle You just need a more precise finger. Might I recommend using the itty bitty part of your fingertip by the nail? It's what everyone else does.

/s

It's an easy fix, thanks for reporting. This one's bugged me for ages, I just kept putting it off :smile:

**Comment by lonkle** [comment]
You’re the hero we all deserved! ☺️
