### ISSUE TITLE
Feature Request: Click the number of upvotes to "see all who voted"

### ISSUE THREAD

**Issue by lonkle** [NodeBB/NodeBB#8785]
Basically the same as clicking Facebook likes. Seeing who voted and for what is important. Right now, you can hover over the number to see a limited number of post voters (up and / or down, NodeBB doesn't distinguish).

**Comment by julianlam** [comment]
We have this 🤔

**Comment by lonkle** [comment]
Is it a setting I have to enable. Because on hover I can see the first 5 upvoters (I don't think you guys display downvoters, but you should). Anyway I used Safari and Chrome on macOS and clicked a post with 13 upvotes. Clicking the number does nothing. Hovering it shows me the last 5 people to upvote though.

**Comment by julianlam** [comment]
Might be a bug, when I click it I see this:

![image](https://user-images.githubusercontent.com/923011/97027569-e92f5300-1528-11eb-9f70-6c63e9051704.png)

**Comment by barisusakli** [comment]
THere is an acp setting to make votes public,

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/97030557-ef273300-152c-11eb-80a4-57fce25743ab.png)


I vaguely recall that we used to show only upvotes and not downvotes, I guess this behaviour was removed?
