### ISSUE TITLE
Feature Request: Remove duplicate notifications

### ISSUE THREAD

**Issue by lonkle** [NodeBB/NodeBB#8787]
If someone @ mentions in a thread I'm watching and get notified about anyway, it gives me two notifications for the exact same thread for the exact same post. I feel like the notification system could merge those two into one since they're literally referencing the exact same post just in different ways. But boy does it make notifications seem a lot more overwhelming than they typically are.

**Comment by julianlam** [comment]
@lonkle I have reverted this commit, use this option instead:

![](https://user-images.githubusercontent.com/37838903/99278893-dd436200-2844-11eb-9884-96673733faa5.png)

**Comment by lonkle** [comment]
Is that an admin or user setting? I can't find it in user settings, but it looks like it should be a user setting.

**Comment by julianlam** [comment]
Hi Joel,

It is an admin setting at this time. It does make sense as a user setting, so I will consider it for the future.

**Comment by lonkle** [comment]
Great, cause I'm just a user, I'll see if I can convince an admin to change that setting. Thank you for considering adding it to user settings! ☺️
