### ISSUE TITLE
option to disable compression middleware in production

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#8801]
Right now it is always enabled in webserver.js 

https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression

For a high-traffic website in production, the best way to put compression in place is to implement it at a reverse proxy level (see Use a reverse proxy). In that case, you do not need to use compression middleware. For details on enabling gzip compression in Nginx, see Module ngx_http_gzip_module in the Nginx documentation.

**Comment by julianlam** [comment]
I think it'd make more sense to have it disabled by default, and enable via ACP
