### ISSUE TITLE
category manage tools didn't work in ACP 

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#8804]
- **NodeBB version:** v1.15.0-rc.0

- **Database type:** mongo, redis, or postgres
- **Database version:**  mongo, redis,

- **Exact steps to cause this issue:**

	1. First I did this...
         i went to ACP page and clicked on mange from menu and I  clicked on categories
	2. Then, I clicked on tools box and  clicked on disable item
![image](https://user-images.githubusercontent.com/37838903/97500254-7ee13d00-1984-11eb-833f-9bcbc5e0f3e2.png)

- **What you expected:**
I expected Disable category 
- **What happened instead:**
It just faded(took disabled style) without being disabled 
![image](https://user-images.githubusercontent.com/37838903/97500313-9d473880-1984-11eb-86f1-33040ef66bd2.png)

and when i refreshed page  took  enable style
i try it from category page and result is same .

I tried other items (like edit,...),they did not work
i think they didn't save.

**Comment by barisusakli** [comment]
I can't reproduce on v1.15.0-rc.2 🤔

**Comment by julianlam** [comment]
@barisusakli I reproduced, it is related to admin logout timer, which does not play nice with the new API.

A less than ideal workaround at this time would be to log out and log back into the admin panel. You will be able to update category settings then.

**Comment by roghaye-m** [comment]
i log out and login and it work 
Why not make an error to login again?

I did not get time, but when I am in the panel for more than a few minutes, despite being active
When I want to create a new category
it  wants me to log in again

**Comment by julianlam** [comment]
Yes, the idea is that you are automatically logged out of the ACP after a certain idle time. It might be buggy, but I will look into its implementation.
