### ISSUE TITLE
write-api is broken with v1.15.0-rc.2

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#8805]
- **NodeBB version:** v1.15.0-rc.2 
- **NodeBB git hash:** 7c08413
- **Installed NodeBB Plugins:** nodebb-plugin-write-api": "^5.8.1
- **Database type:** mongodb 
- **Database version:** 4.x 
- **Exact steps to cause this issue:** post a topic to api/v1 or /v2
- **What you expected:** new created topic in nodebb 
- **What happened instead:** after 1 minute: 504 Gateway Time-out
**switch back to 1.14.3 everything works fine**

**Comment by julianlam** [comment]
@awunnenb Thanks for reporting, we will get this sorted out.

**Comment by julianlam** [comment]
@awunnenb I was not able to successfully reproduce your issue (in that the request was not hanging when I called), but I received this instead:

```
{                                                 
    "code": "not-authorised",
    "message": "A valid login session was not found. Please log in and try again.",
    "params": {}                                                                                    
}
```

Which is an API v3 error. The above commit should fix this.
