### ISSUE TITLE
Categories pagination/infinite loading and sorting

### ISSUE THREAD

**Issue by oplik0** [NodeBB/NodeBB#8813]
I actually wanted to propose this some time ago, but thought that it's a really unique issue to my use case - however [it seems that at least 2 other people have a large number of categories](https://community.nodebb.org/topic/433/how-many-category-can-create-by-nodebb) :) And I'd suspect there are other people who'd like to use NodeBB in a way that would require a large number of categories but can't because of this.

Basically, right now NodeBB paginates topics and posts, but categories are always on a single page (well, subcategories are on a parent category page), loaded all at once. This can present both usability and performance issue.

For example, I keep a fork of Persona theme around just to add lazy loading to category images - because with a larger number of categories with images they quickly add up to slow loading and Lighthouse screaming about images.

Another utility that both topics and posts have is sorting - even being able to sort newest to oldest (or the other way around) or by most topics/posts would greatly improve usability of long lists of categories.

Of course I also understand that this need is not universal - for some types of forums it's better to only have manually arranged categories. And I don't like proposing options for something that could be done in a plugin. But in this case a plugin doesn't seem ideal, as it would need to override the default categories controller in order to do it properly. So ideally this should be a setting just like pagination vs infinite scroll is for topics and posts.

**Comment by barisusakli** [comment]
There are couple places that need re-thinking
- /categories loads entire category tree
- /category/<slug> loads all children categories
- /recent, /unread, /popular, /top loads entire category tree to populate category dropdown
- composer loads entire category tree to populate category dropdown

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/9233
