### ISSUE TITLE
allow guests to increment topic view counts

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8821]
Hello everyone!

With my team we've found a curious bug. 

The views are unique and only for logged in users.

I think that views shouldn't be unique and have to count all users, not only the logged in.

What do you think about that?

**Comment by barisusakli** [comment]
Will make this an option in the ACP so guests count towards views.

**Comment by andreadragotta** [comment]
Ok, and for the unique view? 
On ACP can set it or change the counting method?

**Comment by barisusakli** [comment]
They are not unique, they only increment once per hour so you can't keep reloading the page and increment views. https://github.com/NodeBB/NodeBB/blob/master/src/controllers/topics.js#L132

**Comment by pitaj** [comment]
Sounds like we should also make that time limit configurable.

**Comment by andreadragotta** [comment]
Thank you @barisusakli 
I think is interesting set the time limit configurable as @pitaj wrote
