### ISSUE TITLE
Global Mods are unable to ban/unban users despite having ban privilege

### ISSUE THREAD

**Issue by cra10** [NodeBB/NodeBB#8827]
NodeBB version: v1.15.x
Commit: a30aa5629cb51c881ea99431e739c8813ecfded8

![image](https://user-images.githubusercontent.com/40766708/98180732-92c1fd00-1eb6-11eb-94e8-c9ade95e9445.png)

With this configuration Global Mods are able to see the Ban option but will receive "You do not have enough privileges for this action" prompt.

![image](https://user-images.githubusercontent.com/40766708/98181027-37dcd580-1eb7-11eb-9f09-a7314c22fb2e.png)

Only after giving them admin panel access can they actually ban users

**Comment by julianlam** [comment]
Hi @cra10 thanks for reporting.

Looks like a conflict with the new admin privileges, but you're correct, banning a user shouldn't require the admin user management privilege.

**Comment by cra10** [comment]
Thanks for the fix! btw I know it's off topic but are you still open to paid plugin development requests?

**Comment by julianlam** [comment]
Always, just shoot us an email at sales@NodeBB.org 🙂
