### ISSUE TITLE
NodeBB 1.15.x - error related to /forum/compose in log

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#8840]
- **NodeBB version:** 1.15.x
- **NodeBB git hash:** a30aa5629cb51c881ea99431e739c8813ecfded8 (+cherry picked 76cd5b0fc1967f4ba14211ccab7213c49c0ddb04)

- **Installed NodeBB Plugins:** 

Active plugins:
	* nodebb-plugin-category-notifications (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, disabled)
	* nodebb-plugin-emoji-android (installed, disabled)
	* nodebb-plugin-gdpr (installed, enabled)
	* nodebb-plugin-google-analytics (installed, enabled)
	* nodebb-plugin-gravatar (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-ns-embed (installed, enabled)
	* nodebb-plugin-recent-cards (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-rewards-essentials (installed, disabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo + redis
- **Database version:** 4.2.10

Seeing this in the output.log - not seeing an issue on the frontend but thought it's worth mentioning.

```
2020-11-06T01:22:58.949Z [4568/9259] - ESC[31merrorESC[39m: /forum/compose
Error: [[error:invalid-data]]
    at exports.get (nodebb/src/controllers/composer.js:26:19)
    at async nodebb/src/routes/helpers.js:34:5
(node:9259) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at ServerResponse.header (nodebb/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (nodebb/node_modules/express/lib/response.js:170:12)
    at ServerResponse.renderOverride [as render] (nodebb/src/middleware/render.js:79:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9259) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an a
sync function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandle
d_rejections_mode). (rejection id: 2)
(node:9259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are 
not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by barisusakli** [comment]
@joolswills thanks for reporting, let me know if the issue is resolved. It was reproducible by calling `domain.com/forum/compose` with no query params. That route is usually called with at least one of `?pid`, `?tid` or `?cid`

**Comment by joolswills** [comment]
Looks resolved - thanks very much for the speedy fix.
