### ISSUE TITLE
Allow users and groups to have the same slug again

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8843]
8a510c340bb52b63f8e98ca866a589208ff044d2 introduced a restriction that disallowed users and groups from having identical slugs.

E.g. a user named "foobar" cannot create a group also named "foobar".

Why? I don't know, but if anyone can chime in that'd be helpful for context. Without context this restriction seems unnecessary and should be reverted.

**Comment by barisusakli** [comment]
If a group and user has the same slug a mention would notify them both

**Comment by julianlam** [comment]
A ha.... that's why... :heavy_check_mark:
