### ISSUE TITLE
Missing settings/api.json & api.json in the de translation folder 

### ISSUE THREAD

**Issue by tobiasdossinger** [NodeBB/NodeBB#8852]
- NodeBB version: 1.15.0
- NodeBB git hash: 540a32cfdddbec1c8e691b5e7763a1ef4f0e12fe ** 

Installed NodeBB Plugins:

**Active plugins:**
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, disabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

Database type: redis
Database version: 6.0.9

- **Exact steps to cause this issue:**
When I updated NodeBB to v1.15.0, I recognized that when I was toggling in the admin panel, that under settings the setting/api option and the page itself wasn´t translated into german. So I added the api.json & the setting/api.json to the file structure under the de folder in languages. I was trying to fix it in transifix but I couldn´t find the api tag.

**It would be nice if I could just commit the change to the repository on a fix branch :)**

Thank you!

**Comment by julianlam** [comment]
Thank you, it looks like I forgot to push the language keys to Transifex, I'll fix this shortly.

**Comment by julianlam** [comment]
Fixed via 4e85b5aca78ed5da627be7734b2392fcaba9870b
