### ISSUE TITLE
uncaughtException: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by okpierre** [NodeBB/NodeBB#8853]
Followed the docs for new installation (v1.15.0) but got error message

ran command: 
`./nodebb setup`

then this error showed up:
`uncaughtException: ENOENT: no such file or directory, open /nodebb/build/public/rjs-bundle-client.js`

**Comment by barisusakli** [comment]
Take a look here, sounds like the same issue https://github.com/NodeBB/NodeBB/issues/8846

**Comment by okpierre** [comment]
Sorry if I'm not fully understanding what's being discussed for a new install

Here's my system: Ubuntu 20.04 64-bit / 4GB memory

Am I asked to run commands that's different from the official docs?

**Comment by barisusakli** [comment]
Does your system have any swap setup? Does running `./nodebb build` error? If it does error can you try running `./nodebb build --series` and check if there are any errors?

**Comment by okpierre** [comment]
With `./nodebb build` it starts with the following message:

`(node:3523) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`

but it does show _Asset compilation successful_ at the end

Safe to ignore warning?

**Comment by barisusakli** [comment]
Yeah it's safe to ignore that for now. Are you still getting an error on `./nodebb setup`?

**Comment by okpierre** [comment]
After `./nodebb build` and then now running `./nodebb setup` it is showing _NodeBB Setup Completed_

Not sure what caused the problem. Thanks for your assistance!
