### ISSUE TITLE
NodeBB Demo not loading stylesheet

### ISSUE THREAD

**Issue by simonorzel26** [NodeBB/NodeBB#8860]
- latest
- NA

- NA

	1. Go on NodeBB Demo link https://try.nodebb.org/
	2. css isnt loading
- Page to display with CSS included

- Page displayed only html

**Comment by pitaj** [comment]
Hmm, looks like MIME types are messed up.

**Comment by simonorzel26** [comment]
Still not working...

**Comment by barisusakli** [comment]
https://github.com/postcss/postcss/issues/1464

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/8882

**Comment by barisusakli** [comment]
Should be fixed again let us know if it happens again.
