### ISSUE TITLE
Account Data Hooks Request

### ISSUE THREAD

**Issue by chunterb** [NodeBB/NodeBB#8861]
**NodeBB version:** 1.15.0

I would like to request some hooks for getting specific user account data such as: 
- Session History
- IPs
- Username History
- Email History
- Latest Flags
- Recent Ban History
- Moderation Notes

It will be used for more granular restrictions on what a user can view on another user. The main reason for me needing it is for restricting users from being able to view other user IPs. I can hook into the info controller to filter out the `IPs` value, but that still leaves things such as session history (contains the IP), and exporting user data to spreadsheets vulnerable. 

I've tried to double check on this to make sure there there isn't any other way, so if I've still missed a way to accomplish this then please let me know.

Thanks.

**Comment by barisusakli** [comment]
Isn't filter:account/info.build enough to filter out all those items you listed?

Which other pages/output are you trying to filter?
