### ISSUE TITLE
Improving the Appearance of Deleted Comments

### ISSUE THREAD

**Issue by MasterLillyclaw** [NodeBB/NodeBB#8870]
When a user views their deleted comment, the original text is greyed-out. In contrast, when a user views a different person's deleted comment, it says something like "This comment has been deleted" in place of the original text.

Just having a greyed-out version of the comment makes it seem like the message is simply having trouble uploading to the forum or some other issue - messaging services like Discord often use that "faded text" to symbolize the message is still sending or failed to send. I think appending something to the comment such as "Your comment has been deleted" would be helpful in clarifying that the message is, in fact, deleted.

(I'm not sure if this applies to all themes or a specific one; I was using the J-Novel Club forum when I thought of this.)

**Comment by barisusakli** [comment]
It's up to the theme to determine what the `.deleted` class does, in persona it just adds opacity: 0.3 to the content element.

Unprivileged users don't see the contents of deleted posts this is separate from the styling. So you could override the css and remove the opacity but regular users still won't see the content of deleted posts.

It is very simple for a theme to add additional messaging to posts if they are deleted. ie 

```
{{{ if posts.deleted }}}
this post is deleted 
{{{ end }}}
```

This can be added anywhere in the post.tpl and it will show a message for deleted posts.
