### ISSUE TITLE
Still missing "settings/api": tag in translation/de/menu.json 

### ISSUE THREAD

**Issue by tobiasdossinger** [NodeBB/NodeBB#8872]
- **NodeBB version: v1.15.1** 
- **NodeBB git hash:** 
daf2e73c2919f899438f8da2331143d1e2a5bebb
- **Installed NodeBB Plugins:** 
Active plugins:
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-custom-pages (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, disabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)
- **Database type:** redis
- **Database version:** 
Redis server v=6.0.9 
- **Exact steps to cause this issue:**
Getting Missing translation "admin/menu:settings/api" for language "de" in the command line
- **What you expected:**
Existing translation
- **What happened instead:**
not existing translation

**Comment by julianlam** [comment]
Ah, hm... let me look into it, sorry about that!
