### ISSUE TITLE
Disabling local login/registration in v1.15.1 causes a crash on login

### ISSUE THREAD

**Issue by tmfksoft** [NodeBB/NodeBB#8883]
I've setup an oauth plugin for FusionAuth so I can use oAuth logins.

However, when the user clicks login NodeBB errors and restarts. Refreshing the page then works fine.
I've poked around and managed to find the source of the issue.

The error stack is as follows:
`
2020-11-14T22:59:09.342Z [4567/31189] - [31merror[39m: TypeError: url.startsWith is not a function
    at Object.helpers.redirect (/home/www/NodeBB-1.15.1/src/controllers/helpers.js:147:31)
    at /home/www/NodeBB-1.15.1/src/controllers/index.js:137:20
    at /home/www/NodeBB-1.15.1/src/promisify.js:44:33
    at cb (util.js:207:31)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`
It looks like the code in index.js on line 137 calls the redirect method in helpers.js on line 147 and supplies an object.
The redirect method uses `url.startsWith` to check for an API String even though the supplied url is an object and not a string.

The object received by the redirect method in my case is this:
`{ external: '/auth/fusionauth-oidc' }`

I'm unsure what the correct fix would be, maybe a string check first?
This appears to be the breaking commit:
https://github.com/NodeBB/NodeBB/commit/60e1e99b4f2fef7178f8770dcba9e82e5ed31f15#diff-44b42ddbb8cdc2733109eb02bf8ad54228d45d9cdfbac98c5bdea43623523343L147

I hope this helps.

**Comment by barisusakli** [comment]
We could add a check so nodebb doesn't crash but the correct fix would be to update the plugin so it calls helpers.redirect with an url like this `helpers.redirect(res, '/auth/fusionauth-oidc')`

**Comment by tmfksoft** [comment]
> We could add a check so nodebb doesn't crash but the correct fix would be to update the plugin so it calls helpers.redirect with an url like this `helpers.redirect(res, '/auth/fusionauth-oidc')`

A check would be good.
The plugin doesn't call this, index.js line 137 calls the redirect its self using the first login strategy url:
https://github.com/NodeBB/NodeBB/blob/master/src/controllers/index.js#L137

**Comment by barisusakli** [comment]
Let me know if it works know, I am not sure about this https://github.com/NodeBB/NodeBB/commit/03208807e444e8583051ed8fd04dedcc491ba5c3 since helpers.redirect doesn't handle objects
