### ISSUE TITLE
invalid csrf on relogin

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#8884]
happens on https://community.nodebb.org/ from time to time

1. logout
2. go to /login
3. try to login, resultsin invalid csrf error
4. try to login again works fine

**Comment by julianlam** [comment]
Potential context, csrf token is invalidated on session end and recreated anew on session start. Possibly race condition?

**Comment by barisusakli** [comment]
`config.csrf_token` was cached in the header for guests which was causing the issue.
