### ISSUE TITLE
more 503 error

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#8898]
- **NodeBB version:** v1.15.1
- **NodeJS version:**

- **Installed NodeBB Plugins:** 

- **Database type:** mongo, redis, 
- **Database version:** 
MongoDB Version 4.2.3
Redis Version 5.0.7

- **Exact steps to cause this issue:**

- **What you expected:**

- **What happened instead:**

We have recently received more 503 error
Sometimes it takes 30 minutes to resolve without any action
What could be the reason?
I do not know how to log and send it to you

**Comment by barisusakli** [comment]
503 errors are sent by this piece of code 

```
middleware.busyCheck = function busyCheck(req, res, next) {
	if (global.env === 'production' && meta.config.eventLoopCheckEnabled && toobusy()) {
		analytics.increment('errors:503');
		res.status(503).type('text/html').sendFile(path.join(__dirname, '../../public/503.html'));
	} else {
		setImmediate(next);
	}
};
```
You can configure it in the ACP /admin/settings/advanced#traffic-management.

It usually happens when traffic is higher than your server can handle. Monitor your cpu usage and traffic.
