### ISSUE TITLE
ability  to select a category for post queue

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#8900]
Sometimes i want only certain category posts to be queued

**Comment by barisusakli** [comment]
The posts of users are queued if it's their first post OR their reputation is below `postQueueReputationThreshold`(default 0). 
If you disable post queue for a category a spammer can post in that category to get their first post and then go post in the other categories. So it you should increase `postQueueReputationThreshold` from it's default 0 if you plan on disabling the post queue for certain categories.
