### ISSUE TITLE
 Menus do not close

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#8915]
- **NodeBB version:** v1.15.2

- **Installed NodeBB Plugins:** 

- **Database type:** mongo, redis, 

- **Exact steps to cause this issue:**

	1. First I clicked on notification icon (or chats icon) on  the menu
	2. Then, I clicked another icon(or other link of our forum)
- **What you expected:**

When I go to the new link, i expected the Drop Down menu of notifications to be closed

- **What happened instead:**

 but It was still open !

We also have this problem in the phone version for the main menu of the site

**Comment by barisusakli** [comment]
What theme are you using? Work fine on master and https://community.nodebb.org/

**Comment by roghaye-m** [comment]
We use the same theme(the persona theme)
This conflict does not always happen, but it does happen most of the time.
Can you test the link? https://forum.alaatv.com
Especially the notification part with the desktop version

**Comment by barisusakli** [comment]
Thanks I was able to reproduce, happens on really slow sites if the notification icon is clicked before any event handlers are attached

**Comment by roghaye-m** [comment]
you're welcome.
Exactly the same for the icons I said at the beginning.
