### ISSUE TITLE
Hyperlink POSTS, FOLLOWERS, FOLLOWING, even though available in the three dot menu

### ISSUE THREAD

**Issue by jidanni** [NodeBB/NodeBB#8924]
The user wants to see his old posts.
The user thinks:
I see `Best posts made by jidanni`.
I see `Latest posts made by jidanni`.
I scroll down to the bottom of `Latest posts made by jidanni`... but it ends after just a few.
I look around the web page.
Ah, I see I have "84 POSTS". But clicking it does nothing!
I give up.

Sure, if I were smart I would probe the three dot menu.

But imagine if this were Facebook, and it said 84 Posts, but clicking it
did nothing?

> We are not Facebook.

Yes. Anyway, please hyperlink the
- 7.9k POSTS
- 261 FOLLOWERS
- 2 FOLLOWING

to the same places they link to in the three dot menu. Thanks.

![1801-4](https://user-images.githubusercontent.com/1230959/99860202-589e6e00-2bcd-11eb-8909-bb55b20a4b40.jpg)

Version: as in https://community.nodebb.org/

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/100005908-aff03a00-2d97-11eb-9c6f-2b4ce4727435.png)
