### ISSUE TITLE
Server hook documentation messed up??

### ISSUE THREAD

**Issue by ledlamp** [NodeBB/NodeBB#8927]
It looks to me like the [server-side hook documentation](https://github.com/NodeBB/NodeBB/wiki/Hooks#server-side-hooks) has been erroneously auto-generated from the test scripts instead. 

![](https://pmod.qonq.gq)

**Comment by psychobunny** [comment]
fixed via https://github.com/NodeBB/docgen/commit/c0bd976be8ec3cf59737b0ac33f821ecbb04b9ad
