### ISSUE TITLE
+ as a part of the User Name

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#8939]
Start here:
https://community.nodebb.org

Register new user and use '+' special character.

a+ username passes (form field changes color to green) but NodeBB returns username too short error. '+' seems to not be recognized as a normal character.

Next thing. When a+ is too short I will take abc+ username or any other with '+' on the end. And at least two things needs to be checked and fixed.

First thing.
Empty notification (red '1' on the Notifications icon) on the early stage after creating new account (abc+). When trying to see what it is (See all notifications) NodeBB shows nothing (You have no new notifications). It helps to use Mark all notifications read option and it dissapears (red '1' no longer alerting).

Second thing.
Selected username abc+ is recognized by NodeBB as abc+ 0 (extra '0' on the end).
Everywhere I can see abc+ 0 (username) and @ABC+ 0 (how to mention a user in a message).
When trying to change username NodeBB tells it is abc+ 0 and not selected and confirmed abc+.

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/100139897-28213300-2e5e-11eb-8587-afc6dffa1a4c.png)
The fix is for the missing notification, when you

**Comment by barisusakli** [comment]
Going to open another issue for the `abc+` issue
