### ISSUE TITLE
Order of groups on user profile

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#8944]
Tested here using public groups.
https://community.nodebb.org

NodeBB changelog contains an entry '_fix the order of groups on user profile_ (41f8da2e)'. Profile page also contains extra comment for Group Title - _Select a group and use the arrows to order titles_.

But you can only select one group or use Ctrl/Shift keys to make a multi-select. There is no way to change their order. NodeBB shows GNU/Linux, FreeBSD/OpenBSD, Swedes, Gamers, Anime Lovers labels and you can't tell it to sort it in alphabetical order or in some other way (custom/selected by end user).

**Comment by barisusakli** [comment]
Clicking the arrows moves the item and control click lets you select more than one group. Is this not working for you?

![groups](https://user-images.githubusercontent.com/2583394/100285668-4874ee80-2f3f-11eb-8d17-0fe1061a76b5.gif)

**Comment by nhlpl** [comment]
OK, you need to click those arrows and stop using hardware arrows. Now it works! Thanks.

Closing.
