### ISSUE TITLE
A Former User and Session Mismatch in a loop

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#8950]
Please take a look here:
https://try.nodebb.org/topic/10/123

I can see something like this:
![formatting](https://user-images.githubusercontent.com/11160550/100319443-e5776c00-2fbf-11eb-926a-9bd99e329ab8.jpg)

Copied link from above to Chrome and it tells me Access Denied and shows **Session Mismatch** in a loop. I mean when clicking OK it will be popped-up again and again. No way to use any other buttons. See below.

![session](https://user-images.githubusercontent.com/11160550/100320137-0ab8aa00-2fc1-11eb-9de2-8d81611ca30d.jpg)

Can't be reproduced in browsers where try.nodebb.org was used earlier. Both normal and private windows/tabs.

**Comment by julianlam** [comment]
try.nodebb.org resets daily, likely your existing login session got deleted, you'll have to clear your cookies to get out of the session mismatch loop

**Comment by nhlpl** [comment]
This is exactly what I think it is. DB no longer stores session information on the server side.

Closing.
