### ISSUE TITLE
/register/abort is not found

### ISSUE THREAD

**Issue by ye-yu** [NodeBB/NodeBB#8951]
- **NodeBB version:** v1.15.3
- **NodeBB git hash:** c0d406ae68c285da3ad6ce630e7e73d20f1a7a22
- **NodeJS version:** v14.2

- **Installed NodeBB Plugins:** 

	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-custom-pages (installed, disabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-plugin-sso-auth0 (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, disabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, enabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo
- **Database version:** v4.2.11

- **Exact steps to cause this issue:**

  1. Create a dummy registration information.
  2. Submit the registration.
  3. Cancel the registration on the consent confirmation page
- **What you expected:**
User is notified that the registration is cancelled / User should be redirected back to the home page.
- **What happened instead:**
An error page saying (roughly translated):

> **/register/abort is not found**
> The requested page is not found. Return to the home page.

![image](https://user-images.githubusercontent.com/30603031/100320863-c945f000-2ffc-11eb-867d-76ea78488a15.png)

**Comment by nhlpl** [comment]
Tested it on both community.nodebb.org and try.nodebb.org and I'm redirected to NodeBB Home (start page).

A list of plugins on try.nodebb.org:
Installed nodebb-plugin-dbsearch
Installed nodebb-plugin-emailer-sendgrid
Installed nodebb-plugin-spam-be-gone
Installed nodebb-plugin-iframely

**Comment by ye-yu** [comment]
Are community.nodebb.org and try.nodebb.org both using v1.15.3? afaik v1.15.3 is released just recently

**Comment by nhlpl** [comment]
I have tested it for many times before and after v1.15.3 being released. It means it should work fine on a fresh install and an issue can be related to upgrade steps and maybe plugins.

**Comment by ye-yu** [comment]
I will try reinstall the whole thing again and redo.

**Comment by ye-yu** [comment]
Reinstallation worked well with the following plugins:
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, disabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, disabled)
	* nodebb-plugin-sso-auth0 (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

I just used nodebb today. Previously, I turned a few themes and plugins on and off and rebuilding nodebb at every changes made. I am not sure if this caused the error.
