### ISSUE TITLE
Navigation urls break periodically

### ISSUE THREAD

**Issue by fais3000** [NodeBB/NodeBB#8952]
Navigation links will change the special characters like "/" ":" to coded form "&#x2F;t" after few days. This happens at no specific time but does happen frequently like after a week or sometimes even after days. Also note, it changes all links that have special characters. This started happening after Nodebb 1.14.1, now forum is on Nodebb 1.14.3.

List of plugins

	* nodebb-plugin-adsense (installed, enabled)
	* nodebb-plugin-audio-control (installed, disabled)
	* nodebb-plugin-audio-embed (installed, enabled)
	* nodebb-plugin-beep (installed, disabled)
	* nodebb-plugin-browsing-users (installed, enabled)
	* nodebb-plugin-category-sort-by-votes (installed, disabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-custom-homepage (installed, enabled)
	* nodebb-plugin-custom-pages (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emailer-mailgun (installed, enabled)
	* nodebb-plugin-embed-combo (installed, disabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-emoji-apple (installed, enabled)
	* nodebb-plugin-emoji-extended (installed, enabled)
	* nodebb-plugin-emoji-one (installed, enabled)
	* nodebb-plugin-giphy (installed, enabled)
	* nodebb-plugin-groups-autoassigncategory (installed, disabled)
	* nodebb-plugin-imagemagick (installed, enabled)
	* nodebb-plugin-imgur (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-ns-awards (installed, enabled)
	* nodebb-plugin-ns-custom-fields (installed, enabled)
	* nodebb-plugin-ns-embed (installed, enabled)
	* nodebb-plugin-ns-points (installed, enabled)
	* nodebb-plugin-ns-spoiler (installed, enabled)
	* nodebb-plugin-oauth-server (installed, disabled)
	* nodebb-plugin-poll2 (installed, enabled)
	* nodebb-plugin-recent-cards (installed, enabled)
	* nodebb-plugin-save-plugins (not installed, enabled)
	* nodebb-plugin-share-post-icons (installed, enabled)
	* nodebb-plugin-shoutbox-neho (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-plugin-sso-facebook (installed, enabled)
	* nodebb-plugin-sso-google (installed, enabled)
	* nodebb-plugin-sso-twitter (installed, enabled)
	* nodebb-plugin-tenor-gif (installed, enabled)
	* nodebb-plugin-tws (installed, enabled)
	* nodebb-plugin-user-invitations (installed, enabled)
	* nodebb-plugin-write-api (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)
	* nodebb-widget-rotating-topic (installed, enabled)

![image](https://user-images.githubusercontent.com/25720059/100323356-6d24a100-2fe7-11eb-9b12-88a163b10bd5.png)

**Comment by oplik0** [comment]
This issue was already fixed: #8595 
It doesn't actually happen periodically, but when a group is renamed.

The fix is already implemented in all 1.15 versions

**Comment by julianlam** [comment]
👍
