### ISSUE TITLE
Delete Account Content and forked topic

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#8955]
Cloudron Demo
NobeBB v1.15.2, MongoDB 4.0.19

admin and demo users
change owner of the opening post (from admin to demo)
go to demo user profile
use Delete Account Content

1 )
For the first time it deleted topic as it should but redirected from profile (demo user) to the purged topic (no longer exist so it shows error).

2 )
For the second time topic is not purged and not even deleted.
Why? Not deleted topic is a fork from parent topic. I guess DB store it as something different.

Expected:
1 ) No need to redirect from demo user profile to purged content.
2 ) Please check why forked topic is unable to delete and purge using Delete Account Content tool.

**Comment by julianlam** [comment]
> 2 )
>For the second time topic is not purged and not even deleted.
>Why? Not deleted topic is a fork from parent topic. I guess DB store it as something different.

If a topic ownership is changed to `demo`, and is then forked by admin, the new topic is owned by admin, not demo. It will not be deleted, so this is intentional. Perhaps I am misunderstanding?

**Comment by nhlpl** [comment]
1 ) It works just like 'Back' button in the web browser. Going NodeBB Home (start page) might be a better idea.
2 ) Tested it again. Forked topics are not deleted.

Topic1 created by newly created User5
Reply1 in Topic1 by User5
Admin user uses Topic Tools > Fork Topic
Category shows Topic1 and forked Topic2 (content taken from Reply1)
Admin user visits User5 profile and decides to clear all content added by User5 (topics and posts)
Topic1 and Topic2 are still here after deleting all User5 content by admin user
Topic1 and Topic2 are owned by User5 and can be displayed after page refresh

**Comment by julianlam** [comment]
When forked, the earliest post in the forked posts becomes the topic owner. If the topic owner is `demo`, the topic is purged as intended.
