### ISSUE TITLE
More flexible rules for category Mods

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#8957]
NobeBB v1.15.2, MongoDB 4.0.19

Start here:
NodeBB Admin > Manage > Admins & Mods

Add non-admin and non-mod user as Mod for just one category.
Leave user admin and now use only a newly created category Mod (newly created user).
Create 3rd user after admin and category mod.
Add some topics and posts using 3rd user who is not admin or mod.

Issue:
You can move posts between categories but you can't move topic.

Expected:
Mod for a Category is not an average Joe and we can allow moving not just posts but also topics. Even when we're talking about a Mod for just one category and not a Global Mod or Admin users.

**Comment by julianlam** [comment]
What is the issue here, that user 2 (the mod) is not able to move topics between categories?

I believe a mod can only move topics if they also moderate the other category

**Comment by nhlpl** [comment]
To be clear here.
Created a mod for Category called 1.
Mod for Cat1 can use all topic tools inside Cat1.
Mod for Cat1 can move posts from Cat1 to Cat2 or Cat3.
Mod for Cat1 is unable to do the same with topics. **Moving topic from Cat1 to Cat2 or Cat3 is not possible**.
