### ISSUE TITLE
Impossible to export users list with a lot of user registered

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#8969]
Hello everyone,

If i try to export che list of my users in the ACP after few minutes recive an error because the list is too long (we have about 100.000 users).

could be also usefully to export a partial list made by filter or selection.

How can i fix the export problem?

**Comment by barisusakli** [comment]
Are you using `Download CSV` from the manage users page?

**Comment by andreadragotta** [comment]
Yes
