### ISSUE TITLE
Post Queue editing before approval

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#8984]
NobeBB v1.15.3, MongoDB 4.0.19, nodejs v10.19.0
fresh install, limited cloud resources

/admin/settings/post
Enable Post Queue
Add new post to the queue (normal user)

Go to Home > Post Queue (admin user)
Content can be edited by clicking on submitted text
Category and Title are only links

What is expected?
NodeBB says _You can click on individual content to edit before posting_ and editing should be possible not just for Content but also for Category and Title.

**Comment by barisusakli** [comment]
Maybe something like this is better.

![image](https://user-images.githubusercontent.com/2583394/100484818-e1d10b80-30cb-11eb-80f1-6569d7524526.png)

The post queue shows new topics and replies. Only the category and title of new topics are editable.
