### ISSUE TITLE
Ability to use widgets on core pages

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#8989]
- **NodeBB version:** v1.15.3

Sometimes I want to personalize core pages, like users or tags with adding the widgets
Like  I want to add the most popular  tags just on tag pages, but this page is not available in the widgets .
 We can add widget on globals or category and topics .
But I think it's  useful if we have the option for core pages

**Comment by oplik0** [comment]
Neither tags nor users page is defined in core. All of these templates are left to themes now, so I believe you can just add widget ares there.
To do this you will need to add widget areas to these templates and make NodeBB aware of them using `filter:widgets.getAreas` hook.
If you are basing your theme on Persona, the function that adds areas to this hook is [`library.defineWidgetAres`](https://github.com/NodeBB/nodebb-theme-persona/blob/master/library.js#L28).
The templates are [`templates/users.tpl`](https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/users.tpl) and [`templates/tags.tpl`](https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/tags.tpl).

The same method applies for almost all pages except for admin routes (templates for which are actually in core and not the theme)

**Comment by barisusakli** [comment]
Persona already had header widgets defined for users and tags in the tpl file so I added them to define widgets hook.

For other pages @oplik0 already explained how it is done. See [here](https://github.com/NodeBB/nodebb-theme-persona/commit/ad5c1e640ed31cb82d6be9a0b37309c4f18183fc) for code sample

![image](https://user-images.githubusercontent.com/2583394/100565536-ddeee600-3291-11eb-9cc3-77743aeca684.png)

**Comment by roghaye-m** [comment]
@barisusakli  hi can you add the login page into this lists?

> Persona already had header widgets defined for users and tags in the tpl file so I added them to define widgets hook.
> 

> ![image](https://user-images.githubusercontent.com/2583394/100565536-ddeee600-3291-11eb-9cc3-77743aeca684.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/dbc87c8a8e90b9cb231bc7f86aaa50cc0011d9ea
