### ISSUE TITLE
IP Blacklist works for all users including admin

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#8993]
NobeBB v1.15.3, MongoDB 4.0.19, nodejs v10.19.0
fresh install, limited cloud resources

admin user profile > IP Blacklist > add your own IP
Check how it works for normal users and admin

Issue:
Admin user is unable to log-in using blacklisted IP.

What is expected?
Admin user whitelisted.

**Comment by julianlam** [comment]
No need to complicate the IP blacklist functionality... I feel it is the admin's responsibility to not shoot themselves in the foot

**Comment by julianlam** [comment]
If we allowed this, then the blacklist functionality would become opaque, with rules that seem to apply to some users, and not others. This would be especially complicated if we updated the logic to include all privileged users (administrators, global moderators, category moderators)
