### ISSUE TITLE
Ability to change route for /admin

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#8996]
NobeBB v1.15.3, MongoDB 4.0.19, nodejs v10.19.0
fresh install, limited cloud resources

Use admin user
/admin/settings/navigation
Select last icon > /admin
Change route from /admin to /admincp and save changes

Issue:
/admin path not changed and admincp in the same place.

What is expected?
Ability to hide admincp by changing default route.

**Comment by oplik0** [comment]
`/admin/settings/navigation` is not changing anything about routes and it's not supposed to. It's made for modifying the navbar, so all it does and is supposed to do is change where the button will point to.

Default routes are not configurable and I believe somewhere here on on the community forums it was stated that there are no plans to change that (thought that was with a question about translating routes I believe).

Hiding admin control panel in the way you suggest is kinda useless. To get to it, users need to have appropriate privileges, so unless an attacker stole an admin account they can't do it anyway. To actually get security through obscurity you would need to also remove this shortcut from the navbar and remove any other mentions of admin route in any metadata (for example `robots.txt`, which will allow google to possibly index that route though), change some things in themes to not have any links to admin panel and make sure there are no notifications that would redirect you to the admin panel.

And additionally of course not mention the route in any private chat, admin only category or anywhere where the attacker could find it when they gained access to admin account :)
Kinda a lot of work just to get a bit of security through obscurity that will only help if someone got administrator privileges anyway and could be randomly defeated by Google indexing... Or just found via some route scanner if you used some other common word for it.

**Comment by nhlpl** [comment]
Text field can be disabled to not confuse users after fresh install.

**Comment by oplik0** [comment]
You mean removing the option to change the url a navbar icon points to?

I think you're thinking about this whole settings section wrong - it's just for manually modifying what links are in the navbar (and who can see them). The url there is just that - and url that this specific link will point to.

You can remove the admin shortcut from there if you want, or show it to everyone (by default only administrators will see it). You can make it point to another site completely.

I don't really see a reason to make special exceptions to customizability of these links.
