### ISSUE TITLE
Limiting sessions to 1

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9007]
NobeBB v1.15.3, MongoDB 4.0.19, nodejs v10.19.0
fresh install, limited cloud resources

Use admin user
/admin/settings/cookies
Settings > Max active sessions per user > 1 (limit to only one session)

Issues:
1 ) NodeBB limits sessions to 2 instead of 1 (based on saved settings).
2 ) Normal and private window/tab are 2 different sessions recognized as only 1 session.
3 ) 3rd session revokes one of the older sessions and forces to re-login.

What is expected?
1 ) User logged-in only in one internet browser.
2 ) Two different sessions to revoke for the same user (logged-in for two times).
3 ) Intuitive and guessable for computer geeks but less friendly for the rest of the world.

**Comment by barisusakli** [comment]
related https://github.com/NodeBB/NodeBB/issues/8730
