### ISSUE TITLE
Missing lang string for no-users-browsing

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9009]
Admin Dashboard
![langnobrow](https://user-images.githubusercontent.com/11160550/100650318-09caa400-3344-11eb-83ae-3cfbffaa859f.jpg)

**Comment by psychobunny** [comment]
![no-users-browsing](https://user-images.githubusercontent.com/654670/100651593-acb6fa00-3313-11eb-9ba4-ebd2069215b9.png)
hmm seems alright to me, also first thought was to add it here and it already exists for some time: https://github.com/NodeBB/NodeBB/blame/9004319e0d7b9b103cb520e9f9cebf6f71930b75/public/language/en-GB/admin/dashboard.json#L78

**Comment by psychobunny** [comment]
Nevermind. it looks like the popup is not translated as per your screenshot. fixing :)

**Comment by nhlpl** [comment]
And it is used below circle and I'm talking about what happens when you check what is under red colour.
