### ISSUE TITLE
Use Outgoing Links Warning Page for links added by plugins

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9012]
NobeBB v1.15.3, MongoDB 4.0.19, nodejs v10.19.0
fresh install, limited cloud resources

/admin/settings/general > Use Outgoing Links Warning Page (enabled)

New topic or reply to open Composer
Click '?' to get help (near Compose and Show preview phrases)
`/outgoing?url=http%3A%2F%2Fcommonmark.org%2Fhelp%2F`

Issue:
Double click needed to go to external website.

What is expected:
A part of NodeBB core links to not be treated as external just like 'Powered by NodeBB | Contributors'. Even if added by a plugin.

**Comment by barisusakli** [comment]
If you don't want the outgoing links warning for certain domains add it to the ACP.
![image](https://user-images.githubusercontent.com/2583394/100760999-62d81d80-33c0-11eb-9791-7b94be3d4957.png)
