### ISSUE TITLE
Category does not exist when nested under section

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9013]
NobeBB v1.15.3, MongoDB 4.0.19, nodejs v10.19.0
fresh install, limited cloud resources

Create section and move categories to the lower levels (see attached screenshot)
New topic and try to post it
![sectioncat](https://user-images.githubusercontent.com/11160550/100710624-4633e980-33b0-11eb-817b-415a6971407e.png)

Issue:
`ERROR Category does not exist`

What is expected:
Nested categories under section to work normally.

**Comment by barisusakli** [comment]
I couldn't reproduce with these steps

1. create new forum
2. create a new category called "section"
3. edit "section" category and make it a section
4. move the default categories under the section category 
![image](https://user-images.githubusercontent.com/2583394/100758797-e93f3000-33bd-11eb-9e82-e8b9fd6ac717.png)
5. Create a new non admin user
6. Try posting in all the categories.
![image](https://user-images.githubusercontent.com/2583394/100758886-0411a480-33be-11eb-8c43-28662f348f6a.png)


I was able to post in all the categories. Please let us know if there are different reproduction steps.

**Comment by nhlpl** [comment]
Tested it again and see nothing wrong.

Closing.
