### ISSUE TITLE
Delete Account Content didn't work 

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#9014]
- **NodeBB version:** v1.15.3
- 

- **Database type:** mongo, redis, 
- **Database version:** MongoDB Version 4.2.3
Redis Version 5.0.7

- **Exact steps to cause this issue:**

	1. First I went to an user profile 
	2. Then, I clicked on user more info bottom,
then i clicked on delete account content

- **What you expected:**

I expected all user posts to be deleted
- **What happened instead:**

But only the following message was added to the user profile, below the best posts made from someone
![image](https://user-images.githubusercontent.com/37838903/100717433-45f71680-33cf-11eb-9234-a4929f9ab53e.png)

And the posts still existed and were not deleted
As you can see in the picture, the post counter has not changed either
![image](https://user-images.githubusercontent.com/37838903/100717086-d97c1780-33ce-11eb-94e0-b8bb13f49f51.png)

I also tried the "Delete Account and Content" but it did not work
Neither the posts were deleted nor the user was banned

None of the following options  didn't work
![image](https://user-images.githubusercontent.com/37838903/100717929-f82ede00-33cf-11eb-9171-74a92fbbbb23.png)

**Comment by nhlpl** [comment]
Reported it here but have no idea how to reproduce it.
https://github.com/NodeBB/NodeBB/issues/8955

**Comment by julianlam** [comment]
The functionality was tested as recently as one week ago. What do you see in the client-side inspector tools' console?

**Comment by nhlpl** [comment]
![workerjs](https://user-images.githubusercontent.com/11160550/100762305-1b6b8480-33f4-11eb-9a5e-6ee656415699.png)

**Comment by nhlpl** [comment]
![alrdel](https://user-images.githubusercontent.com/11160550/100770736-e5330280-33fd-11eb-92dd-c8a2964ddb39.png)

**Comment by julianlam** [comment]
That's been fixed in latest master.
