### ISSUE TITLE
Missing lang string for reset-colors

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9016]
NobeBB v1.15.3, MongoDB 4.0.19, nodejs v10.19.0
fresh install, limited cloud resources

Backported enhancement needs new translation file with reset-colors included.
![rescol](https://user-images.githubusercontent.com/11160550/100731457-b0a65300-33cb-11eb-82b3-182dc8b2640c.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/d3c04afb98611e152cafbd4cb804e3a689f86cc3
