### ISSUE TITLE
Ensure that when thumbs have been uploaded, that they are discarded if composer is discarded

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#9042]

**Comment by barisusakli** [comment]
Where are the thumbs stored? What if user closes browser tab are they deleted?

**Comment by julianlam** [comment]
Thumbs are saved on server disk. If a composer window is closed, the draft is still valid and will be opened again when user loads the draft, so no special handling is required there.

**Comment by julianlam** [comment]
Occasionally there may be cases where an upload is orphaned. In which case maybe a cleanup script is required.
