### ISSUE TITLE
find replacement for david-dm

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#9043]
since it's down most of the time need a replacement

**Comment by julianlam** [comment]
Do we need it? Renovate should handle most cases of outdated deps...

**Comment by barisusakli** [comment]
Seems to be working better lately, renovate doesn't show a list of deps that are outdated afaik it just opens PR and some can't be merged like bs4 + and couple others. https://david-dm.org/nodebb/nodebb?path=install
