### ISSUE TITLE
Lavender theme stylesheet.css not loaded

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9044]
NodeBB 1.15.4, MongoDB 4.4.2, NodeJS 11.15.0, CentOS 7.9.2009
fresh install, default plugins, default themes

/admin/appearance/themes
Lavender > Select theme
Rebuild & Restart

Browser console returns an error and theme is broken:
_(index):1 Refused to apply style from 'http://server_ip/assets/stylesheet.css?v=balsejpjtis' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled._

All other default themes work fine.
`

**Comment by nhlpl** [comment]
Same thing happens on NodeBB 1.15.5, MongoDB 4.2.11, NodeJS 10.21.0, CentOS 8.2.2004.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-lavender/commit/252c87dc5ebf1adf153affb110a96f814678bb55
