### ISSUE TITLE
I wanna a API to get uploaded files reference

### ISSUE THREAD

**Issue by nidbCN** [NodeBB/NodeBB#9045]
I want to make a program to delete the no-used uploaded files.But I can't find which post referenced the file in API Get uploaded files.I want API return me which post used it so I can know which file shoule I delete.
Thanks you!

**Comment by julianlam** [comment]
Are you planning to use the /api/v3/files API?

**Comment by nidbCN** [comment]
> Are you planning to use the /api/v3/files API?

I am try to get file info from /api/admin/manage/uploads

**Comment by julianlam** [comment]
@nidbCN When you make the call to `/api/admin/manage/uploads`, the return contains a `inPids` array that lists the posts that contain a link to that file. When there are no items in that array, it is considered an orphaned post.

Here is a sample excerpt:

```
{
    "currentFolder": "/files",
    "showPids": true,
    "files": [
        {
            "name": "1590024306504-screenshot-from-2020-05-20-13-02-40.png",
            "path": "/files/1590024306504-screenshot-from-2020-05-20-13-02-40.png",
            "url": "/assets/uploads/files/1590024306504-screenshot-from-2020-05-20-13-02-40.png",
            "fileCount": 0,
            "size": 298047,
            "sizeHumanReadable": "291.1KiB",
            "isDirectory": false,
            "isFile": true,
            "mtime": 1590024306498.5977,
            "inPids": [
                20
            ]
        },
        {
            "name": "1590067459181-screenshot-from-2020-05-20-13-02-40.png",
            "path": "/files/1590067459181-screenshot-from-2020-05-20-13-02-40.png",
            "url": "/assets/uploads/files/1590067459181-screenshot-from-2020-05-20-13-02-40.png",
            "fileCount": 0,
            "size": 298047,
            "sizeHumanReadable": "291.1KiB",
            "isDirectory": false,
            "isFile": true,
            "mtime": 1590067459181.4236,
            "inPids": [
                21
            ]
        },
```

**Comment by nidbCN** [comment]
I can't find "inPids" array anywhere,and I guess it is because the API return:
```json
  "currentFolder": "/files",
  "showPids": false,
  "files": [
    {
```
but I don't konw how to set "showPids" to true

**Comment by nidbCN** [comment]
I have find the problem:
When I use `/api/admin/manage/uploads?dir=/files` it would be shown
but when I use `https://bbs.ai-lab.ltd/api/admin/manage/uploads?dir=/files/` it cannot be shown
But there are the same path,is it a bug?

**Comment by julianlam** [comment]
Thanks for investigating! I've committed a fix :smile:
