### ISSUE TITLE
Missing lang string logged-out-due-to-inactivity

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9046]
NodeBB 1.15.5, MongoDB 4.2.11, NodeJS 10.21.0, CentOS 8.2.2004

Log-in to /admin and leave opened window for a long time:
![dueto](https://user-images.githubusercontent.com/11160550/101173891-734bfa80-3643-11eb-8e85-cc0580f52078.png)

**Comment by julianlam** [comment]
Is this on local?

Your backend server died, so the translations could not be retrieve. This isn't a bug.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/790f4e45214312f6a5af878d094c8e395fe20e9f
