### ISSUE TITLE
Mark unread button redirection

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#9051]
NodeBB version before 1.15.x when click this button, stay me in the thread. Now in 1.15.4 when click, redirect me to unread topics. I think this is no the normal behaviour.

![image](https://user-images.githubusercontent.com/2943127/101192597-0f710400-363a-11eb-8a92-901fb72ea949.png)

**Comment by pitaj** [comment]
The behavior makes sense to me. Mirrors how other platforms work.

**Comment by NormandoHall** [comment]
So, this is behaviour change, because previous 1.14.x versions stays me in the thread.
