### ISSUE TITLE
Category 0 group shows in Rewards

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9064]
NodeBB 1.15.5, MongoDB 4.4.2, NodeJS 15.3.0, nginx 1.19.5, CentOS 7.9.2009
fresh install, default plugins, default themes

Content of /admin/extend/rewards
![rewards0](https://user-images.githubusercontent.com/11160550/101259423-ff841d80-3728-11eb-9a98-706ae588cbf3.png)

Issue:
Outdated reward system shows Category 0.

What is expected:
Category 0 removed and alphabetical order.

Related: https://github.com/NodeBB/NodeBB/issues/4634

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-rewards-essentials/commit/f11dc194e252f307a3be316ade64c0d66b05ef20
