### ISSUE TITLE
composer zen mode broken

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#9067]
![image](https://user-images.githubusercontent.com/2583394/101270876-80eca780-374b-11eb-8bae-f06717d6edba.png)

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/101654378-757cd300-3a0e-11eb-8858-5648ccf6685a.png)

Seems to work for me on local and community

**Comment by barisusakli** [comment]
Try editing https://community.nodebb.org/topic/180/who-is-using-nodebb first post here and going zen mode always broken for me

**Comment by julianlam** [comment]
One bug I will report is that the composer is not full-width in zen mode
