### ISSUE TITLE
SMTP / Registering / Login issues while board is closed.

### ISSUE THREAD

**Issue by Andrew-devweb** [NodeBB/NodeBB#9069]
- **NodeBB version:** 1.15.5
- **NodeBB git hash:** c4e3d84b3843dafb24380bf92b610daf52e15db3
- **NodeJS version:** v.14.15.1

- **Installed NodeBB Plugins:** Not many and I don't think they're related to the issue.

- **Database type:** mongo

I had opened a support thread on the forum regarding an issue I had with SMTP on my server. Turns out, it's not exactly related to SMTP, but to the maitenance mode on the forum.
Let me explain.
I re-installed my board yesterday, and set up an external SMTP service to deliver my email. I let a couple of users register, and here's a screenshot of the email I would get.

![image](https://user-images.githubusercontent.com/74706350/101287526-04ac9f80-37f1-11eb-9bb0-467d0fc6228d.png)
Here, everything works as it should. The email arrives in the inbox folder, the link is clickable, the image is displayed, the /login part of the forum works just fine.

After that, since the board is not yet ready to be launched, I closed the board and worked on it for a while.
Today, I come back and realize some things are not working like yesterday.
The link to log in is not "https://forum.website.com/login" but it's "https://forum.website.com/login?local=1"
![abc](https://user-images.githubusercontent.com/74706350/101287654-d54a6280-37f1-11eb-88ce-ff05c5c03904.PNG)

The emails are not being sent anymore. They only are delivered to gmail and in the spam folder.
The link is not clickable, the image is not displayed, and there's no way to register at all.

The issue would be fine if by disabling the board, it would get simply fixed. The issue is that it persists even after the board is re-opened. It basically stays in a "local" kind of enviroment all the time, and cannot go back to normal.

That's not the end of it though.
The few users who do manage to register with some workarounds, will always receive "Invalid credentials" when they try to login through "https://forum.website.com/login?local=1", as if their account didn't register properly. And since the emails are not being sent to anyone except for gmail (and in the spam folder) they can't change their password. Their account is registered, but the passwords are not saved properly in the database or something like that.
I have to manually change it and send it to them, so then they can log and edit it.

**Comment by barisusakli** [comment]
What are your registration settings?

![image](https://user-images.githubusercontent.com/2583394/101287879-fd6d9d80-37c0-11eb-978c-dc05e8a52a4b.png)

Is everyone registering through invites or does regular registration allowed? Do passwords work when registering via /register?

**Comment by Andrew-devweb** [comment]
Thank you for the quick reply.
Right now, the bug occured with registration and approval both set to normal.
The issue with passwords not being properly saved were with registration type set to invite only, and registration approval set to admin approval.

A few seconds ago, I re-opened my board, restarted nodebb, cleared cache from the ACP and then the emails were being sent normally again. The /login url on the header still isn't working, and I have to manually add ?local=1 to the URL. 

I haven't re-disabled the board to see if the bug triggers again though.

**Comment by pitaj** [comment]
What happens when you click on login? Do registered users have the login privilege?

**Comment by Andrew-devweb** [comment]
When I click on the login, nothing happens because the header link url is "https://forum.website.com/login" but the login page is "https://forum.website.com/login?local=1".
The users are given a group that has login privilege, but the problem happens to me as well, and my account is administrator (the default one) so it should bypass all permissions.

**Comment by pitaj** [comment]
The normal login page will ONLY show up if registered-users has it.

**Comment by barisusakli** [comment]
@pitaj yeah maybe we should add `verified-users` and `unverified-users` to that list 🤔 those groups didn't exist back then.

**Comment by barisusakli** [comment]
I mean if `registered-users` or `verified-users` or `unverified-users` has login privilege then login input should show up?

**Comment by pitaj** [comment]
Or guests, for that matter. Regardless, we should note this caveat on the privileges page.

**Comment by barisusakli** [comment]
>The issue with passwords not being properly saved were with registration type set to invite only, and registration approval set to admin approval.

This should have been fixed 9 days ago https://github.com/NodeBB/NodeBB/commit/dadb2527dae113a023af2517947f94d80ceb1fa6.

Can you check if you have this fix?

**Comment by pitaj** [comment]
@barisusakli I think having showing the login page bound to this privilege is kinda weird in the first place. We can keep the privilege for denying local login for certain users, but I think bringing back the explicit toggle would be best.

**Comment by barisusakli** [comment]
I think the idea is to not show a useless login form if you are doing sso only logins but its not checking if there are any sso logins available right now. That should be fixed as well.

**Comment by barisusakli** [comment]
@Andrew-devweb when you say open/close the board please provide the steps you are doing as well. Is it just putting it in maintenance mode or are you changing privileges in the ACP as well?

**Comment by Andrew-devweb** [comment]
I didn't set any permissions for registered-users nor verified-users nor unverified-users. 
That's because I had no way to close to board to staff only (some of them shouldn't be administrator), and wanted to avoid external users seeing the board at all when i disabled maintenance mode (sadly, maintenance mode only allows administrators to log in). 
Right now, the only permissions I have are these 
![immagine_2020-12-06_210724](https://user-images.githubusercontent.com/74706350/101291166-084b2100-3807-11eb-990f-061c0018c832.png)

When I close the board, I only go to /admin/settings/advanced and change it from there.
From what I understood, the log-in issue is only due to the permissions not being set properly, but the SMTP problems still occurs when I close the board.

**Comment by Andrew-devweb** [comment]
I was able to reproduce the email bug once again.
Set the permissions like I did above for registered-users, verified-users, and unverified-users (and Global Moderators too).
Create a group like "Supporter" with the permissions above.
Registration type normal, Registration approval set to normal.
Confirm emails on.
Close the board from /admin/settings/advanced.
From /admin/manage/users, invite someone through email with "Supporter" permission given.

Email doesn't deliver, or in the best case delivered into spam folder.

**Comment by pitaj** [comment]
You probably shouldn't invite anyone while in maintenance mode. It's not meant for how you're trying to use it.

I'm not sure why it would affect email though, that's kinda weird. Can you place this log code:
```
console.log('transport: ', Emailer.fallbackTransport, 'data: ', data, 'config: ', meta.config);
```

On this line: 
https://github.com/NodeBB/NodeBB/blob/a535350f2db476a9b09b6175d0aab6e24b6924ec/src/emailer.js#L324

**Comment by Andrew-devweb** [comment]
Forgive me for not replying anymore to the issue, you can close it if you want to.
I put the code you gave me in emailer.js, but the email seems to be working fine now even with maintenance mode being set. Weird, but I'm glad I could fix it.
Thank you both for assisting me.
