### ISSUE TITLE
favicon cannot be set anymore

### ISSUE THREAD

**Issue by michael-brade** [NodeBB/NodeBB#9073]
- **NodeBB version:** 1.15.5
- **NodeBB git hash:** 07f8ab4e7
- **NodeJS version:** v12.18.4

- **Installed NodeBB Plugins:** 
Active plugins:
        * nodebb-plugin-calendar (installed, enabled)
        * nodebb-plugin-category-sections (installed, disabled)
        * nodebb-plugin-chats-global (installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-composer-quill (installed, disabled)
        * nodebb-plugin-custom-homepage (installed, enabled)
        * nodebb-plugin-custom-pages (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, disabled)
        * nodebb-plugin-emoji-extended (installed, enabled)
        * nodebb-plugin-emoji-one (installed, enabled)
        * nodebb-plugin-katex (installed, disabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-newsletter (installed, disabled)
        * nodebb-plugin-question-and-answer (installed, disabled)
        * nodebb-plugin-reactions (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, disabled)
        * nodebb-plugin-spam-be-gone (installed, disabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-material (installed, disabled)
        * nodebb-theme-oxide (installed, enabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo
- **Database version:** v3.2.11

- **Exact steps to cause this issue:**
I updated nodebb from v1.14.x to v1.15.x (git branch) and now my custom favicon is not displayed anymore. I re-uploaded it in `/admin/settings/general` again, where it is listed as `/assets/uploads/system/favicon.ico?v=1513543465418` but I still get the standard nodebb favicon. The page source says:
```
<link rel="icon" type="image/x-icon" href="/favicon.ico?v=njktk15lkec" />
```
which is obviously the wrong link.

I entered the url of the favicon manually and that works. So it exists and is available, but the generated forum html is wrong.

**Comment by chocolate012** [comment]
Saw this same issue on several forums.

**Comment by barisusakli** [comment]
From what I can see the favicon uses the cache buster that is generated during the build process which doesn't change when you upload a new icon.

@michael-brade can you try this.

1. upload new favicon
2. stop nodebb
3 run ./nodebb build
4. start nodebb
5. check if the new favicon is returned at the /favicon.ico route

**Comment by michael-brade** [comment]
@barisusakli Yeah, I saw that, too, but I had no luck with a rebuild :-/

**Comment by michael-brade** [comment]
Update: I'm now using NodeBB 1.16.2 and @barisusakli's method worked!
