### ISSUE TITLE
uploading SVG images breaks the SVG and converts it into png

### ISSUE THREAD

**Issue by michael-brade** [NodeBB/NodeBB#9074]
- **NodeBB version:** 1.15.5
- **NodeBB git hash:** 07f8ab4e7
- **NodeJS version:** v12.18.4

- **Installed NodeBB Plugins:** 
Active plugins:
        * nodebb-plugin-calendar (installed, enabled)
        * nodebb-plugin-category-sections (installed, disabled)
        * nodebb-plugin-chats-global (installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-composer-quill (installed, disabled)
        * nodebb-plugin-custom-homepage (installed, enabled)
        * nodebb-plugin-custom-pages (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, disabled)
        * nodebb-plugin-emoji-extended (installed, enabled)
        * nodebb-plugin-emoji-one (installed, enabled)
        * nodebb-plugin-katex (installed, disabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-newsletter (installed, disabled)
        * nodebb-plugin-question-and-answer (installed, disabled)
        * nodebb-plugin-reactions (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, disabled)
        * nodebb-plugin-spam-be-gone (installed, disabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-material (installed, disabled)
        * nodebb-theme-oxide (installed, enabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo
- **Database version:** v3.2.11

- **Exact steps to cause this issue:**
  - create a new post using Markdown editor
  - click upload file button
  - select an SVG

- **What you expected:**
I want the plain SVG to be uploaded, without it being changed.

- **What happened instead:**
Instead, the SVG got converted to a PNG. And if I now click on the link to the PNG, the transferred mime type is xml+svg, but the actual content is png binary. So the browser cannot display it. I searched the net and my plugins but I have no idea where and why the SVG gets converted. If I upload an HTML file, no problem.

**Comment by pitaj** [comment]
FYI the custom homepage plugin has been deprecated in favor of custom-pages instead. Also, you shouldn't be running emoji-extended anymore, its behavior is covered by the normal emoji plugin.

**Comment by michael-brade** [comment]
thank you :grinning: will fix it!
