### ISSUE TITLE
api.users.updateSettings breaks saved properties

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#9081]
need to load raw values from db before merging and saving

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/ec03af7a38cad60260bf182810f2dd4ae472fe66

?

**Comment by barisusakli** [comment]
Need defaults for new users

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/1f32d38778420aba8beeca991be3a81640cb21e1
