### ISSUE TITLE
Deleting Account and Content failed after update to v1.15.5

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#9085]
- **NodeBB version:** v1.15.5
- **NodeBB git hash:** 2b586764e2f3e8869d15b1df523e92a093f99ced
- **NodeJS version:** v12.20.0

- **Installed NodeBB Plugins:** 

	* nodebb-plugin-category-notifications (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-email-blacklist (installed, enabled)
	* nodebb-plugin-embed (installed, enabled)
	* nodebb-plugin-emoji-android (installed, disabled)
	* nodebb-plugin-gdpr (installed, enabled)
	* nodebb-plugin-google-analytics (installed, enabled)
	* nodebb-plugin-gravatar (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-recent-cards (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-rewards-essentials (installed, disabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongodb + redis
- **Database version:** mongodb 4.2.11 / Redis server v=5.0.3

- **Exact steps to cause this issue:**
1. Selected spammer
2. Chose delete account and content from their user page
- **What you expected:**
user to be removed
- **What happened instead:**
Remained on page. User and content remains

According to firebug

XHRDELETE https://retropie.org.uk/forum/api/v3/users/35978
response: {"status":{"code":"forbidden","message":"[[error:no-privileges]]"},"response":{}}

(I am the admin / first user of the forum)

**Comment by joolswills** [comment]
I updated from v1.15.0 (with a few patches from previous fixes to bugs I reported).

Our forum runs from a subfolder. Just noting as this has been an issue before but may be unrelated to this.

config
```
{
    "url": "https://retropie.org.uk/forum",
    "bind_address": "127.0.0.1",
    "secret": "5016b05c-030a-4a96-b7fb-67c9ca6a9854",
    "database": "mongo",
    "port": [4567, 4568, 4569],
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": removed
        "database": removed
        "password": "removed
    },
    "redis": {
        "host":"127.0.0.1",
        "port":"6379",
        "database": 0
    }
}
no```

**Comment by joolswills** [comment]
nginx config (sanitised slightly for security)

```
upstream io_nodes {
  ip_hash;

  server 127.0.0.1:4567;
  server 127.0.0.1:4568;
  server 127.0.0.1:4569;
  server 127.0.0.1:4570;
}

server {
  listen 443 default_server ssl http2;
  listen [::]:443 default_server ssl http2;
  server_name retropie.org.uk;
  access_log [removed];
  error_log [removed] error;

  root [removed];
  index index.html index.php;

  ssl_certificate [removed];
  ssl_certificate_key [removed];

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Host $http_host;
  proxy_set_header X-NginX-Proxy true;

  proxy_buffers 4 256k;
  proxy_buffer_size 128k;
  proxy_busy_buffers_size 256k;
  proxy_read_timeout 180s;
  proxy_send_timeout 180s;

  proxy_redirect off;

  # Socket.IO Support
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  location ~ ^/forum/assets/(.*) {  
    root [removed]/nodebb;
    try_files /build/public/$1 /public/$1 @nodebb;
  }

  location /forum/plugins {
    alias [removed]/nodebb/build/public/plugins;
    try_files $uri @nodebb;
  }

  location /forum {
    proxy_pass http://io_nodes;
  }

  location @nodebb {
    proxy_pass http://io_nodes;
  }
}
```

**Comment by joolswills** [comment]
When I was posting the config earlier I accidently sent a config with  "secret" in it. I wiped it and removed the github history, but it will have been emailed to people. Do I need to change this now - is this used for password encryption or cookies or ?

**Comment by julianlam** [comment]
It is just used for cookies, you should be able to change it with minimal consequences (though everybody will have to log in again)

**Comment by barisusakli** [comment]
@joolswills is `allow account deletion` turned off in your ACP? This seems like a regression from the write api merge. https://github.com/NodeBB/NodeBB/blob/master/src/api/users.js#L253

**Comment by joolswills** [comment]
Own account deletion is switched off for users. Is there another setting for admins to disable user deletion completely that may have been reset ? (I've not changed any setting since updating).

**Comment by barisusakli** [comment]
No there is only one setting. Looks like it is bugged though and preventing admins from deleting normal users when it is turned off.
