### ISSUE TITLE
I hope to turn tags into topic keywords so that the topics can be better discovered by crawlers

### ISSUE THREAD

**Issue by cgh1999520** [NodeBB/NodeBB#9088]
I hope to turn tags into topic keywords so that the topics can be better discovered by crawlers

**Comment by cgh1999520** [comment]
If this request is unreasonable, please let me know, thank you. I will find other suitable methods

**Comment by psychobunny** [comment]
Could you give us an example of what you mean?

**Comment by cgh1999520** [comment]
[image: C7C73B8B-DC08-461f-AA81-B85B52CD408F.png][image:
DD9C0B6B-46D5-4315-B1B8-4D760B4ACFCB.png]
------------------------------------
I hope the language of my website will not affect your understanding. The
example of the picture is the tag I added, hoping to synchronize with the
meta tag keywords. In this way, the search engine can know what the
keywords of my topic are. In order to better recommend my website and theme

Andrew Rodrigues <notifications@github.com> 于2020年12月9日周三 下午6:37写道：

**Comment by psychobunny** [comment]
Hey @cgh1999520 your images don't load for me

**Comment by cgh1999520** [comment]
https://drive.google.com/drive/folders/1LMrSRH9e2QDdglsJy0JLYBM56k8fm9on?usp=sharing

Sorry, I can only share it with you through Google Drive
