### ISSUE TITLE
SocketIO...... error  when got changes from master

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#9093]
- **NodeBB version:** version:  1.15.5
  **Node version**: v12.14.1
  **git hash**: 91899329fc6da96419c513b106358b02df64e996

- **Database type:** mongo, redis,
- **Database version:** mongo 4.2.3, redis 5.0.7
<!`postgres --version` -->
- **Exact steps to cause this issue:**

	1. I got the latest changes from master
	2. Then, when I clicked on any  topic

- **What you expected:**

- **What happened instead:**

I expected the topic  to load as before

But we have some error  When we enter a topic or refresh it 
This error: 
![20201209_232938](https://user-images.githubusercontent.com/37838903/101681152-fa033c00-3a76-11eb-9b39-6a997debccc8.jpg)

**Comment by roghaye-m** [comment]
also the notifications changes same and randomly for all of users !!!


![image](https://user-images.githubusercontent.com/37838903/101683026-a34b3180-3a79-11eb-8477-c0da1a5395aa.png)

After a few minutes, the notification counter changes

![image](https://user-images.githubusercontent.com/37838903/101683238-f0c79e80-3a79-11eb-9c0f-81e51a820e81.png)


As you can see, I have a few unread notifications, but the counter suddenly resets to zero and then changes again.
![e2](https://user-images.githubusercontent.com/37838903/101683055-ad6d3000-3a79-11eb-839b-16b93854351d.PNG)



A strange thing is that these things happen with the same numbers for all users


What could be the reason?

**Comment by barisusakli** [comment]
Are you using this plugin https://github.com/barisusakli/nodebb-plugin-browsing-users?

If so update it to 1.1.1.

Not sure about the notifications can you share your forum url or the type of notifications?

**Comment by roghaye-m** [comment]
> Are you using this plugin https://github.com/barisusakli/nodebb-plugin-browsing-users?
> 
> If so update it to 1.1.1.
> 
> Not sure about the notifications can you share your forum url or the type of notifications?


I updated to this version, but after that we have many warning 
this warning:
Looks like your connection to NodeBB was lost, please wait while we try to reconnect.

about notification it just was for counter, however  when i updated this plugin (browsing-users) it solved 
I do not know if it was related to this issue or not



I had to deactivate this plugin(browsing-users)

**Comment by barisusakli** [comment]
Could be related to the socket.io 3 changes please see this post https://community.nodebb.org/post/80571, 

If you are still having issues open post a topic at https://community.nodebb.org/category/16/technical-support with information about your setup and config.json
