### ISSUE TITLE
missing configuration editor for nodebb-plugin-email-blacklist

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#9098]
I'm missing the nodebb-plugin-email-blacklist configuration editor since nodebb 1.15.x 

The plugin was installed a long time ago and is listed in the plugin list as installed  
nodebb-plugin-email-blacklist
nodebb email blacklist
Installiert 1.1.0 | Neueste 1.1.0

where is the configuration editor gone?

**Comment by julianlam** [comment]
Please file the bug in the appropriate plugin repository's issue tracker, thank you!

Also, you'll want to include details about what you see... is there a button in the ACP, what happens when you click it, etc.
