### ISSUE TITLE
administrator can not remove user

### ISSUE THREAD

**Issue by malaohu** [NodeBB/NodeBB#9101]
NodeBB version: v1.15.5
NodeBB git hash:a815cfdfed27e46c3d1557961a3ff914c9766c20
NodeJS version:v10.16.3

administrator account login control panel, but unable to remove user

show this :  don't have permission

![image](https://user-images.githubusercontent.com/5143704/101969655-8de42c00-3c60-11eb-88a3-3a1da803b284.png)

![image](https://user-images.githubusercontent.com/5143704/101969649-83299700-3c60-11eb-8626-40fb88d88760.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/9085
