### ISSUE TITLE
Unable to limit post category shown on group page

### ISSUE THREAD

**Issue by thewilloftheshadow** [NodeBB/NodeBB#9114]
- **NodeBB version:** 1.15.5
- **NodeBB git hash:** bd5c4a5cffb4d5afc3d02f831ec53ca32bf35c33
- **NodeJS version:** v12.20.0

- **Installed NodeBB Plugins:** 
Active plugins:
        * nodebb-plugin-beep (installed, enabled)
        * nodebb-plugin-browsing-users (installed, enabled)
        * nodebb-plugin-btn-spoilers (installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-custom-homepage (installed, enabled)
        * nodebb-plugin-custom-pages (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-desktop-notifications (installed, enabled)
        * nodebb-plugin-emailer-sendgrid (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-gravatar (installed, enabled)
        * nodebb-plugin-iframely (installed, enabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-poll (installed, enabled)
        * nodebb-plugin-registration-notification (installed, enabled)
        * nodebb-plugin-spam-be-gone (installed, enabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, enabled)
        * nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo
- **Database version:** 4.2.11 (Mongo Atlas)

- **Exact steps to cause this issue:**
1. Open the page for a group
2. Under group administration, limit the posts for the group page to one category (also happens with multiple selections)
3. Save changes
- **What you expected:**
Group updates to only that category's posts are shown
- **What happened instead:**
Received Error: `values.memberPostCids.filter is not a function`, and the setting does not save

**Comment by barisusakli** [comment]
@thewilloftheshadow thanks for reporting, you should be able to save in the ACP since that page seems to work. Fix will be in 1.16.0

**Comment by thewilloftheshadow** [comment]
@barisusakli After changing the setting in the ACP, it saves properly and shows up as saved in the Group Administration section on the group page, but the filter doesn't actually take effect, and it still shows posts from anywhere on the forum

**Comment by barisusakli** [comment]
I think that's how it works right now, when new posts are made by members of the group only the posts in those selected categories will show up and the old ones will just disappear.
