### ISSUE TITLE
Redirection issue. Login page

### ISSUE THREAD

**Issue by fais3000** [NodeBB/NodeBB#9118]
**Background**
We are using google adsense via Nodebb widgets. i.e topic.tpl loads the adsense JS file and then shows an ad on topic page. There is a category which is only visible to users who have joined a certain group. We don't show ads in this category.

**Problem**
Google started giving us warnings that we are serving ads where there is no content. The url it points out is the login page. 
Even though this widget code doesn't execute on login page, neither the login page has adsense code added. 

<img width="773" alt="2020-12-17_12-48-42" src="https://user-images.githubusercontent.com/25720059/102458657-63caa980-4066-11eb-9816-0c6db312abe2.png">

"Valuable Inventory: No Content violation happens when you’re trying to display advertisements on a page with no relevant data. These are common when trying to display ads on a login or registration page."

Happens on nodebb 1.14.3 with mongodb.
Ajax disabled through 
```    
$(document.body).off('click', 'a');
```

**Comment by pitaj** [comment]
Disabling ajaxified links is not the correct way to implement this. Even if it was, that code is not a good or comprehensive way of doing so.

How you looked at nodebb-plugin-adsense? I think it would be simpler to modify that for your needs.

**Comment by fais3000** [comment]
@pitaj I'll look into the plugin to see if it works for our use case.

What is the proper way to disable loading templates via ajax?

**Comment by julianlam** [comment]
It is not recommended to disable ajaxification at all, that's @pitaj's point. 🙂

**Comment by julianlam** [comment]
@fais3000 If you're certain that the login page doesn't execute any adsense code, then it may be a false positive by Google. You may want to reach out to them if possible to see why their automated systems seem to think `/login` is showing an ad.
