### ISSUE TITLE
Shorthand data routes should not need pid/tid/cid in route

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#9123]
```
router.get('/:type/pid/:id', middleware.authenticateOrGuest, controllers.api.getObject);
router.get('/:type/tid/:id', middleware.authenticateOrGuest, controllers.api.getObject);
router.get('/:type/cid/:id', middleware.authenticateOrGuest, controllers.api.getObject);
```

Can be reduced to a single `.get('/:type/:id')`, the string in the middle is superfluous. Right now you can call https://community.nodebb.org/api/category/tid/1 to get category 1 info, even though `tid` is specified.

**Comment by pitaj** [comment]
This doesn't need to be a breaking change, right? Is it not possible to add a new route and keep the existing ones?

**Comment by julianlam** [comment]
Yes, you're right 👍

**Comment by barisusakli** [comment]
`/post/:id` route already exists and redirects user to `/topic/:id/:slug/indexofpost`

**Comment by julianlam** [comment]
Hm, may be a good candidate for migration to v3 then

**Comment by julianlam** [comment]
@barisusakli can you remind me again what this route is used for?

**Comment by barisusakli** [comment]
`/post/:id`? or `router.get('/:type/pid/:id'` ?

**Comment by julianlam** [comment]
The latter, `/:type/pid/:id` and the variants. I can migrate them to write API, but I'd like to update the callers if possible.

**Comment by barisusakli** [comment]
I think they were added for 3rd party plugins don't think core code is calling them.
