### ISSUE TITLE
service-worker.js not respecting forum path

### ISSUE THREAD

**Issue by fgallese** [NodeBB/NodeBB#9127]
Hello.

I see that [here](https://github.com/NodeBB/NodeBB/issues/8126)  a call to register the service worker was added.

The issue I see, is that it seems that it is not respecting the forum installation path.

Our forum is installed under `https://our-domain.tld/forum` but the browser tries to find the js under `https://our-domain.tld/service-worker.js`.

I guess you forgot to add `config.relative_path` to the call of this js file ?

I temporally *fixed* this by using a rule in our proxy (traefik), but it seems to me that this should be handled by nodebb.

In any case, thank you in advance for looking into this.

Edit: [this](https://github.com/NodeBB/NodeBB/commit/aa268d5eeb040ad5477dc78bf7775792ad105cd0) is the commit I meant to link.

**Comment by joolswills** [comment]
I noticed this also, and see it's fixed but with the fix, on an nginx install it means it's handled via a node process as it's via forumfolder/service-worker.js

Is this something that needs to be processed dynamically? Shouldn't it be included via path/assets which then can be mapped to be delivered directly?

Maybe my nginx config is out of date but it was based on documentation from not too long ago afair.

Or has the layout changed since I set this up?

My config is here:
https://github.com/NodeBB/NodeBB/issues/9085#issuecomment-740384607

**Comment by joolswills** [comment]
Checking the code the assets path is still used for other JavaScripts  so I suspect this may need to be changed also?

**Comment by joolswills** [comment]
I made the following change to my set up. Seems to work

```diff
diff --git a/public/src/app.js b/public/src/app.js
index 5e87d5508..ee1178e1b 100644
--- a/public/src/app.js
+++ b/public/src/app.js
@@ -786,7 +786,7 @@ app.cacheBuster = null;
 
 	function registerServiceWorker() {
 		if ('serviceWorker' in navigator) {
-			navigator.serviceWorker.register(config.relative_path + '/service-worker.js')
+			navigator.serviceWorker.register(config.relative_path + '/assets/src/service-worker.js')
 				.then(function () {
 					console.info('ServiceWorker registration succeeded.');
 				}).catch(function (err) {
```

**Comment by joolswills** [comment]
To note profile pics on forum topics also lack assets/ in the path which means they also can't be served directly. Sorry for adding all this here. I will do a ticket if needed later but on my phone with SSH terminal to my server so it's tricky to provide all the info right now.

**Comment by joolswills** [comment]
Patch for user profiles. Uploaded images also seem to lack assets looking at my wevserver logs. 

I will do an issue with all this later as needed but it's all a quick fix for you I'm sure. Also my changes may not be right.

```diff
diff --git a/src/user/data.js b/src/user/data.js
index 1fd101a8a..16418fd20 100644
--- a/src/user/data.js
+++ b/src/user/data.js
@@ -186,10 +186,10 @@ module.exports = function (User) {
 			}
 
 			if (user.picture && user.picture === user.uploadedpicture) {
-				user.uploadedpicture = user.picture.startsWith('http') ? user.picture : relative_path + user.picture;
+				user.uploadedpicture = user.picture.startsWith('http') ? user.picture : relative_path + '/assets' + user.picture;
 				user.picture = user.uploadedpicture;
 			} else if (user.uploadedpicture) {
-				user.uploadedpicture = user.uploadedpicture.startsWith('http') ? user.uploadedpicture : relative_path + user.uploadedpicture;
+				user.uploadedpicture = user.uploadedpicture.startsWith('http') ? user.uploadedpicture : relative_path + '/assets' + user.uploadedpicture;
 			}
 			if (meta.config.defaultAvatar && !user.picture) {
 				user.picture = User.getDefaultAvatar();
```

**Comment by oplik0** [comment]
I think this should be reopened as this basically broke the service worker by changing its scope from the forum to just `/assets/src/` paths (so for `https://our-domain.tld/` it can only access routes starting with `https://our-domain.tld/assets/src/`).

This issue actually needs 2 changes:
1. the service worker response has to contains a `Service-Worker-Allowed` header with the value being the forum URL.
2. the registration function has to be changed to include scope override
```js
navigator.serviceWorker.register(config.relative_path + '/assets/src/service-worker.js', { scope: config.relative_path })
```

Without the first change, the browser won't let service worker even ask for access to the forum url scope (by default the scope is constrained to stuff equal or below the service worker url), and without the second change the service worker won't actually have access to that scope, making it essentially useless.

**Comment by pitaj** [comment]
Not fixed?

**Comment by barisusakli** [comment]
Yeah seems still broken on https://community.nodebb.org with latest changes

**Comment by barisusakli** [comment]
Moved the service worker back relative_path/service-worker.js
