### ISSUE TITLE
uploads are not working anymore

### ISSUE THREAD

**Issue by michael-brade** [NodeBB/NodeBB#9134]
- **NodeBB version:** 1.16.0
- **NodeBB git hash:** 1bece2b79
- **NodeJS version:** v14.15.1
- **Installed NodeBB Plugins:** 
Active plugins:
        * nodebb-plugin-calendar (installed, enabled)
        * nodebb-plugin-category-sections (installed, disabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-composer-quill (installed, disabled)
        * nodebb-plugin-custom-pages (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, enabled)
        * nodebb-plugin-emoji-extended (**not installed**, enabled)
        * nodebb-plugin-emoji-one (installed, enabled)
        * nodebb-plugin-katex (installed, disabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-newsletter (installed, disabled)
        * nodebb-plugin-question-and-answer (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, disabled)
        * nodebb-plugin-spam-be-gone (installed, disabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-material (installed, disabled)
        * nodebb-theme-oxide (installed, enabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)
- **Database type:** mongo
- **Database version:** v3.2.11

- **Exact steps to cause this issue:**
  - reply to a post
  - click upload file or upload image
- **What you expected:**
  I would expect the file to upload normally.

- **What happened instead:**
I get an error:
```
error: /api/post/upload
Error: [[error:invalid-files]]
```
Happens in Firefox and Chrome (Vivaldi).

So I added:
```
diff --git a/src/middleware/index.js b/src/middleware/index.js
index 5e7e93e73..7cb9b69a8 100644
--- a/src/middleware/index.js
+++ b/src/middleware/index.js
@@ -102,6 +102,7 @@ middleware.pluginHooks = helpers.try(async function pluginHooks(req, res, next)
 });
 
 middleware.validateFiles = function validateFiles(req, res, next) {
+       console.error("files", req.files)
        if (!Array.isArray(req.files.files) || !req.files.files.length) {
                return next(new Error(['[[error:invalid-files]]']));
        }
```
which outputs
```
nodebb[15181]: files {}
```
Looking into the Developer Tools in Vivaldi/Chrome I find the request:
```
POST /api/post/upload HTTP/1.1
Connection: keep-alive
Content-Length: 245582
Pragma: no-cache
Cache-Control: no-cache
Accept: */*
DNT: 1
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryY2XNG9WKUPIlIalA
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```
And under Form Data I find:
```
------WebKitFormBoundaryY2XNG9WKUPIlIalA
Content-Disposition: form-data; name="files[]"; filename="test.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryY2XNG9WKUPIlIalA
Content-Disposition: form-data; name="cid"

20
------WebKitFormBoundaryY2XNG9WKUPIlIalA--
```
Now, I'm no expert on uploads, but it seems to me that the request is already missing the data?! But with Firefox I get the same result. It used to work, but I don't know when it stopped. I removed the deprecated plugins after I reported the SVG upload problem and then I didn't try uploads again. Now I updated to NodeBB v1.16.0 to test the SVG fix but I can't upload any files at all anymore.

**Comment by julianlam** [comment]
Were you always on Node 14? We've had issues with it and file uploads in the past although I believe they were resolved.

Any chance you can try with Node 12?

**Comment by michael-brade** [comment]
Oh! Very true, I wasn't!

Yes, it works with Node v12.20.0 :-)

**Comment by barisusakli** [comment]
This might be related https://community.nodebb.org/post/80180.

Make sure these dependencies are at the correct versions.

`-- connect-multiparty@2.2.0
  `-- multiparty@4.2.2

**Comment by michael-brade** [comment]
Yes, true as well! multiparty is still at 4.2.1. How can we make sure this doesn't happen? I did `./nodebb upgrade` and I checked `npm outdated`. Delete `node_modules` and `npm i` again?

**Comment by barisusakli** [comment]
Yeah I am not sure why npm is not installing the correct dependency during ./nodebb upgrade. Safest bet is deleting node_modules and running npm i again.

**Comment by michael-brade** [comment]
Yeah.... anyway, I can confirm it is all working now. No bug left regarding uploads, so I'll close this :)
Thank you!
