### ISSUE TITLE
Socket.io upgrade causes large increase in connections and server load

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#9135]
- **NodeBB version:** v1.16.0
- **NodeBB git hash:** 1bece2b79ee4a5ed377127167c07c777f6f02ab9
- **NodeJS version:** v12.20.0

- **Installed NodeBB Plugins:** 
	* nodebb-plugin-category-notifications (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-email-blacklist (installed, enabled)
	* nodebb-plugin-embed (installed, enabled)
	* nodebb-plugin-emoji (installed, disabled)
	* nodebb-plugin-emoji-android (installed, disabled)
	* nodebb-plugin-gdpr (installed, enabled)
	* nodebb-plugin-github-embed (installed, enabled)
	* nodebb-plugin-google-analytics (installed, enabled)
	* nodebb-plugin-gravatar (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-recent-cards (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-rewards-essentials (installed, disabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongodb + redis
- **Database version:** mongodb v4.2.11 / Redis server v=5.0.3
- **Nginx version** nginx/1.18.0

- **Exact steps to cause this issue:**
Upgraded from v1.15.5 to v1.16.x - forum runs as before
- **What happened instead:**
Forum is working but server load is higher and incoming connections through firewall has increased significantly

--

I initially thought my timing was unlucky and the server was experiencing an attack. However after reverting the SocketIO related code, which I thought was the most likely culprit, the forum is running back as it was again. 

I reverted 13d5a1440b813013ba48644c9f280bf13a9c41bf, 62463430a9b08954c3791fdf7479c8b5ddb2ab6f, and 1c45fa1ba52ee237ade60d8d020c39fd77a944ab

![fw_conntrack-pinpoint=1608317439,1608525663](https://user-images.githubusercontent.com/5365574/102724159-7f9fab00-4305-11eb-8b0d-c2b7cbc8d597.png)

You can see on this chart when I updated, and at the end, where I have reverted the commmits above.

here's my nodebb and nginx config

```
{
    "url": "https://retropie.org.uk/forum",
    "bind_address": "127.0.0.1",
    "secret": removed
    "database": "mongo",
    "port": [4567, 4568, 4569, 4570],
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": removed
        "database": removed
        "password": removed
    },
    "redis": {
        "host":"127.0.0.1",
        "port":"6379",
        "database": 0
    }
}
```

```
upstream io_nodes {
  ip_hash;

  server 127.0.0.1:4567;
  server 127.0.0.1:4568;
  server 127.0.0.1:4569;
  server 127.0.0.1:4570;
}

server {
  listen 443 default_server ssl http2;
  listen [::]:443 default_server ssl http2;
  server_name retropie.org.uk;
  access_log [removed];
  error_log [removed] error;

  root [removed];
  index index.html index.php;

  ssl_certificate [removed];
  ssl_certificate_key [removed];

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Host $http_host;
  proxy_set_header X-NginX-Proxy true;

  proxy_buffers 4 256k;
  proxy_buffer_size 128k;
  proxy_busy_buffers_size 256k;
  proxy_read_timeout 180s;
  proxy_send_timeout 180s;

  proxy_redirect off;

  # Socket.IO Support
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  location ~ ^/forum/assets/(.*) {  
    root [removed]/nodebb;
    try_files /build/public/$1 /public/$1 @nodebb;
  }

  location /forum/plugins {
    alias [removed]/nodebb/build/public/plugins;
    try_files $uri @nodebb;
  }

  location /forum {
    proxy_pass http://io_nodes;
  }

  location @nodebb {
    proxy_pass http://io_nodes;
  }
}
```

**Comment by joolswills** [comment]
![fw_conntrack-pinpoint=1608330545,1608522353](https://user-images.githubusercontent.com/5365574/102725227-2dfb1e80-430d-11eb-9ac6-496b75486f4c.png)

Updated graph now some more time has passed, which shows more clearly it's ok after the reverts.

**Comment by barisusakli** [comment]
Seems like it went from 8k to 32k, does changing the port number affect the number? If you run on 3 ports do you go from 8k to 24k?

**Comment by barisusakli** [comment]
Two more things to test, please test them separately to see if they make any difference.

https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/index.js#L44

Change this line to be: 
`transports: ['websocket'],`

See if you are still getting 4x the connections.

If that doesn't make any difference comment out this line
https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/index.js#L33

And check if there is any difference.

If nothing changes might have to report it upstream on the socket.io repo.

**Comment by joolswills** [comment]
Thanks. Currently testing using 3 ports on vanilla v1.16.0. I'll let that graph for a bit, then try the other changes

**Comment by joolswills** [comment]
![fw_conntrack-pinpoint=1608476352,1608513747](https://user-images.githubusercontent.com/5365574/102727935-ce0e7300-4320-11eb-89eb-9dc00e85fe51.png)

Changing to 3 ports made no difference (23:30 in chart)

Doing the `transports: ['websocket'],` cut it down significantly - but still more than before (00:00  in chart)

**Comment by joolswills** [comment]
I'll still test commenting out https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/index.js#L33 - although that may not be useful to you now.

**Comment by joolswills** [comment]
Commenting out https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/index.js#L33 didn't seem to make a difference.

**Comment by barisusakli** [comment]
So seems like upgrading to 3.x seems to cause a lot more polling and connections 🤔

**Comment by joolswills** [comment]
![nginx_request-pinpoint=1608409866,1608517866](https://user-images.githubusercontent.com/5365574/102733345-f43e0e00-4334-11eb-95c1-f870e222ce79.png)

Adding for info - Probably should have used this graph initially, as it's a better demonstration of the increase in web connections than the firewall one. The increase looks even more significant here.

**Comment by barisusakli** [comment]
Did you check the nginx access log are they mostly socket.io polling requests?

**Comment by joolswills** [comment]
Yes - Most of the lines are 

```
/forum/socket.io/?EIO=3&transport=polling&t=XXXXXXX
```

**Comment by joolswills** [comment]
I can provide you a portion of logfile privately if you need.

**Comment by barisusakli** [comment]
Unfortunately not much we can do on our end, need to report this upstream to socket.io and ask if anything changed from 2.x to 3.x that would cause this.

**Comment by joolswills** [comment]
Thanks. Just to confirm are you saying you will report it upstream or are you saying I should ?

**Comment by barisusakli** [comment]
I would appreciate if you can post here https://github.com/socketio/socket.io/issues and link back to this issue.

**Comment by joolswills** [comment]
Wouldn't it make more sense for someone from nodebb to do that - I have no knowledge of developing with socket.io and will not be able to provide useful answers to any questions regarding the code ?

**Comment by joolswills** [comment]
I'll do it - but I have a feeling they will want more information than I can provide.

**Comment by barisusakli** [comment]
The information you provided in this issue should be enough. If they have specific questions I will try to answer. We aren't really doing anything custom with socket.io it's the same connection code client side for 2.x and 3.x.

**Comment by joolswills** [comment]
https://github.com/socketio/socket.io/issues/3730

**Comment by joolswills** [comment]
Sorry if this is not relevent - but I was reading https://socket.io/docs/v3/migrating-from-2-x-to-3-0/

and it says

>As detailed above, this release contains several non backward compatible changes, and as such a v2 client will not be able to connect to a v3 server (and vice versa).

>In order to upgrade a live production environment, you will need to have both a group of v2 servers and v3 servers in parallel, and route the traffic based on either:
> the EIO query parameter (EIO=3 for Socket.IO v2, EIO=4 for Socket.IO v3)

in the Nginx Log the the urls contain EIO=3 rather than 4 ?

**Comment by barisusakli** [comment]
When I access your forum I get EIO=4, maybe these polling requests are from users who haven't cleared their cache and still using the old socket.io client side library?

**Comment by joolswills** [comment]
This is a problem then as it looks like they might be the cause - constantly trying over and over again causing the increased connections. Is there no way you can force this in the code

I just

```
wc -l access.log 

1258132 access.log

grep -r "EIO=3" access.log | wc -l
1132959

grep -r "EIO=4" access.log | wc -l
10510
```

**Comment by barisusakli** [comment]
How are you serving `nodebb.min.js`? the socket.io library is bundled with nodebb.min.js and rebuilding & restarging nodebb updates the cacheBuster so technically users should get the new client side library. Is there any other caching going on?

**Comment by joolswills** [comment]
No other caching. Just the nginx config above. But if browsers have cached the old library - and for example it's not loaded with some querystring to force a new version, an old one may be used.

**Comment by barisusakli** [comment]
Yeah whenever you rebuild and restart nodebb the the cache-buster in the url should change.

![image](https://user-images.githubusercontent.com/2583394/102800242-9a176a00-4381-11eb-980b-547c657adefd.png)

**Comment by joolswills** [comment]
If that javascript loads others, is that enough to stop them being cached also ?

**Comment by barisusakli** [comment]
The socket.io library is embedded in the nodebb.min.js file https://github.com/NodeBB/NodeBB/blob/master/src/meta/js.js#L24

So it should load the new code when cache buster changes.

**Comment by barisusakli** [comment]
Maybe you have users with open tabs that never reload the page 😆 

How long did you run the 1.16.0 code before reverting? I suggest running it for a few days and see if the connections go back to the previous levels.

**Comment by joolswills** [comment]
I ran it for over 24 hours - I will leave it running for longer. We probably do have users with lots of open tabs - It's a busy forum also.

**Comment by joolswills** [comment]
I can probably force something in nginx for EIO=3 querystrings - ignoring them in nginx or something.

**Comment by joolswills** [comment]
I am returning a 403 now and not logging it for urls with EIO=3 (to avoid the 11GB of logs we had for the 24 hours before). Perhaps this should have been handled by nodebb though or something changed with how often the polling is done ? As it was a significant strain on my server and other busy sites may have similar issues.

**Comment by joolswills** [comment]
Or something to stop polling after a certain amount of time ? (wouldn't help old clients, but something like this changes again)

**Comment by barisusakli** [comment]
Yeah I think this code is the cause https://github.com/NodeBB/NodeBB/blob/master/public/src/sockets.js#L47-L50

Essentially socket.io tries to reconnect X times every Y milliseconds and when it fails reconnecting our code restarts the process after waiting Y * 10 milliseconds, so essentially it never gives up trying. Maybe that code needs to be modified.

**Comment by barisusakli** [comment]
You can increase reconnectionDelay in the ACP to a bigger value to reduce the load, but obviously this won't help with users who haven't refreshed their tabs.

**Comment by joolswills** [comment]
Checking the ACP - So the max reconnection attempts isn't used ? Or it's not used in this particular case ?

**Comment by barisusakli** [comment]
Max reconnection attempt is used for example if it is set to 5 it will try to reconnect 5 times with an interval of reconnection delay.

After it fails for 5 times it will start over after waiting (reconnection delay * 10) milliseconds.

**Comment by barisusakli** [comment]
@joolswills any updates?

**Comment by joolswills** [comment]
Can be closed now thanks. Traffic is fine now nginx is dumping the old polling attempts. I will probably remove that config in some weeks when users have closed their browsers :-)

**Comment by julianlam** [comment]
@joolswills sorry to ask for more, but can you share an nginx config snippet where you block requests with `?EIO-2`? :smile: just if others are interested in doing that as well.

**Comment by joolswills** [comment]
Sure thing - I added 

```
    if ($query_string ~ EIO=3) {
      access_log off;
      return 403;
    }
```

to the /forum location - eg:

```
upstream io_nodes {
  ip_hash;

  server 127.0.0.1:4567;
  server 127.0.0.1:4568;
  server 127.0.0.1:4569;
  server 127.0.0.1:4570;
}

server {
  listen 443 default_server ssl http2;
  listen [::]:443 default_server ssl http2;
  server_name retropie.org.uk;
  access_log [removed];
  error_log [removed] error;

  root [removed];
  index index.html index.php;

  ssl_certificate [removed];
  ssl_certificate_key [removed];

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Host $http_host;
  proxy_set_header X-NginX-Proxy true;

  proxy_buffers 4 256k;
  proxy_buffer_size 128k;
  proxy_busy_buffers_size 256k;
  proxy_read_timeout 180s;
  proxy_send_timeout 180s;

  proxy_redirect off;

  # Socket.IO Support
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  location ~ ^/forum/assets/(.*) {  
    root [removed]/nodebb;
    try_files /build/public/$1 /public/$1 @nodebb;
  }

  location /forum/plugins {
    alias [removed]/nodebb/build/public/plugins;
    try_files $uri @nodebb;
  }

  location /forum {
    if ($query_string ~ EIO=3) {
      access_log off;
      return 403;
    }
    proxy_pass http://io_nodes;
  }

  location @nodebb {
    proxy_pass http://io_nodes;
  }
}
```

**Comment by julianlam** [comment]
@joolswills Thanks!

My brain instantly went "ifisevil" the moment I saw it, but since you are ending with `return` it looks to be safe :smile:

**Comment by joolswills** [comment]
Yeah - I think an `if` is the only way - it's not preferable, but it seems to work and even though can affect performance, it's still better than passing to node :-)

**Comment by joolswills** [comment]
Disabling logging was important - I was getting 12gb a day of webserver logs from the old clients.
