### ISSUE TITLE
Profile pic topic thumbs don't use /assets path

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#9138]
**NodeBB version:** v1.16.0
- **NodeBB git hash:** 1bece2b79ee4a5ed377127167c07c777f6f02ab9
- **NodeJS version:** v12.20.0

- **Installed NodeBB Plugins:** 
	* nodebb-plugin-category-notifications (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-email-blacklist (installed, enabled)
	* nodebb-plugin-embed (installed, enabled)
	* nodebb-plugin-emoji (installed, disabled)
	* nodebb-plugin-emoji-android (installed, disabled)
	* nodebb-plugin-gdpr (installed, enabled)
	* nodebb-plugin-github-embed (installed, enabled)
	* nodebb-plugin-google-analytics (installed, enabled)
	* nodebb-plugin-gravatar (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-recent-cards (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-rewards-essentials (installed, disabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongodb + redis
- **Database version:** mongodb v4.2.11 / Redis server v=5.0.3
- **Nginx version** nginx/1.14.2

I noticed user uploaded profile pics used for topic thumbs (defaulting to profile pics) are not using /assets/ in the path. Not sure if this also affects uploaded thumbnails for topics. Would be useful to use /assets in the path so we can serve these directly from nginx etc as nodebb does with other images/scripts etc.

**Comment by julianlam** [comment]
Hey @joolswills I'm a little confused by what you're reporting. I don't understand exactly what you meant with "user uploaded profile pics used for topic thumbs", since profile pictures cannot be used as topic thumbnails...

Unless there's some use case I totally didn't realize :thinking: ?

**Comment by joolswills** [comment]
I saw that profile pics/avatars on topic lists in categproes didn't seem to be using assets path but I just checked and it looked ok - perhaps it was a specific case, but I'm not sure. I'll close this - if I spot something I'll provide more details information with screenshot.

**Comment by julianlam** [comment]
Okay, no problem! Better to be safe than sorry later on :smile:

**Comment by joolswills** [comment]
I just saw an example on unread posts (https://retropie.org.uk/forum/unread)

![Screenshot_2020-12-23_15-03-50](https://user-images.githubusercontent.com/5365574/103010386-2cf60700-4530-11eb-8423-ae3ea8a6f502.png)

**Comment by joolswills** [comment]
Some seem to contain '/assets' in the path, while others don't

![Screenshot_2020-12-23_15-08-05](https://user-images.githubusercontent.com/5365574/103010734-adb50300-4530-11eb-8dd1-c886668fb2d0.png)

this one for example is ok. There looked to me more when I looked the other day, so perhaps it's related to when the topic was created

**Comment by pitaj** [comment]
It's probably related to when the user changed their profile picture last. You can add another role in your nginx config to cover `/uploads` as well.

**Comment by julianlam** [comment]
Checking...

@joolswills Just FYI, you can remove the HTML from your TOS: 
![image](https://user-images.githubusercontent.com/923011/103225026-fd137e80-48f6-11eb-8bcd-f8df7329756c.png) It looks like the link is converted automatically.

**Comment by julianlam** [comment]
Yes, I believe @pitaj is right, it is just not showing the assets URL because the user likely uploaded their photo before we changed the URL to use the assets path. It is likely OK to leave it as is.

**Comment by joolswills** [comment]
The assets path is included in the database? I would have thought that would be appended later. But no worries - I'll hack it in nginx.

**Comment by joolswills** [comment]
> Checking...
> 
> @joolswills Just FYI, you can remove the HTML from your TOS:
> ![image](https://user-images.githubusercontent.com/923011/103225026-fd137e80-48f6-11eb-8bcd-f8df7329756c.png) It looks like the link is converted automatically.

Thanks. Will do.

**Comment by julianlam** [comment]
> The assets path is included in the database? I would have thought that would be appended in the code 

Yes, so there may be an opportunity for refactoring here :smile:
