### ISSUE TITLE
Posts cannot be discarded on mobile devices

### ISSUE THREAD

**Issue by klauso** [NodeBB/NodeBB#9141]
- **NodeBB version:** 1.16.0
- **NodeBB git hash:** unknown (installed via Cloudron)
- **NodeJS version:** 12.13

- **Installed NodeBB Plugins:** 

        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-embed (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, disabled)
        * nodebb-plugin-emoji-apple (installed, enabled)
        * nodebb-plugin-extended-markdown (installed, enabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-ns-spoiler (installed, enabled)
        * nodebb-plugin-soundpack-default (installed, disabled)
        * nodebb-plugin-spam-be-gone (installed, disabled)
        * nodebb-plugin-twitter-klaus (installed, enabled)
        * nodebb-rewards-essentials (installed, disabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, enabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo
- **Database version:** (installed via Cloudron)
- **Exact steps to cause this issue:**

	1. Open forum on a mobile device (Android, iOS)
	2. Click on "New Topic"
	3. Enter a title and some text
	4. Click on the "X" in the upper left corner. All that happens is that the X is greyed out.
	5. Interestingly, the "Are you sure you wish to discard..." dialog shows up when the "-" is pressed and the post is discarded after confirmation.

This is a new problem that must have been introduced in one of the latest updates.

- **What you expected:**
I expected the "Are you sure..." dialog to show up when pressing "X".
- **What happened instead:**
The X button is greyed out.

**Comment by barisusakli** [comment]
z-index issues, discard confirm modal is behind the mobile composer
