### ISSUE TITLE
MongoDB design

### ISSUE THREAD

**Issue by shayanYousefi** [NodeBB/NodeBB#9146]
Hi. I have been reading the source code to know how NodeBB uses MongoDB and what collections and documents does it have. Insofar as I've learned, the database is at first designed with Redis and the constraints it had in mind. Therefore, even in MongoDB it has only one collection instead of several, and for querying, it uses sorted sets. In addition, to increase the performance, it uses an index on the fields __key_ and _value_ for regular and sorted set documents.
Now my question is, performance wise, since it does not follow best practices, is it not that much of an improvement to change the design, for example to use several collections instead of one and use different indexes for querying instead of adding several sorted set documents or is there another reason it stayed like this?

**Comment by barisusakli** [comment]
This is a tracker for issues with the software itself. For similar discussions about this use the community forum, related topic https://community.nodebb.org/topic/3613/mongodb-single-collection
