### ISSUE TITLE
BUG with chat edit and delete for admin 

### ISSUE THREAD

**Issue by mysterydata** [NodeBB/NodeBB#9149]
I've this option enabled "Disable chat message editing/deletion"

at below i see the message "Administrators and global moderators are exempt from this restriction"

but i as an admin of the forum can't edit and delete the messages from the chat
https://imgur.com/a/PlLDlK5

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/02998669c31e14e22c1d53dc32f848a304beeb37

Mm, broken for 4 years :expressionless:
