### ISSUE TITLE
Got this message in Console

### ISSUE THREAD

**Issue by mysterydata** [NodeBB/NodeBB#9153]
I'm using latest master and getting this warning in console : 

`Missing translation "error:socket-reconnect-failed" for language "en-US"`

can you provide some info ? It seems bug for me.

https://imgur.com/a/6UKZTdP

**Comment by julianlam** [comment]
Likely fixed by @nodebb-misty in 1002c14aa27d0966efb4edfe6720ee3ba383e62b
