### ISSUE TITLE
User Registration ist broken - utils.slugify is not a function

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#9154]
New User Registration ist broken.
Latest Version: 1002c14aa
Error: utils.slugify is not a function
High priority!

**Comment by julianlam** [comment]
@awunnenb If this is truly high priority for you, **you should not be using latest `master` in production**.

Please provide a stack trace if you can, and it will help us narrow down where the error is coming from. User registration is working fine on my end, so I am not seeing what you are seeing.

**Comment by awunnenb** [comment]
how can i got back to stable version now?

**Comment by julianlam** [comment]
There were no upgrade scripts since 1.16.0, so you should be able to `git reset --hard v1.16.0`, then delete `node_modules/` and all lockfiles, re-install dependencies, and run `./nodebb build`.

**Back up your database first.**

**Comment by barisusakli** [comment]
Post your active plugins and the stack trace from console.

**Comment by awunnenb** [comment]
"nodebb-plugin-beep": "^0.4.3",
    "nodebb-plugin-composer-default": "6.5.5",
    "nodebb-plugin-dbsearch": "4.1.2",
    "nodebb-plugin-emoji": "^3.3.0",
    "nodebb-plugin-emoji-android": "2.0.0",
    "nodebb-plugin-emoji-extended": "^1.1.1",
    "nodebb-plugin-emoji-one": "^2.0.0",
    "nodebb-plugin-extended-markdown": "^1.5.0",
    "nodebb-plugin-iframely": "^0.7.14",
    "nodebb-plugin-markdown": "8.12.4",
    "nodebb-plugin-mentions": "2.13.6",
    "nodebb-plugin-poll": "^1.1.2",
    "nodebb-plugin-registration-notification": "^1.2.4",
    "nodebb-plugin-soundpack-default": "1.0.0",
    "nodebb-plugin-spam-be-gone": "0.7.7",
    "nodebb-plugin-write-api": "^5.8.5",
    "nodebb-plugin-youtube-embed": "^0.6.9",
    "eslint-plugin-import": "2.22.1",

**Comment by awunnenb** [comment]
2020-12-29T15:09:21.017Z [60001/1977] - info: Initializing NodeBB v1.16.0 https://xyz
2020-12-29T15:09:22.460Z [60001/1977] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-emailer-ssl-smtp`. Skipping.
2020-12-29T15:09:22.460Z [60001/1977] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-custom-pages`. Skipping.
2020-12-29T15:09:22.745Z [60001/1977] - info: [socket.io] Restricting access to origin: https://hsv-fans.hamburg:* https://www.hsv-fans.hamburg:*
2020-12-29T15:09:22.808Z [60001/1977] - warn:    [plugins/nodebb-theme-persona] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2020-12-29T15:09:22.903Z [60001/1977] - warn:    [plugins/nodebb-plugin-spam-be-gone] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2020-12-29T15:09:23.145Z [60001/1977] - warn: [plugins/nodebb-plugin-write-api] Hook "filter:router.page" is deprecated, please use "response:router.page" instead.
2020-12-29T15:09:23.228Z [60001/1977] - info: [plugins/spam-be-gone] Settings loaded
2020-12-29T15:09:25.787Z [60001/1977] - info: [api] Adding 0 route(s) to `api/v3/plugins`
2020-12-29T15:09:25.797Z [60001/1977] - info: Routes added
2020-12-29T15:09:25.800Z [60001/1977] - info: NodeBB Ready
2020-12-29T15:09:25.801Z [60001/1977] - info: Enabling 'trust proxy'
2020-12-29T15:09:25.803Z [60001/1977] - info: NodeBB is now listening on: 0.0.0.0:60001

**Comment by awunnenb** [comment]
> git reset --hard v1.16.0
...

all done, same issue

**Comment by awunnenb** [comment]
There a no error messages at the console

**Comment by barisusakli** [comment]
Where is the `utils.slugify is not a function` error?

**Comment by awunnenb** [comment]
if the user has filled registration form and confirmed to email notification.

**Comment by barisusakli** [comment]
I am asking the stack trace for that utils.slugify error

**Comment by awunnenb** [comment]
where can i get stack traces?

**Comment by awunnenb** [comment]
is there a log file? i can't find

**Comment by barisusakli** [comment]
For server side logs its at `/path/to/nodebb/logs/output.log`
For client side open your browser developer tools and look at the console tab when trying to register.

**Comment by awunnenb** [comment]
Ok, the last entry in output.log is old: 2020-12-01T08:55:24.899Z
i will look at devtools... one moment please

**Comment by awunnenb** [comment]
jquery.js:10099 HEAD https://hsv-fans.hamburg/api/v3/users/bySlug/dermeister 404
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
r @ api.js?v=os2drsi9dig:1
(anonymous) @ api.js?v=os2drsi9dig:1
s @ api.js?v=os2drsi9dig:1
e.head @ api.js?v=os2drsi9dig:1
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
dispatch @ nodebb.min.js?v=os2drsi9dig:1
g.handle @ nodebb.min.js?v=os2drsi9dig:1
service-worker.js:6 Fetch failed loading: HEAD "https://hsv-fans.hamburg/api/v3/users/bySlug/dermeister".
(anonymous) @ service-worker.js:6
Promise.then (async)
(anonymous) @ service-worker.js:4
jquery.js:10099 HEAD https://hsv-fans.hamburg/api/v3/groups/dermeister 404
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
r @ api.js?v=os2drsi9dig:1
(anonymous) @ api.js?v=os2drsi9dig:1
s @ api.js?v=os2drsi9dig:1
e.head @ api.js?v=os2drsi9dig:1
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
dispatch @ nodebb.min.js?v=os2drsi9dig:1
g.handle @ nodebb.min.js?v=os2drsi9dig:1
jquery.js:10099 XHR failed loading: HEAD "https://hsv-fans.hamburg/api/v3/users/bySlug/dermeister".
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
r @ api.js?v=os2drsi9dig:1
(anonymous) @ api.js?v=os2drsi9dig:1
s @ api.js?v=os2drsi9dig:1
e.head @ api.js?v=os2drsi9dig:1
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
dispatch @ nodebb.min.js?v=os2drsi9dig:1
g.handle @ nodebb.min.js?v=os2drsi9dig:1
service-worker.js:6 Fetch failed loading: HEAD "https://hsv-fans.hamburg/api/v3/groups/dermeister".
(anonymous) @ service-worker.js:6
Promise.then (async)
(anonymous) @ service-worker.js:4
jquery.js:10099 XHR failed loading: HEAD "https://hsv-fans.hamburg/api/v3/groups/dermeister".
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
r @ api.js?v=os2drsi9dig:1
(anonymous) @ api.js?v=os2drsi9dig:1
s @ api.js?v=os2drsi9dig:1
e.head @ api.js?v=os2drsi9dig:1
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
dispatch @ nodebb.min.js?v=os2drsi9dig:1
g.handle @ nodebb.min.js?v=os2drsi9dig:1
recaptcha__de.js:543 XHR finished loading: POST "https://www.google.com/recaptcha/api2/reload?k=6Lfw9E8UAAAAADOxhN6X2UOa39fN9fcP_oXL-Vq8".
wE.send @ VM2622 recaptcha__de.js:543
(anonymous) @ VM2622 recaptcha__de.js:48
(anonymous) @ VM2622 recaptcha__de.js:56
e.Bd @ VM2622 recaptcha__de.js:551
(anonymous) @ VM2622 recaptcha__de.js:287
e.x4 @ VM2622 recaptcha__de.js:549
EZ.fr @ VM2622 recaptcha__de.js:549
EZ.send @ VM2622 recaptcha__de.js:551
(anonymous) @ VM2622 recaptcha__de.js:552
(anonymous) @ VM2622 recaptcha__de.js:376
Sp @ VM2622 recaptcha__de.js:457
nQ.send @ VM2622 recaptcha__de.js:552
(anonymous) @ VM2622 recaptcha__de.js:239
(anonymous) @ VM2622 recaptcha__de.js:240
e.C @ VM2622 recaptcha__de.js:690
L.V @ VM2622 recaptcha__de.js:291
(anonymous) @ VM2622 recaptcha__de.js:291
(anonymous) @ VM2622 recaptcha__de.js:351
q.next @ VM2622 recaptcha__de.js:268
R @ VM2622 recaptcha__de.js:94
Promise.then (async)
U @ VM2622 recaptcha__de.js:94
(anonymous) @ VM2622 recaptcha__de.js:94
(anonymous) @ VM2622 recaptcha__de.js:94
(anonymous) @ VM2622 recaptcha__de.js:104
(anonymous) @ VM2622 recaptcha__de.js:290
(anonymous) @ VM2622 recaptcha__de.js:80
(anonymous) @ VM2622 recaptcha__de.js:251
oU @ VM2622 recaptcha__de.js:482
X @ VM2622 recaptcha__de.js:300
u @ VM2622 recaptcha__de.js:175
recaptcha__de.js:543 XHR finished loading: POST "https://www.google.com/recaptcha/api2/userverify?k=6Lfw9E8UAAAAADOxhN6X2UOa39fN9fcP_oXL-Vq8".
wE.send @ VM2622 recaptcha__de.js:543
(anonymous) @ VM2622 recaptcha__de.js:48
(anonymous) @ VM2622 recaptcha__de.js:56
e.Bd @ VM2622 recaptcha__de.js:551
(anonymous) @ VM2622 recaptcha__de.js:287
e.x4 @ VM2622 recaptcha__de.js:549
EZ.fr @ VM2622 recaptcha__de.js:549
EZ.send @ VM2622 recaptcha__de.js:551
(anonymous) @ VM2622 recaptcha__de.js:552
(anonymous) @ VM2622 recaptcha__de.js:376
Sp @ VM2622 recaptcha__de.js:457
nQ.send @ VM2622 recaptcha__de.js:552
e.Z @ VM2622 recaptcha__de.js:690
Promise.then (async)
e.l @ VM2622 recaptcha__de.js:688
(anonymous) @ VM2622 recaptcha__de.js:342
v.<computed>.w.dispatchEvent @ VM2622 recaptcha__de.js:485
(anonymous) @ VM2622 recaptcha__de.js:204
(anonymous) @ VM2622 recaptcha__de.js:619
(anonymous) @ VM2622 recaptcha__de.js:342
v.<computed>.w.dispatchEvent @ VM2622 recaptcha__de.js:485
t.C @ VM2622 recaptcha__de.js:514
(anonymous) @ VM2622 recaptcha__de.js:251
oU @ VM2622 recaptcha__de.js:482
X @ VM2622 recaptcha__de.js:300
u @ VM2622 recaptcha__de.js:175
jquery.js:10099 HEAD https://hsv-fans.hamburg/api/v3/users/bySlug/dermeister 404
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
r @ api.js?v=os2drsi9dig:1
(anonymous) @ api.js?v=os2drsi9dig:1
s @ api.js?v=os2drsi9dig:1
e.head @ api.js?v=os2drsi9dig:1
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
ws.onmessage @ nodebb.min.js?v=os2drsi9dig:1
service-worker.js:6 Fetch failed loading: HEAD "https://hsv-fans.hamburg/api/v3/users/bySlug/dermeister".
(anonymous) @ service-worker.js:6
Promise.then (async)
(anonymous) @ service-worker.js:4
jquery.js:10099 XHR failed loading: HEAD "https://hsv-fans.hamburg/api/v3/users/bySlug/dermeister".
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
r @ api.js?v=os2drsi9dig:1
(anonymous) @ api.js?v=os2drsi9dig:1
s @ api.js?v=os2drsi9dig:1
e.head @ api.js?v=os2drsi9dig:1
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
ws.onmessage @ nodebb.min.js?v=os2drsi9dig:1
jquery.js:10099 HEAD https://hsv-fans.hamburg/api/v3/groups/dermeister 404
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
r @ api.js?v=os2drsi9dig:1
(anonymous) @ api.js?v=os2drsi9dig:1
s @ api.js?v=os2drsi9dig:1
e.head @ api.js?v=os2drsi9dig:1
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
ws.onmessage @ nodebb.min.js?v=os2drsi9dig:1
service-worker.js:6 Fetch failed loading: HEAD "https://hsv-fans.hamburg/api/v3/groups/dermeister".
(anonymous) @ service-worker.js:6
Promise.then (async)
(anonymous) @ service-worker.js:4
jquery.js:10099 XHR failed loading: HEAD "https://hsv-fans.hamburg/api/v3/groups/dermeister".
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
r @ api.js?v=os2drsi9dig:1
(anonymous) @ api.js?v=os2drsi9dig:1
s @ api.js?v=os2drsi9dig:1
e.head @ api.js?v=os2drsi9dig:1
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
ws.onmessage @ nodebb.min.js?v=os2drsi9dig:1
service-worker.js:6 Fetch finished loading: POST "https://hsv-fans.hamburg/register".
(anonymous) @ service-worker.js:6
Promise.then (async)
(anonymous) @ service-worker.js:4
jquery.js:10099 XHR finished loading: POST "https://hsv-fans.hamburg/register".
send @ nodebb.min.js?v=os2drsi9dig:1
ajax @ nodebb.min.js?v=os2drsi9dig:1
q.fn.ajaxSubmit @ jquery-form.js?v=os2drsi9dig:22
(anonymous) @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
Promise.then (async)
l @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
(anonymous) @ register.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
(anonymous) @ nodebb.min.js?v=os2drsi9dig:1
i.emit @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
e @ nodebb.min.js?v=os2drsi9dig:1
ws.onmessage @ nodebb.min.js?v=os2drsi9dig:1
Navigated to https://hsv-fans.hamburg/register/complete?registered=true
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
Fetch finished loading: GET "<URL>".
app.js:791 ServiceWorker registration succeeded.
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
XHR finished loading: GET "<URL>".
service-worker.js:6 Fetch finished loading: POST "https://hsv-fans.hamburg/socket.io/?EIO=4&transport=polling&t=NQlGDKq&sid=hRypZkYj0TgSNY_jAAB-".
(anonymous) @ service-worker.js:6
Promise.then (async)
(anonymous) @ service-worker.js:4
socket.io.js:3888 XHR finished loading: POST "https://hsv-fans.hamburg/socket.io/?EIO=4&transport=polling&t=NQlGDKq&sid=hRypZkYj0TgSNY_jAAB-".
e @ socket.io.js:3888
n @ socket.io.js:3808
e @ socket.io.js:3737
e @ socket.io.js:3750
(anonymous) @ socket.io.js:4250
(anonymous) @ socket.io.js:4868
e @ socket.io.js:4826
(anonymous) @ socket.io.js:4864
e @ socket.io.js:4862
e @ socket.io.js:4249
e @ socket.io.js:3245
e @ socket.io.js:2913
e @ socket.io.js:2979
e @ socket.io.js:2933
e @ socket.io.js:613
e @ socket.io.js:1025
e @ socket.io.js:1048
(anonymous) @ socket.io.js:1732
i.emit @ socket.io.js:1884
e @ socket.io.js:503
(anonymous) @ socket.io.js:431
i.emit @ socket.io.js:1884
e @ socket.io.js:2789
e @ socket.io.js:2860
e @ socket.io.js:2820
(anonymous) @ socket.io.js:2656
i.emit @ socket.io.js:1884
e @ socket.io.js:3283
e @ socket.io.js:4189
e @ socket.io.js:4193
(anonymous) @ socket.io.js:3773
i.emit @ socket.io.js:1884
e @ socket.io.js:3925
e @ socket.io.js:3984
i.onreadystatechange @ socket.io.js:3876
XMLHttpRequest.send (async)
e @ socket.io.js:3888
n @ socket.io.js:3808
e @ socket.io.js:3737
e @ socket.io.js:3770
e @ socket.io.js:4161
e @ socket.io.js:4105
e @ socket.io.js:3213
e @ socket.io.js:2630
n @ socket.io.js:2559
e.exports @ socket.io.js:2422
e @ socket.io.js:424
n @ socket.io.js:337
l @ socket.io.js:178
(anonymous) @ sockets.js:17
(anonymous) @ sockets.js:7
Show 5 more frames
service-worker.js:6 Fetch failed loading: GET "https://hsv-fans.hamburg/assets/src/client/registerComplete.js?v=os2drsi9dig".
(anonymous) @ service-worker.js:6
Promise.then (async)
(anonymous) @ service-worker.js:4
require.js:1961 GET https://hsv-fans.hamburg/assets/src/client/registerComplete.js?v=os2drsi9dig net::ERR_ABORTED 404
req.load @ require.js:1961
load @ require.js:1685
load @ require.js:834
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
(anonymous) @ require.js:1460
setTimeout (async)
req.nextTick @ require.js:1815
o @ require.js:1449
requirejs @ require.js:1797
(anonymous) @ ajaxify.js:334
(anonymous) @ ajaxify.js:347
ajaxify.loadScript @ ajaxify.js:346
ajaxify.end @ ajaxify.js:280
ajaxify.coldLoad @ ajaxify.js:80
(anonymous) @ app.js:31
dispatch @ jquery.js:5429
g.handle @ jquery.js:5233
trigger @ jquery.js:8715
(anonymous) @ jquery.js:8793
each @ jquery.js:381
each @ jquery.js:203
trigger @ jquery.js:8792
c @ app.js:118
execCb @ require.js:1696
check @ require.js:883
(anonymous) @ require.js:1139
(anonymous) @ require.js:134
(anonymous) @ require.js:1189
each @ require.js:59
emit @ require.js:1188
check @ require.js:938
enable @ require.js:1176
init @ require.js:788
O @ require.js:1203
completeLoad @ require.js:1590
onScriptLoad @ require.js:1717
load (async)
req.load @ require.js:1942
load @ require.js:1685
load @ require.js:834
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
(anonymous) @ require.js:1460
setTimeout (async)
req.nextTick @ require.js:1815
o @ require.js:1449
requirejs @ require.js:1797
(anonymous) @ app.js:124
execCb @ require.js:1696
check @ require.js:883
(anonymous) @ require.js:1139
(anonymous) @ require.js:134
(anonymous) @ require.js:1189
each @ require.js:59
emit @ require.js:1188
check @ require.js:938
(anonymous) @ require.js:1139
(anonymous) @ require.js:134
(anonymous) @ require.js:1189
each @ require.js:59
emit @ require.js:1188
check @ require.js:938
(anonymous) @ require.js:1139
(anonymous) @ require.js:134
(anonymous) @ require.js:1189
each @ require.js:59
emit @ require.js:1188
check @ require.js:938
(anonymous) @ require.js:1139
(anonymous) @ require.js:134
(anonymous) @ require.js:1189
each @ require.js:59
emit @ require.js:1188
check @ require.js:938
enable @ require.js:1176
init @ require.js:788
O @ require.js:1203
completeLoad @ require.js:1590
onScriptLoad @ require.js:1717
load (async)
req.load @ require.js:1942
load @ require.js:1685
load @ require.js:834
fetch @ require.js:824
check @ require.js:856
enable @ require.js:1176
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
enable @ require.js:1557
(anonymous) @ require.js:1161
(anonymous) @ require.js:134
each @ require.js:59
enable @ require.js:1113
init @ require.js:788
(anonymous) @ require.js:1460
setTimeout (async)
req.nextTick @ require.js:1815
o @ require.js:1449
requirejs @ require.js:1797
app.load @ app.js:97
(anonymous) @ app.js:23
l @ jquery.js:3762
u @ jquery.js:3830
setTimeout (async)
(anonymous) @ jquery.js:3868
c @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
c @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
setTimeout (async)
(anonymous) @ jquery.js:4127
(anonymous) @ jquery.js:36
(anonymous) @ jquery.js:14
Show 68 more frames
DevTools failed to load SourceMap: Could not load content for https://hsv-fans.hamburg/assets/src/modules/pulling-drawer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://hsv-fans.hamburg/assets/src/modules/jquery.form.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by julianlam** [comment]
Ah... the `utils.slugify is not a function` error does not seem to be in that stack trace :frowning:

**Comment by awunnenb** [comment]
no it is an Info-Message Box in the Browser. Please feel free to register yourself at the domain

**Comment by barisusakli** [comment]
Try running this in your nodebb folder `grep -rnw "utils.slugify" node_modules/` and let us know the output.

**Comment by awunnenb** [comment]
grep: node_modules/: No such file or directory

**Comment by barisusakli** [comment]
It is probably this plugin https://github.com/julianlam/nodebb-plugin-registration-notification/blob/master/library.js#L52

Try disabling it and rebuilding and try again.

**Comment by oplik0** [comment]
Just a guess - the problem is probably with `nodebb-plugin-registration-notification` - it's using `utils.slugify` which was deprecated recently. It's now just `slugify`

**Comment by awunnenb** [comment]
yes but in another nodebb board we are using the same plugin with 1.16.0.
and i'm sorry i had a typo, now:

node_modules/nodebb-plugin-registration-notification/library.js:52:		payload.userslug = utils.slugify(payload.username);

**Comment by awunnenb** [comment]
i have deactivated the plugin and the error is gone. Puuhhh.

**Comment by oplik0** [comment]
The plugin was just fixed, so if you install version 1.2.5 it should work

**Comment by awunnenb** [comment]
@all: Ok thank you very much. Best support ever!
