### ISSUE TITLE
Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

### ISSUE THREAD

**Issue by alfazaz** [NodeBB/NodeBB#9160]
- **NodeBB version:** 1.16.0
- **NodeJS version:** 14.15.3
- **Exact steps to cause this issue:**
	`./nodebb build` (and also in starting logs) gives this message at the beginning : 
```
  started
(node:460185) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
2021-01-03T17:51:20.963Z [5678/460185] - info: [build] Building in parallel mode
```

I don't know if it is something to solve in nodebb or on my server... What to do to make it disappear ?

Thanks !

**Comment by pitaj** [comment]
Always to be due to this:

https://github.com/foreversd/forever/issues/1077

**Comment by alfazaz** [comment]
Ok ! I reverted to nodejs 12 until this thing will be solved.
