### ISSUE TITLE
Bootstrap with predefined admin password

### ISSUE THREAD

**Issue by rjshrjndrn** [NodeBB/NodeBB#9171]
Hi,

Thank you for this awesome application. I nodebb and it works perfect. But I've one question

Is it possible to bootstrap the setup with a predefined config file with **admin password**?

I've to deploy nodebb in k8s cluster and while running for the first time, nodebb should read the config file and create the username and passwords. I searched in the docs, and couldn't find anything. Any pointers higly appreciated. 

Thank you.

**Comment by barisusakli** [comment]
https://community.nodebb.org/topic/13071/couldn-t-set-default-admin-username-and-password-in-config-json
https://community.nodebb.org/topic/15253/how-to-setup-admin-user-in-config-json-in-nodebb/1
