### ISSUE TITLE
	Parallel Execution of Multiple Functions in a Lambda using Node.js

### ISSUE THREAD

**Issue by ThirumalaV** [NodeBB/NodeBB#9172]
Can we execute multiple functions parallelly/asynchronously in a lambda with synchronous flow using node.js. We tried using run-parallel, async/await, and promise.all. But, the functions are executing synchronously one after another rather than the required asynchronous process. Can anyone suggest best approach?

**Comment by barisusakli** [comment]
This is a tracker for the forum software https://nodebb.org, try stackoverflow for general nodejs questions.
