### ISSUE TITLE
MongoDB error ("key too large to index") when running "Consolidate multiple flags reports" migration

### ISSUE THREAD

**Issue by gwynnarth** [NodeBB/NodeBB#9176]
- **NodeBB version:** 1.15.5.
- **NodeBB git hash:** 2b586764e2f3e8869d15b1df523e92a093f99ced
- **NodeJS version:** 12.20.1

- **Installed NodeBB Plugins:** 

- **Database type:** mongo
- **Database version:** 3.4.24

- **Exact steps to cause this issue:**
When running DB upgrade (from 1.14.x to 1.15.x)
The upgrade script fails on the following:
```
[1G    [##############] (489/489) 100% 2021-01-07T11:40:37.039Z [4567/50] - error: uncaughtException: WiredTigerIndex::insert: key too large to index, failing  2162 { : "flag:219:reports", : "{"state":"State","reporter":"Reporter","reported-at":"Reported At","description":"Description","no-flags":"Hooray! No flags found.","assignee":"Assign..." }
MongoError: WiredTigerIndex::insert: key too large to index, failing  2162 { : "flag:219:reports", : "{"state":"State","reporter":"Reporter","reported-at":"Reported At","description":"Description","no-flags":"Hooray! No flags found.","assignee":"Assign..." }
```
Worked this around by setting `db.adminCommand( { setParameter: 1, failIndexKeyTooLong: false } )` just for the migration phase, but it still something that I believe may need verification on your end.
I am not 100% sure that the data is not corrupted in some way right now.
- **What you expected:**
Migration to succeed
- **What happened instead:**
MongoDB error

**Comment by pitaj** [comment]
I believe this was fixed in 1.16.x. Any reason you did not upgrade directly to that version?

**Comment by gwynnarth** [comment]
Hmmm... No other reason besides that 1.16 was not yet released when we started working on the upgrade before the Christmas break (given our setup is a bit complex and it takes time).
Upgrading to 1.16 will come shortly ;-)

Glad to hear it's fixed already. Can you advise whether we should do something extra to straighten things after that failed/worked around migration?

**Comment by barisusakli** [comment]
This seems like a different issue than the one that we fixed a while ago.

``{ : "flag:219:reports", : "{"state":"State","reporter":"Reporter","reported-at":"Reported At","description":"Description","no-flags":"Hooray! No flags found.","assignee":"Assign..." }``

Trying to save a long json string into `flag:<id>:reports` it seems.

**Comment by pitaj** [comment]
A failed migration could leave your database in a bad spot but it's unlikely. If you're worried I'd recommend restoring from your database backup.
