### ISSUE TITLE
Missing key in translation token "global:"

### ISSUE THREAD

**Issue by gwynnarth** [NodeBB/NodeBB#9177]
- **NodeBB version:** 1.15.5.
- **NodeBB git hash:** 2b586764e2f3e8869d15b1df523e92a093f99ced
- **NodeJS version:** 12.20.1

- **Database type:** mongo
- **Database version:** 3.4.24

- **Exact steps to cause this issue:**

After upgrading to NodeBB v1.15.5 our logs are now filled with quite a lot of these error messages:
```
Missing key in translation token "global:" for language "en-GB"
```
Where the actual language might be any language that NodeBB supports - it looks like this reflects the languages our users have chosen.

- **What you expected:**
No error messages ;-)
- **What happened instead:**
Translation-related errors pop up in logs.

**Comment by barisusakli** [comment]
I am guessing this happens because of the `[[global:{user.status}]]` of `[[global:{status}]]` tokens I couldn't find where it is being triggered and why `status` is an empty string.

**Comment by barisusakli** [comment]
Found a place where this was happening https://community.nodebb.org/topic/7930/using-cloudflare-with-nodebb,
Happens when a topic has multiple deleted users
