### ISSUE TITLE
Missing translations for Post Queue

### ISSUE THREAD

**Issue by gwynnarth** [NodeBB/NodeBB#9178]
- **NodeBB version:** 1.15.5.
- **NodeBB git hash:** 2b586764e2f3e8869d15b1df523e92a093f99ced
- **NodeJS version:** 12.20.1

- **Database type:** mongo
- **Database version:** 3.4.24

- **Exact steps to cause this issue:**
Open a Post Queue page with a user that has language set to anything else than `en-GB`.
- **What you expected:**
No errors in logs + text on the page rendered correctly
- **What happened instead:**
```
Missing translation "post-queue:accept" for language "en-US"
Missing translation "post-queue:reject" for language "en-US"
Missing translation "post-queue:reply" for language "en-US"
Missing translation "post-queue:topic" for language "en-US"
Missing translation "post-queue:accept" for language "en-US"
Missing translation "post-queue:reject" for language "en-US"
Missing translation "post-queue:topic" for language "en-US"
Missing translation "post-queue:category-editable" for language "en-US"
Missing translation "post-queue:title-editable" for language "en-US"
```

Additionally NodeBB falls back to using `key` value when rendering the page so it looks a bit broken (no proper capitalization, no text in tooltip hints).

Thanks! :)

**Comment by barisusakli** [comment]
Translations not pushed to transifex maybe 🤔

**Comment by pitaj** [comment]
Why does this kind of thing keep happening? It seems to occur once a month if not more.

**Comment by barisusakli** [comment]
I blame @nodebb-misty

**Comment by julianlam** [comment]
Feel free to open an issue on her repo :shipit: :trollface:
