### ISSUE TITLE
Wrong link in topic thumbs

### ISSUE THREAD

**Issue by fgallese** [NodeBB/NodeBB#9184]
Hello guys.

Recently we updated to v1.16.1 and noticed an issue with topic thumbs. For some reason, the link to the image is formed wrong, like this:

[OUR_FORUM_ADDRESS][IMGUR_LINK]

Example: `https://forobolso.uy/forohttps://i.imgur.com/KannW8J.jpg` where `https://forobolso.uy/foro` is OUR_FORUM_ADDRESS and `https://i.imgur.com/KannW8J.jpg` is the IMGUR_LINK of the thumb.

This causes a 404 on all those images.

See screenshots:
![Screenshot from 2021-01-10 04-56-42](https://user-images.githubusercontent.com/18407255/104112532-24a81500-5301-11eb-933c-e87f88eb250c.png)

![Screenshot from 2021-01-10 04-56-58](https://user-images.githubusercontent.com/18407255/104112530-1fe36100-5301-11eb-938f-6a5f84de4359.png)

We use the imgur plugin, and this looks super related to that, but we haven't touched anything there and it was working fine up to the nodebb upgrade.

Do you have any ideas what might be happening here ?

Thank you in advance for your usual help !

**Comment by barisusakli** [comment]
I think this is happening because the relative path `/foro` is being prepended to the image url here https://github.com/NodeBB/nodebb-theme-persona/commit/b3e8e8f2eec3711354acbbd896f1cfbd37a4472c.

@fgallese  Can you revert that commit and try again?

**Comment by fgallese** [comment]
@barisusakli indeed, reverting that fixed it ! Thank you.

**Comment by julianlam** [comment]
@fgallese Apologies for this, I will commit a proper fix to this shortly, but I am glad to hear that the revert helped your site :smile:

**Comment by julianlam** [comment]
@fgallese Would appreciate if you could try the latest master and report back as to whether the thumbnails continue to be properly served :smile:

**Comment by fgallese** [comment]
Just tested it with master, it works perfectly fine 👍🏻 
Thank you, I appreciate the quick answer and solution to the issue.
