### ISSUE TITLE
Not able to save group settings

### ISSUE THREAD

**Issue by appagg** [NodeBB/NodeBB#9185]
- **NodeBB version:**  v1.16.1
- **NodeBB git hash:**  d7044a5e8623ae6b95360ff58e8f6dbc0e90629b 
- **NodeJS version:**  v14.15.4

- **Installed NodeBB Plugins:**
        * nodebb-plugin-composer-default@6.5.5 (installed, enabled)
        * nodebb-plugin-dbsearch@4.1.2 (installed, disabled)
        * nodebb-plugin-emoji@3.4.2 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
        * nodebb-plugin-fusionauth-oidc@1.0.1 (installed, enabled)
        * nodebb-plugin-markdown@8.12.4 (installed, enabled)
        * nodebb-plugin-mentions@2.13.6 (installed, enabled)
        * nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
        * nodebb-plugin-spam-be-gone@0.7.7 (installed, disabled)
        * nodebb-rewards-essentials@0.1.4 (installed, enabled)
        * nodebb-theme-lavender@5.0.17 (installed, disabled)
        * nodebb-theme-persona@10.3.17 (installed, disabled)
        * nodebb-theme-slick@1.3.7 (installed, enabled)
        * nodebb-theme-vanilla@11.3.10 (installed, disabled)
        * nodebb-widget-essentials@5.0.2 (installed, enabled)

- **Database type:** mongo
- **Database version:** v4.0.22

- **Exact steps to cause this issue:**
	1. login as admin
	2. go to Admin settings -> Manage -> Groups
	3. click a group, e.g. administorators
	4. change a setting, e.g. check Private
	5. Save
	6. Try navigate away and get the "Change not saved" warning
	7. Confirm and navigate back to the group
	8. All settings are cleared

- **What you expected:**
New settings should be saved and existing settings should be still there.

- **What happened instead:**
All setting were cleared

P.S. the "Hidden" setting doesn't seem to work. The hidden group still shows up in the "Home/Groups" page.

**Comment by julianlam** [comment]
Thanks @barisusakli  :100:

**Comment by barisusakli** [comment]
@appagg thanks for reporting will release 1.16.2 this week
