### ISSUE TITLE
Logout is not triggering any action in iPhone responsive layout mode

### ISSUE THREAD

**Issue by appagg** [NodeBB/NodeBB#9186]
- **NodeBB version:** v1.16.1
- **NodeBB git hash:** d7044a5e8623ae6b95360ff58e8f6dbc0e90629b
- **NodeJS version:** v14.15.4

- **Installed NodeBB Plugins:**
        * nodebb-plugin-composer-default@6.5.5 (installed, enabled)
        * nodebb-plugin-dbsearch@4.1.2 (installed, disabled)
        * nodebb-plugin-emoji@3.4.2 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
        * nodebb-plugin-fusionauth-oidc@1.0.1 (installed, enabled)
        * nodebb-plugin-markdown@8.12.4 (installed, enabled)
        * nodebb-plugin-mentions@2.13.6 (installed, enabled)
        * nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
        * nodebb-plugin-spam-be-gone@0.7.7 (installed, disabled)
        * nodebb-rewards-essentials@0.1.4 (installed, enabled)
        * nodebb-theme-lavender@5.0.17 (installed, disabled)
        * nodebb-theme-persona@10.3.17 (installed, disabled)
        * nodebb-theme-slick@1.3.7 (installed, enabled)
        * nodebb-theme-vanilla@11.3.10 (installed, disabled)
        * nodebb-widget-essentials@5.0.2 (installed, enabled)
 

- **Database type:** mongo
- **Database version:** v4.0.22

- **Exact steps to cause this issue:**
1. using iPhone xr/Safari browser (or Chrome), Nodebb is shown in narrow media display
2. login using Nodebb local login
3. after logging in, click the 'three lines' menu and click "Logout"

- **What you expected:**

logout from Nodebb
- **What happened instead:**

Nothing happen, the menu is still open. 
No network activities for the logout action
No console errors from the browser

**Comment by barisusakli** [comment]
Only happens on iphone? Can you repro on https://community.nodebb.org/?

**Comment by appagg** [comment]
Community nodebb works fine. I can confirm that it's an issue for the "Slick" theme. Switched back to "Persona" theme and the issue is gone.
