### ISSUE TITLE
Delete invite when invitee is empty

### ISSUE THREAD

**Issue by magnusvhendin** [NodeBB/NodeBB#9187]
I was working on a plugin that lets the system invite new users. The use case is to create a new registration flow that can do some additional checks before allowing the user to register. The end result being that the plugin sends an invite to the user who wants access.

I brought up the issue here: https://community.nodebb.org/topic/15136/send-invite-without-a-user

I'm trying to use [User.sendInvitationEmail(uid, email)](https://github.com/NodeBB/NodeBB/blob/3ccebf112e1dd02eaa54904198cd8a08c34850b3/src/user/invite.js#L40), but if I send in null, undefined or 0 as the uid I get no feedback that it's wrong. What I do get is, in the ACP, no ability to delete the invite.

So the issue is that I cannot delete an invite if I leave the inviter uid blank. I would think that an error would've been sent if this would cause problems. Even if we would want an admin to invite manually, the invite should be "deletable". I think the error happens [here](https://github.com/NodeBB/NodeBB/blob/3ccebf112e1dd02eaa54904198cd8a08c34850b3/src/user/invite.js#L82).

NodeBB version: 1.14.3 (but it seems to be present in the latest version)

I won't include more info since this is a problem with the source code logic and not with my db.

**Comment by gasoved** [comment]
Hey Magnus,

Whole concept of invitations is built upon an invitation and an inviter relationship. So just as you've discussed it in the community forum thread, you can have a dummy user with the system email to send the invites. Your plugin can create this user automatically.

An invite without an inviter represents an invalid state, so we'll going to patch User.sendInvitationEmail method to prevent this. Normally, this method is only reachable in the program flow after the uid is checked, but as you've pointed out, for plugin developers usage, it should also check incoming the uids and raise an error if needed.
