### ISSUE TITLE
Problems with session cookie on Safari, introduced by adding service worker

### ISSUE THREAD

**Issue by gwynnarth** [NodeBB/NodeBB#9193]
Hi NodeBB Team!

After recent NodeBB upgrade to v1.15.5 I have discovered that I can no longer sign into our forums in Safari (both mobile and desktop are equally affected). After much debugging and head-scratching I pinpointed the root cause to this:

https://samesite-pwa-demo.herokuapp.com/

In short: Safari (and only Safari... ) does not send `SameSite=Lax` cookies when request is caused by 302 redirect + there is a caching Service Worker installed (and f4d76f1eddd19470fb1fcff0ac27d7f72dbec26a added the Service Worker). Obviously we want the session cookie to be protected so it has to stay as `Lax`.
Unfortunately this bug completely breaks ability to sign in on iPhones, as the only way to sign into our forums is through oAuth2 flow. The bug causes this check in `authentication.js` to fail:
```
next(req.query.state !== req.session.ssoState ? new Error('[[error:csrf-invalid]]') : null);
```
Since Safari didn't send the session cookie the server has no way of retrieving correct state token from the session and returns a 500 error page on the final callback URL.

Hopefully Apple will eventually fix this but until now I have sorta-kinda-worked this around by adding the following to the `service-worker.js`:
```
if (event.request.url.match(/https?:\/\/[^/]+\/auth\/.+/)) {
		return;
	}
```

This causes the SW to skip caching for any `/auth/*` request. The session cookie gets sent and logging in works. It's better, but still not perfect, as now I am back on Homepage greeted by "Session Mismatch" popup. Clicking "OK" reloads the forums page and I am finally properly signed in. For now it's good enough, I guess, but obviously it would be better to have this working flawlessly.

You can try it on https://forums.opera.com yourself - I'd appreciate if you could take a look and maybe figure our what causes the session mismatch to happen.

Sidenote: I was really puzzled to see that on https://community.nodebb.org everything works properly (tried signing in through Google) as this didn't make sense to me. It should exhibit the same bug like on our forums...But then I realized that f4d76f1eddd19470fb1fcff0ac27d7f72dbec26a moved the service worker to a subdirectory.
![obraz](https://user-images.githubusercontent.com/591754/104326157-aeb2d200-54e9-11eb-920c-90d0a62e40f9.png)

> The scope of the service worker determines which files the service worker controls, in other words, from which path the  service worker will intercept requests. The default scope is the location of the service worker file, and extends to all  directories below. So if service-worker.js is located in the root directory, the service worker will control requests from all files at this domain.
-https://developers.google.com/web/ilt/pwa/introduction-to-service-worker

As a consequence it looks like SW it pretty much inactive on newer NodeBB releases. That's something you'll probably want to fix too.

BR,
Artur

**Comment by barisusakli** [comment]
@gwynnarth could this maybe fix this issue as well? https://github.com/NodeBB/NodeBB/commit/20c1b684ed9a4522d6c5ee69a0151be5b68c947f

The upload progress in the composer wasn't working so I disabled the service-worker for POST requests. I think you don't have this code on 1.15.5

**Comment by gwynnarth** [comment]
Yeah. Saw that but I didn't port this particular change since it's irrelevant as all requests in oAuth2 flow are GETs.

**Comment by psychobunny** [comment]
hi @gwynnarth I've been having a hard time producing this reliably on iOS, would you be able to try two things for me please?

1. Lighthouse shows missing manifest icons (Settings -> General -> Progressive Web App). Could you add these icons and see if it makes a difference? 
![lighthouse-opera](https://user-images.githubusercontent.com/654670/105249993-fd461900-5b46-11eb-98e1-dc33ca153957.png)

2. Just to cover our bases, could you comment this line out 
https://github.com/NodeBB/NodeBB/blob/master/public/src/app.js#L95 ?
I had a test case with Twitter SSO where I was able to reproduce the issue regardless of whether or not the service worker code existed (+ hard cache/history clear on every run), which is definitely leaving me scratching my head at the moment 

Assuming it's still bugged, do you have a staging environment that doesn't have the modified service worker code so I can have a look myself?

Thanks!

**Comment by gwynnarth** [comment]
Hi @psychobunny :)

ad 1. Fixed. Did not make a difference, unfortunately.

ad 2. Deployed on our production. It still didn't fix the issue, but it confirmed my suspicions as to WHY you can reproduce the issue even if Service Worker seems disabled: it turns out that disabling SW registration does not mean that already registered workers get unregistered automatically. In fact here's the issue reproduced after I've commented out registering SW on forums.opera.com (my apologies that all screenshots are in Polish, but hopefully it will still make enough sense to you):

![obraz](https://user-images.githubusercontent.com/591754/105483000-7bbacc00-5ca9-11eb-9ed5-9ffd296cea0a.png)

What we see here is that there are no new attempts to register the SW (see lack of the `ServiceWorker registration succeeded.` message in the JS console output), but the SW is still registered and runs with our previous code, as can be peeked through "Programming" menu. Finally - the dreaded "Session mismatch" error is also here.

What's needed is the manual de-registration of the worker, as described here: https://www.danielhill.com.au/removing-service-workers-from-mac-safari/

After that, voilà:

![obraz](https://user-images.githubusercontent.com/591754/105483351-08658a00-5caa-11eb-86df-e7d0cdc15ffe.png)

No more Service Workers - no more problems.

Hope that explains enough to keep you going forward. If you still think you'd benefit from access to our staging environment then please DM me through our forums (I am @amatczak there) as staging is behind a firewall and I'd need to whitelist your IP address to grant you access.

BR,
Artur

**Comment by gasoved** [comment]
Moreover, it seems Safari doesn't send "Lax" cookies even when the browser is navigated to the forum by clicking a link (+ there is a caching service worker).

For session mismatch, we can do a slient reload for Safari instead of showing a confirmation modal. It would probably not noticed by many.
Another option is going nuclear and not registering service workers for Safari, which would also solve SSO problems mentioned above.

**Comment by julianlam** [comment]
I am in favour of disallowing the service worker on Safari until such time as this bug is fixed upstream
