### ISSUE TITLE
First in Use, First in Right

### ISSUE THREAD

**Issue by alenparker123** [NodeBB/NodeBB#9196]
Trademark rights have a simple rule that you must be the first to use the mark in business, either you are selling your products (for goods) or delivering services before you are eligible to register for your trademark. So the question arises, [how do you trademark a name in Florida](https://www.trademarkterminal.com/florida/)? You are required to show evidence of the service you are using. If you want a trademark for goods, you can show forms of labels, decals, tags, wrappers, boxes, and containers as a piece of evidence. For services, business cards, brochures, flyers, and newspaper advertisements are sufficient. What do you think about this strategy of the trademark?

**Comment by psychobunny** [comment]
marked as spam
