### ISSUE TITLE
Group Settings Reset when using WriteAPI

### ISSUE THREAD

**Issue by Starystars67** [NodeBB/NodeBB#9205]
- **NodeBB version:**  v1.16.1
- **Operating System:**  Windows Server 2016
- **NodeBB git hash:** d7044a5e8623ae6b95360ff58e8f6dbc0e90629b
- **NodeJS version:** v12.18.4
- **Installed NodeBB Plugins:** 
Active plugins:
        * nodebb-plugin-announcements@0.1.10 (installed, enabled)
        * nodebb-plugin-archiver@3.0.2 (installed, enabled)
        * nodebb-plugin-calendar@1.0.0-alpha.55 (installed, enabled)
        * nodebb-plugin-canned-responses@2.3.6 (installed, enabled)
        * nodebb-plugin-cards-fullname@0.0.4 (installed, enabled)
        * nodebb-plugin-cards2@0.2.6 (installed, enabled)
        * nodebb-plugin-composer-default@6.5.5 (installed, enabled)
        * nodebb-plugin-dbsearch@4.1.2 (installed, enabled)
        * nodebb-plugin-discord-notification@1.5.0 (installed, enabled)
        * nodebb-plugin-emoji@3.4.2 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
        * nodebb-plugin-featured-topics-extended@0.4.3 (installed, enabled)
        * nodebb-plugin-google-analytics@0.5.11 (installed, enabled)
        * nodebb-plugin-markdown@8.12.4 (installed, enabled)
        * nodebb-plugin-mentions@2.13.6 (installed, enabled)
        * nodebb-plugin-mentions-etr@2.7.6 (installed, disabled)
        * nodebb-plugin-mentions-notifier@0.2.5 (installed, disabled)
        * nodebb-plugin-night-mode@1.0.7 (installed, enabled)
        * nodebb-plugin-ns-awards@6.0.0 (installed, enabled)
        * nodebb-plugin-poll@1.1.4 (installed, enabled)
        * nodebb-plugin-postmentions@0.0.3 (installed, disabled)
        * nodebb-plugin-question-and-answer@0.8.5 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.13 (installed, enabled)
        * nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
        * nodebb-plugin-spam-be-gone@0.7.7 (installed, disabled)
        * nodebb-plugin-sso-discord-with-logo@1.0.2 (installed, enabled)
        * nodebb-plugin-sso-patreon@1.0.0 (installed, enabled)
        * nodebb-plugin-threaded-replies@0.1.0 (installed, enabled)
        * nodebb-rewards-essentials@0.1.4 (installed, enabled)
        * nodebb-theme-lavender@5.0.17 (installed, disabled)
        * nodebb-theme-persona@10.3.17 (installed, enabled)
        * nodebb-theme-slick@1.3.7 (installed, disabled)
        * nodebb-theme-vanilla@11.3.10 (installed, disabled)
        * nodebb-widget-board-stats@1.2.3 (installed, enabled)
        * nodebb-widget-essentials@5.0.2 (installed, enabled)
- **Database type:** mongo
- **Database version:** 4.0.2
- **Exact steps to cause this issue:**
So all was working before I created a script to sync discord roles with NodeBB forum groups.
To apply the group to a user I searched all users with a discordID and then checked this against my discord server.
If a role in discord was found I added this user to the group on NodeBB using the WriteAPI and the following URL:
`https://forum.example.com/api/v3/groups/early-access/membership/${user.uid}`

After this had been running for maybe an hour I checked on the group and noticed that the settings for it being hidden and such had been reset. Trying to re-set them results in a changes saved notification (as you would expect) however reloading the page or opening it up again in a new tab/browser shows that they have not been saved or they had been reset again.

- **What you expected:**
I expected the system to add the user to the given group.
- **What happened instead:**
The user is added to the given group however the group settings such as whether is hidden, show badge, disable join requests, leave, so on are all reset to false. Even disabling my script has now resulted in me being unable to change the settings.

**Comment by barisusakli** [comment]
I think this is the same issue as https://github.com/NodeBB/NodeBB/issues/9185

**Comment by Starystars67** [comment]
Wow this does definitely seem to be of the same issue / area. Cannot believe I missed that. Cheers
