### ISSUE TITLE
Error while submitting message or voting

### ISSUE THREAD

**Issue by fgallese** [NodeBB/NodeBB#9209]
Hello ! I'm here again to report an issue we are facing in our forum.

This time unfortunately I don't have exact information on what is happening, as I personally haven't been able to reproduce it, but a huge number of users of our forum are reporting an error while trying to either post a reply in a topic or upvote/downvote a message.

They all have sent us a lot of screenshots, and this is the error they see:

![error-nodebb](https://user-images.githubusercontent.com/18407255/104900424-1c994680-598d-11eb-98fe-5548c21a3231.jpg)

The common denominator is that they get this error only on the phone, never on the PC, and if they select "View site as in desktop" in the phone the error does not happen.

On the server logs it is difficult to identify exactly log lines when this happens, but what I can see and I assume it is related, is a lot of this error messages:

```
2021-01-18T08:21:54.897Z [4567/274] - error: topics.loadMore
Error: [[error:no-privileges]]
    at SocketTopics.loadMore (/usr/src/app/nodebb/src/socket.io/topics/infinitescroll.js:22:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async onMessage (/usr/src/app/nodebb/src/socket.io/index.js:150:19)
```

```
2021-01-18T04:49:20.259Z [4567/274] - error: posts.getVoters
Error: [[error:no-privileges]]
    at SocketPosts.getVoters (/usr/src/app/nodebb/src/socket.io/posts/votes.js:20:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async onMessage (/usr/src/app/nodebb/src/socket.io/index.js:150:19)
```

```
2021-01-12T00:00:10.400Z [4567/274] - error: meta.rooms.leaveCurrent
Error: [[error:invalid-session]]
    at validateSession (/usr/src/app/nodebb/src/socket.io/index.js:196:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async onMessage (/usr/src/app/nodebb/src/socket.io/index.js:143:3)
```

```
2021-01-12T00:24:02.621Z [4567/274] - error: /foro/api/v3/topics/52
invalid csrf token
2021-01-12T00:26:42.965Z [4567/274] - error: /foro/api/v3/topics/52
invalid csrf token
2021-01-12T00:43:20.021Z [4567/274] - error: /foro/api/v3/posts/125729/vote
invalid csrf token
2021-01-12T00:59:53.548Z [4567/274] - error: /foro/user/el-mana/chats
Error: [[error:no-privileges]]
    at chatsController.get (/usr/src/app/nodebb/src/controllers/accounts/chats.js:22:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/src/app/nodebb/src/routes/helpers.js:34:5
```

There are an awful lot of errors like this, the whole server log is filled with this kind of errors.

Do you think it might be related ? Any idea what might be going on ?

Thank you in advance for your usual help.

BTW we are running version 1.16.1.

**Comment by fgallese** [comment]
I've just spent one hour trying to reproduce it with different browsers and devices and I wasn't able to. The only thing I didn't change is the user I was using to test, so a wild guess is that this is related to some information on the user or maybe some corrupted session information in the browser ?

Regarding the OS, it seems that it affects both android and apple devices.

Anyway, will try to get more information from affected users and keep trying myself to better understand the issue.

Sorry for this vague report, and thank you @psychobunny for your help.

**Comment by alfazaz** [comment]
Hello,

Same thing on my nodebb 1.16.2 site (it was also a problem on 1.16.1 ; I didn't tried 1.16.0). There was no problem on 1.15.x.

I had this problem for example just now trying to post from my android phone. I see in log : 
invalid csrf token

Posting is working again after reloading the page.

**Comment by alfazaz** [comment]
Many users reported again this problem to me. They need to reload page to be able to post without having the red error window. It happens also for me from my smartphone.

Any idea? You haven't this bug on nodebb community forum? 

Each time, it writes in log "invalid crsf token". Is it related to changes with socket.io since nodebb 1.15?

**Comment by pitaj** [comment]
These are submitted with socket.io, so it's possible that's the issue. Have you suggested for your users to clear their browser cache?

**Comment by alfazaz** [comment]
I've already done this but the bug comes back... It's not simple to trace it.

Something goes wrong when a (long?) disconnection occurs, with a reconnection without reloading totally the page.

**Comment by julianlam** [comment]
Actually voting and replying are done via POST now. Could it be your users are logging out in other tabs and expecting NodeBB to still be logged in in another tab?

**Comment by alfazaz** [comment]
No. I had the problem on my smartphone with only one tab opened. I'm always staying logged in (but the network connection can be interrupted from time to time).

**Comment by fgallese** [comment]
Today, for the first time, this happened to me.
It was on the mobile phone using chrome. I was browsing normally the forum when I went to upvote some message and got this error.
Any message I wanted to upvote gave this error, not just a specific one.

As I was in the phone, I had no way of checking the console or network tab to see what is going on.

To nodebb developers: wherever this error message is triggered, can you please add information ? Just "error" is not very helpful to figure out what is failing.

![Screenshot_20210207-100304.png](https://user-images.githubusercontent.com/18407255/107139466-6346e480-692c-11eb-934a-2f916fa8e3e7.png)

**Comment by barisusakli** [comment]
Can you add this code here https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/api.js#L27

```
app.alertError(JSON.stringify({ 
  status: ev.status, 
  responseText: ev.responseText,
  statusText: ev.statusText,
}):
```

It seems like the a server side error is happening but a proper error message isn't being returned.

**Comment by alfazaz** [comment]
I putted this code (changing the last line with `}));` because there was a problem on building with your version).

I will see what it gives on next error...

**Comment by fgallese** [comment]
@barisusakli I got a capture from a user who got the error. It seems to be a forbidden error:

![err](https://user-images.githubusercontent.com/18407255/107786619-2aa96f80-6d5f-11eb-96b3-1bb4d3d767f6.jpg)

Any idea what might be the reason ?

**Comment by barisusakli** [comment]
I recently fixed a csrf forbidden error, in https://github.com/NodeBB/NodeBB/commit/b6493f896fe825a84e6d1373d0351d5430cddf6c.

It was happening if a user loaded the forum on a 404 page like `https://yourforum.com/404page` and then navigated and tried to post or upvote.

Try applying that commit and let us know. Also you can ask your users to check if they are getting this issue after navigating from a 404 or error page.
