### ISSUE TITLE
Saving of Badge Information not Possible

### ISSUE THREAD

**Issue by jsbberlin** [NodeBB/NodeBB#9212]
- **NodeBB version: 1.16.1** 
- **NodeJS version:v10.23.0**
-**Plugins**
	* nodebb-plugin-adsense@1.0.5 (installed, enabled)
	* nodebb-plugin-beep@0.4.4 (installed, enabled)
	* nodebb-plugin-composer-default@6.5.5 (installed, enabled)
	* nodebb-plugin-custom-pages@1.3.1 (installed, enabled)
	* nodebb-plugin-db-explorer@1.0.2 (installed, enabled)
	* nodebb-plugin-dbsearch@4.1.2 (installed, enabled)
	* nodebb-plugin-desktop-notifications@0.3.3 (installed, enabled)
	* nodebb-plugin-emailer-mailjet@1.1.0 (installed, enabled)
	* nodebb-plugin-emoji@3.4.2 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
	* nodebb-plugin-gdpr@1.0.11 (installed, enabled)
	* nodebb-plugin-markdown@8.12.4 (installed, enabled)
	* nodebb-plugin-mentions@2.13.6 (installed, enabled)
	* nodebb-plugin-night-mode@1.0.7 (installed, enabled)
	* nodebb-plugin-poll@1.1.4 (installed, enabled)
	* nodebb-plugin-prometheus@0.4.0 (installed, enabled)
	* nodebb-plugin-question-and-answer@0.8.5 (installed, enabled)
	* nodebb-plugin-spam-be-gone@0.7.7 (installed, enabled)
	* nodebb-rewards-essentials@0.1.4 (installed, enabled)
	* nodebb-theme-persona@10.3.17 (installed, enabled)
	* nodebb-widget-board-stats@1.2.3 (installed, enabled)
	* nodebb-widget-essentials@5.0.2 (installed, enabled)

- **Database type:** mongo, 
- **Database version: v4.2.10** 
- **Steps to reproduce:**
	1. Admin->Manage->Groups ->click'Show Badge'
	2. Saving information 'Success Changes saved!' is displayed
	3.  Leave Page  ->'You have unsaved changes. Are you sure you wish to navigate away?' is displayed
	4. Re-check resent changes: Changes not saved for checkboxes: 'Show Badge', 'Private', 'Disable join requests', 'Disallow users from leaving the group', 'Hidden'

- **Expected behaviour:**
    1. Changes are saved and later displayed

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/9185
