### ISSUE TITLE
Flag count is showing inaccessible flags

### ISSUE THREAD

**Issue by thewilloftheshadow** [NodeBB/NodeBB#9216]
- **NodeBB version:** 1.16.3
- **NodeBB git hash:** 023e4cfcee208a0bae121a6e343a8c53009fd090
- **NodeJS version:** v14.15.3

- **Installed NodeBB Plugins:** Not applicable, but can provide if needed
- **Database type:** mongo
- **Database version:** 4.4.2

On my forums, moderators who are not global moderators are reporting seeing an unread badge count for flags that they can not access and that have already been resolved

My account (admin): 
![image](https://user-images.githubusercontent.com/35580099/105614649-3ae9b280-5d90-11eb-8e9c-a33a05842d21.png)
Global moderator: 
![](https://i.postimg.cc/6pp6JXHV/89-C1-DCBC-51-A2-46-A9-85-F6-0-E2-CEABC11-AC.jpg)
Moderator of two categories:
![](https://forums.theshadow.xyz/assets/uploads/files/1611433068701-49182ff4-4cde-4fe8-ba99-c5fc4c9c3cfd-image.png)
Moderator of one category: 
![](https://forums.theshadow.xyz/assets/uploads/files/1611423878088-screenshot-2021-01-24-at-1.44.01-am.png)

**Comment by julianlam** [comment]
Hi @thewilloftheshadow - I was not able to reproduce this with a moderator of one category, the unread count seems to reflect the actual flags they can access.

When I have a mod of two categories, I see the issue.

**Comment by thewilloftheshadow** [comment]
@julianlam I don’t have any moderators who only have one category, so that seems like it fits the pattern

**Comment by julianlam** [comment]
1603566

**Comment by julianlam** [comment]
Thanks for reporting, this one was an important fix to the filtering logic that had gone unnoticed for 4 years, it seems!

**Comment by thewilloftheshadow** [comment]
Haha awesome, thanks!
