### ISSUE TITLE
Sometimes nodebb ignores my email settings for smtp

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#9223]
- **NodeBB version: 1.16.2**
- **NodeBB git hash: 672959c13f5b416305afe14c04b4706e3e332114** 
- **NodeJS version: v12.20.1**
- Installed NodeBB Plugins:
Active plugins:
	* nodebb-plugin-beep@0.4.4 (installed, enabled)
	* nodebb-plugin-composer-default@6.5.5 (installed, enabled)
	* nodebb-plugin-custom-pages (not installed, enabled)
	* nodebb-plugin-dbsearch@4.1.2 (installed, enabled)
	* nodebb-plugin-emailer-ssl-smtp (not installed, enabled)
	* nodebb-plugin-emoji@3.4.2 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
	* nodebb-plugin-emoji-one@2.0.0 (installed, enabled)
	* nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
	* nodebb-plugin-iframely@0.7.14 (installed, enabled)
	* nodebb-plugin-markdown@8.12.4 (installed, enabled)
	* nodebb-plugin-mentions@2.13.6 (installed, enabled)
	* nodebb-plugin-poll@1.1.4 (installed, enabled)
	* nodebb-plugin-registration-notification@1.2.5 (installed, enabled)
	* nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
	* nodebb-plugin-spam-be-gone@0.7.7 (installed, enabled)
	* nodebb-plugin-write-api@5.8.5 (installed, enabled)
	* nodebb-rewards-essentials@0.1.4 (installed, enabled)
	* nodebb-theme-lavender@5.0.17 (installed, disabled)
	* nodebb-theme-persona@10.3.19 (installed, enabled)
	* nodebb-theme-slick@1.3.8 (installed, disabled)
	* nodebb-theme-vanilla@11.3.10 (installed, disabled)
	* nodebb-widget-essentials@5.0.2 (installed, enabled)
- **Database type: mongo**
- **Database version: 4.4.3** 
- **What you expected: that nodebb will use my email settings for gmail smtp in settings/email/smtp**
- **What happened instead: sometimes nodebb uses my local postfix instead of gmail. Then i have to go to settings/email. The gmail smtp settings are still there. If i save them again, nodebb will use them for a couple of days and then the same issue happens again**

**Comment by barisusakli** [comment]
@awunnenb thanks for reporting, we will fix this for 1.17.0

**Comment by barisusakli** [comment]
@awunnenb, let me know if the issue is resolved after the above commit.

When settings were saved on an acp page other than emails (ie general settings) setupFallbackTransport was called with a wrong config object that didn't have the smtp settings essentially reverting back to sendmail.
