### ISSUE TITLE
scrolling or filter inside dropdown for pre defined tags in category when post new topic

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#9224]
- **NodeBB version: 1.16.2** 
- **NodeBB git hash: 672959c13f5b416305afe14c04b4706e3e332114** 
- **NodeJS version: v12.20.1**
- **Installed NodeBB Plugins:**
Active plugins:
	* nodebb-plugin-beep@0.4.4 (installed, enabled)
	* nodebb-plugin-composer-default@6.5.5 (installed, enabled)
	* nodebb-plugin-custom-pages (not installed, enabled)
	* nodebb-plugin-dbsearch@4.1.2 (installed, enabled)
	* nodebb-plugin-emailer-ssl-smtp (not installed, enabled)
	* nodebb-plugin-emoji@3.4.2 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
	* nodebb-plugin-emoji-one@2.0.0 (installed, enabled)
	* nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
	* nodebb-plugin-iframely@0.7.14 (installed, enabled)
	* nodebb-plugin-markdown@8.12.4 (installed, enabled)
	* nodebb-plugin-mentions@2.13.6 (installed, enabled)
	* nodebb-plugin-poll@1.1.4 (installed, enabled)
	* nodebb-plugin-registration-notification@1.2.5 (installed, enabled)
	* nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
	* nodebb-plugin-spam-be-gone@0.7.7 (installed, enabled)
	* nodebb-plugin-write-api@5.8.5 (installed, enabled)
	* nodebb-rewards-essentials@0.1.4 (installed, enabled)
	* nodebb-theme-lavender@5.0.17 (installed, disabled)
	* nodebb-theme-persona@10.3.19 (installed, enabled)
	* nodebb-theme-slick@1.3.8 (installed, disabled)
	* nodebb-theme-vanilla@11.3.10 (installed, disabled)
	* nodebb-widget-essentials@5.0.2 (installed, enabled)  
- **Database type: mongo**
- **Database version: 4.4.3** 
- **What you expected: scrolling or filter inside dropdown for pre defined tags in category if i post new topic**
- **What happened instead: iI have tags pre defined for some categories and i want to scroll if the list is longer than the screen. nodebb hide the tags now and there is no scrolling possible**

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/issues/115
