### ISSUE TITLE
uploaded images used in widgets are displayed as orphaned

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#9243]
- **NodeBB version: 1.16.2** 
- **NodeBB git hash: 672959c13f5b416305afe14c04b4706e3e332114** 
- **NodeJS version: v12.20.1**
- **Installed NodeBB Plugins:**
Active plugins:
	* nodebb-plugin-beep@0.4.4 (installed, enabled)
	* nodebb-plugin-composer-default@6.5.5 (installed, enabled)
	* nodebb-plugin-custom-pages (not installed, enabled)
	* nodebb-plugin-dbsearch@4.1.2 (installed, enabled)
	* nodebb-plugin-emailer-ssl-smtp (not installed, enabled)
	* nodebb-plugin-emoji@3.4.2 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
	* nodebb-plugin-emoji-one@2.0.0 (installed, enabled)
	* nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
	* nodebb-plugin-iframely@0.7.14 (installed, enabled)
	* nodebb-plugin-markdown@8.12.4 (installed, enabled)
	* nodebb-plugin-mentions@2.13.6 (installed, enabled)
	* nodebb-plugin-poll@1.1.4 (installed, enabled)
	* nodebb-plugin-registration-notification@1.2.5 (installed, enabled)
	* nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
	* nodebb-plugin-spam-be-gone@0.7.7 (installed, enabled)
	* nodebb-plugin-write-api@5.8.5 (installed, enabled)
	* nodebb-rewards-essentials@0.1.4 (installed, enabled)
	* nodebb-theme-lavender@5.0.17 (installed, disabled)
	* nodebb-theme-persona@10.3.19 (installed, enabled)
	* nodebb-theme-slick@1.3.8 (installed, disabled)
	* nodebb-theme-vanilla@11.3.10 (installed, disabled)
	* nodebb-widget-essentials@5.0.2 (installed, enabled)  
- **Database type: mongo**
- **Database version: 4.4.3** 
- **What you expected: if i use uploaded images in the Widgets for example topics/footer they will not shown as used in the ACP / manage/uploads?dir=/files**
- **What happened instead: manage/uploads?dir=/files shows these files as orphaned**

**Comment by julianlam** [comment]
Hi @awunnenb -- thanks for reporting. This is intentional in that right now the post upload tracking only ensures that the image is used in the post itself (or as a topic thumbnail).

I only check those as otherwise it would be too exhaustive to check everywhere (e.g. aboutme, signature, widgets, site logo, the list goes on...)
