### ISSUE TITLE
How to avoid and remove plugins that are not installed but enabled?

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#9249]
How to avoid and remove plugins that are not installed but enabled?

command: ./nodebb plugins

Active plugins:
	* nodebb-plugin-custom-pages (**not installed, enabled**)
	* nodebb-plugin-emailer-ssl-smtp (**not installed, enabled**)

**Comment by pitaj** [comment]
`./nodebb reset -p <plugin>` should do it.

**Comment by awunnenb** [comment]
ok they are gone, thank you.
