### ISSUE TITLE
The thumbnail of the topic cannot be seen after editing the first post

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/NodeBB#9251]
Steps: 

1. Create a new topic, write a first post
2. Click "add a thumbnail to this topic"
3. Then paste the URL of the thumbnail to "paste a topic thumbnail URL"
4. Save the post, and post the topic
5. Thumbnail can be seen clearly 

Then; 

6. Edit the content of the first post without changing the URL and save it 

Thumbnail cannot be reached anymore... it shows an error on the thumbnail... 

The only way to fix this is that every time the first post is edited, the same image URL should be pasted to keep the thumbnail visible.

**Comment by julianlam** [comment]
Hi @AliCihan -- what version of NodeBB are you using at the moment?

Topic thumbnails have been heavily refactored, and uploading a topic thumbnail via URL is no longer available, presently. It may be added again in the future if there is a need for it.

So I think this bug may be invalid as it no longer applies to the latest version of NodeBB.

**Comment by AliCihan** [comment]
We are using NodeBB v1.15.2 , what is happening to the already uploaded or linked thumbnails of the topics in the new (1.16.2) version?
