### ISSUE TITLE
[Plugin] Middleware to redirect user & api requests

### ISSUE THREAD

**Issue by LM1LC3N7** [NodeBB/NodeBB#9258]
Hello,

I would like to know how I can redirect requests to `/login` or `/api/login` based on the request source?
For example, if a user load the main page, I can redirect him to `/login`.
But if he click from the page login to "recent" for example, I need to redirect him to `/api/login` as the navigation is handled by ajaxify.

Currently I redirect that way:

```javascript
return helpers.redirect(res, '/login');
```

But this only work with page reloads. With the Lavender theme for example, it will only print a blank page with console errors:
```javascript
Uncaught TypeError: can't access property "name", t.template is undefined
```
![image](https://user-images.githubusercontent.com/14235706/107040584-b4859580-67bf-11eb-97ab-b09a2527d01d.png)

- **NodeBB version:** v1.16.2
- **NodeBB git hash:** 023e4cfcee208a0bae121a6e343a8c53009fd090
- **NodeJS version:** v14.15.4

- **Installed NodeBB Plugins:** Base

- **Database type:** mongo, redis, or postgres
- **Database version:** Redis server v=5.0.7 sha=36c42f74:0 malloc=libc bits=64 build=2254c3b4d13e72f7

- **Exact steps to cause this issue:**
1. Create and install a plugin with a middleware (https://github.com/LM1LC3N7/nodebb-plugin-private-forum)
2. Redirect users when they are not logged in, and trying to access to private pages
- **What you expected:** All users a redirected to the login page, either they refresh the page or the click to another menu (that is forbidden by the module).

- **What happened instead:** No redirection is the forbidden page is accessed after the first load (except if the user refresh the page). An error is generated in the web browser console.

**Comment by barisusakli** [comment]
Try `router.use` instead of `app.use`. `helpers.notAllowed` will only work if `res.locals.isAPI` is set to true when you try to navigate to `/api/recent`

**Comment by LM1LC3N7** [comment]
Thanks, I will try and close the issue if this is working.

**Comment by LM1LC3N7** [comment]
It seems not to work :

```javascript
res.status('403');
res.redirect('/login');
helpers.redirect('/login')
```

**Comment by barisusakli** [comment]
I modified the plugin to this and it was properly redirecting to login for all routes. I only changed `app.use` to `router.use`
```
plugin.init = function (params, callback) {
	
	const { app, middleware, router } = params;
	let allowedPages = /\/(assets\/|login|register|reset|plugins\/).*|.*(.css|.js)$/;
	
	router.use(function (req, res, next) {
		if ((allowedPages.test(req.url)) || (req.url === "/") || (req.uid > 0)) {
			winston.verbose("[plugin-nodebb-private-forum] User is logged or URL is allowed ("+ req.url +"), no redirect.");
			next();
		} else {
			winston.verbose("[plugin-nodebb-private-forum] User is not logged and URL is not allowed ("+ req.url +"), redirecting to login page.");
			helpers.notAllowed(req, res, next);
		}
	});
	callback();
};
```

**Comment by pitaj** [comment]
You can't do `res.redirect` _and_ `helpers.redirect`. Only use the second one.

**Comment by LM1LC3N7** [comment]
With Lavender theme, @barisusakli this code does not work on my side. 

I don't understand why, but with `router.use` my code does not redirect anything.

**Comment by LM1LC3N7** [comment]
In fact the plugin seems not be used anymore has I can't see the debug messages. 
Is this due to `router.use`?

**Comment by pitaj** [comment]
You're going to need to share more code. Is your plugin falling to load due to an error?

**Comment by LM1LC3N7** [comment]
Ok sorry, it was a mistype in my debug code. Now everything is good! 
Thank you all very much.
