### ISSUE TITLE
 Lack of access to all subcategories 

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#9294]
- **NodeBB version:** v1.16.2

- **Database type:** mongo, redis, 
- **Database version:**  MongoDB Version 4.2.3 ,Redis Version 5.0.7

hi, in latest version, there is a problem displaying subcategories of categories that have more than 10 subcategories
in ACP: 
If there are more than 10 subcategories, only 10 items will be displayed on the  admin/manage/categories.
Thus, it is no longer possible to change the subcategories of these types of categories or the order of display of subcategories of this type of categories, because not all subcategories are available
When a new subcategory is created, it is placed as the last subcategory at the lowest level and is unavailable

in forum:

When we want to create a new topic (especially from the recent and unread page, where the default category is not selected)
In the category selection section
Subcategories related to such categories are not displayed

**Comment by julianlam** [comment]
Commit hash?

**Comment by barisusakli** [comment]
Are you on latest master with latest persona?

ACP:
Should let you search and select subcategories and also have pagination so you can look at all categories. There is also a set order button for each category in the dropdown.

Forum:
The default value for number of subcategories display is 10, if you want to see more subcategories for a particular category you can adjust it in the category settings page for that category.

**Comment by roghaye-m** [comment]
yes, Installed 10.5.5 | Latest 10.5.5

ACP : 
I did not see the pagination!
Use the order set not very useful
Because when we have many categories and subcategories , finding the right number for order is not so easy!

Forum:

I think it's better show all categories and subcategories to select categories when creating a topic
 on the categories page, there is a button to display more subcategories

**Comment by barisusakli** [comment]
How many categories are you trying to order? Setting the order of a category adjust everything else in the same level. So if you set the order of a category from 5 to 2 it will change the other categories orders so everything after 2 is pushed down.

>I think it's better show all categories and subcategories to select categories when creating a topic

We no longer do this as it becomes un-scalable when you have thousands of categories.  However you can achieve it if you increase the setting `Subcategories per page` in category settings and make it equal to the number of subcategories you have.

**Comment by barisusakli** [comment]
Forgot to mention, if you select a category with the category selector on the manage categories page, it will go down to that level and only display children of that category.

**Comment by roghaye-m** [comment]
Maybe the admin panel can be improved because when we limit the number of subcategories
When creating a new subcategory, we must use search to be able to change the order number.

Maybe having an option to locate the new subcategory (up or down) solves this problem
The new subcategory now falls under the previous ones

what do you think?

**Comment by barisusakli** [comment]
Yeah I think when a new subcategory is created it goes to the end of the children list, I think making it go to the top of the list is better UX, I'll make that change.

**Comment by roghaye-m** [comment]
yeah, thank you
