### ISSUE TITLE
Category search doesn't work in NodeJS 10.x

### ISSUE THREAD

**Issue by oplik0** [NodeBB/NodeBB#9307]
- **NodeBB version:** 1.16.2
- **NodeJS version:** 10.x
- **What you expected:**
Category search should work
- **What happened instead:**
Attempting to use it returns an error `childrenCids.flat() is not a function`

This is due to NodeJS 10.x not having `Array.prototype.flat()` - this function was added in NodeJS 11.0.0.
I'm not sure how much is a fix needed though - NodeJS 10.x is in maintenance mode and even that will end soon. I fixed the problem myself by just finally upgrading NodeJS. I'm reporting this mostly to help others who might run into this problem find why it's happening and what to do (upgrade NodeJS).

**Comment by oplik0** [comment]
That was fast :D

**Comment by barisusakli** [comment]
Yeah looks like .flat isnt available in 10.x
