### ISSUE TITLE
Both the article and the reply are not parsed, and the html tag is directly displayed on the page

### ISSUE THREAD

**Issue by hjdo** [NodeBB/NodeBB#9330]
- **NodeBB version:**  v1.16.2
- **NodeBB git hash:** 023e4cfcee208a0bae121a6e343a8c53009fd090
- **NodeJS version:** v14.15.1

- **Installed NodeBB Plugins:** 
Active plugins:
        * nodebb-plugin-adsense (not installed, enabled)
        * nodebb-plugin-beep@0.4.6 (installed, enabled)
        * nodebb-plugin-browsing-users@1.1.2 (installed, enabled)
        * nodebb-plugin-cards2@0.2.6 (installed, enabled)
        * nodebb-plugin-category-notifications@3.0.3 (installed, enabled)
        * nodebb-plugin-code-button@0.0.7 (installed, enabled)
        * nodebb-plugin-composer-default@6.5.5 (installed, enabled)
        * nodebb-plugin-custom-pages@1.3.1 (installed, enabled)
        * nodebb-plugin-dbsearch@4.1.2 (installed, enabled)
        * nodebb-plugin-desktop-notifications@0.3.3 (installed, enabled)
        * nodebb-plugin-embed@3.0.19 (installed, enabled)
        * nodebb-plugin-emoji@3.5.0 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
        * nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
        * nodebb-plugin-google-analytics@0.5.11 (installed, enabled)
        * nodebb-plugin-hidden-content (not installed, enabled)
        * nodebb-plugin-iobroker-colors@0.10.25 (installed, enabled)
        * nodebb-plugin-leaderboard@2.1.2 (installed, enabled)
        * nodebb-plugin-markdown@8.12.4 (installed, enabled)
        * nodebb-plugin-mentions@2.13.6 (installed, enabled)
        * nodebb-plugin-newsletter@0.9.2 (installed, enabled)
        * nodebb-plugin-night-mode@1.0.7 (installed, enabled)
        * nodebb-plugin-ns-likes@2.0.0 (installed, enabled)
        * nodebb-plugin-ns-spoiler@7.2.1 (installed, enabled)
        * nodebb-plugin-nsfw@1.2.0 (installed, enabled)
        * nodebb-plugin-poll@1.1.5 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.8.6 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.15 (installed, enabled)
        * nodebb-plugin-registration-blacklist@0.1.7 (installed, enabled)
        * nodebb-plugin-registration-notification@1.2.5 (installed, enabled)
        * nodebb-plugin-rss (not installed, enabled)
        * nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
        * nodebb-plugin-spam-be-gone@0.7.7 (installed, disabled)
        * nodebb-plugin-sso-facebook@3.5.2 (installed, disabled)
        * nodebb-plugin-sso-google@2.4.2 (installed, disabled)
        * nodebb-plugin-telegram-notifications (not installed, enabled)
        * nodebb-plugin-tenor-gif@1.2.5 (installed, enabled)
        * nodebb-plugin-topic-noindex@1.0.2 (installed, enabled)
        * nodebb-plugin-user-invitations@0.6.0 (installed, enabled)
        * nodebb-plugin-write-api@5.8.5 (installed, enabled)
        * nodebb-rewards-essentials@0.1.4 (installed, enabled)
        * nodebb-theme-lavender@5.0.17 (installed, disabled)
        * nodebb-theme-oxide@6.0.6 (installed, disabled)
        * nodebb-theme-persona@10.3.19 (installed, enabled)
        * nodebb-theme-slick@1.3.8 (installed, disabled)
        * nodebb-theme-vanilla@11.3.10 (installed, disabled)
        * nodebb-widget-discord-embed@1.0.0 (installed, enabled)
        * nodebb-widget-essentials@5.0.2 (installed, enabled)
- **Database type:** mongo
- **Database version:** v4.0.21

- **Exact steps to cause this issue:**

![image](https://user-images.githubusercontent.com/12838659/109302728-a5e94600-7874-11eb-8640-05804dd8bc6b.png)
![image](https://user-images.githubusercontent.com/12838659/109303866-573cab80-7876-11eb-9d17-9e2e6ea96362.png)

This is just a reply, and the same is true for publishing articles. Disabling all plug-ins does not work. It should not be a problem with plug-ins. Please help.

**Comment by julianlam** [comment]
What is an "article"? This sounds like a plugin issue.

**Comment by hjdo** [comment]
@julianlam Is the topic. 
I tried to disable all the plug-ins and then redeploy them to boot, but nothing changed.

**Comment by gasoved** [comment]
I guess you're trying to author html directly in the editor? Since it's a markdown editor (I see that you're using the default composer), it doesn't support html tags. They will be transformed into html entities, and will shown as plain text.

![image](https://user-images.githubusercontent.com/1526638/109307109-31e97680-7851-11eb-869f-3c358508ee00.png)

**Comment by hjdo** [comment]
@gasoved No, I only input "PPPP" in the editor, but submitting, it will display "<p>PPPP</P>"

**Comment by julianlam** [comment]
@hjdo please provide the output of `./nodebb plugins` and `git rev-parse HEAD` after having disabled all of your extra plugins.

You should only need composer-default and markdown enabled.

**Comment by hjdo** [comment]
Active plugins:
        * nodebb-plugin-adsense (not installed, enabled)
        * nodebb-plugin-beep@0.4.6 (installed, disabled)
        * nodebb-plugin-browsing-users@1.1.2 (installed, disabled)
        * nodebb-plugin-cards2@0.2.6 (installed, disabled)
        * nodebb-plugin-category-notifications@3.0.3 (installed, disabled)
        * nodebb-plugin-code-button@0.0.7 (installed, disabled)
        * nodebb-plugin-composer-default@6.5.5 (installed, enabled)
        * nodebb-plugin-custom-pages@1.3.1 (installed, disabled)
        * nodebb-plugin-dbsearch@4.1.2 (installed, disabled)
        * nodebb-plugin-desktop-notifications@0.3.3 (installed, disabled)
        * nodebb-plugin-embed@3.0.19 (installed, disabled)
        * nodebb-plugin-emoji@3.5.0 (installed, disabled)
        * nodebb-plugin-emoji-android@2.0.0 (installed, disabled)
        * nodebb-plugin-extended-markdown@1.5.0 (installed, disabled)
        * nodebb-plugin-google-analytics@0.5.11 (installed, disabled)
        * nodebb-plugin-hidden-content (not installed, enabled)
        * nodebb-plugin-iobroker-colors@0.10.25 (installed, disabled)
        * nodebb-plugin-leaderboard@2.1.2 (installed, disabled)
        * nodebb-plugin-markdown@8.12.4 (installed, enabled)
        * nodebb-plugin-mentions@2.13.6 (installed, disabled)
        * nodebb-plugin-newsletter@0.9.2 (installed, disabled)
        * nodebb-plugin-night-mode@1.0.7 (installed, disabled)
        * nodebb-plugin-ns-likes@2.0.0 (installed, disabled)
        * nodebb-plugin-ns-spoiler@7.2.1 (installed, disabled)
        * nodebb-plugin-nsfw@1.2.0 (installed, disabled)
        * nodebb-plugin-poll@1.1.5 (installed, disabled)
        * nodebb-plugin-question-and-answer@0.8.6 (installed, disabled)
        * nodebb-plugin-recent-cards@2.0.15 (installed, disabled)
        * nodebb-plugin-registration-blacklist@0.1.7 (installed, disabled)
        * nodebb-plugin-registration-notification@1.2.5 (installed, disabled)
        * nodebb-plugin-rss (not installed, enabled)
        * nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
        * nodebb-plugin-sso-facebook@3.5.2 (installed, disabled)
        * nodebb-plugin-sso-google@2.4.2 (installed, disabled)
        * nodebb-plugin-telegram-notifications (not installed, enabled)
        * nodebb-plugin-tenor-gif@1.2.5 (installed, disabled)
        * nodebb-plugin-topic-noindex@1.0.2 (installed, disabled)
        * nodebb-plugin-user-invitations@0.6.0 (installed, disabled)
        * nodebb-plugin-write-api@5.8.5 (installed, disabled)
        * nodebb-rewards-essentials@0.1.4 (installed, disabled)
        * nodebb-theme-lavender@5.0.17 (installed, disabled)
        * nodebb-theme-oxide@6.0.6 (installed, disabled)
        * nodebb-theme-persona@10.3.19 (installed, enabled)
        * nodebb-theme-slick@1.3.8 (installed, disabled)
        * nodebb-theme-vanilla@11.3.10 (installed, disabled)
        * nodebb-widget-discord-embed@1.0.0 (installed, disabled)
        * nodebb-widget-essentials@5.0.2 (installed, disabled)

I tried, and now the display is normal. Next, I try each plug-in one by one, which is the problem of installing plug-ins myself. Thank you!

**Comment by julianlam** [comment]
Ok thank you, and good luck! :smile: 

When you discover the plugin causing issues, please report it on that plugin's issue page.
