### ISSUE TITLE
Write API v3 - be able to modify permissions of a category.

### ISSUE THREAD

**Issue by saesrpg** [NodeBB/NodeBB#9342]
We were looking into a way of doing the following with the new v3 API.

Create a group > create two categories (a public "root" category and a subcategory within it that is privately locked to the new group we create)

Found that we could do the group creation and category creation, however no way to modifying category permissions.

This would be a good feature to have without the need for people to create plugins.

**Comment by julianlam** [comment]
A good suggestion, thank you :smile: 

I will probably be something like

* `POST /api/v3/categories/privileges` &mdash; Accepts `{ privileges[, uid, groupName] }` in post body, any missing privileges are considered false/unchecked
* `PUT /api/v3/categories/privileges/:privilege` &mdash; Accepts `{ [uid, groupName] }` in post body, grants a single privilege
* `DELETE /api/v3/categories/privileges/:privilege` &mdash; Accepts `{ [uid, groupName] }` in post body, rescinds a single privilege

**Comment by pitaj** [comment]
Shouldn't post and put be switched?

**Comment by julianlam** [comment]
`POST` to update the entire set, and `PUT` to update, no?

I think technically it's `PATCH` to update, but we don't use patch requests in our API.

**Comment by pitaj** [comment]
POST is for adding something to a set (like posting a topic to the forum). PUT is for writing to the resource at a location.

If you `PUT data, loc`, you can `GET loc` to retrieve `data`, or `DELETE loc` to remove it. Of course this is just a guideline not a requirement.

**Comment by julianlam** [comment]
@pitaj Thanks for the clarification, `PUT` it is :+1:

**Comment by julianlam** [comment]
* https://docs.nodebb.org/api/write/#tag/categories/paths/~1categories~1{cid}~1privileges/get
* https://docs.nodebb.org/api/write/#tag/categories/paths/~1categories~1{cid}~1privileges~1{privilege}/put
* https://docs.nodebb.org/api/write/#tag/categories/paths/~1categories~1{cid}~1privileges~1{privilege}/delete
