### ISSUE TITLE
Request to add version to show in NodeBB

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [NodeBB/NodeBB#9347]
- **NodeBB version:**  1.16.2
- **What you expected:** I expect to have feature to show NodeBB version in HTML, like by adding it in footer or somewhere else.

I explained it more in: https://community.nodebb.org/topic/15411/how-to-print-nodebb-current-version-in-html

Thanks in advance

**Comment by julianlam** [comment]
We do not advertise the NodeBB version as it is a security concern. Attackers can use the value to target vulnerable NodeBB instances.

If you want to show it, append it via filter:api.config and use as necessary.
