### ISSUE TITLE
Cannot connect to MongoDB with SSL

### ISSUE THREAD

**Issue by Aloento** [NodeBB/NodeBB#9373]
- **NodeBB version:** 1.16.2
- **NodeBB git hash:** 023e4cfcee208a0bae121a6e343a8c53009fd090
- **NodeJS version:** v15.11.0.

- **Installed NodeBB Plugins:** No

- **Database type:** mongo
- **Database version:**  v4.4.4

- **Exact steps to cause this issue:**
```

    "mongo": {
        "host": "nodebb-shard-xx-xx.xxxxx.mongodb.net",
        "port": "27017",
        "username": "nodebb",
        "password": "nodebb",
        "database": "nodebb",
        "url": "mongodb://nodebb:#nodebb@nodebb-shard-xx-xx.xxxxx.mongodb.net:27017/nodebb?ssl=true&authSource=admin"
    },

```
`node app --setup`
- **What happened instead:**

```
Now configuring mongo database:
2021-03-12T17:06:56.884Z [18868] - warn: NodeBB Setup Aborted.
 MongoServerSelectionError: connection <monitor> to 168.63.xxx.xxx:27017 closed
    at Timeout._onTimeout (C:\Codes\NodeBB\node_modules\mongodb\lib\core\sdam\topology.js:438:30)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by Aloento** [comment]
I can use the command line "mongo" to connect the same MongoDB with this URL without any problem.

**Comment by barisusakli** [comment]
Did you try entering the url during `./nodebb setup` ?

**Comment by Aloento** [comment]
> Did you try entering the url during `./nodebb setup` ?

yes, but not working
