### ISSUE TITLE
Undefined /unread when using Node.js 14

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9387]
Hosted on Alpine Linux edge using Podman v3.0.1
**NodeBB v1.17.0-beta.3** is run with **Node.js v14.16.0**
NodeBB SHA:6e8b1bb9ad9301258b0b061705450255532a78ee
Built with Nobbic v0.5.0
It uses:
- nginx (docker.io/nginx:alpine)
  with NGINX_VERSION=1.19.7 NJS_VERSION=0.5.1
- redis (docker.io/redis:6.2.1-alpine)
  with REDIS_VERSION=6.2.1
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.3)
  with YARN_VERSION=1.22.5 NODEBB_VERSION=1.17.0-beta.3 NODE_VERSION=14.16.0
- postgres (docker.io/postgres:alpine)
  with PG_VERSION=13.2

How to reproduce?
Go to /unread
Click New topic
Error shows when category is being selected (Select Category in the Composer window) 

Issue:
Browser console returns:
`GET http://server_ip:8080/undefined 404 (Not Found)
:8080/unread:1`

What is expected?
No console errors when using Node.js 14.

**Comment by pitaj** [comment]
I wasn't able to reproduce this at https://community.nodebb.org/unread

What is your `url` in config.json?

**Comment by barisusakli** [comment]
Please include active theme and version as well.

**Comment by nhlpl** [comment]
Opera 75.0.3969.35

nodebb-theme-lavender 5.2.1
nodebb-theme-persona 11.0.3

config.json
{
    "url": "http://server_ip:8080",
    "secret": "hidden_secet",
    "database": "postgres",
    "port": [
        4567,
        4568,
        4569
    ],
    "postgres": {
        "host": "localhost",
        "port": "5432",
        "username": "postgres",
        "password": "hidden_pass",
        "database": "hidden_db",
        "ssl": false
    }

**Comment by nhlpl** [comment]
Tried Chrome 89.0.4389.82 and I can see reported error. It comes from a cluster config so please close issue if you think it works as it should.
