### ISSUE TITLE
Unable to join mod group by admin

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9389]
Hosted on Alpine Linux edge using Podman v3.0.1
**NodeBB v1.17.0-beta.3** is run with **Node.js v14.16.0**
NodeBB SHA:6e8b1bb9ad9301258b0b061705450255532a78ee
Built with Nobbic v0.5.0
It uses:
- nginx (docker.io/nginx:alpine)
  with NGINX_VERSION=1.19.7 NJS_VERSION=0.5.1
- redis (docker.io/redis:6.2.1-alpine)
  with REDIS_VERSION=6.2.1
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.3)
  with YARN_VERSION=1.22.5 NODEBB_VERSION=1.17.0-beta.3 NODE_VERSION=14.16.0
- postgres (docker.io/postgres:alpine)
  with PG_VERSION=13.2

How to reproduce?
Open /groups/global-moderators
Member List > Add Member > type superadmin name and select/click

Issue?
Browser returns:
```
PUT http://server_ip:8080/api/v3/groups/global-moderators/membership/1 400 (Bad Request)
send @ jquery.js:10109
ajax @ jquery.js:9690
r @ api.js:16
async function (async)
r @ api.js:14
(anonymous) @ api.js:42
n @ api.js:41
t.put @ api.js:68
(anonymous) @ memberlist.js:87
s @ memberlist.js:87
callback @ memberlist.js:32
w @ undefined:1890
(anonymous) @ undefined:1187
dispatch @ jquery.js:5430
g.handle @ jquery.js:5234
```

What is expected?
Adding admin user to the mod group being possible on the frontend.

**Comment by pitaj** [comment]
Please use triple ticks for blocks of code / error stack traces

    ```
    like this
    ```

**Comment by nhlpl** [comment]
It works fine when using invite/bulk invite.
