### ISSUE TITLE
Master branch out of date

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9392]
Fresh NodeBB install, default plug-ins. I have forced 'master' tag. It downloads outdated code. GitHub hash returns a commit added 10 days ago.

Fixing it should solve some issues reported on the NodeBB Community Forums.

Issue?
67bb63bd0979ea68a100dd59d457612313524884 under master branch.

What is expected?
Latest code when calling 'master'.

Hosted on Alpine Linux edge using Podman v3.0.1
NodeBB vmaster is run with Node.js v14.16.0
NodeBB SHA:67bb63bd0979ea68a100dd59d457612313524884
Built with Nobbic v0.5.0
It uses:
- nodebb (localhost/nodebb:14.16.0-master)
  with YARN_VERSION=1.22.5 NODE_VERSION=14.16.0 NODEBB_VERSION=master
- redis (docker.io/redis:6.2.1-alpine)
  with REDIS_VERSION=6.2.1
- nginx (docker.io/nginx:alpine)
  with NGINX_VERSION=1.19.8 NJS_VERSION=0.5.2

**Comment by julianlam** [comment]
@nhlpl If you're downloading from the master branch, how can it be 10 days old? The latest [commits listed here](https://github.com/NodeBB/NodeBB/commits/) are from today, and if you are not retrieving the latest commits, it would not be a fault of the NodeBB codebase...

**Comment by oplik0** [comment]
Did you do a `git fetch` before changing to the branch?
The way to ensure you have the newest commit as head is to first make sure you download it (`git fetch`) then make git actually use it - you can merge the branch but the way that will definitely work is `git reset`. Here, more specifically, you can do `git reset --hard origin/master`. This **will** discard all changes to tracked files that aren't in current `master` branch, so keep that in mind if you were modifying something.
