### ISSUE TITLE
Node.js 10 requirement in package.json

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9393]
Please update package.json and replace node 10 with node 12. It will help automating NodeBB installs for those who are trying to do it using scripts and not manually.

https://github.com/NodeBB/NodeBB/blob/master/install/package.json#L165
```
    "engines": {
        "node": ">=10"
```

**Comment by pitaj** [comment]
We do still support node 10 though.

**Comment by barisusakli** [comment]
Actually we are dropping support for node 10 with 1.17.0. So we can update it in package.json and gh actions

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/8d3ec2348391400a2d991954affd0f1ff5f0b7a6
