### ISSUE TITLE
Raw html when using Post queued for approval link

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9410]
Issue?
Raw HTML in the Content field under Post Queue.
![postq](https://user-images.githubusercontent.com/11160550/111877125-0fef9980-89a2-11eb-9b01-69da627e68ca.png)

How to reproduce?
Enable Post Queue
Add new post by unprivileged user
Check Post Queue
Use link near to 'Topic' (Topic tet on screenshot)
Use 'Post queued for approval' link to go back
F5
F5
F5
F5

What is expected?
Post Queue content correctly rendered.

Hosted on Alpine Linux edge using Podman v3.0.1
NodeBB v1.17.0-beta.4 is run with Node.js v14.16.0
NodeBB SHA:91992240bd1b7abd235a9f009e5eecf82d688a83
Built with Nobbic v0.5.0
It uses:
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.4)
  with YARN_VERSION=1.22.5 NODE_VERSION=14.16.0 NODEBB_VERSION=1.17.0-beta.4
- redis (docker.io/redis:6.2.1-alpine)
  with REDIS_VERSION=6.2.1
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.2 NGINX_VERSION=1.19.8

**Comment by barisusakli** [comment]
Regression from https://github.com/NodeBB/NodeBB/commit/3f35fd335d56da51f573e8f236e9e5bad8bafaf2
