### ISSUE TITLE
category filter on flags page doesn't update after selecting and closing

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9411]
Issue?
Unable to select Category under Home > Flags. It requires using Apply filters button.
![flagscat](https://user-images.githubusercontent.com/11160550/111877649-7d9cc500-89a4-11eb-8af3-c8ceafc3c194.png)

How to reproduce?
Go to /flags (Moderator Tools > Flagged Content)
Try to use Filter Options > Category
It works only after using Apply filters button.

nodebb-theme-persona
11.0.6

What is expected?
Selecting Category to work without using Apply filters button.

Hosted on Alpine Linux edge using Podman v3.0.1
NodeBB v1.17.0-beta.4 is run with Node.js v14.16.0
NodeBB SHA:91992240bd1b7abd235a9f009e5eecf82d688a83
Built with Nobbic v0.5.0
It uses:
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.4)
  with YARN_VERSION=1.22.5 NODE_VERSION=14.16.0 NODEBB_VERSION=1.17.0-beta.4
- redis (docker.io/redis:6.2.1-alpine)
  with REDIS_VERSION=6.2.1
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.2 NGINX_VERSION=1.19.8

**Comment by julianlam** [comment]
Like the other filters in that sidebar, you will need to press the submission button to apply the filters.

**Comment by barisusakli** [comment]
Julian is correct, you need to select the categories from the dropdown and then hit apply. Although there is a small issue in the dropdown which I will fix.
