### ISSUE TITLE
Hidden Topic Events when posts sorted by Most Votes

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9413]
Issue?
Topic Events not displayed when posts are sorted by Most Votes.

How to reproduce?
Use Topic Tools to create some topic events (pinned/unlocked, deleted/restored, locked/unlocked topic).
Make use of 'Sort by' icon to change posts listing.

What is expected?
It works for both Oldest to Newest and Newest to Oldest so it would be nice to enable it for Most Votes.

Hosted on Alpine Linux edge using Podman v3.0.1
NodeBB v1.17.0-beta.4 is run with Node.js v14.16.0
NodeBB SHA:91992240bd1b7abd235a9f009e5eecf82d688a83
Built with Nobbic v0.5.0
It uses:
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.4)
  with YARN_VERSION=1.22.5 NODE_VERSION=14.16.0 NODEBB_VERSION=1.17.0-beta.4
- redis (docker.io/redis:6.2.1-alpine)
  with REDIS_VERSION=6.2.1
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.2 NGINX_VERSION=1.19.8

**Comment by julianlam** [comment]
Topic events are hidden when sorted by most votes because events are time-ordered and do not make sense in that particular sort strategy.
