### ISSUE TITLE
Default favicon.ico not found

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9462]
Issue?
Default favicon not found after upgrading from NodeBB 1.17.0-beta.4 to 1.17.0-beta.5.

How to reproduce?
Install NodeBB 1.17.0-beta.4 and upgrade it to 1.17.0-beta.5.
Open any topic/post to get error.
/assets/uploads/system/favicon.ico?v=8dp9m91e5g4 path returns 'Not Found'.

What is expected?
Default favicon installed and served by nginx.

Screenshot:
![favupgr](https://user-images.githubusercontent.com/11160550/113656584-7a8c1f00-969c-11eb-937b-d4afb895c833.png)

Hosted on Alpine Linux edge using Podman v3.1.0
Running on a machine with 4 CPU(s) and 7962 MB RAM
NodeBB v1.17.0-beta.5 is run with Node.js v14.16.0 on a single process (port 4567)
NodeBB SHA:42c4f963f91669784366b2dc61a0493b8f70d571
Built with Nobbic v0.5.0
It uses:
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.3 NGINX_VERSION=1.19.9
- redis (docker.io/redis:alpine)
  with REDIS_VERSION=6.2.1
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.5)
  with NODE_VERSION=14.16.0 YARN_VERSION=1.22.5 NODEBB_VERSION=1.17.0-beta.5

**Comment by barisusakli** [comment]
Could be docker related, the upgrade script should place the favicon at `/assets/uploads/system/favicon.ico` is the file in that folder?

**Comment by nhlpl** [comment]
Parsing upgrade scripts executed only Add "schedule" to default privileges of admins and gmods for existing categories and ended with OK and Schema update complete! No word about favicon.

Favicon can be opened via /favicon.ico.

You're right when it comes to how Docker/Podman handle files so please close this issue.

**Comment by nhlpl** [comment]
Tested it again on a fresh install. It works just like upgrade. File not found.

Good news. Uploading file (/admin/settings/general#favicon) creates folder and file here /assets/uploads/system/favicon.ico and it works fine. No more favicon errors in the browser's console.

**Comment by barisusakli** [comment]
I think we should fix it for new installs. On a new install it should copy the favicon just like the upgrade script.
