### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9463]
Issue?
```
Uncaught TypeError: Cannot read property 'classList' of null
    at s (sockets.js:187)
```

How to reproduce?
Go to /admin and restart NodeBB.

What is expected?
No extra errors compared to NodeBB 1.16.2.

Screenshot:
![classlist](https://user-images.githubusercontent.com/11160550/113660644-df4b7780-96a4-11eb-9e72-b0bddb265d07.png)

Hosted on Alpine Linux edge using Podman v3.1.0
Running on a machine with 4 CPU(s) and 7962 MB RAM
NodeBB v1.17.0-beta.5 is run with Node.js v14.16.0 on a single process (port 4567)
NodeBB SHA:42c4f963f91669784366b2dc61a0493b8f70d571
Built with Nobbic v0.5.0
It uses:
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.3 NGINX_VERSION=1.19.9
- redis (docker.io/redis:alpine)
  with REDIS_VERSION=6.2.1
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.5)
  with NODE_VERSION=14.16.0 YARN_VERSION=1.22.5 NODEBB_VERSION=1.17.0-beta.5

**Comment by barisusakli** [comment]
already fixed in https://github.com/NodeBB/NodeBB/commit/cb53a64cde69e5b585abed4d742b2462533f89bc
