### ISSUE TITLE
meta.rooms.leaveCurrent errors in the Maintenance Mode

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9466]
Issue?

Errors like this in the Logs (/admin/advanced/logs).
```
2021-04-06T17:19:06.331Z [4567/349] - [31merror[39m: meta.rooms.leaveCurrent
Error: NodeBB is currently undergoing maintenance. Please come back another time.
    at checkMaintenance (/app/nodebb/src/socket.io/index.js:187:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async onMessage (/app/nodebb/src/socket.io/index.js:145:3)
```
All NodeBB versions from 1.16.2 to 1.17.0-beta.5.

How to reproduce?

Enable Maintenance Mode (/admin/settings/advanced#maintenance-mode).
Browse and use NodeBB using superadmin account as usual (create topics/replies).
Check Logs (/admin/advanced/logs) for errors.

What is expected?

No more "meta.rooms.leaveCurrent" errors in the logs.

Tested on QEMU/KVM:

Hosted on Alpine Linux edge using Podman v3.1.0
Running on a machine with 4 CPU(s) and 7962 MB RAM
NodeBB v1.17.0-beta.5 is run with Node.js v14.16.0 on a single process (port 4567)
NodeBB SHA:42c4f963f91669784366b2dc61a0493b8f70d571
Built with Nobbic v0.5.0
It uses:
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.3 NGINX_VERSION=1.19.9
- redis (docker.io/redis:alpine)
  with REDIS_VERSION=6.2.1
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.5)
  with NODE_VERSION=14.16.0 YARN_VERSION=1.22.5 NODEBB_VERSION=1.17.0-beta.5

**Comment by barisusakli** [comment]
Can't reproduce, browsing as admin account doesn't produce maintenance mode messages.

**Comment by nhlpl** [comment]
Guest user or non-privileged needs to use /login route. It produces a log entry in /logs on every single try.

I don't have /assets/src/client/503.js file.
![503js](https://user-images.githubusercontent.com/11160550/113821438-60c20900-977c-11eb-955f-663a1aa6701a.png)
