### ISSUE TITLE
Searchable tags used in scheduled topics

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9469]
How to reproduce?
Schedule a topic with tags using your superadmin account.
Go to /tags and find newly created tags by both superadmin and non-privileged user or guest.

Issue?
Tags used in scheduled topics visible and searchable for all before given startdate.

What is expected?
Tags used in scheduled content to be hidden just like scheduled topic itself.

qemu/kvm vps:
Hosted on Alpine Linux edge using Podman v3.1.0
Running on a machine with 4 CPU(s) and 7962 MB RAM
NodeBB v1.17.0-beta.5 is run with Node.js v14.16.0 on a single process (port 4567)
NodeBB SHA:42c4f963f91669784366b2dc61a0493b8f70d571
Built with Nobbic v0.5.0
It uses:
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.3 NGINX_VERSION=1.19.9
- redis (docker.io/redis:alpine)
  with REDIS_VERSION=6.2.1
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.5)
  with NODE_VERSION=14.16.0 YARN_VERSION=1.22.5 NODEBB_VERSION=1.17.0-beta.5

**Comment by gasoved** [comment]
Agreed with this, but requires a drastic change to prevent a small information leak.
