### ISSUE TITLE
Scheduled topic last edited by timestamp

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9470]
How to reproduce?
Create a new topic and schedule it to be posted in future.
Edit topic by changing only scheduled date.
Repeat editing for many times.
Check results and compare it with a normal topic with no extra schedule data.

Issue?
Wrong "last edited by" information. Future time displayed.
Post Edit History window locked only to a few revisions. Restore this revision and Delete this revision buttons disabled.

What is expected?
Edit history to be compatible with topics scheduling.

Screenshot:
![edittip](https://user-images.githubusercontent.com/11160550/113869299-d778f980-97b0-11eb-9511-cd9628e7c423.png)

qemu/kvm vps:
Hosted on Alpine Linux edge using Podman v3.1.0
Running on a machine with 4 CPU(s) and 7962 MB RAM
NodeBB v1.17.0-beta.5 is run with Node.js v14.16.0 on a single process (port 4567)
NodeBB SHA:42c4f963f91669784366b2dc61a0493b8f70d571
Built with Nobbic v0.5.0
It uses:
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.3 NGINX_VERSION=1.19.9
- redis (docker.io/redis:alpine)
  with REDIS_VERSION=6.2.1
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.5)
  with NODE_VERSION=14.16.0 YARN_VERSION=1.22.5 NODEBB_VERSION=1.17.0-beta.5

**Comment by gasoved** [comment]
I couldn't reproduce this actually.

**Comment by nhlpl** [comment]
Similar issue when it comes to timestap used for replies vs. edited opening post.
![schreply](https://user-images.githubusercontent.com/11160550/114066319-e38db580-989b-11eb-8c9b-75ede759cf25.png)
