### ISSUE TITLE
Scheduled topic reply unhides it

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/NodeBB#9475]
How to reproduce?
Schedule a new topic to be published in the near future.
Add a reply to the scheduled topic before publishing it.

Issue?
A reply to the scheduled topic unhides it and partly shows a reply.

What is expected?
Replies to be treated just like opening post (hidden).

Screenshot:
![schunh](https://user-images.githubusercontent.com/11160550/114065164-a543c680-989a-11eb-9aa9-e88578b6ac87.png)

qemu/kvm vps:
Hosted on Alpine Linux edge using Podman v3.1.0
Running on a machine with 4 CPU(s) and 7962 MB RAM
NodeBB v1.17.0-beta.5 is run with Node.js v14.16.0 on a single process (port 4567)
NodeBB SHA:42c4f963f91669784366b2dc61a0493b8f70d571
Built with Nobbic v0.5.0
It uses:
- nginx (docker.io/nginx:alpine)
  with NJS_VERSION=0.5.3 NGINX_VERSION=1.19.9
- redis (docker.io/redis:alpine)
  with REDIS_VERSION=6.2.1
- nodebb (localhost/nodebb:14.16.0-1.17.0-beta.5)
  with NODE_VERSION=14.16.0 YARN_VERSION=1.22.5 NODEBB_VERSION=1.17.0-beta.5

**Comment by gasoved** [comment]
I couldn't reproduce it as you've described, but editing the main post caused that. Thanks, PR is coming.
