### ISSUE TITLE
Login didn't work in latest beta version 

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#9480]
version:  1.17.0-beta.5
  Node ver: v12.14.1
  git hash: c66032d169d3d925a2d77796b2dd842d681d5bb0

  database: mongo
        version: 4.2.3
        engine:  wiredTiger

- **Exact steps to cause this issue:**

	1. First I updated to this version 
	2. Then, when I  went to users profile get this error:

Error!

/api/user/username
Cannot read property 'length' of undefined

It also does not login

**Comment by barisusakli** [comment]
Can you post the error from logs/output.log

**Comment by roghaye-m** [comment]
> Can you post the error from 

![20210411_024249](https://user-images.githubusercontent.com/37838903/114285875-b265de80-9a6f-11eb-9932-b674b637405e.jpg)

It's empty!!!

**Comment by barisusakli** [comment]
Not sure why your output.log is empty. How are you starting nodebb? Maybe try `./nodebb dev` in the nodebb folder and then try to login and see if you get a more useful stack trace.

**Comment by roghaye-m** [comment]
We removed all the plugins and installed them from the beginning.  And then we built it, it was fixed, but the log is still empty!

**Comment by pitaj** [comment]
That's not what we asked you to do. Try stopping and then running with `./nodebb dev`

**Comment by TomMorant** [comment]
Brother, I do the same in k8s. After clicking install, I enter the nodebb installation environment. After the pod restarts, I stay on the nodebb startup page
![image](https://user-images.githubusercontent.com/40886065/114674488-dc522600-9d39-11eb-8005-8a2bb3b88ff3.png)
![image](https://user-images.githubusercontent.com/40886065/114674581-f4c24080-9d39-11eb-85d8-dc02d5859e1b.png)
![image](https://user-images.githubusercontent.com/40886065/114674658-0c99c480-9d3a-11eb-915c-10ede9324475.png)
Now that is the case, we can't go into the next step at all

**Comment by pitaj** [comment]
@TomMorant that doesn't look like the same issue at all. For technical assistance, please stay a topic at community.nodebb.org

**Comment by TomMorant** [comment]
> @TomMorant看起来根本不一样。要获得技术帮助，请在community.nodebb.org上保持话题。

All right, let me bring up issues again

**Comment by barisusakli** [comment]
This is most likely an issue with outdated sso plugins see here for the fix https://github.com/julianlam/nodebb-plugin-sso-facebook/commit/cfd47dc2a50103642a829b182bab8af1c62169f8
