### ISSUE TITLE
Ability to chat only with admins

### ISSUE THREAD

**Issue by roghaye-m** [NodeBB/NodeBB#9486]
What do you think about the possibility of chatting only with the admin?
I think this is a very useful feature
There are now only two options: enable chat and disable it.
If we select the disabled mode, there may be security issues that the user only needs to inform us privately, but because chat is disabled, this will not be possible.

**Comment by Bitnut** [comment]
May this implementation could help:

[only chat with admin](https://gist.github.com/Bitnut/046ccd66cf27958e34dbca31f5729566#file-nodebb-chat-only-with-admin-js)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/12092
