### ISSUE TITLE
Feature request: reject posts with message

### ISSUE THREAD

**Issue by mzdluo123** [NodeBB/NodeBB#9506]
Hi
Post queue is a good feature, but it can’t tell author the reason why it was rejected, it also result in lost articles.
The author have no chance to edit the rejected posts.

 Thank you!

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/146484060-7ffe8d24-697b-4e6f-b209-081ca4db42d5.png)
![image](https://user-images.githubusercontent.com/2583394/146484076-836365ac-878a-4b49-9256-7ed863ebe906.png)
![image](https://user-images.githubusercontent.com/2583394/146484123-76ebfc50-6682-48b4-a47f-81d3b76d3aba.png)
