### ISSUE TITLE
Integration with shields.io

### ISSUE THREAD

**Issue by z3dev** [NodeBB/NodeBB#9526]
This is a great service for providing badges in documentation. One of the badge types is 'Social' sites. It would be cool if NodeBB has a pre-built badges.

https://shields.io/category/chat

OR 

https://shields.io/category/social

For example, we want to add a badge to our NodeBB site for the JSCAD User Group; https://openjscad.nodebb.com/. It would be cool to have this badge fully supported.

**Comment by julianlam** [comment]
Hm.. sure, but NodeBB isn't actually a standalone site, but the software that runs multiple sites (e.g. JSCAD UG)... how would you use a "NodeBB" badge? It wouldn't say openjscad or anything, but "NodeBB", wouldn't it?

**Comment by z3dev** [comment]
I don’t know the details but some like a ‘NODEBB’ button, which can be associated with
- URL
- Some query into NodeBB server for # of users, # of topics, # of posts, etc.
