### ISSUE TITLE
nodebb authentication from my application (or vice versa)

### ISSUE THREAD

**Issue by ashishgupta2** [NodeBB/NodeBB#953]
Hi all, I developed a CMS application which has authentication system and useing nodebb for forum needs.Currently its running fine, issue is that user need to login twice once in forum and then in my application. My application's username and password are maintained in database. Either of the solution will make my life easier.
1. Is it possible to authenticate the user in nodebb if he/she is logged in my application, I can write a api which can provide username and hashed password to nodebb along with profile details.
2. If the user is logged in nodebb,is there an API which spites out the username and hashed password which I can validate in my application.

If this is already addressed and there is documentation, I would appreciate if you could please direct me.

Regards,
Ashish

**Comment by joncodo** [comment]
This comment ` The recommended way to enable shared login is to use identical single sign-on systems for both applications. For example, NodeBB has plugins for Facebook, Twitter, and Google login.`

Is pretty vague. is this documented somewhere to help me get started?
