### ISSUE TITLE
Block composer during upload/resize of image

### ISSUE THREAD

**Issue by mberglundmx** [NodeBB/NodeBB#9587]
# Feature request

It would be great if the composer disabled the post/submit button during the upload and resize of an image. Currently it's possible to submit a post with the %-counter still visible, and the image will be lost from the post

Either the upload/resize could be done in the background, and the correct markdown added to the composer immediately (I prefer this option) or disable the submit button as the title suggests.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer/uploads.js#L216

The submit button is already disabled during upload, any reproduction steps?

**Comment by barisusakli** [comment]
One way I can reproduce this is to upload an image that is not allowed for example something too wide. Then an error message is displayed and the submit button is reenabled. And the text area has `![0_1630114880175_AyYjeJi.jpg](Uploading 100%)` leftover.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/commit/b1a9dba20fa144bea1bdaeabad0544b94da4b5ac
