### ISSUE TITLE
Translate placeholder errors

### ISSUE THREAD

**Issue by Karlatemp** [NodeBB/NodeBB#9596]
https://github.com/NodeBB/NodeBB/blob/fac0bcbd3558021cab3fc543cd14dc8d97a9a30b/public/language/zh-CN/topic.json#L36

It should be
```
"moved-from": "移自%1版",
```

In `zh-CN`, it will render `Moved from 1%` (Translated, origin: `移自1%版`).

The expected result is `Moved from ****` (`移自****版`)

Also I searched the keyword `1%`, it is the result

![N2W](https://user-images.githubusercontent.com/30070303/120892224-cf69f880-c63f-11eb-84c8-09be2942a067.png)

**Comment by pitaj** [comment]
Yeah those should all be `%1` instead of `1%`

**Comment by julianlam** [comment]
Bit harder than expected to find-and-replace, since `ar` is actually fine for it to be `1%` as it reads RTL.

**Comment by julianlam** [comment]
The strings have also been updated on Transifex

**Comment by pitaj** [comment]
> since `ar` is actually fine for it to be `1%` as it reads RTL.

I don't think that's true. The translator has no concept of RTL or LTR, it just does string replacement.
