### ISSUE TITLE
Removal of profile picture (or account deletion) should purge uploaded avatars from disk

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#9606]
Retaining the avatar is likely a GDPR violation, so let's remove them from disk during these two events.

Can we add tests for this too?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/a26389762799a7dc9be8daba9279dd2c46f6c84c

Looks like this needs to modified to delete all images that start with `<uid>-profile` and also called on removal of profile pic.
