### ISSUE TITLE
Unable to update a post using write api

### ISSUE THREAD

**Issue by spin0us** [NodeBB/NodeBB#9612]
- **NodeBB version:** 1.17.0
- **NodeBB git hash:** 6b4ef46eadce177d51b609bf75df8acdaab61f0a
- **NodeJS version:** v14.17.0
- **Installed NodeBB Plugins:** 
```
Active plugins:
        * nodebb-plugin-alignment@0.3.0 (installed, enabled)
        * nodebb-plugin-composer-default@6.5.27 (installed, enabled)
        * nodebb-plugin-customize@2.0.0 (installed, enabled)
        * nodebb-plugin-dbsearch@4.2.0 (installed, enabled)
        * nodebb-plugin-emoji@3.5.3 (installed, enabled)
        * nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
        * nodebb-plugin-imgbed@1.1.6 (installed, enabled)
        * nodebb-plugin-markdown@8.12.7 (installed, enabled)
        * nodebb-plugin-mentions@2.13.9 (installed, enabled)
        * nodebb-plugin-ns-likes@2.0.0 (installed, enabled)
        * nodebb-plugin-osm-map@0.0.11 (installed, enabled)
        * nodebb-plugin-spam-be-gone@0.7.9 (installed, disabled)
        * nodebb-plugin-youtube-embed@0.6.9 (installed, enabled)
        * nodebb-rewards-essentials@0.1.4 (installed, enabled)
        * nodebb-theme-lavender@5.2.1 (installed, disabled)
        * nodebb-theme-persona@11.0.17 (installed, enabled)
        * nodebb-theme-slick@1.4.6 (installed, disabled)
        * nodebb-theme-vanilla@12.0.7 (installed, disabled)
        * nodebb-widget-essentials@5.0.3 (installed, enabled)
```
- **Database type:** mongo
- **Database version:** 
```
db version v4.4.6
Build Info: {
    "version": "4.4.6",
    "gitVersion": "72e66213c2c3eab37d9358d5e78ad7f5c1d0d0d7",
    "openSSLVersion": "OpenSSL 1.1.1d  10 Sep 2019",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "debian10",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
```
- **Exact steps to cause this issue:**
1. I generate a token for uid 1 using `/admin/settings/api`
2. I try to update an existing post using write api `/api/v3/posts/1241` using `Authorization: Bearer 5de02768-3224xxxxxxxxxxxxx` in the header
This call was made by a "BOT" so there's no open session anywhere.
- **What you expected:**
An update of the post content
- **What happened instead:**
I got a `Forbidden` in write api response and a `invalid csrf token` in the log

**Comment by julianlam** [comment]
Can you try making the same call using curl please?

Just to eliminate variables and also as a debugging step for me.

**Comment by spin0us** [comment]
> Can you try making the same call using curl please?
> 
> Just to eliminate variables and also as a debugging step for me.

I try it using php curl and postman (browser extension to consume rest api).
Is that enough or do I still need to test curl on the command line?

**Comment by spin0us** [comment]
Ok, I finally managed to do the update via my php script. But still impossible via the REST API extension. I applied the same settings though.
