### ISSUE TITLE
Icon Picker links to fontawesome page with newer version than Nodebb has

### ISSUE THREAD

**Issue by skeddles** [NodeBB/NodeBB#9617]
When you are picking an icon for a category or link, there is this blurb at the bottom:

![image](https://user-images.githubusercontent.com/2721332/122647615-f1a94f00-d0f2-11eb-8467-b97842b6d058.png)

To me this heavily implies you can get more icons by clicking that link. But if you go to that page and find an icon and put the name into the icon picker on nodebb, it doesn't work. You just get a blank icon. 

Turns out the list that is linked to is showing icons from FontAwesome5, where nodebb comes with fontawesome4. 

This is very confusing to new users.

**I suggest you do one of the following:**

1. At the very least, link to the proper set of icons in that list: https://fontawesome.com/v4.7/icons/ (and maybe change the wording so it doesn't sound like there's a bigger list of icons)

2. Upgrade nodebb to use the newer fontawesome (this would make it easier to find icons)

3. Make it so admins can easily choose which version of fontawesome to load via settings panel (i know you can upgrade it yourself by editing some server side files, but i dont want to / shouldn't have to do that)

**Comment by barisusakli** [comment]
I think the reason we are using 4.x is because of licensing. I updated the link to the 4.x icons.

**Comment by skeddles** [comment]
Thank you, that will at the very least be less confusing to new users.
