### ISSUE TITLE
System tags disappear when regular user edits their post

### ISSUE THREAD

**Issue by Jane-N** [NodeBB/NodeBB#9622]
- **NodeBB version:** 1.17.1

- **Exact steps to cause this issue:**

1. Create a tag whitelist for a category.
2. Add system tags in tag settings.
3. As a regular user create a topic in the same category and add some tags.
4. As a moderator or admin, add a system tag to the same topic.
5. As a regular user again, edit the topic.

- **What you expected:**

After the regular user has finished editing the topic, the system tag will still be there.

- **What happened instead:**

The system tag is removed.

**Comment by barisusakli** [comment]
What is the tag whitelist for the category and what are the system tags?

Right now editing a topic submits the entire list of tags so it should actually cause an error if it contains any system tags.
