### ISSUE TITLE
Category/Groups Icon Editing

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#9628]
When selecting an icon for either Category/Groups it comes up with the Select Icon modal which displays the FontAwesome icon set. In the modal you select the Icon and press the Select button to choose one. If you enter text in the modal textfield and just press the Select button, the value isn't saved.  

On our website we don't use FontAwesome and have our own Icon set that fits with the UI.  Until now we've used dev tools to set a value we need instead of using the Modal UI. As you can imagine this makes changing icons for the Marketing team more difficult than it should. Would it be possible to allow free text in the text field to set the icon name?

**Comment by barisusakli** [comment]
You  should be able to set any string in the input now and it will saved in the category icon field.
