### ISSUE TITLE
Allow themes to style widgets 

### ISSUE THREAD

**Issue by skeddles** [NodeBB/NodeBB#9643]
Feature request.

Right now if you want to style a widget, you have to do it through the admin panel. If you try to put the code in your theme's CSS, it get's overwritten by the widget. 

You should be able to bundle support for widgets in your theme, and not have to maintain CSS for your forum in multiple places.

**Comment by pitaj** [comment]
This should be possible. What exactly are you trying to accomplish and what have you tried?

**Comment by skeddles** [comment]
I was originally styling my forum using the the Appearence > CSS tab in the admin panel, and was able to style the whole site and the plugins (for example nodebb-plugin-recent-cards and nodebb-widget-ns-stats). 

I recently moved all my CSS from the admin panel to it's own theme, so I can edit it more easily and allow contributors. The site layout worked perfectly, but all the plugins reverted to their default styling. I had to remove the CSS code for the plugins from the theme, and put it back into the Appearance tab in order for them to work. 

I would wager that when compiling the CSS for the site, it combines in the widget CSS after your theme CSS, meaning anything you put in your theme gets overwritten. (though i dont know exactly how nodebb compiles css, this is just a guess).

**Comment by pitaj** [comment]
Can you provide an example of something that gets overridden?

**Comment by skeddles** [comment]
I can do another test if needed, but it seemed to me like 100% of the css from plugins was overwritten.

**Comment by pitaj** [comment]
I'm just asking for a specific set of code that you've seen not work, so I can reproduce the issue.

**Comment by barisusakli** [comment]
The order the plugins are loaded effects how the css is combined. So if the theme is loaded after the plugin it's css can get  overwritten. The order can be configured in the ACP. 
![image](https://user-images.githubusercontent.com/2583394/128564508-6af743fc-f845-4ef5-a636-0ff0ae54ea3b.png)
