### ISSUE TITLE
Question: Is this deprecation correct?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#9648]
In 1.17.1 I cant find any reference to the deprecation url and updateSetting function below in the codebase. (categoryTopicSort is the same underneath that section of code)

https://github.com/NodeBB/NodeBB/blob/f6c14d6b624038d0250f78d6581b970d64d35e28/src/socket.io/user.js#L151-L152

Looking at the handleSort function it uses /settings instead.

https://github.com/NodeBB/NodeBB/blob/902da5402918dbe99c5f298ce769b0b1994739b5/public/src/modules/sort.js#L23-L27

**Comment by julianlam** [comment]
[According to the API documentation](https://docs.nodebb.org/api/write/#tag/users/paths/~1users~1{uid}~1settings/put), you are correct, the deprecation notice is not

**Comment by julianlam** [comment]
However, [as of the original commit](https://github.com/NodeBB/NodeBB/commit/c26f2b6599d78b12ff0ec181da0db0493bb764c4), that route used to exist... looks like it was removed by me (!!) in https://github.com/NodeBB/NodeBB/commit/aa8faf58a0462515bb2ecc8cd6cf026eca680065

**Comment by julianlam** [comment]
Thank you! :smile:
