### ISSUE TITLE
Improving the mobile template to improve the user experience

### ISSUE THREAD

**Issue by loid345** [NodeBB/NodeBB#9653]
The nodebb desktop layout is almost perfect, but the mobile layout is inconvenient in terms of usability. I propose to refine the layout to improve the user interface and usability from mobile devices.
![nodebb mobile](https://user-images.githubusercontent.com/20200970/125022290-02f7d280-e085-11eb-818f-6fc4cbfe45e2.jpg)

**Comment by julianlam** [comment]
Any particular changes you'd like to propose?

**Comment by volanar** [comment]
> Any particular changes you'd like to propose?

I suggest making changes to the layout that I drew in the picture above. I specially drew the layout similar to the desktop version. Now the mobile view looks like this
![2021-07-09_13-59-27](https://user-images.githubusercontent.com/20200970/125069078-f1332100-e0be-11eb-9ce8-ceb13071f862.png)

**Comment by charizzrd** [comment]
It would be better if we could select the menus that appear at the top on mobile

**Comment by volanar** [comment]
> It would be better if we could select the menus that appear at the top on mobile. But you are still great

Do you mean like in this example? https://v4.phpfox.com/

**Comment by loid345** [comment]
Thanks @barisusakli , issue resolved. I close it.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/ca570479b504d0ed221f0d070ff39a2ceb1c012f
