### ISSUE TITLE
[Translate] Wrong translation of user blocking others

### ISSUE THREAD

**Issue by Karlatemp** [NodeBB/NodeBB#9662]
https://github.com/NodeBB/NodeBB/blob/2e6a01a7c8e886650efa37a90e9bbe0c1788fa67/public/language/zh-CN/user.json#L43-L45

In Chinese, `封禁` means `BAN` not `block`, `解封` means `UNBAN` not `unblock`.

Only administrators can `ban` or `unban` a user. When I saw this translation for the first time, I wondered why an ordinary user can ban the administrator.

Suggestion:

```
 "block_toggle": "屏蔽该用户", 
 "block_user": "屏蔽用户", 
 "unblock_user": "取消屏蔽用户", 
```

**Comment by julianlam** [comment]
Hi there,

Our translation efforts are actually handled on the Transifex app, so any changes can be made there 😃

https://www.transifex.com/nodebb/nodebb/
