### ISSUE TITLE
Session information lost after redirect to home from login via custom login popup

### ISSUE THREAD

**Issue by saikiruba-mj** [NodeBB/NodeBB#9672]
**Scenario:**

- I have created a custom login popup and worked login functionality via API code.
- After the login authenticate method the session info is lost after redirecting to the home page.

- **NodeBB version:**   NodeBB v1.17.0-beta.4
- **NPM version:**  6.14.8 
- **Database type:** mongo
- **Database version:** 
  ```   
                db version v4.0.25
                git version: 89306fde6167fa12ea6e30d61e05791e8e214e55
                OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
                allocator: tcmalloc
                modules: none
                build environment:
                    distmod: ubuntu1804
                    distarch: x86_64
                    target_arch: x86_64
```

Thank you!

**Comment by pitaj** [comment]
What code are you using? Have you tried upgrading NodeBB? What do you mean the session info is lost?

**Comment by julianlam** [comment]
We'll need code samples to figure out what exactly you're trying to do.

This is probably a question better suited for our community forum: https://community.nodebb.org
