### ISSUE TITLE
How to achieve linkedin SSO in nodebb?

### ISSUE THREAD

**Issue by saikiruba-mj** [NodeBB/NodeBB#9673]
While exploring I got three plugins to achieve linked in SSO in nodebb.

1. nodebb-plugin-sso-linkedin
2. nodebb-plugin-sso-linkedin-v2
3. nodebb-plugin-sso-linkedin-oauth2

 **nodebb-plugin-sso-linkedin** after plugin activation the LinkedIn configuration menu not showing under social authentication settings and tried via global search throws error like **You seem to have stumbled upon a page that does not exist. Return to the home page.**

**nodebb-plugin-sso-linkedin-v2**  after plugin activation throws error log like below

![image](https://user-images.githubusercontent.com/74354881/126739859-2dc835a1-563a-4a24-a2ef-52cdc6137452.png)

 **nodebb-plugin-sso-linkedin-oauth2** after plugin activation the LinkedIn configuration menu not showing under social authentication settings and tried via global search still no result for configuration setup.

**NodeBB version**: NodeBB v1.17.0-beta.4

**NPM version**: 6.14.8

**Database type**: mongo

**Database version**:

          db version v4.0.25
          git version: 89306fde6167fa12ea6e30d61e05791e8e214e55
          OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
          allocator: tcmalloc
          modules: none
          build environment:
              distmod: ubuntu1804
              distarch: x86_64
              target_arch: x86_64

Kindly let us know there is any solution to achieve Linkedin SSO in nodebb

Thank you!

**Comment by pitaj** [comment]
Are you rebuilding and restarting after installing and activating the plugins?

**Comment by saikiruba-mj** [comment]
@pitaj  

Yes I have restarted the nodebb service

**Comment by pitaj** [comment]
Restarting the NodeBB service doesn't rebuild. You have to rebuild assets after activating a plugin. You should be able to use the "Rebuild and Restart" button in the header of the Admin panel.

**Comment by saikiruba-mj** [comment]
@pitaj 

I have tried both admin panel "rebuild and restart"  button and the development build method

**Development method command:**
./nodebb build
./nodeb dev

**Comment by saikiruba-mj** [comment]
@pitaj 

Can you please mention the plugin name so that I can explain you the scenario in detail?

**Comment by julianlam** [comment]
`nodebb-plugin-sso-linkedin-oauth2` seems to be a suitable implementation. Once you've activated the plugin, stop NodeBB, run `./nodebb build && ./nodebb start` and the plugin settings should show up in the Plugins menu.

**Comment by saikiruba-mj** [comment]
@julianlam 

I have installed, rebuild & restart again and executed it as per your comments from the latest Nodebb repository still menu is not visible.

**Screenshot**:

![image](https://user-images.githubusercontent.com/74354881/126793735-d32d95b3-40f3-413d-b86d-1f664bdabd83.png)

![image](https://user-images.githubusercontent.com/74354881/126794242-ca78bb1c-db28-4519-a5f7-5e3487c027f6.png)

**Comment by julianlam** [comment]
@saikiruba-mj Both myself and @psychobunny have now opened PRs to update that plugin to compatibility with latest. You can install them via npm:

* `npm install psychobunny/nodebb-plugin-sso-linkedin-oauth2#patch-1`
* `npm install julianlam/nodebb-plugin-sso-linkedin-oauth2#master`
