### ISSUE TITLE
High CPU / Network usage since upgrading to 1.17.2

### ISSUE THREAD

**Issue by saesrpg** [NodeBB/NodeBB#9674]
I'm currently experiencing a higher CPU usage and network usage literary sitting at 200mbps since upgrading to 1.17.2 (At first glance, it appears like it's constantly trying to get data from imgur)

As you can see on the images below, it starts right at the same time we upgrade from 1.17.1 to 1.17.2 (Ignore the fact the graph says 16.04, it's on Ubuntu 18.04 as we haven't updated the VM name)

Anyone else experiencing this?

![image](https://user-images.githubusercontent.com/46712840/126788881-81bd3888-9b5e-4a98-8426-5b84f772d653.png)

![image](https://user-images.githubusercontent.com/46712840/126789027-783afad1-ebc9-4306-b44c-f460583d6ef2.png)

- **NodeBB version:** 1.17.2
- **NodeBB git hash:** b2652ae6972ef1a750e0764391638a6d15622dac
- **NodeJS version:** v12.16.2
- **Installed NodeBB Plugins:** 
```
* nodebb-plugin-composer-default@6.5.33 (installed, enabled)
        * nodebb-plugin-custom-pages@1.3.1 (installed, enabled)
        * nodebb-plugin-dbsearch@5.0.2 (installed, enabled)
        * nodebb-plugin-email-blacklist@1.1.0 (installed, enabled)
        * nodebb-plugin-emailer-mailgun@1.0.3 (installed, enabled)
        * nodebb-plugin-embed@3.0.19 (installed, enabled)
        * nodebb-plugin-emoji@3.5.3 (installed, enabled)
        * nodebb-plugin-featured-topics-extended@0.5.1 (installed, enabled)
        * nodebb-plugin-gdpr@1.0.12 (installed, enabled)
        * nodebb-plugin-markdown@8.14.1 (installed, enabled)
        * nodebb-plugin-mentions@2.13.11 (installed, enabled)
        * nodebb-plugin-ns-spoiler@7.0.0 (installed, enabled)
        * nodebb-plugin-poll@1.1.6 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.8.10 (installed, enabled)
        * nodebb-plugin-rainbows@1.5.0 (installed, enabled)
        * nodebb-plugin-redactor-center@0.1.2 (installed, enabled)
        * nodebb-plugin-spam-be-gone@0.7.9 (installed, enabled)
        * nodebb-plugin-write-api@5.8.10 (installed, enabled)
        * nodebb-rewards-essentials@0.1.5 (installed, enabled)
        * nodebb-theme-persona@11.0.25 (installed, disabled)
        * nodebb-theme-saes@1.0.2 (installed, enabled)
        * nodebb-widget-essentials@5.0.4 (installed, enabled)
        * nodebb-widget-game-server-query@1.1.0 (installed, enabled)
        * nodebb-widget-ns-birthdays@3.0.0 (installed, enabled)
```
- **Database type:** Mongo
- **Database version:** v3.6.23

**Comment by julianlam** [comment]
Hm... it sounds like it could be a plugin incompatibility. I know it's a hassle, but could you selectively de-activate plugins one-by-one, rebuild, restart, and observe the network and CPU usage?

Some likely culprits:
* The theme
* embed
* rainbows?
* ns-birthday
* game-server-query

I don't know what most of those plugins do, of course, so could be they don't have anything to do with imgur... but I do know in core the phrase `imgur` doesn't appear anywhere, so while not impossible, I would be hesitant to point to core as the source of these anomalous readings...

**Comment by saesrpg** [comment]
I will give it a go as soon as I return from holiday, thanks.

**Comment by saesrpg** [comment]
I found the culprit of this.

It seems like it was just a coincidence that the same time I upgraded the site, we started getting an attack on the website in which part of it was managing to bleeding through Cloudflare.

**Comment by julianlam** [comment]
:smile: Thanks for closing the loop on this. Those pesky attackers...
