### ISSUE TITLE
API sessions showing in Login Sessions page

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#9690]
Using Nodebb 1.17.1

When making a call to get login sessions (/api/user/:userslug/sessions) through the API it returns the current API session which contains unknown browser, platform, version etc (which could be fixed setting a user agent on the request).

Should this be the case that the API session for this call should be in this response? All other (than current) API requests are destroyed after they finish (and wont show in login sessions as a result) so should the meta user agent data be saved in the session for API requests at all or should the current session in an API requests for sessions be filtered out from the response? 

This issue/question is a result of using master tokens with _uid querystring which on success calls the onSuccessfulLogin function and hits the below code

https://github.com/NodeBB/NodeBB/blob/fadb71bff5e3cfcd7754783978c8ae19b9a6b26e/src/controllers/authentication.js#L388-L394

**Comment by julianlam** [comment]
@uplift Is the issue only that the current session (the one making the API call) is shown in the response?

As long as old API calls don't show up, then that is okay. It seems this would be the desired behaviour, no? When you browse to the `/me/sessions` page, you do see your browser session. The fact that it is a session that expires immediately is besides the point -- when the API route was called, that particular sessions _was still active_, it just isn't active after the call is complete.

**Comment by julianlam** [comment]
For what it's worth, when I make the call to `/api/user/<username>/sessions`, I get the following:

```
    "sessions": [                                                                                                               
        {                                                                                                                       
            "ip": "127.0.0.1",                                                                                                  
            "uuid": "f7eaec90-2846-48c8-bce4-64baf81d17ce",                                                                     
            "datetime": 1628268384365,                                                                                          
            "platform": "Curl",                                                                                                 
            "browser": "curl",                                                                                                  
            "version": "7.68.0",                                                                                                
            "current": true,                                                                                                    
            "datetimeISO": "2021-08-06T16:46:24.365Z"                                                                           
        },                                                                                                                      
        {                                                                                                                       
            "ip": "127.0.0.1",                                                                                                  
            "uuid": "88b80330-0827-46f9-bdca-beac3afd5963",                                                                     
            "datetime": 1628268069911,                                                                                          
            "platform": "Linux",                                                                                                
            "browser": "Firefox",                                                                                               
            "version": "89.0",                                                                                                  
            "current": false,                                                                                                   
            "datetimeISO": "2021-08-06T16:41:09.911Z"                                                                           
        }                                                                                                                       
    ],   
```

Which correctly identifies cURL as the platform/browser/etc. What are you using to make the call?

Gut feeling is this is by design. Let me know if you disagree.

**Comment by uplift** [comment]
> @uplift Is the issue only that the current session (the one making the API call) is shown in the response?

This is correct, the other API requests don't show.

> As long as old API calls don't show up, then that is okay. It seems this would be the desired behaviour, no? 

It depends what you expect the end user to see? I see 3 approaches to integration (might be more, you'd know better 😄)

1. If you aren't using the API and just a theme then the login sessions will show the browser information of each user browser session. (This is pre API behaviour)
2. If you are using Pure API for Nodebb then the Login Sessions page likely isn't needed at all as you wouldn't want to expose how you're serving Nodebb data. (This is Nodebb 2.0 behaviour?)
3. If you are using half API and half Sockets then the the Login Sessions will show each user browser session plus this one unknown (or whatever user agent you pass in request) which seems odd to show to the end user as they have no knowledge how the website gets the Nodebb data and shouldn't really.

Currently we are using a render hook to filter out the unknown request before API response is sent but not sure if this should be built in or not.

**Comment by pitaj** [comment]
I'm confused. Do you see this extra session if you access the page in your browser?

**Comment by uplift** [comment]
Yes with Step 2 or 3, i.e. the browser through our web app that calls the nodebb API to get the login sessions page data.

Step 1 you wont because there is no API call at all in that usage

**Comment by julianlam** [comment]
@uplift okay, I think in that scenario I understand how it looks like a bug, but it really isn't at least on our end.

I think you may need to add logic to filter out that session, before showing it in your app.
