### ISSUE TITLE
Even I checked "Remember me", after some time, the current page redirected to login page and asked me to login again.

### ISSUE THREAD

**Issue by fintechee** [NodeBB/NodeBB#9703]
Hi NodeBB Team,

Many thanks for developing this excellent forum package.
Really helpful.

But I met a weird issue that was not fed back by others(Why only me?).

- **NodeBB version:** 1.16.2
- **NodeJS version:** 14.17.2

- **Installed NodeBB Plugins:** default 

- **Database type:** mongo
- **Database version:** v4.0.26

- **Exact steps to cause this issue:**

1. Checked "Remember me" and signed in.
2. After some time(I don't know how long, maybe 30 minutes, maybe 1 hour), the current page redirected to login page and asked me to login again. I didn't log out and "Remember me" was checked. So, it obviously is a bug that the session expired no matter whether I checked "Remember me". Actually, I was always exploring the dashboard(because I'm new to this software), didn't make the page idle.

- **What you expected:**

I expected keeping me signed in if I checked "Remember me".
- **What happened instead:**

The current page redirected to login page and asked me to login again.

- **Additionally**
Today, I installed the forum package entirely according to the guide on NodeBB's official website.
The only setting that I configured individually is the "301 redirect".
I added one more server section in the Nginx conf.
```
server {
    listen 80;
    listen 443;
    server_name fintechee.org;
    return 301 https://www.fintechee.org$request_uri;
}
```

Please teach me how to solve this problem. Many thanks.

**Comment by julianlam** [comment]
@barisusakli this read like a bug related to the ACP timeout. Browsing the ACP should reset the timeout but it looks like this is no longer the case.

Feel free to re-/un-assign if needed.

**Comment by fintechee** [comment]
@julianlam
Thank you.

Additionally
Browser: Firefox
NodeBB Account: Admin
You can reproduce this issue.

Browser: Chrome
NodeBB Account: Normal User
The session issue doesn't exist. "Remember me" works.

**Comment by julianlam** [comment]
The "Remember Me" option does not relate to the ACP timeout security feature. NodeBB will always ask you to reauthenticate every hour when using the admin panel

**Comment by fintechee** [comment]
@julianlam
So, if I use dashboard as admin, "Remember me" will not be available?

**Comment by julianlam** [comment]
That is correct.

**Comment by fintechee** [comment]
Thank you.

**Comment by julianlam** [comment]
The "remember me" function governs how long the cookie lasts. You'll note that even though when accessing the ACP, you are required to log in again, you are actually still logged in when browsing the regular pages.

We do the admin relogin "challenge" as a security measure.

**Comment by fintechee** [comment]
Understood.
Many thanks for clarification!

**Comment by barisusakli** [comment]
Checked the timeout, it's reset properly if you are browsing the ACP
