### ISSUE TITLE
When I unchecked privilege panel's "view user info" and then checked this option again, the user info page still shows me "Access Denied".

### ISSUE THREAD

**Issue by fintechee** [NodeBB/NodeBB#9715]
Hi NodeBB Team,

Many thanks for developing this excellent forum package.
Really helpful.

But I met an issue that when I unchecked privilege panel's "view user info" and then checked this option again, the user info page still shows me "Access Denied You seem to have stumbled upon a page that you do not have access to.".

- **NodeBB version:** 1.16.2
- **NodeJS version:** 14.17.2

- **Installed NodeBB Plugins:** default 

- **Database type:** mongo
- **Database version:** v4.0.26

- **Exact steps to cause this issue:**

1. Opened the "privilege" panel and unchecked "view user info", save.
2. Checked "view user info" again and then save again.
3. The user info page still shows me(a normal registered user) "Access Denied You seem to have stumbled upon a page that you do not have access to.". Of course, what I planed to see is not my information.

- **What you expected:**

If I checked "view user info", I could see other guys' information as a normal user(not admin).
- **What happened instead:**

The user info page still shows me(a normal registered user) "Access Denied You seem to have stumbled upon a page that you do not have access to.".

- **Additionally**
Yesterday, I installed the forum package entirely according to the guide on NodeBB's official website.
The only setting that I configured individually is the "301 redirect".
I added one more server section in the Nginx conf.
```
server {
    listen 80;
    listen 443;
    server_name fintechee.org;
    return 301 https://www.fintechee.org$request_uri;
}
```

Please teach me how to solve this problem. Many thanks.

**Comment by pitaj** [comment]
What group are you checking / unchecking for this privilege?

**Comment by fintechee** [comment]
@pitaj
Thank you for your fast response.
The group is "registered user".

**Comment by julianlam** [comment]
This seems to be due to confusion over what "View User Info" does.

That particular privilege grants access to `/user/<userslug>/info`, among other small things. It is a moderation privilege, and should be left to Global Moderators (default).

In your case, it looks like you might've left "View Users" unchecked as well.

**Comment by fintechee** [comment]
@julianlam 
I see, thank you.
Is that possible to hide the users list(/users) for normal users(registered-user), but allow normal users to check the info when they know the specific user's username by using /users/xxxxx?
