### ISSUE TITLE
Add permission to view only own topics in category

### ISSUE THREAD

**Issue by saesrpg** [NodeBB/NodeBB#9723]
We used to have a permission back when we used IPB to allow users to post topics in a category, but only be able to see the topics they have created themselves.

This used to allow for people to open a dialogue with admins that would prefer to keep private (such as appealing a ban or reporting other people) and also allowed for better interaction, better visibility to staff and better archive keeping than using a group private message.

**Comment by julianlam** [comment]
You'll want nodebb-plugin-support-forum 🙂
