### ISSUE TITLE
Docker image releases schedule

### ISSUE THREAD

**Issue by bukajsytlos** [NodeBB/NodeBB#9783]
Is it possible to publish docker images right after release of new version?
Thanks

**Comment by barisusakli** [comment]
I thought this was the case 🤔

**Comment by bukajsytlos** [comment]
latest I see on docker hub is from month ago and latest numbered tag is 1.17.2

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/132564002-9191b5e3-e3ea-4fd1-9519-1d66fbbd8a37.png)

This is why. It looks like Docker has now made this a premium plan option.

**Comment by julianlam** [comment]
See #9720

**Comment by julianlam** [comment]
For now I am manually pushing v1.18.2 to Docker Hub. I have no idea whether it will work because I am a newbie to Docker.

**Comment by bukajsytlos** [comment]
thanks

**Comment by bukajsytlos** [comment]
@julianlam I think 1.18.2 image is broken. There are few symlinks to nonexisting plugin folders in node-modules. I guess reason for that was copy of local dev environment. hopefully it can be replaced on docker hub

**Comment by ralyodio** [comment]
where do i get docker version of nodebb?
