### ISSUE TITLE
Does /post/pid routes need authenticateRequest middleware?

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#9794]
When going via /api/post/:pid, some posts return 401 for an request that have correct _uid and headers set. It seems that req.uid that is passed to the privilege checks is 0 instead of _uid value and seems to only break on categories that aren't accessible with guest access from our current testing.

Does it require authenticateRequest middleware to be included in the middleware chain?

https://github.com/NodeBB/NodeBB/blob/52eace4b38ca22f0883fed0f2e43bd63d4de9440/src/routes/index.js#L62-L66

**Comment by julianlam** [comment]
Yes, that'd be the place to use that middleware. Feel free to open a PR or I can get to it Friday 🙂
