### ISSUE TITLE
18.2 upgrade and no email accounts work anymore.

### ISSUE THREAD

**Issue by Sampo2910** [NodeBB/NodeBB#9796]
Have tried with Community but with no joy. My emails no longer work and pressing send on the contact page does nothing. 

I have tried multiple email accounts and options with SMTP etc but i get nothing. The error log shows nothing but in events log i see a test email sent but the event shows the email as target@example.org

**Comment by pitaj** [comment]
You do get an error message client side when you try the test function in the ACP, yes?

**Comment by Sampo2910** [comment]
No. I deleted the contact page plugin to make sure that had nothing to do with it. If I now try to send a test message i get this: 139737218475904:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl

**Comment by Sampo2910** [comment]
Are we to use an app specific password ( i believe so) in the SMTP Transport section or Use our actual account password. It is not clear.

**Comment by pitaj** [comment]
For iCloud I think you need to put the app specific password in there.

**Comment by Sampo2910** [comment]
Ok, well I am using the app specific password and using 'Custom' NOT iCloud option in drop down. Hoping that you can get something from the error message.

**Comment by julianlam** [comment]
@Sampo2910 What version did you upgrade _from_? I find it odd because we haven't touched the emailer code in ages...

**Comment by pitaj** [comment]
Did you ever try with a different email provider?

The other option is a nodemailer upgrade - try `npm install nodemailer@6.5.0`

**Comment by Sampo2910** [comment]
18.1 to 18.2 I can only say that after that it was not working? I have no idea why and I have not touched anything. I have run npm install nodemailer@6.5.0 but this also makes no difference. I just don't see what the problem is. I have tried several different email providers now.

**Comment by Sampo2910** [comment]
This is in the event log:

{
    "confirm_code": "4aba8fc1-14e5-4775-91c8-af51b83ab87d",
    "email": "test@example.org",
    "force": 1,
    "subject": "Welcome to CoD4X Servers Hosted @fmjcod4.com",
    "template": "welcome",
    "timestamp": 1631290361135
}

So it is like it is going or ??

**Comment by barisusakli** [comment]
@Sampo2910 can you remove this line and try again on your environment https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/admin/email.js#L43

**Comment by pitaj** [comment]
Or just try a different template for testing the emailer.

**Comment by Sampo2910** [comment]
> @Sampo2910 can you remove this line and try again on your environment https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/admin/email.js#L43

I did that and got this in events:

{
    "confirm_code": "672e5732-86fa-4c46-9a5b-73e81f474320",
    "email": "my actual admin email address",
    "force": 1,
    "subject": "Welcome to CoD4X Servers Hosted @fmjcod4.com",
    "template": "welcome",
    "timestamp": 1631292533072
}

But still now got invalid login. Like i said i am using app specific password for alias icloud address. 

@pitaj I tried different templates. Same result.

**Comment by Sampo2910** [comment]
Some templates still give invalid login but NOTHING in the events log.

**Comment by Sampo2910** [comment]
Custom settings or the iCloud dropdown., tried specific password, main password also I get:

ERROR
Invalid login: 550 5.1.1 Mailbox does not exist
