### ISSUE TITLE
Missing Privilege in Topic get

### ISSUE THREAD

**Issue by uplift** [NodeBB/NodeBB#9812]
When getting topic data, the privileges section doesn't include topics:schedule Boolean so the schedule button is never shown. It looks like topics:schedule is only present when going through the /compose route as part of the filter:composer.build hook tying into composer-default plugin. Ajaxifying the composer on the topic page (or fetching data through API) doesn't include topics:schedule flag.

https://github.com/NodeBB/NodeBB/blob/05ddd60c5e257b3773b400ae5aec18b157ce3856/src/privileges/topics.js#L16

**Comment by barisusakli** [comment]
Let me know if this resolves the issue.

**Comment by uplift** [comment]
That works for me. Thanks for the fix.
