### ISSUE TITLE
Plugin settings for Persona theme throw an error

### ISSUE THREAD

**Issue by sadaszewski** [NodeBB/NodeBB#9814]
- **NodeBB version:** 1.18.2
- **NodeBB git hash:** 
- **NodeJS version:** 16.2.0

- **Installed NodeBB Plugins:** 

	* nodebb-plugin-composer-default@7.0.2 (installed, enabled)
	* nodebb-plugin-dbsearch@5.0.3 (installed, enabled)
	* nodebb-plugin-emoji@3.5.3 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
	* nodebb-plugin-markdown@8.14.3 (installed, enabled)
	* nodebb-plugin-mentions@2.13.11 (installed, enabled)
	* nodebb-plugin-spam-be-gone@0.7.9 (installed, disabled)
	* nodebb-rewards-essentials@0.1.5 (installed, enabled)
	* nodebb-theme-lavender@5.2.1 (installed, disabled)
	* nodebb-theme-persona@11.2.5 (installed, enabled)
	* nodebb-theme-slick@1.4.12 (installed, disabled)
	* nodebb-theme-vanilla@12.1.3 (installed, disabled)
	* nodebb-widget-essentials@5.0.4 (installed, enabled)
- **Database type:** postgres
- **Database version:** 13.2

- **Exact steps to cause this issue:**
Going to plugin settings for Persona theme throws the following error in the console and nothing is displayed:
```
Uncaught TypeError: t.template is undefined
    go ajaxify.js:84
    success ajaxify.js:410
    jQuery 6
    loadData ajaxify.js:384
    go ajaxify.js:69
    u ajaxify.js:493
    t ajaxify.js:557
    jQuery 2
```
- **What you expected:**
See the Persona theme settings.

- **What happened instead:**
Error thrown as above. In network monitor I can see that the template has been downloaded with the checkboxes etc but still it throws the error.

**Comment by barisusakli** [comment]
What do you get when you load `/api/admin/plugins/persona`

**Comment by sadaszewski** [comment]
Thank you for the fast reply. I get a website saying:

```
Theme Settings
[ ] Hide subcategories on categories view
[ ] Hide last post on categories view
[ ] Enable quick reply
[Save]
```

**Comment by barisusakli** [comment]
Can you try installing persona 11.2.6 and try again

**Comment by sadaszewski** [comment]
Now it works perfectly, thanks!

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/d6d4639626e25f69d3246dd9eaf7766ae95dac21
