### ISSUE TITLE
ACP option to require email address on new registration not working

### ISSUE THREAD

**Issue by ylothar** [NodeBB/NodeBB#9834]
- **NodeBB version:** v1.18.3
- **NodeBB git hash:** 9e52236973276dc4be837eb39e42193c547ba9f1
- **NodeJS version:** v14.17.6

- **Installed NodeBB Plugins:**
  * nodebb-plugin-2factor@2.9.7 (installed, enabled)
  * nodebb-plugin-composer-default@7.0.7 (installed, enabled)
  * nodebb-plugin-customize@2.0.2 (installed, enabled)
  * nodebb-plugin-dbsearch@5.0.3 (installed, enabled)
  * nodebb-plugin-emoji@3.5.3 (installed, enabled)
  * nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
  * nodebb-plugin-emoji-fontawesome@2.0.5 (installed, enabled)
  * nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
  * nodebb-plugin-markdown@8.14.3 (installed, enabled)
  * nodebb-plugin-mentions@2.13.11 (installed, enabled)
  * nodebb-plugin-question-and-answer@0.12.5 (installed, enabled)
  * nodebb-plugin-reputation-rules@1.2.3 (installed, enabled)
  * nodebb-plugin-spam-be-gone@0.7.9 (installed, enabled)
  * nodebb-plugin-tenor-gif@1.2.8 (installed, enabled)
  * nodebb-rewards-essentials@0.1.5 (installed, enabled)
  * nodebb-theme-lavender@5.2.1 (installed, disabled)
  * nodebb-theme-persona@11.2.8 (installed, enabled)
  * nodebb-theme-slick@1.4.13 (installed, disabled)
  * nodebb-theme-vanilla@12.1.3 (installed, disabled)
  * nodebb-widget-essentials@5.0.4 (installed, enabled)

- **Database type:** mongo, redis
- **Database version:** mongo v4.0.27, redis v=4.0.9

- **Exact steps to cause this issue:**
  1. Settings » Email » Flag "Require new users to specify an email address" ON
  2. Try to register a new user without indicating email address
- **What you expected:**
  * to not be able to complete registration
- **What happened instead:**
  * user the user is registered without email

**Comment by julianlam** [comment]
Thanks for reporting!
