### ISSUE TITLE
Nodebb socket.io-mongo-adapter stops broadcasting events

### ISSUE THREAD

**Issue by gsRatti1** [NodeBB/NodeBB#9836]
- **NodeBB version: @nodebb.socket.io-adapter-mongo: 3.1.1, @nodebb/mubsub: 1.7.1** 
- **NodeJS version: 12**
- **Database type:** mongo
- **Database version: 4.4.0** 

- **Exact steps to cause this issue:**

	1. We are using nodebb's mongo socket adapter to broadcast messages across different node js processes 
	`import * as SocketMongoAdaptor from '@nodebb/socket.io-adapter-mongo';
socketServer.adapter(SocketMongoAdaptor('mongodb-conn-string'));`
	2.  This works fine. But randomly all of a sudden the broadcasting stops; I mean the clients stop receiving messages.
	3. In events where it stops working, I checked some mongo logs and do see some topology change and heartbeat failure events; however , in most cases like these, we get a unhandled 'Interrupted at shutdown' exception on the mubsub channel which causes the node process to exit, and after restart things start working fine again
	4. However, in some cases, there are no errors on the channel (I explicitly added a channel error handler, since the adapter does not have this), and still the communication stops.
	5. Later I realized that although the @nodebb/mubsub library claims that the channel recreate flag is true by default; but it looks like it is undefined; so I added a patch to set it to true by default; and I am using this patched library now. Check this https://github.com/NodeBB/mubsub/pull/2
	6. Even after adding the recreate flag, things don't seem to change; randomly things stop working. I think the issue happens when one process is trying to broadcast events to clients connected to other processes; for the same process it works fine, as it must be using the in memory adapter?
	7. This is how I am handling the channel error in server\node_modules\@nodebb\socket.io-adapter-mongo\index.js
	`var channel = client.channel(key);

	channel.on('ready', function () {
		console.log('Mubsub: channel ready');
	});
	
	channel.on('error', function (err) {
		// If this is a broken cursor error, it should be fixed by channel recreate
		// which is true by default
		if (err.message === 'Mubsub: broken cursor.') {
			console.log('Mubsub: broken cursor. Continuing.');
		} else {
			console.log('Mubsub: channel error');
			console.error(err);
			throw err;
		}
	});`
	
	So, wierdly, when things stop working , I see no channel error, no errors on the mubsub client, and maybe because of this the channel recreate also does not happen. But things get broken not sure how; I can understand that maybe the mongo topology events can cause the connection to drop, or maybe the connection times out etc, but atleast I should get an error on the mubsub channel right ? So I don't see any disconnection errors, and everything stops working!
	`

- **What you expected:**
   1. Any connection issues, should emit channel error, or mubsub client error
   2. The recreat flag should take care of connection reinitialization
- **What happened instead:**
  1. Emits stop working with no channel errors

**Comment by pitaj** [comment]
Oh I guess you opened an issue here instead of https://github.com/NodeBB/socket.io-adapter-mongo because issues are disabled there.

I don't think anyone at NodeBB is interested in maintaining this anymore but it has definitely worked for us in the past without recreate and retryinterval:

https://github.com/NodeBB/NodeBB/blob/e8ca993aac4b90cfea131050814a19e144a27094/src/database/mongo.js#L184

**Comment by gsRatti1** [comment]
Thanks for the response @pitaj 

I wonder how the channel recreates itself in case of connection drop if you say that it has worked for you w/o the recreate option :-(
For us, there is something definitely off that leaves the connection/channel in a broken state, although there are no errors on the channel.
What mongo provider have you used it with ? Was it atlas ?
I am wondering if the topology failure events could be causing this.

Is there any recommended way to used the adapter library ? How can I ensure that the channel is always reestablished ? or how can I know if things are broken ?

I see that you have simply set the adapter on the socket server, to an instance of the node bb adapter; we were doing this initially, but as told, things stop working all of a sudden. We have introduced varios pathces to handle channel errors, to set the recreate flag to true etc; but the issue still exists.

Also, is there a recommended minimum socket.io version that  hould be used
@nodebb.socket.io-adapter-mongo: 3.1.1
We are on socket.io 2.0.5. Could that be causing issues ?

(Although I doubt that as the issue is intermittent; it works for sometime and then the emits dont work suddenly)


Would appreciate any help here. Thanks!

**Comment by gsRatti1** [comment]
Also, I see you are passing connection options with the connection string
`return mongoAdapter(connection.getConnectionString(), connection.getConnectionOptions());`

Could you please share what the connection options you are setting ? Want to know if there is something specific to reconnection/retries

**Comment by barisusakli** [comment]
We stopped using mubsub and socket.io-adapter-mongo. I think they stopped working after socket.io dependency got upgraded to 4.x.

If you are using multiple nodebbs to scale, redis is a requirement for pubsub.

**Comment by pitaj** [comment]
> Could you please share what the connection options you are setting ?

Look through our code

https://github.com/NodeBB/NodeBB/blob/e8ca993aac4b90cfea131050814a19e144a27094/src/database/mongo/connection.js#L44

> What mongo provider have you used it with ? Was it atlas ?

Mongo installed locally on the same server as the forum.

> We are on socket.io 2.0.5. Could that be causing issues ?

Sure could be. Make sure the newer mongo drivers sorry your version of mongodb as well.

> Is there any recommended way to used the adapter library ? How can I ensure that the channel is always reestablished ? Or how can I know if things are broken ?

We're not experts on mubsub or the adapter. We merely maintained them temporarily for our own purposes.

> I see that you have simply set the adapter on the socket server, to an instance of the node bb adapter; we were doing this initially, but as told, things stop working all of a sudden. We have introduced various patches to handle channel errors, to set the recreate flag to true etc; but the issue still exists.

I think you're on your own here. I really can't justify spending time on this as I don't think I'll be much help without digging into everything.

Good luck
