### ISSUE TITLE
There is a message shows the topic is deleted

### ISSUE THREAD

**Issue by KashingLiu** [NodeBB/NodeBB#9837]
- **NodeBB version:** 1.18.0
- **Exact steps to cause this issue:**
1. First I create a post and then delete it, but I don't purge it
2. I find there is a message tells me there is a topic or a post has been deleted
![image](https://user-images.githubusercontent.com/22939122/134626675-921489de-f136-4ade-bee2-918b6a2a3644.png)

- **What you expected:**

As a normal user, if a post has been deleted, I don't want to see them on my page, they are unnecessary to me.
If I set the css style, to let the deleted item have 'display: none', the count is not correct.
So I think is there a way to delete the post totally and once I click the delete button, the post will be deleted and an admin don't need to purge each deleted posts?
I think I should modify the `src/posts/delete.js` 

Thank you!

**Comment by psychobunny** [comment]
Hi @KashingLiu the topic that is deleted is not visible to non-admins/global moderators/moderators of that category. It is visible to you for UX reasons to allow you to undelete the topic if necessary. The "purge" function does exactly what you expected delete to do, 

Let us know if I'm misunderstanding here and you need something different from what is currently available. Thanks,
