### ISSUE TITLE
csrf_token not available if routes are created directly

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#9853]
When routes are created like below `config.csrf_token` is undefined which results in `Forbidden` errors on actions.

```
app.get('/unsolved', middleware.buildHeader, renderUnsolved);
app.get('/api/unsolved', renderUnsolved);
```

**Comment by julianlam** [comment]
Unless I'm mistaken you need the applyCsrf middleware on get routes to populate the token

**Comment by barisusakli** [comment]
Fixed it for qna plugin here https://github.com/NodeBB/nodebb-plugin-question-and-answer/commit/b15c8452e5dfc6d14c2c0aeaeea4354bb05c3c71

But I feel like this should be handled in core since pretty much all get routes will require a csrf_token to be generated since we are a SPA. https://github.com/expressjs/csurf#single-page-application-spa

**Comment by barisusakli** [comment]
I think this is better left alone, middleware.applyCSRF needs to be called before middleware.buildHeader.

This is all handled by using helpers.setupPageRoute(plus other middlewares) so that should be used instead of creating the routes manually.
