### ISSUE TITLE
Notifications popup not working

### ISSUE THREAD

**Issue by sadaszewski** [NodeBB/NodeBB#9859]
- **NodeBB version:** 0.18.2
- **NodeBB git hash:** 
- **NodeJS version:** 16.2.0

- **Installed NodeBB Plugins:** 
	* nodebb-plugin-composer-default@7.0.2 (installed, enabled)
	* nodebb-plugin-dbsearch@5.0.3 (installed, enabled)
	* nodebb-plugin-emoji@3.5.3 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
	* nodebb-plugin-markdown@8.14.3 (installed, enabled)
	* nodebb-plugin-mentions@2.13.11 (installed, enabled)
	* nodebb-plugin-spam-be-gone@0.7.9 (installed, disabled)
	* nodebb-rewards-essentials@0.1.5 (installed, enabled)
	* nodebb-theme-lavender@5.2.1 (installed, disabled)
	* nodebb-theme-persona@11.2.5 (installed, enabled)
	* nodebb-theme-slick@1.4.12 (installed, disabled)
	* nodebb-theme-vanilla@12.1.3 (installed, disabled)
	* nodebb-widget-essentials@5.0.4 (installed, enabled)

- **Database type:** postgres
- **Database version:** 13.2

- **Exact steps to cause this issue:**

1. Log in.
2. Click on the Notifications icon.

- **What you expected:**
See the notifications popup.

- **What happened instead:**
The circular arrows icon keeps spinning and the notifications never show. Instead I get the following message in the Console (below). This happens also on `community.nodebb.org` for me.

```
Uncaught Error: Script error for "notifications"
https://requirejs.org/docs/errors.html#scripterror
    makeError require.js:168
    onScriptError require.js:1738
    load require.js:1943
    load require.js:1685
    load require.js:834
    fetch require.js:824
    check require.js:856
    enable require.js:1176
    enable require.js:1557
    enable require.js:1161
    bind require.js:134
    each require.js:59
    enable require.js:1113
    init require.js:788
    o require.js:1460
    setTimeout handler*req.nextTick< require.js:1815
    o require.js:1449
    requirejs require.js:1797
    r notifications.js:40
    prepareDOM notifications.js:17
    jQuery 8
    prepareDOM notifications.js:11
    load app.js:113
    execCb require.js:1696
    check require.js:883
    enable require.js:1139
    bind require.js:134
    emit require.js:1189
    each require.js:59
    emit require.js:1188
    check require.js:938
    enable require.js:1139
    bind require.js:134
    emit require.js:1189
    each require.js:59
    emit require.js:1188
    check require.js:938
    enable require.js:1139
    bind require.js:134
    emit require.js:1189
    each require.js:59
    emit require.js:1188
    check require.js:938
    enable require.js:1139
    bind require.js:134
require.js:168:16
```

**Comment by julianlam** [comment]
Can't repro on community.nodebb.org, could it be related to extensions installed on your machine? Can you try incognito or another browser?

**Comment by sadaszewski** [comment]
Interesting. It was indeed the uBlock filter. Apparently it has a rule matching /modules/notifications in the Fanboy's list. Thanks and sorry for the false alarm, my bad.
