### ISSUE TITLE
Email error: write epipe

### ISSUE THREAD

**Issue by lslzl3000** [NodeBB/NodeBB#9903]
Tried with nodebb 1.16 & 1.18, node v14, everything else works fine. But the email fails.

with default smtp setting, neither choose qq/126/163/… or use custom smtp server，it shows error 'write epipe'

Any ideas?

**Comment by pitaj** [comment]
> 1.6 and 1.8

Do you mean 1.16 and 1.18?

Did you enable the SMTP transport?

**Comment by lslzl3000** [comment]
sorry, my fault, it's 1.16 & 1.18
enable smtp tranaport? I can't find any options in nodebb

**Comment by lslzl3000** [comment]
I  have to use plugins to enable mail service.
still can't use default smtp mailer

**Comment by lslzl3000** [comment]
ok~ so why not just simply use 'enable smtp', 'Use an external server to send emails' makes difficult to understand what does that mean~ It's more like a option to use external services, such as mailgun or sendgrid, not to enable smtp.

Anyway, I will close this issue, thanks for your help
