### ISSUE TITLE
how to enable Register with email

### ISSUE THREAD

**Issue by lslzl3000** [NodeBB/NodeBB#9905]
nodebb v1.18.x
The new register process require no email input, how to enable the old process?
Enable 'require new users to specify an email address' option makes no change, can we have an option to enable the old process way?

**Comment by julianlam** [comment]
Hi @lslzl3000 -- the "require new users to specify an email address" option enforces the email input in the next screen after the registration page. Email is no longer required as part of the initial registration form.

The admin option there restores the old functionality.

If the option is toggled on and you are able to bypass the email entry, then that may be a bug. Let me know. However that functionality was tested quite recently, so I doubt it is broken at this time.
