### ISSUE TITLE
./nodebb setup partially wipes config.json

### ISSUE THREAD

**Issue by Brutus5000** [NodeBB/NodeBB#9957]
- **NodeBB version:** 1.18.5 and afaik all previous versions
- **NodeBB git hash:** 400153f5f585d3a6c0215c3ddc63d885df93da4c
- **NodeJS version:** v16.13.0

- **Installed NodeBB Plugins:** 

- **Database type:** mongo
- **Database version:** 4.2.13

- **Exact steps to cause this issue:**

I'm preparing my nodebb installation by setting up oauth settings for my sso-oauth-plugin. It looks like:

```
{
  "url": "http://localhost:4567",
  "secret": "banana",
  "database": "mongo",
  "port": 4567,
  "mongo": {
    "host": "mongodb",
    "port": "27017",
    "username": "nodebb",
    "password": "banana",
    "database": "nodebb"
  },
  "oauth": {
    "authorizationURL": "http://faf-ory-hydra:4444/oauth2/auth",
    "tokenURL": "http://faf-ory-hydra:4444/oauth2/token",
    "fafApiProfileURL": "http://faf-java-api:8010/me",
    "id": "faf-forum",
    "secret": "{tokenFromScripts-create-hydra-test-clients.sh}",
    "scope": "public_profile"
  }
}
```

Then I run `./nodebb build`

- **What you expected:**
The installer does not touch the config.json

- **What happened instead:**

After running ./nodebb build the config.json looks different:

```
{
    "url": "http://localhost:4567",
    "secret": "banana",
    "database": "mongo",
    "port": "4567",
    "mongo": {
        "host": "mongodb",
        "port": "27017",
        "username": "nodebb",
        "password": "banana",
        "database": "nodebb",
        "uri": ""
    }
}
```

e.g. look at the new `uri` field. That is not a copy&paste error. The installer adds it. Seems like it's rewriting the whole json object and drops all unknown fields.

**Comment by barisusakli** [comment]
I don't think ./nodebb build overwrites config.json, ./nodebb setup does though.

**Comment by Brutus5000** [comment]
You are right, I got the wrong one as my installiert script calls both. Fixed description.

**Comment by pitaj** [comment]
Why are you running setup? Do you not have an existing database?

**Comment by Brutus5000** [comment]
On production yes. On new test instances or as on every developers local machine no.
Our projects docker-compose environment is open source and every developer should be able to replicate a working environment based on template configuration.
