### ISSUE TITLE
dependabot config doesn't seem to know about install/package.json

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#9977]
![image](https://user-images.githubusercontent.com/2583394/140523420-5743ac24-9ee5-4fbd-abf7-7112300c6d24.png)

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/4ddc26fc089cd6718114de15fa7005a05a5290c9

Actually it does, and it was primarily done because of that yellow box :smile: 

I... don't know quite why that box is still there, but dependabot *is* opening PRs against `install/package.json` now.

**Comment by julianlam** [comment]
I can't see that error anymore, what page is it on?

**Comment by julianlam** [comment]
Opened a ticket with GitHub support to see.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/security/dependabot/package.json/validator/open/update-logs/166495036 shows its trying to load  
```
proxy | 2021/11/05 14:46:33 [006] 404 https://api.github.com:443/repos/NodeBB/NodeBB/contents/package.json?ref=9e1d8da643ac39f6d82228b1b78fdfb207108d6b
updater | ERROR <job_229798434> Error during file fetching; aborting
```
