### ISSUE TITLE
Is NodeBB v2 alive?

### ISSUE THREAD

**Issue by andreadragotta** [NodeBB/NodeBB#9980]
What is the state of NodeBB V2 project?

Is defined a release date?

**Comment by julianlam** [comment]
Hi @andreadragotta!

Yes, NodeBB v2 is still in the planning stages, so there is no release date that we can share at this time.

A lot of the changes would break basically every plugin and theme, so we want to tread carefully here...

**Comment by vhendin** [comment]
@julianlam, will you continue to support v1?

**Comment by julianlam** [comment]
@vhendin while the future outlook of v1 (wrt new functionality, etc.) is uncertain, I know with complete certainty that v1 will be supported with security patches for a long while after v2 is released, simply because we have existing clients who will not be upgrading immediately.

**Comment by vhendin** [comment]
@julianlam Thanks for the swift response.

**Comment by andreadragotta** [comment]
News about the state of V2? I ask because i have to evaluate if make a big update in v1 or wait for v2 release

Thank You!

**Comment by julianlam** [comment]
@andreadragotta do the big update 🙂

**Comment by barisusakli** [comment]
https://nodebb.org/blog/roadmap-for-2022/
