### ISSUE TITLE
Digest posts' images not showing and wrong miniatures

### ISSUE THREAD

**Issue by ylothar** [NodeBB/NodeBB#9984]
- **NodeBB version:** v1.18.5
- **NodeBB git hash:** 0f29433bafc901a6cf5f0711ed492d6f593c8817
- **NodeJS version:** v14.18.1
- **Installed NodeBB Plugins:** 
Active plugins:
	* nodebb-plugin-2factor@2.9.7 (installed, enabled)
	* nodebb-plugin-composer-default@7.0.11 (installed, enabled)
	* nodebb-plugin-custom-pages@1.3.1 (installed, enabled)
	* nodebb-plugin-customize@2.0.2 (installed, enabled)
	* nodebb-plugin-dbsearch@5.0.5 (installed, enabled)
	* nodebb-plugin-emoji@3.5.3 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
	* nodebb-plugin-emoji-fontawesome@2.0.5 (installed, enabled)
	* nodebb-plugin-extended-markdown@1.5.0 (installed, enabled)
	* nodebb-plugin-google-analytics@0.6.0 (installed, enabled)
	* nodebb-plugin-markdown@8.14.4 (installed, enabled)
	* nodebb-plugin-mentions@2.14.1 (installed, enabled)
	* nodebb-plugin-question-and-answer@0.12.10 (installed, enabled)
	* nodebb-plugin-reputation-rules@1.2.3 (installed, enabled)
	* nodebb-plugin-soundpack-default@2.0.0 (installed, enabled)
	* nodebb-plugin-spam-be-gone@0.7.10 (installed, enabled)
	* nodebb-plugin-tenor-gif@1.2.8 (installed, enabled)
	* nodebb-plugin-youtube-embed@0.6.9 (installed, enabled)
	* nodebb-rewards-essentials@0.2.0 (installed, enabled)
	* nodebb-theme-lavender@5.2.1 (installed, disabled)
	* nodebb-theme-persona@11.2.19 (installed, enabled)
	* nodebb-theme-slick@1.4.14 (installed, disabled)
	* nodebb-theme-vanilla@12.1.7 (installed, disabled)
	* nodebb-widget-essentials@5.0.4 (installed, enabled)
- **Database type:** mongo, redis
- **Database version:** MongoDB v4.0.27 - Redis server v=4.0.9
- **Exact steps to cause this issue:**
	1. Receive Digest - or force it through ACP
- **What you expected:**
To riceive email with inline images and miniature images in posts with that.
- **What happened instead:**
Images are not present - in their place there is only the name of the original image - and posts with miniature present the user's avatar instead.
I've already verified that "Remove images from email notifications" in ACP (Settings / Email) is not checked.

**Comment by barisusakli** [comment]
These images are stripped due to https://github.com/NodeBB/NodeBB/blob/master/src/topics/teaser.js#L74.

You can remove `img` on that line or use a plugin to do it. Then images will show up on topic teasers on the category page as well as digest emails.

**Comment by ylothar** [comment]
Thanks for the reply :)
Just to make sure you understand correctly: is this behavior then intended?

Should I change the code like this? :

`const { tags } = await plugins.hooks.fire('filter:teasers.configureStripTags', { tags: utils.stripTags.concat(['']) });`

Or is there a plugin to do it?

**Comment by barisusakli** [comment]
Yeah right now it is intended, I am not sure if we should just let img tags tru and hide them via css in the theme though.

You can change it to `const { tags } = await plugins.hooks.fire('filter:teasers.configureStripTags', { tags: utils.stripTags });` in core. If you don't want to modify core you need a plugin that uses that hook like so

```
myPlugin.filterTeasersConfigureStripTags = function (hookData) {
   if (hookData.tags.includes('img')) {  
         hookData.tags.splice(hookData.tags.indexOf('img'), 1);
   }
   return hookData;
});
```

I am not aware of any plugins that does this.

**Comment by pitaj** [comment]
Improved plugin code:

```
myPlugin.filterTeasersConfigureStripTags = function (hookData) {
   hookData.tags = hookData.tags.filter(x => x !== 'img');
   return hookData;
});
```
